<?PHP // $Id$ 
      // admin.php - created with Moodle 2.0 dev (Build: 20080501) (2008030700)


$string['cachetext'] = 'Matnli keshning amal qilish muddati (Text cache)';
$string['configallowunenroll'] = '\'Ha\', aniqlangan holda talabalarga ular istagan paytda mazkur kursdan \'yozib yuborish bilan qutulish\' ruhsat beriladi. Agarda \'Yo\'q\', holda talabalar kursdan  \'yozib yuborish bilan qutulish\' ruxsat etilmaydi.Buni faqat o\'qituvchi yoki ma\'murlar qilishi mumkin.';
$string['configautologinguests'] = 'Agar kurs uchun mehmon kirishi ruhsat etilgan bo\'lsa,keluvchilar mehmonning hisob yozuvi bilan kursga avtomatik ravishda kirishlari shartmi?';
$string['configcachetext'] = 'Bu sozlashlar katta sayt yoki matn filtirlarini ishlatuvchi saytlar uchun ish tezligini haqiqatdan oshirishi mumkin. Matn nushalari shakillar ko\'rib chiqish jarayonida bu erda belgilangan vaqt ichida saqlanadi. Kam vaqt miqdori belgilanishi albatta ishning sekinlanishiga olib kilishi mumkin belgilanganishi ham yangilash, biroq ko\'p vaqt miqdori belgilanishi ham yangilanish bilan bog\'liq qiyinchiliklarni kelib chiqarishi mumkin (misol uchun, yangi ssilkalar bilan). Fahmlab tanlan';
$string['configcountry'] = 'Agar siz foydalanuvchi ushbu joyda davlatni tanlashini istasangiz, bu erni bo\'sh qoldiri';
$string['configdebug'] = 'Bu opsiyani kiritsangiz, xato va PHP ogohlantirishlari to\'g\'risidagi ma\'lumotlar ekranga tez-tez chiqarilib turadi. <br />(Ishlab chiqish bosqichida qo\'llaniladi)';
$string['configdeleteunconfirmed'] = 'Agar siz autentifikatsiyadan elekton pochta orqali foydalanayotgan bo\'lsangiz, bu erda foydalanuvchidan olimgan javob tizilda ro\'hatga olinish uchun sarflanadigan vaqt ko\'rsatiladi. Bu vaqtdan so\'ng barcha ro\'yhatga olinmagan hisob yozuvlari avtomatik ravishda o\'chiriladi.';
$string['configdigestmailtime'] = 'Daydjest shaklida pochta jo\'natuvini tanlagan foydalanuvchilar uni har kuni oladilar. Mazkur opsiya jo\'natish amalga oshiriladigan kun vaqtini boshqaradi (Bu vaqtdan keyin birinchi amalga oshirilgan kron pochtani jo\'natiladi).';
$string['configenablerssfeeds'] = 'Ushbu obsiya saytda PCC formatidagi o\'zgarishlarni kuzatadi. Har qanday o\'zgarishni ko\'rish uchun siz shuningdek RSSga individual modullarda imkoniyat berishingiz kerak (Ma\'mur rejimida – modullar sozlash).';
$string['configenablerssfeedsdisabled'] = 'RSS formati butun saytda barcha modullarda yo\'qilmaganligi tufali bu mumkin emas. Undan foydalanish uchun Ma\'mur rejimida o\'zgaruvchilar sozlashlarini o\'zgartirish kerak.';
$string['configerrorlevel'] = 'Ekranga chiqariladigan xato va PHP ogohlantirishlari to\'g\'risidagi ma\'lumotlar miqdori';
$string['configextendedusernamechars'] = 'Bu sozlash talabalarga ism (Username) kiritishda har qanaqa simvol va belgilarni ishlatish imkoniyatini beradi – bu talabaning haqiqiy ismni o\'zgartirmaydi. Izohsiz bu sozlash – noto\'g\'ridir (false), ya\'ni o\'chirilmagan va shuning uchun talabalar o\'z ismlarida faqat harf va sonlarni ishlatishlari mumkin.';
$string['configfilteruploadedfiles'] = 'Agar bu ko\'rsatma tanlangan bo\'lsa, html va matnli fayllar ishlatish jarayonida ekranga chiqarishdan oldin ularning dastlab filtratsiyasi amalga oshiriladi.';
$string['configforcelogin'] = 'Odatda, saytning birinchi sahifasi va kurslar ro\'yhatiga qirish dastlabke qayd etilishsiz amalga oshiriladi. Agar siz hamma foydalanuvchilar barcha sizning sayt ma\'lumotlaringizga faqat qayd etilganlaridan so\'ng kirishlarini istasangiz, ushbu sozlashni tanlay.';
$string['configforceloginforprofiles'] = 'Bu sozlash boshqa foydalanuvchilar to\'g\'risidagi(mehmonlarni emas) shaxsi ma\'lumot olish uchun barcha foydalanuvchilarni majburiy qayd etish imkoniyatini yaratadi. Izohsiz holda bu sozlash o\'chirilgan (false), natijada nazarda tutilayotgan talabalar (endigina tizimda qayd etilgan) har qanaqa kurs o\'qituvchisi haqidagi ma\'lumotbilan tanishishlari mumkin, biroq bu shuningdek ushbu ma\'lumotni Internetdagi qidiruv mashinalari tomonidan ishlatilish imkoniyatini beradi.';
$string['configframename'] = 'Agar siz tizimni web-frame ga moslagan bo\'lsangiz freymning nomini shu erda yozing. Aks holda joyda \'_top\' aks ettirilishi kerak';
$string['configfullnamedisplay'] = 'Bu sozlash u haqidagi to\'liq ma\'lumot chiqayotganda foydalanuvchi to\'g\'risidagi ma\'lumotlar qanday ko\'rsatilishini aniqlab beradi. Izohsiz yakka tili saytlar uchun (ismi+sharfi) sozlash turadi, biroq siz sharifingizni har doim berkitib qo\'yishingiz yoki bu joyni bo\'sh qoldirishingiz mumkin (ayrim tillarda bu to\'g\'risida turli kelishuvlar mavjud).';
$string['configgdversion'] = 'Sozlangan GDning versiyasi. Izohsiz, avtomatik ravishda aniqlanadi.';
$string['confightmleditor'] = 'Tanlang, foydalanuvchiga moslashtirilgan HTML redaktorini (redaktor 5.5 versiya va undan yuqori IE brauzerlarida ishlaydi) ishlatish ruhsat berilishini yoki yo\'qligini.';
$string['configidnumber'] = 'Bu opsiya qo\'yidagilarni aniqlaydi, (a) Foydalanuvchidan ID haqida so\'ramaslik, (b) Foydalanuvchidan ID kiritilishi so\'raladi, lekin foydalanuvchi uni kiritmasligi ham mumkin, (c) Foydalanuvchidan ID kiritilishi so\'raladi va foydalanuvchi uni kiritishi shart. ID – raqam ko\'rsatilgan holda u foydalanuvchining profaylida e\'tirof etiladi.';
$string['configintro'] = 'Serverdagi tizimni sozlash uchun konfiguratsion o\'zgaruvchilarni tanlang. Siz bu sahifaga keyinroq qaytib uni o\'zgartirishingiz mumkin';
$string['configintroadmin'] = 'Bu sahifada siz saytni to\'liq nazorat qiluvchi asosiy ma\'murning akkauntini to\'ldirishingiz kerak. Havfsiz parol, login va haqiqiy e-mail ko\'rsatganingizga ishonch xosil qiling. Keyingchalik siz ma\'murlarni qo\'shimcha qilishingiz mumkin.';
$string['configintrosite'] = 'Bu sahifada siz birinchi sahifa ko\'rinishini sozlashingiz va saytga nom berishingiz mumkin \'Sayt sozlashlari \' ssilkasi orqali siz bu sahifaga keyinroq qaytishingiz mumkin.';
$string['configlang'] = 'Izohsiz holda butun sayt uchun belgilangan tilni tanlang.';
$string['configlangdir'] = 'Chet tillarni aksariyati chapdan o\'ngga qarab bosiladi, biroq ayrimlarib o\'ngdan chapga qarab, misol uchun, arab tili.';
$string['configlanglist'] = 'Agar foydalanuvchi ishlatilayotgan tilni tanlash imkoniyatiga ega bo\'lishini istasangiz ushbu opsiyanib bo\'sh qoldiring. Taklif etilayotgan tillar menyusini istalayotgan tillarni vergullar bilan ajratilgan belgilarini kiritish orqali o\'zgartirish mumkin. Misol uchun, ru, en.';
$string['configlangmenu'] = 'Foydalanuvchilarga saytda ishlatilayotgan tilni tanlash menyusi ko\'rsatish kerakligini yoki kerak emasligini tanlang. Bu foydalanuvchining o\'zining profaylida qulay til tanlash imkoniyatiga ta\'sir qilmaydi.';
$string['configlocale'] = 'Saytda ishlatilishi ko\'zda tutilgan spetsificatsiyani (format v asana yosiz tiliga ta\'sir ko\'rsatadi) tanlang. Agar nima tanlashni bilmasangiz joyni bo\'sh qoldiring.';
$string['configloglifetime'] = 'Joy siz foydalanuvchilar faoliyati  haqidagi loglarni saqlashni istagan vaqtning bir qismini aniqlaydi. Muddati berilgandan oshganda avtomatik ravishda o\'chiriladi.Odatda loglar uzoq muddat saqlanadi, biroq sizning serveringizda bo\'sh joy cheklangan bo\'lsa va ishda muammolarga duch kelganingizda siz bu parametrni kamaytirishingiz lozim.';
$string['configlongtimenosee'] = 'Parametr, talabaning qaysi bir vaqt davomida saytda paydo bo\'lmasligini aniqlaydi shu bilan birga talabani avtomatik ravishda kursdan chiqarib tashlanmaydiи .';
$string['configmaxbytes'] = 'Bu parametr saytga kiritilayotgan tashqi fayllarning eng katta miqdorini aniqlaydi. Bu parametr o\'z o\'rnida qo\'yidagi sozlashlar bilan cheklangan: PHP da- setting upload_max_filesize hamdaи в Apache da – LimitRequestBody bilan. Shubhasiz, kiritilayotgan fayllarning eng katta miqdori kurs darajasida yoki modul darajasida aniqlanishi mumkin.';
$string['configmaxeditingtime'] = 'Foydalanuvchi tomonidan forumga jo\'natilgan xabarning o\'zgartirilishi mumkin bo\'lgan vaqt... Odatda 30min belgisi ishlatiladi';
$string['confignoreplyaddress'] = 'Ayrim paytda electron pochta xabarlari foydalanuvchining bevosita ishtirokisiz jo\'natiladi (masalan, forumdan xabarlar). Bu erda ko\'rsatilgan electron pochtaning manzili foydalanuvchi electron pochtasi manzilini e\'lon qilishni hohlamagan holda oluvchilar bevosita foydalanuvchiga murojaat qilishi uchun foydalanishi shart bo\'lmagan holda(agar foydalanuvchi o\'z manzilini ko\'rsatishni istamasa)';
$string['configopentogoogle'] = 'Bu sozlashga ruhsat bersangiz  Google qidiruv mashinasi(www.google.com) sizning saytingizni mexmon sifatida qayd etishga imkon beradi. Bundan tashqari, sizning saytingizga Google, orqali kiruvchi odamlar sizning saytingizda avtomatik ravishda mehmon sifatida qayd etiladi. Izoh, bu mexmon  sifatida kirish mumkin bo\'lgan kurslarga faqat sodda kirishni ta\'minlaydi.';
$string['configproxyhost'] = 'Agar <b>server</b>ga Internetga kirish uchun proxy (firewall) zarur bo\'lsa, hostning nomi va portni shu erda yosing, aks holda joyini bo\'sh qoldiring.';
$string['configsecureforms'] = 'Vebdan shakirlar orkali ma\'lumotlar olingan tizim qo\'shimcha havfsizlik darajasini qo\'llashi mumkin. Opsiya yoqilgan bo\'lgan holda HTTP_REFERER brauzeri o\'zgaruvchisi shaklning hozirgi manzili bilan solishtiriladi. Uncha ko\'p bo\'lmagan hollarda bu muammolarga olib kelishi mumkin, misol uchun, agar foydalanuvchi tarmoqli himoyalash tizimini ishlatsa(masolan, Zonealarm), u HTTP_REFERERni tarmoq trafikidan ajratish uchun yaratilgan. Simptomi – shaklga \'yopishishi\'. Agar sizning foydalanuvchilaringiz tizimga kirishda muammolarga duch kelsa, bu sozlashni o\'chirib qo\'yish maqsadga muvofiq bo\'lishi mumkin, biroq bu sizning saytingiz parolini almashtirish orqali aniqlash uchun ochiq bo\'lib qolishga olib kelishi mumkin. Agar shubhalansangiz, opsiyani yoqiq holda qoldiring.';
$string['configsessioncookie'] = 'Bu sessiyalar (sessions) bilan ishlarda qo\'llaniladigan cookie mexanizmi uchun foydalanuvchiga nom qo\'yish. Bu sozlash shart emas, biroq bitta saytda bir necha sessiyalar yuritishda original cookielarni qo\'llash foydalidir.';
$string['configsessiontimeout'] = 'Agag saytga tashrif qiluvchi ma\'lum vaqt ichida hech narsa qilmasa, u avtomatik ravishda chetlatiladi (sessiya yakunlanadi). Bu o\'zgaruvchi vaqtni belgilaydi.';
$string['configslasharguments'] = 'Fayllar (tasvirlar, olingan fayllar) slesh (ikkinchi opsiya) ishlatib script orqali tarqatiladi. Bu uslub fayllarga eng sodda yo\'l bilan serverlarda keshlanishga imkoniyat beradi. Afsuski, ayrim PHP-serverlar bu uslub bilan mos kelmaydi. Agar olingan fayl yoki rasmlarni (foydalanuvchilarning suratlari) ko\'rish borasida muammolarga duch kelsangiz birinchi opsiyani o\'rnating';
$string['configsmtphosts'] = 'SMTP-serveringizni to\'liq nomini yozing, undan tizim pochta ( mail.a.com formati) jo\'natish uchun foydalanadi. Agar siz joyni bo\'sh qoldirsangiz tizim pochta jo\'natish uchun o\'rnatilgan PHP uslubidan foydalanadi';
$string['configsmtpuser'] = 'Agar siz oldingi joyda SMTP-serverning nomini qayd etgan bo\'lsangiz va unga autentifikatsiya zarur bo\'lsa, foydalanuvchi nomini va parolini shu erda sozlang';
$string['configteacherassignteachers'] = 'Oddiy o\'qituvchilar o\'zlarining kursi bo\'yicha boshqa o\'qituvchilarni tayinlashlari mumkinmi? Agar \'Yo\'q\', bo\'lsa kurs tashkilchilari va ma\'murlar o\'qituvchilarni tayinlashi mumkin.';
$string['configtimezone'] = 'Bu erda siz \'vaqt zonasini\' – timezone belgilashingiz mumkin. Bu tizimli sanalarni va vaqtni chiqarish uchun izohsiz vaqt zonasi bo\'ladi, shu bilan birga har bir foydalanuvchi o\'zi uchun vaqt zonasini o\'zining profaylida o\'zgartirishi mumkin. \'Server time\'- \'Server vaqti\' o\'rnatmalarni serverdagi operatsion tizim o\'rnatmalariga mos ravishda qo\'yadi.';
$string['configunzip'] = 'Unzip (faqat Юникс uchun) dasturi uchun yo\'lni ko\'rsating. Serveringizdagi zip-arxivlarni ochish uchun zarur';
$string['configvariables'] = 'O\'zgaruvchilarni sozlash';
$string['configwarning'] = 'Bu sozlashlar o\'zgarishiga e\'tiborli bo\'ling, noto\'g\'ri sozlashlar muammolar keltirib chiqishi mumkin.';
$string['configzip'] = 'Zip (faqat Юникс uchun) dasturi uchun yo\'lni ko\'rsating. Serveringizdagi zip-arhivlarni yaratish uchun zarur';
$string['filteruploadedfiles'] = 'Olinayotgan fayllarning filtratsiyasi';
$string['upgradelogs'] = 'To\'liqroq funksionallik ta\'minlash uchun sizning eski tizimli ma\'lumotingizni (logs) yangilash kerak. <a href=\'$a\'>Ma\'lumotidan ko\'proq</a>';
$string['upgradelogsinfo'] = 'Tizimli ma\'lumot (logs) va uning yozuvi bilan ayrim o\'zgarishlar bo\'lishi mumkin. Barcha eski  logslarni  per-activity basis asosida ko\'rish uchun sizning eski logslaringiz muntazam yangilanib turishi lozim. Bu sizning saytingizga bog\'liq va ko\'p vaqt olishi mumkin (bir necha soatgacha), va siz MBda eng katta fayllar uchun ruhsat etilgan chegaralardan chiqib ketishingiz mumkin. Biroq tizimli ma\'lumotlarning bu kabi yangilash jarayonini qo\'llashingiz kerak va uni to\'liq yakunigacha to\'xtatmasligingiz (brauzer oynalari yopilmasligi) kerak. Tashvish qilmang: вbunday ish davomida boshqa foydalanuvchilar uchun sayt odatdagiday ishlaydi. Tizim ma\'lumotini (logs) hozir yangilashni istaysizmi?';
$string['upgradinglogs'] = 'Tizimli ma\'lumotni (logs) yangilash';
$string['defaultsettingsuser'] = 'Bu erda id foydalanuvchini ko\'rsating. Bu foydalanuvchi uchun ko\'rsatilgan ma\'lumot ( e-mail formati, shahar va h.k), izohsiz holda barcha boshqa tuzilayotgan foydalanuvchilar uchun qo\'llaniladi'; // ORPHANED

?>
