<?PHP // $Id$ 
      // lesson.php - created with Moodle 2.0 dev (Build: 20080501) (2008030700)


$string['accesscontrol'] = 'Ruxsat nazorati';
$string['actionaftercorrectanswer'] = 'To\'g\'ri javobdan keyingi amal';
$string['activitylink'] = 'Bosqichga o\'tish';
$string['addabranchtable'] = 'CHipta-rubrikator qo\'shish';
$string['addanendofbranch'] = 'Bo\'lim ohirini qo\'shish';
$string['addaquestionpage'] = 'Savollar sahifasini qo\'shish';
$string['addcluster'] = 'Klaster qo\'shish';
$string['addedabranchtable'] = 'CHipta-rubrikator qo\'shilgan';
$string['addedanendofbranch'] = 'CHipta-rubrikator oxiri qo\'shilgan';
$string['addedaquestionpage'] = 'Savollar sahifasini qo\'shilgan';
$string['addedcluster'] = 'Klaster qo\'shilgan';
$string['addedendofcluster'] = 'Klaster ohiri qo\'shilgan';
$string['addendofcluster'] = 'Klaster ohiri qo\'shish';
$string['answer'] = 'Javob';
$string['answeredcorrectly'] = 'Javob to\'g\'ri';
$string['answersfornumerical'] = 'Son ko\'rinishidagi javoblar maksimal va minimal qiymatlardan iborat juftlik bilan taqqoslanadi';
$string['arrangebuttonshorizontally'] = 'Slayd-shouda chipta–rubrikator tugmachalari joylashuvi gorizontal bo\'lsinmi?';
$string['attempt'] = 'Urinish: $a';
$string['attempts'] = 'Urinishlar';
$string['available'] = 'dan boshlab ruxsat etilgan';
$string['averagescore'] = 'O\'rtacha ball';
$string['averagetime'] = 'O\'rtacha vaqt';
$string['branchtable'] = 'CHipta-rubrikator';
$string['cancel'] = 'Bekor qilish';
$string['canretake'] = 'Imtihonlarni qayta topshirish ruxsat etilgan';
$string['casesensitive'] = 'Uchun registr ahamiyatli';
$string['checkbranchtable'] = 'CHipta-rubrikatorni sinash';
$string['checkedthisone'] = 'To\'g\'ri javob tanlashdi.';
$string['checknavigation'] = 'Navigtsiyani sinash';
$string['checkquestion'] = 'Savol chiptasini sinash';
$string['classstats'] = 'Sinf statistikasi';
$string['clicktopost'] = 'Bahongizni yuqori natijalar ro\'yxatiga qo\'shish uchun bu erni bosing.';
$string['clusterjump'] = 'Klaster ichidagi ko\'rinmas savol';
$string['clustertitle'] = 'Klaster sarlavhasi';
$string['comments'] = 'Sizning sharhlaringiz';
$string['completed'] = 'YAkunlandi';
$string['conditionsfordependency'] = 'Bog\'liqlik uchun shartlar';
$string['confirmdeletionofthispage'] = 'Ushbu sahifa o\'chirilishini tasdiqlang';
$string['congratulations'] = 'Tabriklaymiz – dars yakunlandi';
$string['continue'] = 'Davom etish';
$string['continuetoanswer'] = 'Javoblarni o\'zgartirishni davom etish';
$string['correctanswerjump'] = 'To\'g\'ri javobda o\'tish:';
$string['correctanswerscore'] = 'To\'g\'ri javob uchun ballar';
$string['correctresponse'] = 'To\'g\'ri javobga sharh';
$string['customscoring'] = 'Har bir savol uchun ballar';
$string['deadline'] = 'Topshirishning ohirgi muddati';
$string['defaultessayresponse'] = 'Matningizni kurs muallimi baholaydi.';
$string['deletedpage'] = 'Sahifa o\'chirilgan';
$string['deleting'] = 'O\'chirish';
$string['deletingpage'] = 'Sahifani o\'chirish: $a';
$string['dependencyon'] = 'ga bog\'liq';
$string['description'] = 'Ma\'lumot';
$string['detailedstats'] = 'Batafsil statistika';
$string['didnotanswerquestion'] = 'Talaba bu savolga javob bermadi.';
$string['displayhighscores'] = 'Eng yaxshi (yuqori)natijalarni ko\'rsatish';
$string['displayinleftmenu'] = 'Sahifalar ro\'yxatida ko\'rsatilsinmi?';
$string['displayleftif'] = '$a ning reytingi quydagidan yuqori bo\'lgan holdagina:';
$string['displayleftmenu'] = 'CHapda sahifalar ro\'yxatini ko\'rsatish';
$string['displayofgrade'] = 'Baholarni ko\'rsatish (faqat talabalar uchun)';
$string['displayreview'] = '”Tuzatish” tugmachasini ko\'rsatish';
$string['displayscorewithessays'] = 'Avtomatik baholangan savollar uchun $a->tempmaxgrade dan $a->score ball oldingiz. <br> $a->essayquestions esse uchun baholar keyinroq yakuniy baho chiqarilayotganda qo\'yiladi va hisobga olinadi. <br> Sizning joriy bahongiz (esse hisobga olinmaganda): $a->grade dan $a->score.';
$string['displayscorewithoutessays'] = 'Savollarga berilgan javoblar uchun baho: $a->score, $a->grade dan';
$string['editlessonsettings'] = 'Dars sozlashlarini tahrir qilish';
$string['editpagecontent'] = 'Sahifani tahrir qilish';
$string['emailallgradedessays'] = 'Baholangan esselarni barchasini tarqatish <br />';
$string['emailgradedessays'] = 'Baholangan esselarni tarqatish';
$string['endofbranch'] = 'Bo\'lim ohiri';
$string['endofclustertitle'] = 'Klaster ohiri';
$string['endoflesson'] = 'Dars ohiri';
$string['entername'] = 'Eng yuqori natijalar ro\'yxatida ko\'rsatish uchun nik kiriting';
$string['enterpassword'] = 'Iltimos, parolni kiriting:';
$string['eolstudentoutoftime'] = 'Diqqat! Darsni o\'tish vaqti tugadi, shuning uchun ohirgi javobingiz, ajratilgan vaqt mobaynida berilmagan bo\'lsa, hisobga olinmagan bo\'lishi mumkin.';
$string['eolstudentoutoftimenoanswers'] = 'Siz birorta ham savolga javob bermadingiz. Darsga 0 oldingiz.';
$string['essay'] = 'Esse';
$string['essays'] = 'Esse';
$string['essayscore'] = 'Esse uchun ballar';
$string['fileformat'] = 'Fayl formati';
$string['firstanswershould'] = 'Birinchi javob \"to\'g\'ri\" sahifada joylashtirilishi kerak';
$string['firstwrong'] = 'Afsuski, javobingiz noto\'g\'ri bo\'lganligi sababli ball olmaysiz. O\'rganish maqsadida (ball to\'plash maqsadida emas) javob topishni davom etasizmi?';
$string['flowcontrol'] = 'Joriy nazorat';
$string['general'] = 'Umumiy';
$string['grade'] = 'Baho';
$string['gradebetterthan'] = 'Baho (&#37;) dan yuqori';
$string['gradeessay'] = 'Esseni baholash ($a->notgradedcount baholanmagan va  $a->notsentcount jo\'natilmagan)';
$string['gradeis'] = 'Baho: $a';
$string['gradeoptions'] = 'Baholash parametrlari';
$string['handlingofretakes'] = 'Imtihonlarni qayta topshirish natijalarini tahlil qilish';
$string['here'] = 'bu erda';
$string['highscore'] = 'Eng yuqori natija';
$string['importppt'] = 'PowerPoint faylini import qilish';
$string['importquestions'] = 'Savollarni import qilish';
$string['insertedpage'] = 'Sahifa joylashtirildi';
$string['jump'] = 'O\'tish';
$string['leftduringtimed'] = 'Darsni o\'tish uchun belgilangan vaqt bilan tark etdingiz. <br/> Iltimos, darsni yangitdan boshlash uchun «Davom etish» tugmachasini bosing.';
$string['leftduringtimednoretake'] = 'Darsni o\'tish uchun belgilangan vaqt bilan tark etdingiz va uni yangitdan o\'tish yoki davom etish imkoniyatiga ega emassiz.';
$string['lessonclosed'] = 'Ushbu dars yopildi $a.';
$string['lessoncloses'] = 'dars yopilmoqda';
$string['lessondefault'] = 'sukunat bo\'yicha ushbu dars belgilashlaridan foydalanish';
$string['lessonformating'] = 'Darsni formatlash';
$string['lessonmenu'] = 'Dars menyusi';
$string['lessonopen'] = 'Ushbu dars ochiladi $a';
$string['lessonopens'] = 'Dars ochilmoqda';
$string['lessonstats'] = 'Dars statistikasi';
$string['loginfail'] = 'Noto\'g\'ri login, iltimos, yana urinib ko\'ring...';
$string['lowscore'] = 'Quyi ball';
$string['matchesanswer'] = 'Javob uchun mutanosiblik';
$string['maxhighscores'] = 'Aks ettiriladigan yuqori natijalar soni';
$string['maximumnumberofanswersbranches'] = 'CHiptadagi javob/o\'tishlarning maksimal soni';
$string['maximumnumberofattempts'] = 'Urinishlarning maksimal soni';
$string['maxtime'] = 'Vaqt bo\'yicha chegaralar (daqiqalarda)';
$string['maxtimewarning'] = 'Darsni yakunlash uchun Sizning ixtiyoringizda $a daqiqa bor.';
$string['mediaclose'] = 'YOpish tugmachasini ko\'rsatish:';
$string['mediafile'] = 'Sakrab chiquvchi fayl yoki vebsahifa';
$string['mediafilepopup'] = 'Ushbu darsni (faylni)ko\'zdan kechirish uchun bu erga cherting.';
$string['mediaheight'] = 'Darcha balandligi:';
$string['mediawidth'] = 'kengligi:';
$string['minimumnumberofquestions'] = 'Savollarning minimal soni';
$string['modattempts'] = 'Talabalarga javoblarini o\'zgartirishni ruxsat etish';
$string['modattemptsnoteacher'] = 'Faqat talabalar javoblarini o\'zgartirishlari mumkin.';
$string['modulename'] = 'Dars';
$string['modulenameplural'] = 'Darslar';
$string['movedpage'] = 'Sahifa';
$string['movepagehere'] = 'Sahifani bu erga ko\'chirish';
$string['moving'] = 'Sahifani ko\'chirish: $a';
$string['multianswer'] = 'Bir nechta javob';
$string['multipleanswer'] = 'Bir necha marta berilgan javob';
$string['nameapproved'] = 'Ism (nom) qabul qilindi';
$string['namereject'] = 'Uzr etasiz, Siz tanlangan ism qabul bo\'la olmaydi. <br/> Boshqa ism kiritishga urinib ko\'ring.';
$string['nextpage'] = 'Keyingi sahifa';
$string['noanswer'] = 'Javob olinmadi';
$string['noattemptrecordsfound'] = 'Urinishlar to\'g\'risida yozuvlar topilmadi: olingan baholar yo\'q';
$string['nohighscores'] = 'YUqori natijalar yo\'q.';
$string['nooneansweredcorrectly'] = 'Ushbu savolga hech kim to\'g\'ri javob bermadi.';
$string['nooneansweredthisquestion'] = 'Ushbu savolga hech kim javob bermadi.';
$string['noonecheckedthis'] = 'Ushbu javobni hech kim tanlamadi.';
$string['nooneenteredthis'] = 'ushbu matnni hech kim kiritmadi.';
$string['noretake'] = 'Ushbu darsni qaytadan o\'ta olmaysiz.';
$string['normal'] = 'Standart – dars sahifalari ketma-ketligi bo\'yicha';
$string['notcompleted'] = 'YAkunlanmagan';
$string['notdefined'] = 'Aniqlanmagan';
$string['notitle'] = 'Sarlavhasiz';
$string['numberofcorrectanswers'] = 'To\'g\'ri javoblar soni: $a';
$string['numberofcorrectmatches'] = 'To\'g\'ri mosliklar soni: $a';
$string['numberofpagestoshow'] = 'Ko\'rsatilgan sahifalar (chiptalar) soni';
$string['numberofpagesviewed'] = 'Ko\'rib chiqilgan sahifalar soni : $a';
$string['ongoing'] = 'Joriy ballni ko\'rsatish';
$string['ongoingnormal'] = 'Siz ko\'rib chiqilgan $a->viewed savoldan $a->correct siga to\'g\'ri javob berdingiz.';
$string['or'] = 'YOKI';
$string['ordered'] = 'Buyurtma berilgan';
$string['other'] = 'Boshqa parametrlar';
$string['outof'] = '$a dan';
$string['overview'] = 'Ko\'zdan kechirish';
$string['page'] = 'Sahifa : $a';
$string['pagecontents'] = 'Sahifa mazmuni (mundarijasi)';
$string['pages'] = 'Sahifalar';
$string['pagetitle'] = 'Sahifa sarlavhasi';
$string['password'] = 'Parol';
$string['passwordprotectedlesson'] = '$a – parol bilan himoyalangan dars';
$string['pleasecheckoneanswer'] = 'Iltimos, bitta javob tanlang';
$string['pleasecheckoneormoreanswers'] = 'Iltimos, bitta yoki bir nechta javob tanlang';
$string['pleaseenteryouranswerinthebox'] = 'Iltimos, maydonchaga javobingizni kiriting';
$string['pleasematchtheabovepairs'] = 'Iltimos, moslikni o\'rnating';
$string['pointsearned'] = 'Olingan ballar';
$string['practice'] = 'Mashq tariqasidagi dars';
$string['previouspage'] = 'Oldingi sahifa';
$string['question'] = 'Savol';
$string['questionoption'] = 'Savol parametri (savol turiga bog\'liq)';
$string['questiontype'] = 'Savol turi';
$string['randombranch'] = 'Tasodifiy sahifa';
$string['redisplaypage'] = 'Sahifani qaytadan ko\'rsatish';
$string['report'] = 'Hisobot';
$string['response'] = 'Javobga sharh';
$string['returntocourse'] = 'Kursga qaytish';
$string['reviewlesson'] = 'Darsdagi javoblarni o\'zgartirish';
$string['reviewquestionback'] = 'Ha, yana bir marta urinib ko\'raman';
$string['reviewquestioncontinue'] = 'Yo\'q, keyingi savolga o\'tishni hohlayman';
$string['sanitycheckfailed'] = 'Tekshirishdagi xato: Bu urinish o\'chirib yuborilgan';
$string['savechanges'] = 'O\'zgartirishlarni saqlash';
$string['savechangesandeol'] = 'Barcha o\'zgartirishlarni saqlab dars ohiriga o\'tish';
$string['savepage'] = 'Sahifani saqlash';
$string['score'] = 'Javob uchun ballar';
$string['scores'] = 'Ballar';
$string['secondpluswrong'] = 'Mutlaqo (unchalik) to\'g\'ri emas. YAna urinib ko\'rasizmi?';
$string['showanunansweredpage'] = 'Noto\'g\'ri javob berilgan savollarni ko\'rsatish';
$string['showanunseenpage'] = 'Faqat yangi savollarni ko\'rsatish';
$string['singleanswer'] = 'YAkka javob';
$string['slideshow'] = 'Slayd-shou';
$string['slideshowbgcolor'] = 'Slayd-shou fonining rangi';
$string['slideshowheight'] = 'Slayd balandligi';
$string['slideshowwidth'] = 'Slayd kengligi';
$string['startlesson'] = 'Darsni boshlash';
$string['studentattemptlesson'] = '$a->lastname $a->firstname Urinish raqami: $a->attempt';
$string['studentname'] = '$a talaba ismi';
$string['studentoneminwarning'] = 'Diqqat! Darsni yakunlash uchun ixtiyoringizda bir yoki kamroq daqiqa qoldi.';
$string['studentresponse'] = 'Javob {$a}';
$string['submitname'] = 'Ismni jo\'natish';
$string['teacherongoingwarning'] = 'Joriy ball faqat talaba uchun aks ettiriladi. Joriy ballni sinash uchun biror talaba nomidan kiring.';
$string['teachertimerwarning'] = 'Taymer faqat talaba uchun aks ettiriladi. Taymerni sinash uchun biror talaba nomidan kiring.';
$string['thatsthecorrectanswer'] = 'Bu to\'g\'ri javob';
$string['thatsthewronganswer'] = 'Bu noto\'g\'ri javob';
$string['thefollowingpagesjumptothispage'] = 'Keyingi sahifalardan bu sahifaga o\'tish amalga oshiriladi';
$string['thispage'] = 'Joriy sahifa';
$string['timed'] = 'Vaqt bo\'yicha chegaralangan';
$string['timeremaining'] = 'Qolgan vaqt';
$string['timespentminutes'] = 'Sarflangan vaqt (daqiqalarda)';
$string['timetaken'] = 'Sarflangan vaqt';
$string['updatedpage'] = 'Sahifa yangilandi';
$string['updatefailed'] = 'YAngilanish ro\'y bermadi';
$string['useeditor'] = 'Vizual (ko\'rinadigan) muharrirdan foydalanish';
$string['usemaximum'] = 'Maksimal Baho';
$string['usemean'] = 'O\'rtacha Baho';
$string['usepassword'] = 'Dars parol bilan himoyalangan';
$string['viewgrades'] = 'Baholarni ko\'rish';
$string['viewhighscores'] = 'YUqori natijalar ro\'yxatini ko\'rish';
$string['welldone'] = 'A\'lo!';
$string['whatdofirst'] = 'Birinchi navbatda nima qilmoqchisiz?';
$string['wronganswerjump'] = 'Noto\'g\'ri javobdagi o\'tish';
$string['wronganswerscore'] = 'Noto\'g\'ri javob uchun ballar';
$string['wrongresponse'] = 'Noto\'g\'ri javobga sharh';
$string['youhaveseen'] = 'Bu dars ustida avval ishlagansiz.<br /> To\'xtagan joyingizdan davom etish hoxlaysizmi?';
$string['youranswer'] = 'Javobingiz';
$string['yourcurrentgradeis'] = 'Sizning joriy bahongiz - $a';
$string['youshouldview'] = 'Siz hech bo\'lmaganda ko\'zdan kechirib chiqishingiz kerak: $a';
$string['backtreeview'] = 'Dars tuzilmasiga qaytish'; // ORPHANED
$string['deleteattempts'] = 'talabaning bu darsni o\'tishga urinishlarini o\'chirib yuborish (talaba loginini kiriting)'; // ORPHANED
$string['essaemailsubject'] = '$a savolga javobingiz uchun baho'; // ORPHANED
$string['gobacktolesson'] = 'Darsga qaytish'; // ORPHANED
$string['havenotgradedet'] = 'Hozircha baholanmagan.'; // ORPHANED
$string['jumptsto'] = 'ga o\'tish:'; // ORPHANED
$string['lesson'] = '$a dars'; // ORPHANED
$string['mainmenu'] = 'Kursning bosh sahifasi'; // ORPHANED
$string['movingtonextpage'] = 'Keyingi sahifaga ko\'chirish'; // ORPHANED
$string['nocommentet'] = 'Hozircha sharhlar berilmagan.'; // ORPHANED
$string['outoftime'] = 'Vaqt tugadi'; // ORPHANED
$string['reached'] = 'erishilgan'; // ORPHANED
$string['returnmainmenu'] = 'Bosh menyuga qaytish'; // ORPHANED
$string['studentoutoftime'] = 'Diqqat! Darsni o\'tish vaqti tugadi. Ohirgi javobingiz darsning vaqt chegaralaridan tashqarida berilganligi sababli hisobga olinmadi. Iltimos, darsni yakunlash uchun ”Davom etish” tugmachasini bosing.'; // ORPHANED
$string['treeview'] = 'Dars tuzilmasini ko\'rsatish'; // ORPHANED
$string['updatesuccess'] = 'YAngilash muvafaqqiyatli o\'tdi'; // ORPHANED
$string['viewallpages'] = 'Barcha sahifalarni ko\'rish'; // ORPHANED
$string['viewlessonstats'] = 'Dars statistikasini ko\'rsatish ($a->users $a->usersname)'; // ORPHANED
$string['youhavereceived'] = 'Esse uchun $a->outof dan $a->score ball oldingiz.'; // ORPHANED
$string['yourgradeisnow'] = 'Sizning bahongiz tuzatildi $a'; // ORPHANED
$string['yourresponse'] = 'Javobingiz'; // ORPHANED

?>
