<?PHP // $Id$ 
      // timezones.php - created with Moodle 1.9 (2007101509)


$string['africa/abidjan'] = 'Afrika/Abidjan';
$string['africa/accra'] = 'Afrika/Akkra';
$string['africa/addis_ababa'] = 'Afrika/Addis_Ababa';
$string['africa/algiers'] = 'Afrika/Aljir';
$string['africa/asmera'] = 'Afrika/Asmera';
$string['africa/bamako'] = 'Afrika/Bamako';
$string['africa/bangui'] = 'Afrika/Bangui';
$string['africa/banjul'] = 'Afrika/Banjul';
$string['africa/bissau'] = 'Afrika/Bissau';
$string['africa/blantyre'] = 'Afrika/Blantyre';
$string['africa/brazzaville'] = 'Afrika/Brazzavill';
$string['africa/bujumbura'] = 'Afrika/Bujumbura';
$string['africa/cairo'] = 'Afrika/Kair';
$string['africa/casablanca'] = 'Afrika/Kasablanka';
$string['africa/ceuta'] = 'Afrika/Ceuta';
$string['africa/conakry'] = 'Afrika/Konakri';
$string['africa/dakar'] = 'Afrika/Dakar';
$string['africa/dar_es_salaam'] = 'Afrika/Dar_es_Salaam';
$string['africa/djibouti'] = 'Afrika/Djibouti';
$string['africa/douala'] = 'Afrika/Douala';
$string['africa/el_aaiun'] = 'Afrika/El_Aaiun';
$string['africa/freetown'] = 'Afrika/Freetown';
$string['africa/gaborone'] = 'Afrika/Gaborone';
$string['africa/harare'] = 'Afrika/Harare';
$string['africa/johannesburg'] = 'Afrika/Yohannesburg';
$string['africa/kampala'] = 'Afrika/Kampala';
$string['africa/khartoum'] = 'Afrika/Khartoum';
$string['africa/kigali'] = 'Afrika/Kigali';
$string['africa/kinshasa'] = 'Afrika/Kinshasa';
$string['africa/lagos'] = 'Afrika/Lagos';
$string['africa/libreville'] = 'Afrika/Librevill';
$string['africa/lome'] = 'Afrika/Loma';
$string['africa/luanda'] = 'Afrika/Luanda';
$string['africa/lubumbashi'] = 'Afrika/Lubumbashi';
$string['africa/lusaka'] = 'Afrika/Lusaka';
$string['africa/malabo'] = 'Afrika/Malabo';
$string['africa/maputo'] = 'Afrika/Maputo';
$string['africa/maseru'] = 'Afrika/Maseru';
$string['africa/mbabane'] = 'Afrika/Mbabane';
$string['africa/mogadishu'] = 'Afrika/Mogadishu';
$string['africa/monrovia'] = 'Afrika/Monrovia';
$string['africa/nairobi'] = 'Afrika/Nairobi';
$string['africa/ndjamena'] = 'Afrika/Ndjamena';
$string['africa/niamey'] = 'Afrika/Niamey';
$string['africa/nouakchott'] = 'Afrika/Nouakchott';
$string['africa/ouagadougou'] = 'Afrika/Ouagadougou';
$string['africa/porto-novo'] = 'Afrika/Porto-Novo';
$string['africa/sao_tome'] = 'Afrika/Sao_Tome';
$string['africa/timbuktu'] = 'Afrika/Timbuktu';
$string['africa/tripoli'] = 'Afrika/Tripoli';
$string['africa/tunis'] = 'Afrika/Tunis';
$string['africa/windhoek'] = 'Afrika/Windhoek';
$string['america/adak'] = 'Amerika/Adak';
$string['america/anchorage'] = 'Amerika/Anchorage';
$string['america/anguilla'] = 'Amerika/Anguilla';
$string['america/antigua'] = 'Amerika/Antigua';
$string['america/araguaina'] = 'Amerika/Araguaina';
$string['america/argentina/buenos_aires'] = 'Amerika/Buenos-Ayres';
$string['america/argentina/catamarca'] = 'Amerika/Argentina/Katamarka';
$string['america/argentina/comodrivadavia'] = 'Amerika/Argentina/KomodRivadavia';
$string['america/argentina/cordoba'] = 'Amerika/Argentina/Kordoba';
$string['america/argentina/jujuy'] = 'Amerika/Argentina/Jujuy';
$string['america/argentina/la_rioja'] = 'Amerika/Argentina/La_Rioja';
$string['america/argentina/mendoza'] = 'Amerika/Argentina/Mendoza';
$string['america/argentina/rio_gallegos'] = 'Amerika/Argentina/Rio_Gallegos';
$string['america/argentina/san_juan'] = 'Amerika/Argentina/San_Juan';
$string['america/argentina/tucuman'] = 'Amerika/Argentina/Tukuman';
$string['america/argentina/ushuaia'] = 'Amerika/Argentina/Ushuaia';
$string['america/aruba'] = 'Amerika/Aruba';
$string['america/asuncion'] = 'Amerika/Asunson';
$string['america/bahia'] = 'Amerika/Bahia';
$string['america/barbados'] = 'Amerika/Barbados';
$string['america/belem'] = 'Amerika/Belem';
$string['america/belize'] = 'Amerika/Beliz';
$string['america/boa_vista'] = 'Amerika/Boa_Vista';
$string['america/bogota'] = 'Amerika/Bogota';
$string['america/boise'] = 'Amerika/Boyse';
$string['america/cambridge_bay'] = 'Amerika/Kembridge_Ko\'rfazi';
$string['america/campo_grande'] = 'Amerika/Kampo_Grande';
$string['america/cancun'] = 'Amerika/Kankun';
$string['america/caracas'] = 'Amerika/Karakas';
$string['america/cayenne'] = 'Amerika/Kayenna';
$string['america/cayman'] = 'Amerika/Kayman';
$string['america/chicago'] = 'Amerika/Chikago';
$string['america/chihuahua'] = 'Amerika/Chihuahua';
$string['america/costa_rica'] = 'Amerika/Kosta-Rika';
$string['america/cuiaba'] = 'Amerika/Kuiaba';
$string['america/curacao'] = 'Amerika/Kurakao';
$string['america/danmarkshavn'] = 'Amerika/Danmarkshavn';
$string['america/dawson'] = 'Amerika/Dawson';
$string['america/dawson_creek'] = 'Amerika/Dawson_Tor ko\'rfazi';
$string['america/denver'] = 'Amerika/Denver';
$string['america/detroit'] = 'Amerika/Detroit';
$string['america/dominica'] = 'Amerika/Dominika';
$string['america/edmonton'] = 'Amerika/Edmonton';
$string['america/eirunepe'] = 'Amerika/Eirunepe';
$string['america/el_salvador'] = 'Amerika/El_Salvador';
$string['america/fortaleza'] = 'Amerika/Fortaleza';
$string['america/glace_bay'] = 'Amerika/Gleys_Ko\'rfazi';
$string['america/godthab'] = 'Amerika/Godthab';
$string['america/goose_bay'] = 'Amerika/G\'oz_Ko\'rfazi';
$string['america/grand_turk'] = 'Amerika/Grand_Turk';
$string['america/grenada'] = 'Amerika/Grenada';
$string['america/guadeloupe'] = 'Amerika/Gvadalupe';
$string['america/guatemala'] = 'Amerika/Gvatemala';
$string['america/guayaquil'] = 'Amerika/Guayakuil';
$string['america/guyana'] = 'Amerika/Gviana';
$string['america/halifax'] = 'Amerika/Halifaks';
$string['america/havana'] = 'Amerika/Havana';
$string['america/hermosillo'] = 'Amerika/Hermosillo';
$string['america/indiana/knox'] = 'Amerika/Indiana/Knoks';
$string['america/indiana/marengo'] = 'Amerika/Indiana/Marengo';
$string['america/indiana/vevay'] = 'Amerika/Indiana/Vevay';
$string['america/indianapolis'] = 'Amerika/Indianapolis';
$string['america/inuvik'] = 'Amerika/Inuvik';
$string['america/iqaluit'] = 'Amerika/Iqaluit';
$string['america/jamaica'] = 'Amerika/Yamayka';
$string['america/juneau'] = 'Amerika/Juneau';
$string['america/kentucky/monticello'] = 'Amerika/Kentucky/Monticello';
$string['america/la_paz'] = 'Amerika/La-Pas';
$string['america/lima'] = 'Amerika/Lima';
$string['america/los_angeles'] = 'Amerika/Los-Anjels';
$string['america/louisville'] = 'Amerika/Louisvill';
$string['america/maceio'] = 'Amerika/Maceio';
$string['america/managua'] = 'Amerika/Mangua';
$string['america/manaus'] = 'Amerika/Manaus';
$string['america/martinique'] = 'Amerika/Martinika';
$string['america/mazatlan'] = 'Amerika/Mazatlan';
$string['america/menominee'] = 'Amerika/Menominee';
$string['america/merida'] = 'Amerika/Merida';
$string['america/mexico_city'] = 'Amerika/Mexico_Shahri';
$string['america/miquelon'] = 'Amerika/Miquelon';
$string['america/monterrey'] = 'Amerika/Monterrey';
$string['america/montevideo'] = 'Amerika/Montevideo';
$string['america/montreal'] = 'Amerika/Montreal';
$string['america/montserrat'] = 'Amerika/Montserrat';
$string['america/nassau'] = 'Amerika/Nassau';
$string['america/new_york'] = 'Amerika/Nyu-York';
$string['america/nipigon'] = 'Amerika/Nipigon';
$string['america/nome'] = 'Amerika/Nom shahri';
$string['america/noronha'] = 'Amerika/Noronha';
$string['america/north_dakota/center'] = 'Amerika/North_Dakota/Center';
$string['america/panama'] = 'Amerika/Panama';
$string['america/pangnirtung'] = 'Amerika/Pangnirtung';
$string['america/paramaribo'] = 'Amerika/Paramalibo';
$string['america/phoenix'] = 'Amerika/Phoeniks';
$string['america/port-au-prince'] = 'Amerika/Port-o-Prins';
$string['america/port_of_spain'] = 'Amerika/Port_of_Spain';
$string['america/porto_velho'] = 'Amerika/Porto_Velho';
$string['america/puerto_rico'] = 'Amerika/Puerto_Rico';
$string['america/rainy_river'] = 'Amerika/Rainy_River';
$string['america/rankin_inlet'] = 'Amerika/Rankin_Inlet';
$string['america/recife'] = 'Amerika/Recife';
$string['america/regina'] = 'Amerika/Regina';
$string['america/rio_branco'] = 'Amerika/Rio_Branco';
$string['america/santiago'] = 'Amerika/Santiago';
$string['america/santo_domingo'] = 'Amerika/Santo_Domingo';
$string['america/sao_paulo'] = 'Amerika/Sao_Paulo';
$string['america/scoresbysund'] = 'Amerika/Scoresbysund';
$string['america/st_johns'] = 'Amerika/Avliyo_Johns';
$string['america/st_kitts'] = 'Amerika/Avliyo_Kitts';
$string['america/st_lucia'] = 'Amerika/Avliyo_Lucia';
$string['america/st_thomas'] = 'Amerika/Avliyo_Thomas';
$string['america/st_vincent'] = 'Amerika/Avliyo_Vincent';
$string['america/swift_current'] = 'Amerika/Swift_Current';
$string['america/tegucigalpa'] = 'Amerika/Tegucigalpa';
$string['america/thule'] = 'Amerika/Thule';
$string['america/thunder_bay'] = 'Amerika/Thunder_Bay';
$string['america/tijuana'] = 'Amerika/Tijuana';
$string['america/toronto'] = 'America/Toronto';
$string['america/tortola'] = 'America/Tortola';
$string['america/vancouver'] = 'Amerika/Vankuver';
$string['america/whitehorse'] = 'Amerika/Whitehorse';
$string['america/winnipeg'] = 'Amerika/Winnipeg';
$string['america/yakutat'] = 'Amerika/Yakutat';
$string['america/yellowknife'] = 'Amerika/Yellowknife';
$string['antarctica/casey'] = 'Antarktika/Casey';
$string['antarctica/davis'] = 'Antarktika/Davis';
$string['antarctica/dumontdurville'] = 'Antarktika/DumontDUrville';
$string['antarctica/mawson'] = 'Antarktika/Mawson';
$string['antarctica/mcmurdo'] = 'Antarktika/McMurdo';
$string['antarctica/palmer'] = 'Antarktika/Palmer';
$string['antarctica/rothera'] = 'Antarktika/Rothera';
$string['antarctica/syowa'] = 'Antarktika/Syowa';
$string['antarctica/vostok'] = 'Antarktika/Vostok';
$string['asia/aden'] = 'Osiyi/Aden';
$string['asia/almaty'] = 'Osiyo/Almati';
$string['asia/amman'] = 'Osiyo/Ommon';
$string['asia/anadyr'] = 'Osiyo/Anadir';
$string['asia/aqtau'] = 'Osiyo/Aqtau';
$string['asia/aqtobe'] = 'Osiyo/Aqtobe';
$string['asia/ashgabat'] = 'Osiyo/Ashxobod';
$string['asia/baghdad'] = 'Osiyo/Bog\'dod';
$string['asia/bahrain'] = 'Osiyo/Baxrain';
$string['asia/baku'] = 'Osiyo/Baku';
$string['asia/bangkok'] = 'Osiyo/Bankok';
$string['asia/beirut'] = 'Osiyo/Bayrut';
$string['asia/bishkek'] = 'Osiyo/Bishkek';
$string['asia/brunei'] = 'Osiyo/Bruney';
$string['asia/calcutta'] = 'Osiyo/Kalkutta';
$string['asia/choibalsan'] = 'Osiyo/Choibalsan';
$string['asia/chongqing'] = 'Osiyo/Chongqing';
$string['asia/colombo'] = 'Osiyo/Kalombo';
$string['asia/damascus'] = 'Osiyo/Damashq';
$string['asia/dhaka'] = 'Osiyo/Daka';
$string['asia/dili'] = 'Osiyo/Dili';
$string['asia/dubai'] = 'Osiyo/Dubay';
$string['asia/dushanbe'] = 'Osiyo/Dushanbe';
$string['asia/gaza'] = 'Osiyo/G\'azo';
$string['asia/harbin'] = 'Osiyo/Harbin';
$string['asia/hong_kong'] = 'Osiyo/Gong-Kong';
$string['asia/hovd'] = 'Osiyo/Hovd';
$string['asia/irkutsk'] = 'Osiyo/Irkutsk';
$string['asia/jayapura'] = 'Osiyo/Jayapura';
$string['asia/jerusalem'] = 'Osiyo/Jerusalem';
$string['asia/kabul'] = 'Osiyo/Qobul';
$string['asia/kamchatka'] = 'Osiyo/Kamchatka';
$string['asia/karachi'] = 'Osiyo/Karachi';
$string['asia/kashgar'] = 'Osiyo/Kashgar';
$string['asia/katmandu'] = 'Osiyo/Katmandu';
$string['asia/krasnoyarsk'] = 'Osiyo/Krasnoyarsk';
$string['asia/kuala_lumpur'] = 'Osiyo/Kuala-Lumpur';
$string['asia/kuching'] = 'Osiyo/Kuching';
$string['asia/kuwait'] = 'Osiyo/Quvayt';
$string['asia/macau'] = 'Osiyo/Macau';
$string['asia/magadan'] = 'Osiyo/Magadan';
$string['asia/makassar'] = 'Osiyo/Makassar';
$string['asia/manila'] = 'Osiyo/Manila';
$string['asia/muscat'] = 'Osiyo/Maskat';
$string['asia/nicosia'] = 'Osiyo/Nicosia';
$string['asia/novosibirsk'] = 'Osiyo/Novosibirsk';
$string['asia/omsk'] = 'Osiyo/Omsk';
$string['asia/oral'] = 'Osiyo/Oral';
$string['asia/phnom_penh'] = 'Osiyo/Pnompen';
$string['asia/pontianak'] = 'Osiyo/Pontianak';
$string['asia/pyongyang'] = 'Osiyo/Pyongyang';
$string['asia/qatar'] = 'Osiyo/Qatar';
$string['asia/qyzylorda'] = 'Osiyo/Qyzylorda';
$string['asia/rangoon'] = 'Osiyo/Rangoon';
$string['asia/riyadh'] = 'Osiyo/Riyadh';
$string['asia/saigon'] = 'Osiyo/Saigon';
$string['asia/sakhalin'] = 'Osiyo/Sakhalin';
$string['asia/samarkand'] = 'Osiyo/Samarqand';
$string['asia/seoul'] = 'Osiyo/Seul';
$string['asia/shanghai'] = 'Osiyo/Shanhay';
$string['asia/singapore'] = 'Osiyo/Singapur';
$string['asia/taipei'] = 'Osiyo/Taypey';
$string['asia/tashkent'] = 'Osiyo/Toshkent';
$string['asia/tbilisi'] = 'Osiyo/Tbilisi';
$string['asia/tehran'] = 'Osiyo/Tehron';
$string['asia/thimphu'] = 'Osiyo/Thimphu';
$string['asia/tokyo'] = 'Osiyo/Tokio';
$string['asia/ulaanbaatar'] = 'Osiyo/Ulanbator';
$string['asia/urumqi'] = 'Osiyo/Urumqi';
$string['asia/vientiane'] = 'Osiyo/Ventyan';
$string['asia/vladivostok'] = 'Osiyo/Vladivostok';
$string['asia/yakutsk'] = 'Osiyo/Yakutsk';
$string['asia/yekaterinburg'] = 'Osiyo/Yekaterinburg';
$string['asia/yerevan'] = 'Osiyo/Yerevan';
$string['atlantic/azores'] = 'Atlantika/Azores';
$string['atlantic/bermuda'] = 'Atlantika/Bermuda';
$string['atlantic/canary'] = 'Atlantika/Kanary';
$string['atlantic/cape_verde'] = 'Atlantika/Cape_Verde';
$string['atlantic/faeroe'] = 'Atlantika/Faeroe';
$string['atlantic/madeira'] = 'Atlantika/Madeira';
$string['atlantic/reykjavik'] = 'Atlantika/Reykyavik';
$string['atlantic/south_georgia'] = 'Atlantika/South_Georgia';
$string['atlantic/st_helena'] = 'Atlantika/St_Helena';
$string['atlantic/stanley'] = 'Atlantika/Stanley';
$string['australia/adelaide'] = 'Australia/Adelaide';
$string['australia/brisbane'] = 'Australia/Brisbane';
$string['australia/broken_hill'] = 'Australia/Broken_Hill';
$string['australia/darwin'] = 'Australia/Darwin';
$string['australia/hobart'] = 'Australia/Hobart';
$string['australia/lindeman'] = 'Australia/Lindeman';
$string['australia/lord_howe'] = 'Australia/Lord_Howe';
$string['australia/melbourne'] = 'Avstraliya/Melburn';
$string['australia/perth'] = 'Australia/Perth';
$string['australia/sydney'] = 'Avstraliya/Sidney';
$string['europe/amsterdam'] = 'Yevropa/Amsterdam';
$string['europe/andorra'] = 'Yevropa/Andorra';
$string['europe/athens'] = 'Yevropa/Athens';
$string['europe/belfast'] = 'Yevropa/Belfast';
$string['europe/belgrade'] = 'Yevropa/Belgrad';
$string['europe/berlin'] = 'Yevropa/Berlin';
$string['europe/brussels'] = 'Yevropa/Brussel';
$string['europe/bucharest'] = 'Yevropa/Buxarest';
$string['europe/budapest'] = 'Yevropa/Budapesht';
$string['europe/chisinau'] = 'Yevropa/Chisinau';
$string['europe/copenhagen'] = 'Yevropa/Kopengagen';
$string['europe/dublin'] = 'Yevropa/Dublin';
$string['europe/gibraltar'] = 'Yevropa/Gibraltar';
$string['europe/helsinki'] = 'Yevropa/ Xelsinki';
$string['europe/istanbul'] = 'Yevropa/Istanbul';
$string['europe/kaliningrad'] = 'Yevropa/Kalilingrad';
$string['europe/kiev'] = 'Yevropa/Kiyev';
$string['europe/lisbon'] = 'Yevropa/Lissabon';
$string['europe/london'] = 'Yevropa/London';
$string['europe/luxembourg'] = 'Yevropa/Lyuksemburg';
$string['europe/madrid'] = 'Yevropa/Madrid';
$string['europe/malta'] = 'Yevropa/Malta';
$string['europe/minsk'] = 'Yevropa/Minsk';
$string['europe/monaco'] = 'Yevropa/Monako';
$string['europe/moscow'] = 'Yevropa/Moskva';
$string['europe/oslo'] = 'Yevropa/Oslo';
$string['europe/paris'] = 'Yevropa/Parij';
$string['europe/prague'] = 'Yevropa/Praga';
$string['europe/riga'] = 'Yevropa/Riga';
$string['europe/rome'] = 'Yevropa/Rim';
$string['europe/samara'] = 'Yevropa/Samara';
$string['europe/simferopol'] = 'Yevropa/Simferopol';
$string['europe/sofia'] = 'Yevropa/Sofiya';
$string['europe/stockholm'] = 'Yevropa/Stokgolm';
$string['europe/tallinn'] = 'Yevropa/Tallin';
$string['europe/tirane'] = 'Yevropa/Tirana';
$string['europe/uzhgorod'] = 'Yevropa/Uzhgorod';
$string['europe/vaduz'] = 'Yevropa/Vaduz';
$string['europe/vienna'] = 'Yevropa/Vienna';
$string['europe/vilnius'] = 'Yevropa/Vilnus';
$string['europe/warsaw'] = 'Yevropa/Varshava';
$string['europe/zaporozhye'] = 'Yevropa/Zaporozhye';
$string['europe/zurich'] = 'Yevropa/Zurich';
$string['indian/antananarivo'] = 'Hind/Antananarivu';
$string['indian/chagos'] = 'Indian/Chagos';
$string['indian/christmas'] = 'Indian/Christmas';
$string['indian/comoro'] = 'Indian/Comoro';
$string['indian/kerguelen'] = 'Indian/Kerguelen';
$string['indian/mahe'] = 'Indian/Mahe';
$string['indian/maldives'] = 'Indian/Maldives';
$string['indian/mauritius'] = 'Indian/Mauritius';
$string['indian/mayotte'] = 'Indian/Mayotte';
$string['indian/reunion'] = 'Indian/Reunion';
$string['pacific/apia'] = 'Tinch okean/Apia';
$string['pacific/auckland'] = 'Tinch okean/Auckland';
$string['pacific/chatham'] = 'Tinch okean/Chatham';
$string['pacific/easter'] = 'Tinch okean/Easter';
$string['pacific/efate'] = 'Tinch okean/Efate';
$string['pacific/enderbury'] = 'Tinch okean/Enderbury';
$string['pacific/fakaofo'] = 'Tinch okean/Fakaofo';
$string['pacific/fiji'] = 'Tinch okean/Fiji';
$string['pacific/funafuti'] = 'Tinch okean/Funafuti';
$string['pacific/galapagos'] = 'Tinch okean/Galapagos';
$string['pacific/gambier'] = 'Tinch okean/Gambier';
$string['pacific/guadalcanal'] = 'Tinch okean/Guadalcanal';
$string['pacific/guam'] = 'Tinch okean/Guam';
$string['pacific/honolulu'] = 'Tinch okean/Honolulu';
$string['pacific/kiritimati'] = 'Tinch okean/Kiritimati';
$string['pacific/kosrae'] = 'Tinch okean/Kosrae';
$string['pacific/kwajalein'] = 'Tinch okean/Kwajalein';
$string['pacific/majuro'] = 'Tinch okean/Majuro';
$string['pacific/marquesas'] = 'Tinch okean/Marquesas';
$string['pacific/midway'] = 'Tinch okean/Midway';
$string['pacific/nauru'] = 'Tinch okean/Nauru';
$string['pacific/niue'] = 'Tinch okean/Niue';
$string['pacific/norfolk'] = 'Tinch okean/Norfolk';
$string['pacific/noumea'] = 'Tinch okean/Noumea';
$string['pacific/pago_pago'] = 'Tinch okean/Pago-Pago';
$string['pacific/palau'] = 'Tinch okean/Palau';
$string['pacific/pitcairn'] = 'Tinch okean/Pitcairn';
$string['pacific/ponape'] = 'Tinch okean/Ponape';
$string['pacific/port_moresby'] = 'Tinch okean/Port_Moresby';
$string['pacific/rarotonga'] = 'Tinch okean/Rarotonga';
$string['pacific/saipan'] = 'Tinch okean/Saipan';
$string['pacific/tahiti'] = 'Tinch okean/Tahiti';
$string['pacific/tarawa'] = 'Tinch okean/Tarawa';
$string['pacific/tongatapu'] = 'Tinch okean/Tongatapu';
$string['pacific/truk'] = 'Tinch okean/Truk';
$string['pacific/wake'] = 'Tinch okean/Wake';
$string['pacific/wallis'] = 'Tinch okean/Wallis';
$string['pacific/yap'] = 'Tinch okean/Yap';
$string['Amerika/whitehorse'] = 'Amerika/Whitehorse'; // ORPHANED
$string['Amerika/winnipeg'] = 'Amerika/Winnipeg'; // ORPHANED
$string['Amerika/yakutat'] = 'Amerika/Yakutat'; // ORPHANED
$string['Amerika/yellowknife'] = 'America/Yellowknife'; // ORPHANED
$string['Afrika/abidjan'] = 'Afrika/Abidjan'; // ORPHANED
$string['Afrika/accra'] = 'Afrika/Akkra'; // ORPHANED
$string['Afrika/addis_ababa'] = 'Afrika/Addis-Abeba'; // ORPHANED
$string['Afrika/bamako'] = 'Afrika/Bamako'; // ORPHANED
$string['Afrika/banjul'] = 'Afrika/Banjul'; // ORPHANED
$string['Afrika/bissau'] = 'Afrika/Bissau'; // ORPHANED
$string['Afrika/brazzaville'] = 'Afrika/Brazzavil'; // ORPHANED
$string['Afrika/bujumbura'] = 'Afrika/Bujumbura'; // ORPHANED
$string['Afrika/casablanca'] = 'Afrika/Kasablanka'; // ORPHANED
$string['Afrika/conakry'] = 'Afrika/Konakri'; // ORPHANED
$string['Afrika/dakar'] = 'Afrika/Dakar'; // ORPHANED
$string['Afrika/djibouti'] = 'Afrika/Djibuti'; // ORPHANED
$string['Afrika/freetown'] = 'Afrika/Fritaun'; // ORPHANED
$string['Afrika/gaborone'] = 'Afrika/Gabon'; // ORPHANED
$string['Afrika/harare'] = 'Afrika/Harari'; // ORPHANED
$string['Afrika/kampala'] = 'Afrika/Kampala'; // ORPHANED
$string['Afrika/khartoum'] = 'Afrika/Xartum'; // ORPHANED
$string['Afrika/kigali'] = 'Afrika/Kigali'; // ORPHANED
$string['Afrika/kinshasa'] = 'Afrika/Kinshasa'; // ORPHANED
$string['Afrika/libreville'] = 'Afrika/Libravil'; // ORPHANED
$string['Afrika/lome'] = 'Afrika/Lome'; // ORPHANED
$string['Afrika/luanda'] = 'Afrika/Luanda'; // ORPHANED
$string['Afrika/lusaka'] = 'Afrika/Lusaka'; // ORPHANED
$string['Afrika/malabo'] = 'Afrika/Malabo'; // ORPHANED
$string['Afrika/maputo'] = 'Afrika/Maputu'; // ORPHANED
$string['Afrika/maseru'] = 'Afrika/Maseru'; // ORPHANED
$string['Afrika/mbabane'] = 'Afrika/Mbabane'; // ORPHANED
$string['Afrika/mogadishu'] = 'Afrika/Mogadishu'; // ORPHANED
$string['Afrika/monrovia'] = 'Afrika/Monroviya'; // ORPHANED
$string['Afrika/nairobi'] = 'Afrika/Nayrobi'; // ORPHANED
$string['Afrika/ndjamena'] = 'Afrika/Ndjamena'; // ORPHANED
$string['Afrika/niamey'] = 'Afrika/Niamey'; // ORPHANED
$string['Afrika/nouakchott'] = 'Afrika/Nuakshot'; // ORPHANED
$string['Afrika/ouagadougou'] = 'Afrika/Uagadaugu'; // ORPHANED
$string['Afrika/porto-novo'] = 'Afrika/Porto-Novo'; // ORPHANED
$string['Afrika/tripoli'] = 'Afrika/Tripoli'; // ORPHANED
$string['Afrika/tunis'] = 'Afrika/Tunis'; // ORPHANED
$string['Afrika/windhoek'] = 'Afrika/Vindhuk'; // ORPHANED

?>
