<?PHP // $Id$ 
      // blog.php - created with Moodle 2.0 dev (Build: 20080504) (2008050200)


$string['addnewentry'] = '新しいエントリの追加';
$string['backupblogshelp'] = '有効にした場合、サイト自動バックアップにブログが含まれます。';
$string['blockmenutitle'] = 'ブログメニュー';
$string['blocktagstitle'] = 'ブログタグ';
$string['blocktitle'] = 'ブログタグのブロックタイトル';
$string['blog'] = 'ブログ';
$string['blogdeleteconfirm'] = 'このブログを削除してもよろしいですか?';
$string['blogdisable'] = 'ブログは無効にされています!';
$string['blogpreferences'] = 'ブログ設定';
$string['blogs'] = 'ブログ';
$string['blogtags'] = 'ブログタグ';
$string['cannotviewcourseblog'] = 'あなたには、このコースのブログを閲覧するパーミッションがありません。';
$string['cannotviewcourseorgroupblog'] = 'あなたには、このコース/グループのブログを閲覧するパーミッションがありません。';
$string['cannotviewsiteblog'] = 'あなたには、すべてのサイトブログを閲覧するパーミッションがありません。';
$string['cannotviewuserblog'] = 'あなたには、ユーザブログを閲覧するパーミッションがありません。';
$string['courseblog'] = 'コースブログ: $a';
$string['courseblogdisable'] = 'コースブログは有効にされていません。';
$string['courseblogs'] = 'ユーザはコースを共有しているユーザのブログのみ読むことができる';
$string['deleteotagswarn'] = '本当にこれらのタグをすべてのブログ投稿およびシステムから削除してもよろしいですか?';
$string['deleteposterror'] = '投稿の削除中にエラーが発生しました。';
$string['disableblogs'] = 'ブログシステムを完全に無効にする';
$string['emptybody'] = 'ブログエントリ本文を入力してください。';
$string['emptytitle'] = 'ブログエントリタイトルを入力してください。';
$string['entrybody'] = 'ブログエントリ本文';
$string['entrybodyonlydesc'] = 'エントリ説明';
$string['entryerrornotyours'] = 'これはあなたのエントリではありません。';
$string['entrysaved'] = 'あなたのエントリが保存されました。';
$string['entrytitle'] = 'エントリタイトル';
$string['entryupdated'] = 'ブログエントリが更新されました。';
$string['groupblog'] = 'グループブログ: $a';
$string['groupblogdisable'] = 'グループブログは有効にされていません。';
$string['groupblogs'] = 'ユーザはグループを共有しているユーザのブログのみ読むことができる';
$string['incorrectblogfilter'] = '正しくないブログフィルタタイプが指定されました。';
$string['intro'] = 'このRSSフィードは、1つまたはそれ以上のブログから自動生成されました。';
$string['noentriesyet'] = '表示できるエントリはありません。';
$string['noguestpost'] = 'ゲストはブログを投稿できません!';
$string['norighttodeletetag'] = 'あなたはこのタグ ($a) を削除できません。';
$string['notallowedtoedit'] = 'あなたはこのエントリを編集できません。';
$string['numberofentries'] = 'エントリ: $a';
$string['numberoftags'] = '表示するタグ数';
$string['pagesize'] = '1ページあたりのブログエントリ数';
$string['permalink'] = 'パーマリンク';
$string['personalblogs'] = 'ユーザは自分のブログのみ読むことができる';
$string['publishto'] = '公開先:';
$string['publishtonoone'] = 'あなたのみ閲覧可 (下書き)';
$string['publishtosite'] = 'このサイトの誰でも閲覧可';
$string['publishtoworld'] = '世界中の誰でも閲覧可';
$string['settingsupdatederror'] = 'エラーが発生したため、ブログ設定は更新されませんでした。';
$string['siteblog'] = 'サイトブログ: $a';
$string['siteblogdisable'] = 'サイトブログは有効にされていません。';
$string['siteblogs'] = 'すべてのサイトユーザはすべてのブログを読むことができる';
$string['tagdatelastused'] = '最後に使用された日付タグ';
$string['tags'] = 'タグ';
$string['tagsort'] = 'タグの並び替え方法';
$string['tagtext'] = 'タグテキスト';
$string['timewithin'] = '指定した期間に使用されたタグを表示する';
$string['updateentrywithid'] = 'エントリの更新';
$string['userblog'] = 'ユーザブログ: $a';
$string['viewcourseentries'] = 'コースエントリを表示する';
$string['viewmyentries'] = 'マイエントリを表示する';
$string['viewsiteentries'] = 'サイトエントリを表示する';
$string['worldblogs'] = '世界中の誰でもエントリを読むことができる';
$string['wrongpostid'] = 'ブログ投稿IDが正しくありません。';
$string['addotags'] = 'オフィシャルタグの追加'; // TBD
$string['addptags'] = 'ユーザ定義タグの追加'; // TBD
$string['otags'] = 'オフィシャルタグ'; // TBD
$string['ptags'] = 'ユーザ定義タグ (カンマ区切り)'; // TBD

?>
