<?PHP // $Id$ 
      // chat.php - created with Moodle 2.0 dev (Build: 20091210) (2009112400)


$string['autoscroll'] = 'オートスクロール';
$string['beep'] = 'ビープ';
$string['chat:chat'] = 'チャットルームにアクセスする';
$string['chat:deletelog'] = 'チャットログを削除する';
$string['chat:readlog'] = 'チャットログを表示する';
$string['chat:talk'] = 'チャットで会話する';
$string['chatintro'] = 'イントロダクションテキスト';
$string['chatname'] = 'チャットルーム名';
$string['chatreport'] = 'チャットセッション';
$string['chattime'] = '次回のチャットタイム';
$string['configmethod'] = 'ノーマルチャットメソッドでは、クライアントは定期的にサーバにアクセスして内容を更新します。このメソッドは設定を必要とせず、どこでも使うことができますが、チャット参加者が多くなれば、サーバに大きな負荷がかかる場合があります。Chatサーバデーモンを使用する場合、Unixのシェルアクセスが必要ですが、軽快なチャット環境を提供することができます。';
$string['confignormalupdatemode'] = 'チャットルームは、通常HTTP 1.1の<em>Keep-Alive</em>機能を使用して効果的に更新されます。 しかし、この方法はサーバに対して非常に負荷がかかります。さらに進歩した方法は、チャットルームの更新に<em>Stream</em>を使用するものです。<em>Stream</em>を使用する方法 (chatdメソッドに似ています) は、 <em>Keep-Alive</em>機能の使用より優れていますが、あなたのサーバではサポートされていない場合があります。';
$string['configoldping'] = 'ユーザの応答がなくなってから、どのくらいの時間 (秒数) で退室したとみなしますか? これは単に上限であり、通常の退室は非常に速く検出されます。小さな値を設定する場合、さらにサーバに対して負荷がかかります。ノーマルメソッドを使用している場合、2* chat_refresh_room より小さな値を<strong>設定しないでください</strong>。';
$string['configrefreshroom'] = 'どのくらいのタイミング (秒数) でチャットルームをリフレッシュしますか? この値を小さくすれば、チャットルームはレスポンスが良いように見えますが、多くの人がチャットをする場合、サーバにかかる負荷が高くなります。あなたが<em>Stream</em>更新を使用している場合、高いリフレッシュ頻度を設定することができます -- 2を試してみてください。';
$string['configrefreshuserlist'] = 'どのくらいのタイミング (秒数) でユーザリストをリフレッシュしますか?';
$string['configserverhost'] = 'サーバデーモンが稼動しているホスト名';
$string['configserverip'] = '上記ホスト名のIPアドレス';
$string['configservermax'] = '最大クライアント数';
$string['configserverport'] = 'デーモンに使用するサーバのポート';
$string['currentchats'] = 'アクティブ・チャットセッション';
$string['currentusers'] = '現在のユーザ';
$string['deletesession'] = 'セッションを削除する';
$string['deletesessionsure'] = '本当にこのセッションを削除してもよろしいですか?';
$string['donotusechattime'] = 'チャット時間を公開しない';
$string['enterchat'] = 'チャットルームに入室する';
$string['errornousers'] = 'ユーザが見つかりませんでした!';
$string['explaingeneralconfig'] = 'これらの設定は、<strong>常に</strong>使用されます。';
$string['explainmethoddaemon'] = 'これらの設定は、chat_methodに「Chatサーバデーモン」を選択した場合<strong>のみ</strong>影響します。';
$string['explainmethodnormal'] = 'これらの設定は、chat_methodに「ノーマルメソッド」を選択した場合<strong>のみ</strong>影響します。';
$string['generalconfig'] = '一般設定';
$string['helpchatting'] = 'チャットヘルプ';
$string['idle'] = 'アイドル';
$string['list_all_sessions'] = 'すべてのセッションを表示する';
$string['list_complete_sessions'] = '完了したセッションのみ表示する';
$string['listing_all_sessions'] = 'すべてのセッションを表示しています。';
$string['messagebeepseveryone'] = '$a が全員にビープします!';
$string['messagebeepsyou'] = '$a があなたにビープしました!';
$string['messageenter'] = '$a が入室しました。';
$string['messageexit'] = '$a が退室しました。';
$string['messages'] = 'メッセージ';
$string['method'] = 'Chatメソッド';
$string['methoddaemon'] = 'Chatサーバデーモン';
$string['methodnormal'] = 'ノーマルメソッド';
$string['modulename'] = 'チャット';
$string['modulenameplural'] = 'チャット';
$string['neverdeletemessages'] = 'メッセージを削除しない';
$string['nextsession'] = '次のスケジュールセッション';
$string['no_complete_sessions_found'] = '終了したセッションは、見つかりませんでした。';
$string['noguests'] = 'ゲストは、このチャットを利用できません。';
$string['nomessages'] = 'メッセージがありません。';
$string['normalkeepalive'] = 'KeepAlive';
$string['normalstream'] = 'Stream';
$string['noscheduledsession'] = 'スケジュールセッションがありません。';
$string['notallowenter'] = 'あなたは、チャットルームへの入室を許可されていません。';
$string['oldping'] = '切断タイムアウト';
$string['pastchats'] = '過去のチャットセッション';
$string['refreshroom'] = 'チャットルームをリフレッシュする';
$string['refreshuserlist'] = 'ユーザリストをリフレッシュする';
$string['removemessages'] = 'すべてのメッセージを削除する';
$string['repeatdaily'] = '毎日同じ時間に';
$string['repeatnone'] = '繰り返しなし - 指定した時間にのみ公開する';
$string['repeattimes'] = 'セッションの繰り返し';
$string['repeatweekly'] = '毎週同じ時間に';
$string['savemessages'] = 'セッションの保存期間';
$string['seesession'] = 'このセッションを見る';
$string['serverhost'] = 'サーバ名';
$string['serverip'] = 'サーバIP';
$string['servermax'] = '最大ユーザ';
$string['serverport'] = 'サーバポート';
$string['sessions'] = 'チャットセッション';
$string['strftimemessage'] = '%%H:%%M';
$string['studentseereports'] = 'すべての人が過去のセッションを見ることができる';
$string['updatemethod'] = '更新方法';
$string['viewreport'] = '過去のチャットセッションを表示する';
$string['ajax'] = 'Ajaxバージョン'; // ORPHANED
$string['cantlogin'] = 'チャットルームに入室できませんでした!'; // ORPHANED
$string['chat:exportparticipatedsession'] = '参加チャットセッションをエクスポートする'; // ORPHANED
$string['chat:exportsession'] = 'チャットセッションをエクスポートする'; // ORPHANED
$string['chatadministration'] = 'チャット管理'; // ORPHANED
$string['inputarea'] = '入力エリア'; // ORPHANED
$string['invalidid'] = 'チャットルームが見つかりませんでした!'; // ORPHANED
$string['nochat'] = 'チャットが見つかりませんでした。'; // ORPHANED
$string['notlogged'] = 'ログインしていません!'; // ORPHANED
$string['saidto'] = '&gt;'; // ORPHANED
$string['send'] = '送信'; // ORPHANED
$string['sending'] = '送信中'; // ORPHANED
$string['talk'] = '会話'; // ORPHANED
$string['updaterate'] = '更新レート:'; // ORPHANED
$string['userlist'] = 'ユーザリスト'; // ORPHANED
$string['cantinsert'] = 'チャットメッセージを追加できませんでした!'; // ORPHANED

?>
