<?PHP // $Id$ 
      // error.php - created with Moodle 1.9.17+ (Build: 20120427) (2007101591.15)


$string['adminprimarynoedit'] = '主管理者は他のユーザから編集することはできません。';
$string['cannotassignrole'] = 'コース内でロールを割り当てることができません。';
$string['cannotcreatelangdir'] = 'langディレクトリを作成できません。';
$string['cannotcreatetempdir'] = 'tempディレクトリを作成できません。';
$string['cannotcustomizelocallang'] = 'あなたには翻訳ストリングをカスタマイズするパーミッションがありません。このパーミッションはケイパビリティ「moodle/site:langeditlocal」でコントロールされます。あなたのサイトの翻訳ストリングを修正したい場合、このケイパビリティを設定して、ローカル言語パックを編集できるようにしてください。';
$string['cannotdownloadcomponents'] = 'コンポーネットをダウンロードできません。';
$string['cannotdownloadlanguageupdatelist'] = 'download.moodle.orgから言語の更新リストをダウンロードできません。';
$string['cannotdownloadzipfile'] = 'ZIPファイルをダウンロードできません。';
$string['cannoteditmasterlang'] = 'あなたにはマスター翻訳ストリングを編集するパーミッションがありません。このパーミッションはケイパビリティ「moodle/site:langeditmaster」でコントロールされます。あなたが言語パックの管理者の場合、このケイパビリティを設定して、マスター言語パックを編集できるようにしてください。';
$string['cannotfindcomponent'] = 'コンポーネントを見つけることができません。';
$string['cannotinsertrecord'] = 'レコードID $a のレコードを追加できませんでした。';
$string['cannotsavemd5file'] = 'mp5ファイルを保存できません。';
$string['cannotsavezipfile'] = 'ZIPファイルを保存できません。';
$string['cannotunzipfile'] = 'ZIPファイルを解凍できません。';
$string['cannotupdaterecord'] = 'レコードID $a を更新できませんでした。';
$string['cannotviewprofile'] = 'あなたはこのユーザのプロファイルを閲覧できません。';
$string['cantunenrollfrommetacourse'] = 'あなたはこのメタコースから登録解除できません。';
$string['cantunenrollinthisrole'] = '現在のロールが割り当てられている間、あなたはこのコースから登録解除できません。';
$string['cmunknown'] = 'このコースモジュールを見つけることができません。';
$string['componentisuptodate'] = 'コンポーネントは最新です。';
$string['confirmsesskeybad'] = '申し訳ございません、このアクションの実行に関して、あなたのセッションキーでは確認できませんでした。このセキュリティ機能はあなたのユーザ名で重要な機能が不測または悪意により実行されることを防ぎます。本当にこの機能を実行したいか確認してください。';
$string['couldnotassignrole'] = 'あなたにロールを割り当てている最中に、深刻ですが不明なエラーが発生しました。';
$string['countriesphpempty'] = 'エラー: 言語パック $a のファイル「countries.php」が空または存在しません。';
$string['coursegroupunknown'] = 'コースに関連するグループ $a が指定されていません。';
$string['csvcolumnduplicates'] = '重複するカラムが見つかりました。';
$string['csvemptyfile'] = 'CSVファイルが空です。';
$string['csvfewcolumns'] = 'カラムが不足しています、デリミタ設定を確認してください。';
$string['csvweirdcolumns'] = '無効なCSVファイルフォーマット - カラム数が一定ではありません!';
$string['dbupdatefailed'] = 'データベースの更新が失敗しました。';
$string['downloadedfilecheckfailed'] = 'ダウンロードファイルのチェックに失敗しました。';
$string['duplicateusername'] = '重複ユーザ名 - レコードをスキップ';
$string['errorcleaningdirectory'] = 'ディレクトリ「 $a 」のクリーニング中にエラーが発生しました。';
$string['errorcopyingfiles'] = 'ファイルのコピー中にエラーが発生しました。';
$string['errorcreatingdirectory'] = 'ディレクトリ「 $a 」の作成中にエラーが発生しました。';
$string['errorcreatingfile'] = 'ファイル「 $a 」の作成中にエラーが発生しました。';
$string['erroronline'] = '$a 行目にエラーがあります。';
$string['errorreadingfile'] = 'ファイル「 $a 」の読み取り中にエラーが発生しました。';
$string['errorsavingrequest'] = 'あなたのリクエストを保存中にエラーが発生しました。';
$string['errorunzippingfiles'] = 'ファイルの解凍処理中にエラーが発生しました。';
$string['fieldrequired'] = '「 $a 」 は必須項目です。';
$string['filenotfound'] = '申し訳ございません、ファイルが見つかりませんでした。';
$string['forumblockingtoomanyposts'] = 'このフォーラムに設定されている登録期限を超えています。';
$string['groupalready'] = 'ユーザはすでにグループ「 $a 」に属しています';
$string['groupexistforcourse'] = 'グループ「 $a 」はすでにこのコースに登録されています。';
$string['groupnotaddederror'] = 'グループ「 $a 」は追加されませんでした。';
$string['groupunknown'] = 'グループ「 $a 」は指定されたコースに関連していません。';
$string['groupusernotmember'] = 'ユーザはこのグループのメンバーではありません。';
$string['guestnoeditprofile'] = 'ゲストユーザはプロファイルを変更できません。';
$string['guestnoeditprofileother'] = 'ゲストユーザのプロファイルを変更できません。';
$string['guestsarenotallowed'] = 'ゲストユーザはこの処理を実行できません。';
$string['invalidadminsettingname'] = '無効なadmin設定 ($a) です。';
$string['invalidcontext'] = '無効なコンテクストです。';
$string['invalidcourse'] = '無効なコースです。';
$string['invalidcourseid'] = 'あなたは無効なコースID ($a) の使用を試みています。';
$string['invalidcoursemodule'] = '無効なコースモジュールIDです。';
$string['invalidfieldname'] = '「 $a 」 は正しいフィールド名ではありません。';
$string['invalidfiletype'] = '「 $a 」は有効なファイルタイプではありません。';
$string['invalidipformat'] = '無効なIPアドレスフォーマットです。';
$string['invalidmd5'] = '無効なmp5ファイルです。';
$string['invalidrequest'] = '無効なリクエストです。';
$string['invalidrole'] = '無効なロールです。';
$string['invalidsesskey'] = '無効なsesskeyが送信されました。フォームの内容は受信されませんでした!';
$string['invalidurl'] = '無効なURIです。';
$string['invalidxmlfile'] = '「 $a 」は有効なXMLファイルではありません。';
$string['iplookupfailed'] = 'このIPアドレス $a に関するgeo情報を見つけることができません。';
$string['iplookupprivate'] = 'プライベートIPアドレスのルックアップは表示できません。';
$string['listcantmovedown'] = 'アイテムの下移動に失敗しました。これは最下位のアイテムです。';
$string['listcantmoveleft'] = 'アイテムの左移動に失敗しました。親がありません。';
$string['listcantmoveright'] = 'アイテムの右移動に失敗しました。子にするアイテムがありません。下に移動して他のアイテムの子にすることはできます。';
$string['listcantmoveup'] = 'アイテムの上移動に失敗しました。これは最上位のアイテムです。';
$string['listnochildren'] = '子アイテムが見つかりませんでした。';
$string['listnoitem'] = 'アイテムが見つかりませんでした。';
$string['listnopeers'] = '同レベルのアイテムが見つかりませんでした。';
$string['listupdatefail'] = 'リスト階層の編集中にデータベースエラーが発生しました。';
$string['loginasnoenrol'] = 'コース「ログイン」セッション時、あなたはユーザ登録および登録抹消することはできません。';
$string['loginasonecourse'] = 'あなたはこのコースに入ることはできません。<br />他のコースに入る前に、現在の「ログイン」セッションを終了する必要があります。';
$string['missingfield'] = 'フィールド「 $a 」 に入力してください。';
$string['missingrequiredfield'] = 'いくつかの必須入力フィールドが入力されていません。';
$string['modulemissingcode'] = 'この機能を実行するためのコードがモジュール $a にありません。';
$string['modulerequirementsnotmet'] = 'モジュール「 $a->modulename 」 ($a->moduleversion) をインストールできませんでした。このモジュールをインストールするためには新しいバージョンのMoodleをインストールする必要があります。(現在、あなたは $a->currentmoodle を使用しています。 $a->requiremoodle が必要です。)';
$string['mustbeteacher'] = 'このページは教師のみ閲覧可能です。';
$string['nocategorydelete'] = 'カテゴリ「 $a 」は削除できません!';
$string['nocontext'] = '申し訳ございません、そのコースは有効なコンテクストではありません。';
$string['noinstances'] = 'このコースに $a のインスタンスがありません!';
$string['nologinas'] = 'あなたはそのユーザとしてのログインを許可されていません。';
$string['nonmeaningfulcontent'] = '意味の無いコンテンツです。';
$string['noparticipatorycms'] = '申し訳ございません、レポートするための参加者がいるコースモジュールはありません。';
$string['nopermissions'] = '申し訳ございません、あなたには現在、「 $a 」のパーミッションがありません。';
$string['nostatstodisplay'] = '申し訳ございません、表示するデータがありません。';
$string['notavailable'] = '現在利用できません';
$string['onlyadmins'] = '管理者のみ処理可能です。';
$string['onlyeditingteachers'] = '編集権限を持った教師のみ処理可能です。';
$string['onlyeditown'] = '他の人の情報は編集できません。';
$string['pagenotexist'] = '異常なエラー (存在しないページへのアクセス) が発生しました。';
$string['pleasereport'] = 'あなたに時間がある場合、エラーが発生したとき、あなたが何を試みたのか私たちにお教えください:';
$string['pluginrequirementsnotmet'] = 'プラグイン 「 $a->pluginname 」 ($a->pluginversion) をインストールできませんでした。インストールするには、新しいバージョンのMoodleが必要です (現在使用しているバージョン: $a->currentmoodle  インストールに必要なバージョン: $a->requiremoodle)。';
$string['processingstops'] = 'ここで処理が停止します。残りのレコードは無視されました。';
$string['remotedownloaderror'] = 'あなたのサーバへのコンポーネントのダウンロードに失敗しました。プロクシ設定を確認してください。PHP cURL拡張モジュールの使用を強くお勧めします。<br /><br /><a href=\"$a->url\">$a->url</a>ファイルを手動でダウンロードした後、あなたのサーバの「 $a->dest 」にコピーおよび解凍してください。';
$string['remotedownloadnotallowed'] = 'あなたのサーバにコンポーネントをダウンロードすることができません (allow_url_fopen が無効)。<br /><br /><a href=\"$a->url\">$a->url</a> ファイルを手動でダウンロードして、サーバの「 $a->dest 」にコピーした後、解凍してください。';
$string['restorechecksumfailed'] = 'あなたのセッションに保存されているリストア情報に問題が生じました。あなたのPHPメモリ/DBパッケージサイズ制限を確認してください。リストアを停止しました。';
$string['restricteduser'] = '申し訳ございません、あなたのアカウント「 $a 」ではこの処理を実行できません。';
$string['scheduledbackupsdisabled'] = 'スケジュールバックアップはサーバ管理者により無効にされています。';
$string['sendmessage'] = 'メッセージを送信する';
$string['sessionerroruser'] = 'セッションがタイムアウトしました。再度ログインしてください。';
$string['sessionerroruser2'] = 'あなたのログインセッションに影響を与えるサーバエラーが検知されました。再度ログインするかブラウザを再起動してください。';
$string['sessionipnomatch'] = '申し訳ございません、あなたのIPアドレスは最初のログインから変更されているようです。このセキュリティ機能はあなたがサイトにログインしている間、クラッカーから個人情報を盗むことを防いでいます。通常のユーザはこのメッセージを見ることはありません - 詳細はシステム管理者にお問合せください。';
$string['socksnotsupported'] = 'PHP4ではSOCKS5プロクシがサポートされていません。';
$string['statscatchupmode'] = '現在、統計はキャッチアップモードです。今までのところ $a->daysdone 日分が処理され、$a->dayspending 日分が未処理です。すぐに確認してください!';
$string['tagnotfound'] = '指定されたタグはデータベースで見つかりませんでした。';
$string['unicodeupgradeerror'] = '申し訳ございません、あなたのデータベースはユニコードに対応していません。このバージョンのMoodleはデータベースをユニコードに移行できません。最初にMoodle 1.7.x にアップグレードして、管理画面でデータベースをユニコードへ移行してください。ユニコード移行後、Moodle $a へのアップグレードが可能となります。';
$string['unknowncourse'] = '不明なコース名「 $a 」です。';
$string['unknowncourseidnumber'] = '不明なコースID「 $a 」です。';
$string['unknowncourserequest'] = '不明なコースリクエストです。';
$string['unknowngroup'] = '不明なグループ「 $a 」です。';
$string['unknownrole'] = '不明なロール「 $a 」です。';
$string['unknownuseraction'] = '申し訳ございません、このユーザアクションが理解できません。';
$string['userautherror'] = '不明な認証プラグイン「 $a 」';
$string['userauthunsupported'] = 'ここでは認証プラグインがサポートされていません。';
$string['useremailduplicate'] = '重複メールアドレス';
$string['usernotaddedadmin'] = '管理者アカウントは削除できません。';
$string['usernotaddederror'] = 'ユーザは追加されませんでした - エラー。';
$string['usernotaddedregistered'] = 'ユーザは追加されませんでした - すでに登録されています。';
$string['usernotavailable'] = 'このユーザの詳細は閲覧できません。';
$string['usernotdeletederror'] = 'ユーザは削除されませんでした - 不明なエラー。';
$string['usernotdeletedmissing'] = 'ユーザは削除されませんでした - ユーザ名が見つかりませんでした。';
$string['usernotdeletedoff'] = 'ユーザは削除されませんでした - 削除が許可されていません。';
$string['usernotrenamedadmin'] = '管理者アカウントは更新できません。';
$string['usernotrenamedexists'] = 'ユーザはリネームされませんでした - 新しいユーザ名がすでに使用されています。';
$string['usernotrenamedmissing'] = 'ユーザはリネームされませんでした - 古いユーザ名が見つかりませんでした。';
$string['usernotrenamedoff'] = 'ユーザはリネームされませんでした - リネームが許可されていません。';
$string['usernotupdatedadmin'] = '管理者アカウントを更新できませんでした。';
$string['usernotupdatederror'] = 'ユーザは更新されませんでした - エラー。';
$string['usernotupdatednotexists'] = 'ユーザは更新されませんでした - 登録されていません。';
$string['wrongdestpath'] = '宛先パスが正しくありません。';
$string['wrongsourcebase'] = 'ソースURIベースが正しくありません。';
$string['wrongzipfilename'] = 'ZIPファイル名が正しくありません。';
$string['youcannotdeletecategory'] = 'コンテンツを削除または移動できないため、あなたはカテゴリ「 $a 」を削除することはできません。';
$string['zipfileserror'] = 'ZIPファイルを作成できません。';
$string['TODO'] = 'TODO'; // ORPHANED
$string['authnotexisting'] = '認証プラグインがありません。'; // ORPHANED
$string['authorizeerror'] = '認証エラー'; // ORPHANED
$string['backupcontainexternal'] = 'このバックアップファイルにはローカルに設定されていない外部Moodleネットワークホストが含まれています。'; // ORPHANED
$string['backuptablefail'] = 'バックアップテーブルが正常に設定されていません!'; // ORPHANED
$string['blockcannotconfig'] = 'このブロックはグローバル設定をサポートしません。'; // ORPHANED
$string['blockcannotinistantiate'] = 'ブロックオブジェクトのインストール中に問題が発生しました。'; // ORPHANED
$string['blockcannotread'] = 'ブロックID = $a のデータを読み込めませんでした。'; // ORPHANED
$string['blockdoesnotexist'] = 'このブロックはありません。'; // ORPHANED
$string['blockdoesnotexistonpage'] = 'このブロック (id=$a->instanceid) はこのページ ($a->url) にはありません。'; // ORPHANED
$string['blocknameconflict'] = 'ネーミングコンフリクト: ブロック $a->name には既存のブロック $a->conflict と同じタイトルが設定されています!'; // ORPHANED
$string['cannotaddcoursemodule'] = '新しいコースモジュールを追加できませんでした。'; // ORPHANED
$string['cannotaddcoursemoduletosection'] = '新しいコースモジュールをセクションに追加できませんでした。'; // ORPHANED
$string['cannotaddmodule'] = '$a モジュールをモジュールリストに追加できませんでした!'; // ORPHANED
$string['cannotaddnewmodule'] = '$a の新しいモジュールを追加できませんでした。'; // ORPHANED
$string['cannotaddrss'] = 'あなたにはRSSフィードを追加するパーミッションがありません。'; // ORPHANED
$string['cannotaddthisblocktype'] = 'あなたはこのページに $a ブロックを追加できません。'; // ORPHANED
$string['cannotassignanthing'] = 'moodle/site:doanythingを割り当てることができません。'; // ORPHANED
$string['cannotassignrolehere'] = 'あなたはこのコンテクスト ($a->context) において、このロール (id = $a->roleid) の割り当てを許可されていません。'; // ORPHANED
$string['cannotassignselfasparent'] = '自分自身を親カテゴリに割り当てることはできません!'; // ORPHANED
$string['cannotcallscript'] = 'このスクリプトを、そのように使うことはできません。'; // ORPHANED
$string['cannotcallusgetselecteduser'] = 'multiselectがtrueの場合、あなたはuser_selector::get_selected_userをコールできません。'; // ORPHANED
$string['cannotcreatebackupdir'] = 'バックアップデータフォルダを作成できませんでした。サイト管理者がファイルパーミッションを変更する必要があります。'; // ORPHANED
$string['cannotcreatecategory'] = 'カテゴリは追加されませんでした。'; // ORPHANED
$string['cannotcreategroup'] = 'グループの作成中にエラーが発生しました。'; // ORPHANED
$string['cannotcreatelangbase'] = 'エラー: ベース言語ディレクトリを作成できませんでした。'; // ORPHANED
$string['cannotcreateorfindstructs'] = 'このコースのセクション構造の検出または作成中にエラーが発生しました。'; // ORPHANED
$string['cannotcreatepopupwin'] = '未定義エレメント - ポップアップウィンドウを作成できません。'; // ORPHANED
$string['cannotcreatesitedir'] = 'サイトフォルダを作成できません。サイト管理者はファイルパーミッションを修正する必要があります。'; // ORPHANED
$string['cannotcreateuploaddir'] = 'アップロードフォルダを作成できません。サイト管理者はファイルパーミッションを修正する必要があります。'; // ORPHANED
$string['cannotcustomisefiltersblockuser'] = 'あなたはユーザまたはブロックコンテクストでフィルタ設定をカスタマイズできません。'; // ORPHANED
$string['cannotdeletebackupids'] = '前回のバックアップIDを削除できませんでした。'; // ORPHANED
$string['cannotdeletecategorycourse'] = 'コース「 $a 」の削除に失敗しました。'; // ORPHANED
$string['cannotdeletecategoryquestions'] = 'カテゴリ「 $a 」から問題を削除できませんでした。'; // ORPHANED
$string['cannotdeletecourse'] = 'あなたにはこのコースを削除するパーミッションがありません。'; // ORPHANED
$string['cannotdeletecustomfield'] = 'カスタムフィールドデータの削除中にエラーが発生しました。'; // ORPHANED
$string['cannotdeletedir'] = '$a を削除できませんでした。'; // ORPHANED
$string['cannotdeletefile'] = 'このファイルを削除できませんでした。'; // ORPHANED
$string['cannotdeletelangcache'] = '言語キャッシュを削除できません。dataroot/cache/languagesのパーミッションを修正してください!'; // ORPHANED
$string['cannotdeleterole'] = '次の理由で削除できません: $a'; // ORPHANED
$string['cannotdeleterolewithid'] = 'ID $a のロールを削除できませんでした。'; // ORPHANED
$string['cannotdeletethisrole'] = 'システムで使用されている、または管理者ケイパビリティの最後のロールのため、あなたはこのロールを削除することができません。'; // ORPHANED
$string['cannoteditcomment'] = 'あなたが編集できるコメントではありません!'; // ORPHANED
$string['cannoteditcommentexpired'] = 'あなたはコメントを編集できません! 編集期限が終了しています!'; // ORPHANED
$string['cannoteditpostorblog'] = 'あなたはブログに投稿または編集できません。'; // ORPHANED
$string['cannoteditsiteform'] = 'あなたはこのフォームを使用してサイトコースを編集できません。'; // ORPHANED
$string['cannotedityourprofile'] = '申し訳ございません、あなたは自分のプロファイルを編集できません。'; // ORPHANED
$string['cannotfindcategory'] = 'データベースからID「 $a 」でカテゴリレコードを見つけることができません。'; // ORPHANED
$string['cannotfindcontext'] = 'コンテクストを見つけることができませんでした。'; // ORPHANED
$string['cannotfinddocs'] = '言語docsファイル「 $a 」を見つけることができません。'; // ORPHANED
$string['cannotfindgradeitem'] = 'grade_itemが見つかりません'; // ORPHANED
$string['cannotfindgroup'] = 'グループを見つけることができません。'; // ORPHANED
$string['cannotfindhelp'] = '言語helpファイル「 $a 」を見つけることができません。'; // ORPHANED
$string['cannotfindinfo'] = '次の情報が見つかりません: 「 $a 」'; // ORPHANED
$string['cannotfindlang'] = '「 $a 」言語パックが見つかりません!'; // ORPHANED
$string['cannotfindteacher'] = '教師が見つかりません。'; // ORPHANED
$string['cannotfinduser'] = 'ユーザ名「 $a 」のユーザが見つかりません。'; // ORPHANED
$string['cannotgetblock'] = 'データベースからブロックを検索できませんでした。'; // ORPHANED
$string['cannotgetcats'] = 'カテゴリレコードを取得できません。'; // ORPHANED
$string['cannotgetdata'] = 'データを取得できません。'; // ORPHANED
$string['cannotgradeuser'] = 'このユーザを評定できません。'; // ORPHANED
$string['cannothaveparentcate'] = 'コースカテゴリには親カテゴリを設定できません!'; // ORPHANED
$string['cannotimport'] = 'インポートエラー'; // ORPHANED
$string['cannotimportformat'] = '申し訳ございません、このフォーマットのインポートはまだ実装されていません!'; // ORPHANED
$string['cannotimportgrade'] = '評定インポートエラー'; // ORPHANED
$string['cannotinsertgrade'] = 'コースIDなしに評定項目を追加できません!'; // ORPHANED
$string['cannotinsertrate'] = '新しい評価 ($a->id = $a->rating) を追加できませんでした。'; // ORPHANED
$string['cannotmailconfirm'] = 'パスワード変更の確認メール送信中にエラーが発生しました。'; // ORPHANED
$string['cannotmanualctrack'] = '活動が手動完了トラッキングをサポートしていません。'; // ORPHANED
$string['cannotmapfield'] = 'マッピングの衝突が発生しました。2つのフィールドが同じ評定項目 $a にマップされています。'; // ORPHANED
$string['cannotmarktopic'] = 'このコースのトピックをマークできませんでした。'; // ORPHANED
$string['cannotmetacourse'] = '選択したコースを、このメタコースに追加できません!'; // ORPHANED
$string['cannotmodulename'] = 'ビルドナビゲーションでモジュール名を取得できません。'; // ORPHANED
$string['cannotmoduletype'] = 'ビルドナビゲーションでモジュールタイプを取得できません。'; // ORPHANED
$string['cannotmoverolewithid'] = 'ID $a のロールを移動できません。'; // ORPHANED
$string['cannotnetgeo'] = 'http://netgeo.caida.orgのNetGeoサーバに接続できません。プロクシ設定およびMaxMind GeoLite Cityデータファイルのインストールを確認してください。'; // ORPHANED
$string['cannotopencsv'] = 'CSVファイルをオープンできません。'; // ORPHANED
$string['cannotopenfile'] = 'ファイル「 $a 」をオープンできません。'; // ORPHANED
$string['cannotopenforwrit'] = '書き込みのため「 $a 」をオープンできません。'; // ORPHANED
$string['cannotopentemplate'] = 'テンプレートファイル「 $a 」をオープンできません。'; // ORPHANED
$string['cannotopenzip'] = 'ZIPファイルを開くことができません。恐らく、64ビットOSのZIP拡張子に関するバグだと考えられます。'; // ORPHANED
$string['cannotoverridebaserole'] = 'ベースロールのケイパビリティをオーバーライドできません。'; // ORPHANED
$string['cannotoverriderolehere'] = 'あなたはこのコンテクスト ($a->context) のロール (id = $a->roleid) をオーバーライドできません。'; // ORPHANED
$string['cannotreadfile'] = 'ファイルを読み込めません。'; // ORPHANED
$string['cannotreadtmpfile'] = '一時ファイルの読み込み中にエラーが発生しました。'; // ORPHANED
$string['cannotreaduploadfile'] = 'アップロードファイルを読み込めません。'; // ORPHANED
$string['cannotremovefrommeta'] = 'このメタコースから、選択したコースを削除できませんでした!'; // ORPHANED
$string['cannotresetguestpwd'] = 'あなたはゲストのパスワードをリセットできません。'; // ORPHANED
$string['cannotresetmail'] = 'パスワードのリセットおよびメール送信中にエラーが発生しました。'; // ORPHANED
$string['cannotresetthisrole'] = 'このロールをリセットできません。'; // ORPHANED
$string['cannotrestore'] = 'エラーが発生したため、正常にリストアできませんでした!'; // ORPHANED
$string['cannotrestoreadminorcreator'] = '新しいコースにリストアするには、あなたはコース作成者または管理者である必要があります!'; // ORPHANED
$string['cannotrestoreadminoredit'] = '選択されたコースにリストアするには、あなたは編集権限のある教師または管理者である必要があります!'; // ORPHANED
$string['cannotsaveagreement'] = 'あなたの同意を保存できませんでした。'; // ORPHANED
$string['cannotsaveblock'] = 'ブロック設定の保存中にエラーが発生しました。'; // ORPHANED
$string['cannotsavecomment'] = 'コメントを保存できません。'; // ORPHANED
$string['cannotsavedata'] = 'データを保存できません。'; // ORPHANED
$string['cannotsavefile'] = 'ファイル「 $a 」を保存できません。'; // ORPHANED
$string['cannotsetparentforcatoritem'] = 'カテゴリまたはコースアイテムに親カテゴリを設定できません!'; // ORPHANED
$string['cannotsetpassword'] = 'ユーザパスワードを設定できませんでした!'; // ORPHANED
$string['cannotsetprefgrade'] = 'この評定カテゴリの $a に総計表示を設定できませんでした。'; // ORPHANED
$string['cannotsettheme'] = 'テーマを設定できませんでした!'; // ORPHANED
$string['cannotsetupblock'] = 'ブロックテーブルが正常に設定されませんでした!'; // ORPHANED
$string['cannotsetupcapformod'] = '$a のケイパビリティを設定できませんでした。'; // ORPHANED
$string['cannotsetupcapforplugin'] = '$a のケイパビリティを設定できませんでした。'; // ORPHANED
$string['cannotshowhidecoursesincategory'] = 'カテゴリ $a 内のコースを表示/非表示できません。'; // ORPHANED
$string['cannotunassigncap'] = '廃止予定のケイパビリティ $a->cap をロール $a->role から割り当て解除できませんでした。'; // ORPHANED
$string['cannotunassignrolefrom'] = 'このユーザをロールID $a から割り当て解除できませんでした。'; // ORPHANED
$string['cannotupdatemod'] = '$a を更新できませんでした。'; // ORPHANED
$string['cannotupdatepasswordonextauth'] = '外部認証「 $a 」のパスワードの更新に失敗しました。詳細はサーバログをご覧ください。'; // ORPHANED
$string['cannotupdateprofile'] = 'ユーザレコードの更新中にエラーが発生しました。'; // ORPHANED
$string['cannotupdaterss'] = 'RSSを更新できません。'; // ORPHANED
$string['cannotupdatesubcourse'] = '子コースを更新できませんでした!'; // ORPHANED
$string['cannotupdateusermsgpref'] = 'ユーザメッセージ設定を更新できません。'; // ORPHANED
$string['cannotupdateuseronexauth'] = '外部認証「 $a 」のユーザデータ更新にエラーが発生しました。詳細はサーバログをご覧ください。'; // ORPHANED
$string['cannotuploadfile'] = 'ファイルのアップロード中にエラーが発生しました。'; // ORPHANED
$string['cannotuseadmin'] = 'このページを使用するには、管理者である必要があります'; // ORPHANED
$string['cannotuseadminadminorteacher'] = 'このページを使用するには、教師または管理者である必要があります'; // ORPHANED
$string['cannotusepage'] = '教師および管理者のみ、このページを使用できます。'; // ORPHANED
$string['cannotusepage2'] = '申し訳ございません、あなたはこのページを使用できません。'; // ORPHANED
$string['cannotwritefile'] = 'ファイル「 $a 」に書き込めません。'; // ORPHANED
$string['commentmisconf'] = 'コメントIDの設定が正しくありません。'; // ORPHANED
$string['couldnotupdatenoexistinguser'] = 'ユーザを更新できません - ユーザが存在しません。'; // ORPHANED
$string['courseidnotfound'] = 'コースIDが存在しません。'; // ORPHANED
$string['coursemisconf'] = 'コース設定が正しくありません。'; // ORPHANED
$string['courserequestdisabled'] = '申し訳ございません、リクエストされたコースは管理者によって無効にされています。'; // ORPHANED
$string['csvinvalidcols'] = '<b>無効なCSVファイル:</b> 最初の行には「ヘッダフィールド」を含み、ファイルタイプは<br />「カンマ区切りの拡張フィールド」<br />または<br />「CAVV結果コード (Cardholder Authentication Verification Value) を含むカンマ区切りの拡張フィールド」にする必要があります。'; // ORPHANED
$string['csvinvalidcolsnum'] = '無効なCSVファイルフォーマット - それぞれの行には49または70フィールドを含む必要があります。'; // ORPHANED
$string['csvloaderror'] = 'CSVファイルの読込み中にエラーが発生しました!'; // ORPHANED
$string['dbconnectionfailed'] = '<p>エラー: データベースの接続に失敗しました。</p>
<p>データベースがオーバーロードしているか、正常に動作していないことが考えられます。</p>
<p>サイト管理者はconfig.phpでデータベース詳細が正しく設定されているか確認してください。</p><p>$a</p>'; // ORPHANED
$string['dbdriverproblem'] = '<p>エラー: データベースドライバに問題が見つかりました。</p>
<p>サイト管理者はサーバ設定を確認してください。</p><p>$a</p>'; // ORPHANED
$string['dbsessionbroken'] = '深刻なデータベースセッション問題が見つかりました。<br /><br />サイト管理者にご連絡ください。'; // ORPHANED
$string['dbsessionhandlerproblem'] = 'データベースセッションのセットアップに失敗しました。<br /><br />サイト管理者にご連絡ください。'; // ORPHANED
$string['dbsessionmysqlpacketsize'] = '深刻なデータベースセッション問題が見つかりました。<br /><br />サイト管理者にご連絡ください。多くの場合、この問題はMySQL設定「max_allowed_packet」の設定値が小さいことで発生します。'; // ORPHANED
$string['ddldependencyerror'] = '$a->targettype 「 $a->targetname 」を修正できません。$a->offendingtype 「 $a->offendingname 」に依存関係が見つかりました。'; // ORPHANED
$string['ddlexecuteerror'] = 'DDL sql実行エラーが発生しました。'; // ORPHANED
$string['ddlfieldalreadyexists'] = 'フィールド「 $a 」がありません。'; // ORPHANED
$string['ddlfieldnotexist'] = 'テーブル「 $a->tablename 」内にフィールド「 $a->fieldname 」がありません。'; // ORPHANED
$string['ddltablealreadyexists'] = 'テーブル「 $a 」はすでに登録されています。'; // ORPHANED
$string['ddltablenotexist'] = 'テーブル「 $a 」がありません。'; // ORPHANED
$string['ddlunknownerror'] = '不明なDDLライブラリエラーが発生しました。'; // ORPHANED
$string['ddlxmlfileerror'] = 'XMLデータベースファイルにエラーが見つかりました。'; // ORPHANED
$string['destinationcmnotexit'] = '目的のコースモジュールがありません。'; // ORPHANED
$string['detectedbrokenplugin'] = '申し訳ございません、プラグイン「 $a 」に問題があるため、継続できません。'; // ORPHANED
$string['dmlreadexception'] = 'データベースからの読み込み中にエラーが発生しました。'; // ORPHANED
$string['dmlwriteexception'] = 'データベースへの書き込み中にエラーが発生しました。'; // ORPHANED
$string['duplicateparaminsql'] = 'エラー: クエリのパラメータ名が重複しています。'; // ORPHANED
$string['duplicaterolename'] = 'この名称のロールはすでに登録されています!'; // ORPHANED
$string['duplicateroleshortname'] = 'この省略名のロールはすでに登録されています!'; // ORPHANED
$string['emailfail'] = 'メール送信に失敗しました。'; // ORPHANED
$string['error'] = 'エラーが発生しました。'; // ORPHANED
$string['errorcreatingrole'] = 'ロールの作成中にエラーが発生しました。'; // ORPHANED
$string['errorfetchingrssfeed'] = 'RSSフィードの取得中にエラーが発生しました。'; // ORPHANED
$string['errorsettinguserpref'] = 'ユーザプリファレンスの設定中にエラーが発生しました。'; // ORPHANED
$string['errorupdatingcoursevisibility'] = 'コース可視性の更新中にエラーが発生しました。'; // ORPHANED
$string['expiredkey'] = 'キーの有効期限が切れています。'; // ORPHANED
$string['failtoloadblocks'] = '1つまたはそれ以上のブロックがデータベースに登録されていますが、すべて読み込みに失敗しました!'; // ORPHANED
$string['filemismatch'] = 'ノンコアのファイル名が一致しません。ファイル「 $a->current 」は「 $a->file 」であるべきです。'; // ORPHANED
$string['filenotreadable'] = 'ファイルを読み込めません。'; // ORPHANED
$string['filterdoesnothavelocalconfig'] = 'フィルタ $a ではローカル設定を許可されていません。'; // ORPHANED
$string['filternotactive'] = '現在、フィルタ $a は有効ではありません。'; // ORPHANED
$string['filternotenabled'] = 'フィルタが有効にされていません!'; // ORPHANED
$string['filternotinstalled'] = '現在、フィルタ $a はインストールされていません。'; // ORPHANED
$string['generalexceptionmessage'] = '例外 - $a'; // ORPHANED
$string['gradepubdisable'] = '評定の公開が無効にされています。'; // ORPHANED
$string['guestnocomment'] = 'ゲストはコメントを投稿できません。'; // ORPHANED
$string['guestnorate'] = 'ゲストはエントリを評価できません。'; // ORPHANED
$string['hackdetected'] = '不正侵入が検知されました!'; // ORPHANED
$string['hashpoolproblem'] = 'POOLファイルコンテンツ $a が正しくありません。'; // ORPHANED
$string['headersent'] = 'すでにヘッダが送信されています。'; // ORPHANED
$string['idnumbertaken'] = 'IDナンバーがすでに別のコースで使用されています。'; // ORPHANED
$string['importformatnotimplement'] = '申し訳ございません、このフォーマットのインポートはまだ実装されていません!'; // ORPHANED
$string['incorrectext'] = 'ファイルの拡張子が正しくありません。'; // ORPHANED
$string['invalidaccess'] = 'このページは正しくアクセスされていません。'; // ORPHANED
$string['invalidaccessparameter'] = '無効なアクセスパラメータです。'; // ORPHANED
$string['invalidaction'] = '無効なアクションパラメータです。'; // ORPHANED
$string['invalidactivityid'] = '無効な活動IDです。'; // ORPHANED
$string['invalidargorconf'] = '有効な引数が提供されていないか、サーバ設定が正しくありません。'; // ORPHANED
$string['invalidarguments'] = '有効な引数が提供されていません。'; // ORPHANED
$string['invalidblockinstance'] = '$a のブロックインスタンスが無効です。'; // ORPHANED
$string['invalidcategory'] = '無効なカテゴリです!'; // ORPHANED
$string['invalidcategoryid'] = '無効なカテゴリIDです!'; // ORPHANED
$string['invalidcomment'] = 'コメントが正しくありません。'; // ORPHANED
$string['invalidconfirmdata'] = '無効な確認データです。'; // ORPHANED
$string['invalidcourselevel'] = '無効なコンテクストレベルです。'; // ORPHANED
$string['invalidcoursenameshort'] = '無効なコース省略名です。'; // ORPHANED
$string['invaliddata'] = '送信されたデータが無効です。'; // ORPHANED
$string['invalidelementid'] = '無効なエレメントIDです。'; // ORPHANED
$string['invalidenrol'] = '無効な登録が試みられました。'; // ORPHANED
$string['invalidentry'] = '有効なエントリではありません!'; // ORPHANED
$string['invalidevent'] = '無効なイベントです。'; // ORPHANED
$string['invalidformatpara'] = '選択パラメータのフォーマットが正しくありません。'; // ORPHANED
$string['invalidformdata'] = 'フォームデータが正しくありません。'; // ORPHANED
$string['invalidfunction'] = '関数が正しくありません。'; // ORPHANED
$string['invalidgradeitmeid'] = '評定項目が正しくありません。'; // ORPHANED
$string['invalidgroupid'] = '不正なグループIDが指定されました。'; // ORPHANED
$string['invaliditemid'] = 'アイテムIDが正しくありません。'; // ORPHANED
$string['invalidkey'] = 'キーが正しくありません。'; // ORPHANED
$string['invalidlegacy'] = '無効なレガシーロールのタイプ定義 ($a) です。'; // ORPHANED
$string['invalidmode'] = '無効なモード ($a) です。'; // ORPHANED
$string['invalidmodule'] = '無効なモジュールです。'; // ORPHANED
$string['invalidmoduleid'] = '無効なモジュールID ($a) です。'; // ORPHANED
$string['invalidmodulename'] = '無効なモジュール名 ($a) です。'; // ORPHANED
$string['invalidnum'] = '無効な数値です。'; // ORPHANED
$string['invalidnumkey'] = '\$conditions 配列には数字キーを含むことができません、コードを修正してください!'; // ORPHANED
$string['invalidoutcome'] = '無効なアウトカムIDです。'; // ORPHANED
$string['invalidpagesize'] = '無効なページサイズです。'; // ORPHANED
$string['invalidpaymentmethod'] = '無効な支払方法: $a'; // ORPHANED
$string['invalidqueryparam'] = 'エラー: クエリパラメータ数が正しくありません。期待されたパラメータ数 Expected $a->expected 件に対して、$a->actual 件が渡されています。'; // ORPHANED
$string['invalidrecord'] = 'データベーステーブル「 $a 」の中にデータレコードが見つかりません。'; // ORPHANED
$string['invalidrecordunknown'] = 'データベースの中にデータレコードが見つかりません。'; // ORPHANED
$string['invalidroleid'] = '無効なロールIDです。'; // ORPHANED
$string['invalidscaleid'] = '無効なスケールIDです。'; // ORPHANED
$string['invalidsection'] = 'コースモジュールのレコードに無効なセクションが含まれています。'; // ORPHANED
$string['invalidshortname'] = '無効なコース省略名です。'; // ORPHANED
$string['invalidstatedetected'] = '不明なエラーが発生しました: $a。通常、このエラーは発生しません。'; // ORPHANED
$string['invaliduser'] = '無効なユーザです。'; // ORPHANED
$string['invaliduserid'] = '無効なユーザIDです。'; // ORPHANED
$string['ipmismatch'] = 'クライアントIPアドレスが一致しません。'; // ORPHANED
$string['logfilenotavailable'] = 'ログは利用できません。'; // ORPHANED
$string['messagingdisable'] = 'このサイトではメッセージングが無効にされています。'; // ORPHANED
$string['mimetexisnotexist'] = 'あなたのシステムはmimeTeXを実行できるよう設定されていません。あなたのPHPおよびOSプラットフォームに適した実行ファイルを<a href=\"http://moodle.org/download/mimetex/\">http://moodle.org/download/mimetex/</a>からダウンロードするか、C言語のソースを<a href=\"http://www.forkosh.com/mimetex.zip\"> http://www.forkosh.com/mimetex.zip</a>からダウンロードしてください。ダウンロードしたファイルをコンパイルした後、 あなたの「moodle/filter/tex/」ディレクトリに入れてください。'; // ORPHANED
$string['mimetexnotexecutable'] = 'カスタムmimetexを実行できません!'; // ORPHANED
$string['missingkeyinsql'] = 'エラー: クエリにパラメータ「 $a 」がありません。'; // ORPHANED
$string['missingparam'] = '必須パラメータ ($a) がありません。'; // ORPHANED
$string['missingparameter'] = 'パラメータがありません。'; // ORPHANED
$string['missinguseranditemid'] = 'ユーザIDおよび項目IDがありません。'; // ORPHANED
$string['missingvarname'] = '必須の変数名がありません!'; // ORPHANED
$string['mixedtypesqlparam'] = 'エラー: SQLクエリパラメータのタイプが混合しています!!'; // ORPHANED
$string['mnetdisable'] = 'MNETが有効にされていません。'; // ORPHANED
$string['mnetlocal'] = 'リモートMNETユーザはローカルにログインできません。'; // ORPHANED
$string['moduledisable'] = 'このコースに対して、モジュール ($a) が無効にされました。'; // ORPHANED
$string['moduledoesnotexist'] = 'このモジュールはありません。'; // ORPHANED
$string['moduleinstancedoesnotexist'] = 'このモジュールのインスタンスがありません。'; // ORPHANED
$string['modulerejectcomment'] = 'このコメントの追加をモジュールが拒否しました。'; // ORPHANED
$string['multiplerecordsfound'] = '複数のレコードが見つかりました。1レコードのみ必要です。'; // ORPHANED
$string['multiplerestorenotallow'] = '複数のリストア実行は許可されていません!'; // ORPHANED
$string['mustbeloggedin'] = 'この処理を実行するには、あなたはログインする必要があります。'; // ORPHANED
$string['needcopy'] = 'あなたは最初に何かコピーする必要があります!'; // ORPHANED
$string['needcoursecategroyid'] = 'コースIDまたはカテゴリを入力してください。'; // ORPHANED
$string['needphpext'] = 'あなたのPHPに $a サポートを追加する必要があります。'; // ORPHANED
$string['noadmins'] = '管理者ではありません!'; // ORPHANED
$string['noblocks'] = 'ブロックがありません!'; // ORPHANED
$string['nodata'] = 'データがありません。'; // ORPHANED
$string['noexistingcategory'] = '存在しないカテゴリです。'; // ORPHANED
$string['nofile'] = 'ファイルが指定されていません。'; // ORPHANED
$string['nofiltersenabled'] = '有効にされているフィルタはありません。'; // ORPHANED
$string['nofolder'] = 'リクエストされたディレクトリはありません。'; // ORPHANED
$string['noformdesc'] = 'この活動にはformslibフォーム記述ファイルがありません。'; // ORPHANED
$string['noguest'] = 'ゲストはいません!'; // ORPHANED
$string['noparticipants'] = 'このコースには参加者が登録されていません。'; // ORPHANED
$string['nopermissiontocomment'] = 'あなたはコメントを追加できません!'; // ORPHANED
$string['nopermissiontodelentry'] = 'あなたは他のユーザのエントリを削除できません!'; // ORPHANED
$string['nopermissiontoeditcomment'] = 'あなたは他のユーザのコメントを編集できません!'; // ORPHANED
$string['nopermissiontohide'] = '非表示にするパーミッションはありません!'; // ORPHANED
$string['nopermissiontoimportact'] = 'あなたにはこのコースに活動をインポートするため必要なパーミッションがありません。'; // ORPHANED
$string['nopermissiontolock'] = 'ロックするパーミッションはありません!'; // ORPHANED
$string['nopermissiontomanagegroup'] = 'あなたにはグループを管理するため必要なパーミッションがありません。'; // ORPHANED
$string['nopermissiontomkdir'] = 'フォルダを作成できません。サイト管理者がファイルパーミッションを変更する必要があります。'; // ORPHANED
$string['nopermissiontorate'] = 'アイテムの評価はできません!'; // ORPHANED
$string['nopermissiontoshow'] = '閲覧するパーミッションがありません!'; // ORPHANED
$string['nopermissiontounlock'] = 'ロック解除するパーミッションはありません!'; // ORPHANED
$string['nopermissiontoviewgrades'] = '評定を表示できません。'; // ORPHANED
$string['nopermissiontoviewletergrade'] = '評定文字を閲覧するパーミッションがありません。'; // ORPHANED
$string['nopermissiontoviewpage'] = 'あなたはこのページを閲覧できません。'; // ORPHANED
$string['nosite'] = 'トップレベルのコースが見つかりませんでした!'; // ORPHANED
$string['nositeid'] = 'サイトIDがありません。'; // ORPHANED
$string['notallowedtoupdateprefremotely'] = 'あなたはこのユーザのプリファレンスをリモートで更新することを許可されていません。'; // ORPHANED
$string['notlocalisederrormessage'] = '$a'; // ORPHANED
$string['notmemberofgroup'] = 'あなたはこのコースグループのメンバーではありません。'; // ORPHANED
$string['notownerofkey'] = 'あなたはこのキーのオーナーではありません。'; // ORPHANED
$string['nousers'] = 'そのようなユーザは登録されていません!'; // ORPHANED
$string['orderidnotfound'] = '注文ID $a が見つかりませんでした。'; // ORPHANED
$string['pathdoesnotstartslash'] = '有効な引数が提供されていないか、パスがスラッシュで始まっていません!'; // ORPHANED
$string['prefixcannotbeempty'] = '<p>エラー: データベーステーブル接頭辞に空白は指定できません ($a)</p>
<p>サイト管理者はこの問題を修正してください。</p>'; // ORPHANED
$string['prefixtoolong'] = '<p>エラー: データベーステーブル接頭辞が長すぎます ($a->dbfamily)</p>
<p>サイト管理者はこの問題を修正してください。$a->dbfamily のテーブル接頭辞の最大長は半角 $a->maxlength 文字です。</p>'; // ORPHANED
$string['refoundto'] = '払戻し可能額: $a'; // ORPHANED
$string['refoundtoorigi'] = '注文金額の払戻し: $a'; // ORPHANED
$string['reportnotavailable'] = 'このタイプのレポートはサイトコースのみで利用できます。'; // ORPHANED
$string['restrictedcontextexception'] = '申し訳ございません、外部関数の実行により、コンテクストの制限に違反します。'; // ORPHANED
$string['reverseproxyabused'] = '申し訳ございません、リバースプロクシが有効にされているため、サーバに直接アクセスできません。<br />サーバ管理者にご連絡ください。'; // ORPHANED
$string['rpcerror'] = 'RPC enrol/mnet/available_courses:<br /> ($a)'; // ORPHANED
$string['secretalreadyused'] = 'パスワード変更の確認リンクはすでに使用されています。パスワードは変更されませんでした。'; // ORPHANED
$string['sectionnotexist'] = 'このセクションはありません。'; // ORPHANED
$string['sessioncookiesdisable'] = 'require_key_login() の使用が正しくありません - セッションクッキーは無効にしてください!'; // ORPHANED
$string['sessiondiskfull'] = 'セッションパーティションがフルになっています。現在、ログインすることはできません。<br /><br />サーバ管理者に連絡してください。'; // ORPHANED
$string['sessionipnomatch2'] = '申し訳ございません、あなたのIPアドレスは最初のログインから変更されているようです。このセキュリティ機能はあなたがサイトにログインしている間、クラッカーから個人情報を盗むことを防いでいます。あなたがワイヤレスネットワークまたは異なるネットワーク間のローミングを使用している場合、このエラーが表示されます。詳細はサイト管理者にお問合せください。<br /><br />続ける場合、このページをリフレッシュするため、F5キーを押してください。'; // ORPHANED
$string['sessionnotwritable'] = 'セッションディレクトリに書き込み権の問題が見つかりました。<br /><br />サーバ管理者にご連絡ください。'; // ORPHANED
$string['shortnametaken'] = '省略名がすでに別のコースで使用されています。'; // ORPHANED
$string['spellcheckernotconf'] = 'スペルチェッカが設定されていません。'; // ORPHANED
$string['sslonlyaccess'] = '申し訳ございません、セキュリティ上の理由から、httpsアクセスのみ許可されています。'; // ORPHANED
$string['statsdisable'] = '統計が有効にされていません。'; // ORPHANED
$string['statsnodata'] = 'このコースおよび期間の組み合わせデータはありません。'; // ORPHANED
$string['storedfilecannotcreatefiledirs'] = 'ローカルファイルの保存ディレクトリを作成できません。datarootのパーミッションを確認してください。'; // ORPHANED
$string['storedfilecannotread'] = 'ファイルを読み込めません。ファイルが存在しないか、パーミッションに問題があります。'; // ORPHANED
$string['storedfilenotcreated'] = 'ファイル「 $a->contextid/$a->filearea/$a->itemid/$a->filepath/$a->filename 」を作成できません。'; // ORPHANED
$string['storedfileproblem'] = 'ローカルファイル ($a) に関して、不明な例外が発生しました。'; // ORPHANED
$string['tagdisabled'] = 'タグが無効にされています!'; // ORPHANED
$string['targetdatabasenotempty'] = 'ターゲットデータベースが空ではありません。安全上の理由から、転送は中止されました。'; // ORPHANED
$string['themenotinstall'] = 'このテーマはインストールされていません。'; // ORPHANED
$string['transactionvoid'] = 'すでに取り消されているため、トランザクションを取り消すことはできません。'; // ORPHANED
$string['unenrolerror'] = 'ユーザの登録抹消中にエラーが発生しました。'; // ORPHANED
$string['unknowaction'] = '不明な処理です!'; // ORPHANED
$string['unknowcategory'] = '不明なカテゴリです!'; // ORPHANED
$string['unknowcontext'] = 'get_child_contextsで不明なコンテクスト ($a) です!'; // ORPHANED
$string['unknowformat'] = '不明なフォーマット「 $a 」です。'; // ORPHANED
$string['unknownblockregion'] = 'このページにはブロック要素「 $a 」が認識されません。'; // ORPHANED
$string['unknowncontext'] = 'これは不明なコンテクストです。'; // ORPHANED
$string['unknownfiletype'] = '不明なファイルタイプです。'; // ORPHANED
$string['unknownhelp'] = '不明なヘルプトピック「 $a 」です。'; // ORPHANED
$string['unknownjsinrequirejs'] = 'JSライブラリ「 $a 」が見つかりません。'; // ORPHANED
$string['unknownmodulename'] = 'フォームに対する不明なモジュール名です。'; // ORPHANED
$string['unknownsortcolumn'] = '不明なソートカラム「 $a 」です。'; // ORPHANED
$string['unknownuserselector'] = '不明なユーザセレクタです。'; // ORPHANED
$string['unknoworder'] = '不明な順序付けです。'; // ORPHANED
$string['unknowparamtype'] = '不明なパラメータタイプ「 $a 」です。'; // ORPHANED
$string['unknowquestiontype'] = 'サポートされていない問題タイプ「 $a 」です。'; // ORPHANED
$string['unknowuploadaction'] = '不明なアップロード処理「 $a 」です。'; // ORPHANED
$string['unspecifycourseid'] = 'コースID、省略名またはIDナンバーを指定してください。'; // ORPHANED
$string['unsupportedevent'] = 'サポートされていないイベントタイプです。'; // ORPHANED
$string['unsupportedstate'] = 'サポートされていない完了状況です。'; // ORPHANED
$string['unsupportedwebserver'] = '申し訳ございません、ウェブサーバソフトウェア ($a) はサポートされていません。'; // ORPHANED
$string['upgraderequires19'] = 'エラー: このサーバに新しいMoodleバージョンがインストールされました。残念ですが、前のバージョンからのアップグレードがサポートされていません。<br />最初に、最新の1.9.xリリースにアップグレードしてください。オリジナルファイルを再インストールすることで、あなたは元のバージョンに戻ることができます。'; // ORPHANED
$string['upgraderunning'] = 'サイトはアップグレード中です。後ほどお試しください。'; // ORPHANED
$string['urlnotdefinerss'] = 'RSSフィードのURIが定義されていません。'; // ORPHANED
$string['usermustbemnet'] = 'MNETアクセスコントロールリストのユーザにはリモートMNETのユーザを使用してください。'; // ORPHANED
$string['usernotincourse'] = 'このユーザはこのコースに受講登録されていません!'; // ORPHANED
$string['userselectortoomany'] = 'multiselectがfalseにもかかわらず、user_selectorが1名以上のユーザを選択しています。'; // ORPHANED
$string['wrongcall'] = 'このスクリプトは正常にコールされていません。'; // ORPHANED
$string['wrongcontextid'] = 'コンテクストIDが正しくありません (見つけることができません)。'; // ORPHANED
$string['wrongroleid'] = 'ロールIDが正しくありません!'; // ORPHANED
$string['wrongusernamepassword'] = 'ユーザID/パスワードが正しくありません。'; // ORPHANED
$string['wscouldnotcreateecoursenopermission'] = 'WS - コースを作成できませんでした - パーミッションがありません。'; // ORPHANED
$string['wwwrootmismatch'] = '申し訳ございません、不正なアクセスが検知されたため、「 $a 」アドレスからのみサーバにアクセスできます。<br />サーバ管理者にご連絡くください。'; // ORPHANED
$string['wwwrootslash'] = 'config.phpに正しくない \$CFG->wwwroot が検知されました。\$CFG->wwwrootでは末尾にスラッシュを付ける必要があります。<br />サーバ管理者にご連絡くください。'; // ORPHANED
$string['xmldberror'] = 'XMLDBエラー!'; // ORPHANED
$string['younotteacher'] = 'あなたは教師ではありません!'; // ORPHANED
$string['cannotfindsite'] = 'サイトレベルのコースが見つかりません。'; // ORPHANED
$string['wscouldnotcreateeusernopermission'] = 'WS - ユーザを作成できませんでした - パーミッションがありません。'; // ORPHANED
$string['wscouldnotdeletenoexistinguser'] = 'WS - ユーザを削除できませんでした - ユーザが登録されていません。'; // ORPHANED
$string['wscouldnotdeleteusernopermission'] = 'WS - ユーザを削除できませんでした - パーミッションがありません。'; // ORPHANED
$string['wscouldnotupdatenoexistinguser'] = 'WS - ユーザを更新できませんでした - ユーザが登録されていません。'; // ORPHANED
$string['wscouldnotupdateuserindb'] = 'WS - ユーザを更新できませんでした。'; // ORPHANED
$string['wscouldnotupdateusernopermission'] = 'WS - ユーザを更新できませんでした - パーミッションがありません。'; // ORPHANED
$string['wscouldnotvieweusernopermission'] = 'WS - ユーザを閲覧できませんでした - パーミッションがありません。'; // ORPHANED
$string['wsdescriptionserviceisempty'] = 'ウェブサービス検索処理中にエラーが発生しました: 「 <b>$a->classname</b> 」クラスの「<b>$a->functionname()</b>」関数が、記述内容に「サービス」を指定していません。'; // ORPHANED
$string['wsdoesntextendbaseclass'] = 'ウェブサービス検索処理中にエラーが発生しました: 「 <b>$a</b> 」クラスが、moodle_externalクラスから拡張されていません。'; // ORPHANED
$string['usernotcreated'] = 'ユーザを作成できませんでした。'; // ORPHANED
$string['wscouldnotcreateeuserindb'] = 'WS - ユーザを作成できませんでした。'; // ORPHANED
$string['cannotaddmembergroupiddoesntexist'] = 'メンバーをグループに追加できません。グループIDが存在しません。'; // ORPHANED
$string['coursedoesntexistcannotcreategroup'] = 'グループを作成できません: コースが存在しません。'; // ORPHANED
$string['groupiddoesntexistcannotdelete'] = 'グループを削除できません。グループIDが存在しません。'; // ORPHANED
$string['useriddoesntexist'] = 'ユーザIDが存在しません。'; // ORPHANED
$string['userisnotaparticipant'] = 'このユーザはコース参加者ではありません。'; // ORPHANED
$string['wscouldnotaddgroupmembernopermission'] = 'WS - グループメンバーを追加できませんでした - パーミッションがありません。'; // ORPHANED
$string['wscouldnotcreategroupnopermission'] = 'WS - グループを作成できませんでした - パーミッションがありません。'; // ORPHANED
$string['wscouldnotdeletegroupnopermission'] = 'WS - グループを削除できませんでした - パーミッションがありません。'; // ORPHANED
$string['wscouldnotgetgroupnopermission'] = 'WS - グループを取得できませんでした - パーミッションがありません。'; // ORPHANED
$string['wscouldnotremovegroupmembernopermission'] = 'WS - グループメンバーを削除できませんでした - パーミッションがありません。'; // ORPHANED
$string['cannotaddblock'] = '$a ブロックをブロックリストに追加できませんでした!'; // ORPHANED
$string['cannotaddcmtosection'] = 'セクションに新しいコースモジュールを追加できませんでした。'; // ORPHANED
$string['cannotaddnewinstance'] = '$a の新しいインスタンスを追加できませんでした。'; // ORPHANED
$string['cannotcreatedefaultcat'] = 'コンテクスト $a のデフォルトカテゴリ作成中にエラーが発生しました。'; // ORPHANED
$string['cannotcreatefield'] = '新しいフィールドの作成中にエラーが発生しました。'; // ORPHANED
$string['cannotcreateuser'] = 'ユーザレコードの作成中にエラーが発生しました。'; // ORPHANED
$string['cannotdeletecap'] = '廃止予定のケイパビリティ $a を削除できませんでした。'; // ORPHANED
$string['cannotdeletecate'] = 'カテゴリの削除中にエラーが発生しました。'; // ORPHANED
$string['cannotinsertkey'] = '新しいキーを追加できません。'; // ORPHANED
$string['cannotsetupcategory'] = '重大なエラー! デフォルトのコースカテゴリを作成できませんでした!'; // ORPHANED
$string['cannotupdatecm'] = 'コースモジュールを正しいセクションに更新できませんでした。'; // ORPHANED
$string['cannotupdatecustomprofile'] = 'ユーザカスタムレコードの更新中にエラーが発生しました。'; // ORPHANED
$string['cannotupdategroup'] = 'グループの更新中にエラーが発生しました。'; // ORPHANED
$string['cannotupdatemodcap'] = '$a のケイパビリティを更新できませんでした!'; // ORPHANED
$string['cannotupdateplugincap'] = '$a のケイパビリティを更新できませんでした!'; // ORPHANED
$string['cannotupdaterate'] = '古い評価 ($a->id = $a->rating) を更新できませんでした。'; // ORPHANED
$string['cannotupdaterole'] = 'ロールを更新できません!'; // ORPHANED
$string['cannotupdatesecret'] = 'ユーザのシークレットストリングのリセット中にエラーが発生しました。'; // ORPHANED
$string['cannotupdatesubcate'] = '子カテゴリを更新できませんでした!'; // ORPHANED
$string['cannotupdateuser'] = 'ユーザの更新に失敗しました。'; // ORPHANED
$string['updatersserror'] = 'ID $a のRSSフィードの更新中にエラーが発生しました。'; // ORPHANED
$string['cannotinsertcategory'] = '不明なエラー: カテゴリが追加されませんでした。'; // ORPHANED
$string['cannotinsertcomment'] = '新しいコメントを追加できませんでした。'; // ORPHANED
$string['cannotsaveconfig'] = 'プラグイン「 $a->plugin 」の設定「 $a->name 」を「 $a->value 」として保存中に問題が発生しました。'; // ORPHANED
$string['cannotupdatecategory'] = 'カテゴリ ($a) を更新できませんでした。'; // ORPHANED
$string['cannotupdatecomment'] = 'コメントを更新できませんでした。'; // ORPHANED
$string['cannotupdatecoursemodule'] = 'コースモジュールを更新できませんでした。'; // ORPHANED
$string['cannotupdatefield'] = 'フィールドの更新中にエラーが発生しました。'; // ORPHANED
$string['cannotupdatelevel'] = 'コースモジュールのインデントレベルを更新できませんでした。'; // ORPHANED
$string['cannotupdatesummary'] = '要約を更新できませんでした!'; // ORPHANED
$string['cannotupgradeblock'] = 'ブロックシステムのアップグレードに失敗しました! (configテーブルのバージョンを更新できませんでした)'; // ORPHANED
$string['cannotupgradecaps'] = 'ロールシステムのコアケイパビリティのアップグレード中に問題が発生しました。'; // ORPHANED
$string['cannotsetupsite'] = '重大なエラー! サイトをセットアップできませんでした!'; // ORPHANED
$string['cannotupdateblock'] = 'ブロックテーブルのブロック $a レコードを更新できませんでした!'; // ORPHANED
$string['nopermissiontoupdateblock'] = '$a を更新するパーミッションがありません!'; // ORPHANED
$string['upgradefail'] = 'アップグレードに失敗しました! $a'; // ORPHANED
$string['upgradeversionfail'] = 'バックアップシステムのアップグレードに失敗しました! (configテーブルのバージョンを更新できませんでした。)'; // ORPHANED
$string['cannofindgradeitem'] = '評定項目が見つかりません。'; // ORPHANED
$string['typenotimplement'] = 'TODO: タイプが実装されていません。'; // ORPHANED
$string['copiedcmnotexist'] = 'コピーされたコースモジュールがありません!'; // ORPHANED
$string['cannotinitpage'] = 'ページを迅速に初期化できません、コースID: $a'; // ORPHANED
$string['cannotmovezip'] = 'ZIPファイルを移動できません。'; // ORPHANED

?>
