<?PHP // $Id$ 
      // message.php - created with Moodle 1.8 dev (2007010404)


$string['addcontact'] = 'コンタクトリストに追加する';
$string['addsomecontacts'] = '誰かにメッセージを送信する場合や、このページにショートカットを作成する場合、上にある<a href=\"$a\">検索タブ</a>を使用してください。';
$string['addsomecontactsincoming'] = 'これらのメッセージは、あなたのコンタクトリストに登録されていない人から受信しています。コンタクトに人を追加したい場合、名前の隣にある「コンタクトリストに追加」アイコンをクリックしてください。';
$string['ago'] = '$a 前';
$string['allmine'] = 'すべての送受信メッセージ';
$string['allstudents'] = 'コースの学生間のすべてのメッセージ';
$string['allusers'] = 'すべてのユーザのすべてのメッセージ';
$string['backupmessageshelp'] = '「Yes」にした場合、自動バックアップにインスタントメッセージが含まれます。';
$string['beepnewmessage'] = 'メッセージが届いたら音を鳴らす。';
$string['blockcontact'] = '受信拒否';
$string['blockedmessages'] = '拒否ユーザの $a 件のto/fromメッセージ';
$string['blocknoncontacts'] = 'コンタクトリストに登録されていないユーザから送信されるすべてのメッセージを拒否する。';
$string['contactlistempty'] = 'あなたのコンタクトリストは空です。';
$string['contacts'] = 'コンタクト';
$string['context'] = 'コンテクスト';
$string['deletemessagesdays'] = '古いメッセージを自動削除する経過日数';
$string['discussion'] = 'ディスカッション';
$string['emailmessages'] = 'オフライン時は下記メールアドレス宛にメッセージを転送する。';
$string['emailtagline'] = 'このメールは $a にあなた宛に送信されたメッセージのコピーです。';
$string['emptysearchstring'] = 'キーワードを入力してください。';
$string['formorethan'] = '経過後';
$string['includeblockedusers'] = '拒否したユーザも含む';
$string['incomingcontacts'] = '受信したコンタクト ($a)';
$string['keywords'] = 'キーワード';
$string['keywordssearchresults'] = '検索結果: $a 件のメッセージが見つかりました。';
$string['maxmessages'] = 'ディスカッション履歴に表示する最大メッセージ数';
$string['message'] = 'メッセージ';
$string['messagehistory'] = 'メッセージ履歴';
$string['messages'] = 'メッセージ';
$string['messaging'] = 'メッセージ';
$string['mycontacts'] = 'マイ コンタクト';
$string['newonlymsg'] = '新しいメッセージのみ表示する';
$string['newsearch'] = '新しい検索';
$string['noframesjs'] = 'フレームおよびJavaスクリプトなしのバージョン';
$string['nomessages'] = '未読メッセージはありません。';
$string['nomessagesfound'] = 'メッセージが見つかりませんでした。';
$string['nosearchresults'] = '該当データが見つかりませんでした。';
$string['offline'] = 'オフライン';
$string['offlinecontacts'] = 'オフライン中のコンタクト ($a)';
$string['online'] = 'オンライン';
$string['onlinecontacts'] = 'オンライン中のコンタクト ($a)';
$string['onlyfromme'] = '送信済みメッセージ';
$string['onlymycourses'] = 'マイ コース内のみ';
$string['onlytome'] = '受信メッセージ';
$string['pagerefreshes'] = 'このページは $a 秒ごとに自動更新されます。';
$string['readmessages'] = '既読メッセージ $a';
$string['removecontact'] = 'コンタクトリストから削除する';
$string['savemysettings'] = '私の設定を保存する';
$string['search'] = '検索';
$string['searchforperson'] = '人の検索';
$string['searchmessages'] = 'メッセージの検索';
$string['sendmessage'] = 'メッセージを送信する';
$string['sendmessageto'] = '$a にメッセージを送信する';
$string['settings'] = '設定';
$string['settingssaved'] = '設定が保存されました。';
$string['showmessagewindow'] = 'メッセージが届いたら自動的にウィンドウを表示する。 (ブラウザのポップアップブロックを解除してください)';
$string['strftimedaydatetime'] = '%%Y/%%m/%%d (%%a) %%I:%%M %%p';
$string['timenosee'] = 'オンライン表示期間 (分)';
$string['timesent'] = '送信回数';
$string['unblockcontact'] = 'コンタクトの拒否解除';
$string['unreadmessages'] = '未読メッセージ $a 件';
$string['userisblockingyou'] = 'このユーザはメッセージの送信を禁止されています。';
$string['userisblockingyounoncontact'] = 'このユーザはコンタクトリストに登録されたユーザからのみメッセージを受信します。あなたは現在コンタクトリストに登録されていません。';
$string['userssearchresults'] = '検索結果: $a 名のユーザが見つかりました。';

?>
