<?PHP // $Id$ 
      // questionnaire.php - created with Moodle 1.8 Beta (2007020200)


$string['alreadyfilled'] = 'あなたは、$a すでにこのアンケートに回答しています。ありがとうございます。';
$string['modulename'] = 'アンケート';
$string['modulenameplural'] = 'アンケート';
$string['mustcomplete'] = '<b>アンケート結果を保存するためには<i>今</i>このアンケートを完了させる必要があります。別の機会に回答することはできません。</b><br /><br />';
$string['notavail'] = 'この質問はまだ利用できません。後でお試しください。';
$string['qmanage'] = 'アンケートの管理';
$string['qmanagetitle'] = 'Survey Management phpESP';
$string['qtype'] = 'アンケート回答タイプ';
$string['questionnaireid'] = 'アンケートコンテンツ';
$string['respondenttype'] = '回答者タイプ';
$string['addaline'] = '答えの行を追加する'; // ORPHANED
$string['additionalinfo'] = '補足情報'; // ORPHANED
$string['addsectionbreak'] = 'セクションブレークを追加する'; // ORPHANED
$string['all'] = 'すべて'; // ORPHANED
$string['anonymous'] = '匿名'; // ORPHANED
$string['average'] = '平均'; // ORPHANED
$string['averagerank'] = '平均ランク'; // ORPHANED
$string['bodytext'] = '本文'; // ORPHANED
$string['cancelandreturn'] = 'キャンセル & 戻る'; // ORPHANED
$string['changeorder'] = 'リストから順番を選択して、問題が表示される順番を変更してください。'; // ORPHANED
$string['closed'] = 'アンケートは、$a に終了しました。ありがとうございます。'; // ORPHANED
$string['closedate'] = '終了日を使用する'; // ORPHANED
$string['confirmationpage'] = '確認ページ'; // ORPHANED
$string['confpagedesc'] = 'ユーザがこの調査を完了した後、「確認」ページで表示される表題 (太字) および本文です。(URLが入力されている場合、確認テキストに優先します。)'; // ORPHANED
$string['createcontent'] = '新しいコンテンツの定義'; // ORPHANED
$string['createnew'] = '新しいアンケートを作成する'; // ORPHANED
$string['crosstabulate'] = 'クロス集計'; // ORPHANED
$string['crosstabulation'] = 'クロス集計'; // ORPHANED
$string['edit'] = '編集'; // ORPHANED
$string['editfield'] = 'このフィールドを編集するか、あなたが編集したいフィールド番号をクリックしてください。'; // ORPHANED
$string['email'] = 'Eメール'; // ORPHANED
$string['errnewname'] = '申し訳ございません、このアンケート名はすでに使用されています。新しいアンケート名を入力してください。'; // ORPHANED
$string['errquestionchange'] = '申し訳ございません、これらのタイプ間で質問を変更することはできません。代わりに新しい質問を作成してください。'; // ORPHANED
$string['errquestionoption'] = '申し訳ございません、この質問タイプには少なくとも1つの回答オプションが必要です。'; // ORPHANED
$string['errquestiontext'] = 'この質問のテキストを入力してください。'; // ORPHANED
$string['errquestiontype'] = '申し訳ございません、この質問のタイプを選択してください。'; // ORPHANED
$string['errrequiredfields'] = '申し訳ございません、続行する前に、アンケート名、オーナー、およびタイトルを入力してください。'; // ORPHANED
$string['field'] = 'フィールド $a'; // ORPHANED
$string['fieldname'] = 'フィールド名'; // ORPHANED
$string['generalpage'] = 'このタブの情報は、調査全体に適用されます。このページの必要事項を入力し、個々のフィールドを編集するには、<b>Edit Questions</b>に移動してください。'; // ORPHANED
$string['headingtext'] = '表題'; // ORPHANED
$string['id'] = 'ID'; // ORPHANED
$string['inuse'] = '使用中'; // ORPHANED
$string['length'] = '長さ'; // ORPHANED
$string['missingquestions'] = 'あなたは次の必須回答質問に回答していません。'; // ORPHANED
$string['myresponsedated'] = 'あなたの回答日: $a'; // ORPHANED
$string['myresponses'] = 'あなたのすべての回答'; // ORPHANED
$string['myresponsetitle'] = 'あなたの回答内容 $a 件'; // ORPHANED
$string['myresults'] = 'マイ リザルト'; // ORPHANED
$string['name'] = 'アンケート名'; // ORPHANED
$string['navigateirs'] = '個別の回答内容'; // ORPHANED
$string['newfield'] = 'フィールドの保存/追加'; // ORPHANED
$string['next'] = '次へ'; // ORPHANED
$string['nextpage'] = '次のページ'; // ORPHANED
$string['noneinuse'] = '現在、定義されているコンテンツはありません。'; // ORPHANED
$string['noresponsedata'] = 'この質問には回答はありません。'; // ORPHANED
$string['noresponses'] = '回答なし'; // ORPHANED
$string['noteligible'] = 'あなたはこのアンケートに回答できません。'; // ORPHANED
$string['notopen'] = 'このアンケートは、$a まで開始されません。'; // ORPHANED
$string['notused'] = '未使用'; // ORPHANED
$string['num'] = '#'; // ORPHANED
$string['of'] = '/'; // ORPHANED
$string['opendate'] = '開始日を使用する'; // ORPHANED
$string['owner'] = 'オーナー'; // ORPHANED
$string['page'] = 'ページ'; // ORPHANED
$string['pageof'] = 'ページ $a->page / $a->totpages'; // ORPHANED
$string['possibleanswers'] = '可能性のある答えを入力してください (妥当な場合)。<tt>!その他</tt>のように、答えの前に「!」をつけることで、書き込むための空欄が、答えの後に追加されます。空白行は、削除されます。'; // ORPHANED
$string['precision'] = '精度'; // ORPHANED
$string['preview'] = 'このプレビューでは、アンケートがどのように見えるか表示しています。プレビューでは、アンケートナビゲーションボタンは動作しません。別のセクションを表示するには、セクション番号ボタンを使用してください。どのようなアクセスが割り当てられるかにより、いくつかのナビゲーションボタンが表示されない場合もあります。アンケートは、ドキュメントに埋め込まれる背景色を使用します。プレビューを完了した場合、このページ下部の「<b>ウィンドウを閉じる</b>」ボタンをクリックしてください。'; // ORPHANED
$string['previous'] = '前へ'; // ORPHANED
$string['previouspage'] = '前のページ'; // ORPHANED
$string['private'] = 'プライベート'; // ORPHANED
$string['public'] = 'パブリック'; // ORPHANED
$string['qtypedaily'] = '毎日回答'; // ORPHANED
$string['qtypemonthly'] = '毎月回答'; // ORPHANED
$string['qtypeonce'] = '1回のみ回答'; // ORPHANED
$string['qtypeunlimited'] = '何回でも回答'; // ORPHANED
$string['qtypeweekly'] = '毎週回答'; // ORPHANED
$string['questiontypes'] = '質問タイプ'; // ORPHANED
$string['rank'] = 'ランク'; // ORPHANED
$string['realm'] = 'アンケートタイプ'; // ORPHANED
$string['redirecturl'] = 'この調査完了後、ユーザがリダイレクトされるURLです。<br /><b>または</b><br />'; // ORPHANED
$string['remove'] = '削除'; // ORPHANED
$string['required'] = '必須'; // ORPHANED
$string['requiredquestions'] = '$a マークの質問は、必須回答です。'; // ORPHANED
$string['reset'] = 'リセット'; // ORPHANED
$string['respondent'] = '回答者'; // ORPHANED
$string['respondentabrev'] = '回答者'; // ORPHANED
$string['respondenteligible'] = 'アンケート対象'; // ORPHANED
$string['respondenteligibleall'] = 'すべて'; // ORPHANED
$string['respondenteligiblestudents'] = '学生のみ'; // ORPHANED
$string['respondenteligibleteachers'] = '教師のみ'; // ORPHANED
$string['respondents'] = '回答者'; // ORPHANED
$string['respondenttypeanonymous'] = '匿名'; // ORPHANED
$string['respondenttypefullname'] = 'フルネーム'; // ORPHANED
$string['response'] = '回答'; // ORPHANED
$string['responseview'] = '回答の表示'; // ORPHANED
$string['responseviewstudents'] = '教師および学生'; // ORPHANED
$string['responseviewteachers'] = '教師のみ'; // ORPHANED
$string['resume'] = '答えの保存/再開'; // ORPHANED
$string['resumesurvey'] = '調査の再開'; // ORPHANED
$string['return'] = '戻る'; // ORPHANED
$string['save'] = '保存する'; // ORPHANED
$string['savedprogress'] = 'あなたの回答内容は、保存されました。いつでも戻って、このアンケートを完了することができます。そのようにするには、下記のリンクをブックマークしてください。アンケートを完了するため、ユーザ名およびパスワードの入力を求められます。'; // ORPHANED
$string['section'] = 'セクション'; // ORPHANED
$string['sectionbreak'] = '----- セクションブレーク -----'; // ORPHANED
$string['selectexisting'] = 'または既存のアンケートを選択する'; // ORPHANED
$string['selecttheme'] = 'この調査で使用するテーマ (CSS) を選択してください。'; // ORPHANED
$string['sendemail'] = '各送信内容のコピーを送信するアドレスです (メールバックアップ不要の場合、空白)。'; // ORPHANED
$string['submitsurvey'] = 'アンケートを送信する'; // ORPHANED
$string['subtitle'] = 'サブタイトル'; // ORPHANED
$string['summary'] = '要約'; // ORPHANED
$string['surveyfilename'] = 'アンケートファイル名です。このファイル名は、以降このアンケートへのアクセスに使用されます。 (スペースなし、半角英数字のみ)'; // ORPHANED
$string['surveyinfo'] = 'この調査のすべてのフィールドの前に表示されるテキストです。(例 インストラクション、バックグラウンド情報等)'; // ORPHANED
$string['surveyresponse'] = 'アンケート回答'; // ORPHANED
$string['surveysubtitle'] = 'この調査のサブタイトルです。タイトルの下に表示されます。(入力自由、スペース含む)'; // ORPHANED
$string['surveytitle'] = 'この調査のタイトルです。このタイトルは調査すべてのページのトップに表示されます。(入力自由、スペース含む)'; // ORPHANED
$string['template'] = 'テンプレート'; // ORPHANED
$string['templatenotviewable'] = '調査テンプレートを表示できません。'; // ORPHANED
$string['theme'] = 'テーマ'; // ORPHANED
$string['thismonth'] = '今月'; // ORPHANED
$string['thisweek'] = '今週'; // ORPHANED
$string['title'] = 'タイトル'; // ORPHANED
$string['today'] = '本日'; // ORPHANED
$string['total'] = '合計'; // ORPHANED
$string['type'] = 'タイプ'; // ORPHANED
$string['unknown'] = 'Unknown'; // ORPHANED
$string['url'] = 'URL'; // ORPHANED
$string['usepublic'] = 'パブリックを使用する'; // ORPHANED
$string['usetemplate'] = '既存のアンケートをコピーする'; // ORPHANED
$string['usingsurvey'] = '$a を使用中'; // ORPHANED
$string['viewresponses'] = 'すべての回答 ($a 件) を表示する'; // ORPHANED
$string['viewyourresponses'] = 'あなたの回答 ($a 件) を表示する'; // ORPHANED

?>
