<?PHP // $Id$ 
      // auth.php - created with Moodle 1.6.1 (2006050510)


$string['alternatelogin'] = 'Om Du skriver in en URL h&auml;r s&aring; kommer den att anv&auml;ndas som sida f&ouml;r inloggning p&aring; den h&auml;r webbplatsen. Sidan b&ouml;r inneh&aring;lla ett formul&auml;r som har egenskapen f&ouml;r h&auml;ndelse inst&auml;lld till <strong>\'$a\'</strong><br />Var f&ouml;rsiktig s&aring; att Du inte skriver in en felaktig URL eftersom Du d&aring; kan st&auml;nga Dig sj&auml;lv ute fr&aring;n webbplatsen. <br />L&aring;t den h&auml;r inst&auml;llningen vara tom om Du vill anv&auml;nda standardsidan f&ouml;r inloggning.';
$string['alternateloginurl'] = 'Alternativ URL f&ouml;r inloggning';
$string['auth_cas_baseuri'] = 'Serverns URI (ingenting om det inte &auml;r en baseURI)<br />IF t.ex. CAS-servern svarar mot
v&auml;rd.dom&auml;n.se/CAS/ THEN <br />cas_baseuri=CAS/';
$string['auth_cas_create_user'] = 'Aktivera detta om Du vill l&auml;gga in CAS-auktoriserade anv&auml;ndare i Moodles databas. Om inte som kommer bara anv&auml;ndare som redan finns i Moodles databas att kunna logga in.';
$string['auth_cas_enabled'] = 'Aktivera detta om Du vill anv&auml;nda autenticering med CAS.';
$string['auth_cas_hostname'] = 'V&auml;rdnamn f&ouml;r CAS-server<br />t.ex. v&auml;rd.dom&auml;n.se';
$string['auth_cas_invalidcaslogin'] = 'Din inloggning misslyckades tyv&auml;rr - Dina r&auml;ttigheter kunde inte bekr&auml;ftas';
$string['auth_cas_language'] = 'Valt spr&aring;k';
$string['auth_cas_logincas'] = 'Tilltr&auml;de via en s&auml;ker uppkoppling';
$string['auth_cas_port'] = 'CAS-serverns port';
$string['auth_cas_server_settings'] = 'Konfiguration av CAS-server';
$string['auth_cas_text'] = 'S&auml;ker uppkoppling';
$string['auth_cas_version'] = 'CAS version';
$string['auth_casdescription'] = 'Den h&auml;r metode anv&auml;nder en CAS-server (Central Authentication Service)f&ouml;r att autentisera anv&auml;ndare i en Single Sign On environment (SSO). Du kan ocks&aring; anv&auml;nda enkel LDAP autentisering. Om ett viss givet annv&auml;ndarnamn och l&ouml;senord &auml;r giltigt enligt CAS s&aring; l&auml;gger Moodle in en ny anv&auml;ndare i sin databas, och h&auml;mtar anv&auml;ndarens egenskaper (attribut) fr&aring;n LDAP om s&aring; kr&auml;vs. Vid n&auml;stf&ouml;ljande inloggningar s&aring; kontrolleras bara anv&auml;ndarnamnet och l&ouml;senordet.';
$string['auth_castitle'] = 'Anv&auml;nd en CAS-server (SSO)';
$string['auth_changepasswordhelp'] = 'Hj&auml;lp ang&aring;ende &auml;ndring av l&ouml;sneord';
$string['auth_changepasswordhelp_expl'] = 'Visa det f&ouml;rlorade l&ouml;senordet f&ouml;r dem som har blivit av sitt $a l&ouml;senord. Det h&auml;r kommer att visas antingen likv&auml;l som eller ist&auml;llet f&ouml;r <strong>Ändra l&ouml;senord URL</strong> eller f&ouml;r Moodle intern &auml;ndring av l&ouml;senord.';
$string['auth_changepasswordurl'] = 'Ändra l&ouml;senord URL';
$string['auth_changepasswordurl_expl'] = 'Ange den url som Du vill skicka till de anv&auml;ndare so m har f&ouml;rlorat sina l&ouml;senord. St&auml;ll in <strong>Anv&auml;nd standardsidan f&ouml;r att &auml;ndra l&ouml;senord</strong> till <strong>Nej</strong>.';
$string['auth_common_settings'] = 'Vanliga inst&auml;llningar';
$string['auth_data_mapping'] = 'Kartor &ouml;ver data';
$string['auth_dbdescription'] = 'Denna metod anv&auml;nder en extern databastabell f&ouml;r att kontrollera huruvida ett givet anv&auml;ndarnamn och l&ouml;senord &auml;r giltigt.  Om kontot &auml;r nytt, s&aring; kan information fr&aring;n andra f&auml;lt ocks&aring; kopieras till Moodle.';
$string['auth_dbextrafields'] = 'Detta f&auml;lt &auml;r valfritt.  Du kan v&auml;lja att p&aring; f&ouml;rhand fylla i n&aring;gra anv&auml;ndarf&auml;lt f&ouml;r Moodle med information fr&aring;n <b>externa databasf&auml;lt</b> som Du kan specificera h&auml;r. <p>Om Du l&auml;mnar dessa f&auml;lt tomma, s&aring; kommer standardv&auml;rden att anv&auml;ndas.</p><p>I vilket fall som helst, kommer anv&auml;ndaren kunna redigera alla dessa f&auml;lt efter det att de loggat in.</p>';
$string['auth_dbfieldpass'] = 'Namn p&aring; det f&auml;lt som inneh&aring;ller l&ouml;senord';
$string['auth_dbfielduser'] = 'Namn p&aring; det f&auml;lt som inneh&aring;ller anv&auml;ndarnamn';
$string['auth_dbhost'] = 'Den dator (v&auml;rd) som anv&auml;nds f&ouml;r databasservern.';
$string['auth_dbname'] = 'Namnet p&aring; sj&auml;lva databasen';
$string['auth_dbpass'] = 'L&ouml;senord som matchar ovanst&aring;ende anv&auml;ndarnamn';
$string['auth_dbpasstype'] = 'Specificera formatet p&aring; det f&auml;lt som l&ouml;senordet ska ligga i. MD-kryptering g&aring;r att anv&auml;nda om Du vill koppla upp Dig mot andra vanliga webbapplikationer som PostNuke.';
$string['auth_dbtable'] = 'Namn p&aring; tabellen i databasen';
$string['auth_dbtitle'] = 'Anv&auml;nd en extern databas';
$string['auth_dbtype'] = 'Databastyp (se <A HREF=../lib/adodb/readme.htm#drivers>ADOdb dokumentation</A> f&ouml;r detaljer)';
$string['auth_dbuser'] = 'Anv&auml;ndarnamn med l&auml;sbeh&ouml;righet till databasen';
$string['auth_emaildescription'] = 'E-postbekr&auml;ftelse &auml;r standardvalet som autenticeringsmetod.  N&auml;r anv&auml;ndaren registrerar sig, v&auml;ljer eget nytt anv&auml;ndarnamn och l&ouml;senord, kommer en bekr&auml;ftelse via e-post s&auml;ndas till anv&auml;ndarens e-postadress.  Detta e-postbrev inneh&aring;ller en s&auml;ker l&auml;nk till en sida d&auml;r anv&auml;ndaren kan bekr&auml;fta sitt konto. Framtida inlogging kontrollerar bara anv&auml;ndarnamn och l&ouml;senord mot de lagrade v&auml;rdena i Moodles databas.';
$string['auth_emailtitle'] = 'E-postbaserad autenticering';
$string['auth_fccreators'] = 'Lista p&aring; grupper vars medlemmar har tillst&aring;nd att skapa nya kurser. Skilj flerfaldiga grupper med \';\'. Namn m&aring;ste stavas exakt som p&aring; FirstClass servern. Systemet &auml;r skiftl&auml;gesk&auml;nsligt.';
$string['auth_fcdescription'] = 'Den h&auml;r metoden anv&auml;nder en FirstClass server f&ouml;r att kontrollera huruvida ett anv&auml;ndarnamn eller ett l&ouml;senord &auml;r giltigt.';
$string['auth_fcfppport'] = 'Serverport (3333 &auml;r den vanligaste)';
$string['auth_fchost'] = 'Adressen till FirstClass-servern. Anv&auml;nd det h&auml;r IP-numret eller DNS-namnet.';
$string['auth_fcpasswd'] = 'L&ouml;senordet f&ouml;r det ovanst&aring;ende kontot';
$string['auth_fctitle'] = 'Anv&auml;nd en FirstClass-server';
$string['auth_fcuserid'] = 'Anv&auml;ndarID f&ouml;r FirstClass-konto med inst&auml;llningen \"Subadministrator\" aktiverad.';
$string['auth_fieldlock'] = 'V&auml;rde f&ouml;r l&aring;sningen';
$string['auth_fieldlock_expl'] = '<p><b>V&auml;rde f&ouml;r l&aring;sningen:</b>Om detta &auml;r aktiverat s&aring; kommer det att hindra anv&auml;ndare och administrat&ouml;rer av Moodle fr&aring;n att redigera detta f&auml;lt direkt. Anv&auml;nd detta f&auml;lt om Du underh&aring;ller dessa data i det externa systemet f&ouml;r autenticering.';
$string['auth_fieldlocks'] = 'L&aring;sning av anv&auml;ndarf&auml;lt';
$string['auth_fieldlocks_help'] = '<p>Du kan l&aring;sa anv&auml;ndarnas dataf&auml;lt. Detta &auml;r anv&auml;ndbart f&ouml;r webbplatser d&auml;r adminstrat&ouml;rerna underh&aring;ller anv&auml;ndardata manuellt genom att redigera anv&auml;ndarposter eller genom att anv&auml;nda komponenten \"Ladda upp anv&auml;ndare\".  Om Du l&aring;ser de f&auml;lt som Moodle kr&auml;ver s&aring; ska Du s&auml;kerst&auml;lla att Du fyller i dessa data n&auml;r Du skapar anv&auml;ndarkonton &emdash; f&ouml;r annars kommer kontona att bli oanv&auml;ndbara.</p><p>Överv&auml;g om Du ska st&auml;lla in l&aring;sningsl&auml;get till \"Inte l&aring;st om f&auml;ltet &auml;r tomt\" f&ouml;r att undvika detta problem.</p>';
$string['auth_imapdescription'] = 'Denna metod anv&auml;nder en IMAP-server f&ouml;r att kontrollera huruvida ett givet anv&auml;ndarnamn och l&ouml;senord &auml;r giltigt.';
$string['auth_imaphost'] = 'IMAP-serverns adress. Anv&auml;nd IP-nummer, inte DNS-namn.';
$string['auth_imapport'] = 'IMAP-serverns portnummer. Vanligtvis &auml;r detta 143 eller 993.';
$string['auth_imaptitle'] = 'Anv&auml;nd en IMAP-server';
$string['auth_imaptype'] = 'IMAP servertyp.  IMAP-servrar kan ha olika typer av autenticeringar och f&ouml;rhandlingar.';
$string['auth_ldap_bind_dn'] = 'Om Du vill bruka \'bind\'-anv&auml;ndare f&ouml;r att s&ouml;ka anv&auml;ndare, s&aring; ska Du specificera det h&auml;r. N&aring;got som \'cn=ldapuser,ou=public,o=org\'';
$string['auth_ldap_bind_pw'] = 'L&ouml;senord f&ouml;r \'bind\'-anv&auml;ndare.';
$string['auth_ldap_bind_settings'] = 'Inst&auml;llningar f&ouml;r \'bind\'';
$string['auth_ldap_contexts'] = 'Lista av kontexter d&auml;r anv&auml;ndarna finns med.  Separera olika kontexter med \';\'.  Till exempel: \'ou=users,o=org; ou=others,o=org\'';
$string['auth_ldap_create_context'] = 'Om Du aktiverar \'Skapa anv&auml;ndare\' med e-postbekr&auml;ftelse s&aring; ska Du specifiera den kontext d&auml;r anv&auml;ndare skapas. Denna kontext b&ouml;r vara en annan &auml;n den vanliga f&ouml;r att undvika s&auml;kerhetsrisker. Du beh&ouml;ver inte l&auml;gga till denna kontext till variabeln \'ldap_context\'. Moodle letar automatiskt efter anv&auml;ndare fr&aring;n den h&auml;r kontexten.';
$string['auth_ldap_creators'] = 'Lista av grupper som har beh&ouml;righet att skapa nya kurser. Skilj p&aring; grupperna med \';\'. Vanligtvis n&aring;got liknande \'ch=utbildare, ou=personal, o=minOrg\'';
$string['auth_ldap_expiration_desc'] = 'V&auml;lj Nej f&ouml;r att avaktivera kontroll av l&ouml;senord som har g&aring;tt ut eller LDAP f&ouml;r att l&auml;sa \'passwordexpiration time\' direkt fr&aring;n LDAP. Kom ih&aring;g att fylla i namnet p&aring; attributet, n&auml;mligen \'ldap_expireattr\'';
$string['auth_ldap_expiration_warning_desc'] = 'Antal dagar innan det skickas en varning om att l&ouml;senordet g&aring;r ut.';
$string['auth_ldap_expireattr_desc'] = 'Det LDAP-attribut som lagrar tiden d&aring; l&ouml;senord g&aring;r ut PasswordExpirationTime';
$string['auth_ldap_graceattr_desc'] = 'LDAP-attributet \'gracelogin\'';
$string['auth_ldap_gracelogins_desc'] = 'Aktivera st&ouml;d f&ouml;r LDAP \'gracelogin\'. N&auml;r tiden f&ouml;r ett l&ouml;senord har g&aring;tt ut s&aring; kan anv&auml;ndaren logga in tills r&auml;knaren f&ouml;r \'gracelogin\' &auml;r 0. Att aktivera denna inst&auml;llning visar ett \'grace login\'-meddelande om l&ouml;senordet har g&aring;tt ut.';
$string['auth_ldap_host_url'] = 'Specificera en LDAP-v&auml;rd i URL-form som \'ldap://ldap.myorg.com/\' eller \'ldaps://ldap.myorg.com/\'';
$string['auth_ldap_login_settings'] = 'Inst&auml;llningar f&ouml;r inloggning';
$string['auth_ldap_memberattribute'] = 'Specificera en medlems egenskaper n&auml;r anv&auml;ndare tillh&ouml;r en grupp. Vanligtvis \'medlem\'';
$string['auth_ldap_objectclass'] = 'Det h&auml;r &auml;r det filter som anv&auml;nds f&ouml;r att namnge/s&ouml;ka efter anv&auml;ndare. Normalt sett s&aring; ska Du st&auml;lla in det till n&aring;gonting i stil med objectClass=posixAccount . Det &auml;r i linje med standarden f&ouml;r objectClass=* som kommer att returnera all aobjekt fr&aring;n LDAP.';
$string['auth_ldap_opt_deref'] = 'Detta avg&ouml;r hur alias hanteras under s&ouml;kning. Markera ett av det f&ouml;ljande v&auml;rdena: \"No\" (LDAP_DEREF_NEVER) eller \"Yes\" (LDAP_DEREF_ALWAYS)';
$string['auth_ldap_passwdexpire_settings'] = 'Inst&auml;llningar f&ouml;r l&ouml;senords giltighetstid enligt LDAP';
$string['auth_ldap_preventpassindb'] = 'Markera \"Ja\" f&ouml;r att f&ouml;rhindra l&ouml;senord fr&aring;n att lagras i Moodles databas.';
$string['auth_ldap_search_sub'] = 'S&auml;tt in ett v&auml;rde <> 0 om Du vill s&ouml;ka anv&auml;ndare fr&aring;n subkontexter.';
$string['auth_ldap_server_settings'] = 'Inst&auml;llningar f&ouml;r LDAP-server';
$string['auth_ldap_update_userinfo'] = 'Uppdatera anv&auml;ndarinformation (f&ouml;rnamn, efternamn, adress..) fr&aring;n LDAP till Moodle.  Se /auth/ldap/attr_mappings.php f&ouml;r mappnings- information';
$string['auth_ldap_user_attribute'] = 'Attributet som anv&auml;nds f&ouml;r namn/s&ouml;kning av anv&auml;ndare.  Vanligtvis \'cn\'.';
$string['auth_ldap_user_settings'] = 'Inst&auml;llningar f&ouml;r  \'sl&aring; upp anv&auml;ndare\'';
$string['auth_ldap_user_type'] = 'V&auml;lj hur anv&auml;ndare ska lagras i LDAP. Den h&auml;r inst&auml;llningen anger hur upph&ouml;rande av login, \'grace\'-login och skapande av anv&auml;ndare ska g&aring; till.';
$string['auth_ldap_version'] = 'Detta &auml;r den version av LDAP-protokollet som Din server anv&auml;nder.';
$string['auth_ldapdescription'] = 'Denna metod ger autenticering mot en extern LDAP-server. Om det givna anv&auml;ndarnamnet och l&ouml;senordet &auml;r giltiga skapar Moodle en plats f&ouml;r en ny anv&auml;ndare i databasen. Denna modul kan l&auml;sa anv&auml;ndarattribut fr&aring;n LDAP och fylla i p&aring; f&ouml;rhand &ouml;nskade f&auml;lt i Moodle. F&ouml;r f&ouml;ljande login &auml;r endast anv&auml;ndarnamn och l&ouml;senord kontrollerade.';
$string['auth_ldapextrafields'] = 'Dessa f&auml;lt &auml;r valfria.  Du kan v&auml;lja att p&aring; f&ouml;rhand fylla i  n&aring;gra anv&auml;ndarf&auml;lt f&ouml;r Moodle med information fr&aring;n <B>LDAP-f&auml;lt</B> som Du kan specificera h&auml;r. <P>Om Du l&auml;mnar dessa f&auml;lt tomma, s&aring; kommer inget att f&ouml;ras &ouml;ver fr&aring;n LDAP och standardv&auml;rden f&ouml;r Moodle kommer att anv&auml;ndas ist&auml;llet.<P>I vilket fall som helst, kommer anv&auml;ndaren kunna redigera alla dessa f&auml;lt efter det att de loggat in.';
$string['auth_ldaptitle'] = 'Anv&auml;nd en LDAP-server';
$string['auth_manualdescription'] = 'Den h&auml;r metoden g&ouml;r det om&ouml;jligt f&ouml;r anv&auml;ndare att skapa sina egna konton. Alla konton m&aring;ste skapas manuellt av administrat&ouml;ren.';
$string['auth_manualtitle'] = 'Endast manuellt skapade konton';
$string['auth_multiplehosts'] = 'Du kan ange flera v&auml;rdar(t ex host1.com;host2.com;host3.com)';
$string['auth_nntpdescription'] = 'Denna metod anv&auml;nder en NNTP-server f&ouml;r att kontrollera huruvida ett givet anv&auml;ndarnamn och l&ouml;senord &auml;r giltiga.';
$string['auth_nntphost'] = 'NNTP-serverns adress.  Anv&auml;nd IP-nummer, inte DNS-namn.';
$string['auth_nntpport'] = 'Serverport (119 &auml;r den vanligaste)';
$string['auth_nntptitle'] = 'Anv&auml;nd en NNTP-server';
$string['auth_nonedescription'] = 'Anv&auml;ndare kan logga in och skapa giltiga konton omedelbart, utan autenticering mot extern server och heller ingen bekr&auml;ftelse via e-post.  Var f&ouml;rsiktig med anv&auml;ndning av detta val - t&auml;nk p&aring; s&auml;kerheten och de administrativa problem som detta kan orsaka.';
$string['auth_nonetitle'] = 'Ingen autenticering';
$string['auth_pamdescription'] = 'Den h&auml;r metoden anv&auml;nder PAM f&ouml;r att f&aring; tillg&aring;ng till \'native\' anv&auml;ndarnamn p&aring; den h&auml;r servern. Du m&aring;ste installera <a href=\"http://www.math.ohio-state.edu/~ccunning/pam_auth/\" target=\"_blank\">PHP4 PAM Authentication</a> f&ouml;r att kunna anv&auml;nda den h&auml;r modulen.';
$string['auth_pamtitle'] = 'PAM (inpluggningsbara moduler f&ouml;r autenticering)';
$string['auth_passwordisexpired'] = 'Ditt l&ouml;senord g&auml;ller inte l&auml;ngre. Vill Du &auml;ndra Ditt l&ouml;senord nu?';
$string['auth_passwordwillexpire'] = 'Ditt l&ouml;senord kommer att upph&ouml;ra att g&auml;lla om $a dagar. Vill Du &auml;ndra Ditt l&ouml;senord nu?';
$string['auth_pop3description'] = 'Denna metod anv&auml;nder en POP3 server f&ouml;r att kontrollera huruvida ett givet anv&auml;ndarnamn och l&ouml;senord &auml;r giltiga.';
$string['auth_pop3host'] = 'POP3-serveradressen. Anv&auml;nd IP-nummer, inte DNS-namn.';
$string['auth_pop3mailbox'] = 'Namn p&aring; den \"brevl&aring;da\" (mailbox) som Du vill f&ouml;rs&ouml;ka skapa en koppling till. (Vanligtvis INBOX)';
$string['auth_pop3port'] = 'Serverport (110 &auml;r den vanligaste)';
$string['auth_pop3title'] = 'Anv&auml;nd en POP3-server';
$string['auth_pop3type'] = 'Servertyp. Om Din server anv&auml;nder certifikat som s&auml;kerhet, v&auml;lj pop3cert.';
$string['auth_radiusdescription'] = 'Den h&auml;r metiden anv&auml;nder en <a href=\"http://en.wikipedia.org/wiki/RADIUS\" target=\"_blank\">RADIUS</a> server f&ouml;r att kontrollera huruvuda ett gívet anv&auml;ndarnamn och l&ouml;senord &auml;r giltiga.';
$string['auth_radiushost'] = 'Adress till RADIUS server';
$string['auth_radiusnasport'] = 'Port att anv&auml;nda f&ouml;r uppkoppling';
$string['auth_radiussecret'] = 'Delad hemlighet';
$string['auth_radiustitle'] = 'Anv&auml;nd en RADIUS server';
$string['auth_shib_convert_data'] = 'API f&ouml;r modifikation av data';
$string['auth_shib_convert_data_description'] = 'Du kan anv&auml;nda denna API f&ouml;r fortsatt modifikation av data som kommer via Shibboleth. L&auml;s <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">README</a> f&ouml;r vidare instruktioner.';
$string['auth_shib_convert_data_warning'] = 'Filen finns inte eller s&aring; kan den inte l&auml;sas av webbserver-processen.';
$string['auth_shib_instructions'] = 'Anv&auml;nd <a href=\"$a\">logga in med Shibboleth</a>
 f&ouml;r att f&aring; tillg&aring;ng via Shibboleth om Din institution st&ouml;djer det.<br />Annars f&aring;r Du anv&auml;nda det vanliga formul&auml;ret(som visas h&auml;r) f&ouml;r att logga in';
$string['auth_shib_instructions_help'] = 'H&auml;r b&ouml;r Du tillhandah&aring;lla instruktioner f&ouml;r hur man anv&auml;nder Shibboleth. Detta kommer att visas p&aring; sektionen f&ouml;r instruktioner p&aring; sidan f&ouml;r att logga in. Detta b&ouml;r inneh&aring;lla en l&auml;nk till \"<b>$a</b>\" s&aring; att Shibboleth-anv&auml;ndare kan logga in p&aring; ett enkelt s&auml;tt. Om Du l&auml;mnar detta tomt s&aring; kommer standardinstruktioner (som inte &auml;r Shibboleth-specifika) att anv&auml;ndas.';
$string['auth_shib_only'] = 'Endast Shibboleth';
$string['auth_shib_only_description'] = 'Markera det h&auml;r alternativet om Du vill aktivera autentisering med Shibboleth.';
$string['auth_shib_username_description'] = 'Namnet p&aring; den webbserver milj&ouml;variabel f&ouml;r Shibboleth som ska anv&auml;ndas som anv&auml;ndarnamn f&ouml;r Moodle.';
$string['auth_shibboleth_login'] = 'Logga in med Shibboleth';
$string['auth_shibboleth_manual_login'] = 'Logga in manuellt';
$string['auth_shibbolethdescription'] = 'Genom att anv&auml;nda den h&auml;r metoden kan Du ansluta till en befintlig Shibboleth server f&ouml;r att kontrollera och skapa nya konton';
$string['auth_shibbolethtitle'] = 'Shibboleth';
$string['auth_updatelocal'] = 'Uppdatera lokala data';
$string['auth_updatelocal_expl'] = '<p><b>Uppdatera lokala data:</b> Om detta &auml;r aktiverat s&aring; kommer f&auml;ltet att uppdateras (fr&aring;n extern autenticering) varje g&aring;ng anv&auml;ndaren loggar in eller n&auml;r det f&ouml;rekommer synkronisering av anv&auml;ndare. F&auml;lt som &auml;r inst&auml;llda att uppdatera lokalt b&ouml;r vara l&aring;sta.</p>';
$string['auth_updateremote'] = 'Uppdatera externa data';
$string['auth_updateremote_expl'] = '<p><b>Uppdatera externa data:</b> Om detta &auml;r aktiverat s&aring; kommer den externa autenticeringen att uppdateras n&auml;r en anv&auml;ndarpost uppdateras. F&auml;lt b&ouml;r vara ol&aring;sta s&aring; att redigering &auml;r till&aring;ten.</p>';
$string['auth_updateremote_ldap'] = '<p><b>OBS!</b> Om Du uppdaterar externa LDAP-data s&aring; m&aring;ste Du st&auml;lla in \'binddn\' och \'bindpw\' till en \'bind-user\' med r&auml;ttigheter att  redigera alla posterna f&ouml;r anv&auml;ndare. F n bevarar detta inte attribut med flerfaldiga v&auml;rden, och det tar bort extra v&auml;rden vid uppdateringar.</p>';
$string['auth_user_create'] = 'Aktivera';
$string['auth_user_creation'] = 'Nya (anonyma) anv&auml;ndare kan utnyttja en extern k&auml;lla f&ouml;r autenticering och skapa anv&auml;ndarkonton som bekr&auml;ftas med e-post. Om Du aktiverar detta f&aring;r Du inte gl&ouml;mma att ocks&aring; konfigurera de modulspecifika valm&ouml;jligheterna som anv&auml;ndare ska kunna skapa.';
$string['auth_usernameexists'] = 'Det valda anv&auml;ndarnamnet finns redan. Du m&aring;ste v&auml;lja ett annat.';
$string['authenticationoptions'] = 'Autenticering tillval';
$string['authinstructions'] = 'H&auml;r kan Du ge instruktioner f&ouml;r Dina anv&auml;ndare, s&aring; att de vet vilket anv&auml;ndarnamn och l&ouml;senord de b&ouml;r anv&auml;nda.  Texten Du skriver in h&auml;r kommer att visas p&aring; loginsidan.  Om Du l&auml;mnar detta tomt s&aring; kommer inga instruktioner att visas.';
$string['changepassword'] = 'Ändra l&ouml;senord URL';
$string['changepasswordhelp'] = 'H&auml;r kan Du specificera en plats d&auml;r Dina anv&auml;ndare kan &aring;terst&auml;lla eller &auml;ndra sina anv&auml;ndarnamn/l&ouml;senord om de har gl&ouml;mt. Detta kommer att visas f&ouml;r anv&auml;ndarna som en knapp p&aring; loginsidan och p&aring; deras anv&auml;ndarsidor. Om Du l&auml;mnar detta tomt kommer inte knappen att visas.';
$string['chooseauthmethod'] = 'V&auml;lj en autentiseringsmetod:';
$string['createpasswordifneeded'] = 'Skapa  ett l&ouml;senord om s&aring; beh&ouml;vs';
$string['forcechangepassword'] = 'Tvinga fram &auml;ndring av l&ouml;senord';
$string['forcechangepassword_help'] = 'Tvinga anv&auml;ndare att byta l&ouml;senord n&auml;sta g&aring;ng de loggar in p&aring; Moodle.';
$string['forcechangepasswordfirst_help'] = 'Tvinga anv&auml;ndare att byta l&ouml;senord f&ouml;rsta g&aring;ngen som de loggar in p&aring; Moodle.';
$string['guestloginbutton'] = 'Knapp f&ouml;r g&auml;stlogin';
$string['infilefield'] = 'Det m&aring;ste finnas ett f&auml;lt i filen';
$string['instructions'] = 'Instruktioner';
$string['internal'] = 'Intern';
$string['locked'] = 'L&aring;st';
$string['md5'] = 'MD5-kryptering';
$string['passwordhandling'] = 'Administration av f&auml;lt f&ouml;r l&ouml;senord';
$string['plaintext'] = 'Ren text';
$string['shib_no_attributes_error'] = 'Du verkar vara autenticerad via Shibboleth men Moodle fick inga data om egenskaper f&ouml;r anv&auml;ndare: Var sn&auml;ll och kontrollera att den som tillhandah&aring;ller Din identitet vidarebefordrar de n&ouml;dv&auml;ndiga egenskaperna ($a) till den som st&aring;r f&ouml;r de tj&auml;nster(Services)som Moodle k&ouml;rs p&aring; eller informera webmaster p&aring; den h&auml;r servern.';
$string['shib_not_all_attributes_error'] = 'Moodle beh&ouml;ver vissa Shibboleth egenskaper som inte f&aring;r att p&aring;tr&auml;ffa f&ouml;r Din Del. Egenskaperna &auml;r:$a<br />Var sn&auml;ll och kontakta webmaster p&aring; den h&auml;r servern eller den som tillhandah&aring;ller de tj&auml;nster som Moodle k&ouml;rs p&aring;.';
$string['shib_not_set_up_error'] = 'Autenticering via Shibboleth verkar inte att fungera  korrekt. Var sn&auml;ll och konsultera <a href=\"README.txt\">README</a> f&ouml;r vidare instruktioner om hur man s&auml;tter upp autenticering via Shibboleth.';
$string['showguestlogin'] = 'Du kan g&ouml;mma eller visa knappen f&ouml;r g&auml;stlogin p&aring; loginsidan.';
$string['stdchangepassword'] = 'Anv&auml;nd standardsidan f&ouml;r \'Ändra l&ouml;senord\'.';
$string['stdchangepassword_expl'] = 'Om det externa systemet f&ouml;r autenticering till&aring;ter &auml;ndring av l&ouml;senord via Moodle s&aring; ska Du &auml;ndra detta till \'Yes\' (Ja). Den h&auml;r inst&auml;llningen har f&ouml;rtr&auml;de &ouml;ver inst&auml;llningen \'Ändra l&ouml;senordets URL\'.';
$string['stdchangepassword_explldap'] = 'OBS! Vi rekommenderar att Du anv&auml;nder LDAP via en SSL-krypterad kanal (ldaps://) om Du anv&auml;nder en fj&auml;rrserver f&ouml;r LDAP.';
$string['unlocked'] = 'Ol&aring;st';
$string['unlockedifempty'] = 'Ol&aring;st om det &auml;r tomt';
$string['update_never'] = 'Aldrig';
$string['update_oncreate'] = 'Vid skapande';
$string['update_onlogin'] = 'Vid varje inloggning';
$string['update_onupdate'] = 'Vid uppdatering';

?>
