<?PHP // $Id$ 
      // group.php - created with Moodle 1.9 Beta + (2007090600)


$string['addgroupstogrouping'] = 'Lägg till grupp till gruppindelning';
$string['addgroupstogroupings'] = 'Lägg till/ta bort grupper';
$string['adduserstogroup'] = 'Lägg till/ta bort användare';
$string['anygrouping'] = '[Alla typer av gruppindelningar ]';
$string['backtogroupings'] = 'Tillbaka till gruppindelningar';
$string['backtogroups'] = 'Tillbaka till grupper';
$string['createautomaticgrouping'] = 'Skapa automatiska gruppindelningar';
$string['creategroup'] = 'Skapa grupp';
$string['creategrouping'] = 'Skapa gruppindelningar';
$string['creategroupinselectedgrouping'] = 'Skapa grupp  i gruppindelning';
$string['createorphangroup'] = 'Skapa \'föräldralös\' grupp';
$string['databaseupgradegroups'] = 'Versionerna för grupper är nu $a';
$string['defaultgroupdescription'] = 'Förvald standardbeskrivning av grupp';
$string['defaultgrouping'] = 'Förinställd gruppindelning';
$string['defaultgroupingname'] = 'Gruppindelningar';
$string['defaultgroupname'] = 'Grupp';
$string['defaultgroupprefix'] = 'Grupp';
$string['deletegroupconfirm'] = 'Är Du säker på att Du vill ta bort grupp \'$a\'?';
$string['deletegrouping'] = 'Tar bort gruppindelning';
$string['deletegroupingconfirm'] = 'Är Du säker på att Du vill ta bort gruppindelning \'$a\'? (Grupper i gruppindelningen tas inte bort.)';
$string['deleteselectedgroup'] = 'Ta bort markerad grupp';
$string['displaygrouping'] = 'Visa gruppindelningar';
$string['distributealphabetically'] = 'Fördela på grupper i alfabetisk ordning enligt efternamn.';
$string['distributeevenly'] = 'Fördela resterande studenter/elever/deltagare/lärande jämnt';
$string['editgroupingsettings'] = 'Redigera inställningar för gruppindelningar';
$string['editgroupsettings'] = 'Redigera inställningar för grupp';
$string['enrolmentkey'] = 'Nyckel för registrering';
$string['erroraddremoveuser'] = 'Fel i samband med att användare  $a skulle läggas till/ tas bort från grupp';
$string['erroreditgroup'] = 'Fel i samband med skapande/uppdatering av  $a';
$string['erroreditgrouping'] = 'Fel i samband med skapande/uppdatering av gruppindelning  $a';
$string['errorinvalidgroup'] = 'Fel, ogiltig grupp $a';
$string['existingmembers'] = 'Befintliga medlemmar: $a';
$string['group'] = 'Grupp';
$string['groupaddedsuccesfully'] = 'Grupp $a har lagts till framgångsrikt';
$string['groupdescription'] = 'Beskrivning av grupp';
$string['groupinfo'] = 'Info om vald grupp';
$string['groupinfomembers'] = 'Info om valda  medlemmar';
$string['groupinfopeople'] = 'Info om valda personer';
$string['grouping'] = 'Gruppindelning';
$string['groupingdescription'] = 'Beskrivning av gruppindelning';
$string['groupingname'] = 'Namn på gruppindelning';
$string['groupingnameexists'] = 'Namnet \'$a\' för gruppindelning finns redan i den här kursen, var snäll och välj en annan.';
$string['groupings'] = 'Gruppindelningar';
$string['groupmember'] = 'Medlem av grupp';
$string['groupmemberdesc'] = 'Standardroll för en medlem i en grupp';
$string['groupmembers'] = 'Gruppmedlemmar';
$string['groupmembersonly'] = 'Endast tillgänglig för gruppmedlemmar';
$string['groupmembersonlyerror'] = 'Du måste tyvärr vara medlem i åtminstone en grupp som används i den här aktiviteten.';
$string['groupmemberssee'] = 'Se gruppmedlemmar';
$string['groupmembersselected'] = 'Medlemmar i vald grupp';
$string['groupmode'] = 'Gruppläge';
$string['groupmodeforce'] = 'Framtvinga gruppläge';
$string['groupmy'] = 'Min grupp';
$string['groupname'] = 'Group name';
$string['groupnameexists'] = 'Gruppnamnet \'$a\' finns redan i den här kursen, var snäll och välj en annan,';
$string['groupnotamember'] = 'Du är tyvärr inte medlem av den gruppen.';
$string['groups'] = 'Grupper';
$string['groupsinselectedgrouping'] = 'Grupper i gruppindelning';
$string['groupsnone'] = 'Inga grupper';
$string['groupsseparate'] = 'Separata grupper';
$string['groupsvisible'] = 'Synliga grupper';
$string['hidepicture'] = 'Dölj bild';
$string['javascriptrequired'] = 'Den här sidan kräver Javascript för att aktiveras.';
$string['membersofselectedgroup'] = 'Medlemmar av grupp';
$string['newpicture'] = 'Ny bild';
$string['nopermissionforcreation'] = 'Det går inte att skapa grupp \'$a\' eftersom Du inte har de rättigheter som krävs.';
$string['notingrouping'] = '[Inte i gruppindelning]';
$string['numberofgroups'] = 'Antal grupper';
$string['numberofstudents'] = 'Antal studenter/elever/deltagare/lärande';
$string['potentialmembers'] = 'Potentiella medlemmar: $a';
$string['prefixforgroupnames'] = 'Prefix för gruppnamn';
$string['printerfriendly'] = 'Utskriftsvänlig visning';
$string['removegroupfromselectedgrouping'] = 'Ta bort grupp från gruppindelning';
$string['removeselectedusers'] = 'Ta bort de markerade användarna';
$string['selectnumberineachgroup'] = 'Välj ett antal i varje grupp';
$string['selectnumberofgroups'] = 'Välj ett antal grupper';
$string['showgroupsingrouping'] = 'Visa grupper i gruppindelning';
$string['showmembersforgroup'] = 'Visa medlemmar i grupp';
$string['usestudentsonlyfromselectedgroup'] = 'Använd endast studenter/elever/deltagare/lärande från den just nu valda gruppen.';
$string['cancel'] = 'Avbryt'; // ORPHANED
$string['editgroupingpermissions'] = 'Redigera rättigheter för gruppindelningar'; // ORPHANED
$string['errorinvalidgrouping'] = 'Fel, ogiltig gruppindelning $a'; // ORPHANED
$string['errornotingrouping'] = 'Du kan tyvärr inte skapa en grupp i $a'; // ORPHANED
$string['errornotingroupingedit'] = 'Du kan tyvärr inte redigera gruppindelningen  $a'; // ORPHANED
$string['groupfor'] = 'för grupp'; // ORPHANED
$string['return'] = 'Återgå'; // ORPHANED
$string['save'] = 'Spara'; // ORPHANED
$string['showusersalreadyingroup'] = 'Visa användare som redan är med i en grupp i gruppindelningen'; // ORPHANED
$string['teachersgroupmark'] = '(Distans)lärare får inte betygssätta aktiviteter för grupper som de inte tillhör.'; // ORPHANED
$string['teachersgroupview'] = '(Distans)lärare får inte visa aktiviteter för grupper som de inte tillhör.'; // ORPHANED
$string['teachersoverride'] = '(Distans)lärare som inte är med i någon grupp får se och betygssätta aktiviteter för alla grupper (detta överskrider det ovanstående).'; // ORPHANED
$string['upgradeconfirm'] = 'Tabeller för grupper som har skapats i Moodle 1.8 DEV måste tyvärr tas bort i samband med den här upgraderingen. Vill Du fortsätta?'; // ORPHANED
$string['viewallgroupsactivities'] = 'Studenter/elever/deltagare/lärande kan se men inte bidra till aktiviteter för alla grupper.'; // ORPHANED
$string['viewallgroupsmembers'] = 'Studenter/elever/deltagare/lärande kan se medlemmarna i alla grupper.'; // ORPHANED
$string['viewowngroup'] = 'Studenter/elever/deltagare/lärande kan se medlemmarna i alla de grupper som de tillhör.'; // ORPHANED

?>
