<?PHP // $Id$ 
      // error.php - created with Moodle 1.7 dev (2006100401)


$string['adminprimarynoedit'] = 'Het profiel van de beheerder met het kleinste gebruikersnummer kan door de andere beheerders niet gewijzigd worden';
$string['cannotcreatelangdir'] = 'Kan lang map niet maken';
$string['cannotcreatetempdir'] = 'Kan tijdelijke map niet maken.';
$string['cannotdownloadcomponents'] = 'Kan componenten niet downloaden.';
$string['cannotdownloadzipfile'] = 'Kan ZIP-bestand niet downloaden.';
$string['cannotfindcomponent'] = 'Kan component niet vinden.';
$string['cannotsavemd5file'] = 'Kan md5-bestand niet bewaren.';
$string['cannotsavezipfile'] = 'Kan ZIP-bestand niet bewaren.';
$string['cannotunzipfile'] = 'Kan bestand niet unzippen';
$string['cantunenrollfrommetacourse'] = 'Je kunt je uit deze koepelcursus niet afmelden';
$string['cantunenrollinthisrole'] = 'Je kunt je door de beperkingen van je huidige rol niet afmelden uit deze cursus';
$string['cmunknown'] = 'Kan deze cursusmodule niet vinden';
$string['componentisuptodate'] = 'Component niet up-to-date';
$string['confirmsesskeybad'] = 'Je sessiesleutel om deze actie uit te voeren kon niet bevestigd worden. Deze beveiligingsfunctie verhindert dat er per ongeluk of met verkeerde bedoelingen belangrijke functies in jouw naam uitgevoerd kunnen worden. Bedenk goed of je deze opdracht wel echt wou uitvoeren.';
$string['couldnotassignrole'] = 'Er gebeurde een ernstige maar niet gespecifieerde fout tijdens het proberen toewijzen van een rol aan jou.';
$string['coursegroupunknown'] = 'De cursus die met groep $a overeenkomt is niet gespecifieerd';
$string['downloadedfilecheckfailed'] = 'Controle van het gedownloade bestand mislukt';
$string['errorcleaningdirectory'] = 'Fout bij het opkuisen van map \"$a\"';
$string['errorcopyingfiles'] = 'Fout bij het kopiëren van bestanden';
$string['errorcreatingdirectory'] = 'Fout bij het maken van map \"$a\"';
$string['errorcreatingfile'] = 'Fout bij het maken van bestand \"$a\"';
$string['erroronline'] = 'Fout op lijn $a';
$string['errorreadingfile'] = 'Fout bij het lezen van bestand \"$a\"';
$string['errorunzippingfiles'] = 'Fout bij het uitpakken van bestanden';
$string['fieldrequired'] = '\"$a\" is een vereist veld';
$string['filenotfound'] = 'Het gevraagde bestand is niet gevonden';
$string['forumblockingtoomanyposts'] = 'Je hebt het maximum aantal berichten voor dit forum bereikt.';
$string['groupalready'] = 'Deze gebruiker behoort al tot groep $a';
$string['groupunknown'] = 'Groep $a is niet geassocieerd met de gespecifieerde groep';
$string['guestnoeditprofile'] = 'De gastgebruiker kan zijn profiel niet wijzigen';
$string['guestnoeditprofileother'] = 'Het profiel van de gastgebruiker kan niet gewijzigd worden';
$string['invalidcourse'] = 'Ongeldige cursus';
$string['invalidfieldname'] = '\"$a\" is geen geldige veldnaam';
$string['invalidfiletype'] = '\"$a\" is geen geldig bestandstype';
$string['invalidmd5'] = 'Ongeldig md5';
$string['invalidrole'] = 'Ongeldige rol';
$string['invalidxmlfile'] = '\"$a\" is geen geldig XML-bestand';
$string['missingfield'] = 'Veld \"$a\" ontbreekt';
$string['missingrequiredfield'] = 'Vereist veld ontbreekt';
$string['modulemissingcode'] = 'De code die nodig is om deze functie uit te voeren ontbreekt in module $a.';
$string['modulerequirementsnotmet'] = 'De module \"$a->modulename\" ($a->moduleversion) kon niet geïnstalleerd worden. Een nieuwere versie van Moodle is vereist (je gebruikt nu $a->currentmoodle en je hebt $a->requiremoodle nodig).';
$string['mustbeteacher'] = 'Je moet leraar zijn om deze pagina te mogen bekijken.';
$string['nocontext'] = 'Sorry, maar deze cursus is geen geldige omgeving';
$string['noinstances'] = 'Er is niets te vinden van $a in deze cursus!';
$string['nonmeaningfulcontent'] = 'Geen zinnige inhoud';
$string['noparticipatorycms'] = 'Sorry, maar je hebt geen vereiste cursusmodules om over te rapporteren';
$string['nopermissions'] = 'Sorry, maar je hebt nu niet het recht om dat te doen ($a).';
$string['notavailable'] = 'Dat is nu niet beschikbaar';
$string['onlyadmins'] = 'Enkel beheerders mogen dit doen.';
$string['onlyeditingteachers'] = 'Alleen leraren met het recht om te wijzigen kunnen dit doen';
$string['onlyeditown'] = 'Je kunt enkel je eigen informatie bewerken';
$string['pagenotexist'] = 'Er is een ongewone fout gebeurd (het proberen te bereiken van een pagina die niet bestaat';
$string['pleasereport'] = 'Probeer tijd te maken om ons te laten weten wat je probeerde te doen toen de fout gebeurde.';
$string['pluginrequirementsnotmet'] = 'Plugin \"$a->pluginname\" ($a->pluginversion) kon niet geïnstalleerd worden. Er is een nieuwere versie van Moodle nodig (je gebruikt nu $a->currentmoodle en je hebt $a->requiremoodle nodig).';
$string['processingstops'] = 'Verwerking stopt hier. De overgebleven records worden genegeerd';
$string['remotedownloadnotallowed'] = 'Het downloaden van componenten naar je server is niet toegelaten (allow_url_fopen is uitgeschakeld)<br /><br />Je moet het <a href=\"$a->url\">$a->url</a>bestand manueel downloaden en het kopiëren naar \"$a->dest\" op je server en het daar unzippen.';
$string['restricteduser'] = 'Sorry, maar je hebt onvoldoende rechten om dat te doen.';
$string['sendmessage'] = 'Stuur bericht';
$string['sessionerroruser'] = 'Je sessie bleef te lang zonder activiteit. Je moet terug inloggen.';
$string['sessionerroruser2'] = 'Er is een serverfout gevonden die je loginsessie verknoeide. Meld je opnieuw aan of herstart je browser.';
$string['sessionipnomatch'] = 'Sorry, maar je IP-adres is gewijzigd sinds je aangemeld bent. Deze beveiligingsmethode voorkomt dat crackers je identiteit stelen terwijl je aangemeld bent op deze site. Gewone gebruikers zouden deze melding niet mogen zien - vraag je sitebeheerder om hulp.';
$string['statscatchupmode'] = 'De statistiekfunctie is nu wat achterstand aan het inhalen. Tot nu zijn al $a->daysdone dagen verwerkt en zijn er nog $a->dayspending dagen te doen. Kom later eens terug kijken!';
$string['unknowncourse'] = 'Onbekende cursus \"$a\"';
$string['unknownuseraction'] = 'Sorry, Moodle begrijpt niet wat je wil';
$string['usernotaddederror'] = 'Gebruiker \"$a\" niet toegevoegd - onbekende fout';
$string['usernotaddedregistered'] = 'Gebruiker \"$a\" niet toegevoegd - gebruiker bestaat al';
$string['usernotavailable'] = 'Je hebt het recht niet om de detailgegevens van deze gebruiker te zien.';
$string['usernotrenamedexists'] = 'Gebruiker niet hernoemd -- de nieuwe gebruikersnaam bestaat al.';
$string['usernotrenamedmissing'] = 'Gebruiker niet hernoemd -- kon de oude gebruikersnaam niet vinden.';
$string['wrongdestpath'] = 'Fout pad voor bestemming';
$string['wrongsourcebase'] = 'Foute URL voor de bron';
$string['wrongzipfilename'] = 'Foute ZIP-bestandsnaam';

?>
