<?PHP // $Id$ 
      // portfolio.php - created with Moodle 2.0 dev (Build: 20080815) (2008081506)


$string['addnewportfolio'] = 'Voeg een nieuw portfolio toe';
$string['addtoportfolio'] = 'Voeg toe aan portfolio';
$string['alreadyexporting'] = 'Je hebt al een actieve portfolioexport in deze sessie. Werk deze eerst af';
$string['availableformats'] = 'Beschikbare exportformats';
$string['callercouldnotpackage'] = 'Inpakken van je gegevens voor export mislukt';
$string['cannotsetvisible'] = 'Kan dit niet zichtbaar zetten - de plugin is volledig uitgeschakeld door een foute configuratie';
$string['configexport'] = 'configureer geëxporteerde gegevens';
$string['configplugin'] = 'Configureer portfolioplugin';
$string['configure'] = 'Configureer';
$string['confirmexport'] = 'Bevestig deze export';
$string['confirmsummary'] = 'Samenvatting van je export';
$string['continuetoportfolio'] = 'Ga verder naar je portfolio';
$string['deleteportfolio'] = 'Verwijder portfolio';
$string['disabled'] = 'Het exporteren van portfolio\'s is niet ingeschakeld voor deze site';
$string['dontwait'] = 'Wacht niet';
$string['enabled'] = 'Portfolio\'s inschakelen';
$string['enableddesc'] = 'Hiermee kunnen beheerders systemen op afstand configureren, zodat gebruikers er inhoud naartoe kunnen exporteren';
$string['err_uniquename'] = 'Portfolionaam moet uniek zijn (per plugin)';
$string['exportcomplete'] = 'Portfolioexport klaar!';
$string['exportedpreviously'] = 'Vorige exports';
$string['exporting'] = 'Exporteren naar portfolio';
$string['exportqueued'] = 'Portfolio-export is klaargezet voor transfer';
$string['failedtosendpackage'] = 'Gegevens sturen naar het geselecteerde portfoliosysteem mislukt!';
$string['filedenied'] = 'Toegang tot dit bestand geweigerd';
$string['filenotfound'] = 'Bestand niet gevonden';
$string['format_file'] = 'Bestand';
$string['format_mbkp'] = 'Moodle backup';
$string['hidden'] = 'Verborgen';
$string['instancedeleted'] = 'Portfolio met succes verwijderd';
$string['instanceismisconfigured'] = 'Portfolio is fout geconfigureerd, overgeslagen. De fout was: $a';
$string['instancenotdelete'] = 'Portfolio verwijderen mislukt';
$string['instancenotsaved'] = 'Portfolio bewaren mislukt';
$string['instancesaved'] = 'Portfolio bewaren gelukt';
$string['invalidaddformat'] = 'Ongeldig add format gegeven aan portfolio_add_button. ($a) Moet er één zijn van PORTFOLIO_ADD_XXX';
$string['invalidformat'] = 'Iets is een ongelige format aan het exporteren, $a';
$string['invalidinstance'] = 'Kon dat portfolio-item niet vinden';
$string['invalidtempid'] = 'Ongeldig tijdelijke ID';
$string['manageportfolios'] = 'Beheer portfolio\'s';
$string['manageyourportfolios'] = 'Beheer jouw portfolio\'s';
$string['noavailableplugins'] = 'Er zijn voor jou geen portfolio\'s beschikbaar om naar te exporteren';
$string['nocallbackfile'] = 'Iets in de module van waaruit je wil exporteren werkt niet - kon een vereist bestan ($a) niet vinden';
$string['nocommonformats'] = 'Geen gemeenschappelijke formaten tussen de portfolio plugin en de vragende locatie $a';
$string['nonprimative'] = 'Een niet-primative waarde is doorgegeven als callback argument aan de portfolio_add_button. Gestopt. De sleutel was $a->key en de waarde was $a->value';
$string['nopermissions'] = 'Je hebt niet de juiste rechten om van hieruit bestanden te exporteren';
$string['notexportable'] = 'Het type inhoud dat je probeert te exporteren is niet exporteerbaar';
$string['notimplemented'] = 'Je probeert een format te exporteren naar een format die nog niet geïmplementeerd is ($a)';
$string['nouploaddirectory'] = 'Kon geen tijdelijke map maken om je gegevens in te verpakken';
$string['plugin'] = 'Portfolio Plugin';
$string['plugincouldnotpackage'] = 'Inpakken van je gegevens voor export mislukt';
$string['portfolio'] = 'Portfolio';
$string['portfolios'] = 'Portfolio\'s';
$string['returntowhereyouwere'] = 'Keer terug';
$string['save'] = 'Bewaar';
$string['selectedformat'] = 'Gekozen export format';
$string['selectedwait'] = 'Gekozen om te wachten?';
$string['selectplugin'] = 'Kies portfolio plugin om naar te exporteren';
$string['someinstancesdisabled'] = 'Sommige geconfigureerde plugins zijn uitegeschakeld ofwel omdat ze fout geconfigureerd zijn of omdat ze afhankelijk zijn van iets anders dat fout geconfigureerd is';
$string['somepluginsdisabled'] = 'Sommige plugins zijn volledig uitgeschakeld omdat ze fout geconfigureerd zijn of omdat ze afhankelijk zijn van iets anders dat fout geconfigureerd is';
$string['sure'] = 'Weet je zeker dat je \'$a\' wil verwijderen? Dit is definitief.';
$string['wait'] = 'Wacht';
$string['wanttowait_high'] = 'Het wordt niet aangeraden te wachten om deze transfer af te ronden, maar je kunt wachten als je zeker weet wat je doet.';
$string['wanttowait_moderate'] = 'Wil je op deze transfer wachten? Het kan een aantal minuten duren';
$string['portfolionotfile'] = 'Exporteer naar een portfolio, eerder dan naar een bestand'; // ORPHANED

?>
