<?PHP // $Id$ 
      // admin.php - created with Moodle 1.5.2 + (2005060223)


$string['adminseesallevents'] = 'Správci vidí všechny události';
$string['adminseesownevents'] = 'Správci jsou jako ostatní uživatelé';
$string['blockinstances'] = 'Výskyty';
$string['blockmultiple'] = 'Složený';
$string['cachetext'] = 'Životnost mezipaměti textu';
$string['calendarsettings'] = 'Kalendář';
$string['change'] = 'změnit';
$string['configallowcoursethemes'] = 'Tato možnost povoluje nastavení vlastních motivů v kurzech. Motivy kurzů mají přednost před všemi ostatními motivy (tj. před motivem stránek, uživatele či sezení)';
$string['configallowemailaddresses'] = 'Chcete-li omezit všechny nové emailové adresy pouze na určité domény. pak je zde uveďte oddělené mezerou. Všechny ostatní domény budou odmítnuty. Příklad: <strong>naseskola.cz .msmt.cz .edu.cz</strong>';
$string['configallowobjectembed'] = 'Výchozí bezpečnostní opatření nedovoluje normálním uživatelům vkládat multimediální objekty (např. Flash) pomocí značek EMBED a OBJECT v jejich HTML textu. Bezpečné vkládání multimediálních objektů zajišťuje jeden z tzv. filtrů. Chcete-li přesto povolit uvedené značky, povolte tuto možnost.';
$string['configallowunenroll'] = 'Je-li toto nastaveno na \'Ano\', mohou se studenti sami vyškrtávat z kurzů. Jinak je může z kurzu vyškrtnout toliko učitel nebo správce.';
$string['configallowuserblockhiding'] = 'Chcete uživatelům povolit zasouvání/vysouvání postranních bloků na těchto strínkách? Tato fičurinka používá Javascript a pomocí cookies si pamatuje stav každého rolovatelného bloku. Vždy je ovlivňován pouze pohled příslušného uživatele.';
$string['configallowuserthemes'] = 'Tímto povolíte uživatelům nastavit si vlastní motiv. Motiv uživatele má přednost před motivem stránek, ale nikoliv před motivem kurzu.';
$string['configallusersaresitestudents'] = 'Měli bý být VŠICHNI uživatelé považováni za studenty v činnostech na titulní stránce? Odpovíte-li \"Ano\", mohou se všichni uživatelé s potvrzeným účtem zapojit do těchto činností jako studenti. Odpovíte-li \"Ne\", pak pouze uživatelé, kteří jsou již členy alespoň jednoho kurzu, budou moci participovat v těchto činnostech. Pouze správci a speciálně určení učitelé mohou figurovat jako vyučující v činnostech na titulní stráce.';
$string['configautologinguests'] = 'Mají být návštěvníci vašich stránek automaticky přihlášeni jako hosté, když vstupují do kurzů, které umožńují hostům vstup?';
$string['configcachetext'] = 'Na větších stránkách nebo na stránkách, které používají textové filtry, může toto nastavení provoz stránek výrazně urychlit. Po dobu určenou zde zůstane zpracovaný text v mezipaměti a bude okamžitě použit. Nastavení příliš malé hodnoty může zobrazování stránek trochu zpomalit, nastavení příliš velké hodnoty zase způsobí, že obnovení textu (např. nové odkazy apod.) se projeví až po delší době.';
$string['configclamactlikevirus'] = 'Považuj soubory za viry';
$string['configclamdonothing'] = 'Považuj soubory za neškodné';
$string['configclamfailureonupload'] = 'Pokud zvolíte, že clam má skenovat nahrávané soubory, ale v konfiguraci uděláte chybu, popřípadě dojde k jinému problému se spouštěním, jak se má Moodle zachovat? Vyberete-li si \'Považuj soubory za viry\', budou soubory umístěny do karantény, nebo budou odstraněny. Zvolíte-li \'Považuj soubory za neškodné\', budou soubory uloženy do cílového adresáře jako obyčejně. Tak jako tak, správci serveru budou upozorněni, že se clam nepodařilo spustit. Zvolíte-li ale \'Považuj soubory za viry\' a clam se z nějakého důvodu nepodaří spustit (většinou proto, že vložíte neplatnou pathtoclam), budou VŠECHNY nahrávané soubory přesunuty do karantény nebo odstraněny! Takže bacha...';
$string['configcountry'] = 'Pokud zde nastavíte zemi, pak bude přednastavená pro všechny nové uživatele. Zůstane-li toto pole prázdné, bude nutné nastavit zemi u každého nového uživatele.';
$string['configdbsessions'] = 'Je-li povoleno, bude se pro ukládání informací o stávajících sezeních (sessions) používat databáze. To může být užitečné pro velké a/nebo zaneprázdněné servery nebo stránky postavené na clustrovaných serverech. Pro většinu stránek by toto mělo zůstat zakázáno, takže se informace budou ukládat na disk. Povšimněte si, že změna tohoto nastavení způsobí odhlášení všech uživatelů (včetně vás).';
$string['configdebug'] = 'Při zapnutí dojde ke zvýšení vlastnosti PHP \'error_reporting\' a bude zobrazováno více varování. Užitečné hlavně pro vývojáře.';
$string['configdeleteunconfirmed'] = 'Používáte-li ověřování emailem, nastavíte tímto dobu, po kterou se bude čekat na potvrzení registrace. Po uplynutí této doby budou nepotvrzené žádosti o založení účtu odstraněny.';
$string['configdenyemailaddresses'] = 'Chcete-li odmítat emailové adresy z jistých domén, uveďte je zde oddělené mezerou. Všechny ostatní domény budou akceptovány. Příklad: <strong>hotmail.com yahoo.co.uk</strong>';
$string['configdigestmailtime'] = 'Lidem, kteří si nastaví souhrnné odebírání novinek emailem, bude tento souhrn odesílán každý den. Tímto nastavujete, v kolik hodin budou tyto souhrnné emaily odesílány (první cron, který se spouští po této hodině, emaily odešle).';
$string['configdisplayloginfailures'] = 'Toto zobrazuje informace vybraným uživatelům o předchozích neúspěšných přihlášeních.';
$string['configenablerssfeeds'] = 'Tímto nastavením povolujete funkce RSS kanálů napříč celou instalací Moodle. Stále ještě musíte povolit funkce RSS u jednotlivých modulů v nabídce Správa modulů na stránce Správa.';
$string['configenablerssfeedsdisabled'] = 'Toto nastavení není dostupné, protože funkce RSS kanálů byly na těchto stránkách zakázány. Chcete-li je povolit, jděte do nabídky Proměnné na stránce Správa.';
$string['configerrorlevel'] = 'Vyberte množství zobrazovaných varování PHP. Většinou je nejlepší volbou \'Normální\'.';
$string['configextendedusernamechars'] = 'Tímto dovolujete uživatelům používat jakékoli znaky v jejich uživatelských jménech (neovlivňuje jejich jména jako taková). Výchozí hodnota \'Ne\' omezí uživatelská jména pouze na alfanumerické znaky.';
$string['configfilterall'] = 'Zpracovávat pomocí filtrů všechny řetězce včetně nadpisů, titulků, navigační lišty apod.? To se hodí zejména při používání filtru vícejazyčné podpory, jinak tato volba představuje pouze zvyšenou zátěž pro váš server bez výrazného zisku.';
$string['configfilteruploadedfiles'] = 'Povolení této proměnné způsobí, že Moodle zpracuje všechny nahrané HTML a textové soubory pomocí aktivních filtrů předtím, než je zobrazí.';
$string['configforcelogin'] = 'Normálně může titulní stránku a seznam kurzů (ale kurzy samotné už ne) vidět kdokoliv bez přihlášení. Pokud chcete vynutit přihlášení uživatelů hned na první stránce (ještě předtím, než budou moci COKOLIV dělat), povolte toto nastavení.';
$string['configforceloginforprofiles'] = 'Povolíte-li toto nastavení, vynutíte si přihlášení návštěvníků vašich stránek předtím, než si budou moci prohlížet stránky s uživatelskými profily. Implicitně je tato volba zakázána (\'Ne\'), takže si potenciální studenti mohou něco přečíst o učitelích v kurzech. Zároveň to však znamená, že stránky s osobními profily jsou přístupné webovým vyhledávačům.';
$string['configframename'] = 'Začleňujete-li Moodle do webového rámce (frame) vašich stránek, vložte název tohoto rámce. Jinak by zde měla zůstat hodnota \'_top\'';
$string['configfullnamedisplay'] = 'Zde se definuje, jak budou zobrazována jména uživatelů. Pro většinu jednojazyčných stránek je nejúčelnější výchozí \"Křestní jméno + Příjmení\", ale můžete si zvolit skrývání příjmení, nebo ponechat toto rozhodnutí na nastavení stávajícího jazyka (jiné jazyky mohou mít jiné konvence).';
$string['configgdversion'] = 'Označuje verzi nainstalované knihovny GD. Implicitně se zobrazuje verze, která byla zjištěna automaticky. Neměňte tuto hodnotu, pokud opravdu nevíte, co děláte.';
$string['confightmleditor'] = 'Vyberte, zda chcete nebo nechcete povolit používání vestavěného HTML textového editoru. I když jej povolíte, editor bude k dispozici pouze uživatelům s kompatibilním prohlížečem. Uživatelé si mohou rovněž zvolit nepoužívání tohoto editoru.';
$string['configidnumber'] = 'Tato možnost určuje, zda (a) uživatelé nejsou vůbec dotazování na jejich ID číslo (například rodné číslo, číslo občanského průkazu či jiný identifikátor), (b) uživatelé jsou dotazováni na ID číslo, ale nemusí jej zadávat, (c) uživatelé jsou dotazováni na ID číslo a musí jej zadat. Je-li číslo zadáno, je zobrazováno v profilech uživatelů.';
$string['configintro'] = 'Na této stránce můžete určit hodnoty několika nastavitelných proměnných, díky nimž poběží Moodle na vašem serveru bez problémů. Nemějte obavy - přednastavené hodnoty většinou postačují a navíc se můžete kdykoliv na tuto stránku vrátit a nastavení změnit.';
$string['configintroadmin'] = 'Na této stránce byste měli nastavit váš hlavní administrátorský účet. Administrátor (správce) má úplnou kontrolu nad těmito stránkami. Ujistěte se, že zadáváte bezpečené uživatelské jméno a heslo, stejně jako platnou emailovou adresu. Později můžete vytvořit více administrátorských účtů.';
$string['configintrosite'] = 'Zde můžete nastavit vzhled titulní stránky a název stránek. Můžete se sem kdykoliv později vrátit a změnit toto nastavení pomocí odkazu \'Nastavení stránek\' na titulní stránce.';
$string['configintrotimezones'] = 'Tato stránka vyhledá nové informace o časových pásmech (včetně informací o letním a zimním čase) a aktualizuje vaši lokální databázi s těmito informace. Prověřovány budou následující lokace (v uvedeném pořadí): $a. Tato procedura je obecně velmi bezpečná a nemůže ohrozit běžné instalace. Přejete si nyní aktualizovat vaše časové zóny?';
$string['configlang'] = 'Vyberte výchozí jazyk pro tyto stránky. Uživatelé si mohou sami toto nastavení sami změnit.';
$string['configlangcache'] = 'Ukládat nabídku jazyků v dočasné paměti (cache)? Tím ušetříte spoustu místa v operační paměti a výkonu serveru. Pokud máte povoleno a přidáte či odstraníte jazyk, může trvat několik minut, než se nabídka jazyků zaktualizuje.';
$string['configlangdir'] = 'Ve většině jazyků se píše zleva doprava, ale v některých (jako arabština nebo hebrejština) se píše zprava doleva.';
$string['configlanglist'] = 'Ponecháte-li toto pole prázdné, budou si uživatelé moci vybrat kterýkoliv z jazyků v této instalaci. Nabídku jazyků však můžete omezit vložením čárkami odděleného seznamu kódů vámi povolených lokalizací. Například: cs,en,es_es,fr,sk,it';
$string['configlangmenu'] = 'Zvolte, zda chcete nebo nechcete zobrazovat nabídku možných jazyků na titulní stránce, přihlašovací stránce apod. Toto neovlivňuje možnost uživatelů vybrat si upřednostňovaný jazyk ve svém profilu.';
$string['configlocale'] = 'Vyberte lokalizaci stránek. Ta ovlivňuje formát a jazyk při zobrazování datumu. Potřebná data musíte mít nainstalována ve vašem operačním systému. Pokud nevíte, co vybrat, ponechte pole prázdné nebo vyzkoušejte \'cs_CZ\' nebo \'czech\'.';
$string['configloginhttps'] = 'Při zapnutím této volby bude Moodle používat zabezpečené https spojení na stránce přihlášení (přihlášení bude probíhat na šifrovaném spojení) a poté se vrátí do normálního http provozu (kvůli rychlosti). UPOZORNĚNÍ: toto nastavení VYŽADUJE, aby bylo https povoleno a nastaveno na vašem webovém serveru - pokud není, MOHLI BYSTE SI ZAMEZIT PŘÍSTUP NA VAŠE STRÁNKY!!!';
$string['configloglifetime'] = 'Toto určuje dobu, po kterou jsou uchovávány protokoly o činnosti uživatelů. Protokoly starší, než je zde vložené doba, jsou automaticky odstraněny. Doporučujeme udržovat protokoly co nejdéle, můžou se vám hodit. Pokud však provozujete často používaný server a zaznamenáváte problémy s výkonem, možná budete chtít dobu uchovávání protokolů zkrátit.';
$string['configlongtimenosee'] = 'Pokud se studenti nepřihlásí po velmi dlouhou dobu, jsou automaticky vyškrtnuti z kurzů. Tento parametr určuje maximální možnou dobu, po kterou se student nemusí přihlásit.';
$string['configmaxbytes'] = 'Toto určuje maximální možnou velikost souborů nahrávaných uploadem na tyto stránky. Toto nastavení je limitováno PHP proměnnou upload_max_filesize a nastavením Apache LimitRequestBody. Na druhou stranu toto nastavení limituje velikosti, které lze nastavit na úrovni kurzů nebo modulů.';
$string['configmaxeditingtime'] = 'Kolik času mají uživatelé na opravu odeslaných příspěvků. Doporučujeme nastavit 30 minut.';
$string['configmessaging'] = 'Povolit systém zasílání zpráv mezi uživateli stránek?';
$string['confignoreplyaddress'] = 'Emaily jsou někdy zasílány pod něčím jménem (např. příspěvky ve fórech). V případech, kdy by se na email nemělo odpovídat přímo odesilateli (např. protože nechce zveřejňovat svou adresu), bude použita jako adresa odesílatele (adresa Od:) adresa zde uvedená.';
$string['confignotifyloginfailures'] = 'Při neúspěšném přihlášení mohou být zasílány upozornění emailem. Kdo by měl obdržet tato upozornění?';
$string['confignotifyloginthreshold'] = 'Je-li aktivní upozorňování na neúspěšná přihlášení, po kolika neúspěšných pokusech na jednoho uživatele nebo jednu IP adresu se má upozornění rozeslat?';
$string['configopentogoogle'] = 'Povolíte-li toto nastavení, umožníte vyhledávači Google, aby vstoupil na vaše stránky jako host. Navíc lidé, kteří se k vám dostanou přes vyhledávání v Google, budou automaticky přihlášení jako host. Povšimněte si, že toto umožní transparentní přístup pouze do kurzů, které mají povolen vstup hostů.';
$string['configpathtoclam'] = 'Cesta k antivirovému programu Clam AV. Pravděpodobně něco jako /usr/bin/clamscan nebo /usr/bin/clamdscan. Toto musíte nastavit, chcete-li spouštet Clam AV.';
$string['configpathtodu'] = 'Cesta k programu du (disk usage). Pravděpodobně něco jako /usr/bin/du. Zadáním této cesty se urychlí generování stránek, které zobrazují obsah adresáře s mnoha soubory.';
$string['configproxyhost'] = 'Pokud tento <b>server</b> používá proxy (např. firewall) pro připojení k Internetu, zadejte hostname a port proxy. Jinak nechejte pole prázdné.';
$string['configquarantinedir'] = 'Chcete-li, aby Clam AV přesouval infikované soubory do karantény, vložte sem adresář, který bude tuto funkci zastávat. Webový server musí mít práva zápisu do tohoto adresáře. Pokud necháte pole prázdné, popř. pokud nebude vložený adresář existovat či nebude zapisovatelný, budou infikované soubory odstraněny. Adresář zapisujte bez koncového lomítka.';
$string['configrunclamonupload'] = 'Spoustět Clam AV na nahrávané soubory? Budete muset vložit platnou pathtoclam. Clam AV je volně šířitelný antivirový program, který si můžete stáhnout z http://clamav.net/';
$string['configsectioninterface'] = 'Rozhraní';
$string['configsectionmail'] = 'Pošta';
$string['configsectionmaintenance'] = 'Údržba';
$string['configsectionmisc'] = 'Různé';
$string['configsectionoperatingsystem'] = 'Operační systém';
$string['configsectionpermissions'] = 'Oprávnění';
$string['configsectionsecurity'] = 'Zabezpečení';
$string['configsectionuser'] = 'Uživatel';
$string['configsecureforms'] = 'Moodle může používat vyšší úroveň zabezpečení při přijímání údajů z webových formulářů. Je-li tato volba povolena, pak je proměnná prohlížeče HTTP_REFERER ověřována proti aktuální adrese formuláře. V několika málo případech však toto může způsobovat problémy, zejména používá-li uživatel firewall (např. Zonealarm) nastavený tak, aby proměnnou HTTP_REFERER z webového provozu odřízl. Příznakem tohoto jsou problémy s formuláři. Pokud tedy uživatelé mají problém například na přihlašovací stránce, možná budete chtít tuto metodu zakázat a tím ulehčit práci případným útokům na hesla uživatelů (brute-force password attacks). Jste-li na pochybách, ponechejte zde hodnotu \'Ano\'.';
$string['configsessioncookie'] = 'Tímto lze upravit název cookie, které se používá pro nastavení Moodle session. Toto nastavení je volitelné, hodí se pouze v případě, kdy provozujete více kopií Moodle na jednom serveru.';
$string['configsessiontimeout'] = 'Pokud jsou lidé přihlášení na tyto stránky nečinní po dlouhou dobu (tj. nenačítají se stránky), jsou automaticky odhlášeni. Tato proměnná určuje, po jak dlouhé době k tomu dojde.';
$string['configshowblocksonmodpages'] = 'Některé moduly činností podporují bloky na svých stránkách. Zapnete-li tuto volbu, budou mít uživatelé možnost přidávat postranní bloky na tyto stránky. V opačném případě se rozhraní pro vložení bloků nezobrazuje.';
$string['configshowsiteparticipantslist'] = 'Na tomto seznamu budou uvedeni všichni studenti a učitelé na těchto stránkách. Komu má být umožněno vidět tento seznam účastníků stránek?';
$string['configsitepolicy'] = 'Máte-li pravidla provozu stránek, které musí všichni uživatelé zhlédnout a souhlasit s nimi před používáním vašich stránek, uveďte zde jejich URL, jinak nechte toto pole prázdné. URL může ukazovat kamkoliv - jedno z vhodných míst může být soubor nahraný do souborobého manažeru Moodle na hlavní stránce, např. http://vas.moodle.server/file.php/1/policy.html';
$string['configslasharguments'] = 'Soubory (t.j. obrázky a další připojené soubory) mohou být dostupné jako parametry za lomítkem (slash arguments, druhá nabízená možnost). Tato metoda umožňuje, aby byly tyto soubory snadněji ukládány ve vyrovnávacích pamětech prohlížečů, proxy serverů apod. Bohužel, některé PHP servery tuto možnost nemají, takže pokud narazíte na problémy se zobrazováním připojených souborů nebo obrázků (např. fotografie uživatelů), vyberte první z nabízených možností.';
$string['configsmtphosts'] = 'Vložte plné jméno jednoho nebo více SMTP serverů, které může Moodle používat k zasílání pošty (např. \'mail.naseskola.cz\' nebo \'mail1.naseskola.cz;mail2.naseskola.cz\'). Pokud ponecháte toto pole prázdné, Moodle bude používat standardní PHP způsob zasílání pošty.';
$string['configsmtpuser'] = 'Pokud jste výše specifikovali nějaký SMTP server a ten vyžaduje ověření, zadejte zde uživatelské jméno a heslo.';
$string['configteacherassignteachers'] = 'Je učitelům dovoleno přiřazovat ke svým kurzům další učitele? Pokud \'Ne\', pak pouze tvůrci kurzů a správci mohou přiřazovat učitele.';
$string['configthemelist'] = 'Nechte toto pole prázdné, pokud chcete povolit k užívání všechny platné motivy. Chcete-li zkrátit nabídku motivů, uveďte zde jejich seznam oddělený čárkami. Např.: standard,orangewhite';
$string['configtimezone'] = 'Zde můžete nastavit výchozí časovou zónu. Toto je pouze VÝCHOZÍ hodnota pro zobrazování času - každý uživatel si může svou časovou zónu nastavit ve svém profilu. Hodnota \"Čas serveru\" zde způsobuje, že Moodle používá nastavení operačního systému. Ale \"Čas serveru\" v profilu uživatele znamená, že bude použita časová zóna uvedená zde.';
$string['configunzip'] = 'Zadejte umístění programu unzip (volitelné). Pokud je zadáno, bude Moodle používat tento program k rozbalování zip archívů na serveru. Jinak bude používat vlastní knihovny.';
$string['configvariables'] = 'Proměnné';
$string['configwarning'] = 'S úpravou těchto hodnot buďte opatrní - nezvyklé hodnoty mohou způsobovat problémy.';
$string['configzip'] = 'Zadejte umístění programu zip (volitelné). Pokud je zadáno, bude Moodle používat tento program k vytváření zip archívů na serveru. Jinak bude používat vlastní knihovny.';
$string['confirmation'] = 'Potvrzení';
$string['cronwarning'] = 'Skript <a href=\"cron.php\">cron.php</a>, který má na starosti běžnou údržbu serveru, nebyl během posledních 24 hodin spuštěn.';
$string['edithelpdocs'] = 'Upravit nápovědu a dokumentaci';
$string['editstrings'] = 'Upravit textové řetězce';
$string['filterall'] = 'Filtrovat všechny řetězce';
$string['filteruploadedfiles'] = 'Filtrovat nahrané soubory';
$string['helpadminseesall'] = 'Vidí správci všechny události v kalendáři nebo jen ty, které se na ně vztahují?';
$string['helpcalendarsettings'] = 'Konfigurace kalendáře a dalších aspektů Moodlu, které se týkají datumu a času';
$string['helpforcetimezone'] = 'Můžete povolit uživatelům nastavovat si jejich vlastní časové pásmo nebo vnutit určité časové pásmo všem';
$string['helpsitemaintenance'] = 'Aktualizace a další';
$string['helpstartofweek'] = 'Kterým dnem má začíná týden v kalendáři?';
$string['helpupcominglookahead'] = 'V kolika následujících dnech se mají implicitně vyhledávat tzv. nadcházející události?';
$string['helpupcomingmaxevents'] = 'Maximálně kolik nadcházejících událostí se má implicitně uživatelům ukazovat?';
$string['helpweekenddays'] = 'Které z dnů v týdnu se mají považovat za \"víkend\" a zobrazovat se v kalendáři odlišnou barvou?';
$string['importtimezones'] = 'Aktualizovat kompletní seznam časových pásem';
$string['importtimezonescount'] = '$a->count položek bylo importováno z $a->source';
$string['importtimezonesfailed'] = 'Nenalezeny žádné zdroje! (to je špatná zpráva)';
$string['incompatibleblocks'] = 'Nekompatibilní bloky';
$string['optionalmaintenancemessage'] = 'Volitelná zpráva o údržbě';
$string['pleaseregister'] = 'Chcete-li se zbavit tohoto tlačítka, registrujte vaše Moodle stránky';
$string['sitemaintenance'] = 'Momentálně pracujeme na údržbě těchto stránek a nejsou proto dočasně k dispozici';
$string['sitemaintenancemode'] = 'Režim údržby';
$string['sitemaintenanceoff'] = 'Režim údržby byl vypnut a stránky zase běží v normálním režimu.';
$string['sitemaintenanceon'] = 'Vaše stránky jsou momentálně v režimu údržby (pouze správci se teď mohou přihlásit a používat tyto stránky).';
$string['sitemaintenancewarning'] = 'Vaše stránky jsou momentálně v režimu údržby (pouze správci se teď mohou přihlásit). K návratu do běžného režimu <a href=\"maintenance.php\">vypněte režim údržby</a>.';
$string['tabselectedtofront'] = 'Má se v tabulkách, které používají navigaci pomocí záložek, přesunout řádek s právě vybranou záložkou do popředí?';
$string['therewereerrors'] = 'Vaše data obsahovala chyby';
$string['timezoneforced'] = 'Toto je vnuceno správcem stránek';
$string['timezoneisforcedto'] = 'Vnutit používání všem uživatelům';
$string['timezonenotforced'] = 'Uživatelé si mohou vybrat vlastní časové pásmo';
$string['upgradeforumread'] = 'Do Moodlu 1.5 byla přidána nová funkce, která umožňuje zaznamenávat stav příspěvků \"přečteno/nepřečteno\".<br />Chcete-li tuto funcki používat, musíte <a href=\"$a\">aktualizovat tabulky v databázi</a>.';
$string['upgradeforumreadinfo'] = 'Do Moodlu 1.5 byla přidána nová funkce, která umožňuje u každého uživatele zaznamenávat stav příspěvků \"přečteno/nepřečteno\". Chcete-li tuto funcki používat, je třeba doplnit ke stávajícím příspěvkům potřebné informace. Tento proces může v závislosti na velikosti vašich stránek trvat až několik hodin a na vašem databázovém serveru bude celkem rušno, takže doporučujeme provést tuto činnost ve vhodném čase (např. o víkendu v noci). Vaše stránky budou nicméně stále v provozu a práce uživatelů by neměla být výrazněji ovlivněna. Jakmile proces spustíte, měli byste jej nechat dokončit (tj. nechat otevřené příslušné okno prohlížeče). Ale nemějte obavy, pokud okno zavřete a proces ukončíte, můžete bez obav začít znovu.<br /><br />Chcete nyní spustit aktualizaci vaší databáze?';
$string['upgradelogs'] = 'Vaše staré protokoly musejí být aktualizovány. <a href=\"$a\">Více informací</a>';
$string['upgradelogsinfo'] = 'Ve způsobu uchovávání protokolů došlo k nějakým změnám. Chcete-li zobrazovat vaše dosavadní protokoly na základě činností, musí být všechny uložené protokoly upgradovány. V závislosti na jejich množství může toto trvat dlouhou dobu (i několik hodin) a obzvláště na větších stránkách to zatíží vaši databázi. Jakmile jednou proces spustíte, měli byste jej nechat dokončit (nechte okno prohlížeče otevřené). Nemusíte mít obavy - vaše stránky budou v průběhu upgradu pro ostatní stále dostupné.<br /><br />Chcete teď upgradovat vaše protokoly?';
$string['upgradesure'] = 'Soubory Moodlu se změnily, takže se pravděpodobně chystáte upgradovat váš server na verzi:
<p><b>$a</b></p>
<p>Jakmile se toto jednou rozhodnete udělat, nemůžete se již vrátit.</p>
<p>Jste si jisti, že chcete upgradovat server na tuto verzi?</p>';
$string['upgradingdata'] = 'Aktualizace dat';
$string['upgradinglogs'] = 'Aktualizace protokolů';

?>
