<?php

// All of the language strings in this file should also exist in
// auth.php to ensure compatibility in all versions of Moodle.

$string['auth_ldap_ad_create_req'] = 'Nelze vytvořit nový účet ve službě Active Directory. Ujistěte se, že jsou splněny všechny požadavky (LDAPS spojení, bind user má dostatečná práva apod.)';
$string['auth_ldap_attrcreators'] = 'Seznam skupin a kontextů, jejichž členové mají oprávnění vytvářet atributy. Více skupin oddělte \';\'. Obvykle něco jako \'cn=teachers,ou=staff,o=myorg\'.';
$string['auth_ldap_attrcreators_key'] = 'Tvůrce atributů';
$string['auth_ldap_auth_user_create_key'] = 'Vytvořit uživatele externě';
$string['auth_ldap_bind_dn'] = 'Chcete-li používat nějaký účet (bind-user) k vyhledání uživatelů, specifikujte jej zde. Příklad: \'cn=ldapuser,ou=public,o=org\'';
$string['auth_ldap_bind_dn_key'] = 'Jednoznačné jméno (Distinguished Name)';
$string['auth_ldap_bind_pw'] = 'Heslo pro bind-user';
$string['auth_ldap_bind_pw_key'] = 'Heslo';
$string['auth_ldap_bind_settings'] = 'Nastavení bind';
$string['auth_ldap_changepasswordurl_key'] = 'Heslo - změna URL';
$string['auth_ldap_contexts'] = 'Seznam kontextů, ve kterých se nacházejí uživatelé. Jednotlivé kontexty oddělujte středníkem. Příklad: \'ou=uzivatele,o=naseskola; ou=dalsi,o=naseskola\'';
$string['auth_ldap_contexts_key'] = 'Kontexty';
$string['auth_ldap_create_context'] = 'Povolíte-li registrování uživatelů na základě e-mailu, určete kontext, ve kterém budou noví uživatelé vytvářeni. Tento kontext by měl být z bezpečnostních důvodů odlišný od kontextu ostatních uživatelů. Není třeba přidávat tento kontext do proměnné auth_ldap_contexts, Moodle automaticky hledá uživatele i v tomto kontextu.<br /><b>Upozornění!</b>Má-li vytváření uživatelských účtů fungovat, musíte upravit funkci auth_user_create() v souboru auth/ldap/lib.php.';
$string['auth_ldap_create_context_key'] = 'Kontext pro nové uživatele';
$string['auth_ldap_create_error'] = 'Chyba při vytváření uživatele v LDAP';
$string['auth_ldap_creators'] = 'Seznam skupin, jejichž členové jsou oprávněni vytvářet nové kurzy. Jednotlivé skupiny oddělujte středníkem. Příklad: \'cn=ucitele,ou=zamestnanci,o=naseskola\'';
$string['auth_ldap_creators_key'] = 'Tvůrci';
$string['auth_ldap_expiration_desc'] = 'Zvolte Ne, chcete-li zakázat ověřování vypršelých hesel nebo čtení \'passwordexpiration time\' přímo z LDAP';
$string['auth_ldap_expiration_key'] = 'Vypršení';
$string['auth_ldap_expiration_warning_desc'] = 'Kolik dní před vypršením hesla zobrazovat varování';
$string['auth_ldap_expiration_warning_key'] = 'Varování o vypršní';
$string['auth_ldap_expireattr_desc'] = 'Volitelné: přenastavuje hodnotu LDAP atributu, ve kterém je uložen čas vypršení hesla';
$string['auth_ldap_expireattr_key'] = 'Atribut vypršení';
$string['auth_ldap_graceattr_desc'] = 'Volitelné: přenastavuje hodnotu atributu \'gracelogin\'';
$string['auth_ldap_gracelogin_key'] = 'Atribut \'gracelogin\'';
$string['auth_ldap_gracelogins_desc'] = 'Povolit podporu LDAP gracelogin (tzv. přihlášení z milosti). Uživatelé se mohou přihlásit i po vypršení hesla, dokud jim počítadlo přihlášení z milosti neklesne na 0. Uživatelé jsou v případě vypršení hesla upozorňováni.';
$string['auth_ldap_gracelogins_key'] = 'Přihlášení z milosti';
$string['auth_ldap_groupecreators'] = 'Seznam skupin a kontextů jejichž členové mají dovolenou vytvářet skupiny. Více skupin oddělte \';\'. Obvykle něco jako \'cn=teachers,ou=staff,o=myorg\'Další';
$string['auth_ldap_groupecreators_key'] = 'Tvůrci skupin';
$string['auth_ldap_host_url'] = 'Zadejte URL serveru LDAP. Například \'ldap://ldap.naseskola.cz/\' nebo \'ldaps://ldap.naseskola.cz/\'';
$string['auth_ldap_host_url_key'] = 'URL hostitele';
$string['auth_ldap_ldap_encoding'] = 'Specifikujte kódování, používané serverem LDAP. Nejpravděpodobněji utf-8, MS AD v2 implicitně používá takové platformy kódování, jako cp1252, cp1250 atd.';
$string['auth_ldap_ldap_encoding_key'] = 'Kódování LDAP';
$string['auth_ldap_login_settings'] = 'Nastavení přihlášení';
$string['auth_ldap_memberattribute'] = 'Volitelné: přenastavuje název atributu člena skupiny (user member attribute), pokud uživatel patří do skupiny. Většinou \'member\'';
$string['auth_ldap_memberattribute_isdn'] = 'Volitelné: přenastavuje manipulaci s hodnotami členství, 0 nebo 1';
$string['auth_ldap_memberattribute_isdn_key'] = 'Atribut členství (member) používá dn';
$string['auth_ldap_memberattribute_key'] = 'Atribut členství';
$string['auth_ldap_no_mbstring'] = 'Pro vytváření uživatelů v Active Directory musíte povolit rozšíření mbstring.';
$string['auth_ldap_noconnect'] = 'Modul LDAP se nemůže připojit k serveru: $a';
$string['auth_ldap_noconnect_all'] = 'LDAP modul se nemůže připojit k žádnému ze serverů: $a';
$string['auth_ldap_noextension'] = 'Varování: Zdá se, že není přítomen PHP LDAP modul. Prosím zajistěte jeho instalaci a zpřístupnění.';
$string['auth_ldap_objectclass'] = 'Volitelné: přenastavuje parametr objectClass použitý při pojmenovávání/vyhledávání uživatelů. Většinou nemusíte měnit.';
$string['auth_ldap_objectclass_key'] = 'Třída objektu';
$string['auth_ldap_opt_deref'] = 'Určuje chování aliasů během vyhledávání. Vyberte jednu z následujících hodnot: \"Ne\" (LDAP_DEREF_NEVER) nebo \"Ano\" (LDAP_DEREF_ALWAYS)';
$string['auth_ldap_opt_deref_key'] = 'Zrušit vazby s aliasy';
$string['auth_ldap_passtype'] = 'Specifikujte formát nového nebo změněného hesla na LDAP serveru.';
$string['auth_ldap_passtype_key'] = 'Formát hesla';
$string['auth_ldap_passwdexpire_settings'] = 'Nastavení vypršení hesla LDAP';
$string['auth_ldap_preventpassindb'] = 'Má se zabránit ukládání hesel v databázi Moodlu? Zvolíte-li \"ano\", nebudou hesla v databázi ukládána.';
$string['auth_ldap_preventpassindb_key'] = 'Skrýt hesla';
$string['auth_ldap_search_sub'] = 'Prohledávat uživatele v subkontextech.';
$string['auth_ldap_search_sub_key'] = 'Prohledávat subkontexty.';
$string['auth_ldap_server_settings'] = 'Nastavení serveru LDAP';
$string['auth_ldap_unsupportedusertype'] = 'Ověřování: ldap user_create() nepodporuje zvolený typ uživatele:\"$a\"';
$string['auth_ldap_update_userinfo'] = 'Aktualizovat informace o uživateli (příjmení, křestní jméno, adresa...) ze serveru LDAP do Moodlu. Dle potřeby definujte \'Mapování dat\'.';
$string['auth_ldap_user_attribute'] = 'Volitelné: přenastavuje atribut použitý pro pojmenování a vyhledávání uživatelů. Většinou \'cn\'.';
$string['auth_ldap_user_attribute_key'] = 'Atribut uživatele';
$string['auth_ldap_user_exists'] = 'Toto uživatelské jméno již v LDAP existuje';
$string['auth_ldap_user_settings'] = 'Nastavení prohledávání uživatelů';
$string['auth_ldap_user_type'] = 'Vyberte, jak jsou uživatelé ukládáni v LDAP. Toto nastavení zároveň určuje, jak se bude chovat vypršení hesla (login expiration), přihlášení z milosti (grace logins) a tvorba uživatelů.';
$string['auth_ldap_user_type_key'] = 'Typ uživatele';
$string['auth_ldap_usertypeundefined'] = 'config.user_type není definován nebo funkce  ldap_expirationtime2unix zvloený typ nepodporuje!';
$string['auth_ldap_usertypeundefined2'] = 'config.user_type není definován nebo funkce  ldap_expirationtime2unix zvloený typ nepodporuje!';
$string['auth_ldap_version'] = 'Verze protokolu LDAP, kterou používá váš server.';
$string['auth_ldap_version_key'] = 'Verze';
$string['auth_ldapdescription'] = 'Tato metoda poskytuje ověření uživatele proti serveru LDAP. Je-li zadané jméno a heslo platné, Moodle si vytvoří nový záznam o uživateli ve své vlastní databázi. Tento modul umí načíst informace ze serveru LDAP a přednastavit požadované pole v Moodlu. Při dalším přihlašování se již pouze ověřuje uživatelské jméno a heslo.';
$string['auth_ldapextrafields'] = 'Tato pole jsou volitelná. Můžete vybrat, která pole s informacemi ze <b>serveru LDAP</b> budou použita jako přednastavená v Moodlu. <p>Necháte-li pole prázdná, nepřevezmou se žádné údaje z LDAP a Moodle použije vlastní přednastavené hodnoty. </p><p>V každém případě si uživatel může tyto hodnoty měnit po přihlášení sám.</p>';
$string['auth_ldapnotinstalled'] = 'Nelze použít ověření LDAP. PHP LDAP modul není nainstalován.';
$string['auth_ldaptitle'] = 'LDAP';
$string['auth_ntlmsso'] = 'NTLM SSO';
$string['auth_ntlmsso_enabled'] = 'Zda se má povolit SSO přihlašování pomocí účtu v doméně NTLM. <strong>Pozor:</strong> tato metoda vyžaduje další konfiguraci na straně webového serveru. Podrobnosti jsou uvedeny v <a href=\"http://docs.moodle.org/en/NTLM_authentication\">dokumentaci</a>.';
$string['auth_ntlmsso_enabled_key'] = 'Povolit';
$string['auth_ntlmsso_ie_fastpath'] = 'Pokud vaši uživatelé používají pouze MS Internet Explorer, můžete zde nastavit \"ano\" a urychlit tak průběh ověřování.';
$string['auth_ntlmsso_ie_fastpath_key'] = 'Pouze MS IE';
$string['auth_ntlmsso_subnet'] = 'Je-li nastaveno, dojde k ověření pomocí NTLM SSO pouze u klientů v dané podsíti. Formát: xxx.xxx.xxx.xxx/bitmask';
$string['auth_ntlmsso_subnet_key'] = 'Podsíť';
$string['ntlmsso_attempting'] = 'Pokouším se o automatické přihlášení přes NTLM ...';
$string['ntlmsso_failed'] = 'Automatické přihlášení selhalo, zkuste normální přihlašovací stránku...';
$string['ntlmsso_isdisabled'] = 'NTLM SSO je vypnuto';