<?PHP // $Id$ 
      // auth.php - created with Moodle 1.5.2 + (2005060223)


$string['alternatelogin'] = 'Pokud sem vložíte nějaké URL, bude použito jako přihlašovací stránka k tomuto systému. Tato vaše stránka by měla obsahovat formulář s vlastností \'action\' nastavenou na <strong>\'$a\'</strong>, který vrací pole <strong>username</strong> a <strong>password</strong>.<br />Dbejte na to, abyste vložili platné URL! V opačném případě byste mohli komukoliv včetně sebe zamezit přístupu k těmto stránkám.<br />Chcete-li používat standardní přihlašovací stránku, nechejte toto pole prázdné.';
$string['alternateloginurl'] = 'URL vlastního přihlášení';
$string['auth_cas_baseuri'] = 'URI serveru (nebo nic, pokud není baseUri)<br />Je-li např. CAS server dostupný na  host.domena.cz/CAS/ pak nastavte<br />cas_baseuri = CAS/';
$string['auth_cas_create_user'] = 'Zapněte tuto volbu, chcete-li vkládat uživatele ověřené pomocí CAS do vaší databáze uživatelů Moodlu. V opačném případě se budou moci přihlásit pouze uživatelé, kteří již mají záznam v databázi Moodlu.';
$string['auth_cas_enabled'] = 'Zapněte tuto volbu, chcete-li používat CAS ověření.';
$string['auth_cas_hostname'] = 'Název hostitele (hostname) serveru CAS<br />např.: host.domena.cz';
$string['auth_cas_invalidcaslogin'] = 'Je mi líto, ale vaše přihlášení selhalo. Nebylo možno vás ověřit';
$string['auth_cas_language'] = 'Vybraný jazyk';
$string['auth_cas_logincas'] = 'Přístup po zašifrovaném spojení';
$string['auth_cas_port'] = 'Port CAS serveru';
$string['auth_cas_server_settings'] = 'Konfigurace CAS serveru';
$string['auth_cas_text'] = 'Zašifrované spojení';
$string['auth_cas_version'] = 'Verze CAS';
$string['auth_casdescription'] = 'Tato metoda používá pro ověření uživatelů server CAS (Central Authentication Service) v prostředí Single Sign On (SSO). Můžete rovněž použít jednoduché LDAP ověřování. Je-li zadané uživatelské jméno a heslo platné na serveru CAS, Moodle si vytvoří nový záznam pro příslušného uživatele a případně načte další atributy z LDAP serveru. Při dalším přihlášení se již kontroluje pouze jméno a heslo.';
$string['auth_castitle'] = 'Používat CAS server (SSO)';
$string['auth_common_settings'] = 'Společné nastavení';
$string['auth_data_mapping'] = 'Mapování dat';
$string['auth_dbdescription'] = 'Tato metoda používá tabulku v externí databázi ke kontrole, zda zadané uživatelské jméno a heslo je platné.  Při vytváření nového účtu mohou být informace z dalších polí zkopírovány do databáze Moodle.';
$string['auth_dbextrafields'] = 'Tato pole jsou volitelná. Můžete si zvolit přednastavení některých informací o uživateli na základě hodnot v <b>polích externí databáze</b>, která určíte zde.<p>Necháte-li tato pole prázdná, budou použity implicitní hodnoty.<p>Tak jako tak si uživatel po přihlášení může tato pole měnit.</p>';
$string['auth_dbfieldpass'] = 'Název pole, které obsahuje hesla';
$string['auth_dbfielduser'] = 'Název pole, které obsahuje uživatelské jména';
$string['auth_dbhost'] = 'Počítač hostující databázi';
$string['auth_dbname'] = 'Název databáze';
$string['auth_dbpass'] = 'Heslo k tomuto uživatelskému jménu';
$string['auth_dbpasstype'] = 'Určete použitý formát pole s heslem. Šifrování MD5 je užitečné při připojování k dalším webovým aplikacím, jako je například PostNuke';
$string['auth_dbtable'] = 'Název tabulky v databázi';
$string['auth_dbtitle'] = 'Používat externí databázi';
$string['auth_dbtype'] = 'Typ databáze (Viz <a href=\"../lib/adodb/readme.htm#drivers\">ADOdb dokumentaci</a>)';
$string['auth_dbuser'] = 'Uživatelské jméno s právy číst externí databázi';
$string['auth_emaildescription'] = 'Potvrzení emailem je přednastavená metoda ověřování. Při registraci si uživatel vybere vlastní uživatelské jméno a heslo. Poté je na jeho adresu odeslán email obsahující zabezpečený odkaz na stránku, kde potvrdí zadané údaje. Při dalším přihlášení se již ověřuje pouze zadané uživatelské jméno a heslo proti hodnotě uložené v databázi Moodle.';
$string['auth_emailtitle'] = 'Ověření na základě emailu';
$string['auth_fccreators'] = 'Seznam skupin, jejichž členové jsou oprávněni vytvářet nové kurzy. Skupiny oddělujte středníkem. Názvy musí být zadány přesně jako na FirstClass serveru a záleží na malých/VELKÝCH písmenech.';
$string['auth_fcdescription'] = 'Tato metoda používá k ověřovaní uživatelského jména a hesla FirstClass server.';
$string['auth_fcfppport'] = 'Port na serveru (nejběžnější je 3333)';
$string['auth_fchost'] = 'Adresa serveru FirstClass. Vložte IP adresu nebo DNS název.';
$string['auth_fcpasswd'] = 'Heslo pro účet uvedený výše.';
$string['auth_fctitle'] = 'Používat FirstClass server';
$string['auth_fcuserid'] = 'Userid pro FirstClass účet s nastaveným právem \'Subadministrator\'';
$string['auth_fieldlock'] = 'Uzamknout hodnotu';
$string['auth_fieldlock_expl'] = '<p><b>Uzamknout hodnotu:</b> Je-li povoleno, zabrání se uživatelům i správcům měnit hodnotu pole přímo. Použijte tuto volbu, pokud udržujete tyto údaje v externím systému.</p>';
$string['auth_fieldlocks'] = 'Uzamknout pole uživatelů';
$string['auth_fieldlocks_help'] = '<p>Máte možnost uzamknout pole s údaji o uživatelích. To je užitečné, pokud jako správce udržujete tyto údaje ručně a/nebo nahráváním údajů pomocí funkce \'Načíst uživatele\'. Pokud zamknete pole, která Moodle vyžaduje, ujistěte se, že poskytujete potřebná data při vytváření nových účtů &emdash; jinak budou účty nepouživatelné.</p><p>Chcete-li předejít tomuto problému, zvažte možnost režimu \'Odemknuto, je-li pole prázdné\'.</p>';
$string['auth_imapdescription'] = 'Tato metoda používá server IMAP ke kontrole, zda je zadané uživatelské jméno a heslo platné.';
$string['auth_imaphost'] = 'Adresa serveru IMAP. Zadejte IP adresu, nikoliv DNS jméno serveru!';
$string['auth_imapport'] = 'Číslo portu IMAP serveru. Většinou bývá 143 nebo 993.';
$string['auth_imaptitle'] = 'Používat IMAP server';
$string['auth_imaptype'] = 'Typ IMAP serveru. IMAP servery mohou mít různé typy ověřování a vyjednávání (IMAP authentication and negotiation).';
$string['auth_ldap_bind_dn'] = 'Chcete-li používat nějaký účet (bind-user) k vyhledání uživatelů, specifikujte jej zde. Příklad: \'cn=ldapuser,ou=public,o=org\'';
$string['auth_ldap_bind_pw'] = 'Heslo pro bind-user';
$string['auth_ldap_bind_settings'] = 'Nastavení bind';
$string['auth_ldap_contexts'] = 'Seznam kontextů, ve kterých se nacházejí uživatelé. Jednotlivé kontexty oddělujte středníkem. Příklad: \'ou=uzivatele,o=naseskola; ou=dalsi,o=naseskola\'';
$string['auth_ldap_create_context'] = 'Povolíte-li vytváření uživatelů (po ověření emailem), určete kontext, ve kterém budou noví uživatelé vytvářeni. Tento kontext by měl být z bezpečnostních důvodů odlišný od kontextu ostatních uživatelů. Není třeba přidávat tento kontext do proměnné auth_ldap_contexts, Moodle automaticky hledá uživatele i v tomto kontextu.';
$string['auth_ldap_creators'] = 'Seznam skupin, jejichž členové jsou oprávněni vytvářet nové kurzy. Jednotlivé skupiny oddělujte středníkem. Příklad: \'cn=ucitele,ou=zamestnanci,o=naseskola\'';
$string['auth_ldap_expiration_desc'] = 'Zvolte Ne, chcete-li zakázat ověřování vypršelých hesel nebo čtení \'passwordexpiration time\' přímo z LDAP';
$string['auth_ldap_expiration_warning_desc'] = 'Kolik dní před vypršením hesla zobrazovat varování';
$string['auth_ldap_expireattr_desc'] = 'Volitelné: LDAP atribut, ve kterém je uložen čas vypršení hesla';
$string['auth_ldap_graceattr_desc'] = 'Volitelné: atribut \'gracelogin\'';
$string['auth_ldap_gracelogins_desc'] = 'Povolit podporu LDAP gracelogin (tzv. přihlášení z milosti). I poté, co jim vypršelo heslo, se mohou uživatelé přihlásit, dokud jim počítadlo přihlášení z milosti neklesne na 0. Uživatelé jsou v případě vypršení hesla upozorňováni.';
$string['auth_ldap_host_url'] = 'Zadejte URL serveru LDAP. Například \'ldap://ldap.naseskola.cz/\' nebo \'ldaps://ldap.naseskola.cz/\' ';
$string['auth_ldap_login_settings'] = 'Nastavení přihlášení';
$string['auth_ldap_memberattribute'] = 'Volitelné: přenastavuje název atributu člena skupiny (user member attribute), pokud uživatel patří do skupiny. Většinou \'member\'';
$string['auth_ldap_objectclass'] = 'Volitelné: parametr objectClass použitý při pojmenovávání/vyhledávání uživatelů. Většinou nemusíte měnit.';
$string['auth_ldap_opt_deref'] = 'Určuje chování aliasů během vyhledávání. Vyberte jednu z následujících hodnot: \"Ne\" (LDAP_DEREF_NEVER) nebo \"Ano\" (LDAP_DEREF_ALWAYS)';
$string['auth_ldap_passwdexpire_settings'] = 'Nastavení vypršení hesla LDAP';
$string['auth_ldap_preventpassindb'] = 'Má se zabránit ukládání hesel v databázi Moodlu? Zvolíte-li \"ano\", nebudou hesla v databázi ukládána.';
$string['auth_ldap_search_sub'] = 'Prohledávat uživatele v subkontextech.';
$string['auth_ldap_server_settings'] = 'Nastavení serveru LDAP';
$string['auth_ldap_update_userinfo'] = 'Aktualizovat informace o uživateli (příjmení, křestní jméno, adresa...) z LDAP serveru do Moodle. Dle potřeby definujte \'Mapování dat\'.';
$string['auth_ldap_user_attribute'] = 'Volitelné: atribut použitý pro pojmenování a vyhledávání uživatelů. Většinou \'cn\'.';
$string['auth_ldap_user_settings'] = 'Nastavení prohledávání uživatelů';
$string['auth_ldap_user_type'] = 'Vyberte, jak jsou uživatelé ukládáni v LDAP. Toto nastavení zároveň určuje, jak se bude chovat vypršení hesla (login expiration), přihlášení z milosti (grace logins) a tvorba uživatelů.';
$string['auth_ldap_version'] = 'Verze protokolu LDAP, kterou používá váš server.';
$string['auth_ldapdescription'] = 'Tato metoda poskytuje ověření uživatele proti LDAP serveru.  Je-li zadané jméno a heslo platné, Moodle si vytvoří nový záznam o uživateli ve své vlastní databázi. Tento modul umí načíst informace z LDAP serveru a přednastavit požadované pole v Moodle. Při dalším přihlašování se již pouze ověřuje uživatelské jméno a heslo.';
$string['auth_ldapextrafields'] = 'Tato pole jsou volitelná. Můžete vybrat, která pole s informacemi z <b>LDAP serveru</b> budou použita jako přednastavená v Moodle. <p>Necháte-li pole prázdná, nepřevezmou se žádné údaje z LDAP a Moodle použije vlastní přednastavené hodnoty. </p><p>V každém případě si uživatel může tyto hodnoty měnit po přihlášení sám.</p>';
$string['auth_ldaptitle'] = 'Používat LDAP server';
$string['auth_manualdescription'] = 'Tato metoda neumožňuje uživatelům zakládat si vlastní účty. Všechny účty musí být ručně vytvořeny správcem Moodle (admin).';
$string['auth_manualtitle'] = 'Pouze ručně vytvářené účty';
$string['auth_multiplehosts'] = 'Můžete vložit i více hostitelů NEBO jejich adres (např. \'server1.cz;server2.cz;server3.com\' nebo \'xxx.xxx.xxx.xxx;xxx.xxx.xxx.xxx\')';
$string['auth_nntpdescription'] = 'Tato metoda používá NNTP server ke kontrole, zda je zadané uživatelské jméno a heslo platné.';
$string['auth_nntphost'] = 'Adresa NNTP serveru. Zadejte IP adresu, nikoliv DNS název!';
$string['auth_nntpport'] = 'Číslo portu NNTP serveru (většinou 119)';
$string['auth_nntptitle'] = 'Používat NNTP serveru';
$string['auth_nonedescription'] = 'Uživatelé si mohou vytvářet nová konta přímo bez ověření vůči externímu serveru nebo potvrzení přes email. S touto volbou buďte opatrní - zvažte možné problémy se zabezpečením a správou uživatelů, které vám tato volba může způsobit.';
$string['auth_nonetitle'] = 'Bez ověření';
$string['auth_pamdescription'] = 'Tato metoda využívá modul PAM pro přístup k nativním uživatelským jménům na tomto serveru. Chcete-li tuto metodu používat, musíte si nainstalovat <a href=\"http://www.math.ohio-state.edu/~ccunning/pam_auth/\" target=\"_blank\">PHP4 PAM Authentication</a>.';
$string['auth_pamtitle'] = 'PAM (Pluggable Authentication Modules)';
$string['auth_passwordisexpired'] = 'Vaše heslo vypršelo. Chcete si jej teď změnit?';
$string['auth_passwordwillexpire'] = 'Počet dnů do vypršení hesla: $a. Chcete si své heslo změnit?';
$string['auth_pop3description'] = 'Tato metoda používá POP3 server ke kontrole, zda zadané uživatelské jméno a heslo je platné.';
$string['auth_pop3host'] = 'Adresa POP3 serveru. Zadejte IP adresu, nikoliv DNS název!';
$string['auth_pop3mailbox'] = 'Název poštovní složky (mailbox), se kterou se má navázat spojení (většinou INBOX).';
$string['auth_pop3port'] = 'Číslo portu POP3 serveru (většinou 110)';
$string['auth_pop3title'] = 'Používat POP3 server';
$string['auth_pop3type'] = 'Typ serveru. Pokud váš server používá zabezpečení pomocí certifikátů, zvolte pop3cert.';
$string['auth_shib_convert_data'] = 'API pro úpravu dat';
$string['auth_shib_convert_data_description'] = 'Toto API (aplikační rozhraní) vám umožňuje dále upravovat data, která máte k dispozici ze systému Shibboleth. Více infomací <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">zde</a>.';
$string['auth_shib_convert_data_warning'] = 'Soubor buď neexistuje, nebo k němu nemá proces webového serveru přístup ke čtení!';
$string['auth_shib_instructions'] = 'Použijte <a href=\"$a\">přihlášení se přes Shibboleth</a>, pakliže vaše instituce tento systém podporuje.<br />V opačném případě použijte normální formulář pro přihlášení.';
$string['auth_shib_instructions_help'] = 'Zde můžete vložit vlastní informace o vašem systému Shibboleth. Budou se zobrazovat na přihlašovací stránce. Vložené informace by měly obsahovat odkaz na zdroj chráněný systémem Shibboleth, který přesměruje uživatele na \"<b>$a</b>\", takže se uživatelé systému Shibboleth budou moci přihlásit do Moodlu. Necháte-li toto pole prázdné, budou se na přihlašovací stránce zobrazovat obecné pokyny.';
$string['auth_shib_only'] = 'Pouze Shibboleth';
$string['auth_shib_only_description'] = 'Zaškrtněte tuto volbu, chcete-li si vynutit přihlášení pomocí systému Shibboleth';
$string['auth_shib_username_description'] = 'Název proměnné prostředí webserveru Shibboleth, která má být použita jako Moodlovské uživatelské jméno';
$string['auth_shibboleth_login'] = 'Přihlášení přes Shibboleth';
$string['auth_shibboleth_manual_login'] = 'Ruční přihlášení';
$string['auth_shibbolethdescription'] = 'Tato metoda umožňuje vytvářet a ověřovat uživatele pomocí systému <a href=\"http://shibboleth.internet2.edu/\" target=\"_blank\">Shibboleth</a>.<br>Ujistěte se, že jste si přečetli soubor <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">README</a> obsahující informace o tom, jak nastavit váš Moodle pro podporu systému Shibboleth.';
$string['auth_shibbolethtitle'] = 'Shibboleth';
$string['auth_updatelocal'] = 'Aktualizovat lokální data';
$string['auth_updatelocal_expl'] = '<p><b>Aktualizovat lokální data:</b> Je-li povoleno, budou pole aktualizována (z externího autentizačního zdroje) po každém přihlášení nebo při synchronizaci uživatelů. Pole určená k místní aktualizaci by měla být uzamknuta.</p>';
$string['auth_updateremote'] = 'Aktualizovat externí data';
$string['auth_updateremote_expl'] = '<p><b>Aktualizovat externí data:</b> Je-li povoleno, provede se aktualizace externího autentizačního zdroje po každém uložení profilu uživatele. Pole by měla být odemknuta, aby je bylo možné upravovat.</p>';
$string['auth_updateremote_ldap'] = '<p><b>Pozn.:</b> Aktualizace externího zdroje LDAP vyžaduje, aby měl uživatel \'binddn\' (s heslem \'bindpw\') oprávnění editovat všechny záznamy o uživatelích. Tento systém momentálně nepodporuje atributy s více hodnotami (multi-values) - extra hodnoty budou proto při aktualizaci odstraněny.</p>';
$string['auth_user_create'] = 'Povolit vytváření uživatelů';
$string['auth_user_creation'] = 'Noví (anonymní) uživatelé si mohou zakládat uživatelský účet v externím zdroji a potvrdit jej přes email. Pokud toto povolíte, nezapomeňte nakonfigurovat nastavení pro daný externí zdroj týkající se vytváření nových uživatelů.';
$string['auth_usernameexists'] = 'Zvolené uživatelské jméno již existuje. Prosím, vyberte si jiné.';
$string['authenticationoptions'] = 'Možnosti ověření';
$string['authinstructions'] = 'Zde můžete zadat instrukce pro vaše uživatele, aby věděli, které uživatelské jméno a heslo mají použít. Tento text se objeví na přihlašovací stránce. Necháte-li toto pole prázdné, nebudou zobrazeny žádné instrukce.';
$string['changepassword'] = 'URL ke změně hesla';
$string['changepasswordhelp'] = 'Zde můžete určit URL, na kterém si vaši uživatelé mohou obnovit heslo nebo změnit své uživatelské jméno, pokud jej zapomněli. URL bude uživatelům poskytnuto jako tlačitko na přihlašovací a osobní stránce. Necháte-li toto pole prázdné, nebude toto tlačítko zobrazováno.';
$string['chooseauthmethod'] = 'Vyberte si způsob ověření uživatelů: ';
$string['createchangepassword'] = 'Vytvořit, pokud chybí - vnutit změny';
$string['createpassword'] = 'Vytvořit, pokud chybí';
$string['forcechangepassword'] = 'Vynutit změnu hesla';
$string['forcechangepassword_help'] = 'Vynutit změnu hesla při příštím přihlášení do Moodlu.';
$string['forcechangepasswordfirst_help'] = 'Vynutit změnu hesla při prvním přihlášení do Moodlu.';
$string['guestloginbutton'] = 'Tlačítko pro hosta';
$string['infilefield'] = 'Pole je v souboru požadované';
$string['instructions'] = 'Pokyny';
$string['locked'] = 'Uzamknuto';
$string['md5'] = 'MD5 šifra';
$string['passwordhandling'] = 'Ukládat pole s heslem jako';
$string['plaintext'] = 'Čistý text';
$string['showguestlogin'] = 'Na přihlašovací stránce můžete skrýt nebo ukázat tlačítko pro přihlášení se jako host.';
$string['stdchangepassword'] = 'Použij standardní stránku \'Změna hesla\'';
$string['stdchangepassword_expl'] = 'Pokud váš externí autentizační systém umožňuje změnu hesla přes Moodle, přepněte na Ano. Tímto potlačíte hodnotu \'URL ke změně hesla\'';
$string['stdchangepassword_explldap'] = 'Pozn.: Pokud používáte vzdálený LDAP server, doporučujeme vám komunikovat přes šifrované SSL spojení (ldaps://)';
$string['unlocked'] = 'Odemknuto';
$string['unlockedifempty'] = 'Odemknuto, je-li pole prázdné';
$string['update_never'] = 'Nikdy';
$string['update_oncreate'] = 'Při vytváření';
$string['update_onlogin'] = 'Při každém přihlášení';
$string['update_onupdate'] = 'Při aktualizaci';

?>
