<?PHP // $Id$ 
      // auth.php - created with Moodle 1.6 Beta 5 (2006050500)


$string['alternatelogin'] = 'Pokud sem vložíte URL, použije se jako přihlašovací stránka k této instalaci Moodlu. Tato vaše stránka by měla obsahovat formulář, který bude mít atribut \'action\' nastaven na <strong>\'$a\'</strong> a který vrací pole <strong>username</strong> a <strong>password</strong>.<br />Dbejte na to, abyste vložili platné URL! V opačném případě byste mohli všem včetně sebe zamezit v přístupu ke stránkám.<br />Chcete-li používat standardní přihlašovací stránku, nechejte toto pole prázdné.';
$string['alternateloginurl'] = 'URL vlastního přihlášení';
$string['auth_cas_baseuri'] = 'URI serveru (nevyplňujte, pokud se baseUri neuplatňuje)<br />Příklad: je-li server CAS dostupný na host.domena.cz/CAS/, nastavte<br />cas_baseuri = CAS/';
$string['auth_cas_create_user'] = 'Zapněte tuto volbu, chcete-li vkládat uživatele ověřené pomocí CAS do vaší databáze uživatelů Moodlu. V opačném případě se budou moci přihlásit pouze uživatelé, kteří již mají záznam v databázi Moodlu.';
$string['auth_cas_enabled'] = 'Zapněte tuto volbu, chcete-li používat ověření CAS.';
$string['auth_cas_hostname'] = 'Název hostitele (hostname) serveru CAS<br />např.: host.domena.cz';
$string['auth_cas_invalidcaslogin'] = 'Je mi líto, ale vaše přihlášení selhalo. Nebylo možno vás ověřit';
$string['auth_cas_language'] = 'Vybraný jazyk';
$string['auth_cas_logincas'] = 'Přístup prostřednictvím šifrovaného spojení';
$string['auth_cas_port'] = 'Port  serveru CAS';
$string['auth_cas_server_settings'] = 'Konfigurace serveru CAS';
$string['auth_cas_text'] = 'Šifrované spojení';
$string['auth_cas_version'] = 'Verze CAS';
$string['auth_casdescription'] = 'Tato metoda používá pro ověření uživatelů server CAS (Central Authentication Service) v prostředí Single Sign On (SSO). Můžete rovněž použít jednoduché LDAP ověřování. Je-li zadané uživatelské jméno a heslo podle serveru CAS platné, Moodle si vytvoří nový záznam pro příslušného uživatele a případně načte další atributy ze serveru LDAP. Při dalším přihlášení se již kontroluje pouze jméno a heslo.';
$string['auth_castitle'] = 'Používat server CAS (SSO)';
$string['auth_changepasswordhelp'] = 'Pokyny ke změně hesla';
$string['auth_changepasswordhelp_expl'] = 'Zobrazit pokyny ke změně $a hesla. Tento text se buď a) zobrazí současně s <strong>URL pro změnu hesla</strong> či s interní stránkou Moodlu pro změnu hesla, nebo se b) zobrazí namísto <strong>URL pro změnu hesla</strong> či interní stránky Moodlu pro změnu hesla.';
$string['auth_changepasswordurl'] = 'URL pro změnu hesla';
$string['auth_changepasswordurl_expl'] = 'Zadejte URL, kam mají být přesměrováni uživatelé požadující změnu svého $a hesla. U volby <strong>Použij standardní stránku \'Změna hesla\'</strong> výše vyberte <strong>Ne</strong>.';
$string['auth_common_settings'] = 'Společná nastavení';
$string['auth_data_mapping'] = 'Mapování dat';
$string['auth_dbdescription'] = 'Tato metoda používá k ověření platnosti zadaného uživatelského jména a hesla tabulku v externí databázi. Při vytváření nového účtu mohou být informace z dalších polí zkopírovány do databáze Moodu.';
$string['auth_dbextrafields'] = 'Tato pole jsou volitelná. Údaje z <b>polí externí databáze</b>, která zde určíte, budou přeneseny do databáze uživatelů Moodlu.<p>Necháte-li tato pole prázdná, budou použity implicitní hodnoty.<p>Nezávisle na tomto nastavení mají po přihlášení uživatelé možnost upravit údaje ve všech zde uvedených polích.</p>';
$string['auth_dbfieldpass'] = 'Název pole, které obsahuje hesla';
$string['auth_dbfielduser'] = 'Název pole, které obsahuje uživatelské jména';
$string['auth_dbhost'] = 'Počítač hostující databázi';
$string['auth_dbname'] = 'Název databáze';
$string['auth_dbpass'] = 'Heslo k tomuto uživatelskému jménu';
$string['auth_dbpasstype'] = 'Určete formát pole s heslem. Šifrování MD5 je vhodné při připojování k dalším webovým aplikacím, jako je například PostNuke.</p><p>Možnost \'Interní\' vyberte v případě, že chcete externí databázi svěřit správu uživatelských jmen a e-mailových adres, a Moodlu správu hesel. Použijete-li možnost \'Interní\', pole s e-mailovými adresami <i>musí</i> být v externí databázi vyplněno a je nutné pravidelně spouštět skript auth/db/cron.php. Moodle zašle novým uživatelům e-mail obsahující dočasné heslo.</p>';
$string['auth_dbtable'] = 'Název tabulky v databázi';
$string['auth_dbtitle'] = 'Používat externí databázi';
$string['auth_dbtype'] = 'Typ databáze (Viz <a href=\"../lib/adodb/readme.htm#drivers\">dokumentaci k ADOdb</a>)';
$string['auth_dbuser'] = 'Uživatelské jméno s právy číst externí databázi';
$string['auth_emaildescription'] = 'Ověření na základě e-mailu je výchozí metoda ověřování. Při registraci si uživatel vybere vlastní uživatelské jméno a heslo. Poté je na jeho adresu odeslán e-mail obsahující zabezpečený odkaz na stránku, kde potvrdí zadané údaje. Při dalším přihlášení se již ověřuje pouze zadané uživatelské jméno a heslo proti údajům uloženým v databázi Moodlu.';
$string['auth_emailtitle'] = 'Ověření na základě e-mailu';
$string['auth_fccreators'] = 'Seznam skupin, jejichž členové jsou oprávněni vytvářet nové kurzy. Skupiny oddělujte středníkem. Názvy musejí být zadány přesně jako na serveru FirstClass, rozlišují se malá/VELKÁ písmena.';
$string['auth_fcdescription'] = 'Tato metoda používá k ověřování uživatelského jména a hesla server FirstClass.';
$string['auth_fcfppport'] = 'Port na serveru (nejběžnější je 3333)';
$string['auth_fchost'] = 'Adresa serveru FirstClass. Vložte IP adresu nebo doménové jméno.';
$string['auth_fcpasswd'] = 'Heslo pro účet uvedený výše.';
$string['auth_fctitle'] = 'Používat server FirstClass';
$string['auth_fcuserid'] = 'Userid pro účet FirstClass s nastaveným právem \'Subadministrator\'';
$string['auth_fieldlock'] = 'Uzamknout hodnotu';
$string['auth_fieldlock_expl'] = '<p><b>Uzamknout hodnotu:</b> Je-li vybrána tato možnost, zabrání se uživatelům i správcům měnit hodnotu pole přímo. Použijte tuto volbu, pokud udržujete tyto údaje v externím systému.</p>';
$string['auth_fieldlocks'] = 'Uzamknout pole uživatelů';
$string['auth_fieldlocks_help'] = '<p>Máte možnost uzamknout pole s údaji o uživatelích. To je užitečné, pokud jako správce udržujete tyto údaje ručně a/nebo nahráváním údajů pomocí funkce \'Načíst uživatele\'. Pokud zamknete pole, která Moodle vyžaduje, ujistěte se, že poskytujete potřebná data při vytváření nových účtů – jinak budou účty nepoužitelné.</p><p>Chcete-li předejít tomuto problému, zvažte možnost režimu \'Odemknuto, je-li pole prázdné\'.</p>';
$string['auth_imapdescription'] = 'Tato metoda používá k ověření platnosti zadaného uživatelského jména a hesla server IMAP.';
$string['auth_imaphost'] = 'Adresa serveru IMAP. Zadejte IP adresu, nikoliv doménové jméno serveru!';
$string['auth_imapport'] = 'Číslo portu serveru IMAP, obvykle 143 nebo 993.';
$string['auth_imaptitle'] = 'Používat server IMAP';
$string['auth_imaptype'] = 'Typ serveru IMAP. Servery IMAP mohou používat různé typy ověřování a komunikace (IMAP authentication and negotiation).';
$string['auth_ldap_bind_dn'] = 'Chcete-li používat nějaký účet (bind-user) k vyhledání uživatelů, specifikujte jej zde. Příklad: \'cn=ldapuser,ou=public,o=org\'';
$string['auth_ldap_bind_pw'] = 'Heslo pro bind-user';
$string['auth_ldap_bind_settings'] = 'Nastavení bind';
$string['auth_ldap_contexts'] = 'Seznam kontextů, ve kterých se nacházejí uživatelé. Jednotlivé kontexty oddělujte středníkem. Příklad: \'ou=uzivatele,o=naseskola; ou=dalsi,o=naseskola\'';
$string['auth_ldap_create_context'] = 'Povolíte-li vytváření uživatelů metodou ověření na základě e-mailu, určete kontext, ve kterém budou noví uživatelé vytvářeni. Tento kontext by měl být z bezpečnostních důvodů odlišný od kontextu ostatních uživatelů. Není třeba přidávat tento kontext do proměnné auth_ldap_contexts, Moodle automaticky hledá uživatele i v tomto kontextu.<br /><b>Upozornění!</b>Má-li vytváření uživatelských účtů fungovat, musíte upravit funkci auth_user_create() v souboru auth/ldap/lib.php.';
$string['auth_ldap_creators'] = 'Seznam skupin, jejichž členové jsou oprávněni vytvářet nové kurzy. Jednotlivé skupiny oddělujte středníkem. Příklad: \'cn=ucitele,ou=zamestnanci,o=naseskola\'';
$string['auth_ldap_expiration_desc'] = 'Zvolte Ne, chcete-li zakázat ověřování vypršelých hesel nebo čtení \'passwordexpiration time\' přímo z LDAP';
$string['auth_ldap_expiration_warning_desc'] = 'Kolik dní před vypršením hesla zobrazovat varování';
$string['auth_ldap_expireattr_desc'] = 'Volitelné: přenastavuje hodnotu LDAP atributu, ve kterém je uložen čas vypršení hesla';
$string['auth_ldap_graceattr_desc'] = 'Volitelné: přenastavuje hodnotu atributu \'gracelogin\'';
$string['auth_ldap_gracelogins_desc'] = 'Povolit podporu LDAP gracelogin (tzv. přihlášení z milosti). Uživatelé se mohou přihlásit i po vypršení hesla, dokud jim počítadlo přihlášení z milosti neklesne na 0. Uživatelé jsou v případě vypršení hesla upozorňováni.';
$string['auth_ldap_host_url'] = 'Zadejte URL serveru LDAP. Například \'ldap://ldap.naseskola.cz/\' nebo \'ldaps://ldap.naseskola.cz/\' ';
$string['auth_ldap_login_settings'] = 'Nastavení přihlášení';
$string['auth_ldap_memberattribute'] = 'Volitelné: přenastavuje název atributu člena skupiny (user member attribute), pokud uživatel patří do skupiny. Většinou \'member\'';
$string['auth_ldap_objectclass'] = 'Volitelné: přenastavuje parametr objectClass použitý při pojmenovávání/vyhledávání uživatelů. Většinou nemusíte měnit.';
$string['auth_ldap_opt_deref'] = 'Určuje chování aliasů během vyhledávání. Vyberte jednu z následujících hodnot: \"Ne\" (LDAP_DEREF_NEVER) nebo \"Ano\" (LDAP_DEREF_ALWAYS)';
$string['auth_ldap_passwdexpire_settings'] = 'Nastavení vypršení hesla LDAP';
$string['auth_ldap_preventpassindb'] = 'Má se zabránit ukládání hesel v databázi Moodlu? Zvolíte-li \"ano\", nebudou hesla v databázi ukládána.';
$string['auth_ldap_search_sub'] = 'Prohledávat uživatele v subkontextech.';
$string['auth_ldap_server_settings'] = 'Nastavení serveru LDAP';
$string['auth_ldap_update_userinfo'] = 'Aktualizovat informace o uživateli (příjmení, křestní jméno, adresa...) ze serveru LDAP do Moodlu. Dle potřeby definujte \'Mapování dat\'.';
$string['auth_ldap_user_attribute'] = 'Volitelné: přenastavuje atribut použitý pro pojmenování a vyhledávání uživatelů. Většinou \'cn\'.';
$string['auth_ldap_user_settings'] = 'Nastavení prohledávání uživatelů';
$string['auth_ldap_user_type'] = 'Vyberte, jak jsou uživatelé ukládáni v LDAP. Toto nastavení zároveň určuje, jak se bude chovat vypršení hesla (login expiration), přihlášení z milosti (grace logins) a tvorba uživatelů.';
$string['auth_ldap_version'] = 'Verze protokolu LDAP, kterou používá váš server.';
$string['auth_ldapdescription'] = 'Tato metoda poskytuje ověření uživatele proti serveru LDAP. Je-li zadané jméno a heslo platné, Moodle si vytvoří nový záznam o uživateli ve své vlastní databázi. Tento modul umí načíst informace ze serveru LDAP a přednastavit požadované pole v Moodlu. Při dalším přihlašování se již pouze ověřuje uživatelské jméno a heslo.';
$string['auth_ldapextrafields'] = 'Tato pole jsou volitelná. Můžete vybrat, která pole s informacemi ze <b>serveru LDAP</b> budou použita jako přednastavená v Moodlu. <p>Necháte-li pole prázdná, nepřevezmou se žádné údaje z LDAP a Moodle použije vlastní přednastavené hodnoty. </p><p>V každém případě si uživatel může tyto hodnoty měnit po přihlášení sám.</p>';
$string['auth_ldaptitle'] = 'Používat server LDAP';
$string['auth_manualdescription'] = 'Tato metoda neumožňuje uživatelům zakládat si vlastní účty. Všechny účty musejí být ručně vytvořeny správcem Moodlu.';
$string['auth_manualtitle'] = 'Pouze ručně vytvářené účty';
$string['auth_multiplehosts'] = 'Můžete vložit i více hostitelů NEBO jejich adres (např. \'server1.cz;server2.cz;server3.com\' nebo \'xxx.xxx.xxx.xxx;xxx.xxx.xxx.xxx\')';
$string['auth_nntpdescription'] = 'Tato metoda používá k ověření platnosti zadaného uživatelského jména a hesla server NNTP.';
$string['auth_nntphost'] = 'Adresa serveru NNTP. Zadejte IP adresu, nikoliv doménové jméno!';
$string['auth_nntpport'] = 'Číslo portu serveru NNTP (většinou 119)';
$string['auth_nntptitle'] = 'Používat server NNTP';
$string['auth_nonedescription'] = 'Uživatelé si mohou vytvářet nová konta přímo bez ověření vůči externímu serveru nebo potvrzení přes e-mail. S touto volbou buďte opatrní - zvažte možné problémy se zabezpečením a správou uživatelů, které vám tato volba může způsobit.';
$string['auth_nonetitle'] = 'Bez ověření';
$string['auth_pamdescription'] = 'Tato metoda využívá pro přístup k nativním uživatelským jménům na tomto serveru modul PAM.  Chcete-li tuto metodu používat, musíte si nainstalovat <a href=\"http://www.math.ohio-state.edu/~ccunning/pam_auth/\" target=\"_blank\">PHP4 PAM Authentication</a>.';
$string['auth_pamtitle'] = 'PAM (Pluggable Authentication Modules)';
$string['auth_passwordisexpired'] = 'Vaše heslo vypršelo. Chcete si je teď změnit?';
$string['auth_passwordwillexpire'] = 'Počet dnů do vypršení hesla: $a. Chcete si své heslo změnit?';
$string['auth_pop3description'] = 'Tato metoda používá k ověření platnosti zadaného uživatelského jména a hesla server POP3.';
$string['auth_pop3host'] = 'Adresa serveru POP3. Zadejte IP adresu, nikoliv doménové jméno!';
$string['auth_pop3mailbox'] = 'Název poštovní složky (mailbox), s níž se má navázat spojení (většinou INBOX).';
$string['auth_pop3port'] = 'Číslo portu serveru POP3 (většinou 110)';
$string['auth_pop3title'] = 'Používat server POP3';
$string['auth_pop3type'] = 'Typ serveru. Pokud váš server používá zabezpečení pomocí certifikátů, zvolte pop3cert.';
$string['auth_radiusdescription'] = 'Tato metoda používá k ověření platnosti zadaného uživatelského jména a hesla server <a href=\"http://en.wikipedia.org/wiki/RADIUS\" target=\"_blank\">RADIUS</a>.';
$string['auth_radiushost'] = 'Adresa serveru RADIUS';
$string['auth_radiusnasport'] = 'Číslo portu pro připojení';
$string['auth_radiussecret'] = 'Sdílený klíč';
$string['auth_radiustitle'] = 'Používat server RADIUS';
$string['auth_shib_convert_data'] = 'API pro úpravu dat';
$string['auth_shib_convert_data_description'] = 'Toto API (aplikační rozhraní) vám umožňuje dále upravovat data, která máte k dispozici ze systému Shibboleth. Více infomací <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">zde</a>.';
$string['auth_shib_convert_data_warning'] = 'Soubor buď neexistuje, nebo k němu nemá proces webového serveru přístup ke čtení!';
$string['auth_shib_instructions'] = 'Použijte <a href=\"$a\">přihlášení přes Shibboleth</a>, jestliže vaše instituce tento systém podporuje.<br />V opačném případě použijte normální formulář pro přihlášení.';
$string['auth_shib_instructions_help'] = 'Zde můžete zadat vlastní pokyny uživatelům pro použití systému Shibboleth. Budou se zobrazovat na přihlašovací stránce. Vložené informace by měly obsahovat odkaz na zdroj chráněný systémem Shibboleth, který přesměruje uživatele na \'<b>$a</b>\', takže se uživatelé systému Shibboleth budou moci přihlásit do Moodlu. Necháte-li toto pole prázdné, budou se na přihlašovací stránce zobrazovat obecné pokyny.';
$string['auth_shib_only'] = 'Pouze Shibboleth';
$string['auth_shib_only_description'] = 'Zaškrtněte tuto volbu, chcete-li si vynutit přihlášení pomocí systému Shibboleth';
$string['auth_shib_username_description'] = 'Název proměnné prostředí Shibboleth, která má být použita jako moodlovské uživatelské jméno';
$string['auth_shibboleth_login'] = 'Přihlášení přes Shibboleth';
$string['auth_shibboleth_manual_login'] = 'Ruční přihlášení';
$string['auth_shibbolethdescription'] = 'Tato metoda umožňuje vytvářet a ověřovat uživatele pomocí systému <a href=\"http://shibboleth.internet2.edu/\" target=\"_blank\">Shibboleth</a>.<br>Přečtěte si soubor <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">README</a> obsahující informace o tom, jak nastavit váš Moodle pro podporu systému Shibboleth.';
$string['auth_shibbolethtitle'] = 'Shibboleth';
$string['auth_updatelocal'] = 'Aktualizovat lokální data';
$string['auth_updatelocal_expl'] = '<p><b>Aktualizovat lokální data:</b> Je-li povoleno, budou pole aktualizována (z externího autentizačního zdroje) po každém přihlášení nebo při synchronizaci uživatelů. Pole určená k místní aktualizaci by měla být uzamknuta.</p>';
$string['auth_updateremote'] = 'Aktualizovat externí data';
$string['auth_updateremote_expl'] = '<p><b>Aktualizovat externí data:</b> Je-li povoleno, provede se aktualizace externího autentizačního zdroje po každém uložení profilu uživatele. Pole by měla být odemknuta, aby je bylo možné upravovat.</p>';
$string['auth_updateremote_ldap'] = '<p><b>Pozn.:</b> Aktualizace externího zdroje LDAP vyžaduje, aby měl uživatel \'binddn\' (s heslem \'bindpw\') oprávnění editovat všechny záznamy o uživatelích. Tento systém momentálně nepodporuje atributy s více hodnotami (multi-values) - extra hodnoty budou proto při aktualizaci odstraněny.</p>';
$string['auth_user_create'] = 'Povolit vytváření uživatelů';
$string['auth_user_creation'] = 'Noví (anonymní) uživatelé si mohou založit uživatelský účet v externím zdroji a potvrdit jej prostřednictvím e-mailu. Pokud tuto možnost povolíte, nezapomeňte provést nastavení pro daný externí zdroj týkající se vytváření nových uživatelů.';
$string['auth_usernameexists'] = 'Zvolené uživatelské jméno již existuje. Prosím, vyberte si jiné.';
$string['authenticationoptions'] = 'Možnosti ověření';
$string['authinstructions'] = 'Zde můžete zadat instrukce pro uživatele s vysvětlením, které uživatelské jméno a heslo mají použít. Tento text se objeví na přihlašovací stránce. Necháte-li toto pole prázdné, nebudou zobrazeny žádné instrukce.';
$string['changepassword'] = 'URL ke změně hesla';
$string['changepasswordhelp'] = 'Zde můžete určit URL, na kterém si uživatelé mohou obnovit či změnit své uživatelské jméno/heslo, pokud je zapomněli. URL bude uživatelům poskytnuto jako tlačitko na přihlašovací a osobní stránce. Necháte-li toto pole prázdné, nebude se tlačítko zobrazovat.';
$string['chooseauthmethod'] = 'Vyberte si způsob ověření uživatelů: ';
$string['createpasswordifneeded'] = 'Vytvořit heslo, je-li to potřeba';
$string['forcechangepassword'] = 'Vynutit změnu hesla';
$string['forcechangepassword_help'] = 'Vynutit změnu hesla při příštím přihlášení do Moodlu.';
$string['forcechangepasswordfirst_help'] = 'Vynutit změnu hesla při prvním přihlášení do Moodlu.';
$string['guestloginbutton'] = 'Tlačítko pro hosta';
$string['infilefield'] = 'Pole je v souboru povinné';
$string['instructions'] = 'Pokyny';
$string['internal'] = 'Interní';
$string['locked'] = 'Uzamknuto';
$string['md5'] = 'MD5 hash';
$string['passwordhandling'] = 'Ukládat pole s heslem jako';
$string['plaintext'] = 'Čistý text';
$string['shib_no_attributes_error'] = 'Vaše ověření prostřednictvím systému Shibboleth proběhlo zřejmě úspěšně, Moodle však neobdržel žádné údaje o uživateli. Ověřte prosím, zda váš poskytovatel identity (Identity Provider) předává potřebné údaje ($a) poskytovateli služeb (Service Provider), od něhož je přebírá Moodle, nebo informujte administrátora těchto stránek.';
$string['shib_not_all_attributes_error'] = 'Moodle potřebuje znát některé údaje systému Shibboleth, které ovšem nejsou ve vašem případě k dispozici. Jedná se o následující údaje: $a<br />Obraťte se na administrátora těchto stránek nebo na vašeho poskytovatele identity.';
$string['shib_not_set_up_error'] = 'Ověření prostřednictvím systému Shibboleth je zřejmě nesprávně nastaveno, protože pro tuto stránku nejsou k dispozici žádné programové proměnné systému Shibboleth. Nahlédněte prosím do souboru <a href=\"README.txt\">README</a> pro další pokyny k nastavení systému Shibboleth, nebo se obraťte na administrátora těchto stránek.';
$string['showguestlogin'] = 'Na přihlašovací stránce můžete skrýt nebo ukázat tlačítko pro přihlášení se jako host.';
$string['stdchangepassword'] = 'Použij standardní stránku \'Změna hesla\'';
$string['stdchangepassword_expl'] = 'Pokud váš externí autentizační systém umožňuje změnu hesla přes Moodle, přepněte na \'Ano\'. Tímto potlačíte hodnotu \'URL ke změně hesla\'.';
$string['stdchangepassword_explldap'] = 'Pozn.: Pokud používáte vzdálený server LDAP, doporučujeme vám použít šifrované spojení SSL (ldaps://).';
$string['unlocked'] = 'Odemknuto';
$string['unlockedifempty'] = 'Odemknuto, je-li pole prázdné';
$string['update_never'] = 'Nikdy';
$string['update_oncreate'] = 'Při vytváření';
$string['update_onlogin'] = 'Při každém přihlášení';
$string['update_onupdate'] = 'Při aktualizaci';

?>
