<?PHP // $Id$ 
      // group.php - created with Moodle 1.9.2+ (Build: 20080720) (2007101520)


$string['addgroupstogrouping'] = 'Přidat skupiny do seskupení';
$string['addgroupstogroupings'] = 'Přidat/odebrat skupiny';
$string['adduserstogroup'] = 'Přidat/odebrat uživatele ze skupiny';
$string['allocateby'] = 'Rozdělit do skupin';
$string['anygrouping'] = '[Libovolné seskupení]';
$string['autocreategroups'] = 'Automatické vytvoření skupin';
$string['backtogroupings'] = 'Zpět k seskupením';
$string['backtogroups'] = 'Zpět ke skupinám';
$string['badnamingscheme'] = 'Musí obsahovat právě jeden znak \"@\" nebo \"#\"';
$string['byfirstname'] = 'Abecedně podle křestního jména a příjmení';
$string['byidnumber'] = 'Abecedně podle identifikátoru';
$string['bylastname'] = 'Abecedně podle příjmení, křestního jména';
$string['createautomaticgrouping'] = 'Vytvořit seskupení automaticky';
$string['creategroup'] = 'Vytvořit skupinu';
$string['creategrouping'] = 'Vytvořit seskupení';
$string['creategroupinselectedgrouping'] = 'vytvořit skupinu ve vybraném seskupení';
$string['createingrouping'] = 'Vytvořit v seskupení';
$string['createorphangroup'] = 'Vytvořit skupinu \"sirotků\"';
$string['databaseupgradegroups'] = 'Verze skupiny je nyní $a';
$string['defaultgrouping'] = 'Výchozí seskupení';
$string['defaultgroupingname'] = 'Seskupení';
$string['defaultgroupname'] = 'Skupina';
$string['deleteallgroupings'] = 'Odstranit všechna seskupení';
$string['deleteallgroups'] = 'Odstranit všechny skupiny';
$string['deletegroupconfirm'] = 'Jste si jisti, že chcete odstranit skupinu \'$a\'?';
$string['deletegrouping'] = 'Odstranit seskupení';
$string['deletegroupingconfirm'] = 'Jste si jisti, že chcete odstranit seskupení \'$a\'? (Skupiny v tomto seskupení nebudou odstraněny)';
$string['deleteselectedgroup'] = 'Odstranit vybranou skupinu';
$string['editgroupingsettings'] = 'Upravit nastavení seskupení';
$string['editgroupsettings'] = 'Upravit nastavení skupiny';
$string['enrolmentkey'] = 'Klíč k zápisu';
$string['erroraddremoveuser'] = 'Chyba při přidávání/odstraňování uživatele $a ke skupině';
$string['erroreditgroup'] = 'Chyba při vytváření/úpravě skupiny $a';
$string['erroreditgrouping'] = 'Chyba při vytváření/úpravě seskupení $a';
$string['errorinvalidgroup'] = 'Chyba - neplatná skupina $a';
$string['evenallocation'] = 'Poznámka: aby bylo možno zachovat vyrovnaný počet uživatelů ve skupinách, liší se stávající počet členů na jednu skupinu od vámi určeného čísla';
$string['existingmembers'] = 'Stávající členové: $a';
$string['filtergroups'] = 'Filtrovat skupiny podle:';
$string['group'] = 'Skupina';
$string['groupaddedsuccesfully'] = 'Skupina \"$a\" byla úspěšně přidána';
$string['groupby'] = 'Číslo určuje';
$string['groupdescription'] = 'Popis skupiny';
$string['groupinfo'] = 'Informace o vybrané skupině';
$string['groupinfomembers'] = 'Informace o vybraných členech';
$string['groupinfopeople'] = 'Informace o vybraných uživatelích';
$string['grouping'] = 'Seskupení';
$string['groupingdescription'] = 'Popis seskupení';
$string['groupingname'] = 'Název seskupení';
$string['groupingnameexists'] = 'V tomto kurzu již existuje seskupení \"$a\", zvolte jiný název.';
$string['groupings'] = 'Seskupení';
$string['groupingsonly'] = 'Pouze seskupení';
$string['groupmember'] = 'Člen skupiny';
$string['groupmemberdesc'] = 'Standardní role pro členy skupiny';
$string['groupmembers'] = 'Členové skupiny';
$string['groupmembersonly'] = 'Dostupné pouze pro členy skupiny';
$string['groupmembersonlyerror'] = 'Je nám líto. Pro účast na této činnosti musíte být členem alespoň jedné skupiny, pro niž je tato činnost určena.';
$string['groupmemberssee'] = 'Zobrazit členy skupiny';
$string['groupmembersselected'] = 'Členové vybrané skupiny';
$string['groupmode'] = 'Režim skupin';
$string['groupmodeforce'] = 'Vnutit režim skupin';
$string['groupmy'] = 'Moje skupina';
$string['groupname'] = 'Název skupiny';
$string['groupnameexists'] = 'Skupina s názvem \'$a\' v tomto kurzu již existuje, prosím vyberte jiný název';
$string['groupnotamember'] = 'Je mi líto, ale nejste členem této skupiny';
$string['groups'] = 'Skupiny';
$string['groupscount'] = 'Skupiny ($a)';
$string['groupsgroupings'] = 'Skupiny a seskupení';
$string['groupsinselectedgrouping'] = 'Skupiny ve vybraném seskupení';
$string['groupsnone'] = 'Žádné skupiny';
$string['groupsonly'] = 'Pouze skupiny';
$string['groupspreview'] = 'Náhled skupin';
$string['groupsseparate'] = 'Oddělené skupiny';
$string['groupsvisible'] = 'Viditelné skupiny';
$string['grouptemplate'] = 'Skupina @';
$string['hidepicture'] = 'Skrýt obrázek';
$string['javascriptrequired'] = 'Tato stránka vyžaduje povolený JavaScript';
$string['members'] = 'Členů na skupinu';
$string['membersofselectedgroup'] = 'Členové vybrané skupiny';
$string['namingscheme'] = 'Vzor pojmenovávání';
$string['namingschemehelp'] = 'Znak \"@\" bude nahrazen prvkem písmenné řady A, B, C, ... Z, znak \"#\" bude nahrazen číslem 1, 2, 3 ...';
$string['newgrouping'] = 'Nové seskupení';
$string['newpicture'] = 'Nový obrázek';
$string['noallocation'] = 'Nerozděluj uživatele';
$string['nogroups'] = 'V tomto kurzu zatím nejsou nastaveny žádné skupiny';
$string['nogroupsassigned'] = 'Žádné skupiny nebyly přiřazeny';
$string['nopermissionforcreation'] = 'Nelze vytvořit skupinu \"$a\" - nemáte potřebná oprávnění';
$string['nosmallgroups'] = 'Zabránit poslední malé skupině';
$string['notingrouping'] = '[Není v žádném seskupení]';
$string['nousersinrole'] = 'Nejsou k dispozici žádní uživatelé s danou rolí';
$string['number'] = 'Počet skupin nebo uživatelů';
$string['numgroups'] = 'Počet skupin';
$string['nummembers'] = 'Počet členů v jedné skupině';
$string['overview'] = 'Přehled';
$string['potentialmembers'] = 'Členové k dispozici: $a';
$string['printerfriendly'] = 'Zobrazení seskupení pro tisk';
$string['random'] = 'Náhodně';
$string['removegroupfromselectedgrouping'] = 'Odebrat skupinu z vybraného seskupení';
$string['removegroupingsmembers'] = 'Odebrat všechny skupiny ze seskupení';
$string['removegroupsmembers'] = 'Odebrat všechna členství ve skupině';
$string['removeselectedusers'] = 'Odebrat vybrané uživatele';
$string['selectfromrole'] = 'Použij uživatele s rolí';
$string['showgroupsingrouping'] = 'Ukázat skupiny v seskupení';
$string['showmembersforgroup'] = 'Ukázat členy pro skupinu';
$string['toomanygroups'] = 'Nedostatečný počet uživatelů k naplnění tohoto počtu skupin. Máte k dispozici pouze $a uživatelů se zvolenou rolí.';
$string['usercount'] = 'Počet uživatelů';
$string['usercounttotal'] = 'Počet uživatelů ($a)';
$string['usergroupmembership'] = 'Členství vybraného uživatele';
$string['cancel'] = 'Zrušit'; // ORPHANED
$string['defaultgroupdescription'] = 'Výchozí popis kupiny'; // ORPHANED
$string['defaultgroupprefix'] = 'Skupina'; // ORPHANED
$string['displaygrouping'] = 'Zobrazit seskupení'; // ORPHANED
$string['distributealphabetically'] = 'Rozdělit do skupin abecedně podle příjmení'; // ORPHANED
$string['distributeevenly'] = 'Rovnoměrně rozdělit zbývající studenty'; // ORPHANED
$string['editgroupingpermissions'] = 'Upravit oprávnění seskupení'; // ORPHANED
$string['errorinvalidgrouping'] = 'Chyba - neplatné seskupení $a'; // ORPHANED
$string['errornotingrouping'] = 'Je mi líto, nemůžete vytvořit skupinu v $a'; // ORPHANED
$string['errornotingroupingedit'] = 'Je mi líto, nemůžete upravit seskupení $a'; // ORPHANED
$string['groupfor'] = 'pro skupinu'; // ORPHANED
$string['numberofgroups'] = 'Počet skupin'; // ORPHANED
$string['numberofstudents'] = 'Počet studentů'; // ORPHANED
$string['prefixforgroupnames'] = 'Předpona názvů skupin'; // ORPHANED
$string['return'] = 'Zpět'; // ORPHANED
$string['save'] = 'Uložit'; // ORPHANED
$string['selectnumberineachgroup'] = 'Zvolte počet v každé skupině'; // ORPHANED
$string['selectnumberofgroups'] = 'Zvolte počet skupin'; // ORPHANED
$string['showusersalreadyingroup'] = 'Ukázat uživatele, kteří jsou již v nějaké skupině spadající do tohoto seskupení'; // ORPHANED
$string['teachersgroupmark'] = 'Učitelé nemohou známkovat činnosti ve skupinách, do nichž nepatří'; // ORPHANED
$string['teachersgroupview'] = 'Učitelé nemohou vidět činnosti ve skupinách, do nichž nepatří'; // ORPHANED
$string['teachersoverride'] = 'Učitelé, kteří nejsou zařazení do žádné skupiny, mohou vidět a známkovat činnosti ve všech skupinách (přenastavuje uvedené výše)'; // ORPHANED
$string['upgradeconfirm'] = 'Je mi líto, databázové tabulky skupin vytvořené ve verzi Moodle 1.8 dev musí být během tohoto upgrade odstraněny. Přejete si pokračovat?'; // ORPHANED
$string['usestudentsonlyfromselectedgroup'] = 'Použij pouze studenty z právě vybraných skupin'; // ORPHANED
$string['viewallgroupsactivities'] = 'Studenti si mohou prohlížet činnosti ve všech skupinách, ale nemohou do nich přispívat'; // ORPHANED
$string['viewallgroupsmembers'] = 'Studenti mohou vidět členy všech skupin'; // ORPHANED
$string['viewowngroup'] = 'Studenti mohou vidět členy všech skupin, do nichž sami patří'; // ORPHANED
$string['addexistinggroupstogrouping'] = 'Přidat stávající skupiny do seskupení'; // ORPHANED

?>
