<?PHP // $Id$ 
      // message.php - created with Moodle 1.8 + (2007021502)


$string['addcontact'] = 'Přidat kontakt';
$string['addsomecontacts'] = 'Chcete-li někomu poslat zprávu nebo si na tuto stránku přidat odkaz pro rychlé odeslání zprávy vybranému uživateli, použijte <a href=\"$a\">záložku Vyhledat</a> nahoře.';
$string['addsomecontactsincoming'] = 'Tyto zprávy jsou od uživatelů, které nemáte ve svém seznamu kontaktů. Přejete-li si je do vašeho seznamu přidat, klikněte na ikonku \"Přidat kontakt\" vedle jejich jména.';
$string['ago'] = 'před: $a';
$string['allmine'] = 'Všechny zprávy pro mě nebo ode mě';
$string['allstudents'] = 'Všechny zprávy mezi studenty v kurzu';
$string['allusers'] = 'Všechny zprávy všech uživatelů';
$string['backupmessageshelp'] = 'Zahrnout do automaticky vytvářených záloh zprávy';
$string['beepnewmessage'] = 'Pípnout při příchozí zprávě (může vyžadovat plugin prohlížeče pro přehrávání zvuku, např. Quicktime)';
$string['blockcontact'] = 'Blokovat kontakt';
$string['blockedmessages'] = 'Počet zpráv u blokovaných uživatelů: $a';
$string['blocknoncontacts'] = 'Blokuj všechny nové zprávy od uživatelů, které nemám v seznamu kontaktů';
$string['contactlistempty'] = 'Váš seznam kontaktů je momentálně prázdný';
$string['contacts'] = 'Kontakty';
$string['context'] = 'kontext';
$string['deletemessagesdays'] = 'Počet dnů, po jejichž uplynutí budou staré zprávy automaticky odstraněny';
$string['discussion'] = 'Diskuse';
$string['emailmessages'] = 'Pošli mi zprávu e-mailem, pokud jsem offline';
$string['emailtagline'] = 'Tento e-mail obsahuje kopii zpravy, ktera vam byla zaslana na \"$a\".';
$string['emptysearchstring'] = 'Musíte zadat řetězec k vyhledávání';
$string['formorethan'] = 'Déle než';
$string['includeblockedusers'] = 'Zahrnout blokované uživatele';
$string['incomingcontacts'] = 'Nové kontakty ($a)';
$string['keywords'] = 'Klíčová slova';
$string['keywordssearchresults'] = 'Výsledky hledání -- počet nalezených zpráv: $a';
$string['maxmessages'] = 'Největší počet zpráv zobrazovaných v historii diskuse';
$string['message'] = 'Zpráva';
$string['messagehistory'] = 'Historie zpráv';
$string['messages'] = 'Zprávy';
$string['messaging'] = 'Zasílání zpráv';
$string['mycontacts'] = 'Moje kontakty';
$string['newonlymsg'] = 'Ukázat jen nové';
$string['newsearch'] = 'Nové hledání';
$string['noframesjs'] = 'Verze bez rámců a JavaScriptu';
$string['nomessages'] = 'Žádné nové zprávy';
$string['nomessagesfound'] = 'Nebyly nalezeny žádné zprávy';
$string['nosearchresults'] = 'Vaše vyhledávání nepřineslo žádný výsledek';
$string['offline'] = 'Offline';
$string['offlinecontacts'] = 'Kontakty offline ($a)';
$string['online'] = 'Online';
$string['onlinecontacts'] = 'Kontakty online ($a)';
$string['onlyfromme'] = 'Pouze zprávy ode mě';
$string['onlymycourses'] = 'Pouze v mých kurzech';
$string['onlytome'] = 'Pouze zprávy pro mě';
$string['pagerefreshes'] = 'Tato stránka se automaticky obnovuje každých $a s.';
$string['readmessages'] = 'Přečtených zpráv: $a';
$string['removecontact'] = 'Odebrat kontakt';
$string['savemysettings'] = 'Uložit mé nastavení';
$string['search'] = 'Vyhledat';
$string['searchforperson'] = 'Vyhledat osobu';
$string['searchmessages'] = 'Vyhledat zprávu';
$string['sendmessage'] = 'Poslat zprávu';
$string['sendmessageto'] = 'Poslat zprávu uživateli $a';
$string['settings'] = 'Nastavení';
$string['settingssaved'] = 'Vaše nastavení bylo uloženo';
$string['showmessagewindow'] = 'Automaticky otevřít okno s novou zprávou (váš prohlížeč nesmí na těchto stránkách blokovat otevírání nových popup oken)';
$string['strftimedaydatetime'] = '%%A %%d.%%B %%Y, %%H:%%M';
$string['timenosee'] = 'Počet minut od doby, kdy jsem byl(a) naposledy viděn(a) online';
$string['timesent'] = 'Čas odeslání';
$string['unblockcontact'] = 'Odblokovat kontakt';
$string['unreadmessages'] = 'Nepřečtených zpráv: $a';
$string['userisblockingyou'] = 'Vaše zprávy tomuto uživateli jsou na základě jeho nastavení blokovány.';
$string['userisblockingyounoncontact'] = 'Tento uživatel přijímá zprávy pouze od lidí, které má v seznamu kontaktů. Vy na tomto seznamu zatím nejste.';
$string['userssearchresults'] = 'Výsledky hledání -- počet nalezených uživatelů: $a';

?>
