<?PHP // $Id$ 
      // auth.php - created with Moodle 1.9.4+ (Build: 20090204) (2007101540)


$string['CASform'] = 'Izbira avtentikacije';
$string['accesCAS'] = 'Uporabniki CAS';
$string['accesNOCAS'] = 'Drugi uporabniki';
$string['actauthhdr'] = 'Aktivni avtentikacijski vtičniki';
$string['alternatelogin'] = 'Če tu vnesete URL, bo uporabljen kot stran za prijavo v to spletno mesto. Stran mora vsebovati obrazec, ki ima nastavljeno lastnost <i>action</i> na <strong>\'$a\'</strong> in polji <strong>uporabniško ime</strong> ter <strong>geslo</strong>.<br />Bodite pozorni, da ne vnesete napačnega naslova URL, da se ne zaklenete iz tega spletnega mesta.<br />Pustite to nastavitev prazno za uporabo privzete prijavne strani.';
$string['alternateloginurl'] = 'Alternativni URL prijave';
$string['auth_cas_auth_user_create'] = 'Zunanje tvorjenje uporabnikov';
$string['auth_cas_baseuri'] = 'URI strežnika (nič, če ni baseUri)<br />Na primer, če se strežnik CAS odziva na gostitelj.domena.si/CAS/ potem<br />cas_baseuri = CAS/';
$string['auth_cas_baseuri_key'] = 'Base URI';
$string['auth_cas_broken_password'] = 'Za nadaljevanje morate spremeniti geslo, vendar pa ni na voljo strani, kjer bi to lahko naredili. Prosimo, stopite v stik z vašim Moodle administratorjem.';
$string['auth_cas_cantconnect'] = 'LDAP del modula CAS se ne more povezati s strežnikom: $a';
$string['auth_cas_casversion'] = 'Različica';
$string['auth_cas_changepasswordurl'] = 'URL za spremembo gesla';
$string['auth_cas_create_user'] = 'Če želite vstaviti CAS preverjene uporabnike v podatkovno zbirko Moodle, to vključite. Sicer se bodo lahko prijavili samo uporabniki, ki že obstajajo v podatkovni zbirki Moodle.';
$string['auth_cas_create_user_key'] = 'Naredi uporabnika';
$string['auth_cas_enabled'] = 'Če želite uporabljati preverjanje pristnosti CAS, to vključite.';
$string['auth_cas_hostname'] = 'Ime gostitelja strežnika CAS <br />npr.: gostitelj.domena.si';
$string['auth_cas_hostname_key'] = 'Strežnik';
$string['auth_cas_invalidcaslogin'] = 'Oprostite, vaša prijava je spodletela - ne morete se prijaviti';
$string['auth_cas_language'] = 'Izbran jezik';
$string['auth_cas_language_key'] = 'Jezik';
$string['auth_cas_logincas'] = 'Dostop z varno povezavo';
$string['auth_cas_logoutcas'] = 'Nastavite \"Da\", če se želite ob odjavi iz Moodle odjaviti tudi iz CAS.';
$string['auth_cas_logoutcas_key'] = 'Odjava CAS';
$string['auth_cas_multiauth'] = 'Nastavite \"Da\", če želite uporabljati multi-avtentikacijo (CAS + druga vrsta avtentikacije)';
$string['auth_cas_multiauth_key'] = 'Multi-avtentikacija';
$string['auth_cas_port'] = 'Vrata strežnika CAS';
$string['auth_cas_port_key'] = 'Vrata';
$string['auth_cas_proxycas'] = 'Nastavite \"Da\", če uporabljate CAS v proxy načinu';
$string['auth_cas_proxycas_key'] = 'Proxy način';
$string['auth_cas_server_settings'] = 'Konfiguracija strežnika CAS';
$string['auth_cas_text'] = 'Varna povezava';
$string['auth_cas_use_cas'] = 'Uporabi CAS';
$string['auth_cas_version'] = 'Različica CAS';
$string['auth_casdescription'] = 'Ta način uporablja strežnik CAS (Central Authentication Service) za preverjanje pristnosti uporabnikov v okolju z enojno prijavo (SSO - Single Sign On). Uporabite lahko tudi preprosto preverjanje pristnosti z LDAP. Če sta podana uporabniško ime in geslo veljavni glede na CAS, bo Moodle ustvaril nov vnos uporabnika v svoji podatkovni zbirki in prevzel zahtevane lastnosti s strežnika LDAP. Ob prihodnjih prijavah se preverjata samo uporabniško ime in geslo.';
$string['auth_casnotinstalled'] = 'Ne morem uporabiti avtentikacije CAS. Modul PHP LDAP ni nameščen.';
$string['auth_castitle'] = 'Uporabi strežnik CAS (SSO)';
$string['auth_changepasswordhelp'] = 'Pomoč za spreminjanje gesla';
$string['auth_changepasswordhelp_expl'] = 'Prikaz pomoči ob izgubljenem geslu uporabnikom, ki so izgubili svoje $a geslo. To bo prikazano bodisi poleg ali namesto <strong>URL spreminjanja gesla</strong> ali vgrajenega mehanizma spreminjanja gesla.';
$string['auth_changepasswordurl'] = 'URL za spremembo gesla';
$string['auth_changepasswordurl_expl'] = 'Navedite URL, kamor naj bodo napoteni uporabniki, ki so izgubili svoje $a geslo. Nastavite <strong>Uporabi običajno stran za spreminjanje gesla</strong> na <strong>Ne</strong>.';
$string['auth_changingemailaddress'] = 'Zahtevali ste spremembo e-poštnega naslova z $a->oldemail na $a->newemail. Zaradi varnostnih razlogov smo vam na nov naslov poslali sporočilo. Vaš e-poštni naslov bo spremenjen takoj, ko potrdite novega s klikom na URL povezavo v sporočilu.';
$string['auth_common_settings'] = 'Splošne nastavitve';
$string['auth_data_mapping'] = 'Povezovanje podatkov';
$string['auth_dbcantconnect'] = 'Ne morem se povezati z navedeno avtentikacijsko zbirko';
$string['auth_dbchangepasswordurl_key'] = 'URL za spreminjanje gesla';
$string['auth_dbdebugauthdb'] = 'Razhroščevanje ADOdb';
$string['auth_dbdebugauthdbhelp'] = 'Vklopi razhroščevalni način ADOdb povezovanja na zunanjo podatkovno zbirko - uporabite, kadar med prijavo dobite prazno stran. Ni primerno za uporabo na produkcijskih strežnikih.';
$string['auth_dbdeleteuser'] = 'Brisanje uporabnika $a[0] id $a[1]';
$string['auth_dbdeleteusererror'] = 'Napaka pri brisanju uporabnika $a';
$string['auth_dbdescription'] = 'Ta način uporablja zunanjo tabelo podatkovne zbirke za preverjanje, če sta podano uporabniško ime in geslo pravilna.  Če je uporabniški račun nov, je možno prenesti v Moodle tudi podatke iz ostalih polj.';
$string['auth_dbextencoding'] = 'Kodni nabor zunanje zbirke';
$string['auth_dbextencodinghelp'] = 'Kodni nabor, ki ga uporablja zunanja podatkovna zbirka';
$string['auth_dbextrafields'] = 'Ta polja niso obvezna.  Odločite se lahko in nekatera uporabniška polja vnaprej izpolnite s podatki iz <b>zunanjih polj podatkovne zbirke</b>, ki jih tu določite. <p>Če pustite ta polja prazna, bodo uporabljene privzete vrednosti.</p><p>V vsakem primeru bodo lahko uporabniki urejali vsa ta polja, ko se bodo prijavili.</p>';
$string['auth_dbfieldpass'] = 'Ime polja, ki vsebuje gesla';
$string['auth_dbfieldpass_key'] = 'Polje za geslo';
$string['auth_dbfielduser'] = 'Ime polja, ki vsebuje uporabniška imena';
$string['auth_dbfielduser_key'] = 'Polje za uporabniško ime';
$string['auth_dbhost'] = 'Računalnik, na katerem teče strežnik podatkovne zbirke.';
$string['auth_dbhost_key'] = 'Gostitelj';
$string['auth_dbinsertuser'] = 'Vstavil uporabnika $a[0] id $a[1]';
$string['auth_dbinsertusererror'] = 'Napaka pri vstavljanju uporabnika $a';
$string['auth_dbname'] = 'Ime podatkovne zbirke';
$string['auth_dbname_key'] = 'Ime podatkovne zbirke';
$string['auth_dbpass'] = 'Geslo, ki ustreza zgornjemu uporabniškemu imenu';
$string['auth_dbpass_key'] = 'Geslo';
$string['auth_dbpasstype'] = '<p>Opredelite zapis, ki ga uporablja polje z geslom. Kodiranje MD5 je uporabno za povezovanje z drugimi pogostimi spletnimi aplikacijami, kot je PostNuke.</p> <p>Uporabite \'interno\', če želite, da zunanja podatkovna zbirka upravlja uporabniška imena in elektronske naslove, Moodle pa naj upravlja gesla. Če uporabite \'interno\', potem <i>morate</i> zagotoviti izpolnjeno polje z elektronskim naslovom v zunanji podatkovni zbirki in morate redno izvajati admin/cron.php. Moodle bo poslal elektronsko sporočilo novim uporabnikom z začasnim geslom.</p>';
$string['auth_dbpasstype_key'] = 'Format gesla';
$string['auth_dbreviveduser'] = 'Oživil uporabnika $a[0] id $a[1]';
$string['auth_dbrevivedusererror'] = 'Napaka pri oživljanju uporabnika $a';
$string['auth_dbsetupsql'] = 'Nastavitveni ukaz SQL';
$string['auth_dbsetupsqlhelp'] = 'Ukaz SQL za posebne nastavitve podatkovne baze. Ponavadi se uporablja za nastavitev kodnega nabora komunikacije. Primer za MySQL in PostgreSQL: <em>SET NAMES \'utf8\'</em>';
$string['auth_dbsuspenduser'] = 'Suspendiral uporabnika $a[0] ID $a[1]';
$string['auth_dbsuspendusererror'] = 'Napaka pri suspendiranju uporabnika $a';
$string['auth_dbsybasequoting'] = 'Uporaba sybase narekovajev';
$string['auth_dbsybasequotinghelp'] = 'Oracle, MS SQL in nekatere druge podatkovne zbirke potrebujejo uporabo enojnih narekovajev tipa Sybase. Ne uporabljajte z MySQL!';
$string['auth_dbtable'] = 'Ime tabele v podatkovni zbirki';
$string['auth_dbtable_key'] = 'Tabela';
$string['auth_dbtitle'] = 'Uporabi zunanjo podatkovno zbirko';
$string['auth_dbtype'] = 'Vrsta podatkovne zbirke (Poglej si  <a href=\"../lib/adodb/readme.htm#drivers\">dokumentacijo ADOdb</A> za podrobnosti)';
$string['auth_dbtype_key'] = 'Podatkovna zbirka';
$string['auth_dbupdatinguser'] = 'Shranjujem podatke uporabnika $a[0] id $a[1]';
$string['auth_dbuser'] = 'Uporabniško ime s pravico bralnega dostopa do podatkovne zbirke';
$string['auth_dbuser_key'] = 'Uporabnik zbirke';
$string['auth_dbusernotexist'] = 'Ne morem shraniti podatke neobstoječega uporabnika: $a';
$string['auth_dbuserstoadd'] = 'Dodaj uporabniške zapise: $a';
$string['auth_dbuserstoremove'] = 'Izbriši uporabniške zapise: $a';
$string['auth_emailchangecancel'] = 'Prekliči spremembo e-poštnega naslova';
$string['auth_emailchangepending'] = 'Sprememba v teku. Kliknite na URL povezavo, ki je bila poslana na naslov $a->preference_newemail.';
$string['auth_emaildescription'] = 'Potrditev prek e-pošte je privzet način preverjanja pristnosti.  Ko se uporabnik prijavi, si izbere novo uporabniško ime in geslo, potrditev prejme prek elektronske pošte na svoj elektronski naslov.  Ta elektronska pošta vsebuje varno povezavo na stran, kjer lahko uporabnik potrdi svoj uporabniški račun. Ob prihodnjih prijavah se zgolj preveri uporabniško ime in geslo z vrednostmi shranjenimi v podatkovni zbirki Moodle.';
$string['auth_emailnoemail'] = 'Napaka pri poskusu pošiljanja e-pošte!';
$string['auth_emailnoinsert'] = 'Napaka pri dodajanju vašega zapisa v podatkovno zbirko!';
$string['auth_emailnowexists'] = 'E-poštni naslov, ki ste ga želeli dodati svojemu profilu, je bil v času od vaše zahteve dodeljen drugemu. Vaša zahteva je bila zato preklicana. Lahko poskusite ponovno z novim naslovom.';
$string['auth_emailrecaptcha'] = 'Doda element s slikovno ali zvočno potrditvijo na prijavno stran za uporabnike, ki si sami ustvarijo uporabniški račun na temelju e-poštnega naslova. To ščiti vaš strežnik pred nadlegovalci in pomaga pri hvalevrednem cilju. Za več informacij si oglejte http://recaptcha.net/learnmore.html. <br /><em>Zahtevana je PHP razširitev cURL.</em>';
$string['auth_emailrecaptcha_key'] = 'Omogoči element reCAPTCHA';
$string['auth_emailsettings'] = 'Nastavitve';
$string['auth_emailtitle'] = 'Preverjanje pristnosti na osnovi e-pošte';
$string['auth_emailupdate'] = 'Posodobi e-poštni naslov';
$string['auth_emailupdatemessage'] = 'Spoštovani $a->fullname,

zahtevali ste spremembo vašega e-poštnega naslova vašega uporabniškega računa na strežniku $a->site. Prosimo, da spodnjo povezavo odprete v vašem brskalniku in potrdite spremembo.

$a->url';
$string['auth_emailupdatesuccess'] = 'E-poštni naslov uporabnika <em>$a->fullname</em> je bil uspešno posodobljen na <em>$a->email</em>.';
$string['auth_emailupdatetitle'] = 'Potrditev e-poštnega naslova na strežniku $a->site';
$string['auth_fcchangepasswordurl'] = 'URL strani za spreminjanje geska';
$string['auth_fcconnfail'] = 'Napaka pri povezovanju. Koda napake: $a[0], opis napake: $a[1]';
$string['auth_fccreators'] = 'Seznam skupin, katerih člani smejo ustvarjati nove predmete. Ločite več skupin s podpičjem \';\'. Imena morajo biti črkovana natančno tako kot na strežniku FirstClass. Sistem razlikuje velike in male črke.';
$string['auth_fccreators_key'] = 'Ustvarjalci';
$string['auth_fcdescription'] = 'Ta način uporablja strežnik FirstClass za preverjanje, če sta podano uporabniško ime in geslo pravilna.';
$string['auth_fcfppport'] = 'Vrata strežnika (3333 je najbolj pogosto)';
$string['auth_fcfppport_key'] = 'Vrata';
$string['auth_fchost'] = 'Naslov strežnika FirstClass. Uporabite številko IP ali ime DNS.';
$string['auth_fchost_key'] = 'Gostitelj';
$string['auth_fcpasswd'] = 'Geslo za gornji račun.';
$string['auth_fcpasswd_key'] = 'Geslo';
$string['auth_fctitle'] = 'Uporabi strežnik FirstClass';
$string['auth_fcuserid'] = 'Uporabniška identifikacija za račun FirstClass z nastavljeno pravico \'Subadministrator\'.';
$string['auth_fcuserid_key'] = 'ID uporabnika';
$string['auth_fieldlock'] = 'Zakleni vrednost';
$string['auth_fieldlock_expl'] = '<p><b>Zakleni vrednost:</b> Če je omogočeno, bo to preprečilo uporabnikom Moodle in skrbnikom neposredno urejanje tega polja. Uporabite to možnost, če vzdržujete te podatke v zunanjem sistemu preverjanja pristnosti. </p>';
$string['auth_fieldlocks'] = 'Zakleni uporabniška polja';
$string['auth_fieldlocks_help'] = '<p>Zaklenete lahko uporabniška podatkovna polja. To je uporabno za spletna mesta, kjer uporabniške podatke vzdržujejo skrbniki ročno z vnašanjem uporabniških zapisov ali nalaganjem z možnostjo \'Naloži uporabnike\'- Če zaklepate polja. ki jih Moodle zahteva, poskrbite, da bodo podatki ob ustvarjanju uporabniških računov ali računov uporabni.</p><p>Razmislite o nastavitvi načina zaklepanja na \'Odkleni prazno\' v izogib tem problemom.</p>';
$string['auth_imapchangepasswordurl_key'] = 'URL strani za spreminjanje gesla';
$string['auth_imapdescription'] = 'Ta način uporablja strežnik IMAP za preverjanje, če sta podano uporabniško ime in geslo pravilna.';
$string['auth_imaphost'] = 'Naslov strežnika IMAP. Uporabi številko IP, ne imena DNS.';
$string['auth_imaphost_key'] = 'Gostitelj';
$string['auth_imapnotinstalled'] = 'Napaka pri poskusu IMAP avtentikacije. Modul PHP IMAP ni nameščen.';
$string['auth_imapport'] = 'Številka vrat strežnika IMAP. Običajno je to 143 ali 993.';
$string['auth_imapport_key'] = 'Vrata';
$string['auth_imaptitle'] = 'Uporabi strežnik IMAP';
$string['auth_imaptype'] = 'Vrsta strežnika IMAP.  Strežniki IMAP lahko uporabljajo različne vrste preverjanja pristnosti in pogajanj.';
$string['auth_imaptype_key'] = 'Vrsta';
$string['auth_invalidnewemailkey'] = 'Napaka: če poskušate potrditi spremembo e-poštnega naslova, je mogoče prišlo do napake pri kopiranju URL naslova, ki ste ga dobili po e-pošti. Skopirajte naslov še enkrat in poskusite ponovno.';
$string['auth_ldap_ad_create_req'] = 'Ne morem ustvariti novega uporabniškega računa v Active Directory. Preverite, če so izpolnjeni vsi pogoji za delovanje (povezava LDAPS, uporabnik z dovolj pravicami, ipd.)';
$string['auth_ldap_attrcreators'] = 'Spisek skupin ali kontekstov, katerih člani lahko ustvarjajo lastnosti. Različne skupine ločite z \';\'. Ponavadi nekaj podobnega kot \'cn=teachers,ou=staff,o=myorg\'';
$string['auth_ldap_attrcreators_key'] = 'Tvorci lastnosti';
$string['auth_ldap_auth_user_create_key'] = 'Zunanje tvorjenje uporabnikov';
$string['auth_ldap_bind_dn'] = 'Če želite uporabljati bind-user za iskanje uporabnikov, to opredelite tu. Nekaj podobnega \'cn=ldapuser,ou=public,o=org\'';
$string['auth_ldap_bind_dn_key'] = 'LDAP Disinguished name';
$string['auth_ldap_bind_pw'] = 'Geslo za bind-user.';
$string['auth_ldap_bind_pw_key'] = 'Geslo';
$string['auth_ldap_bind_settings'] = 'Nastavitev bind';
$string['auth_ldap_changepasswordurl_key'] = 'URL strani za spreminjanje gesla';
$string['auth_ldap_contexts'] = 'Seznam kontekstov kjer se nahajajo uporabniki. Različne kontekste ločite s podpičjem \';\'. Na primer: \'ou=users,o=org; ou=others,o=org\'';
$string['auth_ldap_contexts_key'] = 'Konteksti';
$string['auth_ldap_create_context'] = 'Če omogočite ustvarjanje uporabnika s potrditvijo prek elektronske pošte, opredelite kontekst, kjer se uporabniki ustvarijo. Zaradi varnostnih razlogov bi moral biti ta kontekst različen od ostalih uporabnikov. Ni vam potrebno dodati tega konteksta v spremenljivko ldap_context, Moodle bo iskal uporabnike v tem kontekstu samodejno.<br /><b>Opomba!</b> Spremeniti morate funkcijo auth_user_create() v datoteki auth/ldap/lib.php, da bo delovalo ustvarjanje uporabnikov';
$string['auth_ldap_create_context_key'] = 'Kontekst za nove uporabnike';
$string['auth_ldap_create_error'] = 'Napaka pri tvorjenju uporabnika v LDAP';
$string['auth_ldap_creators'] = 'Seznam skupin, katerih člani smejo ustvarjati nove predmete. Ločite več skupin s podpičjem \';\'. Po navadi nekaj podobnega \'cn=teachers,ou=staff,o=myorg\'';
$string['auth_ldap_creators_key'] = 'Ustvarjalci';
$string['auth_ldap_expiration_desc'] = 'Izberite Ne za onemogočanje preverjanja poteklega gesla ali LDAP branja časa passwordexpiration neposredno iz strežnika LDAP';
$string['auth_ldap_expiration_key'] = 'Potek';
$string['auth_ldap_expiration_warning_desc'] = 'Število dni pred potekom gesla za prikaz opozorila o tem.';
$string['auth_ldap_expiration_warning_key'] = 'Opozorilo o poteku';
$string['auth_ldap_expireattr_desc'] = 'Neobvezno: preglasi lastnost v strežniku LDAP, ki shranjuje čas poteka gesla passwordExpirationTime';
$string['auth_ldap_expireattr_key'] = 'Atribut poteka';
$string['auth_ldap_graceattr_desc'] = 'Neobvezno: Preglasi lastnost gracelogin';
$string['auth_ldap_gracelogin_key'] = 'Atribut podaljšane prijave';
$string['auth_ldap_gracelogins_desc'] = 'Omogoči podporo za podaljšano prijavo LDAP (grace login). Ko je geslo poteklo se lahko uporabnik prijavi dokler ni števec gracelogin enak 0. Če to omogočite se bo prikazalo sporočilo o podaljšani prijavi, če je geslo poteklo.';
$string['auth_ldap_gracelogins_key'] = 'Podaljšana prijava';
$string['auth_ldap_groupecreators'] = 'Spisek skupin ali kontekstov, katerih člani lahko ustvarjajo skupine. Različne skupine ločite z \';\'. Ponavadi nekaj podobnega kot \'cn=teachers,ou=staff,o=myorg\'';
$string['auth_ldap_groupecreators_key'] = 'Tvorci skupin';
$string['auth_ldap_host_url'] = 'Določite gostitelja LDAP v obliki URL kot \'ldap://ldap.myorg.com/\' ali \'ldaps://ldap.myorg.com/\' Ločite vel strežnikov s podpičjem \';\' za podporo prevzema v primeru odpovedi (failover).';
$string['auth_ldap_host_url_key'] = 'URL gostitelja';
$string['auth_ldap_ldap_encoding'] = 'Določite kodni nabor strežnika LDAP. Najverjetneje utf-8. MS AD v2 uporablja privzete nabore platforme, kot sta cp1252, cp1250 itn.';
$string['auth_ldap_ldap_encoding_key'] = 'Kodni nabor LDAP';
$string['auth_ldap_login_settings'] = 'Nastavitve prijave';
$string['auth_ldap_memberattribute'] = 'Neobvezno: Preglasi lastnost uporabnikovega članstva, če uporabnik pripada skupini. Običajno \'member\'';
$string['auth_ldap_memberattribute_isdn'] = 'Neobvezno: Preglasi uporabo vrednosti atributov članov. 0 ali 1.';
$string['auth_ldap_memberattribute_isdn_key'] = 'Atribut člana uporablja dn';
$string['auth_ldap_memberattribute_key'] = 'Atribut člana';
$string['auth_ldap_no_mbstring'] = 'Za tvorjenje uporabnikov v Active Directory potrebujete razširitev mbstring.';
$string['auth_ldap_noconnect'] = 'Modul LDAP se ne more povezati s strežnikom: $a';
$string['auth_ldap_noconnect_all'] = 'Modul LDAP se ne more povezati z nobenim od strežnikov: $a';
$string['auth_ldap_noextension'] = 'Opozorilo: modul PHP LDAP ni prisoten. Prosimo, preverite, če je nameščen in vklopljen.';
$string['auth_ldap_objectclass'] = 'Neobvezno: Preglasi objectClass uporabljen za imenovanje/iskanje uporabnikov v ldap_user_type. Ponavadi vam tega ni potrebno spreminjati.';
$string['auth_ldap_objectclass_key'] = 'Razred objekta.';
$string['auth_ldap_opt_deref'] = 'Določi, kako se ob iskanju obravnavajo vzdevki. Izberite eno od naslednjih vrednosti: \"Ne\" (LDAP_DEREF_NEVER) ali \"Da\" (LDAP_DEREF_ALWAYS)';
$string['auth_ldap_opt_deref_key'] = 'Dereference aliases';
$string['auth_ldap_passtype'] = 'Določite format novih ali spremenjenih gesel na strežniku LDAP';
$string['auth_ldap_passtype_key'] = 'Format gesla';
$string['auth_ldap_passwdexpire_settings'] = 'Nastavitve poteka LDAP gesla.';
$string['auth_ldap_preventpassindb'] = 'Izberite \"Da\" za preprečevanje hranjenja gesel v podatkovni zbirki Moodle.';
$string['auth_ldap_preventpassindb_key'] = 'Skrij gesla';
$string['auth_ldap_search_sub'] = 'Išči uporabnike v podkontekstih.';
$string['auth_ldap_search_sub_key'] = 'Išči podkontekste';
$string['auth_ldap_server_settings'] = 'Nastavitve strežnika LDAP';
$string['auth_ldap_unsupportedusertype'] = 'auth: ldap user_create() (še) ne podpira izbranega tipa uporabnika:\"$a\"';
$string['auth_ldap_update_userinfo'] = 'Posodobi podatke o uporabniku (ime, priimek, naslov...) iz strežnika LDAP v Moodle.  Določite nastavitve \"Povezovanje podatkov\" kakor je potrebno.';
$string['auth_ldap_user_attribute'] = 'Neobvezno: Preglasi lastnost uporabljeno za določanje/iskanje uporabnikov. Običajno \'cn\'.';
$string['auth_ldap_user_attribute_key'] = 'Atribut uporabnika';
$string['auth_ldap_user_exists'] = 'Uporabniško ime že obstaja v LDAP';
$string['auth_ldap_user_settings'] = 'Nastavitve poizvedb uporabnikov';
$string['auth_ldap_user_type'] = 'Izberite, kako so uporabniki shranjeni v LDAP-u. Ta nastavitev tudi določa način delovanja poteka gesel, podaljšane prijave in ustvarjanja uporabnikov.';
$string['auth_ldap_user_type_key'] = 'Vrsta uporabnika';
$string['auth_ldap_usertypeundefined'] = 'config.user_type ni definiran ali pa funkcija ldap_expirationtime2unix ne podpira izbranega tipa!';
$string['auth_ldap_usertypeundefined2'] = 'config.user_type ni definiran ali pa funkcija ldap_unixi2expirationtime ne podpira izbranega tipa!';
$string['auth_ldap_version'] = 'Različica protokola LDAP, ki ga uporablja vaš strežnik.';
$string['auth_ldap_version_key'] = 'Različica';
$string['auth_ldapdescription'] = 'Ta način omogoča preverjanje pristnosti na zunanji strežnik LDAP.

                                  Če sta podano uporabniško ime in geslo veljavna, Moodle ustvari novega uporabnika

                                  v podatkovni zbirki. Ta modul lahko prebere uporabnikove lastnosti iz LDAP-a in vnaprej izpolni

                                  želena polja v Moodlu.  Za nadaljnje prijave se preverita samo uporabniško ime in

                                  geslo.';
$string['auth_ldapextrafields'] = 'Ta polja niso obvezna.  Odločite se lahko in nekatera uporabniška polja vnaprej izpolnite s podatki iz <b>LDAP polj</b>, ki jih tu določite. <p>Če pustite ta polja prazna, ne bo nič preneseno iz LDAP-a in bodo namesto tega uporabljene Moodle privzete vrednosti.</p><p>V obeh primerih bo uporabnik lahko uredil vsa ta polja po prijavi.</p>';
$string['auth_ldapnotinstalled'] = 'Napaka pri uporabi avtentikacije LDAP. Modul PHP LDAP ni nameščen.';
$string['auth_ldaptitle'] = 'Uporabi strežnik LDAP';
$string['auth_manualdescription'] = 'Ta način odstrani vse možnosti, da bi uporabniki sami ustvarili svoje račune.  Vse račune mora ročno ustvariti skrbnik.';
$string['auth_manualtitle'] = 'Samo ročno ustvarjeni računi';
$string['auth_mnet_auto_add_remote_users'] = 'Ko je opcija nastavljena na \"Da\", se ob prvi prijavi oddaljenega uporabnika samodejno shrani lokalni zapis uporabnika.';
$string['auth_mnet_roamin'] = 'Ti uporabniki s strežnika lahko uporabljajo vaše spletno mesto.';
$string['auth_mnet_roamout'] = 'Vaši uporabniki lahko uporabljajo te strežnike';
$string['auth_mnet_rpc_negotiation_timeout'] = 'Časovna omejitev za avtentikacijo prek XMLRPC.';
$string['auth_mnetdescription'] = 'Uporabniki so avtenticirani glede na mrežo zaupanja, določeno v Moodle omrežju.';
$string['auth_mnettitle'] = 'Avtentikacija prek Moodle omrežja';
$string['auth_multiplehosts'] = 'Določenih je več gostiteljev ALI naslovov (npr. host1.com;host2.com;host3.com) ali (npr. xxx.xxx.xxx.xxx;xxx.xxx.xxx.xxx)';
$string['auth_nntpchangepasswordurl_key'] = 'URL naslov za spreminjanje gesla';
$string['auth_nntpdescription'] = 'Ta način uporablja strežnik NNTP za preverjanje, če sta podano uporabniško ime in geslo pravilna.';
$string['auth_nntphost'] = 'Naslov strežnika NNTP Uporabi številko IP, ne imena DNS.';
$string['auth_nntphost_key'] = 'Gostitelj';
$string['auth_nntpnotinstalled'] = 'Ne morem uporabiti avtentikacije NNTP. Modul PHP IMAP ni nameščen.';
$string['auth_nntpport'] = 'Vrata strežnika (119 je najbolj pogosto)';
$string['auth_nntpport_key'] = 'Vrata';
$string['auth_nntptitle'] = 'Uporabi strežnik NNTP';
$string['auth_nologindescription'] = 'Dodatni vtičnik, ki prepreči uporabniku prijavo v sistem in zavrne e-pošto, poslano uporabniku. Lahko se uporablja za <em>suspendiranje</em> uporabniških računov.';
$string['auth_nologintitle'] = 'Onemogoči prijavo';
$string['auth_nonedescription'] = 'Uporabniki se lahko prijavijo in ustvarijo veljavne račune takoj, brez preverjanja pristnosti prek zunanjega strežnika in brez potrditve prek e-pošte.  Bodite previdni pri rabi te možnosti - pomislite na varnostne in skrbniške probleme, ki jih to lahko povzroči.';
$string['auth_nonetitle'] = 'Brez preverjanja pristnosti';
$string['auth_ntlmsso'] = 'NLTM SSO';
$string['auth_ntlmsso_enabled'] = 'Nastavite na Da, če želite omogočiti enotno prijavo na domeni NTLM.<strong>Opomba:</strong> ta funkcija potrebuje dodatne nastavitve na spletnem strežniku. Za več informacij si oglejte <a href=\"http://docs.moodle.org/en/NTLM_authentication\">http://docs.moodle.org/en/NTLM_authentication</a>';
$string['auth_ntlmsso_enabled_key'] = 'Omogoči';
$string['auth_ntlmsso_subnet'] = 'Če je omogočeno, bo enotna prijava dovoljena samo odjemalcem v tem pod-omrežju (subnet). Format: xxx.xxx.xxx.xxx/bitmask';
$string['auth_ntlmsso_subnet_key'] = 'Pod-omrežje';
$string['auth_outofnewemailupdateattempts'] = 'Porabili ste vse dovoljne poskuse posodobitve e-poštnega naslova. Vaša zahteva je bila preklicana.';
$string['auth_pamdescription'] = 'Ta način uporablja PAM za dostop do dejanskih uporabniških imen na tem strežniku. Namestiti morate <a href=\"http://www.math.ohio-state.edu/~ccunning/pam_auth/\" target=\"_blank\">PHP4 PAM Authentication</a>, če želite uporabljati ta modul.';
$string['auth_pamtitle'] = 'PAM (Pluggable Authentication Modules)';
$string['auth_passwordisexpired'] = 'Vaše geslo je poteklo. Želite spremeniti svoje geslo zdaj?';
$string['auth_passwordwillexpire'] = 'Vaše geslo bo poteklo čez $a dni. Želite spremeniti svoje geslo zdaj?';
$string['auth_pop3changepasswordurl_key'] = 'URL naslov za spreminjanje gesla';
$string['auth_pop3description'] = 'Ta način uporablja strežnik POP3 za preverjanje, če sta podano uporabniško ime in geslo pravilna.';
$string['auth_pop3host'] = 'Naslov strežnika POP3. Uporabi številko IP, ne imena DNS.';
$string['auth_pop3host_key'] = 'Gostitelj';
$string['auth_pop3mailbox'] = 'Ime poštnega predala za poskus povezave z njim.  (običajno INBOX)';
$string['auth_pop3mailbox_key'] = 'Poštni predal';
$string['auth_pop3notinstalled'] = 'Ne morem uporabiti POP3 avtentikacije. Modul PHP IMAP ni nameščen.';
$string['auth_pop3port'] = 'Vrata strežnika (110 je najbolj pogosto, 995 je pogosto za SSL)';
$string['auth_pop3port_key'] = 'Vrata';
$string['auth_pop3title'] = 'Uporabi strežnik POP3';
$string['auth_pop3type'] = 'Vrsta strežnika. Če vaš strežnik uporablja varnostne certifikate izberite pop3cert.';
$string['auth_pop3type_key'] = 'Vrsta';
$string['auth_radiuschangepasswordurl_key'] = 'URL naslov za spreminjanje gesla';
$string['auth_radiusdescription'] = 'Ta način uporablja strežnik <a href=\"http://sl.wikipedia.org/wiki/RADIUS\" target=\"_blank\">RADIUS</a> za preverjanje, če sta podana uporabniško ime in geslo veljavna.';
$string['auth_radiushost'] = 'Naslov strežnika RADIUS';
$string['auth_radiushost_key'] = 'Gostitelj';
$string['auth_radiusnasport'] = 'Vrata za povezavo';
$string['auth_radiusnasport_key'] = 'Vrata';
$string['auth_radiussecret'] = 'Skupna skrivnost';
$string['auth_radiussecret_key'] = 'Skrivnost';
$string['auth_radiustitle'] = 'Strežnik RADIUS';
$string['auth_radiustype'] = 'Izberite način preverjanja pristnosti s strežnikom RADIUS';
$string['auth_radiustype_key'] = 'Preverjanje pristnosti';
$string['auth_radiustypechapmd5'] = 'CHAP MD5';
$string['auth_radiustypemschapv1'] = 'Microsoft CHAP verzija 1';
$string['auth_radiustypemschapv2'] = 'Microsoft CHAP verzija 2';
$string['auth_radiustypepap'] = 'PAP';
$string['auth_remove_delete'] = 'Pobriši lokalni račun';
$string['auth_remove_keep'] = 'Ohrani lokalni račun';
$string['auth_remove_suspend'] = 'Suspendiraj lokalni račun';
$string['auth_remove_user'] = 'Določite, kaj se zgodi z lokalnimi uporabniškimi računi v primeru, da je bil uporabnik izbrisan z zunanjega vira. Suspendirani uporabniki so avtomatično oživljeni, če se spet pojavijo v zunanjem viru.';
$string['auth_remove_user_key'] = 'Izbrisan zunanji uporabnik';
$string['auth_shib_changepasswordurl'] = 'URL naslov za spreminjanje gesla';
$string['auth_shib_convert_data'] = 'API spreminjanja podatkov';
$string['auth_shib_convert_data_description'] = 'Ta programski vmesnik (API) lahko uporabite za dodatno spreminjanje podatkov, ki jih zagotavlja Shibboleth. Preberite <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">README</a> za dodatna navodila.';
$string['auth_shib_convert_data_warning'] = 'Datoteka ne obstaja ali ni berljiva za proces spletnega strežnika!';
$string['auth_shib_instructions'] = 'Uporabite <a href=\"$a\">prijavo Shibboleth</a> za pridobitev dostopa prek Shibboleth, če vaša organizacija to podpira.<br />Sicer uporabite navaden tu prikazan prijavni obrazec.';
$string['auth_shib_instructions_help'] = 'Tu morate zagotoviti lastna navodila za vaše uporabnike, da jim razložite Shibboleth.  Prikazana bodo na strani prijave v področju navodil. Navodila morajo vključevati povezavo do \"<b>$a</b>\", ki jo uporabniki kliknejo, ko se želijo prijaviti.';
$string['auth_shib_no_organizations_warning'] = 'Če želite uporabiti vključeno storitev WAYF, morate dodati ID spisek ponudnikov preverjanja pristnosti (Identity Provider entityID), ločenih z vejico, njihova imena in opcijsko pobudnika seje (session initiator).';
$string['auth_shib_only'] = 'Samo Shibboleth';
$string['auth_shib_only_description'] = 'Označite to možnost, če naj bo preverjanje pristnosti Shibboleth vsiljeno';
$string['auth_shib_username_description'] = 'Ime spremenljivke okolja spletnega strežnika Shibboleth, ki naj se uporabi kot Moodle uporabniško ime';
$string['auth_shibboleth_contact_administrator'] = 'Če niste povezani z izbranimi organizacijami in potrebujete dostop do predmeta na tem strežniku, prosimo, da stopite v stik z';
$string['auth_shibboleth_errormsg'] = 'Izberite organizacijo, ki ji pripadate!';
$string['auth_shibboleth_login'] = 'Prijava Shibboleth';
$string['auth_shibboleth_login_long'] = 'Prijava v Moodle prek Shibboleth';
$string['auth_shibboleth_manual_login'] = 'Ročna prijava';
$string['auth_shibboleth_select_member'] = 'Sem član ...';
$string['auth_shibboleth_select_organization'] = 'Za prijavo prek Shibboleth izberite svojo organizacijo iz padajočega menija:';
$string['auth_shibbolethdescription'] = 'Z uporabo tega načina se uporabniki ustvarijo in se njihova pristnost preveri prek <a href=\"http://shibboleth.internet2.edu/\" target=\"_blank\">Shibboleth</a>.<br>Preberite si <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">README</a> za Shibboleth o tem kako nastaviti Moodle s Shibboleth';
$string['auth_shibbolethtitle'] = 'Shibboleth';
$string['auth_sync_script'] = 'Sinhronizacijski program Cron';
$string['auth_updatelocal'] = 'Posodobi lokalno';
$string['auth_updatelocal_expl'] = '<p><b>Posodobi lokalno:</b> Če je omogočeno, bo polje posodobljeno (iz zunanjega mehanizma) vsakič, ko se uporabnik prijavi ali se sinhronizirajo uporabniki. Polja nastavljena za lokalno posodobitev morajo biti zaklenjena.</p>';
$string['auth_updateremote'] = 'Posodobi zunanje';
$string['auth_updateremote_expl'] = '<p><b>Posodobi zunanje:</b> Če je omogočeno bo zunanji mehanizem posodobljen, ko bo posodobljen uporabniški zapis. Polja morajo biti odklenjena za možnost urejanja.</p>';
$string['auth_updateremote_ldap'] = '<p><b>Opomba:</b> Posodabljanje zunanjih LDAP podatkov zahteva nastavitev binddn in bindpw na uporabnika bind s pravicami urejanja vseh uporabniških zapisov. Trenutno ne ohranja lastnosti v zečimi vrednostmi in bo ob posodobitvi odstranilo dodatne vrednosti. </p>';
$string['auth_user_create'] = 'Omogoči ustvarjanje uporabnikov';
$string['auth_user_creation'] = 'Novi (anonimni) uporabniki lahko ustvarjajo uporabniške račune na zunanjem viru preverjanja pristnosti in so potrjeni prek e-pošte. Če to omogočite, konfigurirajte tudi specifične možnosti za posamezne module za ustvarjanje uporabnikov.';
$string['auth_usernameexists'] = 'Izbrano uporabniško ime že obstaja. Prosimo izberite novega.';
$string['authenticationoptions'] = 'Možnosti preverjanja pristnosti';
$string['authinstructions'] = 'Tu lahko zagotovite navodila za vaše uporabnike, da bodo vedeli katero uporabniško ime in geslo naj uporabijo.  Besedilo, ki ga boste tu vnesli, se bo pojavilo na strani prijave.  Če boste pustili to prazno, ne bo prikazanih nobenih navodil.';
$string['auto_add_remote_users'] = 'Samodejno dodaj oddaljene uporabnike';
$string['changepassword'] = 'URL za spremembo gesla';
$string['changepasswordhelp'] = 'Tu lahko navedete lokacijo na kateri lahko vaši uporabniki pridobijo ali spremenijo svoje uporabniško ime ali geslo, če so ga pozabili.  To bo ponujeno uporabnikom kot gumb na prijavni strani in njihovi uporabniški strani.  Če pustite to prazno, gumb ne bo prikazan.';
$string['chooseauthmethod'] = 'Izberite način preverjanja pristnosti';
$string['createpasswordifneeded'] = 'Ustvari geslo, če je potrebno';
$string['enterthenumbersyouhear'] = 'Vnesite številke, ki jih slišite';
$string['enterthewordsabove'] = 'Vnesite besede zgoraj';
$string['errorminpassworddigits'] = 'Geslo mora imeti vsaj $a številk.';
$string['errorminpasswordlength'] = 'Geslo mora biti dolgo vsaj $a znakov.';
$string['errorminpasswordlower'] = 'Geslo mora imeti najmanj $a malih črk.';
$string['errorminpasswordnonalphanum'] = 'Geslo mora imeti vsaj $a znakov, ki niso črke ali številke.';
$string['errorminpasswordupper'] = 'Geslo mora imeti vsaj $a velikih črk.';
$string['errorpasswordupdate'] = 'Napaka pri zapisovanju novega gesla. Geslo ni spremenjeno';
$string['forcechangepassword'] = 'Vsili spremembo gesla';
$string['forcechangepassword_help'] = 'Prisili uporabnike v spremembo geslo ob njihovi naslednji prijavi.';
$string['forcechangepasswordfirst_help'] = 'Prisili uporabnike v spremembo geslo ob njihovi prvi prijavi.';
$string['forgottenpassword'] = 'Če vnesete URL naslov, bo uporabljen za pridobivanje izgubljenih gesel za ta strežnik. Funkcija je namenjena strežnikom, kjer so gesla hranjena zunaj Moodle. Pustite prazno za uporabo privzetega načina pridobivanja izgubljenih gesel.';
$string['forgottenpasswordurl'] = 'URL za pozabljeno geslo';
$string['getanaudiocaptcha'] = 'Nov zvočni CAPTCHA';
$string['getanimagecaptcha'] = 'Nov slikovni CAPTCHA';
$string['getanothercaptcha'] = 'Nov CAPTCHA';
$string['guestloginbutton'] = 'Gumb za prijavo gosta';
$string['incorrectpleasetryagain'] = 'Nepravilno. Prosimo, poskusite znova.';
$string['infilefield'] = 'Zahtevano polje v datoteki';
$string['instructions'] = 'Navodila';
$string['internal'] = 'Interno';
$string['locked'] = 'Zaklenjeno';
$string['md5'] = 'Šifriranje MD5';
$string['nopasswordchange'] = 'Geslo ni mogoče spremeniti';
$string['nopasswordchangeforced'] = 'Za nadaljevanje morate spremeniti geslo, vendar pa ni na voljo strani, kjer bi to lahko naredili. Prosimo, stopite v stik z vašim Moodle administratorjem.';
$string['ntlmsso_attempting'] = 'Poskušam z enotno prijavo prek NTLM..';
$string['ntlmsso_failed'] = 'Samodejna prijava ni uspela. Poskusite z običajno prijavo.';
$string['ntlmsso_isdisabled'] = 'Enotna prjava NTLM ni omogočena.';
$string['passwordhandling'] = 'Obravnava polja za geslo';
$string['plaintext'] = 'Golo besedilo';
$string['pluginnotenabled'] = 'Vtičnik za avtentikacijo \'$a\' ni vključen.';
$string['pluginnotinstalled'] = 'Vtičnik za avtentikacijo \'$a\' ni nameščen.';
$string['recaptcha'] = 'reCAPTCHA';
$string['rpc_negotiation_timeout'] = 'Časovna omejitev za pogajanje RPC';
$string['selfregistration'] = 'Samo-registracija';
$string['selfregistration_help'] = 'Izberite avtentikacijski vtičnik za samo-registracijo';
$string['sha1'] = 'SHA-1 hash';
$string['shib_no_attributes_error'] = 'Kot kaže je vaša pristnost potrjena z mehanizmom Shibboleth, vendar Moodle ni prejel nobenih uporabniških atributov. Prosimo preverite, če vaš ponudnik identitete objavlja potrebne lastnosti ($a) ponudniku storitev kjer teče Moodle ali obvestite skrbnika tega strežnika.';
$string['shib_not_all_attributes_error'] = 'Moodle potrebuje nekatere lastnosti Shibboleth, ki v vašem primeru niso prisotne. Te lastnosti so: $a<br />Prosimo povprašajte skrbnika tega strežnika ali vašega ponudnika identitete.';
$string['shib_not_set_up_error'] = 'Preverjanje pristnosti Shibboleth kot kaže ni pravilno nastavljeno, saj za to stran ni prisotnih spremenljivk okolja Shibboleth. Preverite v datoteki <a href=\"README.txt\">README</a> za nadaljna navodila, kako nastaviti preverjanje pristnosti Shibboleth ali povprašajte skrbnika te namestitve Moodle.';
$string['showguestlogin'] = 'Gumb za prijavo gosta na strani za prijavo lahko skrijete ali prikažete.';
$string['stdchangepassword'] = 'Uporabi standardno stran za spremembo gesla';
$string['stdchangepassword_expl'] = 'Če zunanji sistem preverjanja pristnosti dovoljuje spreminjanje gesel prek Moodle, preklopite to na Da. Ta nastavitev preglasi \'URL za spremembo gesla\'.';
$string['stdchangepassword_explldap'] = 'Opomba: Priporočeno je, da uporabljate LDAP prek SSL šifriranega tunela (ldaps://), če je strežnik LDAP oddaljen strežnik.';
$string['unlocked'] = 'Odklenjeno';
$string['unlockedifempty'] = 'Odkleni prazno';
$string['update_never'] = 'Nikoli';
$string['update_oncreate'] = 'Ob ustvarjanju';
$string['update_onlogin'] = 'Ob vsaki prijavi';
$string['update_onupdate'] = 'Ob posodobitvi';


// Strings below here are module specific and will be duplicated in auth_* files
// Module specific language strings should also be copied into their respective
// auth_*.php files to ensure compatibility in all versions of Moodle

$string['sso_idp_description'] = 'Objavite to storitev, da omogočite vašim uporabnikom uporabo Moodle strežnika $a, ne da bi si morali na njem ustvariti ločen uporabniški račun.
<ul><li><em>Odvisnost</em>: <strong>Naročiti</strong> se morate na storitev SSO (Service provider) na $a.</li></ul><br />Naročite se na to storitev za omogočanje avtenticiranim uporabnikom s strežnika $a uporabljanje storitev vašega strežnika brez potrebe po tvorjenju uporabniškega računa. <ul><li><em>Odvisnost</em>: Za uporabo morate tudi <strong>objaviti</strong> storitev SSO (Service Provider) strežniku $a.</li></ul><br />';
$string['sso_idp_name'] = 'SSO (strežnik identitet)';
$string['sso_mnet_login_refused'] = 'Prijava uporabnika $a[0] s strežnika  $a[1] ni dovoljena.';
$string['sso_sp_description'] = 'Objavite to storitev, da omogočite avtenticiranim uporabnikom s strežnika $a uporabo vašega Moodle strežnika $a, ne da bi si morali na njem ustvariti ločen uporabniški račun.
<ul><li><em>Odvisnost</em>: <strong>Naročiti</strong> se morate na storitev SSO (Service provider) na $a.</li></ul><br />Naročite se na to storitev za omogočanje uporabnikom vašega strežnika uporabljanje storitev Moodle strežnika $a brez potrebe po tvorjenju uporabniškega računa. <ul><li><em>Odvisnost</em>: Za uporabo morate tudi <strong>objaviti</strong> storitev SSO (Service Provider) strežniku $a.</li></ul><br />';
$string['sso_sp_name'] = 'SSO (strežnik storitev)';

?>
