<?PHP // $Id$ 
      // currencies.php - created with Moodle 1.8.2+ (2007021520)


$string['AED'] = 'Dirham (Združeni arabski emirati)';
$string['AFA'] = 'Afgan (Afganistan)';
$string['ALL'] = 'Lek (Albanija)';
$string['ANG'] = 'Nizozemsko-antilski gulden';
$string['AON'] = 'Nova kwanza (Angola)';
$string['ARA'] = 'Argentinski novi peso';
$string['AUD'] = 'Avstralski dolar';
$string['AWG'] = 'Arubski florin';
$string['BBD'] = 'Barbadoški dolar';
$string['BDT'] = 'Taka (Bangladeš)';
$string['BGL'] = 'Bolgarski lev';
$string['BHD'] = 'Bahranski dinar';
$string['BIF'] = 'Burundski frank';
$string['BMD'] = 'Bermudski dolar';
$string['BND'] = 'Brunejski dolar';
$string['BOB'] = 'Bolivijski boliviano';
$string['BRR'] = 'Cruzeiro Real (Brazilija)';
$string['BSD'] = 'Bahamski dolar';
$string['BTN'] = 'Butanska Ngutrum';
$string['BUK'] = 'Burma Kyat';
$string['BWP'] = 'Bocvanska Pula';
$string['BZD'] = 'Beliški dolar';
$string['CAD'] = 'Kanadski dolar';
$string['CDZ'] = 'Zairski novi zaire';
$string['CHF'] = 'Švicarski frank';
$string['CLF'] = 'Chilean Unidades de Fomento';
$string['CLP'] = 'Čilski peso';
$string['CNY'] = 'Juan (Kitajska)';
$string['COP'] = 'Kolumbijski peso';
$string['CRC'] = 'Kolon (Kostarika)';
$string['CSD'] = 'Srbski dinar';
$string['CUP'] = 'Kubanski peso';
$string['CVE'] = 'Kapverdski eskudo';
$string['CYP'] = 'Ciprski funt';
$string['CZK'] = 'Češka krona';
$string['DJF'] = 'Džibutski frank';
$string['DKK'] = 'Danska krona';
$string['DOP'] = 'Dominikanski peso';
$string['DZD'] = 'Alžirski dinar';
$string['EGP'] = 'Egiptovski funt';
$string['ETB'] = 'Etiopski bir';
$string['EUR'] = 'Evro';
$string['FJD'] = 'Fidžijski dolar';
$string['FKP'] = 'Falklandski funt';
$string['GBP'] = 'Britanski funt';
$string['GHC'] = 'Cedi (Gana)';
$string['GIP'] = 'Gibraltarski funt';
$string['GMD'] = 'Dalasi (Gambija)';
$string['GNF'] = 'Gvinejski frank';
$string['GTQ'] = 'Kecal (Gvatemala)';
$string['GWP'] = 'Peso (Gvineja Bisao)';
$string['GYD'] = 'Gvajanski dolar';
$string['HKD'] = 'Hongkonški dolar';
$string['HNL'] = 'Lempira (Honduras)';
$string['HTG'] = 'Gurd (Haiti)';
$string['HUF'] = 'Forint (Madžarska)';
$string['IDR'] = 'Indonezijska rupija (Vzhodni Timor)';
$string['ILS'] = 'Šekel (Izrael)';
$string['INR'] = 'Indijska rupija';
$string['IQD'] = 'Iraški dinar';
$string['IRR'] = 'Rial (Iran)';
$string['ISK'] = 'Islandska krona';
$string['JMD'] = 'Jamajski dolar';
$string['JOD'] = 'Jordanski dinar';
$string['JPY'] = 'Japonski jen';
$string['KES'] = 'Kenijski šiling';
$string['KHR'] = 'Riel (Kambodža)';
$string['KMF'] = 'Komorski frank';
$string['KPW'] = 'Severnokorejski von';
$string['KRW'] = 'Von (Južna Koreja)';
$string['KWD'] = 'Kuvajtski dinar';
$string['KYD'] = 'Kajmanski dolar';
$string['LAK'] = 'Kip (Laos)';
$string['LBP'] = 'Libanonski funt';
$string['LKR'] = 'Šrilanška rupija';
$string['LRD'] = 'Liberijski dolar';
$string['LSL'] = 'Loti (Lesoto)';
$string['LYD'] = 'Libijski dinar';
$string['MAD'] = 'Dirham (Maroko in Zah. Sahara)';
$string['MGF'] = 'Malgaški frank (Madagaskar)';
$string['MNT'] = 'Tugrik (Mongolija)';
$string['MOP'] = 'Macao pataca';
$string['MRO'] = 'Uguija (Mavretanija)';
$string['MTL'] = 'Malteška lira';
$string['MUR'] = 'Mavricijska rupija';
$string['MVR'] = 'Rufija (Maldivski otoki)';
$string['MWK'] = 'Malavijska kvača';
$string['MXN'] = 'Mehiški novi peso';
$string['MYR'] = 'Ringit (Malezija)';
$string['MZM'] = 'Metikal (Mozambik)';
$string['NGN'] = 'Naira (Nigerija)';
$string['NIO'] = 'Kordoba (Nikaragva)';
$string['NOK'] = 'Norveška krona';
$string['NPR'] = 'Nepalska rupija';
$string['NZD'] = 'Novozelandski dolar';
$string['OMR'] = 'Omanski rial';
$string['PAB'] = 'Balboa (Panama)';
$string['PEN'] = 'Purujski novi sol';
$string['PGK'] = 'Kina (Papua Nova Gvineja)';
$string['PHP'] = 'Filipinski peso';
$string['PKR'] = 'Pakistanska rupija';
$string['PLN'] = 'Poljski novi zlot';
$string['PYG'] = 'Gvarani (Paragvaj)';
$string['QAR'] = 'Katarski rial';
$string['ROL'] = 'Lej (Romunija)';
$string['RWF'] = 'Ruandski frank';
$string['SAR'] = 'Rial (Saudska Arabija)';
$string['SBD'] = 'Solomonski dolar';
$string['SCR'] = 'Rupija (Sejšelski otoki)';
$string['SDP'] = 'Sudanski dinar';
$string['SEK'] = 'Švedska krona';
$string['SGD'] = 'Singapurski dolar';
$string['SHP'] = 'Funt Svete Helene';
$string['SKK'] = 'Slovaška krona';
$string['SLL'] = 'Leone (Siera Leone)';
$string['SOS'] = 'Somalski šiling';
$string['SRG'] = 'Surinamski gulden';
$string['STD'] = 'Dobra (Sao Tome in Pricipe)';
$string['SUR'] = 'Rubelj (Rusija)';
$string['SVC'] = 'Kolon (El Salvador)';
$string['SYP'] = 'Sirski funt';
$string['SZL'] = 'Lilangeni (Svazi)';
$string['THB'] = 'Bat (Tajska)';
$string['TND'] = 'Tunizijski dinar';
$string['TOP'] = 'Paanga (Tonga)';
$string['TPE'] = 'Eskudo (Vzhodni Timor)';
$string['TRL'] = 'Turška lira';
$string['TTD'] = 'Dolar Trinidada in Tobaga';
$string['TWD'] = 'Novi tajvanski dolar';
$string['TZS'] = 'Tanzanski šiling';
$string['UGS'] = 'Ugandski šiling';
$string['USD'] = 'Ameriški dolar';
$string['UYU'] = 'Urugvajski novi peso';
$string['VEB'] = 'Bolivar (Venezuela)';
$string['VND'] = 'Dong (Vietnam)';
$string['VUV'] = 'Vatu (Vanuatu)';
$string['WST'] = 'Tala (Samoa)';
$string['YER'] = 'Jemenski rial';
$string['ZAR'] = 'Južnoafriški rand';
$string['ZMK'] = 'Kvača (Zambija)';
$string['ZWD'] = 'Zimbabvejski dolar';
$string['ADP'] = 'Andorska Peseta'; // ORPHANED
$string['AOK'] = 'Kvanza (Angola)'; // ORPHANED
$string['ATS'] = 'Avstrijski šiling'; // ORPHANED
$string['BEF'] = 'Belgijski frank'; // ORPHANED
$string['BRC'] = 'Brazilski real'; // ORPHANED
$string['CSK'] = 'Krona (Češka)'; // ORPHANED
$string['DDM'] = 'Vzhodnonemška marka (DDR)'; // ORPHANED
$string['DEM'] = 'Nemška marka'; // ORPHANED
$string['ECS'] = 'Sukre (Ekvador)'; // ORPHANED
$string['ESP'] = 'Španska pezeta'; // ORPHANED
$string['FIM'] = 'Finska marka'; // ORPHANED
$string['FRF'] = 'Francoski frank'; // ORPHANED
$string['GRD'] = 'Grška drahma'; // ORPHANED
$string['IEP'] = 'Irsku funt'; // ORPHANED
$string['ITL'] = 'Italijanska lira'; // ORPHANED
$string['LUF'] = 'Luksemburški frank'; // ORPHANED
$string['MXP'] = 'Mehiški peso'; // ORPHANED
$string['NIC'] = 'Kordoba (Nikaragva)'; // ORPHANED
$string['NLG'] = 'Nizozemski gulden'; // ORPHANED
$string['PEI'] = 'Inti (Peru)'; // ORPHANED
$string['PLZ'] = 'Zlot (Poljska)'; // ORPHANED
$string['PTE'] = 'Eskudo (Portugalska)'; // ORPHANED
$string['TRY'] = 'Turška lira'; // ORPHANED
$string['UYP'] = 'Peso (Urugvaj)'; // ORPHANED
$string['YDD'] = 'Dinar (Jemen)'; // ORPHANED
$string['YUD'] = 'Jugoslovanski dinar'; // ORPHANED
$string['ZRZ'] = 'Zair (Zair)'; // ORPHANED

?>
