<?PHP // $Id$ 
      // group.php - created with Moodle 1.9.4+ (Build: 20090204) (2007101540)


$string['addgroupstogrouping'] = 'Dodaj skupino v skupek';
$string['addgroupstogroupings'] = 'Dodaj/odstrani skupine';
$string['adduserstogroup'] = 'Dodaj/odstrani uporabnike';
$string['allocateby'] = 'Dodeli člane';
$string['anygrouping'] = '[Katerikoli skupek]';
$string['autocreategroups'] = 'Samodejno ustvari skupine';
$string['backtogroupings'] = 'Nazaj na skupke';
$string['backtogroups'] = 'Nazaj na skupine';
$string['badnamingscheme'] = 'Mora vsebovati vaj en \'@\' ali en \'#\' znak';
$string['byfirstname'] = 'Po abecedi glede na ime, priimek';
$string['byidnumber'] = 'Po abecedi glede na ID številko';
$string['bylastname'] = 'Po abecedi glede na priimek, ime';
$string['createautomaticgrouping'] = 'Ustvari samodejni skupek';
$string['creategroup'] = 'Ustvari skupino';
$string['creategrouping'] = 'Ustvari skupek';
$string['creategroupinselectedgrouping'] = 'Ustvari skupino v skupku';
$string['createingrouping'] = 'Ustvari v skupku';
$string['createorphangroup'] = 'Ustvari osirotelo skupino';
$string['databaseupgradegroups'] = 'Verzija skupin je sedaj $a';
$string['defaultgrouping'] = 'Privzet skupek';
$string['defaultgroupingname'] = 'Skupek';
$string['defaultgroupname'] = 'Skupina';
$string['deleteallgroupings'] = 'Izbriši vse skupke';
$string['deleteallgroups'] = 'Izbriši vse skupine';
$string['deletegroupconfirm'] = 'Ali ste prepričani, da želite izbrisati skupino \'$a\'?';
$string['deletegrouping'] = 'Izbriši skupek';
$string['deletegroupingconfirm'] = 'Ali ste prepričani, da želite izbrisati skupek \'$a\'? (Skupine v skupku ne bodo izbrisane)';
$string['deletegroupsconfirm'] = 'Ali ste prepričani, da želite izbrisati sledeče skupine?';
$string['deleteselectedgroup'] = 'Izbriši izbrano skupino';
$string['editgroupingsettings'] = 'Uredi nastavitve skupka';
$string['editgroupsettings'] = 'Uredi nastavitve skupine';
$string['enrolmentkey'] = 'Ključ za vpis';
$string['erroraddremoveuser'] = 'Napaka pri dodajanju/odstranjevanju uporabnik $a v skupino/iz skupine';
$string['erroreditgroup'] = 'Napaka pri ustvarjanju/posodabljanju skupine $a';
$string['erroreditgrouping'] = 'Napaka pri ustvarjanju/posodabljanju skupka $a';
$string['errorinvalidgroup'] = 'Napaka, neveljavna skupina $a';
$string['errorselectone'] = 'Izberite samo eno skupino pred izbiro te možnosti';
$string['errorselectsome'] = 'Izberite eno ali več skupin pred izbiro te možnosti';
$string['evenallocation'] = 'Pomni: Zaradi zagotovitve enakomerne zapolnitve skupin se dejansko število članov v skupini razlikuje od števila, ki ste ga določili.';
$string['existingmembers'] = 'Obstoječi člani: $a';
$string['filtergroups'] = 'Filtriraj skupine po:';
$string['group'] = 'Skupina';
$string['groupaddedsuccesfully'] = 'Skupina $a je bila uspešno dodana';
$string['groupby'] = 'Določi';
$string['groupdescription'] = 'Opis skupine';
$string['groupinfo'] = 'informacije o izbrani skupini';
$string['groupinfomembers'] = 'informacije o izbranih članih';
$string['groupinfopeople'] = 'informacije o izbranih osebah';
$string['grouping'] = 'Skupek';
$string['groupingdescription'] = 'Opis skupka';
$string['groupingname'] = 'Ime skupka';
$string['groupingnameexists'] = 'Skupek z imenom \'$a\' že obstaja v tem predmetu, prosimo, izberite drugo ime.';
$string['groupings'] = 'Skupki';
$string['groupingsonly'] = 'Samo skupki';
$string['groupmember'] = 'Član skupine';
$string['groupmemberdesc'] = 'Standardna vloga za člana skupine.';
$string['groupmembers'] = 'Člani skupine';
$string['groupmembersonly'] = 'Na voljo samo za člane skupine';
$string['groupmembersonlyerror'] = 'Žal morate biti član vsaj ene skupine, ki se uporablja pri tej dejavnosti.';
$string['groupmemberssee'] = 'Poglej člane skupine';
$string['groupmembersselected'] = 'Člani izbrane skupine';
$string['groupmode'] = 'Skupinski način';
$string['groupmodeforce'] = 'Vsili skupinski način';
$string['groupmy'] = 'Moja skupina';
$string['groupname'] = 'Ime skupine';
$string['groupnameexists'] = 'Ime skupine \'$a\' že obstaja v predmetu, prosimo, izberite drugo ime.';
$string['groupnotamember'] = 'Žal niste član te skupine';
$string['groups'] = 'Skupine';
$string['groupscount'] = 'Skupine ($a)';
$string['groupsgroupings'] = 'Skupine &amp; skupki';
$string['groupsinselectedgrouping'] = 'Skupine v:';
$string['groupsnone'] = 'Brez skupin';
$string['groupsonly'] = 'Samo skupine';
$string['groupspreview'] = 'Predogled skupin';
$string['groupsseparate'] = 'Ločene skupine';
$string['groupsvisible'] = 'Vidne skupine';
$string['grouptemplate'] = 'Skupina @';
$string['hidepicture'] = 'Skrij sliko';
$string['javascriptrequired'] = 'Stran zahteva omogočen Javascript.';
$string['members'] = 'Članov na skupino';
$string['membersofselectedgroup'] = 'Člani:';
$string['namingscheme'] = 'Način poimenovanja';
$string['namingschemehelp'] = 'Uporabite znak @ za predstavitev črke skupine (A-Z) ali znak # za predstavitev številke skupine.';
$string['newgrouping'] = 'Nov skupek';
$string['newpicture'] = 'Nova slika';
$string['noallocation'] = 'Ni dodelitve';
$string['nogroups'] = 'V tem predmetu še ni nastavljenih skupin';
$string['nogroupsassigned'] = 'Ni določenih skupin';
$string['nopermissionforcreation'] = 'Ne morem ustvariti skupine \"$a\", saj nimate zahtevanih dovoljenj';
$string['nosmallgroups'] = 'Prepreči zadnjo manjšo skupino';
$string['notingrouping'] = '[Ni v skupku]';
$string['nousersinrole'] = 'V izbrani vlogi ni primernih uporabnikov';
$string['number'] = 'Števec skupina/član';
$string['numgroups'] = 'Število skupin';
$string['nummembers'] = 'Članov na skupino';
$string['overview'] = 'Pregled';
$string['potentialmembers'] = 'Možni člani: $a';
$string['printerfriendly'] = 'Različica primerna za tisk';
$string['random'] = 'Naključno';
$string['removegroupfromselectedgrouping'] = 'Odstrani skupino iz skupka';
$string['removegroupingsmembers'] = 'Odstrani vse skupine iz skupka';
$string['removegroupsmembers'] = 'Odstrani vse člane skupine';
$string['removeselectedusers'] = 'Odstrani izbrane uporabnike';
$string['selectfromrole'] = 'Izberi člane iz vloge';
$string['showgroupsingrouping'] = 'Pokaži skupine v skupkih';
$string['showmembersforgroup'] = 'Prikaži člane skupine';
$string['toomanygroups'] = 'Ni dovolj članov za napolnitev določenega števila skupin - v izbrani vloge je le $a uporabnikov.';
$string['usercount'] = 'Števec uporabnikov';
$string['usercounttotal'] = 'Števec uporabnikov ($a)';
$string['usergroupmembership'] = 'Članstvo izbranega uporabnika:';
$string['cancel'] = 'Prekliči'; // ORPHANED
$string['defaultgroupdescription'] = 'Privzet opis skupine'; // ORPHANED
$string['defaultgroupprefix'] = 'Skupina'; // ORPHANED
$string['displaygrouping'] = 'Prikaži skupek'; // ORPHANED
$string['distributealphabetically'] = 'Razdeli v skupine po abecednem redu imena'; // ORPHANED
$string['distributeevenly'] = 'Enakomerno porazdeli preostale udeležence'; // ORPHANED
$string['editgroupingpermissions'] = 'Uredi dovoljenja skupka'; // ORPHANED
$string['errorinvalidgrouping'] = 'Napaka, neveljaven skupek $a'; // ORPHANED
$string['errornotingrouping'] = 'Žal ne morete ustvariti skupine v $a'; // ORPHANED
$string['errornotingroupingedit'] = 'Žal ne morete urejati skupka $a'; // ORPHANED
$string['groupfor'] = 'za skupino'; // ORPHANED
$string['numberofgroups'] = 'Število skupin'; // ORPHANED
$string['numberofstudents'] = 'Število udeležencev'; // ORPHANED
$string['prefixforgroupnames'] = 'Naziv pred imeni skupin'; // ORPHANED
$string['return'] = 'Nazaj'; // ORPHANED
$string['save'] = 'Shrani'; // ORPHANED
$string['selectnumberineachgroup'] = 'Izberite število za vsako skupino'; // ORPHANED
$string['selectnumberofgroups'] = 'Izberite število skupin'; // ORPHANED
$string['showusersalreadyingroup'] = 'Prikaži uporabnike, ki so že v skupini v skupku'; // ORPHANED
$string['teachersgroupmark'] = 'Izvajalci ne morejo ocenjevati dejavnosti skupin, katerim sami ne pripadajo'; // ORPHANED
$string['teachersgroupview'] = 'Izvajalci ne morejo pregledovati dejavnosti skupin, katerim sami ne pripadajo'; // ORPHANED
$string['teachersoverride'] = 'Izvajalci, ki niso v nobeni skupini, lahko pregledujejo in ocenjujejo dejavnosti za vse skupine (povozi zgornje)'; // ORPHANED
$string['upgradeconfirm'] = 'Žal morajo biti tabele skupin, ki so bile ustvarjene v Moodle 1.8 DEV, izbrisane za to posodobitev. Želite nadaljevati?'; // ORPHANED
$string['usestudentsonlyfromselectedgroup'] = 'Uporabi samo udeležence iz trenutno izbrane skupine'; // ORPHANED
$string['viewallgroupsactivities'] = 'Udeleženci lahko pregledujejo, vendar ne sodelujejo, pri dejavnostih vseh skupin'; // ORPHANED
$string['viewallgroupsmembers'] = 'Udeleženci lahko vidijo vse člane vseh skupin'; // ORPHANED
$string['viewowngroup'] = 'Udeleženci lahko vidijo člane vseh skupin, katerim sami pripadajo'; // ORPHANED

?>
