<?PHP // $Id$ 
      // auth.php - created with Moodle 1.7+ (2006101007)


$string['alternatelogin'] = 'Hemen URL bat sartuz gero,  tokirako sarbide gisa erabiliko da. Orriak formularioa eduki beharko luke, ekintza <strong>\'$a\'</strong> ezaugarrian ezarrita duena eta eremu hauek itzultzen dituena: <strong>erabiltzaile-izena</strong> eta <strong>pasahitza</strong>.<br />URL desegokia ez sartzen saia zaitez, hori egiteak tokitik egoiztea ekarriko baitu.<br />Lehenetsitako sarbide erabiltzeko zuriz utzi, mesedez.';
$string['alternateloginurl'] = 'Aukerazko sarbiderako URLa';
$string['auth_cas_baseuri'] = 'Zerbitzariaren URIa (zuriz Uri oinarririk ez badago)<br />Adibidez, CAS zerbitzariak host.domaine.com/CAS/ helbideari erantzuten badio, orduan<br />cas_baseuri = CAS/';
$string['auth_cas_create_user'] = 'Moodleren datu-basean CASen bidez onartutako erabiltzaileak erantsi nahi badituzu aktibatu. Bestela, Moodleren datu-basean honez gero dauden erabiltzaileek soilik izango dute sarbidea.';
$string['auth_cas_enabled'] = 'Aktibatu CAS autentifikazioa nahi baduzu.';
$string['auth_cas_hostname'] = 'CAS zerbitzariaren izena<br />ad.: host.domain.eu';
$string['auth_cas_invalidcaslogin'] = 'Sentitzen dugu, zure loginak huts egin du: ezin zara sartu';
$string['auth_cas_language'] = 'Hizkuntza aukeratua';
$string['auth_cas_logincas'] = 'Konexio seguruaren sarbidea';
$string['auth_cas_port'] = 'CAS zerbitzariaren portua';
$string['auth_cas_server_settings'] = 'CAS zerbitzariaren ezarpenak';
$string['auth_cas_text'] = 'Konexio segurua';
$string['auth_cas_version'] = 'CASen bertsioa';
$string['auth_casdescription'] = 'Metodo honek CAS zerbitzaria erabiltzen du (Central Authentication Service) erabiltzaileak SSO (Single Sign On) inguruan autentikatzeko. Nahi baduzu LDAP autentikazio xumea erabil dezakezu. Erabiltzaile-izena eta pasahitza CASen arabera egokiak badira, Moodlek erabiltzaile berri bat sortzen du datubasean, beharko balitz LDAPetik atributuak hartuz. Hurrengo konexioetan erabiltzaile-izena eta pasahitza baieztatzen dira, besterik ez.';
$string['auth_castitle'] = 'CAS zerbitzaria erabili (SSO)';
$string['auth_changepasswordhelp'] = 'Pasahitza aldatzeko laguntza';
$string['auth_changepasswordhelp_expl'] = '$a pasahitza galdu duten erabiltzaileei laguntza erakusten die. Aukera hau erantsi daiteke edo <strong>Pasahitza aldaketaren URLa</strong>ren ordez erakutsi edo Moodleren barne pasahitza-aldaketa moduan azaldu.';
$string['auth_changepasswordurl'] = 'URL Pasahitz aldaketa';
$string['auth_changepasswordurl_expl'] = 'Pasahitza galdu duten erabiltzaileak zer URL helbidera bidaliko dituzun zehaztu $a. <strong>Pasahitz aldaketa orri estandar erabili</strong> orrian <strong>Ez</strong> aukeratu.';
$string['auth_common_settings'] = 'Ezarpen komunak';
$string['auth_data_mapping'] = 'Datuen mapa';
$string['auth_dbdescription'] = 'Metodo honek kanpoko datu-base taula bat erabiltzen du emandako erabiltzaile izen eta pasahitz bat baliozkoa den egiaztatzeko.  kontua berria bada, beste eremuetako informazioa ere zeharka kopiatu daiteke Moddlen.';
$string['auth_dbextrafields'] = 'Eremu hauek aukerazkoak dira.  Moddle erabiltzaileen eremu batzuk hemen zehaztutako <B>kanpoko datu-base eremuetatik</B> aurrez betetzea erabaki dezakezu. <P>Hutsik uzten badituzu, lehenetsitako balioak erabiliko dira.<P>Edozein kasutan, erabiltzaileek eremu guztiak editazeko aukera izango dute behin saioa hasita.';
$string['auth_dbfieldpass'] = 'Pasahitzak dituen eremuaren izena';
$string['auth_dbfielduser'] = 'Erabiltzaile-izenak dituen eremuaren izena';
$string['auth_dbhost'] = 'Datu-base zerbitzaria ostatatzen duen ordenagailua.';
$string['auth_dbname'] = 'Datu-basearen izena';
$string['auth_dbpass'] = 'Goiko erabiltzaile izenarekin bat datorren pasahitza';
$string['auth_dbpasstype'] = 'Pasahitza eremuak erabiltzen duen formatua zehaztu.  MD5 enkiptazioa beste web aplikazio orokorrekin konektatzeko erabilgarria da, PostNuke adibidez';
$string['auth_dbtable'] = 'Datu-baseko taulak duen izena';
$string['auth_dbtitle'] = 'Kanpoko datu-base bat erabili';
$string['auth_dbtype'] = 'Datu-base mota (Ikus <A HREF=../lib/adodb/readme.htm#drivers>ADOdb documentation</A> xehetasun gahiagorako)';
$string['auth_dbuser'] = 'Datu-basean irakurtzeko baimena duen erabiltzaile izena';
$string['auth_emaildescription'] = 'ePostaz berrestea da lehenetsitako autentifikazio metodoa.  Erabiltzaileak izena ematen duenean, bere izen eta pasahitza aukeratuz, konfirmazio ePosta mezu bat bidaltzen zaio erabiltzailearen ePostara.  ePosta Mezu honek, erabiltzaileei kontua berresteko aukera emango dien orri batera lotura zihur bat du. Hurrengoetan saioa hasteko izen eta pasahitza Moodle datu-basean dauden balioekin konparatzea nahikoa da.';
$string['auth_emailtitle'] = 'E-postaren bidezko autentifikazioa';
$string['auth_fccreators'] = 'Ikastaro berriak sor ditzaketen taldeko partaideen zerrenda. Taldeak \';\' erabiliz banandu. Izenak FirstClass zerbitzarian bezalaxe idatzi behar dira. Sistemak maiuskulak eta minuskulak bereizten ditu.';
$string['auth_fcdescription'] = 'Metodo honek FirstClass zerbitzaria erabiltzen du erabiltzailearen izena edo pasahitza zuzenak diren baieztatzeko.';
$string['auth_fcfppport'] = 'Zerbitzariaren portua (ohikoena 3333 izaten da)';
$string['auth_fchost'] = 'FirstClass zerbitzariaren helbidea. IP zenbakia edo DNS izena erabili.';
$string['auth_fcpasswd'] = 'Aurreko kontuko pasahitza.';
$string['auth_fctitle'] = 'FirstClass zerbitzaria erabili';
$string['auth_fcuserid'] = 'FirstClass kontuko erabiltzailearen identifikazioa \'Kudeatzaile-ordea\'.';
$string['auth_fieldlock'] = 'Balorea bloketau';
$string['auth_fieldlock_expl'] = '<p><b>Balorea blokeatu:</b> Ezarriz gero, Moodleko erabiltzaile eta kudeatzaileek ezingo dute eremua zuzenean editatu. Aukeratu hau hautatu datu horiek kanpoko autentifikazio-sisteman badituzu. </p>';
$string['auth_fieldlocks'] = 'Erabiltzaile eremuak blokeatu';
$string['auth_fieldlocks_help'] = '<p>Erabiltzaileen datu-eremuak blokea ditzakezu, kudeatzaileek datuok eskuz mantentzen dituzten guneetan bereziki erabilgarria gertazen dena, erabiltzaileen erregistroak editatuz edo \'Erabiltzaileak igo\' aplikazioaren bidez. Moodlek behar dituen eremuak blokeatzen badituzu, erabiltzaile-kontuak sortzean datu horiek ematen dituzula ziurtatu &emdash; bestela, kontuak ezinog dira erabili.</p><p>Pentsa ezazu ea \'Hutsik egotekotan desblokeatu\' aukera aktibatu behar duzun arazo hori ebitatzeko.</p>';
$string['auth_imapdescription'] = 'Metodo honek IMAP zerbitzari bat erabiltzen du emandako erabiltzaile izen eta pasahitza baliozkoak diren egiaztatzeko.';
$string['auth_imaphost'] = 'IMAP zerbitzariaren helbidea. IP helbidea erabili ezazu, ez DNS izena.';
$string['auth_imapport'] = 'IMAP zerbitzariaren kaia zenbakia. 143 edo 993 izan ohi da.';
$string['auth_imaptitle'] = 'IMAP zerbitzari bat erabili';
$string['auth_imaptype'] = 'IMAP zerbitzari mota.  IMAP zerbitzariak autentifikazio eta negoziazio mota ezberdinak izan ditzazkete.';
$string['auth_ldap_bind_dn'] = 'Erabiltzaileak bilatzeko bind-user erabili nahi baduzu, hemen zehaztu. Honen antzeko zerbait: \'cn=ldapuser,ou=public,o=org\'';
$string['auth_ldap_bind_pw'] = 'bind-user erabiltzaile pasahitza.';
$string['auth_ldap_bind_settings'] = 'Ezarpenak finkatu';
$string['auth_ldap_contexts'] = 'Erabiltzaileak kokatzen diren testuinguru zerrenda. Testuinguruak \';\' erabiliz banatu. Adibidez: \'ou=users,o=org; ou=others,o=org\'';
$string['auth_ldap_create_context'] = 'E-mailaren bitartez erabiltzailearen sorrera indarrean jartzen baduzu, zehaztu erabiltzaileak sortuko direneko egoera. Egoera horrek beste erabiltzaileenaren desberdina izan behar du arazoak ekiditeko. Egoera hori ez da Idap_context-variable-n itsatsi behar, Moodlek egoera horretako erabiltzaileak automatikoki bilatuko ditu.';
$string['auth_ldap_creators'] = 'Ikastaro berriak sortzeko baimena duten partaideen taldeak. Taldeak \';\' zeinuaren bidez bana daiteke. Normalki era honetan egingo genuke: \'cn=teachers,ou=staff,o=myorg\'';
$string['auth_ldap_expiration_desc'] = 'Pasahitza kadukatu ote den indargabetzeko Ez aukeratu, edo LDAP pasahitzaren kaduzitate denbora zuzenean LDAPetik irakurtzeko.';
$string['auth_ldap_expiration_warning_desc'] = 'Pasahitzaren kaduzitate-oharra agertu aurretiko egun-kopurua.';
$string['auth_ldap_expireattr_desc'] = 'Aukerazkoa: Pasahitzaren kaduzitatea metatzen duen ldap atributua indargabetzen du
PasswordExpirationTime';
$string['auth_ldap_graceattr_desc'] = 'Aukerazkoa: Gracelogin atributua indargabetzen du';
$string['auth_ldap_gracelogins_desc'] = 'LDAP sarrera askeko euskarria indartu. Pasahitza kadukatutakoan, erabiltzailea sarbide askeko kontua zerora iritsi arte sar daiteke. Aukera hau aktibatuz gero sarbide askeko mezua erakutsiko da, pasahitza kadukatu bada.';
$string['auth_ldap_host_url'] = 'LDAP ostatua URL bidez zehaztu, adibidez \'ldap://ldap.zerbitzaria.com/\' edo \'ldaps://ldap.zerbitzaria.com/\'';
$string['auth_ldap_login_settings'] = 'Sarrera-ezarpenak';
$string['auth_ldap_memberattribute'] = 'Erabiltzailearen izenerako atributua zehaztu, erabiltzaileak taldean biltzen direnean. Normalean \'partaide\'';
$string['auth_ldap_objectclass'] = 'Name/search erabiltzaileentzako iragazkia. Normalean honen antzeko ezarpena egin beharko duzu: objectClass=posixAccount. ObjectClass=* delakoaren lehenetsitako baloreak objektu guztiak LDAPetik itzuliko dituztenak.';
$string['auth_ldap_opt_deref'] = 'Bilaketan zehar aliasak nola maneiatu zehazten du. Balorea hauetako bat aukeratu: \"Ez\" (LDAP_DEREF_NEVER) edo \"Bai\" (LDAP_DEREF_ALWAYS)';
$string['auth_ldap_passwdexpire_settings'] = 'LDAP pasahitzaren kaduzitate-ezarpenak.';
$string['auth_ldap_preventpassindb'] = '\'Bai\' aukeratu pasahitzak Moodleren datubasean ez gordetzeko.';
$string['auth_ldap_search_sub'] = '<> 0 balioa jarri erabiltzaileak azpi-testuinguruneetan bilatu nahi badituzu.';
$string['auth_ldap_server_settings'] = 'LDAP zerbitzariaren ezarpenak';
$string['auth_ldap_update_userinfo'] = 'Erabiltzaile informazioa (izena, abizena, helbidea..) LDAP-tik Moodle-ra eguneratu. /auth/ldap/attr_mappings.php fitxategian begira ezazu mapa informazioa';
$string['auth_ldap_user_attribute'] = 'Erbiltzaileak izendatzeko edo bilatzeko atributua. \'cn\' izan ohi da.';
$string['auth_ldap_user_settings'] = 'Erabiltzailearen bilaketaren ezarpenak';
$string['auth_ldap_user_type'] = 'Erabiltzaileak LDAPen nola gordeko diren aukeratu. Ezarpen honek sarbidearen kaduzitateak, sarbide askeek eta erabiltzaileen sorrerak nola funtzionatuko duten zehazten du.';
$string['auth_ldap_version'] = 'Zure zerbitzariak erabiltzen duen LDAP protokoloaren bertsioa.';
$string['auth_ldapdescription'] = 'Metodo honek kanpo LDAP zerbitzari baten aurkako autentifikazioa eskeintzen du.
                                  Emandako erabiltzaile izen eta pasahitza baliozkoak badira, Moodlek erabiltzaile 
								  sarrera berri bat sortuko du bere datu-basean. Modulu honek erabiltzaile atributuak 
								  LDAP zerbitzaritik irakurri ditzazke eta eremuak Moodlen bete.  Hurrengo saio hasieretan
								  soilik izen eta pasahitza egiaztatuko dira.';
$string['auth_ldapextrafields'] = 'Eremu hauek aukerazkoak dira.  Moodle erabiltzaile eremu batzuk hemen zehaztutako <b>LDAP eremu</b>etako informazioz betetzea aukeratu dezakezu. <P>Zurian uzten badituzu, ez da ezer transferituko LDAP-tik eta Moodlek lehenetsitako balioak erabiliko dira ordez.<P>Edozein kasutan, erabiltzaileak eremu guzti hauek editatzeko gaitasuna izango du behin saioa hasita.';
$string['auth_ldaptitle'] = 'LDAP zerbitzari bat erabili';
$string['auth_manualdescription'] = 'Metodo honek erabiltzaileen sorrera automatizatua ahalbidetzen du. Erabiltzaile guztiak kudeatzaileak sortu behar ditu.';
$string['auth_manualtitle'] = 'Eskuko kontuak soilik';
$string['auth_multiplehosts'] = 'Zerbitzari anitzak zehaz daitezke (ad. zerbitzari1.com;zerbitzari2.com;zerbitzari3.com';
$string['auth_nntpdescription'] = 'Metodo honek NNTP zerbitzari bat erabiltzen du emandako erabiltzaile izen eta pasahitza baliozkoak diren egiaztatzeko.';
$string['auth_nntphost'] = 'NNTP zerbitzariaren helbidea. IP zenbakia erabili ezazu, ez DNS izena.';
$string['auth_nntpport'] = 'Zerbitzari kaia (119 arruntena da)';
$string['auth_nntptitle'] = 'NNTP zerbitzari bat erabili';
$string['auth_nonedescription'] = 'Erabiltzaileen berehala eman dezakete izena eta baliozko kontuak sortu, kanpo zerbitzari baten aurkako autentifikaziorik gabe eta ePosta bidez berretsi gabe.  Aukera hau erabiltzeerekin kontuz - honek sor ditzazkeen segurtasun eta administrazio arazoak kontutan hartu.';
$string['auth_nonetitle'] = 'Autentifikaziorik ez';
$string['auth_pamdescription'] = 'Metodo honek PAM erabiltzen du zerbitzari honetako erabiltzaileen izenetara sarbidea izateko. Modulu hau erabiltzeko <a href=\"http://www.math.ohio-state.edu/~ccunning/pam_auth/\" target=\"_blank\">PHP4 PAM Authentication</a> instalatu behar duzu.';
$string['auth_pamtitle'] = 'PAM (Pluggable Authentication Modules)';
$string['auth_passwordisexpired'] = 'Zure pasahitza kadukatuta dago. Pasahitza orain aldatu nahi al duzu?';
$string['auth_passwordwillexpire'] = 'Zure pasahitza duela $a egun kadukatu da. Pasahitza orain aldatu nahi al duzu?';
$string['auth_pop3description'] = 'Metodo honek POP3 zerbitzari bat erabiltzen du emandako erabiltzaile izen eta pasahitza baliozkoak diren egiaztatzeko.';
$string['auth_pop3host'] = 'POP3 zerbitzariaren helbidea. IP zenbakia erabili, ez DNS izena.';
$string['auth_pop3mailbox'] = 'Konexioa saiatzeko sarrera ontziaren izena(normalean INBOX)';
$string['auth_pop3port'] = 'Zerbitzari kaia (110 izan ohi da)';
$string['auth_pop3title'] = 'POP3 zerbitzari bat erabili';
$string['auth_pop3type'] = 'Zerbitzari mota. Zure zerbitzariak zertifikatu segurtasuna erabiltzen badu, pop3cert aukeratu ezazu.';
$string['auth_radiusdescription'] = 'Metodo honek <a href=\"http://en.wikipedia.org/wiki/RADIUS\" target=\"_blank\">RADIUS</a> zerbitzaria erabiltzen du erabiltzailearen izena eta pasahitza egokiak diren ziurtatzeko.';
$string['auth_radiushost'] = 'RADIUS zerbitzariaren helbidea';
$string['auth_radiusnasport'] = 'Konexiorako erabili beharreko kaia';
$string['auth_radiussecret'] = 'Elkarbanatutako sekretua';
$string['auth_radiustitle'] = 'RADIUS zerbitzaria erabili';
$string['auth_shib_convert_data'] = 'Datuen aldaketarako APIa';
$string['auth_shib_convert_data_description'] = 'API hau aurrerago Shibboleth-ek emandako datuak aldatzeko erabil dezakezu. <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">README</a> irakurri argibide gehigarriak ikusteko.';
$string['auth_shib_convert_data_warning'] = 'Fitxategirik ez dago, edo zerbitzariaren prozesuak ezin du irakurri.';
$string['auth_shib_instructions'] = '<a href=\"$a\">Shibboleth login</a> erabili Shibboleth-en bidez sartzeko zure erakundeak onartzen badu.<br />Bestela, hemen erakusten den sarrera arrunteko formularioa erabili.';
$string['auth_shib_instructions_help'] = 'Hemen zure erabiltzaileei Shibboleth erabiltzeko argibide pertsonalizatuak eman beharko zenizkieke. Sarbide orriko argibideen atalean agertu beharko lirateke, eta \"<b>$a</b>\" esteka erakutsi, Shibboletheko erabiltzaileak erraz sar daitezen. Zuriz utziz gero, argibide estandarrak erakutsiko dira (ez Shibboleth-enak berak)';
$string['auth_shib_only'] = 'Shibboleth soilik';
$string['auth_shib_only_description'] = 'Aukera hau hartu soilik Shibboleth autentikazioa bortxatu nahi baduzu.';
$string['auth_shib_username_description'] = 'Moodlen erabiltzaile izen gisa erabiliko den Shibboleth zerbitzariaren testuinguru aldagaiaren izena';
$string['auth_shibboleth_login'] = 'Shibboleth sarbidea';
$string['auth_shibboleth_manual_login'] = 'Eskuko sarbidea';
$string['auth_shibbolethdescription'] = 'Metodo honen bidez Shibboleth zerbitzari batera konekta zaitezke kontu berriak sortu eta konprobatzeko';
$string['auth_shibbolethtitle'] = 'Shibboleth';
$string['auth_updatelocal'] = 'Datu lokalak eguneratu';
$string['auth_updatelocal_expl'] = '<p><b>Datu lokalak eguneratu:</b> Aktibatuta badago, eremua eguneratu behar da (kanpoko autentikazioz) erabiltzailea sartu edo erabiltzaileen sinkronizazioa gertatzen den bakoitzean. Modu lokalean eguneratu beharreko eremuak blokeatu beharko lirateke.</p>';
$string['auth_updateremote'] = 'Kanpoko datuak eguneratu';
$string['auth_updateremote_expl'] = '<p><b>Kanpoko datuak eguneratu:</b> Aktibatuta badago, kanpoko autenla autenticaci�n externa ser� actualizada cuando se actualice el registro del usuario. Los campos deber�an estar desbloqueados para poder editarlos.</p>';
$string['auth_updateremote_ldap'] = '<p><b>Oharra:</b> LDAP kanpoko datuen eguneratzeak \'binddn\' eta \'bindpw\' baloreak ezartzeko eskatzen du erabiltzaile-erregistro guztien edizio-baimena duen erabiltzaile batentzat. Oraingoz, honek ez ditu balio anitzeko atributuak babesten, eta soberako baloreak ezabatuko ditu eguneratzean zehar. </p>';
$string['auth_user_create'] = 'Erabiltzailearen sorrera ahalbidetu';
$string['auth_user_creation'] = 'Erabiltzaile anonimo berriek erabiltzaile-kontuak autentikazioko kanpo kodearen gainean sor ditzakete eta e-mailez baieztatu. Hau indarrean jartzen baduzu, erabiltzaileen sorrerarako moduluaren aukerak ere ezarri behar dituzula gogoratu.';
$string['auth_usernameexists'] = 'Aukeratutako erabiltzailearen izena honez gero badago. Beste bat aukeratu, mesedez.';
$string['authenticationoptions'] = 'Autentifikazio aukerak';
$string['authinstructions'] = 'Hemen zure erabiltzaileentzat argibideak eman ditzazkezu, erabili behar duten erabiltzaile eta pasahitza zeintzu diren jakin dezaten.  Hemen sartutako testua saio hasiera pantailan agertuko da.  Zurian uzten baduzu ez da argibiderik emango.';
$string['changepassword'] = 'Pasahitz URL-a aldatu';
$string['changepasswordhelp'] = 'Hemen zure erabiltzaileek bere izen edo pasahitza aldatzeko, edo ahaztekotan berreskuratzeko, erabili dezaketen helbide bat zehaztu dezakezu.  Hau erabiltzaileei saio hasiera pantailan eta erabiltzaile orrian botoi gisa aurkeztuko zaie.  Zurian uzten baduzu ez zaie botoirik aurkeztuko.';
$string['chooseauthmethod'] = 'Autentifikazio metodoa aukeratu:';
$string['createpasswordifneeded'] = 'Pasahitza sortu, beharrezkoa bada.';
$string['forcechangepassword'] = 'Pasahitz aldaketa behartu';
$string['forcechangepassword_help'] = 'Erabiltzaileak Moodlen sartzen diren hurrengoan pasahitza aldatzera behartu.';
$string['forcechangepasswordfirst_help'] = 'Erabiltzaileak Moodlen sartzen diren lehenengoan pasahitza aldatzera behartu.';
$string['guestloginbutton'] = 'Bisitariek saioa hasteko botoia';
$string['infilefield'] = 'Fitxategiko eremu beharrezkoa';
$string['instructions'] = 'Argibideak';
$string['internal'] = 'Barrukoa';
$string['locked'] = 'Blokeatuta';
$string['md5'] = 'MD5 enkriptazioa';
$string['passwordhandling'] = 'Pasahitz eremuaren kudeaketa';
$string['plaintext'] = 'Testu arrunta';
$string['shib_no_attributes_error'] = 'Badirudi Shibboleth-ek autentikatu zaituela, baina Moodlek ez du erabiltzaile-atributurik jaso. Zure nortasun-emaileak beharrezkoak diren ($a) atributuak Moodle egikaritzen ari den Zerbitzu Emaileari pasa dizkiola ziurtatu, edo zerbitzari honetako webmasterrari jakinarazi.';
$string['shib_not_all_attributes_error'] = 'Moodle Shibboleth-en atributu batzuk behar ditu, kasu honetan agertzen ez direnak. Atributuak hauek dira: $a<br />Mesedez, webmasterrarekin edo nortasun-emailearekin harremanetan jarri.';
$string['shib_not_set_up_error'] = 'Ez dirudi Shibboleth autentikazioa zuzena denik orri honetan Shibboleth-en testuinguruko aldagaiak ez daudelako. Shibboleth autentikazioa nola definitzen den jakin nahi baduzu, <a href=\"README.txt\">README</a> fitxategia kontsultatu edo Moodleren instalazio honetako webmasterrarekin harremanetan jarri, mesedez.';
$string['showguestlogin'] = 'Bisitariek saioa hasteko botoia bistaratu edo ezkutatu dezakezu saio hasiera pantailan.';
$string['stdchangepassword'] = 'Pasahitz aldaketa arrunta erabili.';
$string['stdchangepassword_expl'] = 'Kanpoko autentikazio-sistemak Moodlen pasahitz aldaketa ahalbidetzen badu, Bai aukera ezazu. Ezarpen honek \'URL pasahitza aldatu\' gainditzen du.';
$string['stdchangepassword_explldap'] = 'OHARRA: LDAP SSL enkripzio-tunel baten gainean erabiltzea aholkatzen da (ldaps://) LDAP zerbitzaria urrutikoa bada.';
$string['unlocked'] = 'Desblokeatuta';
$string['unlockedifempty'] = 'Desblokeatua hutsik badago';
$string['update_never'] = 'Inoiz ez';
$string['update_oncreate'] = 'Sortzean';
$string['update_onlogin'] = 'Sarrera bakoitzean';
$string['update_onupdate'] = 'Eguneratzean';

?>
