<?PHP // $Id$ 
      // blog.php - created with Moodle 1.9.2+ (Build: 20080910) (2007101522)


$string['addnewentry'] = 'Sarrera berria gehitu';
$string['backupblogshelp'] = 'Gaituz gero, blogak ere GUNEAren automatizatutako segurtasun-kopietan sartuko dira';
$string['blockmenutitle'] = 'Blog-menua';
$string['blocktagstitle'] = 'Blog-etiketak';
$string['blocktitle'] = 'Blog-etiketen bloke izenburua';
$string['blog'] = 'Bloga';
$string['blogdeleteconfirm'] = 'Blog hau ezabatu?';
$string['blogdisable'] = 'Blogak desgaituta daude!';
$string['blogpreferences'] = 'Blog-aukerak';
$string['blogs'] = 'Blogak';
$string['blogtags'] = 'Blogaren etiketak';
$string['cannotviewcourseblog'] = 'Ez duzu baimenik ikastaro honetako blogak ikusteko';
$string['cannotviewcourseorgroupblog'] = 'Ez duzu baimenik ikastaro/talde honetako blogak ikusteko';
$string['cannotviewsiteblog'] = 'Ez duzu baimenik guneko blog guztiak ikusteko';
$string['cannotviewuserblog'] = 'Ez duzu erabiltzaileen bloga irakurtzeko baimenik';
$string['courseblog'] = 'Ikastaroaren bloga: $a';
$string['courseblogdisable'] = 'Ikastaraoko blogak ez daude gaituta';
$string['courseblogs'] = 'Erabiltzaileek beren ikastaro bereko pertsonen blogak baino ezin dituzte ikusi';
$string['deleteotagswarn'] = 'Ziur al zaude etiketa hau(ek) <br /> mezu guztietatik ezabatu nahi d(it)uzula eta sistematik kendu?';
$string['deleteposterror'] = 'Errorea gertatu da mezuak ezabatzean';
$string['disableblogs'] = 'Blog-sistema desgaitu';
$string['donothaveblog'] = 'Zeuk ez duzu blogik, barkatu';
$string['emptybody'] = 'Blog-sarreraren gorputza ezin da hutsik egon';
$string['emptytitle'] = 'Blog-sarreraren izenburua ezin da hutsik egon';
$string['entrybody'] = 'Blog-sarreraren gorputza';
$string['entrybodyonlydesc'] = 'Deskribapena idatzi';
$string['entryerrornotyours'] = 'Sarrera hau ez da zurea';
$string['entrysaved'] = 'Zure sarrera gorde da';
$string['entrytitle'] = 'Izenburua idatzi';
$string['entryupdated'] = 'Blog sarrera eguneratuta';
$string['groupblog'] = 'Taldearen bloga: $a';
$string['groupblogdisable'] = 'Taldearen bloga ez dago gaituta';
$string['groupblogs'] = 'Erabiltzaileek beren talde bereko pertsonen blogak baino ezin dituzte ikusi';
$string['incorrectblogfilter'] = 'Zehaztutako blog-iragazkia ez da zuzena';
$string['intro'] = 'RSS jario hau automatikoki sortu da blog batetik edo batzuetatik';
$string['noentriesyet'] = 'Sarrerak ez daude ikusgai hemen';
$string['noguestpost'] = 'Gonbidatuek ezin dute sarrerarik egin';
$string['norighttodeletetag'] = 'Zuk ez duzu etiketa hau ezabatzeko baimenik';
$string['nosuchentry'] = 'Ez dago blog-sarrerarik';
$string['notallowedtoedit'] = 'Zuk ez duzu sarrera hau editatzeko baimenik';
$string['numberofentries'] = 'Sarrerak: $a';
$string['numberoftags'] = 'Erakutsi beharreko etiketen kopurua';
$string['pagesize'] = 'Orri bakoitzeko sarrera-kopurua';
$string['permalink'] = 'Lotura iraunkorra';
$string['personalblogs'] = 'Erabiltzaileek beren blogak baino ezin dituzte ikusi';
$string['publishto'] = 'Norentzat argitaratu';
$string['publishtonoone'] = 'Zuretzat bakarrik (zirriborroa)';
$string['publishtosite'] = 'Gune honetako guztientzat';
$string['publishtoworld'] = 'Mundu osoarentzat';
$string['settingsupdatederror'] = 'Errorea gertatu da: blog aukera berriak ezin izan dira eguneratu';
$string['siteblog'] = 'Gunearen bloga: $a';
$string['siteblogdisable'] = 'Gunearen bloga ez dago gaituta';
$string['siteblogs'] = 'Erabiltzaile guztiek blog-sarrera guztiak ikusi ahal dituzte';
$string['tagdatelastused'] = 'Etiketa hau erabili zen azken eguna';
$string['tags'] = 'Etiketak';
$string['tagsort'] = 'Zeren arabera ordeantu etiketak';
$string['tagtext'] = 'Etiketaren testua';
$string['timewithin'] = 'Egun hauetan erabilitako etiketak erakutsi';
$string['updateentrywithid'] = 'Sarrera eguneratzen';
$string['userblog'] = 'Erabiltzailearen bloga: $a';
$string['viewcourseentries'] = 'Ikastaroaren sarrerak ikusi';
$string['viewmyentries'] = 'Nire sarrerak ikusi';
$string['viewsiteentries'] = 'Gunearen sarrerak ikusi';
$string['worldblogs'] = 'Edozeinek ikus ditzake mundu osoarentzat argitaratutako sarrerak';
$string['wrongpostid'] = 'Blog-mezuaren ID okerra';
$string['addotags'] = 'Etiketa ofizialak gehitu'; // ORPHANED
$string['addptags'] = 'Erabiltzaileak zehaztutako etiketak gehitu'; // ORPHANED
$string['otags'] = 'Etiketa ofizialak'; // ORPHANED
$string['ptags'] = 'Erabiltzaileak zehaztutako etiketak'; // ORPHANED

?>
