<?PHP // $Id$ 
      // error.php - created with Moodle 1.9.2+ (Build: 20080910) (2007101522)


$string['adminprimarynoedit'] = 'Lehen mailako kudeatzailea ezin dute besteek editatu.';
$string['cannotassignrole'] = 'Ezin da ikastaroan rola ezarri';
$string['cannotcreatelangdir'] = 'Lang direktorioa ezin da sortu.';
$string['cannotcreatetempdir'] = 'Temp direktorioa ezin da sortu.';
$string['cannotcustomizelocallang'] = 'Ez duzu baimenik kateen itzulpena pertsonalizatzeko. Baimen hau \"moodle/site:langeditlocal\" gaitasunak kontrolatzen du. Itzulpenak zure  gunerako egokitu nahi badituzu, gaitasun hau baimendu behar duzu.';
$string['cannotdownloadcomponents'] = 'Ezin dira osagaiak jaitsi.';
$string['cannotdownloadlanguageupdatelist'] = 'Ezin da download.moodle.org-tik eguneratzeko hizkuntza-zerrenda jaitsi';
$string['cannotdownloadzipfile'] = 'ZIP fitxategia ezin da jaitsi.';
$string['cannoteditmasterlang'] = 'Ez duzu baimenik hizkuntza-pakete nagusia editatzeko. Baimen hau \"moodle/site:langeditmaster\" gaitasunak kontrolatzen du. Hizkuntzetako baten arduraduna bazara, gaitasun hau baimendu behar duzu.';
$string['cannotfindcomponent'] = 'Osagaia ezin da aurkitu';
$string['cannotsavemd5file'] = 'Ezin da Md5 fitxategia gorde.';
$string['cannotsavezipfile'] = 'Ezin da ZIP fitxategia gorde.';
$string['cannotunzipfile'] = 'Ezin da fitxategia deskonprimatu.';
$string['cannotviewprofile'] = 'Ezin duzu erabiltzaile honen profila ikusi';
$string['cantunenrollfrommetacourse'] = 'Ezin duzu baja eman metaikastaro honetan.';
$string['cantunenrollinthisrole'] = 'Ezin duzu ikastaro honetan baja eman oraingo rola duzun bitartean.';
$string['cmunknown'] = 'Modulu hau ezin izan da aurkitu';
$string['componentisuptodate'] = 'Osagaia eguneratu da';
$string['confirmsesskeybad'] = 'Sentitzen dugu, baina ekintza hau egiteko zure saio-pasahitza ezin izan da baieztatu. Segurtasun-ezaugarri honek zure izenean, ustekabean edo fede txarrez, eginkizun garrantzitsuen egikaritzea saihesten du. Eginkizun hori egikaritu nahi duzula ziur izan, mesedez.';
$string['couldnotassignrole'] = 'Zuri rol bat ezartzean zehaztu gabeko arazo larria gertatu da.';
$string['coursegroupunknown'] = '$a taldeari dagokion ikastaroa ez da zehaztu';
$string['csvcolumnduplicates'] = 'Bikoiztutako zutabeak atzeman dira';
$string['csvemptyfile'] = 'CSV fitxategia hutsik dago.';
$string['csvfewcolumns'] = 'Ez dago zutabe nahikorik, mesedez egiazta ezazu mugatzailearen ezarpena';
$string['csvweirdcolumns'] = 'CSV fitxategi-formatuak ez du balio - zutabe-kopurua ez da beti bat!';
$string['dbupdatefailed'] = 'Datu-basearen eguneraketak kale egin du.';
$string['downloadedfilecheckfailed'] = 'Jaitsitako fitxategiaren konprobazioak kale egin du.';
$string['duplicateusername'] = 'Bikoiztutako erabiltzaile-izena - erregistroa alde batera utzi da';
$string['errorcleaningdirectory'] = 'Errorea gertatu da \"$a\" direktorioa garbitzean.';
$string['errorcopyingfiles'] = 'Errorea fitxategiak kopiatzean';
$string['errorcreatingdirectory'] = 'Errorea \"$a\" direktorioa sortzean.';
$string['errorcreatingfile'] = 'Errorea \"$a\" fitxategia sortzean.';
$string['erroronline'] = 'Errorea $a lerroan';
$string['errorreadingfile'] = 'Errorea \"$a\" fitxategia irakurtzean';
$string['errorunzippingfiles'] = 'Errorea fitxategiak deskonprimatzean';
$string['fieldrequired'] = '\"$a\" derrigorrezko datua da';
$string['filenotfound'] = 'Barkatu, baina eskatutako fitxategia ezin izan dugu aurkitu';
$string['forumblockingtoomanyposts'] = 'Foro honetara mezuak bidaltzeko denbora-epea gainditu duzu.';
$string['groupalready'] = 'Erabiltzailea oraindik da $a taldeko partaidea';
$string['groupexistforcourse'] = 'Ikastaro honetan dagoeneko bada \"$a\" taldea';
$string['groupnotaddederror'] = '\"$a\" taldea ez da gehitu';
$string['groupunknown'] = '$a taldea ez da inongo ikastarokoa';
$string['guestnoeditprofile'] = 'Erabiltzaile bisitariek ezin dute beren profila editatu.';
$string['guestnoeditprofileother'] = 'Ezinezkoa da bisitarien profila editatzea.';
$string['invalidcontext'] = 'Testuinguru baliogabea';
$string['invalidcourse'] = 'Ikastaro baliogabea';
$string['invalidcoursemodule'] = 'Ikastaro-moduluaren ID-ak ez du balio';
$string['invalidfieldname'] = '\"$a\"  ez da izen erabilgarria eremu honetarako';
$string['invalidfiletype'] = '\"$a\" ez da fitxategi mota erabilgarria.';
$string['invalidipformat'] = 'IP helbide-formatu honek ez du balio';
$string['invalidmd5'] = 'md5 ez da baliagarria';
$string['invalidrequest'] = 'Eskaera ezegokia';
$string['invalidrole'] = 'Rol honek ez du balio';
$string['invalidurl'] = 'URL baliogabea';
$string['invalidxmlfile'] = '\"$a\" ez da XML fitxategi baliagarria.';
$string['iplookupfailed'] = 'Ezin da $a IP helbideari buruzko informaziorik aurkitu';
$string['iplookupprivate'] = 'Ezin da IP helbide pribatuaren bilaketarik erakutsi';
$string['listnoitem'] = 'Ez da elementua aurkitu.';
$string['loginasnoenrol'] = 'Ezin duzu matrikulatu edo desmatrikulatu \"Aukeratu beste rol bat\" erabiltzen ari zarenean.';
$string['loginasonecourse'] = 'Ezin zara ikastaro honetan sartu.<br />\"Aukeratu beste rol bat\" saioa bukatu behar duzu beste edozein ikastarotan sartzeko.';
$string['missingfield'] = '\"$a\" eremua falta da';
$string['missingrequiredfield'] = 'Beharrezko eremuren bat falta da.';
$string['modulemissingcode'] = '$a moduluak funtzio hau aurrera eramateko beharrezko kodea ez dauka.';
$string['modulerequirementsnotmet'] = '\"$a->modulename\" ($a->moduleversion) modulua ezin da instalatu Moodle-ren bertsio berriagoa eskatzen duelako (zure bertsioa $a->currentmoodle da, eta moduluak behar duena $a->requiremoodle da).';
$string['mustbeteacher'] = 'Orri hau irakasleek baino ezin dute ikusi';
$string['nocategorydelete'] = '\'$a\' kategoria ezin da ezabatu!';
$string['nocontext'] = 'Barkatu, ikastaro hau ez da testuinguru baliagarria';
$string['noinstances'] = 'Ikastaro honetan ez da $a azaltzen.';
$string['nologinas'] = 'Ez duzu rol hori aukeratzeko baimenik \"Aukeratu beste rol bat\"-en';
$string['nonmeaningfulcontent'] = 'Eduki esaguratsurik ez.';
$string['noparticipatorycms'] = 'Sentitzen dugu, baina ez duzu ikastaroez informatzeko partaidetza-modulurik.';
$string['nopermissions'] = 'Sentitzen dugu, baina oraingoz ez duzu hori egiteko baimenik ($a)';
$string['nostatstodisplay'] = 'Barkatu, baina ez dago erakusteko daturik';
$string['notavailable'] = 'Ez dago eskura';
$string['onlyadmins'] = 'Kudeatzaileek baino ezin dute hori egin.';
$string['onlyeditingteachers'] = 'Edizio-baimena duten irakasleek baino ezin dute hori egin.';
$string['onlyeditown'] = 'Zeure informazioa baino ezin duzu editatu';
$string['pagenotexist'] = 'Ohiz kanpoko errorea gertatu da (ez dagoen orri batera sartzeko saiakera egin da).';
$string['pleasereport'] = 'Denbora baduzu, errorea gertatu zenean zertan saiatzen ari zinen jakinaraz iezaguzu, mesedez:';
$string['pluginrequirementsnotmet'] = '\"$a->pluginname\" ($a->pluginversion) plugina ezin izan da instalatu. Moodle-ren bertsio berriagoa behar duzu (zure bertsioa $a->currentmoodle da, eta plugin-ak behar duena $a->requiremoodle da)';
$string['processingstops'] = 'Prozesamendua hemen bukatu da. Gainontzeko erregistroak ez dira kontuan hartu.';
$string['remotedownloadnotallowed'] = 'Osagaiak ezin dira zure zerbitzarira jaitsi (allow_url_fopen ez dago aktibatuta).<br /><br /><a href=\"$a->url\">$a->url</a> fitxategia eskuz jaitsi eta \"$a->dest\" kokapenean kopiatu behar duzu.';
$string['restricteduser'] = 'Sentitzen dugu, baina zure kontuak, \"$a\", ezin du holakorik egin.';
$string['scheduledbackupsdisabled'] = 'Guneko kudeatzaileak programatutako segurtasun-kopiak desgaitu ditu';
$string['sendmessage'] = 'Mezua bidali';
$string['sessionerroruser'] = 'Saioa amaitu da. Sar zaitez berriro, mesedez.';
$string['sessionerroruser2'] = 'Zure saioari eragiten dion zerbitzari-errorea antzeman da. Berriz sartu edo nabigatzailea berriro abiatu, mesedez.';
$string['sessionipnomatch'] = 'Sentitzen dugu, baina lehenengo sarreratik zure IPa aldatu dela dirudi. Ziurtasun neurri honen arrazoia crackerrek gune honetan zauden bitartean zure nortasuna ez lapurtzean datza. Erabiltzaile arruntek ez lukete mezu hau ikusi beharko. Beraz, gunearen kudeatzaileari laguntza eskatu.';
$string['statscatchupmode'] = 'Estatistika une honetan \'catchup\' moduan dago. Orain arte $a->daysdone egun prozesatu dira eta $a->dayspending prozesatzeko daude. Mesedez, beranduago aztertu berriz.';
$string['unicodeupgradeerror'] = 'Barkatu baina zure datu-basea oraindik ez dago Unicoden eta Moodle-ren bertsio honek ezin du zure datu-basea Unicodera migratu. Mesedez, eguneratu Moodle 1.7.x-era eta egin Unicoderako migrazioa Kudeaketa orritik. Hori eginda, Moodle $a-rako migrazioa egin ahal izango duzu.';
$string['unknowncourse'] = 'Ez dago \"$a\" izeneko ikastarorik';
$string['unknowncourseidnumber'] = '\"$a\" ikastaroaren ID ezezaguna';
$string['unknowngroup'] = '\"$a\" talde ezezaguna';
$string['unknownrole'] = '\"$a\" rol ezezaguna';
$string['unknownuseraction'] = 'Sentitzen dugu, baina erabiltzailearen ekintza hau ez dugu ulertzen.';
$string['userautherror'] = 'Autentifikazio-plugin ezezaguna';
$string['useremailduplicate'] = 'Bikoiztutako helbidea';
$string['usernotaddedadmin'] = 'Ezin dira kudeatzailearen kontuak ezabatu';
$string['usernotaddederror'] = '\"$a\" erabiltzailea ez da gehitu - errorea';
$string['usernotaddedregistered'] = '\"$a\" erabiltzailea ez da gehitu - dagoeneko izena emanda';
$string['usernotavailable'] = 'Erabiltzaile honen xehetasunak ezin dituzu ikusi';
$string['usernotdeletederror'] = 'Ez da erabiltzailea ezabatu - errorea.';
$string['usernotdeletedmissing'] = 'Ez da erabiltzailea ezabatu - ez da erabiltzaile-izena aurkitu.';
$string['usernotdeletedoff'] = 'Ez da erabiltzailea ezabatu - ezabatzea ez dago baimenduta';
$string['usernotrenamedadmin'] = 'Ezin dira kudeatzailearen kontuak berrizendatu';
$string['usernotrenamedexists'] = 'Erabiltzailea ez da berrizendatu - erabiltzaile-izen berria indarrean dago.';
$string['usernotrenamedmissing'] = 'Erabiltzailea ez da berrizendatu - erabiltzailearen aurreko izena ez da aurkitu.';
$string['usernotrenamedoff'] = 'Erabiltzailea ez da berrizendatu - berrizendatzea ez dago baimenduta';
$string['usernotupdatedadmin'] = 'Ezin dira kudeatzailearen kontuak eguneratu.';
$string['usernotupdatederror'] = 'Ez da erabiltzailea eguneratu - errorea.';
$string['usernotupdatednotexists'] = 'Ez da erabiltzailea eguneratu - ez da existitzen.';
$string['wrongdestpath'] = 'Bide desegokia.';
$string['wrongsourcebase'] = 'URL iturriaren oinarri akastuna.';
$string['wrongzipfilename'] = 'ZIP fitxategiaren izen desegokia.';
$string['blockdoesnotexist'] = 'Bloke hau ez da existitzen'; // ORPHANED
$string['blocknameconflict'] = 'Izenen arteko gatazka: $a->name blokeak dagoeneko baden beste bloke honen izenburu bera du: $a->conflict!'; // ORPHANED
$string['cannotaddcoursemodule'] = 'Ezin da ikastaro modulu berria gehitu'; // ORPHANED
$string['cannotaddnewmodule'] = 'Ezin da modulun berria gehitu $a -rako'; // ORPHANED
$string['cannotaddrss'] = 'Ez duzu baimenik RSS jarioak gehitzeko'; // ORPHANED
$string['cannotassignanthing'] = 'Ezin da moodle/site:doanything esleitu'; // ORPHANED
$string['cannotcreategroup'] = 'Errorea taldea sortzean'; // ORPHANED
$string['cannotfindteacher'] = 'Ezin da irakaslea aurkitu'; // ORPHANED
$string['cannotgradeuser'] = 'Ezin da erabiltzaile honen kalifikaziorik aurkitu'; // ORPHANED
$string['cannotimportgrade'] = 'Errorea kalifikazioak inportatzean'; // ORPHANED
$string['cannotopencsv'] = 'Ezin da CSV fitxategia zabaldu'; // ORPHANED
$string['cannotopenforwrit'] = 'Ezin da zabaldu idazteko: $a'; // ORPHANED
$string['cannotreadfile'] = 'Ezin da fitxategia irakurri'; // ORPHANED
$string['cannotsavefile'] = 'Ezin da \"$a\" fitxategia gorde.'; // ORPHANED
$string['cannotupdategroup'] = 'Errorea taldea eguneratzean'; // ORPHANED
$string['cannotupdatemod'] = 'Eziin da $a eguneratu'; // ORPHANED
$string['cannotusepage'] = 'Irakasleek edo kudeatzaileek baino ezin dute orri hau erabili'; // ORPHANED
$string['invalidcategory'] = 'Kategoriaren IDa ez da zuzena'; // ORPHANED
$string['invalidelementid'] = 'Elemntuaren IDa ez da zuzena!'; // ORPHANED
$string['invalidmodule'] = 'Modulu baligabea'; // ORPHANED
$string['invalidmoduleid'] = 'Moduluaren ID baliogabea: $a'; // ORPHANED
$string['invalidmodulename'] = 'Moduluaren izen baliogabea: $a'; // ORPHANED
$string['invalidoutcome'] = 'Helburuaren ID baliogabea'; // ORPHANED
$string['invaliduser'] = 'Erabiltzaile baliogabea'; // ORPHANED
$string['invaliduserid'] = 'Erabiltzailearen ID baliogabea'; // ORPHANED
$string['missingparameter'] = 'Parametroa falta da'; // ORPHANED
$string['noadmins'] = 'Ez dago kudeatzailerik!'; // ORPHANED
$string['noguest'] = 'Hemen bisitaririk ez!'; // ORPHANED
$string['nopermissiontohide'] = 'Ez duzu ezkutatzeko baimenik!'; // ORPHANED
$string['nopermissiontolock'] = 'Ez duzu blokeatzeko baimenik!'; // ORPHANED
$string['nopermissiontoshow'] = 'Ez duzu erakusteko baimenik!'; // ORPHANED
$string['nopermissiontounlock'] = 'Ez duzu desblokeatzeko baimenik!'; // ORPHANED
$string['nopermissiontoupdateblock'] = 'Ez duzu $a eguneratzeko baimenik!'; // ORPHANED
$string['statsdisable'] = 'Estatistikak ez daude gaituta.'; // ORPHANED
$string['upgradefail'] = 'Eguneratzeak kale egin du!  $a'; // ORPHANED
$string['usernotincourse'] = 'Erabiltzaile hau ez dago ikastaro honetan!'; // ORPHANED

?>
