<?PHP // $Id$ 
      // feedback.php - created with Moodle 1.9.4+ (Build: 20090218) (2007101541)


$string['add_item'] = 'Gehitu galdera jarduerara';
$string['add_items'] = 'Gehitu galderak jarduerara';
$string['add_pagebreak'] = 'Gehitu orri-jauzia';
$string['analysis'] = 'Analisia';
$string['anonymous'] = 'Izengabea';
$string['anonymous_edit'] = 'Izengabea editatu';
$string['anonymous_entries'] = 'Izenik gabeko sarrerak';
$string['anonymous_user'] = 'Erabiltzaile ezezaguna';
$string['average'] = 'Bataz bestekoa';
$string['bold'] = 'Markatua';
$string['cancel_moving'] = 'Mugitzeari utzi';
$string['captcha'] = 'Captcha';
$string['check'] = 'Aukera anitzeko karratutxoa';
$string['check_values'] = 'Aukera edo balore posibleak';
$string['checkbox'] = 'Aukera anitzeko karratutxoa';
$string['choosefile'] = 'Aukeratu fitxategia';
$string['complete_the_form'] = 'Erantzun galderei...';
$string['completed'] = 'bukatua';
$string['completed_feedbacks'] = 'Bukatutako inkestak';
$string['confirmdeleteentry'] = 'Ziur al zaude sarrera hau ezabatu nahi duzula?';
$string['confirmdeleteitem'] = 'Ziur al zaude elementu hau ezabatu nahi duzula?';
$string['confirmdeletetemplate'] = 'Ziur al zaude txantiloi hau ezabatu nahi duzula?';
$string['confirmusetemplate'] = 'Ziur al zaude txantiloi hau erabili nahi duzula?';
$string['courseid'] = 'Ikastaroaren IDa';
$string['creating_templates'] = 'txantiloiak sortzen...';
$string['delete_entry'] = 'Sarrera ezabatu';
$string['delete_item'] = 'Ezabatu galdera';
$string['delete_old_items'] = 'Ezabatu elementu zaharrak';
$string['delete_template'] = 'Ezabatu txantiloia';
$string['delete_templates'] = 'Ezabatu txantiloiak...';
$string['description'] = 'Deskribapena';
$string['drop_feedback'] = 'Ezabatu ikastaro honetatik';
$string['dropdown'] = 'Zerrenda zabalgarria';
$string['dropdown_values'] = 'Aukera edo balore posibleak';
$string['dropdownlist'] = 'Zerrenda';
$string['dropdownrated'] = 'Zerrenda zabalgarria (neurtua)';
$string['edit_item'] = 'Editatu galdera';
$string['edit_items'] = 'Editatu galderak';
$string['email_notification'] = 'Bidali e-posta bidezko jakinarazpenak';
$string['emailteachermail'] = '$a->username (k) inkesta hau bete eta bidali du: \'$a->feedback\'

Hemen ikus dezakezu:

$a->url';
$string['emailteachermailhtml'] = '$a->username (k) inkesta hau bete eta bidali du: <i>\'$a->feedback\'</i><br /><br />
<a href=\"$a->url\">Hemen</a> ikus dezakezu.';
$string['entries_saved'] = 'Gordetako sarrerak';
$string['export_questions'] = 'Esportatu galderak';
$string['export_to_excel'] = 'Esportatu Excelera';
$string['feedback:viewreports'] = 'Ikusi txostenak';
$string['file'] = 'Fitxategia';
$string['filter_by_course'] = 'Ikastaroen araberako bilaketa';
$string['handling_error'] = 'Errorea sortu da eta feedback modulua ezin du ekintza kudeatu';
$string['horizontal'] = 'horizontala';
$string['import_questions'] = 'Inportatu galderak';
$string['info'] = 'Informazioa';
$string['infotype'] = 'Informazioa - Mota';
$string['item_name'] = 'Galdera';
$string['items_are_required'] = 'Item hauei erantzuna ematea ezinbestekoa da';
$string['label'] = 'Etiketa';
$string['line_labels'] = 'Etiketak';
$string['line_values'] = 'Baloreak';
$string['max_args_exceeded'] = 'Gehienez 6 argumentu onar daiteke, argumentu gehiegi';
$string['modulename'] = 'Inkesta-feedbacka';
$string['modulenameplural'] = 'Inkesta-feedbackak';
$string['move_here'] = 'hona mugitu';
$string['move_item'] = 'Elementua mugitu';
$string['movedown_item'] = 'Beherantz joan';
$string['moveup_item'] = 'Gorantz joan';
$string['multiple_submit'] = 'Bidalketa anitza';
$string['name'] = 'Izena';
$string['name_required'] = 'Izena ezinbestekoa da';
$string['next_page'] = 'Hurrengo orria';
$string['no_handler'] = 'Ez dago ekintza kudeatzalerik';
$string['no_items_available_yet'] = 'Oraindik ez dago itemik';
$string['no_templates_available_yet'] = 'Oraindik ez dago txantiloirik';
$string['non_anonymous'] = 'Ez izengabea';
$string['not_completed_yet'] = 'Oraindik ez da bukatu';
$string['of'] = 'nongoa';
$string['page'] = 'Orria';
$string['pagebreak'] = 'Orri-jauzia';
$string['parameters_missing'] = 'Hemengo parametroak falta dira';
$string['picture'] = 'Irudia';
$string['picture_file_list'] = 'Irudien zerrenda';
$string['picture_values'] = 'Zerrendako irudi bat edo gehiago<br />aukeratu:';
$string['position'] = 'Kokapena';
$string['preview'] = 'Aurrebista';
$string['previous_page'] = 'Aurreko orria';
$string['public'] = 'Publikoa';
$string['question'] = 'Galdera';
$string['questions'] = 'Galderak';
$string['radio'] = 'Aukera bakarreko botoia';
$string['radio_values'] = 'Aukera bakarreko botoien baloreak';
$string['radiobutton'] = 'Aukera bakarreko botoia';
$string['radiobutton_rated'] = 'Aukera bakarreko botoia (neurtua)';
$string['radiorated'] = 'Aukera bakarreko botoia (neurtua)';
$string['ready_feedbacks'] = 'Prest dauden inkestak';
$string['required'] = 'Ezinbestekoa';
$string['responses'] = 'Erantzunak';
$string['save_as_new_template'] = 'Txantiloi berri moduan gorde';
$string['save_entries'] = 'Erantzunak gorde';
$string['save_item'] = 'Itema gorde';
$string['saving_failed'] = 'Ezin izan da gorde';
$string['search_course'] = 'Ikastaroa bilatu';
$string['selected_dump'] = '$SESSION saioko aldagai hauek jaitsi dira:';
$string['separator_decimal'] = ',';
$string['separator_thousand'] = '.';
$string['show_all'] = 'Guztiak erakutsi';
$string['show_entries'] = 'Sarrerak erakutsi';
$string['show_entry'] = 'Sarrera erakutsi';
$string['sort_by_course'] = 'Ikastaroen arabera sailkatuta';
$string['start'] = 'Hasiera';
$string['stop'] = 'Amaiera';
$string['switch_item_to_not_required'] = 'Ez ezinbestekora aldatu';
$string['switch_item_to_required'] = 'Ezinbestekora aldatu';
$string['template'] = 'Txantiloia';
$string['template_saved'] = 'Txantiloia gorde da';
$string['templates'] = 'Txantiloiak';
$string['textarea'] = 'Testu-eremua';
$string['textarea_height'] = 'Lerro kopurua';
$string['textarea_width'] = 'Eremuaren zabalera';
$string['textfield'] = 'Testu-lerroa';
$string['textfield_maxlength'] = 'Karaktere gehienezko kopurua';
$string['textfield_size'] = 'Testu-lerroaren zabalera';
$string['update_item'] = 'Itema eguneratu';
$string['use_one_line_for_each_value'] = '<br>(aukera bakoitza lerro batean jarri)';
$string['use_this_template'] = 'Txantiloi hau erabili';
$string['using_templates'] = 'Txantiloiak erabiltzen';
$string['vertical'] = 'bertikala';
$string['all_old_values_will_be_deleted'] = 'Gordetako balore guztiak ezabatu egingo dira'; // ORPHANED
$string['all_related_values_will_be_deleted'] = 'Loturiko balore guztiak ezabatu egingo dira'; // ORPHANED
$string['are_you_sure_to_delete_this_entry'] = 'Sarrera hau ezabatu nahi duzula ziur al zaude?'; // ORPHANED
$string['publish_stats_on_students'] = 'Ikasleentzako estatistika publikoak'; // ORPHANED
$string['are_you_shure_to_delete_this_item'] = 'Item hau ezabatu nahi duzula ziur al zaude?'; // ORPHANED
$string['are_you_shure_to_delete_this_template'] = 'Txantiloi hau ezabatu nahi duzula ziur al zaude?'; // ORPHANED
$string['are_you_shure_to_use_this_template'] = 'Txantiloi hau erabili nahi duzula ziur al zaude?'; // ORPHANED
$string['every_defines_self'] = 'Aukera pertsonala'; // ORPHANED
$string['go_back_to'] = 'Atzera joan'; // ORPHANED
$string['label_item'] = 'Etiketaren itema'; // ORPHANED
$string['please_do_fill_out_all_required_fields'] = 'Bete beharreko item guztiak osatu, mesedez'; // ORPHANED
$string['saving_failed_because_missing_items'] = 'Ezin izan da gorde item batzuk desagertu direlako'; // ORPHANED

?>
