<?PHP // $Id$ 
      // admin.php - created with Moodle 1.6 Beta 2 (2006040500)


$string['adminseesallevents'] = 'Nakikita ng mga Administrador ang lahat ng okasyon';
$string['adminseesownevents'] = 'Katulad lamang ng ibang user ang mga Administrador';
$string['allowrenames'] = 'Pahintulutan ang pagbabago ng pangalan';
$string['availablelangs'] = 'Magagamit na mga pakete ng wika';
$string['backgroundcolour'] = 'Tagusan na kulay';
$string['badwordsconfig'] = 'Ipasok ang listahan mo ng bastos na salita; paghiwalayin ng mga kuwit.';
$string['badwordsdefault'] = 'Kung blangko ang pasadyang listahan, ang default na listahan mula sa pakete ng wika ang gagamitin.';
$string['badwordslist'] = 'Pasadyang listahan ng bastos na salita';
$string['blockinstances'] = 'Mga pag-iral';
$string['blockmultiple'] = 'Marami';
$string['cachetext'] = 'Tagal ng text cache';
$string['calendarsettings'] = 'Kalendaryo';
$string['change'] = 'baguhin';
$string['changesitelang'] = 'Baguhin ang wika ng site';
$string['componentinstalled'] = 'Nakainstol na Piyesa';
$string['configallowcoursethemes'] = 'Kapag binuhay mo ito, pahihintulutan ang mga kurso na itakda ang sarili nilang tema.  Nananaig ang mga tema ng kurso sa iba pang piniling  tema (site,user, o tema ng sesyon)';
$string['configallowemailaddresses'] = 'Kung nais mong limitahan ang lahat ng bagong email na address sa ilang partikular na domain, ilista ang mga ito rito na pinaghihiwalay ng mga espasyo.  Lahat ng iba pang domain ay di tatangapin. hal.<strong>kolehiyonatin.edu.ph    .gov.ph</strong>';
$string['configallowobjectembed'] = 'Bilang default na hakbang panseguridad, ang mga normal na user ay hindi pinapahintulutan na mag-embed ng multimedia (tulad ng Flash) sa loob ng mga teksto sa pamamagitan ng mga tag na EMBED at OBJECT sa kanilang HTML (bagama\'t magagawa pa rin ito nang ligtas sa pamamagitan ng mediaplugin filter).  Kung gusto mong pahintulutan ang mga tag na ito, buhayin ang opsiyon na ito.';
$string['configallowunenroll'] = 'Kapag ginawa mo itong \'Oo\',pahihintulutan ang mga mag-aaral na alisin ang sarili nila sa pagkaka-enrol sa isang kurso anumang oras nila ibigin.  Kundi ay hindi sila pahihintulutan, at ang prosesong ito ay magagawa lamang ng mga gurò at administrador.';
$string['configallowuserblockhiding'] = 'Nais mo bang pahintulutan ang mga user na itago/ipakita ang mga panggilid na bloke sa buong site na ito?  Gumagamit ang katangiang ito ng javascript at mga cookie upang maalala ang katayuan ng bawat napipitpit na bloke, at ang tanging maaapektuhan nito ay ang tanaw ng user.';
$string['configallowusermailcharset'] = 'Kapag pinagana ito, ang bawat user sa site na ito ay puwedeng magtakda ng sarili nilang charset sa email.';
$string['configallowuserthemes'] = 'Kapag binuhay mo ito, ang mga user ay pahihintulutang magtakda ng sarili nilang tema Nananaig ang tema ng user sa tema ng site (pero hindi sa mga tema ng kurso)';
$string['configallusersaresitestudents'] = 'Para sa lahat ng aktibidad sa harapang pahina ng site, dapat bang ituring na mag-aaral ang LAHAT ng user?  Kapag sumagot ka ng \"Oo\", ang may alinmang kumpirmadong user account ay pahihintulutan na lumahok bilang mag-aaral sa mga aktibidad na iyon.  Kapag sumagot ka ng \"Hindi\", tanging ang mga user na kalahok na sa isa man lamang na kurso ang makakalahok sa mga aktibidad sa harapang pahina.  Tanging ang mga admin at mga gurong binigyan ng karapatan ang maaaring magturo sa mga aktibidad sa harapang pahinang iyon.';
$string['configautologinguests'] = 'Dapat bang ilog-in nang awtomatiko ang mga dumadalaw bilang bisita kapag pumasok sila sa kurso nang may pambisitang access?';
$string['configbloglevel'] = 'Nalilimitahan ng kaayusang ito ang antas kung saan   maaaring matingnan ang mga blog ng user sa site na ito.  Tandaan na itinatakda nito ang maksimum sa konteksto ng TUMITINGIN at hindi ng nagpapaskil o uri ng ipinaskil na blog.  Puwede ring ganap na patayin ang mga blog, kung hindi mo kailangan ito.';
$string['configcachetext'] = 'Para sa mas malaking site o site na gumagamit ng text filter, mapapabilis ng kaayusang ito ang pagtakbo ng mga bagay.  Ang mga kopya ng text ay pananatilihin sa anyo nilang prinoseso sa panahong itinakda dito.  Ang labis na pagpapaliit ng kaayusang ito ay magpapabagal ng mga bagay, nguni\'t ang pagpapalaki nito ng labis ay magpapatagal sa pananariwa ng mga teksto (kung may bagong link, halimbawa).';
$string['configclamactlikevirus'] = 'Tratuhin ang mga file na parang virus';
$string['configclamdonothing'] = 'Tratuhin ang mga file na OK';
$string['configclamfailureonupload'] = 'Kapag isinaayos mo ang clam na i-scan ang mga inaplowd na file, pero hindi ito wastong naisaayos o nabigong tumakbo dahil sa hindi malamang dahilan, paano ito magpapatuloy?  Kapag pinili mo ang \'Tratuhin ang mga file na parang virus\', ililipat ang mga ito sa lugar na pangkuwarantina, o buburahin.  Kapag pinili mo ang \'Tratuhin ang mga file na OK\', ililipat ang mga file sa patutunguhang direktoryo nang parang normal.  Alin man dito, ipaaalam pa rin sa admin na nabigo ang clam.  Kung pinili mo ang \'Tratuhin ang mga file na parang virus\' at dahil sa anumang dahilan ay nabigo ang clam na tumakbo (kadalasan ay dahil ditanggap ang ipinasok mong pathtoclam), LAHAT ng file na inaplowd ay ililipat sa ibinigay na lugar pangkuwarantina, o buburahin.  Pag-ingatan ang kaayusang ito.';
$string['configcountry'] = 'Kapag itinakda mo ang bansâ dito, ang bansang ito ang magiging default para sa mga bagong account ng user.  Upang mapilit ang mga user na pumilì ng bansâ, pabayaan lamang itong hindi nakatakda.';
$string['configdbsessions'] = 'Kapag binuhay ito, gagamitin ng kaayusang ito ang database sa pag-iimbak ng mga impormasyon hinggil sa kasalukuyang sesyon.  Kapakipakinabang ito sa malalaki/abalang site o mga site na binuo sa cluster ng mga server.  Para sa karaniwang site malamang na mas mabuting patayin na ito upang gamitin na lamang ang server disk.  Tandaan na ang pagbabago ng kaayusang ito ngayon ay maglalog-out sa lahat ng kasalukuyang user (kasama ka).';
$string['configdebug'] = 'Kung bubuhayin ninyo ito, tataas ang lebel ng error_reporting ng PHP kaya\'t mas maraming babala ang malalathala.  Kapakipakinabang lamang ito sa mga debeloper.';
$string['configdefaultallowedmodules'] = 'Para sa mga kurso na nasa loob ng kategoriya sa itaas, alin bang mga modyul ang nais mong pahintulutan bilang default <b>kapag nilikha na ang kurso</b>?';
$string['configdefaultrequestedcategory'] = 'Default na kategoriya na paglalagyan ng mga hiniling na kurso, kapag naaprubahan na ang mga ito.';
$string['configdeleteunconfirmed'] = 'Kung gumagamit ka ng email authentication, ito ang takdang panahon na tatanggapin ang tugon ng mga user.  Kapag lumagpas na ang taning na ito, ang mga hindi nakumpirmang account ay buburahin.';
$string['configdenyemailaddresses'] = 'Upang mahadlangan ang mga email adress mula sa ilang partikular na domain, ilista ang mga ito rito sa parehong paraan.  Lahat ng iba pang domain ay tatanggapin, hal. <strong>hotmail.com yahoo.co.uk</strong>';
$string['configdigestmailtime'] = 'Ang mga taong pinili na padalhan sila ng digest ng mga email ay padadalhan nang arawan.  Kinokontrol ng kaayusang ito kung anong oras sa isang araw ipadadala ang sulat (ang susunod na cron na tatakbo pagkatapos ng oras na ito ang magpapadala nito).';
$string['configdisplayloginfailures'] = 'Magpapakita ito ng impormasyon sa ilang piling user tungkol sa mga nakaraang bigong login.';
$string['configdocroot'] = 'Itinatakda ang landas patungo sa mga Dokyu ng Moodle.  Maaari mo itong baguhin kung nais mong magkaroon ng sarili mong pasadyang dokumentasyon na online. Magkagayunman, kapag ginawa mo iyan, tiyakin mo na ang mga landas sa iyong dokumentasyon ay sumusunod sa format ng http://docs.moodle.org.';
$string['configenablecourserequests'] = 'Pahihintulutan nito na humiling ang sinumang user na   likhain ang isang bagong kurso.';
$string['configenablerssfeeds'] = 'Nabubuhay sa swits na ito ang RSS feed sa buong site.  Upang makakita ng pagbabago, kailangan mong ring buhayin ang RSS feed sa indibidwal na modyul - pumunta sa mga kaayusan ng Modyul sa loob ng Kaayusang Pang-admin.';
$string['configenablerssfeedsdisabled'] = 'Hindi ito magagamit dahil ang RSS feed ay pinatay sa kabuuan ng Site.  Para mabuhay ang mga ito, tumungo sa kaayusan ng mga Baryabol sa loob ng Kaayusang Pang-admin.';
$string['configenablestats'] = 'Kapag pinilì mo ang \'oo\' rito, ipoproseso ng cronjob ng Moodle ang mga log at mangangalap ito ng ilang estadistika.  Depende sa laki ng trapik sa site mo, maaari itong magtagal.  Kapag binuhay mo ito, makakakita ka ng ilang interesanteng graph at estadistika hinggil sa bawat kurso mo, o hinggil sa kabuuang site.';
$string['configenrolmentplugins'] = 'Pumili po ng mga mga plug-in para sa pag-eenrol na nais mong gamitin.  Huwag ninyong kalilimutan na isaayos ang mga kaayusan nito nang wasto.  
<br /><br />Kailangan ninyong itakda kung aling mga plug-in ang buhay, at maitatakda ang 
<strong>isang</strong> plug-in bilang default na plug-in para sa <em>interaktib</em> na pag-eenrol.  Para mapatay ang interaktib na pag-eenrol, itakda ang \"makapag-eenrol sa kurso\" sa \"Hindi\" sa mga kinakailangang kurso.';
$string['configerrorlevel'] = 'Pumilì ng dami ng babala ng PHP ang nais mong maipakita.  Normal ang karaniwan na pinakamaiging piliin.';
$string['configextendedusernamechars'] = 'Buhayin ang kaayusang ito upang mapahintulutan ang mga mag-aaral na gumamit ng anumang titik sa kanilang username (tandaan na walâ itong epekto sa tunay nilang pangalan).  Ang default ay \"ditotoo\" na nagsasabing tanging alphanumeric na titik lamang ang puwedeng gamitin sa username';
$string['configfilterall'] = 'Ifilter ang lahat ng string, kabilang ang mga heading, pamagat, nabigasyon bar at gayon ng gayon.  Kapakipakinabang ito kapag ginagamit ang multilang na filter, kundi ay lilikha lamang ito ng dagdag na trabaho sa site mo nang walang gaanong benepisyo.';
$string['configfiltermatchoneperpage'] = 'Ang filter na awtomatikong lumilikha ng link ay makagagawa lamang ng isang link para sa unang pagkakataon na nakatagpo ng katugmang teksto sa isang kumpletong pahina. Ang iba pang pagkakatugma  ay babalewalain.';
$string['configfiltermatchonepertext'] = 'Ang filter na awtomatikong lumilikha ng link ay makagagawa lamang ng isang link sa unang pagkakataon na nakatagpo ng katugmang teksto sa bawat aytem ng teksto (hal. rekurso, bloke) sa pahina.  Ang iba pa ay babalewalain.  Ang kaayusang ito ay di papansinin kung ang kaayusang \"isa para sa bawat pahina\"ay <i>oo</i>.';
$string['configfilteruploadedfiles'] = 'Ang pagbuhay ng kaayusang ito ay magbubunga ng pagproseso ng Moodle sa lahat ng inaplowd na HTML at text file sa pamamagitan ng mga filter bago ito ipakita.';
$string['configforcelogin'] = 'Karaniwan ay mababasa ng mga tao ang harapang pahina ng site at ang listahan ng mga kurso (nguni\'t hindi ang mga kurso) nang hindi nagla-log-in sa site.  Kung gusto mong pilitin ang mga tao na mag-log-in muna bago sila makagawa ng ANUMANG bagay sa site, dapat mong buhayin ang kaayusang ito.';
$string['configforceloginforprofiles'] = 'Buhayin ang kaayusang ito upang mapilit ang mga tao na maglog-in ng may tunay (dibisita) na account bago sila pahintulutang makita ang pahina ng pagkakakilanlan sa mga user.  Sa default ay patay (\"ditotoo\") ito, nang mabasa ng mga nagbabalak maging mag-aaral kung sino ang mga gurò sa bawat kurso, kaya lamang ay makikita rin ito ng mga web search engine.';
$string['configframename'] = 'Kung ie-embed mo ang Moodle sa loob ng web frame, isulat ang pangalan ng frame dito.  Kung hindi ay dapat manatili ang laman nito na \'_top\'';
$string['configfullnamedisplay'] = 'Itinatakda nito kung paano ipapakita ang buong pangalan.  Sa karamihang site na iisa ang wikà ang pinakamasinop na kaayusan ay ang default na \"Pangalan + Apelyido\", nguni\'t maaari mong piliin na itagò ang apelyido, o ipaubaya na lamang sa kasalukuyang pakete ng wikà ang pagpapasiya (naiiba ang kaayusan sa ilang wikà).';
$string['configgdversion'] = 'Tukuyin kung anong bersiyon ng GD ang naka-instol.  Ang bersiyong ipinapakita ng default ay ang nahanap nang awtomatiko.  Huwag itong baguhin kung hindi ninyo naiintindihan.';
$string['confighiddenuserfields'] = 'Piliin kung aling kahon ng impormasyon tungkol sa user ang nais mong itago sa iba pang user, maliban sa guro ng kurso at mga admin.  Paiigtingin nito ang privacy ng mag-aaral.  Diinan ang CTRL na teklado para makapili ng marami.';
$string['confightmleditor'] = 'Mamilì kung pahihintulutan o hindi ang paggamit ng embedded HTML na text editor.  Kahit piliin mo na pahintulutan, lilitaw lamang ang editor na ito kung ang user ay gumagamit ng angkop na web browser.  Maaari ring pagpasiyahan ng user na huwag nang gamitin ito.';
$string['configidnumber'] = 'Itinatakda ng opsiyon na ito kung (a) Hindi hihingan ng numerong-ID ang mga user, (o) Hihingan ng bilang na ID ang mga user pero maaari nila itong pabayaang blangko, o (u) Hihingan ng numerong-ID ang mga user at hindi nila puwedeng iwan itong blangko.  Kapag ibinigay, ang numerong-ID ng User ay ipapakita sa kanilang Pagkakakilanlan.';
$string['configintro'] = 'Sa pahinang ito, maitatakda mo ang ilang kaayusang baryabol na tutulong sa Moodle na tumakbo nang maayos sa server mo.  Huwag mong masyadong alalahanin ito - karaniwan ay gagana naman nang maayos ang mga default na kaayusan at maaari ka namang bumalik sa pahinang ito mamaya at baguhin ang mga setting.';
$string['configintroadmin'] = 'Sa pahinang ito, dapat mong iayos ang pangunahing administrador na account na magkakaroon ng kumpletong kontrol sa site.  Tiyakin na mabigyan mo ito ng ligtas na username,password at tanggap na email address.  Maaari kang lumikha ng marami pang admin account mamaya.';
$string['configintrosite'] = 'Maiaayos mo sa pahinang ito ang harapang pahina at pangalan ng bagong site na ito.  Maaari mong balikan ito mamaya upang mabago ang mga kaayusan sa pamamagitan ng \'Mga Kaayusan ng Site\' na link sa pambungad na pahina.';
$string['configintrotimezones'] = 'Ang pahinang ito ay maghahanap ng bagong impormasyon hinggil sa mga timezone ng daigdig (kabilang ang mga alituntunin ng daylight savings time) at babaguhin ang inyong lokal na database sa pamamagitan ng impormasyong ito.  Ang mga lokasyong ito ay itsetsek, nang sunod-sunod: $a Ang prosesong ito ay napakaligtas sa pangkalahatan at hindi makasisira sa mga normal na instalasyon.  Nais mo bang baguhin ang timezone mo ngayon?';
$string['configlang'] = 'Pumilì ng default na wikà para sa buong site.  Maaaring mabago ng mga user ang setting na ito mamaya.';
$string['configlangcache'] = 'Icache ang menu ng wika.  Nakatitipid ng maraming memorya at lakas ng pagproseso ng kompyuter.  Kapag binuhay mo ito, tatagal ng ilang minuto bago magbago ang menu pagkatapos mong magdagdag o magbawas ng mga wika.';
$string['configlangdir'] = 'Karamihan sa mga wikà ay nakasulat ng kaliwa-pakanan, pero ang iba, tulad ng Arabo at Hebreo, ay nakasulat ng kanan-pakaliwa.';
$string['configlanglist'] = 'Bayaan itong blanko upang mapahintulutan ang mga user na mamilì ng anumang wikà na mayroon ka sa instalasyong ito ng Moodle. Magkagayonman, maaari mong paigsiin ang menu ng wikà sa pamamagitan ng pagpasok ng pinaghihiwalay-ng-kuwit na listahan ng mga koda ng wikà na nais mo.  Halimbawa: tl,en,es_es,fr,it';
$string['configlangmenu'] = 'Pagpasiyahan kung nais mo o ayaw mong ipakita ang pangkalahatang menu ng wikà sa home page, pahinang panglog-in atbp.  Hindi naaapektuhan nito ang kakayanan ng user na ilagay ang nais niyang wikà sa sarili niyang pagkakakilanlan.';
$string['configlocale'] = 'Mamilì ng sitewide na locale - makakaapekto ito sa format at wikang ginagamit sa  mga petsa.  Kailangan ay naka-instol ang datos ng locale na ito sa operating system mo.  (hal tl_PH o en_PH).  Kung hindi mo alam kung alin ang pipiliin, pabayaan mo na lamang itong blangko.';
$string['configloginhttps'] = 'Kapag binuhay ito, gagamit ang Moodle ng ligtas na https na koneksiyon para sa pahinang-panglog-in lamang (nagbibigay ng ligtas na log-in), tapos ay babalik sa normal na http URL para bumilis.  BABALA: KINAKAILANGAN ng kaayusang ito na buhay ang https sa web server - kundi ay MAAARI HINDI KA MAKAPASOK SA SARILI MONG SITE.';
$string['configloglifetime'] = 'Itinatakda nito ang haba ng panahon na nais mong manatili ang mga log ng aktibidad ng user.  Ang mga log na mas matanda dito ay awtomatikong binubura.  Pinakamainam na panatilihin ang mga log nang mahaba-habang panahon, kung sakaling kailanganin mo ang mga ito, pero kung napakaraming ginagawa ng server mo at nakakaranas ka ng problema sa paggana nito, baka mas mainam na paigsiin ang buhay ng log.';
$string['configlongtimenosee'] = 'Kung matagal nang hindi nag-lalog-in ang mga mag-aaral, awtomatiko silang ma-aalis sa kurso.  Itinatakda ng parameter na ito ang limitasyon sa oras.';
$string['configmaxbytes'] = 'Itinatakda nito ang maksimum na laki ng inaplowd na file sa buong site.  Nililimitahan ang kaayusang ito ng PHP setting na post_max_size at upload_max_filesize, gayundin ng Apache setting na LimitRequestBody.  Nililimitahan naman ng maxbytes ang mga pagpipiliang laki sa antas kurso o antas modyul.';
$string['configmaxeditingtime'] = 'Itinatakda nito ang oras na mayroon ang mga tao para muling iedit ang mga pinaskil nila sa talakayan, mga puna sa talahulugan atbp.  Katamtaman nang oras ang mga 30 minuto.';
$string['configmessaging'] = 'Dapat bang buhayin ang pangmensaheng sistema sa pagitan ng mga user ng site?';
$string['configmymoodleredirect'] = 'Ipinipilit ng kaayusang ito ang pagbaling sa /my kapag naglog-in ang hindi-admin at pinapalitan ang breadcrumb sa tuktok na antas ng site ng /my';
$string['confignoreplyaddress'] = 'Minsan ang mga email ay ipinapadala para sa isang user (hal. ipinaskil sa talakayan).  Ang email address na itakda mo rito ay gagamitin sa \"Mula sa\" na address sa mga kaso na ang tatanggap ay hindi makakatugon ng direkta sa user (hal. kapag inibig ng user na panatilihing lihim ang address niya).';
$string['confignotifyloginfailures'] = 'Kapag may nairekord na bigong log-in, maaaring magpadala ng mga patalastas na email.  Sino ang dapat makakita ng mga patalastas na ito?';
$string['confignotifyloginthreshold'] = 'Kung aktibo ang pagpapatalastas ng bigong log-in, ilang bigong pagtatangkang maglog-in ng isang user o isang IP address ang dapat bigyan ng patalastas?';
$string['configopentogoogle'] = 'Kapag binuhay mo ang kaayusang ito, pahihintulutan ang Google na pumasok sa iyong site bilang Bisita.  At saka ang mg taong pumapasok sa iyong site sa pamamagitan ng paghahanap sa Google ay awtomatikong ilalog-in bilang Bisita.  Tandaan na nagbibigay lamang ito ng karapatang pumasok nang madali sa mga kursong nagpapahintulot na ng pagpasok ng bisita.';
$string['configpathtoclam'] = 'Path papunta sa clam AV.  Marahil ay tulad ng /usr/bin/clamscan o /usr/bin/clamdscan.  Kailangan mo ito para tumakbo ang clam AV.';
$string['configpathtodu'] = 'Landas papunta sa du.  Maaaring katulad ng /usr/bin/du.  Kapag ipinasok mo ito, ang mga pahina na nagdidispley ng laman ng direktoryo ay tatakbo ng mas mabilis para sa mga direktoryo na maraming lamang file.';
$string['configperfdebug'] = 'Kapag binuhay mo ito, ang impo hinggil sa pagsasakatuparan ay ilalathala sa talababa ng istandard na tema';
$string['configproxyhost'] = 'Kung ang <b>server</b> na ito ay kailangang gumamit ng proxy na kompyuter (hal. firewall) upang ma-access ang Internet, ilagay ang proxy hostname at port dito.  Kung hindi, pabayaan na lamang itong blangko.';
$string['configquarantinedir'] = 'Kung nais mong ilipat ng clam AV ang mga may impeksiyong file sa isang direktoryong pangkuwarantina, ipasok ito rito.  Kailangan ay masusulatan ito ng webserver.  Kapag pinabayaan mo itong blangko, o nagpasok ka ng direktoryong walâ naman o hindi puwedeng sulatan, ang mga may impeksiyong file ay buburahin.  Huwag lagyan ng slash sa dulo.';
$string['configrequestedstudentname'] = 'Salita para sa mag-aaral na ginamit sa mga hiniling na kurso';
$string['configrequestedstudentsname'] = 'Salita para sa mga mag-aaral na ginamit sa mga hiniling na kurso';
$string['configrequestedteachername'] = 'Salita para sa guro na ginamit sa mga hiniling na kurso';
$string['configrequestedteachersname'] = 'Salita para sa mga guro na ginamit sa mga hiniling na kurso';
$string['configrestrictbydefault'] = 'Dapat bang limitahan ang mga modyul bilang default ng mga bagong kurso na nilikha, na napapaloob sa kategoriya sa itaas.';
$string['configrestrictmodulesfor'] = 'Aling kurso ang dapat may <b>kaayusan</b> para sa pagpatay ng ilang modyul ng aktibidad?';
$string['configrunclamonupload'] = 'Patatakbuhin ba ang clam AV sa tuwing may mag-aplowd ng file?   Kailangan mo ng wastong path tungo sa pathtoclam upang gumana ito.  (Ang Clam AV ay isang libreng virus scanner na makukuha mo sa http://www.clamav.net/)';
$string['configsectioninterface'] = 'Interpeys';
$string['configsectionmail'] = 'Liham';
$string['configsectionmaintenance'] = 'Pagmementina';
$string['configsectionmisc'] = 'Atbp.';
$string['configsectionoperatingsystem'] = 'Sistemang pampatakbo';
$string['configsectionpermissions'] = 'Mga pahintulot';
$string['configsectionrequestedcourse'] = 'Mga kahilingan ng kurso';
$string['configsectionsecurity'] = 'Seguridad';
$string['configsectionstats'] = 'Estadistika';
$string['configsecureforms'] = 'Makakatulong sa Moodle ang paglalagay ng dagdag na antas ng seguridad kapag tumatanggap ito ng datos mula sa mga web form.  Kapag  binuhay ito, ang HTTP_REFERER na baryabol ng browser ay ikukumpara sa kasalukuyang form address.  Sa ilang kaso, maaaring magbunga ito ng problema kung gumagamit ang user ng firewall (hal. Zonealarm) na nakaconfigure na tanggalin ang HTTP_REFERER mula sa web traffic nila.  Ang ilang simtomas ng ganitong problema ay kapag \'hindi kayo makaalis\' sa isang form. Kung nagkakaproblema ang mga user mo sa pahinang panglog-in nila (halimbawa) maaaring mas iibigin mong patayin ang setting na ito, bagama\'t maaaring mailagay sa panganib ng brute-force password na atake ang iyong site.  Kung nag-aalangan ka, bayaan mo na lamang itong nakaset sa \'Oo\'.';
$string['configsessioncookie'] = 'Ginagawang pasadya ng kaayusang ito ang pangalan ng cookie na ginagamit ng mga sesyon ng Moodle.  Opsiyonal ito, at ginagamit lamang upang maiwasan ang kalituhan sa cookie kapag higit sa isang kopya ng Moodle ang tumatakbo sa iisang web site.';
$string['configsessioncookiepath'] = 'Kung kailangan mong baguhin ang pook na pinagdadalhan ng Moodle cookie ng mga browser, puwede mong baguhin ang kaayusang ito sa pamamagitan ng pagtakda sa isang subdirektoryo ng web site mo.  Kung hindi ay okey na ang default na \'/\' .';
$string['configsessiontimeout'] = 'Kung ang mga taong nakalog sa site na ito ay walang ginagawa sa mahabang panahon (hindi naglolowd ng pahina), sila ay awtomatikong malalog-out (tatapusin ang sesyon nila).  Itinatakda ng baryabol na ito kung gaano katagal bago sila sipain.';
$string['configshowblocksonmodpages'] = 'Sinusuportahan ng ilang modyul ng aktibidad ang paggamit ng bloke sa mga pahina nila.  Kapag binuhay mo ito, maaaring maglagay ng mga panggilid na bloke ang mga guro sa mga pahinang iyon, kundi ay hindi ipapakita ng interpeys ang katangiang ito.';
$string['configshowsiteparticipantslist'] = 'Lahat ng mag-aaral at gurò ng site na ito ay ililista sa listahan ng kalahok sa site.  Sino ang pahihintulutang makakita ng listahang ito ng kalahok sa site?';
$string['configsitemailcharset'] = 'Lahat ng email na lilikhain ng site mo ay ipadadala na may charset na itinakda rito.  Magkagayunman, maaari itong baguhin ng bawat indibidwal na user kung pagaganahin ang susunod na kaayusan. ';
$string['configsitepolicy'] = 'Kung may patakaran kang pang-site na dapat makita ng lahat ng user at sang-ayunan nila bago nila magamit ang site na ito, ilagay ang URL nito dito, kung hindi iwan na itong blangko.  Maaaring tumuro ang URL saanman - ang isang maalwang pook ay ang isang file sa lagayan ng file sa site.  hal. http://sitemo/file.php/1/patakaran.html';
$string['configslasharguments'] = 'Ang mga file (larawan, inaplowd atbp.) ay ipinapakita sa pamamagitan ng script na gumagamit ng \'slash na argumento\' (ang ikalawang opsiyon dito).  Ginagawa ng paraang ito na maging madali ang pag-cache ng mga file sa mga web browser, proxy server atbp.  Kaya lamang, may ilang PHP server na hindi pinapahintulutan ang paraang ito, kaya\'t kung nagkakaproblema kayo sa pagtingin sa mga naaplowd na mga file o larawan (hal mga larawan ng mga user), itakda ang baryabol na ito sa unang opsiyon';
$string['configsmtphosts'] = 'Ibigay ang buong pangalan ng isa o mahigit pang lokal na SMTP server na dapat gamitin ng Moodle upang makapagpadala ng liham (hal \'liham.a.com\' o \'liham.a.com;liham.b.com\').  Kung pabayaan mo itong blangko, gagamitin ng Moodle ang PHP default na paraan ng pagpapadala ng liham.';
$string['configsmtpuser'] = 'Kung nagtakda ka ng SMTP server sa itaas at kailangan ng server ng authentication, ilagay ang username at password dito.';
$string['configstatsfirstrun'] = 'Itinatakda nito kung hanggang kailan katagal na log ang ipoproseso <b>sa unang pagkakataon</b> na nais magproseso ng estadistika ng cronjob.  Kung marami kang trapik at nasa isang pinagsasaluhang hosting, malamang ay huwag nang masyadong lumang log ang isama, dahil maaaring magtagal nang labis at kumain ng maraming rekurso. (Tandaan na para sa kaayusang ito, 1 buwan = 28 araw.  Sa mga graph at ulat na nilikha 1 buwan = 1 buwan sa kalendaryo.)';
$string['configstatsmaxruntime'] = 'Ang pagpoproseso ng estadistika ay napakamatrabaho, kaya gamitin ang kombinasyon ng field na ito at ng susunod para maitakda kung kailan at gaano ito katagal tatakbo.';
$string['configstatsruntimestart'] = 'Kailan ba <b>magsisimula</b> ang cronjob na nagpoproseso ng estadistika?';
$string['configstatsuserthreshold'] = 'Kapag nagpasok ka ng di-sero, di-numero na halaga dito, ang mga kurso na mas mababa ang bilang ng nakaenrol (guro + mag-aaral) sa numerong ito ay babalewalain.';
$string['configteacherassignteachers'] = 'Dapat bang pahintulutan ang mga ordinaryong gurò na magtakda ng ibang gurò sa kursong pinagtuturuan nila? Kung \'Hindi\', tanging ang mga tagalikha ng kurso at admin ang maaaring magtakda ng gurò.';
$string['configthemelist'] = 'Pabayaan itong blangko upang mapahintulutan ang paggamit ng anumang tanggap na tema.  Kung nais mong paikliin ang menu ng tema, maaari kang magtakda dito ng listahan ng pangalan na pinaghiwalay ng kuwit (Huwag gagamit ng mga espasyo!).  Halimbawa:  standard,orangewhite';
$string['configtimezone'] = 'Maaari mong itakda ang default na timezone dito.  DEFAULT timezone lamang ito para sa padidispley ng mga petsa - maaari itong baguhin ng bawat user sa pamamagitan ng pagtakda ng sarili nila sa kanilang pagkakakilanlan. Ang \"Oras ng server\" dito ay gagawing default ng Moodle ang setting ng operating system ng server, nguni\'t ang \"Oras ng server\" sa pagkakakilanlan ng user ay gagawing default ng user ang kaayusan ng timezone na ito.';
$string['configunzip'] = 'Isulat ang lokasyon ng unzip program mo (pang-Unix lamang, opsiyonal). Kung itinakda, gagamitin ito sa paglalabas ng laman ng mga zip archive sa server. Kung pabayaan mo itong blangko, gagamitin ng Moodle ang mga internal na routine.';
$string['configvariables'] = 'Mga Baryabol';
$string['configwarning'] = 'Mag-ingat sa pagbabago ng mga kaayusang ito - ang dikilalang halaga ay maaaring magdulot ng problema.';
$string['configzip'] = 'Isulat ang lokasyon ng zip program mo (pang-Unix lamang, opsiyonal).  Kung itinakda, gagamitin ito sa paglikha ng zip archive sa server.  Kung pabayaan mo itong blangko, gagamitin ng Moodle ang mga internal na routine.';
$string['confirmation'] = 'Kumpirmasyon';
$string['confirminstall'] = 'Iiinstol mo ang pakete ng wika ($a), ito ba talaga ang gusto mo?';
$string['cronwarning'] = 'Ang <a href=\"cron.php\">pangmentinang iskrip na cron.php</a> ay hindi pa pinatatakbo sa loob ng 24 na oras. ';
$string['dbmigrate'] = 'Pagsasalin ng Moodle Database';
$string['dbmigrateconnecerror'] = 'Hindi makakonekta sa itinakdang database.';
$string['dbmigrateencodingerror'] = 'Ang itinakdang database ay may encoding na $a sa halip na UNICODE/UTF8.<br />Magtakda po ng iba.';
$string['dbmigratepostgres'] = 'Mukhang ang ginagamit mong database server ay 
PostgreSQL.  Para maipagpatuloy ang proseso ng pagsasalin, kailangang mong lumikha ng bagong database nang mano-mano, na may encoding na \"UNICODE\"(PostgreSQL 7) o \"UTF8\" (PostgreSQL 8), na siyang pag-iimbakan ng isinalin na datos. Pakipasok po ng bago ninyong kaayusang ng pagkonekta sa database sa ibaba upang makapagpatuloy na kayo:';
$string['dbmigratewarning'] = 'Tiyakin po na naibak-ap ninyo ang moodle database ninyo bago simulan ang prosesong ito.  Kung hindi mo alam kung paano iyon gawin, pakikontak ang admin mo ng sistema.  Ilalagay sa mode na pangmentina ang Moodle site mo kapag sinimulan mo na ang proseso.';
$string['dbmigratewarning2'] = '<b>Babala:  Magsisimula ka nang isalin ang database.  Tiyakin po na ang buo mong Moodle database ay nabak-ap.</b>';
$string['dbmigrationdeprecateddb'] = '<font color=\"#ff0000\">Ang database na ito ay isinalin na sa isang bagong UTF8 database at ito ay itinakwil na. Pakiedit po ang inyong config.php at gamitin ang bagong database para sa moodle na ito.</font>';
$string['dbmigrationdupfailed'] = 'Ang pagkopya ng database ay nabigo, posibleng dahil sa error na:<font color=\"#ff0000\"><pre>$a</pre></font>';
$string['density'] = 'Kasiksikan';
$string['download'] = 'Idownload';
$string['edithelpdocs'] = 'Iedit ang mga tulong na dokumento';
$string['editlang'] = '<b>Iedit</b>';
$string['editstrings'] = 'Iedit ang mga string';
$string['environment'] = 'Kapaligiran';
$string['environmenterrortodo'] = 'Kailangan mo munang lutasin ang lahat ng suliraning pangkapaligiran (mga error) bago mo maituloy ang pag-instol ng bersiyon ng Moodle na ito.';
$string['environmentrecommendinstall'] = 'ay iminumungkahing mainstol/mabuhay';
$string['environmentrecommendversion'] = 'ang bersiyon $a->needed ay iminumungkahi at ang pinatatakbo mo ay $a->current';
$string['environmentrequireinstall'] = 'ay kinakailangang mainstol/mabuhay';
$string['environmentrequireversion'] = 'ang bersiyon $a->needed ay kinakailangan at ang pinatatakbo mo ay $a->current';
$string['environmentxmlerror'] = 'Nagka-error sa pagbasa ng datos na pangkapaligiran ($a->error_code)';
$string['errors'] = 'Mga error';
$string['filterall'] = 'Ifilter ang lahat ng string';
$string['filtermatchoneperpage'] = 'Ifilter ang katugma nang isang beses sa bawat pahina';
$string['filtermatchonepertext'] = 'Ifilter ang katugma ng isang beses sa bawat teksto';
$string['filteruploadedfiles'] = 'Mga inaplowd na file ng filter';
$string['globalsquoteswarning'] = '<p><strong>Babalang Pangseguridad</strong>: para tumakbo nang maayos, hinihingi ng Moodle <br /> na may gawin kayong ilang pagbabago sa iyong kasalukuyang kaayusan ng PHP.<p/><p> <em>Kailangan</em> ninyong itakda ang <code>register_globals=off</code> at/o <code>magic_quotes_gpc=on</code>. <br />Kung puwede, 
dapat mong itakda ang <code>register_globals=off</code> upang mapaunlad ang pangkalahatang <br /> seguridad ng server , iminumungkahi rin ang pagtakda ng <code>magic_quotes_gpc=on</code>.<p/><p>Kinokontrol ang mga kaayusang ito sa pamamagitan ng pag-edit ng 
<code>php.ini</code> mo, kaayusan ng <br />Apache/IIS o file na <code>.htaccess</code>.</p>';
$string['helpadminseesall'] = 'Makikita ba ng mga admin ang lahat ng okasyon sa kalendaryo o iyon lamang para sa kanila?';
$string['helpcalendarsettings'] = 'Isaayos ang iba\'t-ibang aspekto ng Moodle na may kinalaman sa kalendaryo at petsa/oras';
$string['helpforcetimezone'] = 'Maaari mong pahintulutan ang mga user na piliin ang sarili nilang timezone, o ipilit ang isang timezone para sa lahat.';
$string['helpsitemaintenance'] = 'Para sa paggawang bago at iba pang gawain';
$string['helpstartofweek'] = 'Aling araw ang magsisimula ng linggo sa kalendaryo?';
$string['helpupcominglookahead'] = 'Ilang araw sa hinaharap maghahanap ng magaganap na okasyon ang kalendaryo bilang default?';
$string['helpupcomingmaxevents'] = 'Ilang (maksimum) na magaganap na okasyon ang ipapakita sa user bilang default?';
$string['helpweekenddays'] = 'Aling araw ng linggo ang ituturing na \"katapusan ng isang linggo\" at ipapakita na may ibang kulay?';
$string['iconvrecommended'] = 'Mahigpit na iminumungkahi ang pag-instol ng opsiyonal na ICONV library upang mapahusay ang paggana ng site, lalupa\'t kung sinusuportahan ng site mo ang mga di-latin na wika.';
$string['importlangreminder'] = 'Nagsisimula na ang proseso ng pagsalin ng database.  Kakailanganin mong <b>maglog-in muli</b> upang umapekto ang pagbabago.  Pakiinstol ang mga unicode na pakete ng wika sa pinakamaagang panahon mula sa Admin->Wika->Kagamitan sa Pag-angkat ng Wika <b>pagkatapos</b> makumpleto ang proseso ng pagsasalin.';
$string['importtimezones'] = 'Gawing bago ang kumpletong listahan ng timezone';
$string['importtimezonescount'] = '$a->count talâ ang inangkat mula sa $a->source';
$string['importtimezonesfailed'] = 'Walang natagpuang source! (Masamang balita)';
$string['incompatibleblocks'] = 'Dimagkasundong bloke';
$string['install'] = 'Iinstol ang piniling pakete ng wika';
$string['installedlangs'] = 'Mga naka-instol na pakete ng wika';
$string['invaliduserchangeme'] = 'Nakareserba ang \"changeme\" na username -- hindi ka maaaring lumikha ng account sa pamamagitan nito.';
$string['lang16notify'] = 'Pinapahintulutan ng Moodle 1.6 o mas bago ang pag-iinstol at paggawang bago ng mga pakete ng wika nang direkta mula sa download.moodle.org sa pamamagitan ng pagsunod sa link sa ibaba';
$string['langimport'] = 'Kagamitan sa pag-angkat ng wika';
$string['langimportsuccess'] = 'Matagumpay na nagawang bago ang pakete ng wika';
$string['langpackremoved'] = 'Natanggal na ang pakete ng wika';
$string['langpackupdated'] = 'Matagumpay na naiinstol ang pakete ng wika na $a';
$string['langupdatecomplete'] = 'Kumpleto na ang paggawang bago sa pakete ng wika';
$string['latexpreamble'] = 'Preamble ng LaTex';
$string['latexsettings'] = 'Kaayusan ng renderer ng LaTex';
$string['maintfileopenerror'] = 'Nagka-error sa pagbubukas ng mga file na pangmentina!';
$string['maintinprogress'] = 'Ang pagmementina ay kasalukuyang isinasagawa...';
$string['managelang'] = 'Pamahaláan';
$string['mbstringrecommended'] = 'Ang pag-iinstol ng opsiyonal na MBSTRING library ay mahigpit na inirerekomenda upang mapahusay ang paggana ng site, lalupa\'t kung sinusuportahan ng site mo ang mga di-latin na wika.';
$string['mediapluginavi'] = 'Buhayin ang .avi filter';
$string['mediapluginflv'] = 'Buhayin ang .flv filter';
$string['mediapluginmov'] = 'Buhayin ang .mov filter';
$string['mediapluginmp3'] = 'Buhayin ang .mp3 filter';
$string['mediapluginmpg'] = 'Buhayin ang .mpg filter';
$string['mediapluginram'] = 'Buhayin ang .ram filter';
$string['mediapluginrm'] = 'Buhayin ang .rm filter';
$string['mediapluginrpm'] = 'Buhayin ang .rpm filter';
$string['mediapluginswf'] = 'Buhayin ang .swf filter';
$string['mediapluginwmv'] = 'Buhayin ang .wmv filter';
$string['mysql416bypassed'] = 'Magkagayuman, kung TANGING iso-8859-1 (latin) na wika ang ginagamit ng site mo, maaari mong ipagpatuloy ang kasalukuyan mong nakainstol na MySQL 4.1.12 (o mas bago).';
$string['mysql416required'] = 'Ang MySQL 4.1.16 ang minimum na bersiyong kinakailangan ng Moodle 1.6 upang matiyak na lahat ng datos ay makukumberte sa UTF-8, sa hinaharap.';
$string['nolangupdateneeded'] = 'Bago ang lahat ng pakete ng wika ninyo, hindi na kailangan ng pagbabago';
$string['optionalmaintenancemessage'] = 'Opsiyonal na pangmentinang mensahe';
$string['order1'] = 'Una';
$string['order2'] = 'Ikalawa';
$string['order3'] = 'Ikatlo';
$string['pathconvert'] = 'Path ng <i>convert</i> binary';
$string['pathdvips'] = 'Path ng <i>dvips</i> binary';
$string['pathlatex'] = 'Path ng <i>latex</i> binary';
$string['pathtopgdump'] = 'Path papunta sa pg_dump';
$string['pathtopgdumpdesc'] = 'Kailangan lamang itong ipasok kung higit sa isa ang pg_dump sa sistema mo (halimbawa ay kung higit sa isa ang nakainstol mong bersiyon ng postgresql)';
$string['pathtopgdumpinvalid'] = 'Ditanggap na path papunta sa pg_dump - mali ang path o hindi ito executable';
$string['pathtopsql'] = 'Path papunta sa psql';
$string['pathtopsqldesc'] = 'Kailangan lamang itong ipasok kung higit sa isa ang psql sa sistema mo (halimbawa ay kung higit sa isa ang nakainstol mong bersiyon ng postgresql)';
$string['pathtopsqlinvalid'] = 'Ditanggap na path papunta sa psql - mali ang path o hindi ito executable';
$string['pgcluster'] = 'Cluster na PostgreSQL';
$string['pgclusterdescription'] = 'Parameter ng PostgreSQL version/cluster
para sa command line operation.
Kung iisa lamang ang postgresql
sa sistema mo o hindi mo tiyak 
kung ano ito, iwan na lamang itong blangko.';
$string['pleaseregister'] = 'Pakirehistro ang site mo para maalis ang buton na ito';
$string['releasenoteslink'] = 'Para sa impormasyon tungkol sa bersiyon ng Moodle na ito, pakitingnan po ang online na <a target=\"_new\" href=\"$a\">Mga Talâ ng Lathala</a>';
$string['remotelangnotavailable'] = 'Dahil hindi makakonekta sa download.moodle.org ay hindi kami makapag-instol ng pakete ng wika nang awtomatiko.  Pakidownload ang angkop na (mga) zip file sa listahan sa ibaba, kopyahin ang mga ito sa iyong $a na direktoryo at i-unzip ito nang mano-mano.';
$string['renameerrors'] = 'Nagka-error sa pagbabago ng pangalan';
$string['sitelangchanged'] = 'Matagumpay ang pagbabago ng kaayusang wika ng site';
$string['sitemaintenance'] = 'Kasalukuyang minementina ang site na ito at hindi muna magagamit';
$string['sitemaintenancemode'] = 'Mode na pangmentina';
$string['sitemaintenanceoff'] = 'Pinatay ang mode na pangmentina at tumatakbo na nang normal ang site';
$string['sitemaintenanceon'] = 'Ang site mo ay kasalukuyang nasa mode na pangmentina (tanging ang mga admin ang makakapaglog-in o makagagamit ng site).';
$string['sitemaintenancewarning'] = 'Ang site mo ay kasalukuyang nasa mode na pangmentina (tanging mga admin ang makakapaglog-in).  Upang maibalik ang site na ito sa normal na operasyon, <a href=\"maintenance.php\">patayin ang mode na pangmentina
</a>.';
$string['stickyblocks'] = 'Idinidikit na bloke';
$string['stickyblockscourseview'] = 'Pangkursong pahina';
$string['stickyblocksduplicatenotice'] = 'Kapag nagdagdag ka rito ng bloke na nasa isang partikular na pahina na, magreresulta ito sa isang kadoble. <br /> Tanging ang idinikit na bloke ang hindi maieedit, ang kadoble ay maeedit pa rin.';
$string['stickyblocksmymoodle'] = 'Aking moodle';
$string['stickyblockspagetype'] = 'Uri ng pahina na isasaayos';
$string['tabselectedtofront'] = 'Sa mga teybol na may tab, dapat bang ilagay sa unahan ang hilig na may kasalukuyang piniling tag';
$string['therewereerrors'] = 'May mga error sa datos mo';
$string['timezoneforced'] = 'Ipinilit ito ng administrador ng site';
$string['timezoneisforcedto'] = 'Pilitin ang lahat ng user na gamitin';
$string['timezonenotforced'] = 'Maaaring pumilì ng sarili nilang timezone ang mga user';
$string['unicodeupgradenotice'] = 'Isinalin namin ang lahat ng wika sa Unicode sa Moodle 1.6.  Upang makumpleto ang paggawang bago sa site na ito, kailangan mong ikumberte ang mga datos mo sa database mo, sa Unicode, sa pamamagitan ng aming pangsalin na iskrip.  <a href=\"utfdbmigrate.php\">Iklik ito upang mapatakbo na ang pangsalin na iskrip</a>!';
$string['uninstall'] = 'Tanggalin ang mga piniling pakete ng wika';
$string['uninstallconfirm'] = 'Lubos mong tatanggalin ang pakete ng wika na $a, talaga bang nais mo itong gawin?';
$string['updateaccounts'] = 'Gawing bago ang mga kasalukuyang account';
$string['updatecomponent'] = 'Gawing bago ang mga Piyesa';
$string['updatelangs'] = 'Gawing bago ang lahat ng lokal na pakete ng wika';
$string['upgradeforumread'] = 'May bagong katangian na idinagdag sa Moodle 1.5.  Para ito masubaybayan ang mga nabasa-na/di-pa-nabasang ipinaskil. <br />Para magamit ang kagamitang ito kailangan mong <a href=\"$a\">gawing bago ang mga teybol mo</a>.';
$string['upgradeforumreadinfo'] = 'May bagong katangian na idinagdag sa Moodle 1.5.  Para ito masubaybayan ang mga nabasa-na/di-pa-nabasang ipinaskil.  Para magamit ang kagamitang ito kailangang mong gawing bago ang mga teybol mo .  Kailangan itong magkaroon ng lahat ng impormasyon sa pagsubaybay para sa mga kasalukuyang ipinaskil.  Depende sa laki ng site mo, maaari itong magtagal nang labis (oras) at maaaring maging mabigat para sa database, kaya\'t pinakamaiging gawin ito kapag walang gaanong gumagamit ng site.  Gayonpaman, tuluyang gagana ang site mo sa panahong ito ng pagbabago, at hindi maaapektuhan ang mga user.  Kapag sinimulan mo na ang prosesong ito, dapat mo itong patapusin (panatilihing bukas ang bintana ng browser mo).  Pero, kung ihininto mo ang proseso sa pamamagitan ng pagsara ng bintana:  huwag kang mag-alala, maaari kang magsimula mulî.<br /><br />Nais mo bang simulan na ang proseso ng pagbabago ngayon?';
$string['upgradelogs'] = 'Para ganap na gumana, ang luma mong log ay kailangang gawing bago.   <a href=\"$a\">Marami pang impormasyon</a>';
$string['upgradelogsinfo'] = 'Kamakailan ay may mga pagbabagong ginawa sa kung paano iniimbak ang mga log.  Upang makita ang lahat ng luma mong log para sa bawat aktibidad, kailangang gawing bago ang mga luma mong log.  Depende sa site mo, maaaring magtagal ito (hal. ilang oras) at maaaring maging labis na mabigat para sa database sa malalaking site.  Kapag inumpisahan mo na ang prosesong ito, dapat mo itong patapusin (sa pamamagitan ng pagpapanatili na bukas ang bintana ng browser).  Huwag kang mag-alala, tatakbo ang site mo nang maayos para sa ibang tao habang binabago ang log.<br /><br />Nais mo bang gawing bago na ang mga log mo ngayon?';
$string['upgradesure'] = 'Nagbago ang mga file mo ng Moodle, at awtomatiko mong itataas ang server mo sa bagong bersiyon na ito:<br /><br />
<strong>$a</strong> <br /><br />
Kapag ginawa mo ito hindi ka na makababalik sa dati.<br /><br />
Talaga bang nais mong baguhin ang server mo sa bagong bersiyon na ito?';
$string['upgradingdata'] = 'Ginagawang bago ang datos';
$string['upgradinglogs'] = 'Ginagawang bago ang mga log';
$string['upwards'] = 'pataas';
$string['useraccountupdated'] = 'Nagawang bago ang user';
$string['userrenamed'] = 'Pinalitan ang pangalan ng user';
$string['userscreated'] = 'Nalikha na ang mga user';
$string['usersrenamed'] = 'Napalitan na ang mga pangalan ng user';
$string['usersupdated'] = 'Nagawang bago na ang mga user';

?>
