<?PHP // $Id$ 
      // admin.php - created with Moodle 1.6 Beta 1 (2006032900)


$string['adminseesallevents'] = 'Administrator/innen sehen alle Termine';
$string['adminseesownevents'] = 'Administrator/innen sehen nur Termine eigener Kurse';
$string['allowrenames'] = 'Umbenennen zulassen';
$string['availablelangs'] = 'Verfügbare Sprachpakete';
$string['backgroundcolour'] = 'Hintergrundfarbe';
$string['badwordsconfig'] = 'Geben Sie die Liste der Wörter ein, die zensiert werden sollen. Trennen Sie die Begriffe mit Kommata.';
$string['badwordsdefault'] = 'Wenn Ihre Liste leer ist, wird die Wortliste aus dem Sprachpaket verwendet.';
$string['badwordslist'] = 'Wortzensurliste';
$string['blockinstances'] = 'Instanzen';
$string['blockmultiple'] = 'Mehrfach';
$string['cachetext'] = 'Dauer der Gültigkeit für Cache';
$string['calendarsettings'] = 'Kalender';
$string['change'] = 'Ändern';
$string['changesitelang'] = 'Sprache für die Site ändern';
$string['componentinstalled'] = 'Komponente installiert';
$string['configallowcoursethemes'] = 'Mit der Aktivierung erlauben Sie die Auswahl kursspezifischer Themes. Kurs-Themes überschreiben die Einstellungen für die gesamte Installation und von Nutzer/innen.';
$string['configallowemailaddresses'] = 'Wenn Sie die Nutzung bestimmter E-Mail-Adressen verbindlich vorgeben wollen, können Sie diese auf bestimmte Domains begrenzen. Tragen Sie dazu die zulässigen Domains ein, z.B. <strong>unserefirma.de</strong>.';
$string['configallowobjectembed'] = 'Aus Sicherheitsgründen dürfen normale Benutzer/innen Multmedia-Objekte (wie Flash) nicht über die HTML-Tags EMBED und OBJECT in ihren HTML-Text einbinden. Mit dem moodle-Filter mediaplugins ist dies jedoch ohne Sicherheitsprobleme möglich. Aktivieren Sie diese Option, wenn Sie die beiden Tags dennoch erlauben wollen.';
$string['configallowunenroll'] = 'Wenn Sie \'Ja\' wählen, haben Teilnehmer/innen die Möglichkeit, sich jederzeit selbst aus ihren Kursen auszutragen; andernfalls liegt das allein in der Hand der Kursleiter/innen oder Administrator/innen.';
$string['configallowuserblockhiding'] = 'Wollen Sie zulassen, dass Nutzer/innen selbst Blöcke ein-/und ausblenden können. Das Feature verwendet Javaskript und Cookies, um den Status zu speichern. Die Einstellung bezieht sich nur auf die Ansicht der Nutzer/innnen.';
$string['configallowusermailcharset'] = 'Mit der Aktivierung erlauben Sie jeder/m Nutzer/in der Site den Zeichensatz für E-Mail selber festzulegen.';
$string['configallowuserthemes'] = 'Die Einstellung erlaubt Nutzer/innen, ein Theme auszuwählen. Damit wird das Theme der Installation überschrieben, nicht aber kursspezifische Theme-Einstellungen.';
$string['configallusersaresitestudents'] = 'Hier legen Sie den Zugriff zu den Lernaktivitäten auf der Startseite der moodle-Installation fest. Wenn Sie \'Ja\' eintragen, kann jede/r bestätigte Teilnehmer/in, die Lernaktivitäten auf der Startseite durchführen. Wenn Sie \'Nein\' eintragen, können nur Teilnehmer/innen, die derzeit in mindestens einem Kurs eingetragen sind, die Lernaktivitäten auf der Startseite ausführen. Nur die Administrator/innen und spezielle zugelassene Trainer/innen können die Aktivitäten auf der Startseite einrichten und bearbeiten.';
$string['configautologinguests'] = 'Sollen Gäste automatisch eingeloggt werden, wenn der Kurs den Zugang für Gäste erlaubt?';
$string['configcachetext'] = 'Diese Einstellung kann größere Sites (oder bei Verwendung von Textfiltern) erheblich beschleunigen. Textkopien werden in ihrer verarbeiteten Fassung für die festgelegte Zeit vorgehalten. Eine zu niedrige Einstellung kann sogar zu einer leichten Verlangsamung führen, bei einer zu hohen Einstellung kann die Aktualisierung der Texte (z.B. mit neuen Links) allerdings zu lange dauernn.';
$string['configclamactlikevirus'] = 'Behandle die Dateien wie virenhaltige Dateien';
$string['configclamdonothing'] = 'Behandle die Dateien als ok';
$string['configclamfailureonupload'] = 'Legen Sie fest was passieren soll, wenn Sie hochgeladene Dateien mit Clam-AV auf Viren überprüfen, dabei aber ein Fehler auftritt.
Wenn Sie auswählen \'Behandle Dateien wie virenhaltige Dateien\', werden Sie in das Quarantäne-Verzeichnis verschoben oder gelöscht. Wenn Sie wählen \'Behandle die Dateien als ok\' werden sie normal ohne Prüfung hochgeladen. In jedem Fall werden Admins benachrichtigt, dass ein Problem aufgetreten ist. Seien Sie mit dieser Einstellung sehr vorsichtig.';
$string['configcountry'] = 'Wenn Sie hier ein Land einstellen, wird dieses Land als Vorgabe für neue Zugänge gewählt.  Wenn die Nutzer/innen ein Land aktiv wählen sollen, lassen Sie das Feld einfach leer.';
$string['configdbsessions'] = 'Diese Einstellung verwendet die Datenbank unter anderem dazu Informationen über aktuelle Sitzungen abzuspeichern. Das ist sinnvoll bei sehr großen Anwendungen oder Anwendungen, die über mehrere Cluster von Servern verteilt arbeiten. Meist kann die Einstellung deaktiviert bleiben. Bei einer Änderung der Einstellung werden alle aktuellen Nutzer/innen ausgeloggt. Das gilt auch für Admins.';
$string['configdebug'] = 'Wenn Sie dies einschalten, werden die Fehlermeldungen von PHP erweitert, so dass mehr Warnungen ausgegeben werden. Dies ist nur nützlich für Entwickler.';
$string['configdefaultallowedmodules'] = 'Welche Module sollen in den Kursen der oben genannten Kategorie standardmässig bei der Einrichtung des Kurses aktiviert sein?';
$string['configdefaultrequestedcategory'] = 'Standardkategorie in der Kurse hinterlegt werden, die beantragt wurden.';
$string['configdeleteunconfirmed'] = 'Wenn Sie die Authentifikation per E-Mail verwenden, geben Sie hier den Zeitraum an, innerhalb dessen die Nutzer ihre Registrierung bestätigen müssen. Unbestätigte Zugänge verfallen danach und werden gelöscht.';
$string['configdenyemailaddresses'] = 'Definieren Sie hier Domains von denen keine E-Mail-Adressen akzeptiert werden. z.B. <strong>hotmail.com yahoo.de</strong>.';
$string['configdigestmailtime'] = 'Personen, die E-Mails als Digest (Zusammenfassung) eingerichtet haben, erhalten diese Zusammenfassung einmal täglich. Mit dieser Einstellung legen Sie fest zu welchem Zeitpunkt. Beim darauf folgenden Cron-Aufruf werden die Zusammenfassungen versandt.';
$string['configdisplayloginfailures'] = 'Anzeige von Informationen über frühere gescheiterte Logins der ausgewählten Nutzer.';
$string['configdocroot'] = 'Definiert den Pfad zur moodle-Dokumentation Moodle Docs. Sie können den Pfad ändern, um eine eigene Dokumentation online zu nutzen. Wenn Sie dies tun, sollten sie sicher stellen, dass Sie die gleiche Pfadstruktur nutzen, wie sie bei http://docs.moodle.org verwandt wird. ';
$string['configenablecourserequests'] = 'Erlaubt allen Nutzer/innen Anfragen zur Einrichtung von Kursen zu stellen.';
$string['configenablerssfeeds'] = 'Diese Einstellung aktiviert RSS-Feeds für die gesamte Site. Es ist zusätzlich erforderlich, RSS-Feeds in den einzelnen Modulen zu aktivieren. Öffnen Sie dazuin der Administration die Moduleinstellungen.';
$string['configenablerssfeedsdisabled'] = 'Diese Option ist nicht verfügbar, weil die RSS-Feeds für alle Seiten deaktiviert sind. Um diese zu aktivieren, öffnen Sie die Variableneinstellung in der Administration';
$string['configenablestats'] = 'Mit der Einstellung \"Ja\" verarbeitet der CronJob die Logs und erstellt Statistiken. Je nach Umfang der Aktivitäten auf der Seite kann dies einige Zeit in Anspruch nehmen. Wenn die Option deaktiviert ist (\"Nein\"), werden die Statistiken für jeden Kurs oder die Seite beim Aufruf der Seite erstellt.';
$string['configenrolmentplugins'] = 'Wählen Sie die Anmelde Plugins, die Sie verwenden wollen. Vergessen Sie nicht, die Einstellungen sorgfältig und richtig zu konfigurieren. <br/><br/>Legen Sie fest, welche Plugins verwandt werden sollen. <string>Ein</string> Plugin kann als <em>interaktives</em> Plugin vordefiniert werden. Um die interaktive Anmeldung abzuschalten wählen Sie in den ausgewählten Kursen \"Nein\" bei \"Kurseintragung ist möglich\".';
$string['configerrorlevel'] = 'Wählen Sie die Menge der PHP Warnungen, die angezeigt werden sollen. \'Normal\' ist meist eine gute Wahl.';
$string['configextendedusernamechars'] = 'Aktivieren Sie diese Einstellung, damit jedes Zeichen im Nutzernamen zulässig ist (Dies beeinflusst bereits vorhandene Namen nicht). In der Grundeinstellung sind nur alphanumerische Zeichen zulässig.';
$string['configfilterall'] = 'Filter über alle Begriffe, inkl. Überschriften, Titel, Navigationselemente, etc.) Dies kann im Zusammenhang mit dem Multilang-Filter nützlich sein. Es belastet den Server jedoch stark und kann zu einer Reduzierung der Arbeitsgeschwindigkeit führen.';
$string['configfiltermatchoneperpage'] = 'Der Filter für die automatische Verlinkung soll nur das erste Vorkommen eines Begriffes auf einer Seite verlinken. Wiederholt auf einer Seite auftretende Begriffe werden nur einmal verlinkt.';
$string['configfiltermatchonepertext'] = 'Der Filter für die automatische Verlinkung soll nur das erste Vorkommen eines Begriffes in jedem Abschnitt auf einer Seite (z.B. Block) verlinken. Wiederholt auf einer Seite auftretende Begriffe werden nur einmal verlinkt. Diese Einstellung wird ignoriert wenn die Einstellung \'configfiltermatchoneperpage\' aktiv ist.';
$string['configfilteruploadedfiles'] = 'Beim Aktivieren dieser Option werden alle hochgeladenen HTML- und Textdateien über den Filter bearbeitet bevor sie angezeigt werden.';
$string['configforcelogin'] = 'Normalerweise können die Startseite und die Kursübersicht (nicht jedoch die Kurse) eingesehen werden ohne sich einzuloggen. Aktivieren Sie diese Option, wenn ein Login zwingend sein soll, um IRGENDETWAS auf dieser Site ausführen zu können.';
$string['configforceloginforprofiles'] = 'Wenn Sie diese Einstellung aktivieren, müssen Teilnehmer/innen sich erst anmelden, um die Profile der Trainer/innen einsehen zu können. In der Grundeinstellung (\'Nein\') können die Teilnehmer/innen sich vor der Anmeldung zum Kurs über die Trainer/innen informieren. Zugleich können auch Suchmaschinen auf diese Profile zugreifen.';
$string['configframename'] = 'Sofern Sie Moodle innerhalb eines Frames einbinden, tragen Sie hier den Namen des Frames ein. Anderenfalls sollte dieser Wert auf \'_top\' stehen.';
$string['configfullnamedisplay'] = 'Hier können Sie festlegen, wie Namen in Ihrer Vollform angezeigt werden. In den meisten Fällen wird die Grundeinstellung \"Vorname + Nachname\" geeignet sein. Sie können jedoch auch die Nachnamen ausblenden, ganz nach Ihren Konventionen.';
$string['configgdversion'] = 'Zeigt Ihnen die installierte Version von GD (GD ist eine Funktion zur Anzeige von Bildern) an. Die angezeigte Version wurde automatisch ermittelt. Ändern Sie diese nicht, es sei denn Sie wissen wirklich, was Sie tun. ';
$string['confighiddenuserfields'] = 'Markieren Sie die Felder, deren Inhalte vor anderen Nutzer/innen, nicht aber Trainer/innen und Admins verborgen werden sollen. Dies schützt die Privatsphäre. Mit gedrückter CTRL-/Strg-Taste können Sie mehrere Felder markieren.';
$string['confightmleditor'] = 'Wählen Sie aus, ob Sie die Verwendung des Text-Editors prinzipiell zulassen möchten. Der Editor ist allerdings auf kompatible Browser angewiesen; sonst bleibt er unsichtbar. Die Nutzer können die Verwendung auch individuell ablehnen.';
$string['configidnumber'] = 'Diese Option legt fest, ob (a) Nutzer nicht nach einer ID Nummer gefragt werden, (b) Nutzer zwar nach einer ID Nummer gefragt werden, das Feld aber leer lassen können oder (c) Nutzer nach einer ID Nummer gefragt werden und dieses Feld nicht leer lassen können. Die ID Nummer des Nutzers wird in seinem Profil angezeigt.';
$string['configintro'] = 'Auf dieser Seite können Sie eine Anzahl von Konfigurations-Variablen spezifizieren, die Ihnen helfen, dass Moodle auf Ihrem Server zuverlässig arbeitet. Sorgen Sie sich nicht großartig - die Standard-Einstellungen funktionieren normalerweise sehr gut. Sie können jederzeit auf diese Seite zurückkommen und Einstellungen ändern.';
$string['configintroadmin'] = 'Hier sollten Sie den/die Hauptadminstrator/in einrichten, der/die die vollständige Kontrolle über die Site hat. Achten Sie darauf, hier einen sicheren Benutzernamen samt Passwort sowie eine gültige E-Mail-Adresse anzugeben. Weitere Administrator/innen können Sie später festlegen.';
$string['configintrosite'] = 'Diese Funktion erlaubt es Ihnen, die Startseite und den Namen der neuen Site einzurichten. Sie können später über die Startseite (Konfiguration > Seiteneinstellungen) hierher zurückkehren und die Einstellungen jederzeit bearbeiten.';
$string['configintrotimezones'] = 'Diese Funktion sucht nach neuen Einstellungen für Zeitzonen, inkl. neue Regelungen für die Sommerzeit, und aktualisiert die Datenbank. Dabei werden die Orte geprüft: $a. Der Vorgang ist normalerweise sehr sicher und beeinträchtigt Ihre Installation nicht. Wollen Sie die Zeitzonen nun aktualisieren?';
$string['configlang'] = 'Wählen Sie die Standard-Sprache für die gesamte Site. Die Benutzer können diese später überschreiben.';
$string['configlangcache'] = 'Speichern der Sprachmenüs. Spart eine Menge Speicher und Prozessleistung. Mit der Aktivierung dauert es ein paar Minuten zur Aktualisierung wenn Sprachen gelöscht oder hinzugefügt wurden.';
$string['configlangdir'] = 'In den meisten Sprachen wird von links nach rechts geschrieben, aber in einigen anderen, wie Arabisch oder Hebräisch, von rechts nach links.';
$string['configlanglist'] = 'Lassen Sie dieses Feld leer, um allen Nutzer/inne/n zu erlauben, eine der installierten Sprachen auszuwählen. Sie können das Sprachmenü verkürzen, indem Sie eine durch Kommas getrennte Liste der Spachcodes angeben. Zum Beispiel en, es_es, fr, it.';
$string['configlangmenu'] = 'Wählen Sie aus, ob Sie generell das Sprach-Auswahlmenü auf Ihrer Startseite angezeigt haben möchten, auf der Anmeldungsseite etc. Dies betrifft nicht die Möglichkeit des Nutzers, seine bevorzugte Sprache in seinem Profil einzustellen.';
$string['configlocale'] = 'Wählen Sie eine für die gesamte Site gültige Region (Zeitzone) - diese wird die Anzeige jedes Datums beeinflussen. Die Daten dieser Region müssen in Ihrem Betriebssystem installiert sein. Sofern Sie nicht wissen, was Sie auswählen sollen, lassen Sie dieses Feld leer.';
$string['configloginhttps'] = 'Wenn Sie diese Einstellung aktivieren wird eine sichere https-Verbindung für den Anmeldevorgang  genutzt. Danach wird eine normale http-Verbindung verwendet.
ACHTUNG: Die Einstellung erfordert eine gesonderte Aktivierung von https auf dem Server. Wenn diese NICHT besteht, können Sie sich selbst vom Zugriff zur Site ausschließen!!!';
$string['configloglifetime'] = 'Dies definiert die Zeitdauer, für die die Statistiken der Nutzer-Aktivitäten gespeichert werden. Ältere Statistiken werden automatisch gelöscht. Speichern Sie diese Daten nur so lange, wie sie unbedingt benötigt werden. Wenn Sie einen ausgelasteten Server haben und Geschwindigkeitseinbrüche feststellen, sollten Sie den Statistik-Zeitraum reduzieren.';
$string['configlongtimenosee'] = 'Wenn sich Teilnehmer/innen nach einer sehr langen Zeit nicht mehr angemeldet haben, werden Sie automatisch nach dieser Zeit aus dem Kurs ausgetragen.';
$string['configmaxbytes'] = 'Dieser Wert legt für die gesamte Site die maximale Größe für das Hochladen von Dateien fest. Der Eintrag wird begrenzt durch die PHP-Einstellung \'upload_max_filesize\' und die Apache-Einstellung \'LimitRequestBody\'. Diese Rahmeneinstellung begrenzt also auch die maximal wählbare Größe auf Kurs- oder Modulebene.';
$string['configmaxeditingtime'] = 'Hier bestimmen Sie die Zeitspanne, in der die Teilnehmer/innen die Foren-Beiträge, Glossar-Kommentare usw. erneut bearbeiten dürfen. Normalerweise sind 30 Minuten ein guter Wert. ';
$string['configmessaging'] = 'Soll das Messaging-System zwischen Nutzer/innen aktiviert werden?';
$string['configmymoodleredirect'] = 'Die Einstellung führt Nicht-Admins beim Login automatisch zur Seite /my und ersetzt die normale Breadcrumb-Navigation durch /my';
$string['confignoreplyaddress'] = 'Tragen Sie hier die E-Mail-Adresse ein, die als Absender beim Versand von Nachrichten (z.B. aus Foren) genutzt werden soll, wenn die E-Mail-Adresse des Trainers nicht für Rückantworten genutzt werden kann.';
$string['confignotifyloginfailures'] = 'E-Mail-Benachrichtigungen können versandt werden, wenn Login-Fehler aufgezeichnet wurden. Wer sollte die Nachrichten sehen?';
$string['confignotifyloginthreshold'] = 'Nach wie vielen gescheiterten Anmeldeversuchen soll eine Benachrichtigung erfolgen (nur wenn diese auch aufgezeichnet werden)?';
$string['configopentogoogle'] = 'Wenn Sie diese Option aktivieren, wird Google erlaubt, Ihre Seite als Gast zu besuchen. Außerdem werden Besucher, die über einen Link von Google kommen, automatisch als \'Gäste\' eingeloggt. Dies gilt natürlich nur für Kurse, die Gäste (ohne Schlüssel) zulassen.';
$string['configpathtoclam'] = 'Pfad für Clam-AV. Zumeist /usr/bin/clamscan oder user/bin/clamdscan. Die Einstellung ist erforderlich, damit Clam-AV gefunden wird.';
$string['configpathtodu'] = 'Pfad für du. Meist /usr/bin/du. Mit dieser Option werden Seiten mit Verzeichnissen und vielen Dateien schneller angezeigt.';
$string['configperfdebug'] = 'Nach der Aktivierung der Option wird eine Performanceinformation in der Fußzeile des Standardthemes angezeigt. ';
$string['configproxyhost'] = 'Wenn dieser <B>Server</B> einen Proxy braucht (beispielsweise eine Firewall), um Internetzugriff zu bekommen, dann tragen Sie hier den Namen und den Port des Proxys ein. Anderenfalls lassen sie das Feld leer.';
$string['configquarantinedir'] = 'Wenn Clam-AV infizierte Dateien in ein Quarantäne-Verzeichnis verschieben soll, definieren Sie das Verzeichnis hier. Wenn Sie den Eintrag leer lassen, das Verzeichnis ungültig ist oder nicht beschrieben werden kann, werden infizierte Dateien gelöscht. Tragen Sie keinen Slash am Ende ein.';
$string['configrequestedstudentname'] = 'Begriff für Teilnehmer/in in beantragten Kursen';
$string['configrequestedstudentsname'] = 'Begriff für Teilnehmer/innen in beantragten Kursen';
$string['configrequestedteachername'] = 'Begriff für Trainer/in in beantragten Kursen';
$string['configrequestedteachersname'] = 'Begriff für Trainer/in in beantragten Kursen';
$string['configrestrictbydefault'] = 'Soll bei neu angelegten Kursen dieser Kategorie die Nutzung der Module eingeschränkt werden ? (Grundeinstellung)';
$string['configrestrictmodulesfor'] = 'Welche Kurse sollen die <b>Einstellung</b> zum Deaktivieren von Lernaktivitäten haben?';
$string['configrunclamonupload'] = 'Clam-AV für hochgeladene Dateien nutzen? Sie müssen zusätzlich einen Pfad zu Clam-AV in pathtoclam eintragen. Clam-Av ist ein freier Virenscanner (http.//www.clamav.net).';
$string['configsectioninterface'] = 'Gestaltung';
$string['configsectionmail'] = 'E-Mail';
$string['configsectionmaintenance'] = 'Wartung';
$string['configsectionmisc'] = 'Verschiedenes';
$string['configsectionoperatingsystem'] = 'Arbeitsweise';
$string['configsectionpermissions'] = 'Rechte';
$string['configsectionrequestedcourse'] = 'Kursanträge';
$string['configsectionsecurity'] = 'Sicherheit';
$string['configsectionstats'] = 'Statistiken';
$string['configsectionuser'] = 'Nutzer/innen';
$string['configsecureforms'] = 'Moodle kann einen zusätzlichen Grad an Sicherheit verwenden, wenn es Daten von Web-Formularen erhält. Sofern dies eingeschaltet ist, dann wird die Variable HTTP_REFERER gegen
die Adresse des aktuellen Formulars geprüft.
In einigen wenigen Fällen kann das Probleme verursachen, wenn der Nutzer eine Firewall benutzt (z.B. Zonealarm), die so konfiguriert ist, das der HTTP_REFERER nicht mitgesendet wird.
Das Ergebnis ist, dass Sie bei einem Formular nicht weiterkommen.
Sofern Nutzer z.B. Probleme mit der Zugangsseite haben, sollten Sie diese Einstellung deaktivieren, so ist Ihre Seite allerdings offener für Brute-Force-Attacken. Im Zweifelsfall, belassen Sie es auf \'ja\'.';
$string['configsessioncookie'] = 'Diese Einstellung legt den Namen des Cookies, der für Moodle-Zugriffe benutzt wird fest. Dieser Eintrag ist optional und nur sinnvoll, um zu verhindern das mehrere Cookies sich überlagern. Dies kann der Fall sein, wenn mehrere Moodle-Systeme auf der gleichen Website installiert sind. ';
$string['configsessioncookiepath'] = 'Sollte es erforderlich sein, den Ablageort an dem Browser Cookies ablegen anzupassen, können Sie hier ein Unterverzeichnis Ihrer Website  definieren. Sonst ist die Grundeinstellung \'/\' ausreichend. ';
$string['configsessiontimeout'] = 'Wenn angemeldete Nutzer/innen länger keine Aktionen ausführen (Seiten laden), werden sie automatisch abgemeldet. Diese Variable legt die betreffende Zeitspanne fest.';
$string['configshowblocksonmodpages'] = 'Einige Lernaktivitäten erlauben die Nutzung von Blöcken innerhalb der Aktivität. Mit dieser Einstellung ermöglichen Sie den Trainer/innen auf der Kursseite diese Blöcke in die Lernaktivität einzufügen. Andernfalls steht diese Option nicht zur Verfügung.';
$string['configshowsiteparticipantslist'] = 'Alle auf dieser Site angelegten Teilnehmer/innen und Trainer/innen werden in der Teilnehmerliste aufgeführt. Wer soll die Teilnehmerliste einsehen dürfen?';
$string['configsitemailcharset'] = 'Alle E-Mails, die durch die Site erstellt werden, werden mit dem Zeichensatz versandt, den Sie hier eintragen. Wenn Sie die nächste Funktion aktivieren kann jede/r Nutzer/in diese Einstellung für sich selber definieren.';
$string['configsitepolicy'] = 'Wenn Sie eine Zustimmungserklärung verwenden, die alle Nutzer/innen bei der Nutzung akzeptieren müssen, können Sie hier die URL für diese Seite festlegen. Dies kann z.B. im Verzeichnis der Startseite sein. z.B. http://IhreDomain.de/file.php/1/zustimmung.html';
$string['configslasharguments'] = 'Dateien (Bilder, Dokumente usw.) können über ein Skript, das \'Slash-Argumente\' benutzt (zweite Option) einfacher in Internet-Browsern, Proxy-Servern usw. zwischengespeichert werden.
Leider erlauben nicht alle PHP-Server diese Methode, so dass Sie, sofern Sie Probleme bei der Anzeige von Dateien oder Bildern (beispielsweise den Benutzer-Fotos) haben, diese Variable auf die erste Option stellen müssen. ';
$string['configsmtphosts'] = 'Geben Sie hier den vollen Namen von einem oder mehreren lokalen SMTP-Servern an, die Moodle für den E-Mail-Versand benutzen soll (beispielsweise \'E-Mail.a.de\' oder \'E-Mail.a.de;E-Mail.b.de\'). Wenn Sie dieses frei lassen, wird Moodle die Standard-Methode von PHP zum Senden von E-Mails verwenden.';
$string['configsmtpuser'] = 'Sofern Sie einen SMTP-Server angegeben haben und der Server Zugangsdaten erfordert, dann geben Sie hier Benutzernamen und Passwort an.';
$string['configstatsfirstrun'] = 'Die Einstellung legt den Zeitraum fest, für den durch den Cronjob Statistiken ausgewertet werden sollen. Wenn Sie sehr viele Aktivitäten in Ihren Kursen haben oder sich einen Server mit anderen Anwendungen teilen, sollten Sie keinen zu langen Zeitraum wählen. Die Auswertung erfordert hohe Serverkapazitäten. (Hinweis: für die Einstellung gilt ! Monat = 28 Tage. In der grafischen Auswertung und den Berichten ist 1 Monat = 1 Kalendermonat.)';
$string['configstatsmaxruntime'] = 'Die Berechnung der Statistiken kann sehr viel Rechenleistung erfordern. Verwenden Sie eine Kombination aus diesem Feld und dem nächsten, um festzulegen zu welchem Zeitpunkt und für welchen Zeitraum die Berechnung erfolgen soll.';
$string['configstatsruntimestart'] = 'Zu welchem Zeitpunkt soll der CronJob die Berechnung der Statitiken durchführen?';
$string['configstatsuserthreshold'] = 'Kurse mit weniger Nutzer/innen als der Wert, den Sie hier eintragen, werden beim Erstellen des Kursrankings nicht berücksichtigt. Die Zahl der Nutzer/innen setzt sich aus Teilnehmer/innen und (!) Trainer/innen des Kurses zusammen.';
$string['configteacherassignteachers'] = 'Sollen Trainer/innen ihren Kursen selbst weitere Trainer/innen zuordnen können=? Falls \'Nein\', können nur Kursersteller/innen und Administrator/innen den Kursen Trainer/innen zuordnen.';
$string['configthemelist'] = 'Wenn das Feld leer bleibt kann jedes Theme ausgewählt werden. Wenn das Auswahlmenü für Themes verkürzt werden soll, können Sie hier die auswählbaren Themes eintragen, Trennen Sie die Namen der Themes mit Kommas; z.B.: standard,orangewhite. Verwenden Sie keine Leerzeichen!';
$string['configtimezone'] = 'Stellen Sie hier die bevorzugte Zeitzone ein. Sie steuert die Zeitanzeige in Ihren Kursen. Jeder Teilnehmer kann selbst in seinem Profil eine eigene Zeitzone einstellen und damit Ihre Voreinstellung für sich aufheben. Die Einstellung \"Serverzeit\"  verwendet hier die Zeiteinstellung Ihres Internetservers. Die Einstellung \"Serverzeit\" im Nutzerprofil hingegen greift auf die Einstellung Ihres Moodleprogramms an dieser Stelle zurück.';
$string['configunzip'] = 'Geben Sie hier den Pfad zum Programm unzip an (Nur Unix). Dieser wird für das Entpacken von ZIP-Archiven auf dem Server benötigt.';
$string['configvariables'] = 'Variablen konfigurieren';
$string['configwarning'] = 'Vorsicht bei der Veränderung dieser Einstellungen, ungeeignete Werte können zu Problemen führen.';
$string['configzip'] = 'Geben Sie hier den Pfad zum Programm zip an (nur Unix). Dieser wird für die Erstellung ZIP-Archiven auf dem Server benötigt.';
$string['confirmation'] = 'Bestätigung';
$string['confirminstall'] = 'Sie sind dabei das Sprachpaket ($a) zu installieren. Wollen Sie dies fortsetzen?';
$string['cronwarning'] = 'Das <a href=\"cron.php\">Cron-Skript</a> wurde in den letzten 24 Stunden nicht ausgeführt. <br />Die  <a href=\"../doc/?frame=install.html⊂=cron\">Installations Dokumentation</a> erläutert wie Sie diesen Vorgang automatisieren können.';
$string['dbmigrate'] = 'Moodle-Datenbankmigration';
$string['dbmigrateconnecerror'] = 'Zur ausgewählten Datenbank konnte keine Verbindung hergestellt werden.';
$string['dbmigrateencodingerror'] = 'Die ausgewählte Datenbank verwendet den $a Zeichensatz und nicht UNICODE/UTF-8<br/>Wählen Sie bitte eine andere.';
$string['dbmigratepostgres'] = 'Sie verwenden vermutlich eine PostreSQL-Datenbank auf dem Server. Um die Migration fortzusetzen müssen Sie zunächst manuell eine neue Datenbank mit dem \"UNICODE\" PostgreSQL 7) oder \"UTF-8\" (PostgreSQL 8) anlegen, um die migrierten Daten zu speichern. Tragen Sie die Verbindungsdaten für die neue Datenbank unten ein:';
$string['dbmigratewarning'] = 'Bevor Sie fortfahren müssen Sie die bisher genutzte moodle-Datenbank sichern. Wenn Sie nicht sicher sind, wie dies gemacht wird, fragen Sie den Admin des Systems. Ihre moodle-Site wird in den Wartungsmodus geschaltet wenn der Migrationsprozess startet.';
$string['dbmigratewarning2'] = '<b>Warnung:  Sie beginnen nun mit dem Migrationsprozess für die Datenbank. Sind Sie sicher, dass die bisher bestehende Datenbank gesichert wurde?</b>';
$string['dbmigrationdeprecateddb'] = '<font color=\"#ff0000\">Die Datenbank wurde in eine neue Datenbank mit dem Zeichencode UTF-8 umgewandelt. Nehmen Sie bitte die erforderlichen Änderungen für die neue Datenbank in der Datei config.php vor. Danach können Sie die neue Datenbank nutzen.';
$string['dbmigrationdupfailed'] = 'Bei der Übertragung der Datenbankinhalte ist ein Problem aufgetreten, möglicherweise hilft diese Information weiter: <font color=\"#ff0000\"><pre>$a</pre></font>';
$string['density'] = 'Dichte/Empfindlichkeit';
$string['download'] = 'Download';
$string['edithelpdocs'] = 'Hilfedateien bearbeiten';
$string['editlang'] = '<b>Bearbeiten</b>';
$string['editstrings'] = 'Menütexte bearbeiten';
$string['environment'] = 'Servereinstellungen';
$string['environmenterrortodo'] = 'Sie müssen zunächst alle Probleme mit Einstellungen des Servers beheben, bevor Sie mit der Installation von moodle fortfahren können.';
$string['environmentrecommendinstall'] = 'sollte installiert bzw. aktiviert werden';
$string['environmentrecommendversion'] = 'Version $a->needed wird empfohlen. Derzeit ist $a->current installiert.';
$string['environmentrequireinstall'] = 'muß installiert /aktiviert werden.';
$string['environmentrequireversion'] = 'Version $a->needed muß installiert werden. Derzeit ist $a->current installiert.';
$string['environmentxmlerror'] = 'Beim Auslesen der Einstellungen auf dem Server ist ein Fehler aufgetreten ($a->error_code)';
$string['errors'] = 'Fehler';
$string['filterall'] = 'Alle Begriffe filtern';
$string['filtermatchoneperpage'] = 'Filter einmal pro Seite anwenden';
$string['filtermatchonepertext'] = 'Filter einmal pro Text anwenden';
$string['filteruploadedfiles'] = 'Filter für hochgeladene Dateien';
$string['globalsquoteswarning'] = '<p><strong>Wichtiger Warnhinweis</strong>: damit Sie erfolgreich mit moodle arbeiten können <br />sind einige Änderungen an den derzeitigen PHP-Einstellungen erforderlich.<p/><p>Die Einstellung  <code>register_globals=off</code> und/oder <code>magic_quotes_gpc=on</code> <em>muß</em> gesetzt werden. <br />Wenn möglich sollten Sie  <code>register_globals=off</code> einstellen <br /> Sicherheitseinstellung für Server, die Einstellung <code>magic_quotes_gpc=on</code> ist ebenfalls ratsam.<p/><p>Die Einstellungen werden in der Datei <code>php.ini</code> vorgenommen, in der Apache/IIS <br />Konfiguration oder einer <code>.htaccess</code> Datei.</p>';
$string['helpadminseesall'] = 'Sollen Admins alle  Kalendereinträge sehen oder nur die, die sie betreffen?';
$string['helpcalendarsettings'] = 'Konfiguration verschiedener Kalender und datums- und zeitbezogener Einstellungen';
$string['helpforcetimezone'] = 'Sie können Nutzer/innen erlauben, eine eigene Zeitzone einzustellen oder die verwendete Zeitzone fest definieren.';
$string['helpsitemaintenance'] = 'Für Upgrades und andere Arbeiten am System';
$string['helpstartofweek'] = 'An welchem Tag soll die Woche im Kalender beginnen?';
$string['helpupcominglookahead'] = 'Wie viele Tage im voraus sollen künftige Termine gesucht werden?';
$string['helpupcomingmaxevents'] = 'Wie viele Termine sollen maximal als künftige Termine angezeigt werden?';
$string['helpweekenddays'] = 'Welche Tage der Woche sollen als Wochenende farbig hervorgehoben werden?';
$string['iconvrecommended'] = 'Die Installation der ICONV Bibliothek wird zur Leistungsverbesserung dringend empfohlen. Dies ist besonders wichtig wenn Sie Sprachen mit anderen als lateinischen Zeichensätzen verwenden.';
$string['importlangreminder'] = 'Der Migrationsprozess für die Datenbank beginnt nun.  Sie müssen sich <b>erneut einloggen</b>, damit das Upgrade ausgeführt wird. Installieren Sie alsbald die Unicode-Sprachdateien unter Administration -> Sprache -> Sprachdateien importieren <b>nachdem</b> dieMigration der Datenbank abgeschlossen ist.';
$string['importtimezones'] = 'Update der Zeitzonenliste';
$string['importtimezonescount'] = '$a->count Einträge importiert von $a->source';
$string['importtimezonesfailed'] = 'Keine Daten gefunden (schlechte Nachricht)';
$string['incompatibleblocks'] = 'Inkompatible Blöcke';
$string['install'] = 'Installieren';
$string['installedlangs'] = 'Installierte Sprachpakete';
$string['invaliduserchangeme'] = 'Der Anmeldename \"changeme\" ist reserviert. Wählen Sie einen anderen Anmeldenamen.';
$string['lang16notify'] = 'Moodle 1.6 und alle späteren Versionen erlauben die Installation und Aktualisierung der Sprachpakete direkt von download.moodle.org über diesen Link.';
$string['langimport'] = 'Importprozess für Sprachpakete';
$string['langimportsuccess'] = 'Das Sprachpaket wurde erfolgreich aktualisiert.';
$string['langpackremoved'] = 'Die Deinstallation des Sprachpakets wurde abgeschlossen.';
$string['langpackupdated'] = 'Das Sprachpaket $a wurde aktualisiert.';
$string['langupdatecomplete'] = 'Update des Sprachpakets fertig';
$string['latexpreamble'] = 'LaTeX  Anmerkung';
$string['latexsettings'] = 'LaTeX Rendereinstellungen';
$string['maintfileopenerror'] = 'Fehler beim Aktivieren des Wartungsmodus';
$string['maintinprogress'] = 'Die Wartung wird fortgesetzt. ';
$string['managelang'] = '<b>Verwalten</b>';
$string['mbstringrecommended'] = 'Die Installation der MBSTRING Bibliothek wird zur Leistungsverbesserung dringend empfohlen. Dies ist besonders wichtig wenn Sie Sprachen mit anderen als lateinischen Zeichensätzen verwenden.';
$string['mediapluginavi'] = '.avi Filter aktivieren';
$string['mediapluginflv'] = '.flv Filter aktivieren';
$string['mediapluginmov'] = '.mov Filter aktivieren';
$string['mediapluginmp3'] = '.mp3 Filter aktivieren';
$string['mediapluginmpg'] = '.mpg Filter aktivieren';
$string['mediapluginram'] = '.ram Filter aktivieren';
$string['mediapluginrm'] = '.rm Filter aktivieren';
$string['mediapluginrpm'] = '.rpm Filter aktivieren';
$string['mediapluginswf'] = '.swf  Filter aktivieren';
$string['mediapluginwmv'] = '.wmv Filter aktivieren';
$string['mysql416bypassed'] = 'Wenn Sie auf Ihrer Site NUR iso-8859-1 (lateinische) Sprachen verwenden, können Sied ie derzeitige MySQL-Version 4.1.12 (oder höher) verwenden.';
$string['mysql416required'] = 'MySQL 4.1.16 odereine höhere Version ist für moodle 1.6 unbedingt erforderlich, um sicher zu stellen, dass alle Daten künftig nach UTF-8 konvertiert werden können.';
$string['nolangupdateneeded'] = 'Alle Sprachpakete sind auf dem aktuellen Stand. Ein Update ist nicht erforderlich.';
$string['optionalmaintenancemessage'] = 'Optionale Wartungsinformation';
$string['order1'] = 'Erste';
$string['order2'] = 'Zweite';
$string['order3'] = 'Dritte';
$string['pathconvert'] = 'Pfad <i>convert</i> Binary';
$string['pathdvips'] = 'Pfad <i>dvips</i> Binary';
$string['pathlatex'] = 'Pfad <i>latex</i> Binary';
$string['pgcluster'] = 'PostgreSQL Cluster';
$string['pgclusterdescription'] = '<pre>PostgreSQL Versions-/Cluster-Parameter für Kommandozeilenoperationen. Wenn Sie nur eine PostgreSQL auf Ihrem System verwenden oder sich nicht sicher sind, lassen Sie das Feld leer.</pre>';
$string['pleaseregister'] = 'Registrieren Sie Ihre Site, um diesen Button zu entfernen';
$string['remotelangnotavailable'] = 'Moodle kann keine Verbindung zu download.moodle.org herstellen. Das Sprachpaket kann daher nicht automatisch aktualisiert werden. Laden Sie das/die  ausgewählte(n) Sprachpaket(e) herunter und kopieren Sie es in das Verzeichnis $a und entpacken Sie es manuell.';
$string['renameerrors'] = 'Fehler beim Umbenennen';
$string['sitelangchanged'] = 'Die Spracheinstellungen für die Site wurden erfolgreich geändert.';
$string['sitemaintenance'] = 'Die Site wird zur Zeit überarbeitet und steht vorübergehend nicht zur Verfügung. Bitte versuchen Sie es bald erneut.';
$string['sitemaintenancemode'] = 'Wartungsmodus';
$string['sitemaintenanceoff'] = 'Der Wartungsmodus wurde wieder abgeschaltet. Die Site steht wieder zur Verfügung.';
$string['sitemaintenanceon'] = 'Die Site befindet sich zur Zeit im Wartungsmodus. Nur Admins können die Site nutzen.';
$string['sitemaintenancewarning'] = 'Die Site befindet sich zur Zeit im Wartungsmodus. Nur Admins können sie nutzen und sich einloggen. Um in den Normalmodus zurückzukehren, klicken Sie auf <a href=\"maintenance.php\">Wartungsmodus abschalten</a>.';
$string['stickyblocks'] = 'Angehängte Blöcke';
$string['stickyblockscourseview'] = 'Kursseite';
$string['stickyblocksduplicatenotice'] = 'Wenn Sie einen Block hier hinzufügen, so steht eine Kopie auf jeder einzelnen Seite zur Verfügung.<br />Der angehängte Block ist nicht veränderbar. Veränderungen können Sie am Duplikat weiter vornehmen.';
$string['stickyblocksmymoodle'] = 'Mein moodle';
$string['stickyblockspagetype'] = 'Seitentyp zum konfigurieren';
$string['tabselectedtofront'] = 'Tabellen mit Tabulatoren: soll die Reihe mit dem aktiven Tabulator im Vordergrund platziert werden?';
$string['therewereerrors'] = 'Es gibt Fehler in Ihren Daten';
$string['timezoneforced'] = 'Dies wurde durch die Administration festgelegt.';
$string['timezoneisforcedto'] = 'Für alle Nutzer/innen festlegen.';
$string['timezonenotforced'] = 'Nutzer/innen können eine eigene Zeitzone auswählen.';
$string['unicodeupgradenotice'] = 'In moodle 1.6 wurden alle Sprachdateien nach UTF-8 migriert. Um das Upgrade Ihrer Site zu vervollständigen müssen alle Einträge in der Datenbank mit Hilfe des Migrationsscripts konvertiert werden. <a href=\"utfdbmigrate.php\">Klicken Sie hier, um  die Migration zu starten</a>!';
$string['uninstall'] = 'Deinstallieren';
$string['uninstallconfirm'] = 'Sie sind dabei das Sprachpaket ($a) zu deinstallieren. Wollen Sie dies fortsetzen?';
$string['updateaccounts'] = 'Update bestehender Accounts';
$string['updatecomponent'] = 'Update von Komponenten';
$string['updatelangs'] = 'Sprachpakete aktualisieren';
$string['upgradeforumread'] = 'In der Version 1.5 können Sie Forenbeiträge als gelesen/ungelesen markieren.<br />Für diese Funktion müssen die Datenbanktabellen aktualisiert werden. <a href=\"$a\">Tabellen jetzt aktualisieren</a>.';
$string['upgradeforumreadinfo'] = 'Mit einer neuen Funktion in moodle 1.5 können Forenbeiträge als gelesen/ungelesen markiert werden. Um diese Funktion zu verwenden, müssen die Datenbanktabellen aktualisiert werden. Je nach Größe der Datenbank kann dieser Vorgang längere Zeit (Stunden) erfordern. Führen Sie diesen Vorgang am besten in Zeiten mit wenigen Zugriffen aus. Die Site funktioniert während der Umstellung weiter. Die Nutzer/innen bemerken davon nichts. Wenn Sie den Vorgang einmal gestartet haben, darf er nicht unterbrochen werden. Lassen Sie das Browser-Fenster dabei offen. Sollten Sie das Browser-Fenster versehentlich schließen, können Sie den Prozess neu starten. <br />Wollen Sie nun starten?';
$string['upgradelogs'] = 'Für die vollständige Funktionsfähigkeit müssen die alten Log-Daten aktualisiert werden. <a href=\"$a\">More information</a>';
$string['upgradelogsinfo'] = 'Die Art und Weise in der Log-Daten gespeichert werden wurde verändert. Damit Sie Ihre alten Log-Daten mit den Einzelaktivitäten einsehen können, müssen die alten Log-Daten aktualisiert werden. Je nachdem wie viele Daten auf Ihrer Seite gespeichert sind, kann dieser Vorgang eine längere Zeit beanspruchen (u.U. mehrere Stunden). Der Vorgang beansprucht die Datenbank bei umfangreichen Seiten stark. Wenn Sie den Vorgang einmal gestartet haben, müssen Sie ihn ohne Unterbrechung abschließen lassen. Das Browser-Fenster darf nicht geschlossen und die Internetverbindung nicht unterbrochen werden in dieser Zeit. Der Zugriff auf Ihre Site durch andere Anwender ist dadurch nicht beeinträchtigt. <br /><br>Wollen Sie nun Ihre Log-Daten aktualisieren?';
$string['upgradesure'] = 'Moodledateien wurden verändert. Ihre Installation von Moodle wird auf die Version $a aktualisiert.
<p>Wenn Sie dies tun, können Sie nicht zu einer früheren Version zurückkehren.</p>
<p>Sind Sie sicher, dass Sie das Update ausführen wollen?</p>';
$string['upgradingdata'] = 'Daten aktualisieren';
$string['upgradinglogs'] = 'Log-Daten aktualisieren';
$string['upwards'] = 'aufwärts';
$string['useraccountupdated'] = 'Nutzer/in aktualisiert';
$string['userrenamed'] = 'Nutzer/in umbenannt';
$string['userscreated'] = 'Nutzer/innen angelegt';
$string['usersrenamed'] = 'Nutzer/innen umbenannt';
$string['usersupdated'] = 'Nutzer/innen aktualisiert';

?>
