<?PHP // $Id$ 
      // auth.php - created with Moodle 1.7 (2006101007)


$string['alternatelogin'] = 'Wenn Sie hier eine URL eingeben, wird diese als alternative Login-Seite  verwandt. Die Seite sollte ein Aktionsfeld (Button)auf <strong>\'$a\'</strong> enthalten und Eingabefelder für den <strong>Anmeldenamen</strong> und das <strong>Passwort</strong>.<br />Seien Sie sorgfältig bei der Eingabe der URL. Mit einer falschen URL schließen Sie sich selber vom Zugriff zur Seite aus.<br />Lassen Sie das Feld leer, um die Standardanmeldeseite zu verwenden.';
$string['alternateloginurl'] = 'Alternative Login-URL';
$string['auth_cas_baseuri'] = 'URI des Servers (kein Eintrag, falls es keine baseUri gibt)<br />z.B., wenn der CAS Server an host.domaine.fr/CAS/ dann<br />cas_baseuri = CAS/';
$string['auth_cas_create_user'] = 'Aktivieren Sie die Einstellung, um CAS authentifizierte Nutzer/innen in die Moodle-Datenbank einzufügen. Wenn nicht, können sich nur die Nutzer/innen einloggen, die in der Moodle-Datenbank eingetragen sind.';
$string['auth_cas_enabled'] = 'Aktivieren Sie die Funktion, um die CAS Authentifizierung zu verwenden';
$string['auth_cas_hostname'] = 'Hostname des CAS-Servers <br />z.B.: host.domain.fr';
$string['auth_cas_invalidcaslogin'] = 'Entschuldigung, Ihr Login ist gescheitert - Ihr Zugang konnte nicht bestätigt werden.';
$string['auth_cas_language'] = 'Ausgewählte Sprache';
$string['auth_cas_logincas'] = 'Sicherer Zugang';
$string['auth_cas_port'] = 'Port des CAS-Servers';
$string['auth_cas_server_settings'] = 'CAS-Server-Konfiguration';
$string['auth_cas_text'] = 'Sichere Verbindung';
$string['auth_cas_version'] = 'CAS-Version';
$string['auth_casdescription'] = 'Dieses Verfahren verwendet einen CAS Server (Central Authentification Service) zur Authentifizierung von Nutzer/innen in einer Single-Sign-On Umgebung (SSO). Sie können jedoch auch eine einfache LDAP Authentifizierung verwenden. Wenn der verwandte Anmeldename und das Passwort auf CAS als gültig erkannt werden, erstellt Moodle einen neuen Nutzereintrag in seiner Datenbank und weitere Nutzerdaten von LDAP, falls erforderlich. Bei späteren Logins werden nur Anmeldename und Passwort geprüft.';
$string['auth_castitle'] = 'CAS-Server (SSO)';
$string['auth_changepasswordhelp'] = 'Hilfe für Passwortänderung';
$string['auth_changepasswordhelp_expl'] = 'Nutzerhilfe für vergessene $a Passwörter anzeigen. Diese Hilfe wird neben oder statt der <strong>URL zur Passwortänderung</strong> oder der Moodle internen Passwortänderung angezeigt.';
$string['auth_changepasswordurl'] = 'URL zur Passwortänderung';
$string['auth_changepasswordurl_expl'] = 'Tragen Sie hier eine URL ein, unter der die Nutzer/innen ein neues Passwort anfordern können. Wenn Sie diese Option nutzen, sollten Sie die Standardeinstellung zur Passwortänderung auf \"Nein\" setzen.';
$string['auth_common_settings'] = 'Gemeinsame Einstellungen';
$string['auth_data_mapping'] = 'Data mapping';
$string['auth_dbdescription'] = 'Diese Methode benutzt eine externe Datenbank-Tabelle, um die Gültigkeit von angegebenem Anmeldenamen und Kennwort zu überprüfen, Wenn der Zugang neu ist, werden die Informationen der übrigen Felder ebenso zu Moodle hinüberkopiert.';
$string['auth_dbextrafields'] = 'Diese Felder sind optional. Sie können auswählen, einige Moodle-Nutzerfelder mit Informationen des <b>externen Datenbank-Feldes</b> vorauszufüllen, das Sie hier angeben.
<p>Wenn Sie dieses leer lassen, werden Standardwerte benutzt.</p><p>Im anderen Fall müssen die Nutzer/innen alle Felder nach der Anmeldung ausfüllen./p>';
$string['auth_dbfieldpass'] = 'Name des Feldes, das das Passwort enthält';
$string['auth_dbfielduser'] = 'Name des Feldes, das den Nutzernamen enthält';
$string['auth_dbhost'] = 'Der Computer, der die Datenbank bereitstellt';
$string['auth_dbname'] = 'Name der Datenbank';
$string['auth_dbpass'] = 'Passwort, das zum Nutzernamen gehört';
$string['auth_dbpasstype'] = 'Spezifizieren Sie das Format, das das Passwortfeld benutzt. MD5-Verschlüsselung ist nützlich dafür, mit anderen üblichen Netzanwendungen Verbindung aufzunehmen, wie z.B. PostNuke';
$string['auth_dbtable'] = 'Name der Datenbank-Tabelle';
$string['auth_dbtitle'] = 'Externe Datenbank';
$string['auth_dbtype'] = 'Der Datenbank-Typ (Siehe <a href=\"../lib/adodb/readme.htm#drivers\">ADOdb Anleitung</a> für Einzelheiten)';
$string['auth_dbuser'] = 'Nutzername mit Schreibzugriff auf die Datenbank';
$string['auth_emaildescription'] = 'E-Mail-Bestätigung ist die Standard-Authentifizierungsmethode. Wenn sich Nutzer/innen neu anmelden, ihren eigenen Anmeldenamen und ihr Passwort auswählen, dann wird zur Bestätigung eine E-Mail an die angegebene E-Mail-Adresse gesendet. Diese E-Mail enthält einen sicheren Verweis auf eine Seite, wo die Nutzer/innen ihren Zugang bestätigen müssen. Spätere Anmeldungen prüfen nur  Anmeldenamen und Kennwort anhand der in der Moodle-Datenbank gespeicherten Daten.';
$string['auth_emailtitle'] = 'E-Mail basiert';
$string['auth_fccreators'] = 'Liste der Kursverwalter/innen. Trennen Sie verschiedene Gruppen durch \';\'. Namen müssen genau so geschrieben werden, wie auf dem Referenz-Server. Achten Sie auch auf die korrekte Groß-/ Kleinschreibung.';
$string['auth_fcdescription'] = 'Dieses Verfahren überprüft auf einem anderen Server die Gültigkeit von Anmeldenamen und Passwort.';
$string['auth_fcfppport'] = 'Server-Port (3333 wird zumeist genutzt)';
$string['auth_fchost'] = 'Server-Adresse des Referenz-Servers. Tragen Sie die IP-Adresse oder den DNS Namen ein.';
$string['auth_fcpasswd'] = 'Passwort für den Zugang';
$string['auth_fctitle'] = 'Referenz-Server';
$string['auth_fcuserid'] = 'Nutzer-ID auf dem Referenz-Server mit der bevorzugten \'Subadmin\'-Einstellung';
$string['auth_fieldlock'] = 'Sperrwert';
$string['auth_fieldlock_expl'] = '<p><b>Sperrwert:</b> Wenn Sie die Funktion aktivieren, verhindert Moodle die Bearbeitung des Feldes durch Nutzer/innen und Administrator/innen. Dies ist sinnvoll, wenn die Daten in einer externen Datenbank gepflegt werden. </p>';
$string['auth_fieldlocks'] = 'Nutzerdatenfelder sperren';
$string['auth_fieldlocks_help'] = '<p>Sie können Datenfelder der Nutzer/innen sperren. Dies ist u.U. sinnvoll wenn die Nutzerdaten von Administrator/innen gepflegt werden, manuell angelegt oder im Bulkupload (Hochladen über Textdatei) hochgeladen werden. Wenn Sie Felder sperren, die von Moodle benötigt werden, müssen Sie sicher stellen, dass diese beim Anlegen der Nutzerzugänge brauchbar vorbelegt sind.</p><p>Achten Sie darauf, dass die Einstellung auf \"Bearbeitbar wenn Feld leer\" gesetzt ist, um Probleme zu vermeiden.</p>';
$string['auth_imapdescription'] = 'Diese Methode verwendet einen IMAP-Server, um zu prüfen, ob der angegebene Anmeldename und das Passwort gültig sind.';
$string['auth_imaphost'] = 'IMAP Server-Adresse. Benutzen Sie die IP, nicht den DNS-Namen';
$string['auth_imapport'] = 'IMAP Serverport-Nummer. Normalerweise ist das 143 oder 993.';
$string['auth_imaptitle'] = 'IMAP-Server';
$string['auth_imaptype'] = 'Der IMAP Servertyp. IMAP Server können verschiedene Arten der Authentifizierung und Überprüfung haben.';
$string['auth_ldap_bind_dn'] = 'Möchten Sie Bind-User für die Nutzersuche verwenden, so geben Sie dies hier an. Normalerweise etwas wie \'cn=ldapuser,ou=public,o=org\'';
$string['auth_ldap_bind_pw'] = 'Passwort für Bind-User.';
$string['auth_ldap_bind_settings'] = 'Bind-Einstellungen';
$string['auth_ldap_contexts'] = 'Liste der Umgebungen, in denen sich Nutzer/innen befinden. Trennen Sie verschiedene Umgebungen durch \';\'. Beispiel: \'ou=users,o=org; ou=others,o=org\'';
$string['auth_ldap_create_context'] = 'Wenn Sie die Nutzererstellung mit E-Mail-Bestätigung aktivieren, geben Sie die Umgebung an, wo die Nutzer/innen erstellt werden sollen. Diese Umgebung sollte sich von der andererer Nutzer/innen unterscheiden, um Sicherheitsrisiken zu vermeiden. Sie brauchen diese Umgebung nicht zur ldap_context Variable hinzuzufügen, Moodle sucht in dieser Umgebung automatisch nach Nutzer/innen.';
$string['auth_ldap_creators'] = 'Eine Liste von Gruppen, denen es erlaubt ist, neue Kurse zu erstellen. Trennen Sie mehrere Gruppen durch \';\'. Normalerweise etwas wie \'cn=teachers, ou=staff, o=myorg\'';
$string['auth_ldap_expiration_desc'] = 'Setzen Sie Nein (no) um die Überprüfung abgelaufener Passworte abzuschalten oder LDAP um sie direkt über LDAP abzuwickeln.';
$string['auth_ldap_expiration_warning_desc'] = 'Zahl der Tage vor dem Ablauf der Gültigkeit des Passwortes an denen eine Nachricht versandt wird.';
$string['auth_ldap_expireattr_desc'] = 'optional: Ändert die LDAP-Attribute zur Speicherung der Passwortgültigkeitsdauer passwordExpirationTime';
$string['auth_ldap_graceattr_desc'] = 'optional: Ändert die gracelogin Attribute';
$string['auth_ldap_gracelogins_desc'] = 'Aktiviert LDAP gracelogin Unterstützung. Wenn das Passwort abgelaufen ist, können die Nutzer/innen sich weiter einloggen bis gracelogin den Wert 0 hat. Nach dem Aktivieren der Einstellung wird eine gracelogin Mitteilung angezeigt, wenn das Passwort abgelaufen ist.';
$string['auth_ldap_host_url'] = 'Geben Sie einen LDAP Server in URL-Form an wie \'ldap://ldap.myorg.de/\' oder \'ldaps://ldap.myorg.de/\'';
$string['auth_ldap_login_settings'] = 'Login-Einstellungen';
$string['auth_ldap_memberattribute'] = 'Geben Sie die Mitgliedsoptionen an, wenn Nutzer/innen zu einer Gruppe gehören. Normalerweise \'member\'';
$string['auth_ldap_objectclass'] = 'Filter für die Suche nach Nutzernamen. Normalerweise tragen Sie ein objectClass=posixAccount . Defaults to objectClass=* what will return all objects from LDAP.';
$string['auth_ldap_opt_deref'] = 'Legt fest wie Aliasbezeichnungen bei der Suche behandelt werden. Wählen Sie einen der folgenden Werte: \"No\" (LDAP_DEREF_NEVER) or \"Yes\" (LDAP_DEREF_ALWAYS)';
$string['auth_ldap_passwdexpire_settings'] = 'LDAP Passwortablaufeinstellung';
$string['auth_ldap_preventpassindb'] = 'Wählen Sie ja, um Passwörter <b>nicht</b> in der Moodle-Datenbank zu speichern';
$string['auth_ldap_search_sub'] = 'Nutzer/innen in Unterumgebungen suchen';
$string['auth_ldap_server_settings'] = 'LDAP Server-Einstellungen';
$string['auth_ldap_update_userinfo'] = 'Nutzerdaten (Vorname, Name, Adresse...) von LDAP zu Moodle aktualisieren. Weitere Informationen in /auth/ldap/attr_mappings.php';
$string['auth_ldap_user_attribute'] = 'Verwendete Eigenschaften, um Nutzer zu benennen/suchen. Normalerweise \'cn\'.';
$string['auth_ldap_user_settings'] = 'Einstellung zur Nutzerüberprüfung (user lookup settings)';
$string['auth_ldap_user_type'] = 'Auswahl wie Nutzer in LDAP hinterlegt werden. Die Einstellungen legen fest wie der Login-Ablauf, grace Logins und Nutzererstellung ablaufen.';
$string['auth_ldap_version'] = 'Diese Version des LDAP Protokolls nutzt Ihr Server.';
$string['auth_ldapdescription'] = 'Diese Methode bietet Authentifizierung gegenüber einem externen LDAP-Server. Wenn der vergebene Nutzername und Passwort gültig sind, erstellt Moodle einen neuen Nutzereintrag in seiner Datenbank. Diese Modul kann Nutzereinträge aus LDAP                                  lesen und gewünschte Felder in Moodle vorbelegen. Für die folgenden Zugänge                                  werden nur Benutzername und Passwort überprüft.';
$string['auth_ldapextrafields'] = 'Diese Felder sind optional. Sie können einige Moodle Nutzer-Felder mit Daten aus <b>LDAP-Feldern</b>, die Sie hier spezifizieren, vorbelegen. <p>Wenn Sie diese Felder leer lassen, wird nichts von LDAP transferiert und die Moodle Voreinstellungen werden verwendet.</p><p>In jedem Fall können Nutzer diese Felder editieren, nachdem Sie sich angemeldet haben.</p>';
$string['auth_ldaptitle'] = 'LDAP-Server';
$string['auth_manualdescription'] = 'Diese Methode verhindert, dass Nutzer Ihre eigenen Zugänge anlegen können. Jeder Zugang muss manuell vom Administrator selbst eingerichtet werden.';
$string['auth_manualtitle'] = 'Nur manuelle Zugänge';
$string['auth_multiplehosts'] = 'Mehrere Hosts können angegeben werden (z.B. host1.com;host2.com;host3.com)';
$string['auth_nntpdescription'] = 'Diese Methode verwendet einen NNTP-Server, um zu prüfen, ob der angegebener Nutzername und das Passwort gültig sind.';
$string['auth_nntphost'] = 'NNTP Server-Adresse. Benutzen Sie die IP, nicht den DNS-Namen.';
$string['auth_nntpport'] = 'NNTP Serverport-Nummer. Normalerweise ist das 119.';
$string['auth_nntptitle'] = 'NNTP-Server';
$string['auth_nonedescription'] = 'Nutzer können sich anmelden und gültige Nutzer-Accounts erstellen, und zwar ohne Authentifizierung durch einen externen Server und ohne E-Mail-Bestätigung. Verwenden Sie diese Option vorsichtig, denken Sie an mögliche Sicherheits- und Administrationsprobleme.';
$string['auth_nonetitle'] = 'Keine Authentifizierung';
$string['auth_pamdescription'] = 'Diese Methode verwendet PAM um auf die richtigen Nutzernamen auf dem Server zuzugreifen. Sie müssen hierzu <a href=\"http://www.math.ohio-state.edu/~ccunning/pam_auth/\" target=\"_blank\">PHP4 PAM Authentication</a> installieren, um das Modul zu nutzen.';
$string['auth_pamtitle'] = 'PAM (Pluggable Authentication Modules)';
$string['auth_passwordisexpired'] = 'Ihr Passwort ist abgelaufen. Wollen Sie Ihr Passwort jetzt aktualisieren?';
$string['auth_passwordwillexpire'] = 'Ihr Passwort wird in $a Tagen ablaufen. Wollen Sie Ihr Passwort nun aktualisieren?';
$string['auth_pop3description'] = 'Diese Methode verwendet einen POP3-Server, um zu prüfen, ob der angegebener Nutzername und das Passwort gültig sind.';
$string['auth_pop3host'] = 'POP3-Server-Adresse. Benutzen Sie die IP, nicht den DNS-Namen.';
$string['auth_pop3mailbox'] = 'Name der Mailbox mit der eine Verbindung hergestellt werden soll (z.B. Inbox)';
$string['auth_pop3port'] = 'POP3-Serverport-Nummer. Normalerweise ist das 110, für SSL 995.';
$string['auth_pop3title'] = 'POP3-Server';
$string['auth_pop3type'] = 'Servertyp. Wenn Ihr Server Sicherheitszertifikate verwendet, wählen Sie pop3cert.';
$string['auth_radiusdescription'] = 'Dieses Verfahren verwendet einen <a href=\"http://en.wikipedia.org/wiki/RADIUS\" target=\"_blank\">RADIUS</a> Server zur Prüfung des Nutzernamens und des Passwortes.';
$string['auth_radiushost'] = 'Adresse des RADIUS-Servers';
$string['auth_radiusnasport'] = 'Port für Verbindung';
$string['auth_radiussecret'] = 'Shared secret';
$string['auth_radiustitle'] = 'RADIUS-Server';
$string['auth_shib_convert_data'] = 'Datenmodifikation APU';
$string['auth_shib_convert_data_description'] = 'Sie können diese API nutzen, um Daten von Shibboleth zu bearbeiten. <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">Hier</a> finden Sie weitere Hinweise.';
$string['auth_shib_convert_data_warning'] = 'Die Datei existiert nicht oder ist vom Server nicht lesbar.';
$string['auth_shib_instructions'] = 'Nutzen Sie den <a href=\"$a\">Shibboleth Login</a>, um Zugangüber Shibboleth zu erhalten, wenn Ihr Unternehmen dies unterstützt. <br />Sonst verwenden Sie das normale hier angezeigte Loginformular.';
$string['auth_shib_instructions_help'] = 'Tragen Sie hier Informationen für Ihre Nutzer/innen ein, die ihnen den Zugang mit Hilfe von Shibboleth erklären. Diese werden auf der Loginseite angzeigt. Der Text sollte einen Link \"<b>$a</b>\" enthalten, damit ein einfachere Login möglich ist. Wenn Sie das Feld leer lassen, werden die Standard-Texte angezeigt und keine Hinweise auf den Shibboleth Login.';
$string['auth_shib_only'] = 'nur Shibboleth';
$string['auth_shib_only_description'] = 'Checken Sie diese Option, wenn eine Shibboleth-Authentifizierung bevorzugt wird.';
$string['auth_shib_username_description'] = 'Name der Shibboleth Umgebungsvariable, die als Moodle-Nutzername verwandt werden soll';
$string['auth_shibboleth_login'] = 'Shibboleth Login';
$string['auth_shibboleth_manual_login'] = 'Manueller Login';
$string['auth_shibbolethdescription'] = 'Mit diesem Verfahren können Sie die Verbindung zu einem bestehenden Shibboleth Server herstellen, um  Zugänge zu prüfen und anzulegen.';
$string['auth_shibbolethtitle'] = 'Shibboleth';
$string['auth_updatelocal'] = 'Update lokaler Daten';
$string['auth_updatelocal_expl'] = '<p><b>Update lokaler Daten:</b> Wenn dieses Feld aktiviert wird, wird das Feld (aus externer Quelle (external auth)) jedes Mal aktualisiert wenn der Teilnehmer sich einloggt oder eine Nutzersynchronisation erfolgt. Dateneinträge, die lokal aktualisiert werden, sollten geschützt werden.</p>';
$string['auth_updateremote'] = 'Update externer Daten';
$string['auth_updateremote_expl'] = '<p><b>Update externer Daten:</b> Wenn aktiviert wird die externe Authentifizierung aktualisiert wennn der Nutzerdatzensatz aktualisiert wird. Felder sollten offen bleiben, um Dateneinträge zuzulassen.</p>';
$string['auth_updateremote_ldap'] = '<p><b>Anmerkung:</b> Das Update externer LDAP-Daten erfordert die Einstellung binddn und bindpw für einen Bind-user mit Schreibrechten für alle Nutzerdatensätze. It currently does not preserve multi-valued attributes, and will remove extra values on update. </p>';
$string['auth_user_create'] = 'Nutzer-Erstellung aktivieren';
$string['auth_user_creation'] = 'Neue (anonyme) Nutzer können Nutzer-Accounts erstellen außerhalb der Authentifizierungsquelle und per E-Mail bestätigen. Sofern Sie dies aktivieren, achten Sie darauf, ebenso modulspezifische Optionen für die Modulerstellung zu konfigurieren.';
$string['auth_usernameexists'] = 'Der ausgewählte Nutzername existiert bereits. Bitte wählen Sie einen neuen.';
$string['authenticationoptions'] = 'Authentifizierungsoptionen';
$string['authinstructions'] = 'Hier können Sie Ihren Nutzern Anweisungen geben, welche Nutzernamen und Passwort sie verwenden sollen. Der eingegebene Text erscheint auf der Anmeldeseite. Wenn Sie nichts eingeben, werden keine Anweisungen angezeigt.';
$string['changepassword'] = 'Passwort-URL ändern';
$string['changepasswordhelp'] = 'Hier können Sie eine Adresse angeben, unter der die Nutzer ihren Nutzernamen/Passwort ändern können, sofern Sie dies vergessen haben. Diese Option wird den Nutzern als Schaltfläche auf der Anmeldungsseite angeboten. Wenn Sie dieses Feld leer lassen, wird er nicht angezeigt.';
$string['chooseauthmethod'] = 'Authentifizierungsmethode';
$string['createpasswordifneeded'] = 'Passwort anlegen, falls erforderlich';
$string['forcechangepassword'] = 'Verbindliche Änderung des Passwortes';
$string['forcechangepassword_help'] = 'Nutzer werden aufgefordert, Ihr Passwort beim nächsten Login zu ändern';
$string['forcechangepasswordfirst_help'] = 'Nutzer werden aufgefordert, Ihr Passwort beim ersten Login zu ändern';
$string['guestloginbutton'] = 'Taste für das Gast-Login';
$string['infilefield'] = 'Erforderliches Feld in Datei';
$string['instructions'] = 'Anweisungen';
$string['internal'] = 'Intern';
$string['locked'] = 'Gesperrt';
$string['md5'] = 'MD5-Verschlüsselung';
$string['passwordhandling'] = 'Nutzung des Passwortfeldes';
$string['plaintext'] = 'Reiner Text';
$string['shib_no_attributes_error'] = 'Sie versuchen vermutlich die Shibboleth Authentifizierung zu verwenden. Moodle hat jedoch keine Attribute für die Nutzer/innen erhalten. Prüfen Sie bitte, ob der Identity Provider die erforderlichen Attribute ($a) dem Moodle-Serviceprovider zur Verfügung stellt oder informieren Sie den Webmaster des Servers.';
$string['shib_not_all_attributes_error'] = 'Moodle benötigt einige Shibboleth-Attribute die derzeitnicht bereitgestellt werden. Es handelt sich um die Attribute: $a<br />Benachrichtigen Sie bitte den Webmaster des Servers oder Ihren Identity Provider.';
$string['shib_not_set_up_error'] = 'Die Shibboleth-Authentifizierung scheint nicht richtig eingerichtet zu sein. Beachten Sie die <a href=\"README.txt\">README-Datei</a> mit weiteren Informationen zur Einrichtung der Shibboleth-Authentifizierung.';
$string['showguestlogin'] = 'Sie können die Gast-Login Schaltfläche auf der Anmeldeseite anzeigen oder verbergen.';
$string['stdchangepassword'] = 'Standardseite zur Passwortänderung nutzen';
$string['stdchangepassword_expl'] = 'Stellen Sie Ja ein, wenn das externe Authentifizierungssystem eine Änderung des Passwortes durch Moodle zulässt. Die Einstellungen überschreiben \'Passwort-URL ändern\'';
$string['stdchangepassword_explldap'] = 'Anmerkung: Es wird empfohlen LDAP über einen SSL verschlüsselten Tunnel (ldaps://) zu nutzen wenn der LDAP Server remote verwendet wird.';
$string['unlocked'] = 'Bearbeitbar';
$string['unlockedifempty'] = 'Bearbeitbar wenn Feld leer';
$string['update_never'] = 'Nie';
$string['update_oncreate'] = 'Beim Anlegen';
$string['update_onlogin'] = 'Bei jedem Login';
$string['update_onupdate'] = 'Bei der Aktualisierung';

?>
