<?php

// All of the language strings in this file should also exist in
// auth.php to ensure compatibility in all versions of Moodle.

$string['auth_ldap_ad_create_req'] = 'Im Active Directory konnte kein neuer Account angelegt werden. Prüfen Sie, ob alle Voraussetzungen hierfür getroffen wurden (LDAPS Verbindung, bind user mit angemessenen Rechten etc.)';
$string['auth_ldap_attrcreators'] = 'Liste von Gruppen oder Kontexten, deren Mitglieder berechtigt sind Attribute zu erstellen. Mehrere Gruppen werden durch ein \';\' (Semikolon) getrennt. Der Eintrag lautet üblicherweise ähnlich wie: cn=teacher,ou=staff,o=myorg.';
$string['auth_ldap_attrcreators_key'] = 'Ersteller von Attributen';
$string['auth_ldap_auth_user_create_key'] = 'Nutzer extern anlegen';
$string['auth_ldap_bind_dn'] = 'Möchten Sie Bind-User für die Nutzersuche verwenden, so geben Sie dies hier an. Normalerweise etwas wie \'cn=ldapuser,ou=public,o=org\'';
$string['auth_ldap_bind_dn_key'] = 'Gekennzeichneter Name';
$string['auth_ldap_bind_pw'] = 'Passwort für Bind-User.';
$string['auth_ldap_bind_pw_key'] = 'Kennwort';
$string['auth_ldap_bind_settings'] = 'Bind-Einstellungen';
$string['auth_ldap_changepasswordurl_key'] = 'URL zur Kennwortänderung';
$string['auth_ldap_contexts'] = 'Liste der Umgebungen, in denen sich Nutzer/innen befinden. Trennen Sie verschiedene Umgebungen durch \';\'. Beispiel: \'ou=users,o=org; ou=others,o=org\'';
$string['auth_ldap_contexts_key'] = 'Kontexte';
$string['auth_ldap_create_context'] = 'Wenn Sie die Nutzererstellung mit E-Mail-Bestätigung aktivieren, geben Sie die Umgebung an, wo die Nutzer/innen erstellt werden sollen. Diese Umgebung sollte sich von der anderer Nutzer/innen unterscheiden, um Sicherheitsrisiken zu vermeiden. Sie brauchen diese Umgebung nicht zur ldap_context Variable hinzuzufügen, Moodle sucht in dieser Umgebung automatisch nach Nutzer/innen.';
$string['auth_ldap_create_context_key'] = 'Kontext für neue Nutzer';
$string['auth_ldap_create_error'] = 'Fehler beim Anlegen von Nutzern in LDAP';
$string['auth_ldap_creators'] = 'Eine Liste von Gruppen, denen es erlaubt ist, Kurse zu verwalten und neu anzulegen (Liste der Kursverwalter/innen). Trennen Sie mehrere Gruppen durch \';\'. Normalerweise etwas wie \'cn=teachers, ou=staff, o=myorg\'';
$string['auth_ldap_creators_key'] = 'Kursverwalter/innen';
$string['auth_ldap_expiration_desc'] = 'Setzen Sie Nein (no) um die Überprüfung abgelaufener Passworte abzuschalten oder LDAP um sie direkt über LDAP abzuwickeln.';
$string['auth_ldap_expiration_key'] = 'Ablauf';
$string['auth_ldap_expiration_warning_desc'] = 'Zahl der Tage vor dem Ablauf der Gültigkeit des Passwortes an denen eine Nachricht versandt wird.';
$string['auth_ldap_expiration_warning_key'] = 'Ablaufhinweis';
$string['auth_ldap_expireattr_desc'] = 'optional: Ändert die LDAP-Attribute zur Speicherung der Passwortgültigkeitsdauer passwordExpirationTime';
$string['auth_ldap_expireattr_key'] = 'Ablauf-Attribut';
$string['auth_ldap_graceattr_desc'] = 'optional: Ändert die gracelogin Attribute';
$string['auth_ldap_gracelogin_key'] = 'grace Login Attribute';
$string['auth_ldap_gracelogins_desc'] = 'Aktiviert LDAP gracelogin Unterstützung. Wenn das Passwort abgelaufen ist, können die Nutzer/innen sich weiter einloggen bis gracelogin den Wert 0 hat. Nach dem Aktivieren der Einstellung wird eine gracelogin Mitteilung angezeigt, wenn das Passwort abgelaufen ist.';
$string['auth_ldap_gracelogins_key'] = 'Frist Login';
$string['auth_ldap_groupecreators'] = 'Liste von Gruppen oder Kontexten, deren Mitglieder berechtigt sind Gruppen zu erstellen. Mehrere Gruppen werden durch ein \';\' (Semikolon) getrennt. Der Eintrag lautet üblicherweise ähnlich wie: cn=teacher,ou=staff,o=myorg.';
$string['auth_ldap_groupecreators_key'] = 'Gruppenersteller';
$string['auth_ldap_host_url'] = 'Geben Sie einen LDAP Server in URL-Form an wie \'ldap://ldap.myorg.de/\' oder \'ldaps://ldap.myorg.de/\'';
$string['auth_ldap_host_url_key'] = 'Host URL';
$string['auth_ldap_ldap_encoding'] = 'Geben Sie die Codierung des LDAP Servers an. Meist ist dies utf-8. MS AD v2 verwendet andere Codierung wie cp1252, cp1250, etc.';
$string['auth_ldap_ldap_encoding_key'] = 'LDAP Codierung';
$string['auth_ldap_login_settings'] = 'Login-Einstellungen';
$string['auth_ldap_memberattribute'] = 'Geben Sie die Mitgliedsoptionen an, wenn Nutzer/innen zu einer Gruppe gehören. Normalerweise \'member\'';
$string['auth_ldap_memberattribute_isdn'] = 'Optional: Überschreib-Handlung für Mitgliedsattribut-Werte, entweder 0 oder 1';
$string['auth_ldap_memberattribute_isdn_key'] = 'Mitgliedsattribut nutzt dn';
$string['auth_ldap_memberattribute_key'] = 'Mitgliedsattribut';
$string['auth_ldap_no_mbstring'] = 'Die mbstrings Erweiterung ist erforderlich, um Nutzer im Active Dirctory anzulegen.';
$string['auth_ldap_noconnect'] = 'LDAP-Modul kann keine Verbindung zum Server herstellen: $a';
$string['auth_ldap_noconnect_all'] = 'LDAP-Modul kann keine Verbindung zu irgendeinem Server herstellen: $a';
$string['auth_ldap_noextension'] = 'Hinweis: Das PHP LDAP Modul scheint nicht verfügbar zu sein. Prüfen Sie, ob es installiert und aktiviert ist.';
$string['auth_ldap_objectclass'] = 'Filter für die Suche nach Nutzernamen. Normalerweise tragen Sie ein: objectClass=posixAccount . Defaults to objectClass=* what will return all objects from LDAP.';
$string['auth_ldap_objectclass_key'] = 'Objekt Class';
$string['auth_ldap_opt_deref'] = 'Legt fest wie Aliasbezeichnungen bei der Suche behandelt werden. Wählen Sie einen der folgenden Werte: \"No\" (LDAP_DEREF_NEVER) or \"Yes\" (LDAP_DEREF_ALWAYS)';
$string['auth_ldap_opt_deref_key'] = 'Alias berücksichtigen';
$string['auth_ldap_passtype'] = 'Format für neue oder geänderte Passworte auf LDAP-Server';
$string['auth_ldap_passtype_key'] = 'Passwortformat';
$string['auth_ldap_passwdexpire_settings'] = 'LDAP Passwortablaufeinstellung';
$string['auth_ldap_preventpassindb'] = 'Wählen Sie ja, um Passwörter <b>nicht</b> in der Moodle-Datenbank zu speichern';
$string['auth_ldap_preventpassindb_key'] = 'Kennwörter verbergen';
$string['auth_ldap_search_sub'] = 'Nutzer/innen in Teilumgebungen suchen';
$string['auth_ldap_search_sub_key'] = 'Subkontexte suchen';
$string['auth_ldap_server_settings'] = 'LDAP Server-Einstellungen';
$string['auth_ldap_unsupportedusertype'] = 'auth: ldap user_create() unterstützt ausgewählten Nutzertyp nicht:\"$a\" (..yet)';
$string['auth_ldap_update_userinfo'] = 'Nutzerdaten (Vorname, Name, Adresse...) von LDAP zu Moodle aktualisieren. Weitere Informationen in /auth/ldap/attr_mappings.php';
$string['auth_ldap_user_attribute'] = 'Verwendete Eigenschaften, um Nutzer zu benennen/suchen. Normalerweise \'cn\'.';
$string['auth_ldap_user_attribute_key'] = 'Nutzerattribut';
$string['auth_ldap_user_exists'] = 'Der LDAP Nutzername existiert bereits';
$string['auth_ldap_user_settings'] = 'Einstellung zur Nutzerüberprüfung (user lookup settings)';
$string['auth_ldap_user_type'] = 'Auswahl, wie Nutzer in LDAP hinterlegt werden. Die Einstellungen legen fest wie der Login-Ablauf, grace Logins und Nutzererstellung ablaufen.';
$string['auth_ldap_user_type_key'] = 'Nutzertyp';
$string['auth_ldap_usertypeundefined'] = 'config.user_type ist nicht definiert oder Funktion ldap_expirationtime2unix unterstützt den ausgewählten Typ nicht.';
$string['auth_ldap_usertypeundefined2'] = 'config.user_type ist nicht definiert oder Funktion ldap_unixi2expirationtime unterstützt den ausgewählten Typ nicht.';
$string['auth_ldap_version'] = 'Diese Version des LDAP Protokolls nutzt Ihr Server.';
$string['auth_ldap_version_key'] = 'Version';
$string['auth_ldapdescription'] = 'Diese Methode bietet die Authentifizierung gegenüber einem externen LDAP-Server. Wenn der vergebene Nutzername und Passwort gültig sind, erstellt Moodle einen neuen Nutzereintrag in seiner Datenbank. Dieses Modul kann Nutzereinträge aus LDAP                                  lesen und gewünschte Felder in Moodle vorbelegen. Für die nachfolgenden Zugänge werden nur Nutzername und Passwort überprüft.';
$string['auth_ldapextrafields'] = 'Diese Felder sind optional. Sie können einige Moodle Nutzer-Felder mit Daten aus <b>LDAP-Feldern</b> vorbelegen, die Sie hier spezifizieren. <p>Wenn Sie diese Felder leer lassen, wird nichts von LDAP transferiert und die Moodle Voreinstellungen werden verwendet.</p><p>In jedem Fall können Nutzer diese Felder editieren, nachdem sie sich angemeldet haben.</p>';
$string['auth_ldapnotinstalled'] = 'LDAP Authentifizierung kann nicht genutzt werden. Das PHP LDAP Modul ist nichtinstalliert.';
$string['auth_ldaptitle'] = 'LDAP-Server';
$string['auth_ntlmsso'] = 'NTLM SSO';
$string['auth_ntlmsso_enabled'] = 'Aktivieren Sie diese Einstellung, um die einmalige Anmeldung (Single Sign On) mit der NTML-Domain zu versuchen. 
<strong>Anmerkung:</strong> Zusätzlich sind Einstellungen für den Webserver notwendig. Siehe <a href=\"http://docs.moodle.org/en/NTLM_authentication\">http://docs.moodle.org/en/NTLM_authentication</a>';
$string['auth_ntlmsso_enabled_key'] = 'Aktivieren';
$string['auth_ntlmsso_ie_fastpath'] = 'Aktivieren Sie diese Einstellung, um \'NTLM SSO fast path\' zuzulassen. Dies funktioniert ausschließlich, wenn mit dem MS Internet Explorer auf Moodle zugegriffen wird.';
$string['auth_ntlmsso_ie_fastpath_key'] = 'MS IE fast path?';
$string['auth_ntlmsso_subnet'] = 'Wenn das Feld nicht leer ist, dann ist SSO nur mit Adressen aus dem Subnet möglich. Format: xxx.xxx.xxx.xxx/bitmask';
$string['auth_ntlmsso_subnet_key'] = 'Subnet';
$string['ntlmsso_attempting'] = 'Einmal-Anmeldung über NTLM versuchen...';
$string['ntlmsso_failed'] = 'Die automatische Anmeldung ist fehlgeschlagen. Versuchen Sie das normale Login...';
$string['ntlmsso_isdisabled'] = 'NTLM SSO ist deaktiviert.';