<?PHP // $Id$ 
      // blog.php - created with Moodle 1.9.7+ (Build: 20091226) (2007101570)


$string['addnewentry'] = 'Neuer Eintrag';
$string['backupblogshelp'] = 'Mit der Aktivierung dieser Funktion werden die Blogs in das automatische Backup der Website einbezogen.';
$string['blockmenutitle'] = 'Blog-Menü';
$string['blocktagstitle'] = 'Blog-Schlagworte';
$string['blocktitle'] = 'Titel des Blocks für Schlagworte';
$string['blog'] = 'Blog';
$string['blogdeleteconfirm'] = 'Diesen Blog löschen?';
$string['blogpreferences'] = 'Einstellungen';
$string['blogs'] = 'Blogs';
$string['blogtags'] = 'Blog-Schlagworte';
$string['courseblog'] = 'Kursblog: $a';
$string['courseblogs'] = 'Blogs von anderen im Kurs';
$string['deleteotagswarn'] = 'Sind Sie sicher, dass Sie diese Schlagworte <br />aus allen Blog-Einträgen und aus dem System entfernen möchten?';
$string['disableblogs'] = 'Blog-System vollständig deaktivieren';
$string['emptybody'] = 'Der Eingabetext darf nicht leer sein';
$string['emptytitle'] = 'Der Titel darf nicht leer sein';
$string['entrybody'] = 'Eingabetext';
$string['entrybodyonlydesc'] = 'Beschreibung';
$string['entryerrornotyours'] = 'Dies ist kein eigener Eintrag';
$string['entrysaved'] = 'Eintrag wurde gespeichert';
$string['entrytitle'] = 'Titel';
$string['entryupdated'] = 'Eintrag aktualisiert';
$string['groupblog'] = 'Gruppenblog: $a';
$string['groupblogs'] = 'Blogs von anderen in einer Gruppen';
$string['intro'] = 'Der RSS-Feed wurde automatisch von einem oder mehreren Blogs erstellt.';
$string['noentriesyet'] = 'Keine sichtbaren Einträge';
$string['noguestpost'] = 'Gäste können in Blogs keine Beiträge veröffentlichen!';
$string['norighttodeletetag'] = 'Sie dürfen dieses Schlagwort nicht löschen: $a';
$string['notallowedtoedit'] = 'Sie haben keine Berechtigung, diesen Beitrag zu bearbeiten';
$string['numberofentries'] = 'Einträge: $a';
$string['numberoftags'] = 'Zahl der anzuzeigenden Schlagworte';
$string['pagesize'] = 'Zahl der Einträge pro Seite';
$string['permalink'] = 'Permalink';
$string['personalblogs'] = 'Nur den eigenen Blog';
$string['publishto'] = 'Veröffentlichen';
$string['publishtonoone'] = 'Für mich alleine (Entwurf)';
$string['publishtosite'] = 'Für alle auf dieser Website';
$string['publishtoworld'] = 'Für alle auch außerhalb (öffentlich)';
$string['settingsupdatederror'] = 'Es ist ein Fehler aufgetreten. Die Einstellungen konnten nicht aktualisiert werden.';
$string['siteblog'] = 'Site-Blog: $a';
$string['siteblogs'] = 'Nutzer/innen können alle Blogs sehen';
$string['tagdatelastused'] = 'Tag, an dem das Schlagwort zuletzt gebraucht wurde';
$string['tags'] = 'Schlagworte';
$string['tagsort'] = 'Sortierung der Schlagworte nach';
$string['tagtext'] = 'Schlagworttext';
$string['timewithin'] = 'Anzeige der Schlagworte, die an so vielen Tagen gebraucht wurden';
$string['updateentrywithid'] = 'Eintrag aktualisieren';
$string['userblog'] = 'Nutzer-Blog: $a';
$string['viewcourseentries'] = 'Kurseinträge';
$string['viewmyentries'] = 'Meine Einträge';
$string['viewsiteentries'] = 'Alle Einträge';
$string['worldblogs'] = 'Für alle weltweit sichtbar (öffentlich)';
$string['blogdisable'] = 'Blogfunktion ist deaktiviert!'; // ORPHANED
$string['cannotviewcourseblog'] = 'Sie haben nicht die erforderlichen Berechtigungen, Blogs in diesem Kurs zu sehen'; // ORPHANED
$string['cannotviewcourseorgroupblog'] = 'Sie haben nicht die erforderlichen Berechtigungen, Blogs in diesem Kurs/Gruppe zu sehen'; // ORPHANED
$string['cannotviewsiteblog'] = 'Sie haben nicht die erforderlichen Berechtigungen, alle Blogs dieser Site zu sehen'; // ORPHANED
$string['cannotviewuserblog'] = 'Sie haben nicht die erforderlichen Berechtigungen, Blogs der Nutzer zu lesen'; // ORPHANED
$string['courseblogdisable'] = 'Blogfunktion ist nicht aktiviert'; // ORPHANED
$string['deleteposterror'] = 'Beim Löschen von Einträgen ist ein Fehler aufgetreten'; // ORPHANED
$string['donothaveblog'] = 'Sie haben zur Zeit keinen eigenen Blog.'; // ORPHANED
$string['groupblogdisable'] = 'Gruppenblogs sind nicht aktiviert'; // ORPHANED
$string['incorrectblogfilter'] = 'Es wurde ein falscher Blogfilter ausgewählt'; // ORPHANED
$string['nosuchentry'] = 'Kein Blogeintrag dazu vorhanden'; // ORPHANED
$string['siteblogdisable'] = 'Site-Blogs wurden nicht aktiviert'; // ORPHANED
$string['wrongpostid'] = 'Falsche Blog-Post-ID'; // ORPHANED
$string['addotags'] = 'Offizielles Schlagwort hinzufügen'; // ORPHANED
$string['addptags'] = 'Nutzerdefiniertes Schlagwort hinzufügen'; // ORPHANED
$string['otags'] = 'Offizielles Schlagwort'; // ORPHANED
$string['ptags'] = 'Nutzerdefiniertes Schlagwort'; // ORPHANED

?>
