<?PHP // $Id$ 
      // group.php - created with Moodle 1.9 Beta + (2007081600)


$string['addgroupstogrouping'] = 'Gruppe zur Gruppierung hinzufügen';
$string['addgroupstogroupings'] = 'Gruppen verwalten';
$string['adduserstogroup'] = 'Nutzer/innen verwalten';
$string['anygrouping'] = '[Jede Gruppierung]';
$string['backtogroupings'] = 'Zurück zu Gruppierungen';
$string['backtogroups'] = 'Zurück zu Gruppen';
$string['createautomaticgrouping'] = 'Automatische Gruppierung anlegen';
$string['creategroup'] = 'Gruppe anlegen';
$string['creategrouping'] = 'Gruppierung anlegen';
$string['creategroupinselectedgrouping'] = 'Gruppe in der Gruppierung anlegen';
$string['createorphangroup'] = 'Einzelne Gruppe';
$string['databaseupgradegroups'] = 'Die Gruppenversion ist jetzt $a';
$string['defaultgroupdescription'] = 'Voreingestellte Gruppenbeschreibung';
$string['defaultgrouping'] = 'Voreingestellte Gruppierung';
$string['defaultgroupingname'] = 'Gruppierung';
$string['defaultgroupname'] = 'Gruppe';
$string['defaultgroupprefix'] = 'Gruppe';
$string['deletegroupconfirm'] = 'Sind Sie sicher, dass Sie die Gruppe \'$a\' löschen möchten?';
$string['deletegrouping'] = 'Gruppierung löschen';
$string['deletegroupingconfirm'] = 'Sind Sie sicher, dass Sie die Gruppierung \'$a\' löschen möchten? (Die Gruppen innerhalb der Gruppierung werden nicht gelöscht.)';
$string['deleteselectedgroup'] = 'Markierte Gruppe löschen';
$string['displaygrouping'] = 'Gruppierung anzeigen';
$string['distributealphabetically'] = 'Alphabetisch nach Nachname in Gruppen einteilen';
$string['distributeevenly'] = 'Übrig gebliebene Teilnehmer/innen gleichmäßig auf Gruppen  verteilen';
$string['editgroupingsettings'] = 'Gruppierungseinstellungen bearbeiten';
$string['editgroupsettings'] = 'Gruppeneinstellungen bearbeiten';
$string['enrolmentkey'] = 'Zugangsschlüssel';
$string['erroraddremoveuser'] = 'Fehler beim Hinzufügen/Entfernen von $a in der Gruppe';
$string['erroreditgroup'] = 'Fehler beim Bearbeiten der Gruppe $a';
$string['erroreditgrouping'] = 'Fehler beim Bearbeiten der Gruppierung $a';
$string['errorinvalidgroup'] = 'Fehler: Ungültige Gruppe $a';
$string['existingmembers'] = 'Vorhandene Mitglieder: $a';
$string['group'] = 'Gruppe';
$string['groupaddedsuccesfully'] = 'Gruppe $a erfolgreich hinzugefügt';
$string['groupdescription'] = 'Gruppenbeschreibung';
$string['groupinfo'] = 'Info über markierte Gruppen';
$string['groupinfomembers'] = 'Info über markierte Mitglieder';
$string['groupinfopeople'] = 'Info über markierte Personen';
$string['grouping'] = 'Gruppierung';
$string['groupingdescription'] = 'Beschreibung der Gruppierung';
$string['groupingname'] = 'Name der Gruppierung';
$string['groupingnameexists'] = 'Der Name der Gruppierung \'$a\' existiert bereits in diesem Kurs. Bitte wählen Sie einen anderen Namen.';
$string['groupings'] = 'Gruppierungen';
$string['groupmember'] = 'Gruppenmitglied';
$string['groupmemberdesc'] = 'Standard-Rolle für Mitglieder einer Gruppe';
$string['groupmembers'] = 'Gruppenmitglieder';
$string['groupmembersonly'] = 'Nur für Gruppenmitglieder verfügbar';
$string['groupmembersonlyerror'] = 'Entschuldigung, aber Sie müssen Mitglied in einer Gruppe sein, die diese Aktivität nutzt';
$string['groupmemberssee'] = 'Gruppenmitglieder anzeigen';
$string['groupmembersselected'] = 'Mitglieder der markierten Gruppe';
$string['groupmode'] = 'Gruppenmodus';
$string['groupmodeforce'] = 'Gruppenmodus modulübergreifend erzwingen';
$string['groupmy'] = 'Meine Gruppe';
$string['groupname'] = 'Gruppenname';
$string['groupnameexists'] = 'Der Gruppenname \'$a\' existiert in diesem Kurs bereits, wählen Sie bitte einen anderen.';
$string['groupnotamember'] = 'Entschuldigung, aber Sie sind nicht Mitglied dieser Gruppe';
$string['groups'] = 'Gruppen';
$string['groupsinselectedgrouping'] = 'Gruppen in der Gruppierung';
$string['groupsnone'] = 'Keine Gruppen';
$string['groupsseparate'] = 'Getrennte Gruppen';
$string['groupsvisible'] = 'Sichtbare Gruppen';
$string['hidepicture'] = 'Bild verbergen';
$string['javascriptrequired'] = 'Diese Seite benötigt JavaScript, um aktiviert zu werden.';
$string['membersofselectedgroup'] = 'Mitglieder der Gruppe';
$string['newpicture'] = 'Neues Bild';
$string['nopermissionforcreation'] = 'Die Gruppe \"$a\" konnte nicht erstellt werden, weil Sie nicht über die notwendigen Rechte verfügen.';
$string['notingrouping'] = '[Nicht in einer Gruppierung]';
$string['numberofgroups'] = 'Anzahl der Gruppen';
$string['numberofstudents'] = 'Anzahl der Teilnehmer/innen';
$string['potentialmembers'] = 'Mögliche Mitglieder: $a';
$string['prefixforgroupnames'] = 'Prefix für Gruppennamen';
$string['printerfriendly'] = 'Druckansicht';
$string['removegroupfromselectedgrouping'] = 'Gruppe aus der Gruppierung entfernen';
$string['removeselectedusers'] = 'Ausgewählte';
$string['selectnumberineachgroup'] = 'Zahl in jeder Gruppe wählen';
$string['selectnumberofgroups'] = 'Zahl der Gruppen wählen';
$string['showgroupsingrouping'] = 'Gruppen in Gruppierungen anzeigen';
$string['showmembersforgroup'] = 'Mitglieder der Gruppe anzeigen';
$string['usestudentsonlyfromselectedgroup'] = 'Nur Teilnehmer/innen der ausgewählten Gruppe verwenden';
$string['cancel'] = 'Abbrechen'; // ORPHANED
$string['editgroupingpermissions'] = 'Gruppierungsrechte bearbeiten'; // ORPHANED
$string['errorinvalidgrouping'] = 'Fehler: Ungültige Gruppierung $a'; // ORPHANED
$string['errornotingrouping'] = 'Entschuldigung, aber Sie können keine Gruppe in $a anlegen'; // ORPHANED
$string['errornotingroupingedit'] = 'Entschuldigung, aber Sie können die Gruppierung $a nicht bearbeiten'; // ORPHANED
$string['groupfor'] = 'für die Gruppe'; // ORPHANED
$string['return'] = 'Zurück'; // ORPHANED
$string['save'] = 'Sichern'; // ORPHANED
$string['showusersalreadyingroup'] = 'Nutzer/innen anzeigen, die bereits in einer Gruppe in der Gruppierung sind'; // ORPHANED
$string['teachersgroupmark'] = 'Trainer/innen dürfen keine Aktivitäten von Gruppen bewerten, in denen sie nicht Mitglied sind'; // ORPHANED
$string['teachersgroupview'] = 'Trainer/innen dürfen keine Aktivitäten von Gruppen sehen, in denen sie nicht Mitglied sind'; // ORPHANED
$string['teachersoverride'] = 'Trainer/innen, die in keiner Gruppe sind, dürfen Aktivitäten aller Gruppen ansehen und bewerten (überschreibt die o.g. Einstellungen)'; // ORPHANED
$string['upgradeconfirm'] = 'Achtung: Gruppentabellen, die in Moodle 1.8 dev angelegt wurden, müssen für diesen Upgrade gelöscht werden. Wollen Sie fortsetzen?'; // ORPHANED
$string['viewallgroupsactivities'] = 'Teilnehmer/innen dürfen Aktivitäten aller Gruppen sehen, aber nicht ausführen'; // ORPHANED
$string['viewallgroupsmembers'] = 'Teilnehmer/innen dürfen die Mitglieder aller Gruppen sehen'; // ORPHANED
$string['viewowngroup'] = 'Teilnehmer/innen dürfen die Mitglieder ihrer eigenen Gruppen sehen'; // ORPHANED

?>
