<?php

// All of the language strings in this file should also exist in
// auth.php to ensure compatibility in all versions of Moodle.

$string['auth_ldap_ad_create_req'] = 'Kan ikke lage ny konto i Active Directory. Pass på at du har fått med alle ting nødvendig for att dette skal virke (LDAPS forbindelse, bind bruker med nødvendige rettigheter osv.)';
$string['auth_ldap_attrcreators'] = 'Liste med grupper eller kontekster hvor medlemmene kan lage egenskaper. Separer flere grupper med \';\'. Vanligvis noe i likhet med \'cn=lærere,ou=stab,o=minorg\'';
$string['auth_ldap_attrcreators_key'] = 'Egenskap oppretter';
$string['auth_ldap_auth_user_create_key'] = 'Lag brukere eksternt';
$string['auth_ldap_bind_dn'] = 'Hvis du vil bruke bind-user for å søke blant brukere skal det angis her. (Noe som f.eks. \'cn=ldapuser,ou=public,o=org\')';
$string['auth_ldap_bind_dn_key'] = 'Særpreget navn';
$string['auth_ldap_bind_pw'] = 'Passord for bind-user';
$string['auth_ldap_bind_pw_key'] = 'Passord';
$string['auth_ldap_bind_settings'] = 'Bind instillinger';
$string['auth_ldap_changepasswordurl_key'] = 'URL for å endre passord';
$string['auth_ldap_contexts'] = 'Innholdsliste over hvor brukerne er. Del ulike sammenhenger med \';\'. (F.eks. \'ou=users,o=org; ou=others,o=org\')';
$string['auth_ldap_contexts_key'] = 'Kontekster';
$string['auth_ldap_create_context'] = 'Hvis du lar brukere registrere seg med e-postbekreftelse, spesifiser sammenhengen de registreres. Dette må være ulikt andre brukere for å forhindre sikkerhetsproblemer. Du trenger ikke å legge denne sammenhengen til variabelen ldap_context, Moodle vil automatisk søke etter brukere fra denne sammenhengen.';
$string['auth_ldap_create_context_key'] = 'Kontekst for nye brukere';
$string['auth_ldap_create_error'] = 'Feil ved opprettelse av bruker i LDAP';
$string['auth_ldap_creators'] = 'Liste over grupper der medlemmene tillates å opprette nye klassesider. Separer flere grupper med \';\'. (Vanligvis f.eks. \'cn=teachers,ou=staff,o=myorg\')';
$string['auth_ldap_creators_key'] = 'Opprettere';
$string['auth_ldap_expiration_desc'] = 'Velg Nei for å slå av sjekking av utgått passord eller om LDAP leser passwordexpiration time direkte fra LDAP';
$string['auth_ldap_expiration_key'] = 'Utgår';
$string['auth_ldap_expiration_warning_desc'] = 'Antall dager før passordutløpsadvarsel vises.';
$string['auth_ldap_expiration_warning_key'] = 'Advarsel om utløp';
$string['auth_ldap_expireattr_desc'] = 'Valgritt: overstyrer ldap-egenskaper som lagrer passord ved utløpstid.';
$string['auth_ldap_expireattr_key'] = 'Utløper egenskap';
$string['auth_ldap_graceattr_desc'] = 'Valgfritt: Overstyrer antall påloggingeregenskapen.';
$string['auth_ldap_gracelogin_key'] = 'Egenskap for påloggingsforsøk';
$string['auth_ldap_gracelogins_desc'] = 'Slå på support for påloggingsforsøk ved bruk av LDAP. Etter at passordet er utløpt kan utløpt bruker logge på til antall påloggingsforsøk er lik 0. Ved å slå på denne innstillinger vises brukere en beskjed om at passordet er utløpt.';
$string['auth_ldap_gracelogins_key'] = 'Antall påloggingsforsøk';
$string['auth_ldap_groupecreators'] = 'Medlemmene i disse gruppene er tillatt å opprette grupper. Del forskjellige grupper med \';\'. Ser vanligvis ut som \'cn=teachers,ou=staff,o=myorg\'';
$string['auth_ldap_groupecreators_key'] = 'Gruppe opprettere';
$string['auth_ldap_host_url'] = 'Angi LDAP-vert i URL-form, f.eks. \'ldap://ldap.myorg.com/\' eller \'ldaps://ldap.myorg.com/\'';
$string['auth_ldap_host_url_key'] = 'Vert URL';
$string['auth_ldap_ldap_encoding'] = 'Angi koding som blir brukt av LDAP-serveren. Sannsynligvis utf-8, MS AD v2 bruker plattformkoding som cp1252, cp1250 osv.';
$string['auth_ldap_ldap_encoding_key'] = 'LDAP koding';
$string['auth_ldap_login_settings'] = 'Logginn-innstillinger';
$string['auth_ldap_memberattribute'] = 'Spesifiser atributt for medlemmer i en gruppe, f.eks. \'medlem\'';
$string['auth_ldap_memberattribute_isdn'] = 'Valgfritt: Overstyrer behandling av medlemsegenskaper, enten 0 eller 1';
$string['auth_ldap_memberattribute_isdn_key'] = 'Medlemsegenskap bruker dn';
$string['auth_ldap_memberattribute_key'] = 'Medlemsegenskap';
$string['auth_ldap_no_mbstring'] = 'Du trenger mbstring tillegget for å opprette brukere i Active Directory.';
$string['auth_ldap_noconnect'] = 'LDAP-modulen kan ikke kontakte server: $a';
$string['auth_ldap_noconnect_all'] = 'LDAP-modulen kan ikke kontakte noen servere: $a';
$string['auth_ldap_noextension'] = 'Advarsel: Det virker som PHP LDAP modulen ikke er på plass. Vær vennlig å sjekk at den er installert og påslått.';
$string['auth_ldap_objectclass'] = 'Valgfritt: Overstyrer objectClass brukt for å gi navn/lete eller brukere med ldap_user_type. Vanligvis trenger du ikke å endre denne.';
$string['auth_ldap_objectclass_key'] = 'Objektklasse';
$string['auth_ldap_opt_deref'] = 'Angir hvordan aliaser blir behandlet ved søking. Velg en av følgende verdier: \"No\" (LDAP_DER_NEVER) eller \"Yes\" (LDAP_DEREF_ALWAYS)';
$string['auth_ldap_opt_deref_key'] = 'Avreferanse aliaser';
$string['auth_ldap_passtype'] = 'Angi format for nye eller endrede passord i LDAP serveren.';
$string['auth_ldap_passtype_key'] = 'Passordformat';
$string['auth_ldap_passwdexpire_settings'] = 'Utløpsinnstillinger for LDAP-passord';
$string['auth_ldap_preventpassindb'] = 'Velg ja for å forhindre at passord blir lagret i Moodle\'s database.';
$string['auth_ldap_preventpassindb_key'] = 'Skjul passordene';
$string['auth_ldap_search_sub'] = 'Sett verdi <> 0 hvis du vil søke etter brukere fra underemner.';
$string['auth_ldap_search_sub_key'] = 'Velg underkontekster';
$string['auth_ldap_server_settings'] = 'LDAP serverinnstillinger';
$string['auth_ldap_unsupportedusertype'] = 'auth: ldap user_create() støtter ikke valgte brukertype: $a (...ennå)';
$string['auth_ldap_update_userinfo'] = 'Oppdater brukerinfo (fornavn, etternavn, adresse...) fra LDAP til Moodle. Se /auth/ldap/attr_mappings.php for informasjon';
$string['auth_ldap_user_attribute'] = 'Atributten for å navngi og søke etter brukere (vanligvis \'cn\').';
$string['auth_ldap_user_attribute_key'] = 'Brukeregenskap';
$string['auth_ldap_user_exists'] = 'LDAP brukernavn eksisterer allerede';
$string['auth_ldap_user_settings'] = 'Innstillinger for brukeroppslag';
$string['auth_ldap_user_type'] = 'Velg hvordan brukere lagres i LDAP. Denne innstilingen angir også hvordan, passordutløp, pålogging ved utløpt passord og brukeropprettelse virker.';
$string['auth_ldap_user_type_key'] = 'Brukertype';
$string['auth_ldap_usertypeundefined'] = 'config.user_type er ikke definert eller funksjonen ldap_expirationtime2unix støtter ikke valgt type!';
$string['auth_ldap_usertypeundefined2'] = 'config.user_type er ikke definert eller funksjonen ldap_unixi2expirationtime støtter ikke valgte type.';
$string['auth_ldap_version'] = 'Versjonen av LDAP-protokoll serveren din bruker.';
$string['auth_ldap_version_key'] = 'Versjon';
$string['auth_ldapdescription'] = 'Denne metoden krever godkjenning opp mot en ekstern LDAP-server. Hvis det gitte brukernavnet/passordet er gyldig oppretter Moodle en ny bruger i databasen. Denne modulen kan lese brugerinfo fra LDAP og forhåndsutfylle ønskede felter i Moodle. For senere innlogging blir kun brukernavn og passord kontrollert.';
$string['auth_ldapextrafields'] = 'Disse feltene er valgfrie.  Du kan velge å forhåndsutfylle noen brukerfelter i Moodle på forhånd fra <b>LDAP-felterne</b> som du spesifiserer her. <p>Hvis du ikke skriver noe her, vil det ikke overføres noe fra LDAP og standardene i Moodle vil bli brukt i stedet.<p>Uansett vil brukeren være i stand til å endre disse feltene etter at de har logget inn.';
$string['auth_ldapnotinstalled'] = 'Kan ikke bruke LDAP autentisering. PHP LDAP modulen er ikke installert.';
$string['auth_ldaptitle'] = 'Bruk en LDAP-server';
$string['auth_ntlmsso'] = 'NTLM SSO';
$string['auth_ntlmsso_enabled'] = 'Sett til ja for å forsøke Single Sign On på NTLM domene. <strong>Merk:</strong> dette krever tilleggsinnstillinger på webserveren for å virke, se <a href=\"http://docs.moodle.org/en/NTLM_authentication\">http://docs.moodle.org/en/NTLM_authentication</a>';
$string['auth_ntlmsso_enabled_key'] = 'Slå på';
$string['auth_ntlmsso_ie_fastpath'] = 'Settes til JA for å aktivere NTLM SSO snarvei som går utenom noen trinn og BARE virker med MS Internet Explorer';
$string['auth_ntlmsso_ie_fastpath_key'] = 'MS IE snarvei?';
$string['auth_ntlmsso_subnet'] = 'Hvis påslått, vil en bare forsøke SSO med klienter i dette subnettet. Format xxx.xxx.xxx.xxx/bitmaske';
$string['auth_ntlmsso_subnet_key'] = 'Subnet';
$string['ntlmsso_attempting'] = 'Forsøker Singel Sign on via NTLM...';
$string['ntlmsso_failed'] = 'Auto-login feilet, prøver vanlig loginside.';
$string['ntlmsso_isdisabled'] = 'NTLM SSO er slått av.';