<?PHP // $Id$ 
      // certificate.php - created with Moodle 1.7.1+ (2006101010)


$string['alert1'] = 'Denne prosedyren genererer et kursbevis. Etter første utskrift kan du ikke endre kursbeviset, selv om du laster ned flere ganger. Innhold som karakter, navn og dato vil bli låst. Dersom du har tenkt å forbedre resultatene dine, må du gjøre det før du fortsetter.';
$string['alert2'] = 'Når du skriver ut dette kursbeviset blir du også utmeldt fra kurset. Utskrift av kursbevis bør derfor være den absolutt siste handlingen i kurset før du forlater det.';
$string['attention'] = 'ADVARSEL';
$string['awarded'] = 'Belønnet';
$string['back'] = 'Tilbake';
$string['backbutton'] = 'Tilbake';
$string['border'] = 'Bord';
$string['borderblack'] = 'Svart';
$string['borderblue'] = 'Blå';
$string['borderbrown'] = 'Brun';
$string['bordercolor'] = 'Bord-farge';
$string['bordergreen'] = 'Grønn';
$string['borderlines'] = 'Linjer';
$string['bordernone'] = 'Ingen bord';
$string['borderstyle'] = 'Bordstil';
$string['cert'] = '#';
$string['certificate'] = 'Verifisering av kursbevis kode:';
$string['certificate:manage'] = 'Administrer kursbevis';
$string['certificate:student'] = 'Skriv ut kursbevis';
$string['certificate:teacher'] = 'Før opp lærer';
$string['certificate:view'] = 'Vis kursbevis';
$string['certificatetype'] = 'Type kursbevis';
$string['code'] = 'Kode';
$string['condeactivationa'] = 'Aktiviser';
$string['condeactivationd'] = 'Koble ut';
$string['conditional'] = 'Grunnlag for karakter';
$string['configcontent'] = 'Konfigurer innhold';
$string['course'] = 'For';
$string['courseenddate'] = 'Kursets slutt-dato (må settes i Innstillinger for kurset!)';
$string['coursegrade'] = 'Kurskarakter';
$string['credithours'] = 'Omfang i timer';
$string['date'] = 'Den';
$string['dateformat'] = 'Datoformat';
$string['datehelp'] = 'Dato';
$string['deliver'] = 'Levering';
$string['dontallowall'] = 'Ikke tillat alle';
$string['download'] = 'Last ned';
$string['emailcertificate'] = 'E-post (Må også velge Lagre!)';
$string['emailstudenttext'] = 'Vedlagt følger ditt kursbevis for $a->course.';
$string['emailteachermail'] = '$a->student har mottatt kursbevis: \'$a->certificate\'
for $a->course.';
$string['emailteachermailhtml'] = '$a->student har mottatt kursbevis: \'<i>$a->certificate</i>\'
for $a->course.

Du kan vise kursbeviset her:
<a href=\"$a->url\">Kursbevis rapport</a>.';
$string['emailteachers'] = 'Send e-post til lærere';
$string['format'] = 'FORMAT';
$string['getcertificate'] = 'Vis ditt kursbevis';
$string['grade'] = 'Karakter';
$string['gradeformat'] = 'Karakterskala';
$string['gradeletter'] = 'Bokstav karakter';
$string['gradepercent'] = 'Prosent karakter';
$string['gradepoints'] = 'Poeng karakter';
$string['gradesettings'] = 'KARAKTER INNSTILLINGER';
$string['gsettings'] = 'INNSTILLINGER';
$string['hours'] = 'timer';
$string['introlandscape'] = 'Dette kursbeviset bekrefter at';
$string['introletterlandscape'] = 'Dette kursbeviset bekrefter at';
$string['introletterportrait'] = 'Dette kursbeviset bekrefter at';
$string['introportrait'] = 'Dette kursbeviset bekrefter at';
$string['issued'] = 'Tildelt';
$string['modulename'] = 'Kursbevis';
$string['modulenameplural'] = 'Kursbevis';
$string['nogrades'] = 'Ingen karakterer foreligger';
$string['notfound'] = 'Kursbevisets nummer kunne ikke valideres.';
$string['notissued'] = 'Ikke tildelt';
$string['notissuedyet'] = 'Ikke tildelt ennå';
$string['notpossible'] = 'Karakteren din i dette kurset er for lav for å få dette kursbeviset. </br> For å få dette kursbeviset trenger du:';
$string['notreceived'] = 'Du har ikke mottatt dette kursbeviset tidligere';
$string['on'] = 'på';
$string['ondayportrait'] = 'på dagen';
$string['openbrowser'] = 'Åpne i nytt vindu';
$string['opendownload'] = 'Klikk på knappen under for å lagre kursbeviset på din egen pc.';
$string['openemail'] = 'Når du klikker på knappen under vil kursbeviset bli sendt deg som e-postvedlegg.';
$string['openwindow'] = 'Klikk på knappen under for å vise kursbeviset i et nytt vindu.';
$string['printcode'] = 'Skriv ut med kode';
$string['printcredithours'] = 'Skriv ut med omfang i timer';
$string['printdate'] = 'Skriv ut med dato';
$string['printgrade'] = 'Skriv ut med karakter';
$string['printseal'] = 'Skriv ut med segl';
$string['printsignature'] = 'Skriv ut med signatur';
$string['printteacher'] = 'Skriv ut med lærer';
$string['printwmark'] = 'Skriv ut med vannmerke';
$string['receivedcerts'] = 'Mottatte kursbevis';
$string['receiveddate'] = 'Dato mottatt';
$string['referencegrade'] = 'Karakterskala som skal brukes';
$string['report'] = 'Rapport';
$string['reviewcertificate'] = 'Vis kursbeviset';
$string['savecertificate'] = 'Lagre kursbeviset';
$string['sigline'] = 'signaturstrek';
$string['statementlandscape'] = 'har fullført kurset';
$string['statementletterlandscape'] = 'har fullført kurset';
$string['statementletterportrait'] = 'har fullført kurset';
$string['statementportrait'] = 'har fullført kurset';
$string['titlelandscape'] = 'KURSBEVIS';
$string['titleletterlandscape'] = 'KURSBEVIS';
$string['titleletterportrait'] = 'KURSBEVIS';
$string['titleportrait'] = 'KURSBEVIS';
$string['to'] = 'Tildelt';
$string['typelandscape'] = 'Liggende';
$string['typeletter_landscape'] = 'Liggende (Letter)';
$string['typeletter_portrait'] = 'Stående (Letter)';
$string['typeportrait'] = 'Stående';
$string['typeunicode_landscape'] = 'Unicode (Liggende)';
$string['unenrol'] = 'Meld ut av kurset';
$string['validate'] = 'Verifiser';
$string['verifycertificate'] = 'Verifiser kursbevis';
$string['viewcertificateviews'] = 'Vis $a tildelte kursbevis';
$string['viewed'] = 'Du mottok dette kursbeviset:';

?>
