<?PHP // $Id$ 
      // auth.php - created with Moodle 1.6.2+ (2006050521)


$string['alternatelogin'] = 'Ki te tāuruhia he URL ki konei, ka whakamahia hei whārangi takiuru mō tēnei pae.  Me whiwhi e te whārangi he puka kua whakatautuhia te āhuatanga mahi ki te <strong>\'$a\'</strong> me ngā āpure whakahoki <strong>ingoakaiwhakamahi</strong> me te <strong>kupuhipa</strong>.<br/>Kaua e hapa te takoto o te URL, kei rakaina koe ki waho o tēnei pae.<br />';
$string['alternateloginurl'] = 'URL takiuru atu anō.';
$string['auth_cas_baseuri'] = 'URI o te tūmau (mēnā karekau he baseUri)<br />Hei tauira, mēnā ka urupare te tūmau CAS ki host.domaine.fr/CAS/ ka puta ko<br/>cas_baseuri = CAS/';
$string['auth_cas_create_user'] = 'Whakakāngia tēnei mēnā e pīrangi ana koe kia kōkuhuna ki roto i te pātengi raraunga o Moodle he kaiwhakamahi kua whakamotuhēhēhia ki-te-CAS.  Ki te kore, ko ngā kaiwhakamahi onāianei o Moodle anake ka āhei ki takiuru.';
$string['auth_cas_enabled'] = 'Whakakāngia tēnei mō te whakamahi i te whakamotuhēhēnga CAS.';
$string['auth_cas_hostname'] = 'Ingoahautū o te tūmau CAS <br />hei tauira: host.domain.fr';
$string['auth_cas_invalidcaslogin'] = 'Kua rahua tō takiurunga - kāore i taea koe te whakamotuhēhē.';
$string['auth_cas_language'] = 'Reo kua tīpakohia';
$string['auth_cas_logincas'] = 'Āheinga uru tūhononga haumaru';
$string['auth_cas_port'] = 'Tauranga o te tūmau CAS';
$string['auth_cas_server_settings'] = 'Whirihorahanga o te tūmau CAS';
$string['auth_cas_text'] = 'Tūhononga Haumaru';
$string['auth_cas_version'] = 'Putanga o CAS';
$string['auth_casdescription'] = 'Whakamahia ai i tēnei aratuka he tūmau CAS (Central Authentication Service - Ratonga Whakamotuhēhēnga Pūwaenga) hei whakamotuhēhē i ngā kaiwhakamahi mā roto i tētahi āhuatanga SSO (single sign on - takiuru kotahi). Ka taea hoki he whakamotuhēhēnga LDAP ngāwari te whakamahi.  Mēnā, e ai ki te CAS, he whaimana te ingoakaiwhakamahi me te kupuhipa, ka hangā e Moodle tētahi kaiwhakamahi hōu i roto i tana pātengi raraunga, me te tango anō hoki i ngā huanga mēnā e hiahiatia ana. Mō ngā takiurunga o muri ka takina ko te ingoakaiwhakamahi me te kupuhipa anake.';
$string['auth_castitle'] = 'Whakamahia tētahi tūmau CAS (SSO)';
$string['auth_changepasswordhelp'] = 'Āwhina huri kupuhipa';
$string['auth_changepasswordhelp_expl'] = 'Whakaatu i te āwhina huri kupuhipa ki ngā kaiwhakmahi kua ngaro tō rātou kupuhipa $a. Ka whakaaturia tēnei me te/hei <strong>Change Password URL</strong>, hei huringa kupuhipa ō roto Moodle rānei.';
$string['auth_changepasswordurl'] = 'URL huri kupuhipa';
$string['auth_changepasswordurl_expl'] = 'Whakaritea te url hei tuku ki ngā kaiwhakamahi kua ngaro tō rātou kupuhipa $a. Tautuhi te <strong>Use standard Change Password page</strong> hei <strong>No</strong>.';
$string['auth_common_settings'] = 'Ngā Tautuhinga Pūnoa';
$string['auth_data_mapping'] = 'Whakamahere RaurangaWhakamahia ai i tēnei aratuka he ripanga pātengi raraunga ā-waho kia taki ai mēnā he whaimana tētahi ingoakaiwhakamahi me te kupuhipa.  Mēnā he pūkete hōu, ka tāruatia mai pea he mōhiohio mai ētahi atu āpure ki Moodle.';
$string['auth_dbdescription'] = 'Whakamahia ai i tēnei aratuka he ripanga pātengi raraunga ā-waho kia taki ai mēnā he whaimana tētahi ingoakaiwhakamahi me te kupuhipa.  Mēnā he pūkete hōu, ka tāruatia mai pea he mōhiohio mai ētahi atu āpure ki Moodle.';
$string['auth_dbextrafields'] = 'He kōwhiringa noa iho ēnei āpure. Ka taea e koe ētahi āpure kaiwhakamahi o Moodle te whakakī-i-mua ki ngā mōhiohio mai i <b>ngā āpure pātengi raraunga ā-waho</b> e whakapūtāhia nei e koe. <p>Mēnā ka waiho ēnei kia pātea tonu, ka whakamaiha ngā taunoa.</p><p>Ahakoa he aha, ka taea e te kaiwhakamahi ngā āpure katoa nei te whakarerekē mō muri i te takiurunga mai.</p>';
$string['auth_dbfieldpass'] = 'Ingoa o te āpure kei roto ko ngā kupuhipa';
$string['auth_dbfielduser'] = 'Ingoa o te āpure kei roto ko ngā ingoakaiwhakamahi';
$string['auth_dbhost'] = 'Ko te rorohiko e hautū ana i te tūmau pātengi raraunga';
$string['auth_dbname'] = 'Ingoa o te pātengi raraunga anō';
$string['auth_dbpass'] = 'Kupuhipa e hāngai ana ki te ingoa o runga ake nei';
$string['auth_dbpasstype'] = 'Whakapātāhia te hōputu e whakamahia nei e te āpure kupuhipa.  He pai te wetemunatanga MD5 hei tūhono atu ki ētahi atu taupānga tukutuku noa, pēnei ake i te PostNuke';
$string['auth_dbtable'] = 'Ingoa o te ripanga i roto i te pātengi raraunga';
$string['auth_dbtitle'] = 'Whakamahia he pātengi raraunga ā-waho';
$string['auth_dbtype'] = 'Ko te momo pātengi raraunga (tirohia te <a href=\"../lib/adodb/readme.htm#drivers\">puka ADOdb</a> mō ngā taipitopito)';
$string['auth_dbuser'] = 'Ingokaiwhakamahi e whiwhi ana i te āheinga uru ki te pātengi raraunga';
$string['auth_emaildescription'] = 'Ko te aratuka whakamotuhēhē taunoa ko te whakaūtanga īmēra. Inā waitohua mai e te kaiwhakamahi me tana kōwhiri i tōna ake ingoakaiwhakamahi/kupuhipa hōu, ka tukuna atu he īmēra whakaū ki tana wāhitau īmēra. Kei roto i tēnei īmēra he hononga haumaru ki tētahi whārangi e taea ai e ia tana pūkete te whakaū.  Ko ngā takiurunga o muri mai, he taki kau noa i te ingoa/kupuhipa e purutia ana i a Moodle.';
$string['auth_emailtitle'] = 'Whakamotuhēhēnga ā-Īmēra';
$string['auth_fccreators'] = 'Rārangi o ngā rōpū e āhei ana ana mema ki te waihanga pū akoranga hōu. Whakawehea ngā rōpū-maha ki te \';\'. Me ōrite pū ngā ingoa ki tā te tūmau FirstClass.  He mea pū tairongo tēnei.';
$string['auth_fcdescription'] = 'Whakamahia ai i tēnei aratuka tētahi tūmai FirstClass hei taki mēnā he whaimana tētahi ingoakaiwhakamahi/kupuhipa';
$string['auth_fcfppport'] = 'Tauranga Tūmau (ko te mea tino auau te 3333)';
$string['auth_fchost'] = 'Ko te wāhitau tūmau FirstClass. Whakamahia te tau IP, te ingoa DNS rānei.';
$string['auth_fcpasswd'] = 'Kupuhipa mō te pūkete o runga ake nei.';
$string['auth_fctitle'] = 'Whakamahia he tūmau FirstClass';
$string['auth_fcuserid'] = 'Ko te idkaiwhakamahi mō te pūkete FirstClass me te mana \'teina-kaiwhakahaere\'\'';
$string['auth_fieldlock'] = 'Uara Maukati';
$string['auth_fieldlock_expl'] = '<p><b>Uara Maukati:</b> Ki te whakahohe, ka kaupare i ngā whakarerekētanga tōtika a ngā kaiwhakamahi/haere o Moodle ki tēnei āpura. Whakamahia tēnei kōwhiringa mēnā e tiaki ana koe i tēnei raraunga i roto i te pūnaha whakamotuhēhē ā-waho.</p>';
$string['auth_fieldlocks'] = 'Maukati Ngā Āpure Kaiwhakamahi';
$string['auth_fieldlocks_help'] = '<p> Ka taea ngā āpure kaiwhakamahi te maukati. He pai tēnei mō ngā pae ka taurima ā-ringahia te raraunga kaiwhakamahi e ngā kaiwhakahaere mā  te whakarerekē i ngā rīkoata kaiwhakamahi, mā te tukuake rānei ki te pūmahinga \'Tukuake Ngā Kaiwhakamahi\'. Mēnā e maukati ana ngā āpure e hiahiatia ana e Moodle, me tuku tonu taua raraunga inā hangā ana ngā pūkete kaiwhakamahi &emdash; ki moumou noa ngā pūkete.</p><p>Ko te whakatautuhi i te aratau maukati ki te \'Kua wetemaukati inā pātea\' te rongoā mō tēnei raru.</p>';
$string['auth_imapdescription'] = 'Whakamahia ai i tēnei aratuka he tūmau IMAP hei taki mēnā he whaimana tētahi kaiwhakamahi/kupuhipa';
$string['auth_imaphost'] = 'Ko te wāhitau tūmau IMAP. Whakamahia te tau IP, kaua ko te ingoa DNS.';
$string['auth_imapport'] = 'Tau tauranga tūmau IMAP.  143, 993 i te nuinga o te wā.';
$string['auth_imaptitle'] = 'Whakamahia he tūmau IMAP';
$string['auth_imaptype'] = 'Ko te momo tūmau IMAP. He maha ngā momo whakamotuhēhēnga, whakawhitinga o ngā tūmau IMAP.';
$string['auth_ldap_bind_dn'] = 'Mēnā e pīrangi ana koe ki te whakamahi i te bind-user ki te rapu i ngā kaiwhakamahi, whakapūtāhia ki konei.  Hei tauira \'cn=ldapuser,ou=public,o=org\'';
$string['auth_ldap_bind_pw'] = 'Kupuhipa mō te bind-user';
$string['auth_ldap_bind_settings'] = 'Ngā tautuhinga Bind';
$string['auth_ldap_contexts'] = 'Rārangi o ngā horopaki e nōhia ana e ngā kaiwhakamahi.  Whakawehea ngā horopaki ki te \';\'. Hei tauira \'ou=users,o=org; ou=others,o=org\'';
$string['auth_ldap_create_context'] = 'Ki te whakahohea e koe te waihanga kaiwhakamahi mā te īmēra whakaū, whakapūtāhia te horopaki e hanga nei ngā kaiwhakamahi.  Me rerekē hoki tēnei horopaki i ētahi atu kaiwhakamahi kia noho haumaru tonu ai.  Kāore he take o te tāpiri i tēnei horopaki ki ldap_context-variable, te take, ka rapu aunoa a Moodle i ngā kaiwhakamahi i ahu mai i tēnei horopaki.<br /><b>Kia mōhio mai!</b> Me whakakē te pūmahinga auth_user_create() i roto i te kōnae auth/ldap/lib.php kia oti tika ai te waihanga kaiwhakamahi';
$string['auth_ldap_creators'] = 'Rārangi o ngā rōpū e āhei ana āna mema ki te waihanga i ngā pū akoranga hōu. Whakawehea ngā rōpū-maha ki te \';\'. Hei tauira \'cn=teachers,ou=staff,o=myorg\'';
$string['auth_ldap_expiration_desc'] = 'Tīpakohia Tau kia mono ai i te Takinga o ngā kupuhipa kua pau, i te LDAP rānei kia taea te wā pau kupuhipa te pānui tōtika mai i te LDAP';
$string['auth_ldap_expiration_warning_desc'] = 'Tau o ngā rangi mō mua i te tukunga o te whakatupatoranga mō te paunga o te wā kupuhipa.';
$string['auth_ldap_expireattr_desc'] = 'Kōwhiringa Noa: turakina ai te huanga-LDAP e pupuru ana i ngā wā paunga kupuhipa. passwordExpirationTime';
$string['auth_ldap_graceattr_desc'] = 'Kōwhiringa Noa: Turakinga huanga takiurukerēhi';
$string['auth_ldap_gracelogins_desc'] = 'Whakahohe tautoko LDAP takiurukerēhi.  A muri ake i te paunga o te kupuhipa ka taea tonu e te kaiwhakamahi te takiuru kia 0 te tatau takiurukerēhi.  Ki te whakahohea tēnei tautuhinga, ka whakaaturia te karere takiuru kerēhi inā pau te wā kupuhipa.';
$string['auth_ldap_host_url'] = 'Whakapūtāhia te kaihautū LDAP i roto i te hanga-URL pēnei ake i te \'ldap://ldap.myorg.com/\', \'ldaps://ldap.myorg.com/\' rānei.  Whakawehea ngā tūmau-maha ki te \';\' kia whiwhi ai ki te tautoko hinga.';
$string['auth_ldap_login_settings'] = 'Ngā Tautuhinga Takiuru';
$string['auth_ldap_memberattribute'] = 'Kōwhiringa Noa: Turakina ai te huanga mema kaiwhakamahi, inā kei roto te kaiwhakamahi i tētahi rōpū.  Ko \'Mema\' i te nuinga o te wā.';
$string['auth_ldap_objectclass'] = 'Kōwhiringa Noa: Turakina ai te tūemiTūmomo e whakamahia ana ki te rapu/whakaingoa i ngā kaiwhakamahi i runga i ldap_user_type.  I te nuinga o te wā kāore he take o te whakarerekē i tēnei.';
$string['auth_ldap_opt_deref'] = 'Whakaritea te whakahaeretanga o ngā ingoakē i te rapunga.  Tīpakohia tētahi o ngā uara e whai ake nei: \"Kāo\" (LDAP_DEREF_NEVER) or \"Āe\" (LDAP_DEREF_ALWAYS)';
$string['auth_ldap_passwdexpire_settings'] = 'Ngā Tautuhinga Paunga Kupuhipa LDAP';
$string['auth_ldap_preventpassindb'] = 'Tīpakohia Āe kia kore ai ngā kupuhipa e pupurutia i roto i te PR o Moodle.';
$string['auth_ldap_search_sub'] = 'Rapua ngā kaiwhakamahi mai i ngā horopakiroto';
$string['auth_ldap_server_settings'] = 'Ngā Tautuhinga Tūmau LDAP';
$string['auth_ldap_update_userinfo'] = 'Whakahōungia te mōhiohio kaiwhakamahi (ingoatuatahi, ingoawhānau, wāhitau..) mai i a LDAP ki Moodle. Whakapātāhia ngā tautuhinga \"Whakamahere raraunga\" inā hiahiatia ana.';
$string['auth_ldap_user_attribute'] = 'Kōwhiringa Noa: Turakina ai te huanga e whakaingoa/rapu ana i ngā kaiwhakamahi. Ko \'cn\' i te nuinga o te wā.';
$string['auth_ldap_user_settings'] = 'Ngā Tautuhinga Rapu Kaiwhakamahi';
$string['auth_ldap_user_type'] = 'Tīpakohia te momo penapena o ngā kaiwhakamahi ki roto i a LDAP.  Whakapūtāhia ai hoki e tēnei tautuhinga te mahinga o te paunga takiurunga, ngā takiurunga kerēhi, me te waihanga kaiwhakamahi.';
$string['auth_ldap_version'] = 'Ko te putanga o te kawa LDAP e whakamahia nei e tō tūmau.';
$string['auth_ldapdescription'] = 'Ko tā tēnei aratuka he whakamotuhēhē ki tētahi tūmau LDAP ā-waho.<br> Mēnā he whaimana te ingoakaiwhakamahi/kupuhipa, ka waihangatia e Moodle tētahi tāurunga kaiwhakamahi hōu i roto i tana pētangi raraunga.  Ka taea e tēnei kōwae ngā huanga kaiwhakamahi te pānui mai i ngā LDAP me ngā āpure whakakī-ā-mua e hiahiatia ana i roto i a Moodle.';
$string['auth_ldapextrafields'] = 'He kōwhiringa noa iho ēnei āpure. Ka taea e koe ētahi āpure kaiwhakamahi o Moodle te whakakī-ā-mua ki ngā mōhiohio mai i <b>Ngā āpure LDAPs</b> e whakapūtāhia nei e koe. <p>Ki te waiho ēnei kia pātea tonu, kāore tētahi mea e whakawhitihia mai i LDAP, ā, ka whakamahi kētia ngā taunoa o Moodle.</p><p>Ahakoa, ka taea tonu e te kaiwhakamahi ēnei āpure katoa te whakarerekē a mrui i te takiurunga.</p>';
$string['auth_ldaptitle'] = 'Whakamahia he tūmau LDAP';
$string['auth_manualdescription'] = 'I tēnei aratuka kāore e taea e ngā kaiwhakamahi ā rātou pūkete ake te waihanga. Me waihanga ā-ringa katoa ngā pūkete e te kaiwhakahaere.';
$string['auth_manualtitle'] = 'Ngā pūkete ā-ringa anake';
$string['auth_multiplehosts'] = 'Ka taea ngā Kaihautū-maha, ngā wāhitau-maha RĀNEI te whakapūtā (eg kaihautū1.com;kaihautū2.com;kaihautū3.com) or (eg xxx.xxx.xxx.xxx;xxx.xxx.xxx.xxx)';
$string['auth_nntpdescription'] = 'Whakamahia ai i tēnei aratuka he tūmau NNTP hei taki mēnā he whaimana tētahi ingoakaiwhakamahi/kupuhipa.';
$string['auth_nntphost'] = 'Ko te wāhitau tūmau NNTP.  Whakamahia te tau IP, kaua ko te ingoa DNS.';
$string['auth_nntpport'] = 'Tauranga tūmau (ko te 119 te mea tino auau)';
$string['auth_nntptitle'] = 'Whakamahia he tūmau NNTP';
$string['auth_nonedescription'] = 'Ka taea e ngā kaiwhakamahi te waitohu mai me te waihanga tonu atu i ngā pūkete whaimana, kāore e whakamotuhēhēngia ki te tūmau ā-waho, kāore hoki e tukuna he īmēra whakaū.  Kia tūpato koe inā whakamahi ana i tēnei kōwhiringa - ka puta mai pea ngā raru haumaru me ngā raru whakahaere.';
$string['auth_nonetitle'] = 'Karekau he whakamotuhēhēnga';
$string['auth_pamdescription'] = 'Whakamahia ai i tēnei aratuka a PAM hei uru atu ki ngā ingoakaiwhakamahi taketake o tēnei tūmau.  Me tāuta te <a href=\"http://www.math.ohio-state.edu/~ccunning/pam_auth/\" target=\"_blank\">Whakamotuhēhēnga PHP4 PAM</a> kia taea e koe tēnei kōwae te whakamahi.';
$string['auth_pamtitle'] = 'PAM (Pluggable Authentication Modules - Ngā Kōwae Whakamotuhēhē Puruāhei )';
$string['auth_passwordisexpired'] = 'Kua pau te wā ki tō kupuhipa. Me huri ināianei?';
$string['auth_passwordwillexpire'] = 'Ka pau te wā ki tō kupuhipa i ngā rangi e $a. Me huri ināianei?';
$string['auth_pop3description'] = 'Whakamahia ai i tēnei aratuka he tūmau POP3 hei taki mēnā he whaimana tētahi kaiwhakamahi/kupuhipa.';
$string['auth_pop3host'] = 'Ko te wāhitau tūmau POP3. Whakamahia te tau IP, kaua ko te ingoa DNS.';
$string['auth_pop3mailbox'] = 'Ingoa o te pouaka mēra hei whakahonoa atu. (POUAKAROTO i te nuinga o te wā)';
$string['auth_pop3port'] = 'Tauranga tūmau (110 te mea tino auau, he auau hokiu te 995 mō te SSL)';
$string['auth_pop3title'] = 'Whakamahia he tūmau POP3';
$string['auth_pop3type'] = 'Momo tūmau. Mēnā e whakamahia ana e tō tūmau he haumaru ā-tīwhikete, kōwhirihia a pop3cert.';
$string['auth_radiusdescription'] = 'Ka whakamahi tēnei tuka i te tūmau <a href=\"http://en.wikipedia.org/wiki/RADIUS\" target=\"_blank\">RADIUS</a> hei taki mēnā he tika te ingoa kaiwhakamahi me te kupuhipa.';
$string['auth_radiushost'] = 'Wāhitau o te tūmau RADIUS';
$string['auth_radiusnasport'] = 'Tauranga hei whakamahi ki te hono';
$string['auth_radiussecret'] = 'Kupu huna tiri';
$string['auth_radiustitle'] = 'Whakamahi tūmau RADIUS';
$string['auth_shib_convert_data'] = 'API Whakakē Raraunga';
$string['auth_shib_convert_data_description'] = 'Ka taea e koe tēnei API te whakakē tonu ake i te raraunga i homai e Shibboleth. Pānuitia te <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">PĀNUIMAI</a> mō ētahi tohutohu atu anō.';
$string['auth_shib_convert_data_warning'] = 'Kāore te kōnae i te tīariari, kāore e taea rānei te pānui i roto i te tukanga tūmautukutuku!';
$string['auth_shib_instructions'] = 'whakamahia te <a href=\"$a\">Takiuru Shibboleth</a> kia uru mā te Shibboleth, mēnā ka tautokona e tō Wānanga.<br />Ki te kore, wjhakamahia te puka takiuru noa i konei.';
$string['auth_shib_instructions_help'] = 'I konei, me whakatakoto ngā tohutohu ritenga motuhake hei whakamārama i a Shibboleth ki ō kaiwhakamahi. Na, ka whakaaturia ēnei ki te whārangi takiuru, ki te wāhanga tohutohu. Me tāpiri hoki he hononga ki tētahi rauemi parea-ki-te-Shibboleth e tahuri kē ana i ngā kaiwhakamahi Shibboleth ki \"<b>$a</b>\" kia taea ai e rātou te takiuru ki a Moodle. Ki te waiho kia pātea tonu, ka whakamahia ngā tohutohu paerewa kē (tē hāngai pū ki a Shibboleth)';
$string['auth_shib_only'] = 'Shibboleth Anake';
$string['auth_shib_only_description'] = 'Takina tēnei kōwhiringa mēnā ka whakahautia he whakamotuhēhēnga Shibboleth.';
$string['auth_shib_username_description'] = 'Ingoa o te tāupe taiao Shibboleth o te tūmautukutuku e whakamahia ai hei ingoakaiwhakamahi o Moodle.';
$string['auth_shibboleth_login'] = 'Takiuru Shibboleth';
$string['auth_shibboleth_manual_login'] = 'Takiuru ā-Ringa';
$string['auth_shibbolethdescription'] = 'I tēnei aratuka, ka waihangatia, ā, ka whakamotuhēhētia ai ngā kaiwhakamahi mā <a href=\"http://shibboleth.internet2.edu/\" target=\"_blank\">Shibboleth</a>.<br>Me matua pānui  href=\"../auth/shibboleth/README.txt\" target=\"_blank\">README</a> for Shibboleth on how to set up your Moodle with Shibboleth';
$string['auth_shibbolethtitle'] = 'Shibboleth';
$string['auth_updatelocal'] = 'Whakahōu Paetata';
$string['auth_updatelocal_expl'] = '<p><b>Whakahōu Paetata:</b> Ki te whakahohea, ka whakahōungia te āpure (mai i te whakamotuhēhē ā-waho) i ia takiurunga, hototahitanga rānei  a te kaiwhakamahi. Me maukati ngā āpure kua whakatautuhia ki te whakahōu paetata ake.</p>';
$string['auth_updateremote'] = 'Whakahōu Tōwaho';
$string['auth_updateremote_expl'] = '<p><b>Whakahōu Tōwaho:</b> Ki te whakahohea, ka whakahōungia te whakamotuhēhē ā-waho i te whakahōunga o te pūranga kaiwhakamahi. Me wetemaukati ngā āpure kia taea te whakarerekē.</p>';
$string['auth_updateremote_ldap'] = '<p><b>Kia mōhio mai:</b> Mō mua i te whakahōunga raraunga LDAP ā-waho me whakatautuhi te binddn me te bindpw ki te bind-user me te mana hei whakarerekē i ngā pūranga kaiwhakamahi katoa. I tēnei wā, kāore e tiakina ngā huanga uara-maha, ā, ka tango i ētahi uara atu anō i te whakahōunga.</p>';
$string['auth_user_create'] = 'Whakaahei Waihanga Kaiwhakamahi';
$string['auth_user_creation'] = 'Ka taea te waihanga e ngā kaiwhakamahi hōu (ingoakore) he pūkete kaiwhakamahi i runga i pūtaki whakamotuhēhē ā-waho, ka whakaūngia mā te īmēra.  Ki te whakahohe koe i tēnei, kaua e wareware ki te whirihora ngā kōwhiringa hāngai-ki-te-kōwae mō te waihanga kaiwhakamahi.';
$string['auth_usernameexists'] = 'Kua riro kē tēnā ingoa i tētahi.  Kōwhirihia he ingoa hōu anō.';
$string['authenticationoptions'] = 'Ngā Kōwhiringa Whakamotuhēhēnga';
$string['authinstructions'] = 'Hei konei whakatakotohia ai e koe he tohutohu ki ngā kaiwhakamahi, kia mōhiotia ai ko tēhea tō rātou ingoakaiwhakamahi/kupuhipa. Ka puta te kuputuhi ka patohia ki konei i te whārangi takiuru. Ki te waiho tēnei kia pātea tonu, ka kore ngā tohutohu e puta.';
$string['changepassword'] = 'Huri URL Kupuhipa';
$string['changepasswordhelp'] = 'Hei konei taea ai tētahi wāhitau te pato hei huri, hei kimi anō rānei i ngā ingoakaiwhakamahi/kupuhipa i wareware. Ka puta tēnei hei pātene ki te whārangi takiuru, ki te whārangi kaiwhakamahi hoki. Ki te waiho tēnei kia pātea tonu, ka kore taua pātene e puta.';
$string['chooseauthmethod'] = 'Kōwhirihia he aratuka whakamotuhēhē';
$string['createpasswordifneeded'] = 'Waihanga kupuhipa ki te hiahia';
$string['forcechangepassword'] = 'Whakahautia te huringa kupuhipa';
$string['forcechangepassword_help'] = 'Whakahautia ngā kaiwhakamahi kia huri ai i ō rātou kupuhipa a te takiurunga tōmuri ki Moodle.';
$string['forcechangepasswordfirst_help'] = 'Whakahautia ngā kaiwhakamahi kia huri ai i ō rātou kupuhipa a te takiurunga tuatahi ki Moodle.';
$string['guestloginbutton'] = 'Pātene Takiuru ā-Manuwhiri';
$string['infilefield'] = 'E hiahiatia ana te āpure i roto i te kōnae';
$string['instructions'] = 'Ngā Tohutohu';
$string['internal'] = 'Ā-roto';
$string['locked'] = 'Kua Maukati';
$string['md5'] = 'Whakamunatanga MD5';
$string['passwordhandling'] = 'Whakahaeretanga o te āpure kupuhipa';
$string['plaintext'] = 'Kuputuhi Tōkau';
$string['shib_no_attributes_error'] = 'Te āhua kua kua whakamotuhēhē ā Shibboleth koe, ēngari kāore te Moodle i whiwhi i ētahi huanga kaiwhakamahi. Taki koa ka tuku tō kaituku tangatatanga i ngā huanga e hiahiatia ana ki te Kaituku Tūmau e whakahaere ana i te Moodle, whakapā atu rānei ki te kaiwhakahaere tukutuku matua o tēnei tūmau.';
$string['shib_not_all_attributes_error'] = 'E hiahia ana te Moodle ētahi huanga Shibboleth kāore i roto i tō tairongo. Ko ngā huanga ko: $a<br />Whakapā atu koa ki te kaiwhakahaere tukutuku mata o tēnei tūmau, ki tō kaituku tangatatanga rānei.';
$string['shib_not_set_up_error'] = 'Te āhua nei kāore i tika te tautuhinga o te huangatanga Shibboleth i te mea kāore he tāupe taiao Shibboleth mō tēnei whārangi. Whakapā atu koa ki te <a href=\"README.txt\">README</a> mō ngā tohutohu anō kia mōhio me pēhea te tautuhi huangatanga Shibboleth, whakapā atu rānei ki te kaiwhakahaere tukutuku matua o tēne tāutatanga o Moodle.';
$string['showguestlogin'] = 'Ka taea e koe te pātene takiuru ā-manuwhiri, kei te whārangi takiuru, te huna, te hura rānei.';
$string['stdchangepassword'] = 'Whakamahia te whārangi huri kupuhipa paerewa';
$string['stdchangepassword_expl'] = 'Mēnā ka whakaaetia e te pūnaha whakamotuhēhēnga ā-waho ngā huringa i roto i a Moodle, hurihia tēnei kia \'Āe\'.  Ka turakina e tēnei tautuhinga \'Huri URL kupuhipa\'.';
$string['stdchangepassword_explldap'] = 'KIA MŌHIO MAI: Mēnā he mamao te tūmau LDAP, he pai ake te LDAP i te kauhanga SSL (ldaps://) kua whakamunahia.';
$string['unlocked'] = 'Kua wetemaukati';
$string['unlockedifempty'] = 'Kua wetemaukati inā pātea';
$string['update_never'] = 'E Kore Rawa';
$string['update_oncreate'] = 'hei te waihanganga';
$string['update_onlogin'] = 'hei ia takiurunga';
$string['update_onupdate'] = 'Hei te whakahōunga';

?>
