<?PHP // $Id$ 
      // message.php - created with Moodle 1.8.2+ (2007021520)


$string['addcontact'] = 'தொடர்பைச் சேர்க்க';
$string['addsomecontacts'] = 'To send a message to someone, or to add a shortcut for them on this page, use the <a href=\"$a\">search tab</a> above.';
$string['addsomecontactsincoming'] = 'These messages are from people who are not in your contact list. To add them to your contacts, click the \"Add contact\" icon next to their name.';
$string['ago'] = '$a க்கு முன்னர்';
$string['allmine'] = 'என்னிடமிருந்து அல்லது எனக்கான எல்லாச் செய்திகளும்';
$string['allstudents'] = 'பாடநெறியிலுள்ள மாணவர்களுக்கிடையிலான எல்லாச் செய்திகளும்';
$string['allusers'] = 'எல்லாப் பயனளரிடமுமுள்ள எல்லாச் செய்திகளும்';
$string['backupmessageshelp'] = 'If enabled, then instant messages will be included in SITE automated backups';
$string['beepnewmessage'] = 'புதிய செய்தி வந்ததும் பீப் செய்க. (ஓசைகளைக் கையாளக்கூடிய Quicktime போன்ற உலாவி உட்செருகல்கள் தேவைப்படலாம்)';
$string['blockcontact'] = 'தொடர்பைத் தடு';
$string['blockedmessages'] = 'தடுக்கப்பட்ட பயனாளரிடமிருந்து/பயனாளருக்கான $a செய்திகள்.';
$string['blocknoncontacts'] = 'எனது தொடர்புப் பட்டியலில் இல்லாத எவரிடமிருந்து வரும் செய்தியையும் தடுக்கவும்.';
$string['contactlistempty'] = 'உங்கள் தொடர்புப் பட்டியல் தற்சமயம் வெறுமையாக உள்ளது';
$string['contacts'] = 'தொடர்புகள்';
$string['context'] = 'context';
$string['deletemessagesdays'] = 'இத்தனை நாட்களின் பின்னர் பழைய செய்திகளைத் தானாக அழிக்கவும்.';
$string['discussion'] = 'கலந்துரையாடல்';
$string['emailmessages'] = 'இணைப்பிலா நிலையில் உள்ளபோது எனக்கு வரும் மின்னஞ்சல்கள்';
$string['emailtagline'] = 'இம்மின்னஞ்சல் \"$a\" இல் உங்களுக்கு அனுப்பப்பட்ட தகவலின் பிரதியாகும்.';
$string['emptysearchstring'] = 'நீங்கள் எதற்காவது தேட வேண்டும்';
$string['formorethan'] = 'For more than';
$string['includeblockedusers'] = 'தடுக்கப்பட்ட பயனாளரையும் சேர்க்க';
$string['incomingcontacts'] = 'உள்வரும் தொடர்புகள் ($a)';
$string['keywords'] = 'Keywords';
$string['keywordssearchresults'] = 'தேடல் விளைவுகள்: $a செய்திகள் காணப்பட்டன.';
$string['maxmessages'] = 'கலந்துரையாடல் வரலாற்றில் காட்டப்படவேண்டிய செய்திகளின் அதிகூடிய எண்ணிக்கை.';
$string['message'] = 'செய்தி';
$string['messagehistory'] = 'செய்தி வரலாறு';
$string['messages'] = 'செய்திகள்';
$string['messaging'] = 'செய்தியனுப்பல்';
$string['mycontacts'] = 'எனது தொடர்புகள்';
$string['newonlymsg'] = 'புதியதை மட்டும் காட்டு';
$string['newsearch'] = 'புதிய தேடல்';
$string['noframesjs'] = 'Version without frames and JavaScript';
$string['nomessages'] = 'தகவல் எதுவும் இல்லை';
$string['nomessagesfound'] = 'தகவல் எதுவும் காணப்படவில்லை';
$string['nosearchresults'] = 'உங்கள் தேடலுக்கு ஒரு விளைவும் கிடைக்கவில்லை';
$string['offline'] = 'இணைப்பிலா';
$string['offlinecontacts'] = 'இணைப்பிலாத் தொடர்புகள் $a';
$string['online'] = 'இணையுள்ள நிலை';
$string['onlinecontacts'] = 'இணையுள்ள தொடர்புகள் ($a)';
$string['onlyfromme'] = 'என்னிடமிருந்தான செய்திகள் மட்டும்';
$string['onlymycourses'] = 'எனது பாடநெறிகளில் மட்டும்';
$string['onlytome'] = 'எனக்கான செய்திகள் மட்டும்';
$string['pagerefreshes'] = 'ஒவ்வொரு $a விநாடிக்கொரு தடவை, இப்பக்கம் தானாகப் புதுப்பிக்கப்படும்.';
$string['readmessages'] = '$a வாசிக்கப்பட்ட செய்திகள்';
$string['removecontact'] = 'தொடர்பை நீக்குக';
$string['savemysettings'] = 'எனது அமைப்புகளைச் சேமிக்க';
$string['search'] = 'தேடு';
$string['searchforperson'] = 'ஒரு நபரைத் தேடுக';
$string['searchmessages'] = 'செய்திகளைத் தேடுக';
$string['sendmessage'] = 'செய்தி அனுப்புக';
$string['sendmessageto'] = '$a க்கு செய்தி அனுப்புக';
$string['sendmessagetopopup'] = '$a க்கு செய்தி அனுப்புக - புதிய சாளரம்';
$string['settings'] = 'அமைப்புகள்';
$string['settingssaved'] = 'உங்கள் அமைப்புகள் சேமிக்கப்பட்டன.';
$string['showmessagewindow'] = 'Automatically show Message window when I get new messages (your browser needs to be set so that it doesn\'t block popups on this site)';
$string['strftimedaydatetime'] = '%%A, %%d %%B %%Y, %%I:%%M %%p';
$string['timenosee'] = 'Minutes since I was last seen online';
$string['timesent'] = 'அனுப்பப்பட்ட நேரம்';
$string['unblockcontact'] = 'தொடர்பின் தடைநீக்கு';
$string['unreadmessages'] = '$a வாசிக்கப்படாத செய்திகள்';
$string['userisblockingyou'] = 'உங்களிடமிருந்து வரம் செய்திகளை இப்பயனாளர் தடுத்துள்ளார்.';
$string['userisblockingyounoncontact'] = 'இப்பயனாளர், தமது தொடர்புப் பட்டியலில் உள்ளவர்களிடமிருந்து மட்டும் செய்திகளைப் பெறுவார், ஆனால் நீங்கள் அவர் பட்டியலில் இல்லை.';
$string['userssearchresults'] = 'தேடல் விளைவுகள்: $a பயனாளர் காணப்பட்டனர்.';

?>
