<?PHP // $Id$ 
         // xmldb.php - created with Moodle 1.8.2 + (November 27, 2007)


$string['aftertable'] = 'பின் அட்டவணை';
$string['back'] = 'பின்புறம்';
$string['backtomainview'] = 'திரும்பவும் பிரதானத்திற்கு';
$string['binaryincorrectlength'] = 'துவித நிரலிற்கான சரியற்ற நீளம்';
$string['cannotuseidfield'] = '\"id\" நிரலை உள்ளீடு செய்ய முடியவில்லை.இது ஒரு தன்னியல்பு எண் நிரலாக உள்ளது.';
$string['change'] = 'மாற்றுக';
$string['charincorrectlength'] = 'அரிச்சுவடு நிரலிற்கான சரியற்ற நீளம்';
$string['confirmdeletefield'] = 'நீங்கள் நிரலை அழிக்க வேண்டும் என்பதில் முழுமையாக நிச்சயமாக இருக்கிறீர்களா:';
$string['confirmdeleteindex'] = 'நீங்கள் சுட்டியை அழிக்க வேண்டும் என்பதில் முழுமையாக நிச்சயமாக இருக்கிறீர்களா:';
$string['confirmdeletekey'] = 'நீங்கள் திறவுகோலை அழிக்க வேண்டும் என்பதில் முழுமையாக நிச்சயமாக இருக்கிறீர்களா:';
$string['confirmdeletesentence'] = 'நீங்கள் வசனத்தை அழிக்க வேண்டும் என்பதில் முழுமையாக நிச்சயமாக இருக்கிறீர்களா:';
$string['confirmdeletestatement'] = 'நீங்கள் கூற்றையும் அதனுடைய அனைத்து வசனங்களையும் அழிக்க வேண்டும் என்பதில் முழுமையாக நிச்சயமாக இருக்கிறீர்களா:';
$string['confirmdeletetable'] = 'நீங்கள் அட்டவணையை அழிக்க வேண்டும் என்பதில் முழுமையாக நிச்சயமாக இருக்கிறீர்களா:';
$string['confirmdeletexmlfile'] = 'நீங்கள் கோப்பை அழிக்க வேண்டும் என்பதில் முழுமையாக நிச்சயமாக இருக்கிறீர்களா:';
$string['confirmrevertchanges'] = 'நீங்கள் முடிவாக செய்யப்பட்ட மாற்றங்களை பழைய நிலைக்கு கொண்டுவர வேண்டும் என்பதில் முழுமையாக நிச்சயமாக இருக்கிறீர்களா:';
$string['create'] = 'உருவாக்குக';
$string['createtable'] = 'அட்டவணையை உருவாக்குக';
$string['defaultincorrect'] = 'சரியற்ற முன்னியல்பு';
$string['delete'] = 'அழிக்க';
$string['delete_field'] = 'நிரலை அழிக்க';
$string['delete_index'] = 'சுட்டியை அழிக்க';
$string['delete_key'] = 'திறவுகோலை அழிக்க';
$string['delete_sentence'] = 'வசனத்தை அழிக்க';
$string['delete_statement'] = 'கூற்றை அழிக்க';
$string['delete_table'] = 'அட்டவணையை அழிக்க';
$string['delete_xml_file'] = 'XML கோப்பை அழிக்க';
$string['down'] = 'கீழே';
$string['duplicate'] = 'நகல் எடுக்க';
$string['duplicatefieldname'] = 'ஏற்கனவே இருக்கின்ற பெயருடனான மற்றொரு நிரல்';
$string['edit'] = 'மாற்றுக';
$string['edit_field'] = 'நிரலை மாற்றுக';
$string['edit_index'] = 'சுட்டியை மாற்றுக';
$string['edit_key'] = 'திறவுகோலை மாற்றுக';
$string['edit_sentence'] = 'வசனத்தை மாற்றுக';
$string['edit_statement'] = 'கூற்றை மாற்றுக';
$string['edit_table'] = 'அட்டவணையை மாற்றுக';
$string['edit_xml_file'] = 'XML கோப்பை மாற்றுக';
$string['enumvaluesincorrect'] = 'enum நிரலுக்கான சரியற்ற மதிப்புகள்';
$string['field'] = 'நிரல்';
$string['fieldnameempty'] = 'பெயர் நிரல் வெற்றாக உள்ளது';
$string['fields'] = 'நிரல்கள்';
$string['filenotwriteable'] = 'கோப்பு எழுதக்கூடியதாக இல்லை';
$string['floatincorrectdecimals'] = 'float நிரலுக்கான பதின்மெண்களின் சரியற்ற எண்ணிக்கை';
$string['floatincorrectlength'] = 'float நிரலுக்கான சரியற்ற நீளம்';
$string['gotolastused'] = 'கடைசியாக பயன்படுத்தப்பட்ட கோப்பிற்கு செல்க';
$string['incorrectfieldname'] = 'சரியற்ற பெயர்';
$string['indexes'] = 'சுட்டிகள்';
$string['integerincorrectlength'] = 'integer நிரலுக்கான சரியற்ற நீளம்';
$string['keys'] = 'திறவுகோல்கள்';
$string['listreservedwords'] = 'ஒதுக்கீடு செய்யப்பட்ட எழுத்துகளின் பட்டியல்<br/>(வைத்திருப்பதற்கு பயன்பட்டது <a href=\"http://docs.moodle.org/en/XMLDB_reserved_words\" target=\"_blank\">XMLDB_ஒதுக்கீடு செய்யப்பட்ட_எழுத்துகள்</a> இற்றைப்படுத்தப்பட்டது)';
$string['load'] = 'ஏற்று';
$string['main_view'] = 'பிரதான பார்வை';
$string['missingfieldsinsentence'] = 'வசனத்தில் தவறுகின்ற நிரல்கள்';
$string['missingvaluesinsentence'] = 'வசனத்தில் தவறுகின்ற மதிப்புகள்';
$string['mustselectonefield'] = 'நிரல் சம்பந்தப்படுகின்ற செயற்பாடுகளை பார்ப்பதற்கு ஒரு நிரலை நீங்கள் தெரிவு செய்ய வேண்டும்!';
$string['mustselectoneindex'] = 'சுட்டி சம்பந்தப்படுகின்ற செயற்பாடுகளை பார்ப்பதற்கு ஒரு சுட்டியை நீங்கள் தெரிவு செய்ய வேண்டும்!';
$string['mustselectonekey'] = 'திறவுகோல் சம்பந்தப்படுகின்ற செயற்பாடுகளை பார்ப்பதற்கு ஒரு திறவுகோலை நீங்கள் தெரிவு செய்ய வேண்டும்!';
$string['new_statement'] = 'புதிய கூற்று';
$string['new_table_from_mysql'] = 'MySQL இலிருந்தான புதிய அட்டவணை';
$string['newfield'] = 'புதிய நிரல்';
$string['newindex'] = 'புதிய சுட்டி';
$string['newkey'] = 'புதிய திறவுகோல்';
$string['newsentence'] = 'புதிய வசனம்';
$string['newstatement'] = 'புதிய கூற்று';
$string['newtable'] = 'புதிய அட்டவணை';
$string['newtablefrommysql'] = 'MySQL இலிருந்தான புதிய அட்டவணை';
$string['numberincorrectdecimals'] = 'எண்ணிக்கை நிரலுக்கான பதின்மெண்களின் சரியற்ற எண்ணிக்கை';
$string['numberincorrectlength'] = 'எண்ணிக்கை நிரலுக்கான சரியற்ற நீளம்';
$string['reserved'] = 'ஒதுக்கீடு செய்யப்பட்டது';
$string['reservedwords'] = 'ஒதுக்கீடு செய்யப்பட்ட எழுத்துகள்';
$string['revert'] = 'பழைய நிலைக்கு கொண்டுவருக';
$string['revert_changes'] = 'மாற்றங்களை பழைய நிலைக்கு கொண்டுவருக';
$string['save'] = 'சேமிக்க';
$string['selectaction'] = 'செயற்பாடுகளை தெரிவு செய்க';
$string['selectdb'] = 'தரவுத்தளத்தை தெரிவு செய்க';
$string['selectfieldkeyindex'] = 'நிரல்/திறவுகோல்/சுட்டியை தெரிவு செய்க';
$string['selectonecommand'] = 'தயவுசெய்து, PHP குறிமொழியை பார்வையிடுவதற்கு பட்டியலிருந்து செயற்பாடொன்றை தெரிவு செய்க';
$string['selectonefieldkeyindex'] = 'தயவுசெய்து, PHP குறிமொழியை பார்வையிடுவதற்கு பட்டியலிருந்து நிரல்/திறவுகோல்/சுட்டியொன்றை தெரிவு செய்க';
$string['selecttable'] = 'அட்டவணை தெரிவு செய்க';
$string['sentences'] = 'வசனங்கள்';
$string['statements'] = 'கூற்றுக்கள்';
$string['statementtable'] = 'கூற்று அட்டவணை';
$string['statementtype'] = 'கூற்று வகை';
$string['table'] = 'அட்டவணை';
$string['tables'] = 'அட்டவணைகள்';
$string['test'] = 'சோதனை';
$string['textincorrectlength'] = 'உரை நிரலுக்கான சரியற்ற நீளம்';
$string['unload'] = 'இறக்கு';
$string['up'] = 'மேலே';
$string['view'] = 'பார்வையிடுக';
$string['view_reserved_words'] = 'ஒதுக்கீடு செய்யப்பட்ட எழுத்துகளை பார்வையிடுக';
$string['view_structure_php'] = 'கட்டமைப்பு PHPஐ பார்வையிடுக';
$string['view_structure_sql'] = 'கட்டமைப்பு SQLஐ பார்வையிடுக';
$string['view_table_php'] = 'அட்டவணை PHPஐ பார்வையிடுக';
$string['view_table_sql'] = 'அட்டவணை PHPஐ பார்வையிடுக';
$string['viewedited'] = 'மாற்றப்பட்டதை பார்வையிடுக';
$string['vieworiginal'] = 'அசலை பார்வையிடுக';
$string['viewphpcode'] = 'PHP குறிமொழியை பார்வையிடுக';
$string['viewsqlcode'] = 'SQL குறிமொழியை பார்வையிடுக';
$string['wronglengthforenum'] = 'enum நிரலுக்கான சரியற்ற நீளம்';
$string['wrongnumberoffieldsorvalues'] = 'நிரல்களின் அல்லது வசனத்திலுள்ள மதிப்புகளின் சரியற்ற எண்ணிக்கை';
$string['wrongreservedwords'] = 'தற்போது பயன்படுத்தப்பட்ட ஒதுக்கீடு செய்யப்பட்ட எழுத்துகள்<br />($CFG->முற்சேர்க்கை ஐ பயன்படுத்தினால் அட்டவணைப் பெயர்கள் முக்கியமானதாக இருப்பதில்லை என்பதை குறிப்பிடுக)';
$string['check_indexes'] = 'தவறிய தரவுத்தள சுட்டிகளுக்கான தேடல்'; // ORPHANED
$string['checkindexes'] = 'சுட்டிகளை சரிபார்க்க'; // ORPHANED
$string['completelogbelow'] = '(கீழேயுள்ள தேடல்களின் பூரண பதிவுகளைப் பார்க்க)'; // ORPHANED
$string['confirmcheckindexes'] = 'உங்களுடைய Moodle சேவையகத்தில் தவற வாய்ப்புள்ள சுட்டிகளுக்காக இந்த செய்முறை அனைத்தையும் இற்றைப்படுத்தப்பட்டதாக வைத்திருப்பதற்கு தன்னியல்பாக தேவைப்பட்ட SQL கூற்றுக்களை உருவாக்கின்றதாக(ஆனால் இயக்கமற்றதாக!)தேடலைச் செய்யும்.ஒருமுறை உருவாக்கப்பட்டவுடன் உங்களால் அந்தக் கூற்றுக்களை நகல் செய்ய முடிகிறது மற்றும் அவைகளை உங்களுடைய விருப்பத்திற்குரிய SQL இடைமுகத்துடன் பாதுகாப்பாக இயக்கமுடிகிறது.<br /><br />தவறிய சுட்டிகளின் தேடலை இயக்க முன்பு உங்களுடைய Moodle வெளியீட்டின் (1.8, 1.9, 2.x ...) உபயோகத்திலுள்ள கடைசி (+ பதிப்பு)இயங்கிக்கொண்டிருப்பதற்கு இது உயர்வாக சிபார்சு செய்யப்படுகிறது.<br /><br />இந்தச் செயல்முறை தரவுத்தளத்திற்கெதிராக எந்தவொரு செயற்பாட்டையும் செய்யவில்லை(சரியாக அதிலிருந்து வாசிக்கின்றது), ஆகையால் எந்தக் கணத்திலும் பாதுகாப்பாக நிறைவேற்றப்படமுடிகிறது.'; // ORPHANED
$string['index'] = 'சுட்டி'; // ORPHANED
$string['key'] = 'திறவுகோல்'; // ORPHANED
$string['missing'] = 'தவறல்'; // ORPHANED
$string['missingindexes'] = 'தவறுகின்ற நிரல்கள் கண்டுபிடிக்கப்பட்டது'; // ORPHANED
$string['nomissingindexesfound'] = 'தவறிய சுட்டிகள் எதுவும் கண்டுபிடிக்கப்படவில்லை,உங்களுடைய தரவுத்தளத்திற்கு மேலதிக செயற்பாடுகள் தேவையாக இல்லை.'; // ORPHANED
$string['searchresults'] = 'முடிவுகளை தேடுக'; // ORPHANED
$string['yesmissingindexesfound'] = 'உங்களுடைய தரவுத்தளத்தில் தவறிய சுட்டிகள் கண்டுபிடிக்கப்பட்டிருக்கின்றன.இங்கே, அவைகள் எல்லாவற்றையும் உருவாக்குவதற்கு, உங்களுடைய விருப்பத்திற்குரிய SQL இடைமுகத்துடன் இயக்கப்படுவதற்கு தேவைப்படுகின்ற SQL கூற்றுகளும் மற்றும் அவைகளுடைய விவரங்களும் இருக்கின்றன.<br /><br /> அதை செய்த பின்னர்,தவறிய சுட்டிகள் எதுவும் கண்டுபிடிக்கப்படவில்லை என்பதை சரிபார்ப்பதற்கு மீண்டும் இந்தப் பயன்பாட்டை இயக்குவதற்கு இது உயர்வாக சிபார்சு செய்யப்படுகிறது.'; // ORPHANED

?>