<?PHP // $Id$ 
      // blog.php - created with Moodle 2.0 dev (Build: 20091216) (2009112400)


$string['addnewentry'] = 'Yeni girdi ekle';
$string['addnewexternalblog'] = 'Harici bir blog kaydet...';
$string['assocdescription'] = 'Bir ders/etkinlik eklentisi hakkında yazıyorsanız onları burada seçin.';
$string['associatewithcourse'] = '$a->coursename dersi hakkında blog';
$string['associatewithmodule'] = '$a->modtype: $a->modname hakkında blog';
$string['association'] = 'İlişki';
$string['associations'] = 'İlişkiler';
$string['backupblogshelp'] = 'Etkinleştirilirse, bloglar, SITE otomatik yedeklemelerine dahil edilir.';
$string['blockexternalstitle'] = 'Harici Bloglar';
$string['blockmenutitle'] = 'Blog Menüsü';
$string['blockrecenttitle'] = 'Şimdiki Blog Gridileri';
$string['blocktagstitle'] = 'Blog Etiketleri';
$string['blocktitle'] = 'Blog etiketleri blok başlığı';
$string['blog'] = 'Blog';
$string['blogaboutthis'] = 'Bu $a->type hakkında blog';
$string['blogadministration'] = 'Blog yönetimi';
$string['blogdeleteconfirm'] = 'Bu blog silinsin mi?';
$string['blogdisable'] = 'Blog etkinleştirilmemiş!';
$string['blogentries'] = 'Blog girdileri';
$string['blogentriesabout'] = '$a hakkında blog girdileri';
$string['blogentriesbygroupaboutcourse'] = '$a->group / $a->course hakkında blog girdileri';
$string['blogentriesbygroupaboutmodule'] = '$a->group / $a->mod hakkında blog girdileri';
$string['blogentriesbyuseraboutcourse'] = '$a->user / $a->course hakkında blog girdileri';
$string['blogentriesbyuseraboutmodule'] = '$a->user / $a->mod hakkında blog girdileri';
$string['blogentrybyuser'] = '$a hakkında blog girdileri';
$string['blogpreferences'] = 'Blog seçenekleri';
$string['blogs'] = 'Bloglar';
$string['blogtags'] = 'Blog Etiketleri';
$string['cannotviewcourseblog'] = 'Bu dersteki blogları görmek için gerekli izinleriniz yok';
$string['cannotviewcourseorgroupblog'] = 'Bu dersteki/gruptaki blogları görmek için gerekli izinleriniz yok';
$string['cannotviewsiteblog'] = 'Sitedeki tüm blogları görmek için gerekli izinleriniz yok';
$string['cannotviewuserblog'] = 'Kullanıcı bloglarını görmek için gerekli izinleriniz yok';
$string['courseblog'] = 'Ders blogu: $a';
$string['courseblogdisable'] = 'Ders blogları etkin değil';
$string['courseblogs'] = 'Kullanıcılar, sadece derste paylaşıma açılan kullanıcı bloglarını görebilir';
$string['deleteotagswarn'] = 'Bu etiketleri bütün blog mesajlarından<br />ve sistemden kaldırmak istediğinizden emin misiniz?';
$string['disableblogs'] = 'Blog sistemini tamamen kapat';
$string['donothaveblog'] = 'Kendinize ait bir bloğunuz yok, üzgünüz.';
$string['editentry'] = 'Blog girdisi düzenle';
$string['editexternalblog'] = 'Bu harici blogu düzenle';
$string['emptybody'] = 'Blog metni boş olamaz';
$string['emptytitle'] = 'Blog başlığı boş olamaz';
$string['entrybody'] = 'Blog metni';
$string['entrybodyonlydesc'] = 'Açıklama';
$string['entryerrornotyours'] = 'Bu girdi size ait değil';
$string['entrysaved'] = 'Girdiniz kaydedildi';
$string['entrytitle'] = 'Girdi başlığı';
$string['entryupdated'] = 'Blog güncellendi';
$string['externalblogs'] = 'Harici bloglar';
$string['feedisinvalid'] = 'Bu akış geçersiz';
$string['feedisvalid'] = 'Bu akış geçerli';
$string['filterblogsby'] = 'Girdileri filtrele...';
$string['filtertags'] = 'Harici etiketler';
$string['groupblog'] = 'Grup blogu: $a';
$string['groupblogdisable'] = 'Grup blogu etkin değil';
$string['groupblogs'] = 'Kullanıcılar, sadece grupta paylaşıma açılan kullanıcı bloglarını görebilir';
$string['incorrectblogfilter'] = 'Hatalı blog filtreleme tipi';
$string['intro'] = 'Bu RSS kaynağı bir veya birden fazla blogdan otomatik olarak oluşturuldu.';
$string['noentriesyet'] = 'Henüz gösterilecek girdi yok';
$string['noguestpost'] = 'Konuklar blog gönderemezler!';
$string['norighttodeletetag'] = 'Bu etiketi silme hakkınız yok - $a';
$string['nosuchentry'] = 'Böyle bir blog girdisi yok';
$string['notallowedtoedit'] = 'Bu girdiyi düzenleme izniniz yok';
$string['numberofentries'] = 'Girdiler: $a';
$string['numberoftags'] = 'Gösterilecek etiket sayısı';
$string['pagesize'] = 'Her sayfadaki blog sayısı';
$string['permalink'] = 'SabitBağlantı';
$string['personalblogs'] = 'Kullanıcılar sadece kendi bloglarını görebilir';
$string['publishto'] = 'Yayınla';
$string['publishtonoone'] = 'Kendinize (taslak)';
$string['publishtosite'] = 'Bu sitedeki herkese';
$string['publishtoworld'] = 'Dünyadaki herkese';
$string['settingsupdatederror'] = 'Bir hata oluştu, blog seçenekleri ayarları güncellenemedi';
$string['siteblog'] = 'Site blogu: $a';
$string['siteblogdisable'] = 'Site blogu etkin değil';
$string['siteblogs'] = 'Tüm site kullanıcıları tüm blog girdilerini görebilir';
$string['tagdatelastused'] = 'En son kullanım tarihi';
$string['tags'] = 'Etiketler';
$string['tagsort'] = 'Etiket görünümünü sırala';
$string['tagtext'] = 'Etiket metni';
$string['timewithin'] = 'Şu gün içinde kullanılan etiketleri göster';
$string['updateentrywithid'] = 'Girdi güncelleniyor';
$string['userblog'] = 'Kullanıcı blogu: $a';
$string['viewmyentries'] = 'Girdilerime bak';
$string['viewsiteentries'] = 'Site girdilerine bak';
$string['worldblogs'] = 'Tüm dünyaya açık olarak ayarlanmış blogları görebilir';
$string['wrongpostid'] = 'Hatalı blog gönderim kimliği';
$string['deleteposterror'] = 'Gönderi silinirken hata oluştu'; // ORPHANED
$string['viewcourseentries'] = 'Ders girdilerine bak'; // ORPHANED
$string['addotags'] = 'Resmi etiket ekle'; // ORPHANED
$string['addptags'] = 'Kullanıcı tanımlı etiket ekle'; // ORPHANED
$string['otags'] = 'Resmi etiketler'; // ORPHANED
$string['ptags'] = 'Kullanıcı tanımlı etiketler (Virgülle ayrılmış)'; // ORPHANED

?>
