<?PHP // $Id$ 
      // error.php - created with Moodle 1.7 dev (2006091901)


$string['adminprimarynoedit'] = 'Ana yönetici başka kullanıcılar tarafından düzenlenemez';
$string['cannotcreatelangdir'] = 'Dil dizini oluşturulamıyor.';
$string['cannotcreatetempdir'] = 'Geçici dizin oluşturulamıyor.';
$string['cannotdownloadcomponents'] = 'Bileşenler indirilemedi.';
$string['cannotdownloadzipfile'] = 'ZIP dosyası indirilemedi.';
$string['cannotfindcomponent'] = 'Bileşen bulunamadı.';
$string['cannotsavemd5file'] = 'Md5 dosyadı kaydedilemedi.';
$string['cannotsavezipfile'] = 'ZIP dosyası kaydedilemedi.';
$string['cannotunzipfile'] = 'Dosya arşivi açılamadı.';
$string['cmunknown'] = 'Bu kurs modülü bulunamadı';
$string['componentisuptodate'] = 'Bileşen günceldir.';
$string['confirmsesskeybad'] = 'Üzgünüz, oturum anahtarınız bu eylemi gerçekleştirmek için onaylanamadı. Bu güvenlik özelliği, sizin adınıza yapılacak olan önemli işlevlerin yanlışlıkla ya da kasten kullanılmasını engellemek içindir. Lütfen bu işlevi gerçekten yapmak istediğinizden emin olun.';
$string['couldnotassignrole'] = 'Size rol atanmaya çalışılırken ciddi ama belirlenemeyen bir hata oluştu';
$string['coursegroupunknown'] = 'Grup $a ile ilgili kurs belirtilmemiş';
$string['downloadedfilecheckfailed'] = 'İndirilmiş dosya kontrol hatası';
$string['errorcleaningdirectory'] = '\"$a\" dizinini temizlerken hata oluştu';
$string['errorcopyingfiles'] = 'Dosyaları kopyalarken hata oluştu';
$string['errorcreatingdirectory'] = '\"$a\" dizinini oluştururken hata oluştu';
$string['errorcreatingfile'] = '\"$a\" dosyasını oluştururken hata oluştu';
$string['erroronline'] = '$a. satırda hata var';
$string['errorreadingfile'] = '\"$a\" dosyasını okurken hata oluştu';
$string['errorunzippingfiles'] = 'Zipli dosyaları açarken hata oluştu';
$string['fieldrequired'] = '\"$a\" doldurulması gerekli bir alandır';
$string['filenotfound'] = 'Üzgünüz, aranan dosya bulunamadı';
$string['forumblockingtoomanyposts'] = 'Bu forum için mesaj gönderme aralığını aştınız.';
$string['groupalready'] = 'Kullanıcı $a grubuna zaten kayıtlı';
$string['groupunknown'] = '$a grubu belirtilen kursla ilişkili değil';
$string['guestnoeditprofile'] = 'Konuk kullanıcı kendi profilini düzenleyemez';
$string['guestnoeditprofileother'] = 'Konuk kullanıcının profili düzenlenemez';
$string['invalidcourse'] = 'Geçersiz kurs';
$string['invalidfieldname'] = '\"$a\" geçerli bir alan adı değil';
$string['invalidfiletype'] = '\"$a\" geçerli bir dosya tipi değil';
$string['invalidmd5'] = 'Geçersiz md5';
$string['invalidxmlfile'] = '\"$a\" geçerli bir XML dosyası değil';
$string['missingfield'] = '\"$a\" alanı eksik';
$string['missingrequiredfield'] = 'Bazı gerekli alanlar eksik';
$string['modulemissingcode'] = 'Bu eylemi gerçekleştirecek gerekli kod $a modülü için eksik';
$string['modulerequirementsnotmet'] = '\"$a->modulename\" ($a->moduleversion) modülü kurulamadı. Bu modül daha yeni bir Moodle sürümü gerektirmektedir (şu anda kullandığınız: $a->currentmoodle, gereken: $a->requiremoodle).';
$string['mustbeteacher'] = 'Bu sayfaya bakabilmek için eğitimci olmalısınız';
$string['nocontext'] = 'Üzgünüz, bu kursun geçerli bir bağlamı yok';
$string['noinstances'] = '$a bu kursta kullanılmadı!';
$string['nonmeaningfulcontent'] = 'Anlamsız içerik';
$string['noparticipatorycms'] = 'Üzgünüz, rapor edilecek kurs modüllerinin katılımcısı değilsiniz.';
$string['nopermissions'] = 'Üzgünüz, şu anda bunu yapmaya yetkiniz yok: $a';
$string['notavailable'] = 'Şu anda erişilemez';
$string['onlyadmins'] = 'Sadece yöneticiler bunu yapabilir';
$string['onlyeditingteachers'] = 'Sadece eğitimciler bunu yapabilir';
$string['onlyeditown'] = 'Sadece kendi bilgilerinizi düzenleyebilirsiniz';
$string['pagenotexist'] = 'Nadiren görülen bir hata oluştu (olmayan bir sayfaya erişilmeye çalışıldı)';
$string['pleasereport'] = 'Zamanınız varsa, lütfen hata oluştuğunda ne yapmaya çalıştığınızı bilmemize izin verin:';
$string['pluginrequirementsnotmet'] = '\"$a->pluginname\" ($a->pluginversion) eklentisi kurulamadı. Bu eklenti daha yeni bir Moodle sürümü gerektirmektedir (şu anda kullandığınız: $a->currentmoodle, gereken: $a->requiremoodle).';
$string['processingstops'] = 'İşlem burada sona erer. Kalan kayıtlar yoksayılır.';
$string['remotedownloadnotallowed'] = 'Sunucunuza bileşen indirmeye izin verilmiyor. (allow_url_fopen pasif).<br /><br />Arşivlenmiş dosyayı <a href=\"$a->url\">$a->url</a> elle indirip buraya \"$a->dest\" açmalısınız.';
$string['restricteduser'] = 'Üzgünüz, şu anki \"$a\" hesabınız bunu yapmak için sınırlandırılmıştır.';
$string['sendmessage'] = 'Mesajı Gönder';
$string['sessionerroruser'] = 'Oturumunuz zaman aşımına uğradı. Lütfen tekrar giriş yapınız.';
$string['sessionerroruser2'] = 'Giriş oturumunuzu etkileyen bir sunucu hatası algılandı. Lütfen yeniden giriş yapınız ya da tarayıcınızı yeniden başlatınız.';
$string['sessionipnomatch'] = 'Üzgünüz, IP numaranız ilk girdiğinizden farklıdır. Bu güvenlik özelliği, siteye giriş yaptığınızda crackerların kimlik bilgilerinizi çalmalarını engellemek içindir. Normal kullanıcıların bu mesajı görmemeleri gerekir - lütfen yardım için site yöneticisine başvurun.';
$string['statscatchupmode'] = 'İstatistikler şu anda işleme modunda. Şu ana kadar $a->daysdone gün işlendi ve $a->dayspending gün de beklemede. Daha sonra tekrar kontrol edin!';
$string['unknowncourse'] = '\"$a\" adlı kurs bilinmiyor';
$string['unknownuseraction'] = 'Üzgünüm, bu kullanıcı eylemini anlamıyorum.';
$string['usernotaddederror'] = '\"$a\" kullanıcısı eklenmedi - bilinmeyen hata';
$string['usernotaddedregistered'] = '\"$a\" kullanıcısı eklenmedi - zaten kayıtlı';
$string['usernotavailable'] = 'Bu kullanıcının ayrıntıları sizin erişiminize kapalı.';
$string['usernotrenamedexists'] = 'Kullanıcı yeniden adlandırılamadı - yeni kullanıcı adı zaten kullanımda.';
$string['usernotrenamedmissing'] = 'Kullanıcı yeniden adlandırılamadı - eski kullanıcı adı bulunamadı.';
$string['wrongdestpath'] = 'Hatalı hedef yolu';
$string['wrongsourcebase'] = 'Hatalı kaynak URL base.';
$string['wrongzipfilename'] = 'Hatalı ZIP dosya adı.';

?>
