<?PHP // $Id$ 
      // group.php - created with Moodle 2.0 dev (2007101503)


$string['addgroupstogrouping'] = 'Grupları gruplamaya ekle';
$string['addgroupstogroupings'] = 'Grup ekle/sil';
$string['adduserstogroup'] = 'Kullanıcı ekle/sil';
$string['anygrouping'] = '[Herhangi gruplama]';
$string['autocreategroups'] = 'Grupları otomatik oluştur';
$string['backtogroupings'] = 'Gruplamalara geri dön';
$string['backtogroups'] = 'Gruplara geri dön';
$string['createautomaticgrouping'] = 'Otomatik gruplama oluştur';
$string['creategroup'] = 'Grup oluştur';
$string['creategrouping'] = 'Gruplama oluştur';
$string['creategroupinselectedgrouping'] = 'Gruplamada grup oluştur';
$string['databaseupgradegroups'] = 'Grup sürümü şu anda $a';
$string['defaultgroupdescription'] = 'Varsayılan grup açıklaması';
$string['defaultgrouping'] = 'Varsayılan gruplama';
$string['defaultgroupingname'] = 'Gruplama';
$string['defaultgroupname'] = 'Grup';
$string['defaultgroupprefix'] = 'Grup';
$string['deletegroupconfirm'] = '\'$a\' grubunu silmek istediğinizden emin misiniz?';
$string['deletegrouping'] = 'Gruplamayı sil';
$string['deletegroupingconfirm'] = '\'$a\' gruplamasını silmek istediğinizden emin misiniz? (Gruplama içindeki gruplar silinmez.)';
$string['deleteselectedgroup'] = 'Seçili grubu sil';
$string['displaygrouping'] = 'Gruplamayı göster';
$string['distributealphabetically'] = 'Grupları soyada göre alfabetik dağıt';
$string['distributeevenly'] = 'Artan öğrencileri eşit dağıt';
$string['editgroupingsettings'] = 'Gruplama ayarlarını düzenle';
$string['editgroupsettings'] = 'Grup ayarlarını düzenle';
$string['enrolmentkey'] = 'Kayıt anahtarı';
$string['erroraddremoveuser'] = '$a kullanıcısını gruba eklerken hata';
$string['erroreditgroup'] = '$a grubunu oluştururken/güncellerken hata';
$string['erroreditgrouping'] = '$a gruplamasını oluştururken/güncellerken hata';
$string['errorinvalidgroup'] = 'Hata, geçersiz grup $a';
$string['existingmembers'] = 'Mevcut kullanıcı: $a';
$string['filtergroups'] = 'Grupları süz:';
$string['firstname'] = 'isme göre alfabetik';
$string['group'] = 'Grup';
$string['groupaddedsuccesfully'] = '$a grubu başarıyla eklendi';
$string['groupdescription'] = 'Grup açıklaması';
$string['groupinfo'] = 'Seçili grup hakkında bilgi';
$string['groupinfomembers'] = 'Seçili üyeler hakkında bilgi';
$string['groupinfopeople'] = 'Seçili kişiler hakkında bilgi';
$string['grouping'] = 'Gruplama';
$string['groupingdescription'] = 'Gruplama açıklaması';
$string['groupingname'] = 'Gruplama adı';
$string['groupings'] = 'Gruplamalar';
$string['groupmember'] = 'Grup Üyesi';
$string['groupmemberdesc'] = 'Bir grubun bir üyesi için standart rol';
$string['groupmembers'] = 'Grup üyeleri';
$string['groupmemberssee'] = 'Grup üyelerine bak';
$string['groupmembersselected'] = 'Seçili grubun üyeleri';
$string['groupmode'] = 'Grup modu';
$string['groupmodeforce'] = 'Grup modu zorunluluğu';
$string['groupmy'] = 'Grubum';
$string['groupname'] = 'Grup adı';
$string['groupnotamember'] = 'Üzgünüz, bu grubun üyesi değilsiniz';
$string['groups'] = 'Gruplar';
$string['groupsinselectedgrouping'] = 'Gruplamadaki gruplar';
$string['groupsnone'] = 'Grup yok';
$string['groupsseparate'] = 'Ayrı gruplar';
$string['groupsvisible'] = 'Görünür gruplar';
$string['hidepicture'] = 'Resmi gizle';
$string['javascriptrequired'] = 'Bu sayfa, Javascriptin etkin olmasını gerektirir.';
$string['membersofselectedgroup'] = 'Grubun üyeleri';
$string['newpicture'] = 'Yeni resim';
$string['notingrouping'] = '[Gruplama içinde değil]';
$string['numberofgroups'] = 'Grup sayısı';
$string['numberofstudents'] = 'Öğrenci sayısı';
$string['prefixforgroupnames'] = 'Grup adları için önek';
$string['printerfriendly'] = 'Yazıcı-dostu görünüm';
$string['removegroupfromselectedgrouping'] = 'Grubu gruplamadan sil';
$string['removeselectedusers'] = 'Seçili kullanıcıları sil';
$string['selectnumberineachgroup'] = 'Her bir gruptaki sayı';
$string['selectnumberofgroups'] = 'Grup sayısını seçin';
$string['showgroupsingrouping'] = 'Gruplamadaki grupları göster';
$string['showmembersforgroup'] = 'Grup için üyeleri göster';
$string['usestudentsonlyfromselectedgroup'] = 'Sadece şu an seçili gruptan öğrencileri kullan';
$string['addexistinggroupstogrouping'] = 'Mevcut grupları gruplamaya ekle'; // ORPHANED
$string['cancel'] = 'İptal'; // ORPHANED
$string['editgroupingpermissions'] = 'Gruplama yetkilerini düzenle'; // ORPHANED
$string['errorinvalidgrouping'] = 'Hata, geçersiz gruplama $a'; // ORPHANED
$string['errornotingrouping'] = 'Üzgünüz, $a içinde bir grup oluşturamazsınız.'; // ORPHANED
$string['errornotingroupingedit'] = 'Üzgünüz, $a gruplamasını düzenleyemezsiniz.'; // ORPHANED
$string['groupfor'] = 'grup için'; // ORPHANED
$string['return'] = 'Geri dön'; // ORPHANED
$string['save'] = 'Kaydet'; // ORPHANED
$string['showusersalreadyingroup'] = 'Gruplamada zaten bir grupta olan öğrencileri göster'; // ORPHANED
$string['teachersgroupmark'] = 'Eğitimciler, abonesi olmadıkları gruplardaki etkinlikleri işaretleyemez'; // ORPHANED
$string['teachersgroupview'] = 'Eğitimciler, abonesi olmadıkları gruplardaki etkinlikleri göremez'; // ORPHANED
$string['teachersoverride'] = 'Hiçbir gruba abone olmayan eğitimciler, bütün grupları görebilir ve grup etkinliklerini işaretleyebilir (yukarıdakini hükümsüz kılar)'; // ORPHANED
$string['upgradeconfirm'] = 'Üzgünüz, Moodle1.8-DEV\'de oluşturulan grup tablolarının bu güncellemede silinmesi gerekiyor. Devam etmek istiyor musunuz?'; // ORPHANED
$string['viewallgroupsactivities'] = 'Öğrenciler görebilir, ama bütün gruplardaki etkinliklere dağıtılamaz'; // ORPHANED
$string['viewallgroupsmembers'] = 'Öğrenciler, bütün grupların üyelerini görebilir'; // ORPHANED
$string['viewowngroup'] = 'Öğrenciler, abonesi oldukları herhangi bir grubun üyelerini görebilir'; // ORPHANED

?>
