<?PHP // $Id$ 
      // group.php - created with Moodle 2.0 dev (Build: 20090322) (2009030501)


$string['addgroupstogrouping'] = 'Grupları gruplamaya ekle';
$string['addgroupstogroupings'] = 'Grup ekle/sil';
$string['adduserstogroup'] = 'Kullanıcı ekle/sil';
$string['allocateby'] = 'Üyeleri yerleştir';
$string['anygrouping'] = '[Herhangi gruplama]';
$string['autocreategroups'] = 'Grupları otomatik oluştur';
$string['backtogroupings'] = 'Gruplamalara geri dön';
$string['backtogroups'] = 'Gruplara geri dön';
$string['badnamingscheme'] = 'Sadece bir \'@\' işareti veya bir \'#\' işareti içermeli';
$string['byfirstname'] = 'İsme, soyisme göre';
$string['byidnumber'] = 'ID numarasına göre';
$string['bylastname'] = 'Soyisme, isme göre';
$string['createautomaticgrouping'] = 'Otomatik gruplama oluştur';
$string['creategroup'] = 'Grup oluştur';
$string['creategrouping'] = 'Gruplama oluştur';
$string['creategroupinselectedgrouping'] = 'Gruplamada grup oluştur';
$string['createingrouping'] = 'Gruplamada oluştur';
$string['createorphangroup'] = 'Sahipsiz grup oluştur';
$string['databaseupgradegroups'] = 'Grup sürümü şu anda $a';
$string['defaultgrouping'] = 'Varsayılan gruplama';
$string['defaultgroupingname'] = 'Gruplama';
$string['defaultgroupname'] = 'Grup';
$string['deleteallgroupings'] = 'Tüm gruplamaları sil';
$string['deleteallgroups'] = 'Tüm grupları sil';
$string['deletegroupconfirm'] = '\'$a\' grubunu silmek istediğinizden emin misiniz?';
$string['deletegrouping'] = 'Gruplamayı sil';
$string['deletegroupingconfirm'] = '\'$a\' gruplamasını silmek istediğinizden emin misiniz? (Gruplama içindeki gruplar silinmez.)';
$string['deletegroupsconfirm'] = 'Aşağıdaki grupları silmek istediğinizden emin misiniz?';
$string['deleteselectedgroup'] = 'Seçili grubu sil';
$string['editgroupingsettings'] = 'Gruplama ayarlarını düzenle';
$string['editgroupsettings'] = 'Grup ayarlarını düzenle';
$string['enrolmentkey'] = 'Kayıt anahtarı';
$string['erroraddremoveuser'] = '$a kullanıcısını gruba eklerken hata';
$string['erroreditgroup'] = '$a grubunu oluştururken/güncellerken hata';
$string['erroreditgrouping'] = '$a gruplamasını oluştururken/güncellerken hata';
$string['errorinvalidgroup'] = 'Hata, geçersiz grup $a';
$string['errorselectone'] = 'Bu seçeneği seçmeden önce lütfen tek bir grup seçin';
$string['errorselectsome'] = 'Bu seçeneği seçmeden önce lütfen bir ya da daha fazla grup seçin';
$string['evenallocation'] = 'Not: Grup dağılımını eşit tutabilmek için, her bir grubun gerçek sayısı sizin belirttiğiniz sayıdan farklı olacaktır.';
$string['existingmembers'] = 'Mevcut kullanıcı: $a';
$string['filtergroups'] = 'Grupları süz:';
$string['group'] = 'Grup';
$string['groupaddedsuccesfully'] = '$a grubu başarıyla eklendi';
$string['groupby'] = 'Grupla';
$string['groupdescription'] = 'Grup açıklaması';
$string['groupinfo'] = 'Seçili grup hakkında bilgi';
$string['groupinfomembers'] = 'Seçili üyeler hakkında bilgi';
$string['groupinfopeople'] = 'Seçili kişiler hakkında bilgi';
$string['grouping'] = 'Gruplama';
$string['groupingdescription'] = 'Gruplama açıklaması';
$string['groupingname'] = 'Gruplama adı';
$string['groupingnameexists'] = '\'$a\' gruplaması bu kursta zaten var. Lütfen başka bir isim seçin.';
$string['groupings'] = 'Gruplamalar';
$string['groupingsonly'] = 'Sadece gruplamalar';
$string['groupmember'] = 'Grup Üyesi';
$string['groupmemberdesc'] = 'Bir grubun bir üyesi için standart rol';
$string['groupmembers'] = 'Grup üyeleri';
$string['groupmembersonly'] = 'Sadece grup üyelerine açık';
$string['groupmembersonlyerror'] = 'Üzgünüz, bu etkinlikte kullanılan en az bir grubun üyesi olmalısınız.';
$string['groupmemberssee'] = 'Grup üyelerine bak';
$string['groupmembersselected'] = 'Seçili grubun üyeleri';
$string['groupmode'] = 'Grup modu';
$string['groupmodeforce'] = 'Grup modu zorunluluğu';
$string['groupmy'] = 'Grubum';
$string['groupname'] = 'Grup adı';
$string['groupnameexists'] = '\'$a\' grubu bu kursta zaten var. Lütfen başka bir isim seçin.';
$string['groupnotamember'] = 'Üzgünüz, bu grubun üyesi değilsiniz';
$string['groups'] = 'Gruplar';
$string['groupscount'] = 'Gruplar ($a)';
$string['groupsgroupings'] = 'Gruplar &amp; gruplamalar';
$string['groupsinselectedgrouping'] = 'Gruplamadaki gruplar';
$string['groupsnone'] = 'Grup yok';
$string['groupsonly'] = 'Sadece gruplar';
$string['groupspreview'] = 'Grup önizlemesi';
$string['groupsseparate'] = 'Ayrı gruplar';
$string['groupsvisible'] = 'Görünür gruplar';
$string['grouptemplate'] = 'Grup @';
$string['hidepicture'] = 'Resmi gizle';
$string['javascriptrequired'] = 'Bu sayfa, Javascriptin etkin olmasını gerektirir.';
$string['members'] = 'Her gruptaki üye';
$string['membersofselectedgroup'] = 'Grubun üyeleri';
$string['namingscheme'] = 'İsimlendirme şeması';
$string['namingschemehelp'] = 'Grup harfi (A-Z) sunmak için @ karakterini, grup numarası sunmak içinse # karakterini kullanın.';
$string['newgrouping'] = 'Yeni gruplama';
$string['newpicture'] = 'Yeni resim';
$string['noallocation'] = 'Yerleştirme yok';
$string['nogroups'] = 'Bu kursta ayarlanmış herhangi grup yok.';
$string['nogroupsassigned'] = 'Grup atanmadı';
$string['nopermissionforcreation'] = 'Gerekli izinleriniz olmadığından \"$a\" grubu oluşturulamıyor.';
$string['nosmallgroups'] = 'Son küçük grubu engelle';
$string['notingrouping'] = '[Gruplama içinde değil]';
$string['nousersinrole'] = 'Seçili role uygun kullanıcı yok';
$string['number'] = 'Grup/üye sayısı';
$string['numgroups'] = 'Grup sayısı';
$string['nummembers'] = 'Her gruptaki üye';
$string['overview'] = 'Önizle';
$string['potentialmembers'] = 'Olası üyeler: $a';
$string['potentialmembs'] = 'Olası üyeler';
$string['printerfriendly'] = 'Yazıcı-dostu görünüm';
$string['random'] = 'Rasgele';
$string['removegroupfromselectedgrouping'] = 'Grubu gruplamadan sil';
$string['removegroupingsmembers'] = 'Tüm grupları gruplamadan sil';
$string['removegroupsmembers'] = 'Tüm grup üyelerini sil';
$string['removeselectedusers'] = 'Seçili kullanıcıları sil';
$string['selectfromrole'] = 'Rolden kullanıcıları seç';
$string['showgroupsingrouping'] = 'Gruplamadaki grupları göster';
$string['showmembersforgroup'] = 'Grup için üyeleri göster';
$string['toomanygroups'] = 'Bu sayıda grubu doldurmak için yetersiz kullanıcı - seçili rolde yalnızca $a kullanıcı vardır.';
$string['usercount'] = 'Kullanıcı sayısı';
$string['usercounttotal'] = 'Kullanıcı sayısı ($a)';
$string['usergroupmembership'] = 'Seçili kullanıcıların üyeliği:';
$string['defaultgroupdescription'] = 'Varsayılan grup açıklaması'; // ORPHANED
$string['defaultgroupprefix'] = 'Grup'; // ORPHANED
$string['displaygrouping'] = 'Gruplamayı göster'; // ORPHANED
$string['distributealphabetically'] = 'Grupları soyada göre alfabetik dağıt'; // ORPHANED
$string['distributeevenly'] = 'Artan öğrencileri eşit dağıt'; // ORPHANED
$string['firstname'] = 'isme göre alfabetik'; // ORPHANED
$string['numberofgroups'] = 'Grup sayısı'; // ORPHANED
$string['numberofstudents'] = 'Öğrenci sayısı'; // ORPHANED
$string['prefixforgroupnames'] = 'Grup adları için önek'; // ORPHANED
$string['selectnumberineachgroup'] = 'Her bir gruptaki sayı'; // ORPHANED
$string['selectnumberofgroups'] = 'Grup sayısını seçin'; // ORPHANED
$string['usestudentsonlyfromselectedgroup'] = 'Sadece şu an seçili gruptan öğrencileri kullan'; // ORPHANED
$string['addexistinggroupstogrouping'] = 'Mevcut grupları gruplamaya ekle'; // ORPHANED
$string['cancel'] = 'İptal'; // ORPHANED
$string['editgroupingpermissions'] = 'Gruplama yetkilerini düzenle'; // ORPHANED
$string['errorinvalidgrouping'] = 'Hata, geçersiz gruplama $a'; // ORPHANED
$string['errornotingrouping'] = 'Üzgünüz, $a içinde bir grup oluşturamazsınız.'; // ORPHANED
$string['errornotingroupingedit'] = 'Üzgünüz, $a gruplamasını düzenleyemezsiniz.'; // ORPHANED
$string['groupfor'] = 'grup için'; // ORPHANED
$string['return'] = 'Geri dön'; // ORPHANED
$string['save'] = 'Kaydet'; // ORPHANED
$string['showusersalreadyingroup'] = 'Gruplamada zaten bir grupta olan öğrencileri göster'; // ORPHANED
$string['teachersgroupmark'] = 'Eğitimciler, abonesi olmadıkları gruplardaki etkinlikleri işaretleyemez'; // ORPHANED
$string['teachersgroupview'] = 'Eğitimciler, abonesi olmadıkları gruplardaki etkinlikleri göremez'; // ORPHANED
$string['teachersoverride'] = 'Hiçbir gruba abone olmayan eğitimciler, bütün grupları görebilir ve grup etkinliklerini işaretleyebilir (yukarıdakini hükümsüz kılar)'; // ORPHANED
$string['upgradeconfirm'] = 'Üzgünüz, Moodle1.8-DEV\'de oluşturulan grup tablolarının bu güncellemede silinmesi gerekiyor. Devam etmek istiyor musunuz?'; // ORPHANED
$string['viewallgroupsactivities'] = 'Öğrenciler görebilir, ama bütün gruplardaki etkinliklere dağıtılamaz'; // ORPHANED
$string['viewallgroupsmembers'] = 'Öğrenciler, bütün grupların üyelerini görebilir'; // ORPHANED
$string['viewowngroup'] = 'Öğrenciler, abonesi oldukları herhangi bir grubun üyelerini görebilir'; // ORPHANED

?>
