<?PHP // $Id$ 
      // question.php - created with Moodle 2.0 dev (Build: 20090318) (2009030501)


$string['adminreport'] = 'Soru veritabanınız için olası sorunları bildirin.';
$string['broken'] = 'Bu \"bağlantı\" yanlıştır. Olmayan bir dosyayı gösteriyor.';
$string['byandon'] = '<em>$a->user</em> tarafından <em>$a->time</em> tarihinde';
$string['cannotcopybackup'] = 'Yedek dosya kopyalanamadı';
$string['cannotcreate'] = 'question_attempts tablosunda yeni kayıt oluşturulamadı';
$string['cannotcreatepath'] = 'Yol oluşturulamadı: $a';
$string['cannotfindcate'] = 'Kategori kaydı bulunamadı';
$string['cannotfindquestionfile'] = 'Zip dosyasında soru verisi bulunamadı';
$string['cannothidequestion'] = 'Soru gizlenemedi';
$string['cannotinsertquestion'] = 'Yeni soru eklenemedi!';
$string['cannotloadquestion'] = 'Soru yüklenemedi';
$string['cannotretrieveqcat'] = 'Soru kategorisi alınamadı';
$string['cannotsavequiz'] = 'Şu anki sınav uygulamasını kaydederken hata';
$string['cannotunhidequestion'] = 'Soruyu görünür yaparken hata.';
$string['cannotunzip'] = 'Zipli dosya açılamadı';
$string['categorycurrent'] = 'Şimdiki kategori';
$string['categorycurrentuse'] = 'Bu kategoriyi kullanın';
$string['categorydoesnotexist'] = 'Bu kategori yok';
$string['categorymoveto'] = 'Kategoride saklayın';
$string['changepublishstatuscat'] = '\"$a->coursename\" kursundaki <a href=\"$a->caturl\">\"$a->name\" kategorisi</a>nin paylaşım durumu $a->changefrom, <strong>$a->changeto</strong> olarak değiştirildi.';
$string['copy'] = 'Buradan $a kopyala ve linkleri değiştir.';
$string['created'] = 'Oluşturma';
$string['createdmodifiedheader'] = 'Oluşturma / Son Kaydetme';
$string['cwrqpfs'] = 'Alt kategorilerden gelişigüzel sorular seçiliyor';
$string['cwrqpfsinfo'] = '<p>Moodle 1.9 yükseltmesi sırasında soru kategorilerini farklı bağlamlara ayıracağız. Bazı soru kategorileri ve sitenizdeki soruların paylaşım konumu değişmek zorunda kalacaktır. Bu, çok nadir bir durum olarak bir küçük sınavdaki \'gelişigüzel\' soruların paylaşılan ve paylaşılmayan kategorilerin karışımından seçilmek üzere ayarlandığı bir durum için gereklidir (aynen bu sitede olduğu gibi). Bu, \'gelişigüzel\' bir soru alt kategorilerden seçilmek üzere ayarlandığında ve bir ya da daha fazla alt kategorinin gelişigüzel sorunun oluşturulduğu üst kategoriye farklı bir paylaşım konumu varsa olur.</p>
<p> Üst kategorilerdeki \'gelişigüzel\' sorulardan soru seçen aşağıdaki soru kategorileri, paylaşım konumlarını değiştirerek Moodle 1.9\'a yükseltmedeki \'gelişigüzel\' soru kategorisindeki paylaşım konumu ile aynı yapacaklardır. Etkilenen sorular, mevcut bütün küçük sınavlarda, siz bu soruları bu küçük sınavlardan kaldırmadığınız sürece çalışmaya devam edecektir.</p>';
$string['cwrqpfsnoprob'] = '\'Alt kategorilerden sorular seçen gelişigüzel sorular\' konusundan sitenizdeki hiçbir soru kategorisi etkilenmez.';
$string['defaultfor'] = '$a için varsayılan';
$string['defaultinfofor'] = 'Sorular için varsayılan kategori \'$a\' bağlamında paylaşıldı.';
$string['deletecoursecategorywithquestions'] = 'Soru bankasında bu ders kategorisiyle ilişkili sorular mevcuttur. İlerlerseniz, bunlar silinecektir. Soru bankası arayüzünü kullanarak ilk önce bunları taşımak isteyebilirsiniz.';
$string['donothing'] = 'Dosyaları kopyalamayın/taşımayın ya da linkleri değiştirmeyin.';
$string['editingcategory'] = 'Kategori düzenleniyor';
$string['editingquestion'] = 'Soru düzenleniyor';
$string['emptyxml'] = 'Bilinmeyen hata - boş imsmanifest.xml';
$string['erroraccessingcontext'] = 'Bağlama erişilemedi';
$string['errordeletingquestionsfromcategory'] = '$a kategorisinden soruları silmede hata.';
$string['errorfilecannotbecopied'] = '$a dosyasını kopyalarken hata.';
$string['errorfilecannotbemoved'] = '$a dosyasını taşırken hata.';
$string['errorfileschanged'] = 'Formun görüntülenmesinden beri form sorularına bağlı hata dosyaları değişti.';
$string['errormanualgradeoutofrange'] = '$a->grade notu, $a->name sorusu için 0 ve $a->maxgrade arasında değil. Skor ve komut kaydedilmedi.';
$string['errormovingquestions'] = 'Soruları ID\'ler $a ile taşırken hata.';
$string['errorprocessingresponses'] = 'Yanıtlarınızı işlemede hata oluştu.';
$string['errorsavingcomment'] = '$a->name sorusu için komutu veritabanına kaydederken hata.';
$string['errorupdatingattempt'] = '$a->id girişimini veritabanında güncellemede hata.';
$string['exportcategory'] = 'Kategoriyi dışa ver';
$string['filesareacourse'] = 'kurs dosyaları alanı';
$string['filesareasite'] = 'site dosyaları alanı';
$string['filestomove'] = 'Dosyalar buraya taşınsın/kopyalansın mı: $a?';
$string['fractionsnomax'] = 'Bu sorudan tam not alınabilmesi için sorulardan en az bir tanesinin puanı %%100 olması gerekir.';
$string['getcategoryfromfile'] = 'Kategoriyi dosyadan getir';
$string['getcontextfromfile'] = 'Bağlamı dosyadan getir';
$string['ignorebroken'] = 'Kırık linkleri yok say';
$string['invalidcontextinhasanyquestions'] = 'Geçersiz bağlam question_context_has_any_questions\'a geçirildi.';
$string['linkedfiledoesntexist'] = '$a bağlantılı dosyası yok';
$string['makechildof'] = '\'$a\' nın alt ögesi yap';
$string['maketoplevelitem'] = 'En üste taşı';
$string['missingimportantcode'] = 'Bu soru tipinin önemli bir kodu eksik: $a.';
$string['modified'] = 'Son kaydetme';
$string['move'] = '$a dan taşı ve bağlantıları değiştir.';
$string['movecategory'] = 'Kategori Taşı';
$string['movedquestionsandcategories'] = 'Sorular ve soru kategorileri $a->oldplace\'dan $a->newplace\'a taşındı.';
$string['movelinksonly'] = 'Yalnızca bağların işaret ettiği yerleri değiştirin, dosyalarıhareket ettirmek ya da kopyalamada bulunmayın.';
$string['moveq'] = 'Soruları taşıyın';
$string['moveqtoanothercontext'] = 'Soruyu başka bağlama taşıyın';
$string['movingcategory'] = 'Kategoriyi Taşımak';
$string['movingcategoryandfiles'] = '{$a->name}kategorisini ve tüm ast kategorileri \"{$a->contextto}\"  bağlamına taşımak istediğinizden emin misiniz?<br /> {$a->fromareaname}içindeki sorulara bağlı {$a->urlcount} dosyaları bulduk, bunları kopyalamak ya da {$a->toareaname}\'a taşımak ister misiniz?';
$string['movingcategorynofiles'] = '\"{$a->name}\" kategorisini ve tüm ast kategorileri \"{$a->contextto}\"
için bağlama taşımak istediğinizden emin misiniz?';
$string['movingquestions'] = 'Soruları ve Her Dosyayı Taşımak';
$string['movingquestionsandfiles'] = '{$a->name}kategorisini <strong>\"{$a->tocontext}\"</strong>?bağlamına taşımak istediğinizden emin misiniz?<br {$a->fromareaname}içindeki sorulara bağlı <strong>{$a->urlcount} files</strong> dosyaları bulduk, bunları kopyalamak ya da {$a->toareaname}\'a taşımak ister misiniz?';
$string['movingquestionsnofiles'] = 'Soru(yu)/(ları){$a->questions}<strong>\"{$a->tocontext}\"</strong>?<br /> bağlamına taşımak istediğinizden emin misiniz? {$a->fromareaname}içinde bu soru(ya)/(lara) bağlı hiç <strong>dosya</strong> yok.';
$string['needtochoosecat'] = 'Bu soruyu taşımak için bir kategori seçmeniz gerekir ya da \'iptal\'e basın.';
$string['nopermissionadd'] = 'Buraya soru ekleme izniniz yok.';
$string['nopermissionmove'] = 'Buradan hiçbir soruyu taşımaya izniniz yok. Bu kategorideki soruyu kaydetmeli ya da bunu yeni bir soru olarak kaydetmelisiniz.';
$string['noprobs'] = 'Soru veritabanında hiç bir sorun bulunamadı.';
$string['notenoughdatatoeditaquestion'] = 'Ne soru id, ne de kategori id ve soru tipi belirtilmedi.';
$string['notenoughdatatomovequestions'] = 'Taşımak istediğiniz soruların soru ID\'lerini sağlamanız gerekir.';
$string['permissionedit'] = 'Bu soruyu düzenle';
$string['permissionmove'] = 'Bu soruyu taşı';
$string['permissionsaveasnew'] = 'Bu soruyu yeni soru olarak kaydet';
$string['permissionto'] = 'İzinleriniz:';
$string['published'] = 'paylaşıldı';
$string['questionaffected'] = '<a href=\"$a->qurl\">Soru \"$a->name\" ($a->qtype)</a> bu soru kategorisindedir ancak <a href=\"$a->qurl\"> \"$a->coursename\" bir başka dersteki \"$a->quizname\"</a> quizinde de kullanılıyor.';
$string['questionbank'] = 'Soru bankası';
$string['questioncategory'] = 'Soru kategorisi';
$string['questioncatsfor'] = '\'$a\' için Soru Kategorileri';
$string['questiondoesnotexist'] = 'Bu soru yok';
$string['questionsmovedto'] = 'Hâlâ kullanımda olan sorular üst ders kategorisinde \"$a\"\'ya taşındı.';
$string['questionsrescuedfrom'] = '$a bağlamından kaydedilmiş sorular.';
$string['questionsrescuedfrominfo'] = 'Bu sorular (bazıları gizli olabilir)$a bağlamı silindiğinde saklanmıştı çünkü bunlar hâlâ bazı küçük sınavlar ve etkinlikler tarafından kullanılmakta.';
$string['questionuse'] = 'Bu etkinlikte soruyu kullan';
$string['shareincontext'] = '$a bağlamında paylaş';
$string['tofilecategory'] = 'Kategoriyi dosyaya yaz';
$string['tofilecontext'] = 'Bağlamı dosyaya yaz';
$string['unknown'] = 'Bilinmeyen';
$string['unknownquestiontype'] = 'Bilinmeyen soru tipi: $a.';
$string['unpublished'] = 'paylaşılmadı';
$string['upgradeproblemcategoryloop'] = 'Soru kategorilerini yükseltirken görülen sorun. Kategori ağacında döngü var. ETkilenmiş kategori idleri $a.';
$string['upgradeproblemcouldnotupdatecategory'] = 'Soru kategorisi $a->name ($a->id)\'yi güncelleyemedi.';
$string['upgradeproblemunknowncategory'] = 'Soru kategorileri yükseltilirken sorunla karşılaşıldı. $a->id kategorisi $a->parent üstüne işaret eder, ki bu da mevcut değildir. Sorunu çözmek için üst değiştirildi.';
$string['yourfileshoulddownload'] = 'Dışa verim dosyanızın birazdan indirmeye başlaması gerekir. Başlamazsa, lütfen <a href=\"$a\">click here</a>. Sorunu çözmek için üst değiştirildi.';

?>
