<?PHP // $Id$ 
      // auth.php - created with Moodle 1.9.5 (Build: 20090515) (2007101550)


$string['actauthhdr'] = 'Aktivni dodatak za proveru identiteta';
$string['alternatelogin'] = 'Ako ovde unesete URL, biće korišćen kao stranica za prijavu na ovaj sajt. Stranica bi trebala sadržati formu sa akcijskom opcijom podešenom na <strong>\'$a\'</strong> i vraćanjem polja <strong>username</strong> i <strong>password</strong>.<br />Budite oprezni da ne biste slučajno uneli pogrešan URL i time sami sebi onemogućili pristup sajtu.<br />Ostavite ovo podešavanje prazno da biste koristili podrazumevanu stranicu za pristup sistemu.';
$string['alternateloginurl'] = 'Alternativni URL za prijavu na sistem';
$string['auth_changepasswordhelp'] = 'Promena pomoći za lozinku';
$string['auth_changepasswordhelp_expl'] = 'Prikaz pomoći za slučaj izgubljene lozinke korisnicima koji su izgubili svoju $a lozinku. To će biti prikazano ili isto kao ili umesto <strong>URL-a za promenu lozinke</strong> ili interne promene Moodle lozinke.';
$string['auth_changepasswordurl'] = 'URL za promenu lozinke';
$string['auth_changepasswordurl_expl'] = 'Specificirajte URL koji će se slati korisnicima koji izgube svoje $a lozinke. Podesite<strong>Koristiti standardnu stranicu za promenu lozinke</strong> na <strong>Ne</strong>.';
$string['auth_common_settings'] = 'Opšta podešavanja';
$string['auth_data_mapping'] = 'Mapiranje podataka';
$string['auth_fieldlock'] = 'Zaključavanje vrednosti';
$string['auth_fieldlock_expl'] = '<p><b>Zaključavanje vrednosti:</b> Ako je omogućeno, sprečiće Moodle korisnike i administratore da direktno uređuju polje. Koristite ovu opciju ako održavate ove podatke u eksternom autentikacionom sistemu. </p>';
$string['auth_fieldlocks'] = 'Zaključavanje korisničkih polja';
$string['auth_fieldlocks_help'] = '<p>Možete zaključati polja sa korisničkim podacima. To je korisno za sajtove na kojima korisničke podatke ručno održavaju administratori uređivanjem korisničkih zapisa u bazi podataka ili postavljanjem podataka korišćenjem mogućnosti za postavljanje korisnika iz drugih izvora. Ako zaključavate polja koja su neophodna za rad Moodle sistema, proverite da li ste omogućili korišćenje tih podataka pri kreiranju korisničkih naloga &emdash; jer se u suprotnom nalozi neće moći koristiti.</p><p>Razmotrite podešavanje moda za taključavanje na \'Otključano ako je prazno\' da biste izbegli taj problem.</p>';
$string['auth_multiplehosts'] = 'Određivanje više domaćina ili adresa (npr. host1.com;host2.com;host3.com) ili (npr. xxx.xxx.xxx.xxx;xxx.xxx.xxx.xxx)';
$string['auth_remove_delete'] = 'Potpuno brisanje internih podataka';
$string['auth_remove_keep'] = 'Zadržavanje internih podataka';
$string['auth_remove_suspend'] = 'Obustavljanje internih podataka';
$string['auth_remove_user'] = 'Odredite šta raditi sa unutrašnjim korisničkim nalogom za vreme masovne sinhronizacije kada je korisnik uklonjen od strane spoljnog izvora. Samo obustavljeni korisnici se automatski obnavljaju ako se ponovo pojavljuju u spoljnom izvoru.';
$string['auth_remove_user_key'] = 'Uklonjen spoljni korisnik';
$string['auth_sync_script'] = 'Skripta sinhronizacije krona';
$string['auth_updatelocal'] = 'Ažuriranje lokalnih podataka';
$string['auth_updatelocal_expl'] = '<p><b>Ažuriranje lokalnih podataka:</b> Ako je omogućeno, polje će biti ažurirano (koristi se eksterni auth) svaki put kada korisnik pristupi sistemu ili dođe do korisničke sinhronizacije. Polja za koja je podešeno lokalno ažuriranje bi trebala biti zaključana.</p>';
$string['auth_updateremote'] = 'Ažuriranje eksternih podataka';
$string['auth_updateremote_expl'] = '<p><b>Ažuriranje eksternih podataka:</b> Ako je omogućeno, eksterni auth će biti ažuriran pri ažuriranju zapisa o korisnicima. Polja bi trebala biti otključana da bi se dozvolile promene.</p>';
$string['auth_updateremote_ldap'] = '<p><b>Napomene:</b> Ažuriranje eksternih LDAP podataka zahteva da podesite povezivanje binddn i bindpw za bind-korisnika sa privilegijama korigovanja svih korisničkih zapisa. Ovo trenutno ne čuva viševrednosne atribute i ukloniće dodatne vrednosti nadogradnje.</p>';
$string['auth_user_create'] = 'Omogućiti kreiranje korisnika';
$string['auth_user_creation'] = 'Novi (anonimni) korisnici mogu napraviti korisničke naloge na spoljašnjem izvoru za proveru identiteta i izvršiti potvrdu putem e-pošte. Ako omogućite ovu opciju, konfigurišite i specifične opcije modula koje služe za kreiranje korisnika.';
$string['auth_usernameexists'] = 'Odabrano korisničko ime već postoji. Molimo izaberite drugo korisničko ime.';
$string['authenticationoptions'] = 'Opcije za proveru identiteta';
$string['authinstructions'] = 'Ovde možete dati instrukcije Vašim korisnicima, tako da znaju koje korisničko ime i lozinku treba da koriste. Tekst koji ovde napišete biće prikazan na stranici za pristup sistemu. Ako polje ostavite prazno, onda instrukcije neće biti prikazane.';
$string['changepassword'] = 'URL za promenu lozinke';
$string['changepasswordhelp'] = 'Ovde možete zadati lokaciju na kojoj Vaši korisnici mogu obnoviti ili promeniti svoje korisničko ime/lozinku, u slučaju da su je zaboravili.
Ova opcija se može ponuditi korisnicima u vidu dugmeta na stranici za pristup sistemu i njihovoj korisničkoj strani. Ako ostavite prazno polje, dugme neće biti prikazano.';
$string['chooseauthmethod'] = 'Izaberite način provere identiteta';
$string['createpasswordifneeded'] = 'Kreiranje lozinke ako je to potrebno';
$string['enterthenumbersyouhear'] = 'Unesite broj koji čujete';
$string['enterthewordsabove'] = 'Unesite reč iznad';
$string['errormaxconsecutiveidentchars'] = 'Maksimalan broj istovetnih karaktera za redom koje mora sadržati lozinka je: $a';
$string['errorminpassworddigits'] = 'Minimalan broj cifara koji lozinka mora sadržati je: $a.';
$string['errorminpasswordlength'] = 'Minimalan broj karaktera koji lozinka mora sadržati je: $a.';
$string['errorminpasswordlower'] = 'Minimalan broj malih slova koji lozinka mora sadržati je: $a.';
$string['errorminpasswordnonalphanum'] = 'Minimalan broj karaktera koji nisu alfanumerički koji lozinka mora sadržati je: $a.';
$string['errorminpasswordupper'] = 'Minimalan broj velikih slova koji lozinka mora sadržati je: $a.';
$string['errorpasswordupdate'] = 'Greška u ažuriranju lozinke, lozinka nije promenjena.';
$string['forcechangepassword'] = 'Obavezna promena lozinke';
$string['forcechangepassword_help'] = 'Obavezna promena lozinke za sve korisnike pri njihovom sledećem pristupu Moodle sistemu';
$string['forcechangepasswordfirst_help'] = 'Obavezna promena lozinke za sve korisnike pri njihovom prvom pristupu Moodle sistemu';
$string['forgottenpassword'] = 'Ukoliko ovde unesete URL adresu, ona će biti korišćena za stranicu za obnavljanje zaboravljene lozinke, na ovom sajtu. Ovo je namenjeno sajtovima na kojima se lozinkama, u potpunosti, upravlja izvan Moodlea. Ostavite ovo polje prazno da biste koristili uobičajeni način za obnavljanje lozinke.';
$string['forgottenpasswordurl'] = 'URL adresa za obnavljanje zaboravljene lozinke';
$string['getanaudiocaptcha'] = 'Dobijanje zvučnog CAPTCHA';
$string['getanimagecaptcha'] = 'Dobijanje CAPTCHA slike';
$string['getanothercaptcha'] = 'Dobijanje drugog CAPTCHA';
$string['guestloginbutton'] = 'Dugme za prijavu gostiju';
$string['incorrectpleasetryagain'] = 'Neispravno. Molimo pokušajte ponovo';
$string['infilefield'] = 'Polje zahtevano u datoteci';
$string['instructions'] = 'Uputstva';
$string['internal'] = 'Interno';
$string['locked'] = 'Zaključano';
$string['md5'] = 'MD5 kodiranje';
$string['nopasswordchange'] = 'Nije moguće promeniti lozinku';
$string['nopasswordchangeforced'] = 'Niste u mogućnosti da nastavite dalje bez promene korisničkog imena, međutim ne postoji raspoloživa stranica za promenu. Molimo kontaktirajte Moodle administratora.';
$string['passwordhandling'] = 'Upravljenje poljem lozinke';
$string['plaintext'] = 'Običan tekst';
$string['pluginnotenabled'] = 'Dodatak za proveru identiteta \'$a\' nije osposobljen.';
$string['pluginnotinstalled'] = 'Dodatak za proveru identiteta \'$a\' nije instaliran.';
$string['recaptcha'] = 'reCAPTCHA (ponovo)';
$string['selfregistration'] = 'Samoregistracija';
$string['selfregistration_help'] = 'Izaberite koji dodatak za proveru identiteta  će rukovati samoregistracijom korisnika';
$string['sha1'] = 'SHA-1 heš';
$string['showguestlogin'] = 'Možete sakriti ili prikazati dugme za prijavu gostiju na prijavnoj stranici.';
$string['stdchangepassword'] = 'Upotreba standardne stranice za promenu lozinke';
$string['stdchangepassword_expl'] = 'Ako spoljašnji sistem za proveru identiteta dozvoljava promenu lozinke iz Moodle sistema, uključite ga. Ovo podešavanje zaobilazi \'URL za promenu lozinke\'.';
$string['stdchangepassword_explldap'] = 'Napomena: Preporučuje se da koristite LDAP pre nego SSL šifrovanje tunela (ldaps://) ako je LDAP server udaljen.';
$string['unlocked'] = 'Otključano';
$string['unlockedifempty'] = 'Otključano ako je prazno';
$string['update_never'] = 'Nikad';
$string['update_oncreate'] = 'Pri kreiranju';
$string['update_onlogin'] = 'Pri svakom pristupu sistemu';
$string['update_onupdate'] = 'Pri ažuriranju';
$string['user_activatenotsupportusertype'] = 'auth: ldap user_activate() ne podržava izabrani tip korisnika: $a';
$string['user_disablenotsupportusertype'] = 'auth: ldap user_activate() ne podržava izabrani tip korisnika (...još)';
$string['CASform'] = 'Izbor provere identiteta'; // ORPHANED
$string['accesCAS'] = 'CAS korisnici'; // ORPHANED
$string['accesNOCAS'] = 'Ostali korisnici'; // ORPHANED
$string['auth_cas_auth_user_create'] = 'Eksterno kreiranje korisnika'; // ORPHANED
$string['auth_cas_baseuri'] = 'URI servera (ništa ako nije podešen baseUri)<br />Na primer, ako CAS server odgovara domenu host.domaine.fr/CAS/ onda je <br />cas_baseuri = CAS/'; // ORPHANED
$string['auth_cas_baseuri_key'] = 'Base URI'; // ORPHANED
$string['auth_cas_broken_password'] = 'Niste u mogućnosti da nastavite dalje bez promene korisničkog imena, međutim ne postoji raspoloživa stranica za promenu. Molimo kontaktirajte Moodle administratora.'; // ORPHANED
$string['auth_cas_cantconnect'] = 'LDAP deo CAS-modula nije u mogućnosti da se poveže na server: $a'; // ORPHANED
$string['auth_cas_casversion'] = 'Verzija'; // ORPHANED
$string['auth_cas_changepasswordurl'] = 'URL za promenu lozinke'; // ORPHANED
$string['auth_cas_create_user'] = 'Uključite ovo podešavanje ako želite da ubacite korisnike za koje je izvršena CAS provera identiteta u Moodle bazu podataka. Ako to ne želite, samo korisnici koji već postoje u Moodle bazi podataka će moći da pristupe sistemu.'; // ORPHANED
$string['auth_cas_create_user_key'] = 'Kreiraj korisnika'; // ORPHANED
$string['auth_cas_enabled'] = 'Uključite ovo podešavanje ako želite da koristite CAS proveru identiteta.'; // ORPHANED
$string['auth_cas_hostname'] = 'Naziv domaćina CAS servera <br />npr. host.domain.fr'; // ORPHANED
$string['auth_cas_hostname_key'] = 'Naziv domaćina'; // ORPHANED
$string['auth_cas_invalidcaslogin'] = 'Nažalost, Vaša prijava nije uspela - niste mogli biti autorizovani'; // ORPHANED
$string['auth_cas_language'] = 'Odabrani jezik'; // ORPHANED
$string['auth_cas_language_key'] = 'Jezik'; // ORPHANED
$string['auth_cas_logincas'] = 'Pristup preko sigurne veze'; // ORPHANED
$string['auth_cas_logoutcas'] = 'Postavite ovo na \"DA\" ako želite da se odjavite sa CASa nakon okončanja veze na Moodle'; // ORPHANED
$string['auth_cas_logoutcas_key'] = 'CAS odjava'; // ORPHANED
$string['auth_cas_multiauth'] = 'Postavite ovo na \"DA\" ako želite da imate višestruku proveru identiteta (CAS + ostale provere identiteta)'; // ORPHANED
$string['auth_cas_multiauth_key'] = 'Višestruka provera identiteta'; // ORPHANED
$string['auth_cas_port'] = 'Port CAS servera'; // ORPHANED
$string['auth_cas_port_key'] = 'Port'; // ORPHANED
$string['auth_cas_proxycas'] = 'Postavite ovo na \"DA\" ako koristite  CAS u proxy modu'; // ORPHANED
$string['auth_cas_proxycas_key'] = 'Proxy mod'; // ORPHANED
$string['auth_cas_server_settings'] = 'Konfiguracija CAS servera'; // ORPHANED
$string['auth_cas_text'] = 'Sigurna veza'; // ORPHANED
$string['auth_cas_use_cas'] = 'Korišćenje CAS-a'; // ORPHANED
$string['auth_cas_version'] = 'CAS verzija'; // ORPHANED
$string['auth_casdescription'] = 'Ovaj način koristi CAS server (Central Authentication Service) za proveru identiteta korisnika u Single Sign On okruženju (SSO). Možete koristiti i jednostavnu LDAP proveru identiteta. Ako su dato korisničko ime i lozinka validni prema CAS-u, Moodle kreira novi korisnički unos u svojoj bazi podataka, po potrebi preuzimajući atribute korisnika iz LDAP-a. Pri sledećim pristupima vrši se samo provera korisničkog imena i lozinke.'; // ORPHANED
$string['auth_casnotinstalled'] = 'Nije moguće korišćenje  CAS provere identiteta. PHP LDAP modul nije instaliran.'; // ORPHANED
$string['auth_castitle'] = 'Koristiti CAS server (SSO)'; // ORPHANED
$string['auth_changingemailaddress'] = 'Tražili ste izmenu adrese e-pošte od $a->oldemail na $a->newemail. Iz bezbednosnih razloga, šaljemo Vam e-poruku na novu adresu da potvrdite da ona pripada Vama. Vaša adresa e-pošte biće ažurirana čim otvorite URL link koji Vam je poslat u toj poruci.'; // ORPHANED
$string['auth_dbcantconnect'] = 'Nije moguće povezivanje na navedenu bayu podataka ya proveru identiteta'; // ORPHANED
$string['auth_dbchangepasswordurl_key'] = 'URL za promenu lozinke'; // ORPHANED
$string['auth_dbdebugauthdb'] = 'Uklanjanje grešaka iz ADO baze podataka'; // ORPHANED
$string['auth_dbdebugauthdbhelp'] = 'Uklanjanje grešaka iz povezivanja ADO baze podataka na spoljnu bazu bazu podataka - koristiti kod dobijanja prazne stranice za vreme prijavljivanja. Nije pogodno za produkcione sajtove.'; // ORPHANED
$string['auth_dbdeleteuser'] = 'Uklonjen korisnik  $a[0] id $a[1]'; // ORPHANED
$string['auth_dbdeleteusererror'] = 'Greška pri uklanjanju korisnika  $a'; // ORPHANED
$string['auth_dbdescription'] = 'Ovaj metod koristi tabelu spoljašnje baze podataka za proveru da li su dodeljeno korisničko ime i lozinka ispravni. Ako je nalog nov, onda informacija iz ostalih polja može biti kopirana u Moodle.'; // ORPHANED
$string['auth_dbextencoding'] = 'Spoljno kodiranje baze podataka'; // ORPHANED
$string['auth_dbextencodinghelp'] = 'Kodiranje korišćeno u spoljnoj bazi podataka'; // ORPHANED
$string['auth_dbextrafields'] = 'Ova polja su izborna. Možete izabrati da prethodno popunite neka Moodle korisnička polja sa informacijama iz <b>polja spoljašnje baze podataka</b> koja naznačite ovde. <br />Ako ih ostavite prazne, onda će biti korišćene podrazumevane vrednosti.<br /> U svakom slučaju, korisnik će biti u mogućnosti da uređuje sva polja nakon prijavljivanja.'; // ORPHANED
$string['auth_dbfieldpass'] = 'Ime polja koje sadrži lozinke'; // ORPHANED
$string['auth_dbfieldpass_key'] = 'Polje za lozinku'; // ORPHANED
$string['auth_dbfielduser'] = 'Ime polja koje sadrži korisnička imena'; // ORPHANED
$string['auth_dbfielduser_key'] = 'Polje za korisničko ime'; // ORPHANED
$string['auth_dbhost'] = 'Računar domaćin servera baze podataka.'; // ORPHANED
$string['auth_dbhost_key'] = 'Domaćin'; // ORPHANED
$string['auth_dbinsertuser'] = 'Dodat korisnik $a[0] id $a[1]'; // ORPHANED
$string['auth_dbinsertusererror'] = 'Greška pri dodavanju korisnika'; // ORPHANED
$string['auth_dbname'] = 'Naziv baze podataka'; // ORPHANED
$string['auth_dbname_key'] = 'Naziv baze podataka'; // ORPHANED
$string['auth_dbpass'] = 'Lozinka koja odgovara gore navedenom korisničkom imenu'; // ORPHANED
$string['auth_dbpass_key'] = 'Lozinka'; // ORPHANED
$string['auth_dbpasstype'] = '<p>Zadajte format koje koristi polje za lozinku. MD5 šifrovanje je korisno prilikom povezivanja na ostale često korišćene Web aplikacije kao što je PostNuke.</p> <p> Upotrebite opciju \'interno\' ako želite da spoljašnja baza podataka vodi računa o korisničkim imenima i adresama e-pošte, ali da sam Moodle bude nadležan za lozinke. Ako koristite opciju \'interno\', <i>morate</i> obezbediti pristup popunjenom polju za adrese e-pošte u spoljašnjoj bazi podataka, i morate redovno izvršavati admin/cron.php. Moodle će slati e-poruke novim korisnicima sa njihovim privremenim lozinkama.</p>'; // ORPHANED
$string['auth_dbpasstype_key'] = 'Format lozinke'; // ORPHANED
$string['auth_dbreviveduser'] = 'Ponovo dodat korisnik $a[0] id $a[1]'; // ORPHANED
$string['auth_dbrevivedusererror'] = 'Greška pri ponovnom dodavanju korisnika $a'; // ORPHANED
$string['auth_dbsetupsql'] = 'SQL naredba za podešavanje'; // ORPHANED
$string['auth_dbsetupsqlhelp'] = 'SQL naredba za specijalno podešavanje baze  podataka, često korišćeno za podešavanje kodiranja komunikacije - primer za MySQL and PostgreSQL: <em>SET NAMES \'utf8\'</em>'; // ORPHANED
$string['auth_dbsuspenduser'] = 'Obustavljen rad korisnika $a[0] id $a[1]'; // ORPHANED
$string['auth_dbsuspendusererror'] = 'Greška pri obustavljanju rada korisnika $a[0] id $a[1]'; // ORPHANED
$string['auth_dbsybasequoting'] = 'Korišćenje sybase navodnika'; // ORPHANED
$string['auth_dbsybasequotinghelp'] = 'Sybase stil izlaza jednostrukim navodnicima - potrebno za Oracle, MS SQL i neke druge baze podataka. Ne koristiti za  MySQL!'; // ORPHANED
$string['auth_dbtable'] = 'Ime tabele u bazi podataka'; // ORPHANED
$string['auth_dbtable_key'] = 'Tabela'; // ORPHANED
$string['auth_dbtitle'] = 'Koristiti spoljašnju bazu podataka'; // ORPHANED
$string['auth_dbtype'] = 'Tip baze podataka (Pogledajte <a href=\"../lib/adodb/readme.htm#drivers\">ADOdb dokumentaciju</a> za detalje)'; // ORPHANED
$string['auth_dbtype_key'] = 'Baza podataka'; // ORPHANED
$string['auth_dbupdatinguser'] = 'Ažuriranje korisnika $a[0] id $a[1]'; // ORPHANED
$string['auth_dbuser'] = 'Korisničko ime sa pristupom čitanju korisničke baze'; // ORPHANED
$string['auth_dbuser_key'] = 'Korisnik baze podataka'; // ORPHANED
$string['auth_dbusernotexist'] = 'Nije moguće ažuriranje nepostojećeg korisnika: $a'; // ORPHANED
$string['auth_dbuserstoadd'] = 'Stavke korisnika za dodavanje: $a'; // ORPHANED
$string['auth_dbuserstoremove'] = 'Stavke korisnika za uklanjanje: $a'; // ORPHANED
$string['auth_emailchangecancel'] = 'Otkaži promenu adrese e-pošte'; // ORPHANED
$string['auth_emailchangepending'] = 'Promena se uspostavlja. Otvorite link kji Vam je poslat na $a->preference_newemail.'; // ORPHANED
$string['auth_emaildescription'] = 'Potvrđivanje putem e-pošte je uobičajen način provere identiteta. Nakon što se korisnik prijavi i izabere svoje novo ime i lozinku, e-pošta se šalje na adresu tog korisnika. U e-pošti se nalazi sigurnosni link prema stranici gde novi korisnik potvrđuje svoj nalog. Pri svakom narednom pristup uneti podaci se samo upoređuju sa onima koji su sačuvani u Moodle bazi podataka.'; // ORPHANED
$string['auth_emailnoemail'] = 'Pokušaj slanja e-pošte nije uspeo!'; // ORPHANED
$string['auth_emailnoinsert'] = 'Nije moguće dodati dati zapis u bazu podataka!'; // ORPHANED
$string['auth_emailnowexists'] = 'Adresa e-pošte koju ste hteli pridružiti Vašem profilu već je dodeljena nekome drugome od Vašeg provobitnog zahteva. Stoga je Vaš zahtev za promenu adrese e-pošte odbijen, ali možete pokušati ponovo za različitu adresu.'; // ORPHANED
$string['auth_emailrecaptcha'] = 'Dodaje element na formi za audio/vizuelnu potvrdu na stranicu za upis za korisnike koji se sami prijavljuju na sajt putem e-poruke. Ovo štiti Vaš sajt protiv neželjenih poruka. Vidite http://recaptcha.net/learnmore.html za više detalja.'; // ORPHANED
$string['auth_emailrecaptcha_key'] = 'Uključi reCAPTCHA element'; // ORPHANED
$string['auth_emailsettings'] = 'Podešavanja'; // ORPHANED
$string['auth_emailtitle'] = 'Provera identiteta putem e-pošte'; // ORPHANED
$string['auth_emailupdate'] = 'Ažuriranje adrese e-pošte'; // ORPHANED
$string['auth_emailupdatemessage'] = 'Dragi korisniče $a->fullname,
Zahtevali ste izmenu Vaše adrese e-pošte za korisnički nalog na $a->site. Molimo Vas da otvorite sledeći URL link u Vašem Web čitaču da biste potvrdili ovu izmenu.
$a->url'; // ORPHANED
$string['auth_emailupdatesuccess'] = 'Adresa e-pošte korisnika <em>$a->fullname</em> uspešno je ažurirana na <em>$a->email</em>.'; // ORPHANED
$string['auth_emailupdatetitle'] = 'Potvrda ažuriranja adrese e-pošte na $a->site'; // ORPHANED
$string['auth_fcchangepasswordurl'] = 'URL za promenu lozinke'; // ORPHANED
$string['auth_fcconnfail'] = 'Povezivanje nije uspelo - greška:$a[0] i tekst greške: $a[1]'; // ORPHANED
$string['auth_fccreators'] = 'Lista grupa čijim saradnicima je dozvoljeno da kreiraju nove kurseve. Odvojite spojene grupe sa \';\'. Imena moraju biti napisana upravo onako kao na FirstClass serveru. Sistem vodi računa o velikim i malim slovima.'; // ORPHANED
$string['auth_fccreators_key'] = 'Tvorac'; // ORPHANED
$string['auth_fcdescription'] = 'Ova metoda koristi FirstClass server za proveru da li su dodeljeno korisničko ime i lozinka ispravni.'; // ORPHANED
$string['auth_fcfppport'] = 'Serverski port (3333 je najčešći)'; // ORPHANED
$string['auth_fcfppport_key'] = 'Port'; // ORPHANED
$string['auth_fchost'] = 'Adresa FirstClass servera. Koristite IP broj ili DSN ime.'; // ORPHANED
$string['auth_fchost_key'] = 'Domaćin'; // ORPHANED
$string['auth_fcpasswd'] = 'Lozinka za gornji nalog.'; // ORPHANED
$string['auth_fcpasswd_key'] = 'Lozinka'; // ORPHANED
$string['auth_fctitle'] = 'Koristiti FirstClass server'; // ORPHANED
$string['auth_fcuserid'] = 'Korisnik FirstClass naloga sa kompletnim privilegijama \'podadministrator\'.'; // ORPHANED
$string['auth_fcuserid_key'] = 'Identifikator korisnika'; // ORPHANED
$string['auth_imapchangepasswordurl_key'] = 'URL za promenu lozinke'; // ORPHANED
$string['auth_imapdescription'] = 'Ovaj metod koristi IMAP server da proveri da li su dodeljeno korisničko ime i lozinka ispravni.'; // ORPHANED
$string['auth_imaphost'] = 'IMAP adresa servera. Koristite IP broj, a ne DNS nazive.'; // ORPHANED
$string['auth_imaphost_key'] = 'Domaćin'; // ORPHANED
$string['auth_imapnotinstalled'] = 'Nije moguće korišćenje IMAP provere identiteta. PHP IMAP modul nije instaliran'; // ORPHANED
$string['auth_imapport'] = 'Broj porta IMAP servera. Obično je 143 ili 993.'; // ORPHANED
$string['auth_imapport_key'] = 'Port'; // ORPHANED
$string['auth_imaptitle'] = 'Koristiti IMAP server'; // ORPHANED
$string['auth_imaptype'] = 'Tip IMAP servera. IMAP serveri mogu imati različite tipove provere identiteta.'; // ORPHANED
$string['auth_imaptype_key'] = 'Tip'; // ORPHANED
$string['auth_invalidnewemailkey'] = 'Greška: Ako pokušavate potvrdu izmene adrese e-pošte, možda ste napravili grešku pri kopiranju URL linka koji smo Vam poslali putem e-pošte. Molimo Vas da kopirate adresu i pokušate ponovo.'; // ORPHANED
$string['auth_ldap_ad_create_req'] = 'Nije moguće kreirati korisnika u aktivnom direktorijumu. Proverite da li su ispunjeni da li su ispunjeni svi zahtevi da bi ova aktivnost uspela LDAPS povezivanje, vezivanje korisnika za odgovarajuća ovlašćenja, itd.)'; // ORPHANED
$string['auth_ldap_attrcreators'] = 'Spisak grupa ili konteksta čijim članovima je dopušteno da kreiraju osobine. Odvajati posebne grupe sa \';\'. Obično nešto nalik \'cn=nastavnici,ou=osoblje,o=mojaorg\''; // ORPHANED
$string['auth_ldap_attrcreators_key'] = 'Kreatori osobina'; // ORPHANED
$string['auth_ldap_auth_user_create_key'] = 'Eksterno kreiranje korisnika'; // ORPHANED
$string['auth_ldap_bind_dn'] = 'Ako želite da koristite veznog korisnika za pretragu korisnika, odredite to ovde. Nešto nalik na \'cn=ldapuser,ou=public,o=org\''; // ORPHANED
$string['auth_ldap_bind_dn_key'] = 'Karakteristično ime'; // ORPHANED
$string['auth_ldap_bind_pw'] = 'Lozinka za veznog korisnika.'; // ORPHANED
$string['auth_ldap_bind_pw_key'] = 'Lozinka'; // ORPHANED
$string['auth_ldap_bind_settings'] = 'Bind podešavanja'; // ORPHANED
$string['auth_ldap_changepasswordurl_key'] = 'URL za promenu lozinke'; // ORPHANED
$string['auth_ldap_contexts'] = 'Lista konteksta gde su korisnici locirani. Razdvojite različite kontekste sa \';\'. Na primer : \'ou=users,o=org; ou=others,o=org\''; // ORPHANED
$string['auth_ldap_contexts_key'] = 'Kontekst'; // ORPHANED
$string['auth_ldap_create_context'] = 'Ako omogućite kreiranje korisnika sa potvrdom putem e-pošte, naznačite kontekst u kom su korisnici kreirani. Trebalo bi da je taj kontekst drugačiji od konteksta ostalih korisnika da bi se sprečili sigurnosni problemi. Nema potrebe dodavati ovaj kontekst u ldap_context-variable, jer će Moodle potražiti korisnike iz tog sadržaja automatski.<br /><b>Napomena:</b> Morate izmeniti funkciju auth_user_create() u datoteci auth/ldap/lib.php da biste omogućili kreiranje korisnika'; // ORPHANED
$string['auth_ldap_create_context_key'] = 'Kontekst za novog korisnika'; // ORPHANED
$string['auth_ldap_create_error'] = 'Greška pri kreiranju novog  korisnika u LDAP.'; // ORPHANED
$string['auth_ldap_creators'] = 'Lista grupa čijim članovima je dozvoljeno kreiranje novih kurseva. Razdvojite višestruke grupe sa \';\'. Obično nešto poput \'cn=teachers,ou=staff,o=myorg\''; // ORPHANED
$string['auth_ldap_creators_key'] = 'Tvorci'; // ORPHANED
$string['auth_ldap_expiration_desc'] = 'Izaberite NE da onemogućite proveru isteka lozinke ili LDAP da učitate vreme isteka lozinke direktno sa LDAP-a.'; // ORPHANED
$string['auth_ldap_expiration_key'] = 'Prestanak važenja'; // ORPHANED
$string['auth_ldap_expiration_warning_desc'] = 'Broj dana pre isteka lozinke kad se korisniku šalje upozorenje o isticanju lozinke.'; // ORPHANED
$string['auth_ldap_expiration_warning_key'] = 'Upozorenje o prestanku važenja'; // ORPHANED
$string['auth_ldap_expireattr_desc'] = 'Opciono: Mimoiđite LDAP atribute koji su potrebni za čuvanje vremena prestanka važenja lozinke passwordExpirationTime'; // ORPHANED
$string['auth_ldap_expireattr_key'] = 'Atributi prestanka važenja'; // ORPHANED
$string['auth_ldap_graceattr_desc'] = 'Opciono: Mimoiđite poček unosa atributa'; // ORPHANED
$string['auth_ldap_gracelogin_key'] = 'Atribut odložene prijave'; // ORPHANED
$string['auth_ldap_gracelogins_desc'] = 'Omogućite LDAP podršku za poček unosa. Nakom isteka lozinke korisnik može pristupati sistemu sve dok je iznos počeka unosa 0. Ako je lozinka istekla omogućite ova podešavanja za prikazivanje poruke počeka unosa.'; // ORPHANED
$string['auth_ldap_gracelogins_key'] = 'Odložene prijave'; // ORPHANED
$string['auth_ldap_groupecreators'] = 'Spisak grupa ili konteksta čijim članovima je dopušteno da kreiraju grupe. Odvajati posebne grupe sa \';\'. Obično nešto nalik \'cn=nastavnici,ou=osoblje,o=mojaorg\''; // ORPHANED
$string['auth_ldap_groupecreators_key'] = 'Kreatori grupa'; // ORPHANED
$string['auth_ldap_host_url'] = 'Naznačite LDAP domaćina u URL-formi kao što je \'ldap://ldap.myorg.com/\' ili \'ldaps://ldap.myorg.com/\' Odvojite višestruke servere znakom \';\' da biste dobili podršku pri prevazilaženju problema vezanih za pad sistema'; // ORPHANED
$string['auth_ldap_host_url_key'] = 'URL domaćina'; // ORPHANED
$string['auth_ldap_ldap_encoding'] = 'Navedite kodiranje korišćeno od strane LDAP servera. Najverovatnije utf-8, MS AD v2 koristi podrazumevanu platformu kodiranja kao što je cp1252, cp1250, etc.'; // ORPHANED
$string['auth_ldap_ldap_encoding_key'] = 'LDAP kodiranje'; // ORPHANED
$string['auth_ldap_login_settings'] = 'Podešavanja vezana za pristup korisnika sistemu'; // ORPHANED
$string['auth_ldap_memberattribute'] = 'Opciono: Određuje korisnikov članski atribut, kad korisnik pripada grupi. Obično \'member\''; // ORPHANED
$string['auth_ldap_memberattribute_isdn'] = 'Opciono: Redefiniše rukovanje vrednostima atributa članova, ili 0 ili 1'; // ORPHANED
$string['auth_ldap_memberattribute_isdn_key'] = 'Atributi članova koriste dn'; // ORPHANED
$string['auth_ldap_memberattribute_key'] = 'Atributi članova'; // ORPHANED
$string['auth_ldap_no_mbstring'] = 'Potrebno je proširenje mbstringa za kreiranje korisnika u aktivnom direktorijumu.'; // ORPHANED
$string['auth_ldap_noconnect'] = 'LDAP modul nije u mogućnosti da se poveže na server: $a'; // ORPHANED
$string['auth_ldap_noconnect_all'] = 'LDAP modul nije u mogućnosti da se poveže na neki server: $a'; // ORPHANED
$string['auth_ldap_noextension'] = 'Upozorenje: Moguće je da PHP LDAP modul nije prisutan. Molimo proverite da li je instaliran i omogućen.'; // ORPHANED
$string['auth_ldap_objectclass'] = 'Opciono: Određuje objectClass koristeći ime/tražeći korisnika na ldap_user_type. Obično nema potrebe da ovo menjate.'; // ORPHANED
$string['auth_ldap_objectclass_key'] = 'Klase objekata'; // ORPHANED
$string['auth_ldap_opt_deref'] = 'Ustanovite kako upravljati usvojenim imenima u toku traženja. Izaberite jednu od pratećih vrednosti: 
\"Ne\" (LDAP_DEREF_NEVER) ili \"Da\" (LDAP_DEREF_ALWAYS)'; // ORPHANED
$string['auth_ldap_opt_deref_key'] = 'Opozovi usvojena imena'; // ORPHANED
$string['auth_ldap_passtype'] = 'Odredite format nove ili izmenjene lozinke na LDAP serveru.'; // ORPHANED
$string['auth_ldap_passtype_key'] = 'Format lozinke'; // ORPHANED
$string['auth_ldap_passwdexpire_settings'] = 'Podešavanja LDAP isteka lozinke'; // ORPHANED
$string['auth_ldap_preventpassindb'] = 'Izaberite \"da\" da biste sprečili čuvanje lozinki u Moodle bazi podataka.'; // ORPHANED
$string['auth_ldap_preventpassindb_key'] = 'Sakrij lozinke'; // ORPHANED
$string['auth_ldap_search_sub'] = 'Stavite vrednost <> 0 ako želite da tražite korisnike u potkontekstima'; // ORPHANED
$string['auth_ldap_search_sub_key'] = 'Pretraži podkontekst'; // ORPHANED
$string['auth_ldap_server_settings'] = 'Podešavanja LDAP servera'; // ORPHANED
$string['auth_ldap_unsupportedusertype'] = 'auth: ldap user_create() ne podržava odabrani tip korisnika: $a (..yet)'; // ORPHANED
$string['auth_ldap_update_userinfo'] = 'Ažurirajte informacije korisnika (ime, prezime, adrese...) iz LDAP-a u Moodle. Specificirajte podešavanja za mapiranje podataka prema sopstvenim potrebama.'; // ORPHANED
$string['auth_ldap_user_attribute'] = 'Atribut koji se koristi za ime/pretragu korisnika. Uglavnom je \'cn\'.'; // ORPHANED
$string['auth_ldap_user_attribute_key'] = 'Atributi korisnika'; // ORPHANED
$string['auth_ldap_user_exists'] = 'LDAP korisničko ime već postoji'; // ORPHANED
$string['auth_ldap_user_settings'] = 'Podešavanja pretrage korisnika'; // ORPHANED
$string['auth_ldap_user_type'] = 'Izaberite kako se korisnik čuva u LDAP. Ovo podešavanje takođe određuje kako će funkcionisati istek upisa, poček unosa i kreiranje korisnika.'; // ORPHANED
$string['auth_ldap_user_type_key'] = 'Tip korisnika'; // ORPHANED
$string['auth_ldap_usertypeundefined'] = 'config.user_type nije definisano ili funkcija ldap_expirationtime2unix ne podržava odabrani tip!'; // ORPHANED
$string['auth_ldap_usertypeundefined2'] = 'config.user_type nije definisano ili funkcija ldap_unixi2expirationtime ne podržava odabrani tip!'; // ORPHANED
$string['auth_ldap_version'] = 'Verzija LDAP protokola koju Vaš server koristi.'; // ORPHANED
$string['auth_ldap_version_key'] = 'Verzija'; // ORPHANED
$string['auth_ldapdescription'] = 'Ovaj metod služi za proveru identiteta od strane spoljašnjeg LDAP servera.
Ako su dodeljeno korisničko ime i lozinka ispravni, Moodle kreira novu instancu korisnika u svojoj bazi podataka.
Ovaj modul može čitati korisničke atribute sa LDAP-a i postaviti tražena polja u Moodle. Za sledeće upise samo se proveravaju korisničko ime i lozinka.'; // ORPHANED
$string['auth_ldapextrafields'] = 'Ova polja nisu obavezna. Možete izabrati da ispunite neka Moodle korisnička polja sa informacijama iz <b>LDAP polja</b> koja ovde odredite. <br />Ako polja ostavite prazna, onda se ništa neće prebaciti sa LDAP-a, tako da će biti korišćene podrazumevane Moodle vrednosti.<br />U svakom slučaju, korisnici mogu da uređuju ova polja nakon pristupa sistemu.'; // ORPHANED
$string['auth_ldapnotinstalled'] = 'Nije moguće korišćenje LDAP provere identiteta. The PHP LDAP modul nije instaliran.'; // ORPHANED
$string['auth_ldaptitle'] = 'Koristiti LDAP server.'; // ORPHANED
$string['auth_manualdescription'] = 'Ovaj metod uklanja korisnicima sve načine pravljenja njihovih sopstvenih naloga. Sve naloge mora ručno napraviti administrator.'; // ORPHANED
$string['auth_manualtitle'] = 'Samo za ručno pravljenje naloga'; // ORPHANED
$string['auth_mnet_auto_add_remote_users'] = 'Kada je postavljeno na \"Da\", slog lokalnog korisnika se automatski kreira kada se udaljeni korisnik prijavi prvi put.'; // ORPHANED
$string['auth_mnet_roamin'] = 'Ovi korisnici domaćina mogu ukrstariti u Vašu oblast.'; // ORPHANED
$string['auth_mnet_roamout'] = 'Vaši korisnici mogu iskrstariti na ove domaćine.'; // ORPHANED
$string['auth_mnet_rpc_negotiation_timeout'] = 'Prekid vremena za proveru identiteta  preko XMLRPC prenosa u sekundama.'; // ORPHANED
$string['auth_mnetdescription'] = 'Izvršena provera identiteta korisnika u skladu sa mrežom poverenja definisanom u podešavanjima Moodle mreže.'; // ORPHANED
$string['auth_mnettitle'] = 'Provera identiteta u Moodle mreži'; // ORPHANED
$string['auth_nntpchangepasswordurl_key'] = 'URL za promenu lozinke'; // ORPHANED
$string['auth_nntpdescription'] = 'Ovaj metod koristi NNTP server za proveru ispravnosti korisničkih imena i lozinki.'; // ORPHANED
$string['auth_nntphost'] = 'NNTP adrese servera. Koristite IP broj, a ne DNS nazive.'; // ORPHANED
$string['auth_nntphost_key'] = 'Domaćin'; // ORPHANED
$string['auth_nntpnotinstalled'] = 'Nije moguće koristiti NNTP proveru identiteta. PHP IMAP modul nije instaliran.'; // ORPHANED
$string['auth_nntpport'] = 'Serverski port (119 je najčešći)'; // ORPHANED
$string['auth_nntpport_key'] = 'Port'; // ORPHANED
$string['auth_nntptitle'] = 'Koristiti NNTP server.'; // ORPHANED
$string['auth_nologindescription'] = 'Pomoćni dadatak koji sprečava korisnike da se prijave na sistem i takođe odbacuje svako slanje pošte korisniku. Može se koristiti za <em>suspend</em> korisničke naloge.'; // ORPHANED
$string['auth_nologintitle'] = 'Nema prijave'; // ORPHANED
$string['auth_nonedescription'] = 'Korisnici se mogu upisati i odmah napraviti važeće naloge, bez provere identiteta od strane spoljašnjeg servera i bez potvrde putem e-pošte.
Budite oprezni kad koristite ovu opciju - mislite na sigurnost i administrativne probleme koji njome mogu biti prouzrokovani!'; // ORPHANED
$string['auth_nonetitle'] = 'Nema provere identiteta'; // ORPHANED
$string['auth_ntlmsso'] = 'NTLM SSO'; // ORPHANED
$string['auth_ntlmsso_enabled'] = 'Postavite na Da za pokušaj jedne prijave sa NTLM domenom. <strong>Napomena:</strong> da bi ovo radilo, zahtevaju se dodatna podešavanja Web-servera, videti <a href=\"http://docs.moodle.org/en/NTLM_authentication\">http://docs.moodle.org/en/NTLM_authentication</a>'; // ORPHANED
$string['auth_ntlmsso_enabled_key'] = 'Uključi'; // ORPHANED
$string['auth_ntlmsso_subnet'] = 'Ako je uključeno, pokušaće samo sa klijentima iz ove podmreže. Format: xxx.xxx.xxx.xxx/bitmas'; // ORPHANED
$string['auth_ntlmsso_subnet_key'] = 'Podmreža'; // ORPHANED
$string['auth_outofnewemailupdateattempts'] = 'Više nemate pravo na pokušaje ažuriranja Vaše adrese e-pošte. Vaš zahtev za ažuriranje je odbijen.'; // ORPHANED
$string['auth_pamdescription'] = 'Ovaj metod koristi PAM za pristup korisničkom imenu na domaćem serveru. Morate instalirati <a href=\"http://www.math.ohio-state.edu/~ccunning/pam_auth/\" target=\"_blank\">PHP4 PAM proveru identiteta</a> da biste koristili ovaj modul.'; // ORPHANED
$string['auth_pamtitle'] = 'PAM (Pluggable Authentication Modules)'; // ORPHANED
$string['auth_passwordisexpired'] = 'Vaša lozinka je istekla. Želite li sad da je promenite?'; // ORPHANED
$string['auth_passwordwillexpire'] = 'Vaša lozinka će isteći za $a dana. Želite li sad da je promenite?'; // ORPHANED
$string['auth_pop3changepasswordurl_key'] = 'URL za promenu lozinke'; // ORPHANED
$string['auth_pop3description'] = 'Ovaj metod koristi POP3 server za proveru ispravnosti korisničkih imena i lozinki.'; // ORPHANED
$string['auth_pop3host'] = 'POP3 adresa servera. Koristite IP broj, a ne DNS naziv.'; // ORPHANED
$string['auth_pop3host_key'] = 'Domaćin'; // ORPHANED
$string['auth_pop3mailbox'] = 'Naziv mailbox-a s kojim treba uspostaviti vezu. (obično INBOX)'; // ORPHANED
$string['auth_pop3mailbox_key'] = 'Poštansko sanduče'; // ORPHANED
$string['auth_pop3notinstalled'] = 'Nije moguće koristiti POP3 proveru identiteta. PHP IMAP modul nije instaliran.'; // ORPHANED
$string['auth_pop3port'] = 'Port na serveru (najčešće je to 110, a port 995 je čest za SSL)'; // ORPHANED
$string['auth_pop3port_key'] = 'Port'; // ORPHANED
$string['auth_pop3title'] = 'Koristiti POP3 server'; // ORPHANED
$string['auth_pop3type'] = 'Tip servera. Ako Vaš server koristi sigurnosne sertifikate, izaberite pop3cert.'; // ORPHANED
$string['auth_pop3type_key'] = 'Tip'; // ORPHANED
$string['auth_radiuschangepasswordurl_key'] = 'URL za promenu lozinke'; // ORPHANED
$string['auth_radiusdescription'] = 'Ovaj metod koristi <a href=\"http://en.wikipedia.org/wiki/RADIUS\" target=\"_blank\">RADIUS</a> server za proveru da li su dato korisničko ime i lozinka validni.'; // ORPHANED
$string['auth_radiushost'] = 'Adresa RADIUS servera'; // ORPHANED
$string['auth_radiushost_key'] = 'Domaćin'; // ORPHANED
$string['auth_radiusnasport'] = 'Port koji će se koristiti za uspostavljanje veze'; // ORPHANED
$string['auth_radiusnasport_key'] = 'Port'; // ORPHANED
$string['auth_radiussecret'] = 'Javna tajna'; // ORPHANED
$string['auth_radiussecret_key'] = 'Sakrij'; // ORPHANED
$string['auth_radiustitle'] = 'Koristiti RADIUS server'; // ORPHANED
$string['auth_radiustype_key'] = 'Provera identiteta'; // ORPHANED
$string['auth_radiustypechapmd5'] = 'CHAP MD5'; // ORPHANED
$string['auth_radiustypemschapv1'] = 'Majkrosoft CHAP verzija 1'; // ORPHANED
$string['auth_radiustypemschapv2'] = 'Majkrosoft CHAP verzija 2'; // ORPHANED
$string['auth_radiustypepap'] = 'PAP'; // ORPHANED
$string['auth_shib_changepasswordurl'] = 'URL za promenu lozinke'; // ORPHANED
$string['auth_shib_convert_data'] = 'API za modifikacije podataka'; // ORPHANED
$string['auth_shib_convert_data_description'] = 'Možete da koristite ovaj API za dalje modifikacije podataka koje omogućava Shibboleth. Pročitajte <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">README</a> za dalja uputstva.'; // ORPHANED
$string['auth_shib_convert_data_warning'] = 'Datoteka ne postoji ili je proces Web servera ne može čitati!'; // ORPHANED
$string['auth_shib_instructions'] = 'Koristite <a href=\"$a\">Shibboleth pristup sistemu</a> da biste dobili pristup preko Shibboleth-a, ako ga Vaša institucija podržava.<br />U suprotnom, koristite normalnu pristupnu formu prikazanu ovde.'; // ORPHANED
$string['auth_shib_instructions_help'] = 'Ovde biste trebali postaviti sopstvena uputstva da biste Vašim korisnicima objasnili Shibboleth. Ona će biti prikazana na pristupnoj stranici u odeljku sa uputstvima. Uputstva moraju sadržati link do \"<b>$a</b>\" na koji će korisnici kliknuti kad budu želeli da da pristupe sistemu.'; // ORPHANED
$string['auth_shib_no_organizations_warning'] = 'Ukoliko želite da koristite integrisani WAYF servis, morate da date listu Provajdera identiteta (Identity Provider entityIDs) razdvojenu zarezom, njihova imena i opciono pokretača sesije.'; // ORPHANED
$string['auth_shib_only'] = 'Samo Shibboleth'; // ORPHANED
$string['auth_shib_only_description'] = 'Potvrdite ovu opciju ako će se primenjivati Shibboleth provera identiteta'; // ORPHANED
$string['auth_shib_username_description'] = 'Naziv Web servera promenljive Shibboleth okruženja koja će se koristiti kao Moodle korisničko ime'; // ORPHANED
$string['auth_shibboleth_contact_administrator'] = 'U slučaju da niste povezani sa datom organizacijom a potreban Vam je pristup kursu na ovom serveru, molimo Vas da kontaktirate administratora'; // ORPHANED
$string['auth_shibboleth_errormsg'] = 'Molimo vas da odaberete organizaciju čiji ste član!'; // ORPHANED
$string['auth_shibboleth_login'] = 'Shibboleth pristup sistemu'; // ORPHANED
$string['auth_shibboleth_login_long'] = 'Prijava na Moodle putem Shibboletha'; // ORPHANED
$string['auth_shibboleth_manual_login'] = 'Ručni prijava na sistem'; // ORPHANED
$string['auth_shibboleth_select_member'] = 'Član sam ...'; // ORPHANED
$string['auth_shibboleth_select_organization'] = 'Za proveru identiteta putem Shibboletha, odaberite svoju organizaciju iz padajuće liste:'; // ORPHANED
$string['auth_shibbolethdescription'] = 'Korišćenjem ovog metoda korisnici se kreiraju i proverava im se identitet pomoću <a href=\"http://shibboleth.internet2.edu/\" target=\"_blank\">Shibboleth-a</a>.<br>Obavezno pročitajte <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">UPUTSTVO</a> za podešavanje Vašeg Moodle sajta sa Shibboleth-om'; // ORPHANED
$string['auth_shibbolethtitle'] = 'Shibboleth'; // ORPHANED
$string['auto_add_remote_users'] = 'Automatsko dodavanje udaljenog korisnika'; // ORPHANED
$string['ntlmsso_attempting'] = 'Pokušava se samo jedna prijava preko NTLM...'; // ORPHANED
$string['ntlmsso_failed'] = 'Automatsko prijavljivanje nije uspelo, pokušajte sa običnom stranicom za prijavu'; // ORPHANED
$string['ntlmsso_isdisabled'] = 'NTLM SSO (jedinstvena prijava) nije uključeno'; // ORPHANED
$string['rpc_negotiation_timeout'] = 'RPC posredovanje u prekidima'; // ORPHANED
$string['shib_no_attributes_error'] = 'Čini se da Vam je identitet proveren Shibboleth-om, ali Moodle nije dobio nikakve atribute korisnika. Molimo proverite da li Vaš davalac identiteta izdaje neophodne atribute ($a) za davaoca usluga na kom Moodle radi ili informišite Webmastera ovog servera.'; // ORPHANED
$string['shib_not_all_attributes_error'] = 'Moodle-u su neophodni izvesni Shibboleth atributi, koji u Vašem slučaju nisu prisutni. Potrebni atributi su: $a<br />Molimo kontaktirajte Webmastera ovog servera ili svog davaoca identiteta.'; // ORPHANED
$string['shib_not_set_up_error'] = 'Shibboleth provera identiteta izgleda nije dobro podešena, jer nema prisutnih varijabli Shibboleth okruženja za ovu stranicu. Molimo pogledajte <a href=\"README.txt\">README</a> za dalja uputstva za podešavanje Shibboleth autentikacije ili kontaktirajte Webmastera ove Moodle instalacije.'; // ORPHANED

?>
