<?PHP // $Id$ 
      // auth.php - created with Moodle 1.6.2 (2006050520)


$string['alternatelogin'] = 'Ako ovde unesete URL, biće korišćen kao stranica za prijavu na ovaj sajt. Stranica bi trebala sadržati formu sa akcijskom opcijom podešenom na <strong>\'$a\'</strong> i vraćanjem polja <strong>username</strong> i <strong>password</strong>.<br />Budite oprezni da ne biste slučajno uneli pogrešan URL i time sami sebi onemogućili pristup sajtu.<br />Ostavite ovo podešavanje prazno da biste koristili podrazumevanu stranicu za pristup sistemu.';
$string['alternateloginurl'] = 'Alternativni URL za prijavu na sistem';
$string['auth_cas_baseuri'] = 'URI servera (ništa ako nije podešen baseUri)<br />Na primer, ako CAS server odgovara domenu host.domaine.fr/CAS/ onda je <br />cas_baseuri = CAS/';
$string['auth_cas_create_user'] = 'Uključite ovo podešavanje ako želite da ubacite korisnike za koje je izvršena CAS provera identiteta u Moodle bazu podataka. Ako to ne želite, samo korisnici koji već postoje u Moodle bazi podataka će moći da pristupe sistemu.';
$string['auth_cas_enabled'] = 'Uključite ovo podešavanje ako želite da koristite CAS proveru identiteta.';
$string['auth_cas_hostname'] = 'Naziv domaćina CAS servera <br />npr. host.domain.fr';
$string['auth_cas_invalidcaslogin'] = 'Nažalost, Vaša prijava nije uspela - niste mogli biti autorizovani';
$string['auth_cas_language'] = 'Odabrani jezik';
$string['auth_cas_logincas'] = 'Pristup preko sigurne veze';
$string['auth_cas_port'] = 'Port CAS servera';
$string['auth_cas_server_settings'] = 'Konfiguracija CAS servera';
$string['auth_cas_text'] = 'Sigurna veza';
$string['auth_cas_version'] = 'CAS verzija';
$string['auth_casdescription'] = 'Ovaj način koristi CAS server (Central Authentication Service) za proveru identiteta korisnika u Single Sign On okruženje (SSO). Možete koristiti i jednostavnu LDAP proveru identiteta. Ako su dato korisničko ime i lozinka validni prema CAS-u, Moodle kreira novi korisnički unos u svojoj bazi podataka, po potrebi preuzimajući atribute korisnika iz LDAP-a. Pri sledećim pristupima vrši se samo provera korisničkog imena i lozinke.';
$string['auth_castitle'] = 'Koristiti CAS server (SSO)';
$string['auth_changepasswordhelp'] = 'Promena pomoći za lozinku';
$string['auth_changepasswordhelp_expl'] = 'Prikaz pomoći za slučaj izgubljene lozinke korisnicima koji su izgubili svoju $a lozinku. To će biti prikazano ili isto kao ili umesto <strong>URL-a za promenu lozinke</strong> ili interne promene Moodle lozinke.';
$string['auth_changepasswordurl'] = 'URL za promenu lozinke';
$string['auth_changepasswordurl_expl'] = 'Specificirajte URL koji će se slati korisnicima koji izgube svoje $a lozinke. Podesite<strong>Koristiti standardnu stranicu za promenu lozinke</strong> na <strong>Ne</strong>.';
$string['auth_common_settings'] = 'Opšta podešavanja';
$string['auth_data_mapping'] = 'Mapiranje podataka';
$string['auth_dbdescription'] = 'Ovaj metod koristi tabelu spoljašnje baze podataka za proveru da li su dodeljeno korisničko ime i lozinka ispravni. Ako je nalog nov, onda informacija iz ostalih polja može biti kopirana u Moodle.';
$string['auth_dbextrafields'] = 'Ova polja su izborna. Možete izabrati da prethodno popunite neka Moodle korisnička polja sa informacijama iz <b>polja spoljašnje baze podataka</b> koja naznačite ovde. <br />Ako ih ostavite prazne, onda će biti korišćene podrazumevane vrednosti.<br /> U svakom slučaju, korisnik će biti u mogućnosti da uređuje sva polja nakon prijavljivanja.';
$string['auth_dbfieldpass'] = 'Ime polja koje sadrži lozinke';
$string['auth_dbfielduser'] = 'Ime polja koje sadrži korisnička imena';
$string['auth_dbhost'] = 'Računar domaćin servera baze podataka.';
$string['auth_dbname'] = 'Naziv baze podataka';
$string['auth_dbpass'] = 'Lozinka koja odgovara gore navedenom korisničkom imenu';
$string['auth_dbpasstype'] = '<p>Zadajte format koje koristi polje za lozinku. MD5 šifrovanje je korisno prilikom povezivanja na ostale često korišćene Web aplikacije kao što je PostNuke.</p> <p> Upotrebite opciju \'interno\' ako želite da spoljašnja baza podataka vodi računa o korisničkim imenima i adresama e-pošte, ali da sam Moodle bude nadležan za lozinke. Ako koristite opciju \'interno\', <i>morate</i> obezbediti pristup popunjenom polju za adrese e-pošte u spoljašnjoj bazi podataka, i morate redovno izvršavati auth/db/auth_db_sync_users.php. Moodle će slati e-poruke novim korisnicima sa njihovim privremenim lozinkama.</p>';
$string['auth_dbtable'] = 'Ime tabele u bazi podataka';
$string['auth_dbtitle'] = 'Koristiti spoljašnju bazu podataka';
$string['auth_dbtype'] = 'Tip baze podataka (Pogledajte <a href=\"../lib/adodb/readme.htm#drivers\">ADOdb dokumentaciju</a> za detalje)';
$string['auth_dbuser'] = 'Korisničko ime sa pristupom čitanju korisničke baze';
$string['auth_emaildescription'] = 'Potvrđivanje putem e-pošte je uobičajen način provere identiteta. Nakon što se korisnik prijavi i izabere svoje novo ime i lozinku, e-pošta se šalje na adresu tog korisnika. U e-pošti se nalazi sigurnosni link prema stranici gde novi korisnik potvrđuje svoj nalog. Pri svakom narednom pristup uneti podaci se samo upoređuju sa onima koji su sačuvani u Moodle bazi podataka.';
$string['auth_emailtitle'] = 'Provera identiteta putem e-pošte';
$string['auth_fccreators'] = 'Lista grupa čijim saradnicima je dozvoljeno da kreiraju nove kurseve. Odvojite spojene grupe sa \';\'. Imena moraju biti napisana upravo onako kao na FirstClass serveru. Sistem vodi računa o velikim i malim slovima.';
$string['auth_fcdescription'] = 'Ova metoda koristi FirstClass server za proveru da li su dodeljeno korisničko ime i lozinka ispravni.';
$string['auth_fcfppport'] = 'Serverski port (3333 je najčešći)';
$string['auth_fchost'] = 'Adresa FirstClass servera. Koristite IP broj ili DSN ime.';
$string['auth_fcpasswd'] = 'Lozinka za gornji nalog.';
$string['auth_fctitle'] = 'Koristiti FirstClass server';
$string['auth_fcuserid'] = 'Korisnik FirstClass naloga sa kompletnim privilegijama \'podadministrator\'.';
$string['auth_fieldlock'] = 'Zaključavanje vrednosti';
$string['auth_fieldlock_expl'] = '<p><b>Zaključavanje vrednosti:</b> Ako je omogućeno, sprečiće Moodle korisnike i administratore da direktno uređuju polje. Koristite ovu opciju ako održavate ove podatke u eksternom autentikacionom sistemu. </p>';
$string['auth_fieldlocks'] = 'Zaključavanje korisničkih polja';
$string['auth_fieldlocks_help'] = '<p>Možete zaključati polja sa korisničkim podacima. To je korisno za sajtove na kojima korisničke podatke ručno održavaju administratori uređivanjem korisničkih zapisa u bazi podataka ili postavljanjem podataka korišćenjem mogućnosti za postavljanje korisnika iz drugih izvora. Ako zaključavate polja koja su neophodna za rad Moodle sistema, proverite da li ste omogućili korišćenje tih podataka pri kreiranju korisničkih naloga &emdash; jer se u suprotnom nalozi neće moći koristiti.</p><p>Razmotrite podešavanje moda za taključavanje na \'Otključano ako je prazno\' da biste izbegli taj problem.</p>';
$string['auth_imapdescription'] = 'Ovaj metod koristi IMAP server da proveri da li su dodeljeno korisničko ime i lozinka ispravni.';
$string['auth_imaphost'] = 'IMAP adresa servera. Koristite IP broj, a ne DNS nazive.';
$string['auth_imapport'] = 'Broj porta IMAP servera. Obično je 143 ili 993.';
$string['auth_imaptitle'] = 'Koristiti IMAP server';
$string['auth_imaptype'] = 'Tip IMAP servera. IMAP serveri mogu imati različite tipove provere identiteta.';
$string['auth_ldap_bind_dn'] = 'Ako želite da koristite bind-korisnika za pretragu korisnika, odredite to ovde. Nešto nalik na \'cn=ldapuser,ou=public,o=org\'';
$string['auth_ldap_bind_pw'] = 'Lozinka za bind-korisnika.';
$string['auth_ldap_bind_settings'] = 'Bind podešavanja';
$string['auth_ldap_contexts'] = 'Lista konteksta gde su korisnici locirani. Razdvojite različite kontekste sa \';\'. Na primer : \'ou=users,o=org; ou=others,o=org\'';
$string['auth_ldap_create_context'] = 'Ako omogućite kreiranje korisnika sa potvrdom putem e-pošte, naznačite kontekst u kom su korisnici kreirani. Trebalo bi da je taj kontekst drugačiji od konteksta ostalih korisnika da bi se sprečili sigurnosni problemi. Nema potrebe dodavati ovaj kontekst u ldap_context-variable, jer će Moodle potražiti korisnike iz tog sadržaja automatski.<br /><b>Napomena:</b> Morate izmeniti funkciju auth_user_create() u datoteci auth/ldap/lib.php da biste omogućili kreiranje korisnika';
$string['auth_ldap_creators'] = 'Lista grupa čijim članovima je dozvoljeno kreiranje novih kurseva. Razdvojite višestruke grupe sa \';\'. Obično nešto poput \'cn=teachers,ou=staff,o=myorg\'';
$string['auth_ldap_expiration_desc'] = 'Izaberite NE da onemogućite proveru isteka lozinke ili LDAP da učitate vreme isteka lozinke direktno sa LDAP-a.';
$string['auth_ldap_expiration_warning_desc'] = 'Broj dana pre isteka lozinke kad se korisniku šalje upozorenje o isticanju lozinke.';
$string['auth_ldap_expireattr_desc'] = 'Opciono: Mimoiđite LDAP atribute koji su potrebni za čuvanje vremena isteka lozinke passwordExpirationTime';
$string['auth_ldap_graceattr_desc'] = 'Opciono: Mimoiđite poček unosa atributa';
$string['auth_ldap_gracelogins_desc'] = 'Omogućite LDAP podršku za poček unosa. Nakom isteka lozinke korisnik može pristupati sistemu sve dok je iznos počeka unosa 0. Ako je lozinka istekla omogućite ova podešavanja za prikazivanje poruke počeka unosa.';
$string['auth_ldap_host_url'] = 'Naznačite LDAP domaćina u URL-formi kao što je \'ldap://ldap.myorg.com/\' ili \'ldaps://ldap.myorg.com/\' Odvojite višestruke servere znakom \';\' da biste dobili podršku pri prevazilaženju problema vezanih za pad sistema';
$string['auth_ldap_login_settings'] = 'Podešavanja vezana za pristup korisnika sistemu';
$string['auth_ldap_memberattribute'] = 'Opciono: Određuje korisnikov članski atribut, kad korisnik pripada grupi. Obično \'member\'';
$string['auth_ldap_objectclass'] = 'Opciono: Određuje objectClass koristeći ime/tražeći korisnika na ldap_user_type. Obično nema potrebe da ovo menjate.';
$string['auth_ldap_opt_deref'] = 'Ustanovite kako drugačije upravljati u toku traženja. Izaberite jednu od pratećih vrednosti: 
\"Ne\" (LDAP_DEREF_NEVER) ili \"Da\" (LDAP_DEREF_ALWAYS)';
$string['auth_ldap_passwdexpire_settings'] = 'Podešavanja LDAP isteka lozinke';
$string['auth_ldap_preventpassindb'] = 'Izaberite \"da\" da biste sprečili čuvanje lozinki u Moodle bazi podataka.';
$string['auth_ldap_search_sub'] = 'Stavite vrednost <> 0 ako želite da tražite korisnike u potkontekstima';
$string['auth_ldap_server_settings'] = 'Podešavanja LDAP servera';
$string['auth_ldap_update_userinfo'] = 'Ažurirajte informacije korisnika (ime, prezime, adrese...) iz LDAP-a u Moodle. Specificirajte podešavanja za mapiranje podataka prema sopstvenim potrebama.';
$string['auth_ldap_user_attribute'] = 'Atribut koji se koristi za ime/pretragu korisnika. Uglavnom je \'cn\'.';
$string['auth_ldap_user_settings'] = 'Podešavanja pretrage korisnika';
$string['auth_ldap_user_type'] = 'Izaberite kako se korisnik čuva u LDAP. Ovo podešavanje takođe određuje kako će funkcionisati istek upisa, poček unosa i kreiranje korisnika.';
$string['auth_ldap_version'] = 'Verzija LDAP protokola koju Vaš server koristi.';
$string['auth_ldapdescription'] = 'Ovaj metod služi za proveru identiteta od strane spoljašnjeg LDAP servera.
Ako su dodeljeno korisničko ime i lozinka ispravni, Moodle kreira novu instancu korisnika u svojoj bazi podataka.
Ovaj modul može čitati korisničke atribute sa LDAP-a i postaviti tražena polja u Moodle. Za sledeće upise samo se proveravaju korisničko ime i lozinka.';
$string['auth_ldapextrafields'] = 'Ova polja nisu obavezna. Možete izabrati da ispunite neka Moodle korisnička polja sa informacijama iz <b>LDAP polja</b> koja ovde odredite. <br />Ako polja ostavite prazna, onda se ništa neće prebaciti sa LDAP-a, tako da će biti korišćene podrazumevane Moodle vrednosti.<br />U svakom slučaju, korisnici mogu da uređuju ova polja nakon pristupa sistemu.';
$string['auth_ldaptitle'] = 'Koristiti LDAP server.';
$string['auth_manualdescription'] = 'Ovaj metod uklanja korisnicima sve načine pravljenja njihovih sopstvenih naloga. Sve naloge mora ručno napraviti administrator.';
$string['auth_manualtitle'] = 'Samo za ručno pravljenje naloga';
$string['auth_multiplehosts'] = 'Određivanje više domaćina ili adresa (npr. host1.com;host2.com;host3.com) ili (npr. xxx.xxx.xxx.xxx;xxx.xxx.xxx.xxx)';
$string['auth_nntpdescription'] = 'Ovaj metod koristi NNTP server za proveru ispravnosti korisničkih imena i lozinki.';
$string['auth_nntphost'] = 'NNTP adrese servera. Koristite IP broj, a ne DNS nazive.';
$string['auth_nntpport'] = 'Serverski port (119 je najčešći)';
$string['auth_nntptitle'] = 'Koristiti NNTP server.';
$string['auth_nonedescription'] = 'Korisnici se mogu upisati i odmah napraviti važeće naloge, bez provere identiteta od strane spoljašnjeg servera i bez potvrde putem e-pošte.
Budite oprezni kad koristite ovu opciju - mislite na sigurnost i administrativne probleme koji njome mogu biti prouzrokovani!';
$string['auth_nonetitle'] = 'Nema provere identiteta';
$string['auth_pamdescription'] = 'Ovaj metod koristi PAM za pristup korisničkom imenu na domaćem serveru. Morate instalirati <a href=\"http://www.math.ohio-state.edu/~ccunning/pam_auth/\" target=\"_blank\">PHP4 PAM proveru identiteta</a> da biste koristili ovaj modul.';
$string['auth_pamtitle'] = 'PAM (Pluggable Authentication Modules)';
$string['auth_passwordisexpired'] = 'Vaša lozinka je istekla. Želite li sad da je promenite?';
$string['auth_passwordwillexpire'] = 'Vaša lozinka će isteći za $a dana. Želite li sad da je promenite?';
$string['auth_pop3description'] = 'Ovaj metod koristi POP3 server za proveru ispravnosti korisničkih imena i lozinki.';
$string['auth_pop3host'] = 'POP3 adresa servera. Koristite IP broj, a ne DNS naziv.';
$string['auth_pop3mailbox'] = 'Naziv mailbox-a s kojim treba uspostaviti vezu. (obično INBOX)';
$string['auth_pop3port'] = 'Port na serveru (najčešće je to 110, a port 995 je čest za SSL)';
$string['auth_pop3title'] = 'Koristiti POP3 server';
$string['auth_pop3type'] = 'Tip servera. Ako Vaš server koristi sigurnosne sertifikate, izaberite pop3cert.';
$string['auth_radiusdescription'] = 'Ovaj metod koristi <a href=\"http://en.wikipedia.org/wiki/RADIUS\" target=\"_blank\">RADIUS</a> server za proveru da li su dato korisničko ime i lozinka validni.';
$string['auth_radiushost'] = 'Adresa RADIUS servera';
$string['auth_radiusnasport'] = 'Port koji će se koristiti za uspostavljanje veze';
$string['auth_radiussecret'] = 'Javna tajna';
$string['auth_radiustitle'] = 'Koristiti RADIUS server';
$string['auth_shib_convert_data'] = 'API za modifikacije podataka';
$string['auth_shib_convert_data_description'] = 'Možete da koristite ovaj API za dalje modifikacije podataka koje omogućava Shibboleth. Pročitajte <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">README</a> za dalja uputstva.';
$string['auth_shib_convert_data_warning'] = 'Datoteka ne postoji ili je proces Web servera ne može čitati!';
$string['auth_shib_instructions'] = 'Koristite <a href=\"$a\">Shibboleth pristup sistemu</a> da biste dobili pristup preko Shibboleth-a, ako ga Vaša institucija podržava.<br />U suprotnom, koristite normalnu pristupnu formu prikazanu ovde.';
$string['auth_shib_instructions_help'] = 'Ovde biste trebali postaviti sopstvena uputstva da biste Vašim korisnicima objasnili Shibboleth. Ona će biti prikazana na pristupnoj stranici u odeljku sa uputstvima. Uputstva moraju sadržati link do \"<b>$a</b>\" na koji će korisnici kliknuti kad budu želeli da da pristupe sistemu.';
$string['auth_shib_only'] = 'Samo Shibboleth';
$string['auth_shib_only_description'] = 'Potvrdite ovu opciju ako će se primenjivati Shibboleth provera identiteta';
$string['auth_shib_username_description'] = 'Naziv Web servera promenljive Shibboleth okruženja koja će se koristiti kao Moodle korisničko ime';
$string['auth_shibboleth_login'] = 'Shibboleth pristup sistemu';
$string['auth_shibboleth_manual_login'] = 'Ručni pristup sistemu';
$string['auth_shibbolethdescription'] = 'Korišćenjem ovog metoda korisnici se kreiraju i proverava im se identitet pomoću <a href=\"http://shibboleth.internet2.edu/\" target=\"_blank\">Shibboleth-a</a>.<br>Obavezno pročitajte <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">UPUTSTVO</a> za podešavanje Vašeg Moodle sajta sa Shibboleth-om';
$string['auth_shibbolethtitle'] = 'Shibboleth';
$string['auth_updatelocal'] = 'Ažuriranje lokalnih podataka';
$string['auth_updatelocal_expl'] = '<p><b>Ažuriranje lokalnih podataka:</b> Ako je omogućeno, polje će biti ažurirano (koristi se eksterni auth) svaki put kada korisnik pristupi sistemu ili dođe do korisničke sinhronizacije. Polja za koja je podešeno lokalno ažuriranje bi trebala biti zaključana.</p>';
$string['auth_updateremote'] = 'Ažuriranje eksternih podataka';
$string['auth_updateremote_expl'] = '<p><b>Ažuriranje eksternih podataka:</b> Ako je omogućeno, eksterni auth će biti ažuriran pri ažuriranju zapisa o korisnicima. Polja bi trebala biti otključana da bi se dozvolile promene.</p>';
$string['auth_updateremote_ldap'] = '<p><b>Napomene:</b> Ažuriranje eksternih LDAP podataka zahteva da podesite povezivanje binddn i bindpw za bind-korisnika sa privilegijama korigovanja svih korisničkih zapisa. Ovo trenutno ne čuva viševrednosne atribute i ukloniće dodatne vrednosti nadogradnje.</p>';
$string['auth_user_create'] = 'Omogućiti kreiranje korisnika';
$string['auth_user_creation'] = 'Novi (anonimni) korisnici mogu napraviti korisničke naloge na spoljašnjem izvoru za proveru identiteta i izvršiti potvrdu putem e-pošte. Ako omogućite ovu opciju, konfigurišite i specifične opcije modula koje služe za kreiranje korisnika.';
$string['auth_usernameexists'] = 'Odabrano korisničko ime već postoji. Molimo izaberite drugo korisničko ime.';
$string['authenticationoptions'] = 'Opcije za proveru identiteta';
$string['authinstructions'] = 'Ovde možete dati instrukcije Vašim korisnicima, tako da znaju koje korisničko ime i lozinku treba da koriste. Tekst koji ovde napišete biće prikazan na stranici za pristup sistemu. Ako polje ostavite prazno, onda instrukcije neće biti prikazane.';
$string['changepassword'] = 'URL za promenu lozinke';
$string['changepasswordhelp'] = 'Ovde možete zadati lokaciju na kojoj Vaši korisnici mogu obnoviti ili promeniti svoje korisničko ime/lozinku, u slučaju da su je zaboravili.
Ova opcija se može ponuditi korisnicima u vidu dugmeta na stranici za pristup sistemu i njihovoj korisničkoj strani. Ako ostavite prazno polje, dugme neće biti prikazano.';
$string['chooseauthmethod'] = 'Izaberite način provere identiteta';
$string['createpasswordifneeded'] = 'Kreiranje lozinke ako je to potrebno';
$string['forcechangepassword'] = 'Obavezna promena lozinke';
$string['forcechangepassword_help'] = 'Obavezna promena lozinke za sve korisnike pri njihovom sledećem pristupu Moodle sistemu';
$string['forcechangepasswordfirst_help'] = 'Obavezna promena lozinke za sve korisnike pri njihovom prvom pristupu Moodle sistemu';
$string['guestloginbutton'] = 'Dugme za prijavu gostiju';
$string['infilefield'] = 'Polje zahtevano u datoteci';
$string['instructions'] = 'Uputstva';
$string['internal'] = 'Interno';
$string['locked'] = 'Zaključano';
$string['md5'] = 'MD5 kodiranje';
$string['passwordhandling'] = 'Upravljenje poljem lozinke';
$string['plaintext'] = 'Običan tekst';
$string['shib_no_attributes_error'] = 'Čini se da Vam je identitet proveren Shibboleth-om, ali Moodle nije dobio nikakve atribute korisnika. Molimo proverite da li Vaš davalac identiteta izdaje neophodne atribute ($a) za davaoca usluga na kom Moodle radi ili informišite webmastera ovog servera.';
$string['shib_not_all_attributes_error'] = 'Moodle-u su neophodni izvesni Shibboleth atributi, koji u Vašem slučaju nisu prisutni. Potrebni atributi su: $a<br />Molimo kontaktirajte webmastera ovog servera ili svog davaoca identiteta.';
$string['shib_not_set_up_error'] = 'Shibboleth provera identiteta izgleda nije dobro podešena, jer nema prisutnih varijabli Shibboleth okruženja za ovu stranicu. Molimo pogledajte <a href=\"README.txt\">README</a> za dalja uputstva za podešavanje Shibboleth autentikacije ili kontaktirajte webmastera ove Moodle instalacije.';
$string['showguestlogin'] = 'Možete sakriti ili prikazati dugme za prijavu gostiju na prijavnoj stranici.';
$string['stdchangepassword'] = 'Upotreba standardne stranice za promenu lozinke';
$string['stdchangepassword_expl'] = 'Ako spoljašnji sistem za proveru identiteta dozvoljava promenu lozinke iz Moodle sistema, uključite ga. Ovo podešavanje zaobilazi \'URL za promenu lozinke\'.';
$string['stdchangepassword_explldap'] = 'Napomena: Preporučuje se da koristite LDAP pre nego SSL šifrovanje tunela (ldaps://) ako je LDAP server udaljen.';
$string['unlocked'] = 'Otključano';
$string['unlockedifempty'] = 'Otključano ako je prazno';
$string['update_never'] = 'Nikad';
$string['update_oncreate'] = 'Pri kreiranju';
$string['update_onlogin'] = 'Pri svakom pristupu sistemu';
$string['update_onupdate'] = 'Pri ažuriranju';

?>
