<?PHP // $Id$ 
      // currencies.php - created with Moodle 1.8.1+ (2007021510)


$string['AED'] = 'Emiratski dirham';
$string['AFA'] = 'Avganistanski avgani';
$string['ALL'] = 'Albanski lek';
$string['ANG'] = 'Holandski Antilski gvilder';
$string['AON'] = 'Angolska nova kvanca';
$string['ARA'] = 'Argentinski novi pezos';
$string['AUD'] = 'Australijski dolar';
$string['AWG'] = 'Arubski florin';
$string['BBD'] = 'Barbadoski dolar';
$string['BDT'] = 'Bangladeška taka';
$string['BGL'] = 'Bugarski lev';
$string['BHD'] = 'Bahreinski dinar';
$string['BIF'] = 'Burundijski franak';
$string['BMD'] = 'Bermudski dolar';
$string['BND'] = 'Brunejski dolar';
$string['BOB'] = 'Bolivijski bolivijano';
$string['BRR'] = 'Brazilski kruzero real';
$string['BSD'] = 'Bahamski dolar';
$string['BTN'] = 'Butanski ngultrum';
$string['BUK'] = 'Burmanski kiat';
$string['BWP'] = 'Bocvanska pula';
$string['BZD'] = 'Belizejski dolar';
$string['CAD'] = 'Kanadski dolar';
$string['CDZ'] = 'Zairski novi zair';
$string['CHF'] = 'Švajcarski franak';
$string['CLF'] = 'Čileanska moneta fomento';
$string['CLP'] = 'Čileanski pezos';
$string['CNY'] = 'Kineski renminbi';
$string['COP'] = 'Kolumbijski pezos';
$string['CRC'] = 'Kostarikanski kolon';
$string['CSD'] = 'Srpski dinar';
$string['CUP'] = 'Kubanski pezos';
$string['CVE'] = 'Kape Verdanski eskudo';
$string['CYP'] = 'Kiparska funta';
$string['CZK'] = 'Češka kruna';
$string['DJF'] = 'Džibutski franak';
$string['DKK'] = 'Danska kruna';
$string['DOP'] = 'Dominikanski pezos';
$string['DZD'] = 'Alžirski dinar';
$string['EGP'] = 'Egipatska funta';
$string['ETB'] = 'Etiopski bir';
$string['EUR'] = 'Evro';
$string['FJD'] = 'Fidži dolar';
$string['FKP'] = 'Foklandska ostrvska funta';
$string['GBP'] = 'Britanska funta';
$string['GHC'] = 'Ganski kedi';
$string['GIP'] = 'Gibraltarska funta';
$string['GMD'] = 'Gambijski dalasi';
$string['GNF'] = 'Gvinejski franak';
$string['GTQ'] = 'Gvatemalanski kvecal';
$string['GWP'] = 'Gvineja-Bisajski pezos';
$string['GYD'] = 'Gvajanski dolar';
$string['HKD'] = 'Hong-Kongški dolar';
$string['HNL'] = 'Honduraska lempira';
$string['HTG'] = 'Haitski gurde';
$string['HUF'] = 'Mađarska forinta';
$string['IDR'] = 'Indonezijska rupija';
$string['ILS'] = 'Izraelski šejkel';
$string['INR'] = 'Indijski rupi';
$string['IQD'] = 'Irački dinar';
$string['IRR'] = 'Iranski rial';
$string['ISK'] = 'Islandska kruna';
$string['JMD'] = 'Jamajkanski dolar';
$string['JOD'] = 'Jordanski dinar';
$string['JPY'] = 'Japanski jen';
$string['KES'] = 'Kenijski šiling';
$string['KHR'] = 'Kambodžanski riel';
$string['KMF'] = 'Komoroški franak';
$string['KPW'] = 'Severnokorejski von';
$string['KRW'] = 'Južnokorejski von';
$string['KWD'] = 'Kuvajtski dinar';
$string['KYD'] = 'Kajmanski ostrvski dolar';
$string['LAK'] = 'Laoški kip';
$string['LBP'] = 'Libanska funta';
$string['LKR'] = 'Šri Lanški rupi';
$string['LRD'] = 'Liberijski dolar';
$string['LSL'] = 'Lesotski loti';
$string['LYD'] = 'Libijski dinar';
$string['MAD'] = 'Marokanski dirham';
$string['MGF'] = 'Malagazijski franak';
$string['MNT'] = 'Mongolski tugrik';
$string['MOP'] = 'Makajska pataka';
$string['MRO'] = 'Mauritanijska ougvija';
$string['MTL'] = 'Malteška lira';
$string['MUR'] = 'Mauricijski rupi';
$string['MVR'] = 'Maldivska rufija';
$string['MWK'] = 'Malavijska kvača';
$string['MXN'] = 'Meksički pezos';
$string['MYR'] = 'Malezijski ringit';
$string['MZM'] = 'Mozambiški metikal';
$string['NGN'] = 'Nigerijska naira';
$string['NIO'] = 'Nikaragvanska kordoba';
$string['NOK'] = 'Norveški kroner';
$string['NPR'] = 'Nepalski rupi';
$string['NZD'] = 'Novozelandski dolar';
$string['OMR'] = 'Omanski rial';
$string['PAB'] = 'Panamska balboa';
$string['PEN'] = 'Novi sol';
$string['PGK'] = 'Papua Novogvinejska kina';
$string['PHP'] = 'Filipinski pezos';
$string['PKR'] = 'Pakistanski rupi';
$string['PLN'] = 'Poljski zloti';
$string['PYG'] = 'Paragvajski gvarani';
$string['QAR'] = 'Katarski rial';
$string['ROL'] = 'Rumunski lej';
$string['RWF'] = 'Ruandski franak';
$string['SAR'] = 'Saudijski rijal';
$string['SBD'] = 'Solomonski ostrvski dolar';
$string['SCR'] = 'Sejšelski rupi';
$string['SDP'] = 'Sudanska funta';
$string['SEK'] = 'Švedska kruna';
$string['SGD'] = 'Singapurški dolar';
$string['SHP'] = 'Sveta Helena funta';
$string['SKK'] = 'Slovačka kruna';
$string['SLL'] = 'Sijera Leonski leone';
$string['SOS'] = 'Somalijski šiling';
$string['SRG'] = 'Surinamski gvilder';
$string['STD'] = 'Sao Tome i Principe dobra';
$string['SUR'] = 'Sovjetska rublja';
$string['SVC'] = 'El Salvadorski kolon';
$string['SYP'] = 'Sirijski potmd';
$string['SZL'] = 'Svazilandski lilangeni';
$string['THB'] = 'Tajlandski bat';
$string['TND'] = 'Tuniški dinar';
$string['TOP'] = 'Tongaška paanga';
$string['TPE'] = 'Istočnotimorski eskudo';
$string['TRL'] = 'Turska lira';
$string['TTD'] = 'Trinidad i Tobago dolar';
$string['TWD'] = 'Tajvanski dolar';
$string['TZS'] = 'Tanzanijski šiling';
$string['UGS'] = 'Ugandski šiling';
$string['USD'] = 'SAD dolar';
$string['UYU'] = 'Urugvajski novi pezos';
$string['VEB'] = 'Venecuelanski bolivar';
$string['VND'] = 'Vijetnamski dong';
$string['VUV'] = 'Vanuatski vatu';
$string['WST'] = 'Samoanska tala';
$string['YER'] = 'Jemenski rial';
$string['ZAR'] = 'Južnoafrički rand';
$string['ZMK'] = 'Zambijska kvača';
$string['ZWD'] = 'Zimbabvijski dolar';
$string['ADF'] = 'Andorski franak'; // ORPHANED
$string['ADP'] = 'Andorska pezeta'; // ORPHANED
$string['AMD'] = 'Jermenski dram'; // ORPHANED
$string['AZM'] = 'Azerbejdžanski manat'; // ORPHANED
$string['AZN'] = 'Azerbejdžanski novi manat'; // ORPHANED
$string['BAM'] = 'Bosanska konvertibilna marka'; // ORPHANED
$string['BYR'] = 'Beloruska rublja'; // ORPHANED
$string['CDF'] = 'Kongoleški franak'; // ORPHANED
$string['ECS'] = 'Ekvadorski sukre'; // ORPHANED
$string['EEK'] = 'Estonski kron'; // ORPHANED
$string['GEL'] = 'Gruzijski lari'; // ORPHANED
$string['HRK'] = 'Hrvatska kuna'; // ORPHANED
$string['KGS'] = 'Kirgistanski som'; // ORPHANED
$string['KZT'] = 'Kazahstanski tenge'; // ORPHANED
$string['LTL'] = 'Litvanski litas'; // ORPHANED
$string['LVL'] = 'Letonski lats'; // ORPHANED
$string['MDL'] = 'Moldavski lev'; // ORPHANED
$string['MKD'] = 'Makedonski denar'; // ORPHANED
$string['MMK'] = 'Mjanmarski kiat'; // ORPHANED
$string['NAD'] = 'Namibijski dolar'; // ORPHANED
$string['PEI'] = 'Peruanski inti'; // ORPHANED
$string['RSD'] = 'Srpski dinar'; // ORPHANED
$string['RUB'] = 'Ruska rublja'; // ORPHANED
$string['SIT'] = 'Slovenački tolar'; // ORPHANED
$string['TMM'] = 'Turkmenistanski manat'; // ORPHANED
$string['UAH'] = 'Ukrajinska hrivnia'; // ORPHANED
$string['ZRZ'] = 'Zairski zair'; // ORPHANED

?>
