<?PHP // $Id$ 
      // data.php - created with Moodle 1.9.9 (Build: 20100609) (2007101590)


$string['action'] = 'Akcija';
$string['add'] = 'Dodaj unos';
$string['addafield'] = 'Dodaj polje';
$string['addcomment'] = 'Dodaj komentar';
$string['addentries'] = 'Dodaj unose';
$string['addtemplate'] = 'Šablon za dodavanje';
$string['advancedsearch'] = 'Napredno pretraživanje';
$string['allowcomments'] = 'Dozvoliti komentare?';
$string['allowratings'] = 'Dozvoliti ocenjivanje poruka?';
$string['alttext'] = 'Alternativni tekst';
$string['approve'] = 'Odobri';
$string['approved'] = 'Odobreno';
$string['ascending'] = 'Rastuće';
$string['asearchtemplate'] = 'Šablon za napredno pretraživanje';
$string['atmaxentry'] = 'Uneli ste maksimalan dozvoljeni broj unosa!';
$string['authorfirstname'] = 'Ime autora';
$string['authorlastname'] = 'Prezime autora';
$string['autogenallforms'] = 'Generisanje svih podrazumevanih šablona';
$string['autolinkurl'] = 'Automatsko linkovanje URL-a';
$string['availablefromdate'] = 'Dostupno od';
$string['availabletags'] = 'Dostupne oznake';
$string['availabletodate'] = 'Dostupno do';
$string['blank'] = 'Prazno';
$string['buttons'] = 'Dugmad';
$string['bynameondate'] = 'uneo/la $a->name dana $a->date';
$string['cancel'] = 'Odustani';
$string['checkbox'] = 'Polje za potvrdu';
$string['chooseexportfields'] = 'Izaberite polja koja želite izvoziti:';
$string['chooseexportformat'] = 'Izaberite format u koji želite izvoziti:';
$string['chooseorupload'] = 'Odaberi datoteku';
$string['columns'] = 'kolone';
$string['comment'] = 'Komentar';
$string['commentdeleted'] = 'Komentar je obrisan';
$string['commentempty'] = 'Komentar je bio prazan';
$string['comments'] = 'Komentari';
$string['commentsaved'] = 'Komentar je sačuvan';
$string['commentsn'] = '$a komentar(a)';
$string['configenablerssfeeds'] = 'Ovaj prekidač će omogućiti korišćenje RSS servisa za sve baze podataka. Ipak ćete morati istu opciju ručno da uključite i u podešavanjima svake baze podataka.';
$string['confirmdeletefield'] = 'Upravo ćete obrisati ovo polje. Da li ste sigurni da to želite?';
$string['confirmdeleterecord'] = 'Da li ste sigurni da želite da obrišete ovaj unos?';
$string['csstemplate'] = 'CSS šablon';
$string['csvfailed'] = 'Nije moguće pročitati neobrađene podatke iz CSV datoteke';
$string['csvfile'] = 'CSV datoteka';
$string['csvimport'] = 'Uvoz CSV datoteke';
$string['csvwithselecteddelimiter'] = '<acronym title=\"Comma Separated Values\">CSV</acronym> tekst sa izabranim znakom razdvajanja';
$string['data:approve'] = 'Odobravanje neodobrenih unosa';
$string['data:comment'] = 'Piši komentare';
$string['data:managecomments'] = 'Upravljanje komentarima';
$string['data:manageentries'] = 'Upravljaj unosima';
$string['data:managetemplates'] = 'Upravljaj šablonima';
$string['data:manageuserpresets'] = 'Upravljanje svim šablonima skupova podešavanja';
$string['data:rate'] = 'Oceni unose';
$string['data:readentry'] = 'Čitaj unose';
$string['data:viewalluserpresets'] = 'Pregled postojećih skupova podešavanje svih korisnika';
$string['data:viewentry'] = 'Pregled unosa';
$string['data:viewrating'] = 'Pregled ocena';
$string['data:writeentry'] = 'Piši unose';
$string['date'] = 'Datum';
$string['dateentered'] = 'Datum unosa';
$string['defaultfielddelimiter'] = '(podrazumevani znak je zarez)';
$string['defaultfieldenclosure'] = '(podrazumevano je ništa)';
$string['defaultsortfield'] = 'Podrazumevano sortiranje polja';
$string['delete'] = 'Briši';
$string['deleteallentries'] = 'Briši sve unose';
$string['deletecomment'] = 'Da li ste sigurni da želite da obrišete ovaj komentar?';
$string['deleted'] = 'obrisano';
$string['deletefield'] = 'Brisanje postojećeg polja';
$string['deletenotenrolled'] = 'Briši unose korisnika koji nisu upisani na kurs';
$string['deletewarning'] = 'Da li ste sigurni da želite da obrišete postojeći skup podešavanja?';
$string['descending'] = 'Opadajuće';
$string['directorynotapreset'] = '$a->directory ne postoji: datoteke koje nedostaju su sledeće: $a->missing_files';
$string['download'] = 'Preuzmi';
$string['edit'] = 'Uredi';
$string['editcomment'] = 'Uredi komentar';
$string['editentry'] = 'Uredi unos';
$string['editordisable'] = 'Onemogući uređivanje';
$string['editorenable'] = 'Omogući uređivanje';
$string['emptyadd'] = 'Dodavanje šablona je prazno, generiše se podrazumevana forma...';
$string['emptyaddform'] = 'Niste ispunili nijedno polje!';
$string['entries'] = 'Unosi';
$string['entrieslefttoadd'] = 'Morate dodati još $a->entriesleft unos(a) pre nego što budete mogli pregledati unose drugih učesnika.';
$string['entrieslefttoaddtoview'] = 'Morate da dodate još $a->entrieslefttoview unosa pre nego što budete mogli da vidite unose drugih korisnika.';
$string['entry'] = 'Unos';
$string['entrysaved'] = 'Vaš unos je sačuvan';
$string['errormustbeteacher'] = 'Morate biti predavač da biste koristili ovu stranicu!';
$string['example'] = 'Primer modula baze podataka';
$string['excel'] = 'Excel';
$string['export'] = 'Izvezi';
$string['exportaszip'] = 'Izvezi u vidu arhive';
$string['exportdatabaserecords'] = 'Izvezi zapise baze podataka';
$string['exportedtozip'] = 'Izvezeno u privremenu arhivu...';
$string['failedpresetdelete'] = 'Greška pri brisanju definisanog skupa podešavanja!';
$string['fieldadded'] = 'Polje je dodato';
$string['fieldallowautolink'] = 'Dozvoliti automatsko linkovanje';
$string['fielddeleted'] = 'Polje je obrisano';
$string['fielddelimiter'] = 'Znak za razdvajanje polja';
$string['fielddescription'] = 'Opis polja';
$string['fieldenclosure'] = 'Prilaganje polja';
$string['fieldheight'] = 'Visina';
$string['fieldheightlistview'] = 'Visina u prikazu liste';
$string['fieldheightsingleview'] = 'Visina u pojedinačnom prikazu';
$string['fieldids'] = 'Identifikatori polja';
$string['fieldmappings'] = 'Mapiranje polja';
$string['fieldname'] = 'Naziv polja';
$string['fieldnotmatched'] = 'Sledeća polja u Vašoj datoteci su nepoznata u ovoj bazi podataka';
$string['fieldoptions'] = 'Opcije (jedna po liniji)';
$string['fields'] = 'Polja';
$string['fieldupdated'] = 'Polje je ažurirano';
$string['fieldwidth'] = 'Širina';
$string['fieldwidthlistview'] = 'Širina u prikazu liste';
$string['fieldwidthsingleview'] = 'Širina u pojedinačnom prikazu';
$string['file'] = 'Datoteka';
$string['filesnotgenerated'] = 'Nisu sve datoteke generisane: $a';
$string['filtername'] = 'Automatsko linkovanje baze podataka';
$string['footer'] = 'Podnožje';
$string['forcelinkname'] = 'Obavezan naziv za linkovanje';
$string['foundnorecords'] = 'Nisu pronađeni zapisi(<a href=\"$a->reseturl\">Vrati stara podešavanja filtera</a>)';
$string['foundrecords'] = 'Pronađeni zapisi: $a->num/$a->max(<a href=\"$a->reseturl\">Vrati stara podešavanja filtera</a>)';
$string['fromfile'] = 'iz arhive';
$string['header'] = 'Zaglavlje';
$string['headeraddtemplate'] = 'Definiše interfejs pri uređivanju unosa';
$string['headerasearchtemplate'] = 'Definiše interfejs za napredna pretraživanja';
$string['headercsstemplate'] = 'Definiše lokalne CSS stilove za druge šablone';
$string['headerjstemplate'] = 'Definiše prilagođeni Javascript za druge šablone';
$string['headerlisttemplate'] = 'Definiše interfejs pregledanja višestrukih unosa';
$string['headerrsstemplate'] = 'Definiše izgled unosa u RSS servisima';
$string['headersingletemplate'] = 'Definiše interfejs pregledanja pojedinačnog unosa';
$string['importsuccess'] = 'Definisani skup podešavanja je uspešno primenjen.';
$string['insufficiententries'] = 'potrebno je više unosa za pregled ove baze podataka';
$string['intro'] = 'Uvod';
$string['invalidfieldname'] = 'Molimo izaberite neko drugo ime za ovo polje';
$string['invalidrate'] = 'Neispravni nivo baze podataka ($a)';
$string['invalidurl'] = 'URL koji ste upravo uneli nije ispravan';
$string['jstemplate'] = 'Javascript šablon';
$string['latitude'] = 'Širina';
$string['latlong'] = 'Širina/dužina';
$string['latlongdownloadallhint'] = 'Preuzimanje linka za sve unose u KML obliku';
$string['latlongkmllabelling'] = 'Kako označiti stavke u KML datotekama (Google Earth)';
$string['latlonglinkservicesdisplayed'] = 'Linkovani servisi za prikaz';
$string['latlongotherfields'] = 'Ostala polja';
$string['list'] = 'Prikaži listu';
$string['listtemplate'] = 'Šablon za listu';
$string['longitude'] = 'Dužina';
$string['mappingwarning'] = 'Sva stara polja koje nisu mapirana na novo polje će biti izgubljena i svi podaci u tim poljima će biti uklonjeni.';
$string['maxentries'] = 'Maksimalno unosa';
$string['maxsize'] = 'Maksimalna veličina';
$string['menu'] = 'Meni';
$string['menuchoose'] = 'Izaberite...';
$string['modulename'] = 'Baza podataka';
$string['modulenameplural'] = 'Baze podataka';
$string['more'] = 'Još';
$string['moreurl'] = 'Još URL-a';
$string['movezipfailed'] = 'Nije moguće premestiti arhivu';
$string['multientry'] = 'Ponovljeni unos';
$string['multimenu'] = 'Meni (mogućnost višestrukog izbora)';
$string['multipletags'] = 'Pronađene su višestruke oznake! Šablon nije sačuvan';
$string['namecheckbox'] = 'Polje za potvrdu';
$string['namedate'] = 'Polje za datum';
$string['namefile'] = 'Polje za datoteku';
$string['namelatlong'] = 'Polje širine/dužine';
$string['namemenu'] = 'Polje menija';
$string['namemultimenu'] = 'Polje menija za višestruki izbor';
$string['namenumber'] = 'Polje za broj';
$string['namepicture'] = 'Polje za sliku';
$string['nameradiobutton'] = 'Polje za pojedinačan izbor';
$string['nametext'] = 'Polje za tekst';
$string['nametextarea'] = 'Polje za tekstualnu oblast';
$string['nameurl'] = 'Polje za URL';
$string['newentry'] = 'Novi unos';
$string['newfield'] = 'Kreiranje novog polja';
$string['noaccess'] = 'Nemate pristup ovoj stranici';
$string['nodefinedfields'] = 'Novo postojeći skup podešavanja nema definisanih polja!';
$string['nofieldindatabase'] = 'Nema polja definisanih za ovu bazu podataka.';
$string['nolisttemplate'] = 'Šablon liste još nije definisan';
$string['nomatch'] = 'Nema unosa koji se poklapaju!';
$string['nomaximum'] = 'Nema maksimuma';
$string['norecords'] = 'Nema unosa u bazi podataka';
$string['nosingletemplate'] = 'Još nije definisan pojedinačni šablon';
$string['notapproved'] = 'Unos još uvek nije odobren';
$string['notinjectivemap'] = 'Mapa ne može da se ubaci';
$string['number'] = 'Broj';
$string['numberrssarticles'] = 'RSS članci';
$string['numnotapproved'] = 'Na čekanju';
$string['numrecords'] = '$a unosa';
$string['ods'] = '<acronym title=\"OpenDocument Spreadsheet\">ODS</acronym> (OpenOffice)';
$string['optionaldescription'] = 'Kratak opis (opciono)';
$string['optionalfilename'] = 'Naziv datoteke (opciono)';
$string['other'] = 'Drugo';
$string['overwrite'] = 'Prepiši';
$string['overwritesettings'] = 'Prepiši preko važećih podešavanja';
$string['pagesize'] = 'Unosa po stranici';
$string['participants'] = 'Učesnici';
$string['picture'] = 'Slika';
$string['pleaseaddsome'] = 'Molimo kreirajte neke ispod ili <a href=\"$a\">izaberite već definisan skup</a> za početak.';
$string['presetinfo'] = 'Čuvanje u vidu skupa podešavanja će objaviti ovaj šablon. Drugi korisnici će možda moći da ga koriste u svojim bazama podataka.';
$string['presets'] = 'Postojeći skupovi podešavanja';
$string['radiobutton'] = 'Dugmad za pojedinačni izbor';
$string['rate'] = 'Oceni';
$string['rating'] = 'Ocena';
$string['ratingeveryone'] = 'Svi mogu ocenjivati poruke';
$string['ratingno'] = 'Bez ocenjivanja';
$string['ratingonlyteachers'] = 'Samo $a može ocenjivati poruke';
$string['ratingpublic'] = '$a može videti svačije ocene';
$string['ratingpublicnot'] = '$a može videti samo sopstvene ocene';
$string['ratings'] = 'Ocene';
$string['ratingssaved'] = 'Ocene su sačuvane';
$string['ratingsuse'] = 'Koristiti ocenjivanje';
$string['recordapproved'] = 'Unos je odobren';
$string['recorddeleted'] = 'Unos je obrisan';
$string['recordsnotsaved'] = 'Nije sačuvan nijedan unos. Molimo proverite format postavljene datoteke.';
$string['recordssaved'] = 'unosi sačuvani';
$string['requireapproval'] = 'Zahtevati odobrenje?';
$string['requiredentries'] = 'Potrebni unosi';
$string['requiredentrieschanged'] = '<p><strong>VAŽNO - MOLIMO PROČITAJTE</strong></p><p>Usled popravke greške u kôdu, biće izmenjeno ponašanje aktivnosti u bazi podataka korišćenjem \'Obavezni entiteti\' i \'Obavezni unosi pre pregleda podešavanja\'. Detaljnije objašnjenje promena može se pročitati na <a href=\"http://moodle.org/mod/forum/discuss.php?d=110928\" target=\"_blank\">forumu za modul baze podataka</a>. Očekivano ponašanje ovih podešavanja može se pročitati takođe u <a href=\"http://docs.moodle.org/en/Adding/editing_a_database#Required_entries\" target=\"_blank\">Moodle Docs</a>.</p><p>Ova promena utiče na sledeće baze podataka u Vašem sistemu: (Molimo da sačuvate sada ovaj spisak i posle unapređenja proverite da li ove aktivnosti još uvek rade na način koji nastavnik želi.)</p><strong style=\"color:red\">$a->text</strong><br/>';
$string['requiredentriestoview'] = 'Unosi potrebni pre pregledanja';
$string['resetsettings'] = 'Resetuj polje';
$string['resettemplate'] = 'Resetuj šablon';
$string['resizingimages'] = 'Promena veličine umanjenog prikaza slike...';
$string['rows'] = 'redovi';
$string['rssglobaldisabled'] = 'Onemogućeno. Pogledajte promenljive konfiguracije sajta.';
$string['rsshowmany'] = '(broj poslednjih unosa za prikaz, 0 za onemogućavanje RSS-a)';
$string['rsstemplate'] = 'RSS šablon';
$string['rsstitletemplate'] = 'Šablon RSS naslova';
$string['save'] = 'Sačuvaj';
$string['saveandadd'] = 'Sačuvaj i dodaj još';
$string['saveandview'] = 'Sačuvaj i prikaži';
$string['saveaspreset'] = 'Sačuvaj kao skup podešavanja';
$string['savesettings'] = 'Sačuvaj podešavanja';
$string['savesuccess'] = 'Uspešno sačuvano. Vaš skup podešavanja će biti dostupan na čitavom sajtu.';
$string['savetemplate'] = 'Sačuvaj šablon';
$string['search'] = 'Traži';
$string['selectedrequired'] = 'Sve izabrano obavezno';
$string['sendinratings'] = 'Pošalji u moje poslednje ocene';
$string['showall'] = 'Prikaži sve unose';
$string['single'] = 'Prikaži pojedinačno';
$string['singletemplate'] = 'Pojedinačni šablon';
$string['teachersandstudents'] = '$a->teachers i $a->students';
$string['templates'] = 'Šabloni';
$string['templatesaved'] = 'Šabloni su sačuvani';
$string['text'] = 'Tekst';
$string['textarea'] = 'Tekstualna oblast';
$string['timeadded'] = 'Vreme dodavanja';
$string['timemodified'] = 'Vreme izmene';
$string['todatabase'] = 'u ovu bazu podataka.';
$string['type'] = 'Tip polja';
$string['undefinedprocessactionmethod'] = 'Ne postoji metoda definisana u Data_Preset da koristi akciju \"$a\".';
$string['unsupportedexport'] = '($a->fieldtype)se ne može izvoziti';
$string['updatefield'] = 'Ažuriranje postojećeg polja';
$string['uploadfile'] = 'Postavi datoteku';
$string['uploadrecords'] = 'Postavljenje unosa iz datoteke';
$string['url'] = 'URL';
$string['usestandard'] = 'koristiti postojeći skup podešavanja';
$string['viewfromdate'] = 'Može se pregledati od';
$string['viewtodate'] = 'Može se pregledati do';
$string['wrongdataid'] = 'Pogrešna ID podataka je obezbeđena';
$string['cannotaccesspresentsother'] = 'Nije Vam dozvoljen pristup početnim podešavanjima drugih korisnika'; // ORPHANED
$string['cannotadd'] = 'Ne mogu se dodati unosi!'; // ORPHANED
$string['cannotdeletepreset'] = 'Greška u brisanju početnih podešavanja!'; // ORPHANED
$string['cannotinsertempty'] = 'Nije moguće kreirati prazan zapis!'; // ORPHANED
$string['cannotrate'] = 'Ocenjivanje stavki nije dopušteno!'; // ORPHANED
$string['cannotunziptopreset'] = 'Ne može se raspakovati direktorijum početnih podešavanja'; // ORPHANED
$string['data:exportallentries'] = 'Izveti sve stavke iz baze podataka'; // ORPHANED
$string['data:exportentry'] = 'Izvezi stavku iz baze podataka'; // ORPHANED
$string['data:exportownentry'] = 'Izvezi sopstvenu stavku iz baze podataka'; // ORPHANED
$string['generateerror'] = 'Nisu sve datoteke generisane!'; // ORPHANED
$string['guestrate'] = 'Gostima nije dopušteno da ocenjuju unose'; // ORPHANED
$string['invalidaccess'] = 'Stranici nije ispravno pristupljeno'; // ORPHANED
$string['invalidfieldid'] = 'ID polja nije ispravan'; // ORPHANED
$string['invalidfieldtype'] = 'Tip polja nije ispravan'; // ORPHANED
$string['invalidid'] = 'ID podataka nije ispravan'; // ORPHANED
$string['invalidpreset'] = '$a nije postojeće podešavanje.'; // ORPHANED
$string['invalidratedata'] = 'Neispravni su prosleđeni podaci o ocenjivanju'; // ORPHANED
$string['invalidrecord'] = 'Neispravan zapis'; // ORPHANED
$string['missingdata'] = 'id podataka ili objekt mora se proslediti klasi polja'; // ORPHANED
$string['missingfield'] = 'Greška programera: Morate odrediti polje i/ili podatke kada definišete klasu polja.'; // ORPHANED
$string['nofieldcontent'] = 'Sadržaj polja nije pronađen'; // ORPHANED
$string['norating'] = 'Ova aktivnost ne koristi ocenjivanja'; // ORPHANED
$string['portfolionotfile'] = 'Izvezi u portfolio a ne u datoteku (samo za .csv)'; // ORPHANED
$string['updatingerror'] = 'Postojala je greška pri ažuriranju baze podataka.'; // ORPHANED
$string['cannotinsertrate'] = 'Nije moguće umetnuti novo ocenjivanje($a[0] = $a[1])'; // ORPHANED
$string['cannotupdaterate'] = 'Nije moguće izmeniti staro ocenjivanje($a[0] = $a[1])'; // ORPHANED
$string['invaliddata'] = 'Neispravni podaci'; // ORPHANED

?>
