<?PHP // $Id$ 
      // error.php - created with Moodle 1.9.9 (Build: 20100609) (2007101590)


$string['adminprimarynoedit'] = 'Podaci primarnog administratora ne mogu biti menjani od strane drugih korisnika';
$string['cannotassignrole'] = 'Nije moguće dodeliti ulogu u kursu';
$string['cannotcreatelangdir'] = 'Nije moguće kreiranje direktorijuma jezika';
$string['cannotcreatetempdir'] = 'Nije moguće kreiranje privremenog direktorijuma.';
$string['cannotcustomizelocallang'] = 'Nemate odobrenje da menjate izraze iz prevoda. Ovim odobrenjem upravlja se posedovanjem privilegije \"moodle/site:langeditlocal\". Postavite ovu privilegiju da bi Vam bila omogućena izmena lokalnih jezičkih paketa u slučaju da želite vršiti izmene prevodâ za Vaš sajt.';
$string['cannotdownloadcomponents'] = 'Nije moguće preuzeti komponente.';
$string['cannotdownloadlanguageupdatelist'] = 'Nije moguće preuzeti spisak ažuriranih jezika sa download.moodle.org';
$string['cannotdownloadzipfile'] = 'Nije moguće preuzimanje arhive.';
$string['cannoteditmasterlang'] = 'Nemate odobrenje da menjate izraze iz glavnog jezičkog paketa. Ovim odobrenjem upravlja se posedovanjem privilegije \"moodle/site:langeditlocal\". Postavite ovu privilegiju da bi Vam bila omogućena izmena glavnih jezičkih paketa u slučaju da ste Vi nadležni za paket.';
$string['cannotfindcomponent'] = 'Nije moguće pronaći komponentu.';
$string['cannotinsertrecord'] = 'Nije moguć unos ID za novi zapis: $a';
$string['cannotsavemd5file'] = 'Nije moguće sačuvati md5 datoteku.';
$string['cannotsavezipfile'] = 'Nije moguće sačuvti ZIP arhivu.';
$string['cannotunzipfile'] = 'Nije moguće raspakovati ZIP datoteku.';
$string['cannotupdaterecord'] = 'Nije moguće ažurirati zapis sa ID $a';
$string['cannotviewprofile'] = 'Ne možete videti profil ovog korisnika';
$string['cantunenrollfrommetacourse'] = 'Ne možete se ispisati sa ovog meta kursa.';
$string['cantunenrollinthisrole'] = 'Ne možete se ispisati sa ovog kursa dok ste u trenutnoj ulozi.';
$string['cmunknown'] = 'Nije pronađen taj modul kursa';
$string['componentisuptodate'] = 'Komponenta je dostupna u svojoj najnovijoj verziji.';
$string['confirmsesskeybad'] = 'Nažalost, ali ključ Vaše sesije ne može biti potvrđen da bi se izvršila ova akcija. Ova sigurnosna opcija sprečava slučajno ili zlonamerno izvršavanje važnih funkcija u Vaše ime. Molimo budite sigurni da stvarno želite da izvršite ovu funkciju.';
$string['couldnotassignrole'] = 'Došlo je do ozbiljne, ali neodređene greške prilikom pokušaja dodele Vaše nove uloge';
$string['countriesphpempty'] = 'Greška: Datoteka countries.php u jezičkom paketu $a je prazna ili nedostaje.';
$string['coursegroupunknown'] = 'Odgovarajući kurs za grupu $a nije zadat';
$string['csvcolumnduplicates'] = 'Otkrivene su duplikati kolona';
$string['csvemptyfile'] = 'CSV datoteka je prazna';
$string['csvfewcolumns'] = 'Nema dovoljno kolona, molimo proverite podešavanje za znak razdvajanja';
$string['csvweirdcolumns'] = 'Neispravan format CSV datoteke - broj kolona nije svuda isti!';
$string['dbupdatefailed'] = 'Ažuriranje baze podataka nije uspelo';
$string['downloadedfilecheckfailed'] = 'Nije uspela provera preuzete datoteke.';
$string['duplicateusername'] = 'Duplirano korisničko ime - preskače se zapis';
$string['errorcleaningdirectory'] = 'Greška pri čišćenju direktorijuma \"$a\"';
$string['errorcopyingfiles'] = 'Greška pri kopiranju datoteka';
$string['errorcreatingdirectory'] = 'Greška pri kreiranju direktorijuma \"$a\"';
$string['errorcreatingfile'] = 'Greška pri kreiranju datoteke \"$a\"';
$string['erroronline'] = 'Greška u liniji $a';
$string['errorreadingfile'] = 'Greška pri čitanju datoteke \"$a\"';
$string['errorsavingrequest'] = 'Kada ste pokušali da sačuvate svoj zahtev pojavila se greška';
$string['errorunzippingfiles'] = 'Greška pri raspakivanju datoteka';
$string['fieldrequired'] = '\"$a\" je obavezno polje';
$string['filenotfound'] = 'Nažalost traženi dokument nije bilo moguće pronaći';
$string['forumblockingtoomanyposts'] = 'Prekoračili ste ograničenje za broj poruka na ovom forumu.';
$string['groupalready'] = 'Korisnik već pripada grupi $a';
$string['groupexistforcourse'] = 'Grupa \"$a\" već postoji u ovom kursu';
$string['groupnotaddederror'] = 'Grupa \"$a\" nije dodata';
$string['groupunknown'] = 'Grupa $a ne pripada datom kursu';
$string['groupusernotmember'] = 'Korisnik nije član ove grupe';
$string['guestnoeditprofile'] = 'Gost ne može da uređuje svoj profil';
$string['guestnoeditprofileother'] = 'Ne može se uređivati profil gosta';
$string['guestsarenotallowed'] = 'Korisniku sa nalogom gosta nije dozvoljeno da uradi';
$string['invalidadminsettingname'] = 'Neispravno admin podešavanje ($a)';
$string['invalidcontext'] = 'Neispravan kontekst';
$string['invalidcourse'] = 'Neispravan kurs';
$string['invalidcourseid'] = 'Pokušavate da koristite neispravan ID kursa ($a)';
$string['invalidcoursemodule'] = 'Neispravan ID modula kursa';
$string['invalidfieldname'] = '\"$a\" nije ispravno ime polja';
$string['invalidfiletype'] = '\"$a\" nije ispravan tip datoteke';
$string['invalidipformat'] = 'Neispravan format IP adrese';
$string['invalidmd5'] = 'Neispravna md5 datoteka';
$string['invalidrequest'] = 'Neispravan zahtev';
$string['invalidrole'] = 'Neispravna uloga';
$string['invalidsesskey'] = 'Netačan kod sesije je prosleđen, forma nije prihvaćena!';
$string['invalidurl'] = 'Neispravan url';
$string['invalidxmlfile'] = '\"$a\" nije ispravna XML datoteka';
$string['iplookupfailed'] = 'Nije moguće pronaći geografske podatke o ovoj IP adresi $a.';
$string['iplookupprivate'] = 'Nije moguće prikazati pretragu privatne IP adrese';
$string['listcantmovedown'] = 'Prebacivanje stavke na dole nije uspelo, ovo je poslednja stavka u nizu.';
$string['listcantmoveleft'] = 'Prebacivanje stavke ulevo nije uspelo,nema nijedne nadređene stavke.';
$string['listcantmoveright'] = 'Prebacivanje stavke udesno nije uspelo, nema niza čiji bi ona bila član. Prebaci ga u drugi niz i tada ga možeš pomeriti udesno.';
$string['listcantmoveup'] = 'Prebacivanje stavke naviše nije uspelo, jer je to prva stavka u nizu.';
$string['listnochildren'] = 'Nema potomaka stavke';
$string['listnoitem'] = 'Stavka nije pronađena';
$string['listnopeers'] = 'Niz stavki nije pronađen';
$string['listupdatefail'] = 'DB operacija nije uspela dok je uređivana hijerarhija liste.';
$string['loginasnoenrol'] = 'Ne možeš se učlanjivati i odjavnjivati kada si u kursu u sesiji \"Prijavljen kao\".';
$string['loginasonecourse'] = 'Ne možeš pristupiti ovom kursu <br /> Moraš prekinuti sesiju \"Prijavljeni ste kao\" pre ulaska u bilo koji kurs';
$string['missingfield'] = 'Nedostaje polje \"$a\"';
$string['missingrequiredfield'] = 'Nedostaje neko obavezno polje';
$string['modulemissingcode'] = 'Modulu $a nedostaje kod potreban za izvođenje ove funkcije';
$string['modulerequirementsnotmet'] = 'Modul \"$a->modulename\" ($a->moduleversion) nije mogao biti instaliran. Navedeni modul zahteva noviju verziju sistema Moodle (Vi trenutno imate $a->currentmoodle, a potrebna Vam je verzija $a->requiremoodle).';
$string['mustbeteacher'] = 'Morate biti predavač da biste videli ovu stranicu';
$string['nocategorydelete'] = 'Kategorija \'$a\' se ne može obrisati!';
$string['nocontext'] = 'Žao nam je, ali taj kurs nije validan kontekst';
$string['noinstances'] = 'Nema instanci $a u ovom kursu!';
$string['nologinas'] = 'Nije ti dozvoljeno da se prijaviš kao taj korisnik';
$string['nonmeaningfulcontent'] = 'Besmislen sadržaj';
$string['noparticipatorycms'] = 'Nažalost nemate učestvujućih modula kursa o kojima bi se mogao podneti izveštaj.';
$string['nopermissions'] = 'Žao nam je, ali trenutno nemate dozvolu da to radite ($a)';
$string['nostatstodisplay'] = 'Izvinite, nema raspoloživih podataka za prikaz';
$string['notavailable'] = 'Trenutno nije na raspolaganju.';
$string['onlyadmins'] = 'Samo administratori mogu to da rade.';
$string['onlyeditingteachers'] = 'Samo predavači mogu to da rade.';
$string['onlyeditown'] = 'Možete menjati samo lične podatke';
$string['pagenotexist'] = 'Došlo je do neuobičajene greške (pokušano je dostizanje kraja stranice koja uopšte ne postoji).';
$string['pleasereport'] = 'Ako imate vremena, molimo objasnite nam šta ste pokušavali da učinite kada je došlo do greške:';
$string['pluginrequirementsnotmet'] = 'Dodatak \"$a->pluginname\" ($a->pluginversion) nije mogao biti instaliran. On zahteva noviju verziju Moodle sistema (Vi trenutno koristite $a->currentmoodle, a potrebna Vam je verzija $a->requiremoodle).';
$string['processingstops'] = 'Procesiranje se ovde zaustavlja. Preostali zapisi biće ignorisani.';
$string['remotedownloaderror'] = 'Preuzimanje komponente na Vaš server nije uspelo. Proverite podešavanja proksi serevera. PHP cURL ekstenzija se preporučuje.<br /><br />Morate da preuzmete <a href=\"$a->url\">$a->url</a> datoteku ručno, kopirate je u direktorijum \"$a->dest\" na svom sereveru tamo je raspakujete.';
$string['remotedownloadnotallowed'] = 'Nije dozvoljeno preuzimanje komponenti na Vaš server (opcija allow_url_fopen je onemogućena).<br /><br />Morate ručno preuzeti datoteku <a href=\"$a->url\">$a->url</a>, kopirati je u \"$a->dest\" na svom serveru i tamo je raspakovati.';
$string['restorechecksumfailed'] = 'Došlo je do nekog problema sa informacijom za obnavljanje, sačuvanom u Vašoj sesiji. Molimo proverite Vaša podešavanja granica veličina PHP memorije/DB paketa. Obnavljanje je prekinuto.';
$string['restricteduser'] = 'Žao nam je, ali vaš tekući nalog \"$a\" je ograničen i ne možete uraditi ovu akciju.';
$string['scheduledbackupsdisabled'] = 'Planirane sigurnosne kopije su onemogućene od strane administratora';
$string['sendmessage'] = 'Slanje poruke';
$string['sessionerroruser'] = 'Vaša sesija je istekla. Molimo, prijavite se na sistem ponovo.';
$string['sessionerroruser2'] = 'Došlo je do greške koja utiče na Vašu tekuću sesiju. Molimo pristupite sistemu ponovo ili ponovo pokrenite svoj web čitač.';
$string['sessionipnomatch'] = 'Nažalost, ali izgleda da se Vaš IP broj promenio od kada ste se prijavili na sistem. Ova sigurnosna opcija sprečava krakere da ukradu Vaš indentitet dok ste prijavljeni na ovaj sajt. Normalni korisnici ne bi trebalo da vide ovu poruku - molimo Vas da tražite pomoć od administratora sajta.';
$string['socksnotsupported'] = 'SOCKS5 proksi nije podržan u PHP4';
$string['statscatchupmode'] = 'Statistika je trenutno u modu za sustizanje obrade padataka. Do sada je procesirano $a->daysdone dan(a), a još $a->dayspending dana čeka na obradu. Vratite se nešto kasnije!';
$string['tagnotfound'] = 'Navedena oznaka (tag) nije pronađena u bazi podataka';
$string['unicodeupgradeerror'] = 'Žao nam je, ali Vaša baza podataka nije u Unicode formatu, a ova vezija Moodlea ne može da je prebaci u Unicode bazu podataka. Molimo prvo uradite nadogradnju sistema do Moodle 1.7.x verzije i uradite Unicode migraciju sa administratorske stranice. Nakon što to uradite moći ćete da pređete na Moodle $a';
$string['unknowncourse'] = 'Ne postoji kurs pod nazivom \"$a\"';
$string['unknowncourseidnumber'] = 'Nepoznati kurs ID \"$a\"';
$string['unknowncourserequest'] = 'Npoznat zahtev za kurs';
$string['unknowngroup'] = 'Nepoznata grupa \"$a\"';
$string['unknownrole'] = 'Nepoznata uloga \"$a\"';
$string['unknownuseraction'] = 'Žao nam je, ali sistem nije razumeo ovu akciju korisnika.';
$string['userautherror'] = 'Nepoznat dodatak za proveru identiteta';
$string['userauthunsupported'] = 'Dodatak za proveru identiteta nije moguće ovde primeniti';
$string['useremailduplicate'] = 'Ponovljena adresa';
$string['usernotaddedadmin'] = 'Ne mogu se obrisati administratorski nalozi.';
$string['usernotaddederror'] = 'Korisnik \"$a\" nije dodat - nepoznata greška';
$string['usernotaddedregistered'] = 'Korisnik \"$a\" nije dodat - već je registrovan';
$string['usernotavailable'] = 'Detaljne informacije o ovom korisniku Vam nisu dostupne.';
$string['usernotdeletederror'] = 'Korisnik nije izbrisan - nepoznata greška';
$string['usernotdeletedmissing'] = 'Korisnik nije izbrisan - korisničko ime nije pronađeno';
$string['usernotdeletedoff'] = 'Korisnik nije obrisan - brisanje nije dozvoljeno.';
$string['usernotrenamedadmin'] = 'Ne mogu se preimenovati administratorski nalozi.';
$string['usernotrenamedexists'] = 'Korisnik nije preimenovan -- novo korisničko ime je već zauzeto.';
$string['usernotrenamedmissing'] = 'Korisnik nije preimenovan -- nije pronađeno staro korisničko ime.';
$string['usernotrenamedoff'] = 'Korisnik nije preimenovan - preimenovanje nije dozvoljeno.';
$string['usernotupdatedadmin'] = 'Ne mogu se izmeniti administratorski nalozi.';
$string['usernotupdatederror'] = 'Korisnik nije ažuriran - nepoznata greška';
$string['usernotupdatednotexists'] = 'Nisu izmenjeni podaci o korisniku - ne postoje podaci.';
$string['wrongdestpath'] = 'Pogrešna odredišna putanja.';
$string['wrongsourcebase'] = 'Pogrešan izvorni URL baze.';
$string['wrongzipfilename'] = 'Pogrešan naziv arhive.';
$string['youcannotdeletecategory'] = 'Ne možete da obrišete kategoriju \'$a\' zato što ne možete da obrišete sadržaje ili da ih premestite negde drugo.';
$string['TODO'] = 'TODO'; // ORPHANED
$string['authnotexisting'] = 'Dodatak ѕa proveru identiteta ne postoji'; // ORPHANED
$string['backuptablefail'] = 'Tabele rezervnre kopije nisu mogle biti uspešno podešene!'; // ORPHANED
$string['blockcannotconfig'] = 'Ovaj blok ne podržaba globalnu konfiguraciju'; // ORPHANED
$string['blockcannotinistantiate'] = 'Probelem priliko kreiranja instance objekta bloka'; // ORPHANED
$string['blockcannotread'] = 'Nije bilo moguće pročitati podatke za blockid= $a'; // ORPHANED
$string['blockdoesnotexist'] = 'Ovaj blok ne postoji'; // ORPHANED
$string['blockdoesnotexistonpage'] = 'Ovaj blok (id=$a->instanceid) ne postoji ma ovoj stranici ($a->url).'; // ORPHANED
$string['blocknameconflict'] = 'Konflikt u nazivu: blok $a->name ima isti naslov kao i postojeći blok: $a->conflict!'; // ORPHANED
$string['cannotaddcoursemodule'] = 'Nije biloo moguće dodati novi modul'; // ORPHANED
$string['cannotaddcoursemoduletosection'] = 'Nije bilo moguće dodati novi modul u ovu sekciju'; // ORPHANED
$string['cannotaddmembergroupiddoesntexist'] = 'Nije moguće dodati člana grupe: id grupe ne postoji'; // ORPHANED
$string['cannotaddmodule'] = '$a modul nije mogao biti dodat listi modula!'; // ORPHANED
$string['cannotaddnewmodule'] = 'Nije bilo moguće dodati novi modul $a'; // ORPHANED
$string['cannotaddrss'] = 'Nemate dozvolu da dodajete RSS izvore vesti'; // ORPHANED
$string['cannotassignanthing'] = 'Nije moguće dodeliti moodle/site:doanything'; // ORPHANED
$string['cannotassignrolehere'] = 'Nije Vam dozvoljeno da dodeljujete ovu ulogu (id = $a->roleid) u ovom kontekstu ($a->context)'; // ORPHANED
$string['cannotcallscript'] = 'Ne možete da pozovete ovaj skript na taj način'; // ORPHANED
$string['cannotcallusgetselecteduser'] = 'Ne možete da pozovete user_selector::get_selected_user ukoliko je opcija multiselect uključena'; // ORPHANED
$string['cannotcreatebackupdir'] = 'Nije bilo moguće kreirati direktorijum za rezervnu kopiju podataka. Administrator sajta mora da reši taj problem'; // ORPHANED
$string['cannotcreatecategory'] = 'Kategorija nije ubačena'; // ORPHANED
$string['cannotcreategroup'] = 'Greška prilikom kreiranja grupe'; // ORPHANED
$string['cannotcreatelangbase'] = 'Greška: Nije bilo moguće kreirati osnovni direktorijum jezika'; // ORPHANED
$string['cannotcreateorfindstructs'] = 'Greška u pronalaženju ili kreiranju sturkture sekcija za ovaj kurs'; // ORPHANED
$string['cannotcreatepopupwin'] = 'Nedefinisani element - nije moguće kreirati iskačući prozor'; // ORPHANED
$string['cannotcreatesitedir'] = 'Nije moguće kreirati direktorijum sajta. Administrator sajta mora da reši taj problem'; // ORPHANED
$string['cannotcreateuploaddir'] = 'Nije moguće kreirati direktorijum za postavljanje datoteka. Administrator sajta mora da reši taj problem'; // ORPHANED
$string['cannotcustomisefiltersblockuser'] = 'Ne možete da prilagodite podešavanja u kontekstu korisnika odnosno u kontekstu bloka'; // ORPHANED
$string['cannotdeletebackupids'] = 'Nije bilo moguće obrisati id oznake prethodnih rezervnih kopija'; // ORPHANED
$string['cannotdeletecategorycourse'] = 'Nije uspelo brisanje kursa \'$a\''; // ORPHANED
$string['cannotdeletecategoryquestions'] = 'Nije bilo moguće obrisati pitanja iz kategorije  \'$a\''; // ORPHANED
$string['cannotdeletecourse'] = 'Nemate dozvolu da obrišete ovaj kurs'; // ORPHANED
$string['cannotdeletedir'] = 'Nije moguće obrisati ($a)'; // ORPHANED
$string['cannotdeletelangcache'] = 'Jezički keš ne može biti obrisan. Molimo, rešite problem ovlašćenja u dataroot/cache/languages!'; // ORPHANED
$string['cannotdeleterole'] = 'Ne  može biti obrisano zbog $a'; // ORPHANED
$string['cannotdeleterolewithid'] = 'Nije moguće obrisati ulogu sa ID $a'; // ORPHANED
$string['cannotdeletethisrole'] = 'Ne možete da obrišete ovu ulogu zato što je koristi sistem ili je to poslednja uloga sa administratorskim nivoom pristupa.'; // ORPHANED
$string['cannoteditcomment'] = 'Ovaj komentar nije Vaš da bi mogli da ga uređujete!'; // ORPHANED
$string['cannoteditcommentexpired'] = 'Ne možete ovo da uređujete. Vreme je isteklo!'; // ORPHANED
$string['cannoteditpostorblog'] = 'Ne možete da postujete ili uređujete blog'; // ORPHANED
$string['cannoteditsiteform'] = 'Ne možete urediti kurs sajta koristeći ovaj obrazac'; // ORPHANED
$string['cannotedityourprofile'] = 'Oprostite, ali ne možete da uređujete svoj profil'; // ORPHANED
$string['cannotfindcontext'] = 'Nije moguće pronaći kontekst.'; // ORPHANED
$string['cannotfinddocs'] = 'Nije moguće pronaći datoteke dokumentacije za \"$a\" jezik'; // ORPHANED
$string['cannotfindgradeitem'] = 'Nije moguće naći grade_item'; // ORPHANED
$string['cannotfindgroup'] = 'Nije moguće naći grupu'; // ORPHANED
$string['cannotfindhelp'] = 'Nije moguće pronaći datoteke pomoći za \"$a\" jezik.'; // ORPHANED
$string['cannotfindinfo'] = 'Nije moguće naći informacije za: \"$a\"'; // ORPHANED
$string['cannotfindlang'] = 'Nije moguće pronaći \"$a\" jezički paket!'; // ORPHANED
$string['cannotfindsite'] = 'Nije moguće naći kurs na nivou sajta'; // ORPHANED
$string['cannotfindteacher'] = 'Nije moguće pronaći predavača'; // ORPHANED
$string['cannotfinduser'] = 'Nije moguće pronaći korisnika po imenu \"$a\"'; // ORPHANED
$string['cannotgetcats'] = 'Nije moguće dobiti zapis kategorije'; // ORPHANED
$string['cannotgetdata'] = 'Nije moguće dobiti podatak'; // ORPHANED
$string['cannotgradeuser'] = 'Nije moguće oceniti ovog korisnika'; // ORPHANED
$string['cannotimport'] = 'Greška prilikom uvoza'; // ORPHANED
$string['cannotimportformat'] = 'Oprostite, ali uvoz ovog formata još uvek nije implementiran'; // ORPHANED
$string['cannotimportgrade'] = 'Greška u uvozu ocena'; // ORPHANED
$string['cannotinsertgrade'] = 'Nije moguće ubaciti stavku ocene bez id oznake kursa!'; // ORPHANED
$string['cannotinsertrate'] = 'Nije bilo moguće ubaciti novo ocenjivanje ($a->id = $a->rating)'; // ORPHANED
$string['cannotmailconfirm'] = 'Greška u slanju e-poruke sa potvrdom o promeni lozinke'; // ORPHANED
$string['cannotmetacourse'] = 'Nije moguće dodati izabrani kurs ovom meta kursu!'; // ORPHANED
$string['cannotmoverolewithid'] = 'Nije moguće premestiti ulogu sa ID $a'; // ORPHANED
$string['cannotnetgeo'] = 'Nije moguće uspostaviti vezu sa NetGeo serverom na http://netgeo.caida.org. Molimo proverite podešavanja Vašeg proksi servera ili još bolje instalirajte datoteku za MaxMind GeoLite City'; // ORPHANED
$string['cannotopencsv'] = 'Nije moguće otvoritu CSV datoteku'; // ORPHANED
$string['cannotopenfile'] = 'Nije moguće otvoriti datoteku ($a)'; // ORPHANED
$string['cannotopenforwrit'] = 'Nije moguće otvoriti za upsisivanje: $a'; // ORPHANED
$string['cannotopentemplate'] = 'Nije moguće otvoriti datoteku šablona ($a)'; // ORPHANED
$string['cannotopenzip'] = 'Nije moguće otvoriti zip arhivu. Verovatno je u pitanju greška sa zip ekstenzijom na 64-bitnom operativnom sistemu.'; // ORPHANED
$string['cannotoverridebaserole'] = 'Nije moguće menjati osnovne mogućnosti uloge'; // ORPHANED
$string['cannotoverriderolehere'] = 'Nije Vam dozvljeno da menjate ovu ulogu (id = $a->roleid) u ovom kontekstu ($a->context)'; // ORPHANED
$string['cannotreadfile'] = 'Nije moguće pročitati datoteku ($a)'; // ORPHANED
$string['cannotreadtmpfile'] = 'Greška u čitanju privremene datoteke'; // ORPHANED
$string['cannotreaduploadfile'] = 'Nije bilo moguće pročitati postavljenu datoteku'; // ORPHANED
$string['cannotremovefrommeta'] = 'Nnje bilo moguće ukloniti izabrani kurs iz ovog metakursa!'; // ORPHANED
$string['cannotresetguestpwd'] = 'Ne možete te da resetujete lozinku gosta'; // ORPHANED
$string['cannotresetthisrole'] = 'Nije moguće resetovati ovu ulogu'; // ORPHANED
$string['cannotrestore'] = 'Pojavila se greška te poroces restauracije ne može biti završen!'; // ORPHANED
$string['cannotrestoreadminorcreator'] = 'Morate da bude kreator kursa ili administrator kako bi restauraciju rezervne kopije u novi kurs'; // ORPHANED
$string['cannotrestoreadminoredit'] = 'Morate da bude predavač ili administrator kako bi restauraciju rezervne kopije u izabrani kurs'; // ORPHANED
$string['cannotsaveblock'] = 'Greška prilikom pokušaja da se sačuva konfoguracija blokova'; // ORPHANED
$string['cannotsavecomment'] = 'Nije moguće sačuvati komentar'; // ORPHANED
$string['cannotsavedata'] = 'Nije moguće sačuvati podatke'; // ORPHANED
$string['cannotsavefile'] = 'Nije moguće sačuvati datoteku \"$a\"!'; // ORPHANED
$string['cannotsetpassword'] = 'Nije moguće podesiti korisničku lozinku!'; // ORPHANED
$string['cannotsettheme'] = 'Nije moguće podesiti šemzu izgleda'; // ORPHANED
$string['cannotsetupblock'] = 'NIJE bilo moguće uspešno podesiti tabele blokova !'; // ORPHANED
$string['cannotsetupcapformod'] = 'Nije bilo moguće podesiti mogućnosti za  $a'; // ORPHANED
$string['cannotsetupcapforplugin'] = 'Nije bilo moguće podesiti mogućnosti za  $a'; // ORPHANED
$string['cannotshowhidecoursesincategory'] = 'Nije moguće prikazati/sakriti kurseve u kategoriji $a'; // ORPHANED
$string['cannotupdatemod'] = 'Nije bilo moguće ažurirati $a'; // ORPHANED
$string['cannotupdatepasswordonextauth'] = 'Ažuriranje lozinke na eksternom sistemu za proveru identiteta: $a nije uspelo. Za više detanja pogledajte zapise na serveru.'; // ORPHANED
$string['cannotupdateprofile'] = 'Greška prilikom ažuriranja korisničkog zapisa'; // ORPHANED
$string['cannotupdaterss'] = 'Nije moguće ažurirati RSS izvor vesti'; // ORPHANED
$string['cannotupdateusermsgpref'] = 'Nije moguće ažuriranje korisnikovih podešavanja privatnih poruka'; // ORPHANED
$string['cannotupdateuseronexauth'] = 'Ažuriranje korisničkih podataka na eksternom sistemu za proveru identiteta: $a nije uspelo. Za više detanja pogledajte zapise na serveru.'; // ORPHANED
$string['cannotuploadfile'] = 'Greška u procesisiranju postavljanja datoteke'; // ORPHANED
$string['cannotuseadmin'] = 'Morate da budete administrator da biste koristili ovu stranicu'; // ORPHANED
$string['cannotuseadminadminorteacher'] = 'Morate da budete predavač ili administrator da biste koristili ovu stranicu'; // ORPHANED
$string['cannotusepage'] = 'Samo predavači i adminstratori mogu da koriste ovu stranicu'; // ORPHANED
$string['cannotusepage2'] = 'Oprostite, ne možet da koristite ovu stranicu'; // ORPHANED
$string['cannotwritefile'] = 'Nije moguće upisivanje u ovu datoteku ($a)'; // ORPHANED
$string['commentmisconf'] = 'ID komentara je pogrešno konfigurisan'; // ORPHANED
$string['couldnotupdatenoexistinguser'] = 'Nije moguće ažurirati korisnika - korisnik ne postoji'; // ORPHANED
$string['coursedoesntexistcannotcreategroup'] = 'Nije moguće kreirati grupu: kurs ne postoji'; // ORPHANED
$string['courseidnotfound'] = 'Id kursa ne postoji'; // ORPHANED
$string['coursemisconf'] = 'Kurs je pogrešno konfigurisan'; // ORPHANED
$string['courserequestdisabled'] = 'Oprostite, ali administator je onemogućio traženi kurs'; // ORPHANED
$string['csvinvalidcols'] = '<b>Neispravna CSV datoteka:</b> Prva linija mora da sadrži \"Header Fields\" a datoteeka mora da bude tipa <br />\"Expanded Fields/Comma Separated\"<br />ili<br /> \"Expanded Fields with CAVV Result Code/Comma Separated\"'; // ORPHANED
$string['csvinvalidcolsnum'] = 'Neispravna CSV datoteka - svaka linija mora da ima 49 ili 70 polja'; // ORPHANED
$string['csvloaderror'] = 'Pojavila se greška u toku učitavanja CSV datoteke!'; // ORPHANED
$string['dbconnectionfailed'] = '<p>Greška: Konekcija sa bazom podataka nije uspela</p>
<p>Moguće je da je baza podataka preopterećena ili na drugi način ne funkioniše pravilno.</p>
<p>Administrator sajta bi, takođe, trebalo da proveri da li su u config.php datoteci svi detalji vezani za bazu podataka ispravno navedeni</p>$a'; // ORPHANED
$string['dbdriverproblem'] = '<p>Greška: uočen je problem sa drajverom baze podataka</p>
<p>Administrator sajta bi trebalo da proveri konfiguraciju servera</p><p>$a</p>'; // ORPHANED
$string['dbsessionbroken'] = 'Uočen je ozbiljan problem sa sesijom baze podataka.<br /><br />Molimo, obavestite administratora servera.'; // ORPHANED
$string['dbsessionhandlerproblem'] = 'Podešavanje sessije baze podataka nije uspeleo.<br /><br />Molimo, obavestite administratora servera.'; // ORPHANED
$string['dbsessionmysqlpacketsize'] = '<br /><br />Molimo, obavestite administratora. Ovaj problem je najverovatnije'; // ORPHANED
$string['ddlfieldalreadyexists'] = 'Polje \"$a\" ne postoji'; // ORPHANED
$string['ddlfieldnotexist'] = 'Polje \"$a->fieldname\" ne postoji u tabeli \"$a->tablename\"'; // ORPHANED
$string['ddltablealreadyexists'] = 'Tabela \"$a\" već postoji'; // ORPHANED
$string['ddltablenotexist'] = 'Tabela \"$a\" ne postoji'; // ORPHANED
$string['ddlunknownerror'] = 'Nepoznata DDL greška'; // ORPHANED
$string['ddlxmlfileerror'] = 'Pronađena je greška u datoteci XML baze podataka'; // ORPHANED
$string['destinationcmnotexit'] = 'Odredišni kurs ne postoji'; // ORPHANED
$string['detectedbrokenplugin'] = 'Dodatak \"$a\" je oštećen. Oprostite ali nije moguće nastaviti.'; // ORPHANED
$string['dmlreadexception'] = 'Greška prilikom čitanja iz baze podataka'; // ORPHANED
$string['dmlwriteexception'] = 'Greška prilikom upisvanja u bazu podtaka'; // ORPHANED
$string['duplicaterolename'] = 'Već postoji uloga sa ovim imenom!'; // ORPHANED
$string['duplicateroleshortname'] = 'Već postoji uloga sa ovim kratkim imenom!'; // ORPHANED
$string['emailfail'] = 'Slanje e-pošte nije uspelo'; // ORPHANED
$string['error'] = 'Pojavila se greška'; // ORPHANED
$string['errorcreatingrole'] = 'Greška u kreiranju uloge'; // ORPHANED
$string['errorsettinguserpref'] = 'Greška u podešavanju korisnikovih preferenci'; // ORPHANED
$string['expiredkey'] = 'Ključ je istekao'; // ORPHANED
$string['failtoloadblocks'] = 'Jedan ili više blokova je registrovano u bazzi podataka, ali nisu uspeli da se učitaju!'; // ORPHANED
$string['filenotreadable'] = 'Datoteka nije čitljiva'; // ORPHANED
$string['filterdoesnothavelocalconfig'] = 'Filter $a ne dopušta lokalnu konfiguraciju.'; // ORPHANED
$string['filternotactive'] = 'Filter $a trenutno nije aktivan'; // ORPHANED
$string['filternotinstalled'] = 'Filter $a trenutno nije instaliran'; // ORPHANED
$string['generalexceptionmessage'] = 'Izuzetak - $a'; // ORPHANED
$string['gradepubdisable'] = 'Objavljivanje ocena je onemogućeno'; // ORPHANED
$string['groupiddoesntexistcannotdelete'] = 'Nije moguće obrisati grupu: id grupe ne postoji'; // ORPHANED
$string['guestnocomment'] = 'Gostima nije dozvoljeno da postuju komentare'; // ORPHANED
$string['guestnorate'] = 'Gostima nije dozvoljeno da ocenjuju pojmove'; // ORPHANED
$string['hackdetected'] = 'Otkriven je hakerski napad!'; // ORPHANED
$string['headersent'] = 'Zaglavlja su već poslata'; // ORPHANED
$string['idnumbertaken'] = 'ID broj se već koristi za drugi kurs'; // ORPHANED
$string['importformatnotimplement'] = 'Oprostite, ali uvoz ovog formata još nije implementiran!'; // ORPHANED
$string['incorrectext'] = 'Datoteka ima neispravnu ekstenziju'; // ORPHANED
$string['invalidaccess'] = 'Neispravan pristup ovoj stranici'; // ORPHANED
$string['invalidaccessparameter'] = 'Neispravan parameter pristupa'; // ORPHANED
$string['invalidaction'] = 'Neispravan parameter akcije'; // ORPHANED
$string['invalidactivityid'] = 'Neispravan ID Aktivnosti'; // ORPHANED
$string['invalidargorconf'] = 'Nisu prosleđen ispravni argumenti ili pogrešna konfiguracija servera'; // ORPHANED
$string['invalidarguments'] = 'Nisu prosleđen ispravni argumenti'; // ORPHANED
$string['invalidblockinstance'] = 'Neispravna instanca bloka ѕa $a'; // ORPHANED
$string['invalidcategory'] = 'Pogrešna kategorija'; // ORPHANED
$string['invalidcategoryid'] = 'Pogrešan id kategoeije!'; // ORPHANED
$string['invalidcomment'] = 'Komentar je neispravan'; // ORPHANED
$string['invalidconfirmdata'] = 'Neispravni podaci za potvrdu'; // ORPHANED
$string['invalidcourselevel'] = 'Pogrešan nivo konteksta'; // ORPHANED
$string['invalidcoursenameshort'] = 'Neispravno kratko naziv kursa'; // ORPHANED
$string['invaliddata'] = 'Prosleđeni podaci su neispravni'; // ORPHANED
$string['invalidelementid'] = 'Pogrešan id elementa'; // ORPHANED
$string['invalidenrol'] = 'Pokušan je nedozvoljen upis na kurs'; // ORPHANED
$string['invalidentry'] = 'Ovo nije ispravan unos'; // ORPHANED
$string['invalidevent'] = 'Neispravan događaj'; // ORPHANED
$string['invalidformatpara'] = 'Pogrešan format za parametar izbora'; // ORPHANED
$string['invalidfunction'] = 'Neispravna funkcija'; // ORPHANED
$string['invalidgradeitmeid'] = 'Neispravan id stavke ocene'; // ORPHANED
$string['invalidgroupid'] = 'Naveden je neispravan id grupe'; // ORPHANED
$string['invaliditemid'] = 'Neispravan id stavke'; // ORPHANED
$string['invalidkey'] = 'Neispravan ključ'; // ORPHANED
$string['invalidlegacy'] = 'Neispravna definicija nasleđene uloge za tip: $a'; // ORPHANED
$string['invalidmode'] = 'Neispravan mod ($a)'; // ORPHANED
$string['invalidmodule'] = 'Neispravan modul'; // ORPHANED
$string['invalidmoduleid'] = 'Neispravan modul ID: $a'; // ORPHANED
$string['invalidmodulename'] = 'Neispravan naziv modula: $a'; // ORPHANED
$string['invalidnum'] = 'Neispravna numerička vrednost'; // ORPHANED
$string['invalidoutcome'] = 'Neispravan id ishoda'; // ORPHANED
$string['invalidpagesize'] = 'Neispravna veličina stranice'; // ORPHANED
$string['invalidpaymentmethod'] = 'Neispravan mačin plaćanja $a'; // ORPHANED
$string['invalidqueryparam'] = 'GREŠKA: Pogrešan broj parametara upita. Očekivano $a->expected, a dobijeno $a->actual.'; // ORPHANED
$string['invalidrecord'] = 'Nije moguće naći zapis podatka u tabeli baze $a.'; // ORPHANED
$string['invalidrecordunknown'] = 'Nije moguće naći zapis podatka u bazi'; // ORPHANED
$string['invalidroleid'] = 'Neispravan ID uloge'; // ORPHANED
$string['invalidsection'] = 'Zapis modula kursa sadrži neispravnu sekciju'; // ORPHANED
$string['invalidshortname'] = 'To je neispravno kratko ime kursa'; // ORPHANED
$string['invalidstatedetected'] = 'Nešto je krenulo naopako: $a. Normalno, ovo ne bi trebalo da se događa.'; // ORPHANED
$string['invaliduser'] = 'Neispravan korisnik'; // ORPHANED
$string['invaliduserid'] = 'Neispravan id korisnika'; // ORPHANED
$string['logfilenotavailable'] = 'Zapisi nisu dostupni'; // ORPHANED
$string['messagingdisable'] = 'Slanje poruka na ovom sajtu nije omogućeno'; // ORPHANED
$string['mimetexisnotexist'] = 'Vaš sistem nije konfigursan da bi mofao da pokrene mimeTeX. Morate da preuzmete odgovarajuću izvršnu datoteku za Vašu PHP_OS platformu sa <a href=\"http://moodle.org/download/mimetex/\">http://moodle.org/download/mimetex/</a>, ili da pribavite C izvorni kod sa <a href=\"http://www.forkosh.com/mimetex.zip\"> http://www.forkosh.com/mimetex.zip</a>,  da ga kompajlirate i postavite izvršmu datoteku u Vaš moodle/filter/tex/ direktorijum'; // ORPHANED
$string['missingkeyinsql'] = 'Greška: nedostaje parametar \"$a\" u upitu'; // ORPHANED
$string['missingparam'] = 'Nedostaje neophodni parametar ($a)'; // ORPHANED
$string['missingparameter'] = 'Nedostaje parametar'; // ORPHANED
$string['missinguseranditemid'] = 'Nedostaje userid i itemid'; // ORPHANED
$string['missingvarname'] = 'Nedostaje ime neophodne varijable'; // ORPHANED
$string['mixedtypesqlparam'] = 'GREŠKA: Izmešani tipovi sql parametara upita!!!'; // ORPHANED
$string['mnetdisable'] = 'MNET je isključen'; // ORPHANED
$string['mnetlocal'] = 'Udaljeni MNET korisnik ne može da se prijavi lokalno'; // ORPHANED
$string['moduledisable'] = 'Ovaj modul ($a) je onemogućen za ovaj konkretan kurs'; // ORPHANED
$string['moduledoesnotexist'] = 'Ovaj modul ne postoji'; // ORPHANED
$string['moduleinstancedoesnotexist'] = 'Instanca ovog modula ne postoji'; // ORPHANED
$string['multiplerecordsfound'] = 'Pronađeni su višestruki zapisi, a očekivan je samo jedan zapis.'; // ORPHANED
$string['mustbeloggedin'] = 'Morate biti prijavljeni na sistem kako biste ovo uradili'; // ORPHANED
$string['needcopy'] = 'Prvo morate nešto da kopirate!'; // ORPHANED
$string['needcoursecategroyid'] = 'Bilo id kursa ili kategorije mora biti naveden'; // ORPHANED
$string['needphpext'] = 'Potrebi je da dodate $a podršku za Vašu PHP instalaciju'; // ORPHANED
$string['noadmins'] = 'Nema administratora!'; // ORPHANED
$string['noblocks'] = 'Nijedan blok nije pronađen!'; // ORPHANED
$string['nodata'] = 'Nema podataka'; // ORPHANED
$string['noexistingcategory'] = 'Nema kategorije'; // ORPHANED
$string['nofile'] = 'Datoteka nije navedena'; // ORPHANED
$string['nofiltersenabled'] = 'Nijedan filter nije omogućen'; // ORPHANED
$string['nofolder'] = 'Traženi direktorijum ne postoji'; // ORPHANED
$string['noguest'] = 'Ovde nema gostiju!'; // ORPHANED
$string['noparticipants'] = 'Nije pronađen ni jedan učesnik na ovom kursu'; // ORPHANED
$string['nopermissiontocomment'] = 'Ne možete da dodate komentar u ovaj rečnik!'; // ORPHANED
$string['nopermissiontodelentry'] = 'Ne možete da brišete unose drugih korisnika!'; // ORPHANED
$string['nopermissiontoeditcomment'] = 'Ne možete da uređujete komentare drugih korisnika!'; // ORPHANED
$string['nopermissiontohide'] = 'Nemate ovlašćenja za sakrivanje!'; // ORPHANED
$string['nopermissiontoimportact'] = 'Nemate neophodna ovlašćenja da biste uvezli aktivnosti u ovaj kurs'; // ORPHANED
$string['nopermissiontolock'] = 'Nemate ovlašćenja za zaključavanje!'; // ORPHANED
$string['nopermissiontomanagegroup'] = 'Nemate neophodna ovlašćenja da biste upravljali grupama'; // ORPHANED
$string['nopermissiontomkdir'] = 'Nije moguće kreirati folder. Administrator sajta treba da reši problem'; // ORPHANED
$string['nopermissiontorate'] = 'Ocenjivanje stavki nije dozvoljeno'; // ORPHANED
$string['nopermissiontoshow'] = 'Nemate ovlašćenja da vidite ovo!'; // ORPHANED
$string['nopermissiontounlock'] = 'Nemate ovlašćenja za otključavanje!'; // ORPHANED
$string['nopermissiontoviewletergrade'] = 'Nedostaje ovlašćenje da bi se videle slovne ocene'; // ORPHANED
$string['nopermissiontoviewpage'] = 'Nije Vam dozvoljeno da gledate ovu stranicu'; // ORPHANED
$string['nositeid'] = 'Ne postoji ID sajta'; // ORPHANED
$string['notallowedtoupdateprefremotely'] = 'Nemate dozvolu da ažurirate preference ovog korisnika udaljeno'; // ORPHANED
$string['notlocalisederrormessage'] = '$a'; // ORPHANED
$string['notmemberofgroup'] = 'Niste član ove grupe'; // ORPHANED
$string['notownerofkey'] = 'Niste vlasnik ovg ključa'; // ORPHANED
$string['nousers'] = 'Ne postoji takav korisnik'; // ORPHANED
$string['prefixcannotbeempty'] = '<p>Greška: prefiks tabela baze podataka ne može biti prazan ($a)</p>
<p>Administrator sajta mora da reši ovaj problem.</p>'; // ORPHANED
$string['prefixtoolong'] = '<p>Greška: prefiks tabele baze podataka je predug ($a->dbfamily)</p>
<p>Administrator sajta mora da reši ovaj proble. Maksimalna dužina prefiksa tabela u $a->dbfamily je $a->maxlength karaktera.</p>'; // ORPHANED
$string['reportnotavailable'] = 'Ova vrsta izveštaj je jedino dostupna za sajt.'; // ORPHANED
$string['reverseproxyabused'] = 'Oprostite, uključen je reverzni proksi pa serveru ne može direktno da se pristupi. <br />Kontaktirajte server administratora.'; // ORPHANED
$string['rpcerror'] = 'RPC enrol/mnet/available_courses: ($a)'; // ORPHANED
$string['secretalreadyused'] = 'Link za potvrdu promene lozinke je već iskorišćen. Lozinka nije promenjena'; // ORPHANED
$string['sectionnotexist'] = 'Ova sekcija ne postoji'; // ORPHANED
$string['sessioncookiesdisable'] = 'Nepravilna upotreba require_key_login() - kolačići sesije moraju biti onemogućeni!'; // ORPHANED
$string['sessionipnomatch2'] = 'Oprostite, ali izgleda da se, od trenutka kada ste se prvi put prijavili na sistem, promenila Vaša IP adresa. Ovo bezbedosno svojstvo sprečava zlonamerne od krađe Vašeg identiteta dok ste prijavljeni na ovom sajtu. Ovu grešku možete videti ukoliko koristite bežični pristup Internetu. Molimo Vas da kontaktirate administratora ѕa pomoć.<br /><br />Ukoliko želite da nastavite molimo vas pritisnite na tastaturi F5 da biste osvežili ovu stranicu.'; // ORPHANED
$string['sessionnotwritable'] = 'Uočen je problem sa dozvolom za upisivanje i direktorijum sesija.<br /><br />Obavestite server administratora.'; // ORPHANED
$string['shortnametaken'] = 'Kratak naziv već koristi drugi kurs'; // ORPHANED
$string['spellcheckernotconf'] = 'Provera pravopisa nije konfigurisana'; // ORPHANED
$string['sslonlyaccess'] = 'Iz razloga bezbednosti dozvoljenu su samo https konekcije.'; // ORPHANED
$string['statsdisable'] = 'Statistika nije omgućena'; // ORPHANED
$string['statsnodata'] = 'Nema dostupnih podataka za tu kombinaciju kursa i vremenskog perioda.'; // ORPHANED
$string['storedfilecannotread'] = 'Nije moguće pročitati datoteku - ili datoteka ne postoji ili postoje problemi sa ovlašćenjima'; // ORPHANED
$string['storedfilenotcreated'] = 'Nije moguće kreirati datoteku  \"$a->contextid/$a->filearea/$a->itemid/$a->filepath/$a->filename\"'; // ORPHANED
$string['tagdisabled'] = 'Oznake su onemogućene'; // ORPHANED
$string['targetdatabasenotempty'] = 'Ciljna baza podataka nije prazna. Transfer je poništen iz razloga bezbednosti'; // ORPHANED
$string['themenotinstall'] = 'Ova šema izgleda nije instalirana'; // ORPHANED
$string['unknowaction'] = 'Nepoznata akcija!'; // ORPHANED
$string['unknowcategory'] = 'Kategorija nije poznata!'; // ORPHANED
$string['unknowcontext'] = 'Ovo je nepoznati kontekst($a) u get_child_contexts!'; // ORPHANED
$string['unknowformat'] = 'Format nije poznat ($a)'; // ORPHANED
$string['unknowncontext'] = 'Ovo je nepoznat kontekst'; // ORPHANED
$string['unknownjsinrequirejs'] = 'Nije moguće naći JS biblioteku $a'; // ORPHANED
$string['unknowparamtype'] = 'Nepoznati tip parametra $a'; // ORPHANED
$string['unknowquestiontype'] = 'Nepodržani tip pitanja $a'; // ORPHANED
$string['unspecifycourseid'] = 'Mora se navesti id kursa, kratak naziv ili  identifikacioni (id) broj'; // ORPHANED
$string['unsupportedevent'] = 'Nepodržani tip događaja'; // ORPHANED
$string['unsupportedwebserver'] = 'Oprostite, softver za Web server ($a) nije podržan.'; // ORPHANED
$string['upgraderequires19'] = 'Greška: Nova verzija Moodlea je instalirana na server, Na žalost,  ažuriranje sa prethodne verzije nije podržano.<br />MOlimo Vas da prvo ažurirate Moodle na poslednju 1.9.x verziju. Na prethodnu verziju se, takođe, možete bratiti tako što ćete ponovo instalirati originalne datoeke.'; // ORPHANED
$string['upgraderunning'] = 'Sajt se ažurira, molimo pokušajte kasnije'; // ORPHANED
$string['urlnotdefinerss'] = 'Nije defisana URL adresa za RSS izvor vesti'; // ORPHANED
$string['useriddoesntexist'] = 'Id korisnika ne postoji'; // ORPHANED
$string['userisnotaparticipant'] = 'Korisnik nije učesnik kursa'; // ORPHANED
$string['usermustbemnet'] = 'Korisnici na MNET kontrolnoj listi pristupa mora biti udaljeni MNET korisnik'; // ORPHANED
$string['usernotcreated'] = 'Korisnik nije mogao biti kreiran'; // ORPHANED
$string['usernotincourse'] = 'Ovaj korsinik nije na ovom kursu'; // ORPHANED
$string['wrongcall'] = 'Ovaj skript je pozvan pogrešno'; // ORPHANED
$string['wrongcontextid'] = 'ID konteksta je neisoravan (nije ga moguće naći)'; // ORPHANED
$string['wrongroleid'] = 'Neispravan ID uloge'; // ORPHANED
$string['wscouldnotaddgroupmembernopermission'] = 'WS - Nije bilo moguće dodati člana grupe -Nema ovlašćenja'; // ORPHANED
$string['wscouldnotcreateecoursenopermission'] = 'WS - Nije bilo moguće kreirati kurs - Nema ovlašćenja'; // ORPHANED
$string['wscouldnotcreateeuserindb'] = 'WS - Nije bilo moguće kreirati korisnika'; // ORPHANED
$string['wscouldnotcreateeusernopermission'] = 'WS - Nije bilo moguće kreirati korisnika -Nema ovlašćenja'; // ORPHANED
$string['wscouldnotcreategroupnopermission'] = 'WS - Nije bilo moguće kreirati grupu -Nema ovlašćenja'; // ORPHANED
$string['wscouldnotdeletegroupnopermission'] = 'WS - Nije bilo moguće obrisati grupu -Nema ovlašćenja'; // ORPHANED
$string['wscouldnotdeletenoexistinguser'] = 'WS - Nije bilo moguće obrisati korisnika -Korisnik ne postoji'; // ORPHANED
$string['wscouldnotdeleteusernopermission'] = 'WS - Nije bilo moguće obrisati korisnika -Nema ovlašćenja'; // ORPHANED
$string['wscouldnotremovegroupmembernopermission'] = 'WS - Nije bilo moguće ukloniti člana grupe - Nema ovlašćenja'; // ORPHANED
$string['wscouldnotupdatenoexistinguser'] = 'WS - Nije bilo moguće ažurirati korisnika - Korisnik ne postoji'; // ORPHANED
$string['wscouldnotupdateuserindb'] = 'WS - Nije bilo moguće ažurirati korisnika'; // ORPHANED
$string['wscouldnotupdateusernopermission'] = 'WS - Nije bilo moguće ažurirati korisnika - Nema ovlašćenja'; // ORPHANED
$string['wscouldnotvieweusernopermission'] = 'WS - Nije bilo moguće videti korisnika - Nema ovlašćenja'; // ORPHANED
$string['wwwrootmismatch'] = 'Otkriven je neispravan pristup. Ovom serveru se jedino može pristupiti preko adres \"$a\". Molimo Vas da obavestite administratora.'; // ORPHANED
$string['wwwrootslash'] = 'U config.php datoteci neispravno je podešena linija \$CFG->wwwroot. Ona na kraju ne sme da ima kosu crtu  /<br />Molimo Bas, da o tome obavestite administratora.'; // ORPHANED
$string['xmldberror'] = 'XMLDB greška!'; // ORPHANED
$string['younotteacher'] = 'vi niste predavač!'; // ORPHANED
$string['cannotaddblock'] = '$a blok nije mogao biti dodat listi blokova!'; // ORPHANED
$string['cannotaddcmtosection'] = 'Nije bilo moguće dodati novi modul u ovu sekciju'; // ORPHANED
$string['cannotaddnewinstance'] = 'Nije bilo moguće dodati instancu $a'; // ORPHANED
$string['cannotcreatedefaultcat'] = 'Greška priliko kreiranja podrazumevane kategorije za kontekst $a'; // ORPHANED
$string['cannotcreatefield'] = 'Greška prilikom kreiranja novog polja'; // ORPHANED
$string['cannotcreateuser'] = 'Greška u kreiranju zapisa korisnika'; // ORPHANED
$string['cannotdeletecate'] = 'Greška prilikom brisanja kategorije'; // ORPHANED
$string['cannotinsertkey'] = 'Nije moguće ubaciti novi ključ'; // ORPHANED
$string['cannotsetupcategory'] = 'Ozbiljna greška! Nije bilo moguće podesiti podrazumevanu kategoriju kursa!'; // ORPHANED
$string['cannotupdategroup'] = 'Greška u ažuriranju grupe'; // ORPHANED
$string['cannotupdatemodcap'] = 'Nije bilo moguće ažurirati $a mogućnosti!'; // ORPHANED
$string['cannotupdateplugincap'] = 'Nije bilo moguće ažurirati $a mogućnosti!'; // ORPHANED
$string['cannotupdaterate'] = 'Nije bilo moguće ažurirati staro ocenjivanje ($a->id = $a->rating)'; // ORPHANED
$string['cannotupdaterole'] = 'Nije moguće ažururati ulogu!'; // ORPHANED
$string['cannotupdateuser'] = 'Ažuriranje korsinika nije uspelo'; // ORPHANED

?>
