<?PHP // $Id$ 
      // feedback.php - created with Moodle 1.9.5 (Build: 20090515) (2007101550)


$string['add_item'] = 'Dodaj pitanje';
$string['add_items'] = 'Dodaj pitanje';
$string['add_pagebreak'] = 'Dodaj prekid stranice';
$string['adjustment'] = 'Poravnanje';
$string['after_submit'] = 'Nakon predaje upitnika';
$string['analysis'] = 'Analiza';
$string['anonymous'] = 'Anonimni upitnik';
$string['anonymous_edit'] = 'Da li je upitnik anoniman?';
$string['anonymous_entries'] = 'Anonimni odgovori';
$string['anonymous_user'] = 'Anonimni korisnik';
$string['append_new_items'] = 'Dodaj nova pitanja';
$string['autonumbering'] = 'Automatski brojevi za svako pitanje';
$string['average'] = 'Prosečno';
$string['bold'] = 'Podebljano';
$string['cancel_moving'] = 'Poništi prebacivanje';
$string['cannotmapfeedback'] = 'Problemi sa bazom podataka. Nije moguće povezati upitnik sa kursom.';
$string['cannotsavetempl'] = 'čuvanje šablona nije dozvoljeno';
$string['cannotunmap'] = 'Problem sa bazom podatkom. Nije moguće razdovojiti upitnik i kurseve';
$string['captcha'] = 'Captcha upit';
$string['captchanotset'] = 'Captcha upit nije podešen';
$string['check'] = 'Višestruki izbor - više odgovora';
$string['check_values'] = 'Mogući odgovori';
$string['checkbox'] = 'Višestruki izbor - dozvoljeno više odgovora (polje za potvrdu)';
$string['choosefile'] = 'Izaberi datoteku';
$string['chosen_feedback_response'] = 'izabrani odgovori iz upitnika';
$string['complete_the_form'] = 'Odgovori na pitanja...';
$string['completed'] = 'završeno';
$string['completed_feedbacks'] = 'Poslatix odgovora';
$string['confirmdeleteentry'] = 'Da li ste sigurni da želite obrisati ovaj unos?';
$string['confirmdeleteitem'] = 'Da li ste sigurni da želite obrisati ovaj element?';
$string['confirmdeletetemplate'] = 'Da li ste sigurni da želite obrisati ovaj šablon?';
$string['confirmusetemplate'] = 'Da li ste sigurni da želite koristiti ovaj šablon?';
$string['continue_the_form'] = 'Nastavi obrazac';
$string['count_of_nums'] = 'Broj cifara';
$string['courseid'] = 'ID Kursa (courseid)';
$string['creating_templates'] = 'Sačuvaj ova pitanja kao novi šablon';
$string['delete_entry'] = 'Obriši unos';
$string['delete_item'] = 'Obriši pitanje';
$string['delete_old_items'] = 'Obriši stara pitanja';
$string['delete_template'] = 'Obriši šablon';
$string['delete_templates'] = 'Obriši šablone';
$string['description'] = 'Opis';
$string['drop_feedback'] = 'Ukloni iz ovog kursa';
$string['dropdown'] = 'Višestruki izbor - dozvoljen jedan odgovor (padajući meni)';
$string['dropdown_values'] = 'Odgovori';
$string['dropdownlist'] = 'Višestruki izbor - jedan odgovor (padajući meni)';
$string['dropdownrated'] = 'Padajući meni (rated)';
$string['edit_item'] = 'Uredi pitanje';
$string['edit_items'] = 'Uredi pitanja';
$string['email_notification'] = 'Pošalji obaveštenje elektronskom poštom';
$string['emailteachermail'] = '$a->username je popunio upitnik : \'$a->feedback\' 

Možete ga pogledati na sledećoj adresi: 

$a->url';
$string['emailteachermailhtml'] = '$a->username je popunio upitnik : <i>\'$a->feedback\'</i><br /><br /> 
Možete ga pogledati <a href=\"$a->url\">na sledećoj adresi</a>.';
$string['entries_saved'] = 'Vaši odgovori su sačuvani. Hvala!';
$string['export_questions'] = 'Izvezi pitanja';
$string['export_to_excel'] = 'Izvezi u Excel';
$string['feedback:complete'] = 'Završi upitnik';
$string['feedback:createprivatetemplate'] = 'Kreiraj privatni šablon';
$string['feedback:createpublictemplate'] = 'Kreiraj javni šablon';
$string['feedback:deletesubmissions'] = 'Obriši završena rešenja';
$string['feedback:deletetemplate'] = 'Obriši šablon';
$string['feedback:edititems'] = 'Uredi pitanja';
$string['feedback:mapcourse'] = 'Poveži kurseve sa opštim upitnicima';
$string['feedback:receivemail'] = 'Dobiti obaveštenje putem e-poruke';
$string['feedback:view'] = 'Pogledaj upitnik';
$string['feedback:viewanalysepage'] = 'Pogledaj stranicu sa analizom rezultata nakon ispunjavanja upitnika';
$string['feedback:viewreports'] = 'Pogledaj izveštaj';
$string['feedback_is_not_for_anonymous'] = 'upitnik nije za anonimne korisnike';
$string['feedback_is_not_open'] = 'Upitnik nije otvoren';
$string['feedback_options'] = 'Opcije za podešavanje upitnika';
$string['feedbackclose'] = 'Upitnik dostupan do';
$string['feedbackcloses'] = 'Upitnik se zatvara';
$string['feedbackopen'] = 'Upitnik dostupan od';
$string['feedbackopens'] = 'Upitnik se otvara';
$string['file'] = 'Datoteka';
$string['filter_by_course'] = 'Filtriraj prema kursu';
$string['handling_error'] = 'Pojavila se greška u modulu Upitnik tokom obrade podataka';
$string['horizontal'] = 'horizontalno';
$string['import_questions'] = 'Uvezi pitanja';
$string['import_successfully'] = 'Uvoz uspešan';
$string['importfromthisfile'] = 'Uvezi iz ove datoteke';
$string['info'] = 'Informacije';
$string['infotype'] = 'Tip informacije';
$string['insufficient_responses_for_this_group'] = 'Ne postoji dovonjno odgovora za ovu grupu';
$string['item_name'] = 'Pitanje';
$string['items_are_required'] = 'Na pitanja obeležena zvezdicom obavezno je odgovoriti';
$string['label'] = 'Oznaka';
$string['line_labels'] = 'Oznaka';
$string['line_values'] = 'Ocenjivanje';
$string['mapcourse'] = 'Poveži kurs';
$string['mapcourseinfo'] = 'Ovo je upitnik dostupan svim kursevima na sajtu koji ga mogu koristi putem bloka Upitnik. Ipak, možete ograničiti kurseve u kojima će se upitnik pojavljivati tako što ćete ih obeležiti. Pretraži kurs i poveži ga sa ovim upitnikom.';
$string['mapcoursenone'] = 'Nijedan kurs nije povezan sa upinkom. Upitnik je dostupan svim kursevima';
$string['mapcourses'] = 'Poveži upitnik sa kursevima';
$string['mappedcourses'] = 'Povezani kursevi';
$string['max_args_exceeded'] = 'Maksimalno 6 argumenata može biti obrađeno, previše je adrgumenata';
$string['maximal'] = 'maksimalno';
$string['mode'] = 'Vrsta upitnika';
$string['modulename'] = 'Upitnik (Feedback)';
$string['modulenameplural'] = 'Upitnici (Feedback Activities)';
$string['move_here'] = 'Premesti ovde';
$string['move_item'] = 'Premesti ovo pitanje';
$string['movedown_item'] = 'Premesti pitanje na dole';
$string['moveup_item'] = 'Premesti pitanje na gore';
$string['multichoice'] = 'Višestruki izbor';
$string['multichoice_values'] = 'Vrednosti za višestruki izbor';
$string['multichoicerated'] = 'Višestruki izbor (rangirano)';
$string['multichoicetype'] = 'Tip višestrukog izbora';
$string['multiple_submit'] = 'Višestruko popunjavanje upitnika<br /><small>Za anonimno anketiranje dozvolite neograničeni broj odgovora svakog korisnika.<br/>Za anketiranja koja nisu anonimna dozvolite korisnicima da ponovo popune anketu.</small>';
$string['name'] = 'Naziv upitnika';
$string['name_required'] = 'Naziv je obavezan';
$string['next_page'] = 'Sledeća stranica';
$string['no_handler'] = 'Nema definisane procedure za obradu događaja za';
$string['no_itemname'] = 'Ne postoji ime stavke';
$string['no_items_available_yet'] = 'Još nije postavljeno nijedno pitanje';
$string['no_templates_available_yet'] = 'Još nema dostupnih šablona';
$string['non_anonymous'] = 'Ime korisnika biće zapisano i prikazano zajedno sa odgovorima';
$string['non_anonymous_entries'] = 'neanonimni odgovori';
$string['not_completed_yet'] = 'Još nije završeno';
$string['not_selected'] = 'Nije izabrano';
$string['notavailable'] = 'ovaj upitnik nije dostupan';
$string['numeric'] = 'Brojčani odgovor';
$string['numeric_range_from'] = 'Rangiraj od';
$string['numeric_range_to'] = 'Rangiraj do';
$string['of'] = 'od';
$string['oldvaluespreserved'] = 'Sva stara pitanja i dodeljene vrednosti biće sačuvani';
$string['oldvalueswillbedeleted'] = 'Trenutno prisutna pitanja i svi odogovori Vaših korisnika biće obrisani';
$string['overview'] = 'Pregled';
$string['page'] = 'Stranica';
$string['page_after_submit'] = 'Stranica koja će biti prikazan korisniku nakon što popuni upitnik';
$string['pagebreak'] = 'Prekid stranice';
$string['parameters_missing'] = 'Parametri koji nedostaju';
$string['picture'] = 'Slika';
$string['picture_file_list'] = 'Spisak slika';
$string['picture_values'] = 'Izaberi jednu ili više<br />slika sa spiska:';
$string['position'] = 'Pozicija';
$string['preview'] = 'Pregled';
$string['previous_page'] = 'Prethodna stranica';
$string['public'] = 'Javni šablon';
$string['question'] = 'Pitanje';
$string['questions'] = 'Pitanja';
$string['radio'] = 'Višestruki izbor - jedan odgovor';
$string['radio_values'] = 'Odgovori';
$string['radiobutton'] = 'Višestruki izbor - dozvoljen jedan odgovor (radio dugmad)';
$string['radiobutton_rated'] = 'Dugme opcije (normirano)';
$string['radiorated'] = 'Dugme opcije (normirano)';
$string['ready_feedbacks'] = 'Spremni upitnici';
$string['relateditemsdeleted'] = 'Svi odgovori Vaših korisnika za ovo pitanje biće takođe obrisani';
$string['required'] = 'Neophodno';
$string['resetting_data'] = 'Poništi odgovore na upitnik';
$string['resetting_feedbacks'] = 'Resetuj upitnike';
$string['response_nr'] = 'Odgovor br.';
$string['responses'] = 'Odgovori';
$string['responsetime'] = 'Vreme odgovora';
$string['save_as_new_template'] = 'Sačuvaj kao novi šablon';
$string['save_entries'] = 'Pošalji svoje odgovore';
$string['save_item'] = 'Sačuvaj pitanje';
$string['saving_failed'] = 'Nije sačuvano';
$string['saving_failed_because_missing_or_false_values'] = 'Odgovori nisu sačuvani zbog vrednosti koje nedostaju ili su pogrešne';
$string['search_course'] = 'Pretraži kurs';
$string['selected_dump'] = 'Izabrani indeksi varijable \$SESSION  prikazani su niže:';
$string['separator_decimal'] = '.';
$string['separator_thousand'] = ',';
$string['show_all'] = 'Prikaži sve';
$string['show_analysepage_after_submit'] = 'Prikaži stranicu sa analizom rezultata nakon ispunjavanja upitnika';
$string['show_entries'] = 'Prikaži odgovore';
$string['show_entry'] = 'Prikaži odgovor';
$string['site_after_submit'] = 'Sajt za posle predaje rešenja';
$string['sort_by_course'] = 'Poređaj prema kursu';
$string['start'] = 'Početak';
$string['stop'] = 'Kraj';
$string['switch_group'] = 'Zameni grupu';
$string['switch_item_to_not_required'] = 'prebaci na:odgovor nije neophodan';
$string['switch_item_to_required'] = 'prebaci na:odgovor je neophodan';
$string['template'] = 'Šablon';
$string['template_saved'] = 'Šablon je sačuvan';
$string['templates'] = 'Šabloni';
$string['textarea'] = 'Duži tekstualni odgovor';
$string['textarea_height'] = 'Broj linija';
$string['textarea_width'] = 'Širina';
$string['textfield'] = 'Kratak tekstualni odgovor';
$string['textfield_maxlength'] = 'Maksimalno dozvoljen broj karaktera';
$string['textfield_size'] = 'Širina tekstualnog polja';
$string['this_feedback_is_already_submitted'] = 'Već ste popunili ovaj upitnik.';
$string['typemissing'] = 'nedostaje vrednost \"tip\"';
$string['update_item'] = 'Sačuvaj promene u pitanju';
$string['url_for_continue_button'] = 'URL za nastavak - dugme';
$string['use_one_line_for_each_value'] = '<br />Upotrebi jedan red za svaki odgovor!';
$string['use_this_template'] = 'Upotrebi ovaj šablon';
$string['using_templates'] = 'Upotrebi šablon';
$string['vertical'] = 'vertikalno';
$string['cannotcreatecompletedfeedback'] = 'Nije moguće kreirati završeni upitnik'; // ORPHANED
$string['cannotcreatetmpfeedback'] = 'Nije moguće kreirati privremeni upitnik'; // ORPHANED
$string['publish_stats_on_students'] = 'Prikaži analizu studentima'; // ORPHANED
$string['all_old_values_will_be_deleted'] = 'Tekuće pitanja i svi odgovori korisnika biće obrisani'; // ORPHANED
$string['all_old_values_will_be_preserved'] = 'Sva stara pitanja i dodeljene vrednosti biće sačuvani'; // ORPHANED
$string['all_related_values_will_be_deleted'] = 'Svi odgovori korisnika na ovo pitanje biće, takođe, obrisani'; // ORPHANED
$string['are_you_sure_to_delete_this_entry'] = 'Da li ste sigurni da želite da obrišete ovaj unos?'; // ORPHANED
$string['are_you_sure_to_delete_this_item'] = 'Da li ste sigurni da želite da obrišete ove elemente?'; // ORPHANED
$string['are_you_sure_to_delete_this_template'] = 'Da li ste sigurni da želite da obrišete ovaj šablon?'; // ORPHANED
$string['are_you_sure_to_use_this_template'] = 'Da li ste sigurni da želite da upotrebite ovaj šablon?'; // ORPHANED
$string['feedback:deletecompleteds'] = 'Obriši popunjene upitnike'; // ORPHANED

?>
