<?PHP // $Id$ 
      // grades.php - created with Moodle 1.8.2+ (2007021520)


$string['addcategory'] = 'Dodaj kategoriju';
$string['addcategoryerror'] = 'Nije moguće dodati kategoriju';
$string['addexceptionerror'] = 'Došlo je do greške tokom dodavanja izuzetka za userid:gradeitem';
$string['allgrades'] = 'Sve ocene po kategorijama';
$string['allstudents'] = 'Svi studenti';
$string['average'] = 'Prosek';
$string['backupwithoutgradebook'] = 'Rezervna kopija podataka ne sadrži podešavanja knjige ocena';
$string['bonuspoints'] = 'Dodatni bodovi';
$string['categories'] = 'Kategorije';
$string['category'] = 'Kategorija';
$string['choosecategory'] = 'Izaberi kategoriju';
$string['creatinggradebooksettings'] = 'Kreiranje podešavanja knjige ocena';
$string['curveto'] = 'Prilagodi';
$string['deletecategory'] = 'Obriši kategoriju';
$string['displaylettergrade'] = 'Prikaz slovnih ocena (A, B, C...)';
$string['displaypercent'] = 'Prikaz procenata';
$string['displaypoints'] = 'Prikaz bodova';
$string['displayweighted'] = 'Prikaz težinskih ocena';
$string['dropped'] = 'Odbačeno';
$string['dropxlowest'] = 'Odbaci X najnižih';
$string['dropxlowestwarning'] = 'Napomena: Ako odbacite X najnižih ocena biće pretpostavljeno da sve stavke unutar kategorije imaju istu vrednost u bodovima. Ukoliko različite stavke nose različit broj bodova rezultati će biti nepredvidljivi';
$string['errorgradevaluenonnumeric'] = 'Dobijena je nenumerička vrednost za visoku ili nisku ocenu za';
$string['errornocategorizedid'] = 'Nije moguće dobiti nekategorizovani identifikator!';
$string['errornocourse'] = 'Nije moguće dobiti informacije o kursu';
$string['errorreprintheadersnonnumeric'] = 'Dobijena je nenumerička vrednost za ponovni ispis zaglavlja';
$string['exceptions'] = 'Izuzeci';
$string['excluded'] = 'Isključeno';
$string['extracredit'] = 'Dodatni bodovi';
$string['extracreditwarning'] = 'Napomena: Podešavanje dodatnih bodova za sve stavke u kategoriji će ih ukloniti iz proračuna ocene, te neće biti ukupnog broja bodova';
$string['forstudents'] = 'Za studente';
$string['gradebook'] = 'Knjiga ocena';
$string['gradebookhiddenerror'] = 'Knjiga ocena je trenutno podešena tako da sve skriva od studenata';
$string['gradecategoryhelp'] = 'Pomoć za kategorije ocena';
$string['gradeexceptions'] = 'Izuzeci od ocenjivanja';
$string['gradeexceptionshelp'] = 'Pomoć za izuzetke od ocenjivanja';
$string['gradehelp'] = 'Pomoć za ocene';
$string['gradeitem'] = 'Moguća ocena';
$string['gradeitemaddusers'] = 'Isključi iz ocenjivanja';
$string['gradeitemmembersselected'] = 'Isključeno iz ocenjivanja';
$string['gradeitemnonmembers'] = 'Uključeno u ocenjivanje';
$string['gradeitemremovemembers'] = 'Uključi u ocenjivanje';
$string['gradeitems'] = 'Moguće ocene';
$string['gradeletter'] = 'Slovne ocene (A, B, C...)';
$string['gradeletterhelp'] = 'Pomoć za slovne ocene';
$string['gradeletternote'] = 'Da biste izbrisali slovnu ocenu samo obrišite bilo koje od <br /> tri tekstulna polja za dato slovo i pritisnite taster za čuvanje podešavanja.';
$string['gradepreferenceshelp'] = 'Pomoć za svojstva ocene';
$string['grades'] = 'Ocene';
$string['gradeweighthelp'] = 'Pomoć za težinsku vrednost ocena';
$string['hideadvanced'] = 'Sakrij napredne opcije';
$string['hidecategory'] = 'Sakriveno';
$string['highgradeascending'] = 'Sortiraj po visini ocene, rastuće';
$string['highgradedescending'] = 'Sortiraj po visini ocene, opadajuće';
$string['highgradeletter'] = 'Gornja granica';
$string['incorrectcourseid'] = 'Identifikator kursa je netačan';
$string['item'] = 'Stavka';
$string['items'] = 'Stavke';
$string['lettergrade'] = 'Slovna ocena';
$string['lettergradenonnumber'] = 'Najniža i/ili najviša ocena nisu bile numeričke za';
$string['letters'] = 'Slova';
$string['lowest'] = 'Najniže';
$string['lowgradeletter'] = 'Donja granica';
$string['max'] = 'Najviše';
$string['maxgrade'] = 'Maksimalna ocena';
$string['median'] = 'Sredina';
$string['min'] = 'Najniže';
$string['mode'] = 'Mod';
$string['no'] = 'Ne';
$string['nocategories'] = 'Kategorije ocena za ovaj kurs ne mogu biti dodate ili pronađene';
$string['nocategoryview'] = 'Nema kategorije po kojoj bi se mogao izvršiti prikaz';
$string['nogradeletters'] = 'Nema podešenih slovnih ocena';
$string['nogradesreturned'] = 'Nema dobijenih ocena';
$string['nolettergrade'] = 'Nema slovne ocene za';
$string['nomode'] = 'Nema';
$string['nonnumericweight'] = 'Dobijena je nenumerička vrednost za';
$string['nonweightedpct'] = 'netežinski %%';
$string['notteachererror'] = 'Morate biti predavač da biste koristili ovu opciju.';
$string['pctoftotalgrade'] = '%% od ukupne ocene';
$string['percent'] = 'Procenat';
$string['percentascending'] = 'Sortiraj po procentima, rastuće';
$string['percentdescending'] = 'Sortiraj po procentima, opadajuće';
$string['percentshort'] = '%%';
$string['points'] = 'bodova';
$string['pointsascending'] = 'Sortiraj po bodovima rastuće';
$string['pointsdescending'] = 'Sortiraj po bodovima opadajuće';
$string['preferences'] = 'Svojstva';
$string['rawpct'] = 'Neobrađeni %%';
$string['reprintheaders'] = 'Ponovni ispis zaglavlja';
$string['respectingcurrentdata'] = 'ostavljajući trenutna podešavanja neizmenjena';
$string['savechanges'] = 'Sačuvaj izmene';
$string['savepreferences'] = 'Sačuvaj svojstva';
$string['scaledpct'] = 'Skalirani %%';
$string['setcategories'] = 'Podesi kategorije';
$string['setcategorieserror'] = 'Prvo morate da podesite kategorije za Vaš kurs pre nego što im odredite težinske vrednosti.';
$string['setgradeletters'] = 'Podesi slovne ocene';
$string['setpreferences'] = 'Podesi svojstva';
$string['setting'] = 'Podešavanje';
$string['settings'] = 'Podešavanja';
$string['setweights'] = 'Podesi težinske vrednosti';
$string['showallstudents'] = 'Prikaži sve studente';
$string['showhiddenitems'] = 'Prikaži skrivene stavke';
$string['sort'] = 'sortiraj';
$string['sortbyfirstname'] = 'Sortiraj po imenu';
$string['sortbylastname'] = 'Sortiraj po prezimenu';
$string['standarddeviation'] = 'Standardno odstupanje';
$string['stats'] = 'Statistika';
$string['statslink'] = 'Statistika';
$string['student'] = 'Student';
$string['total'] = 'Ukupno';
$string['totalweight100'] = 'Ukupna težinska vrednost jednaka je 100';
$string['totalweightnot100'] = 'Ukupna težinska vrednost nije jednaka 100';
$string['uncategorised'] = 'Nekategorisano';
$string['useadvanced'] = 'Koristi napredne opcije';
$string['usepercent'] = 'Koristi procente';
$string['useweighted'] = 'Koristi težinske vrednosti';
$string['viewbygroup'] = 'Grupa';
$string['viewgrades'] = 'Pogledaj ocene';
$string['weight'] = 'težinska vrednost';
$string['weightedascending'] = 'Sortiraj po težinskim procentima rastuće';
$string['weighteddescending'] = 'Sortiraj po težinskim procentima opadajuće';
$string['weightedpct'] = 'težinski %%';
$string['weightedpctcontribution'] = 'doprinos težinskih %% u ukupnoj oceni';
$string['writinggradebookinfo'] = 'Zapisivanje podešavanja knjige sa ocenama';
$string['yes'] = 'Da';
$string['yourgrade'] = 'Vaša ocena';
$string['addfeedback'] = 'Dodaj povratnu informaciju'; // ORPHANED
$string['additem'] = 'Dodaj moguću ocenu'; // ORPHANED
$string['aggregateextracreditmeanall'] = 'Srednja vrednost svih ocena (ekstra bodovi)'; // ORPHANED
$string['aggregateextracreditmeangraded'] = 'Srednja vrednost upisanih ocena (ekstra bodovi)'; // ORPHANED
$string['aggregatemaxall'] = 'Najviša od svih ocena'; // ORPHANED
$string['aggregatemaxgraded'] = 'Najviša od upisanih ocena'; // ORPHANED
$string['aggregatemeanall'] = 'Srednja vrednost svih ocena'; // ORPHANED
$string['aggregatemeangraded'] = 'Srednja vrednost upisanih ocena'; // ORPHANED
$string['aggregatemedianall'] = 'Medijana svih ocena'; // ORPHANED
$string['aggregatemediangraded'] = 'Medijana upisanih ocena'; // ORPHANED
$string['aggregateminall'] = 'Najniža od svih ocena'; // ORPHANED
$string['aggregatemingraded'] = 'Najniža od upisanih ocena'; // ORPHANED
$string['aggregatemodeall'] = 'Mod upisanih ocena od svih ocena'; // ORPHANED
$string['aggregatemodegraded'] = 'Mod upisanih ocena'; // ORPHANED
$string['aggregateweightedmeanall'] = 'Ponderisana srednja vrednost svih ocena'; // ORPHANED
$string['aggregateweightedmeangraded'] = 'Ponderisana srednja vrednost upisanih ocena'; // ORPHANED
$string['aggregation'] = 'Grupisanje'; // ORPHANED
$string['aggregationposition'] = 'Pozicija grupisanja'; // ORPHANED
$string['aggregationview'] = 'Grupni pogled'; // ORPHANED
$string['autosort'] = 'Automatsko sortiranje'; // ORPHANED
$string['averagesdecimalpoints'] = 'Decimale u koloni sa srednjim ocenama'; // ORPHANED
$string['averagesdisplaytype'] = 'Tip prikaza kolone sa srednjim ocenam'; // ORPHANED
$string['badgrade'] = 'Data ocena je neispravna'; // ORPHANED
$string['baduser'] = 'Dati korisnik je neispravan'; // ORPHANED
$string['bulkcheckboxes'] = 'Opsežna polja za potvrdu'; // ORPHANED
$string['calculation'] = 'Proračun'; // ORPHANED
$string['calculationadd'] = 'Dodaj proračun'; // ORPHANED
$string['calculationedit'] = 'Izmeni proračun'; // ORPHANED
$string['calculationsaved'] = 'Proračun sačuvan'; // ORPHANED
$string['calculationview'] = 'Pogledaj proračun'; // ORPHANED
$string['categoriesedit'] = 'Izmeni kategorije'; // ORPHANED
$string['categoryname'] = 'Ime kategorije'; // ORPHANED
$string['compact'] = 'Kompaktno'; // ORPHANED
$string['configaggregationposition'] = 'Mesto kolone za grupisanje u izveštaju ocenjivača, prema osnovnim ocenama'; // ORPHANED
$string['configaggregationview'] = 'Način na koji je grupisanje prikazano: bilo  pored osnovnih ocena ili u kompaktnom obliku u kojem se u istom trenutku vidi samo jedan tip - osnovne ILI grupisane ocene.'; // ORPHANED
$string['configaveragesdecimalpoints'] = 'Broj decimala za prikaz svakog proseka (grupe ili u celini), ispod kolone sa ocenama. Ovo može biti promenjeno za svaku stavku ocenjivanja.'; // ORPHANED
$string['configaveragesdisplaytype'] = 'Navedite kako prikazati proseke za svaku kolone u izveštaju ocenjivača. Podrazumevana i preporučena je nasleđena vrednost, koja prvo proverava tip prikaza za svaku kolonu. Ukoliko tip prikaza nije eksplicitno podešen, on se postavlja na opšti Tip prikaza ocena. Ako su izabrani drugi tipovi prikaza, ignorisaće se pojedinačna podešavanja za svaku kolonu, i koristiće se isknjučivo izabrani tip.'; // ORPHANED
$string['configbulkcheckboxes'] = 'Polja za potvrdu pored svake ocene za obimne operacije sa ocenama.'; // ORPHANED
$string['configdecimalpoints'] = 'Broj decimala prikazanih za svaku ocenu. Ovo može biti promenjeno za svaku stavku ocenjivanja.'; // ORPHANED
$string['configenableajax'] = 'Dodaje nešto AJAX funkcionalnosti izveštaju ocenjivača, čime pojednostavljuje i ubrzava uobičajene operacije. Zavisi od toga da li je korisnik uključio Javascript na svom čitaču.'; // ORPHANED
$string['configgradeboundary'] = 'Procentualne granice, unutar kojih će ocenama biti dodenjljene slovne ocene (ukoliko se koristi ovaj tip prikaza ocena)'; // ORPHANED
$string['configgradedisplaytype'] = 'Ocene se mogu prikazati u osnovnom obliku, ili kao procenti (u odnosu na najmanje i najveće ocene).'; // ORPHANED
$string['configgradeletter'] = 'Slovo ili drugi simbol koji se koriste za prikaѕ opseg ocena'; // ORPHANED
$string['configmeanselection'] = 'Odaberite koji tip ocena će biti uklljučen u kolonu sa prosecima. Polja bez icena mogu biti ignorisana, ili računata kao 0 (podrazumevano podešavanje)'; // ORPHANED
$string['configquickfeedback'] = 'Brza Povratna Informacija dodaje polje za unos teksta uz svaku ocenu na izveštaju ocenjivača, čime omogućuje uređivanje više ocena odjednom. Klikom na duge Ažuriraj primenjujete sve promene odjednom, umesto jednu po jednu.'; // ORPHANED
$string['configquickgrading'] = 'Brzo Ocenjivanje dodaje polje za unos teksta uz svaku ocenu na izveštaju ocenjivača, čime omogućuje uređivanje više ocena odjednom. Klikom na duge Ažuriraj primenjujete sve promene odjednom, umesto jednu po jednu.'; // ORPHANED
$string['configrangesdecimalpoints'] = 'Broj decimala za prikaz svakog tipa opsega, iznad kolone sa ocenama. Ovo može biti promenjeno za svaku stavku ocenjivanja.'; // ORPHANED
$string['configrangesdisplaytype'] = 'Navedite kako prikazati opseg svake kolone u izveštaju ocenjivača. Podrazumevana i preporučena je nasleđena vrednost, koja prvo proverava tip prikaza za svaku kolonu. Ukoliko tip prikaza nije eksplicitno podešen, on se postavlja na opšti Tip prikaza ocena. Ako su izabrani drugi tipovi prikaza, ignorisaće se pojedinačna podešavanja za svaku kolonu, i koristiće se isknjučivo izabrani tip.'; // ORPHANED
$string['configshowaverages'] = 'Prikaži kolonu sa prosecima u izveštaju ocenjivača'; // ORPHANED
$string['configshowcalculations'] = 'Da li prikazati ikonicu digitrona pored svake moguće ocene i kategorije ocenjivanja, kratak opis preko proračunatih ocena i vizuelni indikator da je kolona proračunata.'; // ORPHANED
$string['configshoweyecons'] = 'Da li prikazati ikonicu prikaži/sakrij pored svake ocene (čime se kontroliše da li će ih korisnik videti).'; // ORPHANED
$string['configshowfeedback'] = 'Da li prikazati ikonicu za povratnu informaciju (za dodavanje/menjanje) pored svake ocene.'; // ORPHANED
$string['configshowgroups'] = 'Prikaži zbirove i srednje vrednosti grupa u izveštaju ocenjivača.'; // ORPHANED
$string['configshowlocks'] = 'Da li prikazati ikonicu zaključaj/otključaj pored svake ocene.'; // ORPHANED
$string['configshowranges'] = 'Prikaži red sa opsegom mogućih ocena za svaku od stavki u izveštaju ocenjivača.'; // ORPHANED
$string['configshowuserimage'] = 'Da li prikazati sliku korisnika pored njegovog imena u izvešataju ocenjivača'; // ORPHANED
$string['configstudentsperpage'] = 'Broj studenata prikazanih na svakoj strani izveštaja ocenjivača'; // ORPHANED
$string['contract'] = 'Smanji Kategoriju'; // ORPHANED
$string['createcategory'] = 'Kreiraj Kategoriju'; // ORPHANED
$string['createcategoryerror'] = 'Kreiranje nove kategorije nemoguće'; // ORPHANED
$string['decimalpoints'] = 'Decimale'; // ORPHANED
$string['default'] = 'Podrazumevano'; // ORPHANED
$string['droplow'] = 'Odbaci najniže'; // ORPHANED
$string['editcalculation'] = 'Izmeni proračun'; // ORPHANED
$string['editfeedback'] = 'Izmeni povratnu informaciju'; // ORPHANED
$string['editgrade'] = 'Izmeni ocenu'; // ORPHANED
$string['edittree'] = 'Kategorije'; // ORPHANED
$string['enableajax'] = 'Omogući AJAX'; // ORPHANED
$string['encoding'] = 'Kodiranje'; // ORPHANED
$string['errorcalculationunknown'] = 'Neispravna formula'; // ORPHANED
$string['expand'] = 'Proširi Kategoriju'; // ORPHANED
$string['exportods'] = 'Izvezi ODS'; // ORPHANED
$string['exportplugins'] = 'Izvezi dodatke'; // ORPHANED
$string['exporttxt'] = 'Izvezi TXT'; // ORPHANED
$string['exportxml'] = 'Izvezi XML'; // ORPHANED
$string['feedback'] = 'Povratna informacija'; // ORPHANED
$string['feedbackadd'] = 'Dodaj povratnu informaciju'; // ORPHANED
$string['feedbackedit'] = 'Izmeni povratnu informaciju'; // ORPHANED
$string['feedbacksaved'] = 'Povratna informacija snimljena'; // ORPHANED
$string['feedbackview'] = 'Pogledaj povratnu informaciju'; // ORPHANED
$string['finalgrade'] = 'Konačna ocena'; // ORPHANED
$string['forelementtypes'] = 'za izabrani $a'; // ORPHANED
$string['full'] = 'Pun'; // ORPHANED
$string['grade'] = 'Ocena'; // ORPHANED
$string['gradeboundary'] = 'Granice slovnih ocena'; // ORPHANED
$string['gradecategory'] = 'Kategorija ocena'; // ORPHANED
$string['gradedisplaytype'] = 'Tip prikaza ocena'; // ORPHANED
$string['gradeitemlocked'] = 'Ocenjivanje zaključano'; // ORPHANED
$string['gradeitemsinc'] = 'Moguće ocene koje treba uključiti'; // ORPHANED
$string['grademax'] = 'Najveća ocena'; // ORPHANED
$string['grademin'] = 'Najmanja ocena'; // ORPHANED
$string['gradepass'] = 'Ocena za prolaz'; // ORPHANED
$string['gradepreferences'] = 'Svojstva ocene'; // ORPHANED
$string['gradereports'] = 'Izveštaj o ocenjivanju'; // ORPHANED
$string['graderreport'] = 'Izveštaj ocenjivača'; // ORPHANED
$string['gradetype'] = 'Tip ocene'; // ORPHANED
$string['gradeview'] = 'Pogledaj ocenu'; // ORPHANED
$string['groupavg'] = 'Prosek grupe'; // ORPHANED
$string['hidden'] = 'Sakriveno'; // ORPHANED
$string['hideaverages'] = 'Sakrij proseke'; // ORPHANED
$string['hidecalculations'] = 'Sakrij proračune'; // ORPHANED
$string['hideeyecons'] = 'Sakrij ikonice prikaži/sakrij'; // ORPHANED
$string['hidefeedback'] = 'Sakrij povratne informacije'; // ORPHANED
$string['hidegroups'] = 'Sakrij grupe'; // ORPHANED
$string['hidelocks'] = 'Sakrij zaključavanja'; // ORPHANED
$string['hideranges'] = 'Sakrij opsege'; // ORPHANED
$string['identifier'] = 'Identifikuj korisnika prema'; // ORPHANED
$string['importcsv'] = 'Uvezi CSV'; // ORPHANED
$string['importfailed'] = 'Uvoz nije uspeo'; // ORPHANED
$string['importfile'] = 'Uvezi datoteku'; // ORPHANED
$string['importplugins'] = 'Uvezi dodatke'; // ORPHANED
$string['importpreview'] = 'Uvezi prikaz'; // ORPHANED
$string['importsuccess'] = 'Uvoz ocena uspešan'; // ORPHANED
$string['importxml'] = 'Uvezi XML'; // ORPHANED
$string['inherit'] = 'Nasleđeno'; // ORPHANED
$string['iteminfo'] = 'Informacije o stavci'; // ORPHANED
$string['itemname'] = 'Ime stavke'; // ORPHANED
$string['itemsedit'] = 'Izmeni moguću ocenu'; // ORPHANED
$string['keephigh'] = 'Zadrži najveću'; // ORPHANED
$string['left'] = 'Levo'; // ORPHANED
$string['letter'] = 'Slovo'; // ORPHANED
$string['lock'] = 'Zaključaj'; // ORPHANED
$string['locked'] = 'Zaključano'; // ORPHANED
$string['locktime'] = 'Zaključano do'; // ORPHANED
$string['mapfrom'] = 'Preslikaj iz'; // ORPHANED
$string['mappings'] = 'Preslikavanje mogućih ocena'; // ORPHANED
$string['mapto'] = 'Preslikaj u'; // ORPHANED
$string['meanall'] = 'Sve ocene'; // ORPHANED
$string['meangraded'] = 'Neprazne ocene'; // ORPHANED
$string['meanselection'] = 'Ocene odabrane za računanje proseka'; // ORPHANED
$string['movingelement'] = 'Pomeranje $a'; // ORPHANED
$string['multfactor'] = 'Multiplikator'; // ORPHANED
$string['newcategory'] = 'Nova kategorija'; // ORPHANED
$string['nocategoryname'] = 'Nije dato ime kategorije'; // ORPHANED
$string['noselectedcategories'] = 'nije izabrana nijedna kategorija.'; // ORPHANED
$string['noselecteditems'] = 'nije izabrana nijedna stavka.'; // ORPHANED
$string['onascaleof'] = 'na skali od $a->grademin do $a->grademax'; // ORPHANED
$string['outcome'] = 'Ishod'; // ORPHANED
$string['overridden'] = 'Odbačeno'; // ORPHANED
$string['percentage'] = 'Procenat'; // ORPHANED
$string['plusfactor'] = 'Pomak'; // ORPHANED
$string['quickfeedback'] = 'Brza povratna informacija'; // ORPHANED
$string['quickgrading'] = 'Brzo ocenjivanje'; // ORPHANED
$string['range'] = 'Opseg'; // ORPHANED
$string['rangesdecimalpoints'] = 'Decimale prikazane u opsezima'; // ORPHANED
$string['rangesdisplaytype'] = 'Tip prikaza sa opsezima'; // ORPHANED
$string['rank'] = 'Rang'; // ORPHANED
$string['reportplugins'] = 'Dodaci za izveštaj'; // ORPHANED
$string['right'] = 'Desno'; // ORPHANED
$string['selectdestination'] = 'Izaberi odredište za $a'; // ORPHANED
$string['selectplugin'] = 'Izaberi dodatak'; // ORPHANED
$string['separator'] = 'Graničnik'; // ORPHANED
$string['sepcomma'] = 'Zarez'; // ORPHANED
$string['septab'] = 'Tabulator'; // ORPHANED
$string['showaverages'] = 'Prikaži kolonu sa prosecima'; // ORPHANED
$string['showcalculations'] = 'Prikaži proračune'; // ORPHANED
$string['showeyecons'] = 'Prikaži ikonice za prikaz/sakrivanje'; // ORPHANED
$string['showfeedback'] = 'Prikaži povratne informacije'; // ORPHANED
$string['showgroups'] = 'Prikaži grupe'; // ORPHANED
$string['showlocks'] = 'Prikaži zaključavanja'; // ORPHANED
$string['showranges'] = 'Prikaži opsege'; // ORPHANED
$string['showuserimage'] = 'Prikaži slike iz korisničkih profila'; // ORPHANED
$string['sortasc'] = 'Sortiraj u rastući niz'; // ORPHANED
$string['sortdesc'] = 'Sortiraj u opadajući niz'; // ORPHANED
$string['studentsperpage'] = 'Broj studenata po strani'; // ORPHANED
$string['subcategory'] = 'Normalna Kategorija'; // ORPHANED
$string['synclegacygrades'] = 'Sinhronizuj stare ocene'; // ORPHANED
$string['topcategory'] = 'Natkategorija'; // ORPHANED
$string['turnfeedbackoff'] = 'Isključi povratne informacije'; // ORPHANED
$string['turnfeedbackon'] = 'Uključi povratne informacije'; // ORPHANED
$string['typenone'] = 'Nijedan'; // ORPHANED
$string['typescale'] = 'Skala'; // ORPHANED
$string['typetext'] = 'Tekst'; // ORPHANED
$string['typevalue'] = 'Vrednost'; // ORPHANED
$string['unlock'] = 'Otključaj'; // ORPHANED
$string['unused'] = 'Nekorišćeno'; // ORPHANED
$string['uploadgrades'] = 'Pošalji ocene'; // ORPHANED
$string['usenooutcome'] = 'Bez ishoda'; // ORPHANED
$string['usenoscale'] = 'Bez skala'; // ORPHANED
$string['userpreferences'] = 'Korisničke preferencije'; // ORPHANED
$string['userreport'] = 'Koristi izveštaj o ocenjivanju'; // ORPHANED
$string['configgrandtotalsdisplaytype'] = 'Zbirovi kolona mogu se prikazati u osnovnom obliku ili kao procentii (u odnosu na najmanje i najveće ocene).'; // ORPHANED
$string['configshowgrandtotals'] = 'Prikaži zbirove kolona u izveštaju ocenjivača'; // ORPHANED
$string['configshowscales'] = 'Prikaži red koji prikazuje skalu za svaku moguću ocenu, u izveštaju ocenjivača'; // ORPHANED
$string['grandtotalsdisplaytype'] = 'Način prikaza zbirova kolona'; // ORPHANED
$string['hidegrandtotals'] = 'Sakrij ukupne zbirove'; // ORPHANED
$string['hidescales'] = 'Sakrij skale'; // ORPHANED
$string['raw'] = 'Osnovno'; // ORPHANED
$string['showgrandtotals'] = 'Prikaži zbirove kolona'; // ORPHANED
$string['showscales'] = 'Prikaži skale'; // ORPHANED

?>
