<?PHP // $Id$ 
      // group.php - created with Moodle 1.8.1+ (2007021510)


$string['addgroupstogrouping'] = 'Dodaj grupu grupisanju';
$string['addgroupstogroupings'] = 'Dodaj/izbriši grupe';
$string['adduserstogroup'] = 'Dodaj/izbriši korisnike';
$string['allocateby'] = 'Izdvoj članove';
$string['anygrouping'] = '[Bilo koje grupisanje]';
$string['autocreategroups'] = 'Automatski kreiraj grupe';
$string['backtogroupings'] = 'Nazad u grupisanja';
$string['backtogroups'] = 'Nazad u grupe';
$string['badnamingscheme'] = 'Mora sadržati tačno jedan znak \'@\' ili jedan \'#\'';
$string['createautomaticgrouping'] = 'Kreiraj automatsko grupisanje';
$string['creategroup'] = 'Kreiraj grupu';
$string['creategrouping'] = 'Kreiraj grupisanje';
$string['creategroupinselectedgrouping'] = 'Kreiraj grupu u grupisanju';
$string['createorphangroup'] = 'Kreiraj grupu negrupisanih studenata';
$string['databaseupgradegroups'] = 'Verzija grupa je sada $a';
$string['defaultgroupdescription'] = 'Opis standardne grupe';
$string['defaultgrouping'] = 'Podrazumevano grupisanje';
$string['defaultgroupingname'] = 'Grupisanje';
$string['defaultgroupname'] = 'Grupa';
$string['defaultgroupprefix'] = 'Grupa';
$string['deletegroupconfirm'] = 'Da li ste sigurni da želite da izbrišete grupu \'$a\'?';
$string['deletegrouping'] = 'Izbriši grupisanje';
$string['deletegroupingconfirm'] = 'Da li ste sigurni da želite da izbrišete grupisanje \'$a\'?';
$string['deleteselectedgroup'] = 'Izbrišite označenu grupu';
$string['displaygrouping'] = 'Prikažite grupisanje';
$string['distributealphabetically'] = 'Razvrstaj u grupe abecedno prema prezimenu';
$string['distributeevenly'] = 'Ravnomerno podeli studente koji su preostali';
$string['editgroupingsettings'] = 'Uredi podešavanje grupisanja';
$string['editgroupsettings'] = 'Uredi podešavanje grupe';
$string['enrolmentkey'] = 'Šifra';
$string['erroraddremoveuser'] = 'Greška u dodavanju/brisanju korisnika $a grupi';
$string['erroreditgroup'] = 'Greška u kreiranju/ažuriranju  grupe $a';
$string['erroreditgrouping'] = 'Greška u kreiranju/ažuriranju grupisanja $a';
$string['errorinvalidgroup'] = 'Greška, pogrešna grupa $a';
$string['evenallocation'] = 'Obratite pažnju: kako bi se grupe održale jednakim, trenutni broj članova po grupama se razlikuju od broja koji ste naveli.';
$string['existingmembers'] = 'Postojeći članovi: $a';
$string['filtergroups'] = 'Izdvoj grupe po';
$string['firstname'] = 'ime po azbučnom redu';
$string['group'] = 'Grupa';
$string['groupaddedsuccesfully'] = 'Grupa $a je uspešno dodata';
$string['groupby'] = 'Kreiraj grupe prema broju';
$string['groupdescription'] = 'Opis grupe';
$string['groupinfo'] = 'Informacije o izabranoj grupi';
$string['groupinfomembers'] = 'Informacije o iѕabranim članovima';
$string['groupinfopeople'] = 'Informacije o izabranim ljudima';
$string['grouping'] = 'Grupisanje';
$string['groupingdescription'] = 'Opis grupisanja';
$string['groupingname'] = 'Naѕiv grupisanja';
$string['groupingnameexists'] = 'Ime grupisanja \'$a\' već postoji u ovom kursu, molimo izaberite neko drugo ime.';
$string['groupings'] = 'Grupisanja';
$string['groupmember'] = 'Član grupe';
$string['groupmemberdesc'] = 'Standardna uloga člana grupe';
$string['groupmembers'] = 'Članovi grupe';
$string['groupmembersonly'] = 'Dostupno samo članovima grupe';
$string['groupmembersonlyerror'] = 'Izvinite, morate biti član bar jedne grupe koja se koristi u ovoj aktivnosti.';
$string['groupmemberssee'] = 'Vidi članove grupe';
$string['groupmembersselected'] = 'Članovi izabrane grupe';
$string['groupmode'] = 'Grupni način rada';
$string['groupmodeforce'] = 'Obavezni grupni način rada';
$string['groupmy'] = 'Moja grupa';
$string['groupname'] = 'Naziv grupe';
$string['groupnameexists'] = 'Naziv grupe \'$a\' već postoji u okviru ovog kursa, molim vas izaberite neko drugo';
$string['groupnotamember'] = 'Izvini, nisi član te grupe';
$string['groups'] = 'Grupe';
$string['groupsinselectedgrouping'] = 'Grupe u:';
$string['groupsnone'] = 'Nema grupa';
$string['groupspreview'] = 'Pregled grupe';
$string['groupsseparate'] = 'Razdvoji grupe';
$string['groupsvisible'] = 'Vidljive grupe';
$string['hidepicture'] = 'Sakrij sliku';
$string['javascriptrequired'] = 'Ova stranica zahteva Javascript da bi bilo omogućeno njeno čitanj';
$string['lastname'] = 'prezime po azbučnom redu';
$string['members'] = 'Članova po grupi';
$string['membersingroup'] = 'članovi';
$string['membersofselectedgroup'] = 'Članovi:';
$string['namingscheme'] = 'Šema imenovanja';
$string['namingschemehelp'] = 'napomena: Koristiti \'@\' za predstavljanje slova grupe ili \'#\' za predstavljanje broja grupe';
$string['newpicture'] = 'Nova slika';
$string['nogroups'] = 'Još uvek nema postavljenih grupa u ovom kursu';
$string['nogroupsassigned'] = 'Nema pridruženih grupa';
$string['nopermissionforcreation'] = 'Ne možeš kreirati grupu \"$a\" jer nemaš dozvolu';
$string['notingrouping'] = '[Not in a grouping]';
$string['nousersinrole'] = 'Nema odgovarajućih korisnika sa izabranom ulogom';
$string['number'] = 'Broj grupa ili članova po grupi';
$string['numberofgroups'] = 'Broj grupa';
$string['numberofstudents'] = 'Broj studenata';
$string['overview'] = 'Pregled';
$string['potentialmembers'] = 'Moguću članovi: $a';
$string['prefixforgroupnames'] = 'Prefiks za ime grupa';
$string['printerfriendly'] = 'Prikaz za štampu';
$string['random'] = 'slučajnim izborom';
$string['removegroupfromselectedgrouping'] = 'Izbriši grupu iz grupisanja';
$string['removeselectedusers'] = 'Izbriši označene korisnike';
$string['selectfromrole'] = 'Uloga da bi se birali članovi iz';
$string['selectnumberineachgroup'] = 'Odabran broj u svakoj grupi';
$string['selectnumberofgroups'] = 'Iѕabran broj grupa';
$string['showgroupsingrouping'] = 'Pokaži grupe u grupisanju';
$string['showmembersforgroup'] = 'Prikaži članove grupe';
$string['toomanygroups'] = 'Nedovoljno korisnika da popune ovaj broj grupa - ima samo $a korisnika sa izabranom ulogom';
$string['usergroupmembership'] = 'Izabrano članstvo korisnika';
$string['usestudentsonlyfromselectedgroup'] = 'Koristi samo studente iz trenutno označene grupe';
$string['cancel'] = 'Obustavi'; // ORPHANED
$string['editgroupingpermissions'] = 'Uredi dozvole grupisanja'; // ORPHANED
$string['errorinvalidgrouping'] = 'Greška, pogrešno grupisanje $a'; // ORPHANED
$string['errornotingrouping'] = 'Iѕvini, ne možeš kreirati grupu u $a'; // ORPHANED
$string['errornotingroupingedit'] = 'Iѕvini, ne možeš uređivati grupisanje $a'; // ORPHANED
$string['groupfor'] = 'za grupu'; // ORPHANED
$string['return'] = 'Povratak'; // ORPHANED
$string['save'] = 'Sačuvaj'; // ORPHANED
$string['showusersalreadyingroup'] = 'Prikaži korisnike koji su već u grupama u grupisanju'; // ORPHANED
$string['teachersgroupmark'] = 'Nastavnici ne mogu da markiraju aktivnosti  grupa kojima ne pripadaju'; // ORPHANED
$string['teachersgroupview'] = 'Nastavnici ne mogu da vide aktivnosti grupa kojima ne pripadaju'; // ORPHANED
$string['teachersoverride'] = 'Nastavnici koji nisu ni u jednoj grupi mogu da vide i markiraju akrivnosti svih grupa'; // ORPHANED
$string['upgradeconfirm'] = 'Nažalost, tabele grupa kreirane u Moodle 18DEV moraju biti izbrisani u ovoj verziji. Da li želiš da nastaviš?'; // ORPHANED
$string['viewallgroupsactivities'] = 'Studenti mogu da vide ali ne mogu da učestvuju u aktivnostima svih grupa'; // ORPHANED
$string['viewallgroupsmembers'] = 'Studenti mogu da vide članove svih grupa'; // ORPHANED
$string['viewowngroup'] = 'Studenti mogu da vide članove svih grupa kojima pripadaju'; // ORPHANED

?>
