<?PHP // $Id$ 
      // question.php - created with Moodle 1.9.5 (Build: 20090515) (2007101550)


$string['adminreport'] = 'Izveštaj o mogućim problemima u vašoj bazi podataka sa pitanjima';
$string['availableq'] = 'Dostupno?';
$string['broken'] = 'Ovo je \"prekinut link\", pokazuje na ne postojeći fajl.';
$string['byandon'] = 'uredio/la <em>$a->user</em> (<em>$a->time</em>)';
$string['cannotcopybackup'] = 'Nije moguće kopirati datoteku rezervne kopije';
$string['cannotcreate'] = 'Nije moguće kreirati novi unos u tabeli  question_attempts';
$string['cannotcreatepath'] = 'Nije moguće kreirati putanju: $a';
$string['cannotdeletecate'] = 'Ne možete da obrišete ovu kategoriju, pošto je u ovom kontekstu to podrazumevana kategorija.';
$string['cannotenable'] = 'Tip pitanja $a ne može biti kreiran direktno.';
$string['cannotfindcate'] = 'Nije moguće pronaći zapis kategorije';
$string['cannotfindquestionfile'] = 'Nije moguće pronaći datoteku sa pitanjima u zip arhivi';
$string['cannothidequestion'] = 'Nije bilo moguće sakriti pitanje';
$string['cannotimportformat'] = 'Oprostite, unoz ovog formata još nije implementiran!';
$string['cannotinsertquestion'] = 'Nije moguće ubaciti novo pitanje!';
$string['cannotloadquestion'] = 'Nije moguće učitati pitanje';
$string['cannotmovequestion'] = 'Ne možete da koristite ovaj skript za prebacivanje pitanja koja sa sobom imaju pridružene datoteke iz različitih područja.';
$string['cannotopenforwriting'] = 'Nije moguće otvoriti za upisivanje: $a';
$string['cannotpreview'] = 'Ne možete da pregledate ova pitanja!';
$string['cannotretrieveqcat'] = 'Možete povratiti ovu kategoriju pitanja';
$string['cannotunzip'] = 'Nije moguće raspakovati arhiviranu zip datoteku';
$string['cannotwriteto'] = 'Nije moguće upisati izvezena pitanja u $a';
$string['categorycurrent'] = 'Trenutna kategorija';
$string['categorycurrentuse'] = 'Koristi ovu kategoriju';
$string['categorydoesnotexist'] = 'Ova kategorija ne postoji';
$string['categorymoveto'] = 'Snimi u kategoriji';
$string['changepublishstatuscat'] = '<a href=\"$a->caturl\">Kategoriji \"$a->name\"</a> će u okviru kursa \"$a->coursename\" biti promenjen status deljenja iz <strong>$a->changefrom u $a->changeto</strong>.';
$string['chooseqtypetoadd'] = 'Izaberi tip pitanja za dodavanje';
$string['clicktoflag'] = 'Obeleži ovo pitanje indikatorpm (zastavicom)';
$string['clicktounflag'] = 'Ukloni indikator(zastavicu)';
$string['contexterror'] = 'Ne biste smeli da budete ovde ukoliko niste premsetili kategoriju u drugi kontekst';
$string['copy'] = 'Kopiraj iz $a i promeni linkove.';
$string['created'] = 'Kreirano';
$string['createdby'] = 'Kreirao/la';
$string['createdmodifiedheader'] = 'Kreirano / Poslednja izmena';
$string['createnewquestion'] = 'Kreiraj novo pitanje';
$string['cwrqpfs'] = 'Nasumično izabrana pitanja se biraju iz podkategorija.';
$string['cwrqpfsinfo'] = '<p>Tokom nadogradnje do Moodle verzije 1.9 kategorije pitanja će biti podeljene u različite kontekste. Nekim pitanjima i kategorijama na Vašem sajtu će morati biti promenjen status deljenja. To je neophodno u retkim slučajevima kada je jedno ili više nasumično izabranih pitanja u nekom testu podešeno tako da se biraju iz mešavine deljenih i nedeljenih kategorija (što se pojavljuje na ovom sajtu). Ova pojava je tipična za situaciju u kojoj je pitanje koje se nasumično bira podešeno tako da se bira iz više potkategorija od kojih je bar jedna različitog statusa deljenja u odnosu na nadređenu kategoriju u kojoj je kreirano pitanje koje se nasumično bira.</p>
<p>Sledećim kategorijama pitanja, iz kojih se biraju nasumična pitanja u nadređenim kategorijama, biće promenjen status deljenja u isti onaj kakav važi za kategoriju u kojoj je nasumično izabrano pitanje pri nadogradnji do Moodle verzije 1.9. Pitanja na koja će te izmene uticati će i dalje normalno funkcionisati u svim postojećim testovima sve dok ih ne uklonite iz tih testova.';
$string['cwrqpfsnoprob'] = 'Nema kategorija pitanja na Vašem sajtu na koje bi mogao uticati problem \'Nasumično izabranih pitanja biranih iz potkategorija\'.';
$string['defaultfor'] = 'Podrazumevano za $a';
$string['defaultinfofor'] = 'Podrazumevana kategorija za pitanja deljena u kontekstu \'$a\'.';
$string['deletecoursecategorywithquestions'] = 'Postoje pitanja u bazi pitanja pridruženoj ovoj kategoriji kurseva. Ako nastavite, ona će biti obrisana. Možda biste želeli da ih prvo premestite, koristeći interfejs za baze pitanja.';
$string['disabled'] = 'Onemogućeno';
$string['disterror'] = 'Distribucija $a je izazvala probleme';
$string['donothing'] = 'Nemojte kopirati/premeštati datoteke ili menjati linkove.';
$string['editingcategory'] = 'Uređivanje kategorije';
$string['editingquestion'] = 'Uređivanje pitanja';
$string['emptyxml'] = 'Nepoznata grešja - prazna imsmanifest.xml datoteka';
$string['enabled'] = 'Omogućeno';
$string['erroraccessingcontext'] = 'Ne može se pristupiti kontekstu';
$string['errordeletingquestionsfromcategory'] = 'Greška pri brisanju pitanja iz kategorije $a.';
$string['errorduringpost'] = 'Pojavila se greška u toku post-procesiranja!';
$string['errorduringpre'] = 'Pojavila se greška u toku pre-procesiranja!';
$string['errorduringproc'] = 'Pojavila se greška u toku procesiranja!';
$string['errorfilecannotbecopied'] = 'Greška, ne može se kopirati fajl $a.';
$string['errorfilecannotbemoved'] = 'Greška, ne može se premestiti fajl $a.';
$string['errorfileschanged'] = 'Datoteke grešaka povezane s pitanjima su izmenjene od kad je forma prikazana.';
$string['errormanualgradeoutofrange'] = 'Ocena $a->grade nije između 0 i $a->maxgrade za pitanje $a->name. Rezultat i komentar nisu sačuvani.';
$string['errormovingquestions'] = 'Greška pri premeštanju pitanja sa id vrednostima $a.';
$string['errorpostprocess'] = 'Pojavila se greška u toku post-procesiranja!';
$string['errorpreprocess'] = 'Pojavila se greška u toku pre-procesiranja!';
$string['errorprocess'] = 'Pojavila se greška u toku procesiranja!';
$string['errorprocessingresponses'] = 'Nastala je greška pri obradi Vaših odziva.';
$string['errorsavingcomment'] = 'Greška pri čuvanju komentara za pitanje $a->name u bazi podataka.';
$string['errorupdatingattempt'] = 'Greška pri pokušaju ažuriranja $a->id u bazi podataka.';
$string['exportcategory'] = 'Izvezi kategoriju';
$string['exporterror'] = 'Pojavila se greška u toku eksportovanja!';
$string['filesareacourse'] = 'Oblast fajlova sa kursa';
$string['filesareasite'] = 'Oblast fajlova sa sajta';
$string['filestomove'] = 'Kopiraj / premesti fajlove u $a?';
$string['flagged'] = 'Obeleženo';
$string['flagthisquestion'] = 'Obeleži ovo pitanje';
$string['fractionsnomax'] = 'Jedan od odgovora bi trebao nositi 100%% rezultata tako da je moguće dobiti maksimalan mogući broj bodova za ovo pitanje.';
$string['getcategoryfromfile'] = 'Preuzmi kategoriju iz datoteke';
$string['getcontextfromfile'] = 'Preuzmi kontekst iz datoteke';
$string['ignorebroken'] = 'Ignoriši neispravne linkove';
$string['impossiblechar'] = 'Otkriven je nemogući karakter $a kao znak za zagrade';
$string['invalidconfirm'] = 'Izraz za potvrdu je neispravan';
$string['invalidcontextinhasanyquestions'] = 'Neispravan kontekst prosleđen u question_context_has_any_questions.';
$string['lastmodifiedby'] = 'Poslednji put izmenio/la';
$string['linkedfiledoesntexist'] = 'Datoteka $a do koje vodi link ne postoji';
$string['makechildof'] = 'Napravi potomka od \'$a\'';
$string['maketoplevelitem'] = 'Pomeri na najviši nivo';
$string['missingimportantcode'] = 'Ovom tipu pitanja nedostaje važan kod: $a.';
$string['missingoption'] = 'Pitanju tipa Umetnuti odgovori $a nedostaju opcije';
$string['modified'] = 'Poslednja izmena';
$string['move'] = 'Premesti iz $a i promeni linkove.';
$string['movecategory'] = 'Premesti kategoriju';
$string['movedquestionsandcategories'] = 'Premeštena su pitanja i kategorije pitanja sa $a->oldplace na $a->newplace.';
$string['movelinksonly'] = 'Samo promenite destinacije linkova, nemojte premeštati niti kopirati datoteke.';
$string['moveq'] = 'Premesti pitanje(a)';
$string['moveqtoanothercontext'] = 'Premesti pitanje u drugi kontekst.';
$string['movingcategory'] = 'Premeštanje kategorije';
$string['movingcategoryandfiles'] = 'Da li ste sigurni da želite da premestite kategoriju {$a->name} i sve njoj podređene kategorije u kontekst za \"{$a->contextto}\"?<br /> Postoji {$a->urlcount} datoteka u vezi sa pitanjima u {$a->fromareaname}. Da li želite da je(ih) kopirate ili premestite u {$a->toareaname}?';
$string['movingcategorynofiles'] = 'Da li ste sigurni da želite da premestite kategoriju \"{$a->name}\" i sve potkategorije u kontekst za \"{$a->contextto}\"?';
$string['movingquestions'] = 'Premeštanje pitanja i datoteka';
$string['movingquestionsandfiles'] = 'Da li ste sigurni da želite da premestite pitanje(a) {$a->questions} u kontekst za <strong>\"{$a->tocontext}\"</strong>?<br /> Postoji <strong>{$a->urlcount} datoteka</strong> do koje(kojih) vode linkovi iz ovog(ovih) pitanja u {$a->fromareaname}. Da li želite da je(ih) kopirate ili premestite u {$a->toareaname}?';
$string['movingquestionsnofiles'] = 'Da li ste sigurni da želite da premestite pitanje(a) {$a->questions} u kontekst za <strong>\"{$a->tocontext}\"</strong>?<br /> <strong>Nema datoteka</strong> povezanih sa njim(a) u {$a->fromareaname}.';
$string['needtochoosecat'] = 'Morate odabrati kategoriju u koju želite da premestite ovo pitanje ili pritisnuti \'otkaži\'.';
$string['nocate'] = 'Ne postoji kategorija $a!';
$string['nopermissionadd'] = 'Nemate odobrenje da dodate pitanje ovde.';
$string['nopermissionmove'] = 'Nemate dozvole da premeštate pitanja odavde. Morate sačuvati pitanje u ovoj kategoriji ili ga sačuvati kao novo pitanje.';
$string['noprobs'] = 'Nije nađen ni jedan problem u vašoj bazi podataka sa pitanjima.';
$string['notenoughdatatoeditaquestion'] = 'Nisu specificirani ni identifikator pitanja, ni identifikator kategorije sa tipom pitanja.';
$string['notenoughdatatomovequestions'] = 'Morate navecti identifikatore pitanja koja želite da premestite.';
$string['notflagged'] = 'Nije obeleženo';
$string['parenthesisinproperclose'] = 'zagrade pre ** nisu pravilno zatvorene u $a*';
$string['parenthesisinproperstart'] = 'zagrade pre ** nisu pravilno otvorene u $a*';
$string['permissionedit'] = 'Uredite ovo pitanje';
$string['permissionmove'] = 'Premestite ovo pitanje';
$string['permissionsaveasnew'] = 'Snimite ovo pitanje kao novo';
$string['permissionto'] = 'Imate dozvolu da:';
$string['published'] = 'objavljeno';
$string['qtypeveryshort'] = 'T';
$string['questionaffected'] = '<a href=\"$a->qurl\">Pitanje \"$a->name\" ($a->qtype)</a> je u ovoj kategoriji pitanja ali se koristi i u <a href=\"$a->qurl\">testu \"$a->quizname\"</a> koji pripada drugom kursu \"$a->coursename\".';
$string['questionbank'] = 'Banka pitanja';
$string['questioncategory'] = 'Kategorija pitanja';
$string['questioncatsfor'] = 'Kategorije pitanja za \'$a\'';
$string['questiondoesnotexist'] = 'Ovo pitanje ne postoji';
$string['questionname'] = 'Naziv pitanja';
$string['questionsaveerror'] = 'U toku pokušaja da se sačuva pitanje  ($a) pojavila se greška';
$string['questionsmovedto'] = 'Pitanje koje se još uvek koristi je premešteno u \"$a\" u okviru nadređene kategorije.';
$string['questionsrescuedfrom'] = 'Pitanje sačuvano iz konteksta $a.';
$string['questionsrescuedfrominfo'] = 'Ova pitanja (od kojih neka mogu biti skrivena) sačuvana su kada je kontekst $a bio obrisan, zato što se još uvek koriste u nekim testovima ili drugim aktivnostima.';
$string['questiontype'] = 'Tip pitanja';
$string['questionuse'] = 'Koristi pitanje u ovoj aktivnosti';
$string['saveflags'] = 'Sačuvaj stanje inditkatora (zastavica)';
$string['selectacategory'] = 'Izaberi kategoriju';
$string['selectaqtypefordescription'] = 'Izaberi tip pitanja da bi video njegov opis';
$string['shareincontext'] = 'Deli u kontekstu za $a';
$string['tofilecategory'] = 'Upiši kategoriju u datoteku';
$string['tofilecontext'] = 'Upiši kontekst u datoteku';
$string['unknown'] = 'Nepoznato';
$string['unknownquestiontype'] = 'Nepoznat tip pitanja: $a.';
$string['unpublished'] = 'neobjavljeno';
$string['upgradeproblemcategoryloop'] = 'Otkriven je problem pri pokušaju ažuriranja kategorija pitanja. Postoji petlja u stablu kategorija. Pogođene su time kategorije sa id vrednostima $a.';
$string['upgradeproblemcouldnotupdatecategory'] = 'Nije moguće ažurirati kategoriju pitanja $a->name ($a->id).';
$string['upgradeproblemunknowncategory'] = 'Otkriven je problem pri pokušaju ažuriranja kategorija pitanja. Kategorija $a->id ukazuje na nadređenu kategoriju $a->parent, koja ne postoji. Promenjena je nadređena kategorija da bi se rešio problem.';
$string['wrongprefix'] = 'Pogrešno formatiran nameprefix $a';
$string['yourfileshoulddownload'] = 'Vaša datoteka za izvoz - trebalo bi da uskoro započne preuzimanje. U suprotnom, molimo <a href=\"$a\">kliknite ovde</a>. Promenjena je nadređena kategorija da bi se rešio problem.';
$string['cannotinsertquestioncate'] = 'Nije moguće ubaciti novu kategoriju pitanja: $a'; // ORPHANED
$string['cannotmovecate'] = 'Nije moguće premestiti kategoriju $a. U ovom kontekstu to je posnjednja kategorija.'; // ORPHANED
$string['cannotmovefromto'] = 'Nije moguće premestiti kategoriju $a[0] u $a[1]'; // ORPHANED
$string['cannotsavequiz'] = 'Tekući pokušaj testa nije sačuvan!'; // ORPHANED
$string['cannotupdatecate'] = 'Nije moguće ažurirati kategoriju $a'; // ORPHANED
$string['cannotupdatequestion'] = 'Nije moguće ažurirati pitanje!'; // ORPHANED
$string['cannotupdatequestionver'] = 'Nije moguće ažurirati polje za verziju pitanja'; // ORPHANED
$string['cannotupdaterandomqname'] = 'Nije moguće ažurirati nasumični naziv pitanja'; // ORPHANED

?>
