<?PHP // $Id$ 
      // quiz.php - created with Moodle 1.9.9 (Build: 20100609) (2007101590)


$string['1day'] = '1 dan';
$string['1hour'] = '1 sat';
$string['2hours'] = '2 sata';
$string['30minutes'] = '30 minuta';
$string['6hours'] = '6 sati';
$string['acceptederror'] = 'Prihvaćena greška';
$string['action'] = 'Akcija';
$string['adaptive'] = 'Adaptivni režim';
$string['addcategory'] = 'Dodaj kategoriju';
$string['addingcalculated'] = 'Dodavanje izračunatih pitanja';
$string['addingdescription'] = 'Dodavanje opisa';
$string['addingessay'] = 'Dodavanje eseja';
$string['addingmatch'] = 'Dodavanje pitanja sa sparivanjem';
$string['addingmultianswer'] = 'Dodavanje umetnutih odgovora';
$string['addingmultichoice'] = 'Dodavanje pitanja sa višestrukim odabirima';
$string['addingnumerical'] = 'Dodavanje numeričkog pitanja';
$string['addingquestion'] = 'Dodavanje pitanja';
$string['addingquestions'] = 'Na ovom delu stranice uređujete svoju bazu pitanja. Pitanja su sačuvana po kategorijama kako bi se što lakše organizovala, i mogu biti upotrebljena u bilo kom testu unutar Vašeg kursa ili nekog drugog kursa ako odaberete opciju \'objavljivanja\' pitanja. <br /><br />
Nakon što odaberete određenu kategoriju pitanja, možete kreirati nova ili uređivati već postojeća pitanja. Možete označiti bilo koje od tih pitanja i dodati ga (ih) u Vaš test koji se nalazi s leve strane ekrana.';
$string['addingrandom'] = 'Dodavanje nasumičnog odabranog pitanja';
$string['addingrandomsamatch'] = 'Dodavanje nasumičnog odabranog pitanja tipa sparivanje kratkih odgovora';
$string['addingshortanswer'] = 'Dodavanje pitanja tipa Kratak odgovor';
$string['addingtruefalse'] = 'Dodavanje tačno/netačnih pitanja';
$string['addmoreoverallfeedbacks'] = 'Dodaj {no} još polja za povratne informacije';
$string['addquestions'] = 'Dodaj pitanja';
$string['addquestionstoquiz'] = 'Dodaj pitanja u tekući test';
$string['addrandom'] = 'Dodaj $a slučajnih pitanja';
$string['addrandom1'] = '<< Dodaj';
$string['addrandom2'] = 'slučajna pitanja';
$string['addselectedtoquiz'] = 'Dodaj odabrano u test';
$string['addtoquiz'] = 'Dodaj u test';
$string['affectedstudents'] = 'Uticalo je na $a';
$string['aiken'] = 'Aiken format';
$string['allattempts'] = 'Svi pokušaji';
$string['allinone'] = 'Neograničeno';
$string['allowreview'] = 'Dozvoli pregled';
$string['alreadysubmitted'] = 'Verovatno ste već predali test.';
$string['alternativeunits'] = 'Alternativne jedinice';
$string['alwaysavailable'] = 'Uvek dostupno';
$string['analysisoptions'] = 'Opcije analize';
$string['analysistitle'] = 'Tabela analize stavki';
$string['answer'] = 'Odgovor';
$string['answerhowmany'] = 'Jedan ili više tačnih odgovora?';
$string['answers'] = 'Odgovori';
$string['answersingleno'] = 'Dozvoljeno je više tačnih odgovora';
$string['answersingleyes'] = 'Samo jedan odgovor je tačan';
$string['answerswithacceptederrormarginmustbenumeric'] = 'Odgovori sa prihvaćenom greškom moraju biti numerički';
$string['answertoolong'] = 'Odgovor je predugačak nakon linije $a (maks. 255 znakova)';
$string['aon'] = 'AON format';
$string['attempt'] = 'Pokušaj broj $a';
$string['attemptduration'] = 'Utrošeno vreme';
$string['attemptedon'] = 'Datum predaje testa';
$string['attemptfirst'] = 'Prvi pokušaj';
$string['attemptincomplete'] = 'Ovaj pokušaj (korisnika: $a) još nije završen.';
$string['attemptlast'] = 'Poslednji pokušaj';
$string['attemptquiznow'] = 'Započni test';
$string['attempts'] = 'Pokušaji';
$string['attemptsallowed'] = 'Dozvoljen broj pokušaja';
$string['attemptsdeleted'] = 'Broj izbrisanih pokušaja';
$string['attemptselection'] = 'Izaberite koje pokušaje treba analizirati po korisniku:';
$string['attemptsexist'] = 'Test je već u upotrebi, ne možete više dodavati ili brisati pitanja.';
$string['attemptsnum'] = 'Poukašaji: $a';
$string['attemptsnumthisgroup'] = 'Pokušaji: $a->total ($a->group oz ove grupe)';
$string['attemptsnumyourgroups'] = 'Pokušaji: $a->total ($a->group iz vaše grupe)';
$string['attemptsonly'] = 'Prikaži samo studenata sa pokušajima';
$string['attemptsunlimited'] = 'Neograničen broj pokušaja';
$string['back'] = 'Nazad na pregled pitanja';
$string['backtoquestionlist'] = 'Nazad na listu pitanja';
$string['backtoquiz'] = 'Nazad na uređivanje testa';
$string['bestgrade'] = 'Najviša ocena';
$string['blackboard'] = 'Blackboard';
$string['blackboard_6'] = 'Blackboard V6+';
$string['bothattempts'] = 'Prikaži studente sa i bez pokušaja';
$string['braceerror'] = 'Nisu pronađene {...} oko odgovora';
$string['browsersecurity'] = 'Bezbednost Web čitača';
$string['calculated'] = 'Računsko';
$string['calculatedquestion'] = 'Računsko pitanje nije podržano na liniji $a. Ovo pitanje će biti ignorisano.';
$string['cannotcreatepath'] = 'Ne može se kreirati putanja ($a)';
$string['cannoteditafterattempts'] = 'Ne možete da dodate ili uklonite pitanja zbog toga što postoje pokušaji.';
$string['cannotinsert'] = 'Ne može se umetnuti pitanje';
$string['cannotopen'] = 'Ne može se otvoriti izvozna datoteka ($a)';
$string['cannotread'] = 'Ne može se čitati uvozna datoteka (ili je prazna)';
$string['cannotwrite'] = 'Ne može se upisivati u izvoznu datoteku ($a)';
$string['caseno'] = 'Ne treba voditi računa o malim i velikim slovima';
$string['casesensitive'] = 'Vođenje računa o malim i velikim slovima';
$string['caseyes'] = 'Da, moraju se poklapati čak i mala i velika slova';
$string['categories'] = 'Kategorije';
$string['category'] = 'Kategorija';
$string['categoryadded'] = 'Kategorija \'$a\' je dodata';
$string['categorydeleted'] = 'Kategorija \'$a\' je obrisana';
$string['categoryinfo'] = 'Informacije o kategoriji';
$string['categorymove'] = 'Kategorija \'$a->name\' sadrži $a->count pitanja.  (neka od njih mogu biti stara, skrivena ili pitanja koja se i dalje koriste u postojećim testovima).<br /> Odaberite drugu kategoriju u koju ćete ih premestiti.';
$string['categorymoveto'] = 'Premesti ih u ovu kategoriju';
$string['categorynamecantbeblank'] = 'Naziv kategorije ne može ostati nepopunjen.';
$string['categorynoedit'] = 'Nemate ovlašćenja za menjanje kategorije \'$a\'.';
$string['categoryupdated'] = 'Kategorija je uspešno izmenjena';
$string['changessaved'] = 'Promene u ocenjivanju su sačuvane';
$string['changessavedwitherrors'] = 'Došlo je do nekih grešaka pri čuvanju promena u ocenjivanju';
$string['checkanswer'] = 'Proveri';
$string['choice'] = 'Izbor';
$string['choices'] = 'Dostupni izbori';
$string['choosedatasetproperties'] = 'Izaberi osobine seta podataka';
$string['choosefile'] = 'Odaberite datoteku';
$string['close'] = 'Zatvori prozor';
$string['closebeforeopen'] = 'Nije moguće ažurirati test. Odredili ste datum zatvaranja pre datuma otvaranja.';
$string['closepreview'] = 'Zatvori pregled';
$string['closereview'] = 'Zatvori pregled';
$string['comment'] = 'Komentar';
$string['commentorgrade'] = 'Komentarišite ili promennite ocenu';
$string['comments'] = 'Komentari';
$string['completedon'] = 'Završeno dana';
$string['confirmclose'] = 'Spremni ste da završite ovaj test. Jednom kada završite test nećete više biti u mogućnosti da menjate svoje odgovore.';
$string['confirmserverdelete'] = 'Da li ste sigurni da želite da uklonite server <b>$a</b> sa spiska?';
$string['confirmstartattemptlimit'] = 'Ovaj test je ograničen na $a pokušaja. Pristup testu će se računati kao pokušaj. Da li želite da nastavite?';
$string['confirmstartattempttimelimit'] = 'Test ima vremensko ograničenje, a moguće ga je raditi $a put(a). Svaki pristup testu se računa kao pokušaj njegovog rešavanja. Da li želite da nastavite?';
$string['confirmstarttimelimit'] = 'Test je vremenski ograničen. Da li ste sigurni da želite da počnete?';
$string['containercategorycreated'] = 'Ova kategorija je kreirana sa ciljem da se u nju smeste sve originalne kategorije koje se pomere na nivo sajta iz dole navedenih razloga.';
$string['continueattemptquiz'] = 'Nastavite poslednji pokušaj';
$string['continuepreview'] = 'Nastavi poslednji pregled';
$string['copyingfrom'] = 'Kreiranje kopije pitanja \'$a\'';
$string['copyingquestion'] = 'Kopiranje pitanja';
$string['correct'] = 'Tačno';
$string['correctanswer'] = 'Tačan odgovor';
$string['correctanswerformula'] = 'Formula tačnih odgovora';
$string['correctansweris'] = 'Tačan odgovor: $a';
$string['correctanswerlength'] = 'Značajne cifre';
$string['correctanswers'] = 'Tačni odgovori';
$string['correctanswershows'] = 'Prikaz tačnih odgovora';
$string['corrresp'] = 'Tačan odziv sistema';
$string['countdown'] = 'Brojač';
$string['countdownfinished'] = 'Test se uskoro zatvara, vreme je da predate svoje odgovore.';
$string['countdowntenminutes'] = 'Test se zatvara za deset minuta.';
$string['coursetestmanager'] = 'Test Menadžer format';
$string['createfirst'] = 'Morate prvo kreirati neka pitanja sa kratkim odgovorima.';
$string['createmultiple'] = 'Dodajte testu nekoliko slučajnih pitanja';
$string['createnewquestion'] = 'Kreiraj novo pitanje';
$string['custom'] = 'Proizvoljan format';
$string['dataitemneed'] = 'Morate dodati bar jedan skup stavki podataka da biste dobili validno pitanje';
$string['datasetdefinitions'] = 'Ponovo upotrebljene definicije seta podataka za kategoriju $a';
$string['datasetnumber'] = 'Broj';
$string['daysavailable'] = 'Dostupni dani';
$string['decimaldigits'] = 'Broj decimala u ocenama';
$string['decimalformat'] = 'decimale';
$string['decimalpoints'] = 'Decimalna mesta';
$string['decimals'] = 'sa $a';
$string['default'] = 'Podrazumevano';
$string['defaultgrade'] = 'Podrazumevana ocena pitanja';
$string['defaultinfo'] = 'Podrazumevana kategorija za pitanja';
$string['delay1'] = 'Vremenski razmak između prvog i drugog pokušaja';
$string['delay2'] = 'Vremenski razmak između svih ostalih pokušaja';
$string['deleteattemptcheck'] = 'Da li ste apsolutno sigurni da želite da obrišete ove pokušaje?';
$string['deletequestioncheck'] = 'Jeste li u potpunosti sigurni da želite da obrišete \'$a\'?';
$string['deletequestionscheck'] = 'Jeste li u potpunosti sigurni da želite da obrišete sledeća pitanja? <div>$a</div>';
$string['deleteselected'] = 'Obriši označeno';
$string['deletingquestionattempts'] = 'Obriši pokušaje pitanja';
$string['description'] = 'Opis';
$string['discrimination'] = 'Indeks diskriminativnosti';
$string['displayoptions'] = 'Opcije za prikaz';
$string['download'] = 'Kliknite za preuzimanje izvezene datoteke sa kategorijama';
$string['downloadextra'] = '(datoteka se čuva i među datotekama kursa u /backupdata/quiz direktorijumu)';
$string['duplicateresponse'] = 'Ovo predato rešenje je ignorisano jer ste već ranije dali ekvivalentan odgovor.';
$string['eachattemptbuildsonthelast'] = 'Svaki pokušaj se nastavlja na prethodni';
$string['editcategories'] = 'Uređivanje kategorija';
$string['editcategory'] = 'Uređivanje kategorije';
$string['editcatquestions'] = 'Uređivanje pitanja u kategoriji';
$string['editdatasets'] = 'Uređivanje seta podataka';
$string['editingcalculated'] = 'Uređivanje računskog pitanja';
$string['editingdescription'] = 'Uređivanje opisa';
$string['editingessay'] = 'Uređivanje pitanja na koje se traži odgovor u vidu eseja';
$string['editingmatch'] = 'Uređivanje pitanja sa sparivanjem odgovora';
$string['editingmultianswer'] = 'Uređivanje umetnutih odgovora (zatvorenog pitanja)';
$string['editingmultichoice'] = 'Uređivanje pitanja višestrukog izbora';
$string['editingnumerical'] = 'Uređivanje numeričkog pitanja';
$string['editingquestion'] = 'Uređivanje pitanja';
$string['editingquiz'] = 'Uređivanje testa';
$string['editingrandom'] = 'Uređivanje nasumično odabranog pitanja';
$string['editingrandomsamatch'] = 'Uređivanje slučajnog pitanja sa sparivanjem kratkih odgovora';
$string['editingrqp'] = '$a: uređivanje pitanja';
$string['editingshortanswer'] = 'Uređivanje pitanja sa kratkim odgovorom';
$string['editingtruefalse'] = 'Uređivanje Tačno/Netačno pitanja';
$string['editqcats'] = 'Uređivanje kategorija pitanja';
$string['editquestions'] = 'Uređivanje pitanja';
$string['editquiz'] = 'Uređivanje testa';
$string['editquizquestions'] = 'Uređivanje pitanja testa';
$string['emailconfirmbody'] = 'Dragi $a->username,

Hvala za prosleđivanje Vaših odgovora na \'$a->quizname\'
u okviru kursa \'$a->coursename\'
u $a->submissiontime.

Ovaj email potvrđuje da smo bezbedno primili Vanje odgovore.

Možete oceniti ovaj test na $a->quizurl.';
$string['emailconfirmsubject'] = 'Potvrda predavanja testa: $a->quizname';
$string['emailnotifybody'] = 'Dragi $a->username,

$a->studentname je završio test \'$a->quizname\' ($a->quizurl)
u okviru kursa \'$a->coursename\'.

Možete pregledati ovaj pokušaj na  $a->quizreviewurl.';
$string['emailnotifysubject'] = '$a->studentname je završio test $a->quizname';
$string['errorinquestion'] = 'Greška u pitanju';
$string['errormissingquestion'] = 'Greška: Sistem ne može da pronađe pitanje čiji je identifikator $a';
$string['errornotnumbers'] = 'Greška - odgovori moraju biti numerički';
$string['errorsdetected'] = 'Broj nađenih grešaka: $a';
$string['essay'] = 'Esej';
$string['essayquestions'] = 'Pitanja';
$string['event1'] = 'Automatsko čuvanje';
$string['event2'] = 'Sačuvaj';
$string['event3'] = 'Ocena';
$string['event5'] = 'Proveri';
$string['event6'] = 'Zatvori';
$string['event7'] = 'Predaj';
$string['event8'] = 'Zatvori';
$string['event9'] = 'Oceni ručno';
$string['examview'] = 'Pregled testa';
$string['export'] = 'Izvoz';
$string['exportcategory'] = 'izvezi kategoriju';
$string['exporterror'] = 'Došlo je do greške prilikom procesiranja izvoza';
$string['exportfilename'] = 'test';
$string['exportingquestions'] = 'Pitanja se izvoze u datoteku';
$string['exportname'] = 'Naziv datoteke';
$string['exportnameformat'] = '%%d.%%m.%%Y.-%%H.%%M';
$string['exportquestions'] = 'Izvezi pitanja u datoteku';
$string['false'] = 'Pogrešno';
$string['feedback'] = 'Povratne informacije';
$string['feedbackerrorboundaryformat'] = 'Ograničenja ocenjivanja povratnih informacija moraju biti ili procentualne ili numeričke. Vrednost koju ste uneli ograničena sa $a nije podržana.';
$string['feedbackerrorboundaryoutofrange'] = 'Ograničenja ocenjivanja povratnih informacija moraju biti između 0%% i 100%%. Vrednost koju ste uneli ograničena sa $a je van dozvoljenog opsega.';
$string['feedbackerrorjunkinboundary'] = 'Morate popuniti polja sa ograničenjima ocenjivanja povratnih informacija, bez ostavljanja bilo kakvih praznina.';
$string['feedbackerrorjunkinfeedback'] = 'Morate popuniti polja povratnih informacija, bez ostavljanja bilo kakvih praznina.';
$string['feedbackerrororder'] = 'Granice ocenjivanja povratnih informacija moraju biti sortirane, počevši od najviše. Vrednost koju ste uneli ograničena sa $a nije u dobrom poretku.';
$string['file'] = 'Datoteka';
$string['fileformat'] = 'Format datoteke';
$string['fillcorrect'] = 'Unesite tačan odgovor';
$string['filloutnumericalanswer'] = 'Obezbedite bar jedan mogući odgovor i toleranciju. Prvi odgovarajući odgovor biće korišćen za utvrđivanje rezultata i povratnih informacija. Ako stavite na raspolaganje neke povratne informacije bez odgovora na kraju, one će biti prikazane studentima čiji se odgovori ne poklapaju ni sa jednim od ostalih odgovora.';
$string['filloutoneanswer'] = 'Morate ispuniti bar jedan od mogućih odgovora. Prazni odgovori se neće koristiti. \'*\' se može koristiti kao džoker znak koji odgovara svim znakovima. Prvi odgovor koji se uklopi se koristi za utvrđivanje razultata i povratnih informacija.';
$string['filloutthreequestions'] = 'Morate ispuniti bar tri pitanja sa odgovarajućim rešenjima. Možete dodati još netačnih odgovora davanjem rešenja uz prazna pitanja. Stavke u kojima su i pitanje i odgovor prazni neće se uzimati u obzir.';
$string['fillouttwochoices'] = 'Morate ispuniti bar dva odgovora. Prazni odgovori se neće koristiti.';
$string['finishattempt'] = 'Predaj sve odgovore i završi test';
$string['finishreview'] = 'Završi pregled';
$string['forceregeneration'] = 'Obavezno obnavljanje';
$string['formatnotfound'] = 'Nije pronađen format $a za uvoz/izvoz';
$string['formatnotimplemented'] = 'Ovaj format nije ispravno implementiran, molimo podnesite izveštaj o grešci';
$string['fractionsaddwrong'] = 'Pozitivne ocene koje ste odabrali u zbiru ne daju 100%%<br />Naime njihov zbir je $a%%<br />Da li želite da se vratite nazad i ispravite pitanje?';
$string['fractionsnomax'] = 'Jedan od odgovora bi trebao nositi 100%% ocene, tako da je <br />moguće dobiti maksimalnu ocenu za ovo pitanje.<br />Da li želite da se vratite nazad i ispravite pitanje?';
$string['fromfile'] = 'iz datoteke:';
$string['functiontakesatleasttwo'] = 'Funkcija $a mora imati najmanje dva argumenta';
$string['functiontakesnoargs'] = 'Funkcija $a ne upotrebljava nijedan argument';
$string['functiontakesonearg'] = 'Funkcija $a mora imati tačno jedan argument';
$string['functiontakesoneortwoargs'] = 'Funkcija $a mora imati ili jedan ili dva argumenta';
$string['functiontakestwoargs'] = 'Funkcija $a mora imati tačno dva argumenta';
$string['generalfeedback'] = 'Opšte povratne informacije';
$string['generatevalue'] = 'Generiši novu vrednost između';
$string['geometric'] = 'Geometrijski';
$string['gift'] = 'GIFT format';
$string['giftleftbraceerror'] = 'Nije pronađen znak {';
$string['giftmatchingformat'] = 'Odgovori u pitanju sa sparivanjem odgovora nisu pravilno formatirani';
$string['giftnonumericalanswers'] = 'Nije pronađen nijedan odgovor za numeričko pitanje';
$string['giftnovalidquestion'] = 'Nije pronađen nijedan ispravan odgovor';
$string['giftqtypenotset'] = 'Nije podešen tip pitanja';
$string['giftrightbraceerror'] = 'Nije pronađen znak }';
$string['grade'] = 'Ocena';
$string['gradeall'] = 'Oceni sve';
$string['gradeaverage'] = 'Prosečna ocena';
$string['gradeboundary'] = 'Ograničenje ocene';
$string['gradeessays'] = 'Oceni eseje';
$string['gradehighest'] = 'Najviša ocena';
$string['grademethod'] = 'Metod ocenjivanja';
$string['gradesdeleted'] = 'Izbrisano ocena testa:';
$string['gradesofar'] = '$a->method: $a->mygrade / $a->quizgrade.';
$string['gradingdetails'] = 'Ocena za ovaj odgovor je: $a->raw/$a->max.';
$string['gradingdetailsadjustment'] = 'Sa prethodnim kaznenim bodovima ocena je <strong>$a->cur/$a->max</strong>.';
$string['gradingdetailspenalty'] = 'Ovim odgovorom ste zaradili $a kaznenih bodova.';
$string['gradingdetailszeropenalty'] = 'Niste zaradili kaznene bodove za ovaj odgovor';
$string['guestsno'] = 'Nažalost, gosti ne mogu ni da vide ni da rešavaju testove';
$string['history'] = 'Istorijat odziva sistema';
$string['hotpot'] = 'Hot Potatoes format';
$string['illegalformulasyntax'] = 'Nepodržana sintaksa formule počevši od \'$a\'';
$string['imagedisplay'] = 'Slika za prikaz';
$string['imagemissing'] = 'Slika nije raspoloživa u liniji $a. Ime datoteke biće ignorisano';
$string['import'] = 'Uvoz';
$string['importcategory'] = 'kategorija uvoza';
$string['importerror'] = 'Došlo je do greške prilikom procesiranja uvoza';
$string['importerrorquestion'] = 'Greška pri uvozu pitanja';
$string['importfilearea'] = 'Uvoz iz datoteke koja je već među datotekama kursa';
$string['importfileupload'] = 'Uvoz iz novoučitane datoteke...';
$string['importfromthisfile'] = 'Uvoz iz ove datoteke';
$string['importingquestions'] = 'Uvoz $a pitanja iz datoteke';
$string['importmax10error'] = 'Postoji greška u pitanju. Ne može biti više od deset odgovora';
$string['importmaxerror'] = 'Postoji greška u pitanju. Ima previše odgovora.';
$string['importminerror'] = 'Postoji greška u pitanju. Nema dovoljno ponuđenih odgovora za ovaj tip pitanja';
$string['importparseerror'] = 'Pronađena je greška u toku parsiranja uvezene datoteke. Nijedno pitanje nije uvezeno. Da bi ste uvezli ona pitanja koja su dobra podesite opciju \'Stani pri pojavi greške\' na \'Ne\'';
$string['importquestions'] = 'Uvoz pitanja iz datoteke';
$string['incorrect'] = 'Netačno';
$string['indivresp'] = 'Odgovori pojedinaca na svaku stavku';
$string['info'] = 'Informacije';
$string['introduction'] = 'Uvod';
$string['invalidcategory'] = 'Identifikator kategorije nije valjan';
$string['invalidnumericanswer'] = 'Jedan od odgovora koji ste uneli nije ispravan broj.';
$string['invalidnumerictolerance'] = 'Jedna od tolerancija koji ste uneli nije ispravan broj.';
$string['invalidsource'] = 'Izvor nije prihvaćen kao validan.';
$string['invalidsourcetype'] = 'Nije validan tip izvora';
$string['itemanal'] = 'Analiza odziva sistema za stavke';
$string['itemdefinition'] = 'Definicija';
$string['itemsource'] = 'Izvor stavke';
$string['itemsourceformat'] = 'Format izvora stavke';
$string['itemtypes'] = 'Vrste udaljenih pitanja';
$string['lastanswer'] = 'Vaš odgovor je bio';
$string['learnwise'] = 'Learnwise format';
$string['link'] = 'Link';
$string['listitems'] = 'Lista stavki u testu';
$string['literal'] = 'Znak';
$string['loguniform'] = 'cifre, iz loguniform distribucije';
$string['makecopy'] = 'Sačuvaj kao novo pitanje';
$string['managetypes'] = 'Upravljanje tipovima pitanja i serverima';
$string['manualgrading'] = 'Ocenjivanje';
$string['mark'] = 'Predajte';
$string['markall'] = 'Predajte stranicu';
$string['marks'] = 'Ocene';
$string['match'] = 'Sparivanje';
$string['matchanswer'] = 'Sparivanje odgovora';
$string['matchanswerno'] = 'Sparivanje odgovora $a';
$string['matcherror'] = 'Ocene se ne slažu sa opcijama za ocenjivanje - pitanje je preskočeno';
$string['matchgrades'] = 'Sparivanje ocena';
$string['matchgradeserror'] = 'Greška ako ocena nije navedena';
$string['matchgradesnearest'] = 'Najbliža ocena ako nije navedena';
$string['max'] = 'Maksimalno';
$string['min'] = 'Minimalno';
$string['minutes'] = 'Minut(a)';
$string['missinganswer'] = 'Premalo :ODGOVOR, :Lx, :Rx stanja za liniju $a ovog pitanja. Morate definisati najmanje 2 moguća odgovora';
$string['missingcorrectanswer'] = 'Morate zadati tačan odgovor';
$string['missingformula'] = 'Nedostaje formula';
$string['missingitemtypename'] = 'Nedostaje naziv';
$string['missingname'] = 'Nedostaje naziv pitanja';
$string['missingquestion'] = 'Nedostaje naziv pitanja nakon linije $a';
$string['missingquestiontext'] = 'Nedostaje tekst pitanja';
$string['missingword'] = 'Nedostaje format reči';
$string['modulename'] = 'Test';
$string['modulenameplural'] = 'Testovi';
$string['moveto'] = 'Premesti u >>';
$string['multianswer'] = 'Umetnuti odgovori (Zatvoreno pitanje)';
$string['multichoice'] = 'Višestruki izbor';
$string['multipleanswers'] = 'Odaberite bar jedan odgovor.';
$string['multiplier'] = 'Množitelj';
$string['name'] = 'Naziv';
$string['newattemptfail'] = 'Greška: Nije bilo moguće započeti novi pokušaj rešavanja testa';
$string['noanswers'] = 'Nijedan odgovor nije odabran!';
$string['noattempts'] = 'Nije bilo pokušaja da se reši ovaj test';
$string['noattemptstoshow'] = 'Nema pokušaja za prikaz';
$string['nocategory'] = 'Pogrešna ili nespecificirana kategorija';
$string['nocommentsyet'] = 'Još nema komentara';
$string['noconnection'] = 'Trenutno nije uspostavljena veza sa Web servisom koji može da obradi ovo pitanje. Molimo kontaktirajte svog administratora';
$string['nodataset'] = 'ništa - nije džoker znak';
$string['noessayquestionsfound'] = 'Nisu pronađena pitanja koja se ručno ocenjuju';
$string['nogradewarning'] = 'Ovaj test se ne ocenjuje, tako da ne možete da podesite sveobuhvatnu povratnu informaciju.';
$string['nomatchinganswer'] = 'Morate navesti tačan odgovor za pitanje \'$a\'.';
$string['nominal'] = 'Nominalan';
$string['nomoreattempts'] = 'Nemate više pravo da pokušavate da rešite test';
$string['none'] = 'Nema';
$string['nopossibledatasets'] = 'Nema mogućih skupova podataka';
$string['noquestionintext'] = 'Tekst pitanja ne sadrži umetnuta pitanja';
$string['noquestions'] = 'Nijedno pitanje još nije dodato';
$string['noquestionsfound'] = 'Nema pitanja';
$string['noquestionsinfile'] = 'Nema pitanja u datoteci odabranoj za uvoz';
$string['noresponse'] = 'Bez odziva sistema';
$string['noreview'] = 'Nije Vam dozvoljen pregled ovog testa';
$string['noreviewuntil'] = 'Nije Vam dozvoljen pregled ovog testa do $a';
$string['noscript'] = 'JavaScript mora biti omogućen da biste nastavili dalje!';
$string['notavailable'] = 'Nažalost, ovaj test nije još raspoloživ';
$string['notavailabletostudents'] = 'Napomena: Ovaj test nije još dostupan Vašim studentima.';
$string['notenoughanswers'] = 'Ovaj tip pitanja zahteva bar $a odgovora';
$string['notenoughsubquestions'] = 'Nije definisano dovoljno potpitanja!<br />Da li želite da se vratite nazad i ispravite pitanje?';
$string['notimedependentitems'] = 'Modul za testove trenutno ne podržava vremenski ograničena pitanja. Podesite vremenko ograničenje za čitav test. Da li želite da izaberete drugo pitanje (ili da ipak upotrebite trenutno pitanje)?';
$string['numattempts'] = '$a->studentnum $a->studentstring su načinili $a->attemptnum pokušaja';
$string['numattemptsmade'] = '$a učinjenih pokušaja rešavanja ovog testa';
$string['numberabbr'] = '#';
$string['numerical'] = 'Numeričko';
$string['onlyteachersexport'] = 'Samo predavači mogu da izvoze pitanja';
$string['onlyteachersimport'] = 'Samo predavači sa pravima uređivanja mogu da uvoze pitanja';
$string['openclosedatesupdated'] = 'Ažurirani su datumi otvaranja i zatvaranja testa';
$string['optional'] = 'opciono';
$string['outof'] = '$a->grade od maksimalnih $a->maxgrade';
$string['outofpercent'] = '$a->grade od maksimuma $a->maxgrade ($a->percent%%)';
$string['outofshort'] = '$a->grade/$a->maxgrade';
$string['overallfeedback'] = 'Sveobuhvatne povratne informacije';
$string['overdue'] = 'Zakasneli';
$string['pagesize'] = 'Broj pokušaja prikazanih po stranici:';
$string['paragraphquestion'] = 'Paragraf pitanje nije podržano u liniji $a. Pitanje će biti ignorisano.';
$string['parent'] = 'Nadređeni';
$string['parsingquestions'] = 'Parsiranje pitanja iz uvozne datoteke.';
$string['partiallycorrect'] = 'Delimično tačno';
$string['passworderror'] = 'Uneta lozinka je pogrešna';
$string['penalty'] = 'Kazneni bodovi';
$string['penaltyfactor'] = 'Kazneni faktor';
$string['penaltyscheme'] = 'Primeni kaznene poene';
$string['percentcorrect'] = 'Procenat tačnosti';
$string['pleaseclose'] = 'Vaš zahtev je prosleđen. Možete da zatvorite prozor';
$string['popup'] = 'Prikaži test u \'sigurnom\' prozoru';
$string['popupblockerwarning'] = 'Ovaj deo testa se radi u bezbednom modu, što znači da morate rešavati test u bezbednom prozoru. Molimo isključite sve alate za sprečavanje pojave iskačućih prozora. Hvala.';
$string['popupnotice'] = 'Studenti će videti test u \'sigurnom\' prozoru';
$string['popupwithjavascriptsupport'] = 'Iskačući prozor na celom ekranu sa nešto bezbednosti JavaScript-a';
$string['preview'] = 'Pregled';
$string['previewquestion'] = 'Pregled pitanja';
$string['previewquiz'] = 'Pregledaj $a';
$string['previewquiznow'] = 'Pregledaj test sada';
$string['previous'] = 'Prethodno stanje';
$string['publish'] = 'Objavi';
$string['publishedit'] = 'Da bi ste dodali ili uredili pitanja u ovoj kategoriji morate imati odgovarajuće pravo pristupa';
$string['qti'] = 'IMS QTI format';
$string['qti2'] = 'IMS QTI 2.0 format';
$string['question'] = 'Pitanje';
$string['questioncats'] = 'Kategorije pitanja';
$string['questiondeleted'] = 'Ovo pitanje je obrisano. Molimo kontaktirajte svog predavača.';
$string['questioninuse'] = 'Pitanje \'$a->questionname\' se trenutno koristi u <br />$a->quiznames<br />Pitanje neće biti obrisano iz ovih testova, već samo sa spiska kategorije.';
$string['questionname'] = 'Naziv pitanja';
$string['questionnametoolong'] = 'Naziv pitanja je predugačak u liniji $a (maksimum je 255 karaktera). Naziv je zato skraćen.';
$string['questionno'] = 'Pitanje $a';
$string['questions'] = 'Pitanja';
$string['questionsinclhidden'] = 'Pitanja (uključujući i skrivena)';
$string['questionsinthisquiz'] = 'Pitanja u ovom testu';
$string['questionsinuse'] = '(* Pitanja označena zvezdicom se već koriste u nekim testovima. Ta pitanja neće biti obrisana iz tih testova već samo sa spiska kategorije.)';
$string['questionsperpage'] = 'Broj pitanja po stranici';
$string['questiontext'] = 'Tekst pitanja';
$string['questiontype'] = 'Tip pitanja $a';
$string['questiontypesetupoptions'] = 'Opcije podešavanja za tipove pitanja:';
$string['quiz:attempt'] = 'Pokušaj rešavanja testova';
$string['quiz:deleteattempts'] = 'Brisanje pokušaja rešavanja testova';
$string['quiz:emailconfirmsubmission'] = 'Pošalji potvrdu o predaji testa elektronskom poštom';
$string['quiz:emailnotifysubmission'] = 'Pošalji obaveštenje o predatim testovima elektronskom poštom';
$string['quiz:grade'] = 'Pregled testova';
$string['quiz:ignoretimelimits'] = 'Ignoriše vremenska ograničenja testova';
$string['quiz:manage'] = 'Upravljanje testovima';
$string['quiz:preview'] = 'Pregled testova';
$string['quiz:reviewmyattempts'] = 'Pregledaj sopstvene pokušaje';
$string['quiz:view'] = 'Pregled informacija o testu';
$string['quiz:viewreports'] = 'Pregled izveštaja o testu';
$string['quizavailable'] = 'Test je dostupan do: $a';
$string['quizclose'] = 'Zatvorite test';
$string['quizclosed'] = 'Test je zatvoren dana $a';
$string['quizcloses'] = 'Test se zatvara';
$string['quizcloseson'] = 'Ovaj test se zatvara $a';
$string['quiznotavailable'] = 'Test neće biti dostupan do: $a';
$string['quizopen'] = 'Otvorite test';
$string['quizopens'] = 'Test se otvara dana';
$string['quizsettings'] = 'Podešavanja testa';
$string['quiztimelimit'] = 'Vremensko ograničenje: $a';
$string['quiztimer'] = 'Štoperica';
$string['random'] = 'Slučajno pitanje';
$string['randomcreate'] = 'Kreiraj slučajna pitanja';
$string['randomsamatch'] = 'Slučajna pitanja sa sparivanjem kratkih odgovora';
$string['randomsamatchcreate'] = 'Napravite slučajna pitanja sa sparivanjem kratkih odgovora';
$string['randomsamatchintro'] = 'Za svako od navedenih pitanja, izaberite odgovarajući odgovor iz menija.';
$string['randomsamatchnumber'] = 'Broj pitanja za izbor';
$string['readytosend'] = 'Upravo ćete poslati svoje rešenje testa na ocenjivanje. Da li ste sigurni da želite da nastavite?';
$string['reattemptquiz'] = 'Ponovni pokušaj rešavanja testa';
$string['recentlyaddedquestion'] = 'Nedavno dodato pitanje!';
$string['recurse'] = 'Prikaži i pitanja iz podkategorija';
$string['regrade'] = 'Ponovo oceni sve pokušaje';
$string['regradecomplete'] = 'Svi pokušaji su ponovo ocenjeni';
$string['regradecount'] = '$a->changed od ukupno $a->attempt ocena je promenjeno';
$string['regradedisplayexplanation'] = 'Pokušaji koji se menjaju tokom ponovnog ocenjivanja se prikazuju kao linkovi na prozor za pregled pitanja';
$string['regradenotallowed'] = 'Nemate dozvolu za ponovno ocenjivanje ovog testa';
$string['regradingquestion'] = 'Ponovno ocenjivanje \"$a\".';
$string['regradingquiz'] = 'Ponovno ocenjivanje testa \"$a\"';
$string['relative'] = 'Relativno';
$string['remove'] = 'Ukloni';
$string['removeallquizattempts'] = 'Ukloni sve pokušaje testa';
$string['rename'] = 'Preimenuj';
$string['renderingserverconnectfailed'] = 'Server $a nije uspeo da obradi RQP zahtev. Proverite da li je URL adresa tačna.';
$string['reordertool'] = 'Prikaži alat za reorganizovanje';
$string['repaginate'] = 'Reorganizuj stranice sa $a pitanja po jednoj stranici';
$string['replace'] = 'Zameni';
$string['replacementoptions'] = 'Opcije za zamenjivanje';
$string['report'] = 'Izveštaji';
$string['reportanalysis'] = 'Analiza stavki';
$string['reportfullstat'] = 'Detaljna statistika';
$string['reportmulti_percent'] = 'Više-procentno';
$string['reportmulti_q_x_student'] = 'Više mogućnosti za studenta';
$string['reportmulti_resp'] = 'Individualni odzivi sistema';
$string['reportoverview'] = 'Pregled';
$string['reportregrade'] = 'Ponovna ocena pokušaja rešavanja testa';
$string['reportresponses'] = 'Detaljni odzivi sistema';
$string['reports'] = 'Izveštaji';
$string['reportsimplestat'] = 'Prosta statistika';
$string['requirepassword'] = 'Neophodna je lozinka';
$string['requirepasswordmessage'] = 'Da biste pristupili rešavanju ovog testa morate znati lozinku testa';
$string['requiresafeexambrowser'] = 'Zahteva korišćenje Sigurnog Web čitača za ispite';
$string['requiresubnet'] = 'Zahtevana mrežna adresa';
$string['response'] = 'Odziv sistema';
$string['responses'] = 'Odzivi sistema';
$string['results'] = 'Rezultati';
$string['reuseifpossible'] = 'ponovo iskoristi prethodno uklonjeno';
$string['review'] = 'Pregled';
$string['reviewafter'] = 'Dozvoliti pregled nakon što se test zatvori';
$string['reviewalways'] = 'Dozvoliti pregled u bilo koje vreme';
$string['reviewbefore'] = 'Dozvoliti pregled dok je test otvoren';
$string['reviewclosed'] = 'Nakon što se test zatvori';
$string['reviewimmediately'] = 'Odmah nakon pokušaja';
$string['reviewnever'] = 'Nikad nemoj dozvoliti pregled';
$string['reviewofattempt'] = 'Pregled pokušaja $a';
$string['reviewofpreview'] = 'Pregled prikaza';
$string['reviewopen'] = 'Kasnije, dok je test još uvek otvoren';
$string['reviewoptions'] = 'Studenti mogu da pregledaju';
$string['reviewoptionsheading'] = 'Opcije za pregled';
$string['reviewresponse'] = 'Pregled odziva sistema';
$string['reviewresponsetoq'] = 'Pregledaj odgovore (pitanje $a)';
$string['rqp'] = 'Udaljeno pitanje';
$string['rqps'] = 'Udaljena pitanja';
$string['safebrowsererror'] = 'Ovaj test je podešen tako da se njegovo rešavanje može pokušati samo korišćenjem Sigurnog Web čitača za ispite. Ne možete mu pristupiti iz ovog Web čitača.';
$string['safebrowsernotice'] = 'Ovaj test je tako podešen da mu studenti mogu pristupiti samo ako koriste Sigurni Web čitač za ispite.';
$string['save'] = 'Sačuvaj';
$string['saveandedit'] = 'Sačuvaj promene i uredi pitanja';
$string['savedfromdeletedcourse'] = 'Sačuvano sa kursa \"$a\" koji je obrisan';
$string['savegrades'] = 'Sačuvaj ocene';
$string['savemyanswers'] = 'Sačuvaj moje odgovore';
$string['savenosubmit'] = 'Sačuvaj bez predavanja';
$string['savequiz'] = 'Sačuvaj ceo test';
$string['score'] = 'Neobrađeni rezultat';
$string['scores'] = 'Rezultati';
$string['select'] = 'Selektuj';
$string['selectall'] = 'Selektuj sve';
$string['selectcategoryabove'] = 'Izaberite kategoriju od gore navedenih';
$string['selectedattempts'] = 'Izabrani pokušaji...';
$string['selectnone'] = 'Deselektuj sve';
$string['serveradded'] = 'Server je dodat';
$string['serveridentifier'] = 'Identifikator';
$string['serverinfo'] = 'Informacije o serveru';
$string['serverinuse'] = 'Server koji se spremate da obrišete je poslednji $a server i ukoliko ga obrišete ostaće pitanja koje neće moći više da se koriste';
$string['servers'] = 'Serveri';
$string['serverurl'] = 'URL servera';
$string['shortanswer'] = 'Pitanje sa kratkim odgovorom';
$string['show'] = 'Prikaži';
$string['showall'] = 'Prikaži sva pitanja na jednoj stranici';
$string['showbreaks'] = 'Prikaži prekide između stranica';
$string['showcorrectanswer'] = 'Da li da se uz povratne informacije prikažu i tačni odgovori?';
$string['showdetailedmarks'] = 'Prikaži detalje ocene';
$string['showfeedback'] = 'Da li da se prikažu i povratne informacije nakon davanja odgovora na pitanja?';
$string['showhidden'] = 'Prikaži i stara pitanja';
$string['shownoattempts'] = 'Prikaži studente bez pokušaja';
$string['shownoattemptsonly'] = 'Prikaži samo studente bez pokušaja';
$string['showquestiontext'] = 'Prikaži tekst pitanja u listi pitanja';
$string['showteacherattempts'] = 'Prikaži pokušaje predavača da reši test';
$string['shuffle'] = 'Izmešaj';
$string['shuffleanswers'] = 'Izmešaj odgovore';
$string['shufflequestions'] = 'Izmešaj pitanja';
$string['shufflewithin'] = 'Izmešaj u okviru pitanja';
$string['significantfigures'] = 'sa $a';
$string['significantfiguresformat'] = 'značajne cifre';
$string['singleanswer'] = 'Odaberite jedan odgovor';
$string['sortage'] = 'Sortiraj po vremenu kreiranja';
$string['sortalpha'] = 'Sortiraj po imenu';
$string['sortsubmit'] = 'Sortiraj pitanja';
$string['sorttypealpha'] = 'Sortiraj po tipu, imenu';
$string['startagain'] = 'Počni ponovo';
$string['startedon'] = 'Započeto';
$string['stoponerror'] = 'Stani pri pojavi greške';
$string['subneterror'] = 'Nažalost, ovaj test je zaključan, odnosno dostupan je samo sa pojedinih lokacija. Trenutno Vaš računar nije jedan od onih kojima je dozvoljeno da koriste ovaj test.';
$string['subnetnotice'] = 'Ovom testu se može pristupiti samo sa određenih mesta. Vaš računar se ne nalazi u mreži sa koje je pristup dozvoljen. Ipak, kao predavač svakako možete da pregledate test.';
$string['substitutedby'] = 'biće zamenjeno sa';
$string['summaryofattempts'] = 'Kratak pregled vaših prethodnih pokušaja';
$string['temporaryblocked'] = 'Privremeno Vam nije dozvoljeno da ponovo pokušate da rešite test.<br /> Moći ćete ponovo da mu pristupite dana:';
$string['time'] = 'Vreme';
$string['timecompleted'] = 'Završeno';
$string['timedelay'] = 'Nije Vam dozvoljeno da radite test jer još nije prošao zadati razmak od Vašeg poslednjeg do sledećeg mogućeg pokušaja rešavanja drugog testa.';
$string['timeleft'] = 'Preostalo vreme';
$string['timelimit'] = 'Vremensko ograničenje';
$string['timelimitexeeded'] = 'Nažalost, vreme za rešavanje testa je isteklo!';
$string['timelimitmin'] = 'Vremensko ograničenje (u minutima)';
$string['timestr'] = '%%H:%%M:%%S dana %%d.%%m.%%y.';
$string['timesup'] = 'Vreme je isteklo!';
$string['timetaken'] = 'Utrošeno vreme';
$string['tofile'] = 'u datoteku';
$string['tolerance'] = 'Tolerancija';
$string['tolerancetype'] = 'Vrsta tolerancije';
$string['toomanyrandom'] = 'Broj slučajnih pitanja potrebnih za test je veći od ukupnog broja pitanja raspoloživih u zadatoj kategoriji!';
$string['top'] = 'Najviši nivo';
$string['true'] = 'Tačno';
$string['truefalse'] = 'Tačno/Netačno';
$string['truefalseimporterror'] = '<b>Upozorenje</b>: Pitanje tipa Tačno/Netačno \'$a->questiontext\' nije moglo pravilno da se uveze. Nije bilo jasno da li je tačan odgovor Tačno ili Netačno. Pitanje je uvezeno uz pretpostavku da je odgovor \'$a->answer\'. Ukoliko uočite da to nije korektno, moraćete dodatno urediti pitanje.';
$string['type'] = 'Tip';
$string['unfinished'] = 'otvoreno';
$string['ungraded'] = 'Neocenjeno';
$string['uniform'] = 'decimale, iz uniformne distribucije';
$string['unit'] = 'Jedinica';
$string['unknowntype'] = 'Tip pitanja koji nije podržan u liniji $a. Ovo pitanje će biti ignorisano.';
$string['unsupportedformulafunction'] = 'Funkcija $a nije podržana';
$string['unusedcategorydeleted'] = 'Nakon brisanja kursa, ova kategorija je obrisana, zbog toga što se pitanja iz ove kategorija ne koriste u testovima drugih kurseva.';
$string['updatesettings'] = 'Ažuriraj podešavanja testa';
$string['upgradesure'] = '<div style=\"color: red;\">Test modul će izvesti krupne promene tabela sa testovima u bazi podataka. Ova nadogradnja još uvek nije dovoljno testirana. Pre nego što nastavite strogo Vam preporučujemo da napravite rezervnu kopiju.</div>';
$string['url'] = 'URL';
$string['usedcategorymoved'] = 'Nakon brisanja kursa, ova kategorija je sačuvana i premeštena na nivo sajta, zbog toga što se pitanja iz ove kategorije koriste u testovima drugih kurseva.';
$string['validate'] = 'Proveri';
$string['viewallanswers'] = 'Prikaz $a pokušaja rešavanja testa';
$string['viewallreports'] = 'Pogledaj izveštaje za $a pokušaja';
$string['warningmissingtype'] = '<p><b>Ovo pitanje spada u pitanja tipa koji još nije instaliran na Vašem Moodle sajtu.<br />Molimo upozorite svog adimistratora.</b></p>';
$string['warningsdetected'] = 'Detektovano je $a upozorenje(a)';
$string['webct'] = 'WebCT format';
$string['wheregrade'] = 'Gde je moja ocena?';
$string['wildcard'] = 'Džoker znak';
$string['withselected'] = 'Sa izabranim';
$string['withsummary'] = 'sa statističkim rezimeom';
$string['wronggrade'] = 'Pogrešna ocena (nakon linije $a):';
$string['wronguse'] = 'Ne možete tako da koristite ovu stranicu';
$string['xhtml'] = 'XHTML format';
$string['xml'] = 'Moodle XML format';
$string['xmlimportnoname'] = 'Nedostaje naziv pitanja u xml datoteci';
$string['xmlimportnoquestion'] = 'Nedostaje tekst pitanja u xml datoteci';
$string['xmltypeunsupported'] = 'Tip pitanja $a nije podržan XML uvozom';
$string['youneedtoenrol'] = 'Potrebno je da se upišete na ovaj kurs pre nego što pokušate rešavanje ovog testa';
$string['yourfinalgradeis'] = 'Vaša konačna ocena na ovom testu je $a';
$string['zerosignificantfiguresnotallowed'] = 'Tačan odgovor ne može imati nula značajnih cifara!';
$string['accessnoticesheader'] = 'Možete pregledati ovaj test, ali ako je ovo stvarni pokušaj rešavanja, bićete blokirani jer:'; // ORPHANED
$string['addaquestion'] = 'Dodaj pitanje...'; // ORPHANED
$string['addarandomquestion'] = 'Dodaj nasumično odabrano pitanje'; // ORPHANED
$string['adddescriptionlabel'] = 'Dodaj opis/natpis'; // ORPHANED
$string['addnewpagesafterselected'] = 'Dodaj nove stranice posle odabranih pitanja'; // ORPHANED
$string['addnewquestionsqbank'] = 'Dodaj pitanja u kategoriju $a->catname: $a->link'; // ORPHANED
$string['addpagehere'] = 'Dodaj stranicu ovde'; // ORPHANED
$string['addquestion'] = 'Dodaj pitanje'; // ORPHANED
$string['addrandomfromcategory'] = 'Dodaj nasumično odabrana pitanja iz kategorije'; // ORPHANED
$string['addrandomquestion'] = 'Dodaj nasumično odabrana pitanja'; // ORPHANED
$string['addrandomquestiontoquiz'] = 'Dodaj nasumično odabrana pitanja u test $a'; // ORPHANED
$string['aftereachquestion'] = 'Nakon dodavanja svakog pitanja'; // ORPHANED
$string['afternquestions'] = 'Nakon dodavanja $a pitanja'; // ORPHANED
$string['answered'] = 'Odgovoreno'; // ORPHANED
$string['areyousureremoveselected'] = 'Da li ste sigurni da želite da obrišete sva pitanja'; // ORPHANED
$string['asshownoneditscreen'] = 'Kao što je prikazano na stranici za uređivanje'; // ORPHANED
$string['attemptalreadyclosed'] = 'Ovaj pokušaj je već završen'; // ORPHANED
$string['attemptclosed'] = 'Pokušaj još uvek nije zatvoren'; // ORPHANED
$string['attempterror'] = 'Trenutno vam nije dozvoljeno da pokušate ovaj test zbog  $a'; // ORPHANED
$string['attemptsallowedn'] = 'Dozvoljen broj pokušaja: $a'; // ORPHANED
$string['basicideasofquiz'] = 'Osnovne ideje pravljenja testa'; // ORPHANED
$string['blackboard_six'] = 'Blackboard V6+'; // ORPHANED
$string['cannotfindprevattempt'] = 'Nije moguće pronaći prethodni pokušaj'; // ORPHANED
$string['cannotinsertrandomquestion'] = 'Nije bilo moguće ubaciti novo nasumično odabrano pitanje'; // ORPHANED
$string['cannotloadquestion'] = 'Nije bilo moguće učitati opcije pitanja'; // ORPHANED
$string['cannotloadtypeinfo'] = 'Nije moguće učitati informacije vezane za tip pitanja'; // ORPHANED
$string['cannotrestore'] = 'Nije bilo moguće vratiti podatke za sesije pitanja'; // ORPHANED
$string['cannotreviewopen'] = 'Ne možete da pregledate ovaj pokušaj, još uvek je otvoren'; // ORPHANED
$string['cannotsavelayout'] = 'Nije bilo moguće sačuvati'; // ORPHANED
$string['cannotsavenumberofquestion'] = 'Nije bilo moguće sačuvati broj pitanja po jedno stranici'; // ORPHANED
$string['cannotsavequestion'] = 'Ne može se sačuvati spisak pitanja'; // ORPHANED
$string['cannotsetgrade'] = 'Nije bilo moguće postaviti novu maksimalnu ocenu za test'; // ORPHANED
$string['cannotsetsumgrades'] = 'Pokušaj da se podesi suma ocena nije uspeo'; // ORPHANED
$string['configadaptive'] = 'Ukoliko izaberete Da ѕa ovu opciju onda će studentu biti dozvoljeno da više puta odgovori na pitanja čak u okviru istog pokušaja rešavanja testa.'; // ORPHANED
$string['configattemptsallowed'] = 'Ograničenje u broju pokušaja koji su studentima dozvoljeni na testu'; // ORPHANED
$string['configdecimaldigits'] = 'Broj cifara nakon decimalne tačke koje treba prikazati kada se pokazuju ocene.'; // ORPHANED
$string['configdecimalplaces'] = 'Broj cifara nakon decimalne tačke koje treba prikazati kada se pokazuju ocene za test.'; // ORPHANED
$string['configdecimalplacesquestion'] = 'Broj cifara nakon decimalne tačke koje treba prikazati kada se pokazuju ocene za pojedinačna potanja.'; // ORPHANED
$string['configdelay1'] = 'Ukoliko podesite vremenski razmak, onda će student nakon prvog pokušaja morati toliko vremena da sačeka pre nego što bude mogao ponovo da pokuša da uradi test.'; // ORPHANED
$string['configdelay1st2nd'] = 'Ukoliko ovde podesite vremenski razmak, studenti ne mogu da drugi put urade test pre nego što ne protekne toliko vremene od njihovog prvog pokušaja.'; // ORPHANED
$string['configdelay2'] = 'Ukoliko ovde podesite vremenski razmak, onda student mora da sačeka toliko vremene da prođe pre nego što započne svoj treći (i svaki naredni) pokušaj rešavanja testa.'; // ORPHANED
$string['configdelaylater'] = 'Ukoliko ovde podesite vremenski razmak, onda student ne može da započne treći, četvrti,... pokušaj pre nego toliko vremena ne prođe od kraja prethodnog pokušaja rešavanja testa.'; // ORPHANED
$string['configeachattemptbuildsonthelast'] = 'Ukoliko su dozvoljeni višestruki pokušaji onda svaki novi pokušaj sadrži rezultate prethodnog pokušaja.'; // ORPHANED
$string['configgrademethod'] = 'Kada su višestruki pokušaji dozvoljeni koji metod treba koristiti za izračunavanje studentove završne ocene za test.'; // ORPHANED
$string['configintro'] = 'Vrednosti koje ste ovde podesili definiše podrazumevane vrednosti koje se koriste u obrascu za podešavanje kada kreirate novi test. Možete, takođe, da konfigurišete koja podešavanja testa se smatraju naprednim.'; // ORPHANED
$string['confignewpageevery'] = 'Kod dodavanja pitanja u test, prekid stranice će automatski biti ubačen prema podešavanju koje odve odaberete,'; // ORPHANED
$string['configpenaltyscheme'] = 'Kazneni poeni koji se oduzimaju za svaki pogrešan odgovor u adaptivnom modu.'; // ORPHANED
$string['configrequirepassword'] = 'Studenti moraju da unese ovu lozinku pre nego što pokušaju da reši test.'; // ORPHANED
$string['configrequiresubnet'] = 'Studenti mogu da pokušaju da reše test samo sa ovih računara.'; // ORPHANED
$string['configreviewoptions'] = 'Ove opcije kontrolišu koje informacije će korisnici moći da vide kada budu pregledali pokušaj ili kada budu gledali izveštaje o testu.'; // ORPHANED
$string['configshowuserpicture'] = 'Prikaži sliku korisnika na ekranu tokom pokušaja rešavanja testa.'; // ORPHANED
$string['configshufflequestions'] = 'Ukoliko omogućite ovu opciju, onda će redosled pitanja u testu će nasumično izmešan svaki put kada student pokuša da reši test.'; // ORPHANED
$string['configshufflewithin'] = 'Ako omogućote ovu opciju, onda će delovi koji sačinjavaju pojedinačno pitanje biti nasumočno izmešani svaki put kada student započne da rešava ovaj test. Ponuđena opcija je takođe uključenlj u podešavaljima pitanja.'; // ORPHANED
$string['configtimelimit'] = 'Podraumevano vremensko ograničenje za testove u minutima. 0 znači da nema vremenskog ograničenja.'; // ORPHANED
$string['configtimelimitsec'] = 'Podraumevano vremensko ogrničenje za testove u sekundama. 0 znači da nema vremenskog ograničenja.'; // ORPHANED
$string['configurerandomquestion'] = 'Konfiguriši pitanje'; // ORPHANED
$string['createcategoryfornewrandomquestion'] = 'Kreiraj novu kategoriju pitanja za novo nasumično odabrano pitanje'; // ORPHANED
$string['createquestionandadd'] = 'Kreiraj novo pitanje i dodaj ga testu.'; // ORPHANED
$string['decimalplaces'] = 'Decimalna mesta u ocenama'; // ORPHANED
$string['decimalplacesquestion'] = 'Decimalna mesta u ocenama pitanja'; // ORPHANED
$string['delay1st2nd'] = 'Prinudni vremenski razmak između prvog i drugog pokušaja'; // ORPHANED
$string['delaylater'] = 'Prinudni vremenski razmak između naknadni pokušaja'; // ORPHANED
$string['empty'] = 'Prazno'; // ORPHANED
$string['endtest'] = 'Završi test...'; // ORPHANED
$string['erroraccessingreport'] = 'Ne možete da pristupite ovom izveštaju'; // ORPHANED
$string['errorunexpectedevent'] = 'Neočekivani kod događaja $a->event pronađen za šitanje $a->questionid u pokušaju $a->attemptid.'; // ORPHANED
$string['everynquestions'] = 'Svaka/ih $a pitanja'; // ORPHANED
$string['everyquestion'] = 'Svako pitanje'; // ORPHANED
$string['extraattemptrestrictions'] = 'Dodatna ograničenja prilikom pokušaja'; // ORPHANED
$string['formulaerror'] = 'Greška u formuli!'; // ORPHANED
$string['gradingmethod'] = 'Metod ocenjivanja: $a'; // ORPHANED
$string['hidebreaks'] = 'Sakrij prekide stranica'; // ORPHANED
$string['hidereordertool'] = 'Sakrij alatku za reorganizaciju'; // ORPHANED
$string['infoshort'] = 'i'; // ORPHANED
$string['invalidattemptid'] = 'Takav id pokušaja ne postoji'; // ORPHANED
$string['invalidquestionid'] = 'Neispravan id pitanja'; // ORPHANED
$string['invalidquizid'] = 'Neispravan id testa'; // ORPHANED
$string['invalidstateid'] = 'Neispravan id stanja'; // ORPHANED
$string['layout'] = 'Izgled (raspored pitanja)'; // ORPHANED
$string['layoutasshown'] = 'Izgled stranice kao što je prikazano.'; // ORPHANED
$string['layoutasshownwithpages'] = 'Izgled stranice kao što je prikazano. <small>(Nova stranica automatski na svakih  $a pitanja.)</small>'; // ORPHANED
$string['layoutshuffledandpaged'] = 'Pitanja su nasumično izmešana sa $a pitanja po stranici.'; // ORPHANED
$string['layoutshuffledsinglepage'] = 'Pitanja nasumično izmešana, sva prikazana na jednoj stranici.'; // ORPHANED
$string['loadingquestionsfailed'] = 'Broj neuspelih učitavanja pitanja: $a'; // ORPHANED
$string['moveselectedonpage'] = 'Premesti izabrana pitanja na stranicu: $a'; // ORPHANED
$string['neverallononepage'] = 'Nikad, sva pitanja na jednu stranicu'; // ORPHANED
$string['newpage'] = 'Nova stranica'; // ORPHANED
$string['newpageevery'] = 'Automatski staruj novu stranicu'; // ORPHANED
$string['nodatasubmitted'] = 'Nijedan podatak nije poslat.'; // ORPHANED
$string['noquestionsinquiz'] = 'Ne postoje pitanja u ovom testu'; // ORPHANED
$string['noquestionsnotinuse'] = 'Ovo nasumično odrabrano pitanje nije u upotrebi jer je njegova kategorija prazna'; // ORPHANED
$string['noquestionsonpage'] = 'Prazna stranica'; // ORPHANED
$string['noreviewshort'] = 'Nije dozvoljeno'; // ORPHANED
$string['noreviewuntilshort'] = 'Dostupno $a'; // ORPHANED
$string['notyourattempt'] = 'Ovo nije Vaš pokušaj!'; // ORPHANED
$string['noview'] = 'Prijavljenom korisniku nije dozvoljeno da pregleda ovaj test'; // ORPHANED
$string['numquestionsx'] = 'Pitanja: $a'; // ORPHANED
$string['open'] = 'Započet'; // ORPHANED
$string['orderandpaging'] = 'Redosled pitanja i organizacija stranica'; // ORPHANED
$string['orderingquiz'] = 'Redosled pitanja i organizacija stranica'; // ORPHANED
$string['parentcategory'] = 'Nadređena kategorija'; // ORPHANED
$string['preprocesserror'] = 'Došlo je do greške u toku preprocesiranja!'; // ORPHANED
$string['qname'] = 'ime'; // ORPHANED
$string['qti_two'] = 'MS QTI 2.0 format'; // ORPHANED
$string['qtypename'] = 'tip, ime'; // ORPHANED
$string['questionbankcontents'] = 'Sadržaj Banke pitanja'; // ORPHANED
$string['questionbankmanagement'] = 'Upravljanje bankom pitanja'; // ORPHANED
$string['questionbehaviour'] = 'Karakteristike pitanja'; // ORPHANED
$string['questionmissing'] = 'Nedostaje pitanje za ovu sesiju'; // ORPHANED
$string['questionnotloaded'] = 'Pitanje $a nije učitano iz baze podataka'; // ORPHANED
$string['questionorder'] = 'Redosled pitanja'; // ORPHANED
$string['questionsperpageselected'] = 'Broj pitanja po stranici je podešen, tako da je trenutno broj stranica fiksiran. Usled toga kontrole za reorganiѕaciju stranica su isključene. Ovo možete da promenite na $a.'; // ORPHANED
$string['questionsperpagex'] = 'Pitanja po jednoj stranici: $a'; // ORPHANED
$string['questiontextisempty'] = '[Nema teksta pitanja]'; // ORPHANED
$string['quiz:regrade'] = 'Ponovo oceni pokušaje'; // ORPHANED
$string['quizisclosed'] = 'Ovaj test je ѕatvoren'; // ORPHANED
$string['quizisopen'] = 'Ovaj test je otvoren'; // ORPHANED
$string['quizisopenwillclose'] = 'Test je otvoren (zatvara se $a)'; // ORPHANED
$string['quiznavigation'] = 'Navigacija testa'; // ORPHANED
$string['quizopened'] = 'Ovaj test je otvoren'; // ORPHANED
$string['quizopenedon'] = 'Ovaj test otvoren u $a'; // ORPHANED
$string['quizopenwillclose'] = 'Ovaj test je otvoren, biće zatovoren $a'; // ORPHANED
$string['quizordernotrandom'] = 'Redosled testa nije izmešan'; // ORPHANED
$string['quizorderrandom'] = '* Redosled testa je izmešan'; // ORPHANED
$string['quizwillopen'] = 'Ovaj test se otvara $a'; // ORPHANED
$string['randomfromcategory'] = 'Nasumično odabrano pitanje iz kategorije'; // ORPHANED
$string['randomnosubcat'] = 'Pitanja samo iѕ ove kategorije, ne i njenih podkategorija'; // ORPHANED
$string['randomwithsubcat'] = 'Pitanja iz ove kategorije i njenih podkategorija'; // ORPHANED
$string['removeemptypage'] = 'Ukloni praznu stranicu'; // ORPHANED
$string['removeselected'] = 'Ukloni izabrane'; // ORPHANED
$string['reorderquestions'] = 'Promeni redosled pitanja'; // ORPHANED
$string['repaginatecommand'] = 'Reorganizuj stranice'; // ORPHANED
$string['repaginatenow'] = 'Reorganizuj stranice sad'; // ORPHANED
$string['reportnotfound'] = 'Izveštaj nije poznat ($a)'; // ORPHANED
$string['reviewthisattempt'] = 'Pregledaj svoj odgovor na ovaj pokušaj'; // ORPHANED
$string['sameasoverall'] = 'Isto kao i za sveukupne ocene'; // ORPHANED
$string['saveattemptfailed'] = 'Neuspelo čuvanje aktuelnog pokušaja rešenja testa.'; // ORPHANED
$string['selectcategory'] = 'Izaberi kategoriju'; // ORPHANED
$string['selectquestiontype'] = '-- Izbaeri tip pitanja --'; // ORPHANED
$string['showcategorycontents'] = 'Prikaži sadržaj kategorija $a->arrow'; // ORPHANED
$string['showinsecurepopup'] = 'Upotrebiti \'bezbedni\' iskačući prozor za pokušaje'; // ORPHANED
$string['showuserpicture'] = 'Prikaži sliku korisnika'; // ORPHANED
$string['shuffledrandomly'] = 'Nasumično izmešano'; // ORPHANED
$string['shufflequestionsselected'] = 'S obzirom da je opcija za mešanje pitanja uključena, neke akcije koje se tiču stranica nisu dostupne. Za promenu opcije mešanja, $a.'; // ORPHANED
$string['sortquestionsbyx'] = 'Poređaj pitanja po $a'; // ORPHANED
$string['specificapathnotonquestion'] = 'Zadata putanja datoteke nije na datom pitanju'; // ORPHANED
$string['specificquestionnotonquiz'] = 'Zadato pitanje nije u datom testu'; // ORPHANED
$string['statenotloaded'] = 'Stanje za pitanje  $a nije učitano iz baze podataka'; // ORPHANED
$string['status'] = 'Status'; // ORPHANED
$string['subnetwrong'] = 'Ovom testu moguće je pristupiti samo sa određenih lokacija, a ovaj računar nije na spisku dozvoljenih lokacija.'; // ORPHANED
$string['summaryofattempt'] = 'Rezime pokušaja'; // ORPHANED
$string['timelimitsec'] = 'Vremensko ograničenje (sekunde)'; // ORPHANED
$string['totalpointsx'] = 'Ukupno ocena: $a'; // ORPHANED
$string['totalquestionsinrandomqcategory'] = 'Ukupno $a pitanja u kategoriji.'; // ORPHANED
$string['windowclosing'] = 'Ovaj prozor će se ubrzo zatvoriti.'; // ORPHANED
$string['youcannotwait'] = 'Ovaj test se zatvara pre nego što će Vam biti dozvoljeno da počnete novi pokušaj.'; // ORPHANED
$string['youmustwait'] = 'Morate sačekati pre nego što budete mogli da ponovo pokušate rešavanje testa. Biće Vam dozvoljeno da započnete novi pokušaj posle $a.'; // ORPHANED
$string['reviewnotallowed'] = 'Nije Vam dopuštenoi da pregledate pokušaje drugih korisnika na ovom testu.'; // ORPHANED
$string['existingcategory1'] = 'izraz iz već postojećeg skupa izraza koji se koristi i u drugim pitanjima u ovoj kategoriji'; // ORPHANED
$string['existingcategory2'] = 'datoteka iz već postojećeg skupa datoteka koja se koristi i u drugim pitanjima u ovoj kategoriji'; // ORPHANED
$string['existingcategory3'] = 'link iz već postojećeg skupa linkove koji se koristi i u drugim pitanjima u ovoj kategoriji'; // ORPHANED
$string['keptcategory1'] = 'izraz iz iste kategorije skupa izraza koji se mogu višestruko iskoristiti kao pre'; // ORPHANED
$string['keptcategory2'] = 'datoteka iz iste kategorije skupa datoteka koji se mogu višestruko iskoristiti kao pre'; // ORPHANED
$string['keptcategory3'] = 'link iz iste kategorije skupa linkova koji se mogu višestruko iskoristiti kao pre'; // ORPHANED
$string['keptlocal1'] = 'izraz iz istog privatnog skupa izraza za pitanje kao pre'; // ORPHANED
$string['keptlocal2'] = 'datoteka iz istog privatnog skupa datoteka za pitanje kao pre'; // ORPHANED
$string['keptlocal3'] = 'link iz istog privatnog skupa linkova za pitanje kao pre'; // ORPHANED
$string['newcategory1'] = 'izraz iz novog skupa izraza koji se može takođe koristiti u drugim pitanjima ove kategorije'; // ORPHANED
$string['newcategory2'] = 'datoteka iz novog skupa datoteka koja se može takođe koristiti u drugim pitanjima ove kategorije'; // ORPHANED
$string['newcategory3'] = 'link iz novog skupa linkova koji se može takođe koristiti u drugim pitanjima ove kategorije'; // ORPHANED
$string['newlocal1'] = 'izraz iz novog skupa izraza koji će se koristiti samo u ovom pitanju'; // ORPHANED
$string['newlocal2'] = 'datoteka iz novog skupa datoteka koja će se koristiti samo u ovom pitanju'; // ORPHANED
$string['newlocal3'] = 'link iz novog skupa linkova koji će se koristiti samo u ovom pitanju'; // ORPHANED

?>
