<?PHP // $Id$ 
      // role.php - created with Moodle 1.9.9 (Build: 20100609) (2007101590)


$string['addrole'] = 'Dodaj novu ulogu';
$string['allow'] = 'Dozvoli';
$string['allowassign'] = 'Dozvoli dodeljivanje uloga';
$string['allowoverride'] = 'Dozvoli menjanje uloga';
$string['allsiteusers'] = 'Svi korisnici na sajtu';
$string['assignglobalroles'] = 'Dodeli globalne uloge';
$string['assignroles'] = 'Dodeli uloge';
$string['assignrolesin'] = 'Dodeli uloge u $a';
$string['backup:userinfo'] = 'Napravi rezervnu kopiju podataka o korisnicima';
$string['block:view'] = 'Pregled bloka';
$string['blog:create'] = 'Kreiranje novih blog unosa';
$string['blog:manageentries'] = 'Uređivanje i upravljanje unosima';
$string['blog:manageofficialtags'] = 'Upravljanje zvaničnim oznakama';
$string['blog:managepersonaltags'] = 'Upravljanje ličnim oznakama';
$string['blog:view'] = 'Pogledaj unose bloga';
$string['calendar:manageentries'] = 'Upravljanje proizvoljnim unosima u kalendar';
$string['calendar:managegroupentries'] = 'Upravljanje stavkama vezanim za grupe';
$string['calendar:manageownentries'] = 'Upravljanje sopstvenim unosima u kalendar';
$string['capabilities'] = 'Sposobnosti';
$string['capability'] = 'Sposobnost';
$string['category:create'] = 'Kreiranje kategorija';
$string['category:delete'] = 'Obriši kategorije';
$string['category:manage'] = 'Upravljanje kategorijama';
$string['category:update'] = 'Ažuriraj kategorije';
$string['category:viewhiddencategories'] = 'Vidi skrivene kategorije';
$string['category:visibility'] = 'Bidi skrivene kategorije';
$string['course:activityvisibility'] = 'Sakrij/prikaži aktivnosti';
$string['course:bulkmessaging'] = 'Pošalji poruku većem broju ljudi';
$string['course:changecategory'] = 'Promeni kategoriju kursa';
$string['course:changefullname'] = 'Izmeni pun naziv kursa';
$string['course:changeidnumber'] = 'Izmeni ID broj kursa';
$string['course:changeshortname'] = 'Izmeni kraći naziv kursa';
$string['course:changesummary'] = 'Izmeni rezime kursa';
$string['course:create'] = 'Kreiraj kurseve';
$string['course:delete'] = 'Obriši kurseve';
$string['course:manageactivities'] = 'Upravljanje aktivnostima';
$string['course:managefiles'] = 'Upravljanje datotekama';
$string['course:managegrades'] = 'Upravljanje ocenama';
$string['course:managegroups'] = 'Upravljanje grupama';
$string['course:managemetacourse'] = 'Upravljanje metakursom';
$string['course:managescales'] = 'Upravljanje skalama za ocenjivanje';
$string['course:request'] = 'Zahtev za otvaranje novog kursa';
$string['course:reset'] = 'Ponovno postavljanje kursa';
$string['course:sectionvisibility'] = 'Kontrolisanje vidljivosti odeljaka';
$string['course:setcurrentsection'] = 'Postavljanje trenutnog odeljka';
$string['course:update'] = 'Ažuriranje podešavanja kursa';
$string['course:useremail'] = 'Može omogućiti/onemogućiti adresu e-pošte';
$string['course:view'] = 'Pregled kurseva';
$string['course:viewcoursegrades'] = 'Pregled ocena na kursevima';
$string['course:viewhiddenactivities'] = 'Pregled skrivenih aktivnosti';
$string['course:viewhiddencourses'] = 'Pregled skrivenih kurseva';
$string['course:viewhiddensections'] = 'Pregled skrivenih odeljaka';
$string['course:viewhiddenuserfields'] = 'Pregled skrivenih korisničkih polja';
$string['course:viewparticipants'] = 'Pregled učesnika';
$string['course:viewscales'] = 'Pregled skala za ocenjivanje';
$string['course:visibility'] = 'Skrivanje/prikazivanje kurseva';
$string['currentcontext'] = 'Trenutni kontekst';
$string['currentrole'] = 'Trenutna uloga';
$string['defaultrole'] = 'Podrazumevana uloga';
$string['defineroles'] = 'Definiši uloge';
$string['deletecourseoverrides'] = 'Obriši sve izmene uloga na kursu';
$string['deletelocalroles'] = 'Obriši sve lokalno dodeljene uloge';
$string['deleterolesure'] = '<p>Da li ste sigurni da želite da obrišete ulogu \"$a->name ($a->shortname)\"?</p><p>Broj korisnika kojima je ova uloga je trenutno dodeljena je: $a->count.</p>';
$string['duplicaterole'] = 'Kopiraj ulogu';
$string['duplicaterolesure'] = 'Da li ste sigurni da želite da kopirate ulogu \"$a->name ($a->shortname)\"?</p>';
$string['editrole'] = 'Uredi ulogu';
$string['errorbadrolename'] = 'Pogrešan naziv uloge';
$string['errorbadroleshortname'] = 'Pogrešan naziv uloge';
$string['errorexistsrolename'] = 'Naziv uloge već postoji';
$string['errorexistsroleshortname'] = 'Naziv uloge već postoji';
$string['existingusers'] = '$a postojećih korisnika';
$string['globalrole'] = 'Globalna uloga';
$string['globalroleswarning'] = 'UPOZORENJE! Svaka uloga koju dodelite na ovoj stranici primenjivaće se na korisnike kojima je dodeljena na čitavom sajtu, uključujući i početnu stranicu i sve kurseve.';
$string['grade:edit'] = 'Edituj ocene';
$string['grade:export'] = 'Izvoz ocena';
$string['grade:hide'] = 'Sakrij ocenu';
$string['grade:import'] = 'Uvoz ocena';
$string['grade:lock'] = 'Zaključi ocenu';
$string['grade:manage'] = 'Upravljanje stavkama za ocenjivanje';
$string['grade:manageletters'] = 'Upravljanje slovnim ocenama';
$string['grade:manageoutcomes'] = 'Upravljanje ishodima ocena';
$string['grade:override'] = 'Izmeni ocene';
$string['grade:unlock'] = 'Otključavanje ocena ili stavki';
$string['grade:view'] = 'Pregled sopstvenih ocena';
$string['grade:viewall'] = 'Pregled ocena drugih korisnika';
$string['grade:viewhidden'] = 'Vidi skrivenu ocenu';
$string['inactiveformorethan'] = 'neaktivan više od $a->timeperiod';
$string['ingroup'] = 'u grupi \"$a->group\"';
$string['inherit'] = 'Nasleđivanje';
$string['legacy:admin'] = 'NASLEĐENA ULOGA: Administrator';
$string['legacy:coursecreator'] = 'NASLEĐENA ULOGA: Kreator kursa';
$string['legacy:editingteacher'] = 'NASLEĐENA ULOGA: Predavač (sa uređivačkim pravima)';
$string['legacy:guest'] = 'NASLEĐENA ULOGA: Gost';
$string['legacy:student'] = 'NASLEĐENA ULOGA: Student';
$string['legacy:teacher'] = 'NASLEĐENA ULOGA: Predavač (bez uređivačkih prava)';
$string['legacy:user'] = 'NASLEĐENA ULOGA: Identifikovan korisnik';
$string['legacytype'] = 'Tip nasleđene uloge';
$string['listallroles'] = 'Spisak svih uloga';
$string['localroles'] = 'Lokalno dodeljene uloge';
$string['manageroles'] = 'Upravljanje ulogama';
$string['metaassignerror'] = 'Nije moguće dodeliti ovu ulogu korisniku \"$a\" jer je neophodna sposobnost upravljanja metakursevima.';
$string['metaunassignerror'] = 'Uloga korisnika \"$a\" je automatski ponovo dodeljena. Molimo uklonite ulogu u podređenim kursevima umesto toga.';
$string['morethan'] = 'Više od $a';
$string['multipleroles'] = 'Višestruke uloge';
$string['my:manageblocks'] = 'Uređivanje blokove na mojMoodle strani';
$string['nocapabilitiesincontext'] = 'Nema sposobnosti raspoloživih u ovom kontekstu';
$string['notes:manage'] = 'Uređivanje beleški';
$string['notes:view'] = 'Vidi beleške';
$string['notset'] = 'Nije postavljeno';
$string['overridepermissions'] = 'Izmeni ovlašćenja';
$string['overridepermissionsin'] = 'Izmeni ovlašćenja u $a';
$string['overrideroles'] = 'Izmeni uloge';
$string['overriderolesin'] = 'Izmeni uloge u $a';
$string['overrides'] = 'Izmene';
$string['permissions'] = 'Ovlašćenja';
$string['potentialusers'] = '$a potencijalnih korisnika';
$string['prevent'] = 'Spreči';
$string['prohibit'] = 'Zabrani';
$string['question:add'] = 'Dodavanje novih pitanja';
$string['question:config'] = 'Kofigurisanje tipova pitanja';
$string['question:editall'] = 'Uredi sva pitanja';
$string['question:editmine'] = 'Uredi svoja pitanja';
$string['question:managecategory'] = 'Uredi kategorije pitanja';
$string['question:moveall'] = 'Premesti sva pitanja';
$string['question:movemine'] = 'Premesti svoja pitanja';
$string['question:useall'] = 'Koristi sva pitanja';
$string['question:usemine'] = 'Koristi svoja pitanja';
$string['question:viewall'] = 'Pogledaj sva pitanja';
$string['question:viewmine'] = 'Pogledaj svpja pitanja';
$string['resetrole'] = 'Vrati na podrazumevane vrednosti';
$string['resetrolenolegacy'] = 'Obriši ovlašćenja';
$string['resetrolesure'] = 'Da li ste sigurni da želite da vratite ulogu \"$a->name ($a->shortname)\" na podrazumevane vrednosti?<p></p>Podrazumevane vrednosti se preuzimaju iz odabranih nasleđenih sposobnosti ($a->legacytype).';
$string['resetrolesurenolegacy'] = 'Da li ste sigurni da želite da obrišete sve ovlašćenja koja su definisane za ovu ulogu \"$a->name ($a->shortname)\"?';
$string['restore:createuser'] = 'Kreiraj korisnike pri rekonstrukciji rezervnih kopija';
$string['restore:rolldates'] = 'Dozvoljeno nizanje datuma za podešavanje aktivnosti pri obnavljanju iz rezervne kopije';
$string['restore:userinfo'] = 'Rekonstruiši podatke o korisnicima';
$string['risks'] = 'Rizici';
$string['role:assign'] = 'Dodeljivanje uloga korisnicima';
$string['role:manage'] = 'Kreiranje i upravljanje ulogama';
$string['role:override'] = 'Izmeni ovlašćenja za druge';
$string['role:safeoverride'] = 'Prepravi bezbedne dozvole za ostale';
$string['role:switchroles'] = 'Prebacivanje na druge uloge';
$string['role:unassignself'] = 'Poništi sopstvenih uloga';
$string['role:viewhiddenassigns'] = 'Pregled dodeljenih uloge koje su skrivene';
$string['roleassignments'] = 'Dodeljivanje uloga';
$string['roles'] = 'Uloge';
$string['roletoassign'] = 'Uloga koja se dodeljuje';
$string['roletooverride'] = 'Uloga koja se menja';
$string['safeoverridenotice'] = 'Napomena: Mogućnosti sa više rizika su zaključane jer Vam je dopušteno da prepravljate jedino bezbedne mogućnosti ovlašćenja.';
$string['selectrole'] = 'Izaberite ulogu';
$string['showallroles'] = 'Prikaz svih uloga';
$string['site:accessallgroups'] = 'Pristup svim grupama';
$string['site:approvecourse'] = 'Odobravanje kreiranja kursa';
$string['site:backup'] = 'Kreiranje rezervnih kopija kurseva';
$string['site:config'] = 'Promena konfiguracije sajta';
$string['site:doanything'] = 'Dozvoljeno da radi bilo šta';
$string['site:doclinks'] = 'Prikaz linkova ka dokumentima van sajta';
$string['site:import'] = 'Uvoz drugih kurseva u tekući kurs';
$string['site:langeditlocal'] = 'Izmene lokalnog prevoda';
$string['site:langeditmaster'] = 'Uredi glavne jezičke pakete';
$string['site:manageblocks'] = 'Upravljanje blokovima na nivou sajta';
$string['site:mnetloginfromremote'] = 'Pristup sa udaljene Moodle lokacije';
$string['site:mnetlogintoremote'] = 'Prelaz na udaljenu Moodle lokaciju';
$string['site:readallmessages'] = 'Pročitaj sve poruke na sajtu';
$string['site:restore'] = 'Restauriranje kurseva';
$string['site:sendmessage'] = 'Pošalji poruku bilo kom korisniku';
$string['site:trustcontent'] = 'Poverenje u bezbednost sadržaja';
$string['site:uploadusers'] = 'Postavi nove korisnike iz datoteke';
$string['site:viewfullnames'] = 'Uvek videti puna imena korisnika';
$string['site:viewparticipants'] = 'Pregled učesnika';
$string['site:viewreports'] = 'Pregled izveštaja';
$string['tag:create'] = 'Kreiranje novih oznaka';
$string['tag:edit'] = 'Uređivanje postojećih oznaka';
$string['tag:editblocks'] = 'Uređivanje blokova na stranicama oznaka';
$string['tag:manage'] = 'Upravljanje svim oznakama';
$string['user:changeownpassword'] = 'Izmeni sopstvenu lozinke';
$string['user:create'] = 'Kreiraj korisnike';
$string['user:delete'] = 'Obriši korisnike';
$string['user:editownprofile'] = 'Uredi svoj korisnički profil';
$string['user:editprofile'] = 'Uređivanje korisničkog profila';
$string['user:loginas'] = 'Prijavite se kao drugi korisnik';
$string['user:readuserblogs'] = 'Vidi sve korisničke blogove';
$string['user:readuserposts'] = 'Vidi sve korisničke poruke';
$string['user:update'] = 'Ažuriranje korisničkih profila';
$string['user:viewdetails'] = 'Pregled korisničkih profila';
$string['user:viewhiddendetails'] = 'Pregled skrivenih detalja o korisnicima';
$string['user:viewuseractivitiesreport'] = 'Videti izveštaje o aktivnostima korisnika';
$string['user:viewusergrades'] = 'Pregled korisničkih ocena';
$string['userhashiddenassignments'] = 'Ovaj korisnik ima jednu ili više skrivenih uloga dodeljenih za ovaj kurs';
$string['userswithrole'] = 'Svi korisnici sa ulogom';
$string['viewrole'] = 'Pregled detalja o ulogama';
$string['xuserswiththerole'] = 'Broj korisnika sa ulogom \"$a->role\" je: $a->number';
$string['addinganewrole'] = 'Dodavanje nove uloge'; // ORPHANED
$string['addingrolebycopying'] = 'Dodavanje nove uloge zasnovane na $a'; // ORPHANED
$string['allowed'] = 'Doѕvoljeno'; // ORPHANED
$string['allowroletoassign'] = 'Dozvoli korisniku sa ulogom $a->fromrole da dodeli ulogu $a->targetrole'; // ORPHANED
$string['allowroletooverride'] = 'Dozvoli korisniku sa ulogom $a->fromrole da izmeni ulogu $a->targetrole'; // ORPHANED
$string['allowroletoswitch'] = 'Dozvoli korisniku sa ulogom $a->fromrole da menja uloge u ulogu $a->targetrole'; // ORPHANED
$string['allowswitch'] = 'Doѕvoli menjanje uloga'; // ORPHANED
$string['assignanotherrole'] = 'Dodeli još jednu ulogu'; // ORPHANED
$string['assignerror'] = 'Greška prilikom dodeljivanja uloge $a->role korisniku $a->user.'; // ORPHANED
$string['assignmentcontext'] = 'Kontekst dodeljivanja uloga'; // ORPHANED
$string['assignmentoptions'] = 'Opcije dodeljivanja uloga'; // ORPHANED
$string['assignrolenameincontext'] = 'Dodeli ulogu \'$a->role\' u $a->context'; // ORPHANED
$string['assignrolesrelativetothisuser'] = 'Dodeli uloge u odnosu na ovog korisnika'; // ORPHANED
$string['backtoallroles'] = 'Povratak na listu svih uloga'; // ORPHANED
$string['checkglobalpermissions'] = 'Proveri globalna ovlašćenja'; // ORPHANED
$string['checkpermissions'] = 'Proveri ovlašćenja'; // ORPHANED
$string['checkpermissionsin'] = 'Proveri ovlašćenja u $a'; // ORPHANED
$string['checksystempermissionsfor'] = 'Proveri globalna ovlašćenja za $a->fullname'; // ORPHANED
$string['checkuserspermissionshere'] = 'Proveri globalna ovlašćenja za $a->fullname koje ima u ovom $a->contextleve'; // ORPHANED
$string['chooseroletoassign'] = 'Molimo da izaberete ulogu za dodeljivanje'; // ORPHANED
$string['context'] = 'Kontekst'; // ORPHANED
$string['createhiddenassign'] = 'Kreiranje dodeljivljnje sakrivenih uloga'; // ORPHANED
$string['createrolebycopying'] = 'Kreiranje novih uloga preuzimanje od  $a'; // ORPHANED
$string['createthisrole'] = 'Kreiranje ovih uloga'; // ORPHANED
$string['defaultx'] = 'Podrazumevano $a'; // ORPHANED
$string['deletexrole'] = 'Obriši $a ulogu'; // ORPHANED
$string['editingrolex'] = 'Uređivanje uloge \'$a\''; // ORPHANED
$string['editxrole'] = 'Uredi $a ulogu'; // ORPHANED
$string['enrolmentoptions'] = 'Opcije za upisicanje'; // ORPHANED
$string['explainpermission'] = 'Objasni ovlašćenja'; // ORPHANED
$string['explainpermissionsdoanything'] = 'Vodite računa da ovaj korisnik ima mogućnost da uradi bilo šta na noivou sajta (the moodle/site:doanything), tako da iako donja tabela pokazuje  drugačije ovaj korisnik će ustvari imati mogućnost $a u majvećem broju slučajeva.'; // ORPHANED
$string['explainpermissionsinfo'] = '<p>Uputsvo za korišćenje ove tabele:</p><ol><li>Prvo pogledajte da li postoji bilo koja Zabrana. Ukoliko postoji, funkcija has_capability će imati vrednost false.</li><li>U suprotnom, pregledajte sve redove, sa leva na desno, od gore na dole i pronađite prvu ćeliju gde je broj Prevencija i Dozvola različit. Ukoliko je više Dozvola nego Prevencija u toj ćeliji, onda će fumkcija has_capability imati vrednost true, u suprotnom njena vrednost će biti.</li><li>Ukoliko ni jedna ćelija nema različit broj Prevencija i Dozvola, onda će has_capability imati vrednost false.</li></ol>'; // ORPHANED
$string['explanation'] = 'Objašnjenje'; // ORPHANED
$string['extusers'] = 'Postojeći korisnici'; // ORPHANED
$string['extusersmatching'] = 'Postojeći korisnici koji odgovaraju \'$a\''; // ORPHANED
$string['filter:manage'] = 'Upravljanje podešavanjima lokalnih filtera'; // ORPHANED
$string['gotoassignroles'] = 'Idi na Dodeli uloge za ovaj kontekst $a->contextlevel'; // ORPHANED
$string['gotoassignsystemroles'] = 'Idi na Dodeli globalne uloge'; // ORPHANED
$string['hidden'] = 'Sakriveno'; // ORPHANED
$string['highlightedcellsshowdefault'] = 'Zasenčene ćelije u tabeli ispod pokazuju podrazumevano ovlašćenje za ovaj tip uloge, zasnovane na \'Nasleđeno od gornjeg tipa uloge\'.'; // ORPHANED
$string['highlightedcellsshowinherit'] = 'Zasenčene ćelije u tabeli ispod pokazuju dozvole koje će biti nasleđene. Nezavisno od mogućnosti čija ovlašćenja ustvari želite da promenite, trebalo bi sve ostaviti podešena na Nasleđeno'; // ORPHANED
$string['maybeassignedin'] = 'Vrsta konteksta u kojem ova uloga može biti dodeljena'; // ORPHANED
$string['noneinthisx'] = 'Ništa u ovoj $a'; // ORPHANED
$string['noneinthisxmatching'] = 'Nijedan korisnik ne odgovara \'$a->search\' u ovom $a->contexttype'; // ORPHANED
$string['noroleassignments'] = 'Ovaj korisnik nema dodeljenu nijednu ulogu bilo gde na ovom sajtu'; // ORPHANED
$string['notabletoassignroleshere'] = 'Niste u mogućnosti da ovde dodelite bilo koju ulogu'; // ORPHANED
$string['notabletooverrideroleshere'] = 'Niste u mogućnosti da ovde menjate ovlašćenja bilo koje uloge'; // ORPHANED
$string['overrideanotherrole'] = 'Izmeni drugu ulogu'; // ORPHANED
$string['overridecontext'] = 'Izmeni kontekst'; // ORPHANED
$string['overridepermissionsforrole'] = 'Izmeni ovlašćenja uloge \'$a->role\' u $a->context'; // ORPHANED
$string['overridesbycontext'] = 'Izmene (prema kontekstu)'; // ORPHANED
$string['permission'] = 'Ovlašćenje'; // ORPHANED
$string['permissionsforuser'] = 'Ovlašćenja za korisnika $a'; // ORPHANED
$string['portfolio:export'] = 'Izvezi u portfolio'; // ORPHANED
$string['potusers'] = 'Potencijalni korisnici'; // ORPHANED
$string['potusersmatching'] = 'Potencijalni korisncici koji odgovaraju \'$a\''; // ORPHANED
$string['question:flag'] = 'Obeleži (zastavicom)pitanja u toku davanja odgovora na njih'; // ORPHANED
$string['roledefinitions'] = 'Definicija uloga'; // ORPHANED
$string['selectanotheruser'] = 'Izaberi drugog korisnika'; // ORPHANED
$string['selectauser'] = 'Izaberi korisnika'; // ORPHANED
$string['showthisuserspermissions'] = 'Prikaži ovlašćenja ovog korisnika'; // ORPHANED
$string['thisusersroles'] = 'Uloge dodeljene ovom korisniku'; // ORPHANED
$string['unassignerror'] = 'Greška prilikom odzimanja uloge $a->role korisniku $a->user.'; // ORPHANED
$string['usersfrom'] = 'Korisnik iz $a'; // ORPHANED
$string['usersfrommatching'] = 'Korisnici iz $a->contextname koji odgovaraju \'$a->search\''; // ORPHANED
$string['usersinthisx'] = 'Korisnici u ovom $a'; // ORPHANED
$string['usersinthisxmatching'] = 'Korisnici u ovom $a->contexttype koji odgovaraju \'$a->search\''; // ORPHANED
$string['userswiththisrole'] = 'Korisnici sa ulogom'; // ORPHANED
$string['useshowadvancedtochange'] = 'Upotrebi \'Prikaži napredno\' za promenu'; // ORPHANED
$string['viewingdefinitionofrolex'] = 'Pregled definicije uloge \'$a\''; // ORPHANED
$string['whydoesuserhavecap'] = 'Zašto $a->fullname ima mogućnost $a->capability u kontekstu $a->context?'; // ORPHANED
$string['whydoesusernothavecap'] = 'Zašto $a->fullname nema mogućnost $a->capability u kontekstu $a->context?'; // ORPHANED
$string['question:export'] = 'Izvoz pitanja'; // ORPHANED
$string['question:import'] = 'Uvoz pitanja'; // ORPHANED
$string['question:manage'] = 'Upravljanje pitanjima'; // ORPHANED
$string['course:downloadallgrades'] = 'Preuzmi sve ocene'; // ORPHANED
$string['course:viewallgrades'] = 'Vidi sve ocene'; // ORPHANED
$string['course:viewowngrades'] = 'Vidi svoje ocene'; // ORPHANED
$string['grade:editlocked'] = 'Izmeni zaključene ocene'; // ORPHANED

?>
