<?PHP // $Id$ 
      // scorm.php - created with Moodle 1.9.9 (Build: 20100609) (2007101590)


$string['activation'] = 'Aktivacija';
$string['activityloading'] = 'Bićete automatski preusmereni na ovu aktivnost za';
$string['activitypleasewait'] = 'Aktivnost se učitava, molimo sačekajte';
$string['advanced'] = 'Parametri';
$string['asset'] = 'Element';
$string['assetlaunched'] = 'Element - Pregledano';
$string['attempt'] = 'pokušaj';
$string['attempt1'] = '1 pokušaj';
$string['attempts'] = 'pokušaji';
$string['attemptsx'] = '$a pokušaj(a)';
$string['attr_error'] = 'Neadekvatne vrednosti za atribut ($a->attr) u oznaci $a->tag.';
$string['autocontinue'] = 'Automatski nastavak';
$string['autocontinuedesc'] = 'Ovo podešavanje postavlja podrazumevano automatski nastavak za aktivnost';
$string['averageattempt'] = 'Prosečni broj pokušaja';
$string['badmanifest'] = 'Ima grešaka u manifestu: pogledajte izveštaj o greškama';
$string['badpackage'] = 'Ima nekih problema sa datim paketom. Proverite ga i pokušajte ponovo.';
$string['browse'] = 'Pregled';
$string['browsed'] = 'Pretraženo';
$string['browsemode'] = 'Način pregledanja podataka';
$string['browserepository'] = 'Pretraga repozitorijuma';
$string['chooseapacket'] = 'Izaberi ili ažuriraj SCORM paket';
$string['completed'] = 'Završeno';
$string['confirmloosetracks'] = 'UPOZORENJE: Čini se da je došlo do promene paketa. Ako je promenjena struktura paketa, podaci o aktivnostima nekih korisnika se mogu izgubiti tokom procesa ažuriranja.';
$string['contents'] = 'Sadržaj';
$string['coursepacket'] = 'Paket kursa';
$string['coursestruct'] = 'Struktura kursa';
$string['datadir'] = 'Greška datotečnog sistema: Nije moguće kreirati direktorijum za podatke kursa';
$string['deleteallattempts'] = 'Obriši sve pokušaje pregleda SCORM  paketa';
$string['details'] = 'Prati detalje';
$string['directories'] = 'Prikaz linkova direktorijuma';
$string['display'] = 'Prikaži paket';
$string['displaydesc'] = 'Ovo podešavanje postavlja podrazumevanu vrednost da li prikazati paket ili ne za aktivnost';
$string['domxml'] = 'DOMXML eksterna biblioteka';
$string['element'] = 'Element';
$string['enter'] = 'Uđi';
$string['entercourse'] = 'Uđi u SCORM kurs';
$string['errorlogs'] = 'Izveštaj o greškama';
$string['everyday'] = 'Svakodnevno';
$string['everytime'] = 'Pri svakom korišćenju';
$string['exit'] = 'Izađi iz SCORM kursa';
$string['exitactivity'] = 'Izađi iz aktivnosti';
$string['expcoll'] = 'Proširi/Skupi';
$string['external'] = 'Ažuriraj vremensko usklađivanje eksternih paketa';
$string['failed'] = 'Nije uspelo';
$string['finishscorm'] = 'Ukoliko ste završili sa pregledanjem ovog resursa,';
$string['finishscormlinkname'] = 'kliknite ovde da biste se vratili na stranicu kursa.';
$string['firstaccess'] = 'Prvi pristup';
$string['firstattempt'] = 'Prvi pokušaj';
$string['found'] = 'Manifest je nađen';
$string['frameheight'] = 'Ovo svojstvo određuje podrazumevanu visinu okvira ili prozora nivoa';
$string['framewidth'] = 'Ovo svojstvo određuje podrazumevanu širinu okvira ili prozora nivoa';
$string['fullscreen'] = 'Popuni ceo ekran';
$string['general'] = 'Opšti podaci';
$string['gradeaverage'] = 'Prosečna ocena';
$string['gradehighest'] = 'Najviša ocena';
$string['grademethod'] = 'Način ocenjivanja';
$string['grademethoddesc'] = 'Ovo podešavanje postavlja podrazumevani metod ocenjivanja za aktivnost';
$string['gradescoes'] = 'Objekti za učenje';
$string['gradesum'] = 'Konačna ocena';
$string['height'] = 'Visina';
$string['hidden'] = 'Sakriveno';
$string['hidebrowse'] = 'Onemogući mod prikaza';
$string['hidebrowsedesc'] = 'Ovo podešavanje postavlja podrazumevano da li onemogućiti ili omogućiti režim pregleda';
$string['hideexit'] = 'Sakrij link za izlaz';
$string['hidenav'] = 'Sakrij navigacionu dugmad';
$string['hidenavdesc'] = 'Ovo podešavanje postavlja podrazumevano da li prikazati ili sakriti navigacionu dugmad';
$string['hidereview'] = 'Sakrij dugme za pregled';
$string['hidetoc'] = 'Prikaz strukture kursa (sadržaja)';
$string['hidetocdesc'] = 'Ovo podešavanje postavlja podrazumevano da li prikazati ili sakriti prikaz strukture kursa (stablo sadržaja - TOC)';
$string['highestattempt'] = 'Najbolji pokušaj';
$string['identifier'] = 'Identifikator pitanja';
$string['iframe'] = 'Tekući prozor';
$string['iframedisplay'] = 'Otvaranje paketa u tekućem prozoru';
$string['incomplete'] = 'Nepotpuno';
$string['interactions'] = 'Interakcije';
$string['last'] = 'Poslednji put pristupljeno dana';
$string['lastaccess'] = 'Poslednji pristup';
$string['lastattempt'] = 'Poslednji pokušaj';
$string['location'] = 'Prikaži lokacionu liniju';
$string['max'] = 'Najbolji rezultat';
$string['maximumattempts'] = 'Broj pokušaja';
$string['maximumattemptsdesc'] = 'Ovo podešavanje postavlja podrazumevani maksimalni broj pokušaja za aktivnost';
$string['maximumgradedesc'] = 'Ovo podešavanje postavlja podrazumevanu maksimalnu ocenu za aktivnost';
$string['menubar'] = 'Prikaži liniju menija';
$string['min'] = 'Najgori rezultat';
$string['missing_attribute'] = 'Nedostaje atribut $a->attr u oznaci $a->tag';
$string['missing_tag'] = 'Nedostaje oznaka $a->tag';
$string['missingparam'] = 'Obavezna informacija nedostaje ili je nekorektna';
$string['mode'] = 'Način rada';
$string['modulename'] = 'SCORM/AICC';
$string['modulenameplural'] = 'SCORM/AICC paketi';
$string['newattempt'] = 'Počni novi pokušaj';
$string['next'] = 'Nastavak';
$string['no_attributes'] = 'Oznaka $a->tag mora imati atribute';
$string['no_children'] = 'Oznaka $a->tag mora imati potomke';
$string['noactivity'] = 'Nema podataka za izveštaj';
$string['nolimit'] = 'Neograničeni broj pokušaja';
$string['nomanifest'] = 'Manifest nije pronađen';
$string['noprerequisites'] = 'Nažalost, ne ispunjavate dovoljno preduslova za pristup ovom objektu za učenje';
$string['noreports'] = 'Nema izveštaja za prikaz';
$string['normal'] = 'Normalno';
$string['noscriptnoscorm'] = 'Vaš Web čitač ne podržava Javascript ili je u njegovim podešavanjima isključena podrška za Javascript. Nije moguće zabeležiti nikakve podatke o praćenju.';
$string['not_corr_type'] = 'Neslaganje tipova za oznaku $a->tag';
$string['notattempted'] = 'Nije pokušavano';
$string['objectives'] = 'Ciljevi';
$string['onchanges'] = 'Kad god se promeni';
$string['options'] = 'Opcije';
$string['organization'] = 'Organizacija';
$string['organizations'] = 'Organizacije';
$string['othersettings'] = 'Dodatna podešavanja';
$string['othertracks'] = 'Drugi zapisi';
$string['package'] = 'Paket';
$string['packagedir'] = 'Greška datotečnog sistema: Nije moguće kreirati direktorijum paketa';
$string['packagefile'] = 'Nije navedena datoteka s paketom';
$string['passed'] = 'Položeno';
$string['php5'] = 'PHP 5 (DOMXML izvorna biblioteka)';
$string['popup'] = 'Novi prozor';
$string['popupblocked'] = 'ukoliko se novi prozor ne pojavi';
$string['popupblockedlinkname'] = 'klikni ovde kako bi pokrenuli aktivnost';
$string['popupmenu'] = 'U padajućem meniju';
$string['popupopen'] = 'Otvori paket u novom prozoru';
$string['position_error'] = 'Oznaka $a->tag ne može biti podređena oznaci $a->parent';
$string['prev'] = 'Prethodni';
$string['raw'] = 'Osnovni rezultat';
$string['regular'] = 'Regularni manifest';
$string['report'] = 'Izveštaj';
$string['resizable'] = 'Dozvoli promenu veličine prozora';
$string['result'] = 'Rezultat';
$string['review'] = 'Pregled';
$string['reviewmode'] = 'Mod za pregledanje';
$string['scoes'] = 'Objekti za učenje';
$string['score'] = 'Rezultat';
$string['scorm:deleteresponses'] = 'Obriši SCORM pokušaje';
$string['scorm:savetrack'] = 'Čuvanje rezultata praćenja';
$string['scorm:skipview'] = 'Preskakanje pregleda';
$string['scorm:viewreport'] = 'Pregled izveštaja';
$string['scorm:viewscores'] = 'Pregled rezultata';
$string['scormcourse'] = 'SCORM kurs';
$string['scormloggingoff'] = 'API izveštavanje je isključeno';
$string['scormloggingon'] = 'API izveštavanje je uključeno';
$string['scormresponsedeleted'] = 'Obrisani pokušaji korisnika';
$string['scrollbars'] = 'Dozvoli izlistavanje prozora';
$string['sided'] = 'Sa leve strane';
$string['skipview'] = 'Student preskače stranicu sa strukturom sadržaja';
$string['skipviewdesc'] = 'Ovo podešavanje postavlja podrazumevano kada ne prikazati strukturu sadržaja za stranicu';
$string['slashargs'] = 'UPOZORENJE: sleš argumenti nisu dozvoljeni na ovom sajtu i objekti možda neće funkcionisati kako se očekuje!';
$string['stagesize'] = 'Veličina nivoa';
$string['started'] = 'Započeto dana';
$string['status'] = 'Status';
$string['statusbar'] = 'Prikaži statusnu liniju';
$string['student_response'] = 'Odgovor';
$string['suspended'] = 'Suspendovano';
$string['syntax'] = 'Sintaksna greška';
$string['tag_error'] = 'Nepoznata oznaka ($a->tag) sa ovim sadržajem: $a->value';
$string['time'] = 'Vreme';
$string['title'] = 'Naslov';
$string['too_many_attributes'] = 'Oznaka $a->tag ima jako puno karakteristika';
$string['too_many_children'] = 'Oznaka $a->tag ima jako puno potomaka';
$string['toolbar'] = 'Prikaži liniju sa alatkama';
$string['totaltime'] = 'Vreme';
$string['trackingloose'] = 'UPOZORENJE: Podaci o praćenju ovog SCORM paketa biće izgubljeni!';
$string['type'] = 'Tip';
$string['unziperror'] = 'Došlo je do greške prilikom raspakivanja paketa';
$string['updatefreq'] = 'Učestalost automatskog ažuriranja';
$string['updatefreqdesc'] = 'Ovo podešavanje postavlja podrazumevanu frekvenciju automatskog ažuriranja aktivnosti';
$string['validateascorm'] = 'Proveri ispravnost SCORM paketa';
$string['validation'] = 'Rezultat provere ispravnosti';
$string['validationtype'] = 'Ovo svojstvo određuje DOMXML biblioteku koja se koristi za validaciju SCORM manifesta. Ako niste sigurni koju vrednost treba da postavite, ostavite trenutno aktivni izbor.';
$string['value'] = 'Vrednost';
$string['versionwarning'] = 'Verzija manifesta je starija od 1.3, upozorenje na oznaci $a->tag';
$string['viewallreports'] = 'Prikaži izveštaj za $a pokušaja';
$string['viewalluserreports'] = 'Prikaži izveštaj za $a korisnika';
$string['whatgrade'] = 'Ocenjivanje pokušaja';
$string['whatgradedesc'] = 'Ovo podešavanje postavlja podrazumevano ocenjivanje pokušaja';
$string['width'] = 'Širina';
$string['window'] = 'Prozor';
$string['allowtypeexternal'] = 'Omogući spoljašnji tip paketa'; // ORPHANED
$string['allowtypeimsrepository'] = 'Omogući IMS tip paketa'; // ORPHANED
$string['allowtypelocalsync'] = 'Omogući preuzeti tip paketa'; // ORPHANED
$string['areacontent'] = 'Datoteke sadržaja'; // ORPHANED
$string['areapackage'] = 'Datoteka paketa'; // ORPHANED
$string['cannotfindsco'] = 'Nije bilo moguće naći SCO'; // ORPHANED
$string['displayattemptstatus'] = 'Prikaži status pokušaja'; // ORPHANED
$string['displaycoursestructure'] = 'Prikaži strukturu kursa'; // ORPHANED
$string['exceededmaxattempts'] = 'Dostigli ste maksimalan broj pokušaja'; // ORPHANED
$string['expired'] = 'Oprostite, ova aktivnost je zatovrena $a i nije više dostupna'; // ORPHANED
$string['gradeforattempt'] = 'Ocena za pokušaj'; // ORPHANED
$string['invalidactivity'] = 'Scorm aktivnost je neispravna'; // ORPHANED
$string['lastattemptlock'] = 'Zaključaj nakon završnog pokušaja'; // ORPHANED
$string['noattemptsallowed'] = 'Broj dozvoljenih pokušaja'; // ORPHANED
$string['noattemptsmade'] = 'Broj pokušaja koji ste imali'; // ORPHANED
$string['notopenyet'] = 'Oprostite, ali ova aktivnost nije dostupna do $a'; // ORPHANED
$string['scormclose'] = 'Do'; // ORPHANED
$string['scormopen'] = 'Od'; // ORPHANED
$string['scormtype'] = 'Tip'; // ORPHANED
$string['timerestrict'] = 'Ograniči davanje odgovora na ovaj vremenski period'; // ORPHANED
$string['typeexternal'] = 'Eksterni SCORM manifest'; // ORPHANED
$string['typeimsrepository'] = 'Lokalni repozitorijum IMS sadržaja'; // ORPHANED
$string['typelocal'] = 'Postavnjeni paket'; // ORPHANED
$string['typelocalsync'] = 'Preuteti paket'; // ORPHANED
$string['updatetime'] = 'Vreme sinhronizacije'; // ORPHANED
$string['url'] = 'URL'; // ORPHANED
$string['zlibwarning'] = 'Upozorenje: PHP Zlib kompresija je omogućena na ovom sajtu, neki korisnici mogu mogu imati problema sa učitavanjem SCORM objekata u određenim Web čitačima.'; // ORPHANED

?>
