<?PHP // $Id$ 
      // grades.php - created with Moodle 1.9.5+ (Build: 20091007) (2007101553)


$string['activities'] = 'Actividaes';
$string['addcategory'] = 'Amestar categoría';
$string['addcategoryerror'] = 'Nun se pudo amestar categoría.';
$string['addexceptionerror'] = 'Ocurrió un erru de la que s\'amestaba una esceición a userid:gradeitem';
$string['addfeedback'] = 'Amestar Retroallimentación';
$string['addgradeletter'] = 'Amestar lletra de calificación';
$string['addidnumbers'] = 'Amestarr númberos id';
$string['additem'] = 'Amestar ítem de calificación';
$string['addoutcome'] = 'Amestar un resultáu';
$string['addoutcomeitem'] = 'Amestar ítem de resultáu';
$string['addscale'] = 'Amestar una escala';
$string['aggregateextracreditmean'] = 'Media de notes (con créditos estra)';
$string['aggregatemax'] = 'Nota más alta';
$string['aggregatemean'] = 'Media de notes';
$string['aggregatemedian'] = 'Mediana de notes.';
$string['aggregatemin'] = 'Nota más baxa';
$string['aggregatemode'] = 'Moda de notes.';
$string['aggregateonlygraded'] = 'Amestar namás notes non vacíes';
$string['aggregateonlygradedhelp'] = 'Les notes non esistentes van tratase como notes mínimes o nun se van incluyir na agregación.';
$string['aggregateoutcomes'] = 'Incluyir resultaos en cálculu total';
$string['aggregateoutcomeshelp'] = 'L\'incluyir resultaos nel cálculu total pue dar una nota global indeseyada, poro, pue incluyilos o descartalos.';
$string['aggregatesonly'] = 'Namás cálculos totales';
$string['aggregatesubcats'] = 'Amestar socategoríes incluyentes';
$string['aggregatesubcatshelp'] = 'El cálculu total faise normalmente namás colos fíos inmediatos, pero tamién se puen incluyir notes en toles socategoríes escluyendo otres notes sumaes.';
$string['aggregatesum'] = 'Suma de notes.';
$string['aggregateweightedmean'] = 'Media ponderada de les notes.';
$string['aggregateweightedmean2'] = 'Media ponderada simple de notes.';
$string['aggregation'] = 'Cálculu total';
$string['aggregationcoef'] = 'Coeficiente';
$string['aggregationcoefextra'] = 'Puntos estra';
$string['aggregationcoefextrahelp'] = 'Puntos estra d\'esti ítem de nota na agregación';
$string['aggregationcoefextrasum'] = 'Actuar como puntos estra.';
$string['aggregationcoefextrasumhelp'] = 'Puntos estra d\'esti ítem de calificación nel cálculu total.';
$string['aggregationcoefweight'] = 'Pesu del ítem';
$string['aggregationcoefweighthelp'] = 'Peso aplicáu a toles notes nesti ítem de calificación nel cálculu colos demás ítems de calificación.';
$string['aggregationhelp'] = 'Estratexa usada pa calcular les notes de tolos alumnos d\'un cursu.';
$string['aggregationposition'] = 'Posición del resultáu del cálculu.';
$string['aggregationsvisible'] = 'Tipos d\'estratexes de cálculu.';
$string['aggregationsvisiblehelp'] = 'Escueya tolos tipos de cálculu que tendríen de tar disponibles. Caltenga calcada la tecla Control pa escoyer ítems múltiples.';
$string['aggregationview'] = 'Vista de categoríes y cálculos';
$string['allgrades'] = 'Toles notes per categoría';
$string['allstudents'] = 'Tolos estudiantes';
$string['allusers'] = 'Tolos usuarios';
$string['autosort'] = 'Orde automáticu';
$string['availableidnumbers'] = 'Cantidá d\'id disponibles';
$string['average'] = 'Promediu';
$string['averagesdecimalpoints'] = 'Cantidá de decimales nel promediu de les columnes';
$string['averagesdisplaytype'] = 'Mou de visualización nel promediu de les columnes.';
$string['backupwithoutgradebook'] = 'La copia de seguridá nun tien la configuración del Llibru de Notes.';
$string['badgrade'] = 'La nota puesta nun ye válida.';
$string['badlyformattedscale'] = 'Por favor, escriba un llistáu de valores separtaos por comes (necesítense, a lo menos, dos valores).';
$string['baduser'] = 'L\'usuariu solicitáu nun ye válidu.';
$string['bonuspoints'] = 'Puntos de bonificación';
$string['bulkcheckboxes'] = 'Caxellos de verificación masivos';
$string['calculatedgrade'] = 'Nota calculada';
$string['calculation'] = 'Cálculu';
$string['calculationadd'] = 'Amestar cálculu.';
$string['calculationedit'] = 'Editar cálculu.';
$string['calculationsaved'] = 'Cálculu guardáu.';
$string['calculationview'] = 'Ver cálculu';
$string['cannotaccessgroup'] = 'Nun se pue acceder a les notes del grupu escoyíu.';
$string['categories'] = 'Categoríe';
$string['categoriesanditems'] = 'Categoríes ya ítems';
$string['categoriesedit'] = 'Editar Categoríes';
$string['category'] = 'Categoría.';
$string['categoryedit'] = 'Editar categoría.';
$string['categoryname'] = 'Nome de la categoría.';
$string['categorytotal'] = 'Total categoría.';
$string['categorytotalfull'] = 'Total $a->category';
$string['changedefaults'] = 'Camudar valores por defeutu.';
$string['changereportdefaults'] = 'Camudar valores por defeutu del informe.';
$string['chooseaction'] = 'Escueya una aición...';
$string['choosecategory'] = 'Escoyer categoría';
$string['combo'] = 'Tabuladores y menú desplegable';
$string['compact'] = 'Compactar';
$string['configaggregationposition'] = 'Posición de la columna col cálculu total nel informe referíu a les notes.';
$string['configaggregationview'] = 'Caúna les categoríes pue apaecer de tres formes: mou completu (columna amestada y columnes d\'ítems de nota), namás columna amestada, o namás ítems de nota.';
$string['configaveragesdecimalpoints'] = 'Cantidá de decimales que van apaecer en caúna les puntuaciones media (por grupo o completa) embaxo d\'una columna de notes. Pue anulala l\'ítem de nota.';
$string['configaveragesdisplaytype'] = 'Especifica cómo van apaecer les medies de caúna les columnes nel informe de notes. El valir por defeutu (recomendaú) ye Heredar, que comprueba primero\'l tipu de caúna les columnes y, si ésti nun s\'axustó esplícitamente, garra\'l valor por defeutu del tipu xeneral de visionáu de notes. Si se seleicionaren otros tipos de visionáu, pasen per alto los axustes individuales de caúna les columnes y usen esclusivamente\'l tipu escoyíu.';
$string['configcoursegradedisplaytype'] = 'Escueya cómo van apaecer les notes nesti cursu. Pue escoyer tamién el valor por defeutu del sitiu. Les notes puen apaecer como notes reales, como porcentaxes (en rellación a les notes mínima y máxima) o como lletres (A, B, C, &c.). Si escueye les lletres, va poder tamién definir les sos propies lletres y les llendes de calificación.';
$string['configdecimalpoints'] = 'Cantidá de decimales de caúna les notes. Pue cambiase pola nota del ítem.';
$string['configdisablegradehistory'] = 'Desactivar l\'historial de rastréu de cambios nes tables de notes rellacionaes. Esto pue axilizar daqué\'l funcionamientu del servidor y guardar espaciu na base de datos.';
$string['configenableajax'] = 'Amiesta una capa de funcionalidá AJAX al informe del calificador, faciendo más cencielles y áxiles les operaciones comunes. Según qué Javascript tea activáu nel navegador del usuariu.';
$string['configenableoutcomes'] = 'Apoyo a los Resultaos (tamién conocíos como \'competencies\', \'oxetivos\', \'estándars\' o \'criterios\'). Quier dicir que calificamos usando una o más escales que tean coneutaes a les declaraciones de resultaos. L\'activación de los resultaos posibilita esta manera especial de calificación en tol sitiu.';
$string['configexportdecimalpoints'] = 'Cantidá de decimales que van apaecer nel archivu esportáu. Pue dexalo de llau na esportación.';
$string['configfixedstudents'] = 'Afita la columna d\'estudiantes nel informe del calificador, permitiendo que les notes corran horizontalmente.';
$string['configgradeboundary'] = 'Llende del porcentaxe penriba\'l que van asignase unes lletres a les calificaciones (nel casu de que s\'use notes  con lletres).';
$string['configgradedisplaytype'] = 'Les notes puen apaecer como notes reales, como porcentaxes (según les notes máxima y mínima) o como lletres (A, B, C, etc.)';
$string['configgradeexportdisplaytype'] = 'Les notes puen apaecer como notes reales, como porcentaxes (según les notes mínima y máxima) o como lletres (A, B, C, &c.) na esportación. Pue dexalo de llau na esportación.';
$string['configgradehistorylifetime'] = 'Esta opción especifica cuánto tiempu quier que se caltenga l\'historial de cambios nes tables de notes rellacionaes. Recomiéndase caltenelo tol tiempu posible. Si tien problemes de funcionamientu o tien un espaciu llendáu na base de datos, pruebe con un valor más baxu.';
$string['configgradeitemadvanced'] = 'Escoyer tolos ítems que van apaecer de la que s\'editen los ítems de nota.';
$string['configgradeletter'] = 'Lletra o otru símbolu usáu pa representar un rangu de notes.';
$string['configgradeletterdefault'] = 'Lletra o otru símbolu usáu pa representar un rangu de notes. Dexe esti campu vacíu si quier usar el valor por defeutu del sitiu (actualmente $a).';
$string['configgradepublishing'] = 'Activar la espublización n\'esportaciones ya importaciones: Pue entrar a les notes esportaes accediendo a una URL, ensin tener qu\'almacenales nun sitiu Moodle. Les notes puen importase entrando en esa URL (lo que quier dicir qu\'un sitiu Moodle pue importar notes espublizaes por otru sitiu).';
$string['confighiddenasdate'] = 'Si l\'usuariu nun pue ver les notes escondíes, enseñe la fecha d\'unvíu nel sitiu de \'-\'.';
$string['confighideforcedsettings'] = 'Nun enseñar asustes forzaos na calificación UI.';
$string['configincludescalesinaggregation'] = 'Pue incluyir les escales como númberos en toles notes agregaes de tolos llibros de notes en caún los cursos. PRECAUCIÓN: si cambia esti axuste toles notes van recalculase.';
$string['configmeanselection'] = 'Escueya qué tipu de notes van incluyise nos promedios de columna. Les celdes ensin nota van pasase per altu, o van ser calificaes con 0 (axuste por defeutu).';
$string['configprofilereport'] = 'Informe de notes usáu na páxina del perfil del usuariu.';
$string['configquickgrading'] = 'La nota rápida amiesta un testu a caúna los caxellos de nota nel informe del calificador, permitiendo editar la retroalimentación en munches notes al mesmu tiempu. Pue calcar nel botón Actualizar pa executar tolos cambios d\'una vez en vez de facelo d\'ún nún.';
$string['configrangesdecimalpoints'] = 'Cantidá de decimales que van apaecer en caún los rangos enriba d\'una columna de notes. Pue anulase calificando l\'ítem.';
$string['configrangesdisplaytype'] = 'Especifica cómo va apaecer el rangu de caúna les  columnes nel informe del calificador. El valor por defeutu (recomendáu) ye Heredar, que fai una comprobación primero del tipu de visionáu de caúna les columnes y, si nun ta axustáu de manera esplícita, garra\'l valor por defeutu del tipu de visionáu xeneral de la calificación. Si tán seleicionaos otros tipos de visionáu, pasen per altu los axustes individuales de caúna les columnes y usen esclusivamente\'l tipu escoyíu.';
$string['configshowactivityicons'] = 'Amosar o non un iconu d\'actividá al llau de caún los ítem de nota vinculáu a una actividá nel informe del calificador.';
$string['configshowaverages'] = 'Amuesa les medies de les columnes nel informe del calificador.';
$string['configshowcalculations'] = 'Amostrar o non iconos de cálculu al llau de caún los ítem y categoría de calificación, ferramientes sobre los ítems calculaos ya indicador visual de qu\'una columna ye calculada.';
$string['configshoweyecons'] = 'Amosar o non un iconu de \'enseñar/esconderr\' al llau de caúna les notes (controlando que l\'usuariu pueda velu).';
$string['configshowfeedback'] = 'Amosar o non un iconu de retroalimentación (p\'amestar/editar) al llau de caúna les calificaciones.';
$string['configshowgroups'] = 'Amosar promedios de grupu y medies nel informe del calificador.';
$string['configshowhiddenitems'] = 'Amosar ítems escondíos nel informe, incluso si l\'usuariu nun tien permiso moodle/grade:viewhidden. La visibilidá de les calificaciones escondíes nun queda afeutada por esti axuste.';
$string['configshowlocks'] = 'Amosar o non un iconu de \'bloquear/desbloquear\' al llau de caúna les calificaciones.';
$string['configshownumberofgrades'] = 'Enseña la cantidá de notes que se tán amestando al llau de caúna los promedios, ente paréntesis. Exemplu: 45 (34).';
$string['configshowpercentage'] = 'Enseñar el porcentaxe de caún los ítem de nota.';
$string['configshowquickfeedback'] = 'La Retroalimentación Rápida amiesta un ítem de testu a caún los caxellos de nota nel informe del calificador, permitiéndo qu\'edite los comentarios de munches notes al mesmu tiempu. Pue entós calcar nel botón Actualizar pa executar toos estos cambios d\'una vez en llugar de facelo d\'ún nún.';
$string['configshowranges'] = 'Amuesa una ringlera que tien el rangu de notes posibles pa caún los ítem nel informe del calificador.';
$string['configshowrank'] = 'Enseñar rango de caún los ítem.';
$string['configshowuseridnumber'] = 'Enseñar los númberos d\'identificación del usuariu nuna columna adicional.';
$string['configshowuserimage'] = 'Amosar o non la imaxe del perfil del usuariu al llau del so nome nel informe del calificador.';
$string['configstudentsperpage'] = 'Cantidá d\'estudiantes que van apaecer per páxina nel informe del calificador.';
$string['configstudentsperpagedefault'] = 'Canitidá d\'estudiantes que van apaecer per páxina nel informe del calificador. Dexe esti campu ensin enllenar pa usar el valor por defeutu del sitiu (actualmente $a).';
$string['configunlimitedgrades'] = 'Por defeutu, les notes tán llendaes polos valores máximu y mínimu del ítem de calificación. Si activa esta opción va esborrase esa llende y va permitise que s\'escriban direutamente nel \'gradebook\' notes penriba del 100%%. Recomiéndase activar esta opción nun momentu de baxa demanda, porque recalcular toles  notes pue ser una sobrecarga pal servidor.';
$string['contract'] = 'Contraer categoría';
$string['controls'] = 'Controles';
$string['courseavg'] = 'Promediu del cursu.';
$string['coursegradecategory'] = 'Categoría de calificación de cursu';
$string['coursegradedisplaytype'] = 'Forma d\'enseñar les notes del cursu';
$string['coursegradedisplayupdated'] = 'La forma d\'enseñar les notes del cursu actualizóse.';
$string['coursename'] = 'Nome del cursu.';
$string['coursescales'] = 'Escales del cursu.';
$string['coursesettings'] = 'Axustes del cursu.';
$string['coursesettingsexplanation'] = 'Los axustes del cursu determinen cómo apaez el llibru de notes pa tolos participantes del cursu.';
$string['coursetotal'] = 'Total del cursu.';
$string['createcategory'] = 'Crear categoría';
$string['createcategoryerror'] = 'Nun se pudo crear una categoría nueva.';
$string['creatinggradebooksettings'] = 'Creando axustes del llibru de notes.';
$string['csv'] = 'CSV';
$string['currentparentaggregation'] = 'Amestando padre actual.';
$string['curveto'] = 'Curvar a';
$string['decimalpoints'] = 'Puntos decimales globales';
$string['default'] = 'Por defeutu';
$string['defaultprev'] = 'Valor por defeutu ($a)';
$string['deletecategory'] = 'Esborrar categoría';
$string['disablegradehistory'] = 'Desactivar historial de notes.';
$string['displaylettergrade'] = 'Amosar notes con lletra.';
$string['displaypercent'] = 'Amosar porcentaxes';
$string['displaypoints'] = 'Amosar puntos';
$string['displayweighted'] = 'Amosar notes ponderaes';
$string['dropdown'] = 'Menú desplegable';
$string['droplow'] = 'Descartar la más baxa.';
$string['droplowhelp'] = 'Esta opción va descartar les X notes más baxes, y X ye\'l valor seleicionáu.';
$string['dropped'] = 'Descartaes';
$string['dropxlowest'] = 'Descartar X más baxes';
$string['dropxlowestwarning'] = 'Nota: Si usa \'descartar x más baxes\', la nota asume que tolos ítems de la categoría tienen el mesmu valir en puntos. Si esoc valires difieren, los resultaos van ser impredecibles.';
$string['duplicatescale'] = 'Duplicar escala';
$string['edit'] = 'Editar';
$string['editcalculation'] = 'Editar cálculu';
$string['editcalculationverbose'] = 'Editar cáculu pa $a->category$a->itemmodule $a->itemname';
$string['editfeedback'] = 'Editar retroalimentación';
$string['editgrade'] = 'Editar nota.';
$string['editgradeletters'] = 'Editar lletres de nota.';
$string['editoutcome'] = 'Editar resultáu';
$string['editoutcomes'] = 'Editar resultaos';
$string['editscale'] = 'Editar escala';
$string['edittree'] = 'Categoríes ya ítems';
$string['editverbose'] = 'Editar $a->category$a->itemmodule $a->itemname';
$string['enableajax'] = 'Activar AJAX';
$string['enableoutcomes'] = 'Activar resultaos';
$string['encoding'] = 'Codificación';
$string['errorcalculationnoequal'] = 'La fórmula tien d\'entamar pol signu \'igual\' (=1+2)';
$string['errorcalculationunknown'] = 'Fórmula inválida';
$string['errorgradevaluenonnumeric'] = 'Recibióse un valor non numbéricu pa nota baxa o alta de';
$string['errornocalculationallowed'] = 'Nun se permiten cálculos con esti ítem';
$string['errornocategorisedid'] = 'Nun se pudo consiguir una ID non categorizada.';
$string['errornocourse'] = 'Nun se pudo consiguir información del cursu.';
$string['errorreprintheadersnonnumeric'] = 'Recibióse un valor non numbéricu pa les cabeceres de reimpresión';
$string['errorsavegrade'] = 'Nun se se foi quien a guardar la nota.';
$string['exceptions'] = 'Esceiciones';
$string['excluded'] = 'Excluyíos';
$string['excludedhelp'] = 'Si ta activada esta opción, esta nota va ser excluyída de cualquier amiestamientu executáu por cualquier ítem o categoría de nota de rangu superior.';
$string['expand'] = 'Espandir categoría';
$string['export'] = 'Esportar';
$string['exportalloutcomes'] = 'Esportar tolos resultaos';
$string['exportfeedback'] = 'Incluyir retroalimentación na esportación';
$string['exportplugins'] = 'Coneutores d\'esportación';
$string['exportsettings'] = 'Esportar axustes';
$string['exportto'] = 'Esportar a';
$string['extracredit'] = 'Créditu estra';
$string['extracreditwarning'] = 'Nota: Si s\'adscribe un créditu estra a tolos ítems d\'una categoría, van esborrase del cálculu de la nota, polo que nun va esistir una puntuación total.';
$string['feedback'] = 'Retroalimentación';
$string['feedbackadd'] = 'Amestar retroalimentación';
$string['feedbackedit'] = 'Editar retroalimentación';
$string['feedbackhelp'] = 'Notes que\'l profesor amiesta a la nota. Puen ser una retroalimentación estensa, personalizada, o un códigu cenciellu inxertáu nun sistema internu de retroalimentación.';
$string['feedbacksaved'] = 'Retroalimentación guardada.';
$string['feedbackview'] = 'Ver retroalimentación.';
$string['finalgrade'] = 'Nota final.';
$string['finalgradehelp'] = 'Calcúlase la nota final depués de facer tolos cálculos.';
$string['fixedstudents'] = 'Columna d\'estudiantes afitada.';
$string['forceoff'] = 'Forzar: Desconeutar';
$string['forceon'] = 'Forzar: Coneutar';
$string['forelementtypes'] = 'pal $a escoyíu.';
$string['forstudents'] = 'Pa los estudiantes';
$string['full'] = 'Completu';
$string['fullmode'] = 'Vista completa';
$string['fullview'] = 'Vista completa';
$string['generalsettings'] = 'Axustes xenerales';
$string['grade'] = 'Nota';
$string['gradebook'] = 'Llibru de notes.';
$string['gradebookhiddenerror'] = 'El libru de notes ta axustáu de mou y manera que nun va enseñar nada a los estudiantes.';
$string['gradebookhistories'] = 'Historiales de notes.';
$string['gradeboundary'] = 'Llende de nota con lletra.';
$string['gradecategories'] = 'Categoríes de calificación.';
$string['gradecategory'] = 'Categoría de calificación actual:';
$string['gradecategoryhelp'] = 'Ayuda sobre categoríes de calificaciones.';
$string['gradecategorysettings'] = 'Axustes de categoría de calificación';
$string['gradedisplay'] = 'Amosar nota.';
$string['gradedisplaytype'] = 'Mou d\'amosar la nota.';
$string['gradedon'] = 'Calificaos $a';
$string['gradeexceptions'] = 'Escluyir de calificación.';
$string['gradeexceptionshelp'] = 'Ayuda sobre escepciones de calificaciones.';
$string['gradeexportdecimalpoints'] = 'Puntos decimales na esportación de notes.';
$string['gradeexportdisplaytype'] = 'Forma d\'amosar la esportación de notes.';
$string['gradeforstudent'] = '$a->student<br />$a->item$a->feedback';
$string['gradehelp'] = 'Ayuda sobre les notes.';
$string['gradehistorylifetime'] = 'Duración del historial de notes.';
$string['gradeitem'] = 'Ítem de nota';
$string['gradeitemaddusers'] = 'Escluyir de calificación';
$string['gradeitemadvanced'] = 'Opciones avanzaes d\'ítems de nota.';
$string['gradeitemislocked'] = 'Esta actividá ta bloqueada nel llibru de notes. Los cambios realizaos a les notes nesta actividá nun se van copiar nel llibru de notes hasta que nun se desbloquée.';
$string['gradeitemlocked'] = 'Calificación bloqueada';
$string['gradeitemmembersselected'] = 'Escluyíos de calificación';
$string['gradeitemnonmembers'] = 'Incluyíos na calificación';
$string['gradeitemremovemembers'] = 'Incluyir en calificación';
$string['gradeitems'] = 'Ítems de calificación';
$string['gradeitemsettings'] = 'Axustes d\'ítems de calificación';
$string['gradeitemsinc'] = 'Ítems de calificación pa incluyir';
$string['gradeletter'] = 'Lletra de nota';
$string['gradeletterhelp'] = 'Ayuda sobre lletra de nota.';
$string['gradeletternote'] = 'Pa esborrar una lletra de nota, cenciellamente vacíe una cualquier de les<br />tres árees de testu d\'esa lletra y calque en guardar cambios.';
$string['gradeletters'] = 'Lletres de nota.';
$string['gradelocked'] = 'La nota ta bloqueada';
$string['gradelong'] = '$a->grade / $a->max';
$string['grademax'] = 'Nota máxima';
$string['grademaxhelp'] = 'Nota máxima posible nesti ítem.';
$string['grademin'] = 'Nota mínima.';
$string['grademinhelp'] = 'Nota mínima posible nesti ítem.';
$string['gradeoutcomeitem'] = 'Ítem de resultáu de nota.';
$string['gradeoutcomes'] = 'Resultaos';
$string['gradeoutcomescourses'] = 'Resultaos del cursu.';
$string['gradepass'] = 'Nota p\'aprobar';
$string['gradepasshelp'] = '¿Qué nota ye necesaria p\'aprobar?';
$string['gradepreferences'] = 'Preferencies de Calificación';
$string['gradepreferenceshelp'] = 'Ayuda sobre preferencies de calificación.';
$string['gradepublishing'] = 'Activar espublización.';
$string['graderreport'] = 'Informe del calificador.';
$string['grades'] = 'Notes';
$string['gradesonly'] = 'Namás notes.';
$string['gradessettings'] = 'Ajustes';
$string['gradetype'] = 'Tipu de nota.';
$string['gradetypehelp'] = 'Tipu de nota usáu nesti ítem. Hai 4 tipos: nengún, valor, escala y testu. Namás puen amestase los tipos de valor y escala.';
$string['gradeview'] = 'Ver nota.';
$string['gradeweighthelp'] = 'Ayuda sobre ponderación de notes.';
$string['groupavg'] = 'Promediu del grupu';
$string['hidden'] = 'Esconder';
$string['hiddenasdate'] = 'Enseñar fecha d\'unvíu de les calificaciones escondíes.';
$string['hiddenuntil'] = 'Esconder hasta';
$string['hiddenuntildate'] = 'Esconder hasta: $a';
$string['hideadvanced'] = 'Esconder carauterístiques avanzaes';
$string['hideaverages'] = 'Esconder promedios';
$string['hidecalculations'] = 'Esconder cálculos';
$string['hidecategory'] = 'Escondíos';
$string['hideeyecons'] = 'Esconder iconos \'amosar/esconder\'';
$string['hidefeedback'] = 'Esconder retroalimentación';
$string['hideforcedsettings'] = 'Esconder axustes forzaos';
$string['hidegroups'] = 'Esconder grupos';
$string['hidelocks'] = 'Esconder bloqueos';
$string['hidenooutcomes'] = 'Enseñar resultaos';
$string['hidequickfeedback'] = 'Esconder Retroalimentación Rápida.';
$string['hideranges'] = 'Esconder rangos';
$string['hideverbose'] = 'Esconder $a->category$a->itemmodule $a->itemname';
$string['highgradeascending'] = 'Ordenar per nota ascendente';
$string['highgradedescending'] = 'Ordenar per nota descendente';
$string['highgradeletter'] = 'Altes';
$string['identifier'] = 'Identificar l\'usuariu por';
$string['idnumberhelp'] = 'Númberu d\'identificación arbitrariu proporcionáu pol módulu responsable (tien de tar definíu y ser únicu).';
$string['idnumbers'] = 'Númberos id';
$string['import'] = 'Importar';
$string['importcsv'] = 'Importar CSV';
$string['importcustom'] = 'Importar como resultaos personalizaos (namás esti cursu)';
$string['importerror'] = 'Hubo un erru: esti script nun se pidió colos parámetros correutos.';
$string['importfailed'] = 'Importación fallida';
$string['importfeedback'] = 'Importar retroalimentación';
$string['importfile'] = 'Importar archivu.';
$string['importfilemissing'] = 'Nun se recibió nengún archivu. Vuelva al formulariu y asegúrese de que sube un archivu válidu.';
$string['importfrom'] = 'Importar de';
$string['importoutcomenofile'] = 'L\'archivu que subió ta vacíu o corruptu. Por favor, verifique que ye un archivu válidu. El problema deteutóse na ringlera $a; esto pasa si les ringleres de datos nun tienen les mesmes columnes que la primer ringlera (cabecera) o si l\'archivu importáu nun tien les cabeceres esperaes. Mire que l\'archivu esportáu pa ver un exemplu d\'archivu con cabecera válida.';
$string['importoutcomes'] = 'Importar resultaos';
$string['importoutcomesuccess'] = 'Resultáu importáu \"$a->name\" con ID #$a->id';
$string['importplugins'] = 'Plugins d\'importación';
$string['importpreview'] = 'Vista previa de la importación';
$string['importsettings'] = 'Importar axustes';
$string['importskippednomanagescale'] = 'Nun tien permisu p\'amestar una escala nueva. El resultáu \"$a\" omitióse porque necesita crear una  escala nueva.';
$string['importskippedoutcome'] = 'Yá esiste un resultáu col nome curtiu \"$a\" nesti contestu; l\'archivu importáu omitióse.';
$string['importstandard'] = 'Importar como resultaos estándar.';
$string['importsuccess'] = 'Importación de notes correuta.';
$string['importxml'] = 'Importar XML';
$string['includescalesinaggregation'] = 'Incluyir escales na agregación';
$string['incorrectcourseid'] = 'La ID del cursu ye incorreuta';
$string['incorrectcustomscale'] = '(Escala personalizada incorreuta: cámbiela, por favor)';
$string['incorrectminmax'] = 'El mínimu tien de ser menor que\'l máximu.';
$string['inherit'] = 'Heredar';
$string['intersectioninfo'] = 'Info Estudiante/Nota.';
$string['item'] = 'Ítem';
$string['iteminfo'] = 'Información del ítem';
$string['iteminfohelp'] = 'Información y notas d\'esti ítem.';
$string['itemname'] = 'Nome del ítem';
$string['itemnamehelp'] = 'Nome d\'esti ítem, suministráu pol módulu.';
$string['items'] = 'Ítems';
$string['itemsedit'] = 'Editar ítem de nota.';
$string['keephigh'] = 'Caltener la más alta';
$string['keephighhelp'] = 'Esta opción va conservar namás les X calificaciones más altes. El valor X ye\'l valor escoyíu.';
$string['keymanager'] = 'Xestor de claves.';
$string['lessthanmin'] = 'La nota otorgada en $a->itemname a $a->username ye menor que\'l mínimu permitíu.';
$string['letter'] = 'Lletra';
$string['lettergrade'] = 'Nota por letra';
$string['lettergradenonnumber'] = 'Notes baxes y/o altes non numbériques pa';
$string['letterpercentage'] = 'Lletra (porcentaxe)';
$string['letterreal'] = 'Lletra (real)';
$string['letters'] = 'Lletres';
$string['linkedactivity'] = 'Actividá vinculada';
$string['linkedactivityhelp'] = 'Actividá opcional a la que ta vinculáu esti ítem de resultáu.';
$string['linktoactivity'] = 'Enllazar a l\'actividá $a->name';
$string['lock'] = 'Bloquear';
$string['locked'] = 'Bloquear';
$string['locktime'] = 'Bloquear dende';
$string['locktimedate'] = 'Bloqueada dende: $a';
$string['lockverbose'] = 'Bloquear $a->category$a->itemmodule $a->itemname';
$string['lowest'] = 'Más baxa';
$string['lowgradeletter'] = 'Baxa';
$string['manualitem'] = 'Ítem manual';
$string['mapfrom'] = 'Mapa dende';
$string['mappings'] = 'Mapeos d\'ítems de nota.';
$string['mapto'] = 'Mapa a';
$string['max'] = 'Más alta';
$string['maxgrade'] = 'Nota máxima';
$string['meanall'] = 'Toles notes.';
$string['meangraded'] = 'Notes non vacíes.';
$string['meanselection'] = 'Notes escoyíes pa promedios.';
$string['median'] = 'Mediana';
$string['min'] = 'Más baxa';
$string['missingscale'] = 'La escala tien de tar seleicionada.';
$string['mode'] = 'Moda';
$string['morethanmax'] = 'La nota en $a->itemname de $a->username ye más grande que la máxima permitida.';
$string['moveselectedto'] = 'Mover los ítems seleicionaos a:';
$string['movingelement'] = 'Moviendo $a';
$string['multfactor'] = 'Multiplicador';
$string['multfactorhelp'] = 'Factor pol que se van multiplicar toles notes d\'esti ítem.';
$string['mypreferences'] = 'Les mios preferencies.';
$string['myreportpreferences'] = 'Les mios preferencies d\'informe.';
$string['navmethod'] = 'Métodu de navegación';
$string['neverdeletehistory'] = 'Enxamás esborrar historial';
$string['newcategory'] = 'Categoría nueva';
$string['newitem'] = 'Item nuevu de calificación.';
$string['newoutcomeitem'] = 'Item nuevu de resultáu.';
$string['newuserkey'] = 'Clave nueva d\'usuariu.';
$string['no'] = 'Non';
$string['nocategories'] = 'Nun s\'amestaren o nun s\'atoparen les categoríes de nota d\'esti cursu.';
$string['nocategoryname'] = 'Nun se dio nome a esta categoría.';
$string['nocategoryview'] = 'Ensin categoría pa ver por';
$string['nocourses'] = 'Entá nun hai cursos';
$string['noforce'] = 'Non forzar';
$string['nogradeletters'] = 'Nun s\'axustaren les lletres de nota.';
$string['nogradesreturned'] = 'Nun se devolvieren notes.';
$string['noidnumber'] = 'Ensin númberu d\'id';
$string['nolettergrade'] = 'Ensin nota por lletra pa';
$string['nomode'] = 'NA';
$string['nonnumericweight'] = 'Recibóse un valor non numbéricu pa';
$string['nonunlockableverbose'] = 'Esta nota nun pue desbloquease hasta que $a->itemname nun tea desbloqueáu/ada.';
$string['nonweightedpct'] = '%% ensin ponder';
$string['nooutcome'] = 'Ensin resultáu';
$string['nooutcomes'] = 'Los ítems de resultaos tienen de tar vinculaos a un resultáu de cursu, pero nun esisten resultaos pa esti cursu. ¿Quier amestar ún?';
$string['nopublish'] = 'Non espublizar';
$string['noscales'] = 'Los resultaos tienen de tar vinculaos a una escala (de cursu o global), pero nun esiste nengún. ¿Quier amestar ún?';
$string['noselectedcategories'] = 'nun s\'escoyeren categoríes.';
$string['noselecteditems'] = 'nun s\'escoyeren ítems.';
$string['notteachererror'] = 'Namás los profesores puen usar esta opción.';
$string['numberofgrades'] = 'Cantidá de calificaciones.';
$string['onascaleof'] = 'nuna escala de $a->grademin a $a->grademax';
$string['operations'] = 'Operaciones';
$string['options'] = 'Opciones';
$string['outcome'] = 'Resultáu.';
$string['outcomeassigntocourse'] = 'Asignar otru resultáu a esti cursu.';
$string['outcomecategory'] = 'Crear resultaos en categoría.';
$string['outcomecategorynew'] = 'Categoría nueva.';
$string['outcomeconfirmdelete'] = '¿Ta seguru/a de que quier esborrar el resultáu \"$a\"?';
$string['outcomecreate'] = 'Amestar resultáu nuevu.';
$string['outcomedelete'] = 'Esborrar resultáu';
$string['outcomeidhelp'] = 'Resultáu que representa esti ítem de nota.';
$string['outcomeitem'] = 'Ítem de resultáu.';
$string['outcomeitemsedit'] = 'Editar ítem de resultaú.';
$string['outcomename'] = 'Nome del resultáu.';
$string['outcomereport'] = 'Informe del resultáu.';
$string['outcomes'] = 'Resultaos';
$string['outcomescourse'] = 'Resultaos usaos nel cursu.';
$string['outcomescoursecustom'] = 'Usu personal (non quitar)';
$string['outcomescoursenotused'] = 'Estándar ensin usar.';
$string['outcomescourseused'] = 'Estándar usáu (non quitar)';
$string['outcomescustom'] = 'Resultaos personalizaos';
$string['outcomesstandard'] = 'Resultaos estándar';
$string['outcomesstandardavailable'] = 'Resultaos estándar disponibles.';
$string['outcomestandard'] = 'Resultáu disponible.';
$string['outcomestandardhelp'] = 'Resultáu estándar disponible en tol sitiu (i.e., en tolos cursos).';
$string['overallaverage'] = 'Promediu xeneral';
$string['overridden'] = 'Anulaes';
$string['overriddenhelp'] = 'Si ta activaú, previén cualquier intentu futuru d\'axustar automáticamente\'l valor de la nota. Esti FLAG davezu queda axustáu internamente pol llibru de notes, pero pue activase o desactivase manualmente usando esta opción.';
$string['overriddennotice'] = 'La nota final d\'esta actividá axusltóse manualmente.';
$string['overridesitedefaultgradedisplaytype'] = 'Pasar per altu los valores por defeutu del sitiu.';
$string['overridesitedefaultgradedisplaytypehelp'] = 'Marque esti caxellu pa pasar per altu los valores por defeutu del sitiu referíos a la manera na que van apaecer les notes nel llibru de notes. Esta opción activa los ellementos del formulariu que permiten definir les lletres de nota y les llendes escoyíes.';
$string['parentcategory'] = 'Categoría padre';
$string['pctoftotalgrade'] = '%% de la nota total';
$string['percent'] = 'Porcentaxe';
$string['percentage'] = 'Porcentaxe';
$string['percentageletter'] = 'Porcentaxe (lletra)';
$string['percentagereal'] = 'Porcentaxe (real)';
$string['percentascending'] = 'Clasificar per porcentaxe ascendente';
$string['percentdescending'] = 'Ordenar per porcentaxe descendente';
$string['percentshort'] = '%%';
$string['plusfactor'] = 'Compensar';
$string['plusfactorhelp'] = 'Númberu que se va añadir a caúna les calificaciones d\'esti ítem, dempués que s\'aplique\'l multiplicador.';
$string['points'] = 'puntos';
$string['pointsascending'] = 'Clasificar por puntos ascendente';
$string['pointsdescending'] = 'Clasificar por puntos descendente';
$string['positionfirst'] = 'Primeru';
$string['positionlast'] = 'Últimu';
$string['preferences'] = 'Preferencies';
$string['prefgeneral'] = 'Xeneral';
$string['prefletters'] = 'Lletres de nota y llendes.';
$string['prefrows'] = 'Files especiales';
$string['prefshow'] = 'Enseñar/esconder conmutadores';
$string['previewrows'] = 'Previsualizar files';
$string['profilereport'] = 'Informe de perfil d\'usuariu.';
$string['publishing'] = 'Espublizando';
$string['quickfeedback'] = 'Retroalimentación rápida';
$string['quickgrading'] = 'Nota rápida';
$string['range'] = 'Rangu';
$string['rangesdecimalpoints'] = 'Decimales nos rangos';
$string['rangesdisplaytype'] = 'Tipu de visualización del rangu.';
$string['rank'] = 'Rangu.';
$string['rawpct'] = '%% brutu';
$string['real'] = 'Real';
$string['realletter'] = 'Real (lletra)';
$string['realpercentage'] = 'Real (porcentaxe)';
$string['regradeanyway'] = 'Recalificar de tolos moos';
$string['removeallcoursegrades'] = 'Esborrar toles notes.';
$string['removeallcourseitems'] = 'Esborrar tolos ítems y categoríes.';
$string['report'] = 'Informe';
$string['reportdefault'] = 'Valor por defeutu del informe ($a)';
$string['reportplugins'] = 'Coneutores d\'informe';
$string['reportsettings'] = 'Axustes d\'informe';
$string['reprintheaders'] = 'Reimprimir cabeceres';
$string['respectingcurrentdata'] = 'la configuración actual queda ensin cambiar.';
$string['rowpreviewnum'] = 'Previsualizar files';
$string['savechanges'] = 'Guardar cambios';
$string['savepreferences'] = 'Guardar preferencies';
$string['scaledpct'] = 'Escaláu %%';
$string['scaleidhelp'] = 'Escala a la que se vincula esti $a.';
$string['scalestandardhelp'] = 'Una escala estándar ta disponible en tolos cursos del sitiu.';
$string['seeallcoursegrades'] = 'Ver toles notes del cursu.';
$string['selectalloroneuser'] = 'Escoyer toos o un usuariu.';
$string['selectauser'] = 'Escoyer un usuariu';
$string['selectdestination'] = 'Escoyer destín de $a';
$string['separator'] = 'Separtador';
$string['sepcomma'] = 'Coma';
$string['septab'] = 'Tabulador';
$string['setcategories'] = 'Categoríes';
$string['setcategorieserror'] = 'Tien d\'axustar les categoríes del cursu enantes de poder asignar ponderaciones.';
$string['setgradeletters'] = 'Calificar con lletra';
$string['setpreferences'] = 'Preferencies';
$string['setting'] = 'Axuste';
$string['settings'] = 'Axustes';
$string['setweights'] = 'Pesos';
$string['showactivityicons'] = 'Enseñar iconos d\'actividá.';
$string['showallhidden'] = 'Toos ocultos';
$string['showallstudents'] = 'Enseñar a tolos estudiantes.';
$string['showaverages'] = 'Enseñar promedios de columna.';
$string['showcalculations'] = 'Enseñar cálculos.';
$string['showeyecons'] = 'Enseñar iconos \'amosar/esconder\'';
$string['showfeedback'] = 'Enseñar retroalimentación';
$string['showgroups'] = 'Enseñar grupos';
$string['showhiddenitems'] = 'Enseñar ítems escondíos.';
$string['showhiddenuntilonly'] = 'Escondíos namás hasta';
$string['showlocks'] = 'Enseñar bloqueos';
$string['shownohidden'] = 'Non escondíos';
$string['shownooutcomes'] = 'Esconder resultaos';
$string['shownumberofgrades'] = 'Enseñar númberu de notes nos promedios.';
$string['showpercentage'] = 'Enseñar porcentaxe.';
$string['showquickfeedback'] = 'Enseñar Retroalimentación Rápida';
$string['showranges'] = 'Enseñar rangos';
$string['showrank'] = 'Enseñar rangu';
$string['showuseridnumber'] = 'Enseñar el númberu d\'identificación del usuariu.';
$string['showuserimage'] = 'Enseñar imáxenes de perfil del usuariu.';
$string['showverbose'] = 'Enseñar $a->category$a->itemmodule $a->itemname';
$string['simpleview'] = 'Vista cenciella';
$string['sitewide'] = 'Tol sitiu';
$string['sort'] = 'ordenar';
$string['sortasc'] = 'Ordenar (ascendente)';
$string['sortbyfirstname'] = 'Ordenar por nome';
$string['sortbylastname'] = 'Ordenar por apellíu';
$string['sortdesc'] = 'Ordenar (descendente)';
$string['standarddeviation'] = 'Desviación típica';
$string['stats'] = 'Estadístiques';
$string['statslink'] = 'Estadístiques';
$string['student'] = 'Estudiante';
$string['studentsperpage'] = 'Estudiantes per páxina';
$string['subcategory'] = 'Categoría normal';
$string['submissions'] = 'Unvíos';
$string['submittedon'] = 'Unviáu: $a';
$string['switchtofullview'] = 'Cambiar a vista completa';
$string['switchtosimpleview'] = 'Cambiar a vista cenciella.';
$string['synclegacygrades'] = 'Sincronizar notes heredaes';
$string['tabs'] = 'Tabuladores';
$string['topcategory'] = 'Categoría super';
$string['total'] = 'Total';
$string['totalweight100'] = 'El pesu total ye igual a 100';
$string['totalweightnot100'] = 'El pesu total nun ye igual a 100';
$string['turnfeedbackoff'] = 'Desactivar retroalimentación';
$string['turnfeedbackon'] = 'Activar retroalimentación';
$string['typenone'] = 'Nengún';
$string['typescale'] = 'Escala';
$string['typetext'] = 'Testu';
$string['typevalue'] = 'Valor';
$string['uncategorised'] = 'Ensin categorizar';
$string['unchangedgrade'] = 'Nota ensin cambios';
$string['unenrolledusersinimport'] = 'Esta importación incluye les siguientes notes de los usuarios non matriculaos actualmente nesti cursu: $a';
$string['unlimitedgrades'] = 'Notes non llendaes.';
$string['unlock'] = 'Desbloquear';
$string['unlockverbose'] = 'Desbloquear $a->category$a->itemmodule $a->itemname';
$string['unused'] = 'Ensin usu';
$string['updatedgradesonly'] = 'Esportar namás notes nueves o actualizaes';
$string['uploadgrades'] = 'Subir notes';
$string['useadvanced'] = 'Usar carauterístiques avanzaes';
$string['usedcourses'] = 'Cursos usaos';
$string['usedgradeitem'] = 'Ítem de nota usáu.';
$string['usenooutcome'] = 'Non usar resultáu';
$string['usenoscale'] = 'Non usar escala';
$string['usepercent'] = 'Usar porcentaxe';
$string['user'] = 'Usuariu';
$string['usergrade'] = 'Usuariu $a->fullname ($a->useridnumber) nel ítem $a->gradeidnumber';
$string['userkeyhelp'] = 'Escueya una clave guardada que dea a los usuarios entrada a los datos espublizaos por esti plugin d\'esportación, ensin tener qu\'almacenalos en Moodle. Escueya \'crear clave nueva d\'usuariu\' pa xenerar una clave nueva de la que remite esti formulariu.';
$string['userpreferences'] = 'Preferencies del usuariu.';
$string['useweighted'] = 'Usar ponderación';
$string['verbosescales'] = 'Escales de testu.';
$string['viewbygroup'] = 'Grupu';
$string['viewgrades'] = 'Ver notes.';
$string['warningexcludedsum'] = 'Alvertencia: la esclusión de notes nun ye compatible cola agregación.';
$string['weight'] = 'Pesu';
$string['weightcourse'] = 'Usar notes non ponderaes pal cursu';
$string['weightedascending'] = 'Clasificar por porcentaxe ponderáu ascendente.';
$string['weighteddescending'] = 'Clasificar por porcentaxe ponderáu descendente.';
$string['weightedpct'] = '%% ponderada';
$string['weightedpctcontribution'] = 'contribución %% ponderada';
$string['weightorextracredit'] = 'Ponderación o créditu estra';
$string['weights'] = 'Ponderaciones';
$string['weightsedit'] = 'Editar ponderaciones y créditos estra';
$string['weightuc'] = 'Pesu';
$string['writinggradebookinfo'] = 'Escribiendo axustes del llibru de notes.';
$string['xml'] = 'XML';
$string['yes'] = 'Sí';
$string['yourgrade'] = 'La so nota';
$string['errorupdatinggradecategoryaggregateonlygraded'] = 'Error al actualizar el ajuste \"Agregar sólo ítems calificados\" de la categoría de calificación ID $a->id'; // ORPHANED
$string['errorupdatinggradecategoryaggregateoutcomes'] = 'Error al actualizar el ajuste \"Agregar resultados\" de la categoría de calificación ID $a->id'; // ORPHANED
$string['errorupdatinggradecategoryaggregatesubcats'] = 'Error al actualizar el ajuste \"Agregar subcategorías\" de la categoría de calificación ID $a->id'; // ORPHANED
$string['errorupdatinggradecategoryaggregation'] = 'Error al actualizar el tipo de agregación de la categoría de calificación ID $a->id'; // ORPHANED
$string['errorupdatinggradeitemaggregationcoef'] = 'Error al actualizar el coeficiente de agregación (ponderación o crédito extra) de la categoría de calificación ID $a->id'; // ORPHANED
$string['norolesdefined'] = 'No hay roles definidos en Administración > Calificaciones > Ajustes generales > Roles calificados'; // ORPHANED
$string['nousersloaded'] = 'No se han subido usuarios'; // ORPHANED
$string['scaleconfirmdelete'] = '¿Está seguro de que desea eliminar la escala \"$a\"?'; // ORPHANED
$string['configbulkcheckboxes'] = 'Casillas de verificación al lado de cada calificación para operaciones de calificación masiva.'; // ORPHANED
$string['configquickfeedback'] = 'La retroalimentación rápida añade un texto a cada celda de calificación en el informe del calificador, permitiendo editar muchas calificaciones simultáneamente. Puede hacer clic en el botón Actualizar para ejecutar todos estos cambios de una vez en lugar de hacerlo uno a uno.'; // ORPHANED
$string['errornocategorizedid'] = '¡No se ha podido conseguir una id no categorizada!'; // ORPHANED
$string['overallavg'] = 'Promedio general'; // ORPHANED
$string['aggregationcoefhelp'] = 'Peso aplicado a todas las calificaciones de este ítem durante la agregación con otros ítems de calificación.'; // ORPHANED
$string['addevent'] = 'Agregar ítem calificado'; // ORPHANED
$string['addgrade'] = 'Gestionar ítems calificados'; // ORPHANED
$string['addgrades'] = 'Agregrar calificaciones'; // ORPHANED
$string['aggregateextracreditmeanall'] = 'Media de todas las calificaciones (créditos extra)'; // ORPHANED
$string['aggregateextracreditmeangraded'] = 'Media de las calificaciones no vacías (créditos extra)'; // ORPHANED
$string['aggregatemaxall'] = 'Calificación más alta de todas'; // ORPHANED
$string['aggregatemaxgraded'] = 'Calificación más alta de las no vacías'; // ORPHANED
$string['aggregatemeanall'] = 'Media de todas las calificaciones'; // ORPHANED
$string['aggregatemeangraded'] = 'Media de las calificaciones no vacías'; // ORPHANED
$string['aggregatemedianall'] = 'Mediana de todas las calificaciones'; // ORPHANED
$string['aggregatemediangraded'] = 'Mediana de las calificaciones no vacías'; // ORPHANED
$string['aggregateminall'] = 'Calificación más baja de todas'; // ORPHANED
$string['aggregatemingraded'] = 'Calificación más baja de las no vacías'; // ORPHANED
$string['aggregatemodeall'] = 'Moda de todas las calificaciones'; // ORPHANED
$string['aggregatemodegraded'] = 'Moda de las de las calificaciones no vacías'; // ORPHANED
$string['aggregateweightedmeanall'] = 'Media ponderada de todas las calificaciones'; // ORPHANED
$string['aggregateweightedmeangraded'] = 'Media ponderada de las calificaciones no vacías'; // ORPHANED
$string['changesitedefaults'] = 'Cambiar valores por defecto del sitio'; // ORPHANED
$string['completedonly'] = 'Sólo completadas'; // ORPHANED
$string['confirmexit'] = 'Pulse OK para guardar los cambios antes de salir. Si presiona Cancelar se perderán todos los cambios no guardados.'; // ORPHANED
$string['confirmresetgrades'] = '¿Está seguro de que quiere revertir sus últimas calificaciones guardadas? Cualesquiera cambios desde la última vez que guardó se perderán.'; // ORPHANED
$string['confirmresetprefs'] = '¿Reiniciar prefrerencias?'; // ORPHANED
$string['confirmsubmitgrades'] = '¿Está seguro de que quiere enviar los cambios?'; // ORPHANED
$string['createevent'] = 'Crear evento'; // ORPHANED
$string['deleteevent'] = 'Eliminar evento'; // ORPHANED
$string['description'] = 'Descripción:'; // ORPHANED
$string['duplicatename'] = 'copiar'; // ORPHANED
$string['editanotherassignmentcategory'] = 'Editar calificaciones en otra categoría'; // ORPHANED
$string['editassignment'] = 'Editar'; // ORPHANED
$string['editevent'] = 'Editar evento calificado existente'; // ORPHANED
$string['editgrades'] = 'Editar calificaciones'; // ORPHANED
$string['exportletters'] = 'Exportar letras'; // ORPHANED
$string['exportlettershelp'] = 'Cuando los ítems usen letras en lugar de valores, se exportarán las letras en lugar de los valores reales.'; // ORPHANED
$string['gradebookstatswarning'] = 'Las estadísticas incluyen tareas incompletas que aparecen como \'-\' y se cuentan como 0'; // ORPHANED
$string['gradeeventname'] = 'Nombre del ítem calificado:'; // ORPHANED
$string['gradeeventpoints'] = 'Puntos'; // ORPHANED
$string['havenotsaved1'] = 'No ha guardado en los últimos'; // ORPHANED
$string['havenotsaved2'] = '. minutos. ¿Desea guardar sus cambios ahora?'; // ORPHANED
$string['incompleteincluded'] = 'Incluyendo incompletas'; // ORPHANED
$string['left'] = 'Izquierda'; // ORPHANED
$string['na'] = 'ND'; // ORPHANED
$string['negativegrade'] = 'Calificación negativa'; // ORPHANED
$string['newevent'] = 'Agregar nuevo ítem calificado'; // ORPHANED
$string['nogradeitemsinanycategory'] = 'No hay categorías de calificación que incluyan ítems calificados'; // ORPHANED
$string['nogradeschanged'] = 'No se cambió ninguna calificación'; // ORPHANED
$string['notvalid'] = 'calificación no válida'; // ORPHANED
$string['resetgradepreferences'] = '¿Está seguro de que desea reiniciar todas las preferencias de calificación para $a? <br /><br />Se perderán todos los ajustes (e. g., ponderación, categorías, descartar la más baja, curvado, etc.).'; // ORPHANED
$string['reverttolastsave'] = 'Descartar cambios'; // ORPHANED
$string['right'] = 'Derecha'; // ORPHANED
$string['savegradechanges'] = 'Guardar cambios de calificación'; // ORPHANED
$string['savegradeserror'] = 'Se han encontrado $a problema(s) al intentar guardar las calificaciones. Por favor, revise más abajo'; // ORPHANED
$string['savegradesinfo'] = '<br>Las calificaciones editables se muestran en verde. Haga clic en Guardar cambios de calificación para ver los resultados en los cambios que ha hecho en las calificaciones de los estudiantes.'; // ORPHANED
$string['savegradessuccess'] = '$a calificación(es) se han guardado con éxito'; // ORPHANED
$string['sitedefault'] = 'Valor por defecto del sitio ($a)'; // ORPHANED
$string['yourchangesweresaved'] = 'Sus cambios se han guardado'; // ORPHANED
$string['exportods'] = 'Exportar ODS'; // ORPHANED
$string['exporttxt'] = 'Exportar TXT'; // ORPHANED
$string['exportxml'] = 'Exportar XML'; // ORPHANED
$string['gradereports'] = 'Informe de calificaciones'; // ORPHANED
$string['userreport'] = 'Informe de calificación del usuario'; // ORPHANED

?>
