<?PHP // $Id$ 
      // group.php - created with Moodle 1.9.5+ (Build: 20091007) (2007101553)


$string['addgroupstogrouping'] = 'Amestar grupos a  agrupaciones.';
$string['addgroupstogroupings'] = 'Amestar/Quitar grupos';
$string['adduserstogroup'] = 'Amestar/Esborrar usuarios d\'un grupu.';
$string['allocateby'] = 'Asitiar miembros.';
$string['anygrouping'] = 'Cualquier grupu';
$string['autocreategroups'] = 'Autocrear grupos';
$string['backtogroupings'] = 'Tornar a agrupaciones';
$string['backtogroups'] = 'Tornar a grupos';
$string['badnamingscheme'] = 'Tien de contener esautamente una \'@\' o una \'#\'.';
$string['byfirstname'] = 'N\'orde alfabéticu pol nome, apellíos.';
$string['byidnumber'] = 'N\'orde alfabéticu por númberu d\'ID.';
$string['bylastname'] = 'N\'orde alfabéticu por apellíos, nome.';
$string['createautomaticgrouping'] = 'Crear agrupación automática.';
$string['creategroup'] = 'Crear grupu';
$string['creategrouping'] = 'Crear agrupación.';
$string['creategroupinselectedgrouping'] = 'Crear un grupu na agrupación escoyida.';
$string['createingrouping'] = 'Crear na agrupación';
$string['createorphangroup'] = 'Crear un grupu güérfanu.';
$string['databaseupgradegroups'] = 'La versión de los grupos agora ye $a';
$string['defaultgrouping'] = 'Agrupación por defeutu.';
$string['defaultgroupingname'] = 'Agrupación';
$string['defaultgroupname'] = 'Grupu';
$string['deleteallgroupings'] = 'Esborrar toles agrupaciones.';
$string['deleteallgroups'] = 'Esborrar tolos grupos.';
$string['deletegroupconfirm'] = '¿Ta seguru/a de que quier esborrar el grupu \'$a\'?';
$string['deletegrouping'] = 'Esborrar agrupación';
$string['deletegroupingconfirm'] = '¿Ta seguru/a de que quier esborrar l\'agruación \'$a\'? (Los grupos nun se van esborrar).';
$string['deletegroupsconfirm'] = '¿Ta seguru/a de que quier esborrar los grupos que vienen darréu?';
$string['deleteselectedgroup'] = 'Esborrar el grupu seleicionáu.';
$string['editgroupingsettings'] = 'Editar configuración d\'agrupación.';
$string['editgroupsettings'] = 'Editar configuración de grupu';
$string['enrolmentkey'] = 'Llave de matricula.';
$string['erroraddremoveuser'] = 'Erru de la que s\'amestaba/quitaba l\'usuariu $a del grupu.';
$string['erroreditgroup'] = 'Erru de la que s\'amestaba/actualizaba grupu $a';
$string['erroreditgrouping'] = 'Erru de la que se creaba/actualizaba agrupación $a';
$string['errorinvalidgroup'] = 'Erru, el grupu $a nun ye válidu.';
$string['errorselectone'] = 'Por favor, escueya un únicu grupu enantes escoyer esta opción.';
$string['errorselectsome'] = 'Por favor, escueya ún o más grupos enantes escoyer esta opción.';
$string['evenallocation'] = 'Nota: pa caltener l\'asitiamientu del grupu, el númberu de miembros per grupu ye distintu del númberu qu\'especificó.';
$string['existingmembers'] = 'Miembros esistentes: $a';
$string['filtergroups'] = 'Filtrar grupos por:';
$string['group'] = 'Grupu';
$string['groupaddedsuccesfully'] = 'Grupu $a amestáu correutamente.';
$string['groupby'] = 'Especificar.';
$string['groupdescription'] = 'Descripción del grupu.';
$string['groupinfo'] = 'Información del grupu seleicionáu.';
$string['groupinfomembers'] = 'Información de los/les miembros seleicionaos.';
$string['groupinfopeople'] = 'Información de les persones seleicionaes';
$string['grouping'] = 'Agrupación';
$string['groupingdescription'] = 'Descripción de l\'agrupación';
$string['groupingname'] = 'Nome de l\'agrupación.';
$string['groupingnameexists'] = 'El nome de l\'agrupación \'$a\' yá esiste nesti cursu, por favor, escueya otru.';
$string['groupings'] = 'Agrupación.';
$string['groupingsonly'] = 'Namás agrupaciones.';
$string['groupmember'] = 'Miembru del grupu';
$string['groupmemberdesc'] = 'Papel(rol) estándar pal miembru d\'un grupu.';
$string['groupmembers'] = 'Miembros del grupu.';
$string['groupmembersonly'] = 'Disponible namás pa los miembros de grupu.';
$string['groupmembersonlyerror'] = 'Tien de ser miembru polo menos d\'un grupu qu\'use esta actividá.';
$string['groupmemberssee'] = 'Ver miembros del grupu';
$string['groupmembersselected'] = 'Miembros del grupu escoyíu.';
$string['groupmode'] = 'Mou del grupu.';
$string['groupmodeforce'] = 'Facer obligatoriu\'l mou del grupu.';
$string['groupmy'] = 'El mio grupu';
$string['groupname'] = 'Nome del grupu';
$string['groupnameexists'] = 'El nome del grupu \'$a\' yá esiste nesti cursu; por favor, escueya otru.';
$string['groupnotamember'] = 'Perdón, nun ye miembru d\'esti grupu.';
$string['groups'] = 'Grupos';
$string['groupscount'] = 'Grupos ($a)';
$string['groupsgroupings'] = 'Grupos &amp; agrupaciones';
$string['groupsinselectedgrouping'] = 'Grupos en agrupaciones escoyíes.';
$string['groupsnone'] = 'Ensin grupos';
$string['groupsonly'] = 'Namás grupos';
$string['groupspreview'] = 'Prever grupos';
$string['groupsseparate'] = 'grupos separtaos';
$string['groupsvisible'] = 'grupos visibles';
$string['grouptemplate'] = 'Grupu @';
$string['hidepicture'] = 'Esconder imaxe';
$string['javascriptrequired'] = 'P\'activar esta páxina necesita Javascript.';
$string['members'] = 'Miembros por grupu.';
$string['membersofselectedgroup'] = 'Miembros del grupu escoyíu.';
$string['namingscheme'] = 'Esquema de nome.';
$string['namingschemehelp'] = 'Use @ pa representar el grupu de lletres (A-Z) o # pa representar el grupu de númberos.';
$string['newgrouping'] = 'Agrupación nueva.';
$string['newpicture'] = 'Imaxe nueva';
$string['noallocation'] = 'Ensin asitiamientu.';
$string['nogroups'] = 'Nun hai grupos actualizaos nesti cursu.';
$string['nogroupsassigned'] = 'Ensin grupos asignaos.';
$string['nopermissionforcreation'] = 'Nun se pue crear el grupu $a: nun tien el permisu necesariu.';
$string['nosmallgroups'] = 'Prevenir grupu pequeñu a la fin';
$string['notingrouping'] = '[Nun ta en nengún grupu]';
$string['nousersinrole'] = 'Nun hai usuarios disponibles col papel(rol) escoyíu.';
$string['number'] = 'Grupu/contar miembros.';
$string['numgroups'] = 'Cantidá de grupos';
$string['nummembers'] = 'Miembros per grupu';
$string['overview'] = 'Descripción.';
$string['potentialmembers'] = 'Miembros potenciales: $a';
$string['printerfriendly'] = 'Visualización amigable d\'impresión pa les agrupaciones.';
$string['random'] = 'Al debalu';
$string['removegroupfromselectedgrouping'] = 'Esborrar un grupu de l\'agrupación escoyida.';
$string['removegroupingsmembers'] = 'Esborrar tolos grupos de les agrupaciones.';
$string['removegroupsmembers'] = 'Esborrar tolos miembros del grupu.';
$string['removeselectedusers'] = 'Esborrar usuarios seleicionaos';
$string['selectfromrole'] = 'Escoyer miembros por papel(rol)';
$string['showgroupsingrouping'] = 'Amosar grupos nel agrupamientu.';
$string['showmembersforgroup'] = 'Amosar miembros del grupu.';
$string['toomanygroups'] = 'Cantidá insuficiente d\'usuarios pa enllenar esta cantidá de grupos - Namás hai $a usuarios nel papel(rol) escoyíu.';
$string['usercount'] = 'Contar usuarios.';
$string['usercounttotal'] = 'Cuenta d\'usuarios ($a)';
$string['usergroupmembership'] = 'Escoyer pertenencia d\'usuarios.';
$string['cancel'] = 'Cancelar'; // ORPHANED
$string['defaultgroupdescription'] = 'Descrición predefinida de grupo'; // ORPHANED
$string['defaultgroupprefix'] = 'Grupo'; // ORPHANED
$string['displaygrouping'] = 'Mostrar agrupamento'; // ORPHANED
$string['distributealphabetically'] = 'Distribuír nos grupos por orde alfabética de apelidos'; // ORPHANED
$string['distributeevenly'] = 'Distribuír equitativamente estudantes que quedaron fóra'; // ORPHANED
$string['editgroupingpermissions'] = 'Editar permisos de agrupamento'; // ORPHANED
$string['errorinvalidgrouping'] = 'Erro, o agrupamento $a non é válido'; // ORPHANED
$string['errornotingrouping'] = 'Non pode crear un grupo en $a'; // ORPHANED
$string['errornotingroupingedit'] = 'Non pode editar un agrupamento en $a'; // ORPHANED
$string['groupfor'] = 'para o grupo'; // ORPHANED
$string['numberofgroups'] = 'Número de grupos'; // ORPHANED
$string['numberofstudents'] = 'Número de estudantes'; // ORPHANED
$string['prefixforgroupnames'] = 'Prefixo dos nomes de grupo'; // ORPHANED
$string['return'] = 'Volver'; // ORPHANED
$string['save'] = 'Gardar'; // ORPHANED
$string['selectnumberineachgroup'] = 'Escoller o número en cada grupo'; // ORPHANED
$string['selectnumberofgroups'] = 'Escoller o número de grupos'; // ORPHANED
$string['showusersalreadyingroup'] = 'Mostrar no agrupamento usuarios que xa estean dentro dun grupo'; // ORPHANED
$string['teachersgroupmark'] = 'Os/As profesores/as non poden marcar grupos aos que non pertenzan'; // ORPHANED
$string['teachersgroupview'] = 'Os/As profesores/as non poden ver actividades dos grupos aos que non pertenzan'; // ORPHANED
$string['teachersoverride'] = 'Os/As profesores/as que non pertencen a ningún grupo poden ver e marcar actividades en todos os grupos (substitúe o anterior)'; // ORPHANED
$string['upgradeconfirm'] = 'As táboas de grupos creadas en Moodle 1.8 dev deben ser eliminadas para realizar esta actualización. Desexa continuar?'; // ORPHANED
$string['usestudentsonlyfromselectedgroup'] = 'Só utilizar estudantes dos grupos seleccionados actualmente'; // ORPHANED
$string['viewallgroupsactivities'] = 'Os/As estudantes poden ver todas as actividades de todos os grupos, mais non poden participar nelas'; // ORPHANED
$string['viewallgroupsmembers'] = 'Os/As estudantes poden ver os/as membros de todos os grupos'; // ORPHANED
$string['viewowngroup'] = 'Os/As estudantes poden ver os/as membros de calquera grupo a que pertenzan'; // ORPHANED
$string['addexistinggroupstogrouping'] = 'Engadir grupos existentes a un agrupamento'; // ORPHANED

?>
