<?PHP // $Id$ 
      // message.php - created with Moodle 1.9.5+ (Build: 20091007) (2007101553)


$string['addcontact'] = 'Amestar contautu';
$string['addsomecontacts'] = 'Pa unviar a daquién un mensaxe, o p\'amestar nesta páxina un atayu que los guie hasta ellos, use\'l <a href=\"$a\">separtador de busca</a>.';
$string['addsomecontactsincoming'] = 'Estos mensaxes son de persones que nun tán nel so llistáu de contautos. P\'amestales, calque l\'iconu \"Amestar contautu\" asitiáu cabu\'l so nome.';
$string['ago'] = 'hai $a';
$string['allmine'] = 'Tolos mensaxes pa min y los unviaos por min';
$string['allstudents'] = 'Tolos mensaxes ente estudiantes del cursu.';
$string['allusers'] = '<br />Tolos mensaxes de tolos usuarios';
$string['backupmessageshelp'] = 'Si ta inactivu, los mensaxes instantáneos inclúyense nes copies de seguridá automátiques del sitiu';
$string['beepnewmessage'] = 'Oyer una señal de la qu\'entra un mensaxe nuevu (Pue que necesite un plugin del navegador pa oyer los soníos, del tipu Quicktime)';
$string['blockcontact'] = 'Bloquear contautu';
$string['blockedmessages'] = '$a mensaxes pa/d\'usuarios bloqueaos';
$string['blocknoncontacts'] = 'Bloquear tolos mensaxes nuevos de persones que nun tean nel mio llistáu de contautos';
$string['contactlistempty'] = 'El so llistáu de contautos ta vacíu.';
$string['contacts'] = 'Contautos';
$string['context'] = 'contestu';
$string['deletemessagesdays'] = 'Cantidá de díes enantes d\'esborrar automáticamente los mensaxes vieyos.';
$string['discussion'] = 'Discutiniu';
$string['emailmessages'] = 'Mensaxes de corréu ellectrónicu de la que nun toi coneutáu/ada';
$string['emailtagline'] = 'Esto corréu ellectrónicu ye copia d\'un mensaxe que-y unviaren en \"$a\"';
$string['emptysearchstring'] = 'Tien de buscar daqué';
$string['formorethan'] = 'Pa más de';
$string['includeblockedusers'] = 'Incluyir usuarios bloqueaos';
$string['incomingcontacts'] = 'Contautos qu\'entran ($a)';
$string['keywords'] = 'Pallabres llave';
$string['keywordssearchresults'] = 'Resultáu de la busca: $a mensaxes encontraos';
$string['mailsent'] = 'El so mensaxe unvióse per corréu ellectrónicu.';
$string['maxmessages'] = 'Cantidá máxima de mensaxes que van apaecer nel historial del discutiniu.';
$string['message'] = 'Mensaxe';
$string['messagehistory'] = 'Historial de mensaxes';
$string['messages'] = 'Mensaxes';
$string['messaging'] = 'Unviando mensaxes';
$string['messagingdisabled'] = 'Unviar mensaxes ta desactiváu nesti sitiu, en vez d\'ello van unviase correos ellectrónicos.';
$string['mycontacts'] = 'Los mios contautos';
$string['newonlymsg'] = 'Amosar namás novedaes';
$string['newsearch'] = 'Busca nueva';
$string['noframesjs'] = 'Versión ensin marcos nin JavaScript';
$string['nomessages'] = 'Ensin mensaxes esperando';
$string['nomessagesfound'] = 'Nun s\'atopó nengún mensaxe';
$string['nosearchresults'] = 'Nun hubo resultaos na so busca.';
$string['offline'] = 'Desconeutáu';
$string['offlinecontacts'] = 'Contautos desconeutaos ($a)';
$string['online'] = 'Coneutáu';
$string['onlinecontacts'] = 'Contautos coneutaos ($a)';
$string['onlyfromme'] = 'Namás mensaxes unviaos por mi.';
$string['onlymycourses'] = 'Namás de los mios cursos.';
$string['onlytome'] = 'Namás mensaxes pa mi.';
$string['pagerefreshes'] = 'Esta páxina actualízase automáticamente cada $a segundos';
$string['readmessages'] = '$a mensaxes lleíos';
$string['removecontact'] = 'Esborrar contautu';
$string['savemysettings'] = 'Guardar la mio configuración.';
$string['search'] = 'Buscar';
$string['searchforperson'] = 'Buscar una persona';
$string['searchmessages'] = 'Buscar nos mensaxes';
$string['sendmessage'] = 'Unviar mensaxe';
$string['sendmessageto'] = 'Unviar mensaxe a $a';
$string['sendmessagetopopup'] = 'Unviar mensaxe a $a - ventanu nuevu.';
$string['settings'] = 'Configuración';
$string['settingssaved'] = 'Guardóse la so configuración';
$string['showmessagewindow'] = 'Amosar automáticamente un ventanu de mensaxe de la que recibo mensaxes nuevos (El restolador tien de tar configuráu de mou y manera que nun bloquie los desplegables d\'esti sitiu)';
$string['strftimedaydatetime'] = '%%A, %%d %%B %%Y, %%I:%%M %%p';
$string['timenosee'] = 'Minutos trescorríos dende a última vez que se lu vio coneutáu/ada.';
$string['timesent'] = 'Tiempu unviáu';
$string['unblockcontact'] = 'Desbloquear contautu';
$string['unreadmessages'] = '$a mensaxes ensin lleer.';
$string['userisblockingyou'] = 'Esti usuariu bloqueólu pa impedir que-y unvíe mensaxes.';
$string['userisblockingyounoncontact'] = 'Esti usuariu namás acepta mensaxes de persones incluyíes nel so llistáu de contautos y usté nun ta nesi llistáu nesti momentu.';
$string['userssearchresults'] = 'Resultáu de la busca: $a usuarios atopaos.';

?>
