<?PHP // $Id$ 
      // moodle.org.php - created with Moodle 1.9.5+ (Build: 20091007) (2007101553)


$string['aboutdemosite'] = 'El nuestru sitiu de demostración ye dafechu usable y tien dellos cursos d\'exemplu que pue probar como mayestru, estudiante o alministrador. Nun tenga mieu d\'equivocase, el sitiu reaníciase cada hora y torna al so estáu orixinal.';
$string['aboutdemositetitle'] = 'Sitiu de Demonstración.';
$string['aboutintro'] = 'Moodle ye un sistema de manexu de cursos de códigu abieru (Open Source Course Management System (CMS) nes sos sigles ingleses), tamién conocíu com Sistema de Manexu del aprendizaxe (Learning Management System (LMS)) o Ambiente Virtual d\'Aprendizaxe (Virtual Learning Environment (VLE)). Ye mui popular ente docentes de tol mundu como ferramienta pa iguar sitios web dinámicos d\'enseñanza \"on line\".  Pa trabayar con él, necesita que lu instale en dalgún servidor d\'internet o nel so ordenador.';
$string['aboutoverview'] = '<p>L\'oxetivu del proyeutu Moodle ye ufiertar a los docentes les meyores ferramientes pa controlar y promocionar l\'aprendizase, pero hai maneres dixebraes d\'usar Moodle:</p>
<ul>
<li>Moodle tien carauterístiques que-y permiten munchos trabayos dixebraos y manexar cientos de miles d\'estudiantes, tamién se pue usar pa educación primaria o cualquier otru usu educativu.</li>
<li>Munches instituciones usen Moodle como plataforma pa los sos cursos, pero otres namás pa completar los sos cursos presenciales.</li>
<li>A Munchos de los nuestros usuarios présta-yos usar los módulos d\'actividaes (del tipu Foros, Wikis, Bases de datos, etc.) pa iguar comunidaes collaboratives d\'aprendizaxe sobre un tema o materia (na mena del construccionismu tradicional) pero otros prefieren usar Moodle como ferramienta pa ufiertar conteníos a los estudiantes (como los paquetes SCORM estándar) y otres tarees como cuestionarios.</li>
</ul>';
$string['aboutoverviewtitle'] = '¿Qué ye Moodle?';
$string['aboutstatistics'] = 'Moodle ye gratis na so descarga y el so rexistru ye voluntariu. Poro, nun tenemos información completa de tol mundu que lu usa. De toles formes, colo que sabemos, facemos automáticamente gráficos y contabilizamos los nuestros datos na nuestra páxina d\'Estadístiques.';
$string['aboutstatisticstitle'] = 'Estadístiques';
$string['browsecvstitle'] = 'Ver el nuestru códigu fonte';
$string['communityintro'] = 'Moodle tien una pergrande y diversa comunidá d\'usuarios d\'unos <a href=\"http://moodle.org/userpics\">$a->usercount usuarios rexistraos</a> col so sitiu Moodle particular, fala unes <a href=\"http://download.moodle.org/lang16/\">$a->langcount llingües</a> en <a href=\"http://moodle.org/sites\">$a->countrycount países</a> (tenemos <a href=\"http://moodle.org/stats\">más estadístiques</a>).';
$string['conferencecenter'] = 'Centru de Conferencia Moodle';
$string['connectedsites'] = 'Dellos sitios Moodle tienen contautao con moodle.org usando Moodle Networking, Usté pue rexistrase y entrar en escribiendo su nome y seña.';
$string['connectedsitestitle'] = 'Sitios Coneutaos';
$string['contactbugs'] = 'Pue informar de problemes en Moodle a cualquier sitiu de la moodle.org describiendo\'l fallu nel Moodle Tracker.';
$string['contactbugstitle'] = 'Informe de Bug';
$string['contactcommunity'] = 'Toles entrugues d\'otru tipu hai que les unviar al Alministrador de la Comuindá Moodle.';
$string['contactintro'] = 'Por favor, escueya ente les opciones de contautu que vienen darréu:';
$string['contactlogin'] = 'Pa cualquier otra entruga, entre nesti sitiu col so nome y seña y use\'l formulariu de contautu que va apecer nesta páxina.';
$string['contactmoodlecom'] = 'Pa cualquier entruga sobre la llicencia, la marca o cuestiones comerciales, igual que pa les rellacionaes con los desenrollos mayor de Moodle, contaute con Información <a href=\"http://moodle.com/\">Moodle.com</a>';
$string['contactmoodlecomhelpdesk'] = 'Información Moodle.com';
$string['contactmoodlecomtitle'] = 'Moodle.com';
$string['contactmoodleorgemail'] = 'Pa problemes de confirmación de la cuenta en moodle.org, unvíe un corréu ellectrónicu a esta direición:';
$string['contactmoodleorglogin'] = 'Entre con nome y seña nesti sitiu';
$string['contactmoodleorgother'] = 'Pa toles demás entrugues, use\'l formulariu que vien darréu.';
$string['contactmoodleorgtitle'] = 'Moodle.org';
$string['contactsecurity'] = 'Cuestiones de seguridá puen unviase pel Tracker, lo que consigue caltener un nivel de seguridá apropiáu.';
$string['contactsent'] = 'El so mensaxe unvióse por corréu ellectrónicu al Alministrador de la Comunidá Moodle.';
$string['contactsupport'] = 'Pa entrugues de cómo usar Moodle, mire les nuestres páxines d\'ayuda nes que pue atopar munchos retruques y soluciones.';
$string['contactsupporttitle'] = 'Ayuda';
$string['developercontributors'] = 'Creditos';
$string['developerlist'] = 'Llistáu completu de desarrolladores con nivel d\'accesu d\'escritura';
$string['developermeetings'] = 'Reuniones de Desarrolladores';
$string['developers'] = 'El desendolcu principal de Moodle llévalu un equipu en Moodle.com, ayudáu por cientos d\'otros desarrolladores de tol mundu. Munchos d\'ellos son tamién los responsables principales de módulos y plugins.';
$string['developerstitle'] = 'Desarrolladores';
$string['developmentdocs'] = 'Lo principal de la nuestra documentación atópase en Moodle Docs - incluyíes especificaciones, idees, maneres de facer, estándares y guíes d\'usuariu acabaes.';
$string['developmentdocstitle'] = 'Documentación de desarrollador';
$string['developmentintro'] = 'Naguamos por desendolcu tresparente y abiertu qu\'anime a tola comunidá a participar. Damos la bienvenida a tolos programadores de PHP, pero tamién a tolos demás que puen ayudar con opiniones, comprobaciones de funcionamientu, cambios d\'impresiones, documentación o cualquier otro que pueda aportar.';
$string['developmenttracker'] = 'Tolo que cinca al desendolcu (bugs, nueves capacidaes, meyoramientos) grábase y queda rexistrao nel Moodle Tracker. Pue ver quién ta trabayando y en qué y, con ello, ayudar con cualquier comentariu en cualquier discutiniu. Pue buscar nel tracker si anda tres dalgún datu o capacidá específicos y, por favor, ayúdenos col so <strong>votu</strong> pa saber qué carauterístiques quier, n\'especial, que se revisen, porque col so votu determinamos les prioridaes de desendolcu.';
$string['donations'] = 'Moodle ye gratis y nun tien nenguna llende económica. De toles maneres, muncha xente tien donao daqué al proyeutu pa facer que los desendolcadores trabayen más agustu.';
$string['donationstitle'] = 'Donaciones';
$string['downloadcore'] = 'El nuestru métodu de distribución por defeutu ye por paquetes estándar. Nellos alcuéntrense dellos módulos calteníos polos desarrolladores principales y ye conveniente instalalos en cualquier plataforma siempre que tenga PHP y una base de datos yá instalada.';
$string['downloadcoretitle'] = 'Paquetes Moodle estándar';
$string['downloadcvs'] = 'Otra manera de consiguir el códigu fonte ye usar CVS y coneutase direutamente a ún de los nuestros espeyos nos que se guarda el códigu qu\'usen los desarrolladores de Moodle. Esta manera convierte\'l procesu d\'actualización en percenciellu, inclusu si tien fechos cambios pa la so instalación particular de Moodle.';
$string['downloadcvstitle'] = 'Moodle via CVS';
$string['downloadintro'] = 'Moodle ye códigu abiertu según la <a href=\"http://docs.moodle.org/en/License\">Llicencia GPL </a>.  Tolo que facemos pue baxase y usase gratis.';
$string['downloadlang'] = 'Nes actuales versiones de Moodle, amestar ayuda pa llingües nueves ye un procesu automáticu que se pue activar dende\'l menu d\'alministración del so sitiu. De toles formes, en delles versiones más vieyes, los paquetes d\'idioma hai que los baxar manualmente.';
$string['downloadlangtitle'] = 'Paquetes de Llingua';
$string['downloadlogotitle'] = 'Logos de Moodle';
$string['downloadmac'] = 'Si entá nun tien un servidor web, estos paquetes de Too Nuno puen facer que seya fácil instalar Moodle en cualquier ordenador Apple que tenga Mac OS X.';
$string['downloadmactitle'] = 'Moodle pa Mac OS X';
$string['downloadmodules'] = 'Navegue pela nuestra base de datos de modulos y plugins qu\'ufiertamos dende\'l sitiu web y que puen amestase al so sitiu web pa consiguir más funcionalidá que la que dan los paquetes principales.';
$string['downloadmodulestitle'] = 'Modulos y plugins';
$string['downloadthemes'] = 'L\'apariencia d\'un sitiu Moodle pue cambiase completamente usando un tema distintu. Tenemos una base de datos de temes que los usuarios ficieren y comparten.';
$string['downloadthemestitle'] = 'Temes';
$string['downloadwin'] = 'Si entá nun tien un servidor web preparáu, estos paquetes Too Nuno puen facer fácil instalar Moodle en cualquier ordenador con Microsoft Windows.';
$string['downloadwintitle'] = 'Moodle pa Windows';
$string['events'] = 'Magar tamos especializaos na enseñanza online, ¡préstanos facer reuniones pa venos la cara!  Eche una güeyada nesti enllaz pa informase de les nuestres renuniones (llamámosles MoodleMoots) y otros acontecimientos.';
$string['eventstitle'] = 'Acontecimientos';
$string['frontpagewelcome1'] = 'Moodle ye un Sistema de Manexu de Cursos (CMS nes sos sigles n\'inglés), tamién conocíos como Sistema de Manexu d\'Enseñanza (LMS nes sos sigles n\'inglés) o Llugar d\'Enseñanza Virtual (VLE ne sos sigles n\'inglés).  Ye una aplicación Gratuita que los docentes puen usar pa iguar llugares d\'aprendizaxe online eficientes.';
$string['frontpagewelcome2'] = 'Moodle.org ye el nuestru sitiu comunitariu, nel que Moodle se fabrica y discute.  Por favor, use los menús pa visitalu y ¡que-y preste!';
$string['frontpagewelcometitle'] = '¡Bienveníu a la comunidá Moodle!';
$string['generaldeveloperforum'] = 'Foru de desendolcu xeneral';
$string['jobs'] = 'Visite la nuestra base de datos de los trabayos pa conocer información sobre la posición de Moodle n\'Internet.';
$string['jobstitle'] = 'Trabayos de Moodle';
$string['moodlecertification'] = 'Certificación de Moodle';
$string['moodleconsulting'] = 'Asesoría de Moodle';
$string['moodlecourseware'] = 'Cursos de Moodle';
$string['moodlecustomisation'] = 'Personalización de Moodle';
$string['moodledocs'] = 'Docs de Moodle';
$string['moodlehosting'] = 'Agospiamientu de Moodle';
$string['moodleinstallation'] = 'Instalación de Moodle';
$string['moodleintegrations'] = 'Integraciones de Moodle';
$string['moodlesupport'] = 'Ayuda de Moodle';
$string['moodlethemes'] = 'Temes de Moodle';
$string['moodletrackertitle'] = 'Moodle Tracker';
$string['moodletraining'] = 'Entrenando con Moodle';
$string['mycoursesintro'] = 'Ta matriculáu/ada nestos \"cursos\" d\'esta comunidá, caún d\'ellos tien ún o más foros.';
$string['nameabout'] = 'Al rodiu de';
$string['nameaboutmoodle'] = 'All rodiu de Moodle';
$string['namecommercial'] = 'Servicios comerciales';
$string['namecommunity'] = 'Comunidá';
$string['namecontact'] = 'Contáutu';
$string['namedevelopment'] = 'Desendolcu';
$string['namedocumentation'] = 'Documentación';
$string['namedownloads'] = 'Descargues';
$string['nameevents'] = 'Eventos';
$string['nameforums'] = 'Foros';
$string['namehome'] = 'Páxina d\'entamu';
$string['namemycourses'] = 'Los mios cursos';
$string['namenetwork'] = 'Sitios coneutaos';
$string['namenews'] = 'Noticies';
$string['namesecurity'] = 'Noticies de seguridá';
$string['namesupport'] = 'Ayuda';
$string['networkintro'] = 'Los sitios Moodle que vienen darréu coneutárense a moodle.org usando Moodle networking, polo que pue entrar nellos direutamente dende equí.';
$string['newsbuzz'] = 'Pitíu Moodle';
$string['newsbuzzdetail'] = 'Publicaciones sobre Moodle en tol mundu';
$string['newscalendar'] = 'Calendariu';
$string['newscalendardetail'] = 'Futuros eventos Moodle.';
$string['newsofficial'] = 'Official news about Moodle';
$string['newsplanet'] = 'Planeta Moodle';
$string['newsplanetdetail'] = 'Blogs de los desarrolladores de Moodle amestaos';
$string['newsrecent'] = 'Noticies recientes';
$string['newssecurity'] = 'Noticies de seguridá';
$string['newssecuritydetail'] = 'Información importante sobre problemes de seguridá.';
$string['noenrolledcoursesyet'] = 'Nun ta matriculáu en nengún cursu.';
$string['overview'] = 'Güeyada';
$string['overviewabout'] = 'Una güeyada a Moodle';
$string['overviewcommunity'] = 'Una güeyada a la comunidá Moodle';
$string['overviewdevelopment'] = 'Una güeyada al desendolcu Moodle';
$string['overviewdownloads'] = 'Una güeyada a les descargues Moodle';
$string['overviewmy'] = 'Ver tolos cursos de moodle.org nos que ta matriculáu/ada.';
$string['overviewnews'] = 'Una güeyada a les noticies más nueves de Moodle.';
$string['overviewsupport'] = 'Una güeyada a les opciones d\'ayuda de Moodle.';
$string['popularissues'] = 'Carauterístiques más populares';
$string['recentpart'] = 'Esta páxina enseña della xente qu\'anguaño usa moodle.org.';
$string['recentparttitle'] = 'Participantes recientes';
$string['registeredsites'] = 'Les Instituciones nun tienen necesidá d\'informar de que tan usando Moodle, Moodle ye códigu abiertu.  De toles formes, dellos sitios Moodle prefirieren rexistrase y con ellos ficimos un llistáu.';
$string['registeredsitestitle'] = 'Sitios rexistraos.';
$string['roadmap'] = 'Mapa de ruta Moodle';
$string['shop'] = '¿Ta buscando una manera d\'amosar que ye parte de la nuestra comunidá?  Eche una güeyada a la nuestra tienda de camisetes, taces y otru tipu d\'oxetos.';
$string['shoptitle'] = 'Tienda Moodle';
$string['sourcecodetitle'] = 'Códigu abiertu';
$string['supportbooks'] = 'Tenemos un llistáu actualizáu de llibros que se puen comprar sobre Moodle.';
$string['supportbookstitle'] = 'Llibros y manuales';
$string['supportcommercial'] = 'Los <a href=\"http://moodle.com/\">Patrocinadores Moodle</a> son un grupu de compañíes de tol mundu que tienen autorización pa usar la marca Moodle de manera comercial y que contribuyen finacieramente nel desendolcu del proyeutu de Códigu Abiertu Moodle. Dan una serie de servicios de tipu comercial a tolos usuarios Moodle del mundu:';
$string['supportcommercialtitle'] = 'Servicios comerciales';
$string['supportdocs1'] = 'Docs de Moodle ye un bon llugar pa entamar, n\'especial nes Entrugues Más Frecuentes (FAQ).';
$string['supportdocs2'] = 'Una bona manera d\'atopar documentación importante ye usar \"Documentos Moodle pa esta páxina\" (Moodle Docs for this page n\'nglés) nel enllaz col que se pue dar na parte d\'embaxo de cualquier páxina Moodle.';
$string['supportdocsfaq'] = 'Entrugues Más Frecuentes';
$string['supportdocslang'] = 'documentos Moodle n\'otres llingües.';
$string['supportdocstitle'] = 'Documentación';
$string['supportforums'] = 'La nuestra comunidá d\'usuarios aveza comunicase mediante los foros de dientro los \"cursos\" del so sitiu Moodle. Tien de \"matriculase\" nel cursu pa poder escribir nos foros (la matriculación ye gratis).';
$string['supportforumsenglish'] = 'L\'ayuda principal y los discutinios ente desarrolladores y usuarios ta n\'inglés equí:';
$string['supportforumsenglishname'] = 'Usar Moodle';
$string['supportforumslang'] = 'The llave del foru pa Moodlers si se quier socializar n\'inglés ta equí:';
$string['supportforumslangname'] = 'Sala de tar Moodle';
$string['supportforumslangurl'] = 'http://moodle.org/course/view.php?id=55';
$string['supportforumslist'] = 'Tenemos otros foros, n\'otres llingües:';
$string['supportforumslistname'] = 'Llistar tolos foros';
$string['supportforumstitle'] = 'Foros';
$string['supportintro'] = '¡Nun ta solu/a!  Hai munches maneres de consiguir ayuda si la necesita.';

?>
