<?PHP // $Id$ 
      // group.php - created with Moodle 1.9.2+ (Build: 20080813) (2007101521)


$string['adduserstogroup'] = 'Bæta við eða fjarlægja notendur';
$string['backtogroups'] = 'Aftur í hópa';
$string['creategroup'] = 'Mynda hóp';
$string['databaseupgradegroups'] = 'Útgáfa hópa er núna $a';
$string['defaultgroupname'] = 'Hópur';
$string['deleteallgroupings'] = 'Eyða öllum hópaskiptingum';
$string['deleteallgroups'] = 'Eyða öllum hópum';
$string['deletegroupconfirm'] = 'Viltu örugglega eyða hópnum \'$a\'?';
$string['deleteselectedgroup'] = 'Eyða völdum hóp';
$string['editgroupsettings'] = 'Breyta uppsetningu hópa';
$string['enrolmentkey'] = 'Skráningarlykill';
$string['erroraddremoveuser'] = 'Villa kom upp þegar reynt var að bæta við eða fjarlægja notandann $a úr hóp.';
$string['erroreditgroup'] = 'Villa kom upp þegar reynt var að búa til eða uppfæra hópinn $a';
$string['errorinvalidgroup'] = 'Villa, ótækur hópur: $a';
$string['existingmembers'] = 'Núverandi meðlimir';
$string['filtergroups'] = 'Sía hópa eftir:';
$string['group'] = 'Hópur';
$string['groupaddedsuccesfully'] = 'Hópnum $a var bætt við';
$string['groupby'] = 'Tilgreina';
$string['groupdescription'] = 'Lýsing á hóp';
$string['groupinfo'] = 'Upplýsingar um valinn hóp';
$string['groupinfomembers'] = 'Upplýsingar um valda meðlimi';
$string['groupinfopeople'] = 'Upplýsingar um valda notendur';
$string['groupmember'] = 'Meðlimur hóps';
$string['groupmemberdesc'] = 'Sjálfgefið hlutverk fyrir meðlim hóps.';
$string['groupmembers'] = 'Meðlimir hóps';
$string['groupmembersonly'] = 'Einungis aðgengilegt meðlimum hóps';
$string['groupmemberssee'] = 'Sýna meðlimi hóps';
$string['groupmembersselected'] = 'Meðlimir valins hóps';
$string['groupmode'] = 'Hópahamur';
$string['groupmodeforce'] = 'Skilyrða hópaham';
$string['groupmy'] = 'Minn hópur';
$string['groupname'] = 'Heiti hóps';
$string['groupnotamember'] = 'Því miður, þú ert ekki meðlimur í þeim hópi.';
$string['groups'] = 'Hópar';
$string['groupscount'] = 'Hópar ($a)';
$string['groupsinselectedgrouping'] = 'Hópar í:';
$string['groupsnone'] = 'Engir hópar';
$string['groupsonly'] = 'Einungis hópar';
$string['groupsseparate'] = 'Aðskildir hópar';
$string['groupsvisible'] = 'Sýnilegir hópar';
$string['hidepicture'] = 'Fela mynd';
$string['javascriptrequired'] = 'Vefsíðan krefst þess að Javascript sé virkjað.';
$string['membersofselectedgroup'] = 'Meðlimir hóps';
$string['newpicture'] = 'Ný mynd';
$string['potentialmembers'] = 'Hugsanlegir meðlimir: $a';
$string['printerfriendly'] = 'Prentvæn útgáfa';
$string['removegroupsmembers'] = 'Tæma alla hópa';
$string['removeselectedusers'] = 'Fjarlægja valda notendur';
$string['showmembersforgroup'] = 'Birta meðlimi hóps';
$string['cancel'] = 'Hætta við'; // ORPHANED
$string['defaultgroupdescription'] = 'Sjálfgefin lýsing á hóp'; // ORPHANED
$string['defaultgroupprefix'] = 'Hópur'; // ORPHANED
$string['errornotingrouping'] = 'Því miður, ekki er hægt að búa til hóp í $a'; // ORPHANED
$string['groupfor'] = 'fyrir hóp'; // ORPHANED
$string['numberofgroups'] = 'Fjöldi hópa'; // ORPHANED
$string['numberofstudents'] = 'Fjöldi nemenda'; // ORPHANED
$string['prefixforgroupnames'] = 'Forskeyti fyrir nöfn hópa'; // ORPHANED
$string['return'] = 'Til baka'; // ORPHANED
$string['save'] = 'Vista'; // ORPHANED
$string['selectnumberineachgroup'] = 'Veldu fjölda í hverjum hóp'; // ORPHANED
$string['selectnumberofgroups'] = 'Veldu fjölda hópa'; // ORPHANED
$string['teachersgroupmark'] = 'Kennarar geta ekki gefið hópum sem þeir tilheyra ekki einkunnir'; // ORPHANED
$string['teachersgroupview'] = 'Kennarar geta ekki skoðað viðföng hópa sem þeir tilheyra ekki'; // ORPHANED
$string['upgradeconfirm'] = 'Því miður, eyða verður hópatöflum sem myndaðar voru í Moodle 1.8 DEV. Viltu halda áfram?'; // ORPHANED
$string['viewallgroupsactivities'] = 'Nemendur geta séð en ekki tekið þátt í viðfangsefnum allra hópa'; // ORPHANED
$string['viewallgroupsmembers'] = 'Nemendur geta séð meðlimi í öllum hópum'; // ORPHANED
$string['viewowngroup'] = 'Nemendur geta séð meðlimi í öllum hópum sem þeir sjálfir tilheyra'; // ORPHANED

?>
