<?PHP


$string['accessdenied'] = 'ވަނުން މަނާ';
$string['accounts'] = 'އެކައުންޓުތައް';
$string['adminseesall'] = 'އެޑުމިނިސްޓުރޭޓާއަށް ހުރިހާ އެއްޗެއް ފެންނާނެ';
$string['adminseesallevents'] = 'އެޑުމިނިސްޓުރޭޓާއަށް ހުރިހާ ކަމެއް ފެންނާނެ';
$string['adminseesownevents'] = 'އެހެން ޔޫސަރުންނާއި އެޑުމިނިސްޓުރޭޓާއާއި ހަމަހަމަ';
$string['allowcategorythemes'] = 'ކެޓަގަރީ ތީމުތައް ހުއްދަކުރޭ';
$string['allowcoursethemes'] = 'ކޯސް ތީމުތައް ހުއްދަކުރޭ';
$string['allowdeletes'] = 'ފޮހުން ހުއްދަކުރޭ';
$string['allowemailaddresses'] = 'އީމެއިލ ޑޮމެއިންތައް ހުއްދަކުރޭ';
$string['allowobjectembed'] = 'EMBED އަދި OBJECT ޓެގުތައް ހުއްދަކުރޭ';
$string['allowrenames'] = 'އަލުން ނަން ދިނުން ހުއްދަކުރޭ';
$string['allowuserblockhiding'] = 'ޔޫސަރުންނަށް ބުލޮކުތައް ފޮރުވުން ހުއްދަކުރޭ';
$string['allowusermailcharset'] = 'ޔޫސަރުންނަށް އަކުރު ސެޓު ނެގުން ހުއްދަކުރޭ';
$string['allowuserswitchrolestheycantassign'] = 'ވަކި ރޯލުތަކެއް ކަނޑައެޅިފައިނުވާ ޔޫސަރުންނަށް ރޯލު ބަދަލުކުރުން ހުއްދަކުރޭ';
$string['allowuserthemes'] = 'ޔޫސަރުންގެ ތީމުތައް ހުއްދަކުރޭ';
$string['allowvisiblecoursesinhiddencategories'] = 'ފޮރުވިފައިވާ ކެޓަގަރީ ތަކުގައިވާ ފެންނަ ކޯސްތައް ހުއްދަކުރޭ';
$string['antivirus'] = 'އެންޓި ވައިރަސް';
$string['appearance'] = 'ފެންނަ ގޮތް';
$string['aspellpath'] = 'ސުޕެލްކުރަންވީ ޕާތު';
$string['authentication'] = 'ސައިޓަށް ވަނުމުގެ އިންތިޒާމު';
$string['authsettings'] = 'ސައިޓަށް ވަނުމުގެ އިންތިޒާމު ބަލަހައްޓާ';
$string['autolang'] = 'ބަސް އޮޓޯއިން ދެނެގަނޭ';
$string['autologinguests'] = 'ގެސްޓުން އޮޓޯއިން ލޮގިންކުރޭ';
$string['availablelangs'] = 'ލިބެންހުރި ބަސް ޕެކުތައް';
$string['backgroundcolour'] = 'އެތެރެފެންނަ ކުލަ';
$string['backups'] = 'ބެކަޕުތައް';
$string['badwordsconfig'] = 'ވިޔާނުދާ ބަސްތަކުގެ ލިސްޓު ކޮމާއިން ވަކިކޮށް ލިޔާށެވެ.';
$string['badwordsdefault'] = 'އަމިއްލަ ލިސްޓު ހުސްނަމަ ބަސް ޕެކުގައިވާ ލިސްޓެއް ބޭނުންކުރެވޭނެއެވެ.';
$string['badwordslist'] = 'އަމިއްލަ ވިޔާނުދާ ބަސްތަކުގެ ލިސްޓު';
$string['blockinstances'] = 'އެއްޗެހިތައް';
$string['blockmultiple'] = 'ގިނަ';
$string['blocksettings'] = 'ބުލޮކުތައް ބަލަހައްޓާ';
$string['bloglevel'] = 'ބުލޮގު ދެއްކުމާއި ނުދެއްކުން';
$string['bookmarkadded'] = 'ބުކްމާކު އިތުރުކުރެވިއްޖެ';
$string['bookmarkalreadyexists'] = 'މި ސަފުހާ މިހާރުވެސްވަނީ ބުކްމާކު ކުރެވިފައި';
$string['bookmarkdeleted'] = 'ބުކްމާކު ފޮހެލެވިއްޖެ';
$string['bookmarkthispage'] = 'މި ސަފުހާ ބުކްމާކުކުރޭ';
$string['cachetext'] = 'ލިޔުންކޮޅު މެމޮރީގައި ހުންނަ ވަގުތު';
$string['cachetype'] = 'މެމޮރީގެ ވައްތަރު';
$string['calendar_weekend'] = 'ހަފުތާ ނިމޭ ދުވަސްތައް';
$string['calendarexportsalt'] = 'ކަލަންޑަރު އެކްސްޕޯޓޫ ؟؟؟';
$string['calendarsettings'] = 'ކަލަންޑަރު';
$string['cfgwwwrootslashwarning'] = 'config.php ފައިލުގައި &#36;CFG->wwwroot ވަނީ ނުބައިކޮށް ހެދިފައެވެ. އޭގެ ފަހަތުގައި \'/\' ފަދަ ކެރެކްޓާއެއްލިޔެފައިވެއެވެ. އެ ކެރެކްޓާ ފޮހެލާށެވެ. ނޫންނަމަ <a href=\'http://tracker.moodle.org/browse/MDL-11061\'>MDL-11061</a> ފަދަ ބަގުތައް ކުރިމަތިވާނެއެވެ.';
$string['cfgwwwrootwarning'] = 'config.php ފައިލުގައި &#36;CFG->wwwroot ވަނީ ނުބައިކޮށް ހެދިފައެވެ. އެއާއި މި ސަފުހާއަށް ވަނުމަށް ބޭނުންކުރާ URL އަކާއި ދިމައެއް ނުވެއެވެ. މިކަން ރަނގަޅުކުރާށެވެ. ނޫންނަމަ <a href=\'http://tracker.moodle.org/browse/MDL-11061\'>MDL-11061</a> ފަދަ ބަގުތައް ކުރިމަތިވާނެއެވެ.';
$string['change'] = 'ބަދަލުކުރޭ';
$string['changesitelang'] = 'ސައިޓުގެ ބަސް ބަދަލުކުރޭ';
$string['checkboxno'] = 'ނޫން';
$string['checkboxyes'] = 'އާނ';
$string['choosefiletoedit'] = 'ބަދަލުކުރަންވީ ފައިލު ނަގާ';
$string['cleanup'] = 'ސާފުކުރޭ';
$string['commonsettings'] = 'އާއްމު ސެޓިންތައް';
$string['componentinstalled'] = 'ކޮމްޕޮނެންޓު އިންސްޓޯލުކުރެވިއްޖެ';
$string['computedfromlogs'] = '$a ހަމައަށްވާ ލޮގުތަކުން ހިސާބުހެދިފައި';
$string['confeditorhidebuttons'] = 'HTML އެޑިޓަރުގައި ފޮރުވަންވީ ބަޓަންތައް ނަގާ';
$string['configallowassign'] = 'ވާއަތް ފަޅީގައިވާ ރޯލުތައްހުރި މީހުންނަށް އެ ކޮލަމުގައިވާ ބައެއް ރޯލުތައް އެހެން މީހުންނަށް ކަނޑައެޅުމުގެ ހުއްދަދެވިދާނެއެވެ.';
$string['configallowcategorythemes'] = 'މިތަން އެންއޭބަލް ކޮށްފިނަމަ ތީމުތައް ސެޓުކުރެވޭނީ ކެޓަގަރީ ލެވެލުންނެވެ. މިހެންވުމުން ކެޓަގަރީގެ ދަށުގައިވާ ކެޓަގަރީތަކާއި ކޯސްތަކަށް، ވަކިވަކިން އެތަކެއްޗަށް އަމިއްލަ ތީމުތަކެއް ސެޓުކޮށްފައިނުވާނަމަ، މިކަމުގެ އަސަރުކުރާނެއެވެ. އިންޒާރު: ކެޓަގަރީ ތީމުތައް އެންއޭބަލް ކުރުމުން މަސައްކަތުގެ ސްޕީޑަށް ނޭދެވޭ އަސަރުކުރާނެއެވެ.';
$string['configallowcoursethemes'] = 'މިތަން އެންއޭބަލް ކޮށްފިނަމަ ކޯސްތަކަށް އަމިއްލަ ވަކި ތީމުތައް ސެޓުކުރެވޭނެއެވެ. ކޯސް ތީމުތަކުން އެހެން ހުރިހާ ތީމުތަކެއް (ސައިޓު، ޔޫސަރު ނުވަތަ ސެޝަން ތީމުތައް) ބަދަލުކުރާނެއެވެ.';
$string['configallowemailaddresses'] = 'ވަކި ޑޮމެއިންއަކަށްވާ އައުއީމެއިލު އެޑުރެސްތައް މަނާކުރަން ބޭނުންނަމަ، އެ ޑޮމެއިންތައް، ކޮމާއިން ވަކިކޮށް، ލިސްޓުކުރާށެވެ. އެހެން ހުރިހާ ޑޮމެއިންތަކެއް ދޫކޮށްލެވޭނެއެވެ. ސަބުޑޮމެއިންތައް ހުއްދަކުރުމަށް އެ ޑޮމެއިންއެއްގެ ފަހަތުގައި \'.\' އިތުރުކުރާށެވެ. މިސާލަކަށް: <strong>ourcollege.edu.au .gov.au</strong>';
$string['configallowobjectembed'] = 'ޑީފޯލްޓު ސެކިއުރިޓީ މެޝާއެއްގެ ގޮތުން އާދައިގެ ޔޫސަރުންނަކަށް އެމީހުންގެ ލިޔުންތަކުގައި މަލްޓީމީޑިއައު(ފުލެޝް ކަހަލަ) އެކްސްޕުލިސިޓު EMBED އަދި OBJECT ޓެގުތައް HTML ގައި ބޭނުންކުރުން ހުއްދައެއް ނުކުރެވޭނެއެވެ. ނަމަވެސް މި ކަންތައް މީޑިއައުޕުލަގިން ފިލްޓަރުގެ އެހީގައި ސަލާމަތްތެރިކަމާއިއެކު ކުރެވޭނެއެވެ. އެ ކަހަލަ ޓެގުތައް ބޭނުންކުރުން ހުއްދަކުރުމަށް މިތަން އެންއޭބަލް ކުރާށެވެ.';
$string['configallowoverride'] = 'ވާއަތް ފަޅީގައިވާ ރޯލުތައްހުރި މީހުންނަށް އެ ކޮލަމުގައިވާ ބައެއް ރޯލުތައް ބަދަލުކުރުމުގެ ހުއްދަދެވިދާނެއެވެ.';
$string['configallowoverride2'] = 'ވާއަތް ފަޅީގައިވާ ރޯލުތަކުގެތެރެއިން ބަދަލުކުރެވޭނެ ރޯލު(ތައް) ނަގާށެވެ. <br />ނޯޓު: މި ސެޓިންތައް ބޭނުންވާނީ ހަމައެކަނި moodle/role:override ނުވަތަ moodle/role:safeoverride ހުއްދަވާ ޔޫސަރުންނަށެވެ.';
$string['configallowunenroll'] = 'މިތަން \'އާނ\' އަށް ސެޓުކޮށްފިނަމަ ދަރިވަރުންނަށް އެ ދަރިވަރުން ބޭނުންއިރަކު ކޯހުން ވަކިވުމުގެ އިޚުތިޔާރު އޮންނާނެއެވެ. އެހެންނޫންނަމަ އެ އިޚުތިޔާރެއް ނޯންނާނެއެވެ. އަދި އެކަންތައް ކުރެވޭނީ ހަމަ އެކަނި މުދައްރިސުންނަށް ނުވަތަ އެޑުމިނިސްޓުރޭޓާއަށެވެ.';
$string['configallowuserblockhiding'] = 'މި ސައިޓުގެ ހުރިހާ ހިސާބެއްގައި އަރިމަތީގައިވާ ބުލޮކުތައް ޔޫސަރުންނަށް ފޮރުވާ ދެއްކުން ހުއްދަކުރަން ބޭނުންތަ؟ މިކަމަށް Javascript އާއި ކުކީޒް ބޭނުންކުރާނެއެވެ. އެއީ ފޮރުވޭ ކޮންމެ ބުލޮކެއްގެ ހާލަތު ހަނދާންކުރުމަށެވެ. އަދި މިކަމުގެ އަސަރުކުރާނީ ހަމައެކަނި އެ ޔޫސަރެއްގެ އަމިއްލަ ބަޔަށެވެ.';
$string['configallowusermailcharset'] = 'މިތަން އެންއޭބަލް ކޮށްފިނަމަ މި ސައިޓުގައިވާ ކޮންމެ ޔޫސަރަކަށް އީމެއިލުގައި ބޭނުންކުރުމަށް އެމީހެއްގެ އަމިއްލަ އަކުރު ސެޓެއް ކަނޑައެޅިދާނެއެވެ.';
$string['configallowuserswitchrolestheycantassign'] = 'ޑީފޯލްޓުކޮށް moodle/role:assign އިން ޔޫސަރުންނަށް އެމީހުންގެ ރޯލު ބަދަލުކުރަން ޖެހޭނެއެވެ. މި ސެޓިން އެންއޭބަލް ކުރުމުން ރޯލު ބަދަލުކުރާކަށް ނުޖެހޭނެއެވެ. އަދި \"ރޯލު ބަދަލުކުރުމަށް\" ޑުރޮޕުޑައުން ބޮކްސްއިން ރޯލު ނެގެން ހުންނާނެއެވެ. އަދި މިކަން ކަނޑައަޅާނީ ހަމައެކަނި \"ރޯލު ދިނުން ހުއްދަކުރާ\" ޓޭބަލުގައިވާ ސެޓިންތަކުންނެވެ. \"ރޯލު ދިނުން ހުއްދަކުރާ\" ޓޭބަލުގައިވާ ސެޓިންތައް ހުރުން އެދެވިގެންވަނީ އެ ޔޫސަރެއްގެ ރޯލަށްވުރެ މަތީގައިވާ ރޯލަކާއި ބަދަލު ނުކުރެވޭނެ ގޮތަށެވެ.
It is recommended that the settings in the \"Allow role assignments\" table do not allow users to switch to a role with more capabilities than their existing role.';
$string['configallowuserthemes'] = 'މިތަން އެންއޭބަލް ކޮށްފިނަމަ ޔޫސަރުންނަށް އަމިއްލަ ވަކި ތީމުތައް ސެޓުކުރެވޭނެއެވެ. ޔޫސަރު ތީމުތަކުން އެހެން ހުރިހާ ތީމުތަކެއް (ކޯސް ތީމުތައް ފިޔަވައި) ބަދަލުކުރާނެއެވެ.';
$string['configallusersaresitestudents'] = 'މި ސައިޓުގެ ފުރަތަމަ ސަފުހާގައިވާ އެކްޓިވިޓީތަކަށް ހުރިހައި ޔޫސަރުން ބަލަންވީ އެއީ ދަރިވަރުންކަމަށްތަ؟ ޖަވާބަކީ \"އާނ\" ނަމަ ކޮންފާމުވެފައިވާ ހުރިހައި ޔޫސަރުންނަށް ދަރިވަރެއްގެ ގޮތުގައި މި އެކްޓިވިޓީގައި ބައިވެރިވުމުގެ ހުއްދަ އޮންނާނެއެވެ. ޖަވާބަކީ \"ނޫން\" ނަމަ މި އެކްޓިވިޓީގައި ބައިވެރިވެވޭނީ ހަމައެކަނި މަދުވެގެން އެއް ކޯހުގެ ބައިވެރިވެފައިވާ ޔޫސަރުންނަށް އެކަންޏެވެ. މި ފުރަތަމަ ސަފުހާގައިވާ އެކްޓިވިޓީތަކުގައި މުދައްރިސުންގެ ގޮތުގައި ހަރަކާތްތެރިވެވޭނީ ހަމައެކަނި ހާއްސަކޮށް ކަނޑައެޅިފައިވާ މުދައްރިސުންނަށް ނުވަތަ އެޑުމިނިސްޓުރޭޓާއަށެވެ.';
$string['configauthenticationplugins'] = 'ބޭނުންކުރަން ބޭނުންވާ އޯތެންޓިކޭޝަން ޕުލަގިންތައް ނަގާށެވެ. އަދި އެއް ޕުލަގިން ފެއިލްވުމުން ދެން ބޭނުންކުރާނެ ޕުލަގިންގެ ތަރުތީބުން ޕުލަގިންތައް ތަރުތީބުކުރާޭވެ.';
$string['configautolang'] = 'ބުރައުސަރުގެ ސެޓިންތަކުން ޑީފޯލްޓު ބަސް ނަގާށެވެ. ޑިސްއޭބަލް ކޮށްފިނަމަ ސައިޓުގެ ޑީފޯލްޓު ބަސް ބޭނުންކުރެވޭނެއެވެ.';
$string['configautologinguests'] = 'ގެސްޓުންނަށް ހުއްދަދެވިފައިވާ ކޯސްތަކަށް ވިސިޓަރުން ވަންނައިރު އޮޓޯއިން އެމީހުންނަކީ ގެސޓުންގެ ގޮތުގައި ލޮގިންކުރަންވީތަ؟';
$string['configbloglevel'] = 'މި ސެޓިން ބޭނުންކޮށްގެން ސައިޓުގައި ޔޫސަރުންގެ ބުލޮގު ބެލުމުގެ މިންވަރު މަނާކުރެވޭނެއެވެ. ނޯޓު: ބުލޮގު ބަލާ މީހުންގެ (ބުލޮގު ޕޯސްޓުކުރާ މީހާ ނުވަތަ ބުލޮގު ޕޯސްޓުތަކުގެ ވައްތަރުތަކުގެއެއް ނޫން) ގިނަ އަދަދު ކަނޑައެޅިފައިވާން ޖެހޭނެއެވެ. އަދި ބުލޮގު އެއްވެސް ވަރަކަށް ބޭނުން ނޫންނަމަ އެ ބުލޮގެއް ހަމަ މުޅިން ޑިސްއޭބަލް ކުރެވިވެސްދާނެއެވެ.';
$string['configcachetext'] = 'މި ސެޓިން ބޭނުންކޮށްގެން ބޮޑެތި ސައިޓުތައް ނުވަތަ ލިޔުން ފިލްޓަރުތައް ބޭނުންކުރާ ސައިޓުތަކުގެ ކަންކަން އަވަސްކުރެވޭނެއެވެ. ލިޔުންތަކުގެ ކޮޕީތައް މިތަނުގައި ކަނޑައަޅާ ގަޑިއަކަށް އެ ލިޔުންތައް ހުރި ފޯމެއްގައި ބެހެއްޓޭނެއެވެ. މިތަން ދަށްކޮށް ސެޓުކޮށްފިނަމަ ކަންކަން ލަސްވެދާނެއެވެ. އަދި މަތިކޮށްފިނަމަ ލިޔުންތައް ރިފުރެޝްވާން ގިނަ އިރު ނަގާފާނެއެވެ. މިސާލަކަށް އައުލިންކުތައް ވާ ލިޔުންތައް';
$string['configcachetype'] = 'މޫޑުލްއިން ބޭނުންކުރަންވީ ކޭޝް މެމޮރީގެ ވައްތަރު ނަގާށެވެ. މިކަމުން ހަމައެކަނި ސެޓުކުރެވޭނީ ކޭޝް އެކަންޏެވެ. ކަމަކަށް ކޭޝް ބޭނުންކުރެވޭނެ ގޮތް ހެދުމަށް ރީކޭޝް އެންއޭބަލްކުރަން ހަނދާންކުރާށެވެ. މިކަން ބޭނުންކުރާނީ <strong>ހަމައެކަނި</strong> ޑޭޓާބޭސް ސިސްޓަމަށް ކުރާ ބުރަ ކުޑަކުރުމަށެވެ. އެހެންނޫންނަމަ މޫޑުލް ކުރިޔަށްދާނީ މާ ލަހުންނެވެ. \'އެތެރޭގައި\' ބޭނުންކުރުމުން އާދައިގެ ވަރަކަށް ޓުރެފިކުވާ ސައިޓުތަކަށް ފައިދާކުރާނެއެވެ. eAccelerator ނުވަތަ Turckmmcache އިންސްޓޯލުކުރެވިފައިވާ އަދި ހިއްސާކުރެވޭ މެމޮރީ އެންއޭބަލްކުރެވިފައިވާ ވެބު ސާވަރަކުން \'eaccelerator\' ބޭނުންކުރަންވާނެއެވެ. ގިނަ ސާވަރުތަކެއް ސެޓަޕުކޮށްފައިވާނަމަ އަދި އެކެއް ނުވަތަ އެކަކަށްވުރެ ގިނަ memcached ޑީމަންތަކެއް އަދި PHP-memcached އެކްސްޓެންޝަން ރަންކުރާނަމަ \'memcached\' ނެގުމަށްފަހު ތިރީގައި memcached ގެ އިޚުތިޔާރުތައް ސެޓުކުރާށެވެ. <br /><strong>ނޯޓު:</strong> ބުރަ ދަނޑިވަޅުތަކާއި ޓިއުނާއި އެއްގޮތަށް ޕާފޮމެންސް ޓެސްޓުކުރަންވާނެއެވެ. ކޭޝްތަކުގެ ސަބަބުން ސައިޓު ލަސްވެދާނެއެވެ. މަތީ ޓުރެފިކު ހިނގާ ވަގުތުތަކުގައި eAccelerator އަދި memcached ގެ ސަބަބުން ވަރަށް ފައިދާ ކުރާނެއެވެ. ނަމަވެސް CPU ގެ ބޭނުން އެންމެ ބޮޑަށްކުރުން ވެބު ސާވަރަށް ދޫކޮށްލާށެވެ.';
$string['configcalendarexportsalt'] = 'މި ތަރުތީބެއްނެތް ލިޔުންކޮޅުގެ ސަބަބުން ކަލަންޑަރު އެކްސްޕޯޓުކުރާއިރު އޯތެންޓިކޭޝަންގެ ޓޯކެންތަކުގެ ސަލާމަތްތެރިކަން އިތުރުކުރެވޭނެއެވެ. ނޯޓު: މި ހޭޝް ސޯލްޓު ބަދަލުކޮށްފިނަމަ މިހާރު ހުރި ހުރިހައި ޓޯކެންތަކެއް ގަބޫލުނުކުރެވޭ ޓޯކެންތަކަކަށް ހެދޭނެއެވެ.';
$string['configclamactlikevirus'] = 'ފައިލުތައް ވައިރަހުގެ ގޮތުގައި ބަލާ';
$string['configclamdonothing'] = 'ފައިލުތައް OK ކަމަށް ބަލާ';
$string['configclamfailureonupload'] = 'އަޕްލޯޑުކުރެވޭ ފައިލްތައް ސްކޭންކުރުމަށް ކުލެމް ސެޓުކުރެވިފައިވީނަމަވެސް ކޮންމެވެސް ސަބަބަކާއި ހެދި ރަން ނުކުރާނަމަ ނުވަތަ ނުބައިކޮށް ކޮންފިގާކުރެވިފައިވާނަމަ ކަންތައްކުރަންޖެހޭނީ ކިހިނެއްތަ؟ \'ފައިލުތައް ވައިރަހުގެ ގޮތުގައި ބަލާ\' ނަގާފައިވާނަމަ އެ ފައިލުތައް ކަރަންޓީނަށް ލެވޭނެއެވެ. ނުވަތަ ފޮހެލެވޭނެއެވެ.  \'ފައިލުތައް OK ކަމަށް ބަލާ\' ނަގާފައިވާނަމަ އާދައިގެމަތިން އެ ފައިލުތައް ލާންޖެހޭ ޑައިރެކްޓުރީތަކަށް ލެވޭނެއެވެ. ކޮންމެގޮތެއްގައިވެސް ކުލެމް ފެއިލުވެއްޖެނަމަ އެޑުމިންއަށް އެންގޭނެއެވެ. \'ފައިލުތައް ވައިރަހުގެ ގޮތުގައި ބަލާ\' ނަގާފައިވަނިކޮށް ކުލެމް ރަން ނުކޮށްފިނަމަ (އާއްމުކޮށް މިހެންވަނީ ކަމުނުދާ pathtoclam އެއް ދެވިފައިވާތީ) އެ ހުރިހާ ފައިލުތައް ކަރަންޓީނަށް ލެވޭނެއެވެ. ނުވަތަ ފޮހެލެވޭނެއެވެ. ވީމާ މި ސެޓިންނާއިމެދު ފަރުވާބަހަށްޓާށެވެ.';
$string['configcookiehttponly'] = 'އައުPHP 5.2.0 ފީޗާ އެންއޭބަލް ކުރެވޭނެއެވެ. ބުރައުސާތަކަށް އަސްލު HTTP ރިކުއެސްޓުތަކާއިއެކު ކުކީޒް ފޮނުވުމަށް އެންގޭނެއެވެ. އަދި ކުކީޒްތައް ސްކުރިޕްޓިން އެއްވެސް ބަހަކަށް އެކްސެސް ކުރެވިގެންނުވާނެއެވެ. މިކަމަކީ ހުރިހާ ބުރައުސާތަކެއް ސަޕޯޠުކުރާ ކަމެއްނޫނެވެ. އަދި މިޙަރުގެ ކޯޑުގައިވެސް މި މަސައްކަތް ނުކޮށްފާނެއެވެ. މިކަމުގެ ސަބަބުން ބައެއް XSS ހަމަލާތަކުން ސަލާމަތްވާނެއެވެ.';
$string['configcookiesecure'] = 'ސާވަރުން ހަމައެކަނި HTTP ކަނެކްޝަންތައް ގަބޫލުކުރާނަމަ ސެކިޔުއައުކުކީޒް ފޮނުވުން އެންއޭބަލްކުރުން އެދވިގެންވެއެވެ. އެންއޭބަލްކޮށްފައިވާނަމަ ވެބު ސާވަރުން http:// ގަބޫލުކުރިޔަ ނުދޭށެވެ. ނުވަތަ ދާއިމީގޮތެއްގައި https??? އެޑުރެހަށް ރީޑައިރެކްޓުކުރާގޮތަށް ސެޓުނުކުރާށެވެ. <em>wwwroot</em> އެޑުރެސްތައް https:// ކޮށް ނުފެށޭނަމަ މި ސެޓިން އޮޓޯއިން ޓާން އޮފްކުރެވޭނެއެވެ.';
$string['configcountry'] = 'މިތަނުގައި ގައުމެއް ސެޓުކޮށްފިނަމަ އައުޔޫސަރު އެކައުންޓުތަކުގައި ޑީފޯލްޓުކޮށް މި ގައުމު ނެގޭނެއެވެ. ޔޫސަރުން އަމިއްލައަށް ގައުމެއް ނަގަން އިޚުތިޔާރު ދިނުމަށް މިތަން ސެޓުނުކުކޮށް ދޫކޮށްލާށެވެ.';
$string['configcoursemanager'] = 'މި ސެޓިން ބޭނުންކޮށްގެން ކޯހެއްގެ ތަފުސީލުގައި ހިމަނަން ބޭނުންވަނީ ކާކުކަން ކޮންޓުރޯލު ކުރެވޭނެއެވެ. ކޯހެއްގެ ތަފުސީލުގައި ޔޫސަރަކު ދެއްކުމަށް އެ ޔޫސަރަކަށް ކޯހެއްގައި މަދުވެގެން މީގެ އެއް ރޯލު އޮންނަންޖެހޭނެއެވެ.';
$string['configcourserequestnotify'] = 'އައުކޯހަކުން ދައުވަތު ދިނުމުން އެކަން އަންގަންވީ ޔޫސަރުގެ ޔޫސަރުނަން ލިޔޭ';
$string['configcourserequestnotify2'] = 'އައުކޯހަކުން ދައުވަތު ދިނުމުން އެކަން އަންގަންވީ ޔޫސަރުން. މިތާ ލިސްޓުކުރެވޭނީ ހަމައެކަނި އައުކޯސްތަކުގެ ދައުވަތު ގަބޫލުކުރެވޭނެ ޔޫސަރުންނެވެ.';
$string['configcoursesperpage'] = 'ކޯސް ލިސްޓުކުރާ ސަފުހާއެއްގައި ދައްކަންވީ ކޯސްތަކުގެ އަދަދު ލިޔޭ';
$string['configcreatornewroleid'] = 'މި ރޯލަކީ އައުކޯހެއް ހެދުމުން އެ ކޯސް ހެދި މީހާކަށް ކަނޑައެޅޭ ރޯލެކެވެ. ޕޭރެންޓު ކޮންޓެކްސްޓުގައި އެ ބޭނުންވާ ކޭޕަބިލިޓީޒްތައް މިހާރުވެސް އެ ޔޫސަރަށް ލިބިފައިވާނަމަ މި ރޯލެއް ކަނޑައެއް ނޭޅޭނެއެވެ.';
$string['configcronremotepassword'] = 'http://site.example.com/admin/cron.php?password =
</pre>If this is left empty, no password is required.';
$string['configdbsessions'] = 'މިތަން އެންއޭބަލް ކޮށްފިނަމަ މިހާރު ހިނގަމުންދާ ސެޝަންތަކާއިބެހޭ މައުލޫމާތު ސްޓޯކުރަން ޑޭޓާބޭސް ބޭނުންކުރެވޭނެއެވެ. މިކަން ހާއްސަގޮތެއްގައި ބޭނުންތެރިވަނީ ބޮޑެތި/ބުރަ ސައިޓުތަކަށެވެ. ނުވަތަ ކުލަސްޓާ ސާވަރުތަކެއްގައި ހެދިފައިވާ ސައިޓުތަކަށެވެ. ޑޭޓާބޭސްއާއި ހިލާފަށް ސާވަރުގެ ޑިސްކު ބޭނުންކުރުމަށް ގިނަ ސައިޓުތަކުގައި މިތަން ވާންޖެހޭނީ ޑިސްއޭބަލް ކުރެވިފައެވެ. ނޯޓު: މި ސެޓިން މިހާރު ބަދަލުކޮށްފިނަމަ މިހާރ ލޮގިންވެފައިވާ ހުރިހާ ޔޫސަރުން (ކަލޭވެސް) ލޮގް އައުޓުކުރެވޭނެއެވެ. MySQL ބޭނުންކުރާނަމަ my.cnf ނުވަތަ my.ini ގައިވާ \'max_allowed_packet\' ކުޑަވެގެން 4 އަށް ސެޓުކުރެވިފައިވޭތޯ ޔގީންކުރާށެވެ.';
$string['configdebug'] = 'މިތަން ޓާން އޮން ކޮށްފިނަމަ PHP ގެ error_reporting މަތިކުރެވޭނެއެވެ. މިހެންވުމުން މާ ގިނަ އިންޒާރުތައް ޕުރިންޓުކުރެވޭނެއެވެ. މި ބޭނުންތެރިވަނީ ހަމަ އެކަނު ޑިވެލޮޕަރުންނަށެވެ.';
$string['configdebugdisplay'] = 'މިތަން ޓާން އޮން ކޮށްފިނަމަ އެރާ ރިޕޯޓިން HTML ސަފުހާއަށް ދާނެއެވެ. މިއީ ބޭނުންތެރި ގޮތެކެވެ. ނަމަވެސް އާއްމުކޮށް XTML، Javascript، ކުކީޒް އަދި HTTP ހެޑާތައް ހަލާކުކޮށްލާނެއެވެ. ޓާން އޮފް ކޮށްފިނަމަ ސާވަރު ލޮގުތަކަށް އައުޓުޕުޓު ފޮނުވާނެއެވެ. އެހެންކަމުން ޑީބަގުކުރުން ރަނގަޅުވާނެއެވެ. PHP ގެ error_log ސެޓިން އިން މި އައުޓުޕުޓު ދާންވީ ލޮގުތައް ކޮންޓުރޯލުކުރާނެއެވެ.';
$string['configdebugsmtp'] = 'SMTP ސާވަރަށް އީމެއިލު މެސެޖު ފޮނުވާއިރު verbose ޑީބަގު މައުލޫމާތު އެންއޭބަލްކުރޭ';
$string['configdefaultallowedmodules'] = 'މަތީގައިވާ ކެޓަގަރީގައިވާ ކޯސްތަކަށް، <b>އެ ކޯސްތައް ހެދުމުން</b>، ޑީފޯލްޓުކޮށް ހުއްދަކުރަންވީ ކޮން މޮޑިއުލްތަކެއް؟';
$string['configdefaultcourseroleid'] = 'ކޯހަކަށް ޔޫސަރަކު ވެއްދުމުން އޮޓޮމެޓިކުން މި ރޯލު އެ ޔޫސަރަކަށް ކަނޑައެޅޭނެއެވެ.';
$string['configdefaultrequestcategory'] = 'ޔޫސަރުން ރިކުއެސްޓުކުރާ ކޯސްތައް އޮޓޮމެޓިކުން މި ކެޓަގަރީއަށް ލެވޭނެއެވެ.';
$string['configdefaultrequestedcategory'] = 'ކޯސަތައް ރިކުއެސްޓުކުރުމަށްފަހު ގަބޫލުކުރުމުން އެ ކޯސްތައް ލާންވީ ޑީފޯލްޓު ކެޓަގަރީ';
$string['configdefaultuserroleid'] = 'ލޮގިންވެފައިވާ ޔޫސަރުންނަށް ދެވިފައިވާ އެހެނިހެން ރޯލުތަކުގެ އިތުރަށް، ސައިޓު ލެވެލްގައި، މިތަނުގައި ކަލޭ ކަނޑައަޅާ ރޯލުގެ ކޭޕަބިލިޓީޒް އެ ޔޫސަރުންނަށް ދެވޭނެއެވެ. ޑީފޯލްޓުކޮށްވާނީ އޯތެންޓިކޭޓެޑު ރޯލު (ކުޜިގެ ވާޝަންއެއްގައިނަމަ ގެސްޓު ރޯލު) އެވެ. ނޯޓު: މިކަމަކުން އެ ޔޫސަރުންގެ އެހެން ރޯލުތަކާއި އަރާރުމެއް ނުވާނެއެވެ. އަދި މިކަމުގެ ސަބަބުން ހުރިހައި ޔޫސަރުންނަށް ކޯސް ލެވެލުގައި ނުލިބޭ ކޭޕަބިލިޓީޒްތައް (މިސާލަކަށް ބުލޮގު އެންޓުރީތައް ޕޯސްޓު ކުރުން، އަމިއްލަ ކަލަންޑަރު ބެލެހެއްޓުން، އަދިވެސް...) ހޯދައިދިނުން ޔަގީންކުރެވޭނެއެވެ.';
$string['configdeleteincompleteusers'] = 'މި ވަގުތުގެ ފަހުން ފަހުން މުޅިން ސެޓަޕުނުކޮށްވާ އެކައުންޓުތައް ފޮހެލެވޭނެއެވެ.';
$string['configdeleteunconfirmed'] = 'އީމެއިލު އޯތެންޓިކޭޝަން ބޭނުންކުރާނަމަ، މިތަނުގައި މި ކަނޑައަޅާ ވަގުތަކީ ޔޫސަރުންގެ ފަރާތުން ޖަވާބުތައް ގަބޫލުކުރެވޭނެ ވަގުތެވެ. މިވަގުތުގެ ފަހުން، ކުރީގެ ކޮންފާމުނުކޮށްވާ އެކައުންޓުތައް ފޮހެލެވޭނެއެވެ.';
$string['configdenyemailaddresses'] = 'ވަކި ޑޮމެއިންއަކުން އީމެއިލު އެޑުރެސްތައް މަނާކުރަން ބޭނުންނަމަ، ހަމަ އެގޮތަށް މިތަނުގައި ލިސްޓުކުރާށެވެ. އެހެން ހުރިހާ ޑޮމެއިންތަކެއް ގަބޫލުކުރެވޭނެއެވެ. ސަބުޑޮމެއިންތައް މަނާކުރުމަށް އެ ޑޮމެއިންއެއްގެ ފަހަތުގައި \'.\' އިތުރުކުރާށެވެ. މިސާލަކަށް: <strong>hotmail.com yahoo.co.uk .live.com</strong>';
$string['configdigestmailtime'] = 'ޑައިޖެސްޓުކޮށް އީމެއިލު ފޮނުވުމަށް ނަގާފައިވާ މީހުންނަށް ޑައިޖެސްޓު ކޮންމެ ދުވަހަކު އީމެއިލު ކުރެވޭނެއެވެ. މި ސެޓިން އިން އެ މެއިލު ފޮނުވަންވީ ދުވަހުގެ ކޮން ވަގުތެއްގައިކަން ކޮންޓުރޯލުކުރެވޭނެއެވެ. މި ގަޑީގެ ފަހުން ރަންކުރާ ފުރަތަމަ cron އިން މެއިލް ފޮނުވާނެއެވެ.';
$string['configdisablecourseajax'] = 'މެއިން ކޯސް ސަފުހާތައް އެޑިޓުކުރާއިރު AJAX ބޭނުންނުކުރާށެވެ.';
$string['configdisableuserimages'] = 'ޔޫސަރުންނަށް ޔޫސަރު ޕުރޮފައިލުގެ ފޮޓޯ ބަދަލުކުރުން ޑިސްއޭބަލްކުރޭ';
$string['configdisplayloginfailures'] = 'މިކަމުން ކަނޑައެޅިފައިވާ ވަކި ޔޫސަރުންތަކަކަށް ކުރީގެ ލޮގިން ފެއިލްތަކުގެ މައުލޫމާތު ދެއްކޭނެއެވެ.';
$string['configdocroot'] = 'Moodle Docs އަށް ދެވޭ ޕާތު ހެދޭނެއެވެ. އަމިއްލަ އޮންލައިން ޑޮކިޔުމެންޓޭޝަނެއް އޮންނަން ބޭނުންނަމަ މިތަން ބަދަލުކުރެވިދާނެއެވެ. ނަމަވެސް، ބަދަލުކޮށްފިނަމަ، އެ އަމިއްލަ ޑޮކިޔުމެންޓޭޝަނުގައިވާ ޕާތުތައް http://docs.moodle.org ގައިވާ ޕާތުތަކާއި އެއް ފޯމެޓަކަށް ހުރިތޯ ޔަގީންކުރާށެވެ.';
$string['configdoctonewwindow'] = 'މިތަން އެންއޭބަލްކޮށްފިނަމަ Moodle Docs އަށްދެވޭ ލިންކުތައް ދެއްކޭނީ އައުވިންޑޯއެއްގައެވެ.';
$string['configeditordictionary'] = 'ޔޫސަރުގެ އަމިއްލަ ބަހުގެ ބަހަކަށް ރަދީފު ނެތްނަމަ މި ލިޔުންކޮޅު ބޭނުންކުރެވޭނެއެވެ.';
$string['configeditorfontlist'] = 'އެޑިޓަރުގެ ޑުރޮޕުޑައުން ލިސްޓުގައި ދައްކަންވީ ފޮންޓުތައް ނަގާ';
$string['configemailchangeconfirmation'] = 'ޔޫސަރުންގެ ޕުރޮފައިލުގައިވާ އީމެއިލު އެޑުރެސް ބަދަލުކޮށްފިނަމަ އެކަން ޔަގީންކުރަން (އީމެއިލު ކޮންފޮމޭޝަން) ޖެހޭނެއެވެ.';
$string['configemoticons'] = 'ކަނާއަތް ފަޅީގައިވާ އިމޮޓިކަނުގެ ނަމާއި ގުޅޭ ކޯޑު ވާއަތް ފަރާތުގައި ބަދަލުކުރާށެވެ. އައުއިމޮޓިކަނެއް އިތުރުކުރުމަށް އެއިގެ ކޯޑާއި ނަން ދިނުމަށްފަހު އިމޮޓިކަނުގެ ފޮޓޯއެއް /pix/s ކޮށް name.gif ފޯމެޓަށް އިތުރުކުރާށެވެ.';
$string['configenableajax'] = 'މި ސެޓިން ބޭނުންކޮށްގެން މުޅި ސައިޓުގައި AJAX (މާ މޮޅު Javascript ކުލައެންޓު/ސާވަރު އިންޓަފޭސްއެއް) ބޭނުންކުރާގޮތް ކޮންޓުރޯލުކުރެވޭނެއެވެ. މި ސެޓިން އެންއޭބަލްކޮށްފައިވީނަމަވެސް ޔޫސަރުންނަށް އެމީހުންގެ ޕުރޮފައިލުގައި ވަކި އިޚުތިޔާރެއް ނެގެންހުންނާނެއެވެ. ނޫންނަމަ ހުރިހައި ޔޫސަރުނަނަށްވެސް AJAX ވާނީ ޑިސްއޭބަލްކުރެވިފައެވެ.';
$string['configenablecalendarexport'] = 'ކަލަންޑަރުތައް އެކްސްޕޯޓުކުރުން ނުވަތަ ކަލަންޑަރުތަކަށް ސަބުސްކުރައިބުކުރުން އެންއޭބަލްކުރޭ';
$string['configenablecourserequests'] = 'މިހެންވުމުން ކޮންމެ ޔޫސަރަކަށްވެސް ކޯހެއް ހެދުމަށް ރެިކުއެސްޓުކުރުމުގެ ހުއްދަ ދެވޭނެއެވެ.';
$string['configenableglobalsearch'] = 'މި ސެޓިން އިން ގުލޯބަލްކޮށް ރިސޯސްތަކުންނާއި އެކްޓިވިޓީތަކުން ލިޔުން ހޯދުން އެންއޭބަލްކުރާނއެއެވެ. PHP 4 ގައި މިކަން މަސައްކަތެއްނުކުރާނެއެވެ.';
$string['configenablegroupings'] = 'މި ސެޓިން އިން ގުރޫޕުތައް ގުރޫޕުކުރުން އެންއޭބަލްކުރާނއެއެވެ.';
$string['configenablehtmlpurifier'] = 'އިތުބާރުނުކުރެވޭ ލިޔުންތައް ސާފުކުރުމަށް KSES ބޭނުންނުކޮށް HTML Purifier ބޭނުންކުރާށެވެ. HTML Purifier އަކީ މިހާރުވެސް ހެދެމުންދާ، އަދި ގަބޫލުކުރެވޭގޮތުގައި މާ ސަލާމަތްތެރި، ނަމަވެސް މާބޮޑަށް ރިސޯސް ބޭނުންކުރާ އެއްޗެކެވެ. ފެނުމުގައި ކުދިކުދި ތަފާތުތަށް ހުރުމަކީ އެކަށީގެންވާ ކަމަކެވެ. ނޯޓު: EMBED އަދި OBJECT ޓެގުތައް އެންއޭބަލެއް ނުކުރެވޭނެއެވެ. އަދި MathML އާއި މުސްކުޅި Lang ޓެގުތަކެއް ސަޕޯޓެއް ނުކުރާނެއެވެ.';
$string['configenablerssfeeds'] = 'މި ސުވިޗުން މުޅި ސައިޓުގައިވާ RSS ފީޑުތައް އެންއޭބަލްކުރާނެއެވެ. އަސްލު އެއްވެސް ބަދަލެއް ބަލަން ބޭނުންނަމަ ވަކިވަކި މޮޑިއުލްތަކުގައިވާ RSS ފީޑުތައްވެސް އެންއޭބަލްކުރަންޖެހޭނެއެވެ. އެކަން ކުރުމަށް އެޑުމިން ކޮންފިގަރޭޝަނުގެ ދަށުގައިވާ މޮޑިއުލްތަކުގެ ސެޓިންއަށް ދާށެވެ.';
$string['configenablerssfeedsdisabled'] = 'އެ ލިބެންނެތީ މުޅި ސައިޓުގައި RSS ފީޑުތައް ޑިސްއޭބަލްކޮށްފައިވާތީއެވެ. RSS ފީޑުތައް އެންއޭބަލްކުރުމަށް އެޑުމިން ކޮންފިގަރޭޝަނުގެ ދަށުގައިވާ ވޭރިއަބަލްތަކުގެ ސެޓިންއަށް ދާށެވެ.';
$string['configenablerssfeedsdisabled2'] = 'ސާވަރާއި ހިސާބުން RSS ފީޑުތައްވަނީ ޑިސްއޭބަލްކުރެވިފައެވެ. ފުރަތަމަ Server/RSS އިން އެ ފީޑުތައް އެންއޭބަލްކުރަން ޖެހޭނެއެވެ.';
$string['configenablestats'] = 'މިތަނުގައި \'އާނ\' ނަގައިފިނަމަ މޫޑުލްގެ cronjob އިން ލޮގުތައް ޕުރޯސަސްކުރުމަށްފަހު ބައެއް ސްޓެޓިސްޓިކްސް އެއްކުރާނެއެވެ. ސައިޓުގެ ޓުރެފިކުގެ މިންވަރަށް ބަލާފައި މިކަމަށް ވަގުތުކޮޅެއް ހޭދަވެދާނެއެވެ. މިތަން އެންއޭބަލް ކޮށްފިނަމަ ކޮންމެ ކޯހަކަށް ނުވަތަ ސައިޓަށް ވަރަށް ޝައުގުވެރިވާފަދަ ގުރާފުތަކެއް ނުވަތަ ސްޓެޓިސްޓިކްސް ފެންނާނެއެވެ.';
$string['configenabletrusttext'] = 'ޔޫސަރުންގެ ފަރާތުން ލިބޭ ލިޔުންތައް މޫޑުލްއިން ޑީފޯލްޓުކޮށް ވަރަށް ރަނގަޅަށް ސާފުކުރާނެއެވެ. އެއީ ސަލާމަތްތެރިކަމަށް ބަލާފައި ނުބައި ސުކުރިޕްޓުތަކާއި މީޑިއައުފަދަ ތެކެތި ފޮހެލުމަށެވެ. Trusted Content ސިސަޓަމަކީ ވަކި ކަހަލަ ޔޫސަރުންނަށް އިތުބާރާއި އެކީ އެއްވެސް ދަތިކަމެއްނެތި އެ ޔޫސަރުންނަށް އެފަދަ މޮޅު ފީޗާތައް ހިމެނޭނެ ހުއްދަދޭ ސިސްޓަމެކެވެ. މި ސިސްޓަމު އެންއޭބަލް ކުރުމަށް ފުރަތަމަ މި ސެޓިން އެންއޭބަލްކުރުމަށްފަހު މޫޑުލްގެ ވަކި ރޯލަކަށް Trusted Content ގެ ހުއްދަ ދޭންޖެހޭނެއެވެ. މިފަދަ ޔޫސަރުން ހަދާ ނުވަތަ އަޕްލޯޑުކުރާ ލިޔުންތައް އިތުބާރުކުރެވޭކަމަށް މާކު ކުރެވޭނެއެވެ. އަދި މި ލިޔުންތައް ދެއްކުމުގެ ކުރިން ސާފެއް ނުކުރެވޭނެއެވެ.';
$string['configenrolmentplugins'] = 'ބޭނުންކުރަން ބޭނުންވާ އެންރޯލްމެންޓު ޕުލަގިންތައް ނަގާށެވެ. އަދި އަދި އެ ސެޓިންތައް ރަނގަޅަށް ހަދަން ހަނދާންކުރާށެވެ. <br /><br /> އެންއޭބަލްކޮށްފައިވަނީ ކޮން ޕުލަގިންތަކެއްކަން ދައްކަންޖެހޭނެއެވެ. އަދި އިންޓެރެކްޓިވް އެންރޯލްމެންޓަށް <strong>އެއް</strong> ޕުލަގިން ޑީފޯލްޓުކޮށް ނެގިދާނެއެވެ. އިންޓެރެކްޓިވް އެންރޯލްމެންޓު ޑިސްއޭބަލް ކުރުމަށް ނަގަންޖެހޭ ކޯސްތަކުގައިވާ \"އެންރޯލުކުރެވޭ\" ތަން \"ނޫން\" އަށް ސެޓުކުރާށެވެ.';
$string['configmaxevents'] = 'ކުރިއަށްހުރި ހަރަކާތްތައް';
$string['configsectionmail'] = 'މެއިލް';
$string['configsectionmisc'] = 'އެހެނިހެން';
$string['configsectionoperatingsystem'] = 'އޮޕަރޭޓިންގް ސިސްޓަމް';
$string['configsectionpermissions'] = 'ހުއްދަތައް';
$string['configsectionrequestedcourse'] = 'ކޯހުގެ ރިކުއެސްޓްތައް';
$string['configsectionsecurity'] = 'ސެކިއުރިޓީ';
$string['configsectionstats'] = 'ތަފާސްހިސާބުތައް';
$string['configsectionuser'] = 'ޔޫސަރ';
$string['configstartwday'] = 'ހަފްތާގެ ފެށުން';
$string['configthemelist'] = 'For example:  standard,orangewhite.';
$string['configvisiblecourses'] = 'ފޮރުވިފައިވާ ކެޓަގަރީ ތަކުގައިވާ ކޯސްތައް އާދައިގެމަތިން ދައްކާ';
$string['confirmation'] = 'ޔަޤީންކުރުން';
$string['confirmed'] = 'ޔަޤީންކުރެވިފަ';
$string['coursemanager'] = 'ކޯސް ބެލެހެއްޓުން';
$string['coursemgmt'] = 'ކޯހަށް ބަދަލުގެންނަން / ކޯހެއް އިތުރުކުރަން';
$string['courseoverview'] = 'ކޯހުގެ އޯވަރވިއު';
$string['courserequests'] = 'ކޯހުގެ ރިކުއެސްޓްތައް';
$string['courses'] = 'ކޯސްތައް';
$string['cronerrorclionly'] = 'އެޑުމިނިސްޓުރޭޓަރު ވަނީ މި ސަފުހާއަށް އިންޓަނެޓު ނުލިބޭގޮތް ހަދާފައި';
$string['datarootsecurityerror'] = '<p>You <em>must</em> move dataroot directory ($a) to a new location that is not within your public web directory, and update the <code>\$CFG->dataroot</code> setting in your config.php accordingly.</p>';
$string['debugging'] = 'ޑިބަގްކުރުން';
$string['defaultcourseroleid'] = 'ކޯހުގައި ހިމެނޭ ޔޫސަރުންގެ ޑިފޯލްޓް ރޯލް';
$string['defaultsettinginfo'] = 'ޑިފޯލްޓް: $a';
$string['defaultuserroleid'] = 'ހުރިހާ ޔޫސަރުންގެ ޑިފޯލްޓް ރޯލް';
$string['defaultvalues'] = 'ޑިފޯލްޓް އަދަދުތައް';
$string['deleteerrors'] = 'މައްސަލަތައް ފުހެލަން';
$string['deleteuser'] = 'ޔޫސަރު ފުހެލަން';
$string['doctonewwindow'] = 'އައު ވިންޑޯއެއްގަ ހުޅުވަން';
$string['download'] = 'ޑައުންލޯޑް';
$string['edithelpdocs'] = 'އެހީއަށް ބޭނުންކުރާ ފައިލްތަކަށް ބަދަލުގެންނަން';
$string['editlang'] = '<b>ބަދަލުގެންނަން</b>';
$string['editorbackgroundcolor'] = 'ބެކްގަރައުންޑްކުލަ';
$string['editorfontfamily'] = 'ފޮންޓް ފެމިލީ';
$string['editorfontlist'] = 'ފޮންޓް ލިސްޓް';
$string['editorfontsize'] = 'ފޮންޓް ސައިޒު';
$string['editstrings'] = 'ބަސްތަކާ ލިޔުން ބަދަލުކުރަން';
$string['emailchangeconfirmation'] = 'އީމެއިލް ބަދަލުކުރުން ޔަޤީންކުރުން';
$string['emoticons'] = 'އިމޮޓޮކޮންސް';
$string['emptysettingvalue'] = 'ހުސްކޮށް';
$string['environment'] = 'ވެށި';
$string['errors'] = 'މައްސަލަތައް';
$string['errorsetting'] = 'ސެޓިންގްސ ސޭވެއް ނުކުރެވުނު';
$string['experimental'] = 'އެކްސްޕެރިމަންޓަށް';
$string['filecreated'] = 'އައު ފައިލެއް ހެދިއްޖެ';
$string['filestoredin'] = 'ފޯލްޑަރގައި ފައިލް ސޭވަކުރަން';
$string['filtersettings'] = 'ފިލްޓަރގެ ސެޓިންގްތައް';
$string['forcelogin'] = 'ޔޫސަރުން ލޮގިން ކުރަން މަޖުބޫރުކުރަން';
$string['frontpage'] = 'ފުރަތަމަ ޞަފުހާ';
$string['frontpagebackup'] = 'ފުރަތަމަ ޞަފުހާ ބެކްއަޕް';
$string['frontpagedefaultrole'] = 'ފުރަތަމަ ޞަފުހާގެ ޑިފޯލްޓް ރޯލް';
$string['frontpagequestions'] = 'ފުރަތަމަ ޞަފުހާގެ ސުވާލުތައް';
$string['frontpagerestore'] = 'ފުރަތަމަ ޞަފްހާ ރިސްޓޯކުރަން';
$string['frontpageroles'] = 'ފުރަތަމް ޞަފުހާގެ ރޯލްތައް';
$string['frontpagesettings'] = 'ފުރަތަމް ޞަފުހާގެ ސެޓިންގތައް';
$string['generalsettings'] = 'އާންމު ސެޓިންގްސ';
$string['gotofirst'] = 'މަދުވާ ފުރަތަމަ ސްޓްރިންގަށް ދާން';
$string['gradebook'] = 'ގްރޭޑްފޮތް';
$string['gradebookroles'] = 'ގްރޭޑްކުރެވިފަހުރި ރޯލްތައް';
$string['guestroleid'] = 'މެހެމާނުންގެ ރޯލް';
$string['helpstartofweek'] = 'ހަފްތާ ފެށެނީ ކޮންދުވަހަކު؟';
$string['hidefromall'] = 'ހުރިހާ އެންމެނަށް ފޮރުވަން';
$string['hidefromnone'] = 'ހުރިހާ އެންމެނަށް ދައްކަން';
$string['hidefromstudents'] = 'ދަރިވަރުންނަށް ނުދައްކަން';
$string['htmleditor'] = 'އެޗްޓީއެމްއެލް އެޑިޓަރ';
$string['htmlsettings'] = 'އެޗްޓީއެމްއެލް ސެޓިންގްތައް';
$string['http'] = 'އެޗްޓީޓީޕީ';
$string['httpsecurity'] = 'އެޗްޓީޓީޕީ ސެކިއުރިޓީ';
$string['ignore'] = 'އަޅާނުލަން';
$string['install'] = 'ޙިޔާރުކުރެވިފަ ހުރި ބަސްތަކުގެ އިންސްޓޯލްކުރަން';
$string['installedlangs'] = 'އިންސްޓޯލްކުރެވިފަ ހުރި ބަހުގެ ޕެކޭޖްތައް';
$string['lang'] = 'ޑިފޯލްޓް ބަސް';
$string['langedit'] = 'ބަސް ބަދަލުކުރުން';
$string['langimportsuccess'] = 'ބަހުގެ ޕެކޭޖް $a އަޕްޑޭޓްކުރެވިއްޖެ';
$string['langlist'] = 'ބަސް މެނުގައި ހިމެނޭ ބަސްތައް';
$string['langmenu'] = 'ބަސް މެނު ދައްކަން';
$string['langpackinstalled'] = 'ބަހުގެ ޕެކޭޖް $a އިންސްޓޯލްކުރެވިއްޖެ';
$string['langpackremoved'] = 'ބަހުގެ ޕެކޭޖް އަންއިންސްޓޯލްކުރެވިއްޖެ';
$string['langpacks'] = 'ބަހުގެ ޕެކޭޖްތައް';
$string['langpackupdated'] = 'ބަހުގެ ޕެކޭޖް $a އަޕްޑޭޓްކުރެވިއްޖެ';
$string['langpackupdateskipped'] = 'ބަހުގެ ޕެކޭޖް $a އަޕްޑޭޓްނުކޮށް ދޫކޮށްލެވިފަ';
$string['languagesettings'] = 'ބަހުގެ ސެޓިންގްތައް';
$string['langupdatecomplete'] = 'ބަހުގެ ޕެކޭޖް އަޕްޑޭޓްކުރެވިއްޖެ';
$string['localetext'] = 'ސައިޓުގައި ބޭނުންކުރެވޭ ލޮކޭލް';
$string['location'] = 'ތަން';
$string['locationsettings'] = 'ތަނުގެ ސެޓިންގތައް';
$string['log'] = 'ލޮގުތައް';
$string['mail'] = 'އީމެއިލް';
$string['managelang'] = 'ބަލަހައްޓަން';
$string['maxbytes'] = 'އަޕްލޯޑްކުރެވޭ އެންމެ ބޮޑު ސައިޒު';
$string['maxeditingtime'] = 'ޕޯސްޓަށް ބަދަލުގެނެވޭނެ މުއްދަތު';
$string['minpasswordlength'] = 'ޕާސްވޯޑް ދިގުމިން';
$string['misc'] = 'އެހެނިހެން';
$string['modsettings'] = 'ހަރަކާތްތައް މެނޭޖްކުރަން';
$string['modulesecurity'] = 'މޮޑިއުލް ސެކިއުރިޓީ';
$string['mycoursesperpage'] = 'ކޯސް އެންމެ ގިނަ ކުރެވޭނެ އަދަދު';
$string['mymoodle'] = 'މައި މޫޑޫލް';
$string['mymoodleredirect'] = 'މައި މޫޑުލް ބޭނުންކުރަން މަޖުބޫރުކުރަން';
$string['nobookmarksforuser'] = 'އެއްވެސް ބުކްމާކެއް ނެތް';
$string['nochanges'] = 'ބަދަލެއް ނެތް';
$string['nolangupdateneeded'] = 'ހުރިހާ ބަސްތަކުގެ ޕެކޭޖް ހުރީ އަޕްޑޭޓްކޮށް';
$string['nomissingstrings'] = 'އެއްވެސް ސްޓްރިންގެއް މަދެއް ނޫން';
$string['nonexistentbookmark'] = 'ތިބާ ބޭނުންވާ ބުކްމާކެއް ނެތް';
$string['noreplyaddress'] = 'ޖަވާބު ފޮނުވަންވީ އެޑުރެހެއް ނުފެނުނު';
$string['noresults'] = 'ނަތީޖާއެއް ނުފެނުނު';
$string['notifications'] = 'އެންގުންތައް';
$string['numberofmissingstrings'] = 'މަދުވާ ސްޓްރިންގުގެ އަދަދު: $a';
$string['numberofstrings'] = 'ޖުމްލަ ސްޓްރިންގް: $a->strings<br /> މަދުވަނީ: $a->missing ($a->missingpercent&nbsp;%%';
$string['order1'] = 'ފުރަތަމަ';
$string['order2'] = 'ދެވަނަ';
$string['order3'] = 'ތިންވަނަ';
$string['order4'] = 'ހަތަރުވަނަ';
$string['performance'] = 'ފެންވަރު';
$string['plugins'] = 'މޮޑިއުލްތައް';
$string['profilecategory'] = 'ކެޓަގަރި';
$string['profilecategoryname'] = 'ކެޓަގަރީ ނަން (ތަފާތު ވާންވާނެ)';
$string['profilecategorynamenotunique'] = 'މި ކެޓަގަރީ ނަން މިހާރުވެސް ބޭނުންކުރެވޭ';
$string['profilecommonsettings'] = 'އާންމު ސެޓިންގްސ';
$string['profilecreatecategory'] = 'އައު ޕްރޮފައިލް ކެޓަގަރީއެއް ހަދަން';
$string['profilecreatefield'] = 'އައު ޕްރޮފައިލް ފީލްޑެއް ހަދަން';
$string['profilecreatenewcategory'] = 'އައު ކެޓަގަރީއެއް ހަދަން';
$string['profiledefaultcategory'] = 'އެހެން ފީލްޑްތައް';
$string['profiledefaultdata'] = 'ޑިފޯލްޓް ވެލިއު';
$string['profiledeletecategory'] = 'ކެޓަގަރީއެއް ފުހެލަނީ';
$string['profiledeletefield'] = 'ފީލްޑެއް ފުހެލަނީ';
$string['profiledescription'] = 'ފީލްޑްގެ މަޢުލޫމާތު';
$string['profileeditcategory'] = 'ކެޓަގަރީއަށް ބަދަލުގެންނަން: $a';
$string['profilefieldispassword'] = 'މި އީ ޕާސްވޯޑް ފީލްޑެއްތަ؟';
$string['profileforceunique'] = 'ޑޭޓާ ތަފާތު ވާންޖެހޭނެތަ؟';
$string['profileinvaliddata'] = 'އަދަދު ކަމަކުނުދޭ';
$string['profilemenutoofewoptions'] = 'މަދުވެގެން ދެ ގޮތެއް ދޭންވާނެ';
$string['profilename'] = 'ނަން';
$string['profilenofieldsdefined'] = 'އެއްވެސް ފީލްޑެއް ބަޔާންކުރެވިފައެއް ނުވޭ';
$string['profilerequired'] = 'މިއީ ކޮންމެހެން ބޭނުން ފީލްޑެއްތަ';
$string['profilesforenrolledusersonly'] = 'ޕްރޮފައިލް ހަމައެކަނި އެންރޯލްކުރެވިފަތިބި ޔޫސަރުންނަށް';
$string['profileshortname'] = 'ކުރުނަން (ތަފާތުވާން ވާނެ)';
$string['profileshortnamenotunique'] = 'މި ކުރުނަން މިހާރުވެސް ބޭނުންކުރެވޭ';
$string['profilesignup'] = 'ސައިންއަޕް ސަފްޙާގައި ދައްކަން';
$string['profilevisible'] = 'މި ފީލްޑް ފެންނަން ހުންނާނީ ކާކަށް';
$string['profilevisibleall'] = 'ހުރިހާ އެންމެނަށް ފެންނަގޮތަށް';
$string['profilevisiblenone'] = 'ނުފެނޭ';
$string['profilevisibleprivate'] = 'ޔޫސަރަށް ފެންނަގޮތަށް';
$string['protectusernames'] = 'ޔޫސަރު ނަންތައް ހިމާޔަތްކުރަން';
$string['question'] = 'ސުވާލު';
$string['riskpersonal'] = 'އެހެން ޔޫސަރުންގެ ޒާތީ މަޢުލޫމާތު ޔޫސަރަށް ބެލޭނެ';
$string['savechanges'] = 'ބަދަލުތައް ސޭވްކުރަން';
$string['search'] = 'ހޯދުން';
$string['searchinsettings'] = 'ސެޓިންގތަކުގައި ހޯދަން';
$string['searchresults'] = 'ސަރޗްގެ ނަތީޖާ';
$string['security'] = 'ސެކިއުރިޓީ';
$string['sendcoursewelcomemessage'] = 'ކޯހުގެ މަރުޙަބާ މެސެޖް ފޮނުވަން';
$string['server'] = 'ސާވަރު';
$string['sessionhandling'] = 'ސެޝަން ބެލެހެއްޓުން';
$string['sessiontimeout'] = 'ވަޤުތު ހަމަވެއްޖެ';
$string['showblocksonmodpages'] = 'މޮޑިއުލް ސަފްޚާތަކުގައި ބްލޮކްތައް ދައްކާ';
$string['simpletest'] = 'ޔުނިޓު ޓެސްޓުތައް';
$string['sitelangchanged'] = 'ސައިޓުގައި ބޭނުންކުރެވޭ ބަސްތަކުގެ ސެޓިންގްސ ބަދަލުކުރެވިއްޖެ';
$string['sitemaintenance'] = 'މިވަގުތު ސައިޓު ހިންގުމުގެ މަސައްކަތެއް ކުރިއަށްދާތީވެ ސައިޓަށް މިވަގުތަކު ނުވަދެވޭނެއެވެ.';
$string['sitemaintenancemode'] = 'ސައިޓުގެ މެއިންޓަނަންސް މޯޑު';
$string['sitepolicies'] = 'ސައިޓުގެ ޕޮލިސީ';
$string['stats'] = 'ތަފާސްހިސާބު';
$string['stickyblocks'] = 'ސްޓިކީ ބްލޮކްތައް';
$string['stickyblockscourseview'] = 'ކޯސް ސަފުހާ';
$string['stickyblocksmymoodle'] = 'އަހަރެންގެ މޫޑުލް';
$string['stripalltitletags'] = 'ހުރިހާ ހަރަކާތްތަކުގެ ނަންތަކުގެ ތެރެއިން އެޗްޓީއެމްއެލް ޓެގުތައް ފުހެލަން';
$string['systempaths'] = 'ސިސްޓަމް ޕާރތުތައް';
$string['themelist'] = 'ތީމްތަކުގެ ލިސްޓް';
$string['themeselector'] = 'ތީމް ސިލެކްޓަރ';
$string['themesettings'] = 'ތީމްގެ ސެޓިންގްސ';
$string['therewereerrors'] = 'ތިބާގެ ޑޭޓާގައި މައްސަލަ އެބަހުރި';
$string['timezone'] = 'ޑީފޯލްޓު ޓައިމް ޒޯނު';
$string['timezoneforced'] = 'މިއީ ސައިޓުގެ އެޑުމިނިސްޓުރޭޓަރު މަޖުބޫރުކޮށްފަ އިންކަމެއް';
$string['timezoneisforcedto'] = 'ހުރިހާ ޔޫސަރުން ބޭނުން ކުރަން މަޖުބޫރުކުރޭ';
$string['timezonenotforced'] = 'ޔޫސަރުންނަށް އެމީހުން ބޭނުން ޓައިމްޒޯނެއް ޚިޔާރުކުރެވޭނެ';
$string['unbookmarkthispage'] = 'މި ސަފުހާގެ ބުކްމާކު ފޮހެލާ';
$string['uninstall'] = 'ޙިޔާރު ކުރެވިފަ ހުރި ބަސްތައް އަންއިންސްޓޯލްކުރަން';
$string['uninstallconfirm'] = 'ތި އުޅެނީ $a ބަސް ޕެކޭޖް އެއްކޮށް ފުހަލަން. މި ޔަޤީންކޮށްލާ';
$string['unsupported'] = 'ސަޕޯޓެއް ނުކުރޭ';
$string['updateaccounts'] = 'މިހާރު ހުރި އެކައުންޓްތައް އަޕްޑޭޓްކުރަން';
$string['updatecomponent'] = 'ކޮމްޕޯނަންޓް އަޕްޑޭޓްކުރަން';
$string['updatelangs'] = 'އިންސްޓޯލްކުރެވިފަ ހުރި ހުރިހާ ބަސްތައް އަޕްޑޭޓްކުރަން';
$string['updatetimezones'] = 'ޓައިމްޒޯންތައް އަޕްޑޭޓްކުރަން';
$string['upgradesettings'] = 'އައު ސެޓިންގްސ';
$string['upgradingdata'] = 'ޑޭޓާ އަޕްގްރޭޑްކުރެވެނީ';
$string['upgradinglogs'] = 'ލޮގްތައް އަޕްލޯޑްކުރެވެނީ';
$string['uploadpicture_cannotmovezip'] = 'ޒިޕް ފައިލް ވަޤުތީ ޑައިރެކްޓޮރީއަށް ބަދަލެއް ނުކުރެވުނު';
$string['uploadpicture_cannotprocessdir'] = 'އަންޒިޕް ކުރެވިފަހުރި ފައިލެއް ޕްރޮސެސްއެއް ނުކުރެވޭނެ';
$string['uploadpicture_cannotsave'] = 'ޔޫސަރު $a ގެ ފޮޓޯ ސޭވެއް ނުކުރެވުނު. އޮރިޖިނަލް ފޮޓޯ ފައިލު ޗެކު ކޮށްލާ';
$string['uploadpicture_cannotunzip'] = 'ފޮޓޯފައިލް އަންޒިޕެއް ނުކުރެވުނު';
$string['uploadpicture_overwrite'] = 'މިހާރު ހުރި ޔޫސަރުންގެ ފޮޓޯތަކުގެ މައްޗަށް އަޅަންވީ؟';
$string['uploadpicture_userskipped'] = 'ޔޫސަރ $a ދޫކޮށްލަނީ (މިހާރުވެސް ފޮޓޯ އެބަހުރި)';
$string['uploadpicture_userupdated'] = 'ޔޫސަރު $a ގެ ފޮޓޯ ބަދަލުކުރެވިއްޖެ';
$string['uploadpictures'] = 'ޔޫސަރުގެ ފޮޓޯތައް އަޕްލޯޑުކުރޭ';
$string['uploaduserspreview'] = 'ޔޫސަރުންގެ ޕްރިވިއު އަޕްލޯޑްކުރަން';
$string['uploadusersresult'] = 'ޔޫސަރުގެ ނަތީޖާ އަޕްލޯޑްކުރަން';
$string['usehtmleditor'] = 'HTML އެޑިޓަރު ބޭނުންކުރޭ';
$string['user'] = 'ޔޫސަރ';
$string['useraccountupdated'] = 'ޔޫސަރ އަޕްޑޭޓްކުރެވިއްޖެ';
$string['userbulk'] = 'ޔޫސަރ ތަކުގެ ބޮޑެތި އެކްޝަންސް';
$string['userdeleted'] = 'ޔޫސަރ ފުހެވިއްޖެ';
$string['userlist'] = 'ޔޫސަރުންގެ ލިސްޓް ބަލާލަން';
$string['userpolicies'] = 'ޔޫސަރ ޕޮލިސީތައް';
$string['userrenamed'] = 'ޔޫސަރގެ ނަންބަދަލުކުރެވިއްޖެ';
$string['users'] = 'ޔޫސަރުން';
$string['userscreated'] = 'ހެދުނު ޔޫސަރުން';
$string['usersdeleted'] = 'ފުހެވުނު ޔޫސަރުން';
$string['usersrenamed'] = 'ނަން ބަދަލުކުރިވުނު ޔޫސަރުން';
$string['usersskipped'] = 'ދޫކޮށްލެވިފަހުރި ޔޫސަރުން';
$string['usersupdated'] = 'ޔޫސަރުން އަޕްޑޭޓްކުރެވިއްޖެ';
$string['usersweakpassword'] = 'ދެރަ ޕާސްވޯޑް ގެންގުޅޭ ޔޫސަރުން';
$string['uubulk'] = 'ބޮޑެތި އޮޕެރޭޝަންތަކަށް ޙިޔާރުކުރަން';
$string['uubulkall'] = 'ހުރިހާ ޔޫސަރިން';
$string['uubulknew'] = 'އައު ޔޫސަރުން';
$string['uubulkupdated'] = 'އަޕްޑޭޓްކުރެވިފަ ހުރި ޔޫސަރުން';
$string['uucoursedefaultrole'] = 'ޑީފޯލްޓު ކޯސް ރޯލު';
$string['uucsvline'] = 'CSV ލައިން';
$string['uunoemailduplicates'] = 'އީމެއިލް އެޑްރެސް ޑުޕްލިކޭޓް ނުކުރެވޭގޮތަށް ހަދަން';
$string['uuoptype'] = 'އަޕްލޯޑުގެ ވައްތަރު';
$string['uuoptype_addnew'] = 'އިތުރުކުރަންވީ އައު ޔޫސަރުން އެކަނި، މިހާރު ހުރި ޔޫސަރުން ދޫކޮށްލާ';
$string['uuoptype_addupdate'] = 'މިހާރު ހުރި ޔޫސަރުން އަޕްޑޭޓްކޮށް އައު ޔޫސަރުން އަޕްޑޭޓްކުރަން';
$string['uuoptype_update'] = 'އަޕްޑޭޓްކުރަންވީ ހަމައެކަނި މިހާރު ހުރި ޔޫސަރުން';
$string['uupasswordnew'] = 'އައުޔޫސަރުގެ ޕާސްވޯޑު';
$string['uupasswordold'] = 'މިހާރު ހުރި ޔޫސަރުގެ ޕާސްވޯޑު';
$string['uuupdatetype'] = 'މިހާރު ހުރި ޔޫސަރުގެ ތަފްޞީލް';
$string['validateerror'] = 'މި އަދަދު ކަމަކުނުދިޔަ';
$string['warningcurrentsetting'] = 'މިހާރުގެ އަދަދު ކަމަކުނުދޭ: $a';
$string['clamfailureonupload'] = ''; // ORPHANED
$string['configerrorlevel'] = ''; // ORPHANED
$string['configexperimentalsplitrestore'] = ''; // ORPHANED
$string['configextendedusernamechars'] = ''; // ORPHANED
$string['configextramemorylimit'] = ''; // ORPHANED
$string['configfilterall'] = ''; // ORPHANED
$string['configfiltermatchoneperpage'] = ''; // ORPHANED
$string['configfiltermatchonepertext'] = ''; // ORPHANED
$string['configfilteruploadedfiles'] = ''; // ORPHANED
$string['configforcelogin'] = ''; // ORPHANED
$string['configforceloginforprofiles'] = ''; // ORPHANED
$string['configframename'] = ''; // ORPHANED
$string['configfrontpage'] = ''; // ORPHANED
$string['configfrontpageloggedin'] = ''; // ORPHANED
$string['configfullnamedisplay'] = ''; // ORPHANED
$string['configgdversion'] = ''; // ORPHANED
$string['configgeoipfile'] = ''; // ORPHANED
$string['configgetremoteaddrconf'] = ''; // ORPHANED
$string['configgooglemapkey'] = ''; // ORPHANED
$string['configgradebookroles'] = ''; // ORPHANED
$string['configgradeexport'] = ''; // ORPHANED
$string['configguestroleid'] = ''; // ORPHANED
$string['confighiddenuserfields'] = ''; // ORPHANED
$string['confighideactivitytypenavlink'] = ''; // ORPHANED
$string['confightmleditor'] = ''; // ORPHANED
$string['configidnumber'] = ''; // ORPHANED
$string['configintcachemax'] = ''; // ORPHANED
$string['configintro'] = ''; // ORPHANED
$string['configintroadmin'] = ''; // ORPHANED
$string['configintrosite'] = ''; // ORPHANED
$string['configintrotimezones'] = ''; // ORPHANED
$string['configiplookup'] = ''; // ORPHANED
$string['configkeeptagnamecase'] = ''; // ORPHANED
$string['configlang'] = ''; // ORPHANED
$string['configlangcache'] = ''; // ORPHANED
$string['configlangdir'] = ''; // ORPHANED
$string['configlanglist'] = ''; // ORPHANED
$string['configlangmenu'] = ''; // ORPHANED
$string['configlatinexcelexport'] = ''; // ORPHANED
$string['configlocale'] = ''; // ORPHANED
$string['configloginhttps'] = ''; // ORPHANED
$string['configloglifetime'] = ''; // ORPHANED
$string['configlongtimenosee'] = ''; // ORPHANED
$string['configlookahead'] = ''; // ORPHANED
$string['configmailnewline'] = ''; // ORPHANED
$string['configmaxbytes'] = ''; // ORPHANED
$string['configsitemaxcategorydepth'] = ''; // ORPHANED
$string['configsitemaxcategorydepthhelp'] = ''; // ORPHANED
$string['configmaxeditingtime'] = ''; // ORPHANED
$string['configmemcachedhosts'] = ''; // ORPHANED
$string['configmemcachedpconn'] = ''; // ORPHANED
$string['configmessaging'] = ''; // ORPHANED
$string['configminpassworddigits'] = ''; // ORPHANED
$string['configminpasswordlength'] = ''; // ORPHANED
$string['configminpasswordlower'] = ''; // ORPHANED
$string['configminpasswordnonalphanum'] = ''; // ORPHANED
$string['configminpasswordupper'] = ''; // ORPHANED
$string['configmymoodleredirect'] = ''; // ORPHANED
$string['configmycoursesperpage'] = ''; // ORPHANED
$string['confignodefaultuserrolelists'] = ''; // ORPHANED
$string['confignonmetacoursesyncroleids'] = ''; // ORPHANED
$string['confignoreplyaddress'] = ''; // ORPHANED
$string['confignotifyloginfailures'] = ''; // ORPHANED
$string['confignotifyloginthreshold'] = ''; // ORPHANED
$string['confignotloggedinroleid'] = ''; // ORPHANED
$string['configpasswordpolicy'] = ''; // ORPHANED
$string['configopentogoogle'] = ''; // ORPHANED
$string['configoverride'] = ''; // ORPHANED
$string['configpathtoclam'] = ''; // ORPHANED
$string['configpathtodu'] = ''; // ORPHANED
$string['configperfdebug'] = ''; // ORPHANED
$string['configprofilesforenrolledusersonly'] = ''; // ORPHANED
$string['configprotectusernames'] = ''; // ORPHANED
$string['configproxyhost'] = ''; // ORPHANED
$string['configproxypassword'] = ''; // ORPHANED
$string['configproxyport'] = ''; // ORPHANED
$string['configproxyuser'] = ''; // ORPHANED
$string['configproxytype'] = ''; // ORPHANED
$string['configquarantinedir'] = ''; // ORPHANED
$string['configcronclionly'] = ''; // ORPHANED
$string['configrcache'] = ''; // ORPHANED
$string['configrcachettl'] = ''; // ORPHANED
$string['configrecaptchaprivatekey'] = ''; // ORPHANED
$string['configrecaptchapublickey'] = ''; // ORPHANED
$string['configrequestedstudentname'] = ''; // ORPHANED
$string['configrequestedstudentsname'] = ''; // ORPHANED
$string['configrequestedteachername'] = ''; // ORPHANED
$string['configrequestedteachersname'] = ''; // ORPHANED
$string['configrestrictbydefault'] = ''; // ORPHANED
$string['configrestrictmodulesfor'] = ''; // ORPHANED
$string['configrunclamavonupload'] = ''; // ORPHANED
$string['configrunclamonupload'] = ''; // ORPHANED
$string['configsectioninterface'] = ''; // ORPHANED
$string['configsectionmaintenance'] = ''; // ORPHANED
$string['configsecureforms'] = ''; // ORPHANED
$string['configsendcoursewelcomemessage'] = ''; // ORPHANED
$string['configsessioncookie'] = ''; // ORPHANED
$string['configsessioncookiedomain'] = ''; // ORPHANED
$string['configsessioncookiepath'] = ''; // ORPHANED
$string['configsessiontimeout'] = ''; // ORPHANED
$string['configshowblocksonmodpages'] = ''; // ORPHANED
$string['configshowsiteparticipantslist'] = ''; // ORPHANED
$string['configsitemailcharset'] = ''; // ORPHANED
$string['configsitepolicy'] = ''; // ORPHANED
$string['configslasharguments'] = ''; // ORPHANED
$string['configsmartpix'] = ''; // ORPHANED
$string['configsmtpmaxbulk'] = ''; // ORPHANED
$string['configsmtphosts'] = ''; // ORPHANED
$string['configsmtpuser'] = ''; // ORPHANED
$string['configstatscatdepth'] = ''; // ORPHANED
$string['configstatsfirstrun'] = ''; // ORPHANED
$string['configstatsmaxruntime'] = ''; // ORPHANED
$string['configstatsmaxruntime2'] = ''; // ORPHANED
$string['configstatsmaxruntime3'] = ''; // ORPHANED
$string['configstatsruntimedays'] = ''; // ORPHANED
$string['configstatsruntimestart'] = ''; // ORPHANED
$string['configstatsuserthreshold'] = ''; // ORPHANED
$string['configstripalltitletags'] = ''; // ORPHANED
$string['configsupportemail'] = ''; // ORPHANED
$string['configsupportname'] = ''; // ORPHANED
$string['configsupportpage'] = ''; // ORPHANED
$string['configteacherassignteachers'] = ''; // ORPHANED
$string['configtimezone'] = ''; // ORPHANED
$string['configunzip'] = ''; // ORPHANED
$string['configusetags'] = ''; // ORPHANED
$string['configvariables'] = ''; // ORPHANED
$string['configverifychangedemail'] = ''; // ORPHANED
$string['configwarning'] = ''; // ORPHANED
$string['configxmlstrictheaders'] = ''; // ORPHANED
$string['configzip'] = ''; // ORPHANED
$string['confirminstall'] = ''; // ORPHANED
$string['cookiehttponly'] = ''; // ORPHANED
$string['cookiesecure'] = ''; // ORPHANED
$string['country'] = ''; // ORPHANED
$string['courserequestnotify'] = ''; // ORPHANED
$string['courserequestnotifyemail'] = ''; // ORPHANED
$string['courserequestspending'] = ''; // ORPHANED
$string['coursesperpage'] = ''; // ORPHANED
$string['creatornewroleid'] = ''; // ORPHANED
$string['cronclionly'] = ''; // ORPHANED
$string['cronerrorpassword'] = ''; // ORPHANED
$string['cronremotepassword'] = ''; // ORPHANED
$string['cronwarning'] = ''; // ORPHANED
$string['ctyperecommended'] = ''; // ORPHANED
$string['ctyperequired'] = ''; // ORPHANED
$string['csvdelimiter'] = ''; // ORPHANED
$string['curlrecommended'] = ''; // ORPHANED
$string['customcheck'] = ''; // ORPHANED
$string['datarootsecuritywarning'] = ''; // ORPHANED
$string['dbmigrate'] = ''; // ORPHANED
$string['dbmigrateconnecerror'] = ''; // ORPHANED
$string['dbmigrateencodingerror'] = ''; // ORPHANED
$string['dbmigratepostgres'] = ''; // ORPHANED
$string['dbmigratewarning'] = ''; // ORPHANED
$string['dbmigratewarning2'] = ''; // ORPHANED
$string['dbmigrationdeprecateddb'] = ''; // ORPHANED
$string['dbmigrationdupfailed'] = ''; // ORPHANED
$string['dbsessions'] = ''; // ORPHANED
$string['debug'] = ''; // ORPHANED
$string['debugdisplay'] = ''; // ORPHANED
$string['debugsmtp'] = ''; // ORPHANED
$string['debugall'] = ''; // ORPHANED
$string['debugdeveloper'] = ''; // ORPHANED
$string['debugminimal'] = ''; // ORPHANED
$string['debugnone'] = ''; // ORPHANED
$string['debugnormal'] = ''; // ORPHANED
$string['defaultallowedmodules'] = ''; // ORPHANED
$string['defaultrequestcategory'] = ''; // ORPHANED
$string['deleteincompleteusers'] = ''; // ORPHANED
$string['deleteunconfirmed'] = ''; // ORPHANED
$string['density'] = ''; // ORPHANED
$string['denyemailaddresses'] = ''; // ORPHANED
$string['digestmailtime'] = ''; // ORPHANED
$string['disablecourseajax'] = ''; // ORPHANED
$string['disableuserimages'] = ''; // ORPHANED
$string['displayerrorswarning'] = ''; // ORPHANED
$string['displayloginfailures'] = ''; // ORPHANED
$string['docroot'] = ''; // ORPHANED
$string['editennotallowed'] = ''; // ORPHANED
$string['editingnoncorelangfile'] = ''; // ORPHANED
$string['editordictionary'] = ''; // ORPHANED
$string['editorhidebuttons'] = ''; // ORPHANED
$string['editorkillword'] = ''; // ORPHANED
$string['editorspellinghelp'] = ''; // ORPHANED
$string['editorspelling'] = ''; // ORPHANED
$string['enableajax'] = ''; // ORPHANED
$string['enablecalendarexport'] = ''; // ORPHANED
$string['enablecourserequests'] = ''; // ORPHANED
$string['enableglobalsearch'] = ''; // ORPHANED
$string['enablegroupings'] = ''; // ORPHANED
$string['enablehtmlpurifier'] = ''; // ORPHANED
$string['enablerecordcache'] = ''; // ORPHANED
$string['enablerssfeeds'] = ''; // ORPHANED
$string['enablestats'] = ''; // ORPHANED
$string['enabletrusttext'] = ''; // ORPHANED
$string['encoding'] = ''; // ORPHANED
$string['environmenterrortodo'] = ''; // ORPHANED
$string['environmenterrorupgrade'] = ''; // ORPHANED
$string['environmentok'] = ''; // ORPHANED
$string['environmentrecommendcustomcheck'] = ''; // ORPHANED
$string['environmentrecommendinstall'] = ''; // ORPHANED
$string['environmentrecommendversion'] = ''; // ORPHANED
$string['environmentrequirecustomcheck'] = ''; // ORPHANED
$string['environmentrequireinstall'] = ''; // ORPHANED
$string['environmentrequireversion'] = ''; // ORPHANED
$string['environmentxmlerror'] = ''; // ORPHANED
$string['errorwithsettings'] = ''; // ORPHANED
$string['everyonewhocan'] = ''; // ORPHANED
$string['experimentalsplitrestore'] = ''; // ORPHANED
$string['extendedusernamechars'] = ''; // ORPHANED
$string['extramemorylimit'] = ''; // ORPHANED
$string['filestoredinhelp'] = ''; // ORPHANED
$string['filterall'] = ''; // ORPHANED
$string['filtermatchoneperpage'] = ''; // ORPHANED
$string['filtermatchonepertext'] = ''; // ORPHANED
$string['filtersettingsgeneral'] = ''; // ORPHANED
$string['filteruploadedfiles'] = ''; // ORPHANED
$string['forceloginforprofiles'] = ''; // ORPHANED
$string['forcetimezone'] = ''; // ORPHANED
$string['framename'] = ''; // ORPHANED
$string['frontpageloggedin'] = ''; // ORPHANED
$string['fullnamedisplay'] = ''; // ORPHANED
$string['gdrecommended'] = ''; // ORPHANED
$string['gdversion'] = ''; // ORPHANED
$string['geoipfile'] = ''; // ORPHANED
$string['getremoteaddrconf'] = ''; // ORPHANED
$string['globalsquoteswarning'] = ''; // ORPHANED
$string['globalswarning'] = ''; // ORPHANED
$string['googlemapkey'] = ''; // ORPHANED
$string['gradeexport'] = ''; // ORPHANED
$string['helpadminseesall'] = ''; // ORPHANED
$string['helpcalendarsettings'] = ''; // ORPHANED
$string['helpforcetimezone'] = ''; // ORPHANED
$string['helpsitemaintenance'] = ''; // ORPHANED
$string['helpupcominglookahead'] = ''; // ORPHANED
$string['helpupcomingmaxevents'] = ''; // ORPHANED
$string['helpweekenddays'] = ''; // ORPHANED
$string['hiddenuserfields'] = ''; // ORPHANED
$string['hideactivitytypenavlink'] = ''; // ORPHANED
$string['iconvrecommended'] = ''; // ORPHANED
$string['importlangreminder'] = ''; // ORPHANED
$string['importtimezones'] = ''; // ORPHANED
$string['importtimezonescount'] = ''; // ORPHANED
$string['importtimezonesfailed'] = ''; // ORPHANED
$string['includemoduleuserdata'] = ''; // ORPHANED
$string['incompatibleblocks'] = ''; // ORPHANED
$string['intcachemax'] = ''; // ORPHANED
$string['invalidsection'] = ''; // ORPHANED
$string['invaliduserchangeme'] = ''; // ORPHANED
$string['iplookup'] = ''; // ORPHANED
$string['iplookupinfo'] = ''; // ORPHANED
$string['iplookupmaxmindnote'] = ''; // ORPHANED
$string['iplookupnetgeonote'] = ''; // ORPHANED
$string['keeptagnamecase'] = ''; // ORPHANED
$string['lang16notify'] = ''; // ORPHANED
$string['langcache'] = ''; // ORPHANED
$string['langmasterpackage'] = ''; // ORPHANED
$string['langmasterenglish'] = ''; // ORPHANED
$string['langlocalpackage'] = ''; // ORPHANED
$string['langimport'] = ''; // ORPHANED
$string['langimportdisabled'] = ''; // ORPHANED
$string['langnoeditenglish'] = ''; // ORPHANED
$string['langpackmaintaining'] = ''; // ORPHANED
$string['langpackwillbeupdated'] = ''; // ORPHANED
$string['langrmyourself'] = ''; // ORPHANED
$string['latexpreamble'] = ''; // ORPHANED
$string['latexsettings'] = ''; // ORPHANED
$string['latinexcelexport'] = ''; // ORPHANED
$string['localstringcustomization'] = ''; // ORPHANED
$string['loginhttps'] = ''; // ORPHANED
$string['loglifetime'] = ''; // ORPHANED
$string['longtimenosee'] = ''; // ORPHANED
$string['longtimewarning'] = ''; // ORPHANED
$string['mailnewline'] = ''; // ORPHANED
$string['maintfileopenerror'] = ''; // ORPHANED
$string['maintinprogress'] = ''; // ORPHANED
$string['mbstringrecommended'] = ''; // ORPHANED
$string['mediapluginavi'] = ''; // ORPHANED
$string['mediapluginflv'] = ''; // ORPHANED
$string['maintenancemode'] = ''; // ORPHANED
$string['mediapluginmov'] = ''; // ORPHANED
$string['mediapluginmp3'] = ''; // ORPHANED
$string['mediapluginmpg'] = ''; // ORPHANED
$string['mediapluginram'] = ''; // ORPHANED
$string['mediapluginrm'] = ''; // ORPHANED
$string['mediapluginrpm'] = ''; // ORPHANED
$string['mediapluginswf'] = ''; // ORPHANED
$string['mediapluginswfnote'] = ''; // ORPHANED
$string['mediapluginwmv'] = ''; // ORPHANED
$string['memcachedhosts'] = ''; // ORPHANED
$string['memcachedpconn'] = ''; // ORPHANED
$string['messaging'] = ''; // ORPHANED
$string['minpassworddigits'] = ''; // ORPHANED
$string['minpasswordlower'] = ''; // ORPHANED
$string['minpasswordnonalphanum'] = ''; // ORPHANED
$string['minpasswordupper'] = ''; // ORPHANED
$string['missinglangparent'] = ''; // ORPHANED
$string['mnetrestore_extusers'] = ''; // ORPHANED
$string['mnetrestore_extusers_admin'] = ''; // ORPHANED
$string['mnetrestore_extusers_mismatch'] = ''; // ORPHANED
$string['mnetrestore_extusers_noadmin'] = ''; // ORPHANED
$string['mnetrestore_extusers_switchuserauth'] = ''; // ORPHANED
$string['multilangforceold'] = ''; // ORPHANED
$string['multilangupgrade'] = ''; // ORPHANED
$string['multilangupgradeinfo'] = ''; // ORPHANED
$string['multilangupgradenotice'] = ''; // ORPHANED
$string['mustenablestats'] = ''; // ORPHANED
$string['mysql416bypassed'] = ''; // ORPHANED
$string['mysql416required'] = ''; // ORPHANED
$string['nodefaultuserrolelists'] = ''; // ORPHANED
$string['nonewsettings'] = ''; // ORPHANED
$string['nonmetacoursesyncroleids'] = ''; // ORPHANED
$string['notifyloginfailures'] = ''; // ORPHANED
$string['notifyloginthreshold'] = ''; // ORPHANED
$string['notloggedinroleid'] = ''; // ORPHANED
$string['opensslrecommended'] = ''; // ORPHANED
$string['opentogoogle'] = ''; // ORPHANED
$string['optionalmaintenancemessage'] = ''; // ORPHANED
$string['passwordpolicy'] = ''; // ORPHANED
$string['pathconvert'] = ''; // ORPHANED
$string['pathdvips'] = ''; // ORPHANED
$string['pathlatex'] = ''; // ORPHANED
$string['pathtoclam'] = ''; // ORPHANED
$string['pathtodu'] = ''; // ORPHANED
$string['pathtopgdump'] = ''; // ORPHANED
$string['pathtopgdumpdesc'] = ''; // ORPHANED
$string['pathtopgdumpinvalid'] = ''; // ORPHANED
$string['pathtopsql'] = ''; // ORPHANED
$string['pathtopsqldesc'] = ''; // ORPHANED
$string['pathtopsqlinvalid'] = ''; // ORPHANED
$string['pathtounzip'] = ''; // ORPHANED
$string['pathtozip'] = ''; // ORPHANED
$string['perfdebug'] = ''; // ORPHANED
$string['pgcluster'] = ''; // ORPHANED
$string['pgclusterdescription'] = ''; // ORPHANED
$string['php50restricted'] = ''; // ORPHANED
$string['phpfloatproblem'] = ''; // ORPHANED
$string['pleaseregister'] = ''; // ORPHANED
$string['pleaserefreshregistration'] = ''; // ORPHANED
$string['profileconfirmcategorydeletion'] = ''; // ORPHANED
$string['profileconfirmfielddeletion'] = ''; // ORPHANED
$string['profilecreatenewfield'] = ''; // ORPHANED
$string['profiledefaultchecked'] = ''; // ORPHANED
$string['profileeditfield'] = ''; // ORPHANED
$string['profilefield'] = ''; // ORPHANED
$string['profilefieldcolumns'] = ''; // ORPHANED
$string['profilefieldrows'] = ''; // ORPHANED
$string['profilefields'] = ''; // ORPHANED
$string['profilefieldsize'] = ''; // ORPHANED
$string['profilefieldtypecheckbox'] = ''; // ORPHANED
$string['profilefieldtypemenu'] = ''; // ORPHANED
$string['profilefieldtypetext'] = ''; // ORPHANED
$string['profilefieldtypetextarea'] = ''; // ORPHANED
$string['profilefieldmaxlength'] = ''; // ORPHANED
$string['profilelocked'] = ''; // ORPHANED
$string['profilemenudefaultnotinoptions'] = ''; // ORPHANED
$string['profilemenunooptions'] = ''; // ORPHANED
$string['profilemenuoptions'] = ''; // ORPHANED
$string['profilespecificsettings'] = ''; // ORPHANED
$string['proxyhost'] = ''; // ORPHANED
$string['proxyport'] = ''; // ORPHANED
$string['proxypassword'] = ''; // ORPHANED
$string['proxyuser'] = ''; // ORPHANED
$string['proxytype'] = ''; // ORPHANED
$string['qtyperqpwillberemoved'] = ''; // ORPHANED
$string['qtyperqpwillberemovedanyway'] = ''; // ORPHANED
$string['quarantinedir'] = ''; // ORPHANED
$string['questioncwqpfscheck'] = ''; // ORPHANED
$string['questioncwqpfsok'] = ''; // ORPHANED
$string['rcache'] = ''; // ORPHANED
$string['rcachettl'] = ''; // ORPHANED
$string['recaptchapublickey'] = ''; // ORPHANED
$string['recaptchaprivatekey'] = ''; // ORPHANED
$string['releasenoteslink'] = ''; // ORPHANED
$string['remotelangnotavailable'] = ''; // ORPHANED
$string['renameerrors'] = ''; // ORPHANED
$string['requiredtemplate'] = ''; // ORPHANED
$string['restrictbydefault'] = ''; // ORPHANED
$string['restrictmodulesfor'] = ''; // ORPHANED
$string['reverseproxy'] = ''; // ORPHANED
$string['riskconfig'] = ''; // ORPHANED
$string['riskconfigshort'] = ''; // ORPHANED
$string['riskmanagetrust'] = ''; // ORPHANED
$string['riskmanagetrustshort'] = ''; // ORPHANED
$string['riskpersonalshort'] = ''; // ORPHANED
$string['riskspam'] = ''; // ORPHANED
$string['riskspamshort'] = ''; // ORPHANED
$string['riskxss'] = ''; // ORPHANED
$string['riskxssshort'] = ''; // ORPHANED
$string['rowpreviewnum'] = ''; // ORPHANED
$string['rssglobaldisabled'] = ''; // ORPHANED
$string['runclamavonupload'] = ''; // ORPHANED
$string['sectionerror'] = ''; // ORPHANED
$string['secureforms'] = ''; // ORPHANED
$string['serverchecks'] = ''; // ORPHANED
$string['serverlimit'] = ''; // ORPHANED
$string['sessioncookie'] = ''; // ORPHANED
$string['sessioncookiedomain'] = ''; // ORPHANED
$string['sessioncookiepath'] = ''; // ORPHANED
$string['simplexmlrequired'] = ''; // ORPHANED
$string['sitemailcharset'] = ''; // ORPHANED
$string['sitemaintenanceoff'] = ''; // ORPHANED
$string['sitemaintenanceon'] = ''; // ORPHANED
$string['sitemaintenancewarning'] = ''; // ORPHANED
$string['sitepolicy'] = ''; // ORPHANED
$string['sitesectionhelp'] = ''; // ORPHANED
$string['slasharguments'] = ''; // ORPHANED
$string['smartpix'] = ''; // ORPHANED
$string['smtphosts'] = ''; // ORPHANED
$string['smtpmaxbulk'] = ''; // ORPHANED
$string['smtppass'] = ''; // ORPHANED
$string['smtpuser'] = ''; // ORPHANED
$string['spamcleaner'] = ''; // ORPHANED
$string['statscatdepth'] = ''; // ORPHANED
$string['statsfirstrun'] = ''; // ORPHANED
$string['statsmaxruntime'] = ''; // ORPHANED
$string['statsruntimedays'] = ''; // ORPHANED
$string['statsruntimestart'] = ''; // ORPHANED
$string['statsuserthreshold'] = ''; // ORPHANED
$string['stickyblocksduplicatenotice'] = ''; // ORPHANED
$string['stickyblockspagetype'] = ''; // ORPHANED
$string['supportemail'] = ''; // ORPHANED
$string['supportname'] = ''; // ORPHANED
$string['supportpage'] = ''; // ORPHANED
$string['switchlang'] = ''; // ORPHANED
$string['tabselectedtofront'] = ''; // ORPHANED
$string['tabselectedtofronttext'] = ''; // ORPHANED
$string['tokenizerrecommended'] = ''; // ORPHANED
$string['unattendedoperation'] = ''; // ORPHANED
$string['unicodeupgradenotice'] = ''; // ORPHANED
$string['unicoderecommended'] = ''; // ORPHANED
$string['unicoderequired'] = ''; // ORPHANED
$string['uploadpicture_baduserfield'] = ''; // ORPHANED
$string['uploadpicture_invalidfilename'] = ''; // ORPHANED
$string['uploadpicture_userfield'] = ''; // ORPHANED
$string['uploadpicture_usernotfound'] = ''; // ORPHANED
$string['upgradeforumread'] = ''; // ORPHANED
$string['upgradeforumreadinfo'] = ''; // ORPHANED
$string['upgradelogs'] = ''; // ORPHANED
$string['upgradelogsinfo'] = ''; // ORPHANED
$string['upgradesettingsintro'] = ''; // ORPHANED
$string['upgradesure'] = ''; // ORPHANED
$string['upwards'] = ''; // ORPHANED
$string['usetags'] = ''; // ORPHANED
$string['uulegacy1role'] = ''; // ORPHANED
$string['uulegacy2role'] = ''; // ORPHANED
$string['uulegacy3role'] = ''; // ORPHANED
$string['uuoptype_addinc'] = ''; // ORPHANED
$string['uupreprocessedcount'] = ''; // ORPHANED
$string['uuupdateall'] = ''; // ORPHANED
$string['uuupdatefromfile'] = ''; // ORPHANED
$string['uuupdatemissing'] = ''; // ORPHANED
$string['verifychangedemail'] = ''; // ORPHANED
$string['webproxy'] = ''; // ORPHANED
$string['webproxyinfo'] = ''; // ORPHANED
$string['xmlrpcrecommended'] = ''; // ORPHANED
$string['xmlstrictheaders'] = ''; // ORPHANED
$string['ziprequired'] = ''; // ORPHANED

?>
