<?PHP


$string['accesscontrol'] = 'އެކްސެސް ކޮންޓްރޯލް';
$string['actionaftercorrectanswer'] = 'ރަނގަޅު ޖަވާބަށްފަހު ކުރަންވީ ކަންތައް';
$string['actions'] = 'އެކްޝަންތަށް';
$string['activitylink'] = 'ހަރަކާތަކަށް ގުޅުވާލަން';
$string['activitylinkname'] = 'ދަންވީ: $a';
$string['addabranchtable'] = 'ބްރާންޗް ޓޭބަލެއް އިތުރުކުރުމަށް';
$string['addanendofbranch'] = 'ބްރާންޗެއްގެ ނިމުން އިތުރު ކުރޭ';
$string['addaquestionpage'] = 'ސުވާލު ގަނޑެއް އިތުރުކުރަން';
$string['addaquestionpagehere'] = 'މިތަނަށް ސުވާލު ގަނޑެއް އިތުރުކުރަން';
$string['addcluster'] = 'ކުލަސްޓަރެއް އިތުރުކުރަން';
$string['addedabranchtable'] = 'ބްރާންޗް ޓޭބަލެއް އިތުރުކުރެވިއްޖެ';
$string['addedanendofbranch'] = 'ބްރާންޗެއްގެ ނިމުން އިތުރުށްފި';
$string['addedaquestionpage'] = 'ސުވާލު ގަނޑެއް އިތުރުކުރެވިއްޖެ';
$string['addedcluster'] = 'ކުލަސްޓަރެއް އިތުރުކުރެވިއްޖެ';
$string['addedendofcluster'] = 'ކްލަސްޓަރެއްގެ ނިމުން އިތުރުކޮށްފި';
$string['addendofcluster'] = 'ކްލަސްޓަރެއްގެ ނިމުން އިތުރު ކުރޭ';
$string['addpage'] = 'ގަނޑެއް އިތުރުކުރެވިއްޖެ';
$string['anchortitle'] = 'މައިގަނޑުގެ ފެށުން';
$string['and'] = 'އަދި';
$string['answer'] = 'ޖަވާބު';
$string['answeredcorrectly'] = 'ރަނގަޅަށް ޖަވާބުދެވިއްޖެ';
$string['arrangebuttonshorizontally'] = 'ބްރާންޗު ބަޓަންތަައް ހުރަހަށް އަތުރާ';
$string['attempt'] = 'ކުރި މަސައްކަތް: $a';
$string['attempts'] = 'ކުރި މަސައްކަތްތައް';
$string['attemptsdeleted'] = 'ކުރި މަސައްކަތްތައް ފުހެލާ';
$string['attemptsremaining'] = 'ތިބާއަށް ބާކީ $a އެޓެމްޕްޓު އެބައިން';
$string['available'] = 'ލިބެން ހުންނާނީ';
$string['averagescore'] = 'އެވުރެޖު ސްކޯރ';
$string['averagetime'] = 'އެވުރެޖު ވަޤުތު';
$string['branchtable'] = 'ބްރާންޗު ޓޭބަލް';
$string['cancel'] = 'ކެންސަލް';
$string['canretake'] = '$a އަލުން ނެގިދާނެ';
$string['casesensitive'] = 'ރެގިއުލަރ އެކްސްޕްރެޝަން ބޭނުންކުރޭ';
$string['checkbranchtable'] = 'ބްރާންޗު ޓޭބަލް އެއްކުރޭ';
$string['checkedthisone'] = 'މި ޗެކު ކޮށްލާ';
$string['checknavigation'] = 'ނެވިގޭޝަން ޗެކު ކޮށްލާ';
$string['checkquestion'] = 'ސުވާލު ޗެކްކުރަން';
$string['classstats'] = 'ކުލާހުގެ ސްޓެޓިސްޓިކްސް';
$string['clicktodownload'] = 'ފައިލް ޑައުންލޯޑް ކުރުމަށް ތިރީގައިވާ ލިންކަށް ފިތާލާ';
$string['clicktopost'] = 'އެންމެ މަތީ ސްކޯތަކުގެ ލިސްޓަށް ކަލޭގެ ގްރޭޑް ލުމަށް މިތަނަށް ފިތާލާ';
$string['clusterjump'] = 'ކްލަސްޓާއެއްގެ ތެރޭގައިވާ ނުފެންނަ ސުވާލެއް';
$string['clustertitle'] = 'ކްލަސްޓާ';
$string['collapsed'] = 'ކުޑަ ކޮށްލައިފައި';
$string['comments'] = 'ކަލޭގެ ކޮމެންޓްތައް';
$string['completed'] = 'ނިމިފަ';
$string['completederror'] = 'ފިލާވަޅު ނިމަފަ';
$string['completethefollowingconditions'] = 'ކުރިައަށް ގެންދިއުމުގެ ކުރިން <b>$a</b> ފިލާވަޅުގައިވާ ޝަރުތުތައް ފުރިހަމަ ކުރަން ޖެހޭނެ.';
$string['conditionsfordependency'] = 'ބަރޯސާ ކުރުމުގެ ޝަރުތުތައް';
$string['confirmdeletionofthispage'] = 'މި ގަނޑު ފުހެލުމަށް ފަހުބަސް ދީ';
$string['congratulations'] = 'މަރުޚަބާ - ފިލާވަޅުގެ ނިމުމާ ހަމަވެއްޖެ';
$string['continue'] = 'ކުރިޔަށް';
$string['continuetoanswer'] = 'ޖަވާބުތައް ބަދަލުކުރަމުން ގެންދަން';
$string['correctanswerjump'] = 'ރަނގަޅު ސުވާލަށް ދޭ';
$string['correctanswerscore'] = 'ރަނގަޅު ޖަވާބުގެ ސްކޯރ';
$string['correctresponse'] = 'ރަނގަޅު އިޖާބައެއް';
$string['credit'] = 'ކުރެޑިޓް';
$string['customscoring'] = 'އަމިއްލަ ސްކޯއެއް ދިނުން';
$string['deadline'] = 'ޑެޑްލައިން';
$string['defaultessayresponse'] = 'ކަލޭގެ މަޒުމޫނު ގްރޭޑްކުރަނީ ކޯހުގެ އިންސްޓްރަކްޓަރ';
$string['deleteallattempts'] = 'ހުރިހާ ފިލާވަޅަކަށް ކުި މަސަ';
$string['deletedefaults'] = '$a x ލެސަން ޑީފޯލްޓު ފުހެލައިފި';
$string['deletedpage'] = 'ޕޭޖް ފުހެލެވިއްޖެ';
$string['deleting'] = 'ފުހެވެނީ';
$string['deletingpage'] = 'ޞަފްޙާ $a ފުހެލަނީ';
$string['dependencyon'] = 'ބަރޯސާވަނީ';
$string['description'] = 'މަޢުލޫމާތު';
$string['detailedstats'] = 'ތަފާސްހިސާބުތައް ތަފްޞީލުކޮށް';
$string['didnotanswerquestion'] = 'މި ސުވާލަށް ޖަވާބެއް ދެވިފަނެތް';
$string['didnotreceivecredit'] = 'ކްރެޑިޓެއް ނުލިބެ';
$string['displaydefaultfeedback'] = 'ދީފޯލްޓް ފީޑްބެކް ދައްކާ';
$string['displayhighscores'] = 'އެންމެ މަތީ ސްކޯތައް ދައްކާ';
$string['displayinleftmenu'] = 'ވައަތްފަޅީގެ މެނޫގައި ދައްކާ';
$string['displayleftif'] = 'ވައަތް މެނޫ ދައްކަންވީ ހަމައެކަނި ފަހަތުގައި މިވާ ގުރޭޑަށްވުރެ މަތިވާނަމަ:';
$string['displayleftmenu'] = 'ވައަތްފަޅި މެނޫ ދައްކާ';
$string['displayofgrade'] = 'ގުރޭޑު ދެއްކުން (ހަމައެކަނި ދަރިވަރުންނަށް)';
$string['displayreview'] = 'ރިވިއު ބަޓަން ދައްކާ';
$string['displayscorewithoutessays'] = 'ތިބާގެ ސްކޯ އަކީ: $a->score ($a->grade ން)';
$string['edit'] = 'ބަދަލުކުރޭ';
$string['editlessonsettings'] = 'ފިލާވަޅުގެ ސެޓިންތަކަށް ބަދަލު ގެނޭ';
$string['editpagecontent'] = 'ޞަފްޙާގައި ހިމެނޭ ބައިތަށް ބަދަލު ގެނޭ';
$string['email'] = 'އީމެއިލް';
$string['emailallgradedessays'] = 'އީމެއިލް ކުރޭ ހުރިހާ <br />ގުރޭޑު ކޮށްފައިވާ މަޒުމޫނުތައް';
$string['emailgradedessays'] = 'ގުރޭޑު ކޮށްފައިވާ މަޒުމޫނުތައް އީމެއިލް ކުރޭ';
$string['emailsuccess'] = 'ކާމިޔާބުކަމާއެކީ އީމެއިލް ފޮނުވިއްޖެ';
$string['endofbranch'] = 'ބްރާންޗުގެ ނިމުން';
$string['endofclustertitle'] = 'ކްލަސްޓަރުގެ ނިމުން';
$string['endoflesson'] = 'ފިލާވަޅުގެ ނިމުން';
$string['enteredthis'] = 'ލިޔުނީ މި.';
$string['entername'] = 'އެންމެ މަތީ ސްކޯތަކުގެ ލިސްޓަށް ވަނަމެއް ދީ';
$string['enterpassword'] = 'ޕާސްވޯޑު ލިޔޭ';
$string['eolstudentoutoftime'] = 'ސަމާލު: މި ފިލާވަޅަށް ކަނޑައެޅިފައިވާ ވަގުތަށްވުރެ އިތުރަށް ތިބާ އަށް ކުރިއަށް ގެންދެވިއްޖެ. އެންމެ ފަހު ޖަވާބު ދީފައިވަނީ ވަގުތު ހަމަވުމަށްފަހު ކަމުގައި ވަނީ ނަމަ އެ ޖަވާބެއް ނުހިމެނޭނެ.';
$string['eolstudentoutoftimenoanswers'] = 'ކަލޭ އެއްވެސް ސުވާލަކަށް ޖަވާބެއް ނުދޭ. ލިބިފަ ސްކޯރ އަކީ 0.';
$string['essay'] = 'މަޒުމޫނު';
$string['essayemailsubject'] = 'ތިބާގެ $a ސުވާލުގެ ގުރޭޑު';
$string['essays'] = 'މަޒުމޫނުތައް';
$string['essayscore'] = 'މަޒުމޫނުގެ ސްކޯރ';
$string['fileformat'] = 'ފައިލްގެ ފޯރމެޓް';
$string['firstanswershould'] = 'ފުރަތަމަ ޖަވާބު \"ރަނގަޅު\" ޞަފްޙާއަށް ދާންޖެހޭނެ.';
$string['flowcontrol'] = 'ފްލޯރ ކޮންޓްރޯލް';
$string['full'] = 'ބޮޑުކޮށްފައި';
$string['general'] = 'އާންމު';
$string['grade'] = 'ގްރޭޑް';
$string['gradebetterthan'] = '(&#37;) ވުރެން ގުރޭޑު ރަނގަޅު';
$string['gradebetterthanerror'] = '$a އިންސައްތަ އަށްވުރެ ރަނގަޅު ގުރޭޑެއް ހޯދާ';
$string['gradeessay'] = 'މަޒުމޫނު ސުވާލުތައް ގުރޭޑު ކުރޭ (ގުރޭޑު ނުކޮށް $a->notgradedcount އަދި ނުފޮނުވައި $a->notsentcount)';
$string['gradeis'] = 'ގުރޭޑަކީ $a';
$string['gradeoptions'] = 'ގްރޭޑު އޮޕްޝަންތައް';
$string['handlingofretakes'] = 'އަލުން ނަގާ އެއްޗެހި ބެލެހެއްޓުން';
$string['havenotgradedyet'] = 'އަދި ގުރޭޑެއް ނުކުރޭ';
$string['here'] = 'މިތާ';
$string['highscore'] = 'އެންމެ މަތީ ސްކޯރ';
$string['highscores'] = 'އެންމެ މަތީ ސްކޯރތައް';
$string['hightime'] = 'ގިނަ ވަގުތު';
$string['importcount'] = '$a ސުވާލު އިމްޕޯޓު ކުރަނީ';
$string['importppt'] = 'ޕަވަރޕޮއިންޓް އިމްޕޯޓްކުރަން';
$string['importquestions'] = 'ސުވާލުތައް އިމްޕޯޓުކުރަން';
$string['insertedpage'] = 'ޕޭޖް ލެވިއްޖެ';
$string['jump'] = 'ދާން';
$string['jumps'] = 'ދާން';
$string['jumpsto'] = '<em>$a</em> އަށް ދާން';
$string['leftduringtimed'] = 'ތިބާ ތި ހުއަޓާލީ ވަގުތު ކަނޑައެޅިފައިވާ ފިލާވަޅެއް ކުރިއަށް ދަނިކޮށް.<br /> އަލުން ފެށުމަށް ކުރިއަށް ފިތާލާ.';
$string['leftduringtimednoretake'] = 'ތިބާ ތި ހުއަޓާލީ ވަގުތު ކަނޑައެޅިފައިވާ ފިލާވަޅެއް ކުރިއަށް ދަނިކޮށް.<br /> ތިބާއަކަށް އަލުން އެ ފިލާވަޅެއް ނުނެގެނެ އަދި ކުރިއަކަށް ނުގެންދެވޭނެ.';
$string['lesson:edit'] = 'ފިލާވަޅުގެ މަސައްކަތަކަށް ބަދަލު ގެނޭ';
$string['lesson:manage'] = 'ފިލާވަޅުގެ މަސައްކަތައެއް ބަލަހައްޓަން';
$string['lessonattempted'] = 'މަސައްކަތް ކުރި ފިލާވަޅުތައް';
$string['lessonclosed'] = 'މި ފިލާވަޅު ބަންދުކޮށްފައިވަނީ $a.';
$string['lessoncloses'] = 'ފިލާވަޅު ބަންދުވާނީ';
$string['lessoncloseson'] = 'ފިލާވަޅު ބަންދުވާނީ $a';
$string['lessondefault'] = 'މި ފިލާވަޅުގެ ސެޓިންއަށް ޑީފޯލްޓު ސެޓިން ލާ';
$string['lessonformating'] = 'ފިލާވަޅު ފޯމެޓު ކުރުން';
$string['lessonmenu'] = 'ފިލާވަޅު މެނޫ';
$string['lessonnotready'] = 'އަދި މި ފިލާވަޅު ނެގޭކަށް ނެތް. $a އަށް ގުޅާ.';
$string['lessonopen'] = 'މި ފިލާވަޅު ހުޅުވޭނީ $a ގައި';
$string['lessonopens'] = 'ފިލާވަޅު ހުޅުވޭނީ';
$string['lessonpagelinkingbroken'] = 'ފުރަތަމަ ޞަފްޙާއެއް ނުފެނުނު. ހީވާ ގޮތުން ފިލާވަޅު އިން ޞަފްޙާގެ ލިންކުގައި މައްސަލައެއް އުޅޭ. އެޑްމިނިސްޓުރޭޓަރަކަށް ގުޅާ.';
$string['lessonstats'] = 'ފިލާވަޅުގެ ސްޓެޓިސްޓިކްސް';
$string['linkedmedia'] = 'ފިލާވަޅުގެ ތަފާސްހިސާބު';
$string['loginfail'] = 'ލޮގިން ފެއިލްވެއްޖެ. އަދި މަސައްކަތްކޮށްލައްވާ';
$string['lowscore'] = 'ދަށް ސްކޯ';
$string['lowtime'] = 'މަދު ވަގުތު';
$string['manualgrading'] = 'މަޒުމޫނުތައް ގްރޭޑްކުރުމަށް';
$string['matchesanswer'] = 'ޖަވާބާ ދިމާވޭ';
$string['maxhighscores'] = 'ހައި ސްކޯތައް ދައްކަންވީ އަދަދު';
$string['maximumnumberofanswersbranches'] = 'އެންމެ ގިނަ ޖަވާބު/ބްރާންޗުތައް';
$string['maximumnumberofattempts'] = 'މަސައްކަތް ކުރެވުނު އެންމެ ގިނަ ފަހަރު';
$string['maxtime'] = 'ކަނޑައެޅިފައިވާ ވަގުތު (މިނެޓު)';
$string['maxtimewarning'] = 'ފިލާވަޅު ނިންމުމަށް ބާކީ $a އެބަ އިން';
$string['mediaclose'] = 'ނިވާ ފިތް ދައްކާ';
$string['mediafile'] = 'ޕޮޕް-އަޕް ފައިލު ނުވަތަ ވެބް ޕޭޖު';
$string['mediafilepopup'] = 'ބަލާލަން މިތަނަށް ފިތާލާ';
$string['mediaheight'] = 'ވިންޑޯގެ އުސްމިން:';
$string['mediawidth'] = 'ފުޅާމިން:';
$string['minimumnumberofquestions'] = 'އެންމެ މަދުވެގެން ބެހެއްޓޭނެ ސުވާލު އަދަދު';
$string['missingname'] = 'ވަނަމެއް ލިޔުއްވާ';
$string['modattempts'] = 'ދަރިވަރުންގެ ރިވިއު ހެދޭގޮތަށް';
$string['modulename'] = 'ފިލާވަޅު';
$string['modulenameplural'] = 'ފިލާވަޅުތައް';
$string['movedpage'] = 'އެހެން ތަނަކަށް ބަދަލުކޮށްފައިވާ ޞަފްޙާތައް';
$string['movepagehere'] = 'ޞަފްޙާ މިތަނަށް ބަދަލު ކުރޭ';
$string['moving'] = 'ބަދަލުވަމުންދާ ޞަފްޙާ: $a';
$string['multianswer'] = 'ބައިވަރު ޖަވާބު';
$string['multipleanswer'] = 'ބައިވަރު ޖަވާބު';
$string['nameapproved'] = 'ނަން ފާސްވެއްޖެ';
$string['namereject'] = 'ފިލްޓަރުން ތިބާގެ ނަމެއް ޤަބޫލެއް ނުކުރި.<br /> އެހެން ނަމެއް މަސައްކަތް ކޮށްލާ.';
$string['nextpage'] = 'ދެން ޖެހިގެން އިން ގަނޑު';
$string['noanswer'] = 'ޖަވާބެއް ދެވިފައެއް ނެތް. ފަހަތަށް ގޮސް ޖަވާބެއް ދެއްވާ';
$string['noattemptrecordsfound'] = 'މަސައްކަތެއް ކުރެވިފައެއް ނެތް: ގުރޭޑު ދީފައެއް ނެތް';
$string['nobranchtablefound'] = 'ބުރާންޗު ޓޭބަލެއް ނެތް';
$string['nocommentyet'] = 'އަދި އެއްވެސް ކޮމެންޓެއް ދެވިފައެއް ނެތް';
$string['nocoursemods'] = 'އެއްވެސް ހަރަކާތެއް ނުފެނުނު';
$string['nocredit'] = 'ކުރެޑިޓެއް ނެތް';
$string['nodeadline'] = 'ވަކި މުއްދަތެއް ކަނޑައެޅިފައެއް ނެތް';
$string['nohighscores'] = 'ހައި ސްކޯއެއް ނެތް';
$string['nolessonattempts'] = 'މި ފިލާވަޅަށް އެއްވެސް ފަހަރަކު މަސައްކަތް ކުރެވިފައެއް ނެތް';
$string['nooneansweredcorrectly'] = 'އެއްވެސް ފަރާތަކުން ރަނގަޅު ޖަވާބެއް ދެވިފައެއް ނެތް';
$string['nooneansweredthisquestion'] = 'އެއްވެސް ފަރާތަކުންޖަވާބެއް ދީފައެއް ނެތް';
$string['noonehasanswered'] = 'އެއްވެސް މީހަކު އެއްވެސް ސުވާލަކަށް ޖަވާބު ދީފައެއް ނެތް';
$string['noretake'] = 'މި ފިލާވަޅު ދެވަނަ ފަހަރަކަށް ނުހުދޭނެ';
$string['notcompleted'] = 'ނުނިމި';
$string['notdefined'] = 'ބަޔާންނުވެ';
$string['notitle'] = 'ސުރުޚީއެއް ނެތް';
$string['or'] = 'ނުވަތަ';
$string['other'] = 'އެހެނިހެން';
$string['overview'] = 'އޯވަވިއު';
$string['pagecontents'] = 'ޕޭޖުގަ ހިމެނޭ ބައިތައް';
$string['pages'] = 'ޕޭޖުތައް';
$string['pagetitle'] = 'ގަނޑުގެ ސުރުޚީ';
$string['password'] = 'ޕާސްވޯޑު';
$string['pleasecheckoneanswer'] = 'އެއްޖަވާބު ޗެކްކޮށްލައްވާ';
$string['pleasecheckoneormoreanswers'] = 'އެއްޖަވާބު ނުވަތަ އެއަށް ވުރެން ގިނަ ޖަވާބު ޗެކްކޮށްލައްވާ';
$string['pleaseenteryouranswerinthebox'] = 'ފޮށީގައި ޖަވާބު ލިޔުއްވާ';
$string['pointsearned'] = 'ލިބުނު ޕޮއިންޓްތައް';
$string['postsuccess'] = 'ކާމިޔާބު ކަމާއެކީ ލެވިއްޖެ';
$string['practice'] = 'ފްރެކްޓިސް ފިލާވަޅު';
$string['previouspage'] = 'ކުރިން ދިޔަ ގަނޑު';
$string['qtype'] = 'ޕޭޖުގެ ބާވަތް';
$string['question'] = 'ސުވާލު';
$string['questionoption'] = 'ސުވާލު';
$string['questiontype'] = 'ސުވާލުގެ ބާވަތް';
$string['rank'] = 'މަޤާމް';
$string['report'] = 'ރިޕޯޓް';
$string['reports'] = 'ރިޕޯޓްތައް';
$string['returntocourse'] = 'އެނބުރި ކޯހަށްދިޔުމަށް';
$string['review'] = 'ރިވިއު';
$string['reviewlesson'] = 'ފިލާވަޅު ރިވިއު ކުރަން';
$string['reviewquestionback'] = 'އާނ، އަދި މަސަކަތްކޮށްލަން ބޭނުން';
$string['reviewquestioncontinue'] = 'ނޫން، ދެން ޖެހިގެން އިން ސުވާލަށް ދާންބޭނުމީ';
$string['savechanges'] = 'ބަދަލުތައް ސޭވްކޮށްލަން';
$string['savechangesandeol'] = 'ހުރިހާ ބަދަލުތައް ސޭވްކޮށް ފިލާވަޅުގެ ނިމުމަށް ދާން';
$string['savepage'] = 'ޕޭޖް ސޭވް ކުރަން';
$string['score'] = 'ސްކޯރ';
$string['scores'] = 'ސްކޯރތައް';
$string['secondpluswrong'] = 'މުޅިޔަކުން ނޫން، އަނެއްކާ މަސައްކަތްކޮށްލަން ބޭނުންތަ؟';
$string['singleanswer'] = 'އެއް ޖަވާބު';
$string['slideshow'] = 'ސްލައިޑް ޝޯރ';
$string['slideshowbgcolor'] = 'ސްލައިޑް ޝޯރގެ ބެކްގްރައުންޑް ކުލަ';
$string['slideshowheight'] = 'ސްލައިޑް ޝޯރގެ އުސްމިން';
$string['slideshowwidth'] = 'ސްލައިޑް ޝޯރގެ ފުޅާމިން';
$string['startlesson'] = 'ފިލާވަޅު ފަށަން';
$string['thatsthecorrectanswer'] = 'ތީ ރަނގަޅު ޖަވާބު';
$string['thatsthewronganswer'] = 'ތީ ނުބައި ޖަވާބު';
$string['thispage'] = 'މި ޕޭޖް';
$string['timed'] = 'ވަޤުތު ކަނޑައެޅިފަ';
$string['timeremaining'] = 'ބާކީ ވަޤުތު';
$string['timespentminutes'] = '(ހޭދަ ކުރެވުނު ވަޤުތު (މިނިޓް';
$string['timetaken'] = 'ނެގި ވަޤުތު';
$string['updatedpage'] = 'ޕޭޖް އަޕްޑޭޓްކުރެވިއްޖެ';
$string['updatefailed'] = 'އަޕްޑޭޓެއް ނުކުރެވުނު';
$string['useeditor'] = 'އެޑިޓަރ ބޭނުންކުރޭ';
$string['viewgrades'] = 'ގްރޭޑްތައް ދައްކާ';
$string['viewhighscores'] = 'ހައިސްކޯރ ލިސްޓް ދައްކާ';
$string['welldone'] = 'ވަރަށް ރަގަޅު!';
$string['whatdofirst'] = 'އެންމެ ފުރަތަމަ ކުރަން ބޭނުމީ ކޮންކަމެއް؟';
$string['answersfornumerical'] = ''; // ORPHANED
$string['displayscorewithessays'] = ''; // ORPHANED
$string['essayemailmessage'] = ''; // ORPHANED
$string['firstwrong'] = ''; // ORPHANED
$string['maximumnumberofattemptsreached'] = ''; // ORPHANED
$string['modattemptsnoteacher'] = ''; // ORPHANED
$string['noessayquestionsfound'] = ''; // ORPHANED
$string['noonecheckedthis'] = ''; // ORPHANED
$string['nooneenteredthis'] = ''; // ORPHANED
$string['normal'] = ''; // ORPHANED
$string['nothighscore'] = ''; // ORPHANED
$string['numberofcorrectanswers'] = ''; // ORPHANED
$string['numberofcorrectmatches'] = ''; // ORPHANED
$string['numberofpagestoshow'] = ''; // ORPHANED
$string['numberofpagesviewed'] = ''; // ORPHANED
$string['numberofpagesviewednotice'] = ''; // ORPHANED
$string['ongoing'] = ''; // ORPHANED
$string['ongoingcustom'] = ''; // ORPHANED
$string['ongoingnormal'] = ''; // ORPHANED
$string['ordered'] = ''; // ORPHANED
$string['outof'] = ''; // ORPHANED
$string['page'] = ''; // ORPHANED
$string['passwordprotectedlesson'] = ''; // ORPHANED
$string['pleasematchtheabovepairs'] = ''; // ORPHANED
$string['preview'] = ''; // ORPHANED
$string['previewlesson'] = ''; // ORPHANED
$string['progressbar'] = ''; // ORPHANED
$string['progressbarteacherwarning'] = ''; // ORPHANED
$string['randombranch'] = ''; // ORPHANED
$string['randompageinbranch'] = ''; // ORPHANED
$string['rawgrade'] = ''; // ORPHANED
$string['receivedcredit'] = ''; // ORPHANED
$string['redisplaypage'] = ''; // ORPHANED
$string['response'] = ''; // ORPHANED
$string['returnto'] = ''; // ORPHANED
$string['sanitycheckfailed'] = ''; // ORPHANED
$string['showanunansweredpage'] = ''; // ORPHANED
$string['showanunseenpage'] = ''; // ORPHANED
$string['skip'] = ''; // ORPHANED
$string['studentattemptlesson'] = ''; // ORPHANED
$string['studentname'] = ''; // ORPHANED
$string['studentoneminwarning'] = ''; // ORPHANED
$string['studentresponse'] = ''; // ORPHANED
$string['submitname'] = ''; // ORPHANED
$string['teacherjumpwarning'] = ''; // ORPHANED
$string['teacherongoingwarning'] = ''; // ORPHANED
$string['teachertimerwarning'] = ''; // ORPHANED
$string['thefollowingpagesjumptothispage'] = ''; // ORPHANED
$string['timespenterror'] = ''; // ORPHANED
$string['topscorestitle'] = ''; // ORPHANED
$string['unseenpageinbranch'] = ''; // ORPHANED
$string['unsupportedqtype'] = ''; // ORPHANED
$string['usemaximum'] = ''; // ORPHANED
$string['usemean'] = ''; // ORPHANED
$string['usepassword'] = ''; // ORPHANED
$string['viewreports'] = ''; // ORPHANED
$string['wronganswerjump'] = ''; // ORPHANED
$string['wronganswerscore'] = ''; // ORPHANED
$string['wrongresponse'] = ''; // ORPHANED
$string['xattempts'] = ''; // ORPHANED
$string['youhaveseen'] = ''; // ORPHANED
$string['youmadehighscore'] = ''; // ORPHANED

?>
