<?PHP // $Id$ 
      // role.php - created with Moodle 1.7.1+ (2006101010)


$string['addrole'] = 'Προσθήκη ρόλου';
$string['allowassign'] = 'Να επιτρέπεται η ανάθεση ρόλων';
$string['assignroles'] = 'Ανάθεση ρόλων';
$string['capabilities'] = 'Δυνατότητες';
$string['capability'] = 'Δυνατότητα';
$string['category:create'] = 'Δημιουργία τμημάτων';
$string['category:delete'] = 'Διαγραφή τμημάτων';
$string['category:update'] = 'Τροποποίηση τμημάτων';
$string['category:visibility'] = 'Προβολή κρυφών τμημάτων';
$string['course:activityvisibility'] = 'Προβολή/απόκρυψη δραστηριοτήτων';
$string['course:bulkmessaging'] = 'Αποστολή ενός μηνύματος σε πολλούς παραλήπτες';
$string['course:create'] = 'Δημιουργία μαθημάτων';
$string['course:delete'] = 'Διαγραφή μαθημάτων';
$string['course:manageactivities'] = 'Διαχείριση δραστηριοτήτων';
$string['course:managefiles'] = 'Διαχείριση αρχείων';
$string['course:managegrades'] = 'Διαχείριση βαθμών';
$string['course:managegroups'] = 'Διαχείριση ομάδων';
$string['course:managemetacourse'] = 'Διαχείριση μεταπληροφοριών';
$string['course:managescales'] = 'Διαχείριση κλιμάκων';
$string['course:view'] = 'Προβολή μαθημάτων';
$string['course:viewparticipants'] = 'Προβολή συμμετεχόντων';
$string['course:visibility'] = 'Προβολή/απόκρυψη μαθημάτων';
$string['currentcontext'] = 'Τρέχων περιβάλλον';
$string['currentrole'] = 'Τρέχων ρόλος';
$string['defaultrole'] = 'Αρχική κατηγορία χρηστών';
$string['defineroles'] = 'Διαχείριση ρόλων';
$string['editrole'] = 'Επεξεργασία ρόλου';
$string['errorbadrolename'] = 'Εσφαλμένο όνομα ρόλου';
$string['errorbadroleshortname'] = 'Εσφαλμένο όνομα ρόλου';
$string['errorexistsrolename'] = 'Υπάρχει ήδη ένας ρόλος με το ίδιο όνομα';
$string['errorexistsroleshortname'] = 'Υπάρχει ήδη ένας ρόλος με το ίδιο όνομα';
$string['existingusers'] = '$a υπάρχοντες χρήστες';
$string['listallroles'] = 'Παράθεση όλων των ρόλων';
$string['manageroles'] = 'Διαχείριση ρόλων';
$string['permissions'] = 'Δικαιώματα χρήσης';
$string['potentialusers'] = '$a ενδεχόμενοι χρήστες';
$string['prohibit'] = 'Απαγόρευση';
$string['question:export'] = 'Εξαγωγή ερωτήσεων';
$string['question:import'] = 'Εισαγωγή ερωτήσεων';
$string['question:manage'] = 'Διαχείριση ερωτήσεων';
$string['question:managecategory'] = 'Διαχείριση κατηγοριών ερωτήσεων';
$string['risks'] = 'Κίνδυνοι';
$string['role:assign'] = 'Ανάθεση ρόλων στους χρήστες';
$string['role:manage'] = 'Δημιουργία και διαχείριση ρόλων';
$string['role:viewhiddenassigns'] = 'Προβολή κρυφών αναθέσεων ρόλων';
$string['roleassignments'] = 'Ανάθεση ρόλων';
$string['roles'] = 'Ρόλοι';
$string['roletoassign'] = 'Ρόλος να καταχωρηθεί';
$string['selectrole'] = 'Επιλογή ρόλου';
$string['showallroles'] = 'Προβολή όλων των ρόλων';
$string['site:uploadusers'] = 'Δημιουργία νένων χρηστών από αρχείο';
$string['site:viewfullnames'] = 'Προβολή του ονοματεπώνυμου των χρηστών';
$string['site:viewparticipants'] = 'Προβολή συμμετεχόντων';
$string['site:viewreports'] = 'Προβολή αναφορών';
$string['user:create'] = 'Δημιούργησε χρήστες';
$string['user:delete'] = 'Διέγραψε χρήστες';
$string['user:editprofile'] = 'Επεξεργασία του προφίλ του χρήστη';
$string['user:readuserposts'] = 'Προβολή όλων των μηνυμάτων του χρήστη';
$string['user:viewdetails'] = 'Προβολή των προφίλ των χρηστών';
$string['user:viewhiddendetails'] = 'Προβολή των κρυφών πληροφοριών των χρηστών';
$string['user:viewuseractivitiesreport'] = 'Προβολή των αναφορών δραστηριότητας του χρήστη';
$string['user:viewusergrades'] = 'Προβολή των βαθμών του φοιτητή';
$string['viewrole'] = 'Προβολή των λεπτομερειών του ρόλου';

?>
