<?php // $Id$

$string['addgroupstogrouping'] = 'Ajouter le groupe au groupement';
$string['addgroupstogroupings'] = 'Ajouter/retirer des groupes';  //'du group'
$string['adduserstogroup'] = 'Ajouter/retirer des utilisateurs'; // au groupe
$string['allocateby'] = 'Répartir les membres';
$string['anygrouping'] = '[N\'importe quel groupement]';
$string['autocreategroups'] = 'Créer des groupes automatiquement';
$string['backtogroups'] = 'Retour aux groupes';
$string['backtogroupings'] = 'Retour aux groupements';
$string['badnamingscheme'] = 'Doit contenir exactement un caractère «&nbsp;@&nbsp;» ou un «&nbsp;#&nbsp;»';
$string['createautomaticgrouping'] = 'Créer groupement automatique';
$string['creategroup'] = 'Créer un groupe';
$string['creategrouping'] = 'Créer un groupement';
$string['creategroupinselectedgrouping'] = 'Créer un groupe dans le groupement'; // sélectionné
$string['createorphangroup'] = 'Créer un groupe orphelin';
$string['databaseupgradegroups'] = 'La version des groupes est maintenant $a';
$string['defaultgroupdescription'] = 'Description du groupe par défaut';
$string['defaultgrouping'] = 'Groupement par défaut';
$string['defaultgroupingname'] = 'Groupement';
$string['defaultgroupname'] = 'Groupe';
$string['defaultgroupprefix'] = 'Groupe ';
$string['deletegroupconfirm'] = 'Voulez-vous vraiment supprimer le groupe «&nbsp;$a&nbsp;»?';
$string['deletegrouping'] = 'Supprimer groupement';
$string['deletegroupingconfirm'] = 'Voulez-vous vraiment supprimer le groupement «&nbsp;$a&nbsp;»? (les groupes dans ce groupement ne seront pas supprimés.)';
$string['deleteselectedgroup'] = 'Supprimer le groupe sélectionné';
$string['displaygrouping'] = 'Affichage du groupement';
$string['distributealphabetically'] = 'Répartir alphabétiquement (nom de famille) dans les groupes';
$string['distributeevenly'] = 'Répartir équitablement les étudiants restants';
$string['editgroupingsettings'] = 'Modifier les réglages du groupement';
$string['editgroupsettings'] = 'Modifier les réglages du groupe';
$string['enrolmentkey'] = 'Clef d\'inscription';
$string['erroraddremoveuser'] = 'Erreur lors de l\'ajout ou du retrait de l\'utilisateur $a du groupe';
$string['erroreditgroup'] = 'Erreur lors de la création ou de la modification du groupe $a';
$string['erroreditgrouping'] = 'Erreur lors de la création ou de la modification du groupement $a';
$string['errorinvalidgroup'] = 'Groupe $a non valide';
$string['evenallocation'] = 'Remarque&nbsp;: pour obtenir une répartition équilibrée des groupes, le nombre réel des membres par groupe a été adapté. Il différera du nombre que vous avez indiqué.';
$string['existingmembers'] = 'Membres actuels&nbsp;: $a';
$string['filtergroups'] = 'Filtrer les groupes par&nbsp;: ';
$string['firstname'] = 'alphabétiquement par prénom';
$string['group'] = 'Groupe';
$string['groupaddedsuccesfully'] = 'Le groupe $a a été ajouté';
$string['groupby'] = 'Créer des groupes d\'après le nombre de ';
$string['groupdescription'] = 'Description du groupe';
$string['groupinfo'] = 'Information sur le groupe sélectionné';
$string['groupinfomembers'] = 'Information sur les membres sélectionnés';
$string['groupinfopeople'] = 'Information sur les personnes sélectionnées';
$string['grouping'] = 'Groupement';
$string['groupingdescription'] = 'Description du groupement';
$string['groupingname'] = 'Nom du groupement';
$string['groupingnameexists'] = 'Le nom de groupement «&nbsp;$a&nbsp;» existe déjà dans ce cours. Veuillez en choisir un autre.';
$string['groupings'] = 'Groupements';
$string['groupmember'] = 'Membre du groupe';
$string['groupmemberdesc'] = 'Rôle par défaut pour un membre d\'un groupe.';
$string['groupmembers'] = 'Membres du groupe';
$string['groupmemberssee'] = 'Voir les membres du groupe';
$string['groupmembersselected'] = 'Membres du groupe sélectionné';
$string['groupmembersonly'] = 'Disponible uniquement pour les membres du groupe';
$string['groupmembersonlyerror'] = 'Désolé, vous devez être membre d\'au moins un groupe utilisé dans cette activité.';
$string['groupmode'] = 'Mode de groupe';
$string['groupmodeforce'] = 'Imposer le mode de groupe';
$string['groupmy'] = 'Mon groupe';
$string['groupname'] = 'Nom du groupe';
$string['groupnameexists'] = 'Le nom de groupe «&nbsp;$a&nbsp;» existe déjà dans ce cours. Veuillez en choisir un autre.';
$string['groupnotamember'] = 'Désolé, vous n\'êtes pas membre de ce groupe';
$string['groups'] = 'Groupes';
$string['groupsinselectedgrouping'] = 'Groupes dans'; // groupement sélectionné
$string['groupsnone'] = 'Aucun groupe';
$string['groupspreview'] = 'Prévisualisation des groupes';
$string['groupsseparate'] = 'Groupes séparés';
$string['groupsvisible'] = 'Groupes visibles';
$string['hidepicture'] = 'Cacher l\'image';
$string['javascriptrequired'] = 'Cette page requiert l\'activation de Javascript.';
$string['lastname'] = 'alphabétiquement par nom';
$string['members'] = 'Membres par groupe';
$string['membersingroup'] = 'Membres';
$string['membersofselectedgroup'] = 'Membres de';
$string['namingscheme'] = 'Schéma de dénomination';
$string['namingschemehelp'] = 'Utilisez «&nbsp;@&nbsp;» pour représenter la lettre du groupe ou «&nbsp;#&nbsp;» pour représenter le numéro du groupe';
$string['newpicture'] = 'Nouvelle image';
$string['nogroupsassigned'] = 'Aucun groupe n\'a été attribué';
$string['nogroups'] = 'Il n\'y a pas encore de groupes dans ce cours';
$string['nopermissionforcreation'] = 'Impossible de créer le groupe «&nbsp;$a&nbsp;», car vous n\'avez pas les permissions requises';
$string['notingrouping'] = '[Dans aucun groupement]';
$string['nousersinrole'] = 'Il n\'y a pas d\'utilisateur adéquat dans le rôle sélectionné';
$string['number'] = 'Nombre de groupes ou membres par groupe';
$string['numberofgroups'] = 'Nombre de groupes';
$string['numberofstudents'] = 'Nombre d\'étudiants';
$string['overview'] = 'Vue d\'ensemble';
$string['potentialmembers'] = 'Membres potentiels&nbsp;: $a';
$string['prefixforgroupnames'] = 'Préfixe des noms de groupe';
$string['printerfriendly'] = 'Affichage pour impression'; // du groupement
$string['random'] = 'aléatoirement';
$string['removegroupfromselectedgrouping'] = 'Retirer le groupe du groupement'; // sélectionné
$string['removeselectedusers'] = 'Retirer les utilisateurs sélectionnés';
$string['selectfromrole'] = 'Rôle dans lequel les membres seront sélectionnés';
$string['selectnumberineachgroup'] = 'Sélectionner un nombre de chaque groupe';
$string['selectnumberofgroups'] = 'Sélectionner un nombre de groupes';
$string['showgroupsingrouping'] = 'Afficher les groupes du groupement';
$string['showmembersforgroup'] = 'Afficher les membres du groupe';
$string['toomanygroups'] = 'Il n\'y a pas assez d\'utilisateurs pour répartir ce nombre de groupes. Il n\'y a que $a utilisateurs ayant le rôle sélectionné.';
$string['usergroupmembership'] = 'Groupes dont l\'utilisateur sélectionné fait partie&nbsp;:';
$string['usestudentsonlyfromselectedgroup'] = 'N\'utiliser que les étudiants du groupe sélectionné';

?>