<?php // $Id$

// Terme actuellement choisi pour "repository" : dépôt
// Autres possibilités à envisager : entrepôt, stockage, zone de dépôt, ...

$string['activaterep'] = 'Activer les dépôts de documents';
$string['activerepository'] = 'Plugins de dépôt actifs';
$string['add'] = 'Ajouter';
$string['addplugin'] = 'Ajouter un plugin de dépôt';
$string['areabackup'] = 'Sauvegardes';
$string['areacategoryintro'] = 'Descriptif de catégorie';
$string['areacourseintro'] = 'Descriptif du cours';
$string['arearoot'] = 'Système';
$string['areauserdraft'] = 'Brouilons';
$string['areauserpersonal'] = 'Personnel';
$string['attachment'] = 'Annexe';
$string['back'] = '&lt; Retour';
$string['cacheexpire'] = 'Échéance du cache';
$string['close'] = 'Fermer';
$string['configcacheexpire'] = 'Configurer la durée avant échéance du cache (en minutes).';
$string['configsaved'] = 'Configuration enregistrée&nbsp;!';
$string['confirmdelete'] = 'Voulez-vous vraiment supprimer le dépôt $a&nbsp;?';
$string['confirmremove'] = 'Voulez-vous vraiment supprimer le plugin de dépôt $a, ses réglages et <strong style=color:red>toutes ces instances</strong>&nbsp;?';
$string['copying'] = 'Copie en cours';
$string['create'] = 'Créer';
$string['createinstance'] = 'Créer une instance de dépôt';
$string['createrepository'] = 'Créer une instance de dépôt';
$string['date'] = 'Date';
$string['deleted'] = 'Dépôt supprimé';
$string['deleterepository'] = 'Supprimer ce dépôt';
$string['download'] = 'Télécharger';
$string['downloadsucc'] = 'Le fichier a été téléchargé correctement';
$string['editrepositoryinstance'] = 'Modifier l\'instance de dépôt';
$string['emptytype'] = 'Impossible de créer le type de dépôt&nbsp;: le nom du type est vide';
$string['error'] = 'Une erreur inconnue est survenue&nbsp;!';
$string['existingrepository'] = 'Ce dépôt existe déjà';
$string['filename'] = 'Nom de fichier';
$string['filenotnull'] = 'Vous devez choisir un fichier à déposer.';
$string['filesaved'] = 'Le fichier a été enregistré';
$string['getfile'] = 'Sélectionner ce fichier';
$string['hiddenshow'] = 'Cacher/montrer';
$string['instance'] = 'Instance';
$string['instancedeleted'] = 'Instance supprimée';
$string['instances'] = 'Instances de dépôt';
$string['invalidjson'] = 'Chaîne JSON non valide';
$string['invalidplugin'] = 'Plugin de dépôt non valide';
$string['invalidrepositoryid'] = 'Identifiant de dépôt non valide';
$string['listview'] = 'Afficher en liste';
$string['loading'] = 'Chargement...';
$string['logout'] = 'Déconnexion';
$string['manage'] = 'Gérer les dépôts';
$string['manageurl'] = 'Gestion';
$string['manageuserrepository'] = 'Gérer le dépôt personnel';
$string['noenter'] = 'Pas de saisie';
$string['nopermissiontoaccess'] = 'Pas d\'autorisation d\'accéder à ce dépôt';
$string['notyourinstances'] = 'Vous ne pouvez pas voir ni modifier les instances de dépôts d\'un autre utilisateur';
$string['openpicker'] = 'Choisir un fichier...';
$string['operation'] = 'Opération';
$string['personalrepositories'] = 'Dépôts personels';
$string['plugin'] = 'Plugins de dépôt';
$string['preview'] = 'Prévisualiser';
$string['removed'] = 'Dépôt supprimé';
$string['repositories'] = 'Dépôts';
$string['repository'] = 'Dépôt';
$string['repositorycourse'] = 'Dépôts du cours';
$string['save'] = 'Enregistrer';
$string['saveas'] = 'Enregistrer sous';
$string['saved'] = 'Enregistré';
$string['saving'] = 'En cours d\'enregistrement';
$string['search'] = 'Recherche ';
$string['searching'] = 'Que cherchez-vous&nbsp;?';
$string['settings'] = 'Réglages';
$string['siteinstances'] = 'Instances de dépôts du site';
$string['size'] = 'Taille';
$string['submit'] = 'Envoyer';
$string['sync'] = 'Sync';
$string['thumbview'] = 'Afficher en vignettes';
$string['title'] = 'Sélecteur de fichier du dépôt';
$string['typenotvisible'] = 'Type non visible';
$string['updown'] = 'Ordre d\'affichage';
$string['upload'] = 'Déposer ce fichier';
$string['uploading'] = 'En cours de dépôt...';
$string['wrongcontext'] = 'Vous ne pouvez pas accéder à ce contexte';

?>