<?php // $Id$ 

$string['allow'] = 'Autoriser';
$string['assignroles'] = 'Assigner des rôles';
$string['capability'] = 'Autorisation';
$string['currentrole'] = 'Rôle actuel';
$string['currentcontext'] = 'Contexte actuel';
$string['existingusers'] = '$a utilisateurs existants';
$string['inherit'] = 'Hériter';
$string['overrideroles'] = 'Ne pas tenir compte des rôles';
$string['potentialusers'] = '$a utilisateurs potentiels';
$string['prevent'] = 'Empêcher';
$string['prohibit'] = 'Interdire';

$string['site:doanything'] = 'Permettre de tout faire';
$string['legacy:guest'] = 'ANCIEN RÔLE : Invité';
$string['legacy:student'] = 'ANCIEN RÔLE : Étudiant';
$string['legacy:teacher'] = 'ANCIEN RÔLE : Enseignant (non éditeur)';
$string['legacy:editingteacher'] = 'ANCIEN RÔLE : Enseignant (editing)';
$string['legacy:coursecreator'] = 'ANCIEN RÔLE : Responsable de cours';
$string['legacy:admin'] = 'ANCIEN RÔLE : Administrateur';
$string['site:config'] = 'Modifier la configuration du site';
$string['site:import'] = 'Importer d\'autres cours dans un cours';
$string['site:backup'] = 'Sauvegarder des cours';
$string['site:restore'] = 'Restaurer des cours';
$string['site:manageblocks'] = 'Gérer les blocs au niveau du site';
$string['site:accessallgroups'] = 'Accéder à tous les groupes';
$string['site:viewfullnames'] = 'Toujours voir les noms complets des utilisateurs';
$string['user:create'] = 'Créer des utilisateurs';
$string['user:delete'] = 'Supprimer des utilisateurs';
$string['user:update'] = 'Mettre à jour les profils des utilisateurs';
$string['user:viewdetails'] = 'Voir les profils des utilisateurs';
$string['role:assign'] = 'Assigner des rôles aux utilisateurs';
$string['role:manage'] = 'Créer et gérer des rôles';
$string['blog:view'] = 'Voir les articles de blog';
$string['blog:create'] = 'Créer des articles de blog';
$string['blog:manageofficialtags'] = 'Gérer les balises officielles';
$string['blog:managepersonaltags'] = 'Gérer les balises personnelles';
$string['blog:manageentries'] = 'Modifier et gérer les articles de blog';
$string['calendar:manageownentries'] = 'Gérer ses propres événements du calendrier';
$string['calendar:manageentries'] = 'Gérer tous les événements du calendrier';
$string['category:create'] = 'Créer des catégories de cours';
$string['category:delete'] = 'Supprimer des catégories de cours';
$string['category:update'] = 'Modifier des catégories de cours';
$string['category:visibility'] = 'Voir les catégories de cours cachées';
$string['course:create'] = 'Créer des cours';
$string['course:delete'] = 'Supprimer des cours';
$string['course:update'] = 'Modifier les réglages des cours';
$string['course:view'] = 'voir les cours';
$string['course:visibility'] = 'Cacher/afficher des cours';
$string['course:manageactivities'] = 'Gérer des activités';
$string['course:activityvisibility'] = 'Cacher/afficher des activités';
$string['course:viewhiddenactivities'] = 'Voir les activités cachées';
$string['course:viewparticipants'] = 'Voir les participants';
$string['course:viewscales'] = 'Voir les barêmes';
$string['course:managescales'] = 'Gérer les barêmes';
$string['course:managegroups'] = 'Gérer les groupes';

?>