<?PHP // $Id$ 
      // question.php - created with Moodle 2.0 dev (Build: 20090514) (2009051200)


$string['adminreport'] = 'Հաշվետվություն հարցերի շտեմարանի հնարավոր խնդիրների վերաբերյալ:';
$string['broken'] = 'Սա \"խախտված հղում\" է, այն հղում է գոյություն չունեցող ֆայլի:';
$string['byandon'] = '<em>$a->user</em>-ից <em>$a->time</em>-ին';
$string['categorycurrent'] = 'Ընթացիկ կարգ';
$string['categorycurrentuse'] = 'Օգտագործել այս կարգը';
$string['categorydoesnotexist'] = 'Այս կարգը գոյություն չունի';
$string['categorymoveto'] = 'Պահպանել կարգում';
$string['changepublishstatuscat'] = '\"$a->coursename\" <a href=\"$a->name $a->caturl\">կարգը\"</a> օգտագործման կարգավիճակը <strong>$a->changefrom -ից կփոխի $a->changeto</strong>։';
$string['copy'] = 'Պատճենել $a-ից և փոխել հղումները։';
$string['created'] = 'Ստեղծվել է';
$string['createdmodifiedheader'] = 'Ստեղծվել է / Վերջին անգամ պահպանվել է';
$string['cwrqpfs'] = 'Պատահական հարցեր, որոնք ընտրում են հարցեր ենթակարգերից։';
$string['cwrqpfsinfo'] = '<p>Մինչև Moodle 1.9 տաբերակ նորացնելիս մենք կարգերը կառանձնացնենք տարբեր համատեքստերում։ Ձեր կայքի որոշ հարցերի և հարցերի կարգերի օգտագործման կարգավիճակն անհրաժեշտ կլինի փոխել։ Սա անհրաժեշտ է բացառիկ դեպքերում, երբ հարցաշարում մեկ կամ մի քանի \'պատահական\' հարցեր կարգաբերված են հարցեր ընտրելու համօգտագործելի և ոչ համօգտագործելի կարգերից։ Սա պատահում է այն դեպքերում է, երբ սահմանվել է \'պատահական\' հարցն ընտրել ենթակարգերից, և մեկ կամ մի քանի ենթակարգեր ունեն մայր կարգից տարբեր օգտագործման կարգավիճակ, որում ստեղծվել է պատահական հարցը։</p>
<p>Հետևյալ հարցերի կագերը, որոնցից \'պատահական\' հարցերը մայր կարգերից ընտրել են հարցեր, իրենց օգտագործման կարգավիճակը Moodle 1.9 տարբերակով նորացնելիս կփոխարինեն նույն կարգավիճակով, ինչպիսին \'պատահական\' հարցի կարգն է։ Հետևյալ կարգերը կփոխեն իրենց օգտագործման կարգավիճակը։ Հարցերը, որոնք վնասվել են, կշարունակեն աշխատել բոլոր գոյություն ունեցող հարցաշարերում, մինչև դրանք չջնջեք հարցաշարերից։</p>';
$string['cwrqpfsnoprob'] = '\'Պատահական հարցեր, որոնք ընտրում են հարցեր ենթակարգերից\' արդյունքը ոչ մի ներգործություն չի ունեցել Ձեր կայքի ոչ մի կարգի վրա';
$string['defaultfor'] = 'Կանխորոշված $a համար';
$string['defaultinfofor'] = 'Կանխորոշված կարգ \'$a\' համատեքստում օգտագործվող հարցերի համար:';
$string['deletecoursecategorywithquestions'] = 'Հարցերի բանկում կան հարցեր, որոնք կապված են դասընթացի այս կարգի հետ: Եթե շարունակեք, դրանք կջնջվեն: Դուք կարող եք դրանք տեղափոխել` օգտվելով հարցերի բանկի միջերեսից:';
$string['donothing'] = 'Չպատճենել կամ տեղափոխել նշոցները կամ փոխել հղումները։';
$string['editingcategory'] = 'Կարգի խմբագրում';
$string['editingquestion'] = 'Հարցի խմբագրում';
$string['erroraccessingcontext'] = 'Չի հաջողվում մատչելիություն ստանալ համատեքստին';
$string['errordeletingquestionsfromcategory'] = '$a կարգից հարցերի ջնջման սխալ:';
$string['errorfilecannotbecopied'] = 'Սխալ. չի կարող պատճենել $a ֆայլը:';
$string['errorfilecannotbemoved'] = 'Սխալ. չի կարող տեղափոխել $a ֆայլը:';
$string['errorfileschanged'] = 'Հարցերի հետ կապված սխալ ֆայլերը փոփոխվել են ձևի ցուցադրումից հետո։';
$string['errormanualgradeoutofrange'] = '$a->name հարցի $a->grade գնահատականը 0 և $a->maxgrade միջակայքից չէ: Հաշիվը և մեկնաբանությունը չեն պահպանվել';
$string['errormovingquestions'] = 'Սխալ է ստացվել $a id-ներով հարցերը տեղափոխելիս։';
$string['errorprocessingresponses'] = 'Սխալ է ստացվլ Ձեր պատասխանների մշակման ընթացքում';
$string['errorsavingcomment'] = 'Տվյալների շտեմարանում $a->name հարցի մեկնաբանության պահպանման սխալ։';
$string['errorupdatingattempt'] = '$a->id փորձի նորացման սխալ տվյաների շտեմաեանում։';
$string['exportcategory'] = 'Արտահանվող կարգ';
$string['filesareacourse'] = 'դասընթացի ֆայլերի միջավայր';
$string['filesareasite'] = 'կայքի ֆայլերի միջավայր';
$string['filestomove'] = 'Ֆայլերը տեղափոխե՞լ / պատճենե՞լ $a';
$string['fractionsnomax'] = 'Պատասխաններից մեկը պետք է գնահատվի 100%%, որպեսզի հնարավոր լինի հարցի համար ստանալ ամբողջական գնահատական։';
$string['getcategoryfromfile'] = 'Ստանալ կարգ ֆայլից';
$string['getcontextfromfile'] = 'Ստանալ համատեքստ ֆայլից';
$string['ignorebroken'] = 'Անտեսել խախտված հղումները';
$string['invalidcontextinhasanyquestions'] = 'Անվավեր համատեքստ է անցել question_context_has_any_questions:';
$string['linkedfiledoesntexist'] = 'Հղված ֆայլը` $a, գոյություն չունի';
$string['makechildof'] = 'Ստեղծել \'$a\' դուստրը';
$string['maketoplevelitem'] = 'Տեղափոխել վերին մակարդակ';
$string['missingimportantcode'] = 'Այս հարցում լրացված չէ կարևոր կոդ` $a :';
$string['modified'] = 'Վերջին անգամ պահպանվել է';
$string['move'] = 'Տեղափոխել $a-ից և փոխել հղումները:';
$string['movecategory'] = 'Տեղափոխել կարգը';
$string['movedquestionsandcategories'] = 'Հարցերը և կարգերը $a->oldplace -ից տեղափոխվել են $a->newplace :';
$string['movelinksonly'] = 'Միայն փոխել հղվման կետը, չտեղափոխել կամ պատճենել ֆայլերը:';
$string['moveq'] = 'Տեղափոխել հարց(եր)ը';
$string['moveqtoanothercontext'] = 'Հարցը տեղափոխել այլ համատեքստ:';
$string['movingcategory'] = 'Կարգի տեղափոխում';
$string['movingcategoryandfiles'] = 'Դուք իսկապե՞ս համոզված եք, որ ցանկանում եք {$a->name} կարգը և բոլոր դուստր կարգերը տեղափոխել \"{$a->contextto}\"-ի համատեքստ։<br /> Մենք հայտնաբերել ենք {$a->urlcount} ֆայլեր, որոնք կապված են {$a->fromareaname} հարցերի հետ, ցանկանու՞մ եք դրանք պատճենել կամ տեղափոխել {$a->toareaname}։';
$string['movingcategorynofiles'] = 'Դուք իսկապե՞ս համոզված եք, որ ցանկանում եք  \"{$a->name}\" կարգը և բոլոր դուստր կարգերը տեղափոխել \"{$a->contextto}\"-ի համատեքստ։';
$string['movingquestions'] = 'Հարցերի և ֆայլերի տեղափոխում';
$string['movingquestionsandfiles'] = 'Դուք իսկապե՞ս համոզված եք, որ ցանկանում եք {$a->questions}  հարցերը տեղափոխել <strong>\"{$a->tocontext}\"</strong> համատեքստ։<br /> Մենք հայտնաբերել ենք  <strong>{$a->urlcount} ֆայլեր</strong>, որոնք կապված են {$a->fromareaname}-ի հարցերի հետ, ցանկանու՞մ եք դրանք պատճենել կամ տեղափոխել {$a->toareaname}։';
$string['movingquestionsnofiles'] = 'Դուք իսկապե՞ս համոզված եք, որ ցանկանում եք {$a->questions} հարցերը տեղափոխել <strong>\"{$a->tocontext}\"</strong> համատեքստ։ Չկան <strong>ֆայլեր</strong>, որոնք կապված են {$a->fromareaname}-ի այս հարցերի հետ։';
$string['needtochoosecat'] = 'Հարցը տեղափոխելու համար Ձեզ անհրաժեշտ է ընտրել կարգ կամ սեղմել \'չեղյալ\' կոճակը։';
$string['nopermissionadd'] = 'Դուք չունեք այստեղ հարցեր ավելացնելու թույլտվություն։';
$string['nopermissionmove'] = 'Դուք այստեղից հարցեր տեղափոխելու թույլտվություն չունեք: Դուք հարցը պետք է պահպանեք այս կարգում կամ պարզապես պահպանեք որպես նոր հարց:';
$string['noprobs'] = 'Հարցերի շտեմարանում ոչ մի խնդիր չի հայտնաբերվել։';
$string['notenoughdatatoeditaquestion'] = 'Ոչ հարցի id-ն, ոչ կարգի id-ն և հարցի տիպը չեն սահմանվել։';
$string['notenoughdatatomovequestions'] = 'Ձեզ անհրաժեշտ է տրամադրել այն հարցերի id-ները, որոնք ցանկանում եք տեղափոխել:';
$string['permissionedit'] = 'Խմբագրել հարցը';
$string['permissionmove'] = 'Տեղափոխել հարցը';
$string['permissionsaveasnew'] = 'Պահպանել որպես նոր հարց';
$string['permissionto'] = 'Ձեզ թույլատրված է .';
$string['published'] = 'օգտագործվել է';
$string['questionaffected'] = '<a href=\"$a->qurl\">Հարցը \"$a->name\" ($a->qtype)</a> կարգից է, սակայն նաև օգտագործվում է \"$a->coursename\" դասընթացի  <a href=\"$a->qurl\">հարցաշարում \"$a->quizname\"</a>։';
$string['questionbank'] = 'Հարցերի բանկ';
$string['questioncategory'] = 'Հարցերի կարգ';
$string['questioncatsfor'] = 'Հարցերի կարգ \'$a\' համար';
$string['questiondoesnotexist'] = 'Այս հարցը գոյություն չունի';
$string['questionsmovedto'] = 'Դեռ օգտագործվող հարցերը տեղափոխվել են \"$a\" դասընթացի մայր կարգ:';
$string['questionsrescuedfrom'] = 'Հարցերը պահպանվել են $a կոնտեքստից:';
$string['questionsrescuedfrominfo'] = 'Այս հարցերը (որոնցից որոշները հնարավոր է թաքցված են) պահպանվել են, երբ $a համատեքստը ջնջվել է, քանի որ դրանք դեռևս օգտագործվում են որոշ հարցաշարերում կամ գործունեություններում:';
$string['questionuse'] = 'Այս գործունեությունում օգտագործել հարց';
$string['shareincontext'] = 'Օգտագործել համատեքստում $a համար';
$string['tofilecategory'] = 'Ֆայլին գրանցել կարգ';
$string['tofilecontext'] = 'Ֆայլին գրանցել համատեքստ';
$string['unknown'] = 'Անհայտ';
$string['unknownquestiontype'] = 'Հարցի անհայտ տիպ՝ $a։';
$string['unpublished'] = 'ոչ համօգտագործելի';
$string['upgradeproblemcategoryloop'] = 'Հարցերի կարգերը նորացնելիս խնդիրներ են հայտնաբերվել: Կարգերի ծառում շրջան կա։ Վնասված կարգերի id-ներն են` $a:';
$string['upgradeproblemcouldnotupdatecategory'] = 'Չի հաջողվել նորացնել կարգը $a->name ($a->id).';
$string['upgradeproblemunknowncategory'] = 'Հարցերի կարգերը նորացնելիս խնդիրներ են հայտնաբերվել: Կարգի $a->id -ն հղվում է մայրին` $a->parent, որը գոյություն չունի:';
$string['yourfileshoulddownload'] = 'Ձեր արտահանվող ֆայլը պետք է սկսի բեռնավորել արագ։ Եթե ոչ, <a href=\"$a\">սեղմեք այստեղ</a>։';

?>
