<?PHP // $Id$ 
      // currencies.php - created with Moodle 1.9.3+ (Build: 20081112) (2007101531)


$string['AED'] = 'dirham';
$string['AFA'] = 'afgani';
$string['ALL'] = 'lek';
$string['ANG'] = 'gulden';
$string['ARA'] = 'peso';
$string['AUD'] = 'dollar australijski';
$string['AWG'] = 'gulden';
$string['BBD'] = 'dollar';
$string['BDT'] = 'taka';
$string['BGL'] = 'lew';
$string['BHD'] = 'dinar';
$string['BIF'] = 'frank';
$string['BMD'] = 'dollar';
$string['BND'] = 'dollar';
$string['BOB'] = 'boliwiano';
$string['BSD'] = 'dollar';
$string['BTN'] = 'ngultrum';
$string['BWP'] = 'pula';
$string['BZD'] = 'dollar';
$string['CAD'] = 'dollar';
$string['CHF'] = 'frank szwajcarski';
$string['CLP'] = 'peso';
$string['CNY'] = 'yuan';
$string['COP'] = 'peso';
$string['CRC'] = 'colon';
$string['CUP'] = 'peso';
$string['CVE'] = 'escudo';
$string['CYP'] = 'funt';
$string['DJF'] = 'frank';
$string['DKK'] = 'korona';
$string['DOP'] = 'peso';
$string['DZD'] = 'dinar';
$string['EGP'] = 'funt';
$string['ETB'] = 'birr';
$string['EUR'] = 'euro';
$string['FJD'] = 'dollar';
$string['FKP'] = 'funt';
$string['GBP'] = 'funt brytyjski';
$string['GHC'] = 'cedi';
$string['GIP'] = 'funt';
$string['GMD'] = 'dalasi';
$string['GNF'] = 'frank';
$string['GTQ'] = 'quetzal';
$string['GWP'] = 'peso';
$string['GYD'] = 'dollar';
$string['HKD'] = 'dollar';
$string['HNL'] = 'lempira';
$string['HTG'] = 'gourde';
$string['HUF'] = 'forint';
$string['IDR'] = 'rupia';
$string['ILS'] = 'szekel';
$string['INR'] = 'rupia';
$string['IQD'] = 'dinar';
$string['IRR'] = 'rial';
$string['ISK'] = 'korona';
$string['JMD'] = 'dollar';
$string['JOD'] = 'dinar';
$string['JPY'] = 'yen';
$string['KES'] = 'szyling';
$string['KHR'] = 'riel';
$string['KMF'] = 'frank';
$string['KPW'] = 'won';
$string['KRW'] = 'won';
$string['KWD'] = 'dinar';
$string['KYD'] = 'dollar';
$string['LAK'] = 'kip';
$string['LBP'] = 'funt';
$string['LKR'] = 'rupia';
$string['LRD'] = 'dollar';
$string['LSL'] = 'loti';
$string['LYD'] = 'dinar';
$string['MAD'] = 'dirham';
$string['MGF'] = 'frank';
$string['MNT'] = 'tugrik';
$string['MOP'] = 'pataca';
$string['MRO'] = 'ugijja';
$string['MTL'] = 'lira';
$string['MUR'] = 'rupia';
$string['MVR'] = 'rupia';
$string['MWK'] = 'kwacha';
$string['MXN'] = 'peso';
$string['MYR'] = 'ringgit';
$string['MZM'] = 'metical';
$string['NGN'] = 'naira';
$string['NOK'] = 'korona';
$string['NPR'] = 'rupia';
$string['NZD'] = 'dollar';
$string['OMR'] = 'rial';
$string['PAB'] = 'balboa';
$string['PGK'] = 'kina';
$string['PHP'] = 'peso';
$string['PKR'] = 'rupia';
$string['PLN'] = 'złoty';
$string['PYG'] = 'guarani';
$string['QAR'] = 'rial';
$string['ROL'] = 'lej';
$string['RWF'] = 'frank';
$string['SAR'] = 'rial';
$string['SBD'] = 'dollar';
$string['SCR'] = 'rupia';
$string['SDP'] = 'funt';
$string['SEK'] = 'korona';
$string['SGD'] = 'dollar';
$string['SHP'] = 'funt';
$string['SKK'] = 'korona';
$string['SLL'] = 'leone';
$string['SOS'] = 'szyling';
$string['SRG'] = 'gulden';
$string['STD'] = 'dobra';
$string['SUR'] = 'rubel';
$string['SVC'] = 'colon';
$string['SYP'] = 'funt';
$string['SZL'] = 'lilangeni';
$string['THB'] = 'bat';
$string['TND'] = 'dinar';
$string['TOP'] = 'pa\'anga';
$string['TPE'] = 'escudo';
$string['TRL'] = 'lir';
$string['TTD'] = 'dollar';
$string['TWD'] = 'dollar';
$string['TZS'] = 'szyling';
$string['UGS'] = 'szyling';
$string['USD'] = 'dollar';
$string['UYU'] = 'peso';
$string['VEB'] = 'bolivar';
$string['VND'] = 'dong';
$string['VUV'] = 'vatu';
$string['WST'] = 'tala';
$string['YER'] = 'dinar';
$string['ZAR'] = 'rand';
$string['ZMK'] = 'kwacha';
$string['ZWD'] = 'dollar';
$string['ADP'] = 'peseta'; // ORPHANED
$string['AOK'] = 'kwanza'; // ORPHANED
$string['ATS'] = 'szyling'; // ORPHANED
$string['BEF'] = 'frank belgijski'; // ORPHANED
$string['BRC'] = 'real'; // ORPHANED
$string['CSK'] = 'korona'; // ORPHANED
$string['DEM'] = 'marka niemiecka'; // ORPHANED
$string['ECS'] = 'dollar'; // ORPHANED
$string['ESP'] = 'peseta'; // ORPHANED
$string['FIM'] = 'marka'; // ORPHANED
$string['FRF'] = 'frank francuski'; // ORPHANED
$string['GRD'] = 'drachma'; // ORPHANED
$string['IEP'] = 'funt'; // ORPHANED
$string['ITL'] = 'liry'; // ORPHANED
$string['LUF'] = 'frank'; // ORPHANED
$string['MXP'] = 'peso'; // ORPHANED
$string['PLZ'] = 'złotówki'; // ORPHANED
$string['PTE'] = 'escudo'; // ORPHANED
$string['UYP'] = 'peso'; // ORPHANED
$string['YDD'] = 'dinar'; // ORPHANED
$string['YUD'] = 'dinar'; // ORPHANED

?>
