<?PHP // $Id$ 
      // error.php - created with Moodle 1.9 Beta 3 (2007101505)


$string['adminprimarynoedit'] = 'Ustawienia głównego administratora nie mogą być zmieniane przez innych';
$string['cannotcreatelangdir'] = 'Nie można utworzyć katalogu językowego';
$string['cannotcreatetempdir'] = 'Nie można utworzyć katalogu tymczasowego';
$string['cannotdownloadcomponents'] = 'Nie można pobrać składowych (komponentów)';
$string['cannotdownloadzipfile'] = 'Nie można pobrać spakowanego pliku (ZIP)';
$string['cannotfindcomponent'] = 'Nie można znaleźć komponentu';
$string['cannotsavemd5file'] = 'Nie mozna zapisać pliku md5';
$string['cannotsavezipfile'] = 'Nie można zapisać spakowanego pliku';
$string['cannotunzipfile'] = 'Nie można rozpakować pliku ZIP';
$string['cantunenrollfrommetacourse'] = 'Nie można wypisać się z kursu meta.';
$string['cantunenrollinthisrole'] = 'Nie można wypisać się z kursu przy tej roli.';
$string['cmunknown'] = 'Nie można znaleźć modułu kursu';
$string['componentisuptodate'] = 'Komponent jest aktualny';
$string['confirmsesskeybad'] = 'Niestety Twój klucz sesji nie pozwala na wykonanie tej czynności. Zabezpieczenie te zapobiega przypadkowemu lub złośliwemu wykonaniu operacji w Twoim imieniu. Zrób to, jeżeli naprawdę musisz wykonać tę operację';
$string['couldnotassignrole'] = 'Podczas przypisywania roli wystąpił poważny, nieokreślony błąd.';
$string['coursegroupunknown'] = 'Nie określono kursu dla grupy $a';
$string['downloadedfilecheckfailed'] = 'Pobierany plik jest uszkodzony';
$string['errorcleaningdirectory'] = 'Błąd czyszczenia katalogu. \"$a\"';
$string['errorcopyingfiles'] = 'Błąd kopiowania plików';
$string['errorcreatingdirectory'] = 'Błąd tworzenia katalogu. \"$a\";';
$string['errorcreatingfile'] = 'Błąd tworzenia pliku \"$a\"';
$string['erroronline'] = 'Błąd na lini $a.';
$string['errorreadingfile'] = 'Błąd odczytu pliku\"$a\"';
$string['errorunzippingfiles'] = 'Błąd rozpakowywania plików';
$string['fieldrequired'] = '\"$a\" jest polem wymaganym';
$string['filenotfound'] = 'Niestety nie mogę znaleźć pliku';
$string['forumblockingtoomanyposts'] = 'Przekroczyłeś liczbę możliwych postów, które można zamieścić na tym forum';
$string['groupalready'] = 'Użytkownik należy już do grupy $a';
$string['groupexistforcourse'] = 'Grupa \"$a\" została już utworzona w tym kursie';
$string['groupnotaddederror'] = 'Grupa \"$a\" nie została utworzona';
$string['groupunknown'] = 'Grupa $a nie jest przypisana do tego kursu';
$string['guestnoeditprofile'] = 'Gość nie może edytować swojego profilu.';
$string['guestnoeditprofileother'] = 'Profil gościa nie może być zmieniony';
$string['invalidcourse'] = 'Nieważny kurs';
$string['invalidfieldname'] = '\"$a\" nie jest nazwą dozwoloną.';
$string['invalidfiletype'] = '\"$a\" nie jest obsługiwanym typem pliku';
$string['invalidmd5'] = 'Nieważne md5';
$string['invalidrequest'] = 'Niewłaściwe żądanie';
$string['invalidrole'] = 'Niewłaściwa rola';
$string['invalidxmlfile'] = '\"$a\" nie jest obsługiwanym plikiem XLM';
$string['loginasnoenrol'] = 'Nie możesz używać funkcji \'zapisz na kurs\' i \'wypisz z kursu\', będąc zalogowanym jako inny użytkownik.';
$string['loginasonecourse'] = 'Nie możesz wejść do kursu.<br /> Musisz zakończyć sesję \'Zaloguj się jako\', aby wejść do innego kursu.';
$string['missingfield'] = 'Brakuje pola \"$a\" .';
$string['missingrequiredfield'] = 'Brak wymaganego pola';
$string['modulemissingcode'] = 'Moduł $a stracił kod niezbędny do działania tej funkcji';
$string['modulerequirementsnotmet'] = 'Moduł \"$a->modulename\" ($a->moduleversion) nie został poprawnie zainstalowany. Zainstaluj nowszą wersję Moodle! Aktualnie używasz wersji $a->currentmoodle, a potrzebujesz $a->requiremoodle).';
$string['mustbeteacher'] = 'Dostęp do tej strony mają tylko nauczyciele';
$string['noinstances'] = 'Przypadki $a nie występują w tym kursie';
$string['nologinas'] = 'Nie masz uprawnień, by zalogować się jako ten użytkownik';
$string['nonmeaningfulcontent'] = 'Brak znaczącej treści';
$string['noparticipatorycms'] = 'Nie posiadasz modułów biorących udział w kursie odpowiedzialnych za możliwość zgłoszeń.';
$string['nopermissions'] = 'Brak odpowiednich uprawnień do wykonania ($a)';
$string['notavailable'] = 'Nie jest to w tej chwili dostępne';
$string['onlyadmins'] = 'Tylko administrator może to zrobić';
$string['onlyeditingteachers'] = 'Tylko nauczyciele z uprawnieniami do edycji mogą to zrobić.';
$string['onlyeditown'] = 'Możesz edytować tylko własne informacje';
$string['pagenotexist'] = 'Pojawił się nieoczekiwany błąd
(próba połączenia z nieistniejącą stroną)';
$string['pleasereport'] = 'Aby lepiej zapobiegać takim sytuacjom w przyszłości, opisz, co próbowałeś zrobić, zanim pojawił się błąd.';
$string['pluginrequirementsnotmet'] = 'Wtyczka \"$a->pluginname\" ($a->pluginversion) nie może zostać zainstalowana. Potrzebna jest nowsza wersja Moodle (teraz używasz $a->currentmoodle,  a potrzebujesz $a->requiremoodle).';
$string['processingstops'] = 'Operacja została zatrzymana. Operacja zapisu nie została wykonana';
$string['remotedownloadnotallowed'] = 'Pobieranie komponentów na Twój serwer jest niedozwolone. Musisz pobrać pliki ręcznie z <a href=\"$a->url\">$a->url</a> i skopiować do \"$a->dest\" na swoim serwerze i tam go otworzyć';
$string['restricteduser'] = 'Twoje konto \"$a\" nie daje uprawnień do wykonania tej operacji.';
$string['sendmessage'] = 'Wyślij wiadomość';
$string['sessionerroruser'] = 'Sesja wygasła. Zaloguj się ponownie.';
$string['sessionerroruser2'] = 'Błąd serwera wpłynął na Twoją sesję logowania. Zaloguj się ponownie. Możesz też najpierw zamknąć i ponownie otworzyć przeglądarkę internetową.';
$string['sessionipnomatch'] = 'Twój nr IP został zmieniony, od kiedy zalogowałeś się po raz pierwszy. Zabezpieczenie to nie pozwala osobom niepowołanym wykorzystać Twojego identyfikatora do logowania się na tej stronie. Skontaktuj się z administratorem.';
$string['statscatchupmode'] = 'Statystyki znajdują się obecnie w trybie aktualizacji. Przez $a->daysdone dni będą przetwarzane a przez $a->dayspending są oczekujące. Sprawdź ponownie wkrótce!';
$string['unicodeupgradeerror'] = 'Twoja baza danych nie jest w formacie Unicode, a ta wersja Moodle nie może przenieść twojej bazy danych do Unicode. Najpierw aktualizuj wersję Moodle do 1.7.x i przeprowadź migrację Unicode ze strony Administracji. Później powinieneś móc przejść do Moodle $a';
$string['unknowncourse'] = 'Kurs o nazwie \"$a\" nie istnieje.';
$string['unknowncourseidnumber'] = 'Nieznane ID kursu \"$a\"';
$string['unknownuseraction'] = 'Akcja użytkownika jest niezrozumiała.';
$string['usernotaddederror'] = 'Nieznany błąd - użytkownik \"$a\" nie został dodany.';
$string['usernotaddedregistered'] = 'Użytkownik \"$a\" już istnieje.';
$string['usernotavailable'] = 'Szczegóły tego użytkownika nie są dla Ciebie dostępne';
$string['usernotrenamedexists'] = 'Użytkownik nie zmienił nazwy – nowa nazwa użytkownika jest już używana.';
$string['usernotrenamedmissing'] = 'Użytkownik nie zmienił nazwy – nie można znaleźć starej nazwy użytkownika.';
$string['wrongdestpath'] = 'Błędna scieżka docelowa';
$string['wrongsourcebase'] = 'Błędne żródło bazy URL';
$string['wrongzipfilename'] = 'Błędna nazwa pliku ZIP.';

?>
