<?PHP // $Id$ 
      // message.php - created with Moodle 1.9.3 (Build: 20081015) (2007101530)


$string['addcontact'] = 'Dodaj kontakt';
$string['addsomecontacts'] = 'Aby wysłać wiadomość lub dodać skrót do użytkowników na tej stronie, użyj <a href=\"$a\">szukaj tab</a> powyżej.';
$string['addsomecontactsincoming'] = 'Te wiadomości są od użytkowników spoza listy kontaktów. Aby dodać ich do listy, kliknij \"Dodaj kontakt\" obok nazwy użytkownika.';
$string['ago'] = '$a temu';
$string['allmine'] = 'Wszystkie moje wiadomości wysłane i otrzymane';
$string['allstudents'] = 'Wszystkie wiadomości pomiędzy uczestnikami kursu';
$string['allusers'] = 'Wszystkie wiadomości od użytkowników';
$string['backupmessageshelp'] = 'Jeżeli włączone, wiadomości będą automatycznie zachowywane.';
$string['beepnewmessage'] = 'Powiadom dźwiękiem o nowej wiadomości (wymagany plugin w przeglądarce, obsługujący dźwięk)';
$string['blockcontact'] = 'Blokuj kontakt';
$string['blockedmessages'] = '$a wiadomości od zablokowanych użytkowników';
$string['blocknoncontacts'] = 'Blokuj wiadomości od użytkowników spoza listy kontaktów';
$string['contactlistempty'] = 'Lista kontaktów jest pusta';
$string['contacts'] = 'Kontakty';
$string['context'] = 'zawartość';
$string['deletemessagesdays'] = 'Po ilu dniach wiadomości będą kasowane';
$string['discussion'] = 'Dyskusja';
$string['emailmessages'] = 'Wyślij wiadomości mailem, gdy jestem offline';
$string['emailtagline'] = 'Ten mail jest kopią wiadomości wysłanej do Ciebie o \"$a\"';
$string['emptysearchstring'] = 'Wpisz słowo kluczowe';
$string['formorethan'] = 'więcej niż';
$string['includeblockedusers'] = 'Uwzględniaj zablokowanych użytkowników';
$string['incomingcontacts'] = 'Przychodzące kontakty ($a)';
$string['keywords'] = 'Słowa kluczowe';
$string['keywordssearchresults'] = 'Wyniki wyszukiwania: $a wiadomości';
$string['mailsent'] = 'Twoja wiadomość została wysłana emailem.';
$string['maxmessages'] = 'Maksymalna liczba wiadomości w historii';
$string['message'] = 'Wiadomość';
$string['messagehistory'] = 'Historia wiadomości';
$string['messages'] = 'Wiadomości';
$string['messaging'] = 'Przesyłanie wiadomości';
$string['messagingdisabled'] = 'Przesyłanie wiadomości na tej stronie jest wyłączone; zamiast tego wiadomości będą przesłane jako emaile.';
$string['mycontacts'] = 'Moje kontakty';
$string['newonlymsg'] = 'Pokaż tylko nowe';
$string['newsearch'] = 'Nowe wyszukiwanie';
$string['noframesjs'] = 'Wersja bez ramek i JavaScript';
$string['nomessages'] = 'Brak oczekujących wiadomości';
$string['nomessagesfound'] = 'Brak wiadomości';
$string['nosearchresults'] = 'Brak rezultatów wyszukiwania';
$string['offline'] = 'Offline';
$string['offlinecontacts'] = 'Kontakty offline ($a)';
$string['online'] = 'Online';
$string['onlinecontacts'] = 'Kontakty online ($a)';
$string['onlyfromme'] = 'Wiadomości tylko ode mnie';
$string['onlymycourses'] = 'Tylko w moich kursach';
$string['onlytome'] = 'Wiadomości tylko do mnie';
$string['pagerefreshes'] = 'Strona odświeża się automatycznie co $a sekund';
$string['readmessages'] = '$a przeczytanych wiadomości';
$string['removecontact'] = 'Usuń kontakt';
$string['savemysettings'] = 'Zapisz ustawienia';
$string['search'] = 'Szukaj';
$string['searchforperson'] = 'Szukaj osoby';
$string['searchmessages'] = 'Szukaj wiadomości';
$string['sendmessage'] = 'Wyślij wiadomość';
$string['sendmessageto'] = 'Wyślij wiadomość do $a';
$string['sendmessagetopopup'] = 'Wyślij wiadomość do $a - nowe okno';
$string['settings'] = 'Ustawienia';
$string['settingssaved'] = 'Zapisano ustawienia';
$string['showmessagewindow'] = 'Pokaż okno wiadomości, gdy nadejdzie nowa (Twoja przeglądarka powinna mieć wyłączone blokowanie wyskakujących okien)';
$string['strftimedaydatetime'] = '%%A, %%d %%B %%Y, %%I:%%M %%p';
$string['timenosee'] = 'Czas od ostatniej obecności (w minutach)';
$string['timesent'] = 'Czas wysłania';
$string['unblockcontact'] = 'Odblokuj kontakt';
$string['unreadmessages'] = '$a nieprzeczytanych wiadomości';
$string['userisblockingyou'] = 'Ten użytkownik zablokował możliwość otrzymywania wiadomości od ciebie';
$string['userisblockingyounoncontact'] = 'Ten użytkownik otrzymuje wiadomości tylko od osób z listy kontaktów. Ty nie jesteś na tej liście.';
$string['userssearchresults'] = 'Wyniki wyszukiwania: $a znalezionych użytkowników';

?>
