<?PHP // $Id$ 
      // assignment.php - created with Moodle 1.7 dev (2006091901)


$string['allowmultiple'] = '여러 파일을 허용함';
$string['allowresubmit'] = '재제출 허가';
$string['assignment:grade'] = '과제 점수';
$string['assignment:submit'] = '과제 제출';
$string['assignment:view'] = '과제 보기';
$string['assignmentdetails'] = '과제 세부사항';
$string['assignmentmail'] = '$a->teacher 선생님께서 당신이 제출한 \'$a->assignment\' 과제에 대한 의견을 달아놓으셨습니다.

과제에 대한 평은 다음에서 볼 수 있습니다: $a->url';
$string['assignmentmailhtml'] = '$a->teacher 선생님께서 제출한 \'<i>$a->assignment</i>\' 과제에 대한 의견을 달아놓으셨습니다. <br /><br />
<a href=\"$a->url\">제출한 과제</a>에 꼬리가 붙어있을 것입니다.';
$string['assignmentname'] = '과제명';
$string['assignmenttype'] = '과제 형태';
$string['attachfile'] = '파일 첨부';
$string['attachfiletoassignment'] = '과제로 파일을 첨부함';
$string['availabledate'] = '가능한 형태';
$string['backtoassignment'] = '과제로 되돌아 감';
$string['backtofeedback'] = '평가항목으로 되돌아 감';
$string['choosereviewfile'] = '평가 받을 과제를 올리기 위해 선택함';
$string['comment'] = '평';
$string['commentinline'] = '즉시 처리된 평';
$string['configitemstocount'] = '온라인 과제를 제출한 학생들의 계수 항목 특성';
$string['configmaxbytes'] = '이 사이트에 있는 모든 과제의 기본 최대 크기';
$string['deletecheckfile'] = '이 파일을 지우는게 확실합니까?';
$string['deleteednotification'] = '파일이 삭제되었습니다.';
$string['deletefail'] = '다음 파일은 삭제되지 않았습니다.';
$string['description'] = '설명';
$string['duedate'] = '만기일';
$string['duedateno'] = '기한이 없습니다.';
$string['early'] = '$a 일찍 체줄함';
$string['editmysubmission'] = '제출물 편집';
$string['emailstudents'] = '학생에게 이메일로 알림';
$string['emailteachermail'] = '$a->username 은 \'$a->assignment\'에 대한 과제 제출을 갱신했습니다. 이것은 $a->url 에서 볼 수 있습니다.';
$string['emailteachermailhtml'] = '$a->username 은 <i>\'$a->assignment\'</i>에 대한 과제 제출을 갱신했습니다.<br /><br />
그것은 <a href=\"$a->url\">이 곳</a>에서 볼 수 있습니다.';
$string['emailteachers'] = '선생님들께 알림';
$string['emptysubmission'] = '아무것도 제출되지 않았습니다.';
$string['existingfiledeleted'] = '제출되었던 파일 $a 이 지워졌습니다.';
$string['failedupdatefeedback'] = '$a 가 제출한 과제에 대한 평을 갱신하는데 실패함';
$string['feedback'] = '피드백';
$string['feedbackfromteacher'] = '$a 로부터의 피드백';
$string['feedbackupdated'] = '$a 명의 과제에 대한 의견을 갱신함';
$string['graded'] = '채점됨';
$string['guestnosubmit'] = '죄송합니다. 손님은 과제를 제출할 수 없습니다. 답안을 제출하려면 로그인하거나 사용자 등록을 하시기 바랍니다.';
$string['guestnoupload'] = '죄송합니다. 손님은 업로드할 수 없습니다.';
$string['helpoffline'] = '<p>이것은 과제가 무들 외부에서 수행되어질 때 유용합니다. 웹상에서 혹은 면대면 상황에서 활용할 수 있습니다.</p> <p>학생들은 과제의 설명을 볼수 있습니다만, 파일을 올릴 수는 없습니다. 정상적으로 채점이 되며, 학생들은 성적에 대한 공지를 받을 것입니다.</p>';
$string['helponline'] = '<p>이 과제 형식은 사용자에게 표준 편집기를 이용하여 텍스트를 편집하도록 합니다. 교사들은 온라인 상에서 채점을 할 수 있으며, 즉석에서 평이나 변경사항을 입력할 수도 있습니다.</p> <p>(만일 예전의 무들에 익숙하다면, 이 과제 형식은 저널 모듈과 동일하게 작동됩니다.)</p>';
$string['helpupload'] = '<p>이 과제 유형은 학생들이 어떤 형태의 파일을 하나나 그 이상 올릴 수 있도록 합니다.</p>
<p>이는 문서 작성기에 의한 문서, 묶음 파일 등 여러분들이 제출하라고 요구한 어떤 형태라도 가능합니다.</p>
<p>이 유형은 종류를 막론하고 각 항목에 대한 여러분들의 의견을 올릴 수 있도록 허용합니다.</p>';
$string['helpuploadsingle'] = '<p>이 과제의 형태는 각각의 참여자들에게 하나의 화일을 업로드 할 것을 허락합니다.</p> <p>화일은 워드프로세서 문서 혹은 이미지, 압축된 웹 사이트, 혹은 여러분이 요청했던 어떤 것이든 관계 없습니다.</p>';
$string['late'] = '$a 늦음';
$string['markingsubmitnotification'] = '채점을 위한 과제가 성공적으로 접수되었습니다.';
$string['maximumgrade'] = '최대 점수';
$string['maximumsize'] = '최대 용량';
$string['modulename'] = '과제';
$string['modulenameplural'] = '과제모음';
$string['namedeletefile'] = '이 파일을 지우려고 합니다.';
$string['newsubmissions'] = '제출된 과제들';
$string['noassignments'] = '아직 과제가 지정되지 않았습니다.';
$string['noattempts'] = '이 과제를 제출하려는 시도가 없었음';
$string['nofilesforsubmit'] = '제출된 과제가 없습니다. - 파일을 올리시렵니까?';
$string['notgradedyet'] = '아직 채점되지 않음';
$string['notsubmittedyet'] = '아직 제출되지 않음';
$string['onceassignmentsent'] = '일단 채점을 위한 과제가 제출되고 나면, 더 이상 파일을 삭제하거나 첨부할 수 없습니다.';
$string['overwritewarning'] = '경고: 다시 업로드를 하면 기존의 내용과 대체됩니다';
$string['pagesize'] = '한 쪽당 보이는 제출물';
$string['preventlate'] = '제출 기한 엄수';
$string['quickgrade'] = '신속 채점 허용';
$string['removelink'] = '링크제거';
$string['responsefile'] = '응답 파일';
$string['responsesfromteacher'] = '선생님이 올린 평';
$string['saveallfeedback'] = '내 의견을 모두 저장';
$string['sendformarking'] = '채점을 위한 제출';
$string['step1'] = '1단계';
$string['step2'] = '2단계';
$string['submission'] = '제출';
$string['submissionfeedback'] = '과제에 대한 의견';
$string['submissions'] = '제출된 과제들';
$string['submissionsaved'] = '변경 사항이 저장되었습니다';
$string['submissionsnotgraded'] = '$a 제출된 것이 채점되지 않음';
$string['submissionstatus'] = '체출 상황';
$string['submissionstatusblank'] = '비었음';
$string['submissionstatusdraft'] = '낙제';
$string['submissionstatusmarked'] = '채점됨';
$string['submissionstatusreturned'] = '반송';
$string['submissionstatussubmitted'] = '제출됨';
$string['submitassignment'] = '이 양식을 사용하여 과제를 제출함';
$string['submitformarking'] = '채점을 위한 과제 제출';
$string['submitted'] = '제출 완료';
$string['typeoffline'] = '오프라인 활동';
$string['typeonline'] = '온라인 문서';
$string['typeupload'] = '파일 올리기';
$string['typeuploadsingle'] = '한 개의 파일을 올림';
$string['uploadbadname'] = '파일이름에 알 수 없는 문자가 포함되있어서 올릴 수 없음';
$string['uploadedfiles'] = '올려진 파일들';
$string['uploaderror'] = '서버에 파일을 저장하던 중 오류 발생';
$string['uploadfailnoupdate'] = '파일이 성공적으로 전송되었지만 제출 상황을 갱신할 수는 없음';
$string['uploadfiletoobig'] = '파일용량이 너무 큽니다 ($a bytes 까지)';
$string['uploadnofilefound'] = '파일을 찾을 수 없음 - 업로드할 파일을 선택하셨습니까?';
$string['uploadnotregistered'] = '\'$a\' 는 전송 되었지만 제출된 과제는 등록되지 않음';
$string['uploadsuccess'] = '\'$a\' 가 성공적으로 업로드됨';
$string['uploadsuccessresponse'] = '응답파일이 성공적으로 올려짐';
$string['viewfeedback'] = '과제 점수와 피드백 보기';
$string['viewsubmissions'] = '내가 제출한  $a 개의 과제 보기';
$string['yoursubmission'] = '과제 제출';

?>
