<?PHP // $Id$ 
      // portfolio.php - created with Moodle 2.0 dev (Build: 20080819) (2008081600)


$string['addalltoportfolio'] = '모두 포트폴리오에 추가';
$string['addnewportfolio'] = '포트폴리오 작성';
$string['addtoportfolio'] = '포트폴리오에 추가';
$string['alreadyexporting'] = '이미 본 세션에서 포트폴리오를 내보냈습니다. 우선 그 내용을 완성하기 바랍니다.';
$string['availableformats'] = '이용가능한 내보내기 형식';
$string['callercouldnotpackage'] = '내보내기 위한 자료 묶기 실패';
$string['cannotsetvisible'] = '공개로 설정할 수 없음 - 설정오류로 인해 플러그인이 작동 불가';
$string['configexport'] = '내보낼 자료 설정';
$string['configplugin'] = '포트폴리오 플러그인 설정';
$string['configure'] = '설정';
$string['confirmexport'] = '내보낼 사항을 확인하기 바람';
$string['confirmsummary'] = '내보낼 항목 개요';
$string['continuetoportfolio'] = '포트폴리오 계속';
$string['deleteportfolio'] = '포트폴리오 인스턴스 삭제';
$string['disabled'] = '죄송합니다만, 이 사이트에서는 포트폴리오 내보내기가 되지 않습니다';
$string['dontwait'] = '기다리지 말 것';
$string['enabled'] = '포트폴리오 가능';
$string['enableddesc'] = '사용자의 포트폴리오 내용을 관리자가 원격 시스템을 조정하여 내보낼 수 있게 허용할 것임';
$string['err_uniquename'] = '포트폴리오의 명칭은 중복되면 안됨';
$string['exportcomplete'] = '포트폴리오 내보내기 성공!';
$string['exportedpreviously'] = '이전에 내보낸 포트폴리오';
$string['exporting'] = '포트폴리오 내보내기';
$string['exportqueued'] = '포트폴리오 내보내기 준비작업 성공';
$string['failedtosendpackage'] = '지정된 포트폴리오 시스템에 자료 전송 실패!';
$string['filedenied'] = '접속이 허용되지 않음';
$string['filenotfound'] = '파일 없음';
$string['format_file'] = '파일';
$string['format_mbkp'] = '무들 백업';
$string['hidden'] = '비공개';
$string['instancedeleted'] = '포트폴리오 삭제 완료';
$string['instanceismisconfigured'] = '포트폴리오 설정오류로 중지됨. $a 오류';
$string['instancenotdelete'] = '포트폴리오 삭제 실패';
$string['instancenotsaved'] = '포트폴리오 저장 실패';
$string['instancesaved'] = '포트폴리오 저장 완료';
$string['invalidaddformat'] = 'portfolio_add_button에 잘못된 추가 형식 전달.  ($a) 반드시 PORTFOLIO_ADD_XXX 중에 하나가 되어야 함';
$string['invalidformat'] = '잘못된 형식 $a 로 내보내려 하고 있음';
$string['invalidinstance'] = '포트폴리오 인스턴스가 없음';
$string['invalidtempid'] = '잘못된 임시 ID';
$string['manageportfolios'] = '포트폴리오 관리';
$string['manageyourportfolios'] = '내 포트폴리오 관리';
$string['noavailableplugins'] = '내보낼 포트폴리오가 없음';
$string['nocallbackfile'] = '내보내려는 포트폴리오가 깨졌음 - 요청한 $a 파일을 찾을 수 없음';
$string['nocommonformats'] = '요청한 $a 와 이용가능한 플러그인 사이에 공유 형식이 없음';
$string['nonprimative'] = 'portfolio_add_button으로 초기값 전송없음. 작업 중단.  $a->key 키의 키값은 $a->value 였음';
$string['nopermissions'] = '죄송합니다만, 이 영역에서 파일을 내보낼 권한이 없음';
$string['notexportable'] = '죄송합니다만, 내보낼 수 없는 내용 형식을 지정하였음';
$string['notimplemented'] = '죄송합니다만, 아직 지원하지 않는 ($a) 형식으로 내용을 내보내려 하고 있습니다.';
$string['nouploaddirectory'] = '자료를 묶을 임시 저장고를 생생할 수 없음';
$string['plugin'] = '포트폴리오 플러그인';
$string['plugincouldnotpackage'] = '내보낼 자료를 묶는 데 실패';
$string['portfolio'] = '포트폴리오';
$string['portfolios'] = '포트폴리오';
$string['returntowhereyouwere'] = '원래 위치로 돌아감';
$string['save'] = '저장';
$string['selectedformat'] = '선택된 내볼낼 형식';
$string['selectedwait'] = '기다릴까요?';
$string['selectplugin'] = '내보낼 플러그인 선택';
$string['someinstancesdisabled'] = '설정오류거나 알지 못하는 이유에 의해 플러그인 인스턴스 작동 안 됨';
$string['somepluginsdisabled'] = '설정오류거나 알지 못하는 이유에 의해 전체 플러그인 작동 안 됨';
$string['sure'] = '\'$a\'를 삭제하겠습니까? 이는 되돌이킬 수 없습니다.';
$string['wait'] = '대기';
$string['wanttowait_high'] = '완료되기까지 대기하는 것을 권장하지는 않습니다만, 확실하게 그 결과를 알고 싶다면 대기하실 수 있습니다.';
$string['wanttowait_moderate'] = '전송을 위해 대기하길 원하십니까? 수분 정도 걸립니다.';
$string['portfolionotfile'] = '파일대신 포트폴리오로 내보냄'; // ORPHANED

?>
