<?PHP // $Id$ 
      // auth.php - created with Moodle 1.8.2+ (2007021520)


$string['CASform'] = 'Dewis dilysu';
$string['accesCAS'] = 'defnyddwyr CAS';
$string['accesNOCAS'] = 'defnyddwyr eraill';
$string['alternatelogin'] = 'Os teipiwch URL yma, caiff ei ddefnyddio fel tudalen mewngofnodi\'r safle hwn. Dylai\'r dudalen gynnwys ffurflen gyda\'r briodwedd gweithredu wedi\'i osod yn <strong>\'$a\'</strong> a\'r meysydd dychwelyd <strong>enw defnyddiwr</strong> a <strong>chyfrinair</strong>.<br />Byddwch yn ofalus i beidio â theipio URL anghywir, oherwydd gallai hyn eich cloi allan o\'r safle.<br />Gadewch y gosodiad hwn yn wag i ddefnyddio\'r dudalen mewngofnodi ddiofyn.';
$string['alternateloginurl'] = 'URL mewngofnodi gwahanol';
$string['auth_cas_auth_user_create'] = 'Creu defnyddwyr yn allanol';
$string['auth_cas_baseuri'] = 'URI y gweinydd (dim byd os nad oes baseUri)<br />Er enghraifft, os yw\'r gweinydd CAS yn ymateb i host.domaine.fr/CAS/ yna<br />cas_baseuri = CAS/';
$string['auth_cas_baseuri_key'] = 'URI sylfaenol';
$string['auth_cas_broken_password'] = 'Ni allwch fwrw ymlaen heb newid eich cyfrinair. Fodd bynnag, nid oes tudalen ar gael i\'w newid. Cysylltwch â\'ch Gweinyddwr Moodle.';
$string['auth_cas_cantconnect'] = 'All rhan LDAP y modiwl-CAS ddim cysylltu â\'r gweinydd: $a';
$string['auth_cas_casversion'] = 'Fersiwn';
$string['auth_cas_changepasswordurl'] = 'URL newid-cyfrinair';
$string['auth_cas_create_user'] = 'Galluogwch hwn os ydych chi am fewnosod defnyddwyr a ddilyswyd gan CAS mewn cronfa ddata Moodle. Os na wnewch, dim ond defnyddwyr sydd eisoes yn bodoli yn y gronfa ddata Moodle all fewngofnodi.';
$string['auth_cas_create_user_key'] = 'Creu defnyddiwr';
$string['auth_cas_enabled'] = 'Galluogwch hwn os ydych am ddefnyddior broses dilysu CAS.';
$string['auth_cas_hostname'] = 'Enw gwesteiwr y gweinydd CAS <br />e.e.: host.domain.fr';
$string['auth_cas_hostname_key'] = 'Enw\'r gwesteiwr';
$string['auth_cas_invalidcaslogin'] = 'Mae\'n flin gennyf, ni lwyddwyd i\'ch mewngofnodi - doedd dim modd eich awdurdodi';
$string['auth_cas_language'] = 'Iaith a ddewiswyd';
$string['auth_cas_language_key'] = 'Iaith';
$string['auth_cas_logincas'] = 'Mynediad drwy gysylltiad diogel';
$string['auth_cas_logoutcas'] = 'Newidiwch hwn i \'iawn\' os ydych chi eisiau allgofnodi o CAS wrth ddatgysylltu o Moodle';
$string['auth_cas_logoutcas_key'] = 'Allgofnodi CAS';
$string['auth_cas_multiauth'] = 'Newidiwch hwn i \'iawn\' os ydych chi eisiau aml-ddilysu (CAS a dull dilysu arall)';
$string['auth_cas_multiauth_key'] = 'Aml-ddilysu';
$string['auth_cas_port'] = 'Porth y gweinydd CAS';
$string['auth_cas_port_key'] = 'Porth';
$string['auth_cas_proxycas'] = 'Newidiwch hwn i \"iawn\" os ydych chi\'n defnyddio CAS yn y modd dirprwyol';
$string['auth_cas_proxycas_key'] = 'Modd dirprwyol';
$string['auth_cas_server_settings'] = 'Ffurfweddiad y gweinydd CAS';
$string['auth_cas_text'] = 'Cysylltiad diogel';
$string['auth_cas_use_cas'] = 'Defnyddio CAS';
$string['auth_cas_version'] = 'Fersiwn o CAS';
$string['auth_casdescription'] = 'Mae\'r dull hwn yn defnyddio gweinydd CAS (Gwasanaeth Dilysu Canolog) i ddilysu defnyddwyr mewn amgylchedd Mewngofnodi Unigol (SSO). Gallwch hefyd ddefnyddio dull dilysu LDAP syml. Os yw\'r enw defnyddiwr a\'r cyfrinair a roddir yn ddilys yn ôl CAS, bydd Moodle yn creu cofnod defnyddiwr newydd yn ei gronfa ddata, gan gymryd priodweddau\'r defnyddiwr o LDAP os oes eu hangen. Wrth fewngofnodi ar ôl hynny, dim ond yr enw defnyddiwr a\'r cyfrinair gaiff eu gwirio.';
$string['auth_casnotinstalled'] = 'Does dim modd defnyddio dilysiad CAS. Nid yw\'r modiwl PHP LDAP wedi\'i osod.';
$string['auth_castitle'] = 'Gweinyddwr CAS (SSO)';
$string['auth_changepasswordhelp'] = 'Help i newid cyfrinair';
$string['auth_changepasswordhelp_expl'] = 'Dangos help ar gyfer cyfrinair coll i ddefnyddwyr sydd wedi colli eu cyfrinair $a. Dangosir hwn yn ogystal â, neu yn lle\'r <strong>URL Newid Cyfrinair</strong> neu newid cyfrinair Moodle Mewnol.';
$string['auth_changepasswordurl'] = 'URL newid cyfrinair';
$string['auth_changepasswordurl_expl'] = 'Nodwch yr url i\'w anfon i ddefnyddwyr sydd wedi colli eu cyfrinair $a. Dewiswch <strong>beidio â</strong> <strong>Defnyddio\'r dudalen Newid Cyfrinair safonol</strong>.';
$string['auth_common_settings'] = 'Gosodiadau cyffredin';
$string['auth_data_mapping'] = 'Mapio data';
$string['auth_dbcantconnect'] = 'Doedd dim modd cysylltu â\'r gronfa ddata dilysu a bennwyd...';
$string['auth_dbchangepasswordurl_key'] = 'URL newid cyfrinair';
$string['auth_dbdebugauthdb'] = 'Dadfygio ADOdb';
$string['auth_dbdebugauthdbhelp'] = 'Dadfygio\'r cysylltiad ADOdb â\'r gronfa ddata allanol - defnyddiwch hwn pan gewch dudalen wag wrth fewngofnodi. Nid yw hyn yn addas ar gyfer safleoedd cynhyrchu.';
$string['auth_dbdeleteuser'] = 'Wedi dileu defnyddiwr $a[0] id $a[1]';
$string['auth_dbdeleteusererror'] = 'Gwall wrth ddileu defnyddiwr $a';
$string['auth_dbdescription'] = 'Mae\'r dull hwn yn defnyddio tabl cronfa ddata allanol i wirio a yw enw defnyddiwr a chyfrinair a roddir yn ddilys. Os yw\'r cyfrif yn un newydd, gellir copïo gwybodaeth o feysydd eraill drosodd i Moodle hefyd.';
$string['auth_dbextencoding'] = 'Amgodio cronfa ddata allanol';
$string['auth_dbextencodinghelp'] = 'Amgodio a ddefnyddir mewn cronfa ddata allanol';
$string['auth_dbextrafields'] = 'Mae\'r meysydd hyn yn ddewisol.  Gallwch ddewis llenwi rhai meysydd Moodle ymlaen llaw gyda gwybodaeth o\'r <b>meysydd cronfa ddata allanol</b> a bennwch yma. <p>Os gadewch y rhain yn wag, defnyddir y rhagosodiadau.</p><p>Yn y naill achos a\'r llall, bydd y defnyddiwr yn gallu golygu\'r holl feysydd hyn ar ôl mewngofnodi.</p>';
$string['auth_dbfieldpass'] = 'Enw\'r maes sy\'n cynnwys cyfrineiriau';
$string['auth_dbfieldpass_key'] = 'Maes cyfrinair';
$string['auth_dbfielduser'] = 'Enw\'r maes sy\'n cynnwys enwau defnyddwyr';
$string['auth_dbfielduser_key'] = 'Maes enw defnyddiwr';
$string['auth_dbhost'] = 'Y cyfrifiadur sy\'n westeiwr i weinydd y gronfa ddata.';
$string['auth_dbhost_key'] = 'Gwesteiwr';
$string['auth_dbinsertuser'] = 'Wedi mewnosod defnyddiwr $a[0] id $a[1]';
$string['auth_dbinsertusererror'] = 'Gwall wrth fewnosod defnyddiwr $a';
$string['auth_dbname'] = 'Enw\'r gronfa ddata ei hun';
$string['auth_dbname_key'] = 'Enw Cronfa Ddata';
$string['auth_dbpass'] = 'Cyfrinair yn cyfateb i\'r enw defnyddiwr uchod';
$string['auth_dbpass_key'] = 'Cyfrinair';
$string['auth_dbpasstype'] = '<p>Nodwch y fformat y mae\'r maes cyfrinair yn ei ddefnyddio. Mae stwnsio MD5 yn ddefnyddiol er mwyn cysylltu â rhaglenni gwe cyffredin eraill megis PostNuke.</p> <p>Defnyddiwch \'mewnol\' os ydych chi am i\'r gronfa ddata allanol reoli enwau defnyddwyr &amp; cyfeiriadau e-bost, ond am i Moodle reoli cyfrineiriau. Os defnyddiwch \'mewnol\', <i>rhaid</i> i chi lenwi\'r maes cyfeiriad e-bost yn y gronfa ddata allanol, a rhaid i chi weithredu admin/cron.php ac auth/db/auth_db_sync_users.php yn rheolaidd. Bydd Moodle yn anfon neges e-bost at ddefnyddwyr newydd gyda chyfrinair dros dro.</p>';
$string['auth_dbpasstype_key'] = 'Fformat cyfrinair';
$string['auth_dbreviveduser'] = 'Wedi adfer defnyddiwr $a[0] id $a[1]';
$string['auth_dbrevivedusererror'] = 'Gwall wrth adfer defnyddiwr $a';
$string['auth_dbsetupsql'] = 'Gorchymyn cysodi SQL';
$string['auth_dbsetupsqlhelp'] = 'Gorchymyn SQL i drefnu cronfa ddata arbennig, defnyddir hwn yn aml i drefnu amgodio cyfathrebu - er enghraifft ar gyfer MySQL a PostgreSQL: <em>SET NAMES \'utf8\'</em>';
$string['auth_dbsuspenduser'] = 'Wedi gwahardd y defnyddiwr $a[0] id $a[1]';
$string['auth_dbsuspendusererror'] = 'Gwall wrth wahardd y defnyddiwr $a';
$string['auth_dbsybasequoting'] = 'Defnyddio dyfyniadau sybase';
$string['auth_dbsybasequotinghelp'] = 'Dyfyniad sengl math sybase yn dianc - mae ei angen ar gyfer cronfeydd data Oracle, MS SQL a rhai mathau eraill. Peidiwch â\'i ddefnyddio ar gyfer MySQL!';
$string['auth_dbtable'] = 'Enw\'r tabl yn y gronfa ddata';
$string['auth_dbtable_key'] = 'Tabl';
$string['auth_dbtitle'] = 'Cronfa ddata allanol';
$string['auth_dbtype'] = 'Math o gronfa ddata (Gweler y <a href=\"../lib/adodb/readme.htm#drivers\">dogfennau ADOdb</a> am fwy o fanylion)';
$string['auth_dbtype_key'] = 'Cronfa ddata';
$string['auth_dbupdatinguser'] = 'Wrthi\'n diweddaru\'r defnyddiwr $a[0] id $a[1]';
$string['auth_dbuser'] = 'Enw defnyddiwr gyda mynediad darllen i\'r gronfa ddata';
$string['auth_dbuser_key'] = 'Defnyddiwr Cronfa Ddata';
$string['auth_dbusernotexist'] = 'Does dim modd diweddaru defnyddiwr nad yw\'n bodoli: $a';
$string['auth_dbuserstoadd'] = 'Cofnodion defnyddwyr i\'w hychwanegu: $a';
$string['auth_dbuserstoremove'] = 'Cofnodion defnyddwyr i\'w dileu: $a';
$string['auth_emaildescription'] = 'Cadarnhad e-bost yw\'r dull dilysu diofyn. Pan fydd y defnyddiwr yn cofrestru, gan ddewis ei enw defnyddiwr a\'i gyfrinair ei hun, anfonir e-bost cadarnhau i gyfeiriad e-bost y defnyddiwr. Mae\'r e-bost hwn yn cynnwys dolen ddiogel at dudalen lle gall y defnyddiwr gadarnhau ei gyfrif. Wrth fewngofnodi yn y dyfodol,yr unig beth a wneir fydd gwirio\'r enw defnyddiwr a\'r cyfrinair yn erbyn y gwerthoedd sydd wedi\'u storio yng nghronfa ddata Moodle.';
$string['auth_emailnoemail'] = 'Wedi ceisio anfon e-bost atoch ond wedi methu!';
$string['auth_emailnoinsert'] = 'Doedd dim modd ychwanegu eich cofnod at y gronfa ddata!';
$string['auth_emailtitle'] = 'Hunangofrestru drwy e-bost';
$string['auth_fcchangepasswordurl'] = 'URL newid cyfrinair';
$string['auth_fcconnfail'] = 'Cysylltiad wedi methu gydag Errno: $a[0] a Llinyn Gwall: $a[1]';
$string['auth_fccreators'] = 'Rhestr o\'r grwpiau y caiff eu haelodau greu cyrsiau newydd. Gwahanwch fwy nag un grŵp gyda \';\'. Rhaid sillafu\'r enwau\'n union yr un fath ag ar y gweinydd FirstClass. Mae\'r system yn gwahaniaethu rhwng priflythrennau a llythrennau bach.';
$string['auth_fccreators_key'] = 'Crewyr';
$string['auth_fcdescription'] = 'Mae\'r dull hwn yn defnyddio gweinydd FirstClass i wirio a yw\'r enw defnyddiwr a\'r cyfrinair a roddir yn ddilys.';
$string['auth_fcfppport'] = 'Porth gweinydd (3333 yw\'r mwyaf cyffredin)';
$string['auth_fcfppport_key'] = 'Porth';
$string['auth_fchost'] = 'Cyfeiriad y gweinydd FirstClass. Defnyddiwch y rhif IP neu\'r enw DNS.';
$string['auth_fchost_key'] = 'Gwesteiwr';
$string['auth_fcpasswd'] = 'Cyfrinair ar gyfer y cyfrif uchod.';
$string['auth_fcpasswd_key'] = 'Cyfrinair';
$string['auth_fctitle'] = 'Gweinydd FirstClass';
$string['auth_fcuserid'] = 'ID defnyddiwr ar gyfer cyfrif FirstClass gyda hawliau \'Is-weinyddwr\'.';
$string['auth_fcuserid_key'] = 'ID Defnyddiwr';
$string['auth_fieldlock'] = 'Cloi gwerth';
$string['auth_fieldlock_expl'] = '<p><b>Cloi gwerth:</b> Os galluogir hwn, bydd yn atal defnyddwyr Moodle a gweinyddwyr rhag golygu\'r maes yn uniongyrchol. Defnyddiwch y dewis hwn os ydych yn cynnal y data hwn yn y system dilysu allanol. </p>';
$string['auth_fieldlocks'] = 'Cloi meysydd defnyddwyr';
$string['auth_fieldlocks_help'] = '<p>Gallwch gloi meysydd data defnyddwyr. Mae hyn yn ddefnyddiol i safleoedd lle cynhelir data\'r defnyddwyr gan y gweinyddwyr eu hunain drwy olygu cofnodion y defnyddwyr, neu drwy eu llwytho i fyny gan ddefnyddio\'r cyfleustod \'Llwytho defnyddwyr i fyny\'. Os ydych chi\'n cloi meysydd y mae eu hangen ar Moodle, sicrhewch eich bod yn darparu\'r data hwnnw wrth greu cyfrifon defnyddwyr neu ni fydd modd defnyddio\'r cyfrifon.</p><p>Gallech ystyried dewis \'Datgloi os yn wag\' fel modd cloi i osgoi\'r broblem hon.</p>';
$string['auth_imapchangepasswordurl_key'] = 'URL newid cyfrinair';
$string['auth_imapdescription'] = 'Mae\'r dull hwn yn defnyddio gweinydd IMAP i wirio a yw\'r enw defnyddiwr a\'r cyfrinair a roddwyd yn ddilys.';
$string['auth_imaphost'] = 'Cyfeiriad y gweinydd IMAP. Defnyddiwch y rhif IP, nid yr enw DNS.';
$string['auth_imaphost_key'] = 'Gwesteiwr';
$string['auth_imapnotinstalled'] = 'Does dim modd defnyddio dilysu IMAP. Nid yw\'r modiwl PHP IMAP wedi\'i osod.';
$string['auth_imapport'] = 'Rhif porth y gweinydd IMAP. Fel arfer, 143 neu 993 fydd hwn.';
$string['auth_imapport_key'] = 'Porth';
$string['auth_imaptitle'] = 'Gweinydd IMAP';
$string['auth_imaptype'] = 'Math y gweinydd IMAP.  Gall gweinyddion IMAP gael gwahanol ddulliau dilysu a negodi.';
$string['auth_imaptype_key'] = 'Math';
$string['auth_ldap_auth_user_create_key'] = 'Creu defnyddwyr yn allanol';
$string['auth_ldap_bind_dn'] = 'Os ydych chi am ddefnyddio rhwymo defnyddwyr i chwilio ymysg defnyddwyr, nodwch hynny yma. Rhywbeth fel \'cn=ldapuser,ou=public,o=org\'';
$string['auth_ldap_bind_dn_key'] = 'Enw Enwog';
$string['auth_ldap_bind_pw'] = 'Cyfrinair ar gyfer rhwymo defnyddwyr.';
$string['auth_ldap_bind_pw_key'] = 'Cyfrinair';
$string['auth_ldap_bind_settings'] = 'Gosodiadau rhwymo';
$string['auth_ldap_changepasswordurl_key'] = 'URL newid cyfrinair';
$string['auth_ldap_contexts'] = 'Rhestr o\'r cyd-destunau lle mae defnyddwyr wedi\'u lleoli. Gwahanwch wahanol gyd-destunau gyda \';\'. Er enghraifft: \'ou=users,o=org; ou=others,o=org\'';
$string['auth_ldap_contexts_key'] = 'Cyd-destunau';
$string['auth_ldap_create_context'] = 'Os ydych chi\'n galluogi creu defnyddwyr gyda chadarnhad e-bost, nodwch y cyd-destun lle caiff defnyddwyr eu creu. Dylai\'r cyd-destun hwn fod yn wahanol i ddefnyddwyr eraill er mwyn atal problemau diogelwch. Does dim rhaid i chi ychwanegu\'r cyd-destun hwn at ldap_context-variable, bydd Moodle yn chwilio am ddefnyddwyr o\'r cyd-destun hwn yn awtomatig.<br /><b>Cofiwch!</b> Rhaid i chi addasu\'r dull user_create() yn y ffeil auth/ldap/auth.php fel bod y broses creu defnyddwyr yn gweithio';
$string['auth_ldap_create_context_key'] = 'Cyd-destun ar gyfer defnyddwyr newydd';
$string['auth_ldap_creators'] = 'Rhestr o grwpiau y mae gan eu haelodau hawl i greu cyrsiau newydd. Gwahanwch wahanol grwpiau gyda \';\'. Fel arfer rhywbeth fel \'cn=teachers,ou=staff,o=myorg\'';
$string['auth_ldap_creators_key'] = 'Crewyr';
$string['auth_ldap_expiration_desc'] = 'Dewiswch Na i analluogi gwirio hen gyfrineiriau neu i LDAP ddarllen amser dod i ben cyfrineiriau\'n uniongyrchol o LDAP';
$string['auth_ldap_expiration_key'] = 'Dod i ben';
$string['auth_ldap_expiration_warning_desc'] = 'Nifer y diwrnodau cyn rhoi rhybudd bod y cyfrinair yn dod i ben.';
$string['auth_ldap_expiration_warning_key'] = 'Rhybudd dod i ben';
$string['auth_ldap_expireattr_desc'] = 'Dewisol: yn diystyru\'r priodoledd ldap sy\'n storio amser dod i ben y cyfrinair';
$string['auth_ldap_expireattr_key'] = 'Priodoledd dod i ben';
$string['auth_ldap_graceattr_desc'] = 'Dewisol: yn diystyru\'r priodoledd mewngofnodi gras';
$string['auth_ldap_gracelogin_key'] = 'Priodoledd mewngofnodi gras';
$string['auth_ldap_gracelogins_desc'] = 'Galluogi mewngofnodi gras LDAP. Ar ôl i\'r cyfrinair ddod i ben, gall y defnyddiwr fewngofnodi tan i\'r cyfrif mewngofnodi gras gyrraedd 0. Bydd galluogi\'r gosodiad hwn yn dangos neges mewngofnodi gras os yw\'r cyfrinair wedi dod i ben.';
$string['auth_ldap_gracelogins_key'] = 'Mewngofnodi gras';
$string['auth_ldap_host_url'] = 'Pennwch y gweinydd LDAP ar ffurf URL, fel \'ldap://ldap.myorg.com/\' neu \'ldaps://ldap.myorg.com/\' Gwahanwch wahanol weinyddion gyda \';\' i gael cefnogaeth rhag methu.';
$string['auth_ldap_host_url_key'] = 'URL Gwesteiwr';
$string['auth_ldap_ldap_encoding'] = 'Pennwch yr amgodio a ddefnyddir gan y gweinydd LDAP. Yr un mwyaf tebygol yw utf-8; mae MS AD v2 yn defnyddio amgodio platfform diofyn megis cp1252, cp1250, ayb.';
$string['auth_ldap_ldap_encoding_key'] = 'Amgodio LDAP';
$string['auth_ldap_login_settings'] = 'Gosodiadau mewngofnodi';
$string['auth_ldap_memberattribute'] = 'Dewisol: pan fydd defnyddwyr yn perthyn i grŵp, bydd yn diystyru priodoledd aelod defnyddiwr. Fel arfer \'aelod\'';
$string['auth_ldap_memberattribute_isdn'] = 'Dewisol: yn diystyru trin gwerthoedd priodoleddau aelodau, naill ai 0 neu 1';
$string['auth_ldap_memberattribute_isdn_key'] = 'Priodoledd aelod yn defnyddio dn';
$string['auth_ldap_memberattribute_key'] = 'Priodoledd aelod';
$string['auth_ldap_noconnect'] = 'All y modiwl LDAP ddim cysylltu â\'r gweinydd: $a';
$string['auth_ldap_noconnect_all'] = 'All y modiwl LDAP ddim cysylltu ag unrhyw weinydd: $a';
$string['auth_ldap_noextension'] = 'Rhybudd: Nid yw\'n ymddangos bod y modiwl PHP LDAP yn bresennol. Gwnewch yn siŵr ei fod wedi ei osod a\'i alluogi.';
$string['auth_ldap_objectclass'] = 'Dewisol: yn diystyru objectClass a ddefnyddir i enwi/chwilio ymysg defnyddwyr ar ldap_user_type. Fel arfer, ni fydd angen i chi newid hwn.';
$string['auth_ldap_objectclass_key'] = 'Dosbarth gwrthrych';
$string['auth_ldap_opt_deref'] = 'Pennu sut caiff enwau eraill y defnyddwyr eu trin yn ystod chwiliad. Dewiswch un o\'r gwerthoedd canlynol: \"Na\" (LDAP_DEREF_NEVER) neu \"Iawn\" (LDAP_DEREF_ALWAYS)';
$string['auth_ldap_opt_deref_key'] = 'Dadgyfeirio enwau eraill';
$string['auth_ldap_passtype'] = 'Pennu fformat cyfrineiriau newydd neu rai sydd wedi\'u newid yn y gweinydd LDAP.';
$string['auth_ldap_passtype_key'] = 'Fformat cyfrinair';
$string['auth_ldap_passwdexpire_settings'] = 'Gosodiadau dod-i-ben cyfrinair LDAP.';
$string['auth_ldap_preventpassindb'] = 'Dewiswch \'Iawn\' i atal cyfrineiriau rhag cael eu storio yng nghronfa ddata Moodle.';
$string['auth_ldap_preventpassindb_key'] = 'Cuddio cyfrineiriau';
$string['auth_ldap_search_sub'] = 'Chwilio defnyddwyr mewn is-gyd-destunau.';
$string['auth_ldap_search_sub_key'] = 'Chwilio is-gyd-destunau';
$string['auth_ldap_server_settings'] = 'Gosodiadau\'r gweinydd LDAP';
$string['auth_ldap_unsupportedusertype'] = 'All dilysu: ldap user_create() ddim delio â\'r math o ddefnyddiwr a ddewiswyd: \"$a\" (..eto)';
$string['auth_ldap_update_userinfo'] = 'Diweddaru gwybodaeth defnyddiwr (enw cyntaf, cyfenw, cyfeiriad..) o LDAP i Moodle. Pennwch osodiadau \"Mapio data\" yn ôl yr angen.';
$string['auth_ldap_user_attribute'] = 'Dewisol: yn diystyru\'r priodoledd a ddefnyddir i enwi/chwilio defnyddwyr. Fel arfer \'cn\'.';
$string['auth_ldap_user_attribute_key'] = 'Nodwedd defnyddiwr';
$string['auth_ldap_user_settings'] = 'Gosodiadau edrych am ddefnyddiwr';
$string['auth_ldap_user_type'] = 'Dewiswch sut caiff defnyddwyr eu storio yn LDAP. Mae\'r gosodiad hwn hefyd yn pennu sut y bydd y canlynol yn gweithio: mewngofnodi\'n dod i ben, mewngofnodi gras a chreu defnyddwyr.';
$string['auth_ldap_user_type_key'] = 'Math o ddefnyddiwr';
$string['auth_ldap_usertypeundefined'] = 'config.user_type heb ei ddiffinio neu ffwythiant ldap_expirationtime2unix yn methu delio â\'r math a ddewiswyd!';
$string['auth_ldap_usertypeundefined2'] = 'config.user_type heb ei ddiffinio neu ffwythiant ldap_unixi2expirationtime yn methu delio â\'r math a ddewiswyd!';
$string['auth_ldap_version'] = 'Fersiwn y protocol LDAP y mae eich gweinydd yn ei ddefnyddio.';
$string['auth_ldap_version_key'] = 'Fersiwn';
$string['auth_ldapdescription'] = 'Mae\'r dull hwn yn dilysu yn erbyn gweinydd LDAP allanol.

Os yw\'r enw defnyddiwr a\'r cyfrinair a roddir yn ddilys, bydd Moodle yn creu cofnod defnyddiwr

newydd yn ei gronfa ddata. Gall y modiwl hwn ddarllen priodoleddau defnyddwyr o feysydd LDAP a meysydd y mae angen

eu llenwi ymlaen llaw yn Moodle. Wrth fewngofnodi ar ôl hynny, dim ond yr enw defnyddiwr a\'r 

cyfrinair gaiff eu gwirio.';
$string['auth_ldapextrafields'] = 'Mae\'r meysydd hyn yn ddewisol. Gallwch ddewis llenwi rhai o feysydd defnyddiwr Moodle ymlaen llaw gyda gwybodaeth o\'r <b>meysydd LDAP</b> a bennwch yma. <p>Os gadewch y meysydd hyn yn wag, ni fydd dim byd yn cael ei drosglwyddo o LDAP, a defnyddir rhagosodiadau Moodle yn eu lle.</p><p>Yn y naill achos a\'r llall, bydd y defnyddiwr yn gallu golygu\'r holl feysydd hyn ar ôl mewngofnodi.</p>';
$string['auth_ldapnotinstalled'] = 'Does dim modd defnyddio dull dilysu LDAP. Dydy\'r modiwl PHP LDAP ddim wedi ei osod.';
$string['auth_ldaptitle'] = 'Gweinydd LDAP';
$string['auth_manualdescription'] = 'Mae\'r dull hwn yn dileu unrhyw ffordd i ddefnyddwyr greu eu cyfrifon eu hunain. Bydd rhaid i\'r gweinyddwr greu pob cyfrif.';
$string['auth_manualtitle'] = 'Cyfrifon wedi\'u creu gan ddefnyddwyr';
$string['auth_mnet_auto_add_remote_users'] = 'Os dewisir Iawn, caiff cofnod defnyddiwr lleol ei greu\'n awtomatig pan fydd defnyddiwr pell yn mewngofnodi am y tro cyntaf.';
$string['auth_mnet_roamin'] = 'Gall defnyddwyr y gwesteiwr hwn grwydro i\'ch safle';
$string['auth_mnet_roamout'] = 'Gall eich defnyddwyr grwydro allan at y gwesteiwyr hyn';
$string['auth_mnet_rpc_negotiation_timeout'] = 'Yr amser hiraf mewn eiliadau ar gyfer dilysu dros y cludydd XMLRPC.';
$string['auth_mnetdescription'] = 'Caiff defnyddwyr eu dilysu yn ôl y we ymddiriedaeth a ddiffinnir yn eich gosodiadau Rhwydwaith Moodle.';
$string['auth_mnettitle'] = 'Dilysu Rhwydwaith Moodle';
$string['auth_multiplehosts'] = 'Gellir pennu mwy nag un gwesteiwr NEU fwy nag un cyfeiriad (e.e. host1.com;host2.com;host3.com) neu (e.e. xxx.xxx.xxx.xxx;xxx.xxx.xxx.xxx)';
$string['auth_nntpchangepasswordurl_key'] = 'URL newid cyfrinair';
$string['auth_nntpdescription'] = 'Mae\'r dull hwn yn defnyddio gweinydd NNTP i wirio a yw enw defnyddiwr a chyfrinair a roddwyd yn ddilys.';
$string['auth_nntphost'] = 'Cyfeiriad y gweinydd NNTP. Defnyddiwch y rhif IP, nid yr enw DNS.';
$string['auth_nntphost_key'] = 'Gwesteiwr';
$string['auth_nntpnotinstalled'] = 'Does dim modd defnyddio dilysu NNTP. Dydy\'r modiwl PHP IMAP heb gael ei osod.';
$string['auth_nntpport'] = 'Porth gweinydd (119 yw\'r mwyaf cyffredin)';
$string['auth_nntpport_key'] = 'Porth';
$string['auth_nntptitle'] = 'Gweinydd NNTP';
$string['auth_nologindescription'] = 'Ategyn cynorthwyol sy\'n atal defnyddiwr rhag mewngofnodi i\'r system a hefyd yn cael gwared ag unrhyw bost a anfonir at y defnyddiwr. Gellir ei ddefnyddio i <em>wahardd</em> cyfrifon defnyddwyr.';
$string['auth_nologintitle'] = 'Dim mewngofnodi';
$string['auth_nonedescription'] = 'Gall defnyddwyr fewngofnodi a chreu cyfrifon dilys ar unwaith, heb ddim dilysu yn erbyn gweinydd allanol na chadarnhad drwy e-bost. Byddwch yn ofalus wrth ddefnyddio\'r dewis hwn - meddyliwch am y problemau y gallai hyn ei achosi o ran diogelwch a gweinyddu.';
$string['auth_nonetitle'] = 'Dim dilysu';
$string['auth_pamdescription'] = 'Mae\'r dull hwn yn defnyddio PAM i fynd at yr enwau defnyddwyr sydd wedi\'u lleoli ar y gweinydd hwn. Rhaid i chi osod <a href=\"http://www.math.ohio-state.edu/~ccunning/pam_auth/\">Dilysu PHP4 PAM </a> er mwyn defnyddio\'r modiwl hwn.';
$string['auth_pamtitle'] = 'PAM (Modiwlau Dilysu y Gellir eu Plygio)';
$string['auth_passwordisexpired'] = 'Mae eich cyfrinair wedi dod i ben. Ydych chi am newid eich cyfrinair nawr?';
$string['auth_passwordwillexpire'] = 'Bydd eich cyfrinair yn dod i ben mewn $a diwrnod. Ydych chi am newid eich cyfrinair nawr?';
$string['auth_pop3changepasswordurl_key'] = 'URL Newid Cyfrinair';
$string['auth_pop3description'] = 'Mae\'r dull hwn yn defnyddio gweinydd POP3 i wirio a yw enw defnyddiwr a chyfrinair a roddwyd yn ddilys.';
$string['auth_pop3host'] = 'Cyfeiriad y gweinydd POP3. Defnyddiwch y rhif IP, nid yr enw DNS.';
$string['auth_pop3host_key'] = 'Gwesteiwr';
$string['auth_pop3mailbox'] = 'Enw\'r blwch post i geisio cysylltu ag ef. (fel arfer INBOX)';
$string['auth_pop3mailbox_key'] = 'Blwch post';
$string['auth_pop3notinstalled'] = 'Does dim modd defnyddio dilysu POP3. Nid yw\'r modiwl PHP IMAP wedi\'i osod.';
$string['auth_pop3port'] = 'Porth gweinydd (110 yw\'r mwyaf cyffredin, mae 995 yn gyffredin ar gyfer SSL)';
$string['auth_pop3port_key'] = 'Porth';
$string['auth_pop3title'] = 'Gweinydd POP3';
$string['auth_pop3type'] = 'Math o weinydd. Os yw eich gweinydd yn defnyddio diogelwch tystysgrif, dewiswch pop3cert.';
$string['auth_pop3type_key'] = 'Math';
$string['auth_radiuschangepasswordurl_key'] = 'URL newid cyfrinair';
$string['auth_radiusdescription'] = 'Mae\'r dull hwn yn defnyddio gweinydd <a href=\"http://en.wikipedia.org/wiki/RADIUS\">RADIUS</a> i wirio a yw\'r enw defnyddiwr a\'r cyfrinair a roddir yn ddilys.';
$string['auth_radiushost'] = 'Cyfeiriad y gweinydd RADIUS';
$string['auth_radiushost_key'] = 'Gwesteiwr';
$string['auth_radiusnasport'] = 'Porth i\'w ddefnyddio i gysylltu';
$string['auth_radiusnasport_key'] = 'Porth';
$string['auth_radiussecret'] = 'Cyfrinach a rennir';
$string['auth_radiussecret_key'] = 'Cyfrinach';
$string['auth_radiustitle'] = 'Gweinydd RADIUS';
$string['auth_remove_delete'] = 'Dileu llawn mewnol';
$string['auth_remove_keep'] = 'Cadw mewnol';
$string['auth_remove_suspend'] = 'Gwahardd mewnol';
$string['auth_remove_user'] = 'Pennu beth i\'w wneud â chyfrif defnyddiwr mewnol wrth gysoni swmp pan dynnwyd y defnyddiwr o\'r ffynhonnell allanol. Dim ond defnyddwyr wedi\'u gwahardd gaiff eu hadfer yn awtomatig os ydynt yn ailymddangos yn y ffynhonnell allanol.';
$string['auth_remove_user_key'] = 'Wedi tynnu defnyddiwr allanol';
$string['auth_shib_changepasswordurl'] = 'URL newid cyfrinair';
$string['auth_shib_convert_data'] = 'API addasu data';
$string['auth_shib_convert_data_description'] = 'Gallwch ddefnyddio\'r API hwn i addasu ymhellach y data a ddarperir gan Siboleth. Darllenwch y ffeil <a href=\"../auth/shibboleth/README.txt\">README</a> am gyfarwyddiadau pellach.';
$string['auth_shib_convert_data_warning'] = 'Nid yw\'r ffeil hon yn bodoli neu ni all proses y gweinydd gwe ei darllen!';
$string['auth_shib_instructions'] = 'Defnyddiwch y <a href=\"$a\">ffurflen mewngofnodi Siboleth</a> i gael mynediad drwy Siboleth, os gall eich sefydliad ddelio ag ef.<br />Fel arall, defnyddiwch y ffurflen mewngofnodi normal a ddangosir yma.';
$string['auth_shib_instructions_help'] = 'Yma, dylech roi cyfarwyddiadau personol i\'ch defnyddwyr i egluro Siboleth. Caiff ei ddangos ar y dudalen mewngofnodi yn yr adran cyfarwyddiadau. Rhaid i\'r cyfarwyddiadau gynnwys dolen at \"<b>$a</b>\" y bydd defnyddwyr yn ei glicio pan fyddant am fewngofnodi.';
$string['auth_shib_only'] = 'Siboleth yn unig';
$string['auth_shib_only_description'] = 'Ticiwch y dewis hwn os bydd rhaid gorfodi dilysiad Siboleth';
$string['auth_shib_username_description'] = 'Enw\'r newidyn amgylchedd Siboleth gweinydd gwe a ddefnyddir fel enw defnyddiwr Moodle';
$string['auth_shibboleth_login'] = 'Mewngofnodi Siboleth';
$string['auth_shibboleth_manual_login'] = 'Mewngofnodi eich hun';
$string['auth_shibbolethdescription'] = 'Drwy ddefnyddio\'r dull hwn, caiff defnyddwyr eu creu a\'u dilysu gan ddefnyddio <a href=\"http://shibboleth.internet2.edu/\">Siboleth</a>.<br/>Sicrhewch eich bod yn darllen y ffeil <a href=\"../auth/shibboleth/README.txt\">README</a> ar gyfer Siboleth ar sut i gydosod eich Moodle gyda Siboleth';
$string['auth_shibbolethtitle'] = 'Siboleth';
$string['auth_sync_script'] = 'Sgript cysoni cron';
$string['auth_updatelocal'] = 'Diweddaru lleol';
$string['auth_updatelocal_expl'] = '<p><b>Diweddaru lleol:</b> Os galluogir hyn, caiff y maes ei ddiweddaru (o ddilysydd allanol) bob tro y bydd y defnyddiwr yn mewngofnodi neu\'n cael ei gysoni. Dylid cloi meysydd sydd wedi\'u gosod i ddiweddaru\'n lleol.</p>';
$string['auth_updateremote'] = 'Diweddaru allanol';
$string['auth_updateremote_expl'] = '<p><b>Diweddaru allanol:</b> Os galluogir hyn, caiff y dilysydd allanol ei ddiweddaru pan gaiff cofnod y defnyddiwr ei ddiweddaru. Dylid datgloi meysydd i ganiatáu golygu.</p>';
$string['auth_updateremote_ldap'] = '<p><b>Cofiwch:</b> I ddiweddaru data LDAP allanol, mae angen i chi osod binddn a bindpw i ddefnyddiwr rhwymo â hawliau i olygu\'r holl gofnodion defnyddwyr. Nid yw\'n cadw priodoleddau aml-werth ar hyn o bryd, a bydd yn tynnu gwerthoedd ychwanegol wrth ddiweddaru. </p>';
$string['auth_user_create'] = 'Galluogi creu defnyddwyr';
$string['auth_user_creation'] = 'Gall defnyddwyr newydd (dienw) greu cyfrifon defnyddwyr ar y ffynhonnell dilysu allanol a\'u cadarnhau drwy e-bost. Os ydych chi\'n galluogi hyn, cofiwch hefyd ffurfweddu dewisiadau penodol i fodiwlau er mwyn creu defnyddwyr.';
$string['auth_usernameexists'] = 'Mae\'r enw defnyddiwr yr ydych wedi ei ddewis yn bodoli eisoes.  Dewiswch un newydd os gwelwch yn dda.';
$string['authenticationoptions'] = 'Dewisiadau dilysu';
$string['authinstructions'] = 'Yma gallwch roi cyfarwyddiadau i\'ch defnyddwyr, fel eu bod yn gwybod pa enw defnyddiwr a chyfrinair y dylent eu defnyddio. Bydd y testun a roddir yma yn ymddangos ar y dudalen mewngofnodi. Os gadewch hwn yn wag, ni chaiff cyfarwyddiadau eu hargraffu.';
$string['auto_add_remote_users'] = 'Ychwanegu defnyddwyr o bell yn awtomatig';
$string['changepassword'] = 'URL newid cyfrinair';
$string['changepasswordhelp'] = 'Yma, gallwch bennu lleoliad lle gall eich defnyddwyr adfer neu newid eu henwau defnyddwyr/cyfrinair os ydynt wedi\'i anghofio. Bydd hwn ar gael i ddefnyddwyr fel botwm ar y dudalen mewngofnodi ac ar eu tudalen defnyddiwr. Os ydych chi\'n gadael hwn yn wag, ni chaiff y botwm ei argraffu.';
$string['chooseauthmethod'] = 'Dewis dull dilysu';
$string['createpasswordifneeded'] = 'Creu cyfrinair os oes angen';
$string['errorpasswordupdate'] = 'Gwall wrth ddiweddaru\'r cyfrinair, cyfrinair heb ei newid';
$string['forcechangepassword'] = 'Gorfodi newid cyfrinair';
$string['forcechangepassword_help'] = 'Gorfodi defnyddwyr i newid eu cyfrinair y tro nesaf y byddant yn mewngofnodi i Moodle.';
$string['forcechangepasswordfirst_help'] = 'Gorfodi defnyddwyr i newid eu cyfrinair wrth fewngofnodi i Moodle am y tro cyntaf.';
$string['guestloginbutton'] = 'Botwm mewngofnodi gwesteion';
$string['infilefield'] = 'Maes gofynnol yn y ffeil';
$string['instructions'] = 'Cyfarwyddiadau';
$string['internal'] = 'Mewnol';
$string['locked'] = 'Wedi cloi';
$string['md5'] = 'MD5 stwnsh';
$string['nopasswordchange'] = 'Ni ellir newid y cyfrinair';
$string['nopasswordchangeforced'] = 'Ni allwch fwrw ymlaen heb newid eich cyfrinair; fodd bynnag, nid oes tudalen ar gael i\'w newid.  Cysylltwch â\'ch Gweinyddwr Moodle.';
$string['passwordhandling'] = 'Trin maes cyfrinair';
$string['plaintext'] = 'Testun plaen';
$string['pluginnotenabled'] = 'Ategyn dilysu \'$a\' heb ei alluogi.';
$string['pluginnotinstalled'] = 'Ategyn dilysu \'$a\' heb ei osod.';
$string['rpc_negotiation_timeout'] = 'Terfyn amser negodi RPC';
$string['selfregistration'] = 'Hunangofrestru';
$string['selfregistration_help'] = 'Dewiswch pa ategyn dilysu sy\'n delio â hunangofrestru defnyddwyr.';
$string['sha1'] = 'SHA-1 stwnsh';
$string['shib_no_attributes_error'] = 'Ymddengys eich bod wedi eich dilysu gyda Siboleth ond nid yw Moodle wedi derbyn unrhyw briodoleddau defnyddiwr. Sicrhewch fod eich Darparwr Hunaniaeth yn rhyddhau\'r priodoleddau angenrheidiol ($a) i\'r Darparwr Gwasanaeth y mae Moodle yn rhedeg arno, neu rhowch wybod i wefeistr y gweinydd hwn.';
$string['shib_not_all_attributes_error'] = 'Mae angen rhai priodoleddau Siboleth penodol ar Moodle, ac nid ydynt yn bresennol yn eich achos chi. Dyma\'r priodoleddau: $a<br />Cysylltwch â gwefeistr y gweinydd hwn neu eich Darparwr Hunaniaeth.';
$string['shib_not_set_up_error'] = 'Ymddengys nad yw dilysu Siboleth wedi\'i ffurfweddu\'n gywir, oherwydd does dim newidynnau amgylchedd Siboleth yn bresennol ar y dudalen hon. Darllenwch y ffeil <a href=\"README.txt\">README</a> am gyfarwyddiadau pellach am sut i ffurfweddu dilysu Siboleth neu cysylltwch â gwefeistr y gosodiad Moodle hwn.';
$string['showguestlogin'] = 'Gallwch guddio neu ddangos y botwm mewngofnodi gwestai ar y dudalen mewngofnodi.';
$string['stdchangepassword'] = 'Defnyddio\'r Dudalen Newid Cyfrinair safonol';
$string['stdchangepassword_expl'] = 'Os yw\'r system dilysu allanol yn caniatáu newidiadau cyfrinair drwy Moodle, dewiswch Iawn yma. Mae\'r gosodiad hwn yn diystyru \'URL Newid Cyfrinair\'.';
$string['stdchangepassword_explldap'] = 'COFIWCH: Argymhellir eich bod yn defnyddio LDAP dros dwnel SSL wedi ei amgryptio (ldaps://) os yw\'r gweinydd LDAP yn un pell.';
$string['unlocked'] = 'Wedi\'i ddatgloi';
$string['unlockedifempty'] = 'Datgloi os yw\'n wag';
$string['update_never'] = 'Byth';
$string['update_oncreate'] = 'Adeg creu';
$string['update_onlogin'] = 'Adeg pob mewngofnodi';
$string['update_onupdate'] = 'Adeg diweddaru';


// Strings below here are module specific and will be duplicated in auth_* files
// Module specific language strings should also be copied into their respective
// auth_*.php files to ensure compatibility in all versions of Moodle

$string['sso_idp_description'] = 'Cyhoeddwch y gwasanaeth hwn i ganiatáu i\'ch defnyddwyr grwydro i safle Moodle $a heb orfod mewngofnodi eto yno. <ul><li><em>Dibyniaeth</em>: Rhaid i chi hefyd <strong>danysgrifio</strong> i\'r gwasanaeth SSO (Darparwr Gwasanaeth) ar $a.</li></ul><br />Tanysgrifiwch i\'r gwasanaeth hwn i ganiatáu i ddefnyddwyr wedi\'u dilysu o $a gael mynediad i\'ch safle heb orfod mewngofnodi eto. <ul><li><em>Dibyniaeth</em>: Rhaid i chi hefyd <strong>gyhoeddi</strong> y gwasanaeth SSO (Darparwr Gwasanaeth) i $a.</li></ul><br />';
$string['sso_idp_name'] = 'SSO  (Darparwr Hunaniaeth)';
$string['sso_mnet_login_refused'] = 'Ni chaiff yr enw defnyddiwr $a[0] fewngofnodi o $a[1].';
$string['sso_sp_description'] = 'Cyhoeddwch y gwasanaeth hwn i ganiatáu i ddefnyddwyr wedi\'u dilysu o $a gael mynediad i\'ch safle heb orfod mewngofnodi eto. <ul><li><em>Dibyniaeth</em>: Rhaid i chi hefyd <strong>danysgrifio</strong> i\'r gwasanaeth SSO (Darparwr Gwasanaeth) i $a.</li></ul><br />Cyhoeddwch y gwasanaeth hwn i ganiatáu i\'ch defnyddwyr grwydro i safle Moodle $a heb orfod mewngofnodi eto yno. <ul><li><em>Dibyniaeth</em>: Rhaid i chi hefyd <strong>gyhoeddi</strong> y gwasanaeth SSO (Darparwr Gwasanaeth) i $a.</li></ul><br />';
$string['sso_sp_name'] = 'SSO (Darparwr Gwasanaeth)';

?>
