<?PHP // $Id$ 
      // resource.php - created with Moodle 1.4.3 + (2004083131)


$string['addresource'] = 'Tanaki ha naunau';
$string['chooseafile'] = 'Fili\'i pe \'apulouti ha faile';
$string['chooseparameter'] = 'Fili\'i e ngatangata\'anga';
$string['configdefaulturl'] = '\'Oku ngaue\'aki e mahu\'inga ko \'eni ke toe-fakafonu e foomu URL \'i he taimi \'oku fakatupu ai ha URL-peisi lisoosi fo\'ou.';
$string['configfilterexternalpages'] = 'Ko hono fakamalava e setingi ko \'eni tene fakalanga \'e ia e ngaahi lisoosi mei tu\'a (ngaahi peesi uepi, ngaahi faile HTML kuo \'apulouti) ke fakahoko \'aki e ngaahi saiti me\'asivi kuo fakapapau\'i (hange koe ngaahi \'otolingi koloosalii, fakatataa \'aki pe). Ko hono fakamo\'ui e \'opisini ko \'eni tene fakalanga \'e ia e ngaahi peesi ke mamalie pe tuai \'aupito - ngaue tokana\'aki \'ihe taimi pe \'oku ke fu\'u fiema\'u ai. ';
$string['configframesize'] = 'Koe taimi \'oku faka\'ali\'ali ai ha peesi uepi pe ko ha faile \'apulouti \'i ha \'esia, koe mahu\'inga ko \'eni koe saisi (\'ihe pikisela) \'oe \'esia \'i \'olunga (\'aia \'oku \'iai e nevikeisoni).  ';
$string['configparametersettings'] = '\'Oku seti heni e mahu\'inga \'oe tifolo ki he ngaahi setingi \'oe palamita peini foomu \'ihe taimi \'oku tanaki ai ha ngaahi lisoosi fo\'ou. Hili e \'uluaki taimi, \'oku hoko leva \'eni koe fiema\'u ia \'ae tokotaha \'iusa takitaha.';
$string['configpopup'] = '\'I hano tanaki ha lisoosi fo\'ou \'aia \'oku malava ke fakaha \'ihe popu\'apu uinitou, \'oku totonu nai ke fakangofua \'eni \'aki e tifolo?';
$string['configpopupdirectories'] = '\'Oku totonu ke fakaha he\'e popu\'apu uinitou \'ae lingi fakahinohino \'aki e tifolo?';
$string['configpopupheight'] = ' Koeha e ma\'olunga \'oku totonu ke hoko koe tifolo ma\'olunga ki he ngaahi popu\'apu uinitou fo\'ou?';
$string['configpopuplocation'] = '\"Oku totonu ke fakaha he\'e popu\'apu uinitou \'ae pa feitu\'u \'aki e tifolo? ';
$string['configpopupmenubar'] = '\'Oku totonu ke fakaha he\'e pupo\'apu uinitou \'ae pa meniu \'aki e tifolo?';
$string['configpopupresizable'] = '\'Oku totonu ke fakasaisi e popu\'apu uinitou \'aki e tifolo?';
$string['configpopupscrollbars'] = '\'Oku totonu ke \'alu hake/aluhifo e popu\'apu uinitou \'aki e tifolo? ';
$string['configpopupstatus'] = '\'Oku totonu fakaha he\'e pupo\'apu uinitou \'ae pa sitaitusi \'aki e tifolo?';
$string['configpopuptoolbar'] = '\'Oku totonu ke fakaha he\'e popu\'apu uinitou  \'ae tulu paa \'aki e tifolo?  ';
$string['configpopupwidth'] = 'Koeha e faalahi \'oku totonu ke hoko ia koe faalahi ki he tifolo ki he popu\'apu uinitou fo\'ou?';
$string['configsecretphrase'] = 'Koe kupu\'i lea fakapulipuli ko \'eni \'oku ngaue\'aki  ke ma\'u ha mahu\'inga \'oe kouti makehe \'aia \'e lava \'o \'oatu ki ha ngaahi lisoosi ko ha palamita. Koe kouti makehe \'oku ma\'u ia mei ha mahu\'inga md5 \'oe kau \'iusa-lolotonga tu\'asila IP kuo \'osi fakatah\'i \'i ho\'o kupu\'i lea fakapulipuli.   ie kouti = md5(IPkupu\'ileafakapulipuli).  \'Oku hanga \'ehe me\'a ko \'eni \'o fakangofua e lisoosi feitu\'u kene fakapapau\'i e fehokotaki ki ha malu\'i makehe. ';
$string['configwebsearch'] = '\'Ihe taimi e tanaki ai ha URL koha Uepipeesi pe koha Uepilingi, \'e hoko e feitu\'u ko \'eni ko ha saiti ke tokoni ki he \'iusa ki hon kumi e URL \'oku nau fiema\'u.';
$string['configwindowsettings'] = '\'Oku seti heni e mahu\'inga \'oe tifolo ki he ngaai setingi Uinitou peini foomu \'i he taimi \'e tanaki ai ha ngaahi lisoosi. Hili pe \'uluaki taimi, \'e hoko leva \'eni koe fiema\'u ia \'ae tokotaha \'iusa takitaha.';
$string['directlink'] = 'Koe lingi hangatonu ki he faile ko \'eni';
$string['directoryinfo'] = '\'E fakaha kotoa e ngaahi faile kuo fili\'i \'i he fakahinohino.';
$string['display'] = 'Uinitou';
$string['editingaresource'] = '\'Etita\'i ha naunau';
$string['encryptedcode'] = 'Encrypted code';
$string['example'] = 'Fakataataa';
$string['exampleurl'] = 'http://www.example.com/somedirectory/somefile.html';
$string['fetchclienterror'] = 'Ne \'iai e fehalaaki ne ma\'u mo ho\'o uepi kalaieni lolotonga e feinga ke toema\'u e peesi uepi (mahal pe koe URL hala).';
$string['fetcherror'] = 'Ne \'iai e fahalaaki ne \'ilo lolotonga hono feinga\'i mai e peesi Uepi.';
$string['fetchservererror'] = '\'Oku \'iai e fehalaaki ne ma\'u \'ihe seeva mama\'o lolotonga e feinga ke toema\'u peesi uepi (mahalo pe koe fehalaaki fakapolokalama).</p>';
$string['filename'] = 'Hingoa \'oe Faile';
$string['filtername'] = 'Koe fehokotaki-\'otometiki ki he ngaahi Hingoa \'oe Naunau';
$string['frameifpossible'] = 'Fakahu e lisoosi ki ha \'esia kae lava \'o haa mai e saiti nevikeisoni';
$string['fulltext'] = 'Lea kakato';
$string['htmlfragment'] = 'HTML kongokonga';
$string['maindirectory'] = 'Koe fakahinohino kihe ngaahi faile lalahi';
$string['modulename'] = 'Lisoosi/naunau';
$string['modulenameplural'] = 'Ngaahi Lisoosi/naunau';
$string['neverseen'] = 'Te\'eki sio ai';
$string['newdirectories'] = 'Fakahaa mai';
$string['newfullscreen'] = 'Fakafonu e \'ataa kakato';
$string['newheight'] = 'Ma\'olunga \'oe Uinitou tifolo (ihe pikisela)';
$string['newlocation'] = 'Fakaha e Pa Lokeisini';
$string['newmenubar'] = 'Fakaha e Pa Meniu';
$string['newresizable'] = 'Fakangofua e Uinitou ke toe fakasaisi';
$string['newscrollbars'] = 'Fakangofua e Uinitou ke tukuhake-tukuhifo';
$string['newstatus'] = 'Fakaha e Pa tu\'unga';
$string['newtoolbar'] = 'Fakaha e tulu-paa';
$string['newwidth'] = 'Faalahi \'oe Uinitou Tifolo (ihe pikisela)';
$string['newwindow'] = 'Uinitou fo\'ou';
$string['newwindowopen'] = 'Faka\'ali\'ali e lisoosi ko \'eni \'iha popu\'apu Uinitou fo\'ou';
$string['note'] = 'Nouti';
$string['notefile'] = 'Ke teo \'apulouti ha toe ngaahi faile ki he koosi (Koe\'uhi kenau \'asi \'i he lisi ko \'eni) ngaue\'aki e <a href=\"$a\">Faile Pule</a>.';
$string['notypechosen'] = '\'Oku fiema\'u keke fili ha fa\'ahinga. Ngaue\'aki ho\'o patoni foki ke foki \'o toe feinga. ';
$string['pagedisplay'] = 'Faka\'ali\'ali e lisoosi ko \'eni \'i loto \'i he uinitou lolotonga';
$string['pagewindow'] = 'Uinitou tatau';
$string['parameter'] = 'Fakangatangata';
$string['parameters'] = 'Ngaahi fakangatangata';
$string['popupresource'] = 'Koe lisoosi ko \'eni e \'asi \'i he popu\'apu uinitou.';
$string['popupresourcelink'] = 'Kapau \'oku \'ikai, kiliki heni: $a';
$string['resourcetype'] = 'Fa\'ahinga \'oe lisoosi';
$string['resourcetype1'] = 'Fakahinohino/fakamo\'oni';
$string['resourcetype2'] = 'Web Peesi';
$string['resourcetype3'] = 'Falie kuo \'Apulouti';
$string['resourcetype4'] = 'Lea \'ata\'ataa';
$string['resourcetype5'] = 'Web Link';
$string['resourcetype6'] = 'HTML lea';
$string['resourcetype7'] = 'Polokalama';
$string['resourcetype8'] = 'Wiki-like text';
$string['resourcetype9'] = 'Fakahinoino';
$string['resourcetypedirectory'] = 'Fakaa\'li\'ali ha fakahinohino';
$string['resourcetypefile'] = 'Link ki ha faile pe koha web peesi ';
$string['resourcetypehtml'] = 'Fa\'u ha web peesi';
$string['resourcetypelabel'] = 'Fakahu ha leipolo';
$string['resourcetypetext'] = 'Fa\'u ha peesi text';
$string['searchweb'] = 'Fekumi ki ha web peesi';
$string['variablename'] = 'Hingoa kehekehe';

?>
