<?PHP // $Id$ 
      // auth.php - created with Moodle 1.7+ (2006101009)


$string['alternatelogin'] = 'Таны бичсэн хаяг нь энэ сайтын нэвтрэх хуудас болно. Энэ хуудасны формын үйлдэл нь <strong>\'$a\'</strong> заасан байх ёстой ба <strong>username</strong> болон <strong>password</strong утга буцааж байх ёстой. Буруу URL хаяг нь таныг цааш үйлдэл хийж болохгүй болгох тул анхааралтай бөглөнө үү. Энэ хэсгийг хоосон үлдээснээр үндсэн нэвтрэх хуудсыг ашиглах болно.';
$string['alternateloginurl'] = 'Нэвтрэх URL хаяг (Нэмэлт)';
$string['auth_cas_baseuri'] = 'Серверийн URI';
$string['auth_cas_create_user'] = 'Энэ хэсгийг идэвхижүүлснээр та Моодлийн баазад CAS-authenticated хэрэглэгчийг нэмэх болно. Идэвхижүүлээгүй үед Моодлийн бааз дээрхи хэрэглэгчид нэвтрэх боломжтой.';
$string['auth_cas_enabled'] = 'CAS authentication хэрэглэх бол идэвхижүүлнэ үү';
$string['auth_cas_hostname'] = 'CAS cерверийн хост нэр';
$string['auth_cas_invalidcaslogin'] = 'Уучлаарай, таны нэвтрэх оролдлого болсонгүй.';
$string['auth_cas_language'] = 'Сонгосон хэл';
$string['auth_cas_logincas'] = 'Холболтын хандалтыг хамгаалах';
$string['auth_cas_port'] = 'CAS cерверийн порт';
$string['auth_cas_server_settings'] = 'CAS cерверийн тохиргоо';
$string['auth_cas_text'] = 'Аюулгүй холбоо';
$string['auth_cas_version'] = 'CAS -ийн хувилбар';
$string['auth_casdescription'] = 'Энэ арга нь CAS server (Central Authentication Service) ашиглан хэрэглэгчийг ганцаарчилсан нэвтрэх орчинд шалгана. Мөн энгийн LDAP authentication -ийг ашиглах боломжтой. Хэрэглэгчийн оруулсан нэр, нууц үг нь CAS -д тохирч байвал Моодл өгөгдлийн санд шинэ хэрэглэгч үүсгээд шаардлагатай бол хэрэглэгчийн шинжийг LDAP-с авна.';
$string['auth_castitle'] = 'CAS cервер ашиглах';
$string['auth_changepasswordhelp'] = 'Нууц үг өөрчлөх тусламж';
$string['auth_changepasswordhelp_expl'] = 'Нууц үгээ санахгүй байгаа хэрэглэгчдэд тэдний $a нууц үгийг харуул. Энэ нь <strong>Нууц үгээ өөрчлөх хаяг</strong> -ний оронд харагдах болно';
$string['auth_changepasswordurl'] = 'Нууц үгээ өөрчлөх хаяг';
$string['auth_changepasswordurl_expl'] = '$a нууц үгээ мартсан хэрэглэгчдэд илгээх URL хаяг. <strong>Энгийн нууц үг өөрчлөх хуудас</strong> -ийг <strong>Үгүй</strong> болгож тохируул';
$string['auth_common_settings'] = 'Нийтлэг тохиргоо';
$string['auth_data_mapping'] = 'Өгөгдөл заах';
$string['auth_dbdescription'] = 'Энэ арга нь гадаад өгөгдлийн сангаас оруулсан нэр, нууц үгийг шалгана. Хэрэв хэрэглэгч нь шинэ байвал бусад баганын мэдээлэл нь Моодл руу хуулагдах болно.';
$string['auth_dbextrafields'] = 'Энэ талбар нь заавал сонгох албагүй. Та <b>гадаад өгөгдлийн сан</b>-гаас зарим мэдээллийг оруулахын тулд энд сонгож болно. <p>Хэрэв хоосон орхивол анхны өгөгдлүүд хэрэглэгдэнэ.</p> <p>Аль ч тохиолдолд хэрэглэгч нэвтэрч орсны дараа эдгээр утгуудыг өөрчлөх боломжтой.</p>';
$string['auth_dbfieldpass'] = 'Нууц үгийг агуулж байгаа талбарын нэр';
$string['auth_dbfielduser'] = 'Хэрэглэгчийн нэрийг агуулж байгаа талбарын нэр';
$string['auth_dbhost'] = 'Өгөгдлийн санг агуулж байгаа комьпютерийн нэр';
$string['auth_dbname'] = 'Өөрийнх нь өгөгдлийн сангийн нэр';
$string['auth_dbpass'] = 'Дээрхи хэрэглэгчийн нууц үг';
$string['auth_dbpasstype'] = '<p>Нууц үгийг хадгалах хэлбэрийн сонгоно уу. MD5 хөрвүүлэлт нь өргөн хэрэглэгддэг PostNuke гэх мэт програмтай холбогдоход зохимжтой.</p> <p>\'Дотоод\' гэж сонгосноор гадаад өгөгдлийн санд хэрэглэгчийн нэр,  имэйл хаягийг хадгалаад, нууц үгийг Моодл зохицуулно. Хэрэв та \'Дотоод\' ашиглах юм бол гадаад өгөгдлийн сан дээрхи холбогдох имэйл хаяг бүхий талбарыг <i>заавал</i> бөглөх хэрэгтэй бөгөөд auth/db/cron.php -г тогтмол ажиллуулж байх хэрэгтэй.';
$string['auth_dbtable'] = 'Өгөгдлийн сан дахь хүснэгтийн нэр';
$string['auth_dbtitle'] = 'Гадаад өгөгдлийн санг ашиглах';
$string['auth_dbtype'] = 'Өгөгдлийн сангийн төрөл (<a href=\"../lib/adodb/readme.htm#drivers\">DOdb бичиг баримт</a> -г үзнэ үү)';
$string['auth_dbuser'] = 'Өгөгдлийн сан руу унших хандалттай хэрэглэгчийн нэр';
$string['auth_emaildescription'] = 'Майлээр шалгах нь үндсэн шалгах арга юм. Хэрэглэгч шинээр бүртгүүлэх үед батлах майлийг хэрэглэгчийн хаяг руу явуулна. Уг майл нь хэрэглэгчийг идэвхижүүлэх холбоосыг агуулсан байна. Дараагийн удаад хэрэглэгчийн нэр, нууц үгийг Моодл өгөгдлийн сангаас шалгах болно';
$string['auth_emailtitle'] = 'Имэйл-суурилсан шалгалт';
$string['auth_fccreators'] = 'Гишүүд нь курс шинээр үүсгэх боломжтой группын жагсаалт. Олон группыг тусгаарлахдаа \';\' ашигла. FirstClass сервер дээрхитэй яг адилхан үсгээр бичих хэрэгтэй. Систем нь том жижиг үсгийг ялгана.';
$string['auth_fcdescription'] = 'Энэ арга нь FisrtClass сервер ашиглан хэрэглэгчийн нэр, нууц үгийг зөв эсэхийг шалгана.';
$string['auth_fcfppport'] = 'Серверийн порт (3333 нь өргөн хэрэглэгддэг)';
$string['auth_fchost'] = 'FirstClass серверийн хаяг. IP хаяг болон DNS нэр ашигла';
$string['auth_fcpasswd'] = 'Дээрхи хэрэглэгчийн нууц үг';
$string['auth_fctitle'] = 'FirstClass серверийг ашигла';
$string['auth_fcuserid'] = '\'Subadministrator\' эрхтэй FirstClass хэрэглэгчийн UserId';
$string['auth_fieldlock'] = 'Утгыг түгжих';
$string['auth_fieldlock_expl'] = '<p><b>Утгыг түгжих:</b> Идэвхижүүлсэн үед Моодлийн хэрэглэгч болон админ нь энэ талбарын утгыг шууд өөрчлөхгүй болгоно. Гадаад өгөгдлийн баазад шалгах ажиллагаанд энэ талбарыг хэрэглэж байгаа бол энэ сонголтыг сонгоно уу</p>';
$string['auth_fieldlocks'] = 'Хэрэглэгчийн талбарыг түгжих';
$string['auth_fieldlocks_help'] = '<p>Та хэрэглэгчийн өгөгдлийн талбарыг түгжиж болно</p>';
$string['auth_imapdescription'] = 'Энэ арга нь IMAP сервер ашиглан хэрэглэгчийн нэр, нууц үгийг зөв эсэхийг шалгана.';
$string['auth_imaphost'] = 'IMAP серверийн хаяг. IP хаяг болон DNS нэр ашигла';
$string['auth_imapport'] = 'IMAP серверийн порт. 143 болон 993 нь өргөн хэрэглэгддэг';
$string['auth_imaptitle'] = 'IMAP сервер ашиглах';
$string['auth_imaptype'] = 'IMAP серверийн төрөл. IMAP сервер нь олон янзын шалгах үйлдлийг агуулж болно.';
$string['auth_ldap_bind_dn'] = 'Хэрэв та хэрэглэгч хайхдаа  bind-user -ийг хэрэглэх бол энд сонгоно уу. \'cn=ldapuser,ou=public,o=org\' гэх мэт.';
$string['auth_ldap_bind_pw'] = 'bind-user-ийн нууц үг';
$string['auth_ldap_bind_settings'] = 'Bind тохиргоо';
$string['auth_ldap_contexts'] = 'Хэрэглэгчийн холбогдсон context -ийн жагсаалт. Ялгаатай context -ийг \';\' ашиглан заагла.';
$string['auth_ldap_create_context'] = 'Хэрэв та хэрэглэгч үүсгэхдээ мэйлээр идэвхижүүлэх бол хэрэглэгч үүсэх context-г оруулна уу. Нууцлалын асуудлаас хамааран эдгээр context нь бусад хэрэглэгчдээс ялгаатай байх ёстой. Энэ context-ийг ldap_context хувьсагчид нэмэх шаардлагагүй. Моодл автоматаар энэ context-с хэрэглэгчийг хайх болно.<br /><b>Анхаар!</b> Та хэрэглэгч үүсгэх үйлдлийг ажиллуулахын тулд auth/ldap/lib.php файл дахь function auth_user_create() функцыг завсарлах шаардлагатай';
$string['auth_ldap_creators'] = 'Гишүүд нь курс шинээр үүсгэх боломжтой группын жагсаалт. Олон группыг тусгаарлахдаа \';\' ашигла. \'cn=teachers,ou=staff,o=myorg\' гэх мэт.';
$string['auth_ldap_expiration_desc'] = 'Дууссан нууц үгийг идэвхигүй болгох эсвэл LDAP нь passwordexpiration хугацааг LDAP-с шууд унших болгож тохируулахын тулд Үгүй сонгоно уу';
$string['auth_ldap_expiration_warning_desc'] = 'Нууц үг идэвхигүй болох анхааруулгыг өгөх өдрийн тоо';
$string['auth_ldap_expireattr_desc'] = 'Сонголтынх: нууц үгийн дуусах хугацааг хадгалдаг ldap атрибутыг агуулдаг.';
$string['auth_ldap_graceattr_desc'] = 'Сонголтынх: gracelogin атрибутыг агуулдаг';
$string['auth_ldap_gracelogins_desc'] = 'LDAP-д gracelogin-ийг дэмждэг болгох. Нууц үг идэвхигүй болсны дараа хэрэглэгч gracelogin -ийг 0 болтол нэвтэрч орох боломжтой. Энэ тохиргоог идэвхижүүлснээр grace login зурвасыг харуулах болно';
$string['auth_ldap_host_url'] = 'LDAP host-г URL-form хэлбэрээр оруул. \'ldap://ldap.myorg.com/\' эсвэл \'ldaps://ldap.myorg.com/\' гэх мэт. Олон серверийг \';\' -р заагла.';
$string['auth_ldap_login_settings'] = 'Нэвтрэх тохиргоо';
$string['auth_ldap_memberattribute'] = 'Сонголтынх: Хэрэглэгч ямарваа бүлэгт харъяалагдаж байх үед хэрэглэгчийн гишүүнчлэлийн шинж чанарыг агуулж байдаг. Ихэнхдээ “гишүүн” байдаг.';
$string['auth_ldap_objectclass'] = 'Сонголтынх: ldap_user_type дээр хэрэглэгчийг хайх/нэрлэх үед ашиглагддаг. Ихэнхдээ үүнийг өөрчлөх хэрэггүй байдаг.';
$string['auth_ldap_opt_deref'] = 'Хайлтын явцад алясийг хэрхэн удирдахыг тодорхойлдог. Дараах утгуудын нэгийг нь сонго: \"Үгүй\" (LDAP_DEREF_NEVER) эсвэл \"Тийм\" (LDAP_DEREF_ALWAYS)';
$string['auth_ldap_passwdexpire_settings'] = 'LDAP нууц үг идэвхигүй болох тохиргоо';
$string['auth_ldap_preventpassindb'] = 'Моодл өгөгдлийн санд нууц үгийг хадгалахгүйн тулд Үгүй сонгоно уу.';
$string['auth_ldap_search_sub'] = 'Subcontext-с хэрэглэгч хайх';
$string['auth_ldap_server_settings'] = 'LDAP серверийн тохиргоо';
$string['auth_ldap_update_userinfo'] = 'LDAP-с Моодл руу хэрэглэгчийн нэр, хаяг зэрэг мэдээллийг шинэчлэх.';
$string['auth_ldap_user_attribute'] = 'Сонголтынх: Хэрэглэгчийг хайх/нэрлэх үед ашиглагддаг атрибутыг агуулдаг. Ихэвчлэн \'cn\' байна.';
$string['auth_ldap_user_settings'] = 'Хэрэглэгч хайх тохиргоо';
$string['auth_ldap_user_type'] = 'LDAP-д хэрэглэгчид хэрхэн хадгалагдахыг сонго. Энэ тохиргоо нь нэвтрэх хугацаа хэрхэн дуусах, grace нэвтрэлт болон хэрэглэгч үүсгэх хэрхэн ажиллахыг тодорхойлдог.';
$string['auth_ldap_version'] = 'Таны сервер дээрхи LDAP протоколын хувилбар';
$string['auth_ldapdescription'] = 'Энэ арга нь гадаад LDAP серверийг ашиглахгүй болгоно. 

Хэрвээ өгөгдсөн хэрэглэгчийн нэр нууц үг нь хүчинтэй байвал Моодл өгөгдлийн санд шинэ хэрэглэгчийн өгөгдөл үүсгэнэ. Энэ модуль нь LDAP-с хэрэглэгчдийн тухай уншаад Моодл дээрх тохирсон талбарууд дээр нь байрлуулдаг. Дараагийн нэвтрэлтээс эхлээд зөвхөн хэрэглэгчийн нэр, нууц үг шалгагдана.';
$string['auth_ldapextrafields'] = 'Энэ талбарууд нь сонголтынх юм. Та Моодлийн зарим хэрэглэгчийн талбарыг энд тодорхойлох <b>LDAP талбаруудаас</b>  авах мэдээллээр дүүргэж болох юм. <p>Хэрвээ та талбаруудыг хоосон орхивол LDAP-с юу ч шилжихгүй, Mоодлийн анхны утгууд нь ашиглагдах болно.</p><p> Эсрэг тохиолдолд хэрэглэгч нэвтэрсэн хойноо энэ бүх талбаруудыг засварлах боломжтой юм.';
$string['auth_ldaptitle'] = 'LDAP сервер хэрэглэх';
$string['auth_manualdescription'] = 'Энэ арга нь хэрэглэгч өөрөө хэрэглэгч үүсгэх ажиллагааг идэвхигүй болгоно. Бүр хэрэглэгчид админ хэрэглэгчээр гар аргаар үүсэх болно';
$string['auth_manualtitle'] = 'Хэрэглэгчийг гар аргаар үүсгэх';
$string['auth_multiplehosts'] = 'Олон host болон хаягууд оруулна уу (host1.com;host2.com;host3.com) эсвэл (xxx.xxx.xxx.xxx;xxx.xxx.xxx.xxx)  гэх мэт';
$string['auth_nntpdescription'] = 'Энэ арга нь NNTP сервер ашиглан хэрэглэгчийн нэр, нууц үгийг таарч байгаа эсэхийг шалгана.';
$string['auth_nntphost'] = 'NNTP сервер хаяг. IP хаяг ашигла, DNS биш.';
$string['auth_nntpport'] = 'Сервер порт (ихэвчлэн 119 байдаг)';
$string['auth_nntptitle'] = 'NNTP сервер ашиглах';
$string['auth_nonedescription'] = 'Хэрэглэгчид нэвтэрч ороод гадаад серверийн зөвшөөрөл болон шалгах имэйлгүйгээр шууд хүчинтэй эрх үүсгэх боломжтой. Энэ сонголтыг хийхдээ маш болгоомжтой байх хэрэгтэй. Нууцлал, хамгаалалт, удирдах үйл ажиллагаануудад асуудлууд гарч болзошгүй.';
$string['auth_nonetitle'] = 'Шалгахгүй';
$string['auth_pamdescription'] = 'Энэ дүрэм нь сервер дээрх өөрийн хэрэглэгчдийн нэр рүү хандахад  PAM ашигладаг. Та энэ модулийг ашиглахын тулд <a href=\"http://www.math.ohio-state.edu/~ccunning/pam_auth/\" target=\"_blank\">PHP4 PAM Authentication</a> суулгах хэрэгтэй.';
$string['auth_pamtitle'] = 'PAM (pluggable authentication modules)';
$string['auth_passwordisexpired'] = 'Таны нууц үг идэвхигүй боллоо. Нууц үгээ яг одоо өөрчлэх үү?';
$string['auth_passwordwillexpire'] = 'Таны нууц үг $a хоногт идэвхигүй болно. Нууц үгээ яг одоо өөрчлөх үү?';
$string['auth_pop3description'] = 'Энэ арга нь POP3 сервер ашиглан хэрэглэгчийн нэр, нууц үг таарч байгаа эсэхийг шалгана.';
$string['auth_pop3host'] = 'POP3 сервер хаяг. IP хаяг ашиглана. DNS ашиглахгүй.';
$string['auth_pop3mailbox'] = 'Холбогдох оролдлого хийх Mailbox нэр';
$string['auth_pop3port'] = 'Сервер порт (110 хамгийн өргөн тархсан, 995 SLL-д өргөн тархсан)';
$string['auth_pop3title'] = 'POP3 сервер хэрэглэх';
$string['auth_pop3type'] = 'Серверийн төрөл. Хэрэв сервер нь хамгаалалтын гэрчилгээ ашигладаг бол pop3cert сонгоно уу';
$string['auth_radiusdescription'] = 'Энэ арга нь хэрэглэгчийн нэр нууц үг таарч байгаа эсэхийг <a href=\"http://en.wikipedia.org/wiki/RADIUS\" target=\"_blank\">RADIUS</a> сервер ашиглан шалгадаг.';
$string['auth_radiushost'] = 'RADIUS серверийн хаяг';
$string['auth_radiusnasport'] = 'Холбогдох порт';
$string['auth_radiussecret'] = 'Хамтран эзэмших нууц';
$string['auth_radiustitle'] = 'RADIUS сервер хэрэглэх';
$string['auth_shib_convert_data'] = 'API өгөгдөл өөрчлөх';
$string['auth_shib_convert_data_description'] = 'Та энэ API-г Shibboleth-ийн өгөгдлийг засварлахад ашиглаж болно. Нэмэлт заавар авахыг хүсвэл <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">README</a> уншина уу.';
$string['auth_shib_convert_data_warning'] = 'Файл байхгүй эсвэл вэбсервер уншиж чадахгүй банйа';
$string['auth_shib_instructions'] = 'Shibboleth-р дамжиж хандахын тулд <a href=\"$a\">Shibboleth login</a> ашиглана уу. <br />Үгүй бол энгийн нэвтрэх маягт ашиглана уу.';
$string['auth_shib_instructions_help'] = 'Энд та Shibboleth-ийн талаар хэрэглэгчиддээ өгөх заавраа бичнэ үү. Энэ нь нэвтрэх хуудасны зааврын хэсэгт харагдах болно. Заавар нь \"<b>$a</b>\" холбоос агуулсан байх ёстой.';
$string['auth_shib_only'] = 'Зөвхөн Shibboleth';
$string['auth_shib_only_description'] = 'Shibboleth шалгалт заавал хэрэгтэй бол энэ сонголтыг тэмдэглэ.';
$string['auth_shib_username_description'] = 'Моодлийн хэрэглэгчийн нэр шиг ашиглагдах Shibboleth вэбсерверийн орчны хувьсагчийн нэр.';
$string['auth_shibboleth_login'] = 'Shibboleth нэвтрэх';
$string['auth_shibboleth_manual_login'] = 'Өөрөө нэвтрэх';
$string['auth_shibbolethdescription'] = 'Энэ аргыг хэрэглэгчид <a href=\"http://shibboleth.internet2.edu/\" target=\"_blank\">Shibboleth</a>-р үүсэж баталгаажсан бол ашиглана. Моодлээ Shibboleth-тэй хэрхэн тохируулах талаар <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">README</a> -г уншаарай.';
$string['auth_shibbolethtitle'] = 'Shibboleth';
$string['auth_updatelocal'] = 'Дотооддоо шинэчлэх';
$string['auth_updatelocal_expl'] = '<p><b>Дотооддоо шинэчлэх:</b> Хэрвээ идэвхтэй бол талбарууд нь хэрэглэгч нэвтрэх бүрд шинэчлэгдэнэ. Дотооддоо шинэчлэгдэхээр тохируулсан талбарууд нь түгжигдэх ёстой. </p>';
$string['auth_updateremote'] = 'Гадааддаа шинэчлэх';
$string['auth_updateremote_expl'] = '<p><b>Гадааддаа шинэчлэх:</b> Хэрвээ идэвхтэй бол хэрэглэгчийн бичлэг шинэчлэгдэхэд гадаад эрх мөн шинэчлэгдэнэ. Талбарууд нь засвар хийгдэхийн тулд түгжигдээгүй байх ёстой.</p>';
$string['auth_updateremote_ldap'] = '<p><b>Санамж:</b> Гадаад LDAP өгөгдлийг шинэчлэх нь bind-user хэрэглэгчид бусад бүх хэрэглэгчдийн мэдээллийг засварлах давуу эрх олгохын тулд binddn болон bindpw утга оноохыг шаарддаг. Энэ нь одоогоор олон утгатай атрибутуудыг хадгалдаггүй бөгөөд шинэчлэлтийн илүү утгуудыг устгана.</p>';
$string['auth_user_create'] = 'Хэрэглэгч үүсгэхийг идэвхижүүлэх';
$string['auth_user_creation'] = 'Шинэ (нэргүй) хэрэглэгч гадаад хамгаалалт дээр хэрэглэгчийн эрх үүсгээд имэйлээр баталгаажуулж болно. Та үүнийг идэвхжүүлбэл хэрэглэгч үүсгэх модулийн тохиргоогоо тохируулахаа мартаваа.';
$string['auth_usernameexists'] = 'Сонгосон хэрэглэгчийн нэр бүртгэгдсэн байна. Өөр шинэ нэр сонгоно уу.';
$string['authenticationoptions'] = 'Шалгах тохиргоо';
$string['authinstructions'] = 'Энд заавар өгснөөр хэрэглэгчид ямар нууц үг, хэрэглэгчийн нэр ашиглах ёстойгоо мэднэ. Таны энд оруулах текст тань нэвтрэх хуудсан дээр харагдах болно. Хэрвээ хоосон орхивол заавар гарахгүй.';
$string['changepassword'] = 'Нууц үг солих URL';
$string['changepasswordhelp'] = 'Энд та хэрэглэгчид хэрэглэгчийн нэр/нууц үгээ мартсан үед сэргээх болон өөрчлөх хаягийг зааж болно. Энэ нь нэвтрэх хуудсан дээр товчлуур хэлбэртэйгээр хэрэглэгчдэд хүрэх бөгөөд хоосон орхивол товчлуур гарахгүй.';
$string['chooseauthmethod'] = 'Шалгах арга сонгоно уу';
$string['createpasswordifneeded'] = 'Хэрвээ хэрэгтэй бол нууц үг үүсгэх';
$string['forcechangepassword'] = 'Нууц үгийг хүчээр өөрчлүүлэх';
$string['forcechangepassword_help'] = 'Хэрэглэгчдийг дараагийн удаа Моодлд нэвтрэх үед нууц үгийг нь хүчээр өөрчлүүлэх';
$string['forcechangepasswordfirst_help'] = 'Хэрэглэгчдийг анхны удаа Моодлд нэвтрэх үед нууц үгийг нь хүчээр өөрчлүүлэх';
$string['guestloginbutton'] = 'Зочноор нэвтрэх товчлуур';
$string['infilefield'] = 'Файлд шаардлагатай талбар';
$string['instructions'] = 'Заавар';
$string['internal'] = 'Дотоод';
$string['locked'] = 'Цоожтой';
$string['md5'] = 'MD5 хөрвүүлэлт';
$string['passwordhandling'] = 'Нууц үг хадгалах';
$string['plaintext'] = 'Энгийн текст';
$string['shib_no_attributes_error'] = 'Та Shibboleth шалгах аргыг ашиглаж байгаа бололтой. Гэвч Моодл ямар ч хэрэглэгчийн мэдээлэл хүлээж авсангүй. Таны Танигч Провайдер Моодлийн Үйлчилгээний Провайдер руу шаардлагатай атрибутуудыг ($a) явуулж байгаа эсэхийг шалга. Эсвэл вэбмастертаа мэдэгд.';
$string['shib_not_all_attributes_error'] = 'Моодлд танд байхгүй Shibboleth-ийн зарим нэгэн атрибутууд хэрэгтэй байна. Эдгээр атрибутууд нь: $a<br /> Вэбмастертаа хандана уу.';
$string['shib_not_set_up_error'] = 'Shibboleth шалгах арга нь зөв тохироогүй бололтой. Учир нь энэ хуудасны Shibboleth-ийн орчны хувьсагчид алга. Нэмэлт заавар авахын тулд <a href=\"README.txt\">README</a>-ийг уншиж эсвэл энэ Моодлийг суулгасан вэбмастертаа хандана уу.';
$string['showguestlogin'] = 'Нэвтрэх хуудас дээр Зочноор нэвтрэх товчлуурыг ил эсвэл далд болгож болно';
$string['stdchangepassword'] = 'Үндсэн Нууц үг өөрчлөх хуудсыг ашиглах';
$string['stdchangepassword_expl'] = 'Хэрэв гадаад нэвтрэх систем нь нууц үгийг өөрчлөхийг зөвшөөрдөг бол энэ тохиргоог Тийм болго. Энэ тохиргоо нь \'Нууц үг өөрчлөх URL\' тохиргоог дарах болно';
$string['stdchangepassword_explldap'] = 'Анхааруулга: LDAP сервер алсынх бол LDAP сервертээ SSL нууцлалыг ашилаарай.';
$string['unlocked'] = 'Цоожлоогүй';
$string['unlockedifempty'] = 'Хоосон бол цоожлохгүй';
$string['update_never'] = 'Огт үгүй';
$string['update_oncreate'] = 'Үүсгэх үед';
$string['update_onlogin'] = 'Нэвтрэх бүрт';
$string['update_onupdate'] = 'Шинэчлэх бүрт';

?>
