<?PHP // $Id$ 
      // group.php - created with Moodle 1.9 + (Build: 20080320) (2007101509)


$string['addgroupstogrouping'] = '向组群中添加小组';
$string['addgroupstogroupings'] = '添加/删除小组';
$string['adduserstogroup'] = '添加/删除用户';
$string['allocateby'] = '分配成员';
$string['anygrouping'] = '[任何组群]';
$string['autocreategroups'] = '自动创建小组';
$string['backtogroupings'] = '返回组群';
$string['backtogroups'] = '返回小组';
$string['badnamingscheme'] = '必须包含一个“@”或“#”字符';
$string['byfirstname'] = '按名、姓的字典顺序排序';
$string['byidnumber'] = '按ID号码排序';
$string['bylastname'] = '按姓、名的字典顺序排序';
$string['createautomaticgrouping'] = '创建自动组群';
$string['creategroup'] = '创建小组';
$string['creategrouping'] = '创建组群';
$string['creategroupinselectedgrouping'] = '在组群中创建小组';
$string['createingrouping'] = '在组群中创建';
$string['createorphangroup'] = '创建独立小组';
$string['databaseupgradegroups'] = '小组版本为{$a}';
$string['defaultgrouping'] = '缺省的组群';
$string['defaultgroupingname'] = '组群';
$string['defaultgroupname'] = '小组';
$string['deleteallgroupings'] = '删除所有组群';
$string['deleteallgroups'] = '删除所有小组';
$string['deletegroupconfirm'] = '您确信要删除小组“{$a}”吗?';
$string['deletegrouping'] = '删除组群';
$string['deletegroupingconfirm'] = '您确定要删除组群“{$a}”吗？(群中的小组不会被删除。)';
$string['deleteselectedgroup'] = '删除选择的小组';
$string['editgroupingsettings'] = '修改组群设置';
$string['editgroupsettings'] = '修改小组设置';
$string['enrolmentkey'] = '选课密钥';
$string['erroraddremoveuser'] = '将用户添“{$a}”加/删除到小组中时发生错误';
$string['erroreditgroup'] = '创建小组“{$a}”时发生错误';
$string['erroreditgrouping'] = '创建组群“{$a}”时发生错误';
$string['errorinvalidgroup'] = '错误，无效的小组“{$a}”';
$string['existingmembers'] = '已有的成员：{$a}';
$string['filtergroups'] = '过滤小组：';
$string['group'] = '小组';
$string['groupaddedsuccesfully'] = '成功添加小组“{$a}”';
$string['groupby'] = '指定';
$string['groupdescription'] = '小组描述';
$string['groupinfo'] = '已选小组的信息';
$string['groupinfomembers'] = '已选成员信息';
$string['groupinfopeople'] = '已选人员信息';
$string['grouping'] = '组群';
$string['groupingdescription'] = '组群描述';
$string['groupingname'] = '组群名称';
$string['groupingnameexists'] = '组群名称“{$a}”在课程中已经存在了，请重新选择一个。';
$string['groupings'] = '组群';
$string['groupingsonly'] = '只有组群';
$string['groupmember'] = '小组成员';
$string['groupmemberdesc'] = '小组成员的标准角色';
$string['groupmembers'] = '小组成员';
$string['groupmembersonly'] = '仅对小组成员可见';
$string['groupmembersonlyerror'] = '对不起，您必须是使用此活动的小组的成员之一。';
$string['groupmemberssee'] = '查看小组成员';
$string['groupmembersselected'] = '已选小组的成员';
$string['groupmode'] = '小组模式';
$string['groupmodeforce'] = '强制小组模式';
$string['groupmy'] = '我的小组';
$string['groupname'] = '小组名称';
$string['groupnameexists'] = '此课程中已经有小组“{$a}”了，请选择另外一个。';
$string['groupnotamember'] = '对不起，您并非该小组中的一员';
$string['groups'] = '小组';
$string['groupscount'] = '小组（{$a}）';
$string['groupsgroupings'] = '小组和组群';
$string['groupsinselectedgrouping'] = '组群中的小组：';
$string['groupsnone'] = '没有小组';
$string['groupspreview'] = '小组预览';
$string['groupsseparate'] = '独立的小组';
$string['groupsvisible'] = '可视的小组';
$string['grouptemplate'] = '小组 @';
$string['hidepicture'] = '隐藏图片';
$string['javascriptrequired'] = '本页面需要激活JavaScript。';
$string['members'] = '每小组成员';
$string['membersofselectedgroup'] = '小组员：';
$string['namingscheme'] = '命名模式';
$string['namingschemehelp'] = '用@符号表示小组的字符（A-Z），用#表示小组的数字。';
$string['newgrouping'] = '新的组群';
$string['newpicture'] = '新图片';
$string['noallocation'] = '没有分配';
$string['nogroups'] = '在此课程中尚未设置小组';
$string['nogroupsassigned'] = '没有指定小组';
$string['nopermissionforcreation'] = '无法创建小组“{$a}”，因为您没有相关权限';
$string['notingrouping'] = '[不在组群中]';
$string['nousersinrole'] = '没有用户拥有选中的角色';
$string['number'] = '小组/成员统计';
$string['numgroups'] = '小组数';
$string['nummembers'] = '每小组成员';
$string['overview'] = '前概览';
$string['potentialmembers'] = '潜在的用户：{$a}';
$string['printerfriendly'] = '打印显示';
$string['random'] = '随机的';
$string['removegroupfromselectedgrouping'] = '从组群中删除小组';
$string['removegroupingsmembers'] = '从组群中清除全部小组';
$string['removegroupsmembers'] = '清除全部小组成员';
$string['removeselectedusers'] = '删除已选用户';
$string['selectfromrole'] = '通过角色选择成员';
$string['showgroupsingrouping'] = '显示组群中的小组';
$string['showmembersforgroup'] = '显示小组的成员';
$string['toomanygroups'] = '通过选择的角色无法声称小组的成员——拥有该角色的用户只有{$a}人。';
$string['usercount'] = '用户数';
$string['usercounttotal'] = '用户数({$a})';
$string['usergroupmembership'] = '选择用户的小组';
$string['cancel'] = '取消'; // ORPHANED
$string['defaultgroupdescription'] = '缺省的小组描述'; // ORPHANED
$string['defaultgroupprefix'] = '小组'; // ORPHANED
$string['displaygrouping'] = '显示组群'; // ORPHANED
$string['distributealphabetically'] = '通过姓的首字母来分小组'; // ORPHANED
$string['distributeevenly'] = '平均分配剩下的学生'; // ORPHANED
$string['editgroupingpermissions'] = '修改组群权限'; // ORPHANED
$string['errorinvalidgrouping'] = '错误，无效的组群“{$a}”'; // ORPHANED
$string['errornotingrouping'] = '对不起，你无法创建小组“{$a}”'; // ORPHANED
$string['errornotingroupingedit'] = '对不起，您无法修改组群“{$a}”'; // ORPHANED
$string['groupfor'] = '为小组'; // ORPHANED
$string['numberofgroups'] = '组群的数量'; // ORPHANED
$string['numberofstudents'] = '学生的数量'; // ORPHANED
$string['prefixforgroupnames'] = '小组名前缀'; // ORPHANED
$string['return'] = '返回'; // ORPHANED
$string['save'] = '保存'; // ORPHANED
$string['showusersalreadyingroup'] = '显示组群中小组的用户'; // ORPHANED
$string['teachersgroupmark'] = '教师无法参与其它小组的活动'; // ORPHANED
$string['teachersgroupview'] = '教师无法查看其它小组的活动'; // ORPHANED
$string['teachersoverride'] = '不属于任何小组的教师可以查看并参与所有小组的活动'; // ORPHANED
$string['upgradeconfirm'] = '对不起，Moodle 1.8 DEV中创建的小组表格必须在此次升级中删除，您确定吗？'; // ORPHANED
$string['usestudentsonlyfromselectedgroup'] = '值只使用当前选择小组的学生'; // ORPHANED
$string['viewallgroupsactivities'] = '学生可以查看所有小组的活动，但不能参与'; // ORPHANED
$string['viewallgroupsmembers'] = '学生可以查看所有小组的成员'; // ORPHANED
$string['viewowngroup'] = '学生可以查看所在小组的成员'; // ORPHANED

?>
