<?PHP // $Id$ 
      // question.php - created with Moodle 1.9.7+ (Build: 20091209) (2007101570)


$string['adminreport'] = 'Raport despre eventualele probleme apărute în baza de date cu întrebări.';
$string['broken'] = 'Aceasta reprezintă un \"broken link\" adică o legătură la un fişier inexistent';
$string['byandon'] = 'de la <em>$a->user</em> la ora <em>$a->time</em>';
$string['categorycurrent'] = 'Categoria curentă';
$string['categorycurrentuse'] = 'Folosiți această categorie';
$string['categorydoesnotexist'] = 'Această categorie nu există';
$string['categorymoveto'] = 'Salvați în această categorie';
$string['changepublishstatuscat'] = '<a href=\"$a->caturl\">Categoria \"$a->name\"</a> din cursul \"$a->coursename\" îşi va modifica opţiunea de partajare din <strong>$a->changefrom în $a->changeto</strong>.';
$string['copy'] = 'Copiați de la $a și schimbă legătura';
$string['created'] = 'Creat';
$string['createdmodifiedheader'] = 'Creat/Ultima salvare';
$string['cwrqpfs'] = 'Selectare aleatorie de întrebări din sub-categorii';
$string['defaultfor'] = 'Implicit pentru $a';
$string['defaultinfofor'] = 'Categoria implicită pentru întrebările partajate în contextul \'$a\'.';
$string['deletecoursecategorywithquestions'] = 'În banca de întrebări există întrebări asociate cu această categorie de cursuri. Continuarea acestei acţiuni va determina ştergerea acelor întrebări. Dacă doriţi puteţi să mutaţi acele întrebări în altă categorie utilizând interfaţa băncii de întrebări.';
$string['donothing'] = 'Nu copia fişiere, nu muta fişiere, nu modifica linkuri.';
$string['editingcategory'] = 'Se modifică o categorie';
$string['editingquestion'] = 'Se modifică o întrebare';
$string['editthiscategory'] = 'Editează această categorie';
$string['erroraccessingcontext'] = 'Contextul nu poate fi accesat';
$string['errordeletingquestionsfromcategory'] = 'Eroare la ștergerea unor întrebări din categoria $a.';
$string['errorfilecannotbecopied'] = 'Eroare. Nu se poate copia fișierul $a.';
$string['errorfilecannotbemoved'] = 'Eroare. Nu se poate muta fișierul $a.';
$string['errormanualgradeoutofrange'] = 'Nota $a->grade nu se încadrează în intervalul 0 - $a->maxgrade pentru întrebarea $a->name. Nici punctajul nici comentariile nu vor fi salvate.';
$string['errormovingquestions'] = 'S-a produs o eroare la realizarea operaţiunii de mutare a întrebărilor $a.';
$string['errorprocessingresponses'] = 'S-a produs o eroare în timpul procesării răspunsurilor dumneavoastră.';
$string['errorsavingcomment'] = 'Eroare întâmpinată la salvarea comentarilor pentru întrebarea $a->name în baza de date.';
$string['errorupdatingattempt'] = 'Eroare la actualizarea propunerii $a->id în baza de date';
$string['exportcategory'] = 'Exportă categoria';
$string['filesareacourse'] = 'Fișiere curs';
$string['filesareasite'] = 'Fișiere site';
$string['filestomove'] = 'Mutați / copiați fișiere la $a?';
$string['fractionsnomax'] = 'Una din întrebări trebuie să aibă un punctaj de 100%% astfel încât să fie posibilă obţinerea unei note maxime la această întrebare.';
$string['getcategoryfromfile'] = 'Obţine categorie din fişier';
$string['getcontextfromfile'] = 'Obţine context din fişier';
$string['ignorebroken'] = 'Ignorați legăturile întrerupte';
$string['linkedfiledoesntexist'] = 'Fişierul referit $a nu există';
$string['makechildof'] = 'Trasformă în subordonat al \'$a\'';
$string['maketoplevelitem'] = 'Trasferă pe primul nivel';
$string['missingimportantcode'] = 'Acest tip de întrebare nu are un cod important şi anume $a.';
$string['modified'] = 'Ultima salvare';
$string['move'] = 'Mută din $a şi schimbă linkuri.';
$string['movecategory'] = 'Mută Categorie';
$string['movedquestionsandcategories'] = 'Întrebările şi categoriile de întrebări au fost transferate din $a->oldplace în $a->newplace.';
$string['movelinksonly'] = 'Schimbaţi locaţia de destinaţie a link-ului, nu transferaţi sau copiaţi fişiere';
$string['moveq'] = 'Mută Întrebare(Întrebări)';
$string['moveqtoanothercontext'] = 'Mută întrebare în alt context.';
$string['movingcategory'] = 'Se transferă categorie';
$string['movingcategoryandfiles'] = 'Sunteţi sigur că doriţi să transferaţi categoria {$a->name} şi toate sub-categoriile corespunzătoare în contextul \"{$a->contextto}\"?<br /> În {$a->fromareaname} au fost identificate {$a->urlcount} fişiere referite din întrebări, doriţi să le copiaţi sau să le transferaţi în {$a->toareaname}?';
$string['movingcategorynofiles'] = 'Sunteţi sigur că doriţi să transferaţi categoria \"{$a->name}\" împreună cu toate categoriile subordonate în contextul \"{$a->contextto}\"?';
$string['movingquestions'] = 'Transfer Întrebări şi Fişiere Asociate';
$string['needtochoosecat'] = 'Alegeţi categoria în care doriţi să transferaţi această întrebare sau apăsaţi butonul Anulare.';
$string['nopermissionadd'] = 'Nu aveţi permisiunea să adăugaţi întrebări în această secţiune.';
$string['nopermissionmove'] = 'Nu aveţi permisiunea să transferaţi întrebări din cadrul acestei secţiuni. Va trebui să salvaţi întrebarea în această categorie sau să o salvaţi cu un alt nume.';
$string['noprobs'] = 'Nu s-au identificat probleme în baza de date cu întrebări creată de dumneavoastră.';
$string['notenoughdatatoeditaquestion'] = 'N-au fost specificate: id-ul întrebării, id-ul categoriei şi tipul întrebării.';
$string['notenoughdatatomovequestions'] = 'Va trebui să furnizaţi un id pentru fiecare întrebare pe care doriţi să o transferaţi.';
$string['permissionedit'] = 'Editează această întrebare';
$string['permissionmove'] = 'Mută această întrebare';
$string['permissionsaveasnew'] = 'Salvează ca întrebare nouă';
$string['permissionto'] = 'Aveţi permisiunea să';
$string['published'] = 'partajate';
$string['questionbank'] = 'Banca de întrebări';
$string['questioncategory'] = 'Categorie întrebare';
$string['questioncatsfor'] = 'Categorii întrebări pentru $a.';
$string['questiondoesnotexist'] = 'Această întrebare nu există.';
$string['questionsmovedto'] = 'Întrebări care sunt încă în uz au fost transferate în \"$a\" în categoria cursului principal.';
$string['questionsrescuedfrom'] = 'Întrebări salvate din contextul $a.';
$string['questionsrescuedfrominfo'] = 'Aceste întrebări (dintre care unele ar putea fi invizibile) au fost salvate atunci când contextul $a a fost şters deoarece sunt încă utilizate în cadrul unor chestionare şi a altor activităţi.';
$string['questionuse'] = 'Foloseşte întrebare în această activitate';
$string['shareincontext'] = 'Partajează în context pentru $a';
$string['tofilecategory'] = 'Scrie categorie în fişier';
$string['tofilecontext'] = 'Scrie context în fişier';
$string['unknown'] = 'Necunoscut';
$string['unknownquestiontype'] = '$a este un tip de întrebare necunoscut.';
$string['unpublished'] = 'nu este partajat';
$string['upgradeproblemcategoryloop'] = 'A fost identificată o problemă la actualizarea categoriilor de întrebări. Există o buclă în structura arborescentă a categoriilor de întrebări. ID-urile de categorii afectate de această problemă sunt $a.';
$string['upgradeproblemcouldnotupdatecategory'] = 'Nu a putut fi actualizată categoria de întrebări $a->name ($a->id).';
$string['upgradeproblemunknowncategory'] = 'S-a identificat o problemă la actualizarea categoriilor de întrebări. Categoria $a->id se referă la categoria principală $a->parent care nu mai există. Categoria subordonată a fost transferată în altă categorie principală.';
$string['yourfileshoulddownload'] = 'Fişierul dumneavoastră de export ar trebui să înceapă să se descarce în curând. Dacă acest lucru nu se întâmplă executaţi clic <a href=\"$a\">aici</a>. Categoria principală a fost schimbată pentru remedierea problemei.';

?>
