<?PHP // $Id$ 
      // group.php - created with Moodle 1.8.2+ (2007021520)


$string['addgroupstogrouping'] = 'Pridať skupiny do zoskupenia';
$string['adduserstogroup'] = 'Pridať/odstrániť používateľa zo skupiny';
$string['anygrouping'] = '[Ľubovoľné zoskupenie]';
$string['backtogroups'] = 'Späť k skupinám';
$string['cancel'] = 'Zrušiť';
$string['createautomaticgrouping'] = 'Vytvoriť zoskupenie automaticky';
$string['creategroup'] = 'Vytvoriť skupinu';
$string['creategrouping'] = 'Vytvoriť zoskupenie';
$string['creategroupinselectedgrouping'] = 'Vytvoriť skupinu vo vybranom zoskupení';
$string['createorphangroup'] = 'Vytvoriť skupinu \"sirôt\"';
$string['databaseupgradegroups'] = 'Verzia skupín je teraz $a';
$string['defaultgroupdescription'] = 'Východzí opis skupiny';
$string['defaultgroupingname'] = 'Zoskupenie';
$string['defaultgroupname'] = 'Skupina';
$string['defaultgroupprefix'] = 'Skupina';
$string['deletegroupconfirm'] = 'Naozaj chcete odstrániť skupinu \'$a\'?';
$string['deletegrouping'] = 'Odstrániť zoskupenie';
$string['deletegroupingconfirm'] = 'Naozaj chcete odstrániť zoskupenie \'$a\'? (Skupiny v tomto zoskupení nebudú odstránené)';
$string['deleteselectedgroup'] = 'Odstrániť vybranú skupinu';
$string['displaygrouping'] = 'Zobraziť zoskupenie';
$string['distributealphabetically'] = 'Rozdeliť do skupín abecedne podľa priezviska';
$string['distributeevenly'] = 'Rovnomerne rozdeliť ostávajúcich študentov';
$string['editgroupingpermissions'] = 'Upraviť oprávnenia zoskupeniu';
$string['editgroupingsettings'] = 'Upraviť nastavenie zoskupenia';
$string['editgroupsettings'] = 'Upraviť nastavenie skupiny';
$string['enrolmentkey'] = 'Kľúč k zápisu';
$string['erroraddremoveuser'] = 'Chyba pri pridávaní/odstraňovaní používateľa $a v skupine';
$string['erroreditgroup'] = 'Chyba pri vytváraní/úprave skupiny $a';
$string['erroreditgrouping'] = 'Chyba pri vytváraní/úprave zoskupenia $a';
$string['errorinvalidgroup'] = 'Chyba - neplatná skupina $a';
$string['errorinvalidgrouping'] = 'Chyba - neplatné zoskupenie $a';
$string['errornotingrouping'] = 'Ľutujem, nemôžete vytvoriť skupinu v $a';
$string['errornotingroupingedit'] = 'Ľutujem, nemôžete upraviť zoskupenie $a';
$string['existingmembers'] = 'Existujúci členovia: $a';
$string['group'] = 'Skupina';
$string['groupaddedsuccesfully'] = 'Skupina $a bola úspešne pridaná';
$string['groupdescription'] = 'Opis skupiny';
$string['groupfor'] = 'pre skupinu';
$string['groupinfo'] = 'Informácie o vybranej skupine';
$string['groupinfomembers'] = 'Informácie o vybraných členoch';
$string['groupinfopeople'] = 'Informácie o vybraných používateľoch';
$string['grouping'] = 'Zoskupenie';
$string['groupingdescription'] = 'Opis zoskupenia';
$string['groupingname'] = 'Názov zoskupenia';
$string['groupings'] = 'Zoskupenie';
$string['groupmember'] = 'Člen skupiny';
$string['groupmemberdesc'] = 'Štandardná rola pre členov skupiny';
$string['groupmembers'] = 'Členovia skupiny';
$string['groupmemberssee'] = 'Zobraziť členov skupiny';
$string['groupmembersselected'] = 'Členovia vybranej skupiny';
$string['groupmode'] = 'Režim skupin';
$string['groupmodeforce'] = 'Vnútiť režim skupín';
$string['groupmy'] = 'Moja skupina';
$string['groupname'] = 'Názov skupiny';
$string['groupnameexists'] = 'Skupina s názvom \'$a\' v tomto kurze už existuje, prosím vyberte iný názov';
$string['groupnotamember'] = 'Ľutujem, ale nie ste členom tejto skupiny';
$string['groups'] = 'Skupiny';
$string['groupsinselectedgrouping'] = 'Skupiny vo vybranom zoskupení';
$string['groupsnone'] = 'Žiadne skupiny';
$string['groupsseparate'] = 'Oddelené skupiny';
$string['groupsvisible'] = 'Viditeľné skupiny';
$string['hidepicture'] = 'Skryť obrázok';
$string['javascriptrequired'] = 'Táto stránka vyžaduje povolený JavaScript';
$string['membersofselectedgroup'] = 'Členovia vybranej skupiny';
$string['newpicture'] = 'Nový obrázok';
$string['nopermissionforcreation'] = 'Nie je možné vytvoriť skupinu \"$a\" pretože nemáte požadované oprávnenia';
$string['notingrouping'] = '[Nie je v žiadnom zoskupení]';
$string['numberofgroups'] = 'Počet skupín';
$string['numberofstudents'] = 'Počet študentov';
$string['potentialmembers'] = 'Členovia k dispozícii: $a';
$string['prefixforgroupnames'] = 'Predpona názvov skupin';
$string['printerfriendly'] = 'Zobrazenie pre tlač';
$string['removegroupfromselectedgrouping'] = 'Odobrať skupinu z vybraného zoskupenia';
$string['removeselectedusers'] = 'Odobrať vybraných používateľov';
$string['return'] = 'Späť';
$string['save'] = 'Uložiť';
$string['selectnumberineachgroup'] = 'Zvoľte počet v každej skupine';
$string['selectnumberofgroups'] = 'Zvoľte počet skupín';
$string['showgroupsingrouping'] = 'Ukázať skupiny v zoskupení';
$string['showmembersforgroup'] = 'Ukázať členov pre skupinu';
$string['showusersalreadyingroup'] = 'Ukázať používateľov, ktorí sú už v nejakej skupine spadajúcej do tohto zoskupenia';
$string['teachersgroupmark'] = 'Učitelia nemôžu známkovať činnosti v skupinách, do ktorých nepatria';
$string['teachersgroupview'] = 'Učitelia nemôžu vidieť činnosti v skupinách, do ktorých nepatria';
$string['teachersoverride'] = 'Učitelia, ktorí nie sú zaradení do žiadnej skupiny, môžu vidieť a známkovať činnosti vo všetkých skupinách (prestavuje vyššie uvedené)';
$string['upgradeconfirm'] = 'Ľutujem, databázové tabuľky skupín vytvorené vo verzii Moodle 1.8 dev musia byť behom tohto upgrade odstránené. Prajete si pokračovať?';
$string['usestudentsonlyfromselectedgroup'] = 'Použiť iba študentov z vyznačenej skupiny';
$string['viewallgroupsactivities'] = 'Študenti si môžu prehliadať činnosti vo všetkých skupinách, ale nemôžu do nich prispievať';
$string['viewallgroupsmembers'] = 'Študenti môžu vidieť členov všetkých skupín';
$string['viewowngroup'] = 'Študenti môžu vidieť členov všetkých skupín, do ktorých sami patria';
$string['numberofštudents'] = 'Počet študentov'; // ORPHANED
$string['useštudentsonlyfromselectedgroup'] = 'Použi iba študentov z práve vybraných skupín'; // ORPHANED
$string['addexistinggroupstogrouping'] = 'Pridať existujúce skupiny do zoskupenia'; // ORPHANED

?>
