<?PHP // $Id$ 
      // message.php - created with Moodle 1.8.2+ (2007021520)


$string['addcontact'] = 'Pridať kontakt';
$string['addsomecontacts'] = 'Pre poslanie správy niekomu, alebo pre pridanie odkazu naňho na túto stránku, použi <a href=\"$a\">záložku vyhľadávanie</a>.';
$string['addsomecontactsincoming'] = 'Tieto správy sú od ľudí ktorých nemáte v zozname kontaktov. Pokiaľ si ich chcete pridať medzi svoje kontakty, kliknite na ikonu \"Pridať kontakt\" za ich menom.';
$string['ago'] = '$a predtým';
$string['allmine'] = 'Všetky správy pre mňa alebo odo mňa';
$string['allstudents'] = 'Všetky správy medzi študentmi v kurze';
$string['allusers'] = 'Všetky správy od všetkých používateľov';
$string['backupmessageshelp'] = 'Pokiaľ je toto zapnuté, správa bude zahrnutá do automatického zálohovania web stránok.';
$string['beepnewmessage'] = 'Pípnuť, keď príde nová správa (pre prehranie zvuku bude možno treba zásuvný modul do prehliadača, ako napríklad Quicktime)';
$string['blockcontact'] = 'Zablokovať kontakt';
$string['blockedmessages'] = '$a správa(y) pre/od blokovaných používateľov';
$string['blocknoncontacts'] = 'Zablokovať všetky nové správy od ľudí ktorí nie sú v mojom zozname kontaktov';
$string['contactlistempty'] = 'Váš zoznam kontaktov je práve prázdny';
$string['contacts'] = 'Kontakty';
$string['context'] = 'obsah';
$string['deletemessagesdays'] = 'Počet dní, po ktorých budú staré správy automaticky vymazané';
$string['discussion'] = 'Diskusie';
$string['emailmessages'] = 'Pokiaľ nie som prihlásený, posielať mi správy e-mailom';
$string['emailtagline'] = 'Tento e-mail je kópia správy ktorá Vám bola poslaná na \"$a\"';
$string['emptysearchstring'] = 'Musíš niečo hľadať';
$string['formorethan'] = 'Pre viac ako';
$string['includeblockedusers'] = 'Zahrnúť blokovaných používateľov';
$string['incomingcontacts'] = 'Prichádzajúce kontakty ($a)';
$string['keywords'] = 'Kľúčové slová';
$string['keywordssearchresults'] = 'Výsledok hľadania: $a nájdených správ';
$string['maxmessages'] = 'Maximálny počet správ ktoré budú zobrazované v histórii diskusií';
$string['message'] = 'Správa';
$string['messagehistory'] = 'História správ';
$string['messages'] = 'Správy';
$string['messaging'] = 'Posielanie správ';
$string['mycontacts'] = 'Moje kontakty';
$string['newonlymsg'] = 'Ukázať iba nové';
$string['newsearch'] = 'Nové hľadanie';
$string['noframesjs'] = 'Verzia bez rámov a JavaScriptu';
$string['nomessages'] = 'Nečakajú žiadne správy';
$string['nomessagesfound'] = 'Neboli nájdené žiadne správy';
$string['nosearchresults'] = 'Nepodarilo sa nájsť žiadne výsledky';
$string['offline'] = 'Nepripojený';
$string['offlinecontacts'] = 'Nepripojení používatelia ($a)';
$string['online'] = 'Pripojený';
$string['onlinecontacts'] = 'Pripojení používatelia ($a)';
$string['onlyfromme'] = 'Iba správy odo mňa';
$string['onlymycourses'] = 'Iba v mojich kurzoch';
$string['onlytome'] = 'Iba správy pre mňa';
$string['pagerefreshes'] = 'Táto stránka sa obnoví automaticky každých $a sekúnd';
$string['readmessages'] = '$a číta správy';
$string['removecontact'] = 'Odstrániť kontakt';
$string['savemysettings'] = 'Ulož moje nastavenia';
$string['search'] = 'Hľadať';
$string['searchforperson'] = 'Hľadať osobu';
$string['searchmessages'] = 'Hľadať správu';
$string['sendmessage'] = 'Pošli správu';
$string['sendmessageto'] = 'Poslať správu pre $a';
$string['sendmessagetopopup'] = 'Poslať správu pre $a - nové okno';
$string['settings'] = 'Nastavenia';
$string['settingssaved'] = 'Vaše nastavenia boli uložené';
$string['showmessagewindow'] = 'Automaticky zobraz okno správ, keď dostanem novú správu (Váš prehliadač je potrebné nastaviť tak, aby neblokoval vyskakujúce okná na tejto stránke)';
$string['strftimedaydatetime'] = '%%A, %%d %%B %%Y, %%H:%%M';
$string['timenosee'] = 'Počet minút od posledného prihlásenia';
$string['timesent'] = 'Čas poslania';
$string['unblockcontact'] = 'Odblokuj kontakt';
$string['unreadmessages'] = '$a nečítaných správ';
$string['userisblockingyou'] = 'Tento používateľ má nastavené blokovanie správ od Vás';
$string['userisblockingyounoncontact'] = 'Tento používateľ prijíma správy iba od ľudí, ktorých má zapísaných vo svojom zozname kontaktov a Vy sa v ňom nenachádzate.';
$string['userssearchresults'] = 'Výsledok hľadania: $a nájdených používateľov';

?>
