<?PHP // $Id$ 
      // feedback.php - created with Moodle 1.6 (2006050506)


$string['add_item'] = 'Añadir ítem';
$string['add_items'] = 'Añadir ítem';
$string['all_old_values_will_be_deleted'] = 'Todos los valores guardados se borrarán';
$string['all_related_values_will_be_deleted'] = 'Todos los valores relacionados se borrarán';
$string['analysis'] = 'Análisis';
$string['anonymous'] = 'Anónimo';
$string['anonymous_edit'] = 'Editar anónimo';
$string['anonymous_entries'] = 'Entradas anónimas';
$string['are_you_sure_to_delete_this_entry'] = '¿Está seguro de borrar esta entrada?';
$string['are_you_sure_to_delete_this_item'] = '¿Está seguro de querer borrar este ítem?';
$string['are_you_sure_to_delete_this_template'] = '¿Está seguro de querer borrar esta plantilla?';
$string['are_you_sure_to_use_this_template'] = '¿Está seguro de querer usar esta plantilla?';
$string['average'] = 'Promedio';
$string['bold'] = 'Marcado';
$string['check'] = 'Elección múltiple - respuestas múltiples';
$string['check_values'] = 'Opciones posibles o valores';
$string['checkbox'] = 'Cuadro de selección múltiple';
$string['complete_the_form'] = 'Complete el formulario...';
$string['completed'] = 'completed';
$string['completed_feedbacks'] = 'Encuestas completadas';
$string['creating_templates'] = 'creando plantillas';
$string['delete_entry'] = 'Borrar entrada';
$string['delete_item'] = 'Borrar elemento';
$string['delete_template'] = 'Borrar plantilla';
$string['delete_templates'] = 'Borrar plantillas...';
$string['description'] = 'Descripción';
$string['dropdown'] = 'Elección múltiple - se admite respuesta simple (lista emergente)';
$string['dropdown_values'] = 'Opciones posibles o valores';
$string['dropdownlist'] = 'Lista desplegable';
$string['dropdownrated'] = 'Lista emergente (valorada)';
$string['edit_item'] = 'Editar elemento';
$string['edit_items'] = 'Editar elementos';
$string['email_notification'] = 'E-Mail-Notification';
$string['emailteachermail'] = '$a->username has filled out and sent the feedback: \'$a->feedback\'

You can view it here:

$a->url';
$string['emailteachermailhtml'] = '$a->username has filled out and sent th feedback: <i>\'$a->feedback\'</i><br /><br />
You can view it on this <a href=\"$a->url\">website</a>.';
$string['entries_saved'] = 'Entradas guardadas';
$string['export_to_excel'] = 'Exportar a Excel';
$string['handling_error'] = 'Ocurrió un error al manejar una acción en el módulo \'Feedback\'';
$string['item_name'] = 'Nombre del elemento';
$string['items_are_required'] = 'Responder a estos ítem es obligatorio';
$string['label'] = 'Etiqueta';
$string['line_labels'] = 'Etiqueta';
$string['line_values'] = 'Valoración';
$string['max_args_exceeded'] = 'Demasiados argumentos: sólo se admiten 6 argumentos';
$string['modulename'] = 'Encuesta-test';
$string['modulenameplural'] = 'Encuestas-test';
$string['movedown_item'] = 'Desplazar hacia abajo';
$string['moveup_item'] = 'Desplazar hacia arriba';
$string['multiple_submit'] = 'Envío múltiple<br /><small>En encuestas anónimas, cada usuario puede enviar cualquier número de respuestas.<br/>En encuestas que requieren autenticación, se permite a los usuarios volver a enviar sus respuestas.</small>';
$string['name'] = 'Nombre';
$string['name_required'] = 'El nombre es obligatorio';
$string['no_handler'] = 'No existe manejador de acción para';
$string['no_items_available_yet'] = 'Todavía no hay ningún ítem';
$string['no_templates_available_yet'] = 'Todavía no hay ninguna plantilla';
$string['non_anonymous'] = 'No anónimo';
$string['not_completed_yet'] = 'Todavía no se ha completado';
$string['of'] = 'de';
$string['page'] = 'Página';
$string['pagebreak'] = 'Salto de página';
$string['parameters_missing'] = 'Faltan parámetros de';
$string['picture'] = 'Imagen';
$string['picture_file_list'] = 'Lista de imágenes';
$string['picture_values'] = 'Elija uno o másarchivos<br />de imagen de la lista:';
$string['position'] = 'Posición';
$string['preview'] = 'Previsualizar';
$string['public'] = 'Público';
$string['publish_stats_on_students'] = 'Mostrar análisis a los estudiantes';
$string['question'] = 'Pregunta';
$string['questions'] = 'Preguntas';
$string['radio'] = 'Elección múltiple - respuesta única';
$string['radio_values'] = 'Opciones o valores posibles';
$string['radiobutton'] = 'Botón de selección única';
$string['radiobutton_rated'] = 'Botón de radio (valorado)';
$string['radiorated'] = 'Botón de radio (valorado)';
$string['ready_feedbacks'] = 'Encuestas listas';
$string['required'] = 'Obligatorio';
$string['responses'] = 'Respuestas';
$string['save_as_new_template'] = 'Guardar como nueva plantilla';
$string['save_entries'] = 'Guardar respuestas';
$string['save_item'] = 'Guardar ítem';
$string['saving_failed'] = 'No se pudo guardar';
$string['saving_failed_because_missing_items'] = 'no se ha podido guardar porque hay ítem que han desaparecido';
$string['selected_dump'] = 'Los índices seleccionados de la variable $SESSION están volcados más abajo:';
$string['separator_decimal'] = '.';
$string['separator_thousand'] = ',';
$string['show_all'] = 'Mostrar todo';
$string['show_entries'] = 'Mostrar entradas';
$string['show_entry'] = 'Mostrar entrada';
$string['switch_item_to_not_required'] = 'Conmutar a no obligatorio';
$string['switch_item_to_required'] = 'Conmutar a obligatorio';
$string['template'] = 'Plantilla';
$string['template_saved'] = 'Plantilla guardada';
$string['templates'] = 'Plantillas';
$string['textarea'] = 'Área de texto';
$string['textarea_height'] = 'Número de líneas';
$string['textarea_width'] = 'Anchura del área';
$string['textfield'] = 'Cuadro de texto';
$string['textfield_maxlength'] = 'Número máximo de caracteres';
$string['textfield_size'] = 'Anchura del cuadro de texto';
$string['this_feedback_is_already_submitted'] = 'Ya ha completado esta actividad.';
$string['update_item'] = 'actualizar ítem';
$string['use_one_line_for_each_value'] = '<br />(Ponga cada opción en una línea)';
$string['use_this_template'] = 'Utilice esta plantilla';
$string['using_templates'] = 'Usando plantillas';

?>
