<?PHP // $Id$ 
      // grades.php - created with Moodle 1.8.2+ (2007021520)


$string['activities'] = 'Actividades';
$string['addcategory'] = 'Añadir categoría';
$string['addcategoryerror'] = 'No se pudo añadir categoría.';
$string['addevent'] = 'Agregar elemento calificado';
$string['addexceptionerror'] = 'Ocurrió un error al añadir una excepción a userid:gradeitem';
$string['addfeedback'] = 'Agregar Retroalimentación';
$string['addgrade'] = 'Gestionar elementos calificados';
$string['addgrades'] = 'Agregrar calificaciones';
$string['addidnumbers'] = 'Agregar números id';
$string['additem'] = 'Agregar elemento de calificación';
$string['addoutcomeitem'] = 'Agregar elemento de resultado';
$string['aggregateextracreditmean'] = 'Media de calificaciones (con créditos extra)';
$string['aggregateextracreditmeanall'] = 'Media de todas las calificaciones (créditos extra)';
$string['aggregateextracreditmeangraded'] = 'Media de las calificaciones no vacías (créditos extra)';
$string['aggregatemax'] = 'Calificación más alta';
$string['aggregatemaxall'] = 'Calificación más alta de todas';
$string['aggregatemaxgraded'] = 'Calificación más alta de las no vacías';
$string['aggregatemean'] = 'Media de calificaciones';
$string['aggregatemeanall'] = 'Media de todas las calificaciones';
$string['aggregatemeangraded'] = 'Media de las calificaciones no vacías';
$string['aggregatemedian'] = 'Mediana de calificaciones';
$string['aggregatemedianall'] = 'Mediana de todas las calificaciones';
$string['aggregatemediangraded'] = 'Mediana de las calificaciones no vacías';
$string['aggregatemin'] = 'Calificación más baja';
$string['aggregateminall'] = 'Calificación más baja de todas';
$string['aggregatemingraded'] = 'Calificación más baja de las no vacías';
$string['aggregatemode'] = 'Moda de calificaciones';
$string['aggregatemodeall'] = 'Moda de todas las calificaciones';
$string['aggregatemodegraded'] = 'Moda de las de las calificaciones no vacías';
$string['aggregateonlygraded'] = 'Agregar sólo calificaciones no vacías';
$string['aggregateonlygradedhelp'] = 'Las calificaciones no existentes se tratan como calificaciones mínimas o no se incluyen en la agregación.';
$string['aggregateoutcomes'] = 'Incluir resultados en agregación';
$string['aggregateoutcomeshelp'] = 'La inclusión de resultados en la agregación puede no llevar a la calificación global deseada, así que usted tiene la opción de incluirlos o descartarlos.';
$string['aggregatesonly'] = 'Sólo agregados';
$string['aggregatesubcats'] = 'Agregar subcategorías incluyentes';
$string['aggregatesubcatshelp'] = 'La agregación se hace normalmente sólo con los hijos inmediatos, pero también es posible agregar calificaciones en todas las subcategorías excluyendo otras calificaciones agregadas.';
$string['aggregateweightedmean'] = 'Media ponderada de calificaciones';
$string['aggregateweightedmeanall'] = 'Media ponderada de todas las calificaciones';
$string['aggregateweightedmeangraded'] = 'Media ponderada de las calificaciones no vacías';
$string['aggregation'] = 'Agregación';
$string['aggregationcoef'] = 'Coeficiente de agregación';
$string['aggregationcoefhelp'] = 'Peso aplicado a todas las calificaciones de este elemento durante la agregación con otros elementos de calificación.';
$string['aggregationposition'] = 'Posición de agregación';
$string['aggregationview'] = 'Vista de agregación';
$string['allgrades'] = 'Todas las calificaciones por categoría';
$string['allstudents'] = 'Todos los estudiantes';
$string['autosort'] = 'Ordenación automática';
$string['availableidnumbers'] = 'Números id disponibles';
$string['average'] = 'Promedio';
$string['averagesdecimalpoints'] = 'Decimales en promedios columna';
$string['averagesdisplaytype'] = 'Tipo de visualización en promedios columna';
$string['backupwithoutgradebook'] = 'La copia de seguridad no contiene configuración de Libro de Calificaciones';
$string['bonuspoints'] = 'Puntos bonif.';
$string['bulkcheckboxes'] = 'Casillas de verificación masivas';
$string['calculation'] = 'Cálculo';
$string['calculationadd'] = 'Agregar cálculo';
$string['calculationedit'] = 'Editar cálculo';
$string['calculationsaved'] = 'Cálculo guardado';
$string['calculationview'] = 'Ver cálculo';
$string['categories'] = 'Categorías';
$string['categoriesanditems'] = 'Categorías y elementos';
$string['category'] = 'Categoría';
$string['categoryedit'] = 'Editar categoría';
$string['categorytotal'] = 'Total categoría';
$string['changesitedefaults'] = 'Cambiar valores por defecto del sitio';
$string['choosecategory'] = 'Seleccionar categoría';
$string['compact'] = 'Compactar';
$string['completedonly'] = 'Sólo completadas';
$string['configaggregationposition'] = 'Posición de la columna de agregación en la tabla de informe de calificaciones, en referencia a las calificaciones reales.';
$string['configaggregationview'] = 'Cada categoría puede mostrarse de tres formas: modo completo (columna agregada y columnas de elementos de calificación), sólo columna agregada, o sólo elementos de calificación.';
$string['configaveragesdecimalpoints'] = 'Número de decimales a mostrar en cada puntuación media (por grupo o completa) debajo de una columna de calificaciones. Puede ser anulada por el elemento de calificación.';
$string['configaveragesdisplaytype'] = 'Especifica cómo mostrar las medias de cada columna en el informe de calificaciones. El valor por defecto (recomendado) es Heredar, que comprueba en primer lugar el tipo de cada columna y, si éste no se ha ajustado explícitamente, toma el valor por defecto del tipo general de visionado de calificaciones. Si se han seleccionado otros tipos de visionado, pasan por alto los ajustes individuales de cada columna y utilizan exclusivamente el tipo seleccionado.';
$string['configbulkcheckboxes'] = 'Casillas de verificación al lado de cada calificación para operaciones de calificación masiva.';
$string['configdecimalpoints'] = 'Número de decimales de cada calificación. Puede ser anulado por la calificación del elemento.';
$string['configenableajax'] = 'Agrega una capa de funcionalidad AJAX al informe del calificador, simplificando y agilizando las operaciones comunes. Depende de que Javascript esté activado en el navegador del usuario.';
$string['configenableoutcomes'] = 'Apoyo para los Resultados (también conocidos como \'competencias\', \'objetivos\', \'estándars\' o \'criterios\'). Significa que calificamos usando una o más escalas que están conectadas a las declaraciones de resultados. La activación de los resultados posibilita esta forma especial de calificación en todo el sitio.';
$string['configgradeboundary'] = 'Límite del porcentaje por encima del cual se asignará una letra a las calificaciones (en el caso de que se use calificación con letras).';
$string['configgradedisplaytype'] = 'Las calificaciones pueden mostrarse como calificaciones reales, como porcentajes (en referencia a las calificaciones máxima y mínima) o como letras (A, B, C, etc.)';
$string['configgradeletter'] = 'Letra u otro símbolo usado para representar un rango de calificaciones.';
$string['configgradeletterdefault'] = 'Letra u otro símbolo usado para representar un rango de calificaciones. Deje este campo vacío para usar el valor por defecto del sitio (actualmente $a).';
$string['configgradepublishing'] = 'Habilitar la publicación en exportaciones e importaciones: Puede accederse a las calificaciones exportadas accediendo a una URL, sin tener que almacenarlas en un sitio Moodle. Las calificaciones pueden importarse accediendo a dicha URL (lo que significa que un sitio Moodle puede importar calificaciones publicadas por otro sitio).';
$string['configmeanselection'] = 'Seleccione qué tipo de calificaciones se incluirán en los promedios de columna. Las celdas sin calificación se pasarán por alto, o serán calificadas con 0 (ajuste por defecto).';
$string['configquickfeedback'] = 'La retroalimentación rápida añade un texto a cada celda de calificación en el informe del calificador, permitiendo editar muchas calificaciones simultáneamente. Puede hacer clic en el botón Actualizar para ejecutar todos estos cambios de una vez en lugar de hacerlo uno a uno.';
$string['configquickgrading'] = 'La calificación rápida añade un texto a cada celda de calificación en el informe del calificador, permitiendo editar la retroalimentación para muchas calificaciones a la vez. Puede hacer clic en el botón Actualizar para ejecutar todos estos cambios de una vez en lugar de hacerlo uno por uno.';
$string['configrangesdecimalpoints'] = 'Número de decimales a mostrar en cada rango encima de una columna de calificaciones. Puede ser anulado calificando el elemento.';
$string['configrangesdisplaytype'] = 'Especifica cómo mostrar el rango de cada columna en el informe del calificador. El valor por defecto (recomendado) es Heredar, que comprueba en primer lugar el tipo de visionado de cada columna y, si no está ajustado de forma explícita, toma el valor por defecto del tipo de visionado general de la calificación. Si están seleccionados otros tipos de visionado, pasan por alto los ajustes individuales de cada columna y usan exclusivamente el tipo seleccionado.';
$string['configshowactivityicons'] = 'Mostrar o no un icono de actividad junto a cada elemento de calificación vinculado a una actividad en el informe del calificador.';
$string['configshowaverages'] = 'Muestra las medias de las columnas en el informe del calificador.';
$string['configshowcalculations'] = 'Mostrar o no iconos de cálculo junto a cada elemento y categoría de calificación, herramientas sobre los elementos calculados e indicador visual de que una columna es calculada.';
$string['configshoweyecons'] = 'Mostrar o no un icono de \'mostrar/ocultar\' junto a cada calificación (controlando que el usuario pueda verlo).';
$string['configshowfeedback'] = 'Mostrar o no un icono de retroalimentación (para agregar/editar) junto a cada calificación.';
$string['configshowgroups'] = 'Mostrar promedios de grupo y medias en el informe del calificador.';
$string['configshowlocks'] = 'Mostrar o no un icono de \'bloquear/desbloquear\' junto a cada calificación.';
$string['configshownumberofgrades'] = 'Muestra el número de calificaciones que se están agregando junto a cada promedio, entre paréntesis. Ejemplo: 45 (34).';
$string['configshowranges'] = 'Muestra una fila que contiene el rango de calificaciones posibles para cada elemento en el informe del calificador.';
$string['configshowuserimage'] = 'Mostrar o no la imagen del perfil del usuario junto a su nombre en el informe del calificador.';
$string['configstudentsperpage'] = 'Número de estudiantes a mostrar por página en el informe del calificador.';
$string['configstudentsperpagedefault'] = 'Número de estudiantes a mostrar por página en el informe del calificador. Deje este campo vacío para usar el valor por defecto del sitio (actualmente $a).';
$string['confirmexit'] = 'Pulse OK para guardar los cambios antes de salir. Si presiona Cancelar se perderán todos los cambios no guardados.';
$string['confirmresetgrades'] = '¿Está seguro de que quiere revertir sus últimas calificaciones guardadas? Cualesquiera cambios desde la última vez que guardó se perderán.';
$string['confirmresetprefs'] = '¿Reiniciar prefrerencias?';
$string['confirmsubmitgrades'] = '¿Está seguro de que quiere enviar los cambios?';
$string['contract'] = 'Contraer categoría';
$string['coursegradecategory'] = 'Categoría de calificación de curso';
$string['coursename'] = 'Nombre del curso';
$string['coursetotal'] = 'Total del curso';
$string['createevent'] = 'Crear evento';
$string['creatinggradebooksettings'] = 'Creando ajustes de libro de calificaciones';
$string['creatinggradebooksettings'] = 'Creando ajustes del libro de calificaciones';
$string['csv'] = 'CSV';
$string['curveto'] = 'Curvar a';
$string['decimalpoints'] = 'Puntos decimales globales';
$string['default'] = 'Por defecto';
$string['deletecategory'] = 'Eliminar categoría';
$string['deleteevent'] = 'Eliminar evento';
$string['description'] = 'Descripción:';
$string['displaylettergrade'] = 'Mostrar calificaciones con letra';
$string['displaypercent'] = 'Mostrar porcentajes';
$string['displaypoints'] = 'Mostrar puntos';
$string['displayweighted'] = 'Mostrar calificaciones ponderadas';
$string['droplow'] = 'Descartar la más baja';
$string['droplowhelp'] = 'Esta opción descartará las X calificaciones más bajas, siendo X el valor seleccionado.';
$string['dropped'] = 'Descartadas';
$string['dropxlowest'] = 'Descartar X más bajas';
$string['dropxlowestwarning'] = 'Nota: Si usa \'descartar x más bajas\', la calificación asume que todos los ítems de la categoría tienen el mismo valor en puntos. Si dichos valores difieren, los resultados serán impredecibles';
$string['duplicatename'] = 'copiar';
$string['duplicatescale'] = 'Duplicar escala';
$string['edit'] = 'Editar';
$string['editanotherassignmentcategory'] = 'Editar calificaciones en otra categoría';
$string['editassignment'] = 'Editar';
$string['editcalculation'] = 'Editar cálculo';
$string['editevent'] = 'Editar evento calificado existente';
$string['editfeedback'] = 'Editar retroalimentación';
$string['editgrade'] = 'Editar calificación';
$string['editgrades'] = 'Editar calificaciones';
$string['editoutcomes'] = 'Editar resultados';
$string['edittree'] = 'Categorías y elementos';
$string['enableajax'] = 'Habilitar AJAX';
$string['enableoutcomes'] = 'Habilitar resultados';
$string['errorcalculationnoequal'] = 'La fórmula debe comenzar por el signo \'igual\' (=1+2)';
$string['errorcalculationunknown'] = 'Fórmula no válida';
$string['errorgradevaluenonnumeric'] = 'Recibido valor no numérico para calificación baja o alta para';
$string['errornocategorizedid'] = '¡No se ha podido conseguir un id no categorizada!';
$string['errornocategorizedid'] = '¡No se ha podido conseguir una id no categorizada!';
$string['errornocourse'] = 'No se pudo obtener información del curso';
$string['errorreprintheadersnonnumeric'] = 'Recibido valor no numérico para cabeceras de reimpresión';
$string['exceptions'] = 'Excepciones';
$string['excluded'] = 'Excluídos';
$string['excludedhelp'] = 'Si está activada esta opción, esta calificación será excluída de cualquier agregación ejecutada por cualquier elemento o categoría de calificación de rango superior.';
$string['expand'] = 'Expandir categoría';
$string['export'] = 'Exportar';
$string['export'] = 'Exportar';
$string['exportfeedback'] = 'Incluir retroalimentación en la exportación';
$string['exportletters'] = 'Exportar letras';
$string['exportletters'] = 'Exportar letras';
$string['exportlettershelp'] = 'Cuando los elementos usen letras en lugar de valores, se exportarán las letras en lugar de los valores reales.';
$string['exportplugins'] = 'Conectores de exportación';
$string['extracredit'] = 'Crédito extra';
$string['extracreditwarning'] = 'Nota: Si se adscribe un crédito extra a todos los ítems de una categoría, se eliminarán del cálculo de la calificación, por lo que no existirá una puntuación total';
$string['feedback'] = 'Retroalimentación';
$string['feedbackadd'] = 'Agregar retroalimentación';
$string['feedbackedit'] = 'Editar retroalimentación';
$string['feedbackhelp'] = 'Notas que el profesor agrega a la calificación. Pueden ser una retroalimentación extensa, personalizada, o un código simple insertado en un sistema interno de retroalimentación.';
$string['feedbacksaved'] = 'Retroalimentación guardada';
$string['feedbackview'] = 'Ver retroalimentación';
$string['finalgrade'] = 'Calificación final';
$string['finalgradehelp'] = 'Se calcula la calificación final después de realizar todos los cálculos.';
$string['forstudents'] = 'Para los estudiantes';
$string['full'] = 'Completo';
$string['fullmode'] = 'Vista completa';
$string['grade'] = 'Calificación';
$string['gradebook'] = 'Libro de calificaciones';
$string['gradebookhiddenerror'] = 'El libro de calificaciones está ajustado de modo que no se mostrará nada a los estudiantes.';
$string['gradebookhistories'] = 'Historias de calificación';
$string['gradebookstatswarning'] = 'Las estadísticas incluyen tareas incompletas que aparecen como \'-\' y se cuentan como 0';
$string['gradeboundary'] = 'Límite de la calificación con letra';
$string['gradecategory'] = 'Categoría de calificación actual:';
$string['gradecategoryhelp'] = 'Ayuda sobre categorías de calificaciones';
$string['gradedisplaytype'] = 'Modo de mostrar calificación';
$string['gradedon'] = 'Calificados $a';
$string['gradeeventname'] = 'Nombre del elemento calificado:';
$string['gradeeventpoints'] = 'Puntos';
$string['gradeexceptions'] = 'Excluir de calificación';
$string['gradeexceptionshelp'] = 'Ayuda sobre excepciones de calificaciones';
$string['gradehelp'] = 'Ayuda sobre las calificaciones';
$string['gradeitem'] = 'Elemento de calificación';
$string['gradeitemaddusers'] = 'Excluir de calificación';
$string['gradeitemmembersselected'] = 'Excluídos de calificación';
$string['gradeitemnonmembers'] = 'Incluídos en calificación';
$string['gradeitemremovemembers'] = 'Incluir en calificación';
$string['gradeitems'] = 'Elementos de calificación';
$string['gradeletter'] = 'Letra de calif.';
$string['gradeletterhelp'] = 'Ayuda sobre letra de calificación';
$string['gradeletternote'] = 'Para eliminar una letra de calificación, simplemente vacíe cualquiera de las<br />tres áreas de texto de dicha letra y haga clic en guardar cambios.';
$string['grademax'] = 'Calif. máxima';
$string['grademax'] = 'Calif. máxima';
$string['grademaxhelp'] = 'Calificación máxima posible de este elemento.';
$string['grademin'] = 'Calif. mínima';
$string['grademinhelp'] = 'Calificación mínima posible de este elemento.';
$string['gradeoutcomeitem'] = 'Elemento de resultado de calificación';
$string['gradepass'] = 'Calificación para aprobar';
$string['gradepasshelp'] = '¿Qué calificación se necesita para aprobar?';
$string['gradepreferenceshelp'] = 'Ayuda sobre preferencias de calificación';
$string['gradepublishing'] = 'Habilitar publicación';
$string['grades'] = 'Calificaciones';
$string['gradesonly'] = 'Sólo calificaciones';
$string['gradessettings'] = 'Ajustes';
$string['gradetype'] = 'Tipo de calificación';
$string['gradetypehelp'] = 'Tipo de calificación usado por este elemento. Hay 4 tipos: ninguno, valor, escala y texto. Sólo pueden agregarse los tipos de valor y escala.';
$string['gradeview'] = 'Ver calificación';
$string['gradeweighthelp'] = 'Ayuda sobre ponderación de calificaciones';
$string['groupavg'] = 'Promedio del grupo';
$string['havenotsaved1'] = 'No ha guardado en los últimos';
$string['havenotsaved2'] = '. minutos. ¿Desea guardar sus cambios ahora?';
$string['hidden'] = 'Ocultas';
$string['hiddenuntil'] = 'Ocultas hasta';
$string['hiddenuntildate'] = 'Ocultas hasta: $a';
$string['hideadvanced'] = 'Ocultar características avanzadas';
$string['hideaverages'] = 'Ocultar promedios';
$string['hidecalculations'] = 'Ocultar cálculos';
$string['hidecategory'] = 'Ocultos';
$string['hideeyecons'] = 'Ocultar iconos \'mostrar/ocultar\'';
$string['hidefeedback'] = 'Ocultar retroalimentación';
$string['hidegroups'] = 'Ocultar grupos';
$string['hidelocks'] = 'Ocultar bloqueos';
$string['hidenooutcomes'] = 'Mostrar resultados';
$string['hideranges'] = 'Ocultar rangos';
$string['highgradeascending'] = 'Ordenar por calificación ascendente';
$string['highgradedescending'] = 'Ordenar por calificación descendente';
$string['highgradeletter'] = 'Altas';
$string['idnumberhelp'] = 'Número de identificación arbitrario proporcionado por el módulo responsable (debe ser definido y único).';
$string['idnumbers'] = 'Números id';
$string['import'] = 'Importar';
$string['importplugins'] = 'Conectores de importación';
$string['incompleteincluded'] = 'Incluyendo incompletas';
$string['incorrectcourseid'] = 'La ID del curso es incorrecta';
$string['inherit'] = 'Heredar';
$string['item'] = 'Elemento';
$string['iteminfo'] = 'Info elemento';
$string['iteminfohelp'] = 'Info y notas sobre este elemento.';
$string['itemname'] = 'Nombre del elemento';
$string['itemnamehelp'] = 'Nombre de este elemento, suministrado por el módulo.';
$string['items'] = 'Elementos';
$string['itemsedit'] = 'Editar elemento de calificación';
$string['keephigh'] = 'Mantener la más alta';
$string['keephighhelp'] = 'Esta opción conservará sólo las X calificaciones más altas, siendo X el valor seleccionado.';
$string['keymanager'] = 'Gestor de claves';
$string['left'] = 'Izquierda';
$string['letter'] = 'Letra';
$string['lettergrade'] = 'Calificación por letra';
$string['lettergradenonnumber'] = 'Calificaciones bajas y/o altas no numéricas para';
$string['letters'] = 'Letras';
$string['linkedactivity'] = 'Actividad vinculada';
$string['linkedactivityhelp'] = 'Actividad opcional a la que está vinculado este elemento de resultado.';
$string['locked'] = 'Bloqueada';
$string['locktime'] = 'Bloqueada desde';
$string['locktimedate'] = 'Bloqueada desde: $a';
$string['lowest'] = 'Más baja';
$string['lowgradeletter'] = 'Baja';
$string['max'] = 'Más alta';
$string['maxgrade'] = 'Calif. máx.';
$string['meanall'] = 'Todas las calificaciones';
$string['meangraded'] = 'Calificaciones no vacías';
$string['meanselection'] = 'Calificaciones seleccionadas para promedios';
$string['median'] = 'Mediana';
$string['min'] = 'Más baja';
$string['mode'] = 'Moda';
$string['multfactor'] = 'Multiplicador';
$string['multfactorhelp'] = 'Factor por el que se multiplicarán todas las calificaciones de este elemento.';
$string['na'] = 'ND';
$string['negativegrade'] = 'Calificación negativa';
$string['newevent'] = 'Agregar nuevo elemento calificado';
$string['newuserkey'] = 'Nueva clave de usuario';
$string['no'] = 'No';
$string['nocategories'] = 'No se han añadido o no se han encontrado las categorías de calificación para este curso';
$string['nocategoryview'] = 'No categoría para ver por';
$string['nogradeitemsinanycategory'] = 'No hay categorías de calificación que incluyan elementos calificados';
$string['nogradeletters'] = 'No se han ajustado las letras de calificación';
$string['nogradeschanged'] = 'No se cambió ninguna calificación';
$string['nogradesreturned'] = 'No se han devuelto calificaciones';
$string['noidnumber'] = 'No número id';
$string['nolettergrade'] = 'No calificación por letra para';
$string['nomode'] = 'NA';
$string['nonnumericweight'] = 'Recibido valor no numérico para';
$string['nonweightedpct'] = '%% no ponderado';
$string['nooutcome'] = 'No resultado';
$string['nopublish'] = 'No publicar';
$string['notteachererror'] = 'Sólo los profesores pueden usar esta opción.';
$string['notvalid'] = 'calificación no válida';
$string['numberofgrades'] = 'Número de calificaciones';
$string['onascaleof'] = 'en una escala de $a->grademin a $a->grademax';
$string['operations'] = 'Operaciones';
$string['options'] = 'Opciones';
$string['outcome'] = 'Resultado';
$string['outcomecategory'] = 'Crear resultados en categoría';
$string['outcomecategorynew'] = 'Nueva categoría';
$string['outcomecreate'] = 'Agregar nuevo resultado';
$string['outcomeidhelp'] = 'Resultado que representa este elemento de calificación.';
$string['outcomeitem'] = 'Elemento de resultado';
$string['outcomeitemsedit'] = 'Editar elemento de resultado';
$string['outcomename'] = 'Nombre del resultado';
$string['outcomereport'] = 'Informe del resultado';
$string['outcomes'] = 'Resultados';
$string['outcomescourse'] = 'Resultados usados en el curso';
$string['outcomescoursecustom'] = 'Uso personal (no quitar)';
$string['outcomescoursenotused'] = 'Estándar no usado';
$string['outcomescourseused'] = 'Usado estándar (no quitar)';
$string['outcomescustom'] = 'Resultados personalizados';
$string['outcomesstandard'] = 'Resultados estándar';
$string['outcomesstandardavailable'] = 'Resultados estándar disponibles';
$string['outcomestandard'] = 'Resultado disponible';
$string['outcomestandardhelp'] = 'Resultado estándar disponible en todo el sitio (i.e., en todos los cursos).';
$string['overallaverage'] = 'Promedio general';
$string['overallavg'] = 'Promedio general';
$string['overridden'] = 'Anuladas';
$string['overriddenhelp'] = 'Cuando se activa, previene cualesquiera intentos futuros de ajustar automáticamente el valor de la calificación. Este FLAG con frecuencia es ajustado internamente por el libro de calificaciones, pero puede activarse o desactivarse manualmente utilizando esta opción.';
$string['pctoftotalgrade'] = '%% de la calificación total';
$string['percent'] = 'Porcentaje';
$string['percentage'] = 'Porcentaje';
$string['percentascending'] = 'Clasificar por porcentaje ascendente';
$string['percentdescending'] = 'Ordenar por porcentaje descendente';
$string['percentshort'] = '%%';
$string['plusfactor'] = 'Compensar';
$string['plusfactorhelp'] = 'Número que se añadirá a cada calificación de este elemento, una vez que se haya aplicado el multiplicador.';
$string['points'] = 'puntos';
$string['pointsascending'] = 'Clasificar por puntos ascendente';
$string['pointsdescending'] = 'Clasificar por puntos descendente';
$string['preferences'] = 'Preferencias';
$string['prefgeneral'] = 'General';
$string['prefletters'] = 'Letras de calificación y límites';
$string['prefrows'] = 'Filas especiales';
$string['prefshow'] = 'Mostrar/ocultar conmutadores';
$string['publishing'] = 'Publicando';
$string['quickfeedback'] = 'Retroalimentación rápida';
$string['quickgrading'] = 'Calificación rápida';
$string['range'] = 'Rango';
$string['rangesdecimalpoints'] = 'Decimales en los rangos';
$string['rangesdisplaytype'] = 'Tipo de visualización del rango';
$string['rawpct'] = '%% bruto';
$string['real'] = 'Real';
$string['report'] = 'Informe';
$string['reportplugins'] = 'Conectores de informe';
$string['reportsettings'] = 'Ajustes de informe';
$string['reprintheaders'] = 'Reimprimir cabeceras';
$string['resetgradepreferences'] = '¿Está seguro de que desea reiniciar todas las preferencias de calificación para $a? <br /><br />Se perderán todos los ajustes (e. g., ponderación, categorías, descartar la más baja, curvado, etc.).';
$string['respectingcurrentdata'] = 'la configuración actual queda sin modificar';
$string['reverttolastsave'] = 'Descartar cambios';
$string['right'] = 'Derecha';
$string['savechanges'] = 'Guardar cambios';
$string['savegradechanges'] = 'Guardar cambios de calificación';
$string['savegradeserror'] = 'Se han encontrado $a problema(s) al intentar guardar las calificaciones. Por favor, revise más abajo';
$string['savegradesinfo'] = '<br>Las calificaciones editables se muestran en verde. Haga clic en Guardar cambios de calificación para ver los resultados en los cambios que ha hecho en las calificaciones de los estudiantes.';
$string['savegradessuccess'] = '$a calificación(es) se han guardado con éxito';
$string['savepreferences'] = 'Guardar preferencias';
$string['scaledpct'] = 'Escalado %%';
$string['scaleidhelp'] = 'Escala a la que se vincula este $a.';
$string['scalestandardhelp'] = 'Una escala estándar está disponible en todos los cursos del sitio.';
$string['setcategories'] = 'Categorías';
$string['setcategorieserror'] = 'Debe ajustar las categorías del curso antes de poder asignarles ponderaciones.';
$string['setgradeletters'] = 'Calificar con letra';
$string['setpreferences'] = 'Preferencias';
$string['setting'] = 'Ajuste';
$string['settings'] = 'Ajustes';
$string['setweights'] = 'Pesos';
$string['showactivityicons'] = 'Mostrar iconos de actividad';
$string['showallstudents'] = 'Mostrar a todos los estudiantes';
$string['showaverages'] = 'Mostrar promedios de columna';
$string['showcalculations'] = 'Mostrar cálculos';
$string['showeyecons'] = 'Mostrar iconos \'mostrar/ocultar\'';
$string['showfeedback'] = 'Mostrar retroalimentación';
$string['showgroups'] = 'Mostrar grupos';
$string['showhiddenitems'] = 'Mostrar elementos ocultos';
$string['showlocks'] = 'Mostrar bloqueos';
$string['shownooutcomes'] = 'Ocultar resultados';
$string['shownumberofgrades'] = 'Mostrar número de calificaciones en los promedios';
$string['showranges'] = 'Mostrar rangos';
$string['showuserimage'] = 'Mostrar imágenes de perfil del usuario';
$string['sitedefault'] = 'Valor por defecto del sitio ($a)';
$string['sitewide'] = 'Todo el sitio';
$string['sort'] = 'ordenar';
$string['sortasc'] = 'Ordenar (ascendente)';
$string['sortbyfirstname'] = 'Ordenar por nombre';
$string['sortbylastname'] = 'Ordenar por apellido';
$string['sortdesc'] = 'Ordenar (descendente)';
$string['standarddeviation'] = 'Desviación típica';
$string['stats'] = 'Estadísticas';
$string['statslink'] = 'Estadísticas';
$string['student'] = 'Estudiante';
$string['studentsperpage'] = 'Estudiantes por página';
$string['synclegacygrades'] = 'Sincronizar calificaciones heredadas';
$string['total'] = 'Total';
$string['totalweight100'] = 'El peso total es igual a 100';
$string['totalweightnot100'] = 'El peso total no es igual a 100';
$string['turnfeedbackoff'] = 'Desactivar retroalimentación';
$string['turnfeedbackon'] = 'Activar retroalimentación';
$string['typenone'] = 'Ninguno';
$string['typescale'] = 'Escala';
$string['typetext'] = 'Texto';
$string['typevalue'] = 'Valor';
$string['uncategorised'] = 'Sin categorizar';
$string['unused'] = 'Sin uso';
$string['useadvanced'] = 'Usar características avanzadas';
$string['usedcourses'] = 'Cursos usados';
$string['usedgradeitem'] = 'Elemento de calificación usado';
$string['usenooutcome'] = 'No usar resultado';
$string['usenoscale'] = 'No usar escala';
$string['usepercent'] = 'Usar porcentaje';
$string['user'] = 'Usuario';
$string['userkeyhelp'] = 'Seleccione una clave guardada que dé a los usuarios acceso a los datos publicados por este conector de exportación, sin tener que almacenarlos en Moodle. Seleccione \'crear nueva clave de usuario\' para generar una nueva clave al remitir este formulario.';
$string['userpreferences'] = 'Preferencias del usuario';
$string['useweighted'] = 'Usar ponderación';
$string['viewbygroup'] = 'Grupo';
$string['viewgrades'] = 'Ver calificaciones';
$string['weight'] = 'Peso';
$string['weightedascending'] = 'Clasificar por porcentaje ponderado ascendente';
$string['weighteddescending'] = 'Clasificar por porcentaje ponderado descendente';
$string['weightedpct'] = '%% ponderado';
$string['weightedpctcontribution'] = 'contribución %% ponderado';
$string['writinggradebookinfo'] = 'Escribiendo ajustes del libro de calificaciones';
$string['xml'] = 'XML';
$string['yes'] = 'Sí';
$string['yourchangesweresaved'] = 'Sus cambios se han guardado';
$string['yourgrade'] = 'Su calificación';
$string['badgrade'] = 'La calificación suministrada no es válida'; // ORPHANED
$string['baduser'] = 'El usuario suministrado no es válido'; // ORPHANED
$string['categoriesedit'] = 'Editar Categorías'; // ORPHANED
$string['categoryname'] = 'Nombre de la categoría'; // ORPHANED
$string['createcategory'] = 'Crear categoría'; // ORPHANED
$string['createcategoryerror'] = 'No se ha podido crear una categoría nueva'; // ORPHANED
$string['encoding'] = 'Codificación'; // ORPHANED
$string['exportods'] = 'Exportar ODS'; // ORPHANED
$string['exporttxt'] = 'Exportar TXT'; // ORPHANED
$string['exportxml'] = 'Exportar XML'; // ORPHANED
$string['forelementtypes'] = 'para el $a seleccionado'; // ORPHANED
$string['gradeitemlocked'] = 'Calificación bloqueada'; // ORPHANED
$string['gradeitemsinc'] = 'Elementos de calificación a incluir'; // ORPHANED
$string['gradepreferences'] = 'Preferencias de Calificación'; // ORPHANED
$string['gradereports'] = 'Informe de calificaciones'; // ORPHANED
$string['graderreport'] = 'Informe del calificador'; // ORPHANED
$string['identifier'] = 'Identificar al usuario por'; // ORPHANED
$string['importcsv'] = 'Importar CSV'; // ORPHANED
$string['importfailed'] = 'Importación fallida'; // ORPHANED
$string['importfile'] = 'Importar archivo'; // ORPHANED
$string['importpreview'] = 'Vista previa de la importación'; // ORPHANED
$string['importsuccess'] = 'Importación de calificaciones exitosa'; // ORPHANED
$string['importxml'] = 'Importar XML'; // ORPHANED
$string['lock'] = 'Bloquear'; // ORPHANED
$string['mapfrom'] = 'Mapa desde'; // ORPHANED
$string['mappings'] = 'Mapeos de elementos de calificación'; // ORPHANED
$string['mapto'] = 'Mapa a'; // ORPHANED
$string['movingelement'] = 'Moviendo $a'; // ORPHANED
$string['newcategory'] = 'Categoría nueva'; // ORPHANED
$string['nocategoryname'] = 'No se ha dado nombre de categoría'; // ORPHANED
$string['noselectedcategories'] = 'no se han seleccionado categorías'; // ORPHANED
$string['noselecteditems'] = 'no se han seleccionado elementos.'; // ORPHANED
$string['rank'] = 'Rango'; // ORPHANED
$string['selectdestination'] = 'Seleccionar destino de $a'; // ORPHANED
$string['separator'] = 'Separador'; // ORPHANED
$string['sepcomma'] = 'Coma'; // ORPHANED
$string['septab'] = 'Tabulador'; // ORPHANED
$string['subcategory'] = 'Categoría normal'; // ORPHANED
$string['topcategory'] = 'Categoría super'; // ORPHANED
$string['unlock'] = 'Desbloquear'; // ORPHANED
$string['uploadgrades'] = 'Subir calificaciones'; // ORPHANED
$string['userreport'] = 'Informe de calificación del usuario'; // ORPHANED

?>
