<?PHP // $Id$ 
      // grades.php - created with Moodle 1.8.2+ (2007021520)


$string['activities'] = 'Actividades';
$string['addcategory'] = 'Añadir categoría';
$string['addcategoryerror'] = 'No se pudo añadir categoría.';
$string['addevent'] = 'Agregar elemento calificado';
$string['addexceptionerror'] = 'Ocurrió un error al añadir una excepción a userid:gradeitem';
$string['addfeedback'] = 'Agregar Retroalimentación';
$string['addgrade'] = 'Gestionar elementos calificados';
$string['addgrades'] = 'Agregrar calificaciones';
$string['addidnumbers'] = 'Agregar números id';
$string['additem'] = 'Agregar elemento de calificación';
$string['addoutcomeitem'] = 'Agregar elemento de resultado';
$string['aggregateextracreditmeanall'] = 'Media de todas las calificaciones (créditos extra)';
$string['aggregateextracreditmeangraded'] = 'Media de las calificaciones no vacías (créditos extra)';
$string['aggregatemaxall'] = 'Calificación más alta de todas';
$string['aggregatemaxgraded'] = 'Calificación más alta de las no vacías';
$string['aggregatemeanall'] = 'Media de todas las calificaciones';
$string['aggregatemeangraded'] = 'Media de las calificaciones no vacías';
$string['aggregatemedianall'] = 'Mediana de todas las calificaciones';
$string['aggregatemediangraded'] = 'Mediana de las calificaciones no vacías';
$string['aggregateminall'] = 'Calificación más baja de todas';
$string['aggregatemingraded'] = 'Calificación más baja de las no vacías';
$string['aggregatemodeall'] = 'Moda de todas las calificaciones';
$string['aggregatemodegraded'] = 'Moda de las de las calificaciones no vacías';
$string['aggregateoutcomes'] = 'Incluir resultados en agregación';
$string['aggregateoutcomeshelp'] = 'La inclusión de resultados en la agregación puede no llevar a la calificación global deseada, así que usted tiene la opción de incluirlos o descartarlos.';
$string['aggregatesonly'] = 'Sólo agregados';
$string['aggregateweightedmeanall'] = 'Media ponderada de todas las calificaciones';
$string['aggregateweightedmeangraded'] = 'Media ponderada de las calificaciones no vacías';
$string['aggregation'] = 'Agregación';
$string['aggregationcoef'] = 'Coeficiente de agregación';
$string['aggregationcoefhelp'] = 'Peso aplicado a todas las calificaciones de este elemento durante la agregación con otros elementos de calificación.';
$string['aggregationposition'] = 'Posición de agregación';
$string['aggregationview'] = 'Vista de agregación';
$string['allgrades'] = 'Todas las calificaciones por categoría';
$string['allstudents'] = 'Todos los estudiantes';
$string['autosort'] = 'Ordenación automática';
$string['availableidnumbers'] = 'Números id disponibles';
$string['average'] = 'Promedio';
$string['averagesdecimalpoints'] = 'Decimales en promedios columna';
$string['averagesdisplaytype'] = 'Tipo de visualización en promedios columna';
$string['backupwithoutgradebook'] = 'La copia de seguridad no contiene configuración de Libro de Calificaciones';
$string['bonuspoints'] = 'Puntos bonif.';
$string['calculation'] = 'Cálculo';
$string['calculationadd'] = 'Agregar cálculo';
$string['calculationedit'] = 'Editar cálculo';
$string['calculationsaved'] = 'Cálculo guardado';
$string['calculationview'] = 'Ver cálculo';
$string['categories'] = 'Categorías';
$string['categoriesanditems'] = 'Categorías y elementos';
$string['category'] = 'Categoría';
$string['categoryedit'] = 'Editar categoría';
$string['categorytotal'] = 'Total categoría';
$string['changesitedefaults'] = 'Cambiar valores por defecto del sitio';
$string['choosecategory'] = 'Seleccionar categoría';
$string['completedonly'] = 'Sólo completadas';
$string['confirmexit'] = 'Pulse OK para guardar los cambios antes de salir. Si presiona Cancelar se perderán todos los cambios no guardados.';
$string['confirmresetgrades'] = '¿Está seguro de que quiere revertir sus últimas calificaciones guardadas? Cualesquiera cambios desde la última vez que guardó se perderán.';
$string['confirmresetprefs'] = '¿Reiniciar prefrerencias?';
$string['confirmsubmitgrades'] = '¿Está seguro de que quiere enviar los cambios?';
$string['coursename'] = 'Nombre del curso';
$string['coursetotal'] = 'Total del curso';
$string['createevent'] = 'Crear evento';
$string['creatinggradebooksettings'] = 'Creando ajustes de libro de calificaciones';
$string['csv'] = 'CSV';
$string['curveto'] = 'Curvar a';
$string['decimalpoints'] = 'Puntos decimales globales';
$string['default'] = 'Por defecto';
$string['deletecategory'] = 'Eliminar categoría';
$string['deleteevent'] = 'Eliminar evento';
$string['description'] = 'Descripción:';
$string['displaylettergrade'] = 'Mostrar calificaciones con letra';
$string['displaypercent'] = 'Mostrar porcentajes';
$string['displaypoints'] = 'Mostrar puntos';
$string['displayweighted'] = 'Mostrar calificaciones ponderadas';
$string['droplow'] = 'Descartar la más baja';
$string['droplowhelp'] = 'Esta opción descartará las X calificaciones más bajas, siendo X el valor seleccionado.';
$string['dropped'] = 'Descartadas';
$string['dropxlowest'] = 'Descartar X más bajas';
$string['dropxlowestwarning'] = 'Nota: Si usa \'descartar x más bajas\', la calificación asume que todos los ítems de la categoría tienen el mismo valor en puntos. Si dichos valores difieren, los resultados serán impredecibles';
$string['duplicatename'] = 'copiar';
$string['duplicatescale'] = 'Duplicar escala';
$string['edit'] = 'Editar';
$string['editanotherassignmentcategory'] = 'Editar calificaciones en otra categoría';
$string['editassignment'] = 'Editar';
$string['editcalculation'] = 'Editar cálculo';
$string['editevent'] = 'Editar evento calificado existente';
$string['editfeedback'] = 'Editar retroalimentación';
$string['editgrade'] = 'Editar calificación';
$string['editgrades'] = 'Editar calificaciones';
$string['editoutcomes'] = 'Editar resultados';
$string['edittree'] = 'Categorías y elementos';
$string['enableajax'] = 'Habilitar AJAX';
$string['enableoutcomes'] = 'Habilitar resultados';
$string['errorcalculationnoequal'] = 'La fórmula debe comenzar por el signo \'igual\' (=1+2)';
$string['errorcalculationunknown'] = 'Fórmula no válida';
$string['errorgradevaluenonnumeric'] = 'Recibido valor no numérico para calificación baja o alta para';
$string['errornocategorizedid'] = '¡No se ha podido conseguir un id no categorizada!';
$string['errornocourse'] = 'No se pudo obtener información del curso';
$string['errorreprintheadersnonnumeric'] = 'Recibido valor no numérico para cabeceras de reimpresión';
$string['exceptions'] = 'Excepciones';
$string['excluded'] = 'Excluídos';
$string['extracredit'] = 'Crédito extra';
$string['extracreditwarning'] = 'Nota: Si se adscribe un crédito extra a todos los ítems de una categoría, se eliminarán del cálculo de la calificación, por lo que no existirá una puntuación total';
$string['forstudents'] = 'Para los estudiantes';
$string['gradebook'] = 'Libro de calificaciones';
$string['gradebookhiddenerror'] = 'El libro de calificaciones está ajustado de modo que no se mostrará nada a los estudiantes.';
$string['gradebookstatswarning'] = 'Las estadísticas incluyen tareas incompletas que aparecen como \'-\' y se cuentan como 0';
$string['gradecategory'] = 'Categoría de calificación actual:';
$string['gradecategoryhelp'] = 'Ayuda sobre categorías de calificaciones';
$string['gradeeventname'] = 'Nombre del elemento calificado:';
$string['gradeeventpoints'] = 'Puntos';
$string['gradeexceptions'] = 'Excluir de calificación';
$string['gradeexceptionshelp'] = 'Ayuda sobre excepciones de calificaciones';
$string['gradehelp'] = 'Ayuda sobre las calificaciones';
$string['gradeitem'] = 'Elemento de calificación';
$string['gradeitemaddusers'] = 'Excluir de calificación';
$string['gradeitemmembersselected'] = 'Excluídos de calificación';
$string['gradeitemnonmembers'] = 'Incluídos en calificación';
$string['gradeitemremovemembers'] = 'Incluir en calificación';
$string['gradeitems'] = 'Elementos de calificación';
$string['gradeletter'] = 'Letra de calif.';
$string['gradeletterhelp'] = 'Ayuda sobre letra de calificación';
$string['gradeletternote'] = 'Para eliminar una letra de calificación, simplemente vacíe cualquiera de las<br />tres áreas de texto de dicha letra y haga clic en guardar cambios.';
$string['gradepreferenceshelp'] = 'Ayuda sobre preferencias de calificación';
$string['grades'] = 'Calificaciones';
$string['gradeview'] = 'Ver calificación';
$string['gradeweighthelp'] = 'Ayuda sobre ponderación de calificaciones';
$string['groupavg'] = 'Promedio del grupo';
$string['havenotsaved1'] = 'No ha guardado en los últimos';
$string['havenotsaved2'] = '. minutos. ¿Desea guardar sus cambios ahora?';
$string['hidden'] = 'Ocultos';
$string['hiddenuntil'] = 'Ocultos hasta';
$string['hiddenuntildate'] = 'Ocultos hasta: $a';
$string['hideadvanced'] = 'Ocultar características avanzadas';
$string['hideaverages'] = 'Ocultar promedios';
$string['hidecalculations'] = 'Ocultar cálculos';
$string['hidecategory'] = 'Ocultos';
$string['hideeyecons'] = 'Ocultar iconos mostrar/ocultar';
$string['hidefeedback'] = 'Ocultar retroalimentación';
$string['hidegroups'] = 'Ocultar grupos';
$string['hidelocks'] = 'Ocultar bloqueos';
$string['hidenooutcomes'] = 'Mostrar resultados';
$string['hideranges'] = 'Ocultar rangos';
$string['highgradeascending'] = 'Ordenar por calificación ascendente';
$string['highgradedescending'] = 'Ordenar por calificación descendente';
$string['highgradeletter'] = 'Altas';
$string['idnumbers'] = 'Números id';
$string['import'] = 'Importar';
$string['incompleteincluded'] = 'Incluyendo incompletas';
$string['incorrectcourseid'] = 'La ID del curso es incorrecta';
$string['inherit'] = 'Heredar';
$string['item'] = 'Elemento';
$string['iteminfo'] = 'Info elemento';
$string['iteminfohelp'] = 'Info y notas sobre este elemento.';
$string['itemname'] = 'Nombre del elemento';
$string['items'] = 'Elementos';
$string['itemsedit'] = 'Editar elemento de calificación';
$string['keephigh'] = 'Mantener la más alta';
$string['lettergrade'] = 'Calificación por letra';
$string['lettergradenonnumber'] = 'Calificaciones bajas y/o altas no numéricas para';
$string['letters'] = 'Letras';
$string['lowest'] = 'Más baja';
$string['lowgradeletter'] = 'Baja';
$string['max'] = 'Más alta';
$string['maxgrade'] = 'Calif. máx.';
$string['meanall'] = 'Todas las calificaciones';
$string['meangraded'] = 'Calificaciones no vacías';
$string['meanselection'] = 'Calificaciones seleccionadas para promedios';
$string['median'] = 'Mediana';
$string['min'] = 'Más baja';
$string['mode'] = 'Moda';
$string['multfactor'] = 'Multiplicador';
$string['na'] = 'ND';
$string['negativegrade'] = 'Calificación negativa';
$string['newevent'] = 'Agregar nuevo elemento calificado';
$string['no'] = 'No';
$string['nocategories'] = 'No se han añadido o no se han encontrado las categorías de calificación para este curso';
$string['nocategoryview'] = 'No categoría para ver por';
$string['nogradeitemsinanycategory'] = 'No hay categorías de calificación que incluyan elementos calificados';
$string['nogradeletters'] = 'No se han ajustado las letras de calificación';
$string['nogradeschanged'] = 'No se cambió ninguna calificación';
$string['nogradesreturned'] = 'No se han devuelto calificaciones';
$string['nolettergrade'] = 'No calificación por letra para';
$string['nomode'] = 'NA';
$string['nonnumericweight'] = 'Recibido valor no numérico para';
$string['nonweightedpct'] = '%% no ponderado';
$string['nooutcome'] = 'No resultado';
$string['notteachererror'] = 'Sólo los profesores pueden usar esta opción.';
$string['notvalid'] = 'calificación no válida';
$string['numberofgrades'] = 'Número de calificaciones';
$string['operations'] = 'Operaciones';
$string['outcome'] = 'Resultado';
$string['outcomecategory'] = 'Crear resultados en categoría';
$string['outcomecategorynew'] = 'Nueva categoría';
$string['outcomecreate'] = 'Agregar nuevo resultado';
$string['outcomeidhelp'] = 'Resultado que representa este elemento de calificación.';
$string['outcomeitem'] = 'Elemento de resultado';
$string['outcomeitemsedit'] = 'Editar elemento de resultado';
$string['outcomename'] = 'Nombre del resultado';
$string['outcomereport'] = 'Informe del resultado';
$string['outcomes'] = 'Resultados';
$string['outcomescourse'] = 'Resultados usados en el curso';
$string['pctoftotalgrade'] = '%% de la calificación total';
$string['percent'] = 'Porcentaje';
$string['percentascending'] = 'Clasificar por porcentaje ascendente';
$string['percentdescending'] = 'Ordenar por porcentaje descendente';
$string['percentshort'] = '%%';
$string['points'] = 'puntos';
$string['pointsascending'] = 'Clasificar por puntos ascendente';
$string['pointsdescending'] = 'Clasificar por puntos descendente';
$string['preferences'] = 'Preferencias';
$string['rawpct'] = '%% bruto';
$string['reprintheaders'] = 'Reimprimir cabeceras';
$string['resetgradepreferences'] = '¿Está seguro de que desea reiniciar todas las preferencias de calificación para $a? <br /><br />Se perderán todos los ajustes (e. g., ponderación, categorías, descartar la más baja, curvado, etc.).';
$string['respectingcurrentdata'] = 'la configuración actual queda sin modificar';
$string['reverttolastsave'] = 'Descartar cambios';
$string['savechanges'] = 'Guardar cambios';
$string['savegradechanges'] = 'Guardar cambios de calificación';
$string['savegradeserror'] = 'Se han encontrado $a problema(s) al intentar guardar las calificaciones. Por favor, revise más abajo';
$string['savegradesinfo'] = '<br>Las calificaciones editables se muestran en verde. Haga clic en Guardar cambios de calificación para ver los resultados en los cambios que ha hecho en las calificaciones de los estudiantes.';
$string['savegradessuccess'] = '$a calificación(es) se han guardado con éxito';
$string['savepreferences'] = 'Guardar preferencias';
$string['scaledpct'] = 'Escalado %%';
$string['setcategories'] = 'Categorías';
$string['setcategorieserror'] = 'Debe ajustar las categorías del curso antes de poder asignarles ponderaciones.';
$string['setgradeletters'] = 'Calificar con letra';
$string['setpreferences'] = 'Preferencias';
$string['setting'] = 'Ajuste';
$string['settings'] = 'Ajustes';
$string['setweights'] = 'Pesos';
$string['showallstudents'] = 'Mostrar a todos los estudiantes';
$string['showhiddenitems'] = 'Mostrar elementos ocultos';
$string['sort'] = 'ordenar';
$string['sortbyfirstname'] = 'Ordenar por nombre';
$string['sortbylastname'] = 'Ordenar por apellido';
$string['standarddeviation'] = 'Desviación típica';
$string['stats'] = 'Estadísticas';
$string['statslink'] = 'Estadísticas';
$string['student'] = 'Estudiante';
$string['total'] = 'Total';
$string['totalweight100'] = 'El peso total es igual a 100';
$string['totalweightnot100'] = 'El peso total no es igual a 100';
$string['uncategorised'] = 'Sin categorizar';
$string['useadvanced'] = 'Usar características avanzadas';
$string['usepercent'] = 'Usar porcentaje';
$string['useweighted'] = 'Usar ponderación';
$string['viewbygroup'] = 'Grupo';
$string['viewgrades'] = 'Ver calificaciones';
$string['weight'] = 'Peso';
$string['weightedascending'] = 'Clasificar por porcentaje ponderado ascendente';
$string['weighteddescending'] = 'Clasificar por porcentaje ponderado descendente';
$string['weightedpct'] = '%% ponderado';
$string['weightedpctcontribution'] = 'contribución %% ponderado';
$string['writinggradebookinfo'] = 'Escribiendo ajustes del libro de calificaciones';
$string['yes'] = 'Sí';
$string['yourchangesweresaved'] = 'Sus cambios se han guardado';
$string['yourgrade'] = 'Su calificación';
$string['badgrade'] = 'La calificación suministrada no es válida'; // ORPHANED
$string['baduser'] = 'El usuario suministrado no es válido'; // ORPHANED
$string['categoriesedit'] = 'Editar Categorías'; // ORPHANED
$string['categoryname'] = 'Nombre de la categoría'; // ORPHANED
$string['createcategory'] = 'Crear categoría'; // ORPHANED
$string['createcategoryerror'] = 'No se ha podido crear una categoría nueva'; // ORPHANED
$string['encoding'] = 'Codificación'; // ORPHANED
$string['exportods'] = 'Exportar ODS'; // ORPHANED
$string['exporttxt'] = 'Exportar TXT'; // ORPHANED
$string['exportxml'] = 'Exportar XML'; // ORPHANED
$string['forelementtypes'] = 'para el $a seleccionado'; // ORPHANED
$string['gradeitemlocked'] = 'Calificación bloqueada'; // ORPHANED
$string['gradeitemsinc'] = 'Elementos de calificación a incluir'; // ORPHANED
$string['gradepreferences'] = 'Preferencias de Calificación'; // ORPHANED
$string['gradereports'] = 'Informe de calificaciones'; // ORPHANED
$string['graderreport'] = 'Informe del calificador'; // ORPHANED
$string['identifier'] = 'Identificar al usuario por'; // ORPHANED
$string['importcsv'] = 'Importar CSV'; // ORPHANED
$string['importfailed'] = 'Importación fallida'; // ORPHANED
$string['importfile'] = 'Importar archivo'; // ORPHANED
$string['importpreview'] = 'Vista previa de la importación'; // ORPHANED
$string['importsuccess'] = 'Importación de calificaciones exitosa'; // ORPHANED
$string['importxml'] = 'Importar XML'; // ORPHANED
$string['lock'] = 'Bloquear'; // ORPHANED
$string['mapfrom'] = 'Mapa desde'; // ORPHANED
$string['mappings'] = 'Mapeos de elementos de calificación'; // ORPHANED
$string['mapto'] = 'Mapa a'; // ORPHANED
$string['movingelement'] = 'Moviendo $a'; // ORPHANED
$string['newcategory'] = 'Categoría nueva'; // ORPHANED
$string['nocategoryname'] = 'No se ha dado nombre de categoría'; // ORPHANED
$string['noselectedcategories'] = 'no se han seleccionado categorías'; // ORPHANED
$string['noselecteditems'] = 'no se han seleccionado elementos.'; // ORPHANED
$string['rank'] = 'Rango'; // ORPHANED
$string['selectdestination'] = 'Seleccionar destino de $a'; // ORPHANED
$string['separator'] = 'Separador'; // ORPHANED
$string['sepcomma'] = 'Coma'; // ORPHANED
$string['septab'] = 'Tabulador'; // ORPHANED
$string['subcategory'] = 'Categoría normal'; // ORPHANED
$string['topcategory'] = 'Categoría super'; // ORPHANED
$string['unlock'] = 'Desbloquear'; // ORPHANED
$string['uploadgrades'] = 'Subir calificaciones'; // ORPHANED
$string['userreport'] = 'Informe de calificación del usuario'; // ORPHANED

?>
