<?PHP // $Id$ 
      // group.php - created with Moodle 1.8.2+ (2007021520)


$string['addgroupstogrouping'] = 'Agregar grupos al agrupamiento';
$string['addgroupstogroupings'] = 'Agregar/quitar grupos';
$string['adduserstogroup'] = 'Agregar usuarios al grupo';
$string['allocateby'] = 'Asignar miembros';
$string['anygrouping'] = '[Cualquier agrupamiento]';
$string['autocreategroups'] = 'Crear grupos automáticamente';
$string['backtogroupings'] = 'Regresar a agrupamientos';
$string['backtogroups'] = 'Regresar a los grupos';
$string['badnamingscheme'] = 'Debe contener exactamente un carácter \'@\' o \'#\'';
$string['createautomaticgrouping'] = 'Crear agrupamiento automático';
$string['creategroup'] = 'Crear grupo';
$string['creategrouping'] = 'Crear agrupamiento';
$string['creategroupinselectedgrouping'] = 'Crear grupo en agrupamiento seleccionado';
$string['createorphangroup'] = 'Crear un grupo huérfano';
$string['databaseupgradegroups'] = 'La versión de grupos es ahora $a';
$string['defaultgroupdescription'] = 'Descripción por defecto del grupo';
$string['defaultgrouping'] = 'Agrupamiento por defecto';
$string['defaultgroupingname'] = 'Agrupamiento';
$string['defaultgroupname'] = 'Grupo';
$string['defaultgroupprefix'] = 'Grupo';
$string['deletegroupconfirm'] = '¿Está seguro de que desea eliminar el grupo \'$a\'?';
$string['deletegrouping'] = 'Eliminar agrupamiento';
$string['deletegroupingconfirm'] = '¿Está seguro de que desea eliminar el conjunto \'$a\'? (Los grupos no se eliminarán).';
$string['deleteselectedgroup'] = 'Eliminar grupo seleccionado';
$string['displaygrouping'] = 'Mostrar agrupamiento';
$string['distributealphabetically'] = 'Distribuir en grupos alfabéticamente por apellido';
$string['distributeevenly'] = 'Distribuir equitativamente a los estudiantes sobrantes';
$string['editgroupingsettings'] = 'Editar ajustes de agrupamiento';
$string['editgroupsettings'] = 'Editar ajustes de grupo';
$string['enrolmentkey'] = 'Clave de matriculación';
$string['erroraddremoveuser'] = 'Error al agregar/quitar al usuario $a del grupo';
$string['erroreditgroup'] = 'Error al crear o actualizar el grupo $a';
$string['erroreditgrouping'] = 'Error al crear o actualizar el agrupamiento $a';
$string['errorinvalidgroup'] = 'Error, grupo $a no válido';
$string['existingmembers'] = 'Miembros existentes: $a';
$string['filtergroups'] = 'Filtrar grupos por:';
$string['firstname'] = 'alfabéticamente por nombre';
$string['group'] = 'Grupo';
$string['groupaddedsuccesfully'] = 'Grupo $a agregado con éxito';
$string['groupby'] = 'Crear grupos basados en el número de';
$string['groupdescription'] = 'Descripción del grupo';
$string['groupinfo'] = 'Información sobre el grupo seleccionado';
$string['groupinfomembers'] = 'Información sobre los miembros seleccionados';
$string['groupinfopeople'] = 'Información sobre las personas seleccionadas';
$string['grouping'] = 'Agrupamiento';
$string['groupingdescription'] = 'Descripción del agrupamiento';
$string['groupingname'] = 'Nombre del agrupamiento';
$string['groupingnameexists'] = 'El nombre de agrupamiento $a ya existe en este curso. Por favor, elija otro.';
$string['groupings'] = 'Agrupamientos';
$string['groupmember'] = 'Miembro del Grupo';
$string['groupmemberdesc'] = 'Rol estándar de un miembro de grupo.';
$string['groupmembers'] = 'Miembros del grupo';
$string['groupmembersonly'] = 'Sólo disponible para miembros de grupo';
$string['groupmembersonlyerror'] = 'Lo sentimos, debe ser miembro de al menos un grupo que sea usado en esta actividad.';
$string['groupmemberssee'] = 'Ver los integrantes del grupo';
$string['groupmembersselected'] = 'Miembros del grupo seleccionado';
$string['groupmode'] = 'Modo de grupo';
$string['groupmodeforce'] = 'Forzar el modo de grupo';
$string['groupmy'] = 'Mi grupo';
$string['groupname'] = 'Nombre del grupo';
$string['groupnameexists'] = 'El nombre de grupo \'$a\' ya existe en este curso; por favor, elija otro.';
$string['groupnotamember'] = 'Lo sentimos, usted no es miembro de ese grupo';
$string['groups'] = 'Grupos';
$string['groupsinselectedgrouping'] = 'Grupos en el agrupamiento seleccionado';
$string['groupsnone'] = 'No hay grupos';
$string['groupspreview'] = 'Visualización previa de grupos';
$string['groupsseparate'] = 'Grupos separados';
$string['groupsvisible'] = 'Grupos visibles';
$string['hidepicture'] = 'Ocultar imagen';
$string['javascriptrequired'] = 'Esta página requiere que Javascript esté activado.';
$string['lastname'] = 'alfabéticamente por apellido';
$string['members'] = 'Miembros por grupo';
$string['membersofselectedgroup'] = 'Miembros del grupo seleccionado';
$string['namingscheme'] = 'Esquema de denominación';
$string['namingschemehelp'] = 'nota: Usar \'@\' para representar la letra del grupo o \'#\' para representar el número del grupo';
$string['newpicture'] = 'Nueva imagen';
$string['nogroups'] = 'Aún no se han formado grupos en este curso';
$string['nogroupsassigned'] = 'No hay grupos asignados';
$string['nopermissionforcreation'] = 'No se puede crear el grupo $a: usted no dispone de los permisos requeridos';
$string['notingrouping'] = '[Fuera de un agrupamiento]';
$string['nousersinrole'] = 'No existen usuarios disponibles en el rol seleccionado';
$string['number'] = 'Número de grupos o miembros por grupo';
$string['numberofgroups'] = 'Número de grupos';
$string['numberofstudents'] = 'Número de estudiantes';
$string['overview'] = 'Visión general';
$string['potentialmembers'] = 'Miembros potenciales: $a';
$string['prefixforgroupnames'] = 'Prefijo de los nombres del grupo';
$string['printerfriendly'] = 'Mostrar agrupamiento en formato para imprimir';
$string['random'] = 'al azar';
$string['removegroupfromselectedgrouping'] = 'Eliminar grupo del agrupamiento seleccionado';
$string['removeselectedusers'] = 'Eliminar usuarios seleccionados';
$string['selectfromrole'] = 'Rol para seleccionar los miembros';
$string['selectnumberineachgroup'] = 'Seleccionar número en cada grupo';
$string['selectnumberofgroups'] = 'Seleccionar número de grupos';
$string['showgroupsingrouping'] = 'Mostrar grupos del conjunto';
$string['showmembersforgroup'] = 'Mostrar miembros del grupo';
$string['toomanygroups'] = 'Usuarios insuficientes para formar este número de grupos (sólo hay $a usuarios en el rol seleccionado).';
$string['usergroupmembership'] = 'Afiliación del usuario seleccionado:';
$string['usestudentsonlyfromselectedgroup'] = 'Usar sólo estudiantes del grupo actualmente seleccionado';
$string['cancel'] = 'Cancelar'; // ORPHANED
$string['editgroupingpermissions'] = 'Editar permisos de agrupamiento'; // ORPHANED
$string['errorinvalidgrouping'] = 'Error, agrupamiento $a no válido'; // ORPHANED
$string['errornotingrouping'] = 'Lo sentimos, no puede crear un grupo en $a'; // ORPHANED
$string['errornotingroupingedit'] = 'Lo sentimos, no puede editar el agrupamiento $a'; // ORPHANED
$string['groupfor'] = 'para el grupo'; // ORPHANED
$string['return'] = 'Volver'; // ORPHANED
$string['save'] = 'Guardar'; // ORPHANED
$string['showusersalreadyingroup'] = 'Mostrar usuarios que ya están en un grupo en el agrupamiento'; // ORPHANED
$string['teachersgroupmark'] = 'Los profesores no pueden asignar actividades a los grupos a los que no pertenecen'; // ORPHANED
$string['teachersgroupview'] = 'Los profesores no pueden ver las actividades de los grupos a los que no pertenecen'; // ORPHANED
$string['teachersoverride'] = 'Los profesores que no pertenecen a ningún grupo pueden ver y asignar actividades a todos los grupos (anula lo anterior)'; // ORPHANED
$string['upgradeconfirm'] = 'Lo sentimos, las tablas de grupos creadas en Moodle 1.8 dev deben ser eliminadas para realizar esta actualización. ¿Desea continuar?'; // ORPHANED
$string['viewallgroupsactivities'] = 'Los estudiantes pueden ver, pero no contribuir a las actividades de todos los grupos'; // ORPHANED
$string['viewallgroupsmembers'] = 'Los estudiantes pueden ver a los miembros de todos los grupos'; // ORPHANED
$string['viewowngroup'] = 'Los estudiantes pueden ver a los miembros de cualesquiera grupos a los que pertenecen'; // ORPHANED

?>
