<?PHP // $Id$ 
      // moodle.php - created with Moodle 1.8 + (2007021505)


$string['action'] = 'Акција';
$string['actions'] = 'Акции';
$string['active'] = 'Активен';
$string['activeusers'] = 'Активни корисници';
$string['activities'] = 'Активности';
$string['activity'] = 'Активност';
$string['activityclipboard'] = 'Преместување на оваа активност: <b>$a</b>';
$string['activityiscurrentlyhidden'] = 'Жалам, но оваа активност е моментално скриена';
$string['activitymodule'] = 'Модул на активноста';
$string['activityreport'] = 'Извештај за активноста';
$string['activityreports'] = 'Извештаи за активностите';
$string['activityselect'] = 'Одберете ја активноста за да се премести на друго место';
$string['activitysince'] = 'Активности од: $a';
$string['activityweighted'] = 'Активности по корисник';
$string['add'] = 'Додадете';
$string['addactivity'] = 'Додадете активност ...';
$string['addadmin'] = 'Додадете администрaтор ...';
$string['addcreator'] = 'Додадете создавач на курсеви';
$string['added'] = 'Додаден(а) $a';
$string['addedrecip'] = 'Додаден $a нов примател';
$string['addedrecips'] = 'Додадени $a нови приматели';
$string['addedtogroup'] = 'Додаден(а) на групата $a';
$string['addedtogroupnot'] = 'Не е додаден(а) на групата $a';
$string['addedtogroupnotenrolled'] = 'Не е додаден(а) на групата $a, бидејќи не е запишан(а) на курсот';
$string['addinganew'] = 'Додавање на нов(а) $a';
$string['addinganewto'] = 'Додавање на нов(а) $a->what да $a->to';
$string['addingdatatoexisting'] = 'Додавање податоци за постоечки(а)';
$string['addnewcategory'] = 'Додадете нова категорија';
$string['addnewcourse'] = 'Додадете нов курс';
$string['addnewuser'] = 'Додадете нов корисник';
$string['addnousersrecip'] = 'Додадете ги корисниците кои не пристапиле до ова $a во листата на приматели';
$string['addresource'] = 'Додадете ресурс ...';
$string['address'] = 'Адреса';
$string['addstudent'] = 'Додадете студент';
$string['addteacher'] = 'Додадете предавач';
$string['admin'] = 'Администратор';
$string['adminbookmarks'] = 'Обележувачи на администраторот';
$string['adminhelpaddnewuser'] = 'За рачно создавање нова сметка';
$string['adminhelpassignadmins'] = 'Администраторите може да одат секаде и да прават сè';
$string['adminhelpassigncreators'] = 'Создавачите може да создаваат нови курсеви и да предаваат во нив';
$string['adminhelpassignsiteroles'] = 'Применете ги дефинираните улоги на сајтот на наведени корисници';
$string['adminhelpassignstudents'] = 'Одете во курсот и додадете студенти од администраторското мени';
$string['adminhelpassignteachers'] = 'Најдете го курсот и употребете ја иконата за да додадете предавач';
$string['adminhelpauthentication'] = 'Можете да ги користите внатрешните кориснички сметки или надворешни бази на податоци';
$string['adminhelpbackup'] = 'Прилагодете ги автоматизираните резервни копии и нивниот распоред';
$string['adminhelpconfiguration'] = 'Прилагодете го изгледот и работата на сајтот';
$string['adminhelpconfigvariables'] = 'Прилагодете ги променливите кои влијаат на работата на сајтот';
$string['adminhelpcourses'] = 'Дефинирајте ги курсевите и категориите и доделете им луѓе, уредете курсеви кои чекаат';
$string['adminhelpeditorsettings'] = 'Дефинирајте ги основните поставувања за HTML уредувачот';
$string['adminhelpedituser'] = 'Прелистајте ги корисничките сметки и променете некоја од нив';
$string['adminhelpenrolments'] = 'Изберете ги внатрешните или надворешните начини да ги контролирате запишувањата';
$string['adminhelpenvironment'] = 'Проверете како Вашиот сервер стои со сегашните и идни потреби за инсталација';
$string['adminhelpfailurelogs'] = 'Прелистајте ги записниците за неуспешни најавувања';
$string['adminhelphealthcenter'] = 'Автоматско пронаоѓање на проблеми на сајтот';
$string['adminhelplanguage'] = 'За проверување и промена на тековниот јазик';
$string['adminhelplogs'] = 'Прелистајте ги записниците за сите активности на овој сајт';
$string['adminhelpmanageblocks'] = 'Инсталирани блокови и нивни поставувања';
$string['adminhelpmanagedatabase'] = 'Директно пристапи и на базата на податоци (Бидете внимателни!)';
$string['adminhelpmanagefilters'] = 'Одберете текстуални филтри и соодветни поставувања';
$string['adminhelpmanagemodules'] = 'Инсталирани модули и нивни поставувања';
$string['adminhelpmanageroles'] = 'Создадете и дефинирајте улоги кои може да се применат на корисници';
$string['adminhelpmymoodle'] = 'Конфигурирајте го мојот moodle блок за корисници';
$string['adminhelpreports'] = 'Извештаи за нивоата на сајтот';
$string['adminhelpsitefiles'] = 'За објавување на документи или поставување на надворешни резервни копии';
$string['adminhelpsitesettings'] = 'Дефинирајте како изгледа насловната страница';
$string['adminhelpstickyblocks'] = 'Конфигурирајте ги блоковите за лепливите moodle белешки';
$string['adminhelpthemes'] = 'Одберете како да изгледа сајтот (боја, фонт ...)';
$string['adminhelpuploadusers'] = 'Внесете нови кориснички сметки од текстуална датотека';
$string['adminhelpusers'] = 'Дефинирајте ги корисниците и поставете автентикација';
$string['adminhelpxmldbeditor'] = 'Интерфејс за уредување на XMLDB датотеки. Само за развивачи.';
$string['administration'] = 'Администрација';
$string['administrationsite'] = 'Администрација на сајт';
$string['administrator'] = 'Администратор';
$string['administratordescription'] = 'Администраторите најчесто можат да прават сè на сајтот, во сите курсови.';
$string['administrators'] = 'Администратори';
$string['administratorsall'] = 'Сите администратори';
$string['administratorsandteachers'] = 'Администратори и предавачи';
$string['adminprimarynoedit'] = 'Не можете да ја промените лозинката на главниот администратор';
$string['advanced'] = 'Напредно';
$string['advancedfilter'] = 'Напредно пребарување';
$string['advancedsettings'] = 'Напредни поставувања';
$string['again'] = 'повторно';
$string['aimid'] = 'AIM ид.';
$string['ajaxno'] = 'Не: користи основни веб карактеристики';
$string['ajaxuse'] = 'AJAX и Javascript';
$string['ajaxyes'] = 'Да: користи напредни веб карактеристики';
$string['all'] = 'Сите';
$string['allactions'] = 'Сите акции';
$string['allactivities'] = 'Сите активности';
$string['allchanges'] = 'Сите промени';
$string['alldays'] = 'Сите денови';
$string['allfieldsrequired'] = 'Сите полиња се неопходни';
$string['allfiles'] = 'Сите датотеки';
$string['allgroups'] = 'Сите групи';
$string['alllogs'] = 'Сите записници';
$string['allow'] = 'Дозволи';
$string['allowguests'] = 'Овој курс дозволува гости';
$string['allowinternal'] = 'Овозможете ги и внатрешните методи';
$string['allownone'] = 'Не дозволувај ништо';
$string['allownot'] = 'Не дозволувај';
$string['allparticipants'] = 'Сите учесници';
$string['allteachers'] = 'Сите предавачи';
$string['alphabet'] = 'А,Б,В,Г,Д,Ѓ,Е,Ж,З,Ѕ,И,Ј,К,Л,Љ,М,Н,Њ,О,П,Р,С,Т,Ќ,У,Ф,Х,Ц,Ч,Џ,Ш';
$string['alphanumerical'] = 'Може да содржи само алфа-нумерички знаци';
$string['alreadyconfirmed'] = 'Регистрацијата веќе е потврдена';
$string['always'] = 'Секогаш';
$string['and'] = '$a->one и $a->two';
$string['answer'] = 'Одговор';
$string['approve'] = 'Дозволи';
$string['areyousuretorestorethis'] = 'Сакате ли да продолжите?';
$string['areyousuretorestorethisinfo'] = 'Подоцна во овој процес ќе имате можност да ја додадете резервната копија кон постоечки курс или да создадете нов курс';
$string['asc'] = 'Растечки редослед';
$string['assessment'] = 'Одредување';
$string['assignadmins'] = 'Одреди администратори';
$string['assigncreators'] = 'Одреди создавачи';
$string['assignsiteroles'] = 'Одреди улоги за целиот сајт';
$string['assignstudents'] = 'Запиши студенти';
$string['assignstudentsnote'] = 'Забелешка: Не е неопходно да ја користите оваа страница, бидејќи студентите можат сами да се запишуваат';
$string['assignstudentspass'] = 'Сè што треба да направите е да ги известите студентите за клучот за запишување на овој курс, кој моментално е поставен на: \'$a\'';
$string['assignteachers'] = 'Одредете предавачи';
$string['authenticateduser'] = 'Автентициран корисник';
$string['authenticateduserdescription'] = 'Сите најавени корисници';
$string['authentication'] = 'Автентикација';
$string['authenticationplugins'] = 'Додатоци за автентикација';
$string['autosubscribe'] = 'Автоматско пријавување на форумот';
$string['autosubscribeno'] = 'Не: Не ме пријавувај автоматски на форумот';
$string['autosubscribeyes'] = 'Да: Кога ќе пратам порака на форумот, запиши ме на тој форум';
$string['availability'] = 'Достапност';
$string['availablecourses'] = 'Достапни курсеви';
$string['backtoparticipants'] = 'Назад во листата со учесници';
$string['backup'] = 'Резервна копија';
$string['backupactivehelp'] = 'Одбери дали да се прават автоматски резервни копии.';
$string['backupcancelled'] = 'Резервната копија е откажана';
$string['backupcoursefileshelp'] = 'Ако е поставено, тогаш датотеките од курсот ќе се вклучат при автоматското правење на резервни копии';
$string['backupdate'] = 'Датум на резервната копија';
$string['backupdatenew'] = '&nbsp; $a->TAG сега е $a->weekday, $a->mday $a->month $a->year<br />';
$string['backupdateold'] = '$a->TAG беше $a->weekday, $a->mday $a->month $a->year';
$string['backupdaterecordtype'] = '<br />$a->recordtype - $a->recordname<br />';
$string['backupdetails'] = 'Детали за резервната копија';
$string['backupexecuteathelp'] = 'Одберете во кое време треба да се прават автоматските резервни копии.';
$string['backupfailed'] = 'Некои од курсевите не се зачувани!';
$string['backupfilename'] = 'Резервна копија';
$string['backupfinished'] = 'Правењето резервна копија е успешно';
$string['backupincludemoduleshelp'] = 'Модулот за курсот да го вклучам со или без корисничките податоци во резервната копија?';
$string['backupincludemoduleuserdatahelp'] = 'Одберете дали да се вклучуваат корисничките податоци во автоматските резервни копии.';
$string['backupkeephelp'] = 'Колку резервни копии од курсот сакате да чувате? (постарите автоматски ќе се бришат)';
$string['backuplogdetailed'] = 'Детален записник за извршувањето';
$string['backuploglaststatus'] = 'Записник за последното извршување';
$string['backuplogshelp'] = 'Ако е поставено, тогаш записниците ќе се вклучат во резервната копија';
$string['backupmetacoursehelp'] = 'Ако е поставено, тогаш информациите за метакурсот ќе се вклучат во резервната копија.';
$string['backupnameformat'] = '%%Y%%m%%d-%%H%%M';
$string['backupnoneusersinfo'] = 'Забелешка: Во резервната копија не е вклучен ниту еден корисник, па сите модули се префрлени на режим за „без кориснички податоци“. Модулите за вежби и работилници не се компатибилни со овој тип на резервни копии, па се целосно исклучени.';
$string['backupnonisowarning'] = 'Внимание: оваа резервна копија е од не-уникод верзија на Moodle (пред 1.6). Ако резервната копија содржи било какви текстови кои не се ISO-8859-1, тогаш тие може да се РАСИПАНИ ако се обидите да ги вратите во уникод верзија на Moodle. Видете на <a href=\"http://docs.moodle.org/en/Backup_FAQ\">ЧПП за резервни копии</a> за повеќе информации за како правилно да вратите податоци од оваа резервна копија.';
$string['backuporiginalname'] = 'Име на резервната копија';
$string['backupsavetohelp'] = 'Патека до директориумот<br />(оставете го полето празно за да се зачува во предефинираната патека)';
$string['backupschedulehelp'] = 'Одберете во кои денови од неделата да се прават автоматски резервни копии.';
$string['backuptakealook'] = 'Погледнете во записниците за резервната копија во:
$a';
$string['backupuserfileshelp'] = 'Дали корисничките датотеки (на пример профилот) да се зачува во резервната копија?';
$string['backupusershelp'] = 'Сакате да ги вклучите сите корисници или само неопходните за секој курс?';
$string['backupversion'] = 'Верзија на резервната копија';
$string['block'] = 'Блок';
$string['blockconfiga'] = 'Прилагодување на $a блок';
$string['blockconfigbad'] = 'Овој блок не е имплементиран како што треба, па не може да овозможи интерфејс за конфигурирање.';
$string['blockdeleteconfirm'] = 'Блокот ќе биде избришан \'$a\'.  Сигурни ли сте дека го сакате тоа?';
$string['blockdeletefiles'] = 'Сите податоци поврзани со блокот \'$a->block\' се избришани од базата на податоци. За да го комплетирате бришењето (и да спречите блокот да се преинсталира самиот) треба да ги избришете податоците од директориумот: $a->directory';
$string['blocks'] = 'Блокови';
$string['blocksaddedit'] = 'Додавање/уредување на блокови';
$string['blockseditoff'] = 'Уредувањето на блоковите е исклучено';
$string['blocksediton'] = 'Уредувањето на блоковите е вклучено';
$string['blocksetup'] = 'Поставувања на табелите за блоковите';
$string['blocksuccess'] = '$a табели се поставени успешно';
$string['bycourseorder'] = 'По нарачка на курсот';
$string['byname'] = 'Од $a';
$string['bypassed'] = 'Заобиколено';
$string['cachecontrols'] = 'Контроли за кеш';
$string['cancel'] = 'Откажи';
$string['cancelled'] = 'Откажано';
$string['categories'] = 'Категории на курсот';
$string['category'] = 'Категорија';
$string['categoryadded'] = 'Категоријата \'$a\' е додадена';
$string['categorydeleted'] = 'Категоријата \'$a\' е избришана';
$string['categoryduplicate'] = 'Категорија со име \'$a\' веќе постои!';
$string['changedpassword'] = 'Променета лозинка';
$string['changepassword'] = 'Промени лозинка';
$string['changessaved'] = 'Промените се зачувани';
$string['check'] = 'Избери';
$string['checkall'] = 'Избери сѐ';
$string['checkingbackup'] = 'Проверувам резервна копија';
$string['checkingcourse'] = 'Проверувам курс';
$string['checkingforbbexport'] = 'Проверувам за експорт на BlackBoard';
$string['checkinginstances'] = 'Проверувам инстанци';
$string['checkingsections'] = 'Проверувам секции';
$string['checklanguage'] = 'Проверувам јазик';
$string['checknone'] = 'Не избирај ништо';
$string['childcoursenotfound'] = 'Дете курсот не е пронајден!';
$string['childcourses'] = 'Дете курс';
$string['choose'] = 'Одберете';
$string['chooseauthmethod'] = 'Одберете додаток за автентикација';
$string['choosecourse'] = 'Одберете курс';
$string['chooseenrolmethod'] = 'Одберете додаток за запишување';
$string['chooselivelogs'] = 'Или гледај ги тековните активности';
$string['chooselogs'] = 'Одберете кои записници сакате да ги видите';
$string['choosereportfilter'] = 'Одберете филтер за извештајот';
$string['choosetheme'] = 'Одберете тема';
$string['chooseuser'] = 'Одберете корисник';
$string['city'] = 'Град';
$string['clambroken'] = 'Администраторот вклучил антивирус за датотеките што се качуваат, но има грешка <br />Качувањето на датотеката НЕ Е УСПЕШНО. Администраторот ќе биде известен<br />Пробајте да ја качите датотеката подоцна.';
$string['clamdeletedfile'] = 'Датотеката е избришана';
$string['clamdeletedfilefailed'] = 'Датотеката не може да се избрише';
$string['clamemailsubject'] = '$a :: Clam AV известување';
$string['clamfailed'] = 'Clam AV не може да се изврши. Пораката што ја врати е $a. Еве го излезот од Clam:';
$string['clamlost'] = 'Moodle е конфигуриран да употреби clam при качување на датотеки, но патеката добиена од Clam AV, $a, не е валидна.';
$string['clamlostandactinglikevirus'] = 'Moodle е конфигуриран така да, ако clam не може да се изврши, датотеките се третираат како вируси. Ова значи пред сè, дека ниту еден студент не може успешно да качи датотека се додека не го поправите ова.';
$string['clammovedfile'] = 'Датотеката е ставена во карантин, новата локација е $a';
$string['clammovedfilebasic'] = 'Датотеката е поставена во карантин.';
$string['clamquarantinedirfailed'] = 'Не можам да ја ставам датотеката во локацијата за карантин, $a. Поправете го ова, бидејќи датотеките се бришат доколку се заразени.';
$string['clamunknownerror'] = 'Имаше непозната грешка со clam.';
$string['cleaningtempdata'] = 'Чистење на привремените податоци';
$string['clicktochange'] = 'Кликнете за промена';
$string['closewindow'] = 'Затвори го прозорецот';
$string['comparelanguage'] = 'Спореди го и уреди го тековниот јазик';
$string['complete'] = 'Комплетен';
$string['completereport'] = 'Комплетен извештај';
$string['configuration'] = 'Конфигурација';
$string['confirm'] = 'Потврди';
$string['confirmed'] = 'Регистрацијата е потврдена';
$string['confirmednot'] = 'Регистрацијата сè уште не е потврдена!';
$string['continue'] = 'Продолжи';
$string['continuetocourse'] = 'Кликнете овде за да го додадете курсот';
$string['convertingwikitomarkdown'] = 'Конвертирам Wiki во Markdown';
$string['cookiesenabled'] = 'Колачињата мораат да бидат овозможени во Вашиот прелистувач';
$string['cookiesnotenabled'] = 'Колачињата не се овозможени во Вашиот прелистувач';
$string['copy'] = 'копирај';
$string['copyasnoun'] = 'копија';
$string['copyingcoursefiles'] = 'Копирам датотеки за курсот';
$string['copyinguserfiles'] = 'Копирам кориснички датотеки';
$string['copyingzipfile'] = 'Копирам zip датотека';
$string['copyrightnotice'] = 'Забелешка за авторски права';
$string['coresystem'] = 'Јадро на систем';
$string['cost'] = 'Цена';
$string['costdefault'] = 'Предефинирана цена';
$string['counteditems'] = '$a->count $a->items';
$string['country'] = 'Држава';
$string['course'] = 'Курс';
$string['courseapprovedemail'] = 'Вашиот побаран курс, $a->name, беше одобрен и Вие сте направени $a->teacher. За да пристапите до Вашиот нов курс, одете на $a->url';
$string['courseapprovedfailed'] = 'Не успеав да го зачувам курсот како одобрен!';
$string['courseapprovedsubject'] = 'Вашиот курс беше одобрен!';
$string['courseavailable'] = 'Овој курс е достапен за студентите';
$string['courseavailablenot'] = 'Овој курс не е достапен за студентите';
$string['coursebackup'] = 'Резервна копија на курсот';
$string['coursecategories'] = 'Категории на курсот';
$string['coursecategory'] = 'Категорија на курсот';
$string['coursecreators'] = 'Создавачи на курсот';
$string['coursecreatorsdescription'] = 'Креаторите на курсеви можат да креираат нови курсеви и во нив да предаваат.';
$string['coursefiles'] = 'Датотеки за курсот';
$string['courseformatdata'] = 'Формат на податоците на курсот';
$string['courseformats'] = 'Формати на курсот';
$string['coursegrades'] = 'Оценки за курсот';
$string['coursehidden'] = 'Курсот моментално не е достапен за студентите';
$string['courseimportnotaught'] = 'Изгледа дека не сте предавач кој може да уредува во други курсеви, нема курсеви од кои што можете да увезете.';
$string['courseinfo'] = 'Информации за курсот';
$string['coursemessage'] = 'Менаџирајте со корисниците на курсот';
$string['coursenotaccessible'] = 'Овој курс не дозволува јавен пристап';
$string['courseoverview'] = 'Преглед на курсот';
$string['courseoverviewgraph'] = 'Графикон за преглед на курсот';
$string['coursereject'] = 'Одбијте барање за курс';
$string['courserejected'] = 'Курсот беше одбиен и барачот беше известен.';
$string['courserejectemail'] = 'Жалам, но курсот кој го побаравте беше одбиен. Еве ја причината:

$a';
$string['courserejectreason'] = 'Наведете ги причините за одбивањето на овој курс<br />(ова ќе биде испратено по е-пошта до барачот)';
$string['courserejectsubject'] = 'Вашиот курс беше одбиен';
$string['courserequest'] = 'Барање за курс';
$string['courserequestdisabled'] = 'Жалам, но барањето на курсеви е оневозможено од администраторот';
$string['courserequestfailed'] = 'Поради некоја причина, барањето за Вашиот курс не може да се зачува';
$string['courserequestintro'] = 'Користете го овој формулар за да побарате да се креира курс за Вас.<br />Обидете се да пополните што повеќе информации кои што ќе им овозможат на<br />администраторите да ги разберат причините за Вашето барање на курсот.';
$string['courserequestreason'] = 'Причини за барање на овој курс';
$string['courserequestsuccess'] = 'Вашето барање за курс беше успешно зачувано. Очекувајте е-пошта за неколку дена со одговор';
$string['courserestore'] = 'Обнови го курсот';
$string['courses'] = 'Курсеви';
$string['coursescategory'] = 'Курсеви од иста категорија';
$string['coursespending'] = 'Курсеви кои што чекаат одобрување';
$string['coursestaught'] = 'Курсеви што сум ги учел';
$string['courseupdates'] = 'Ажурирање на курсот';
$string['courseuploadlimit'] = 'Лимит за качување за курсот';
$string['create'] = 'Создај';
$string['createaccount'] = 'Создај ја мојата нова корисничка сметка';
$string['createfolder'] = 'Создај директориум во $a';
$string['createuserandpass'] = 'Создај ново корисничко име и лозинка за најавување';
$string['createziparchive'] = 'Создај zip архива';
$string['creatingblocks'] = 'Создавам блокови';
$string['creatingblocksroles'] = 'Создавам назначувања и отфрлања на ниво на блок';
$string['creatingcategoriesandquestions'] = 'Создавам категории и прашања';
$string['creatingcoursemodules'] = 'Создавам модули за курсот';
$string['creatingcourseroles'] = 'Создавам назначувања и отфрлања на ниво на курс';
$string['creatingevents'] = 'Создавам настани';
$string['creatinggradebook'] = 'Создавам дневник за оцени';
$string['creatinggroupings'] = 'Создавам групирања';
$string['creatinggroups'] = 'Создавам групи';
$string['creatinglogentries'] = 'Создавам записи за записниците';
$string['creatingmessagesinfo'] = 'Создавам информации за пораките';
$string['creatingmetacoursedata'] = 'Создавам метакурс информации';
$string['creatingmodroles'] = 'Создавам назначувања и отфрлања на ниво на улога';
$string['creatingnewcourse'] = 'Создавам нов курс';
$string['creatingrolesdefinitions'] = 'Создавам дефиниции за улоги';
$string['creatingscales'] = 'Создавам критериум за оценување';
$string['creatingsections'] = 'Создавам секции';
$string['creatingtemporarystructures'] = 'Создавам привремени структури';
$string['creatinguserroles'] = 'Создавам назначувања и отфрлања на ниво на корисници';
$string['creatingusers'] = 'Создавам корисници';
$string['creatingxmlfile'] = 'Создавам XML датотека';
$string['currency'] = 'Валута';
$string['currentcourseadding'] = 'Тековен курс, додавам податоци на него';
$string['currentcoursedeleting'] = 'Тековен курс, најпрво ќе биде избришан';
$string['currentlanguage'] = 'Тековен јазик';
$string['currentlocaltime'] = 'Ваше тековно локално време';
$string['currentlyselectedusers'] = 'Тековно избрани корисници';
$string['currentpicture'] = 'Тековна слика';
$string['currentrelease'] = 'Тековна информација за оваа верзија на програмата';
$string['currentversion'] = 'Тековна верзија';
$string['databasechecking'] = 'Надградба на базата на податоци од верзија $a->oldversion во $a->newversion...';
$string['databaseperformance'] = 'Перформанси на базата на податоци';
$string['databasesetup'] = 'Поставувања на базата на податоци';
$string['databasesuccess'] = 'Базата е успешно надградена';
$string['databaseupgradebackups'] = 'Верзијата на резервната копија сега е $a';
$string['databaseupgradeblocks'] = 'Верзијата на блокот сега е $a';
$string['databaseupgradegroups'] = 'Верзијата на групата сега е $a';
$string['databaseupgradelocal'] = 'Верзијата на поставувањата на локалната верзија на базата на податоци е $a';
$string['databaseupgrades'] = 'Ја надградувам базата на податоци';
$string['date'] = 'Датум';
$string['datechanged'] = 'Датумот е променет';
$string['datemostrecentfirst'] = 'Датум - прво најновиот';
$string['datemostrecentlast'] = 'Датум - најновиот последен';
$string['day'] = 'ден';
$string['days'] = 'денови';
$string['decodinginternallinks'] = 'Декодирање на внатрешните врски';
$string['default'] = 'Предефинирано';
$string['defaultcoursefullname'] = 'Целосно име на курсот 101';
$string['defaultcourseshortname'] = 'CF101';
$string['defaultcoursestudent'] = 'Студент';
$string['defaultcoursestudentdescription'] = 'Студентите најчесто имаат помалку привилегии во курсот.';
$string['defaultcoursestudents'] = 'Студенти';
$string['defaultcoursesummary'] = 'Создадете концизен и интересен параграф кој објаснува за што е овој курс.';
$string['defaultcourseteacher'] = 'Предавач';
$string['defaultcourseteacherdescription'] = 'Предавачите можат да прават сѐ во еден курс, вклучувајќи промена на активности и оценување на учениците.';
$string['defaultcourseteachers'] = 'Предавачи';
$string['delete'] = 'Избриши';
$string['deleteall'] = 'Избриши сè';
$string['deletecategorycheck'] = 'Дали сигурно сакате да ја избришам категоријата „<b>$a</b>“?<br />Сите курсеви од оваа категорија ќе се префрлат во категорија родител (ако постои) или во „Разно“.';
$string['deletecheck'] = 'Избриши го $a?';
$string['deletecheckfiles'] = 'Дали сигурно сакате да ги избришам датотеките?';
$string['deletecheckfull'] = 'Дали сигурно да ја избришам $a?';
$string['deletecheckwarning'] = 'Датотеките ќе се избришат';
$string['deletecompletely'] = 'Избриши комплетно';
$string['deletecourse'] = 'Избриши курс';
$string['deletecoursecheck'] = 'Дали сигурно да го избришам курсот и целата негова содржина?';
$string['deleted'] = 'Избришано';
$string['deletedactivity'] = 'Избришан(а) $a';
$string['deletedcourse'] = '$a е комплетно избришан(а)';
$string['deletednot'] = 'Не може да се избрише $a!';
$string['deleteselected'] = 'Избриши ги избраните';
$string['deletingcourse'] = 'Бришам $a';
$string['deletingexistingcoursedata'] = 'Бришам постоечки податоци за курсот';
$string['deletingolddata'] = 'Бришам стари податоци';
$string['department'] = 'Отсек';
$string['desc'] = 'Опаѓање';
$string['description'] = 'Објаснување';
$string['deselectall'] = 'Не избирај ништо';
$string['detailedless'] = 'Со малку детали';
$string['detailedmore'] = 'Со повеќе детали';
$string['directorypaths'] = 'Патеки на директориумите';
$string['disable'] = 'Оневозможи';
$string['displayingfirst'] = 'Само првите $a->count $a->things се прикажани';
$string['displayingrecords'] = 'Прикажувам $a записи';
$string['displayingusers'] = 'Прикажувам корисници од $a->start до $a->end';
$string['displayonpage'] = 'Прикажи на страница';
$string['documentation'] = 'Moodle документација';
$string['donotask'] = 'Не прашувај';
$string['down'] = 'Долу';
$string['downloadexcel'] = 'Симни во Excel формат';
$string['downloadods'] = 'Симни во ODS формат';
$string['downloadtext'] = 'Симни во текст формат';
$string['doyouagree'] = 'Дали ги прочитавте условите и дали ги разбравте?';
$string['duplicate'] = 'Дупликат';
$string['duplicatinga'] = 'Дуплирам: $a';
$string['duplicatingain'] = 'Дуплирам $a->what во $a->in';
$string['edhelpaspellpath'] = 'За да користите проверка за спелување, МОРА да имате <strong>aspell 0.50</strong> или понова верзија инсталирана на серверот, и мора да зададете точна патека за пристап до aspell binary. На Unix/Linux системите, оваа патека обично е <strong>/usr/bin/aspell</strong>, но може да биде и поинаква.';
$string['edhelpbgcolor'] = 'Изберете боја на позадината за уредување.<br />Валидни вредности се на пример: #FFFFFF или white';
$string['edhelpcleanword'] = 'Овие поставувања ги овозможуваат или оневозможуваат Word специфичните формати за филтрирање.';
$string['edhelpenablespelling'] = 'Овозможи или оневозможи проверка на спелување. Кога е овозможено, <strong>aspell</strong> мора да е инсталиран на серверот. Втората вредност е <strong>типичен речник</strong>. Оваа вредност ќе се користи ако aspell не содржи речник за јазикот на корисникот.';
$string['edhelpfontfamily'] = 'Типот на фонтот е листа од имиња на фонтови и/или фамилија на генерички имиња. Презимињата мора да се одделени со запирка.';
$string['edhelpfontlist'] = 'Дефинирај листа на фонтови користени во паѓачките менија.';
$string['edhelpfontsize'] = 'Типичната големина на фонтот ја одредува големината на фонтот. <br />Валидни вредности се на пример: medium, large, smaller, larger, 10pt, 11px.';
$string['edit'] = 'Уредете $a';
$string['editcoursesettings'] = 'Уредете ги поставувањата на курсот';
$string['editfiles'] = 'Уредете ги датотеките';
$string['editgroupprofile'] = 'Уредете го профилот на групата';
$string['editinga'] = 'Уредете $a';
$string['editingteachershort'] = 'Уредник';
$string['editlock'] = 'Оваа вредност не може да се уредува!';
$string['editmyprofile'] = 'Уредете профил';
$string['editorbgcolor'] = 'Боја на позадина';
$string['editorcleanonpaste'] = 'Исчисти Word HTML при вметнување';
$string['editorcommonsettings'] = 'Заеднички поставувања';
$string['editordefaultfont'] = 'Стандарден фонт';
$string['editorenablespelling'] = 'Овозможи проверка на спелување';
$string['editorfontlist'] = 'Листа на фонтови';
$string['editorfontsize'] = 'Стандардна големина на фонтот';
$string['editorhelptopics'] = 'Наслови за помош во уредувачот.';
$string['editorresettodefaults'] = 'Врати ги основните вредности';
$string['editorsettings'] = 'Поставувања на уредувачот';
$string['editorshortcutkeys'] = 'Копчиња кратенки за уредувачот.';
$string['editsummary'] = 'Уредете го резимето';
$string['editthisactivity'] = 'Уредете ја оваа активност';
$string['editthiscategory'] = 'Уредете ја оваа категорија';
$string['edituser'] = 'Уредете ја корисничката сметка';
$string['email'] = 'Адреса за е-пошта';
$string['emailactive'] = 'Е-поштата е активирана';
$string['emailagain'] = 'Е-пошта (повторно)';
$string['emailcharset'] = 'Множество знаци за е-пошта';
$string['emailconfirm'] = 'Потврдете ја Вашата сметка';
$string['emailconfirmation'] = 'Здраво $a->firstname,

Нова сметка е побарана на „$a->sitename“
користејќи ја оваа адреса.

За да ја потврдите новата сметка, одете на следната адреса:

$a->link

Во повеќето програми за е-пошта, ова би требало да биде напишано со сини букви
врз кои може да кликнете. Ако тоа не функционира, тогаш ископирајте го текстот, и вметнете го во линија за адреса, која се наоѓа на горниот дел од прелистувачот.

Ако Ви треба помош контактирајте го администраторот на сајтот,
$a->admin';
$string['emailconfirmationsubject'] = '$a: потврда за сметка';
$string['emailconfirmsent'] = '<p>Треба да ви е испратена порака на е-пошта на <b>$a</b></p>
   <p>Содржи инструкции за регистрација.</p>
   <p>Ако и понатаму имате проблеми контактирајте го администраторот на сајтот.</p>';
$string['emaildigest'] = 'Тип на известување по е-пошта';
$string['emaildigestcomplete'] = 'Праќајте ми дневна порака на е-пошта, со листа од сите нови записи на форумот';
$string['emaildigestoff'] = 'Праќајте ми по една порака на е-пошта за секој нов запис на форумот';
$string['emaildigestsubjects'] = 'Теми (праќајте ми ги дневно само темите)';
$string['emaildisable'] = 'Оваа адреса за е-пошта е оневозможена';
$string['emaildisableclick'] = 'Кликнете овде за да го оневозможите праќањето на сите пораки на е-пошта за оваа адреса';
$string['emaildisplay'] = 'Прикажување на пораките на е-пошта';
$string['emaildisplaycourse'] = 'Дозволи им на другите членови во курсот да ја гледаат мојата адреса за е-пошта';
$string['emaildisplayno'] = 'Сокриј ја мојата адреса за е-пошта од сите';
$string['emaildisplayyes'] = 'Дозволи им на сите да ја гледаат мојата адреса за е-пошта';
$string['emailenable'] = 'Оваа адреса за е-пошта е овозможена';
$string['emailenableclick'] = 'Кликнете овде за повторно овозможување на сите пораки на е-пошта што биле пратени на оваа адреса';
$string['emailexists'] = 'Оваа адреса за е-пошта веќе е регистрирана.';
$string['emailformat'] = 'Формат на адресата за е-пошта';
$string['emailmustbereal'] = 'Забелешка: Вашата адреса за е-пошта мора да биде вистинска';
$string['emailnotallowed'] = 'Адреси за е-пошта од овој домен не се дозволени ($a)';
$string['emailnotfound'] = 'Адресата за е-пошта не беше пронајдена во базата со податоци';
$string['emailonlyallowed'] = 'Оваа адреса за е-пошта не е од дозволените ($a)';
$string['emailpasswordchangeinfo'] = 'Здраво $a->firstname,

Некој (најверојатно Вие) побара нова лозинка за Вашата сметка на „$a->sitename“.

За да ја промените лозинката, Ве молам, одете на следната веб адреса:

$a->link

Во повеќето програми за е-пошта, ова треба да се покаже како сина врска која што можете да ја кликнете. Ако тоа не работи, тогаш сечете ја и вметнете ја адресата во прозорецот на веб прелистувачот.

Ако Ви треба помош, Ве молам, контактирајте со администраторот на сајтот.
$a->admin';
$string['emailpasswordchangeinfofail'] = 'Здраво $a->firstname,

Некој (најверојатно Вие) побара нова лозинка за Вашата сметка на „$a->sitename“.

За жал, лозинките не можат да се ресетираат на овој сајт, па ве молам да се обратите кај администраторот на системот, $a->admin';
$string['emailpasswordchangeinfosubject'] = '$a: Променете ги информациите за лозинката';
$string['emailpasswordconfirmation'] = 'Здраво $a->firstname,

Некој (најверојатно Вие) побарал промена на лозинката на страницата \'$a->sitename\'.

За да го потврдете ова и да добиете нова лозинка по е-пошта одете на следната адреса:

$a->link

Во повеќето програми за е-пошта, ова би требало да биде напишано со сини букви
врз кои може да кликнете. Ако тоа не функционира,
тогаш ископирајте го текстот и вметнете го во адресната линија, која се наоѓа на горниот дел од прелистувачот.

Ако Ви треба помош, контактирајте го администраторот на сајтот,
$a->admin';
$string['emailpasswordconfirmationsubject'] = '$a: потврда за промена на лозинка';
$string['emailpasswordconfirmmaybesent'] = '<p>Ако наведовте точно корисничко име или адреса, треба да Ви стигни порака на е-пошта.</p>
<p>Таа ќе содржи лесни упатства за да ја потврдите и завршите промената на лозинката. Ако продолжите да имате потешкотии, Ве молам, контактирајте со администраторот на сајтот.</p>';
$string['emailpasswordconfirmsent'] = 'Треба да има пратено пошта на Вашата адреса <b>$a</b>.
<br />Содржи инструкции за промена на лозинката.
Ако и понатаму имате проблеми, контактирајте со администраторот на сајтот.';
$string['emailpasswordsent'] = 'Ви благодариме што ја потврдивте промената на лозинката.
Порака за е-пошта со новата лозинка е испратена на адресата која ја дадовте<br /><b>$a->email</b>.<br />
Новата лозинка е автоматски креирана, можеби ќе сакате
<a href=\"$a->link\">да ја промените</a> во некоја која полесно ќе ја памтите.';
$string['enable'] = 'Овозможи';
$string['encryptedcode'] = 'Енкриптиран код';
$string['enroldate'] = 'Опсег на датум';
$string['enrolenddate'] = 'Краен датум';
$string['enrolenddaterror'] = 'Крајниот датум на пријавувањето не може да е порано од почетниот датум';
$string['enrollable'] = 'Може да се пријавува на курсот';
$string['enrolledincourse'] = 'Запишан во курс „$a“';
$string['enrolledincoursenot'] = 'Незапишан во курс „$a“';
$string['enrollfirst'] = 'Мора да се запишете во еден од курсевите, пред да може да ги користете активностите на сајтот';
$string['enrolme'] = 'Запиши ме во овој курс';
$string['enrolmentconfirmation'] = 'Ќе бидете запишани како член на овој курс.<br />Дали сигурно го сакате ова?';
$string['enrolmentend'] = 'Пријавувањето завршува';
$string['enrolmentkey'] = 'Клуч за запис';
$string['enrolmentkeyfrom'] = 'Овој курс бара \'клуч за запис\' - еднократна<br />
лозинка која би требало да Ви ја даде $a';
$string['enrolmentkeyhint'] = 'Клучот за запис е погрешен, обидете се повторно<br />
(Мала помош ... започнува на буквата \'$a\')';
$string['enrolmentnew'] = 'Нов запис во $a';
$string['enrolmentnewuser'] = '$a->user се запиша во курсот \"$a->course\"';
$string['enrolmentnointernal'] = 'Рачното запишување моментално не е овозможено';
$string['enrolmentnotyet'] = 'Не може да пристапите во курсот се до <br /> $a';
$string['enrolmentplugins'] = 'Додаток за пријавување';
$string['enrolments'] = 'Пријавување';
$string['enrolmentstart'] = 'Пријавувањето започна';
$string['enrolperiod'] = 'Траење на запишувањето';
$string['enrolstartdate'] = 'Почетен датум';
$string['entercourse'] = 'Кликнете овде за да пристапите до овој курс';
$string['enteremailaddress'] = 'Внесете адреса за е-пошта за да извршите промена на лозинката. Лозинката ќе Ви биде пратена по е-пошта.';
$string['entries'] = 'Записи';
$string['error'] = 'Грешка';
$string['errortoomanylogins'] = 'Ги надминавте дозволените обиди за најавување. Рестартирајте го прелистувачот.';
$string['errorwhenconfirming'] = 'Не сте известени затоа што настана грешка.  Ако кликнавте на некоја врска од адресата за е-пошта за да стигнете до овде, тогаш уверете се дека врската е исправна. Обидете се со копирање на врската и нејзино внесување во прелистувачот.';
$string['everybody'] = 'Сите';
$string['executeat'] = 'Изврши на';
$string['existing'] = 'Постоечки';
$string['existingadmins'] = 'Постоечки администратори';
$string['existingcourse'] = 'Постоечки курс';
$string['existingcourseadding'] = 'Додавам податоци кон постоечкиот курс';
$string['existingcoursedeleting'] = 'Постоечки курс, го бришам прво';
$string['existingcreators'] = 'Креатори на постоечкиот курс';
$string['existingstudents'] = 'Запишани студенти';
$string['existingteachers'] = 'Постоечки предавачи';
$string['expirynotify'] = 'Известување за истекувањето на пријавувањето';
$string['expirynotifyemail'] = 'Курсот за следните студенти истекува по точно $a->threshold денови:

$a->current

Следните студенти во овој курс истекуваат за помалку од $a->threshold денови:

$a->past

Можете да одите на следната страница и да го продолжите рокот за пријавуање:
$a->extendurl';
$string['expirynotifystudents'] = 'Извести ги студентите';
$string['expirynotifystudentsemail'] = 'Почитуван $a->studentstr:';
$string['expirythreshold'] = 'Праг';
$string['explanation'] = 'Објаснување';
$string['extendenrol'] = 'Продолжи го членството';
$string['extendperiod'] = 'Продолжен период';
$string['failedloginattempts'] = '$a->attempts неуспешни најавувања од Вашето последно најавување';
$string['failedloginattemptsall'] = '$a->attempts неуспешни најавувања за $a->accounts сметка(и)';
$string['feedback'] = 'Повратна информација';
$string['file'] = 'Датотека';
$string['filemissing'] = '$a недостига';
$string['files'] = 'Датотеки';
$string['filesfolders'] = 'Датотеки/директориуми';
$string['filloutallfields'] = 'Ве молам пополнете ги сите полиња';
$string['findmorecourses'] = 'Најдете повеќе курсеви...';
$string['firstdayofweek'] = '0';
$string['firstname'] = 'Име';
$string['firsttime'] = 'Дали сте прв пат овде?';
$string['folder'] = 'Папка';
$string['folderclosed'] = 'Затворена папка';
$string['folderopened'] = 'Отворена папка';
$string['followingoptional'] = 'Следните точки се произволни';
$string['followingrequired'] = 'Следните точки се потребни';
$string['force'] = 'Присили';
$string['forcedmode'] = 'присилен режим';
$string['forcelanguage'] = 'Присили јазик';
$string['forceno'] = 'Без присила';
$string['forcepasswordchange'] = 'Присилна промена на лозинката';
$string['forcepasswordchangehelp'] = 'Извести го корисникот да ја смени лозинката при следното најавување';
$string['forcepasswordchangenotice'] = 'Морате да ја промените Вашата лозинка за да продолжете.';
$string['forcetheme'] = 'Присили тема';
$string['forgotaccount'] = 'Ја загубивте лозинката?';
$string['forgotten'] = 'Го заборавивте корисничкото име или лозинката?';
$string['forgottenduplicate'] = 'Адресата за е-пошта е споделена со неколку сметки, Ве молам наместо внесете корисничко име';
$string['forgotteninvalidurl'] = 'Неважечко URL за ресетирање на лозинка';
$string['format'] = 'Формат';
$string['formathtml'] = 'HTML формат';
$string['formatlams'] = 'LAMS курс формат';
$string['formatmarkdown'] = 'Markdown формат';
$string['formatplain'] = 'Обичен текст';
$string['formatscorm'] = 'SCORM формат';
$string['formatsocial'] = 'Социјален формат';
$string['formattext'] = 'Moodle авто-формат';
$string['formattexttype'] = 'Форматирам';
$string['formattopics'] = 'Формат на насловот';
$string['formattopicsajax'] = 'Формат на теми - AJAX';
$string['formatweeks'] = 'Неделен формат';
$string['formatweekscss'] = 'Неделен формат - CSS/без табели';
$string['formatwiki'] = 'Формат од тип на Wiki';
$string['framesetinfo'] = 'Овој документ на збир на рамки содржи:';
$string['from'] = 'Од';
$string['frontpagecategorycombo'] = 'Комбинирана листа';
$string['frontpagecategorynames'] = 'Листа на категории';
$string['frontpagecourselist'] = 'Листа на курсеви';
$string['frontpagedescription'] = 'Опис на насловната страница';
$string['frontpagedescriptionhelp'] = 'Овој опис за сајтот ќе биде прикажан на насловната страница.';
$string['frontpageformat'] = 'Формат на насловната страница';
$string['frontpageformatloggedin'] = 'Формат на насловната страница кога сте најавени';
$string['frontpagenews'] = 'Покажи новoсти';
$string['frontpagetopiconly'] = 'Дел за теми';
$string['fulllistofcourses'] = 'Сите курсеви';
$string['fullname'] = 'Цело име';
$string['fullnamedisplay'] = '$a->firstname $a->lastname';
$string['fullprofile'] = 'Цел профил';
$string['fullsitename'] = 'Цело име на сајтот';
$string['functiondisabled'] = 'Таа функционалност е моментно оневозможена';
$string['gd1'] = 'GD 1.x е инсталиран';
$string['gd2'] = 'GD 2.x е инсталиран';
$string['gdneed'] = 'GD мора да е инсталиран за да се види овој графикон';
$string['gdnot'] = 'GD не е инсталиран';
$string['gettheselogs'] = 'Земи ги овие записници';
$string['go'] = 'Оди';
$string['gpl'] = 'Copyright (C) 1999-2005  Martin Dougiamas  (http://moodle.com)

Оваа програма е бесплатна; можете да ја редистрибуирате и/или изменувате
под условите на GNU General Public License како што е објавено од 
Фондацијата за Слободен Софтвер; верзија 2 или некоја понова верзија.

Оваа програма е дистрибуирана со надеж дека ќе биде корисна,
но БЕЗ НИКАКАВИ ПРЕДУПРЕДУВАЊА; За повеќе детали видете ја
GNU General Public License:

http://www.gnu.org/copyleft/gpl.html';
$string['grade'] = 'Оцена';
$string['grades'] = 'Оцени';
$string['group'] = 'Група';
$string['groupadd'] = 'Додадете нова група';
$string['groupaddusers'] = 'Додадете го избраното во група';
$string['groupfor'] = 'за група';
$string['groupinfo'] = 'Информации за избраната група';
$string['groupinfoedit'] = 'Уредете ги прилагодувањата за групата';
$string['groupinfomembers'] = 'Информации за избраните членови';
$string['groupinfopeople'] = 'Информации за избраните луѓе';
$string['groupmembers'] = 'Членови на групата';
$string['groupmemberssee'] = 'Видете ги членовите на групата';
$string['groupmembersselected'] = 'Членови на избраната група';
$string['groupmode'] = 'Режим на група';
$string['groupmodeforce'] = 'Присили го режимот на група';
$string['groupmy'] = 'Моја група';
$string['groupnonmembers'] = 'Луѓе кои не се во групата';
$string['groupnotamember'] = 'Извинете, но вие не сте член на групата';
$string['grouprandomassign'] = 'Задади ги сите во групи по случаен избор';
$string['groupremove'] = 'Одстрани ја избраната група';
$string['groupremovemembers'] = 'Одстрани ги избраните членови';
$string['groups'] = 'Групи';
$string['groupsnone'] = 'Нема групи';
$string['groupsseparate'] = 'Оддели групи';
$string['groupsvisible'] = 'Видливи групи';
$string['guest'] = 'Гостин';
$string['guestdescription'] = 'Гостите имаат минимални привилегии и најчесто не можат да внесуваат текст било каде.';
$string['guestskey'] = 'Пушти ги гостите кои имаат клуч';
$string['guestsno'] = 'Не дозволувај им влез на гостите';
$string['guestsnotallowed'] = 'Извинете, \'$a\' не дозволува гостите да влезат.';
$string['guestsyes'] = 'Дозволи гости без клучот';
$string['guestuser'] = 'Корисник „гостин“';
$string['guestuserinfo'] = 'Овој корисник е специјален, тоа дозволува само читање на некои датотеки.';
$string['healthcenter'] = 'Состојба на системот';
$string['healthproblemsdetected'] = 'Откриени се проблеми во системот!';
$string['healthproblemsolution'] = 'Решение за проблемите на системот';
$string['healthreturntomain'] = 'Продолжи';
$string['healthsolution'] = 'Решение';
$string['help'] = 'Помош';
$string['helpemoticons'] = 'Користи емоции (симболи за емоции)';
$string['helpformatting'] = 'За форматирање на текст';
$string['helphtml'] = 'Како да пишувате html';
$string['helpindex'] = 'Индекс на сите датотеки за помош';
$string['helppicture'] = 'Како да поставите слика';
$string['helpprefix'] = 'Помош, $a';
$string['helpprefix2'] = 'Помош околу $a';
$string['helpquestions'] = 'Поставете добри прашања';
$string['helpreading'] = 'Читајте внимателно';
$string['helprichtext'] = 'За HTML уредувачот';
$string['helpsummaries'] = 'За овие резимеа';
$string['helptext'] = 'Како да пишувате текст';
$string['helpwiki'] = 'Како да пишувате текст од тип на Wiki';
$string['helpwiththis'] = 'Поможете со ова';
$string['helpwriting'] = 'Пишувајте внимателно';
$string['hiddenassign'] = 'Скриена задача';
$string['hiddensections'] = 'Скриени секции';
$string['hiddensectionscollapsed'] = 'Скриените секции се покажани во собрана форма';
$string['hiddensectionsinvisible'] = 'Скриените секции се потполно невидливи';
$string['hide'] = 'Сокриј';
$string['hideadvancedsettings'] = 'Сокриј ги напредните поставувања';
$string['hidepicture'] = 'Сокриј ја сликата';
$string['hidesettings'] = 'Сокриј ги поставувањата';
$string['hits'] = 'Погодоци';
$string['hitsoncourse'] = 'Погодоци на $a->coursename од $a->username';
$string['hitsoncoursetoday'] = 'Погодоци за денес на $a->coursename од $a->username';
$string['home'] = 'Дома';
$string['hour'] = 'час';
$string['hours'] = 'часови';
$string['howtomakethemes'] = 'Како да направите нови теми';
$string['htmleditor'] = 'Користете HTML уредувач (само некои прелистувачо)';
$string['htmleditoravailable'] = 'HTML уредувачот е достапен';
$string['htmleditordisabled'] = 'Го оневозможивте HTML уредувачот во Вашиот профил';
$string['htmleditordisabledadmin'] = 'Администраторот го има оневозможено HTML уредувачот на овој сајт';
$string['htmleditordisabledbrowser'] = 'HTML уредувачот е недостапен затоа што Вашиот прелистувач е некомпатибилен';
$string['htmlfilesonly'] = 'Само HTML датотеки';
$string['htmlformat'] = 'Убав HTML формат';
$string['icqnumber'] = 'ICQ број';
$string['idnumber'] = 'Ид. број';
$string['idnumbercourse'] = 'Ид. број на курсот';
$string['imagealt'] = 'Опис на сликата';
$string['import'] = 'Увоз';
$string['importactivities'] = 'Увези активности од друг курс';
$string['importdata'] = 'Увези податоци за курсот';
$string['importdataexported'] = 'Податоците од „од“ курсот се пренесени успешно.<br /> Продолжете со внесување „во“ Вашиот курс.';
$string['importdatafinished'] = 'Внесувањето заврши! Продолжете кон Вашиот курс';
$string['importdatafrom'] = 'Најдете курс за внесување на податоци од него:';
$string['importgroups'] = 'Увези групи';
$string['importmetacoursenote'] = 'Користете го овој формулар да додадете курсеви на Вашиот мета курс (ова нема да вклучи записи)';
$string['inactive'] = 'Неактивни';
$string['include'] = 'Вклучи';
$string['includeallusers'] = 'Вклучи ги сите корисници';
$string['includecoursefiles'] = 'Вклучи ги датотеките за курсот';
$string['includecourseusers'] = 'Вклучи ги корисниците на курсот';
$string['included'] = 'Вклучено';
$string['includelogentries'] = 'Вклучи ги записите од записникот';
$string['includemodules'] = 'Вклучи модули';
$string['includemoduleuserdata'] = 'Вклучи ги податоците за корисници за модулот';
$string['includeneededusers'] = 'Вклучи ги потребните корисници';
$string['includenoneusers'] = 'Вклучи ги и оние кои не се корисници';
$string['includeuserfiles'] = 'Вклучи ги корисничките датотеки';
$string['info'] = 'Информации';
$string['institution'] = 'Институција';
$string['instudentview'] = 'во поглед на студент';
$string['invalidemail'] = 'Погрешна адреса за е-пошта';
$string['invalidlogin'] = 'Грешка при најавувањето, обидете се повторно';
$string['ip_address'] = 'IP адреса';
$string['jump'] = 'Скокни';
$string['jumpto'] = 'Скокни до ...';
$string['keep'] = 'Задржи';
$string['keepsearching'] = 'Продолжи со пребарување';
$string['langltr'] = 'Насока на јазикот од лево кон десно';
$string['langrtl'] = 'Насока на јазикот од десно кон лево';
$string['language'] = 'Јазик';
$string['languagegood'] = 'Овој јазичен пакет е најнова верзија';
$string['lastaccess'] = 'Последен пристап';
$string['lastedited'] = 'Последно уредување';
$string['lastlogin'] = 'Последно најавување';
$string['lastmodified'] = 'Последна промена';
$string['lastname'] = 'Презиме';
$string['lastyear'] = 'Минатата година';
$string['latestlanguagepack'] = 'Проверка за најнов јазичен пакет на moodle.org';
$string['latestnews'] = 'Најнови вести';
$string['layouttable'] = 'Табела за изглед';
$string['leavetokeep'] = 'Оставете празно за да ја зачувате моменталната лозинка';
$string['license'] = 'GPL дозвола';
$string['liketologin'] = 'Сакате ли да се најавите со целосна корисничка сметка?';
$string['list'] = 'Листа';
$string['listfiles'] = 'Листа на датотеки во $a';
$string['listofallpeople'] = 'Излистај ги сите корисници';
$string['livelogs'] = 'Живи записници од минатиот час';
$string['locale'] = 'en_AU.UTF-8';
$string['location'] = 'Локација';
$string['log_excel_date_format'] = 'гггг мммм д ч:мм';
$string['loggedinas'] = 'Најавени сте како $a';
$string['loggedinasguest'] = 'Моментно сте најавени како гостин';
$string['loggedinnot'] = 'Не сте најавени.';
$string['login'] = 'Најавете се';
$string['login_failure_logs'] = 'Записници за погрешни најавувања';
$string['loginalready'] = 'Вие сте веќе најавени';
$string['loginas'] = 'Најавете се како';
$string['loginaspasswordexplain'] = '<p>Морате да ја внесете специјалната „најавете се како, лозинка“ за да ја користите оваа карактеристика.<br />Ако не ја знаете, прашајте го Вашиот сервер администратор.</p>';
$string['loginguest'] = 'Најавете се како гостин';
$string['loginsite'] = 'Најавете се на сајтот';
$string['loginsteps'] = 'Здраво! За целосен пристап кон курсевите потребно е да креирате Ваша корисничка сметка на овој сајт. 
   Секој од овие индивидуални курсеви може да има и еднократен
   „клуч за запишување“, кој нема да Ви треба подоцна. Ова се потребните чекори:
   <ol>
   <li>Пополнете го <a href=\"$a\">Нова сметка</a> формуларот со Вашите податоци..</li>
   <li>Наскоро ќе добиете порака на Вашата адреса за е-пошта.</li>
   <li>Прочитајте ја пораката, и кликнете на врската во неа.</li>
   <li>Вашата сметка ќе биде потврдена и ќе бидете најавени на системот.</li>
   <li>Сега, одберете го курсот кој сакате да го следите.</li>
   <li>Ако треба да внесете „клуч за запишување“ - внесете го 
   клучот кој Ви го даде наставникот. Со тоа ќе бидете „запишани“ на дадениот курс.</li>
   <li>Сега имате целосен пристап до курсот. Отсега ќе биде потребно да го внесувате само Вашето корисничко име
   и лозинка за да се најавите на системот (да ги внесете во формуларот на оваа страница) и да пристапите на некој курс на кој сте запишани.</li>
</ol>';
$string['loginstepsnone'] = '<p>Здраво!</p>
<p>За целосен пристап кон курсевите потребно е да креирате Ваша корисничка сметка на оваа страница.</p>
<p>Треба само да смислите корисничко име и лозинка и да ги внесете во формуларот на оваа страница!</p>
<p>Ако некој друг веќе го има избрано Вашето корисничко име, тогаш ќе треба да смислите друго.</p>';
$string['loginto'] = 'Најавете се на $a';
$string['loginusing'] = 'Најавете се тука со Вашето корисничко име и лозинка';
$string['logout'] = 'Одјавете се';
$string['logoutconfirm'] = 'Дали навистина сакате да се одјавите?';
$string['logs'] = 'Записници';
$string['logtoomanycourses'] = '[ <a href=\"$a->url\">повеќе</a> ]';
$string['logtoomanyusers'] = '[ <a href=\"$a->url\">повеќе</a> ]';
$string['lookback'] = 'Погледнете назад';
$string['mailadmins'] = 'Информирај ги администраторите';
$string['mailstudents'] = 'Информирај ги студентите';
$string['mailteachers'] = 'Информирај ги наставниците';
$string['mainmenu'] = 'Главно мени';
$string['makeafolder'] = 'Креирај нов директориум';
$string['makeeditable'] = 'Ако го направите \'$a\' да може да се менува од процес на веб серверот (пр. apache) тогаш можете да ја промените датотеката директно од оваа страница';
$string['manageblocks'] = 'Блокови';
$string['managecourses'] = 'Менаџирајте ги курсевите';
$string['managedatabase'] = 'База на податоци';
$string['managefilters'] = 'Филтри';
$string['managemeta'] = 'Дали ова е мета-курс?';
$string['managemetadisabled'] = 'Овој курс е оневозможен бидејќи веќе е поставен како мета-курс.';
$string['managemetaexplan'] = '(Тоа значи дека листата на запишани студенти се наследува од други курсеви)';
$string['managemodules'] = 'Модули';
$string['manageroles'] = 'Улоги и пермисии';
$string['markedthistopic'] = 'Оваа тема е означена како тековна тема';
$string['markthistopic'] = 'Означи ја оваа тема како тековна';
$string['maximumchars'] = 'Најмногу $a знаци';
$string['maximumgrade'] = 'Максимална оцена';
$string['maximumshort'] = 'Макс.';
$string['maximumupload'] = 'Максимална големина на прикачена датотека';
$string['maxsize'] = 'Максимална големина: $a';
$string['memberincourse'] = 'Луѓе во курсот';
$string['messagebody'] = 'Тело на пораката';
$string['messagedselectedusers'] = 'Пораката беше испратена до избраните корисници и групата на приматели беше ресетирана.';
$string['messagedselectedusersfailed'] = 'Нешто не беше во ред при испраќањето на пораката до избраните корисници. Некои можеби ја примија е-поштата.';
$string['messageselect'] = 'Избери го овој корисник како примател за е-пошта';
$string['messageselectadd'] = 'Додадете/испратете порака';
$string['metaaddcourse'] = 'Додај го курсот';
$string['metaalreadycourses'] = 'Курсевите веќе се назначени';
$string['metaalreadyhascourses'] = 'Овој мета-курс веќе има подкурсеви.';
$string['metaalreadyhasenrolments'] = 'Овој курс веќе има нормална листа на слушатели.';
$string['metaalreadyinmeta'] = 'Овој курс веќе е дел од мета-курс.';
$string['metaassigncourses'] = 'Доделете курсеви';
$string['metacourse'] = 'Мета-курс';
$string['metanoalreadycourses'] = 'Нема дозволени курсеви';
$string['metanopotentialcourses'] = 'Нема овозможени курсеви';
$string['metapotentialcourses'] = 'Овозможени курсеви';
$string['metaremovecourse'] = 'Отстрани го курсот';
$string['min'] = 'мин';
$string['mins'] = 'мин';
$string['minutes'] = 'минути';
$string['miscellaneous'] = 'Разно';
$string['missingcategory'] = 'Треба да одберете држава';
$string['missingcity'] = 'Недостасува град';
$string['missingcountry'] = 'Недостасува држава';
$string['missingdescription'] = 'Недостасува опис';
$string['missingemail'] = 'Недостасува адреса за е-пошта';
$string['missingfirstname'] = 'Недостасува име';
$string['missingfullname'] = 'Недостасуваат име и презиме';
$string['missinglastname'] = 'Недостасува презиме';
$string['missingname'] = 'Недостасува име';
$string['missingnewpassword'] = 'Недостасува нова лозинка';
$string['missingpassword'] = 'Недостасува лозинка';
$string['missingreqreason'] = 'Недостасува причина';
$string['missingshortname'] = 'Недостасува скратено име';
$string['missingshortsitename'] = 'Недостасува скратено име на сајтот';
$string['missingsitedescription'] = 'Недостасува опис на сајтот';
$string['missingsitename'] = 'Недостасува име на сајтот';
$string['missingstrings'] = 'Провери за непреведени зборови или фрази';
$string['missingstudent'] = 'Мора да одберете нешто';
$string['missingsummary'] = 'Недостасува резиме';
$string['missingteacher'] = 'Мора да одберете нешто';
$string['missingurl'] = 'Недостасува URL';
$string['missingusername'] = 'Недостасува корисничко име';
$string['modified'] = 'Променето';
$string['moduledeleteconfirm'] = 'Модулот \'$a\' ќе биде целосно избришан. Тоа ќе избрише се во базата на податоци поврзано со овој модул.  Дали НАВИСТИНА сакате да продолжите?';
$string['moduledeletefiles'] = 'Сите податоци поврзани со модулот \'$a->module\' се избришани од базата на податоци. За да го комплетирате бришењето (и да го оневозможите модулот сам да се реинсталира), треба да го избришете овој директориум од серверот: $a->directory';
$string['modulesetup'] = 'Поставување на табелите од модулот';
$string['modulesuccess'] = '$a табели се успешно поставени';
$string['moodledocs'] = 'Moodle документи';
$string['moodledocslink'] = 'Moodle документи за оваа страница';
$string['moodleversion'] = 'Верзија на Moodle';
$string['more'] = 'повеќе';
$string['moreinformation'] = 'Повеќе информации за оваа грешка';
$string['mostrecently'] = 'последно користени';
$string['move'] = 'Премести';
$string['movecategoryto'] = 'Премести ја категоријата во:';
$string['movecourseto'] = 'Премести го курсот во:';
$string['movedown'] = 'Премести надолу';
$string['movefilestohere'] = 'Премести ги датотеките тука';
$string['movefull'] = 'Премести $a тука';
$string['movehere'] = 'Премести тука';
$string['moveleft'] = 'Премести лево';
$string['moveright'] = 'Премести десно';
$string['moveselectedcoursesto'] = 'Премести ги избраните курсеви во...';
$string['movetoanotherfolder'] = 'Премести во друг директориум';
$string['moveup'] = 'Премести нагоре';
$string['msnid'] = 'MSN ид.';
$string['mustchangepassword'] = 'Новата лозинка мора да биде различна од старата';
$string['mustconfirm'] = 'Треба да го потврдите Вашето најавување';
$string['mycourses'] = 'Моите курсеви';
$string['name'] = 'Име';
$string['namelams'] = 'LAMS';
$string['namescorm'] = 'SCORM';
$string['namesocial'] = 'оддел';
$string['nametopics'] = 'тема';
$string['nameweeks'] = 'седмица';
$string['nameweekscss'] = 'седмица';
$string['needed'] = 'Потребни';
$string['never'] = 'Никогаш';
$string['neverdeletelogs'] = 'Никогаш не ги бриши записниците';
$string['new'] = 'Ново';
$string['newaccount'] = 'Нова сметка';
$string['newcourse'] = 'Нов курс';
$string['newpassword'] = 'Нова лозинка';
$string['newpasswordfromlost'] = '<strong>ЗАБЕЛЕШКА:</strong> Вашата <strong>сегашна лозинка</strong> ќе биде испратена на <strong>втората</strong> од двете адреси за е-пошта кои беа испратени во процесот за враќање на изгубени лозинки. Проверете дали ја добивте Вашата заменета лозинка пред да продолжите со овој екран.';
$string['newpasswordtext'] = 'Здраво $a->firstname,

Лозинката за Вашата сметка на \'$a->sitename\' е ресетирана. 

Вашите нови податоци за најавување на системот:
   Корисничко име: $a->username
   Лозинка: $a->newpassword

На оваа страница можете да ја промените лозинката:
   $a->link

Во повеќето програми за е-пошта, ова би требало да биде напишано со сини букви
врз кои можете да кликнете. Ако тоа не функционира, тогаш ископирајте го текстот и вметнете го во адресната линија, која се наоѓа на горниот дел од прелистувачот.

Поздрав, администраторот на \'$a->sitename\',
$a->signoff';
$string['newpicture'] = 'Нова слика';
$string['newsitem'] = 'предмет од вестите';
$string['newsitems'] = 'предмети од вестите';
$string['newsitemsnumber'] = 'Предмети од вестите за приказ';
$string['newuser'] = 'Нов корисник';
$string['newusernewpasswordsubj'] = 'Нова корисничка сметка';
$string['newusernewpasswordtext'] = 'Здраво $a->firstname,

Нова сметка беше креирана за Вас на „$a->sitename\" и Ви е испратена нова привремена лозинка.

Вашите моментални податоци за најава се:
корисничко име: $a->username
лозинка: $a->newpassword
(ќе треба да ја промените Вашата лозинка после Вашето прво најавување)

За да започнете со користење на „$a->sitename“, најавете се на $a->link

Во повеќето програми за е-пошта, ова би требало да изгледа како сина врска на која можете да кликнете. Ако тоа не работи, тогаш ископирајте ја и вметнете ја адресата во адресната линија на горниот дел од прозорецот на Вашиот веб прелистувач.

Поздрав од администраторот на „$a->sitename“,
$a->signoff';
$string['newusers'] = 'Нови корисници';
$string['newwindow'] = 'нов прозорец';
$string['next'] = 'Следно';
$string['nextsection'] = 'Следна секција';
$string['no'] = 'Не';
$string['nobody'] = 'Никој';
$string['nochange'] = 'Без промена';
$string['nocoursesfound'] = 'Не се пронајдени курсеви со зборовите \'$a\'';
$string['nocoursesyet'] = 'Нема курсеви во оваа категорија';
$string['nodstpresets'] = 'Администраторот ја нема овозможено поддршката за летно сметање на времето.';
$string['noexistingadmins'] = 'Не постојат администратори, ова е сериозна грешка и Вие не требаше никогаш да ја видите оваа порака.';
$string['noexistingcreators'] = 'Не постојат создавачи';
$string['noexistingstudents'] = 'Не постојат студенти';
$string['noexistingteachers'] = 'Не постојат предавачи';
$string['nofilesselected'] = 'Не се избрани датотеки за обнова';
$string['nofilesyet'] = 'Сè уште не се поставени датотеки за Вашиот курс.';
$string['nograde'] = 'Нема оценка';
$string['noimagesyet'] = 'Сè уште не се поставени слики за Вашиот курс.';
$string['nomorecourses'] = 'Не постојат други курсеви според дадениот критериум.';
$string['nomoreidnumber'] = 'Не се користи ид. број за одбегнување на судири';
$string['none'] = 'Нема';
$string['noneditingteacher'] = 'Наставник без уредување';
$string['noneditingteacherdescription'] = 'Наставниците без уредување можат да предаваат во курсевите и да ги оценуваат студентите, но не можат да менуваат активности.';
$string['nopendingcourses'] = 'Нема курсеви кои чекаат за одобрување';
$string['nopotentialadmins'] = 'Не постојат потенцијални администратори';
$string['nopotentialcreators'] = 'Не постојат потенцијални создавачи на курсеви';
$string['nopotentialstudents'] = 'Не постојат потенцијални студенти';
$string['nopotentialteachers'] = 'Не постојат потенцијални предавачи';
$string['norecentactivity'] = 'Нема скорешни активности';
$string['noreplybouncemessage'] = 'Имате одговорено на порака на која не треба да се одговара. Ако се обидувавте да одговорите на порака од форумот, искористете го форумот $a. 

Ова е содржината на Вашата порака:';
$string['noreplybouncesubject'] = '$a - вратена порака.';
$string['noreplyname'] = 'Не враќајте одговор на оваа порака';
$string['noresults'] = 'Нема резултати';
$string['normal'] = 'Нормално';
$string['normalfilter'] = 'Нормално пребарување';
$string['nosite'] = 'Не можев да пронајдам курсеви на ниво на сајтот';
$string['nostatstodisplay'] = 'Нема достапни податоци за приказ, извинете.';
$string['nostudentsfound'] = 'Не е најдено $a';
$string['nostudentsingroup'] = 'Сè уште нема студенти во оваа група';
$string['nostudentsyet'] = 'Сè уште не се запишани студенти на овој курс';
$string['nosuchemail'] = 'Не постои таква адреса за е-пошта';
$string['notavailable'] = 'Не е достапно';
$string['noteachersyet'] = 'Сè уште нема предавачи за овој курс';
$string['notenrollable'] = 'Овој курс моментално не е со членство.';
$string['notenrolled'] = '$a не е запишан на овој курс';
$string['notenrolledprofile'] = 'Овој профил не е достапен бидејќи овој корисник не е зачленет во овој курс.';
$string['noteuserschangednonetocourse'] = 'Забелешка: корисниците на курсот мора да бидат вратени кога се враќаат нивните податоци (датотеки или пораки). Оваа опција е сменета за Вас.';
$string['nothingnew'] = 'Нема ништо ново од Вашето последно најавување на системот';
$string['nothingtodisplay'] = 'Нема ништо за прикажување';
$string['noticenewerbackup'] = 'Оваа резервна датотека е креирана со Moodle $a->backuprelease ($a->backupversion) и таа е понова од моменталната верзија на Moodle $a->serverrelease ($a->serverversion). Ова може да предизвика неконзистентност бидејќи поранешната компатибилност на резервните датотеки не може да биде загарантирана.';
$string['notifications'] = 'Известувања';
$string['notify'] = 'Извести';
$string['notifyloginfailuresmessage'] = '$a->time, IP: $a->ip, Корисник: $a->info';
$string['notifyloginfailuresmessageend'] = 'Можете да ги видите овие записници на $a/course/log.php?id=1&chooselog=1&modid=site_errors.';
$string['notifyloginfailuresmessagestart'] = 'Еве листа на неуспешни најавувања на $a од последниот пат кога бевте известени';
$string['notifyloginfailuressubject'] = '$a :: Известување за неуспешни најавувања на системот';
$string['notincluded'] = 'Не е вклучено';
$string['notingroup'] = 'Извинете, но треба да сте дел од група за да можете да ја видите оваа активност.';
$string['notpublic'] = 'Не е јавно!';
$string['nousersmatching'] = 'Не се пронајдени корисници по критериумот \'$a\'.';
$string['nousersyet'] = 'Сè уште нема корисници';
$string['novalidcourses'] = 'Нема важечки курсеви за да бидат прикажани';
$string['now'] = 'сега';
$string['numattempts'] = '$a неуспешни обиди за најавување на системот';
$string['numberweeks'] = 'Број на седмици/наслови';
$string['numdays'] = '$a денови';
$string['numhours'] = '$a часови';
$string['numletters'] = '$a букви';
$string['numminutes'] = '$a минути';
$string['nummonths'] = '$a месеци';
$string['numseconds'] = '$a секунди';
$string['numviews'] = '$a погледи';
$string['numweeks'] = '$a седмици';
$string['numwords'] = '$a зборови';
$string['numyears'] = '$a години';
$string['ok'] = 'Во ред';
$string['oldpassword'] = 'Сегашна лозинка';
$string['opentoguests'] = 'Пристап како гостин';
$string['optional'] = 'по можност';
$string['order'] = 'Нарачка';
$string['other'] = 'друго';
$string['outline'] = 'Забелешка';
$string['outlinereport'] = 'Извештај (забелешки)';
$string['page'] = 'Страница';
$string['pageheaderconfigablock'] = 'Конфигурирам блок во %%fullname%%';
$string['parentcoursenotfound'] = 'Курсот родител не е пронајден!';
$string['parentcoursenotmetacourse'] = 'Курсот родител не е мета-курс!';
$string['parentfolder'] = 'Родител папка';
$string['parentlanguage'] = '<< ПРЕВЕДУВАЧИ: Ако Вашиот јазик има родител јазик што Moodle треба да го користи кога недостигаат низи од Вашиот јазичен пакет, тогаш овде наведете го кодот за него. Ако го оставите ова празно тогаш ќе се користи англиски. На пример: nl >>';
$string['participants'] = 'Учесници';
$string['participationratio'] = 'Однос на учество';
$string['participationreport'] = 'Извештај за учество';
$string['password'] = 'Лозинка';
$string['passwordchanged'] = 'Лозинката е променета';
$string['passwordconfirmchange'] = 'Потврдете промена на лозинката';
$string['passwordextlink'] = 'Следната врска е доставена за да ја надомести Вашата изгубена лозинка. Ова ќе Ве однесе надвор од Moodle.';
$string['passwordforgotten'] = 'Заборавена лозинка';
$string['passwordforgotteninstructions'] = 'Вашите детали мораат прво да бидат пронајдени во корисничката база на податоци. Ве молам внесете го <strong>или</strong> Вашето корисничко име или Вашата регистрирана адреса за е-пошта во соодветното поле. Нема потреба за да ги внесете и двете.';
$string['passwordnohelp'] = 'Нема достапна помош за пронаоѓање на Вашата изгубена лозинка. Ве молам контактирајте го Вашиот Moodle администратор.';
$string['passwordrecovery'] = 'Да, помогни ми да се најавам';
$string['passwordsdiffer'] = 'Лозинките не се совпаѓаат';
$string['passwordsent'] = 'Лозинката е испратена';
$string['passwordsenttext'] = '<p>Испратена е порака на Вашата адреса за е-пошта $a->email.</p>
   <p><b>Проверете си ја е-поштата за новата лозинка</b></p>
   <p>Новата лозинка беше автоматски генерирана, па можеби ќе сакате 
   <a href=\"$a->link\">да ја смените во нешто полесно за паметење</a>.</p>';
$string['pathnotexists'] = 'Патеката на серверот не е валидна!';
$string['pathslasherror'] = 'Патеката не смее да завршува со коса црта!';
$string['paymentinstant'] = 'Искористете го копчето долу за да платите и да бидете запишани за следење на курсот!';
$string['paymentpending'] = '(<small><b><u>$a</u></b> чекам</small>)';
$string['paymentrequired'] = 'За да се следи овој курс треба да се плати.';
$string['payments'] = 'Плаќања';
$string['paymentsorry'] = 'Благодариме на Вашата исплата! За жал Вашата исплата сè уште не е целосно процесирана, и сè уште не сте запишани за следење на курсот \"$a->fullname\".  Обидете се повторно по неколку секунди, но ако и понатаму имате проблеми известете го предавачот $a->teacher или администраторот на сајтот';
$string['paymentthanks'] = 'Благодариме за Вашата исплата! Сега сте запишани за следење на курсот:<br />„$a“';
$string['people'] = 'Луѓе';
$string['periodending'] = 'Периодот завршува ($a)';
$string['personalprofile'] = 'Личен профил';
$string['phone'] = 'Телефон';
$string['phpinfo'] = 'PHP информации';
$string['pictureof'] = 'Слика од $a';
$string['pleaseclose'] = 'Ве молам сега затворете го овој прозорец.';
$string['pluginsetup'] = 'Поставувам табели за додатоци';
$string['policyagree'] = 'Мора да се согласувате со овие правила за да продолжите да го користите овој сајт. Дали се согласувате?';
$string['policyagreement'] = 'Правилник за користење на сајтот';
$string['policyagreementclick'] = 'Кликнете тука за да го прочитате правилникот за користење на сајтот';
$string['popupwindow'] = 'Отвори ја датотеката во нов прозорец';
$string['post'] = 'Запис';
$string['posts'] = 'Записи';
$string['potentialadmins'] = 'Потенцијални администратори';
$string['potentialcreators'] = 'Потенцијални создавачи на курсеви';
$string['potentialstudents'] = 'Потенцијални студенти';
$string['potentialteachers'] = 'Потенцијални предавачи';
$string['preferences'] = 'Преференции';
$string['preferredlanguage'] = 'Префериран јазик';
$string['preferredtheme'] = 'Преферирана тема';
$string['preview'] = 'Преглед';
$string['previewhtml'] = 'Преглед на HTML форматот';
$string['previeworchoose'] = 'Прегледајте или одберете тема';
$string['previous'] = 'Претходно';
$string['previoussection'] = 'Претходна секција';
$string['primaryadminsetup'] = 'Поставете ја администраторската сметка';
$string['profile'] = 'Профил';
$string['publicdirectory'] = 'Јавен директориум';
$string['publicdirectory0'] = 'Ве молиме не го објавувајте овој сајт';
$string['publicdirectory1'] = 'Објавете го само името на сајтот';
$string['publicdirectory2'] = 'Објавете го името на сајтот со врска';
$string['publicdirectorytitle'] = 'Видете ја сегашната листа со сајтови';
$string['publicsitefileswarning'] = 'Забелешка: датотеките внесени тука ќе можат да бидат пристапени од било кој';
$string['question'] = 'Прашање';
$string['readinginfofrombackup'] = 'Читање информации од резервната копија';
$string['readme'] = 'READ ME';
$string['recentactivity'] = 'Скорешна активност';
$string['recentactivityreport'] = 'Целосен извештај за минатите активности...';
$string['recipientslist'] = 'Листа на приматели';
$string['recreatedcategory'] = 'Повторно создадена категорија $a';
$string['refresh'] = 'Освежи';
$string['refreshingevents'] = 'Ги освежувам настаните';
$string['registration'] = 'Регистрирање на Moodle';
$string['registrationcontact'] = 'Контакт од јавност';
$string['registrationcontactno'] = 'Не, не сакам контакт формулар во јавната листа';
$string['registrationcontactyes'] = 'Да, би сакал контакт формулар во јавната листа за просперитетните Мудлери да ме контактираат';
$string['registrationemail'] = 'Известување преку е-пошта';
$string['registrationinfo'] = '<p>Оваа страница Ви овозможува да го регистрирате Вашиот Moodle сајт со moodle.org. Регистрацијата е бесплатна.
Главната придобивка од регистрирањето е тоа што ќе бидете додадени во поштенската листа за важни известувања како безбедносни предупредувања и нови верзии на Moodle.</p>
<p> Како почетно поставување, Вашата сметка ќе биде зачувана како приватна, и никогаш нема да биде продадена или дадена на некој друг. Единствената причина за собирање на овие информации е за поддршка и за статистички податоци за Moodle заедницата како целина.</p>
<p>Ако одберете, можете да го одберете името на Вашиот сајт, држава и URL да бидат додадени во листата на Moodle сајтови.</p>
<p>Сите нови регистрации рачно се проверуваат пред да бидат додадени во листата, но штом еднаш се додадат, можете да ги менувате со повторно праќање на формуларот.</p>';
$string['registrationno'] = 'Не, не сакам да примам пораки на е-пошта';
$string['registrationsend'] = 'Испрати ги информациите за регистрација кон moodle.org';
$string['registrationyes'] = 'Де, Ве молам известете ме за поважните настани';
$string['reject'] = 'Одбиј';
$string['remove'] = 'Отстрани';
$string['removeadmin'] = 'Отстрани администратор';
$string['removecreator'] = 'Отстрани создавач на курс';
$string['removestudent'] = 'Отстрани студент';
$string['removeteacher'] = 'Отстрани предавач';
$string['rename'] = 'Преименувај';
$string['renamefileto'] = 'Преименувај <b>$a</b> во';
$string['report'] = 'Извештај';
$string['reports'] = 'Извештаи';
$string['requestcourse'] = 'Побарај курс';
$string['requestedby'] = 'Побарано од';
$string['requestreason'] = 'Причина за побарување на курсот';
$string['required'] = 'Потребно';
$string['requireskey'] = 'За следење на овој курс потребен е клуч за активирање';
$string['requirespayment'] = 'За следење на овој курс потребно е да се плати';
$string['reset'] = 'Ресетирај';
$string['resetcourse'] = 'Ресетирај го курсот';
$string['resetinfo'] = 'Оваа страница Ви дозволува да испразните курс од податоците на корисниците, додека активностите и другите поставувања ќе бидат задржани. Ве молам бидете предупредени дека со одбирањето на предмети од подолу и испраќањето на оваа страница ќе ги избрише изберените податоци на корисниците од овој курс засекогаш!';
$string['resetstartdate'] = 'Ресетирај го почетниот датум';
$string['resettodefaults'] = 'Ресетирај на стандардно';
$string['resortcoursesbyname'] = 'Подреди ги курсевите по име';
$string['resource'] = 'Ресурс';
$string['resources'] = 'Ресурси';
$string['restore'] = 'Обновување';
$string['restorecancelled'] = 'Обновувањето е откажано';
$string['restorecoursenow'] = 'Обнови го курсот сега!';
$string['restorefinished'] = 'Обновувањето е успешно завршено';
$string['restoreto'] = 'Обнови како';
$string['restricted'] = 'Ограничени';
$string['restrictmodules'] = 'Ограничи модули за активност?';
$string['returningtosite'] = 'Се враќате на овој веб сајт?';
$string['revert'] = 'Преврти';
$string['role'] = 'Улога';
$string['rolemappings'] = 'Мапирање на улоги';
$string['roles'] = 'Улоги';
$string['rss'] = 'RSS';
$string['rssarticles'] = 'Број на минати RSS статии';
$string['rsserror'] = 'Грешка при читање на RSS податоците';
$string['rsstype'] = 'RSS податоци за оваа активност';
$string['saveandnext'] = 'Зачувај и покажи следна';
$string['savechanges'] = 'Зачувај ги промените';
$string['savedat'] = 'Зачувано во:';
$string['savepreferences'] = 'Зачувај преференции';
$string['saveto'] = 'Зачувај во';
$string['scale'] = 'Критериум';
$string['scales'] = 'Критериуми';
$string['scalescustom'] = 'Дополнителни критериуми';
$string['scalescustomcreate'] = 'Додај нов критериум';
$string['scalescustomno'] = 'Сè уште не се креирани дополнителни критериуми';
$string['scalesstandard'] = 'Стандардни критериуми';
$string['scalestip'] = 'За да креирате дополнителни критериуми, користете ја врската \'Критериуми...\' во менито за администрација на курсот.';
$string['schedule'] = 'Распоред';
$string['scheduledbackupstatus'] = 'Статус на резервниот распоред';
$string['screenreaderno'] = 'Не';
$string['screenreaderuse'] = 'Читач на екранот';
$string['screenreaderyes'] = 'Да';
$string['screenshot'] = 'Слика од екранот';
$string['search'] = 'Барај';
$string['searchagain'] = 'Барај повторно';
$string['searchcourses'] = 'Барај курсеви';
$string['searchhelp'] = 'Можете да пребарувате за повеќе зборови истовремено.<br /><br />збор : најди било какво совпаѓање со дадениот збор.<br />+збор : само точно тој збор ќе биде баран.<br />-збор : не ги прикажувај резултатите кои го содржат дадениот збор.';
$string['searchresults'] = 'Резултати од пребарувањето';
$string['sec'] = 'сек.';
$string['secondstotime172800'] = '2 дена';
$string['secondstotime259200'] = '3 дена';
$string['secondstotime345600'] = '4 дена';
$string['secondstotime432000'] = '5 дена';
$string['secondstotime518400'] = '6 дена';
$string['secondstotime604800'] = '1 седмица';
$string['secondstotime86400'] = '1 ден';
$string['secretalreadyused'] = 'Врската за потврдување на промената на лозинката веќе е искористена, лозинката не е променета.';
$string['secs'] = 'сек.';
$string['section'] = 'Оддел';
$string['sections'] = 'Оддели';
$string['seealsostats'] = 'Видете и: статистика';
$string['select'] = 'Избери';
$string['selectacountry'] = 'Изберете држава';
$string['selectall'] = 'Избери ги сите';
$string['selectamodule'] = 'Ве молам изберете модул за активност';
$string['selectednowmove'] = '$a датотеки се изберени за преместување. Сега одете во целта и притиснете \'Премести ги датотеките тука\'';
$string['selectnos'] = 'Избери ги сите „не“';
$string['selectperiod'] = 'Избери го периодот';
$string['senddetails'] = 'Прати ми ги податоците по е-пошта';
$string['separate'] = 'Раздели';
$string['separateandconnected'] = 'Одделени и поврзани начини на знаење';
$string['serverlocaltime'] = 'Локално време на серверот';
$string['settings'] = 'Поставувања';
$string['shortname'] = 'Кратко име';
$string['shortnamecollisionwarning'] = '[*] = Ова кратко име веќе се користи за друг курс и ќе треба да биде променето на одобрувањето';
$string['shortnametaken'] = 'Краткото име веќе се користи за друг курс ($a)';
$string['shortsitename'] = 'Кратко име за сајтот (пр. еден збор)';
$string['show'] = 'Прикажи';
$string['showactions'] = 'Прикажи акции';
$string['showadvancedsettings'] = 'Прикажи ги напредните поставувања';
$string['showall'] = 'Прикажи ги сите $a';
$string['showallcourses'] = 'Прикажи ги сите курсеви';
$string['showalltopics'] = 'Прикажи ги сите наслови';
$string['showallusers'] = 'Прикажи ги сите корисници';
$string['showallweeks'] = 'Прикажи ги сите седмици';
$string['showblockcourse'] = 'Прикажи листа со курсеви кои содржат блок';
$string['showgrades'] = 'Прикажи ги оценките';
$string['showlistofcourses'] = 'Прикажи листа со курсеви';
$string['showmodulecourse'] = 'Прикажи листа со курсеви кои содржат активност';
$string['showonly'] = 'Прикажи само';
$string['showonlytopic'] = 'Прикажи го само насловот $a';
$string['showonlyweek'] = 'Прикажи ја само седмицата $a';
$string['showperpage'] = 'Прикажувај $a по страница';
$string['showrecent'] = 'Прикажи ги минатите активности';
$string['showreports'] = 'Прикажи ги извештаите';
$string['showsettings'] = 'Прикажи ги поставувањата';
$string['showtheselogs'] = 'Прикажи ги овие записници';
$string['since'] = 'Од';
$string['sincelast'] = 'од последното најавување на системот';
$string['site'] = 'Сајт';
$string['sitedefault'] = 'Основни поставувања за сајтот';
$string['siteerrors'] = 'Грешки со сајтот';
$string['sitefiles'] = 'Датотеки од сајтот';
$string['sitelogs'] = 'Записници од сајтот';
$string['sitenews'] = 'Вести од сајтот';
$string['sitepartlist'] = 'Ги немате потребните пермисии за да ја видете листата со учесници';
$string['sitepartlist0'] = 'Мора да сте предавач на сајтот за да можете да ја видите листата со учесници';
$string['sitepartlist1'] = 'Мора да сте предавач за да можете да ја видите листата со учесници';
$string['sites'] = 'Сајтови';
$string['sitesection'] = 'Вметни оддел со теми';
$string['sitesettings'] = 'Поставувања за сајтот';
$string['siteteachers'] = 'Предавачи за сајтот';
$string['size'] = 'Големина';
$string['sizeb'] = 'бајти';
$string['sizegb'] = 'GB';
$string['sizekb'] = 'KB';
$string['sizemb'] = 'MB';
$string['skipped'] = 'Прескокнати';
$string['skiptomaincontent'] = 'Прескокни нанапред до главната содржина';
$string['skypeid'] = 'Skype ид.';
$string['socialheadline'] = 'Општ форум - најнови наслови';
$string['someallowguest'] = 'Некои курсеви можат да дозволуваат пристап како гостин';
$string['someerrorswerefound'] = 'Некои информации недостасуваат или се погрешни. Видете подолу за подетално.';
$string['sortby'] = 'Подреди по';
$string['sourcerole'] = 'Изворна улога';
$string['specifyname'] = 'Мора да внесете име';
$string['starpending'] = '([*] = чекам одобрение за курсот)';
$string['startdate'] = 'Почетен датум на курсот';
$string['startsignup'] = 'Креирај нова сметка';
$string['state'] = 'Држава/провинција';
$string['statistics'] = 'Статистика';
$string['statisticsgraph'] = 'Графикон за статистика';
$string['stats'] = 'Статистика';
$string['statslogins'] = 'Најавувања';
$string['statsmodedetailed'] = 'Детален (кориснички) поглед';
$string['statsmodegeneral'] = 'Општ поглед';
$string['statsnodata'] = 'Нема достапни податоци за таа комбинација на курс и временски период.';
$string['statsnodatauser'] = 'Нема достапни податоци за таа комбинација на курс, корисник и временски период.';
$string['statsoff'] = 'Статистиката моментално не е овозможена';
$string['statsreads'] = 'Погледи';
$string['statsreport1'] = 'Најавувања';
$string['statsreport10'] = 'Активност на корисниците';
$string['statsreport11'] = 'Најактивни курсеви';
$string['statsreport12'] = 'Најактивни курсеви (значајни)';
$string['statsreport13'] = 'Курсеви со најголемо учество (членови)';
$string['statsreport14'] = 'Курсеви со најголемо учество (погледи/записи)';
$string['statsreport2'] = 'Погледи (сите улоги)';
$string['statsreport3'] = 'Записи (сите улоги)';
$string['statsreport4'] = 'Цела активност (сите улоги)';
$string['statsreport5'] = 'Цела активност (погледи и записи)';
$string['statsreport7'] = 'Активност од корисници (погледи и записи)';
$string['statsreport8'] = 'Цела активност од корисници';
$string['statsreport9'] = 'Најавувања (курс на сајтот)';
$string['statsreportactivity'] = 'Цела активност (сите улоги)';
$string['statsreportactivitybyrole'] = 'Цела активност (погледи и записи)';
$string['statsreportforuser'] = 'за';
$string['statsreportlogins'] = 'Најавувања';
$string['statsreportreads'] = 'Погледи (сите улоги)';
$string['statsreporttype'] = 'Тип на извештај';
$string['statsreportwrites'] = 'Записи (сите улоги)';
$string['statsstudentactivity'] = 'Активност од студенти';
$string['statsstudentreads'] = 'Погледи од студенти';
$string['statsstudentwrites'] = 'Записи од студенти';
$string['statsteacheractivity'] = 'Активност од наставници';
$string['statsteacherreads'] = 'Погледи од наставници';
$string['statsteacherwrites'] = 'Записи од наставници';
$string['statstimeperiod'] = 'Временски период - последни:';
$string['statsuniquelogins'] = 'Уникатни најавувања';
$string['statsuseractivity'] = 'Цела активност';
$string['statsuserlogins'] = 'Најавувања';
$string['statsuserreads'] = 'Погледи';
$string['statsuserwrites'] = 'Записи';
$string['statswrites'] = 'Записи';
$string['status'] = 'Состојба';
$string['strftimedate'] = '%%d %%B %%Y';
$string['strftimedateshort'] = '%%d %%B';
$string['strftimedatetime'] = '%%d %%B %%Y, %%I:%%M %%p';
$string['strftimedaydate'] = '%%A, %%d %%B %%Y';
$string['strftimedaydatetime'] = '%%A, %%d %%B %%Y, %%I:%%M %%p';
$string['strftimedayshort'] = '%%A, %%d %%B';
$string['strftimedaytime'] = '%%a, %%H:%%M';
$string['strftimemonthyear'] = '%%B %%Y';
$string['strftimerecent'] = '%%d %%b, %%H:%%M';
$string['strftimerecentfull'] = '%%a, %%d %%b %%Y, %%I:%%M %%p';
$string['strftimetime'] = '%%I:%%M %%p';
$string['stringsnotset'] = 'Следниве низи не се дефинирани во $a';
$string['studentnotallowed'] = 'Жалам, но не можете да го влезете во овој курс како \'$a\'';
$string['students'] = 'Студенти';
$string['studentsandteachers'] = 'Студенти и предавачи';
$string['studentviewoff'] = 'Исклучи го погледот за студенти';
$string['studentviewon'] = 'Уклучи го погледот за студенти';
$string['subcategories'] = 'Подкатегории';
$string['submit'] = 'Испрати';
$string['success'] = 'Успех';
$string['summary'] = 'Резиме';
$string['summaryof'] = 'Резиме на $a';
$string['supplyinfo'] = 'Внесете некои информации за Вас';
$string['switchrolereturn'] = 'Врати ме на мојата нормална улога';
$string['switchroleto'] = 'Смени ја улогата во...';
$string['tag'] = 'Етикета';
$string['tagalready'] = 'Оваа етикета веќе постои';
$string['tagmanagement'] = 'Додај/избриши етикети...';
$string['tags'] = 'Етикети';
$string['targetrole'] = 'Цел на улога';
$string['teacheronly'] = 'Само за $a';
$string['teacherroles'] = '$a улоги';
$string['teachers'] = 'Предавачи';
$string['textediting'] = 'При промена на текст';
$string['texteditor'] = 'Користи стандардни веб форми';
$string['textformat'] = 'Обичен текст формат';
$string['thanks'] = 'Благодарам';
$string['theme'] = 'Тема';
$string['themes'] = 'Теми';
$string['themesaved'] = 'Зачувана е нова тема';
$string['thischarset'] = 'Секогаш користете utf-8';
$string['thisdirection'] = 'Внесете ltr (лево на десно)';
$string['thislanguage'] = 'Наведете има на Вашиот јазик овде, користете уникод ако е возможно';
$string['time'] = 'Време';
$string['timezone'] = 'Временска зона';
$string['to'] = 'До';
$string['today'] = 'Денес';
$string['todaylogs'] = 'Денешни записници';
$string['toeveryone'] = 'до секого';
$string['toomanybounces'] = 'Оваа адреса за е-пошта има премногу одбивања. <b>Морате</b> да ја промените за да продолжите.';
$string['toomanytoshow'] = 'Има премногу корисници за да се прикажат.';
$string['toonly'] = 'само до $a';
$string['top'] = 'Врв';
$string['topic'] = 'Наслов';
$string['topichide'] = 'Скриј го овој наслов од $a';
$string['topicoutline'] = 'Белешки за насловот';
$string['topicshow'] = 'Прикажи го насловот на $a';
$string['total'] = 'Вкупно';
$string['trackforums'] = 'Следење на форум';
$string['trackforumsno'] = 'Не: не следи кои пораки ги имам прочитано';
$string['trackforumsyes'] = 'Да: обележи ги новите пораки за мене';
$string['trysearching'] = 'Обиди се со пребарување';
$string['turneditingoff'] = 'Исклучи го уредувањето на текст';
$string['turneditingon'] = 'Вклучи го уредувањето на текст';
$string['undecided'] = 'Неодлучено';
$string['unenrol'] = 'Отпиши';
$string['unenrolallstudents'] = 'Отпиши ги сите студенти';
$string['unenrolallstudentssure'] = 'Дали сте сигурни дека сакате целосно да ги отпишите сите студенти од курсов?';
$string['unenrolme'] = 'Отпиши ме од $a';
$string['unenrolsure'] = 'Дали сте сигурни дека сакате да го отпишите $a од овој курс?';
$string['unfinished'] = 'Недовршено';
$string['unknowncategory'] = 'Непозната категорија';
$string['unlimited'] = 'Неограничено';
$string['unpacking'] = 'Го отпакувам $a';
$string['unsafepassword'] = 'Небезбедна лозинка - смислете друга!';
$string['untilcomplete'] = 'Додека не е целосно';
$string['unusedaccounts'] = 'Сметките кои не се користени повеќе од $a денови автоматски се отпишуваат';
$string['unzip'] = 'Отпакувај';
$string['unzippingbackup'] = 'Ја отпакувам резервната копија';
$string['up'] = 'Горе';
$string['update'] = 'Ажурирај';
$string['updated'] = 'Ажурирано е $a';
$string['updatemymoodleoff'] = 'Нормален режим';
$string['updatemymoodleon'] = 'Уреди ја оваа страница';
$string['updatemyprofile'] = 'Ажурирајте го профилот';
$string['updatesevery'] = 'Се ажурира секои $a секунди';
$string['updatethis'] = 'Ажурирајте го ова $a';
$string['updatethiscourse'] = 'Ажурирајте го курсот';
$string['updatinga'] = 'Ажурирам: $a';
$string['updatingain'] = 'Ажурирам $a->what во $a->in';
$string['upload'] = 'Качи';
$string['uploadafile'] = 'Качи датотека';
$string['uploadedfile'] = 'Датотеката е успешно качена';
$string['uploadedfileto'] = 'Качена е $a->file во $a->directory';
$string['uploadedfiletoobig'] = 'Датотеката е премногу голема (границата е $a бајти)';
$string['uploadfailednotrecovering'] = 'Качувањетп беше неуспешно бидејќи имаше проблем со датотеката $a->name.<br /> Еве записник за проблемите:<br />$a->problem<br />Не се обновува.';
$string['uploadfilelog'] = 'Качи го записникот за датотеката $a';
$string['uploadformlimit'] = 'Качената датотека ја надминува максималната големина поставена во формуларот';
$string['uploadlabel'] = 'Наслов:';
$string['uploadnofilefound'] = 'Не беше најдена ниту една датотека - дали сте сигурни дека избравте некоја датотека за качување?';
$string['uploadnotallowed'] = 'Не се дозволени качувања';
$string['uploadoldfilesdeleted'] = 'Старите датотеки од Вашата област за качување се избришани';
$string['uploadpartialfile'] = 'Датотеката беше делумно качена';
$string['uploadproblem'] = 'Се појави непознат проблем при качувањето на датотеката \'$a\' (можеби е премногу голема?)';
$string['uploadrenamedchars'] = 'Датотеката е преименувана од $a->oldname во $a->newname поради недозволени знаци во името.';
$string['uploadrenamedcollision'] = 'Датотеката е преименувана од $a->oldname во $a->newname поради конфликт со името на друга датотека.';
$string['uploadserverlimit'] = 'Качената датотека ја надминува максималната големина одобрена од серверот';
$string['uploadthisfile'] = 'Качи ја оваа датотека';
$string['uploadusers'] = 'Качи корисници';
$string['usedinnplaces'] = 'Искористено на $a места';
$string['usemessageform'] = 'или користете го овој формулар подолу да испратите порака до избраните студенти';
$string['user'] = 'Корисник';
$string['userconfirmed'] = 'Потврдено $a';
$string['userdata'] = 'Кориснички податоци';
$string['userdeleted'] = 'Корисничката сметка е избришана';
$string['userdescription'] = 'Опис';
$string['userfiles'] = 'Кориснички датотеки';
$string['userlist'] = 'Кориснички листи';
$string['username'] = 'Корисничко име';
$string['usernameemailmatch'] = 'Корисничкото име и адресата за е-пошта не припаѓаат на истиот корисник';
$string['usernameexists'] = 'Корисничкото име веќе постои, одберете друго';
$string['usernamelowercase'] = 'Дозволени се само мали букви';
$string['usernamenotfound'] = 'Корисничкото име не беше пронајдено во базата на податоци';
$string['usernameoremail'] = 'Внесете или корисничко име или адреса за е-пошта';
$string['usernotconfirmed'] = 'Не можеше да биде потврдено $a';
$string['userpic'] = 'Слика од корисник';
$string['userprofilefor'] = 'Кориснички податоци за $a';
$string['users'] = 'Корисници';
$string['usersnew'] = 'Нови корисници';
$string['usersnoaccesssince'] = 'Неактивни за повеќе од';
$string['userzones'] = 'Кориснички зони';
$string['usethiscourse'] = 'Користете го курсот';
$string['usingexistingcourse'] = 'Користење на постоечки курс';
$string['version'] = 'Верзија';
$string['view'] = 'Поглед';
$string['views'] = 'Погледи';
$string['viewsolution'] = 'решение на погледот';
$string['virusfound'] = 'Известување до администраторот! Антивирусната програма пронајде вирус во датотека качена од $a->user за курсот $a->course. Еве ги податоците:';
$string['virusfoundlater'] = 'Во датотека која ја качивте на $a->date со име $a->filename за курсот $a->course пронајден е вирус.  Еве извештај за тоа што се случи со датотеката:

$a->action

Ако тоа беше испратена домашна задача, можете да ја препратите, за надлежниот да ја провери.';
$string['virusfoundlateradmin'] = 'Известување до администраторот! Во датотека која е качена на $a->date со име $a->filename за курсот $a->course од страна на $a->user пронајден е вирус.  Еве извештај за тоа што се случи со датотеката:

$a->action

И корисникот е известен.';
$string['virusfoundlateradminnolog'] = 'Известување до администраторот! Во датотека која е качена со име $a->filename пронајден е вирус. Moodle не успеа да ја врати назад до корисникот кој ја качи.

Еве извештај за тоа што се случи со датотеката:

$a->action';
$string['virusfoundsubject'] = '$a: Пронајден е вирус!';
$string['virusfounduser'] = 'Датотеката која ја качивте, $a->filename, беше скенирана за вируси и беше пронајден вирус! Качувањето не беше успешно.';
$string['virusplaceholder'] = 'Во датотеката која беше качена пронајден е вирус и беше преместена или избришана, а корисникот беше известен.';
$string['visible'] = 'Видливо';
$string['visibletostudents'] = 'Видливо за $a';
$string['warningdeleteresource'] = 'Предупредување: $a е упатено во ресурс. Дали сакате да го ажурирате ресурсот?';
$string['webpage'] = 'Веб страница';
$string['week'] = 'Седмица';
$string['weekhide'] = 'Скриј ја оваа седмица од $a';
$string['weeklyoutline'] = 'Неделен извештај';
$string['weekshow'] = 'Прикажи ја оваа седмица на $a';
$string['welcometocourse'] = 'Добродојдовте во $a';
$string['welcometocoursetext'] = 'Добродојдовте во $a->coursename!

Ако досега го немате направено ова, треба да ги дополните Вашите податоци во формуларот за овој курс за да знаеме повеќе за Вас:

$a->profileurl';
$string['whattocallzip'] = 'Како сакате да ја именувате zip датотеката?';
$string['withchosenfiles'] = 'Со одбраните датотеки';
$string['withoutuserdata'] = 'без кориснички податоци';
$string['withselectedusers'] = 'Со избраните корисници...';
$string['withuserdata'] = 'со кориснички податоци';
$string['wordforstudent'] = 'Ваш збор за студент';
$string['wordforstudenteg'] = 'пр. Студент, учесник и сл.';
$string['wordforstudents'] = 'Ваш збор за студенти';
$string['wordforstudentseg'] = 'пр. Студенти, учесници и сл.';
$string['wordforteacher'] = 'Ваш збор за наставник';
$string['wordforteachereg'] = 'пр. Учител, предавач и сл.';
$string['wordforteachers'] = 'Ваш збор за наставници';
$string['wordforteacherseg'] = 'пр. Учители, предавачи и сл.';
$string['writingcategoriesandquestions'] = 'Запишувам категории и прашања';
$string['writingcoursedata'] = 'Запишувам податоци за курсот';
$string['writingeventsinfo'] = 'Запишувам информации за настаните';
$string['writinggeneralinfo'] = 'Запишувам општи информации';
$string['writinggradebookinfo'] = 'Запишувам информации за книгата со оценки';
$string['writinggroupingsinfo'] = 'Запишувам информации за групирањата';
$string['writinggroupsinfo'] = 'Запишувам информации за групите';
$string['writingheader'] = 'Запишувам наслов';
$string['writingloginfo'] = 'Запишувам информации за записниците';
$string['writingmessagesinfo'] = 'Запишувам информации за пораките';
$string['writingmoduleinfo'] = 'Запишувам информации за модулите';
$string['writingscalesinfo'] = 'Запишувам информации за скалите';
$string['writinguserinfo'] = 'Запишувам информации за корисниците';
$string['wrongpassword'] = 'Грешна лозинка на даденото корисничко име';
$string['xmldbeditor'] = 'XMLDB уредувач';
$string['yahooid'] = 'Yahoo ид.';
$string['year'] = 'година';
$string['years'] = 'години';
$string['yes'] = 'Да';
$string['youareabouttocreatezip'] = 'Ќе се креира zip датотека која ќе содржи';
$string['youaregoingtorestorefrom'] = 'Ќе се започне процес на обновување за';
$string['youneedtoenrol'] = 'За да ја изведете таа акција треба да се зачлените во овој курс.';
$string['yourlastlogin'] = 'Вашето последно најавување на системот беше';
$string['yourself'] = 'себеси';
$string['yourteacher'] = 'Вашиот $a';
$string['zippingbackup'] = 'Пакувам резервната копија';

?>
