<?PHP // $Id$ 
      // auth.php - created with Moodle 1.6 (2006050506)


$string['alternatelogin'] = 'Se inserir um URL aqui, será utilizado como página de login para este site. A página deverá conter um formulário que tenha a propriedade action definida para <strong>\'$a\'</strong> e campos de retorno <strong>Utilizador</strong> e <strong>Palavra-Chave</strong>.<br />Tenha cuidado para não inserir um URL incorrecto porque pode bloque-a-lo a si neste site.<br /> Deixe esta definição em branco para utilizar a página de login por defeito.';
$string['alternateloginurl'] = 'Login URL alternativo';
$string['auth_cas_baseuri'] = 'URL do servidor (nada se não houver baseUri)<br />Por exemplo, se o servidor CAS responder a host.domaine.fr/CAS/ então<br />cas_baseuri = CAS/';
$string['auth_cas_create_user'] = 'Active isto se pretender inserir utilizadores com autenticação CAS na Base de Dados do Moodle. Senão apenas utilizadores que já existam na Base de Dados Moodle poderão fazer o login.';
$string['auth_cas_enabled'] = 'Active se quiser utilizar autenticação CAS';
$string['auth_cas_hostname'] = 'Hostname do servidor CAS <br />Ex: host.domain.fr';
$string['auth_cas_invalidcaslogin'] = 'Descuple, o seu Login falhou - não pode ser autorizado';
$string['auth_cas_language'] = 'Linguagem escolhida';
$string['auth_cas_logincas'] = 'Ligação de acesso segura';
$string['auth_cas_port'] = 'Porta do servidor CAS';
$string['auth_cas_server_settings'] = 'Configuração do servidor CAS';
$string['auth_cas_text'] = 'Ligação segura';
$string['auth_cas_version'] = 'Versão do CAS';
$string['auth_casdescription'] = 'Este método utiliza um servidor CAS (Central Authentication Service) para autenticar utilizadores num ambiente SSO (Single Sign On). Também poderá utilizar a autenticação simples LDAP. Se o nome de utilizador e Palavra-Chave forem válidos para o CAS, o Moodle cria uma entrada de novo utilizador na sua Base de Dados, aproveitando os atributos do utilizador do LDAP se necessário. Nos próximos login\'s apenas o nome de utilizador e Palavra-chave serão verificados';
$string['auth_castitle'] = 'Utilize um servidor CAS (SSO)';
$string['auth_changepasswordhelp'] = 'Ajuda para alterar Palavra-chave';
$string['auth_changepasswordhelp_expl'] = 'Mostrar ajuda de perca de Palavra-Chave aos utilizadores que perderam a sua $a Palavra-Chave. Será mostrada também ou em vez do <strong>URL para Mudar Palavra-Chave</strong> ou a mudança de Palavra-chave interna do Moodle.';
$string['auth_changepasswordurl'] = 'URL para alterar Palavra-chave';
$string['auth_changepasswordurl_expl'] = 'Especifique o URL a enviar aos utilizadores que perderam a sua $a Palavra-Chave. Defina <strong> a página standard para mudar a Palavra-Chave a utilizar</strong> para <strong>Não</strong>';
$string['auth_common_settings'] = 'Definições comuns';
$string['auth_data_mapping'] = 'Mapa de Dados';
$string['auth_dbdescription'] = 'Este método usa uma tabela numa base de dados externa para verificar se um nome de utilizador e palavra chave são válidos. Se for uma conta nova, a informação de outros campos pode ser também transferida para Moodle.';
$string['auth_dbextrafields'] = '<p>Estes campos são optativos. Pode optar por preencher previamente alguns dos campos do utilizador em Moodle com informação dos campos da <b>base de dados externa</b> que especificar aqui.</p><p>Se deixar estes campos em branco, nada será transferido de LDAP e os valores por omissão do Moodle serão usados.</p><p>De qualquer forma o utilizador poderá editar todos estes campos mais tarde depois de entrar no servidor.';
$string['auth_dbfieldpass'] = 'Nome do campo que contem as palavras chave';
$string['auth_dbfielduser'] = 'Nome do campo que contem os nomes de utilizadores';
$string['auth_dbhost'] = 'Endereço IP do computador que hospeda a base de dados de utilizadores.';
$string['auth_dbname'] = 'Nome da própria base de dados';
$string['auth_dbpass'] = 'Palavra chave para o utilizador acima';
$string['auth_dbpasstype'] = 'Indique o modo que se está a usar no campo de palavra chave. A criptografia MD5 é útil para trabalhar com outras aplicações como PostNuke';
$string['auth_dbtable'] = 'Nome da tabela na base de dados';
$string['auth_dbtitle'] = 'Use uma base de dados externa';
$string['auth_dbtype'] = 'O tipo de base de dados (veja <a href=\"../lib/adodb/readme.htm#drivers\">Documentação do ADOdb</a> para mais pormenores)';
$string['auth_dbuser'] = 'Nome de utilizador para aceder à base de dados';
$string['auth_emaildescription'] = 'Confirmação via correio electrónico é o método de autenticação padrão. Quando o utilizador se inscrever, após ter escolhido o nome de utilizador e palavra chave, será-lhe enviada uma mensagem de confirmação para o seu endereço de correio electrónico. Essa mensagem contem um apontador seguro para uma página onde o utilizador pode confirmar a sua conta. Quando o utilizador entrar no futuro o seu nome de utilizador e palavra chave serão conferidos na base de dados do Moodle.';
$string['auth_emailtitle'] = 'Autenticação baseada no correio electrónico';
$string['auth_fccreators'] = 'Lista de grupos dos quais os membros têm permissóes para criar novas disciplinas. Separe os múltiplos grupos com \';\'. Os nomes deverão ser inseridos exactamente como no servidor FirstClass. O sistema é case-sensitive.';
$string['auth_fcdescription'] = 'Este método utiliza um servidor FirstClass para verificar se um nome de utilizador e Palavra-chave são válidos.';
$string['auth_fcfppport'] = 'Porta do servidor (3333 é a mais comum)';
$string['auth_fchost'] = 'O endereço do servidor FirstClass. Utilize o IP ou o nome DNS';
$string['auth_fcpasswd'] = 'Palavra-chave para a conta relacionada';
$string['auth_fctitle'] = 'Utilize um servidor FirstClass';
$string['auth_fcuserid'] = 'Definido o privilégio \'SubAdministrator\' para o ID de utilizador da conta FirstClass ';
$string['auth_fieldlock'] = 'Bloquear valor';
$string['auth_fieldlock_expl'] = '<p><b>Valor bloqueado:</b> Se activo, irá prevenir que os utilizadores e administradores do Moodle editem um campo directamente. Utilize esta opção se quiser manter os dados no sistema de autorização externo. </p>';
$string['auth_fieldlocks'] = 'Bloquear campos de utilizador';
$string['auth_fieldlocks_help'] = '<p>Pode bloquear os campos de dados dos utilizadores. É útil para sites onde os dados dos utilizadores são mantidos manualmente pelos administradores, editando os registos dos utilizadores ou fazendo o upload utilizando a ferramenta \'Upload utilizadores\'. Se está a bloquear campos requeridos pelo Moodle, verifique que fornece esses dados ao criar contas de utilizadores &emdash; senão as contas ficam inutilizáveis.</p><p>Considere definir o modo de bloqueio para \'Desbloquear se vazio\' para evitar este problema.</p>';
$string['auth_imapdescription'] = 'Este método usa um servidor de IMAP para verificar se um nome de utilizador e palavra chave são válidos.';
$string['auth_imaphost'] = 'Endereço do servidor de IMAP. Use o NÚMERO IP e não o nome no DNS.';
$string['auth_imapport'] = 'Número da porta do servidor IMAP. Geralmente esta é 143 ou 993.';
$string['auth_imaptitle'] = 'Use um servidor IMAP';
$string['auth_imaptype'] = 'Tipo de servidor IMAP. Os servidores IMAP podem usar diferentes métodos de autenticação e negociação.';
$string['auth_ldap_bind_dn'] = 'Se quiser usar o bind-user para procurar utilizadores, especifique-o aqui. Algo como \'cn=ldapuser,ou=public,o=org\'';
$string['auth_ldap_bind_pw'] = 'Palavra chave para o bind-user.';
$string['auth_ldap_bind_settings'] = 'Definições Bind';
$string['auth_ldap_contexts'] = 'Lista dos contextos onde os utilizadores são encontrados. Contextos diferentes separados com \';\'. Por exemplo: \'ou=users,o=org; ou=others,o=org\'';
$string['auth_ldap_create_context'] = 'Se permitir a criação de utilizadores com confirmação por email, especifique o contexto em que os utilizadores são criados. Este contexto deverá ser diferente do de outros utilizadores por medidas de segurança. Não é necessário adicionar este contexto à variável ldap_context, pois o Moodle irá, automáticamente, procurar utilizadores associados a este contexto.';
$string['auth_ldap_creators'] = 'Lista de grupos cujos membros tém permissões para criar novos cursos. Separe vários grupos com \';\'. Geralmente como \'cn=teacher,ou=staff,o=myorg\'';
$string['auth_ldap_expiration_desc'] = 'Seleccione Não para desactivar a verificação de Palavra-chave expirada ou LDAP para ler directamente o tempo de passwordexpiration directamente a partir do LDAP';
$string['auth_ldap_expiration_warning_desc'] = 'Número de dias antes do aviso de Palavra-chave expirada ser activado';
$string['auth_ldap_expireattr_desc'] = 'Opcional: overrides ldap-attribute what stores password expiration time passwordExpirationTime';
$string['auth_ldap_graceattr_desc'] = 'Opcional: Overrides gracelogin attribute';
$string['auth_ldap_gracelogins_desc'] = 'Active a ajuda LDAP gracelogin. Após a Palavra-Chave ter expirado, o utilizador poderá efectuar o login até que a contagem gracelogin seja 0. Ao activar esta definição, será mostrada uma mensagem grace login se a Palavra-Chave expirar.';
$string['auth_ldap_host_url'] = 'Especifique o servidor de LDAP na forma de uma
URL completa, como \'ldap://ldap.myorg.com/\' ou \'ldaps://ldap.myorg.com/\'';
$string['auth_ldap_login_settings'] = 'Definições de Login';
$string['auth_ldap_memberattribute'] = 'Especifica o atributo de utilizador membro, quando os utilizadores pertencem a um grupo. Geralmente \'member\'';
$string['auth_ldap_objectclass'] = 'Opcional: Overrides objectClass utilizados para nomear/procurar utilizadores em ldap_user_type. Normalmente não precisa de modificar isto.';
$string['auth_ldap_opt_deref'] = 'Determina como é que os aliases são manobrados durante a procura. Seleccione um dos seguintes valores: \"Não\" (LDAP_DEREF_NEVER) ou \"Sim\" (LDAP_DEREF_ALWAYS)';
$string['auth_ldap_passwdexpire_settings'] = 'Definições LDAP de Palavra-chave expirada';
$string['auth_ldap_preventpassindb'] = 'Seleccione Sim para prevenir que as Palavras-chave sejam guardadas na BD do Moodle';
$string['auth_ldap_search_sub'] = 'Escreva <> 0; se quiser procurar utilizadores nos sub-contextos.';
$string['auth_ldap_server_settings'] = 'Definições do servidor LDAP';
$string['auth_ldap_update_userinfo'] = 'Actualizar informação de utilizador (nome, apelido, endereço...) de LDAP para Moodle. Para informação sobre a correspondência, consulte /auth/ldap/attr_mappings.php';
$string['auth_ldap_user_attribute'] = 'O atributo usado para nomear/procurar utilizadores. Geralmente \'cn\'.';
$string['auth_ldap_user_settings'] = 'Definições de visualização do utilizador';
$string['auth_ldap_user_type'] = 'Seleccione como é que os utilizadores são gravados no LDAP. Esta definição tambem especifica como irão trabalhar a expiração do login, os grace logins e a criação de utilizadores.';
$string['auth_ldap_version'] = 'A versão do protocolo LDAP que o seu servidor estiver a usar.';
$string['auth_ldapdescription'] = 'Este método fornece autenticação usando um servidor de LDAP. Se o nome de utilizador e palavra chave forem válidos, Moodle cria um novo registo de utilizador na sua base de dados. Este módulo pode ler atributos do utilizador em LDAP e preencher os valores pedidos em Moodle. As seguintes vezes que o utilizador entrar, só serão verificados o nome de utilizador e palavra chave.';
$string['auth_ldapextrafields'] = '<p>Estes campos são optativos. Pode optar por obter a informação para alguns campos em Moodle a partir de informação dos <b>campos LDAP</b> que especificar aqui.</p><p>Se deixar estes campos em branco, nada será transferido de LDAP e os valores por omissão do Moodle serão usados.</p><p>De qualquer forma o utilizador poderá editar todos estes campos mais tarde depois de entrar no servidor.';
$string['auth_ldaptitle'] = 'Use um servidor LDAP';
$string['auth_manualdescription'] = 'Este método elimina qualquer hipótese de os utilizadores poderem criar as suas próprias contas. Todas as contas terão que ser manualmente criadas pelo administrador.';
$string['auth_manualtitle'] = 'Apenas contas manuais';
$string['auth_multiplehosts'] = 'Podem ser especificados vários servidores (p.e. host1.com;host2.com;host3.com)';
$string['auth_nntpdescription'] = 'Este método usa um servidor NNTP para verificar se um nome de utilizador e palavra chave são válidos.';
$string['auth_nntphost'] = 'Endereço do servidor NNTP. Use o NÚMERO IP e não o nome no DNS.';
$string['auth_nntpport'] = 'Porta do servidor NNTP (normalmente 119)';
$string['auth_nntptitle'] = 'Use um servidor NNTP';
$string['auth_nonedescription'] = 'Os utilizadores podem registrar-se e criar contas válidas imediatamente, sem autenticação em nenhum servidor externo e sem nenhuma confirmação por correio. Tenha cuidado se usar esta opção - pense nos problemas de segurança e administração que isto poderia causar.';
$string['auth_nonetitle'] = 'Nenhuma autenticação';
$string['auth_pamdescription'] = 'Este método utiliza PAM para aceder aos usernames nativos neste servidor. Terá que instalar a autenticação <a href=\"http://www.math.ohio-state.edu/~ccunning/pam_auth/\" target=\"_blank\">PHP4 PAM </a> para poder utilizar este módulo.';
$string['auth_pamtitle'] = 'PAM (Pluggable Authentication Modules)';
$string['auth_passwordisexpired'] = 'A sua Palavra-chave expirou. Quer alterá-la agora?';
$string['auth_passwordwillexpire'] = 'A sua Palavra-chave vai expirar dentro de $a dias. Quer alterá-la agora?';
$string['auth_pop3description'] = 'Este método usa um servidor POP3 para verificar se um nome de utilizador e palavra chave são válidos.';
$string['auth_pop3host'] = 'Endereço do servidor POP3. Use o NÚMERO IP e não o nome no DNS.';
$string['auth_pop3mailbox'] = 'Nome da caixa de correio com a qual tentar uma ligação. (normalmente a INBOX)';
$string['auth_pop3port'] = 'Porta do servidor POP3 (normalmente 110)';
$string['auth_pop3title'] = 'Use um servidor POP3';
$string['auth_pop3type'] = 'Tipo de servidor. Se o seu servidor usar certificados de segurança, escolha pop3cert.';
$string['auth_radiusdescription'] = 'Este método utiliza o servidor <a href=\"http://en.wikipedia.org/wiki/RADIUS\" target=\"_blank\">RADIUS</a> para verificar a veracidade do nome de utilizador e a Palavra-Chave';
$string['auth_radiushost'] = 'Endereço do servidor RADIUS';
$string['auth_radiusnasport'] = 'Porta a usar para a ligação';
$string['auth_radiussecret'] = 'Segredo partilhado';
$string['auth_radiustitle'] = 'Utilizar servidor RADIUS';
$string['auth_shib_convert_data'] = 'API de modificação de dados';
$string['auth_shib_convert_data_description'] = 'Pode utilizar esta API para depois poder modificar os dados provenientes do Shibboleth. Leia <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">README</a> para mais instruções.';
$string['auth_shib_convert_data_warning'] = 'O ficheiro não existe ou não está disponível para leitura pelo processo do servidor Web!';
$string['auth_shib_instructions'] = 'Utilize o login <a href=\"$a\">Shibboleth </a> para ter acesso via Shibboleth, se a sua instituição o suportar.<br />Caso contrário utilize o form de login normalmostrado aqui.';
$string['auth_shib_instructions_help'] = 'Aqui deverá fornecer as instruções a explicar o Shibboleth aos seus utilizadores. Serão mostradas na página de login, na secção de instruções. As instruções deverão incluir um link para \"<b>$a</b>\" para os utilizadores clicarem quando quiserem efectuar o login.';
$string['auth_shib_only'] = 'Apenas Shibboleth';
$string['auth_shib_only_description'] = 'Marque esta opção se quiser forçar uma autenticação Shibboleth';
$string['auth_shib_username_description'] = 'Nome da variável de ambiente do servidor web Shibboleth que deverá ser utilizada como nome de utilizador Moodle.';
$string['auth_shibboleth_login'] = 'Login Shibboleth';
$string['auth_shibboleth_manual_login'] = 'Login Manual';
$string['auth_shibbolethdescription'] = 'Com este método os utilizadores serão criados e autenticados utilizando o <a href=\"http://shibboleth.internet2.edu/\" target=\"_blank\">Shibboleth</a>.<br>Leia atentamente <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">README</a> do Shibboleth de como configurar o seu Moodle com o Shibboleth.';
$string['auth_shibbolethtitle'] = 'Shibboleth';
$string['auth_updatelocal'] = 'Actualizar localmente';
$string['auth_updatelocal_expl'] = '<p><b>Update local:</b> Se activo, o campo será actualizado (com autorização externa) cada vez que o utilizador faz login ou exista uma sincronização de utilizadores. Os campos definidos para serem actualizados localmente deverão estar bloqueados.</p>';
$string['auth_updateremote'] = 'Actualizar externamente';
$string['auth_updateremote_expl'] = '<p><b>Update externo:</b> Se activo, a autorização externa será actualizada quando o registo do utilizador for actualizado. Os campos deverão estar desbloquados para que sejam permitidas edições.</p>';
$string['auth_updateremote_ldap'] = '<p><b>Note:</b> Para actualizar dados externos do LDAP é necessário que defina o binddn e o bindpw para um utilizador bind com privilégios de edição a todos os registos do utilizador. Actualmente não preserva os atributos multi-valued, e irá remover valores extra aquando da actualização. </p>';
$string['auth_user_create'] = 'Permitir a criação de utilizadores';
$string['auth_user_creation'] = 'Novos (anonimos) utilizadores podem criar contas de autenticação externa confirmadas por email. Se activar esta opção, lembre-se de configurar as opções no módulo específico para criação de utilizadores.';
$string['auth_usernameexists'] = 'O nome escolhido já existe. Escolha outro.';
$string['authenticationoptions'] = 'Opções de autenticação';
$string['authinstructions'] = 'Aqui pode incluir instruções para os seus utilizadores, para que saibam que tipo de nome de utilizador e palavra chave deverão usar. O texto que escreva aqui aparecerá na página de entrada. Se deixar este campo em branco, não será dadas nenhumas instruções.';
$string['changepassword'] = 'Mude o endereço da palavra chave';
$string['changepasswordhelp'] = 'Aqui pode especificar um local onde os utilizadores podem recuperar ou alterar a sua palavra chave e nome de usuário caso se esqueçam dela. Isto será fornecido aos utilizadores como um botão na página de entrada a servidor e na sua página de utilizador. Se deixar este espaço em branco o botão não aparecerá.';
$string['chooseauthmethod'] = 'Escolha um método de autenticação: ';
$string['createpasswordifneeded'] = 'Criar Palavra-Chave se necessário';
$string['forcechangepassword'] = 'Obrigar a alterar Palavra-chave';
$string['forcechangepassword_help'] = 'Obrigar os utilizadores a alterar a Palavra-chave no próximo Login';
$string['forcechangepasswordfirst_help'] = 'Obrigar os utilizadores a alterar a Palavra-chave no seu primeiro Login';
$string['guestloginbutton'] = 'Botão de entrada como visitante';
$string['infilefield'] = 'Campo necessário no ficheiro';
$string['instructions'] = 'Instruções';
$string['internal'] = 'Interno';
$string['locked'] = 'Bloqueado';
$string['md5'] = 'Criptografia MD5';
$string['passwordhandling'] = 'Campo de Palavra-chave manejável';
$string['plaintext'] = 'Texto simples';
$string['shib_no_attributes_error'] = 'Parece ser um utilizador com autenticação Shibboleth  mas o Moodle não recebeu quaisquer atributos de utilizador. Por favor verifique que o seu Fornecedor de Identidade libertou os atributos necessários ($a) para o Fornecedor de serviços Moodle que está a correr ou então informe o webmaster deste servidor.';
$string['shib_not_all_attributes_error'] = 'O Moodle precisa de certos atributos Shibboleth que não estão presentes no seu caso. Os atributos são: $a<br />Por favor contacte com o webmaster do servidor ou com o seu Fornecedor de Identidade.';
$string['shib_not_set_up_error'] = 'A autenticação Shibboleth não parece estar definida correctamente porque não estão presentes variáveis de ambiente Shibboleth nesta página. Por favor consulte a <a href=\"README.txt\">README</a> para mais instruções de como configurar a autenticação Shibboleth ou contacte o webmaster desta instalação Moodle.';
$string['showguestlogin'] = 'Pode optar por esconder ou mostrar o botão de entrada para visitantes na página de entrada.';
$string['stdchangepassword'] = 'Utilizar a página standard de alteração de Palavra-chave';
$string['stdchangepassword_expl'] = 'Se o sistema de autenticação externa do sistema permitir alterações da Palavra-Chave pelo Moodle, mude isto para Sim. Esta definição sobrepõe o \'URL Mudar Palavra-Chave\'.';
$string['stdchangepassword_explldap'] = 'NOTA: É recomendado utilizar o LDAP sobre um túnel encriptado SSL (ldaps://) se o servidor LDAP for remoto.';
$string['unlocked'] = 'Desbloqueado';
$string['unlockedifempty'] = 'Desbloquear se vazio';
$string['update_never'] = 'Nunca';
$string['update_oncreate'] = 'Em criação';
$string['update_onlogin'] = 'Em todos os Login';
$string['update_onupdate'] = 'Em actualização';

?>
