<?PHP // $Id$ 
      // role.php - created with Moodle 1.8.2+ (2007021520)


$string['addrole'] = 'Adicionar novo cargo atribuível';
$string['allow'] = 'Permitir';
$string['allowassign'] = 'Permitir atribuir cargos';
$string['allowoverride'] = 'Permitir revogar cargos';
$string['assignglobalroles'] = 'Atribuir cargos globais';
$string['assignroles'] = 'Atribuir cargos';
$string['blog:create'] = 'Crear novos tópicos no blog';
$string['blog:manageentries'] = 'Editar e gerir tópicos';
$string['blog:manageofficialtags'] = 'Gerir palavras chave oficiais';
$string['blog:managepersonaltags'] = 'Gerir palavras chave pessoais';
$string['blog:view'] = 'Ver tópicos do blog';
$string['calendar:manageentries'] = 'Gerir eventos no calendário';
$string['calendar:manageownentries'] = 'Gerir os seus próprios eventos no calendário';
$string['capabilities'] = 'Competências';
$string['capability'] = 'Competência';
$string['category:create'] = 'Criar categorias';
$string['category:delete'] = 'Apagar categorias';
$string['category:update'] = 'Actualizar categorias';
$string['category:visibility'] = 'Ver categorias ocultas';
$string['course:activityvisibility'] = 'Ocultar/mostrar actividades';
$string['course:bulkmessaging'] = 'Enviar mensagem a várias pessoas';
$string['course:create'] = 'Criar disciplinas';
$string['course:delete'] = 'Apagar disciplinas';
$string['course:manageactivities'] = 'Gerir actividades';
$string['course:managefiles'] = 'Gerir ficheiros';
$string['course:managegrades'] = 'Gerir notas';
$string['course:managegroups'] = 'Gerir grupos';
$string['course:managemetacourse'] = 'Gerir metadisciplinas';
$string['course:managescales'] = 'Gerir escalas';
$string['course:reset'] = 'Reverter disciplina';
$string['course:sectionvisibility'] = 'Controlar visibilidade das secções';
$string['course:setcurrentsection'] = 'Designar secção actual';
$string['course:update'] = 'Actualizar configurações da disciplina';
$string['course:useremail'] = 'Activar/desactivar endereços de correio electrónico';
$string['course:view'] = 'Ver disciplinas';
$string['course:viewcoursegrades'] = 'Ver notas da disciplina';
$string['course:viewhiddenactivities'] = 'Ver actividades ocultas';
$string['course:viewhiddencourses'] = 'Ver disciplinas ocultas';
$string['course:viewhiddensections'] = 'Ver secções ocultas';
$string['course:viewhiddenuserfields'] = 'Ver campos do utilizador ocultos';
$string['course:viewparticipants'] = 'Ver participantes';
$string['course:viewscales'] = 'Ver escalas';
$string['course:visibility'] = 'Ocultar/mostrar disciplinas';
$string['currentcontext'] = 'Contexto actual';
$string['currentrole'] = 'Cargo actual';
$string['defaultrole'] = 'Cargo por omissão';
$string['defineroles'] = 'Definir cargos';
$string['deleterolesure'] = 'Tem a certeza que quer apagar o cargo \"$a->name\" ($a->shortname)\"?</p><p>Actualmente há $a ->count utilizadores com esse cargo.';
$string['duplicaterole'] = 'Duplicar cargo';
$string['duplicaterolesure'] = 'Tem a certeza que quer duplicar o cargo  \"$a->name ($a->shortname)\"?</p>';
$string['editrole'] = 'Editar cargo';
$string['errorbadrolename'] = 'Nome de cargo incorrecto';
$string['errorbadroleshortname'] = 'Nome de cargo incorrecto';
$string['errorexistsrolename'] = 'Nome de cargo já existente';
$string['errorexistsroleshortname'] = 'Nome de cargo já existente';
$string['existingusers'] = '$a utilizadores existentes';
$string['globalroleswarning'] = 'AVISO! Qualquer cargo que atribua a partir desta página vai ser aplicada aos utilizadores de todo o sítio, incluindo página principal e todas as disciplinas.';
$string['inherit'] = 'Herdar';
$string['legacy:admin'] = 'DELEGAÇÂO de CARGO: Administrador';
$string['legacy:coursecreator'] = 'DELEGAÇÂO de CARGO: Criador de disciplina';
$string['legacy:editingteacher'] = 'DELEGAÇÂO de CARGO: Docente (editor)';
$string['legacy:guest'] = 'DELEGAÇÂO de CARGO: Visitante';
$string['legacy:student'] = 'DELEGAÇÂO de CARGO: Aluno';
$string['legacy:teacher'] = 'DELEGAÇÂO de CARGO: Docente (não editor)';
$string['legacy:user'] = 'DELEGAÇÂO de CARGO: Utilizador autenticado';
$string['legacytype'] = 'Tipo de delegação de cargo';
$string['listallroles'] = 'Mostrar lista de cargos';
$string['manageroles'] = 'Gerir cargos';
$string['metaassignerror'] = 'Não se pode atribuir este cargo ao utilizador \"$a\" porque precisa permissão para gerir metadisciplina.';
$string['metaunassignerror'] = 'O cargo do utilizador \"$a\" foi reatribuido automaticamente; por favor mude melhor cargo atribuido nas disciplinas descendentes.';
$string['my:manageblocks'] = 'Gerir blocos da página MeuMoodle';
$string['nocapabilitiesincontext'] = 'Não existem competências disponíveis neste contexto';
$string['notset'] = 'Não definido';
$string['overrideroles'] = 'Revogar cargos';
$string['overrides'] = 'Revogações';
$string['permissions'] = 'Permissões';
$string['potentialusers'] = '$a utilizadores potenciais';
$string['prevent'] = 'Impedir';
$string['prohibit'] = 'Proibir';
$string['question:export'] = 'Exportar perguntas';
$string['question:import'] = 'Importar perguntas';
$string['question:manage'] = 'Gerir perguntas';
$string['question:managecategory'] = 'Gerir categorias de perguntas';
$string['resetrole'] = 'Restaurar definições por omissão';
$string['resetrolenolegacy'] = 'Apagar permissões';
$string['resetrolesure'] = 'Tem a certeza que quer restaurar o cargo \"$a->name ($a->shortname)\" para o cargo definido por omissão? ?<p></p> Os restauros são retirados do legado seleccionado  ($a->legacytype).';
$string['resetrolesurenolegacy'] = 'Tem a certeza que quer apagar todas as permissões para este cargo \"$a->name ($a->shortname)\"?';
$string['risks'] = 'Riscos';
$string['role:assign'] = 'Atribuir cargos aos utilizadores';
$string['role:manage'] = 'Criar e editar cargos';
$string['role:override'] = 'Revogar cargos de outros';
$string['role:switchroles'] = 'Mudar os cargos';
$string['role:unassignself'] = 'Mudar o seu próprio cargo';
$string['role:viewhiddenassigns'] = 'Ver atribuições ocultas';
$string['roleassignments'] = 'Atribuição de cargos';
$string['roles'] = 'Cargos';
$string['roletoassign'] = 'Cargo a atribuir';
$string['roletooverride'] = 'Cargo a revogar';
$string['selectrole'] = 'Seleccione o cargo a atribuir';
$string['showallroles'] = 'Mostrar os cargos que podem ser atribuidos';
$string['site:accessallgroups'] = 'Ter acesso a todos os grupos';
$string['site:approvecourse'] = 'Aprovar criação de disciplinas';
$string['site:backup'] = 'Fazer cópias de segurança das disciplinas';
$string['site:config'] = 'Mudar configurações do sítio';
$string['site:doanything'] = 'Autorizado a fazer tudo';
$string['site:doclinks'] = 'Mostrar apontadores para documentos de outros sítios';
$string['site:import'] = 'Importar outras disciplinas dentro duma disciplina';
$string['site:manageblocks'] = 'Gerir blocos a nivel do sítio';
$string['site:mnetloginfromremote'] = 'Entrar a partir de um Moodle remoto';
$string['site:mnetlogintoremote'] = 'Navegar para um Moodle remoto.';
$string['site:readallmessages'] = 'Ler todas as mensagens no sítio';
$string['site:restore'] = 'Recuperar disciplinas';
$string['site:trustcontent'] = 'Confiar no conteúdo enviado';
$string['site:uploadusers'] = 'Enviar ficheiro com novos utilizadores';
$string['site:viewfullnames'] = 'Ver sempre o nome completo dos utilizadores';
$string['site:viewparticipants'] = 'Ver os participantes';
$string['site:viewreports'] = 'Ver relatórios';
$string['user:create'] = 'Criar utilizadores';
$string['user:delete'] = 'Apagar utilizadores';
$string['user:editprofile'] = 'Editar perfis de utilizadores';
$string['user:loginas'] = 'Entrar como outros utilizadores';
$string['user:readuserblogs'] = 'Ver todos os blogs de utilizadores';
$string['user:readuserposts'] = 'Ver todas as mensagens enviadas pelos utilizadores';
$string['user:update'] = 'Actualizar perfis de utilizadores';
$string['user:viewdetails'] = 'Ver perfis de utilizadores';
$string['user:viewhiddendetails'] = 'Ver dados de utilizador ocultos';
$string['user:viewuseractivitiesreport'] = 'Ver relatórios de actividade ocultos';
$string['user:viewusergrades'] = 'Ver notas dos utilizadores';
$string['viewrole'] = 'Ver promenores dos cargos atribuidos';
$string['xuserswiththerole'] = 'Utilizadores com o cargo \"$a->role\": $a->number';
$string['assignrolesin'] = 'Atribuir cargos em $a'; // ORPHANED
$string['block:view'] = 'Ver bloco'; // ORPHANED
$string['calendar:managegroupentries'] = 'Gerir eventos de grupo no calendário'; // ORPHANED
$string['globalrole'] = 'Cargo global'; // ORPHANED
$string['grade:edit'] = 'Editar notas'; // ORPHANED
$string['grade:export'] = 'Exportar notas'; // ORPHANED
$string['grade:hide'] = 'Ocultar/mostrar notas ou pontos'; // ORPHANED
$string['grade:import'] = 'Importar notas'; // ORPHANED
$string['grade:lock'] = 'Congelar notas ou pontos'; // ORPHANED
$string['grade:manage'] = 'Gerir pontos das notas'; // ORPHANED
$string['grade:manageletters'] = 'Gerir notas em letras'; // ORPHANED
$string['grade:manageoutcomes'] = 'Gerir resultados das notas'; // ORPHANED
$string['grade:override'] = 'Alterar notas'; // ORPHANED
$string['grade:unlock'] = 'Descongelar notas ou pontos'; // ORPHANED
$string['grade:view'] = 'Ver as próprias notas'; // ORPHANED
$string['grade:viewall'] = 'Ver as notas de outros utilizadores'; // ORPHANED
$string['grade:viewhidden'] = 'Ver notas ocultas para o dono'; // ORPHANED
$string['morethan'] = 'Mais do que $a'; // ORPHANED
$string['notes:manage'] = 'Gerir notas'; // ORPHANED
$string['notes:view'] = 'Ver notas'; // ORPHANED
$string['overriderolesin'] = 'Revogar cargos em $a'; // ORPHANED
$string['question:add'] = 'Adicionar novas perguntas'; // ORPHANED
$string['question:config'] = 'Configurar tipos de perguntas'; // ORPHANED
$string['question:editall'] = 'Editar todas as perguntas'; // ORPHANED
$string['question:editmine'] = 'Editar as suas próprias perguntas'; // ORPHANED
$string['question:moveall'] = 'Deslocar todas as perguntas'; // ORPHANED
$string['question:movemine'] = 'Deslocar as suas próprias perguntas'; // ORPHANED
$string['question:useall'] = 'Usar todas as perguntas'; // ORPHANED
$string['question:usemine'] = 'Usar as suas próprias perguntas'; // ORPHANED
$string['question:viewall'] = 'Ver todas as perguntas'; // ORPHANED
$string['question:viewmine'] = 'Ver as suas próprias perguntas'; // ORPHANED
$string['site:langeditlocal'] = 'Alterar a tradução local'; // ORPHANED
$string['site:langeditmaster'] = 'Editar pacotes linguísticos originais'; // ORPHANED
$string['tag:create'] = 'Criar novas palavras chave'; // ORPHANED
$string['tag:edit'] = 'Editar palavras chave existentes'; // ORPHANED
$string['tag:editblocks'] = 'Editar blocos nas páginas de palavras chave'; // ORPHANED
$string['tag:manage'] = 'Gerir todas as palavras chave'; // ORPHANED
$string['user:changeownpassword'] = 'Mudar a sua própria senha'; // ORPHANED
$string['user:editownprofile'] = 'Editar o seu próprio perfil'; // ORPHANED

?>
