<?PHP // $Id$ 
      // moodle.php - created with Moodle 1.7+ (2006101009)
/*
	Moodle Language Pack in Lao Language
	By Mr. Somsack INTHASONE
	@ Computer Science Department,
	Faculty of Science,National University of Laos ( Dongdok Campus)
	Vientiane Capital, Lao PDR.

	e-Mail: somsacki@yahoo.com or somsacki@nuol.edu.la
	Mobile: 856-20-2245128
	Tel@home: 856-21-7708226
*/

$string['action'] = 'ຕ້ອງການເຮັດ..';
$string['actions'] = 'ຕ້ອງການເຮັດ..';
$string['active'] = 'ການໃຊ້ງານ';
$string['activeusers'] = 'ສະມາຊິກປະຈຸບັນ';
$string['activities'] = 'ກິດຈະກຳທັງໝົດ';
$string['activity'] = 'ກິດຈະກຳ';
$string['activityclipboard'] = 'ກຳລັງຍ້າຍກິດຈະກຳນີ້ : <b>$a</b>';
$string['activityiscurrentlyhidden'] = 'ຂະອໍໄພກິດຈະກຳນີ້ຍັງບໍ່ເປີດໃຊ້ງານ';
$string['activitymodule'] = 'ຊຸດກິດຈະກຳທີ່ໃຊ້ງານ';
$string['activityreport'] = 'ລາຍງານຜົນກິດຈະກຳ';
$string['activityreports'] = 'ລາຍງານຜົນກິດຈະກຳ';
$string['activityselect'] = 'ຍ້າຍກິດຈະກຳທີ່ເລືອກໄປໄວ້ທີ່ອື່ນ';
$string['activitysince'] = 'ກິດຈະກຳ ຕັ້ງແຕ່ $a';
$string['activityweighted'] = 'ກິດຈະກຳຕໍ່ສະມາຊິກ';
$string['add'] = 'ເພີ່ມ';
$string['addactivity'] = 'ເພີ່ມກິດຈະກຳ...';
$string['addadmin'] = 'ເພີ່ມຜູ້ເບິ່ງແຍງລະບົບ';
$string['addcreator'] = 'ເພີ່ມຜູ້ສ້າງລາຍວິຊາ';
$string['added'] = 'ເພີ່ມ $a  ແລ້ວ';
$string['addedrecip'] = 'ເພີ່ມ $a ຜູ້ຮັບໃໝ່';
$string['addedrecips'] = 'ເພີ່ມ $a ຜູ້ຮັບໃໝ່';
$string['addedtogroup'] = 'ເພີ່ມ $a ໃນກຸ່ມຮຽບຮ້ອຍແລ້ວ';
$string['addedtogroupnot'] = 'ຍັງບໍ່ໄດ້ເພີ່ມເຂົ້າໄປໃນກຸ່ມ $a';
$string['addedtogroupnotenrolled'] = 'ຍັງບໍ່ໄດ້ເພີ່ມເຂົ້າໄປໃນກຸ່ມ $a ເພາະຍັງບໍ່ໄດ້ສະໝັກເຂົ້າຮຽນໃນວິຊານີ້';
$string['addinganew'] = 'ເພີ່ມ $a';
$string['addinganewto'] = 'ເພີ່ມ $a->what  ລົງໃນ  $a->to';
$string['addingdatatoexisting'] = 'ເພີ່ມຂໍ້ມູນລົງໃນທີ່ມີຢູ່ແລ້ວ';
$string['addnewcategory'] = 'ເພີ່ມປະເພດ';
$string['addnewcourse'] = 'ເພີ່ມລາຍວິຊາ';
$string['addnewuser'] = 'ເພີ່ມສະມາຊິກ';
$string['addnousersrecip'] = 'ເພີ່ມສະມາຊິກທີ່ບໍ່ສາມາດເຂົ້າເຖິງ $a ລົງໃນລາຍຊື່ຜູ້ຮັບ';
$string['addresource'] = 'ເພີ່ມແຫລ່ງຂໍ້ມູນ...';
$string['address'] = 'ທີ່ຢູ່';
$string['addstudent'] = 'ເພີ່ມນັກຮຽນ';
$string['addteacher'] = 'ເພີ່ມອາຈານ';
$string['admin'] = 'ຜູ້ເບິ່ງແຍງລະບົບ';
$string['adminhelpaddnewuser'] = 'ເພີ່ມສະມາຊິກໃໝ່ດ້ວຍຕົນເອງ';
$string['adminhelpassignadmins'] = 'ຜູ້ເບິ່ງແຍງລະບົບສາມາດເຮັດຫຍັງກໍໄດ້ ແລະໄປທີ່ໃດກໍໄດ້ໃນເວັບ';
$string['adminhelpassigncreators'] = 'ຜູ້ສ້າງລາຍວິຊາສາມາດເພີ່ມລາຍວິຊາໃໝ່ແລະສອນໃນລາຍວິຊາທີ່ສ້າງຂຶ້ນມາ';
$string['adminhelpassignstudents'] = 'ໄປຍັງລາຍວິຊາ ແລະເພີ່ມນັກຮຽນຈາກເມນູຜູ້ເບິ່ງແຍງລະບົບ';
$string['adminhelpassignteachers'] = 'ຄົ້ນຫາລາຍວິຊາຈາກນັ້ນໃຊ້ icon ເພື່ອເພີ່ມຜູ້ສອນ';
$string['adminhelpauthentication'] = 'ເຈົ້າສາມາດໃຊ້ບັນຊີຜູ້ໃຊ້ພາຍໃນຫລືນອກລະບົບຖານຂໍ້ມູນ';
$string['adminhelpbackup'] = 'ຕັ້ງຄ່າການສຳຮອງຂໍ້ມູນອັດຕະໂນມັດ';
$string['adminhelpconfiguration'] = 'ຕັ້ງຄ່າການສະແດງຜົນຂອງເວັບໄຊຕ໌';
$string['adminhelpconfigvariables'] = 'ຕັ້ງຄ່າຕົວແປທີ່ມີຜົນຕໍ່ການເຮັດວຽກຂອງເວັບໄຊຕ໌';
$string['adminhelpcourses'] = 'ລະບຸລາຍວິຊາແລະປະເພດແລ້ວມອບໝາຍຜູ້ຮັບຜິດຊອບ';
$string['adminhelpeditorsettings'] = 'ກຳນົດຄ່າພື້ນຖານຂອງ HTML editor';
$string['adminhelpedituser'] = 'ເບິ່ງລາຍຊື່ສະມາຊິກແລະແກ້ໄຂຂອງໃຜກໍໄດ້';
$string['adminhelpenrolments'] = 'ເລືອກວິທີການຮັບສະມາຊິກເຂົ້າໃຊ້ງານໃນເວັບໄຊຕ໌ ໂດຍສາມາດຄວບຄຸມຈາກພາຍໃນຫລືນອກ Moodle';
$string['adminhelpenvironment'] = 'ກວດສອບ server ວ່າເໝາະສົມກັບຄວາມຕ້ອງການໃນການຕິດຕັ້ງໂປແກມ Moodle';
$string['adminhelpfailurelogs'] = 'ເບິ່ງບັນທຶກການລັອກອິນເຂົ້າສູ່ລະບົບທີ່ບໍ່ສຳເລັດ';
$string['adminhelphealthcenter'] = 'ກວດຈັບບັນຫາຂອງເວັບໄຊຕ໌ອັດຕະໂນມັດ';
$string['adminhelplanguage'] = 'ສຳລັບກວດສອບແລະແກ້ໄຂພາສາປະຈຸບັນ';
$string['adminhelplogs'] = 'ເບິ່ງບັນທຶກກິດຈະກຳທັງໝົດເທິງເວັບໄຊຕ໌';
$string['adminhelpmanageblocks'] = 'ຈັດການ blocks ແລະຕັ້ງຄ່າ';
$string['adminhelpmanagedatabase'] = 'ເຂົ້າໄປຖານຂໍ້ມູນໂດຍກົງ ( ລະວັງ ! )';
$string['adminhelpmanagefilters'] = 'ເລືອກ text filters ແລະຕັ້ງຄ່າທີ່ກ່ຽວຂ້ອງ';
$string['adminhelpmanagemodules'] = 'ຈັດການຕິດຕັ້ງ Module ແລະຕັ້ງຄ່າຕ່າງ ໆ';
$string['adminhelpmymoodle'] = 'ຕັ້ງຄ່າ Moodle blocks ຂອງຂ້ອຍສຳລັບສະມາຊິກ';
$string['adminhelpreports'] = 'ລາຍງານການໃຊ້ງານທັງເວັບໄຊຕ໌';
$string['adminhelpsitefiles'] = 'ສຳລັບເຜີຍແຜ່ໄຟລ໌ທົ່ວໄປຫລືອັບໂຫລດໄຟລ໌ຂໍ້ມູນສຳຮອງ';
$string['adminhelpsitesettings'] = 'ລະບຸໃຫ້ໜ້າແຮກຂອງເວັບໃຫ້ສະແດງຢ່າງໃດ';
$string['adminhelpstickyblocks'] = 'ຕັ້ງຄ່າ blocks ຫລັກທີ່ໃຊ້ສຳລັບທັງ Moodle';
$string['adminhelpthemes'] = 'ເລືອກວ່າຕ້ອງການໃຫ້ເວັບສະແດງຢ່າງໃດ ( ສີ, ຕົວຫນັງສື ແລະ ອື່ນ  ໆ )';
$string['adminhelpuploadusers'] = 'ນຳສະມາຊິກໃໝ່ເຂົ້າຈາກໄຟລ໌';
$string['adminhelpusers'] = 'ເພີ່ມສະມາຊິກແລະຕັ້ງຄ່າການໃຫ້ສິດ';
$string['administration'] = 'ການຈັດການລະບົບ';
$string['administrator'] = 'ຜູ້ເບິ່ງແຍງລະບົບ';
$string['administrators'] = 'ຜູ້ເບິ່ງແຍງລະບົບ';
$string['administratorsall'] = 'ຜູ້ເບິ່ງແຍງລະບົບທັງໝົດ';
$string['administratorsandteachers'] = 'ຜູ້ເບິ່ງແຍງລະບົບແລະອາຈານ';
$string['adminprimarynoedit'] = 'ບໍ່ສາມາດປ່ຽນລະຫັດຜ່ານຂອງຜູ້ເບິ່ງແຍງລະບົບຫລັກໄດ້';
$string['advanced'] = 'ຂັ້ນສູງ';
$string['advancedfilter'] = 'ຄົ້ນຫາລະດັບຂັ້ນສູງ';
$string['advancedsettings'] = 'ຕັ້ງຄ່າລະດັບຂັ້ນສູງ';
$string['again'] = 'ອີກຄັ້ງ';
$string['all'] = 'ທັງໝົດ';
$string['allactions'] = 'ສິ່ງທີ່ເຮັດແລ້ວທັງໝົດ';
$string['allactivities'] = 'ກິດຈະກຳທັງໝົດ';
$string['allchanges'] = 'ການປ່ຽນແປງທັງໝົດ';
$string['alldays'] = 'ຕະຫລອດເວລາ';
$string['allfieldsrequired'] = 'ກະລຸນາເຕີມໃຫ້ຄົບທຸກຊ່ອງ';
$string['allfiles'] = 'ໄຟລ໌ທັງໝົດ';
$string['allgroups'] = 'ກຸ່ມທັງໝົດ';
$string['alllogs'] = 'ບັນທຶກການໃຊ້ງານເວັບທັງໝົດ';
$string['allow'] = 'Allow';
$string['allowguests'] = 'ບຸກຄົນທົ່ວໄປສາມາດເຂົ້າມາສຶກສາໄດ້';
$string['allowinternal'] = 'ໃຫ້ໃຊ້ວິທີອານຸຍາດພາຍໃນໄດ້ດ້ວຍເຊັ່ນກັນ';
$string['allownone'] = 'ບໍ່ອະນຸຍາດ';
$string['allownot'] = 'ບໍ່ອະນຸຍາດ';
$string['allparticipants'] = 'ສະມາຊິກທັງໝົດ';
$string['allteachers'] = 'ອາຈານທັງໝົດ';
$string['alphabet'] = 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,ກ,ຂ,ຄ,ງ,ຈ,ຊ,ຍ,ດ,ຕ,ຖ,ທ,ນ,ບ,ປ,ຜ,ຝ,ພ,ຟ,ມ,ຢ,ຣ,ລ,ວ,ສ,ຫ,ອ,ຮ';
$string['alphanumerical'] = 'ສາມາດເພີ່ມໄດ້ສະເພາະຕົວອັກສອນແລະຕົວເລກເທົ່ານັ້ນ';
$string['alreadyconfirmed'] = 'ຢືນຢັນການລົງທະບຽນຮຽບຮ້ອຍແລ້ວ';
$string['always'] = 'ຕະຫລອດເວລາ';
$string['answer'] = 'ຄຳຕອບ';
$string['approve'] = 'ເຫັນດີ';
$string['areyousuretorestorethis'] = 'ຕ້ອງການເຮັດຕໍ່ໄປຫລືບໍ່?';
$string['areyousuretorestorethisinfo'] = 'ຫລັງຈາກຂັ້ນຕອນນີ້ຈະມີຄຳຖາມໃຫ້ເລືອກວ່າຕ້ອງການເພີ່ມຂໍ້ມູນສຳຮອງລົງໃນລາຍວິຊາທີ່ມີຢູ່ຫລືວ່າສ້າງລາຍວິຊາໃໝ່';
$string['assessment'] = 'ການປະເມີນ';
$string['assignadmins'] = 'ເພີ່ມຜູ້ເບິ່ງແຍງລະບົບ';
$string['assigncreators'] = 'ເພີ່ມຜູ້ສ້າງລາຍວິຊາ';
$string['assignsiteroles'] = 'Assign site-wide roles';
$string['assignstudents'] = 'ເພີ່ມນັກຮຽນ';
$string['assignstudentsnote'] = 'Note: ບໍ່ມີຄວາມຈຳເປັນທີ່ຕ້ອງໃຊ້ໜ້ານີ້ເພາະວ່ານັກຮຽນສາມາດສະໝັກເຂົ້າຮຽນດ້ວຍຕົນເອງ';
$string['assignstudentspass'] = 'ສິ່ງທີ່ຕ້ອງເຮັດຄືແຈ້ງໃຫ້ນັກຮຽນຮູ້ຫັດຜ່ານເພື່ອເຂົ້າສຶກສາໃນລາຍວິຊານີ້ ລະຫັດປະຈຸບັນຄື: \'$a\'';
$string['assignteachers'] = 'ອາຈານຜູ້ຮັບຜິດຊອບ';
$string['authentication'] = 'ການອານຸຍາດ';
$string['autosubscribe'] = 'ສະໝັກເປັນສະມາຊິກ Forum ອັດຕະໂນມັດ';
$string['autosubscribeno'] = 'ບໍ່ : ບໍ່ສະໝັກເປັນສະມາຊິກ Forum ໃດ ໆ ອັດຕະໂນມັດ';
$string['autosubscribeyes'] = 'ແມ່ນແລ້ວ: ສະໝັກເປັນສະມາຊິກ Forum ທັນທີ ທີ່ໂພດຕ໌ກະທູ້';
$string['availability'] = 'ວິຊາທີ່ມີຢູ່';
$string['availablecourses'] = 'ວິຊາທີ່ມີຢູ່';
$string['backtoparticipants'] = 'ກັບໄປຍັງໜ້າລາຍຊື່ສະມາຊິກທັງໝົດ';
$string['backup'] = 'ການສຳຮອງຂໍ້ມູນ';
$string['backupactivehelp'] = 'Choose whether or not to do automated backups.';
$string['backupcancelled'] = 'ຍົກເລີກການສຳຮອງຂໍ້ມູນ';
$string['backupcoursefileshelp'] = 'ຫາກເລືອກ \"ແມ່ນແລ້ວ \"  ໄຟລ໌ທັງໝົດໃນລາຍວິຊານັ້ນ ໆ ຈະມີການສຳຮອງຂໍ້ມູນອັດຕະໂນມັດ';
$string['backupdate'] = 'ມື້ທີ່ສຳຮອງຂໍ້ມູນ';
$string['backupdatenew'] = '  $a->TAG is now $a->weekday, $a->mday $a->month $a->year<br />';
$string['backupdateold'] = '$a->TAG was $a->weekday, $a->mday $a->month $a->year';
$string['backupdaterecordtype'] = '<br />$a->recordtype - $a->recordname<br />';
$string['backupdetails'] = 'ລາຍລະອຽດຂອງການສຳຮອງຂໍ້ມູນ';
$string['backupexecuteathelp'] = 'Choose what time automated backups should run at.';
$string['backupfailed'] = 'ບາງວິຊາຍັງບໍ່ໄດ້ຮັບການບັນທຶກ';
$string['backupfilename'] = 'ຊື່ໄຟລ໌ຂໍ້ມູນສຳຮອງ';
$string['backupfinished'] = 'ການສຳຮອງຂໍ້ມູນສຳເລັດແລ້ວ';
$string['backupincludemoduleshelp'] = 'ເລືອກວ່າຕ້ອງການໃສ່ຂໍ້ມູນຂອງສະມາຊິກຂອງແຕ່ລະລາຍວິຊາລົງໃນການສຳຮອງຂໍ້ມູນອັດຕະໂນມັດຫລືບໍ່';
$string['backupincludemoduleuserdatahelp'] = 'Choose whether you want to include module user data in automated backups.';
$string['backupkeephelp'] = 'ຕ້ອງການເກັບໄຟລ໌ຂໍ້ມູນສຳຮອງຍ້ອນຫລັງຈຳນວນຈັກໄຟລ໌';
$string['backuplogdetailed'] = 'ບັນທຶກລາຍລະອຽດການສຳຮອງຂໍ້ມູນ';
$string['backuploglaststatus'] = 'ບັນທຶກການສຳຮອງຂໍ້ມູນເທື່ອລ່າສຸດ';
$string['backuplogshelp'] = 'ເລືອກຂໍ້ນີ້ຫາກຕ້ອງການເພີ່ມຂໍ້ມູນການໃຊ້ງານຂອງແຕ່ລະລາຍວິຊາລົງໃນການສຳຮອງຂໍ້ມູນອັດຕະໂນມັດ';
$string['backupmetacoursehelp'] = 'ຫາກເປີດໃຊ້ງານຈະມີການລວມຂໍ້ມູນສຳລັບລາຍວິຊານັ້ນລົງໄປໃນການສຳຮອງຂໍ້ມູນ ມູນອັດຕະໂນມັດດ້ວຍ';
$string['backupnameformat'] = '%%Y%%m%%d-%%H%%M';
$string['backupnoneusersinfo'] = 'Notice: ເຈົ້າເລືອກທີ່ຈະບໍ່ມີການສຳຮອງຂໍ້ມູນຂອງສະມາຊິກ ດັ່ງນັ້ນໂມດູນສຳຮອງຂໍ້ມູນຈະຢູ່ໃນ mod  \"ບໍ່ບັນທຶກຂໍ້ມູນສະມາຊິກ\"  ຢ່າງໃດກໍຕາມໂມດູນ \"ແບບຝຶກຫັດ\" ແລະ \"Forum\" ບໍ່ສາມາດໃຊ້ mod ດັ່ງກ່າວນີ້ໄດ້';
$string['backupnonisowarning'] = 'ຄຳເຕືອນ : ຂໍ້ມູນສຳຮອງນີ້ມາຈາກ Module ທີ່ບໍ່ເປັນ unicode ( ເວີລ໌ຊັນກ່ອນໜ້າ 1.6) ຂໍ້ມູນດັ່ງກ່າວປະກອບໄປດ້ວຍຊຸດອັກຂະທີ່ບໍ່-ແມ່ນ IS-8859-1  ອາດເຮັດໃຫ້ເກີດບັນຫາໃນການກູ້ຄືນໄດ້  ເບິ່ງລາຍລະອຽດເພິ່ມເຕິມທີ່<a  href=\"http://docs.moodle.org/en/Backup_FAQ\">FAQ ການກູ້ຄືນ</a>';
$string['backuporiginalname'] = 'ຊື່ຂອງຂໍ້ມູນສຳຮອງ';
$string['backupsavetohelp'] = 'ໃສ່ຊື່ Path ຂອງ Directory ທີ່ຕ້ອງການບັນທຶກໄຟລ໌ຂໍ້ມູນສຳຮອງ <br/> (leave blank to save in its course default dir)';
$string['backupschedulehelp'] = 'Choose which days of the week to perform automated backups.';
$string['backuptakealook'] = 'ເຈົ້າສາມາດເປີດເບິ່ງບັນທຶກການສຳຮອງຂໍ້ມູນໃນ $a';
$string['backupuserfileshelp'] = 'ເລືອກ ວ່າຕ້ອງການບັນທຶກຂໍ້ມູນຂອງສະມາຊິກລົງໄປໃນການສຳຮອງຂໍ້ມູນພ້ອມກັນຫລືບໍ່?';
$string['backupusershelp'] = 'ເລືອກ ວ່າຕ້ອງການບັນທຶກຂໍ້ມູນສະມາຊິກທຸກຄົນຫລືວ່າຕ້ອງການພຽງສະມາຊິກໃນລາຍວິຊາ';
$string['backupversion'] = 'Backup Version';
$string['block'] = 'Block';
$string['blockconfiga'] = 'ຕັ້ງຄ່າ $a block';
$string['blockconfigbad'] = 'Block ນີ້ໄດ້ຮັບການເພີ່ມບໍ່ຖືກວິທີຈຶ່ງບໍ່ສາມາດສະແດງໜ້າການຕັ້ງຄ່າໄດ້';
$string['blockdeleteconfirm'] = 'ແນ່ໃຈວ່າຕ້ອງກາລົບ Block \'$a\' ? ຂໍ້ມູນທັງໝົດກ່ຽວກັບ Block ນີ້ຈະຖືກລົບອອກຈາກຖານຂໍ້ມູນໄປດ້ວຍ';
$string['blockdeletefiles'] = 'ມີການລືບຂໍ້ມູນທັງໝົດທີ່ກ່ຽວກັບ Block \'$a->block\' ອອກຈາກຖານຂໍ້ມູນຮຽບຮ້ອຍແລ້ວ ເພື່ອໃຫ້ການລືບສຳເລັດຢ່າງສົມບູນເຈົ້າຄວນລຶບ Block ໃນ $a->directory ອອກຈາກ Server ເພື່ອປ້ອງກັນ Block ເພີ່ມຕົວມັນເອງເຂົ້າມາໃໝ່';
$string['blocks'] = 'Blocks';
$string['blocksaddedit'] = 'ເພີ່ມ/ແກ້ໄຂ Block';
$string['blockseditoff'] = 'ປິດການແກ້ໄຂ Block';
$string['blocksediton'] = 'ເປີດການແກ້ໄຂ Block';
$string['blocksetup'] = 'ຕັ້ງຄ່າຕາຕະລາງ Block';
$string['blocksuccess'] = 'ຕັ້ງຄ່າສຳເລັດແລ້ວ $a  ຕາລາງ';
$string['bycourseorder'] = 'ລຽງຕາມລຳດັບວິຊາ';
$string['byname'] = 'ໂດຍ $a';
$string['bypassed'] = 'ຂ້າມ';
$string['cachecontrols'] = 'ການຄວບຄຸມຄວາມຈຳຊົ່ວຄາວ';
$string['cancel'] = 'ຍົກເລີກ';
$string['categories'] = 'ປະເພດຂອງລາຍວິຊາ';
$string['category'] = 'ປະເພດ';
$string['categoryadded'] = 'ເພີ່ມປະເພດ \'$a\' ຮຽບຮ້ອຍແລ້ວ';
$string['categorydeleted'] = 'ລືບປະເພດ \'$a\'ຮຽບຮ້ອຍແລ້ວ';
$string['categoryduplicate'] = 'ປະເພດ \'$a\' ມີຢູ່ແລ້ວ';
$string['changedpassword'] = 'ປ່ຽນລະຫັດຜ່ານຮຽບຮ້ອຍແລ້ວ';
$string['changepassword'] = 'ປ່ຽນລະຫັດຜ່ານ';
$string['changessaved'] = 'ບັນທຶກການປ່ຽນແປງແລ້ວ';
$string['check'] = 'ກວດສອບ';
$string['checkall'] = 'ກວດສອບທັງໝົດ';
$string['checkingbackup'] = 'ກວດສອບຂໍ້ມູນສຳຮອງ';
$string['checkingcourse'] = 'ກວດສອບລາຍວິຊາ';
$string['checkingforbbexport'] = 'ກວດສອບການສົ່ງອອກໄປຍັງ BlackBoard';
$string['checkinginstances'] = 'ກວດສອບຂັ້ນຕອນ';
$string['checkingsections'] = 'ກວດສອບສ່ວນຕ່າງ ໆ';
$string['checklanguage'] = 'ກວດສອບພາສາ';
$string['checknone'] = 'ບໍ່ຕ້ອງກວດສອບ';
$string['childcoursenotfound'] = 'ບໍ່ພົບລາຍວິຊາທີ່ຕ້ອງການ';
$string['childcourses'] = 'ລາຍວິຊາໃນຫລັກສູດ';
$string['choose'] = 'ເລືອກ';
$string['choosecourse'] = 'ເລືອກລາຍວິຊາ';
$string['chooseenrolmethod'] = 'ວິທີການໃນການຮັບເຂົ້າຮຽນ';
$string['chooselivelogs'] = 'ຫລືເບິ່ງກິດຈະກຳທີ່ມີຂະນະນີ້';
$string['chooselogs'] = 'ເລືອກໄຟລ໌ບັນທຶກການໃຊ້ງານເວັບໄຊຕ໌ທີ່ຕ້ອງການເບິ່ງ';
$string['choosereportfilter'] = 'ເລືອກລາຍງານຂອງ Filter ທີ່ຕ້ອງການ';
$string['choosetheme'] = 'ເລືອກຮູບແບບTheme';
$string['chooseuser'] = 'ເລືອກສະມາຊິກ';
$string['city'] = 'ແຂວງ/ເມືອງ';
$string['emailactive'] = 'e-Mail ທີ່ໃຊ້ການໄດ້';
$string['emailagain'] = 'ໃສ່ e-Mail ອີກຄັ້ງ';
$string['emailcharset'] = 'ອັກສອນທີ່ຕ້ອງການໃຊ້ໃນ e-Mail';
$string['emailconfirm'] = 'ຢືນຢັນ account ຂອງເຈົ້າ';
$string['emailconfirmation'] = 'ສະບາຍດີ $a-> firstname,

ທ່ານໄດ້ສະມັກເປັນສະມາຊິກໃໝ່ໃນເວັບໄຊຕ໌ \'$a-> sitename\' <br> ໂດຍໃຊ້ e-Mail ນີ້ໃນການສະມັກ

ກະລຸນາຍືນຍັນການໃຊ້ Account ນີ້ໂດຍການຄິກທີ່ລິງກ໌ດ້ານລຸມນີ້ <br>

$a->link   </br>

ໃນໂປແກມຮັບສົ່ງ e-Mail ທົ່ວໄປເຈົ້າຈະເຫັນລິງກ໌ດ້ານເທິງ <br> ປາກົດເປັນສີຟ້າ ແລະສາມາດຄິກເພື່ອຢືນຢັນ <br> ໃນກໍລະນີທີ່ບໍ່ສາມາດຄິກທີ່ລິງກ໌ໄດ້ <br> ໃຫ້ Copy ລິງກ໌ດັ່ງກ່າວແລ້ວນຳໄປກ່າຍໃນເວັບບຣາວເຊີລ໌

ຈາກຜູ້ເບິ່ງແຍງລະບົບ$a-> sitename,
$a->admin';
$string['emailconfirmationsubject'] = '$a: ການຢືນຢັນ Account <P> e-Mail ສົ່ງໄປໃຫ້ເຈົ້າທີ່ <B> $a </B>';
$string['emailconfirmsent'] = '<P>ປະກອບໄປດ້ວຍວິທີການລົງທະບຽນເທື່ອສຸດທ້າຍ <P> ຖ້າຫາກເຈົ້າມີບັນຫາໃນການລົງທະບຽນ ກະລຸນາຕິດຕໍ່ຜູ້ເບິ່ງແຍງລະບົບ';
$string['firstdayofweek'] = '0';
$string['firstname'] = 'ຊື່';
$string['firsttime'] = 'ເຈົ້າເຂົ້າມາທີ່ນິ້ເປັນເທື່ອທຳອິດຫຼືບໍ່?';
$string['forcepasswordchangehelp'] = 'ໃຫ້ສະມາຊິກປ່ຽນລະຫັດຜ່ານໃນການເຂົ້າສູ່ລະບົບເທື່ອຕໍ່ໄປ';
$string['forcepasswordchangenotice'] = 'ກະລຸນາປ່ຽນລະຫັດຜ່ານກ່ອນໄປຍັງຂັ້ນຕອນຕໍ່ໄປ';
$string['forcetheme'] = 'ບັງຄັບການໃຊ້ Theme';
$string['forgotaccount'] = 'ລະຫັດຜ່ານຫາຍ?';
$string['forgotten'] = 'ລືມຊື່ຜູ້ໃຊ້ຫລືລະຫັດຜ່ານ?';
$string['format'] = 'ຮູບແບບ';
$string['formathtml'] = 'ໃຊ້ໂຄ້ດ HTML';
$string['formatlams'] = 'ຮູບແບບ LAMS';
$string['formatmarkdown'] = 'ຮູບແບບ Markdown';
$string['formatplain'] = 'ຮູບແບບ ຂໍ້ຄວາມ (Plain Text)';
$string['formatscorm'] = 'ຮູບແບບ SCORM';
$string['formatsocial'] = 'ຮູບແບບ ກຸ່ມສົນທະນາ';
$string['formattext'] = 'ຮູບແບບ ອັດໂນມັດ';
$string['formattexttype'] = 'ຮູບແບບ';
$string['formattopics'] = 'ຮູບແບບຫົວຂໍ້';
$string['formattopicsajax'] = 'ຮູບແບບຫົວຂໍ້- AJAX';
$string['formatweeks'] = 'ຮູບແບບ ລາຍອາທິດ';
$string['formatweekscss'] = 'ຮູບແບບ ລາຍອາທິດ: ໃຊ້ CSS/ບໍ່ມີຕາລາງ';
$string['formatwiki'] = 'ຮູບແບບ Wiki-like';
$string['institution'] = 'ສະຖາບັນ';
$string['instudentview'] = 'ມຸມມອງນັກຮຽນ';
$string['invalidemail'] = 'e-Mail ບໍ່ຖືກຕ້ອງ';
$string['invalidlogin'] = 'Oops! ລັອກອິນບໍ່ຖືກຕ້ອງກະລຸນາກວດສອບຄືນ';
$string['ip_address'] = 'ໝາຍເລກ IP';
$string['jump'] = 'ໄປ';
$string['jumpto'] = 'ໄປຍັງ...';
$string['keep'] = 'ເກັບ';
$string['keepsearching'] = 'ຄົ້ນຫາຕໍ່ໄປ';
$string['langltr'] = 'ພາສາຈາກຊ້າຍໄປຂວາ';
$string['langrtl'] = 'ພາສາຈາກຂວາໄປຊ້າຍ';
$string['language'] = 'ພາສາທີ່ໃຊ້ໃນເວັບ';
$string['languagegood'] = 'ພາສາໃຊ້ Version ລ່າສຸດແລ້ວ';
$string['lastaccess'] = 'ເຂົ້າມາເທື່ອສຸດທ້າຍເມື່ອ';
$string['lastedited'] = 'ແກ້ໄຂເທື່ອສຸດທ້າຍ';
$string['lastlogin'] = 'ເຂົ້າມາເທື່ອສຸດທ້າຍເມື່ອ';
$string['lastmodified'] = 'ແກ້ໄຂເທື່ອສຸດທ້າຍ';
$string['lastname'] = 'ນາມສະກຸນ';
$string['lastyear'] = 'ປີກາຍ';
$string['latestlanguagepack'] = 'ກວດສອບຫາໄຟລ໌ພາສາລ່າສຸດໃນ moodle.org';
$string['latestnews'] = 'ຂ່າວລ່າສຸດ';
$string['leavetokeep'] = 'ປະໄວ້ຫາກຕ້ອງການໃຊ້ລະຫັດເດີມ';
$string['license'] = 'ສັນຍາອານຸຍາດໂດຍ GPL';
$string['liketologin'] = 'ຕ້ອງການເຂົ້າສູ່ລະບົບດ້ວຍ account ຂອງເຈົ້າຕອນນີ້ຫລືບໍ່?';
$string['list'] = 'ລາຍຊື່';
$string['listfiles'] = 'ລາຍຊື່ຂອງໄຟລ໌ທັງໝົດໃນ $a';
$string['listofallpeople'] = 'ລາຍຊື່ສະມາຊິກທັງໝົດ';
$string['livelogs'] = 'ບັນທຶກການໃຊ້ງານເວັບໄຊຕ໌ເລີ່ມຈາກຊົ່ວໂມງທີ່ຜ່ານມາ';
$string['locale'] = 'en.UTF-8';
$string['location'] = 'ທີ່ຕັ້ງ';
$string['log_excel_date_format'] = 'yyyy mmmm d h:mm';
$string['loggedinas'] = 'ເຈົ້າເຂົ້າສູ່ລະບົບໃນຊື່ $a';
$string['loggedinasguest'] = 'ເຈົ້າເຂົ້າສູ່ລະບົບໃນຖານະບຸກຄົນທົ່ວໄປ';
$string['loggedinnot'] = 'ເຈົ້າຍັງບໍ່ໄດ້ເຂົ້າສູ່ລະບົບ->';
$string['login'] = 'ເຂົ້າສູ່ລະບົບ';
$string['login_failure_logs'] = 'ບັນທຶກການເຂົ້າສູ່ລະບົບທີ່ລົ້ມເຫລວ';
$string['loginalready'] = 'ເຈົ້າເຂົ້າສູ່ລະບົບຮຽບຮ້ອຍແລ້ວ';
$string['loginas'] = 'ເຂົ້າສູ່ລະບົບໃນຊື່ນີ້';
$string['loginaspasswordexplain'] = '<p>ເຈົ້າຕ້ອງໃສ່ລະຫັດຜ່ານພິເສດ ເພື່ອໃຊ້ງານໃນສ່ວນນີ້ <br/> ຖ້າຫາກບໍ່ຮູ້ໃຫ້ສອບຖາມ ຜູ້ເບິ່ງແຍງລະບົບ</p>';
$string['loginguest'] = 'ເຂົ້າສູ່ລະບົບໃນຖານະບຸກຄົນທົ່ວໄປ';
$string['loginsite'] = 'ລັອກອິນເຂົ້າເວັບ';
$string['loginsteps'] = 'ສະບາຍດີ <p> ກະລຸນາສະມັກສະມາຊິກໃໝ່ເພື່ອທີ່ເຈົ້າຈະສາມາດເຂົ້າຮຽນໄດ້ໃນແຕ່ລະວິຊາ. ກະລຸນາເຮັດຕາມຂັ້ນຕອນຕໍ່ໄປນີ້
<OL size=2>
   <LI> ຂຽນແບບ Form <A HREF=$a> ສະໝັກສະມາຊິກໃໝ່ </A> 
   <LI> ລະບົບຈະການສົ່ງ e-Mail ໄປຍັງອີເມນທີ່ເຈົ້າໃຫ້ໄວ້ <LI> ອ່ານ e-Mail ຈາກນັ້ນຄິກທີ່ ລິງກ໌ໃນ e-Mail ນັ້ນ 
   <LI> ເມື່ອຄິກແລ້ວ Account ຂອງເຈົ້າຈະໄດ້ຮັບການຢືນຢັນແລະສາມາດລັອກອິນເຂົ້າສູ່ລະບົບໄດ້ທັນທີ
   <LI> ເລືອກລາຍວິຊາທີ່ຕ້ອງການເຂົ້າຮຽນ 
   <LI> ຖ້າຫາກມີການຖາມໃຫ້ໃສ່ລະຫັດໃນການເຂົ້າຮຽນ ໃຫ້ໃສ່ລະຫັດທີ່ອາຈານຂອງເຈົ້າໃຫ້ໄວ້ 
 <LI> ນັບຈາກນີ້ເຈົ້າສາມາດເຂົ້າໄປສຶກສາແລະເຮັດກິດຈະກຳໃນແຕ່ລະລາຍວິຊາໄດ້ ໂດຍເທື່ອຕໍ່ໄປພຽງແຕ່ໃສ່ຊື່ຜູ້ໃຊ້ (Username) ແລະລະຫັດຜ່ານ (Password) ຈາກໜ້ານີ້ </OL>';
$string['loginstepsnone'] = 'ສະບາຍດີ <P> ກະລຸນາສະໝັກສະມາຊິກໃໝ່ເພື່ອທີ່ເຈົ້າຈະສາມາດ ເຂົ້າໄປຍັງບົດຮຽນຕ່າງ ໆໄດ້ <P> ຖ້າຫາກມີການເລືອກຊື່ຜູ້ໃຊ້ທີ່ເຈົ້າຕ້ອງການໄປແລ້ວ ກະລຸນາເລືອກຊື່ໃໝ່';
$string['loginto'] = 'ເຂົ້າສູ່ລະບົບໃນຊື່  $a';
$string['loginusing'] = 'ເຂົ້າສູ່ລະບົບໂດຍໃຊ້ຊື່ຜູ້ໃຊ້ແລະລະຫັດຜ່ານຂອງເຈົ້າ';
$string['logout'] = 'ອອກຈາກລະບົບ';
$string['logs'] = 'Logs';
$string['logtoomanycourses'] = '[<a href=\"$a-> url\"> ວິຊາທັງໝົດ </a>]';
$string['logtoomanyusers'] = '[<a href=\"$a-> url\"> ສະມາຊິກທັງໝົດ </a>]';
$string['lookback'] = 'ເບິ່ງຄືນ';
$string['mailadmins'] = 'ແຈ້ງຜູ້ເບິ່ງແຍງລະບົບ';
$string['mailstudents'] = 'ແຈ້ງນັກຮຽນ';
$string['mailteachers'] = 'ແຈ້ງນັກຮຽນ';
$string['mainmenu'] = 'ໜ້າຫລັກ';
$string['makeafolder'] = 'ສ້າງ folder';
$string['makeeditable'] = 'ຫາກຕ້ອງການແກ້ໄຂ  \'$a\'  ຜ່ານເວັບໄດ້ຄວນປ່ຽນ chmod ຂອງໄຟລ໌ເປັນ 777 ກ່ອນ';
$string['manageblocks'] = 'Blocks';
$string['managecourses'] = 'ຈັດການລາຍວິຊາ';
$string['managedatabase'] = 'ຈັດການຖານຂໍ້ມູນ';
$string['managefilters'] = 'ຈັດການ Filters';
$string['new'] = 'ໃໝ່';
$string['newaccount'] = 'ບັນຊີຜູ້ໃຊ້ໃໝ່';
$string['participants'] = 'ນັກຮຽນແລະຜູ້ສົນໃຈ';
$string['participationreport'] = 'ລາຍງານການມີສ່ວນຮ່ວມ';
$string['password'] = 'ລະຫັດຜ່ານ';
$string['passwordchanged'] = 'ລະຫັດຜ່ານປ່ຽນແປງຮຽບຮ້ອຍແລ້ວ';
$string['passwordconfirmchange'] = 'ຢືນຢັນການປ່ຽນລະຫັດຜ່ານ';
$string['passwordextlink'] = 'ລິງກ໌ໄປຍັງຫນ້າທີ່ຕ້ອງການກູ້ລະຫັດຜ່ານຄືນ';
$string['passwordforgotten'] = 'ລືມລະຫັດຜ່ານ';
$string['passwordforgotteninstructions'] = 'ເຈົ້າສາມາດເລືອກໃຊ້ ຊື່ຜູ້ໃຊ້ ຫຼື e-Mail ທີ່ໄດ້ລົງທະບຽນໄວ້ກັບທາງເວັບໄຊຕ໌';
$string['passwordnohelp'] = 'ບໍ່ສາມາດຫາລະຫັດຜ່ານຂອງເຈົ້າໄດ້ ກະລຸນາຕິດຕໍ່ຜູ້ເບິ່ງແຍງລະບົບ';
$string['passwordrecovery'] = 'ໃຊ້, Help ໃນການເຂົ້າສູ່ລະບົບດ້ວຍ';
$string['returningtosite'] = 'ກັບມາທີ່ເວັບໄຊຕ໌ນີ້?';
$string['sites'] = 'ເວັບໄຊຕ໌';
$string['sitesection'] = 'ສະແດງສ່ວນສະແດງຫົວຂໍ້';
$string['sitesettings'] = 'ການຕັ້ງຄ່າຂອງເວັບໄຊຕ໌';
$string['siteteachers'] = 'ອາຈານປະຈຳເວັບໄຊຕ໌';
$string['size'] = 'ຂະໜາດ';
$string['sizeb'] = 'ໄບຕ໌';
$string['sizegb'] = 'ກິກະໄບຕ໌';
$string['sizekb'] = 'ກິໂລໄບຕ໌';
$string['sizemb'] = 'ເມກະໄບຕ໌';
$string['skipped'] = 'ຂ້າມ';
$string['socialheadline'] = 'ຫົວຂໍ້ລ່າສຸດ ໃນ Forum';
$string['someallowguest'] = 'ບຸກຄົນທົ່ວໄປສາມາດເຂົ້າຊົມໄດ້ສະເພາະບາງວິຊາ';
$string['sortby'] = 'ລຽງລຳດັບໂດຍ';
$string['specifyname'] = 'ຕ້ອງກຳນົດຊື່';
$string['starpending'] = '([*] = ຫລັກສູດທີ່ລໍການອານຸມັດ)';
$string['startdate'] = 'ມື້ເລີ່ມຕົ້ນລາຍວິຊາ';
$string['startsignup'] = 'ສະມັກປັນສະມາຊິກ';
$string['state'] = 'ແຂວງ';
$string['statistics'] = 'ສະຖິຕິ';
$string['stats'] = 'ສະຖິຕິ';
$string['statslogins'] = 'ເຂົ້າສູ່ລະບົບ';
$string['statsmodedetailed'] = 'ມຸມມອງ (ຜູ້ໃຊ້) ໂດຍລະອຽດ';
$string['statsmodegeneral'] = 'ມຸມມອງທົ່ວໄປ';
$string['user'] = 'ສະມາຊິກ';
$string['username'] = 'ຊື່ຜູ້ໃຊ້';
$string['webpage'] = 'ເວັບເພດ';
$string['week'] = 'ອາທິດ';
$string['weekhide'] = 'ຊ່ອນອາທິດນີ້ຈາກ $a';
$string['weeklyoutline'] = 'ໂຄງສ້າງລາຍອາທິດ';
$string['weekshow'] = 'ສະແດງອາທິດນີ້ແກ່ $a';
$string['welcometocourse'] = 'ຍິນດີຕ້ອນຮັບສູ່ $a';
$string['welcometocoursetext'] = 'ເຈົ້າໄດ້ສະໝັກເປັນນັກຮຽນວິຊາ $a->coursename! 
ຂໍ້ແນະນຳສຳລັບທ່ານທີ່ຍັງບໍ່ໄດ້ກໍ່ການແກ້ໄຂປະຫວັດສ່ວນຕົວ ທ່ານຄວນແກ້ໄຂປະຫວັດໃຫ້ຖືກຕ້ອງ ໂດຍການເຂົ້າໄປແກ້ໄຂໃນໜ້າລິງກ໌ຕໍ່ໄປນີ້ $a->profileurl';
$string['whattocallzip'] = 'ຕັ້ງຊື່ zip ໄຟລ໌';
$string['withchosenfiles'] = 'ໂດຍໄຟລ໌ທີ່ເລືອກ';
$string['withoutuserdata'] = 'ບໍ່ລວມຂໍ້ມູນສະມາຊິກ';
$string['withselectedusers'] = 'ລວມສະມາຊິກທີ່ເລືອກ';
$string['withuserdata'] = 'ລວມຂໍ້ມູນສະມາຊິກ';
$string['wordforstudent'] = 'ຄຳສຳລັບເອີ້ນນັກຮຽນ';
$string['wordforstudenteg'] = 'ເຊັ່ນ ນັກຮຽນ,ນັກສຶກສາ,ຜູ້ຮ່ວມເຮັດກິດຈະກຳ...';
$string['wordforstudents'] = 'ຄຳສຳລັບເອີ້ນນັກຮຽນ';
$string['wordforstudentseg'] = 'ເຊັ່ນ ນັກຮຽນ,ນັກສຶກສາ,ຜູ້ຮ່ວມເຮັດກິດຈະກຳ...';
$string['wordforteacher'] = 'ຄຳສຳລັບເອີ້ນຜູ້ສອນ';
$string['wordforteachereg'] = 'ເຊັ່ນ ຄູ,ອາຈານ,ຜູ້ສອນ..';
$string['wordforteachers'] = 'ຄຳສຳລັບເອີ້ນຜູ້ສອນ';
$string['wordforteacherseg'] = 'ເຊັ່ນ ຄູ,ອາຈານ,ຜູ້ສອນ...';

?>
