<?PHP // $Id$ 
      // assignment.php - created with Moodle 1.9 + (Build: 20080409) (2007101509)


$string['allowdeleting'] = '允許刪除';
$string['allowmaxfiles'] = '上傳檔案的最大數量';
$string['allownotes'] = '允許加註釋';
$string['allowresubmit'] = '允許重新繳交';
$string['alreadygraded'] = '您的作業已經評分完畢,不允許再繳交!';
$string['assignment:grade'] = '作業評分';
$string['assignment:submit'] = '繳交作業';
$string['assignment:view'] = '檢視作業';
$string['assignmentdetails'] = '作業詳細說明';
$string['assignmentmail'] = '$a->teacher 對您的作業 $a->assignment 給了意見回饋。
您可以在作業：$a->url 後面看到它。';
$string['assignmentmailhtml'] = '$a->teacher 對您的作業 \'<i>$a->assignment</i>\' 給了意見回饋。<br /><br />　您可以在　<a href=\"$a->url\">您的作業</a>　後面看到這些回饋。';
$string['assignmentname'] = '作業名稱';
$string['assignmenttype'] = '作業類型';
$string['availabledate'] = '開始日期';
$string['cannotdeletefiles'] = '發生錯誤！無法刪除檔案';
$string['comment'] = '評閱';
$string['commentinline'] = '線上評閱';
$string['configitemstocount'] = '學生繳交線上作業的計數單位';
$string['configmaxbytes'] = '本網站對所有作業的預設最大作業檔案上傳限制。';
$string['configshowrecentsubmissions'] = '在最新活動報告中，所有人都可以看到作業繳交通知。';
$string['confirmdeletefile'] = '您確定要刪除這個檔案嗎？<br /><strong>$a</strong>';
$string['deleteallsubmissions'] = '刪除所有作業';
$string['deletefilefailed'] = '檔案刪除失敗。';
$string['description'] = '說明';
$string['draft'] = '草稿';
$string['duedate'] = '截止日期';
$string['duedateno'] = '未過期';
$string['early'] = '$a 之前';
$string['editmysubmission'] = '修改繳交的作業';
$string['emailstudents'] = '用電子郵件提醒學生';
$string['emailteachermail'] = '$a->username已經更新他們繳交的\'$a->assignment\'作業

可以在這裡看到:
$a->url';
$string['emailteachermailhtml'] = '$a->username已經更新他們繳交的<i>\'$a->assignment\'</i>作業
它可在網站的<a href=\"$a->url\">此處</a>看到:';
$string['emailteachers'] = '電子郵件通知教師';
$string['emptysubmission'] = '您尚未繳交任何作業';
$string['enableemailnotification'] = '寄發通知郵件';
$string['existingfiledeleted'] = '目前的檔案 $a 已被刪除。';
$string['failedupdatefeedback'] = '更新使用者 $a 的回饋時失敗';
$string['feedback'] = '回饋';
$string['feedbackfromteacher'] = '$a 給予的回饋';
$string['feedbackupdated'] = '替 $a 個人更新繳交後的回饋';
$string['finalize'] = '已無作業';
$string['finalizeerror'] = '發生錯誤!作業繳交未完成';
$string['graded'] = '已評分';
$string['guestnosubmit'] = '抱歉，訪客不允許上傳作業。在上傳答案前，您須先登入或註冊。';
$string['guestnoupload'] = '抱歉，訪客無上傳權限。';
$string['helpoffline'] = '<p>當作業是在Moodle外完成時，這項功能是非常有用的。它可以在網站的其他地方或者是師生面對面的方式進行。</p><p>學生可以看到作業的描述，但是不能上傳檔案或其他資料。評分功能仍可正常使用，而且學生也會收到評分的通知。<p>';
$string['helponline'] = '<p>這個作業型式要求使用者編輯一份文件，使用一般的編輯工具。教師可以線上評分，甚至在文件中加入註解或修改。</p>
<p>(如果您對舊版的Moodle熟悉的話，這個作業型態和舊的期刊模組處理的事情是相同的。)</p>';
$string['helpupload'] = '<p>這種類型的作業允許每個參與者上傳任何類型的一個或多個文件。它們可以是Word文件，圖片，打包了的網站，或者任何您想讓他們提交的。</p> <p>此類作業也允許您上傳多個反饋文件。反饋文件也可以在作業提交前就上傳，這樣可以給每個參與者不同的文件。</p> <p>參與者們也可以輸入註釋來說明提交的文件、進度狀況或任何其它文字資訊。</p> <p>此類作業的提交必由參與者手工設定為結束。您可以在任何時間檢查當前的狀態，未完成的作業會被標記為草稿。您可以把任何未打分的作業恢復成草稿的狀態。</p>';
$string['helpuploadsingle'] = '<p>這個作業型態允許每個參與者上傳任何檔案類型的單一檔案。</p> <p>也許是一份Word文書處理文件，或者一張圖，一個壓縮成的網站，或您要求他們繳交的任何資料。</p>';
$string['hideintro'] = '在開始日期前隱藏作業說明';
$string['itemstocount'] = '計算';
$string['late'] = '$a 之後';
$string['maximumgrade'] = '最高得分';
$string['maximumsize'] = '檔案大小限制';
$string['modulename'] = '作業';
$string['modulenameplural'] = '作業';
$string['newsubmissions'] = '作業已繳交';
$string['noassignments'] = '尚未有作業';
$string['noattempts'] = '尚未有任何嘗試';
$string['nofiles'] = '沒有上傳任何檔案';
$string['nofilesyet'] = '還沒有上傳檔案';
$string['nomoresubmissions'] = '不允許進一步繳交作業';
$string['nosubmitusers'] = '沒有使用者有權限繳交這個作業';
$string['notavailableyet'] = '很抱歉，此作業還未啟動。<br />下面的日期後，將會在此顯示作業說明。';
$string['notes'] = '註釋';
$string['notesempty'] = '沒有資料';
$string['notesupdateerror'] = '更新註釋時發生錯誤';
$string['notgradedyet'] = '尚未評分';
$string['notsubmittedyet'] = '尚未繳交作業';
$string['onceassignmentsent'] = '一旦作業交出去評分，您將無法再刪除或附加檔案。您確定要繼續嗎？';
$string['overwritewarning'] = '警告: 如果重新再上傳作業，將會取代您已經繳交的作業';
$string['pagesize'] = '每頁顯示的作業份數';
$string['preventlate'] = '禁止遲交';
$string['quickgrade'] = '允許快速評分';
$string['responsefiles'] = '回應的檔案';
$string['reviewed'] = '已檢視的';
$string['saveallfeedback'] = '儲存所有回饋';
$string['sendformarking'] = '繳交給老師評分';
$string['showrecentsubmissions'] = '顯示最近的作業';
$string['submission'] = '繳交';
$string['submissiondraft'] = '繳交的草稿';
$string['submissionfeedback'] = '繳交後的回饋';
$string['submissions'] = '繳交';
$string['submissionsaved'] = '您的修改已經儲存';
$string['submissionsnotgraded'] = '$a繳交未評分';
$string['submitassignment'] = '請利用本表單繳交作業';
$string['submitedformarking'] = '作業正在等待評分，不能再修改了';
$string['submitformarking'] = '最後繳交作業以評分';
$string['submitted'] = '已繳交';
$string['submittedfiles'] = '繳交的檔案';
$string['trackdrafts'] = '是否發送評分請求';
$string['typeoffline'] = '離線作業';
$string['typeonline'] = '線上文字';
$string['typeupload'] = '進階檔案上傳';
$string['typeuploadsingle'] = '上傳一個檔案';
$string['unfinalize'] = '還原為草稿';
$string['unfinalizeerror'] = '發生錯誤，此作業無法回復為草稿';
$string['uploadbadname'] = '檔案名稱包含奇怪的字元，無法上傳';
$string['uploadedfiles'] = '已上傳的檔案';
$string['uploaderror'] = '在伺服器儲存檔案時發生錯誤';
$string['uploadfailnoupdate'] = '檔案上傳成功，但是無法更新作業繳交資料！';
$string['uploadfiletoobig'] = '抱歉，檔案太大（不能超過 $a 位元組）';
$string['uploadnofilefound'] = '沒有發現任何檔案―您能確定已選取了一個檔案來上傳嗎?';
$string['uploadnotregistered'] = '$a 上傳成功，但是尚未登記！';
$string['uploadsuccess'] = '上傳 $a 成功';
$string['viewfeedback'] = '檢視作業成績和回饋';
$string['viewsubmissions'] = '檢視 $a 份已繳交的作業';
$string['yoursubmission'] = '個人已繳交的作業';
$string['allowmultiple'] = '允許多個檔案'; // ORPHANED
$string['attachfile'] = '附加檔案'; // ORPHANED
$string['attachfiletoassignment'] = '作業的附加檔案'; // ORPHANED
$string['backtoassignment'] = '回到作業'; // ORPHANED
$string['backtofeedback'] = '回到回饋'; // ORPHANED
$string['choosereviewfile'] = '選擇一個檔案上傳當作作業摘要:'; // ORPHANED
$string['deletecheckfile'] = '您確定要刪除此檔?'; // ORPHANED
$string['deleteednotification'] = '檔案已刪除'; // ORPHANED
$string['deletefail'] = '以下檔案尚未刪除'; // ORPHANED
$string['markingsubmitnotification'] = '註記檔案已傳送'; // ORPHANED
$string['namedeletefile'] = '您將刪除此檔:'; // ORPHANED
$string['nofilesforsubmit'] = '尚未繳交任何檔案-您確定您已上傳?'; // ORPHANED
$string['removelink'] = '移除'; // ORPHANED
$string['responsefile'] = '回應檔:'; // ORPHANED
$string['responsesfromteacher'] = '教師上傳回應'; // ORPHANED
$string['step1'] = '步驟1:'; // ORPHANED
$string['step2'] = '步驟2:'; // ORPHANED
$string['submissionstatus'] = '繳交狀況'; // ORPHANED
$string['submissionstatusblank'] = '空白'; // ORPHANED
$string['submissionstatusdraft'] = '草稿'; // ORPHANED
$string['submissionstatusmarked'] = '已註記'; // ORPHANED
$string['submissionstatusreturned'] = '已轉回'; // ORPHANED
$string['submissionstatussubmitted'] = '已傳送'; // ORPHANED
$string['uploadsuccessresponse'] = '上傳檔案成功回應。'; // ORPHANED

?>
