<?PHP // $Id$ 
      // error.php - created with Moodle 1.6 (2006050506)


$string['adminprimarynoedit'] = '預設的admin 帳號無法被編輯';
$string['cannotcreatelangdir'] = '無法建立語言資料夾';
$string['cannotcreatetempdir'] = '無法建立暫存資料夾';
$string['cannotdownloadcomponents'] = '無法下載元件';
$string['cannotdownloadzipfile'] = '無法下載 ZIP 檔案';
$string['cannotfindcomponent'] = '找不到元件';
$string['cannotsavemd5file'] = '無法儲存 md5 檔案';
$string['cannotsavezipfile'] = '無法儲存 ZIP 檔案';
$string['cannotunzipfile'] = '無法解壓縮檔案';
$string['cmunknown'] = '無法找到這個課程模組';
$string['componentisuptodate'] = '元件是最新狀態';
$string['confirmsesskeybad'] = '抱歉，您的session key 無法確認能進行這個動作，這個安全性功能是為了預防以您的帳號進行意外或惡意執行一些重要功能，請確認您真的要執行這個功能';
$string['coursegroupunknown'] = '發生錯誤於第 $a 行';
$string['downloadedfilecheckfailed'] = '下載檔案檢查錯誤';
$string['errorcleaningdirectory'] = '清除資料夾 \"$a\" 時發生錯誤';
$string['errorcopyingfiles'] = '複製檔案時發生錯誤';
$string['errorcreatingdirectory'] = '建立資料夾 \"$a\" 時發生錯誤';
$string['errorcreatingfile'] = '建立檔案 \"$a\" 時發生錯誤';
$string['erroronline'] = '第 $a 行發生錯誤';
$string['errorreadingfile'] = '讀取檔案 \"$a\" 時發生錯誤';
$string['errorunzippingfiles'] = '解壓縮檔案時發生錯誤';
$string['fieldrequired'] = '$a 是必填的欄位';
$string['filenotfound'] = '抱歉，指定的檔案找不到';
$string['forumblockingtoomanyposts'] = '您已經超過這個討論區的發表限制';
$string['groupalready'] = '使用者已隸屬於群組 $a';
$string['groupunknown'] = '群組 $a 不相關於指定的課程';
$string['guestnoeditprofile'] = '訪客無法編輯個人資料';
$string['guestnoeditprofileother'] = '不行編輯訪客個人資料';
$string['invalidcourse'] = '錯誤的課程';
$string['invalidfieldname'] = '\"$a\" 不是正確的欄位名稱';
$string['invalidfiletype'] = '\"$a\" 不是正確的檔案類型';
$string['invalidmd5'] = '錯誤的 md5';
$string['invalidxmlfile'] = '\"$a\" 不是正確的XML檔案';
$string['missingfield'] = '欄位 !!$a!! 不存在';
$string['missingrequiredfield'] = '缺少部份必填欄位';
$string['modulemissingcode'] = '模組 $a 缺少了執行這個功能所需要的代碼';
$string['modulerequirementsnotmet'] = '模組 $a->modulename ($a->moduleversion)安裝失敗。它需要更新版本的Moodle支援(目前您使用的是 $a->currentmoodle， 您需要 $a->requiremoodle)。';
$string['mustbeteacher'] = '只有教師可以檢視這個頁面';
$string['noinstances'] = '這個課程沒有 $a 實例！';
$string['nonmeaningfulcontent'] = '沒有實際內容';
$string['noparticipatorycms'] = '抱歉，您沒有可以分享的課程模組。';
$string['notavailable'] = '目前無法使用';
$string['onlyadmins'] = '只有管理者可以這麼做';
$string['onlyeditingteachers'] = '只有編輯中的教師可以執行這個動作';
$string['onlyeditown'] = '您只可以編輯您的個人資訊';
$string['pagenotexist'] = '一個不明錯誤發生（嘗試存取不存在的頁面）';
$string['pleasereport'] = '如果您有充裕的時間，請讓我們知道錯誤發生當時您正要執行什麼操作：';
$string['pluginrequirementsnotmet'] = '外掛 \"$a->pluginname\" ($a->pluginversion) 無法安裝，它需要更新版本的 Moodle （目前您正使用 $a->currentmoodle ，需要 $a->requiremoodle）';
$string['processingstops'] = '處理程序中止，其餘的資料將被忽略';
$string['remotedownloadnotallowed'] = '您的伺服器不允許下載元件（停用了 allow_url_fopen ）。<br /><br />您必須手動下載 <a href=\"$a->url\">$a->url</a> ，然後複製到 \"$a->dest\" 並且解壓縮。';
$string['restricteduser'] = '抱歉，您的目前帳號 $a 無權進行上述操作。';
$string['sendmessage'] = '寄送訊息';
$string['sessionerroruser'] = '您的session 己過期，請重新登入';
$string['sessionerroruser2'] = '伺服器產生的錯誤影響了您的登入連線，請重新登入或是重新開啟瀏覽器。';
$string['sessionipnomatch'] = '抱歉，您的ip似乎與您初次登入時不符，這個安全性功能可預防駭客以您的身份竊取您登入此站的資料，一般使用者可能不會看到這個訊息，請向系統管理者詢問取得協助';
$string['statscatchupmode'] = '統計資料目前在 catchup 模式， $a->daysdone 天內的資料已經處理， $a->dayspending 天的資料等候中，請立刻整理！';
$string['unknowncourse'] = '未知的課程名稱： $a';
$string['unknownuseraction'] = '抱歉，不明的使用者操作。';
$string['usernotaddederror'] = '使用者 $a 新增失敗- 未知的錯誤';
$string['usernotaddedregistered'] = '使用者 $a 新增失敗- 該帳號已註冊';
$string['usernotavailable'] = '您無法檢視該使用者的詳細資料';
$string['usernotrenamedexists'] = '使用者沒有更名，新的名稱重複。';
$string['usernotrenamedmissing'] = '使用者沒有更名，找不到舊的帳號。';
$string['wrongdestpath'] = '錯誤的目的路徑。';
$string['wrongsourcebase'] = '錯誤的來源網址基礎';
$string['wrongzipfilename'] = '錯誤的 ZIP 檔名。';

?>
