<?PHP // $Id$ 
      // message.php - created with Moodle 1.9 + (Build: 20080409) (2007101509)


$string['addcontact'] = '增加聯絡人';
$string['addsomecontacts'] = '要發簡訊給某人或在此頁面增加快捷連結，可以使用上方的<a href=\"$a\">搜索</a>功能。';
$string['addsomecontactsincoming'] = '發送簡訊的人不在您的通訊錄中。如果您要將他加入通訊錄，請點擊他們姓名旁邊的\"加入通訊錄”的圖示。';
$string['ago'] = '{$a}之前';
$string['allmine'] = '我發送或接收的全部簡訊';
$string['allstudents'] = '參與課程的所有學生的全部簡訊';
$string['allusers'] = '所有使用者的簡訊';
$string['backupmessageshelp'] = '如果啟動，即時簡訊將會在網站自動備份時一併納入。';
$string['beepnewmessage'] = '收到簡訊時，發出提醒聲音(需要瀏覽器支援)';
$string['blockcontact'] = '黑名單';
$string['blockedmessages'] = '{$a}條來自或發送給黑名單的簡訊';
$string['blocknoncontacts'] = '僅接收通訊錄中的使用者所發送的簡訊。(其他都拒收)';
$string['contactlistempty'] = '您的通訊錄是空的';
$string['contacts'] = '通訊錄';
$string['context'] = '內容';
$string['deletemessagesdays'] = '多少天前的舊簡訊應當被自動刪除';
$string['discussion'] = '互動';
$string['emailmessages'] = '當我離線時，將簡訊寄至我的電子郵件信箱';
$string['emailtagline'] = '這封郵件是在 \"{$a}\" 上傳送給您的簡訊副本';
$string['emptysearchstring'] = '您必須提供要搜尋的資料';
$string['formorethan'] = '超過';
$string['includeblockedusers'] = '包括黑名單';
$string['incomingcontacts'] = '新的聯絡人 ({$a})';
$string['keywords'] = '關鍵字';
$string['keywordssearchresults'] = '搜尋結果: 找到{$a}條簡訊';
$string['mailsent'] = '將透過電子郵件發送簡訊';
$string['maxmessages'] = '最多顯示多少條互動歷史簡訊';
$string['message'] = '簡訊';
$string['messagehistory'] = '歷史簡訊';
$string['messages'] = '簡訊';
$string['messaging'] = '傳簡訊';
$string['messagingdisabled'] = '網站中已禁用簡訊功能，將以電子郵件發送來取代。';
$string['mycontacts'] = '我的通訊錄';
$string['newonlymsg'] = '只顯示新的';
$string['newsearch'] = '新的搜尋';
$string['noframesjs'] = '沒有頁框和JavaScript 的版本';
$string['nomessages'] = '沒有簡訊';
$string['nomessagesfound'] = '沒有找到簡訊';
$string['nosearchresults'] = '您的搜尋沒有結果';
$string['offline'] = '離線';
$string['offlinecontacts'] = '離線中的聯絡人 ({$a})';
$string['online'] = '在線上';
$string['onlinecontacts'] = '在線上的聯絡人 ({$a})';
$string['onlyfromme'] = '我傳送的簡訊';
$string['onlymycourses'] = '只有在我的課程中';
$string['onlytome'] = '給我的簡訊';
$string['pagerefreshes'] = '這個頁面每{$a}秒自動更新一次';
$string['readmessages'] = '{$a}條已讀取的簡訊';
$string['removecontact'] = '刪除聯絡人';
$string['savemysettings'] = '保存我的設定';
$string['search'] = '搜尋';
$string['searchforperson'] = '找人';
$string['searchmessages'] = '找簡訊';
$string['sendmessage'] = '傳送簡訊';
$string['sendmessageto'] = '傳送簡訊給{$a}';
$string['sendmessagetopopup'] = '傳送簡訊給{$a} - 新視窗';
$string['settings'] = '設定';
$string['settingssaved'] = '您的設定已經保存';
$string['showmessagewindow'] = '當有新簡訊到來時自動顯示訊息視窗(您的瀏覽器需要進行設定，使其不會阻擋這個網站的彈出視窗)。';
$string['strftimedaydatetime'] = '%%A, %%d %%B %%Y, %%I:%%M %%p';
$string['timenosee'] = '已經離線多少分鐘';
$string['timesent'] = '傳送時間';
$string['unblockcontact'] = '不再封鎖聯絡';
$string['unreadmessages'] = '{$a}條未讀取的簡訊';
$string['userisblockingyou'] = '這個使用者阻擋了您傳送給他的簡訊';
$string['userisblockingyounoncontact'] = '這個使用者只接收通訊錄中的人所發的簡訊，而您不在其中。';
$string['userssearchresults'] = '搜尋結果：找到{$a}個使用者';

?>
