<?PHP // $Id$ 
      // wiki.php - created with Moodle 1.9.2 (Build: 20080711) (2007101520)


$string['created'] = '建立';
$string['diff'] = '差異';
$string['export'] = '匯出';
$string['hits'] = '{$a}次點閱';
$string['lockcancelled'] = '您的編輯鎖已經被覆蓋，而且其他人正在編輯此頁面。如果您希望保留自己的更改，請在點擊取消之前選擇並且拷貝這些變化，然後嘗試重新編輯。';
$string['modulename'] = 'Wiki';
$string['modulenameplural'] = 'Wikis';
$string['nojslockwarning'] = '因為在您的瀏覽器中Javascript無法使用，所以可能會有別人編輯此頁面。如果發生了這樣的事，您將無法保存您的更改。請嘗試快速編輯，或者打開Javascript功能，並且重新讀取此頁面。';
$string['overridebutton'] = '替換鎖';
$string['overrideinfo'] = '您可以替換這個使用者的鎖，但是這樣做可能會導致他們遺失修改的東西！請小心。';
$string['pagelocked'] = '<p><strong>{$a->name}正在編輯此頁面。</strong> 他們在{$a->since}開始編輯，而且視窗始終打開著直到{$a->seen}為止。</p><p>您如果要編輯此頁面，必須等待他們完成動作。</p>';
$string['pagename'] = '頁面名稱';
$string['save'] = '儲存';
$string['savenolock'] = '您無法儲存頁面，因為您沒有編輯鎖。如果您的瀏覽器關閉了Javascript，或者其他用戶替換了您的鎖，那麼就可能會發生這種事。<br/><br/>您可以使用瀏覽器的按鈕返回到前一個頁面，並且複製任何您做過修改的文字，然後再重新編輯。';
$string['status'] = '狀態';
$string['version'] = '版本';
$string['wiki:overridelock'] = '覆蓋鎖定的頁面';
$string['action'] = '-- 動作 --'; // ORPHANED
$string['administration'] = '系統管理'; // ORPHANED
$string['allowremovepages'] = '允許\"刪除頁面\"'; // ORPHANED
$string['allowrevertchanges'] = '允許\"取消變更\"'; // ORPHANED
$string['allowsetpage'] = '允許\"設定頁面標記\"'; // ORPHANED
$string['allowstrippages'] = '允許\"裁減頁面\"'; // ORPHANED
$string['attachments'] = '這個頁面有附件'; // ORPHANED
$string['author'] = '作者'; // ORPHANED
$string['authorfieldpattern'] = '作者欄位類型'; // ORPHANED
$string['authorfieldpatternerror'] = '請輸入一位作者'; // ORPHANED
$string['backlinks'] = '參考連結'; // ORPHANED
$string['binimgtoolarge'] = '影像檔太大了！'; // ORPHANED
$string['binnoimg'] = '無法接受這種檔案格式！'; // ORPHANED
$string['browse'] = '瀏覽'; // ORPHANED
$string['canceledit'] = '取消'; // ORPHANED
$string['cannotchangepage'] = '此頁無法變更。'; // ORPHANED
$string['changes'] = '{$a} 變更'; // ORPHANED
$string['changesfield'] = '距上次變更時間'; // ORPHANED
$string['changesfielderror'] = '請輸入正確時間。'; // ORPHANED
$string['checklinks'] = '檢查連結'; // ORPHANED
$string['checklinkscheck'] = '確定要檢查本頁連結:'; // ORPHANED
$string['checklinksnotice'] = '請稍候。'; // ORPHANED
$string['chooseadministration'] = '-- 系統管理 --'; // ORPHANED
$string['chooseafile'] = '選擇 /上傳初始頁'; // ORPHANED
$string['choosewikilinks'] = '-- 選擇Wiki連結--'; // ORPHANED
$string['comment'] = '評論'; // ORPHANED
$string['contentsize'] = '內容大小'; // ORPHANED
$string['deletemewikiword'] = '刪除'; // ORPHANED
$string['deletemewikiwordfound'] = '本頁發現{$a}筆'; // ORPHANED
$string['deletepage'] = '刪除頁面'; // ORPHANED
$string['deleteversions'] = '刪除多少以前的版本'; // ORPHANED
$string['deleteversionserror'] = '請輸入正確的版本數'; // ORPHANED
$string['differences'] = '{$a->pagename}頁面的{$a->new_ver}版和{$a->old_ver}版之間的差異。'; // ORPHANED
$string['disablecamel'] = '不為首字母大寫的詞組建立連結'; // ORPHANED
$string['disabledpage'] = '找不到此頁面'; // ORPHANED
$string['doesnotexist'] = '此頁面不存在，如果您想建立它，請點選\"編輯\"按鈕。'; // ORPHANED
$string['downloadaszip'] = '可下載的zip檔案'; // ORPHANED
$string['downloadtimes'] = '下載 $a 次'; // ORPHANED
$string['dwnlnofiles'] = '無上傳檔案'; // ORPHANED
$string['dwnlsection'] = '下載區'; // ORPHANED
$string['editform1'] = '不要太擔心格式的問題，以後還可以繼續修改。'; // ORPHANED
$string['editform2'] = '請仔細編寫，所有的修改操作都會被記錄。'; // ORPHANED
$string['editthispage'] = '編輯此頁'; // ORPHANED
$string['emptypage'] = '空白頁'; // ORPHANED
$string['errorbinandtxt'] = '錯誤標記：同時是二進位和文字類型的頁面'; // ORPHANED
$string['errorhtml'] = 'HTML類型頁面'; // ORPHANED
$string['errornotype'] = '錯誤標記：非二進位且非文字'; // ORPHANED
$string['errororreason'] = '錯誤或原因'; // ORPHANED
$string['errorroandwr'] = '錯誤標記：頁面可寫且唯讀'; // ORPHANED
$string['errorsize'] = '頁面尺寸超過64K'; // ORPHANED
$string['errversionsave'] = '對不起，在您修改這個頁面時有人已經對其進行了修改。請將您修改的部分複製到剪貼簿上，並返回前一頁，然後重新載入它並修改。'; // ORPHANED
$string['ewikiacceptbinary'] = '允許二進位檔'; // ORPHANED
$string['ewikiprinttitle'] = '在每頁上列印Wiki的名字'; // ORPHANED
$string['exportformats'] = '匯出格式'; // ORPHANED
$string['exportsuccessful'] = '成功匯出'; // ORPHANED
$string['exportto'] = '匯出到'; // ORPHANED
$string['fetchback'] = '取回'; // ORPHANED
$string['file'] = '檔案'; // ORPHANED
$string['filedownload'] = '檔案下載'; // ORPHANED
$string['fileisoftype'] = '檔案類型為'; // ORPHANED
$string['filtername'] = 'Wiki頁面自動連結'; // ORPHANED
$string['flagbin'] = '二進位'; // ORPHANED
$string['flaghtm'] = '網頁'; // ORPHANED
$string['flagoff'] = '關'; // ORPHANED
$string['flagro'] = '唯讀'; // ORPHANED
$string['flags'] = '標記'; // ORPHANED
$string['flagsset'] = '標記已變更'; // ORPHANED
$string['flagtxt'] = '文字'; // ORPHANED
$string['flagwr'] = '可寫'; // ORPHANED
$string['for'] = '為'; // ORPHANED
$string['forbidden'] = '您無權存取此頁面'; // ORPHANED
$string['groups'] = '群組'; // ORPHANED
$string['howtooperate'] = '如何操作'; // ORPHANED
$string['howtowiki'] = '如何使用Wiki'; // ORPHANED
$string['html'] = 'HTML格式'; // ORPHANED
$string['htmlmode'] = 'HTML 模式'; // ORPHANED
$string['htmlonly'] = '只有 HTML'; // ORPHANED
$string['index'] = '索引'; // ORPHANED
$string['infoaboutpage'] = '歷程：'; // ORPHANED
$string['initialcontent'] = '選擇一個起始頁'; // ORPHANED
$string['invalidroot'] = '您無權存取現在的根頁面，因此無法建立網站地圖。'; // ORPHANED
$string['lastchanged'] = '最後修改於{$a}'; // ORPHANED
$string['lastmodified'] = '最後修改'; // ORPHANED
$string['linkdead'] = '壞的'; // ORPHANED
$string['linkok'] = '好的'; // ORPHANED
$string['linkschecked'] = '連結已檢查'; // ORPHANED
$string['listall'] = '列出全部'; // ORPHANED
$string['listcandidates'] = '列出候選的'; // ORPHANED
$string['meta'] = '元資料'; // ORPHANED
$string['moduledirectory'] = '模組目錄'; // ORPHANED
$string['mostoftenchangedpages'] = '異動最頻繁的頁面'; // ORPHANED
$string['mostvisitedpages'] = '最多人瀏覽的頁面'; // ORPHANED
$string['newestpages'] = '最新的頁面'; // ORPHANED
$string['noadministrationaction'] = '沒有管理員動作'; // ORPHANED
$string['nocandidatestoremove'] = '沒有要刪除的候選頁面，請選擇\"{$a}\"以顯示全部頁面。'; // ORPHANED
$string['nochangestorevert'] = '沒有變更需要回復'; // ORPHANED
$string['nohtml'] = '不用HTML'; // ORPHANED
$string['nolinksfound'] = '此頁面無連結'; // ORPHANED
$string['noregexp'] = '這必須是一個固定字串(您不能使用*或者正則運算式)，最好使用攻擊者的IP位址或主機名，但不要包含埠號(因為每次http訪問俄它都會變化)。'; // ORPHANED
$string['notadministratewiki'] = '不允許您管理這個Wiki！'; // ORPHANED
$string['nothingtostrip'] = '所有頁面均沒有多個版本。'; // ORPHANED
$string['nowikicreated'] = '此Wiki尚無內容'; // ORPHANED
$string['of'] = '的'; // ORPHANED
$string['offline'] = '離線'; // ORPHANED
$string['optional'] = '選項'; // ORPHANED
$string['orphanedpage'] = '孤獨的頁面'; // ORPHANED
$string['orphanedpages'] = '孤獨的頁面'; // ORPHANED
$string['otherwikis'] = '其他Wikis'; // ORPHANED
$string['ownerunknown'] = '未知'; // ORPHANED
$string['pageactions'] = '頁面動作'; // ORPHANED
$string['pageindex'] = '頁面索引'; // ORPHANED
$string['pageinfo'] = '頁面資訊'; // ORPHANED
$string['pagenamechoice'] = '- 或 -'; // ORPHANED
$string['pageslinkingto'] = '頁面連結到此頁'; // ORPHANED
$string['pagesremoved'] = '頁面已刪除'; // ORPHANED
$string['pagesreverted'] = '變更已被取消'; // ORPHANED
$string['pagesstripped'] = '頁面已被裁減'; // ORPHANED
$string['plaintext'] = '純文字'; // ORPHANED
$string['preview'] = '預覽'; // ORPHANED
$string['readonly'] = '唯讀頁面'; // ORPHANED
$string['refs'] = '參考'; // ORPHANED
$string['reloadlinkdescription'] = '重新載入此頁，以便讓最新的內容顯現'; // ORPHANED
$string['reloadlinktext'] = '重新載入此頁'; // ORPHANED
$string['removenotice'] = '注意此處僅列出未被參考的頁面。由於ewiki本身僅測試那些被參考的頁面，因此此處可能會有遺漏。<br />如果您清空了一個頁面，它也會被列在此處。同時也進行了各種不同的資料庫診斷。'; // ORPHANED
$string['removepagecheck'] = '您確定要刪除這些頁面嗎？'; // ORPHANED
$string['removepages'] = '刪除頁面'; // ORPHANED
$string['removeselectedpages'] = '刪除選定的頁面'; // ORPHANED
$string['revertallsince'] = '恢復到特定版本，同時刪除之後的修改'; // ORPHANED
$string['revertchanges'] = '取消變更'; // ORPHANED
$string['revertlastonly'] = '僅在最後一次修改時'; // ORPHANED
$string['revertpages'] = '回復全部的變更'; // ORPHANED
$string['revertpagescheck'] = '您確定要恢復下列修改嗎：'; // ORPHANED
$string['revertthe'] = '恢復到特定版本，但只清除受影響的版本'; // ORPHANED
$string['safehtml'] = '安全的HTML'; // ORPHANED
$string['searchwiki'] = '搜尋Wiki'; // ORPHANED
$string['setpageflags'] = '設定頁面標記'; // ORPHANED
$string['showversions'] = '顯示版本：'; // ORPHANED
$string['sitemap'] = '網站地圖'; // ORPHANED
$string['smfor'] = '網站地圖'; // ORPHANED
$string['strippagecheck'] = '您確定要刪除這些頁面的舊版本嗎?：'; // ORPHANED
$string['strippages'] = '裁減頁面'; // ORPHANED
$string['studentadminoptions'] = '學生管理選項'; // ORPHANED
$string['submit'] = '送出'; // ORPHANED
$string['tabattachments'] = '附件'; // ORPHANED
$string['tabedit'] = '編輯'; // ORPHANED
$string['tabinfo'] = '歷史記錄'; // ORPHANED
$string['tablinks'] = '連結'; // ORPHANED
$string['tabview'] = '檢視'; // ORPHANED
$string['thanksforcontribution'] = '感謝您的付出.'; // ORPHANED
$string['thispageisntlinkedfromanywhereelse'] = '沒有其他地方連結到此頁面。'; // ORPHANED
$string['updatedpages'] = '更新的頁面'; // ORPHANED
$string['updatedwikipages'] = '更新的Wiki頁面'; // ORPHANED
$string['uplerror'] = '非常抱歉，在上傳檔案的過程中發生錯誤。'; // ORPHANED
$string['uplinsect'] = '上傳到'; // ORPHANED
$string['uplnewnam'] = '另存新檔'; // ORPHANED
$string['upload0'] = '使用此表單可上傳二進位的檔案到Wiki中:'; // ORPHANED
$string['uploadedon'] = '上傳於'; // ORPHANED
$string['uploadpicturebutton'] = '上傳'; // ORPHANED
$string['uplok'] = '您的檔案已經上傳成功。'; // ORPHANED
$string['versionrangetoobig'] = '您無法刪除一個頁面的全部版本!應該要保留最後的版本。'; // ORPHANED
$string['versions'] = '版本'; // ORPHANED
$string['versionstodelete'] = '要刪除的版本'; // ORPHANED
$string['viewpage'] = '檢視頁面'; // ORPHANED
$string['viewsmfor'] = '檢視網站地圖'; // ORPHANED
$string['wantedpages'] = '待建頁面'; // ORPHANED
$string['wiki:manage'] = '管理 wiki 設定'; // ORPHANED
$string['wiki:participate'] = '編輯 wiki 頁面'; // ORPHANED
$string['wikidefaultpagename'] = 'Wiki索引'; // ORPHANED
$string['wikiexport'] = '匯出頁面'; // ORPHANED
$string['wikiexportcomment'] = '您可以在這裡設定您想要匯出的東西。'; // ORPHANED
$string['wikilinkoptions'] = 'Wiki自動連結選項'; // ORPHANED
$string['wikilinks'] = 'Wiki連結'; // ORPHANED
$string['wikiname'] = '頁面名稱'; // ORPHANED
$string['wikistartederror'] = 'Wiki中已經有內容 - 不能再修改'; // ORPHANED
$string['wikitype'] = '類型'; // ORPHANED
$string['wikiusage'] = 'Wiki用法'; // ORPHANED
$string['withbinaries'] = '包含二進位的內容'; // ORPHANED
$string['withvirtualpages'] = '包含Wiki連結'; // ORPHANED
$string['wrongversionrange'] = '{$a}不是正確的範圍！'; // ORPHANED

?>
