<?PHP // $Id$ 
      // auth.php - created with Moodle 1.9.5 (Build: 20090515) (2007101550)


$string['actauthhdr'] = 'Активни додатак за проверу идентитета';
$string['alternatelogin'] = 'Ако овде унесете URL, биће коришћен као страница за пријаву на овај сајт. Страница би требала садржати форму са акцијском опцијом подешеном на <strong>\'$a\'</strong> и враћањем поља <strong>username</strong> i <strong>password</strong>.<br />Будите опрезни да не бисте случајно унели погрешан URL и тиме сами себи онемогућили приступ сајту.<br />Оставите ово подешавање празно да бисте користили подразумевану страницу за приступ систему.';
$string['alternateloginurl'] = 'Алтернативни URL за пријаву на систем';
$string['auth_changepasswordhelp'] = 'Промена помоћи за лозинку';
$string['auth_changepasswordhelp_expl'] = 'Приказ помоћи за случај изгубљене лозинке корисницима који су изгубили своју $a лозинку. То ће бити приказано или исто као или уместо <strong>URL-a за промену лозинке</strong> или интерне промене Moodle лозинке.';
$string['auth_changepasswordurl'] = 'URL за промену лозинке';
$string['auth_changepasswordurl_expl'] = 'Специфицирајте URL који ће се слати корисницима који изгубе своје $a лозинке. Подесите<strong>Користити стандардну страницу за промену лозинке</strong> на <strong>Не</strong>.';
$string['auth_common_settings'] = 'Општа подешавања';
$string['auth_data_mapping'] = 'Мапирање података';
$string['auth_fieldlock'] = 'Закључавање вредности';
$string['auth_fieldlock_expl'] = '<p><b>Закључавање вредности:</b> Ако је омогућено, спречиће Moodle кориснике и администраторе да директно уређују поље. Користите ову опцију ако одржавате ове податке у екстерном аутентикационом систему. </p>';
$string['auth_fieldlocks'] = 'Закључавање корисничких поља';
$string['auth_fieldlocks_help'] = '<p>Можете закључати поља са корисничким подацима. То је корисно за сајтове на којима корисничке податке ручно одржавају администратори уређивањем корисничких записа у бази података или постављањем података коришћењем могућности за постављање корисника из других извора. Ако закључавате поља која су неопходна за рад Moodle система, проверите да ли сте омогућили коришћење тих података при креирању корисничких налога &emdash; јер се у супротном налози неће моћи користити.</p><p>Размотрите подешавање мода за такључавање на \'Откључано ако је празно\' да бисте избегли тај проблем.</p>';
$string['auth_multiplehosts'] = 'Одређивање више домаћина или адреса (нпр. host1.com;host2.com;host3.com) или (npr. xxx.xxx.xxx.xxx;xxx.xxx.xxx.xxx)';
$string['auth_remove_delete'] = 'Потпуно брисање интерних података';
$string['auth_remove_keep'] = 'Задржавање интерних података';
$string['auth_remove_suspend'] = 'Обустављање интерних података';
$string['auth_remove_user'] = 'Одредите шта радити са унутрашњим корисничким налогом за време масовне синхронизације када је корисник уклоњен од стране спољног извора. Само обустављени корисници се аутоматски обнављају ако се поново појављују у спољном извору.';
$string['auth_remove_user_key'] = 'Уклоњен спољни корисник';
$string['auth_sync_script'] = 'Скрипта синхронизације крона';
$string['auth_updatelocal'] = 'Ажурирање локалних података';
$string['auth_updatelocal_expl'] = '<p><b>Ажурирање локалних података:</b> Ако је омогућено, поље ће бити ажурирано (користи се екстерни auth) сваки пут када корисник приступи систему или дође до корисничке синхронизације. Поља за која је подешено локално ажурирање би требала бити закључана.</p>';
$string['auth_updateremote'] = 'Ажурирање екстерних података';
$string['auth_updateremote_expl'] = '<p><b>Ажурирање екстерних података:</b> Ако је омогућено, екстерни auth ће бити ажуриран при ажурирању записа о корисницима. Поља би требала бити откључана да би се дозволиле промене.</p>';
$string['auth_updateremote_ldap'] = '<p><b>Напомене:</b> Ажурирање екстерних LDAP података захтева да подесите повезивање binddn и bindpw за bind-корисника са привилегијама кориговања свих корисничких записа. Ово тренутно не чува вишевредносне атрибуте и уклониће додатне вредности надоградње.</p>';
$string['auth_user_create'] = 'Омогућити креирање корисника';
$string['auth_user_creation'] = 'Нови (анонимни) корисници могу направити корисничке налоге на спољашњем извору за проверу идентитета и извршити потврду путем е-поште. Ако омогућите ову опцију, конфигуришите и специфичне опције модула које служе за креирање корисника.';
$string['auth_usernameexists'] = 'Одабрано корисничко име већ постоји. Молимо изаберите друго корисничко име.';
$string['authenticationoptions'] = 'Опције за проверу идентитета';
$string['authinstructions'] = 'Овде можете дати инструкције Вашим корисницима, тако да знају које корисничко име и лозинку треба да користе. Текст који овде напишете биће приказан на страници за приступ систему. Ако поље оставите празно, онда инструкције неће бити приказане.';
$string['changepassword'] = 'URL за промену лозинке';
$string['changepasswordhelp'] = 'Овде можете задати локацију на којој Ваши корисници могу обновити или променити своје корисничко име/лозинку, у случају да су је заборавили.
Ова опција се може понудити корисницима у виду дугмета на страници за приступ систему и њиховој корисничкој страни. Ако оставите празно поље, дугме неће бити приказано.';
$string['chooseauthmethod'] = 'Изаберите начин провере идентитета';
$string['createpasswordifneeded'] = 'Креирање лозинке ако је то потребно';
$string['enterthenumbersyouhear'] = 'Унесите број који чујете';
$string['enterthewordsabove'] = 'Унесите реч изнад';
$string['errormaxconsecutiveidentchars'] = 'Максималан број истоветних карактера за редом које мора садржати лозинка је: $a';
$string['errorminpassworddigits'] = 'Минималан број цифара који лозинка мора садржати је: $a.';
$string['errorminpasswordlength'] = 'Минималан број карактера који лозинка мора садржати је: $a.';
$string['errorminpasswordlower'] = 'Минималан број малих слова који лозинка мора садржати је: $a.';
$string['errorminpasswordnonalphanum'] = 'Минималан број карактера који нису алфанумерички који лозинка мора садржати је: $a.';
$string['errorminpasswordupper'] = 'Минималан број великих слова који лозинка мора садржати је: $a.';
$string['errorpasswordupdate'] = 'Грешка у ажурирању лозинке, лозинка није промењена.';
$string['forcechangepassword'] = 'Обавезна промена лозинке';
$string['forcechangepassword_help'] = 'Обавезна промена лозинке за све кориснике при њиховом следећем приступу Moodle систему';
$string['forcechangepasswordfirst_help'] = 'Обавезна промена лозинке за све кориснике при њиховом првом приступу Moodle систему';
$string['forgottenpassword'] = 'Уколико овде унесете URL адресу, она ће бити коришћена за страницу за обнављање заборављене лозинке, на овом сајту. Ово је намењено сајтовима на којима се лозинкама, у потпуности, управља изван Moodlea. Оставите ово поље празно да бисте користили уобичајени начин за обнављање лозинке.';
$string['forgottenpasswordurl'] = 'URL адреса за обнављање заборављене лозинке';
$string['getanaudiocaptcha'] = 'Добијање звучног CAPTCHA';
$string['getanimagecaptcha'] = 'Добијање CAPTCHA слике';
$string['getanothercaptcha'] = 'Добијање другог CAPTCHА';
$string['guestloginbutton'] = 'Дугме за пријаву гостију';
$string['incorrectpleasetryagain'] = 'Неисправно. Молимо покушајте поново';
$string['infilefield'] = 'Поље захтевано у датотеци';
$string['instructions'] = 'Упутства';
$string['internal'] = 'Интерно';
$string['locked'] = 'Закључано';
$string['md5'] = 'MD5 кодирање';
$string['nopasswordchange'] = 'Није могуће променити лозинку';
$string['nopasswordchangeforced'] = 'Нисте у могућности да наставите даље без промене корисничког имена, међутим не постоји расположива страница за промену. Молимо контактирајте Moodle администратора.';
$string['passwordhandling'] = 'Управљење пољем лозинке';
$string['plaintext'] = 'Обичан текст';
$string['pluginnotenabled'] = 'Додатак за проверу идентитета \'$a\' није оспособљен.';
$string['pluginnotinstalled'] = 'Додатак за проверу идентитета \'$a\' није инсталиран.';
$string['recaptcha'] = 'reCAPTCHА (поново)';
$string['selfregistration'] = 'Саморегистрација';
$string['selfregistration_help'] = 'Изаберите који додатак за проверу идентитета  ће руковати саморегистрацијом корисника';
$string['sha1'] = 'SHA-1 хеш';
$string['showguestlogin'] = 'Можете сакрити или приказати дугме за пријаву гостију на пријавној страници.';
$string['stdchangepassword'] = 'Употреба стандардне странице за промену лозинке';
$string['stdchangepassword_expl'] = 'Ако спољашњи систем за проверу идентитета дозвољава промену лозинке из Moodle система, укључите га. Ово подешавање заобилази \'URL за промену лозинке\'.';
$string['stdchangepassword_explldap'] = 'Напомена: Препоручује се да користите LDAP пре него SSL шифровање тунела (ldaps://) ако је LDAP сервер удаљен.';
$string['unlocked'] = 'Откључано';
$string['unlockedifempty'] = 'Откључано ако је празно';
$string['update_never'] = 'Никад';
$string['update_oncreate'] = 'При креирању';
$string['update_onlogin'] = 'При сваком приступу систему';
$string['update_onupdate'] = 'При ажурирању';
$string['user_activatenotsupportusertype'] = 'auth: ldap user_activate() не подржава изабрани тип корисника: $a';
$string['user_disablenotsupportusertype'] = 'auth: ldap user_activate() не подржава изабрани тип корисника (...још)';
$string['CASform'] = 'Избор провере идентитета'; // ORPHANED
$string['accesCAS'] = 'CAS корисници'; // ORPHANED
$string['accesNOCAS'] = 'Остали корисници'; // ORPHANED
$string['auth_cas_auth_user_create'] = 'Екстерно креирање корисника'; // ORPHANED
$string['auth_cas_baseuri'] = 'URI сервера (ништа ако није подешен baseUri)<br />На пример, ако CAS сервер одговара домену host.domaine.fr/CAS/ онда је <br />cas_baseuri = CAS/'; // ORPHANED
$string['auth_cas_baseuri_key'] = 'Base URI'; // ORPHANED
$string['auth_cas_broken_password'] = 'Нисте у могућности да наставите даље без промене корисничког имена, међутим не постоји расположива страница за промену. Молимо контактирајте Moodle администратора.'; // ORPHANED
$string['auth_cas_cantconnect'] = 'LDAP део CAS-модула није у могућности да се повеже на сервер: $a'; // ORPHANED
$string['auth_cas_casversion'] = 'Верзија'; // ORPHANED
$string['auth_cas_changepasswordurl'] = 'URL за промену лозинке'; // ORPHANED
$string['auth_cas_create_user'] = 'Укључите ово подешавање ако желите да убаците кориснике за које је извршена CAS провера идентитета у Moodle базу података. Ако то не желите, само корисници који већ постоје у Moodle бази података ће моћи да приступе систему.'; // ORPHANED
$string['auth_cas_create_user_key'] = 'Креирај корисника'; // ORPHANED
$string['auth_cas_enabled'] = 'Укључите ово подешавање ако желите да користите CAS проверу идентитета.'; // ORPHANED
$string['auth_cas_hostname'] = 'Назив домаћина CAS сервера <br />нпр. host.domain.fr'; // ORPHANED
$string['auth_cas_hostname_key'] = 'Назив домаћина'; // ORPHANED
$string['auth_cas_invalidcaslogin'] = 'Нажалост, Ваша пријава није успела - нисте могли бити ауторизовани'; // ORPHANED
$string['auth_cas_language'] = 'Одабрани језик'; // ORPHANED
$string['auth_cas_language_key'] = 'Језик'; // ORPHANED
$string['auth_cas_logincas'] = 'Приступ преко сигурне везе'; // ORPHANED
$string['auth_cas_logoutcas'] = 'Поставите ово на \"ДА\" ако желите да се одјавите са CASа након окончања везе на Moodle'; // ORPHANED
$string['auth_cas_logoutcas_key'] = 'CAS одјава'; // ORPHANED
$string['auth_cas_multiauth'] = 'Поставите ово на \"ДА\" ако желите да имате вишеструку проверу идентитета (CAS + остале провере идентитета)'; // ORPHANED
$string['auth_cas_multiauth_key'] = 'Вишеструка провера идентитета'; // ORPHANED
$string['auth_cas_port'] = 'Порт CAS сервера'; // ORPHANED
$string['auth_cas_port_key'] = 'Порт'; // ORPHANED
$string['auth_cas_proxycas'] = 'Поставите ово на \"ДА\" ако користите  CAS у proxy моду'; // ORPHANED
$string['auth_cas_proxycas_key'] = 'Proxy мод'; // ORPHANED
$string['auth_cas_server_settings'] = 'Конфигурација CAS сервера'; // ORPHANED
$string['auth_cas_text'] = 'Сигурна веза'; // ORPHANED
$string['auth_cas_use_cas'] = 'Коришћенје CAS-а'; // ORPHANED
$string['auth_cas_version'] = 'CAS верзија'; // ORPHANED
$string['auth_casdescription'] = 'Овај начин користи CAS сервер (Central Authentication Service) за проверу идентитета корисника у Single Sign On окружењу (SSO). Можете користити и једноставну LDAP проверу идентитета. Ако су дато корисничко име и лозинка валидни према CAS-у, Moodle креира нови кориснички унос у својој бази података, по потреби преузимајући атрибуте корисника из LDAP-a. При следећим приступима врши се само провера корисничког имена и лозинке.'; // ORPHANED
$string['auth_casnotinstalled'] = 'Није могуће коришћење  CAS провере идентитета. PHP LDAP модул није инсталиран.'; // ORPHANED
$string['auth_castitle'] = 'Користити CAS сервер (SSO)'; // ORPHANED
$string['auth_changingemailaddress'] = 'Тражили сте измену адресе е-поште од $a->oldemail на $a->newemail. Из безбедносних разлога, шаљемо Вам е-поруку на нову адресу да потврдите да она припада Вама. Ваша адреса е-поште биће ажурирана чим отворите URL линк који Вам је послат у тој поруци.'; // ORPHANED
$string['auth_dbcantconnect'] = 'Није могуће повезивање на navedenu bayu podataka ya proveru identiteta'; // ORPHANED
$string['auth_dbchangepasswordurl_key'] = 'URL за промену лозинке'; // ORPHANED
$string['auth_dbdebugauthdb'] = 'Уклањање грешака из ADO базе података'; // ORPHANED
$string['auth_dbdebugauthdbhelp'] = 'Уклањање грешака из повезивања ADO базе података на спољну базу базу података - користити код добијања празне странице за време пријављивања. Није погодно за продукционе сајтове.'; // ORPHANED
$string['auth_dbdeleteuser'] = 'Уклоњен корисник  $a[0] id $a[1]'; // ORPHANED
$string['auth_dbdeleteusererror'] = 'Грешка при уклањању корисника  $a'; // ORPHANED
$string['auth_dbdescription'] = 'Овај метод користи табелу спољашње базе података за проверу да ли су додељено корисничко име и лозинка исправни. Ако је налог нов, онда информација из осталих поља може бити копирана у Moodle.'; // ORPHANED
$string['auth_dbextencoding'] = 'Спољно кодирање базе података'; // ORPHANED
$string['auth_dbextencodinghelp'] = 'Кодирање коришћено у спољној бази података'; // ORPHANED
$string['auth_dbextrafields'] = 'Ова поља су изборна. Можете изабрати да претходно попуните нека Moodle корисничка поља са информацијама из <b>поља спољашње базе података</b> која назначите овде. <br />Ако их оставите празне, онда ће бити коришћене подразумеване вредности.<br /> У сваком случају, корисник ће бити у могућности да уређује сва поља након пријављивања.'; // ORPHANED
$string['auth_dbfieldpass'] = 'Име поља које садржи лозинке'; // ORPHANED
$string['auth_dbfieldpass_key'] = 'Поље за лозинку'; // ORPHANED
$string['auth_dbfielduser'] = 'Име поља које садржи корисничка имена'; // ORPHANED
$string['auth_dbfielduser_key'] = 'Поље за корисничко име'; // ORPHANED
$string['auth_dbhost'] = 'Рачунар домаћин сервера базе података.'; // ORPHANED
$string['auth_dbhost_key'] = 'Домаћин'; // ORPHANED
$string['auth_dbinsertuser'] = 'Додат корисник $a[0] id $a[1]'; // ORPHANED
$string['auth_dbinsertusererror'] = 'Грешка при додавању корисника'; // ORPHANED
$string['auth_dbname'] = 'Назив базе података'; // ORPHANED
$string['auth_dbname_key'] = 'Назив базе података'; // ORPHANED
$string['auth_dbpass'] = 'Лозинка која одговара горе наведеном корисничком имену'; // ORPHANED
$string['auth_dbpass_key'] = 'Лозинка'; // ORPHANED
$string['auth_dbpasstype'] = '<p>Задајте формат које користи поље за лозинку. MD5 шифровање је корисно приликом повезивања на остале често коришћене веб апликације као што је PostNuke.</p> <p> Употребите опцију \'интерно\' ако желите да спољашња база података води рачуна о корисничким именима и адресама е-поште, али да сам Moodle буде надлежан за лозинке. Ако користите опцију \'интерно\', <i>морате</i> обезбедити приступ попуњеном пољу за адресе е-поште у спољашњој бази података, и морате редовно извршавати admin/cron.php. Moodle ће слати е-поруке новим корисницима са њиховим привременим лозинкама.</p>'; // ORPHANED
$string['auth_dbpasstype_key'] = 'Формат лозинке'; // ORPHANED
$string['auth_dbreviveduser'] = 'Поново додат корисник $a[0] id $a[1]'; // ORPHANED
$string['auth_dbrevivedusererror'] = 'Грешка при поновном додавању корисника $a'; // ORPHANED
$string['auth_dbsetupsql'] = 'SQL наредба за подешавање'; // ORPHANED
$string['auth_dbsetupsqlhelp'] = 'SQL наредба за специјално подешавање базе  података, често коришћено за подешавање кодирања комуникације - пример за MySQL and PostgreSQL: <em>SET NAMES \'utf8\'</em>'; // ORPHANED
$string['auth_dbsuspenduser'] = 'Обустављен рад корисника $a[0] id $a[1]'; // ORPHANED
$string['auth_dbsuspendusererror'] = 'Грешка при обустављању рада корисника $a[0] id $a[1]'; // ORPHANED
$string['auth_dbsybasequoting'] = 'Коришћење sybase наводника'; // ORPHANED
$string['auth_dbsybasequotinghelp'] = 'Sybase стил излаза једноструким наводницима - потребно за Oracle, MS SQL и неке друге базе података. Не користити за  MySQL!'; // ORPHANED
$string['auth_dbtable'] = 'Име табеле у бази података'; // ORPHANED
$string['auth_dbtable_key'] = 'Табела'; // ORPHANED
$string['auth_dbtitle'] = 'Користити спољашњу базу података'; // ORPHANED
$string['auth_dbtype'] = 'Тип базе података (Погледајте <a href=\"../lib/adodb/readme.htm#drivers\">ADOdb документацију</a> за детаље)'; // ORPHANED
$string['auth_dbtype_key'] = 'База података'; // ORPHANED
$string['auth_dbupdatinguser'] = 'Ажурирање корисника $a[0] id $a[1]'; // ORPHANED
$string['auth_dbuser'] = 'Корисничко име са приступом читању корисничке базе'; // ORPHANED
$string['auth_dbuser_key'] = 'Корисник базе података'; // ORPHANED
$string['auth_dbusernotexist'] = 'Није могуће ажурирање непостојећег корисника: $a'; // ORPHANED
$string['auth_dbuserstoadd'] = 'Ставке корисника за додавање: $a'; // ORPHANED
$string['auth_dbuserstoremove'] = 'Ставке корисника за уклањање: $a'; // ORPHANED
$string['auth_emailchangecancel'] = 'Откажи промену адресе е-поште'; // ORPHANED
$string['auth_emailchangepending'] = 'Промена се успоставља. Отворите линк кји Вам је послат на $a->preference_newemail.'; // ORPHANED
$string['auth_emaildescription'] = 'Потврђивање путем е-поште је уобичајен начин провере идентитета. Након што се корисник пријави и изабере своје ново име и лозинку, е-пошта се шаље на адресу тог корисника. У е-пошти се налази сигурносни линк према страници где нови корисник потврђује свој налог. При сваком наредном приступ унети подаци се само упоређују са онима који су сачувани у Moodle бази података.'; // ORPHANED
$string['auth_emailnoemail'] = 'Покушај слања е-поште није успео!'; // ORPHANED
$string['auth_emailnoinsert'] = 'Није могуће додати дати запис у базу података!'; // ORPHANED
$string['auth_emailnowexists'] = 'Адреса е-поште коју сте хтели придружити Вашем профилу већ је додељена некоме другоме од Вашег провобитног захтева. Стога је Ваш захтев за промену адресе е-поште одбијен, али можете покушати поново за различиту адресу.'; // ORPHANED
$string['auth_emailrecaptcha'] = 'Додаје елемент на форми за аудио/визуелну потврду на страницу за упис за кориснике који се сами пријављују на сајт путем е-поруке. Ово штити Ваш сајт против нежељених порука. Видите http://recaptcha.net/learnmore.html за више детаља.'; // ORPHANED
$string['auth_emailrecaptcha_key'] = 'Укључи reCAPTCHA елемент'; // ORPHANED
$string['auth_emailsettings'] = 'Подешавања'; // ORPHANED
$string['auth_emailtitle'] = 'Провера идентитета путем е-поште'; // ORPHANED
$string['auth_emailupdate'] = 'Ажурирање адресе е-поште'; // ORPHANED
$string['auth_emailupdatemessage'] = 'Драги корисниче $a->fullname,
Захтевали сте измену Ваше адресе е-поште за кориснички налог на $a->site. Молимо Вас да отворите следећи URL линк у Вашем веб читачу да бисте потврдили ову измену.
$a->url'; // ORPHANED
$string['auth_emailupdatesuccess'] = 'Адреса е-поште корисника <em>$a->fullname</em> успешно је ажурирана на <em>$a->email</em>.'; // ORPHANED
$string['auth_emailupdatetitle'] = 'Потврда ажурирања адресе е-поште на $a->site'; // ORPHANED
$string['auth_fcchangepasswordurl'] = 'URL за промену лозинке'; // ORPHANED
$string['auth_fcconnfail'] = 'Повезивање није успело - грешка:$a[0] и текст грешке: $a[1]'; // ORPHANED
$string['auth_fccreators'] = 'Листа група чијим сарадницима је дозвољено да креирају нове курсеве. Одвојите спојене групе са \';\'. Имена морају бити написана управо онако као на FirstClass серверу. Систем води рачуна о великим и малим словима.'; // ORPHANED
$string['auth_fccreators_key'] = 'Творац'; // ORPHANED
$string['auth_fcdescription'] = 'Ова метода користи FirstClass сервер за проверу да ли су додељено корисничко име и лозинка исправни.'; // ORPHANED
$string['auth_fcfppport'] = 'Серверски порт (3333 је најчешћи)'; // ORPHANED
$string['auth_fcfppport_key'] = 'Порт'; // ORPHANED
$string['auth_fchost'] = 'Адреса FirstClass сервера. Користите IP број или DSN име.'; // ORPHANED
$string['auth_fchost_key'] = 'Домаћин'; // ORPHANED
$string['auth_fcpasswd'] = 'Лозинка за горњи налог.'; // ORPHANED
$string['auth_fcpasswd_key'] = 'Лозинка'; // ORPHANED
$string['auth_fctitle'] = 'Користити FirstClass сервер'; // ORPHANED
$string['auth_fcuserid'] = 'Корисник FirstClass налога са комплетним привилегијама \'подадминистратор\'.'; // ORPHANED
$string['auth_fcuserid_key'] = 'Идентификатор корисника'; // ORPHANED
$string['auth_imapchangepasswordurl_key'] = 'URL за промену лозинке'; // ORPHANED
$string['auth_imapdescription'] = 'Овај метод користи IMAP сервер да провери да ли су додељено корисничко име и лозинка исправни.'; // ORPHANED
$string['auth_imaphost'] = 'IMAP адреса сервера. Користите IP број, а не DNS називе.'; // ORPHANED
$string['auth_imaphost_key'] = 'Домаћин'; // ORPHANED
$string['auth_imapnotinstalled'] = 'Није могуће коришћење IMAP провере идентитета. PHP IMAP модул није инсталиран'; // ORPHANED
$string['auth_imapport'] = 'Број порта IMAP сервера. Обично је 143 или 993.'; // ORPHANED
$string['auth_imapport_key'] = 'Порт'; // ORPHANED
$string['auth_imaptitle'] = 'Користити IMAP сервер'; // ORPHANED
$string['auth_imaptype'] = 'Тип IMAP сервера. IMAP сервери могу имати различите типове провере идентитета.'; // ORPHANED
$string['auth_imaptype_key'] = 'Тип'; // ORPHANED
$string['auth_invalidnewemailkey'] = 'Грешка: Ако покушавате потврду измене адресе е-поште, можда сте направили грешку при копирању URL линка који смо Вам послали путем е-поште. Молимо Вас да копирате адресу и покушате поново.'; // ORPHANED
$string['auth_ldap_ad_create_req'] = 'Није могуће креирати корисника у активном директоријуму. Проверите да ли су испуњени да ли су испуњени сви захтеви да би ова активност успела LDAPS повезивање, везивање корисника за одговарајућа овлашћења, итд.)'; // ORPHANED
$string['auth_ldap_attrcreators'] = 'Списак група или контекста чијим члановима је допуштено да креирају особине. Одвајати посебне групе са \';\'. Обично нешто налик \'cn=наставници,ou=особље,o=мојаорг\''; // ORPHANED
$string['auth_ldap_attrcreators_key'] = 'Креатори особина'; // ORPHANED
$string['auth_ldap_auth_user_create_key'] = 'Екстерно креирање корисника'; // ORPHANED
$string['auth_ldap_bind_dn'] = 'Ако желите да користите везног корисника за претрагу корисника, одредите то овде. Нешто налик на \'cn=ldapuser,ou=public,o=org\''; // ORPHANED
$string['auth_ldap_bind_dn_key'] = 'Карактеристично име'; // ORPHANED
$string['auth_ldap_bind_pw'] = 'Лозинка за везног корисника.'; // ORPHANED
$string['auth_ldap_bind_pw_key'] = 'Лозинка'; // ORPHANED
$string['auth_ldap_bind_settings'] = 'Bind подешавања'; // ORPHANED
$string['auth_ldap_changepasswordurl_key'] = 'URL за промену лозинке'; // ORPHANED
$string['auth_ldap_contexts'] = 'Листа контекста где су корисници лоцирани. Раздвојите различите контексте са \';\'. На пример : \'ou=users,o=org; ou=others,o=org\''; // ORPHANED
$string['auth_ldap_contexts_key'] = 'Контекст'; // ORPHANED
$string['auth_ldap_create_context'] = 'Ако омогућите креирање корисника са потврдом путем е-поште, назначите контекст у ком су корисници креирани. Требало би да је тај контекст другачији од контекста осталих корисника да би се спречили сигурносни проблеми. Нема потребе додавати овај контекст у ldap_context-variable, јер ће Moodle потражити кориснике из тог садржаја аутоматски.<br /><b>Напомена:</b> Морате изменити функцију auth_user_create() у датотеци auth/ldap/lib.php да бисте омогућили креирање корисника'; // ORPHANED
$string['auth_ldap_create_context_key'] = 'Контекст за новог корисника'; // ORPHANED
$string['auth_ldap_create_error'] = 'Грешка при креирању новог  корисника у LDAP.'; // ORPHANED
$string['auth_ldap_creators'] = 'Листа група чијим члановима је дозвољено креирање нових курсева. Раздвојите вишеструке групе са \';\'. Обично нешто попут \'cn=teachers,ou=staff,o=myorg\''; // ORPHANED
$string['auth_ldap_creators_key'] = 'Творци'; // ORPHANED
$string['auth_ldap_expiration_desc'] = 'Изаберите НЕ да онемогућите проверу истека лозинке или LDAP да учитате време истека лозинке директно са LDAP-a.'; // ORPHANED
$string['auth_ldap_expiration_key'] = 'Престанак важења'; // ORPHANED
$string['auth_ldap_expiration_warning_desc'] = 'Број дана пре истека лозинке кад се кориснику шаље упозорење о истицању лозинке.'; // ORPHANED
$string['auth_ldap_expiration_warning_key'] = 'Упозорење о престанку важења'; // ORPHANED
$string['auth_ldap_expireattr_desc'] = 'Опционо: Мимоиђите LDAP атрибуте који су потребни за чување времена престанка важења лозинке passwordExpirationTime'; // ORPHANED
$string['auth_ldap_expireattr_key'] = 'Атрибути престанка важења'; // ORPHANED
$string['auth_ldap_graceattr_desc'] = 'Опционо: Мимоиђите почек уноса атрибута'; // ORPHANED
$string['auth_ldap_gracelogin_key'] = 'Атрибут одложене пријаве'; // ORPHANED
$string['auth_ldap_gracelogins_desc'] = 'Омогућите LDAP подршку за почек уноса. Наком истека лозинке корисник може приступати систему све док је износ почека уноса 0. Ако је лозинка истекла омогућите ова подешавања за приказивање поруке почека уноса.'; // ORPHANED
$string['auth_ldap_gracelogins_key'] = 'Одложене пријаве'; // ORPHANED
$string['auth_ldap_groupecreators'] = 'Списак група или контекста чијим члановима је допуштено да креирају групе. Одвајати посебне групе са \';\'. Обично нешто налик \'cn=наставници,ou=особље,o=мојаорг\''; // ORPHANED
$string['auth_ldap_groupecreators_key'] = 'Креатори група'; // ORPHANED
$string['auth_ldap_host_url'] = 'Назначите LDAP домаћина у URL-форми као што је \'ldap://ldap.myorg.com/\' или \'ldaps://ldap.myorg.com/\' Одвојите вишеструке сервере знаком \';\' да бисте добили подршку при превазилажењу проблема везаних за пад система'; // ORPHANED
$string['auth_ldap_host_url_key'] = 'URL домаћина'; // ORPHANED
$string['auth_ldap_ldap_encoding'] = 'Наведите кодирање коришћено од стране LDAP сервера. Највероватније utf-8, MS AD v2 користи подразумевану платформу кодирања као што је cp1252, cp1250, etc.'; // ORPHANED
$string['auth_ldap_ldap_encoding_key'] = 'LDAP кодирање'; // ORPHANED
$string['auth_ldap_login_settings'] = 'Подешавања везана за приступ корисника систему'; // ORPHANED
$string['auth_ldap_memberattribute'] = 'Опционо: Одређује корисников члански атрибут, кад корисник припада групи. Обично \'member\''; // ORPHANED
$string['auth_ldap_memberattribute_isdn'] = 'Опционо: Редефинише руковање вредностима атрибута чланова, или 0 или 1'; // ORPHANED
$string['auth_ldap_memberattribute_isdn_key'] = 'Атрибути чланова користе dn'; // ORPHANED
$string['auth_ldap_memberattribute_key'] = 'Атрибути чланова'; // ORPHANED
$string['auth_ldap_no_mbstring'] = 'Потребно је проширење mbstringа за креирање корисника у активном директоријуму.'; // ORPHANED
$string['auth_ldap_noconnect'] = 'LDAP модул није у могућности да се повеже на сервер: $a'; // ORPHANED
$string['auth_ldap_noconnect_all'] = 'LDAP модул није у могућности да се повеже на неки сервер: $a'; // ORPHANED
$string['auth_ldap_noextension'] = 'Упозорење: Могуће је да PHP LDAP модул није присутан. Молимо проверите да ли је инсталиран и омогућен.'; // ORPHANED
$string['auth_ldap_objectclass'] = 'Опционо: Одређује objectClass користећи име/тражећи корисника на ldap_user_type. Обично нема потребе да ово мењате.'; // ORPHANED
$string['auth_ldap_objectclass_key'] = 'Класе објеката'; // ORPHANED
$string['auth_ldap_opt_deref'] = 'Установите како управљати усвојеним именима у току тражења. Изаберите једну од пратећих вредности: 
\"Не\" (LDAP_DEREF_NEVER) или \"Да\" (LDAP_DEREF_ALWAYS)'; // ORPHANED
$string['auth_ldap_opt_deref_key'] = 'Опозови усвојена имена'; // ORPHANED
$string['auth_ldap_passtype'] = 'Одредите формат нове или измењене лозинке на LDAP серверу.'; // ORPHANED
$string['auth_ldap_passtype_key'] = 'Формат лозинке'; // ORPHANED
$string['auth_ldap_passwdexpire_settings'] = 'Подешавања LDAP истека лозинке'; // ORPHANED
$string['auth_ldap_preventpassindb'] = 'Изаберите \"da\" да бисте спречили чување лозинки у Moodle бази података.'; // ORPHANED
$string['auth_ldap_preventpassindb_key'] = 'Сакриј лозинке'; // ORPHANED
$string['auth_ldap_search_sub'] = 'Ставите вредност <> 0 ако желите да тражите кориснике у потконтекстима'; // ORPHANED
$string['auth_ldap_search_sub_key'] = 'Претражи подконтекст'; // ORPHANED
$string['auth_ldap_server_settings'] = 'Подешавања LDAP сервера'; // ORPHANED
$string['auth_ldap_unsupportedusertype'] = 'auth: ldap user_create() не подржава одабрани тип корисника: $a (..yet)'; // ORPHANED
$string['auth_ldap_update_userinfo'] = 'Ажурирајте информације корисника (име, презиме, адресе...) из LDAP-a у Moodle. Специфицирајте подешавања за мапирање података према сопственим потребама.'; // ORPHANED
$string['auth_ldap_user_attribute'] = 'Атрибут који се користи за име/претрагу корисника. Углавном је \'cn\'.'; // ORPHANED
$string['auth_ldap_user_attribute_key'] = 'Атрибути корисника'; // ORPHANED
$string['auth_ldap_user_exists'] = 'LDAP корисничко име већ постоји'; // ORPHANED
$string['auth_ldap_user_settings'] = 'Подешавања претраге корисника'; // ORPHANED
$string['auth_ldap_user_type'] = 'Изаберите како се корисник чува у LDAP. Ово подешавање такође одређује како ће функционисати истек уписа, почек уноса и креирање корисника.'; // ORPHANED
$string['auth_ldap_user_type_key'] = 'Тип корисника'; // ORPHANED
$string['auth_ldap_usertypeundefined'] = 'config.user_type није дефинисано или функција ldap_expirationtime2unix не подржава одабрани тип!'; // ORPHANED
$string['auth_ldap_usertypeundefined2'] = 'config.user_type није дефинисано или функција ldap_unixi2expirationtime не подржава одабрани тип!'; // ORPHANED
$string['auth_ldap_version'] = 'Верзија LDAP протокола коју Ваш сервер користи.'; // ORPHANED
$string['auth_ldap_version_key'] = 'Верзија'; // ORPHANED
$string['auth_ldapdescription'] = 'Овај метод служи за проверу идентитета од стране спољашњег LDAP сервера.
Ако су додељено корисничко име и лозинка исправни, Moodle креира нову инстанцу корисника у својој бази података.
Овај модул може читати корисничке атрибуте са LDAP-a и поставити тражена поља у Moodle. За следеће уписе само се проверавају корисничко име и лозинка.'; // ORPHANED
$string['auth_ldapextrafields'] = 'Ова поља нису обавезна. Можете изабрати да испуните нека Moodle корисничка поља са информацијама из <b>LDAP поља</b> која овде одредите. <br />Ако поља оставите празна, онда се ништа неће пребацити са LDAP-a, тако да ће бити коришћене подразумеване Moodle вредности.<br />У сваком случају, корисници могу да уређују ова поља након приступа систему.'; // ORPHANED
$string['auth_ldapnotinstalled'] = 'Није могуће коришћење LDAP провере идентитета. The PHP LDAP модул није инсталиран.'; // ORPHANED
$string['auth_ldaptitle'] = 'Користити LDAP сервер.'; // ORPHANED
$string['auth_manualdescription'] = 'Овај метод уклања корисницима све начине прављења њихових сопствених налога. Све налоге мора ручно направити администратор.'; // ORPHANED
$string['auth_manualtitle'] = 'Само за ручно прављење налога'; // ORPHANED
$string['auth_mnet_auto_add_remote_users'] = 'Када је постављено на \"Да\", слог локалног корисника се аутоматски креира када се удаљени корисник пријави први пут.'; // ORPHANED
$string['auth_mnet_roamin'] = 'Ови корисници домаћина могу укрстарити у Вашу област.'; // ORPHANED
$string['auth_mnet_roamout'] = 'Ваши корисници могу искрстарити на ове домаћине.'; // ORPHANED
$string['auth_mnet_rpc_negotiation_timeout'] = 'Прекид времена за проверу идентитета  преко XMLRPC преноса у секундама.'; // ORPHANED
$string['auth_mnetdescription'] = 'Извршена провера идентитета корисника у складу са мрежом поверења дефинисаном у подешавањима Moodle мреже.'; // ORPHANED
$string['auth_mnettitle'] = 'Провера идентитета у Moodle мрежи'; // ORPHANED
$string['auth_nntpchangepasswordurl_key'] = 'URL за промену лозинке'; // ORPHANED
$string['auth_nntpdescription'] = 'Овај метод користи NNTP сервер за проверу исправности корисничких имена и лозинки.'; // ORPHANED
$string['auth_nntphost'] = 'NNTP адресе сервера. Користите IP број, а не DNS називе.'; // ORPHANED
$string['auth_nntphost_key'] = 'Домаћин'; // ORPHANED
$string['auth_nntpnotinstalled'] = 'Није могуће користити NNTP проверу идентитета. PHP IMAP модул није инсталиран.'; // ORPHANED
$string['auth_nntpport'] = 'Серверски порт (119 је најчешћи)'; // ORPHANED
$string['auth_nntpport_key'] = 'Порт'; // ORPHANED
$string['auth_nntptitle'] = 'Користити NNTP сервер.'; // ORPHANED
$string['auth_nologindescription'] = 'Помоћни дадатак који спречава кориснике да се пријаве на систем и такође одбацује свако слање поште кориснику. Може се користити за <em>suspend</em> корисничке налоге.'; // ORPHANED
$string['auth_nologintitle'] = 'Нема пријаве'; // ORPHANED
$string['auth_nonedescription'] = 'Корисници се могу уписати и одмах направити важеће налоге, без провере идентитета од стране спољашњег сервера и без потврде путем е-поште.
Будите опрезни кад користите ову опцију - мислите на сигурност и административне проблеме који њоме могу бити проузроковани!'; // ORPHANED
$string['auth_nonetitle'] = 'Нема провере идентитета'; // ORPHANED
$string['auth_ntlmsso'] = 'NTLM SSO'; // ORPHANED
$string['auth_ntlmsso_enabled'] = 'Поставите на Да за покушај једне пријаве са NTLM доменом. <strong>Напомена:</strong> да би ово радило, захтевају се додатна подешавања веб-сервера, видети <a href=\"http://docs.moodle.org/en/NTLM_authentication\">http://docs.moodle.org/en/NTLM_authentication</a>'; // ORPHANED
$string['auth_ntlmsso_enabled_key'] = 'Укључи'; // ORPHANED
$string['auth_ntlmsso_subnet'] = 'Ако је укључено, покушаће само са клијентима из ове подмреже. Формат: xxx.xxx.xxx.xxx/bitmas'; // ORPHANED
$string['auth_ntlmsso_subnet_key'] = 'Подмрежа'; // ORPHANED
$string['auth_outofnewemailupdateattempts'] = 'Више немате право на покушаје ажурирања Ваше адресе е-поште. Ваш захтев за ажурирање је одбијен.'; // ORPHANED
$string['auth_pamdescription'] = 'Овај метод користи PAM за приступ корисничком имену на домаћем серверу. Морате инсталирати <a href=\"http://www.math.ohio-state.edu/~ccunning/pam_auth/\" target=\"_blank\">PHP4 PAM проверу идентитета</a> да бисте користили овај модул.'; // ORPHANED
$string['auth_pamtitle'] = 'PAM (Pluggable Authentication Modules)'; // ORPHANED
$string['auth_passwordisexpired'] = 'Ваша лозинка је истекла. Желите ли сад да је промените?'; // ORPHANED
$string['auth_passwordwillexpire'] = 'Ваша лозинка ће истећи за $a дана. Желите ли сад да је промените?'; // ORPHANED
$string['auth_pop3changepasswordurl_key'] = 'URL за промену лозинке'; // ORPHANED
$string['auth_pop3description'] = 'Овај метод користи POP3 сервер за проверу исправности корисничких имена и лозинки.'; // ORPHANED
$string['auth_pop3host'] = 'POP3 адреса сервера. Користите IP број, а не DNS назив.'; // ORPHANED
$string['auth_pop3host_key'] = 'Домаћин'; // ORPHANED
$string['auth_pop3mailbox'] = 'Назив mailbox-a с којим треба успоставити везу. (обично INBOX)'; // ORPHANED
$string['auth_pop3mailbox_key'] = 'Поштанско сандуче'; // ORPHANED
$string['auth_pop3notinstalled'] = 'Није могуће користити POP3 проверу идентитета. PHP IMAP модул није инсталиран.'; // ORPHANED
$string['auth_pop3port'] = 'Порт на серверу (најчешће је то 110, а порт 995 је чест за SSL)'; // ORPHANED
$string['auth_pop3port_key'] = 'Порт'; // ORPHANED
$string['auth_pop3title'] = 'Користити POP3 сервер'; // ORPHANED
$string['auth_pop3type'] = 'Тип сервера. Ако Ваш сервер користи сигурносне сертификате, изаберите pop3cert.'; // ORPHANED
$string['auth_pop3type_key'] = 'Тип'; // ORPHANED
$string['auth_radiuschangepasswordurl_key'] = 'URL за промену лозинке'; // ORPHANED
$string['auth_radiusdescription'] = 'Овај метод користи <a href=\"http://en.wikipedia.org/wiki/RADIUS\" target=\"_blank\">RADIUS</a> сервер за проверу да ли су дато корисничко име и лозинка валидни.'; // ORPHANED
$string['auth_radiushost'] = 'Адреса RADIUS сервера'; // ORPHANED
$string['auth_radiushost_key'] = 'Домаћин'; // ORPHANED
$string['auth_radiusnasport'] = 'Порт који ће се користити за успостављање везе'; // ORPHANED
$string['auth_radiusnasport_key'] = 'Порт'; // ORPHANED
$string['auth_radiussecret'] = 'Јавна тајна'; // ORPHANED
$string['auth_radiussecret_key'] = 'Сакриј'; // ORPHANED
$string['auth_radiustitle'] = 'Користити RADIUS сервер'; // ORPHANED
$string['auth_radiustype_key'] = 'Провера идентитета'; // ORPHANED
$string['auth_radiustypechapmd5'] = 'CHAP MD5'; // ORPHANED
$string['auth_radiustypemschapv1'] = 'Mајкрософт CHAP верзија 1'; // ORPHANED
$string['auth_radiustypemschapv2'] = 'Mајкрософт CHAP верзија 2'; // ORPHANED
$string['auth_radiustypepap'] = 'PAP'; // ORPHANED
$string['auth_shib_changepasswordurl'] = 'URL за промену лозинке'; // ORPHANED
$string['auth_shib_convert_data'] = 'API за модификације података'; // ORPHANED
$string['auth_shib_convert_data_description'] = 'Можете да користите овај API за даље модификације података које омогућава Shibboleth. Прочитајте <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">README</a> за даља упутства.'; // ORPHANED
$string['auth_shib_convert_data_warning'] = 'Датотека не постоји или је процес веб сервера не може читати!'; // ORPHANED
$string['auth_shib_instructions'] = 'Користите <a href=\"$a\">Shibboleth приступ систему</a> да бисте добили приступ преко Shibboleth-a, ако га Ваша институција подржава.<br />У супротном, користите нормалну приступну форму приказану овде.'; // ORPHANED
$string['auth_shib_instructions_help'] = 'Овде бисте требали поставити сопствена упутства да бисте Вашим корисницима објаснили Shibboleth. Она ће бити приказана на приступној страници у одељку са упутствима. Упутства морају садржати линк до \"<b>$a</b>\" на који ће корисници кликнути кад буду желели да да приступе систему.'; // ORPHANED
$string['auth_shib_no_organizations_warning'] = 'Уколико желите да користите интегрисани WAYF сервис, морате да дате листу Провајдера идентитета (Identity Provider entityIDs) раздвојену зарезом, њихова имена и опционо покретача сесије.'; // ORPHANED
$string['auth_shib_only'] = 'Само Shibboleth'; // ORPHANED
$string['auth_shib_only_description'] = 'Потврдите ову опцију ако ће се примењивати Shibboleth провера идентитета'; // ORPHANED
$string['auth_shib_username_description'] = 'Назив веб сервера променљиве Shibboleth окружења која ће се користити као Moodle корисничко име'; // ORPHANED
$string['auth_shibboleth_contact_administrator'] = 'У случају да нисте повезани са датом организацијом а потребан Вам је приступ курсу на овом серверу, молимо Вас да контактирате администратора'; // ORPHANED
$string['auth_shibboleth_errormsg'] = 'Молимо вас да одаберете организацију чији сте члан!'; // ORPHANED
$string['auth_shibboleth_login'] = 'Shibboleth приступ систему'; // ORPHANED
$string['auth_shibboleth_login_long'] = 'Пријава на Moodle путем Shibboletha'; // ORPHANED
$string['auth_shibboleth_manual_login'] = 'Ручни пријава на систем'; // ORPHANED
$string['auth_shibboleth_select_member'] = 'Члан сам ...'; // ORPHANED
$string['auth_shibboleth_select_organization'] = 'За проверу идентитета путем Shibboletha, одаберите своју организацију из падајуће листе:'; // ORPHANED
$string['auth_shibbolethdescription'] = 'Коришћењем овог метода корисници се креирају и проверава им се идентитет помоћу <a href=\"http://shibboleth.internet2.edu/\" target=\"_blank\">Shibboleth-a</a>.<br>Обавезно прочитајте <a href=\"../auth/shibboleth/README.txt\" target=\"_blank\">УПУТСТВО</a> за подешавање Вашег Moodle сајта са Shibboleth-om'; // ORPHANED
$string['auth_shibbolethtitle'] = 'Shibboleth'; // ORPHANED
$string['auto_add_remote_users'] = 'Аутоматско додавање удаљеног корисника'; // ORPHANED
$string['ntlmsso_attempting'] = 'Покушава се само једна пријава преко NTLM...'; // ORPHANED
$string['ntlmsso_failed'] = 'Аутоматско пријављивање није успело, покушајте са обичном страницом за пријаву'; // ORPHANED
$string['ntlmsso_isdisabled'] = 'NTLM SSO (јединствена пријава) није укључено'; // ORPHANED
$string['rpc_negotiation_timeout'] = 'RPC посредовање у прекидима'; // ORPHANED
$string['shib_no_attributes_error'] = 'Чини се да Вам је идентитет проверен Shibboleth-om, али Moodle није добио никакве атрибуте корисника. Молимо проверите да ли Ваш давалац идентитета издаје неопходне атрибуте ($a) за даваоца услуга на ком Moodle ради или информишите вебмастера овог сервера.'; // ORPHANED
$string['shib_not_all_attributes_error'] = 'Moodle-u су неопходни извесни Shibboleth атрибути, који у Вашем случају нису присутни. Потребни атрибути су: $a<br />Молимо контактирајте вебмастерa овог сервера или свог даваоца идентитета.'; // ORPHANED
$string['shib_not_set_up_error'] = 'Shibboleth провера идентитета изгледа није добро подешена, јер нема присутних варијабли Shibboleth окружења за ову страницу. Молимо погледајте <a href=\"README.txt\">README</a> за даља упутства за подешавање Shibboleth аутентикације или контактирајте вебмастерa ове Moodle инсталације.'; // ORPHANED


// Strings below here are module specific and will be duplicated in auth_* files
// Module specific language strings should also be copied into their respective
// auth_*.php files to ensure compatibility in all versions of Moodle

$string['auth_ntlmsso_ie_fastpath_key'] = 'MS IE брза путања?';
$string['auth_radiustype'] = 'Иаберите шему за проверу идентитета која ће се користити са RADIUS сервером.';
$string['auth_shib_auth_method'] = 'Назив метода за проверу идентитета';
$string['auth_shib_idp_list'] = 'Даваоци идентитета';
$string['auth_shib_integrated_wayf'] = 'Moodle WAYF Сервис';
$string['auth_shib_integrated_wayf_description'] = 'Уколико потврдите ово Moodle ће користити свој WAYF сервис уместо оног који је конфигурисан за Shibboleth. Moodle ће приказати падајућу лист на овој алтернативној страници за пријаву на систем где ће корисник моћи да изабере свог Даваоца идентитета.';
$string['sso_idp_description'] = 'Активирајте ову опцију да бисте дозволили својим корисницима да приступају Moodle сајту $a без поновне пријаве. <ul><li><em>Зависност</em>: Морате бити <strong>пријављени</strong> за SSO (давалац услуга) сервис на $a.</li></ul><br />Пријавите се за овај сервис да бисте дозволили корисницима који су прошли проверу идентитета на сајту $a да приступају вашем сајту без поновне пријаве. <ul><li><em>Зависност</em>: Морате <strong>активирати</strong> SSO (давалац услуга) сервис за $a.</li></ul><br />';
$string['sso_idp_name'] = 'SSO (давалац идентитета)';
$string['sso_mnet_login_refused'] = 'Кориснику $a[0] није дозовољено да се пријави са $a[1].';
$string['sso_sp_description'] = 'Активирајте ову опцију да бисте дозволили корисницима који су прошли проверу идентитета на сајту $a да приступају вашем сајту без поновне пријаве. <ul><li><em>Зависност</em>: Морате бити <strong>пријављени</strong> за SSO (давалац идентитета) сервис на $a.</li></ul><br />Пријавите се за овај сервис да бисте дозволили својим корисницима да приступају Moodle сајту $a без поновне пријаве. <ul><li><em>Зависност</em>: Морате <strong>активирати</strong> SSO (давалац идентитета) сервис за $a.</li></ul><br />';
$string['sso_sp_name'] = 'SSO (давалац услуга)';

?>
