<?PHP // $Id$ 
      // blog.php - created with Moodle 1.9.2+ (Build: 20080806) (2007101521)


$string['addnewentry'] = 'Додавање новог уноса';
$string['backupblogshelp'] = 'Ако је укључено, тада ће блогови бити укључени у аутоматско креирање резервних копија на нивоу сајта';
$string['blockmenutitle'] = 'Мени блога';
$string['blocktagstitle'] = 'Ознаке блога';
$string['blocktitle'] = 'Наслов блока са ознакама блога';
$string['blog'] = 'Блог';
$string['blogdeleteconfirm'] = 'Обрисати овај блог?';
$string['blogdisable'] = 'Блогови су онемогућени!';
$string['blogpreferences'] = 'Својства блога';
$string['blogs'] = 'Блогови';
$string['blogtags'] = 'Ознаке блога';
$string['cannotviewcourseblog'] = 'Немате захтеване привилегије да прегледате блогове на овом курсу';
$string['cannotviewcourseorgroupblog'] = 'Немате захтеване привилегије да прегледате блогове на овом курсу/групи';
$string['cannotviewsiteblog'] = 'Немате захтеване привилегије да прегледате све блогове на сајту';
$string['cannotviewuserblog'] = 'Немате захтеване привилегије да читате блогове корисника';
$string['courseblog'] = 'Блог курса: $a';
$string['courseblogdisable'] = 'Блогови на курсу нису омогућени';
$string['courseblogs'] = 'Корисници могу да виде само блогове људи с којима деле курс';
$string['deleteotagswarn'] = 'Да ли сте сигурни да желите да уклоните ову/ове ознаке <br />из свих блог уноса у уклоните је/их из система?';
$string['deleteposterror'] = 'Дошло је до грешке при брисању поруке';
$string['disableblogs'] = 'Потпуно онемогућити коришћење блог система';
$string['emptybody'] = 'Тело блог уноса не може остати непопуњено';
$string['emptytitle'] = 'Наслов блог уноса не може остати непопуњен';
$string['entrybody'] = 'Тело блог уноса';
$string['entrybodyonlydesc'] = 'Опис уноса';
$string['entryerrornotyours'] = 'Овај унос није Ваш';
$string['entrysaved'] = 'Ваш унос је сачуван';
$string['entrytitle'] = 'Наслов уноса';
$string['entryupdated'] = 'Ажуриран је блог унос';
$string['groupblog'] = 'Блог групе: $a';
$string['groupblogdisable'] = 'Блог групе није омогућен';
$string['groupblogs'] = 'Корисници могу да виде само блогове људи с којима деле групу';
$string['incorrectblogfilter'] = 'Задат је неисправан тип филтра блога';
$string['intro'] = 'Овај RSS извор података је аутоматски генерисан из једног или више блогова.';
$string['noentriesyet'] = 'Овде нема доступних уноса';
$string['noguestpost'] = 'Гости не могу да пишу блог уносе!';
$string['norighttodeletetag'] = 'Немате право да обришете ову ознаку - $a';
$string['nosuchentry'] = 'Нема таквог блог уноса';
$string['notallowedtoedit'] = 'Немате право да уређујете овај унос';
$string['numberofentries'] = 'Уноси: $a';
$string['numberoftags'] = 'Број ознака за приказ';
$string['pagesize'] = 'Број блог уноса по страници';
$string['permalink'] = 'Permalink';
$string['personalblogs'] = 'Корисници могу да виде само свој блог';
$string['publishto'] = 'Објавити за';
$string['publishtonoone'] = 'Себе самог (концепт)';
$string['publishtosite'] = 'Све на овом сајту';
$string['publishtoworld'] = 'Све на свету';
$string['settingsupdatederror'] = 'Дошло је до грешке, подешавање својстава блога није могло бити ажурирано';
$string['siteblog'] = 'Блог сајта: $a';
$string['siteblogdisable'] = 'Блог сајта није омогућен';
$string['siteblogs'] = 'Сви корисници сајта могу да виде све блог уносе';
$string['tagdatelastused'] = 'Датум кад је ознака последњи пут коришћена';
$string['tags'] = 'Ознаке';
$string['tagsort'] = 'Сортирати приказ ознака по';
$string['tagtext'] = 'Текст ознаке';
$string['timewithin'] = 'Приказ ознака коришћених у оволико последњих дана';
$string['updateentrywithid'] = 'Ажурирање уноса';
$string['userblog'] = 'Блог корисника: $a';
$string['viewcourseentries'] = 'Приказ уноса курса';
$string['viewmyentries'] = 'Приказ мојих уноса';
$string['viewsiteentries'] = 'Приказ уноса сајта';
$string['worldblogs'] = 'Цео свет може да чита уносе постављене као глобално доступне';
$string['wrongpostid'] = 'Погрешан id поруке на блогу';
$string['addotags'] = 'Додавање званичних ознака'; // ORPHANED
$string['addptags'] = 'Додавање корисничких ознака'; // ORPHANED
$string['otags'] = 'Званичне ознаке'; // ORPHANED
$string['ptags'] = 'Корисничке ознаке'; // ORPHANED

?>
