<?PHP // $Id$ 
      // data.php - created with Moodle 1.9.9 (Build: 20100609) (2007101590)


$string['action'] = 'Акција';
$string['add'] = 'Додај унос';
$string['addafield'] = 'Додај поље';
$string['addcomment'] = 'Додај коментар';
$string['addentries'] = 'Додај уносе';
$string['addtemplate'] = 'Шаблон за додавање';
$string['advancedsearch'] = 'Напредно претраживање';
$string['allowcomments'] = 'Дозволити коментаре?';
$string['allowratings'] = 'Дозволити оцењивање порука?';
$string['alttext'] = 'Алтернативни текст';
$string['approve'] = 'Одобри';
$string['approved'] = 'Одобрено';
$string['ascending'] = 'Растуће';
$string['asearchtemplate'] = 'Шаблон за напредно претраживање';
$string['atmaxentry'] = 'Унели сте максималан дозвољени број уноса!';
$string['authorfirstname'] = 'Име аутора';
$string['authorlastname'] = 'Презиме аутора';
$string['autogenallforms'] = 'Генерисање свих подразумеваних шаблона';
$string['autolinkurl'] = 'Аутоматско линковање URL-a';
$string['availablefromdate'] = 'Доступно од';
$string['availabletags'] = 'Доступне ознаке';
$string['availabletodate'] = 'Доступно до';
$string['blank'] = 'Празно';
$string['buttons'] = 'Дугмад';
$string['bynameondate'] = 'унео/ла $a->name дана $a->date';
$string['cancel'] = 'Одустани';
$string['checkbox'] = 'Поље за потврду';
$string['chooseexportfields'] = 'Изаберите поља која желите извозити:';
$string['chooseexportformat'] = 'Изаберите формат у који желите извозити:';
$string['chooseorupload'] = 'Одабери датотеку';
$string['columns'] = 'колоне';
$string['comment'] = 'Коментар';
$string['commentdeleted'] = 'Коментар је обрисан';
$string['commentempty'] = 'Коментар је био празан';
$string['comments'] = 'Коментари';
$string['commentsaved'] = 'Коментар је сачуван';
$string['commentsn'] = '$a коментар(а)';
$string['configenablerssfeeds'] = 'Овај прекидач ће омогућити коришћење RSS сервиса за све базе података. Ипак ћете морати исту опцију ручно да укључите и у подешавањима сваке базе података.';
$string['confirmdeletefield'] = 'Управо ћете обрисати ово поље. Да ли сте сигурни да то желите?';
$string['confirmdeleterecord'] = 'Да ли сте сигурни да желите да обришете овај унос?';
$string['csstemplate'] = 'CSS шаблон';
$string['csvfailed'] = 'Није могуће прочитати необрађене податке из CSV датотеке';
$string['csvfile'] = 'CSV датотека';
$string['csvimport'] = 'Увоз CSV датотеке';
$string['csvwithselecteddelimiter'] = '<acronym title=\"Comma Separated Values\">CSV</acronym> текст са изабраним знаком раздвајања';
$string['data:approve'] = 'Одобравање неодобрених уноса';
$string['data:comment'] = 'Пиши коментаре';
$string['data:managecomments'] = 'Управљање коментарима';
$string['data:manageentries'] = 'Управљај уносима';
$string['data:managetemplates'] = 'Управљај шаблонима';
$string['data:manageuserpresets'] = 'Управљање свим шаблонима скупова подешавања';
$string['data:rate'] = 'Оцени уносе';
$string['data:readentry'] = 'Читај уносе';
$string['data:viewalluserpresets'] = 'Преглед постојећих скупова подешавање свих корисника';
$string['data:viewentry'] = 'Преглед уноса';
$string['data:viewrating'] = 'Преглед оцена';
$string['data:writeentry'] = 'Пиши уносе';
$string['date'] = 'Датум';
$string['dateentered'] = 'Датум уноса';
$string['defaultfielddelimiter'] = '(подразумевани знак је зарез)';
$string['defaultfieldenclosure'] = '(подразумевано је ништа)';
$string['defaultsortfield'] = 'Подразумевано сортирање поља';
$string['delete'] = 'Бриши';
$string['deleteallentries'] = 'Бриши све уносе';
$string['deletecomment'] = 'Да ли сте сигурни да желите да обришете овај коментар?';
$string['deleted'] = 'обрисано';
$string['deletefield'] = 'Брисање постојећег поља';
$string['deletenotenrolled'] = 'Бриши уносе корисника који нису уписани на курс';
$string['deletewarning'] = 'Да ли сте сигурни да желите да обришете постојећи скуп подешавања?';
$string['descending'] = 'Опадајуће';
$string['directorynotapreset'] = '$a->directory не постоји: датотеке које недостају су следеће: $a->missing_files';
$string['download'] = 'Преузми';
$string['edit'] = 'Уреди';
$string['editcomment'] = 'Уреди коментар';
$string['editentry'] = 'Уреди унос';
$string['editordisable'] = 'Онемогући уређивање';
$string['editorenable'] = 'Омогући уређивање';
$string['emptyadd'] = 'Додавање шаблона је празно, генерише се подразумевана форма...';
$string['emptyaddform'] = 'Нисте испунили ниједно поље!';
$string['entries'] = 'Уноси';
$string['entrieslefttoadd'] = 'Морате додати још $a->entriesleft унос(а) пре него што будете могли прегледати уносе других учесника.';
$string['entrieslefttoaddtoview'] = 'Морате да додате још $a->entrieslefttoview уноса пре него што будете могли да видите уносе других корисника.';
$string['entry'] = 'Унос';
$string['entrysaved'] = 'Ваш унос је сачуван';
$string['errormustbeteacher'] = 'Морате бити предавач да бисте користили ову страницу!';
$string['example'] = 'Пример модула базе података';
$string['excel'] = 'Excel';
$string['export'] = 'Извези';
$string['exportaszip'] = 'Извези у виду архиве';
$string['exportdatabaserecords'] = 'Извези записе базе података';
$string['exportedtozip'] = 'Извезено у привремену архиву...';
$string['failedpresetdelete'] = 'Грешка при брисању дефинисаног скупа подешавања!';
$string['fieldadded'] = 'Поље је додато';
$string['fieldallowautolink'] = 'Дозволити аутоматско линковање';
$string['fielddeleted'] = 'Поље је обрисано';
$string['fielddelimiter'] = 'Знак за раздвајање поља';
$string['fielddescription'] = 'Опис поља';
$string['fieldenclosure'] = 'Прилагање поља';
$string['fieldheight'] = 'Висина';
$string['fieldheightlistview'] = 'Висина у приказу листе';
$string['fieldheightsingleview'] = 'Висина у појединачном приказу';
$string['fieldids'] = 'Идентификатори поља';
$string['fieldmappings'] = 'Мапирање поља';
$string['fieldname'] = 'Назив поља';
$string['fieldnotmatched'] = 'Следећа поља у Вашој датотеци су непозната у овој бази података';
$string['fieldoptions'] = 'Опције (једна по линији)';
$string['fields'] = 'Поља';
$string['fieldupdated'] = 'Поље је ажурирано';
$string['fieldwidth'] = 'Ширина';
$string['fieldwidthlistview'] = 'Ширина у приказу листе';
$string['fieldwidthsingleview'] = 'Ширина у појединачном приказу';
$string['file'] = 'Датотека';
$string['filesnotgenerated'] = 'Нису све датотеке генерисане: $a';
$string['filtername'] = 'Аутоматско линковање базе података';
$string['footer'] = 'Подножје';
$string['forcelinkname'] = 'Обавезан назив за линковање';
$string['foundnorecords'] = 'Нису пронађени записи(<a href=\"$a->reseturl\">Врати стара подешавања филтера</a>)';
$string['foundrecords'] = 'Пронађени записи: $a->num/$a->max(<a href=\"$a->reseturl\">Врати стара подешавања филтера</a>)';
$string['fromfile'] = 'из архиве';
$string['header'] = 'Заглавље';
$string['headeraddtemplate'] = 'Дефинише интерфејс при уређивању уноса';
$string['headerasearchtemplate'] = 'Дефинише интерфејс за напредна претраживања';
$string['headercsstemplate'] = 'Дефинише локалне CSS стилове за друге шаблоне';
$string['headerjstemplate'] = 'Дефинише прилагођени Javascript за друге шаблоне';
$string['headerlisttemplate'] = 'Дефинише интерфејс прегледања вишеструких уноса';
$string['headerrsstemplate'] = 'Дефинише изглед уноса у RSS сервисима';
$string['headersingletemplate'] = 'Дефинише интерфејс прегледања појединачног уноса';
$string['importsuccess'] = 'Дефинисани скуп подешавања је успешно примењен.';
$string['insufficiententries'] = 'потребно је више уноса за преглед ове базе података';
$string['intro'] = 'Увод';
$string['invalidfieldname'] = 'Молимо изаберите неко друго име за ово поље';
$string['invalidrate'] = 'Неисправни ниво базе података ($a)';
$string['invalidurl'] = 'URL који сте управо унели није исправан';
$string['jstemplate'] = 'Javascript шаблон';
$string['latitude'] = 'Ширина';
$string['latlong'] = 'Ширина/дужина';
$string['latlongdownloadallhint'] = 'Преузимање линка за све уносе у KML облику';
$string['latlongkmllabelling'] = 'Како означити ставке у KML датотекама (Google Earth)';
$string['latlonglinkservicesdisplayed'] = 'Линковани сервиси за приказ';
$string['latlongotherfields'] = 'Остала поља';
$string['list'] = 'Прикажи листу';
$string['listtemplate'] = 'Шаблон за листу';
$string['longitude'] = 'Дужина';
$string['mappingwarning'] = 'Сва стара поља које нису мапирана на ново поље ће бити изгубљена и сви подаци у тим пољима ће бити уклоњени.';
$string['maxentries'] = 'Максимално уноса';
$string['maxsize'] = 'Максимална величина';
$string['menu'] = 'Мени';
$string['menuchoose'] = 'Изаберите...';
$string['modulename'] = 'База података';
$string['modulenameplural'] = 'Базе података';
$string['more'] = 'Још';
$string['moreurl'] = 'Још URL-a';
$string['movezipfailed'] = 'Није могуће преместити архиву';
$string['multientry'] = 'Поновљени унос';
$string['multimenu'] = 'Мени (могућност вишеструког избора)';
$string['multipletags'] = 'Пронађене су вишеструке ознаке! Шаблон није сачуван';
$string['namecheckbox'] = 'Поље за потврду';
$string['namedate'] = 'Поље за датум';
$string['namefile'] = 'Поље за датотеку';
$string['namelatlong'] = 'Поље ширине/дужине';
$string['namemenu'] = 'Поље менија';
$string['namemultimenu'] = 'Поље менија за вишеструки избор';
$string['namenumber'] = 'Поље за број';
$string['namepicture'] = 'Поље за слику';
$string['nameradiobutton'] = 'Поље за појединачан избор';
$string['nametext'] = 'Поље за текст';
$string['nametextarea'] = 'Поље за текстуалну област';
$string['nameurl'] = 'Поље за URL';
$string['newentry'] = 'Нови унос';
$string['newfield'] = 'Креирање новог поља';
$string['noaccess'] = 'Немате приступ овој страници';
$string['nodefinedfields'] = 'Ново постојећи скуп подешавања нема дефинисаних поља!';
$string['nofieldindatabase'] = 'Нема поља дефинисаних за ову базу података.';
$string['nolisttemplate'] = 'Шаблон листе још није дефинисан';
$string['nomatch'] = 'Нема уноса који се поклапају!';
$string['nomaximum'] = 'Нема максимума';
$string['norecords'] = 'Нема уноса у бази података';
$string['nosingletemplate'] = 'Још није дефинисан појединачни шаблон';
$string['notapproved'] = 'Унос још увек није одобрен';
$string['notinjectivemap'] = 'Мапа не може да се убаци';
$string['number'] = 'Број';
$string['numberrssarticles'] = 'RSS чланци';
$string['numnotapproved'] = 'На чекању';
$string['numrecords'] = '$a уноса';
$string['ods'] = '<acronym title=\"OpenDocument Spreadsheet\">ODS</acronym> (OpenOffice)';
$string['optionaldescription'] = 'Кратак опис (опционо)';
$string['optionalfilename'] = 'Назив датотеке (опционо)';
$string['other'] = 'Друго';
$string['overwrite'] = 'Препиши';
$string['overwritesettings'] = 'Препиши преко важећих подешавања';
$string['pagesize'] = 'Уноса по страници';
$string['participants'] = 'Учесници';
$string['picture'] = 'Слика';
$string['pleaseaddsome'] = 'Молимо креирајте неке испод или <a href=\"$a\">изаберите већ дефинисан скуп</a> за почетак.';
$string['presetinfo'] = 'Чување у виду скупа подешавања ће објавити овај шаблон. Други корисници ће можда моћи да га користе у својим базама података.';
$string['presets'] = 'Постојећи скупови подешавања';
$string['radiobutton'] = 'Дугмад за појединачни избор';
$string['rate'] = 'Оцени';
$string['rating'] = 'Оцена';
$string['ratingeveryone'] = 'Сви могу оцењивати поруке';
$string['ratingno'] = 'Без оцењивања';
$string['ratingonlyteachers'] = 'Само $a може оцењивати поруке';
$string['ratingpublic'] = '$a може видети свачије оцене';
$string['ratingpublicnot'] = '$a може видети само сопствене оцене';
$string['ratings'] = 'Оцене';
$string['ratingssaved'] = 'Оцене су сачуване';
$string['ratingsuse'] = 'Користити оцењивање';
$string['recordapproved'] = 'Унос је одобрен';
$string['recorddeleted'] = 'Унос је обрисан';
$string['recordsnotsaved'] = 'Није сачуван ниједан унос. Молимо проверите формат постављене датотеке.';
$string['recordssaved'] = 'уноси сачувани';
$string['requireapproval'] = 'Захтевати одобрење?';
$string['requiredentries'] = 'Потребни уноси';
$string['requiredentrieschanged'] = '<p><strong>ВАЖНО - МОЛИМО ПРОЧИТАЈТЕ</strong></p><p>Услед поправке грешке у кôду, биће измењено понашање активности у бази података коришћењем \'Обавезни ентитети\' и \'Обавезни уноси пре прегледа подешавања\'. Детаљније објашњење промена може се прочитати на <a href=\"http://moodle.org/mod/forum/discuss.php?d=110928\" target=\"_blank\">форуму за модул базе података</a>. Очекивано понашање ових подешавања може се прочитати такође у <a href=\"http://docs.moodle.org/en/Adding/editing_a_database#Required_entries\" target=\"_blank\">Moodle Docs</a>.</p><p>Ова промена утиче на следеће базе података у Вашем систему: (Молимо да сачувате сада овај списак и после унапређења проверите да ли ове активности још увек раде на начин који наставник жели.)</p><strong style=\"color:red\">$a->text</strong><br/>';
$string['requiredentriestoview'] = 'Уноси потребни пре прегледања';
$string['resetsettings'] = 'Ресетуј поље';
$string['resettemplate'] = 'Ресетуј шаблон';
$string['resizingimages'] = 'Промена величине умањеног приказа слике...';
$string['rows'] = 'редови';
$string['rssglobaldisabled'] = 'Онемогућено. Погледајте променљиве конфигурације сајта.';
$string['rsshowmany'] = '(број последњих уноса за приказ, 0 за онемогућавање RSS-a)';
$string['rsstemplate'] = 'RSS шаблон';
$string['rsstitletemplate'] = 'Шаблон RSS наслова';
$string['save'] = 'Сачувај';
$string['saveandadd'] = 'Сачувај и додај још';
$string['saveandview'] = 'Сачувај и прикажи';
$string['saveaspreset'] = 'Сачувај као скуп подешавања';
$string['savesettings'] = 'Сачувај подешавања';
$string['savesuccess'] = 'Успешно сачувано. Ваш скуп подешавања ће бити доступан на читавом сајту.';
$string['savetemplate'] = 'Сачувај шаблон';
$string['search'] = 'Тражи';
$string['selectedrequired'] = 'Све изабрано обавезно';
$string['sendinratings'] = 'Пошаљи у моје последње оцене';
$string['showall'] = 'Прикажи све уносе';
$string['single'] = 'Прикажи појединачно';
$string['singletemplate'] = 'Појединачни шаблон';
$string['teachersandstudents'] = '$a->teachers и $a->students';
$string['templates'] = 'Шаблони';
$string['templatesaved'] = 'Шаблони су сачувани';
$string['text'] = 'Текст';
$string['textarea'] = 'Текстуална област';
$string['timeadded'] = 'Време додавања';
$string['timemodified'] = 'Време измене';
$string['todatabase'] = 'у ову базу података.';
$string['type'] = 'Тип поља';
$string['undefinedprocessactionmethod'] = 'Не постоји метода дефинисана у Data_Preset да користи акцију \"$a\".';
$string['unsupportedexport'] = '($a->fieldtype)се не може извозити';
$string['updatefield'] = 'Ажурирање постојећег поља';
$string['uploadfile'] = 'Постави датотеку';
$string['uploadrecords'] = 'Постављење уноса из датотеке';
$string['url'] = 'URL';
$string['usestandard'] = 'користити постојећи скуп подешавања';
$string['viewfromdate'] = 'Може се прегледати од';
$string['viewtodate'] = 'Може се прегледати до';
$string['wrongdataid'] = 'Погрешна ИД података је обезбеђена';
$string['cannotaccesspresentsother'] = 'Није Вам дозвољен приступ почетним подешавањима других корисника'; // ORPHANED
$string['cannotadd'] = 'Не могу се додати уноси!'; // ORPHANED
$string['cannotdeletepreset'] = 'Грешка у брисању почетних подешавања!'; // ORPHANED
$string['cannotinsertempty'] = 'Није могуће креирати празан запис!'; // ORPHANED
$string['cannotrate'] = 'Оцењивање ставки није допуштено!'; // ORPHANED
$string['cannotunziptopreset'] = 'Не може се распаковати директоријум почетних подешавања'; // ORPHANED
$string['data:exportallentries'] = 'Извети све ставке из базе података'; // ORPHANED
$string['data:exportentry'] = 'Извези ставку из базе података'; // ORPHANED
$string['data:exportownentry'] = 'Извези сопствену ставку из базе података'; // ORPHANED
$string['generateerror'] = 'Нису све датотеке генерисане!'; // ORPHANED
$string['guestrate'] = 'Гостима није допуштено да оцењују уносе'; // ORPHANED
$string['invalidaccess'] = 'Страници није исправно приступљено'; // ORPHANED
$string['invalidfieldid'] = 'ID поља није исправан'; // ORPHANED
$string['invalidfieldtype'] = 'Тип поља није исправан'; // ORPHANED
$string['invalidid'] = 'ID података није исправан'; // ORPHANED
$string['invalidpreset'] = '$a није постојеће подешавање.'; // ORPHANED
$string['invalidratedata'] = 'Неисправни су прослеђени подаци о оцењивању'; // ORPHANED
$string['invalidrecord'] = 'Неисправан запис'; // ORPHANED
$string['missingdata'] = 'id података или објект мора се проследити класи поља'; // ORPHANED
$string['missingfield'] = 'Грешка програмера: Морате одредити поље и/или податке када дефинишете класу поља.'; // ORPHANED
$string['nofieldcontent'] = 'Садржај поља није пронађен'; // ORPHANED
$string['norating'] = 'Ова активност не користи оцењивања'; // ORPHANED
$string['portfolionotfile'] = 'Извези у портфолио а не у датотеку (само за .csv)'; // ORPHANED
$string['updatingerror'] = 'Постојала је грешка при ажурирању базе података.'; // ORPHANED
$string['cannotinsertrate'] = 'Није могуће уметнути ново оцењивање($a[0] = $a[1])'; // ORPHANED
$string['cannotupdaterate'] = 'Није могуће изменити старо оцењивање($a[0] = $a[1])'; // ORPHANED
$string['invaliddata'] = 'Неисправни подаци'; // ORPHANED

?>
