<?PHP // $Id$ 
      // error.php - created with Moodle 1.9.9 (Build: 20100609) (2007101590)


$string['adminprimarynoedit'] = 'Подаци примарног администратора не могу бити мењани од стране других корисника';
$string['cannotassignrole'] = 'Није могуће доделити улогу у курсу';
$string['cannotcreatelangdir'] = 'Није могуће креирање директоријума језика';
$string['cannotcreatetempdir'] = 'Није могуће креирање привременог директоријума.';
$string['cannotcustomizelocallang'] = 'Немате одобрење да мењате изразе из превода. Овим одобрењем управља се поседовањем привилегије \"moodle/site:langeditlocal\". Поставите ову привилегију да би Вам била омогућена измена локалних језичких пакета у случају да желите вршити измене преводâ за Ваш сајт.';
$string['cannotdownloadcomponents'] = 'Није могуће преузети компоненте.';
$string['cannotdownloadlanguageupdatelist'] = 'Није могуће преузети списак ажурираних језика са download.moodle.org';
$string['cannotdownloadzipfile'] = 'Није могуће преузимање архиве.';
$string['cannoteditmasterlang'] = 'Немате одобрење да мењате изразе из главног језичког пакета. Овим одобрењем управља се поседовањем привилегије \"moodle/site:langeditlocal\". Поставите ову привилегију да би Вам била омогућена измена главних језичких пакета у случају да сте Ви надлежни за пакет.';
$string['cannotfindcomponent'] = 'Није могуће пронаћи компоненту.';
$string['cannotinsertrecord'] = 'Није могућ унос ID за нови запис: $a';
$string['cannotsavemd5file'] = 'Није могуће сачувати md5 датотеку.';
$string['cannotsavezipfile'] = 'Није могуће сачувти ZIP архиву.';
$string['cannotunzipfile'] = 'Није могуће распаковати ZIP датотеку.';
$string['cannotupdaterecord'] = 'Није могуће ажурирати запис са ID $a';
$string['cannotviewprofile'] = 'Не можете видети профил овог корисника';
$string['cantunenrollfrommetacourse'] = 'Не можете се исписати са овог мета курса.';
$string['cantunenrollinthisrole'] = 'Не можете се исписати са овог курса док сте у тренутној улози.';
$string['cmunknown'] = 'Није пронађен тај модул курса';
$string['componentisuptodate'] = 'Компонента је доступна у својој најновијој верзији.';
$string['confirmsesskeybad'] = 'Нажалост, али кључ Ваше сесије не може бити потврђен да би се извршила ова акција. Ова сигурносна опција спречава случајно или злонамерно извршавање важних функција у Ваше име. Молимо будите сигурни да стварно желите да извршите ову функцију.';
$string['couldnotassignrole'] = 'Дошло је до озбиљне, али неодређене грешке приликом покушаја доделе Ваше нове улоге';
$string['countriesphpempty'] = 'Грешка: Датотека countries.php у језичком пакету $a је празна или недостаје.';
$string['coursegroupunknown'] = 'Одговарајући курс за групу $a није задат';
$string['csvcolumnduplicates'] = 'Откривене су дупликати колона';
$string['csvemptyfile'] = 'CSV датотека је празна';
$string['csvfewcolumns'] = 'Нема довољно колона, молимо проверите подешавање за знак раздвајања';
$string['csvweirdcolumns'] = 'Неисправан формат CSV датотеке - број колона није свуда исти!';
$string['dbupdatefailed'] = 'Ажурирање базе података није успело';
$string['downloadedfilecheckfailed'] = 'Није успела провера преузете датотеке.';
$string['duplicateusername'] = 'Дуплирано корисничко име - прескаче се запис';
$string['errorcleaningdirectory'] = 'Грешка при чишћењу директоријума \"$a\"';
$string['errorcopyingfiles'] = 'Грешка при копирању датотека';
$string['errorcreatingdirectory'] = 'Грешка при креирању директоријума \"$a\"';
$string['errorcreatingfile'] = 'Грешка при креирању датотеке \"$a\"';
$string['erroronline'] = 'Грешка у линији $a';
$string['errorreadingfile'] = 'Грешка при читању датотеке \"$a\"';
$string['errorsavingrequest'] = 'Када сте покушали да сачувате свој захтев појавила се грешка';
$string['errorunzippingfiles'] = 'Грешка при распакивању датотека';
$string['fieldrequired'] = '\"$a\" је обавезно поље';
$string['filenotfound'] = 'Нажалост тражени документ није било могуће пронаћи';
$string['forumblockingtoomanyposts'] = 'Прекорачили сте ограничење за број порука на овом форуму.';
$string['groupalready'] = 'Корисник већ припада групи $a';
$string['groupexistforcourse'] = 'Група \"$a\" већ постоји у овом курсу';
$string['groupnotaddederror'] = 'Група \"$a\" није додата';
$string['groupunknown'] = 'Група $a не припада датом курсу';
$string['groupusernotmember'] = 'Корисник није члан ове групе';
$string['guestnoeditprofile'] = 'Гост не може да уређује свој профил';
$string['guestnoeditprofileother'] = 'Не може се уређивати профил госта';
$string['guestsarenotallowed'] = 'Кориснику са налогом госта није дозвољено да уради';
$string['invalidadminsettingname'] = 'Неисправно админ подешавање ($a)';
$string['invalidcontext'] = 'Неисправан контекст';
$string['invalidcourse'] = 'Неисправан курс';
$string['invalidcourseid'] = 'Покушавате да користите неисправан ID курса ($a)';
$string['invalidcoursemodule'] = 'Неисправан ID модула курса';
$string['invalidfieldname'] = '\"$a\" није исправно име поља';
$string['invalidfiletype'] = '\"$a\" није исправан тип датотеке';
$string['invalidipformat'] = 'Неисправан формат IP адресе';
$string['invalidmd5'] = 'Неисправна md5 датотека';
$string['invalidrequest'] = 'Неисправан захтев';
$string['invalidrole'] = 'Неисправна улога';
$string['invalidsesskey'] = 'Нетачан код сесије је прослеђен, форма није прихваћена!';
$string['invalidurl'] = 'Неисправан url';
$string['invalidxmlfile'] = '\"$a\" није исправна XML датотека';
$string['iplookupfailed'] = 'Није могуће пронаћи географске податке о овој IP адреси $a.';
$string['iplookupprivate'] = 'Није могуће приказати претрагу приватне IP адресе';
$string['listcantmovedown'] = 'Пребацивање ставке на доле није успело, ово је последња ставка у низу.';
$string['listcantmoveleft'] = 'Пребацивање ставке улево није успело,нема ниједне надређене ставке.';
$string['listcantmoveright'] = 'Пребацивање ставке удесно није успело, нема низа чији би она била члан. Пребаци га у други низ и тада га можеш померити удесно.';
$string['listcantmoveup'] = 'Пребацивање ставке навише није успело, јер је то прва ставка у низу.';
$string['listnochildren'] = 'Нема потомака ставке';
$string['listnoitem'] = 'Ставка није пронађена';
$string['listnopeers'] = 'Низ ставки није пронађен';
$string['listupdatefail'] = 'ДБ операција није успела док је уређивана хијерархија листе.';
$string['loginasnoenrol'] = 'Не можеш се учлањивати и одјавњивати када си у курсу у сесији \"Пријављен као\".';
$string['loginasonecourse'] = 'Не можеш приступити овом курсу <br /> Мораш прекинути сесију \"Пријављени сте као\" пре уласка у било који курс';
$string['missingfield'] = 'Недостаје поље \"$a\"';
$string['missingrequiredfield'] = 'Недостаје неко обавезно поље';
$string['modulemissingcode'] = 'Модулу $a недостаје код потребан за извођење ове функције';
$string['modulerequirementsnotmet'] = 'Модул \"$a->modulename\" ($a->moduleversion) није могао бити инсталиран. Наведени модул захтева новију верзију система Moodle (Ви тренутно имате $a->currentmoodle, а потребна Вам је верзија $a->requiremoodle).';
$string['mustbeteacher'] = 'Морате бити предавач да бисте видели ову страницу';
$string['nocategorydelete'] = 'Категорија \'$a\' се не може обрисати!';
$string['nocontext'] = 'Жао нам је, али тај курс није валидан контекст';
$string['noinstances'] = 'Нема инстанци $a у овом курсу!';
$string['nologinas'] = 'Није ти дозвољено да се пријавиш као тај корисник';
$string['nonmeaningfulcontent'] = 'Бесмислен садржај';
$string['noparticipatorycms'] = 'Нажалост немате учествујућих модула курса о којима би се могао поднети извештај.';
$string['nopermissions'] = 'Жао нам је, али тренутно немате дозволу да то радите ($a)';
$string['nostatstodisplay'] = 'Извините, нема расположивих података за приказ';
$string['notavailable'] = 'Тренутно није на располагању.';
$string['onlyadmins'] = 'Само администратори могу то да раде.';
$string['onlyeditingteachers'] = 'Само предавачи могу то да раде.';
$string['onlyeditown'] = 'Можете мењати само личне податке';
$string['pagenotexist'] = 'Дошло је до неуобичајене грешке (покушано је достизање краја странице која уопште не постоји).';
$string['pleasereport'] = 'Ако имате времена, молимо објасните нам шта сте покушавали да учините када је дошло до грешке:';
$string['pluginrequirementsnotmet'] = 'Додатак \"$a->pluginname\" ($a->pluginversion) није могао бити инсталиран. Он захтева новију верзију Moodle система (Ви тренутно користите $a->currentmoodle, а потребна Вам је верзија $a->requiremoodle).';
$string['processingstops'] = 'Процесирање се овде зауставља. Преостали записи биће игнорисани.';
$string['remotedownloaderror'] = 'Преузимање компоненте на Ваш сервер није успело. Проверите подешавања прокси серевера. PHP cURL екстензија се препоручује.<br /><br />Морате да преузмете <a href=\"$a->url\">$a->url</a> датотеку ручно, копирате је у директоријум \"$a->dest\" на свом сереверу тамо је распакујете.';
$string['remotedownloadnotallowed'] = 'Није дозвољено преузимање компоненти на Ваш сервер (опција allow_url_fopen је онемогућена).<br /><br />Морате ручно преузети датотеку <a href=\"$a->url\">$a->url</a>, копирати је у \"$a->dest\" на свом серверу и тамо је распаковати.';
$string['restorechecksumfailed'] = 'Дошло је до неког проблема са информацијом за обнављање, сачуваном у Вашој сесији. Молимо проверите Ваша подешавања граница величина PHP меморије/DB пакета. Обнављање је прекинуто.';
$string['restricteduser'] = 'Жао нам је, али ваш текући налог \"$a\" је ограничен и не можете урадити ову акцију.';
$string['scheduledbackupsdisabled'] = 'Планиране сигурносне копије су онемогућене од стране администратора';
$string['sendmessage'] = 'Слање поруке';
$string['sessionerroruser'] = 'Ваша сесија је истекла. Молимо, пријавите се на систем поново.';
$string['sessionerroruser2'] = 'Дошло је до грешке која утиче на Вашу текућу сесију. Молимо приступите систему поново или поново покрените свој web читач.';
$string['sessionipnomatch'] = 'Нажалост, али изгледа да се Ваш IP број променио од када сте се пријавили на систем. Ова сигурносна опција спречава кракере да украду Ваш индентитет док сте пријављени на овај сајт. Нормални корисници не би требало да виде ову поруку - молимо Вас да тражите помоћ од администратора сајта.';
$string['socksnotsupported'] = 'SOCKS5 прокси није подржан у PHP4';
$string['statscatchupmode'] = 'Статистика је тренутно у моду за сустизање обраде падатака. До сада је процесирано $a->daysdone дан(a), а још $a->dayspending дана чека на обраду. Вратите се нешто касније!';
$string['tagnotfound'] = 'Наведена ознака (таг) није пронађена у бази података';
$string['unicodeupgradeerror'] = 'Жао нам је, али Ваша база података није у Unicode формату, а ова везија Moodleа не може да је пребаци у Unicode базу података. Молимо прво урадите надоградњу система до Moodle 1.7.x верзије и урадите Unicode миграцију са администраторске странице. Након што то урадите моћи ћете да пређете на Moodle $a';
$string['unknowncourse'] = 'Не постоји курс под називом \"$a\"';
$string['unknowncourseidnumber'] = 'Непознати курс ИД \"$a\"';
$string['unknowncourserequest'] = 'Нпознат захтев за курс';
$string['unknowngroup'] = 'Непозната група \"$a\"';
$string['unknownrole'] = 'Непозната улога \"$a\"';
$string['unknownuseraction'] = 'Жао нам је, али систем није разумео ову акцију корисника.';
$string['userautherror'] = 'Непознат додатак за проверу идентитета';
$string['userauthunsupported'] = 'Додатак за проверу идентитета није могуће овде применити';
$string['useremailduplicate'] = 'Поновљена адреса';
$string['usernotaddedadmin'] = 'Не могу се обрисати администраторски налози.';
$string['usernotaddederror'] = 'Корисник \"$a\" није додат - непозната грешка';
$string['usernotaddedregistered'] = 'Корисник \"$a\" није додат - већ је регистрован';
$string['usernotavailable'] = 'Детаљне информације о овом кориснику Вам нису доступне.';
$string['usernotdeletederror'] = 'Корисник није избрисан - непозната грешка';
$string['usernotdeletedmissing'] = 'Корисник није избрисан - корисничко име није пронађено';
$string['usernotdeletedoff'] = 'Корисник није обрисан - брисање није дозвољено.';
$string['usernotrenamedadmin'] = 'Не могу се преименовати администраторски налози.';
$string['usernotrenamedexists'] = 'Корисник није преименован -- ново корисничко име је већ заузето.';
$string['usernotrenamedmissing'] = 'Корисник није преименован -- није пронађено старо корисничко име.';
$string['usernotrenamedoff'] = 'Корисник није преименован - преименовање није дозвољено.';
$string['usernotupdatedadmin'] = 'Не могу се изменити администраторски налози.';
$string['usernotupdatederror'] = 'Корисник није ажуриран - непозната грешка';
$string['usernotupdatednotexists'] = 'Нису измењени подаци о кориснику - не постоје подаци.';
$string['wrongdestpath'] = 'Погрешна одредишна путања.';
$string['wrongsourcebase'] = 'Погрешан изворни URL базе.';
$string['wrongzipfilename'] = 'Погрешан назив архиве.';
$string['youcannotdeletecategory'] = 'Не можете да обришете категорију \'$a\' зато што не можете да обришете садржаје или да их преместите негде друго.';
$string['TODO'] = 'TODO'; // ORPHANED
$string['authnotexisting'] = 'Додатак ѕа проверу идентитета не постоји'; // ORPHANED
$string['backuptablefail'] = 'Табеле резервнре копије нису могле бити успешно подешене!'; // ORPHANED
$string['blockcannotconfig'] = 'Овај блок не подржаба глобалну конфигурацију'; // ORPHANED
$string['blockcannotinistantiate'] = 'Пробелем прилико креирања инстанце објекта блока'; // ORPHANED
$string['blockcannotread'] = 'Није било могуће прочитати податке за blockid= $a'; // ORPHANED
$string['blockdoesnotexist'] = 'Овај блок не постоји'; // ORPHANED
$string['blockdoesnotexistonpage'] = 'Овај блок (id=$a->instanceid) не постоји ма овој страници ($a->url).'; // ORPHANED
$string['blocknameconflict'] = 'Конфликт у називу: блок $a->name има исти наслов као и постојећи блок: $a->conflict!'; // ORPHANED
$string['cannotaddcoursemodule'] = 'Није билоо могуће додати нови модул'; // ORPHANED
$string['cannotaddcoursemoduletosection'] = 'Није било могуће додати нови модул у ову секцију'; // ORPHANED
$string['cannotaddmembergroupiddoesntexist'] = 'Није могуће додати члана групе: ид групе не постоји'; // ORPHANED
$string['cannotaddmodule'] = '$a модул није могао бити додат листи модула!'; // ORPHANED
$string['cannotaddnewmodule'] = 'Није било могуће додати нови модул $a'; // ORPHANED
$string['cannotaddrss'] = 'Немате дозволу да додајете РСС изворе вести'; // ORPHANED
$string['cannotassignanthing'] = 'Није могуће доделити moodle/site:doanything'; // ORPHANED
$string['cannotassignrolehere'] = 'Није Вам дозвољено да додељујете ову улогу (id = $a->roleid) у овом контексту ($a->context)'; // ORPHANED
$string['cannotcallscript'] = 'Не можете да позовете овај скрипт на тај начин'; // ORPHANED
$string['cannotcallusgetselecteduser'] = 'Не можете да позовете user_selector::get_selected_user уколико је опција multiselect укључена'; // ORPHANED
$string['cannotcreatebackupdir'] = 'Није било могуће креирати директоријум за резервну копију података. Администратор сајта мора да реши тај проблем'; // ORPHANED
$string['cannotcreatecategory'] = 'Категорија није убачена'; // ORPHANED
$string['cannotcreategroup'] = 'Грешка приликом креирања групе'; // ORPHANED
$string['cannotcreatelangbase'] = 'Грешка: Није било могуће креирати основни директоријум језика'; // ORPHANED
$string['cannotcreateorfindstructs'] = 'Грешка у проналажењу или креирању стурктуре секција за овај курс'; // ORPHANED
$string['cannotcreatepopupwin'] = 'Недефинисани елемент - није могуће креирати искачући прозор'; // ORPHANED
$string['cannotcreatesitedir'] = 'Није могуће креирати директоријум сајта. Администратор сајта мора да реши тај проблем'; // ORPHANED
$string['cannotcreateuploaddir'] = 'Није могуће креирати директоријум за постављање датотека. Администратор сајта мора да реши тај проблем'; // ORPHANED
$string['cannotcustomisefiltersblockuser'] = 'Не можете да прилагодите подешавања у контексту корисника односно у контексту блока'; // ORPHANED
$string['cannotdeletebackupids'] = 'Није било могуће обрисати ид ознаке претходних резервних копија'; // ORPHANED
$string['cannotdeletecategorycourse'] = 'Није успело брисање курса \'$a\''; // ORPHANED
$string['cannotdeletecategoryquestions'] = 'Није било могуће обрисати питања из категорије  \'$a\''; // ORPHANED
$string['cannotdeletecourse'] = 'Немате дозволу да обришете овај курс'; // ORPHANED
$string['cannotdeletedir'] = 'Није могуће обрисати ($a)'; // ORPHANED
$string['cannotdeletelangcache'] = 'Језички кеш не може бити обрисан. Молимо, решите проблем овлашћења у dataroot/cache/languages!'; // ORPHANED
$string['cannotdeleterole'] = 'Не  може бити обрисано због $a'; // ORPHANED
$string['cannotdeleterolewithid'] = 'Није могуће обрисати улогу са ИД $a'; // ORPHANED
$string['cannotdeletethisrole'] = 'Не можете да обришете ову улогу зато што је користи систем или је то последња улога са администраторским нивоом приступа.'; // ORPHANED
$string['cannoteditcomment'] = 'Овај коментар није Ваш да би могли да га уређујете!'; // ORPHANED
$string['cannoteditcommentexpired'] = 'Не можете ово да уређујете. Време је истекло!'; // ORPHANED
$string['cannoteditpostorblog'] = 'Не можете да постујете или уређујете блог'; // ORPHANED
$string['cannoteditsiteform'] = 'Не можете уредити курс сајта користећи овај образац'; // ORPHANED
$string['cannotedityourprofile'] = 'Опростите, али не можете да уређујете свој профил'; // ORPHANED
$string['cannotfindcontext'] = 'Није могуће пронаћи контекст.'; // ORPHANED
$string['cannotfinddocs'] = 'Није могуће пронаћи датотеке документације за \"$a\" језик'; // ORPHANED
$string['cannotfindgradeitem'] = 'Није могуће наћи grade_item'; // ORPHANED
$string['cannotfindgroup'] = 'Није могуће наћи групу'; // ORPHANED
$string['cannotfindhelp'] = 'Није могуће пронаћи датотеке помоћи за \"$a\" језик.'; // ORPHANED
$string['cannotfindinfo'] = 'Није могуће наћи информације за: \"$a\"'; // ORPHANED
$string['cannotfindlang'] = 'Није могуће пронаћи \"$a\" језички пакет!'; // ORPHANED
$string['cannotfindsite'] = 'Није могуће наћи курс на нивоу сајта'; // ORPHANED
$string['cannotfindteacher'] = 'Није могуће пронаћи предавача'; // ORPHANED
$string['cannotfinduser'] = 'Није могуће пронаћи корисника по имену \"$a\"'; // ORPHANED
$string['cannotgetcats'] = 'Није могуће добити запис категорије'; // ORPHANED
$string['cannotgetdata'] = 'Није могуће добити податак'; // ORPHANED
$string['cannotgradeuser'] = 'Није могуће оценити овог корисника'; // ORPHANED
$string['cannotimport'] = 'Грешка приликом увоза'; // ORPHANED
$string['cannotimportformat'] = 'Опростите, али увоз овог формата још увек није имплементиран'; // ORPHANED
$string['cannotimportgrade'] = 'Грешка у увозу оцена'; // ORPHANED
$string['cannotinsertgrade'] = 'Није могуће убацити ставку оцене без ид ознаке курса!'; // ORPHANED
$string['cannotinsertrate'] = 'Није било могуће убацити ново оцењивање ($a->id = $a->rating)'; // ORPHANED
$string['cannotmailconfirm'] = 'Грешка у слању е-поруке са потврдом о промени лозинке'; // ORPHANED
$string['cannotmetacourse'] = 'Није могуће додати изабрани курс овом мета курсу!'; // ORPHANED
$string['cannotmoverolewithid'] = 'Није могуће преместити улогу са ID $a'; // ORPHANED
$string['cannotnetgeo'] = 'Није могуће успоставити везу са NetGeo сервером на http://netgeo.caida.org. Молимо проверите подешавања Вашег прокси сервера или још боље инсталирајте датотеку за MaxMind GeoLite City'; // ORPHANED
$string['cannotopencsv'] = 'Није могуће отвориту CSV датотеку'; // ORPHANED
$string['cannotopenfile'] = 'Није могуће отворити датотеку ($a)'; // ORPHANED
$string['cannotopenforwrit'] = 'Није могуће отворити за упсисивање: $a'; // ORPHANED
$string['cannotopentemplate'] = 'Није могуће отворити датотеку шаблона ($a)'; // ORPHANED
$string['cannotopenzip'] = 'Није могуће отворити zip архиву. Вероватно је у питању грешка са zip екстензијом на 64-битном оперативном систему.'; // ORPHANED
$string['cannotoverridebaserole'] = 'Није могуће мењати основне могућности улоге'; // ORPHANED
$string['cannotoverriderolehere'] = 'Није Вам дозвљено да мењате ову улогу (id = $a->roleid) у овом контексту ($a->context)'; // ORPHANED
$string['cannotreadfile'] = 'Није могуће прочитати датотеку ($a)'; // ORPHANED
$string['cannotreadtmpfile'] = 'Грешка у читању привремене датотеке'; // ORPHANED
$string['cannotreaduploadfile'] = 'Није било могуће прочитати постављену датотеку'; // ORPHANED
$string['cannotremovefrommeta'] = 'Ннје било могуће уклонити изабрани курс из овог метакурса!'; // ORPHANED
$string['cannotresetguestpwd'] = 'Не можете те да ресетујете лозинку госта'; // ORPHANED
$string['cannotresetthisrole'] = 'Није могуће ресетовати ову улогу'; // ORPHANED
$string['cannotrestore'] = 'Појавила се грешка те пороцес рестаурације не може бити завршен!'; // ORPHANED
$string['cannotrestoreadminorcreator'] = 'Морате да буде креатор курса или администратор како би рестаурацију резервне копије у нови курс'; // ORPHANED
$string['cannotrestoreadminoredit'] = 'Морате да буде предавач или администратор како би рестаурацију резервне копије у изабрани курс'; // ORPHANED
$string['cannotsaveblock'] = 'Грешка приликом покушаја да се сачува конфогурација блокова'; // ORPHANED
$string['cannotsavecomment'] = 'Није могуће сачувати коментар'; // ORPHANED
$string['cannotsavedata'] = 'Није могуће сачувати податке'; // ORPHANED
$string['cannotsavefile'] = 'Није могуће сачувати датотеку \"$a\"!'; // ORPHANED
$string['cannotsetpassword'] = 'Није могуће подесити корисничку лозинку!'; // ORPHANED
$string['cannotsettheme'] = 'Није могуће подесити шемзу изгледа'; // ORPHANED
$string['cannotsetupblock'] = 'НИЈЕ било могуће успешно подесити табеле блокова !'; // ORPHANED
$string['cannotsetupcapformod'] = 'Није било могуће подесити могућности за  $a'; // ORPHANED
$string['cannotsetupcapforplugin'] = 'Није било могуће подесити могућности за  $a'; // ORPHANED
$string['cannotshowhidecoursesincategory'] = 'Није могуће приказати/сакрити курсеве у категорији $a'; // ORPHANED
$string['cannotupdatemod'] = 'Није било могуће ажурирати $a'; // ORPHANED
$string['cannotupdatepasswordonextauth'] = 'Ажурирање лозинке на екстерном систему за проверу идентитета: $a није успело. За више детања погледајте записе на серверу.'; // ORPHANED
$string['cannotupdateprofile'] = 'Грешка приликом ажурирања корисничког записа'; // ORPHANED
$string['cannotupdaterss'] = 'Није могуће ажурирати RSS извор вести'; // ORPHANED
$string['cannotupdateusermsgpref'] = 'Није могуће ажурирање корисникових пoдешавања приватних порука'; // ORPHANED
$string['cannotupdateuseronexauth'] = 'Ажурирање корисничких података на екстерном систему за проверу идентитета: $a није успело. За више детања погледајте записе на серверу.'; // ORPHANED
$string['cannotuploadfile'] = 'Грешка у процесисирању постављања датотеке'; // ORPHANED
$string['cannotuseadmin'] = 'Морате да будете администратор да бисте користили ову страницу'; // ORPHANED
$string['cannotuseadminadminorteacher'] = 'Морате да будете предавач или администратор да бисте користили ову страницу'; // ORPHANED
$string['cannotusepage'] = 'Само предавачи и админстратори могу да користе ову страницу'; // ORPHANED
$string['cannotusepage2'] = 'Опростите, не может да користите ову страницу'; // ORPHANED
$string['cannotwritefile'] = 'Није могуће уписивање у ову датотеку ($a)'; // ORPHANED
$string['commentmisconf'] = 'ИД коментара је погрешно конфигурисан'; // ORPHANED
$string['couldnotupdatenoexistinguser'] = 'Није могуће ажурирати корисника - корисник не постоји'; // ORPHANED
$string['coursedoesntexistcannotcreategroup'] = 'Није могуће креирати групу: курс не постоји'; // ORPHANED
$string['courseidnotfound'] = 'Id курса не постоји'; // ORPHANED
$string['coursemisconf'] = 'Курс је погрешно конфигурисан'; // ORPHANED
$string['courserequestdisabled'] = 'Опростите, али администатор је онемогућио тражени курс'; // ORPHANED
$string['csvinvalidcols'] = '<b>Неисправна CSV датотека:</b> Прва линија мора да садржи \"Header Fields\" а датотеека мора да буде типа <br />\"Expanded Fields/Comma Separated\"<br />или<br /> \"Expanded Fields with CAVV Result Code/Comma Separated\"'; // ORPHANED
$string['csvinvalidcolsnum'] = 'Неисправна CSV датотека - свака линија мора да има 49 или 70 поља'; // ORPHANED
$string['csvloaderror'] = 'Појавила се грешка у току учитавања CSV датотеке!'; // ORPHANED
$string['dbconnectionfailed'] = '<p>Грешка: Конекција са базом података није успела</p>
<p>Могуће је да је база података преоптерећена или на други начин не функионише правилно.</p>
<p>Администратор сајта би, такође, требало да провери да ли су у config.php датотеци сви детаљи везани за базу података исправно наведени</p>$a'; // ORPHANED
$string['dbdriverproblem'] = '<p>Грешка: уочен је проблем са драјвером базе података</p>
<p>Администратор сајта би требало да провери конфигурацију сервера</p><p>$a</p>'; // ORPHANED
$string['dbsessionbroken'] = 'Уочен је озбиљан проблем са сесијом базе података.<br /><br />Молимо, обавестите администратора сервера.'; // ORPHANED
$string['dbsessionhandlerproblem'] = 'Подешавање сессије базе података није успелео.<br /><br />Молимо, обавестите администратора сервера.'; // ORPHANED
$string['dbsessionmysqlpacketsize'] = '<br /><br />Молимо, обавестите администратора. Овај проблем је највероватније'; // ORPHANED
$string['ddlfieldalreadyexists'] = 'Поље \"$a\" не постоји'; // ORPHANED
$string['ddlfieldnotexist'] = 'Поље \"$a->fieldname\" не постоји у табели \"$a->tablename\"'; // ORPHANED
$string['ddltablealreadyexists'] = 'Табела \"$a\" већ постоји'; // ORPHANED
$string['ddltablenotexist'] = 'Табела \"$a\" не постоји'; // ORPHANED
$string['ddlunknownerror'] = 'Непозната DDL грешка'; // ORPHANED
$string['ddlxmlfileerror'] = 'Пронађена је грешка у датотеци XML базе података'; // ORPHANED
$string['destinationcmnotexit'] = 'Одредишни курс не постоји'; // ORPHANED
$string['detectedbrokenplugin'] = 'Додатак \"$a\" је оштећен. Опростите али није могуће наставити.'; // ORPHANED
$string['dmlreadexception'] = 'Грешка приликом читања из базе података'; // ORPHANED
$string['dmlwriteexception'] = 'Грешка приликом уписвања у базу подтака'; // ORPHANED
$string['duplicaterolename'] = 'Већ постоји улога са овим именом!'; // ORPHANED
$string['duplicateroleshortname'] = 'Већ постоји улога са овим кратким именом!'; // ORPHANED
$string['emailfail'] = 'Слање е-поште није успело'; // ORPHANED
$string['error'] = 'Појавила се грешка'; // ORPHANED
$string['errorcreatingrole'] = 'Грешка у креирању улоге'; // ORPHANED
$string['errorsettinguserpref'] = 'Грешка у подешавању корисникових преференци'; // ORPHANED
$string['expiredkey'] = 'Кључ је истекао'; // ORPHANED
$string['failtoloadblocks'] = 'Један или више блокова је регистровано у баззи података, али нису успели да се учитају!'; // ORPHANED
$string['filenotreadable'] = 'Датотека није читљива'; // ORPHANED
$string['filterdoesnothavelocalconfig'] = 'Филтер $a не допушта локалну конфигурацију.'; // ORPHANED
$string['filternotactive'] = 'Филтер $a тренутно није активан'; // ORPHANED
$string['filternotinstalled'] = 'Филтер $a тренутно није инсталиран'; // ORPHANED
$string['generalexceptionmessage'] = 'Изузетак - $a'; // ORPHANED
$string['gradepubdisable'] = 'Објављивање оцена је онемогућено'; // ORPHANED
$string['groupiddoesntexistcannotdelete'] = 'Није могуће обрисати групу: ид групе не постоји'; // ORPHANED
$string['guestnocomment'] = 'Гостима није дозвољено да постују коментаре'; // ORPHANED
$string['guestnorate'] = 'Гостима није дозвољено да оцењују појмове'; // ORPHANED
$string['hackdetected'] = 'Откривен је хакерски напад!'; // ORPHANED
$string['headersent'] = 'Заглавља су већ послата'; // ORPHANED
$string['idnumbertaken'] = 'ИД број се већ користи за други курс'; // ORPHANED
$string['importformatnotimplement'] = 'Опростите, али увоз овог формата још није имплементиран!'; // ORPHANED
$string['incorrectext'] = 'Датотека има неисправну екстензију'; // ORPHANED
$string['invalidaccess'] = 'Неисправан приступ овој страници'; // ORPHANED
$string['invalidaccessparameter'] = 'Неисправан параметер приступа'; // ORPHANED
$string['invalidaction'] = 'Неисправан параметер акције'; // ORPHANED
$string['invalidactivityid'] = 'Неисправан ИД Активности'; // ORPHANED
$string['invalidargorconf'] = 'Нису прослеђен исправни аргументи или погрешна конфигурација сервера'; // ORPHANED
$string['invalidarguments'] = 'Нису прослеђен исправни аргументи'; // ORPHANED
$string['invalidblockinstance'] = 'Неисправна инстанца блока ѕа $a'; // ORPHANED
$string['invalidcategory'] = 'Погрешна категорија'; // ORPHANED
$string['invalidcategoryid'] = 'Погрешан ид категоеије!'; // ORPHANED
$string['invalidcomment'] = 'Коментар је неисправан'; // ORPHANED
$string['invalidconfirmdata'] = 'Неисправни подаци за потврду'; // ORPHANED
$string['invalidcourselevel'] = 'Погрешан ниво контекста'; // ORPHANED
$string['invalidcoursenameshort'] = 'Неисправно кратко назив курса'; // ORPHANED
$string['invaliddata'] = 'Прослеђени подаци су неисправни'; // ORPHANED
$string['invalidelementid'] = 'Погрешан ид елемента'; // ORPHANED
$string['invalidenrol'] = 'Покушан је недозвољен упис на курс'; // ORPHANED
$string['invalidentry'] = 'Ово није исправан унос'; // ORPHANED
$string['invalidevent'] = 'Неисправан догађај'; // ORPHANED
$string['invalidformatpara'] = 'Погрешан формат за параметар избора'; // ORPHANED
$string['invalidfunction'] = 'Неисправна функција'; // ORPHANED
$string['invalidgradeitmeid'] = 'Неисправан ид ставке оцене'; // ORPHANED
$string['invalidgroupid'] = 'Наведен је неисправан ид групе'; // ORPHANED
$string['invaliditemid'] = 'Неисправан ид ставке'; // ORPHANED
$string['invalidkey'] = 'Неисправан кључ'; // ORPHANED
$string['invalidlegacy'] = 'Неисправна дефиниција наслеђене улоге за тип: $a'; // ORPHANED
$string['invalidmode'] = 'Неисправан мод ($a)'; // ORPHANED
$string['invalidmodule'] = 'Неисправан модул'; // ORPHANED
$string['invalidmoduleid'] = 'Неисправан модул ИД: $a'; // ORPHANED
$string['invalidmodulename'] = 'Неисправан назив модула: $a'; // ORPHANED
$string['invalidnum'] = 'Неисправна нумеричка вредност'; // ORPHANED
$string['invalidoutcome'] = 'Неисправан ид исхода'; // ORPHANED
$string['invalidpagesize'] = 'Неисправна величина странице'; // ORPHANED
$string['invalidpaymentmethod'] = 'Неисправан мачин плаћања $a'; // ORPHANED
$string['invalidqueryparam'] = 'ГРЕШКА: Погрешан број параметара упита. Очекивано $a->expected, а добијено $a->actual.'; // ORPHANED
$string['invalidrecord'] = 'Није могуће наћи запис податка у табели базе $a.'; // ORPHANED
$string['invalidrecordunknown'] = 'Није могуће наћи запис податка у бази'; // ORPHANED
$string['invalidroleid'] = 'Неисправан ИД улоге'; // ORPHANED
$string['invalidsection'] = 'Запис модула курса садржи неисправну секцију'; // ORPHANED
$string['invalidshortname'] = 'То је неисправно кратко име курса'; // ORPHANED
$string['invalidstatedetected'] = 'Нешто је кренуло наопако: $a. Нормално, ово не би требало да се догађа.'; // ORPHANED
$string['invaliduser'] = 'Неисправан корисник'; // ORPHANED
$string['invaliduserid'] = 'Неисправан ид корисника'; // ORPHANED
$string['logfilenotavailable'] = 'Записи нису доступни'; // ORPHANED
$string['messagingdisable'] = 'Слање порука на овом сајту није омогућено'; // ORPHANED
$string['mimetexisnotexist'] = 'Ваш систем није конфигурсан да би мофао да покрене mimeTeX. Морате да преузмете одговарајућу извршну датотеку за Вашу PHP_OS платформу са <a href=\"http://moodle.org/download/mimetex/\">http://moodle.org/download/mimetex/</a>, или да прибавите C изворни код са <a href=\"http://www.forkosh.com/mimetex.zip\"> http://www.forkosh.com/mimetex.zip</a>,  да га компајлирате и поставите извршму датотеку у Ваш moodle/filter/tex/ директоријум'; // ORPHANED
$string['missingkeyinsql'] = 'Грешка: недостаје параметар \"$a\" у упиту'; // ORPHANED
$string['missingparam'] = 'Недостаје неопходни параметар ($a)'; // ORPHANED
$string['missingparameter'] = 'Недостаје параметар'; // ORPHANED
$string['missinguseranditemid'] = 'Недостаје userid и itemid'; // ORPHANED
$string['missingvarname'] = 'Недостаје име неопходне варијабле'; // ORPHANED
$string['mixedtypesqlparam'] = 'ГРЕШКА: Измешани типови sql параметара упита!!!'; // ORPHANED
$string['mnetdisable'] = 'MNET је искључен'; // ORPHANED
$string['mnetlocal'] = 'Удаљени MNET корисник не може да се пријави локално'; // ORPHANED
$string['moduledisable'] = 'Овај модул ($a) је онемогућен за овај конкретан курс'; // ORPHANED
$string['moduledoesnotexist'] = 'Овај модул не постоји'; // ORPHANED
$string['moduleinstancedoesnotexist'] = 'Инстанца овог модула не постоји'; // ORPHANED
$string['multiplerecordsfound'] = 'Пронађени су вишеструки записи, а очекиван је само један запис.'; // ORPHANED
$string['mustbeloggedin'] = 'Морате бити пријављени на систем како бисте ово урадили'; // ORPHANED
$string['needcopy'] = 'Прво морате нешто да копирате!'; // ORPHANED
$string['needcoursecategroyid'] = 'Било ид курса или категорије мора бити наведен'; // ORPHANED
$string['needphpext'] = 'Потреби је да додате $a подршку за Вашу PHP инсталацију'; // ORPHANED
$string['noadmins'] = 'Нема администратора!'; // ORPHANED
$string['noblocks'] = 'Ниједан блок није пронађен!'; // ORPHANED
$string['nodata'] = 'Нема података'; // ORPHANED
$string['noexistingcategory'] = 'Нема категорије'; // ORPHANED
$string['nofile'] = 'Датотека није наведена'; // ORPHANED
$string['nofiltersenabled'] = 'Ниједан филтер није омогућен'; // ORPHANED
$string['nofolder'] = 'Тражени директоријум не постоји'; // ORPHANED
$string['noguest'] = 'Овде нема гостију!'; // ORPHANED
$string['noparticipants'] = 'Није пронађен ни један учесник на овом курсу'; // ORPHANED
$string['nopermissiontocomment'] = 'Не можете да додате коментар у овај речник!'; // ORPHANED
$string['nopermissiontodelentry'] = 'Не можете да бришете уносе других корисника!'; // ORPHANED
$string['nopermissiontoeditcomment'] = 'Не можете да уређујете коментаре других корисника!'; // ORPHANED
$string['nopermissiontohide'] = 'Немате овлашћења за сакривање!'; // ORPHANED
$string['nopermissiontoimportact'] = 'Немате неопходна овлашћења да бисте увезли активности у овај курс'; // ORPHANED
$string['nopermissiontolock'] = 'Немате овлашћења за закључавање!'; // ORPHANED
$string['nopermissiontomanagegroup'] = 'Немате неопходна овлашћења да бисте управљали групама'; // ORPHANED
$string['nopermissiontomkdir'] = 'Није могуће креирати фолдер. Администратор сајта треба да реши проблем'; // ORPHANED
$string['nopermissiontorate'] = 'Оцењивање ставки није дозвољено'; // ORPHANED
$string['nopermissiontoshow'] = 'Немате овлашћења да видите ово!'; // ORPHANED
$string['nopermissiontounlock'] = 'Немате овлашћења за откључавање!'; // ORPHANED
$string['nopermissiontoviewletergrade'] = 'Недостаје овлашћење да би се виделе словне оцене'; // ORPHANED
$string['nopermissiontoviewpage'] = 'Није Вам дозвољено да гледате ову страницу'; // ORPHANED
$string['nositeid'] = 'Не постоји ИД сајта'; // ORPHANED
$string['notallowedtoupdateprefremotely'] = 'Немате дозволу да ажурирате преференце овог корисника удаљено'; // ORPHANED
$string['notlocalisederrormessage'] = '$a'; // ORPHANED
$string['notmemberofgroup'] = 'Нисте члан ове групе'; // ORPHANED
$string['notownerofkey'] = 'Нисте власник овг кључа'; // ORPHANED
$string['nousers'] = 'Не постоји такав корисник'; // ORPHANED
$string['prefixcannotbeempty'] = '<p>Грешка: префикс табела базе података не може бити празан ($a)</p>
<p>Администратор сајта мора да реши овај проблем.</p>'; // ORPHANED
$string['prefixtoolong'] = '<p>Грешка: префикс табеле базе података је предуг ($a->dbfamily)</p>
<p>Администратор сајта мора да реши овај пробле. Максимална дужина префикса табела у $a->dbfamily је $a->maxlength карактера.</p>'; // ORPHANED
$string['reportnotavailable'] = 'Ова врста извештај је једино доступна за сајт.'; // ORPHANED
$string['reverseproxyabused'] = 'Опростите, укључен је реверзни прокси па серверу не може директно да се приступи. <br />Контактирајте сервер администратора.'; // ORPHANED
$string['rpcerror'] = 'RPC enrol/mnet/available_courses: ($a)'; // ORPHANED
$string['secretalreadyused'] = 'Линк за потврду промене лозинке је већ искоришћен. Лозинка није промењена'; // ORPHANED
$string['sectionnotexist'] = 'Ова секција не постоји'; // ORPHANED
$string['sessioncookiesdisable'] = 'Неправилна употреба require_key_login() - колачићи сесије морају бити онемогућени!'; // ORPHANED
$string['sessionipnomatch2'] = 'Опростите, али изгледа да се, од тренутка када сте се први пут пријавили на систем, променила Ваша IP адреса. Ово безбедосно својство спречава злонамерне од крађе Вашег идентитета док сте пријављени на овом сајту. Ову грешку можете видети уколико користите бежични приступ Интернету. Молимо Вас да контактирате администратора ѕа помоћ.<br /><br />Уколико желите да наставите молимо вас притисните на тастатури F5 да бисте освежили ову страницу.'; // ORPHANED
$string['sessionnotwritable'] = 'Уочен је проблем са дозволом за уписивање и директоријум сесија.<br /><br />Обавестите сервер администратора.'; // ORPHANED
$string['shortnametaken'] = 'Кратак назив већ користи други курс'; // ORPHANED
$string['spellcheckernotconf'] = 'Провера правописа није конфигурисана'; // ORPHANED
$string['sslonlyaccess'] = 'Из разлога безбедности дозвољену су само https конекције.'; // ORPHANED
$string['statsdisable'] = 'Статистика није омгућена'; // ORPHANED
$string['statsnodata'] = 'Нема доступних података за ту комбинацију курса и временског периода.'; // ORPHANED
$string['storedfilecannotread'] = 'Није могуће прочитати датотеку - или датотека не постоји или постоје проблеми са овлашћењима'; // ORPHANED
$string['storedfilenotcreated'] = 'Није могуће креирати датотеку  \"$a->contextid/$a->filearea/$a->itemid/$a->filepath/$a->filename\"'; // ORPHANED
$string['tagdisabled'] = 'Ознаке су онемогућене'; // ORPHANED
$string['targetdatabasenotempty'] = 'Циљна база података није празна. Трансфер је поништен из разлога безбедности'; // ORPHANED
$string['themenotinstall'] = 'Ова шема изгледа није инсталирана'; // ORPHANED
$string['unknowaction'] = 'Непозната акција!'; // ORPHANED
$string['unknowcategory'] = 'Категорија није позната!'; // ORPHANED
$string['unknowcontext'] = 'Ово је непознати контекст($a) у get_child_contexts!'; // ORPHANED
$string['unknowformat'] = 'Формат није познат ($a)'; // ORPHANED
$string['unknowncontext'] = 'Ово је непознат контекст'; // ORPHANED
$string['unknownjsinrequirejs'] = 'Није могуће наћи JS библиотеку $a'; // ORPHANED
$string['unknowparamtype'] = 'Непознати тип параметра $a'; // ORPHANED
$string['unknowquestiontype'] = 'Неподржани тип питања $a'; // ORPHANED
$string['unspecifycourseid'] = 'Мора се навести id курса, кратак назив или  идентификациони (id) број'; // ORPHANED
$string['unsupportedevent'] = 'Неподржани тип догађаја'; // ORPHANED
$string['unsupportedwebserver'] = 'Опростите, софтвер за веб сервер ($a) није подржан.'; // ORPHANED
$string['upgraderequires19'] = 'Грешка: Нова верзија Moodlea је инсталирана на сервер, На жалост,  ажурирање са претходне верзије није подржано.<br />МОлимо Вас да прво ажурирате Moodle на последњу 1.9.x верзију. На претходну верзију се, такође, можете братити тако што ћете поново инсталирати оригиналне датоеке.'; // ORPHANED
$string['upgraderunning'] = 'Сајт се ажурира, молимо покушајте касније'; // ORPHANED
$string['urlnotdefinerss'] = 'Није дефисана URL адреса за RSS извор вести'; // ORPHANED
$string['useriddoesntexist'] = 'Id корисника не постоји'; // ORPHANED
$string['userisnotaparticipant'] = 'Корисник није учесник курса'; // ORPHANED
$string['usermustbemnet'] = 'Корисници на MNET контролној листи приступа мора бити удаљени MNET корисник'; // ORPHANED
$string['usernotcreated'] = 'Корисник није могао бити креиран'; // ORPHANED
$string['usernotincourse'] = 'Овај корсиник није на овом курсу'; // ORPHANED
$string['wrongcall'] = 'Овај скрипт је позван погрешно'; // ORPHANED
$string['wrongcontextid'] = 'ID контекста је неисораван (није га могуће наћи)'; // ORPHANED
$string['wrongroleid'] = 'Неисправан ID улоге'; // ORPHANED
$string['wscouldnotaddgroupmembernopermission'] = 'WS - Није било могуће додати члана групе -Нема овлашћења'; // ORPHANED
$string['wscouldnotcreateecoursenopermission'] = 'WS - Није било могуће креирати курс - Нема овлашћења'; // ORPHANED
$string['wscouldnotcreateeuserindb'] = 'WS - Није било могуће креирати корисника'; // ORPHANED
$string['wscouldnotcreateeusernopermission'] = 'WS - Није било могуће креирати корисника -Нема овлашћења'; // ORPHANED
$string['wscouldnotcreategroupnopermission'] = 'WS - Није било могуће креирати групу -Нема овлашћења'; // ORPHANED
$string['wscouldnotdeletegroupnopermission'] = 'WS - Није било могуће обрисати групу -Нема овлашћења'; // ORPHANED
$string['wscouldnotdeletenoexistinguser'] = 'WS - Није било могуће обрисати корисника -Корисник не постоји'; // ORPHANED
$string['wscouldnotdeleteusernopermission'] = 'WS - Није било могуће обрисати корисника -Нема овлашћења'; // ORPHANED
$string['wscouldnotremovegroupmembernopermission'] = 'WS - Није било могуће уклонити члана групе - Нема овлашћења'; // ORPHANED
$string['wscouldnotupdatenoexistinguser'] = 'WS - Није било могуће ажурирати корисника - Корисник не постоји'; // ORPHANED
$string['wscouldnotupdateuserindb'] = 'WS - Није било могуће ажурирати корисника'; // ORPHANED
$string['wscouldnotupdateusernopermission'] = 'WS - Није било могуће ажурирати корисника - Нема овлашћења'; // ORPHANED
$string['wscouldnotvieweusernopermission'] = 'WS - Није било могуће видети корисника - Нема овлашћења'; // ORPHANED
$string['wwwrootmismatch'] = 'Откривен је неисправан приступ. Овом серверу се једино може приступити преко адрес \"$a\". Молимо Вас да обавестите администратора.'; // ORPHANED
$string['wwwrootslash'] = 'У config.php датотеци неисправно је подешена линија \$CFG->wwwroot. Она на крају не сме да има косу црту  /<br />Молимо Бас, да о томе обавестите администратора.'; // ORPHANED
$string['xmldberror'] = 'XMLDB грешка!'; // ORPHANED
$string['younotteacher'] = 'ви нисте предавач!'; // ORPHANED
$string['cannotaddblock'] = '$a блок није могао бити додат листи блокова!'; // ORPHANED
$string['cannotaddcmtosection'] = 'Није било могуће додати нови модул у ову секцију'; // ORPHANED
$string['cannotaddnewinstance'] = 'Није било могуће додати инстанцу $a'; // ORPHANED
$string['cannotcreatedefaultcat'] = 'Грешка прилико креирања подразумеване категорије за контекст $a'; // ORPHANED
$string['cannotcreatefield'] = 'Грешка приликом креирања новог поља'; // ORPHANED
$string['cannotcreateuser'] = 'Грешка у креирању записа корисника'; // ORPHANED
$string['cannotdeletecate'] = 'Грешка приликом брисања категорије'; // ORPHANED
$string['cannotinsertkey'] = 'Није могуће убацити нови кључ'; // ORPHANED
$string['cannotsetupcategory'] = 'Озбиљна грешка! Није било могуће подесити подразумевану категорију курса!'; // ORPHANED
$string['cannotupdategroup'] = 'Грешка у ажурирању групе'; // ORPHANED
$string['cannotupdatemodcap'] = 'Није било могуће ажурирати $a могућности!'; // ORPHANED
$string['cannotupdateplugincap'] = 'Није било могуће ажурирати $a могућности!'; // ORPHANED
$string['cannotupdaterate'] = 'Није било могуће ажурирати старо оцењивање ($a->id = $a->rating)'; // ORPHANED
$string['cannotupdaterole'] = 'Није могуће ажурурати улогу!'; // ORPHANED
$string['cannotupdateuser'] = 'Ажурирање корсиника није успело'; // ORPHANED

?>
