<?PHP // $Id$ 
      // grades.php - created with Moodle 1.8.2+ (2007021520)


$string['addcategory'] = 'Додај категорију';
$string['addcategoryerror'] = 'Није могуће додати категорију';
$string['addexceptionerror'] = 'Дошло је до грешке током додавања изузетка за userid:gradeitem';
$string['allgrades'] = 'Све оцене по категоријама';
$string['allstudents'] = 'Сви студенти';
$string['average'] = 'Просек';
$string['backupwithoutgradebook'] = 'Резервна копија података не садржи подешавања књиге оцена';
$string['bonuspoints'] = 'Додатни бодови';
$string['categories'] = 'Категорије';
$string['category'] = 'Категорија';
$string['choosecategory'] = 'Изабери категорију';
$string['creatinggradebooksettings'] = 'Креирање подешавања књиге оцена';
$string['curveto'] = 'Прилагоди';
$string['deletecategory'] = 'Обриши категорију';
$string['displaylettergrade'] = 'Приказ словних оцена (A, B, C...)';
$string['displaypercent'] = 'Приказ процената';
$string['displaypoints'] = 'Приказ бодова';
$string['displayweighted'] = 'Приказ тежинских оцена';
$string['dropped'] = 'Одбачено';
$string['dropxlowest'] = 'Одбаци X најнижих';
$string['dropxlowestwarning'] = 'Напомена: Ако одбаците X најнижих оцена биће претпостављено да све ставке унутар категорије имају исту вредност у бодовима. Уколико различите ставке носе различит број бодова резултати ће бити непредвидљиви';
$string['errorgradevaluenonnumeric'] = 'Добијена је ненумеричка вредност за високу или ниску оцену за';
$string['errornocategorizedid'] = 'Није могуће добити некатегоризовани идентификатор!';
$string['errornocourse'] = 'Није могуће добити информације о курсу';
$string['errorreprintheadersnonnumeric'] = 'Добијена је ненумеричка вредност за поновни испис заглавља';
$string['exceptions'] = 'Изузеци';
$string['excluded'] = 'Искључено';
$string['extracredit'] = 'Додатни бодови';
$string['extracreditwarning'] = 'Напомена: Подешавање додатних бодова за све ставке у категорији ће их уклонити из прорачуна оцене, те неће бити укупног броја бодова';
$string['forstudents'] = 'За студенте';
$string['gradebook'] = 'Књига оцена';
$string['gradebookhiddenerror'] = 'Књига оцена је тренутно подешена тако да све скрива од студената';
$string['gradecategoryhelp'] = 'Помоћ за категорије оцена';
$string['gradeexceptions'] = 'Изузеци од оцењивања';
$string['gradeexceptionshelp'] = 'Помоћ за изузетке од оцењивања';
$string['gradehelp'] = 'Помоћ за оцене';
$string['gradeitem'] = 'Могућа оцена';
$string['gradeitemaddusers'] = 'Искључи из оцењивања';
$string['gradeitemmembersselected'] = 'Искључено из оцењивања';
$string['gradeitemnonmembers'] = 'Укључено у оцењивање';
$string['gradeitemremovemembers'] = 'Укључи у оцењивање';
$string['gradeitems'] = 'Могуће оцене';
$string['gradeletter'] = 'Словне оцене (A, B, C...)';
$string['gradeletterhelp'] = 'Помоћ за словне оцене';
$string['gradeletternote'] = 'Да бисте избрисали словну оцену само обришите било које од <br /> три текстулна поља за дато слово и притисните тастер за чување подешавања.';
$string['gradepreferenceshelp'] = 'Помоћ за својства оцене';
$string['grades'] = 'Оцене';
$string['gradeweighthelp'] = 'Помоћ за тежинску вредност оцена';
$string['hideadvanced'] = 'Сакриј напредне опције';
$string['hidecategory'] = 'Сакривено';
$string['highgradeascending'] = 'Сортирај по висини оцене, растуће';
$string['highgradedescending'] = 'Сортирај по висини оцене, опадајуће';
$string['highgradeletter'] = 'Горња граница';
$string['incorrectcourseid'] = 'Идентификатор курса је нетачан';
$string['item'] = 'Ставка';
$string['items'] = 'Ставке';
$string['lettergrade'] = 'Словна оцена';
$string['lettergradenonnumber'] = 'Најнижа и/или највиша оцена нису биле нумеричке за';
$string['letters'] = 'Слова';
$string['lowest'] = 'Најниже';
$string['lowgradeletter'] = 'Доња граница';
$string['max'] = 'Највише';
$string['maxgrade'] = 'Максимална оцена';
$string['median'] = 'Средина';
$string['min'] = 'Најниже';
$string['mode'] = 'Мод';
$string['no'] = 'Не';
$string['nocategories'] = 'Категорије оцена за овај курс не могу бити додате или пронађене';
$string['nocategoryview'] = 'Нема категорије по којој би се могао извршити приказ';
$string['nogradeletters'] = 'Нема подешених словних оцена';
$string['nogradesreturned'] = 'Нема добијених оцена';
$string['nolettergrade'] = 'Нема словне оцене за';
$string['nomode'] = 'Нема';
$string['nonnumericweight'] = 'Добијена је ненумеричка вредност за';
$string['nonweightedpct'] = 'нетежински %%';
$string['notteachererror'] = 'Морате бити предавач да бисте користили ову опцију.';
$string['pctoftotalgrade'] = '%% од укупне оцене';
$string['percent'] = 'Проценат';
$string['percentascending'] = 'Сортирај по процентима, растуће';
$string['percentdescending'] = 'Сортирај по процентима, опадајуће';
$string['percentshort'] = '%%';
$string['points'] = 'бодова';
$string['pointsascending'] = 'Сортирај по бодовима растуће';
$string['pointsdescending'] = 'Сортирај по бодовима опадајуће';
$string['preferences'] = 'Својства';
$string['rawpct'] = 'Необрађени %%';
$string['reprintheaders'] = 'Поновни испис заглавља';
$string['respectingcurrentdata'] = 'остављајући тренутна подешавања неизмењена';
$string['savechanges'] = 'Сачувај измене';
$string['savepreferences'] = 'Сачувај својства';
$string['scaledpct'] = 'Скалирани %%';
$string['setcategories'] = 'Подеси категорије';
$string['setcategorieserror'] = 'Прво морате да подесите категорије за Ваш курс пре него што им одредите тежинске вредности.';
$string['setgradeletters'] = 'Подеси словне оцене';
$string['setpreferences'] = 'Подеси својства';
$string['setting'] = 'Подешавање';
$string['settings'] = 'Подешавања';
$string['setweights'] = 'Подеси тежинске вредности';
$string['showallstudents'] = 'Прикажи све студенте';
$string['showhiddenitems'] = 'Прикажи скривене ставке';
$string['sort'] = 'сортирај';
$string['sortbyfirstname'] = 'Сортирај по имену';
$string['sortbylastname'] = 'Сортирај по презимену';
$string['standarddeviation'] = 'Стандардно одступање';
$string['stats'] = 'Статистика';
$string['statslink'] = 'Статистика';
$string['student'] = 'Студент';
$string['total'] = 'Укупно';
$string['totalweight100'] = 'Укупна тежинска вредност једнака је 100';
$string['totalweightnot100'] = 'Укупна тежинска вредност није једнака 100';
$string['uncategorised'] = 'Некатегорисано';
$string['useadvanced'] = 'Користи напредне опције';
$string['usepercent'] = 'Користи проценте';
$string['useweighted'] = 'Користи тежинске вредности';
$string['viewbygroup'] = 'Група';
$string['viewgrades'] = 'Погледај оцене';
$string['weight'] = 'тежинска вредност';
$string['weightedascending'] = 'Сортирај по тежинским процентима растуће';
$string['weighteddescending'] = 'Сортирај по тежинским процентима опадајуће';
$string['weightedpct'] = 'тежински %%';
$string['weightedpctcontribution'] = 'допринос тежинских %% у укупној оцени';
$string['writinggradebookinfo'] = 'Записивање подешавања књиге са оценама';
$string['yes'] = 'Да';
$string['yourgrade'] = 'Ваша оцена';
$string['addfeedback'] = 'Додај повратну информацију'; // ORPHANED
$string['additem'] = 'Додај могућу оцену'; // ORPHANED
$string['aggregateextracreditmeanall'] = 'Средња вредност свих оцена (екстра бодови)'; // ORPHANED
$string['aggregateextracreditmeangraded'] = 'Средња вредност уписаних оцена (екстра бодови)'; // ORPHANED
$string['aggregatemaxall'] = 'Највиша од свих оцена'; // ORPHANED
$string['aggregatemaxgraded'] = 'Највиша од уписаних оцена'; // ORPHANED
$string['aggregatemeanall'] = 'Средња вредност свих оцена'; // ORPHANED
$string['aggregatemeangraded'] = 'Средња вредност уписаних оцена'; // ORPHANED
$string['aggregatemedianall'] = 'Медијана свих оцена'; // ORPHANED
$string['aggregatemediangraded'] = 'Медијана уписаних оцена'; // ORPHANED
$string['aggregateminall'] = 'Најнижа од свих оцена'; // ORPHANED
$string['aggregatemingraded'] = 'Најнижа од уписаних оцена'; // ORPHANED
$string['aggregatemodeall'] = 'Мод уписаних оцена од свих оцена'; // ORPHANED
$string['aggregatemodegraded'] = 'Мод уписаних оцена'; // ORPHANED
$string['aggregateweightedmeanall'] = 'Пондерисана средња вредност свих оцена'; // ORPHANED
$string['aggregateweightedmeangraded'] = 'Пондерисана средња вредност уписаних оцена'; // ORPHANED
$string['aggregation'] = 'Груписање'; // ORPHANED
$string['aggregationposition'] = 'Позиција груписања'; // ORPHANED
$string['aggregationview'] = 'Групни поглед'; // ORPHANED
$string['autosort'] = 'Аутоматско сортирање'; // ORPHANED
$string['averagesdecimalpoints'] = 'Децимале у колони са средњим оценама'; // ORPHANED
$string['averagesdisplaytype'] = 'Тип приказа колоне са средњим оценам'; // ORPHANED
$string['badgrade'] = 'Дата оцена је неисправна'; // ORPHANED
$string['baduser'] = 'Дати корисник је неисправан'; // ORPHANED
$string['bulkcheckboxes'] = 'Опсежна поља за потврду'; // ORPHANED
$string['calculation'] = 'Прорачун'; // ORPHANED
$string['calculationadd'] = 'Додај прорачун'; // ORPHANED
$string['calculationedit'] = 'Измени прорачун'; // ORPHANED
$string['calculationsaved'] = 'Прорачун сачуван'; // ORPHANED
$string['calculationview'] = 'Погледај прорачун'; // ORPHANED
$string['categoriesedit'] = 'Измени категорије'; // ORPHANED
$string['categoryname'] = 'Име категорије'; // ORPHANED
$string['compact'] = 'Компактно'; // ORPHANED
$string['configaggregationposition'] = 'Место колоне за груписање у извештају оцењивача, према основним оценама'; // ORPHANED
$string['configaggregationview'] = 'Начин на који је груписање приказано: било  поред основних оцена или у компактном облику у којем се у истом тренутку види само један тип - основне ИЛИ груписане оцене.'; // ORPHANED
$string['configaveragesdecimalpoints'] = 'Број децимала за приказ сваког просека (групе или у целини), испод колоне са оценама. Ово може бити промењено за сваку ставку оцењивања.'; // ORPHANED
$string['configaveragesdisplaytype'] = 'Наведите како приказати просеке за сваку колоне у извештају оцењивача. Подразумевана и препоручена је наслеђена вредност, која прво проверава тип приказа за сваку колону. Уколико тип приказа није експлицитно подешен, он се поставља на општи Тип приказа оцена. Ако су изабрани други типови приказа, игнорисаће се појединачна подешавања за сваку колону, и користиће се искњучиво изабрани тип.'; // ORPHANED
$string['configbulkcheckboxes'] = 'Поља за потврду поред сваке оцене за обимне операције са оценама.'; // ORPHANED
$string['configdecimalpoints'] = 'Број децимала приказаних за сваку оцену. Ово може бити промењено за сваку ставку оцењивања.'; // ORPHANED
$string['configenableajax'] = 'Додаје нешто AJAX функционалности извештају оцењивача, чиме поједностављује и убрзава уобичајене операције. Зависи од тога да ли је корисник укључио Javascript на свом читачу.'; // ORPHANED
$string['configgradeboundary'] = 'Процентуалне границе, унутар којих ће оценама бити додењљене словне оцене (уколико се користи овај тип приказа оцена)'; // ORPHANED
$string['configgradedisplaytype'] = 'Оцене се могу приказати у основном облику, или као проценти (у односу на најмање и највеће оцене).'; // ORPHANED
$string['configgradeletter'] = 'Слово или други симбол који се користе за прикаѕ опсег оцена'; // ORPHANED
$string['configmeanselection'] = 'Одаберите који тип оцена ће бити уклључен у колону са просецима. Поља без ицена могу бити игнорисана, или рачуната као 0 (подразумевано подешавање)'; // ORPHANED
$string['configquickfeedback'] = 'Брза Повратна Информација додаје поље за унос текста уз сваку оцену на извештају оцењивача, чиме омогућује уређивање више оцена одједном. Кликом на дуге Ажурирај примењујете све промене одједном, уместо једну по једну.'; // ORPHANED
$string['configquickgrading'] = 'Брзо Оцењивање додаје поље за унос текста уз сваку оцену на извештају оцењивача, чиме омогућује уређивање више оцена одједном. Кликом на дуге Ажурирај примењујете све промене одједном, уместо једну по једну.'; // ORPHANED
$string['configrangesdecimalpoints'] = 'Број децимала за приказ сваког типа опсега, изнад колоне са оценама. Ово може бити промењено за сваку ставку оцењивања.'; // ORPHANED
$string['configrangesdisplaytype'] = 'Наведите како приказати опсег сваке колоне у извештају оцењивача. Подразумевана и препоручена је наслеђена вредност, која прво проверава тип приказа за сваку колону. Уколико тип приказа није експлицитно подешен, он се поставља на општи Тип приказа оцена. Ако су изабрани други типови приказа, игнорисаће се појединачна подешавања за сваку колону, и користиће се искњучиво изабрани тип.'; // ORPHANED
$string['configshowaverages'] = 'Прикажи колону са просецима у извештају оцењивача'; // ORPHANED
$string['configshowcalculations'] = 'Да ли приказати иконицу дигитрона поред сваке могуће оцене и категорије оцењивања, кратак опис преко прорачунатих оцена и визуелни индикатор да је колона прорачуната.'; // ORPHANED
$string['configshoweyecons'] = 'Да ли приказати иконицу прикажи/сакриј поред сваке оцене (чиме се контролише да ли ће их корисник видети).'; // ORPHANED
$string['configshowfeedback'] = 'Да ли приказати иконицу за повратну информацију (за додавање/мењање) поред сваке оцене.'; // ORPHANED
$string['configshowgroups'] = 'Прикажи збирове и средње вредности група у извештају оцењивача.'; // ORPHANED
$string['configshowlocks'] = 'Да ли приказати иконицу закључај/откључај поред сваке оцене.'; // ORPHANED
$string['configshowranges'] = 'Прикажи ред са опсегом могућих оцена за сваку од ставки у извештају оцењивача.'; // ORPHANED
$string['configshowuserimage'] = 'Да ли приказати слику корисника поред његовог имена у извешатају оцењивача'; // ORPHANED
$string['configstudentsperpage'] = 'Број студената приказаних на свакој страни извештаја оцењивача'; // ORPHANED
$string['contract'] = 'Смањи Категорију'; // ORPHANED
$string['createcategory'] = 'Креирај Категорију'; // ORPHANED
$string['createcategoryerror'] = 'Креирање нове категорије немогуће'; // ORPHANED
$string['decimalpoints'] = 'Децимале'; // ORPHANED
$string['default'] = 'Подразумевано'; // ORPHANED
$string['droplow'] = 'Одбаци најниже'; // ORPHANED
$string['editcalculation'] = 'Измени прорачун'; // ORPHANED
$string['editfeedback'] = 'Измени повратну информацију'; // ORPHANED
$string['editgrade'] = 'Измени оцену'; // ORPHANED
$string['edittree'] = 'Категорије'; // ORPHANED
$string['enableajax'] = 'Омогући AJAX'; // ORPHANED
$string['encoding'] = 'Кодирање'; // ORPHANED
$string['errorcalculationunknown'] = 'Неисправна формула'; // ORPHANED
$string['expand'] = 'Прошири Категорију'; // ORPHANED
$string['exportods'] = 'Извези ODS'; // ORPHANED
$string['exportplugins'] = 'Извези додатке'; // ORPHANED
$string['exporttxt'] = 'Извези TXT'; // ORPHANED
$string['exportxml'] = 'Извези XML'; // ORPHANED
$string['feedback'] = 'Повратна информација'; // ORPHANED
$string['feedbackadd'] = 'Додај повратну информацију'; // ORPHANED
$string['feedbackedit'] = 'Измени повратну информацију'; // ORPHANED
$string['feedbacksaved'] = 'Повратна информација снимљена'; // ORPHANED
$string['feedbackview'] = 'Погледај повратну информацију'; // ORPHANED
$string['finalgrade'] = 'Коначна оцена'; // ORPHANED
$string['forelementtypes'] = 'за изабрани $a'; // ORPHANED
$string['full'] = 'Пун'; // ORPHANED
$string['grade'] = 'Оцена'; // ORPHANED
$string['gradeboundary'] = 'Границе словних оцена'; // ORPHANED
$string['gradecategory'] = 'Категорија оцена'; // ORPHANED
$string['gradedisplaytype'] = 'Тип приказа оцена'; // ORPHANED
$string['gradeitemlocked'] = 'Оцењивање закључано'; // ORPHANED
$string['gradeitemsinc'] = 'Могуће оцене које треба укључити'; // ORPHANED
$string['grademax'] = 'Највећа оцена'; // ORPHANED
$string['grademin'] = 'Најмања оцена'; // ORPHANED
$string['gradepass'] = 'Оцена за пролаз'; // ORPHANED
$string['gradepreferences'] = 'Својства оцене'; // ORPHANED
$string['gradereports'] = 'Извештај о оцењивању'; // ORPHANED
$string['graderreport'] = 'Извештај оцењивача'; // ORPHANED
$string['gradetype'] = 'Тип оцене'; // ORPHANED
$string['gradeview'] = 'Погледај оцену'; // ORPHANED
$string['groupavg'] = 'Просек групе'; // ORPHANED
$string['hidden'] = 'Сакривено'; // ORPHANED
$string['hideaverages'] = 'Сакриј просеке'; // ORPHANED
$string['hidecalculations'] = 'Сакриј прорачуне'; // ORPHANED
$string['hideeyecons'] = 'Сакриј иконице прикажи/сакриј'; // ORPHANED
$string['hidefeedback'] = 'Сакриј повратне информације'; // ORPHANED
$string['hidegroups'] = 'Сакриј групе'; // ORPHANED
$string['hidelocks'] = 'Сакриј закључавања'; // ORPHANED
$string['hideranges'] = 'Сакриј опсеге'; // ORPHANED
$string['identifier'] = 'Идентификуј корисника према'; // ORPHANED
$string['importcsv'] = 'Увези CSV'; // ORPHANED
$string['importfailed'] = 'Увоз није успео'; // ORPHANED
$string['importfile'] = 'Увези датотеку'; // ORPHANED
$string['importplugins'] = 'Увези додатке'; // ORPHANED
$string['importpreview'] = 'Увези приказ'; // ORPHANED
$string['importsuccess'] = 'Увоз оцена успешан'; // ORPHANED
$string['importxml'] = 'Увези XML'; // ORPHANED
$string['inherit'] = 'Наслеђено'; // ORPHANED
$string['iteminfo'] = 'Информације о ставци'; // ORPHANED
$string['itemname'] = 'Име ставке'; // ORPHANED
$string['itemsedit'] = 'Измени могућу оцену'; // ORPHANED
$string['keephigh'] = 'Задржи највећу'; // ORPHANED
$string['left'] = 'Лево'; // ORPHANED
$string['letter'] = 'Слово'; // ORPHANED
$string['lock'] = 'Закључај'; // ORPHANED
$string['locked'] = 'Закључано'; // ORPHANED
$string['locktime'] = 'Закључано до'; // ORPHANED
$string['mapfrom'] = 'Пресликај из'; // ORPHANED
$string['mappings'] = 'Пресликавање могућих оцена'; // ORPHANED
$string['mapto'] = 'Пресликај у'; // ORPHANED
$string['meanall'] = 'Све оцене'; // ORPHANED
$string['meangraded'] = 'Непразне оцене'; // ORPHANED
$string['meanselection'] = 'Оцене одабране за рачунање просека'; // ORPHANED
$string['movingelement'] = 'Померање $a'; // ORPHANED
$string['multfactor'] = 'Мултипликатор'; // ORPHANED
$string['newcategory'] = 'Нова категорија'; // ORPHANED
$string['nocategoryname'] = 'Није дато име категорије'; // ORPHANED
$string['noselectedcategories'] = 'није изабрана ниједна категорија.'; // ORPHANED
$string['noselecteditems'] = 'није изабрана ниједна ставка.'; // ORPHANED
$string['onascaleof'] = 'на скали од $a->grademin до $a->grademax'; // ORPHANED
$string['outcome'] = 'Исход'; // ORPHANED
$string['overridden'] = 'Одбачено'; // ORPHANED
$string['percentage'] = 'Проценат'; // ORPHANED
$string['plusfactor'] = 'Помак'; // ORPHANED
$string['quickfeedback'] = 'Брза повратна информација'; // ORPHANED
$string['quickgrading'] = 'Брзо оцењивање'; // ORPHANED
$string['range'] = 'Опсег'; // ORPHANED
$string['rangesdecimalpoints'] = 'Децимале приказане у опсезима'; // ORPHANED
$string['rangesdisplaytype'] = 'Тип приказа са опсезима'; // ORPHANED
$string['rank'] = 'Ранг'; // ORPHANED
$string['reportplugins'] = 'Додаци за извештај'; // ORPHANED
$string['right'] = 'Десно'; // ORPHANED
$string['selectdestination'] = 'Изабери одредиште за $a'; // ORPHANED
$string['selectplugin'] = 'Изабери додатак'; // ORPHANED
$string['separator'] = 'Граничник'; // ORPHANED
$string['sepcomma'] = 'Зарез'; // ORPHANED
$string['septab'] = 'Табулатор'; // ORPHANED
$string['showaverages'] = 'Прикажи колону са просецима'; // ORPHANED
$string['showcalculations'] = 'Прикажи прорачуне'; // ORPHANED
$string['showeyecons'] = 'Прикажи иконице за приказ/сакривање'; // ORPHANED
$string['showfeedback'] = 'Прикажи повратне информације'; // ORPHANED
$string['showgroups'] = 'Прикажи групе'; // ORPHANED
$string['showlocks'] = 'Прикажи закључавања'; // ORPHANED
$string['showranges'] = 'Прикажи опсеге'; // ORPHANED
$string['showuserimage'] = 'Прикажи слике из корисничких профила'; // ORPHANED
$string['sortasc'] = 'Сортирај у растући низ'; // ORPHANED
$string['sortdesc'] = 'Сортирај у опадајући низ'; // ORPHANED
$string['studentsperpage'] = 'Број студената по страни'; // ORPHANED
$string['subcategory'] = 'Нормална Категорија'; // ORPHANED
$string['synclegacygrades'] = 'Синхронизуј старе оцене'; // ORPHANED
$string['topcategory'] = 'Наткатегорија'; // ORPHANED
$string['turnfeedbackoff'] = 'Искључи повратне информације'; // ORPHANED
$string['turnfeedbackon'] = 'Укључи повратне информације'; // ORPHANED
$string['typenone'] = 'Ниједан'; // ORPHANED
$string['typescale'] = 'Скала'; // ORPHANED
$string['typetext'] = 'Текст'; // ORPHANED
$string['typevalue'] = 'Вредност'; // ORPHANED
$string['unlock'] = 'Откључај'; // ORPHANED
$string['unused'] = 'Некоришћено'; // ORPHANED
$string['uploadgrades'] = 'Пошаљи оцене'; // ORPHANED
$string['usenooutcome'] = 'Без исхода'; // ORPHANED
$string['usenoscale'] = 'Без скала'; // ORPHANED
$string['userpreferences'] = 'Корисничке преференције'; // ORPHANED
$string['userreport'] = 'Користи извештај о оцењивању'; // ORPHANED
$string['configgrandtotalsdisplaytype'] = 'Збирови колона могу се приказати у основном облику или као процентии (у односу на најмање и највеће оцене).'; // ORPHANED
$string['configshowgrandtotals'] = 'Прикажи збирове колона у извештају оцењивача'; // ORPHANED
$string['configshowscales'] = 'Прикажи ред који приказује скалу за сваку могућу оцену, у извештају оцењивача'; // ORPHANED
$string['grandtotalsdisplaytype'] = 'Начин приказа збирова колона'; // ORPHANED
$string['hidegrandtotals'] = 'Сакриј укупне збирове'; // ORPHANED
$string['hidescales'] = 'Сакриј скале'; // ORPHANED
$string['raw'] = 'Основно'; // ORPHANED
$string['showgrandtotals'] = 'Прикажи збирове колона'; // ORPHANED
$string['showscales'] = 'Прикажи скале'; // ORPHANED

?>
