<?PHP // $Id$ 
      // group.php - created with Moodle 1.8.2+ (2007021520)


$string['addgroupstogrouping'] = 'Додај групу груписању';
$string['addgroupstogroupings'] = 'Додај/избриши групе';
$string['adduserstogroup'] = 'Додај/избриши кориснике';
$string['allocateby'] = 'Издвој чланове';
$string['anygrouping'] = '[Било које груписање]';
$string['autocreategroups'] = 'Аутоматски креирај групе';
$string['backtogroupings'] = 'Назад у груписања';
$string['backtogroups'] = 'Назад у групе';
$string['badnamingscheme'] = 'Мора садржати тачно један знак \'@\' или један \'#\'';
$string['createautomaticgrouping'] = 'Креирај аутоматско груписање';
$string['creategroup'] = 'Креирај групу';
$string['creategrouping'] = 'Креирај груписање';
$string['creategroupinselectedgrouping'] = 'Креирај групу у груписању';
$string['createorphangroup'] = 'Креирај групу негруписаних студената';
$string['databaseupgradegroups'] = 'Верзија група је сада $a';
$string['defaultgroupdescription'] = 'Опис стандардне групе';
$string['defaultgrouping'] = 'Подразумевано груписање';
$string['defaultgroupingname'] = 'Груписање';
$string['defaultgroupname'] = 'Група';
$string['defaultgroupprefix'] = 'Група';
$string['deletegroupconfirm'] = 'Да ли сте сигурни да желите да избришете групу \'$a\'?';
$string['deletegrouping'] = 'Избриши груписање';
$string['deletegroupingconfirm'] = 'Да ли сте сигурни да желите да избришете груписање \'$a\'?';
$string['deleteselectedgroup'] = 'Избришите означену групу';
$string['displaygrouping'] = 'Прикажите груписање';
$string['distributealphabetically'] = 'Разврстај у групе абецедно према презимену';
$string['distributeevenly'] = 'Равномерно подели студенте који су преостали';
$string['editgroupingsettings'] = 'Уреди подешавање груписања';
$string['editgroupsettings'] = 'Уреди подешавање групе';
$string['enrolmentkey'] = 'Шифра';
$string['erroraddremoveuser'] = 'Грешка у додавању/брисању корисника $a групи';
$string['erroreditgroup'] = 'Грешка у креирању/ажурирању  групе $a';
$string['erroreditgrouping'] = 'Грешка у креирању/ажурирању груписања $a';
$string['errorinvalidgroup'] = 'Грешка, погрешна група $a';
$string['existingmembers'] = 'Постојећи чланови: $a';
$string['filtergroups'] = 'Издвој групе по';
$string['firstname'] = 'име по азбучном реду';
$string['group'] = 'Група';
$string['groupaddedsuccesfully'] = 'Група $a је успешно додата';
$string['groupby'] = 'Креирај групе према броју';
$string['groupdescription'] = 'Опис групе';
$string['groupinfo'] = 'Информације о изабраној групи';
$string['groupinfomembers'] = 'Информације о иѕабраним члановима';
$string['groupinfopeople'] = 'Информације о изабраним људима';
$string['grouping'] = 'Груписање';
$string['groupingdescription'] = 'Опис груписања';
$string['groupingname'] = 'Наѕив груписања';
$string['groupingnameexists'] = 'Име груписања \'$a\' већ постоји у овом курсу, молимо изаберите неко друго име.';
$string['groupings'] = 'Груписања';
$string['groupmember'] = 'Члан групе';
$string['groupmemberdesc'] = 'Стандардна улога члана групе';
$string['groupmembers'] = 'Чланови групе';
$string['groupmembersonly'] = 'Доступно само члановима групе';
$string['groupmembersonlyerror'] = 'Извините, морате бити члан бар једне групе која се користи у овој активности.';
$string['groupmemberssee'] = 'Види чланове групе';
$string['groupmembersselected'] = 'Чланови изабране групе';
$string['groupmode'] = 'Групни начин рада';
$string['groupmodeforce'] = 'Обавезни групни начин рада';
$string['groupmy'] = 'Моја група';
$string['groupname'] = 'Назив групе';
$string['groupnameexists'] = 'Назив групе \'$a\' већ постоји у оквиру овог курса, молим вас изаберите неко друго';
$string['groupnotamember'] = 'Извини, ниси члан те групе';
$string['groups'] = 'Групе';
$string['groupsinselectedgrouping'] = 'Групе у:';
$string['groupsnone'] = 'Нема група';
$string['groupspreview'] = 'Преглед групе';
$string['groupsseparate'] = 'Раздвоји групе';
$string['groupsvisible'] = 'Видљиве групе';
$string['hidepicture'] = 'Сакриј слику';
$string['javascriptrequired'] = 'Ова страница захтева Јавасцрипт да би било омогућено њено читањ';
$string['lastname'] = 'презиме по азбучном реду';
$string['members'] = 'Чланова по групи';
$string['membersofselectedgroup'] = 'Чланови:';
$string['namingscheme'] = 'Шема именовања';
$string['namingschemehelp'] = 'напомена: Користити \'@\' за представљање слова групе или \'#\' за представљање броја групе';
$string['newpicture'] = 'Нова слика';
$string['nogroups'] = 'Још увек нема постављених група у овом курсу';
$string['nogroupsassigned'] = 'Нема придружених група';
$string['nopermissionforcreation'] = 'Не можеш креирати групу \"$a\" јер немаш дозволу';
$string['notingrouping'] = '[Not in a grouping]';
$string['nousersinrole'] = 'Нема одговарајућих корисника са изабраном улогом';
$string['number'] = 'Број група или чланова по групи';
$string['numberofgroups'] = 'Број група';
$string['numberofstudents'] = 'Број студената';
$string['overview'] = 'Преглед';
$string['potentialmembers'] = 'Могућу чланови: $a';
$string['prefixforgroupnames'] = 'Префикс за име група';
$string['printerfriendly'] = 'Приказ за штампу';
$string['random'] = 'случајним избором';
$string['removegroupfromselectedgrouping'] = 'Избриши групу из груписања';
$string['removeselectedusers'] = 'Избриши означене кориснике';
$string['selectfromrole'] = 'Улога да би се бирали чланови из';
$string['selectnumberineachgroup'] = 'Одабран број у свакој групи';
$string['selectnumberofgroups'] = 'Иѕабран број група';
$string['showgroupsingrouping'] = 'Покажи групе у груписању';
$string['showmembersforgroup'] = 'Прикажи чланове групе';
$string['toomanygroups'] = 'Недовољно корисника да попуне овај број група - има само $a корисника са изабраном улогом';
$string['usergroupmembership'] = 'Изабрано чланство корисника';
$string['usestudentsonlyfromselectedgroup'] = 'Користи само студенте из тренутно означене групе';
$string['cancel'] = 'Обустави'; // ORPHANED
$string['editgroupingpermissions'] = 'Уреди дозволе груписања'; // ORPHANED
$string['errorinvalidgrouping'] = 'Грешка, погрешно груписање $a'; // ORPHANED
$string['errornotingrouping'] = 'Иѕвини, не можеш креирати групу у $a'; // ORPHANED
$string['errornotingroupingedit'] = 'Иѕвини, не можеш уређивати груписање $a'; // ORPHANED
$string['groupfor'] = 'за групу'; // ORPHANED
$string['return'] = 'Повратак'; // ORPHANED
$string['save'] = 'Сачувај'; // ORPHANED
$string['showusersalreadyingroup'] = 'Прикажи кориснике који су већ у групама у груписању'; // ORPHANED
$string['teachersgroupmark'] = 'Наставници не могу да маркирају активности  група којима не припадају'; // ORPHANED
$string['teachersgroupview'] = 'Наставници не могу да виде активности група којима не припадају'; // ORPHANED
$string['teachersoverride'] = 'Наставници који нису ни у једној групи могу да виде и маркирају акривности свих група'; // ORPHANED
$string['upgradeconfirm'] = 'Нажалост, табеле група креиране у Моодле 18ДЕВ морају бити избрисани у овој верзији. Да ли желиш да наставиш?'; // ORPHANED
$string['viewallgroupsactivities'] = 'Студенти могу да виде али не могу да учествују у активностима свих група'; // ORPHANED
$string['viewallgroupsmembers'] = 'Студенти могу да виде чланове свих група'; // ORPHANED
$string['viewowngroup'] = 'Студенти могу да виде чланове свих група којима припадају'; // ORPHANED

?>
