<?PHP // $Id$ 
      // question.php - created with Moodle 1.9.9 (Build: 20100609) (2007101590)


$string['adminreport'] = 'Извештај о могућим проблемима у вашој бази података са питањима';
$string['broken'] = 'Ово је \"прекинут линк\", показује на не постојећи фајл.';
$string['byandon'] = 'уредио/ла <em>$a->user</em> (<em>$a->time</em>)';
$string['categorycurrent'] = 'Тренутна категорија';
$string['categorycurrentuse'] = 'Користи ову категорију';
$string['categorydoesnotexist'] = 'Ова категорија не постоји';
$string['categorymoveto'] = 'Сними у категорији';
$string['changepublishstatuscat'] = '<a href=\"$a->caturl\">Категорији \"$a->name\"</a> ће у оквиру курса \"$a->coursename\" бити промењен статус дељења из <strong>$a->changefrom у $a->changeto</strong>.';
$string['copy'] = 'Копирај из $a и промени линкове.';
$string['created'] = 'Креирано';
$string['createdmodifiedheader'] = 'Креирано / Последња измена';
$string['cwrqpfs'] = 'Насумично изабрана питања се бирају из подкатегорија.';
$string['cwrqpfsinfo'] = '<p>Током надоградње до Moodle верзије 1.9 категорије питања ће бити подељене у различите контексте. Неким питањима и категоријама на Вашем сајту ће морати бити промењен статус дељења. То је неопходно у ретким случајевима када је једно или више насумично изабраних питања у неком тесту подешено тако да се бирају из мешавине дељених и недељених категорија (што се појављује на овом сајту). Ова појава је типична за ситуацију у којој је питање које се насумично бира подешено тако да се бира из више поткатегорија од којих је бар једна различитог статуса дељења у односу на надређену категорију у којој је креирано питање које се насумично бира.</p>
<p>Следећим категоријама питања, из којих се бирају насумична питања у надређеним категоријама, биће промењен статус дељења у исти онај какав важи за категорију у којој је насумично изабрано питање при надоградњи до Moodle верзије 1.9. Питања на која ће те измене утицати ће и даље нормално функционисати у свим постојећим тестовима све док их не уклоните из тих тестова.';
$string['cwrqpfsnoprob'] = 'Нема категорија питања на Вашем сајту на које би могао утицати проблем \'Насумично изабраних питања бираних из поткатегорија\'.';
$string['defaultfor'] = 'Подразумевано за $a';
$string['defaultinfofor'] = 'Подразумевана категорија за питања дељена у контексту \'$a\'.';
$string['deletecoursecategorywithquestions'] = 'Постоје питања у бази питања придруженој овој категорији курсева. Ако наставите, она ће бити обрисана. Можда бисте желели да их прво преместите, користећи интерфејс за базе питања.';
$string['donothing'] = 'Немојте копирати/премештати датотеке или мењати линкове.';
$string['editingcategory'] = 'Уређивање категорије';
$string['editingquestion'] = 'Уређивање питања';
$string['editthiscategory'] = 'Уреди ову категорију';
$string['erroraccessingcontext'] = 'Не може се приступити контексту';
$string['errordeletingquestionsfromcategory'] = 'Грешка при брисању питања из категорије $a.';
$string['errorfilecannotbecopied'] = 'Грешка, не може се копирати фајл $a.';
$string['errorfilecannotbemoved'] = 'Грешка, не може се преместити фајл $a.';
$string['errorfileschanged'] = 'Датотеке грешака повезане с питањима су измењене од кад је форма приказана.';
$string['errormanualgradeoutofrange'] = 'Оцена $a->grade није између 0 и $a->maxgrade за питање $a->name. Резултат и коментар нису сачувани.';
$string['errormovingquestions'] = 'Грешка при премештању питања са id вредностима \$а.';
$string['errorprocessingresponses'] = 'Настала је грешка при обради Ваших одзива.';
$string['errorsavingcomment'] = 'Грешка при чувању коментара за питање $a->name у бази података.';
$string['errorupdatingattempt'] = 'Грешка при покушају ажурирања $a->id у бази података.';
$string['exportcategory'] = 'Извези категорију';
$string['filesareacourse'] = 'Област фајлова са курса';
$string['filesareasite'] = 'Област фајлова са сајта';
$string['filestomove'] = 'Копирај / премести фајлове у $a?';
$string['fractionsnomax'] = 'Један од одговора би требао носити 100%% резултата тако да је могуће добити максималан могући број бодова за ово питање.';
$string['getcategoryfromfile'] = 'Преузми категорију из датотеке';
$string['getcontextfromfile'] = 'Преузми контекст из датотеке';
$string['ignorebroken'] = 'Игнориши неисправне линкове';
$string['invalidcontextinhasanyquestions'] = 'Неисправан контекст прослеђен у question_context_has_any_questions.';
$string['linkedfiledoesntexist'] = 'Датотека $a до које води линк не постоји';
$string['makechildof'] = 'Направи потомка од \'$a\'';
$string['maketoplevelitem'] = 'Помери на највиши ниво';
$string['missingimportantcode'] = 'Овом типу питања недостаје важан код: $a.';
$string['modified'] = 'Последња измена';
$string['move'] = 'Премести из $a и промени линкове.';
$string['movecategory'] = 'Премести категорију';
$string['movedquestionsandcategories'] = 'Премештена су питања и категорије питања са $a->oldplace на $a->newplace.';
$string['movelinksonly'] = 'Само промените дестинације линкова, немојте премештати нити копирати датотеке.';
$string['moveq'] = 'Премести питање(а)';
$string['moveqtoanothercontext'] = 'Премести питање у други контекст.';
$string['movingcategory'] = 'Премештање категорије';
$string['movingcategoryandfiles'] = 'Да ли сте сигурни да желите да преместите категорију {$a->name} и све њој подређене категорије у контекст за \"{$a->contextto}\"?<br /> Постоји {$a->urlcount} датотека у вези са питањима у {$a->fromareaname}. Да ли желите да је(их) копирате или преместите у {$a->toareaname}?';
$string['movingcategorynofiles'] = 'Да ли сте сигурни да желите да преместите категорију \"{$a->name}\" и све поткатегорије у контекст за \"{$a->contextto}\"?';
$string['movingquestions'] = 'Премештање питања и датотека';
$string['movingquestionsandfiles'] = 'Да ли сте сигурни да желите да преместите питање(а) {$a->questions} у контекст за <strong>\"{$a->tocontext}\"</strong>?<br /> Постоји <strong>{$a->urlcount} датотека</strong> до које(којих) воде линкови из овог(ових) питања у {$a->fromareaname}. Да ли желите да је(их) копирате или преместите у {$a->toareaname}?';
$string['movingquestionsnofiles'] = 'Да ли сте сигурни да желите да преместите питање(а) {$a->questions} у контекст за <strong>\"{$a->tocontext}\"</strong>?<br /> <strong>Нема датотека</strong> повезаних са њим(а) у {$a->fromareaname}.';
$string['needtochoosecat'] = 'Морате одабрати категорију у коју желите да преместите ово питање или притиснути \'откажи\'.';
$string['nopermissionadd'] = 'Немате одобрење да додате питање овде.';
$string['nopermissionmove'] = 'Немате дозволе да премештате питања одавде. Морате сачувати питање у овој категорији или га сачувати као ново питање.';
$string['noprobs'] = 'Није нађен ни један проблем у вашој бази података са питањима.';
$string['notenoughdatatoeditaquestion'] = 'Нису специфицирани ни идентификатор питања, ни идентификатор категорије са типом питања.';
$string['notenoughdatatomovequestions'] = 'Морате навецти идентификаторе питања која желите да преместите.';
$string['permissionedit'] = 'Уредите ово питање';
$string['permissionmove'] = 'Преместите ово питање';
$string['permissionsaveasnew'] = 'Снимите ово питање као ново';
$string['permissionto'] = 'Имате дозволу да:';
$string['published'] = 'објављено';
$string['questionaffected'] = '<a href=\"$a->qurl\">Питање \"$a->name\" ($a->qtype)</a> је у овој категорији питања али се користи и у <a href=\"$a->qurl\">тесту \"$a->quizname\"</a> који припада другом курсу \"$a->coursename\".';
$string['questionbank'] = 'Банка питања';
$string['questioncategory'] = 'Категорија питања';
$string['questioncatsfor'] = 'Категорије питања за \'$a\'';
$string['questiondoesnotexist'] = 'Ово питање не постоји';
$string['questionsmovedto'] = 'Питање које се још увек користи је премештено у \"$a\" у оквиру надређене категорије.';
$string['questionsrescuedfrom'] = 'Питање сачувано из контекста $a.';
$string['questionsrescuedfrominfo'] = 'Ова питања (од којих нека могу бити скривена) сачувана су када је контекст $a био обрисан, зато што се још увек користе у неким тестовима или другим активностима.';
$string['questionuse'] = 'Користи питање у овој активности';
$string['shareincontext'] = 'Дели у контексту за $a';
$string['tofilecategory'] = 'Упиши категорију у датотеку';
$string['tofilecontext'] = 'Упиши контекст у датотеку';
$string['unknown'] = 'Непознато';
$string['unknownquestiontype'] = 'Непознат тип питања: $a.';
$string['unpublished'] = 'необјављено';
$string['upgradeproblemcategoryloop'] = 'Откривен је проблем при покушају ажурирања категорија питања. Постоји петља у стаблу категорија. Погођене су тиме категорије са id вредностима \$а.';
$string['upgradeproblemcouldnotupdatecategory'] = 'Није могуће ажурирати категорију питања $a->name ($a->id).';
$string['upgradeproblemunknowncategory'] = 'Откривен је проблем при покушају ажурирања категорија питања. Категорија $a->id указује на надређену категорију $a->parent, која не постоји. Промењена је надређена категорија да би се решио проблем.';
$string['yourfileshoulddownload'] = 'Ваша датотека за извоз - требало би да ускоро започне преузимање. У супротном, молимо <a href=\"$a\">кликните овде</a>. Промењена је надређена категорија да би се решио проблем.';
$string['availableq'] = 'Доступно?'; // ORPHANED
$string['cannotcopybackup'] = 'Није могуће копирати датотеку резервне копије'; // ORPHANED
$string['cannotcreate'] = 'Није могуће креирати нови унос у табели  question_attempts'; // ORPHANED
$string['cannotcreatepath'] = 'Није могуће креирати путању: $a'; // ORPHANED
$string['cannotdeletecate'] = 'Не можете да обришете ову категорију, пошто је у овом контексту то подразумевана категорија.'; // ORPHANED
$string['cannotenable'] = 'Тип питања $a не може бити креиран директно.'; // ORPHANED
$string['cannotfindcate'] = 'Није могуће пронаћи запис категорије'; // ORPHANED
$string['cannotfindquestionfile'] = 'Није могуће пронаћи датотеку са питањима у зип архиви'; // ORPHANED
$string['cannothidequestion'] = 'Није било могуће сакрити питање'; // ORPHANED
$string['cannotimportformat'] = 'Опростите, уноз овог формата још није имплементиран!'; // ORPHANED
$string['cannotinsertquestion'] = 'Није могуће убацити ново питање!'; // ORPHANED
$string['cannotloadquestion'] = 'Није могуће учитати питање'; // ORPHANED
$string['cannotmovequestion'] = 'Не можете да користите овај скрипт за пребацивање питања која са собом имају придружене датотеке из различитих подручја.'; // ORPHANED
$string['cannotopenforwriting'] = 'Није могуће отворити за уписивање: $a'; // ORPHANED
$string['cannotpreview'] = 'Не можете да прегледате ова питања!'; // ORPHANED
$string['cannotretrieveqcat'] = 'Можете повратити ову категорију питања'; // ORPHANED
$string['cannotunzip'] = 'Није могуће распаковати архивирану зип датотеку'; // ORPHANED
$string['cannotwriteto'] = 'Није могуће уписати извезена питања у $a'; // ORPHANED
$string['chooseqtypetoadd'] = 'Изабери тип питања за додавање'; // ORPHANED
$string['clicktoflag'] = 'Обележи ово питање индикаторпм (заставицом)'; // ORPHANED
$string['clicktounflag'] = 'Уклони индикатор(заставицу)'; // ORPHANED
$string['contexterror'] = 'Не бисте смели да будете овде уколико нисте премсетили категорију у други контекст'; // ORPHANED
$string['createdby'] = 'Креирао/ла'; // ORPHANED
$string['createnewquestion'] = 'Креирај ново питање'; // ORPHANED
$string['disabled'] = 'Онемогућено'; // ORPHANED
$string['disterror'] = 'Дистрибуција $a је изазвала проблеме'; // ORPHANED
$string['emptyxml'] = 'Непозната грешја - празна imsmanifest.xml датотека'; // ORPHANED
$string['enabled'] = 'Омогућено'; // ORPHANED
$string['errorduringpost'] = 'Појавила се грешка у току пост-процесирања!'; // ORPHANED
$string['errorduringpre'] = 'Појавила се грешка у току пре-процесирања!'; // ORPHANED
$string['errorduringproc'] = 'Појавила се грешка у току процесирања!'; // ORPHANED
$string['errorpostprocess'] = 'Појавила се грешка у току пост-процесирања!'; // ORPHANED
$string['errorpreprocess'] = 'Појавила се грешка у току пре-процесирања!'; // ORPHANED
$string['errorprocess'] = 'Појавила се грешка у току процесирања!'; // ORPHANED
$string['exporterror'] = 'Појавила се грешка у току експортовања!'; // ORPHANED
$string['flagged'] = 'Обележено'; // ORPHANED
$string['flagthisquestion'] = 'Обележи ово питање'; // ORPHANED
$string['impossiblechar'] = 'Откривен је немогући карактер $a као знак за заграде'; // ORPHANED
$string['invalidconfirm'] = 'Израз за потврду је неисправан'; // ORPHANED
$string['lastmodifiedby'] = 'Последњи пут изменио/ла'; // ORPHANED
$string['missingoption'] = 'Питању типа Уметнути одговори $a недостају опције'; // ORPHANED
$string['nocate'] = 'Не постоји категорија $a!'; // ORPHANED
$string['notflagged'] = 'Није обележено'; // ORPHANED
$string['parenthesisinproperclose'] = 'заграде пре ** нису правилно затворене у $a*'; // ORPHANED
$string['parenthesisinproperstart'] = 'заграде пре ** нису правилно отворене у $a*'; // ORPHANED
$string['qtypeveryshort'] = 'Т'; // ORPHANED
$string['questionname'] = 'Назив питања'; // ORPHANED
$string['questionsaveerror'] = 'У току покушаја да се сачува питање  ($a) појавила се грешка'; // ORPHANED
$string['questiontype'] = 'Тип питања'; // ORPHANED
$string['saveflags'] = 'Сачувај стање индиткатора (заставица)'; // ORPHANED
$string['selectacategory'] = 'Изабери категорију'; // ORPHANED
$string['selectaqtypefordescription'] = 'Изабери тип питања да би видео његов опис'; // ORPHANED
$string['wrongprefix'] = 'Погрешно форматиран nameprefix $a'; // ORPHANED
$string['cannotinsertquestioncate'] = 'Није могуће убацити нову категорију питања: $a'; // ORPHANED
$string['cannotmovecate'] = 'Није могуће преместити категорију $a. У овом контексту то је посњедња категорија.'; // ORPHANED
$string['cannotmovefromto'] = 'Није могуће преместити категорију $a[0] у $a[1]'; // ORPHANED
$string['cannotsavequiz'] = 'Текући покушај теста није сачуван!'; // ORPHANED
$string['cannotupdatecate'] = 'Није могуће ажурирати категорију $a'; // ORPHANED
$string['cannotupdatequestion'] = 'Није могуће ажурирати питање!'; // ORPHANED
$string['cannotupdatequestionver'] = 'Није могуће ажурирати поље за верзију питања'; // ORPHANED
$string['cannotupdaterandomqname'] = 'Није могуће ажурирати насумични назив питања'; // ORPHANED

?>
