<?PHP // $Id$ 
      // quiz.php - created with Moodle 1.9.9 (Build: 20100609) (2007101590)


$string['1day'] = '1 дан';
$string['1hour'] = '1 сат';
$string['2hours'] = '2 сата';
$string['30minutes'] = '30 минута';
$string['6hours'] = '6 сати';
$string['acceptederror'] = 'Прихваћена грешка';
$string['action'] = 'Акција';
$string['adaptive'] = 'Адаптивни режим';
$string['addcategory'] = 'Додаj категорију';
$string['addingcalculated'] = 'Додавање израчунатих питања';
$string['addingdescription'] = 'Додавање описа';
$string['addingessay'] = 'Додавање есеја';
$string['addingmatch'] = 'Додавање питања са спаривањем';
$string['addingmultianswer'] = 'Додавање уметнутих одговора';
$string['addingmultichoice'] = 'Додавање питања са вишеструким одабирима';
$string['addingnumerical'] = 'Додавање нумеричког питања';
$string['addingquestion'] = 'Додавање питања';
$string['addingquestions'] = 'На овом делу странице уређујете своју базу питања. Питања су сачувана по категоријама како би се што лакше организовала, и могу бити употребљена у било ком тесту унутар Вашег курса или неког другог курса ако одаберете опцију \'објављивања\' питања. <br /><br />
Након што одаберете одређену категорију питања, можете креирати нова или уређивати већ постојећа питања. Можете означити било које од тих питања и додати га (их) у Ваш тест који се налази с леве стране екрана.';
$string['addingrandom'] = 'Додавање насумичног одабраног питања';
$string['addingrandomsamatch'] = 'Додавање насумичног одабраног питања типа спаривање кратких одговора';
$string['addingshortanswer'] = 'Додавање питања типа Кратак одговор';
$string['addingtruefalse'] = 'Додавање тачно/нетачних питања';
$string['addmoreoverallfeedbacks'] = 'Додај {no} још поља за повратне информације';
$string['addquestions'] = 'Додаj питања';
$string['addquestionstoquiz'] = 'Додај питања у текући тест';
$string['addrandom'] = 'Додај $a случајних питања';
$string['addrandom1'] = '<< Додај';
$string['addrandom2'] = 'случајна питања';
$string['addselectedtoquiz'] = 'Додај одабрано у тест';
$string['addtoquiz'] = 'Додај у тест';
$string['affectedstudents'] = 'Утицало је на $a';
$string['aiken'] = 'Aiken формат';
$string['allattempts'] = 'Сви покушаји';
$string['allinone'] = 'Неограничено';
$string['allowreview'] = 'Дозволи преглед';
$string['alreadysubmitted'] = 'Вероватно сте већ предали тест.';
$string['alternativeunits'] = 'Алтернативне јединице';
$string['alwaysavailable'] = 'Увек доступно';
$string['analysisoptions'] = 'Опције анализе';
$string['analysistitle'] = 'Табела анализе ставки';
$string['answer'] = 'Одговор';
$string['answerhowmany'] = 'Један или више тачних одговора?';
$string['answers'] = 'Одговори';
$string['answersingleno'] = 'Дозвољено је више тачних одговора';
$string['answersingleyes'] = 'Само један одговор је тачан';
$string['answerswithacceptederrormarginmustbenumeric'] = 'Одговори са прихваћеном грешком морају бити нумерички';
$string['answertoolong'] = 'Одговор је предугачак након линије $a (макс. 255 знакова)';
$string['aon'] = 'AON формат';
$string['attempt'] = 'Покушај број $a';
$string['attemptduration'] = 'Утрошено време';
$string['attemptedon'] = 'Датум предаје теста';
$string['attemptfirst'] = 'Први покушај';
$string['attemptincomplete'] = 'Овај покушај (корисника: $a) још није завршен.';
$string['attemptlast'] = 'Последњи покушај';
$string['attemptquiznow'] = 'Започни тест';
$string['attempts'] = 'Покушаји';
$string['attemptsallowed'] = 'Дозвољен број покушаја';
$string['attemptsdeleted'] = 'Број избрисаних покушаја';
$string['attemptselection'] = 'Изаберите које покушаје треба анализирати по кориснику:';
$string['attemptsexist'] = 'Тест је већ у употреби, не можете више додавати или брисати питања.';
$string['attemptsnum'] = 'Поукашаји: $a';
$string['attemptsnumthisgroup'] = 'Покушаји: $a->total ($a->group оз ове групе)';
$string['attemptsnumyourgroups'] = 'Покушаји: $a->total ($a->group из ваше групе)';
$string['attemptsonly'] = 'Прикажи само студената са покушајима';
$string['attemptsunlimited'] = 'Неограничен број покушаја';
$string['back'] = 'Назад на преглед питања';
$string['backtoquestionlist'] = 'Назад на листу питања';
$string['backtoquiz'] = 'Назад на уређивање теста';
$string['bestgrade'] = 'Највиша оцена';
$string['blackboard'] = 'Blackboard';
$string['blackboard_6'] = 'Blackboard V6+';
$string['bothattempts'] = 'Прикажи студенте са и без покушаја';
$string['braceerror'] = 'Нису пронађене {...} око одговора';
$string['browsersecurity'] = 'Безбедност веб читача';
$string['calculated'] = 'Рачунско';
$string['calculatedquestion'] = 'Рачунско питање није подржано на линији $a. Ово питање ће бити игнорисано.';
$string['cannotcreatepath'] = 'Не може се креирати путања ($a)';
$string['cannoteditafterattempts'] = 'Не можете да додате или уклоните питања због тога што постоје покушаји.';
$string['cannotinsert'] = 'Не може се уметнути питање';
$string['cannotopen'] = 'Не може се отворити извозна датотека ($a)';
$string['cannotread'] = 'Не може се читати увозна датотека (или је празна)';
$string['cannotwrite'] = 'Не може се уписивати у извозну датотеку ($a)';
$string['caseno'] = 'Не треба водити рачуна о малим и великим словима';
$string['casesensitive'] = 'Вођење рачуна о малим и великим словима';
$string['caseyes'] = 'Да, морају се поклапати чак и мала и велика слова';
$string['categories'] = 'Категорије';
$string['category'] = 'Категорија';
$string['categoryadded'] = 'Категорија \'$a\' је додата';
$string['categorydeleted'] = 'Категорија \'$a\' је обрисана';
$string['categoryinfo'] = 'Информације о категорији';
$string['categorymove'] = 'Категорија \'$a->name\' садржи $a->count питања.  (нека од њих могу бити стара, скривена или питања која се и даље користе у постојећим тестовима).<br /> Одаберите другу категорију у коју ћете их преместити.';
$string['categorymoveto'] = 'Премести их у ову категорију';
$string['categorynamecantbeblank'] = 'Назив категорије не може остати непопуњен.';
$string['categorynoedit'] = 'Немате овлашћења за мењање категорије \'$a\'.';
$string['categoryupdated'] = 'Категорија је успешно измењена';
$string['changessaved'] = 'Промене у оцењивању су сачуване';
$string['changessavedwitherrors'] = 'Дошло је до неких грешака при чувању промена у оцењивању';
$string['checkanswer'] = 'Провери';
$string['choice'] = 'Избор';
$string['choices'] = 'Доступни избори';
$string['choosedatasetproperties'] = 'Изабери особине сета података';
$string['choosefile'] = 'Одаберите датотеку';
$string['close'] = 'Затвори прозор';
$string['closebeforeopen'] = 'Није могуће ажурирати тест. Одредили сте датум затварања пре датума отварања.';
$string['closepreview'] = 'Затвори преглед';
$string['closereview'] = 'Затвори преглед';
$string['comment'] = 'Коментар';
$string['commentorgrade'] = 'Коментаришите или променните оцену';
$string['comments'] = 'Коментари';
$string['completedon'] = 'Завршено дана';
$string['confirmclose'] = 'Спремни сте да завршите овај тест. Једном када завршите тест нећете више бити у могућности да мењате своје одговоре.';
$string['confirmserverdelete'] = 'Да ли сте сигурни да желите да уклоните сервер <b>$a</b> са списка?';
$string['confirmstartattemptlimit'] = 'Овај тест је ограничен на $a покушаја. Приступ тесту ће се рачунати као покушај. Да ли желите да наставите?';
$string['confirmstartattempttimelimit'] = 'Тест има временско ограничење, а могуће га је радити $a пут(а). Сваки приступ тесту се рачуна као покушај његовог решавања. Да ли желите да наставите?';
$string['confirmstarttimelimit'] = 'Тест је временски ограничен. Да ли сте сигурни да желите да почнете?';
$string['containercategorycreated'] = 'Ова категорија је креирана са циљем да се у њу сместе све оригиналне категорије које се помере на ниво сајта из доле наведених разлога.';
$string['continueattemptquiz'] = 'Наставите последњи покушај';
$string['continuepreview'] = 'Настави последњи преглед';
$string['copyingfrom'] = 'Креирање копије питања \'$a\'';
$string['copyingquestion'] = 'Копирање питања';
$string['correct'] = 'Тачно';
$string['correctanswer'] = 'Тачан одговор';
$string['correctanswerformula'] = 'Формула тачних одговора';
$string['correctansweris'] = 'Тачан одговор: $a';
$string['correctanswerlength'] = 'Значајне цифре';
$string['correctanswers'] = 'Тачни одговори';
$string['correctanswershows'] = 'Приказ тачних одговора';
$string['corrresp'] = 'Тачан одзив система';
$string['countdown'] = 'Бројач';
$string['countdownfinished'] = 'Тест се ускоро затвара, време је да предате своје одговоре.';
$string['countdowntenminutes'] = 'Тест се затвара за десет минута.';
$string['coursetestmanager'] = 'Тест Менаџер формат';
$string['createfirst'] = 'Морате прво креирати нека питања са кратким одговорима.';
$string['createmultiple'] = 'Додајте тесту неколико случајних питања';
$string['createnewquestion'] = 'Креирај ново питање';
$string['custom'] = 'Произвољан формат';
$string['dataitemneed'] = 'Морате додати бар један скуп ставки података да бисте добили валидно питање';
$string['datasetdefinitions'] = 'Поново употребљене дефиниције сета података за категорију $a';
$string['datasetnumber'] = 'Број';
$string['daysavailable'] = 'Доступни дани';
$string['decimaldigits'] = 'Број децимала у оценама';
$string['decimalformat'] = 'децимале';
$string['decimalpoints'] = 'Децимална места';
$string['decimals'] = 'са $a';
$string['default'] = 'Подразумевано';
$string['defaultgrade'] = 'Подразумевана оцена питања';
$string['defaultinfo'] = 'Подразумевана категорија за питања';
$string['delay1'] = 'Временски размак између првог и другог покушаја';
$string['delay2'] = 'Временски размак између свих осталих покушаја';
$string['deleteattemptcheck'] = 'Да ли сте апсолутно сигурни да желите да обришете ове покушаје?';
$string['deletequestioncheck'] = 'Јесте ли у потпуности сигурни да желите да обришете \'$a\'?';
$string['deletequestionscheck'] = 'Јесте ли у потпуности сигурни да желите да обришете следећа питања? <div>$a</div>';
$string['deleteselected'] = 'Обриши означено';
$string['deletingquestionattempts'] = 'Обриши покушаје питања';
$string['description'] = 'Опис';
$string['discrimination'] = 'Индекс дискриминативности';
$string['displayoptions'] = 'Опције за приказ';
$string['download'] = 'Кликните за преузимање извезене датотеке са категоријама';
$string['downloadextra'] = '(датотека се чува и међу датотекама курса у /backupdata/quiz директоријуму)';
$string['duplicateresponse'] = 'Ово предато решење је игнорисано јер сте већ раније дали еквивалентан одговор.';
$string['eachattemptbuildsonthelast'] = 'Сваки покушај се наставља на претходни';
$string['editcategories'] = 'Уређивање категорија';
$string['editcategory'] = 'Уређивање категорије';
$string['editcatquestions'] = 'Уређивање питања у категорији';
$string['editdatasets'] = 'Уређивање сета података';
$string['editingcalculated'] = 'Уређивање рачунског питања';
$string['editingdescription'] = 'Уређивање описа';
$string['editingessay'] = 'Уређивање питања на које се тражи одговор у виду есеја';
$string['editingmatch'] = 'Уређивање питања са спаривањем одговора';
$string['editingmultianswer'] = 'Уређивање уметнутих одговора (затвореног питања)';
$string['editingmultichoice'] = 'Уређивање питања вишеструког избора';
$string['editingnumerical'] = 'Уређивање нумеричког питања';
$string['editingquestion'] = 'Уређивање питања';
$string['editingquiz'] = 'Уређивање теста';
$string['editingrandom'] = 'Уређивање насумично одабраног питања';
$string['editingrandomsamatch'] = 'Уређивање случајног питања са спаривањем кратких одговора';
$string['editingrqp'] = '$a: уређивање питања';
$string['editingshortanswer'] = 'Уређивање питања са кратким одговором';
$string['editingtruefalse'] = 'Уређивање Тачно/Нетачно питања';
$string['editqcats'] = 'Уређивање категорија питања';
$string['editquestions'] = 'Уређивање питања';
$string['editquiz'] = 'Уређивање теста';
$string['editquizquestions'] = 'Уређивање питања теста';
$string['emailconfirmbody'] = 'Драги $a->username,

Хвала за прослеђивање Ваших одговора на \'$a->quizname\'
у оквиру курса \'$a->coursename\'
у $a->submissiontime.

Овај email потврђује да смо безбедно примили Вање одговоре.

Можете оценити овај тест на $a->quizurl.';
$string['emailconfirmsubject'] = 'Потврда предавања теста: $a->quizname';
$string['emailnotifybody'] = 'Драги $a->username,

$a->studentname је завршио тест \'$a->quizname\' ($a->quizurl)
у оквиру курса \'$a->coursename\'.

Можете прегледати овај покушај на  $a->quizreviewurl.';
$string['emailnotifysubject'] = '$a->studentname је завршио тест $a->quizname';
$string['errorinquestion'] = 'Грешка у питању';
$string['errormissingquestion'] = 'Грешка: Систем не може да пронађе питање чији је идентификатор $a';
$string['errornotnumbers'] = 'Грешка - одговори морају бити нумерички';
$string['errorsdetected'] = 'Број нађених грешака: $a';
$string['essay'] = 'Есеј';
$string['essayquestions'] = 'Питања';
$string['event1'] = 'Аутоматско чување';
$string['event2'] = 'Сачувај';
$string['event3'] = 'Оцена';
$string['event5'] = 'Провери';
$string['event6'] = 'Затвори';
$string['event7'] = 'Предај';
$string['event8'] = 'Затвори';
$string['event9'] = 'Оцени ручно';
$string['examview'] = 'Преглед теста';
$string['export'] = 'Извоз';
$string['exportcategory'] = 'извези категорију';
$string['exporterror'] = 'Дошло је до грешке приликом процесирања извоза';
$string['exportfilename'] = 'тест';
$string['exportingquestions'] = 'Питања се извозе у датотеку';
$string['exportname'] = 'Назив датотеке';
$string['exportnameformat'] = '%%d.%%m.%%Y.-%%H.%%M';
$string['exportquestions'] = 'Извези питања у датотеку';
$string['false'] = 'Погрешно';
$string['feedback'] = 'Повратне информације';
$string['feedbackerrorboundaryformat'] = 'Ограничења оцењивања повратних информација морају бити или процентуалне или нумеричке. Вредност коју сте унели ограничена са $a није подржана.';
$string['feedbackerrorboundaryoutofrange'] = 'Ограничења оцењивања повратних информација морају бити између 0%% и 100%%. Вредност коју сте унели ограничена са $a је ван дозвољеног опсега.';
$string['feedbackerrorjunkinboundary'] = 'Морате попунити поља са ограничењима оцењивања повратних информација, без остављања било каквих празнина.';
$string['feedbackerrorjunkinfeedback'] = 'Морате попунити поља повратних информација, без остављања било каквих празнина.';
$string['feedbackerrororder'] = 'Границе оцењивања повратних информација морају бити сортиране, почевши од највише. Вредност коју сте унели ограничена са $a није у добром поретку.';
$string['file'] = 'Датотека';
$string['fileformat'] = 'Формат датотеке';
$string['fillcorrect'] = 'Унесите тачан одговор';
$string['filloutnumericalanswer'] = 'Обезбедите бар један могући одговор и толеранцију. Први одговарајући одговор биће коришћен за утврђивање резултата и повратних информација. Ако ставите на располагање неке повратне информације без одговора на крају, оне ће бити приказане студентима чији се одговори не поклапају ни са једним од осталих одговора.';
$string['filloutoneanswer'] = 'Морате испунити бар један од могућих одговора. Празни одговори се неће користити. \'*\' се може користити као џокер знак који одговара свим знаковима. Први одговор који се уклопи се користи за утврђивање разултата и повратних информација.';
$string['filloutthreequestions'] = 'Морате испунити бар три питања са одговарајућим решењима. Можете додати још нетачних одговора давањем решења уз празна питања. Ставке у којима су и питање и одговор празни неће се узимати у обзир.';
$string['fillouttwochoices'] = 'Морате испунити бар два одговора. Празни одговори се неће користити.';
$string['finishattempt'] = 'Предај све одговоре и заврши тест';
$string['finishreview'] = 'Заврши преглед';
$string['forceregeneration'] = 'Обавезно обнављање';
$string['formatnotfound'] = 'Није пронађен формат $a за увоз/извоз';
$string['formatnotimplemented'] = 'Овај формат није исправно имплементиран, молимо поднесите извештај о грешци';
$string['fractionsaddwrong'] = 'Позитивне оцене које сте одабрали у збиру не дају 100%%<br />Наиме њихов збир је $a%%<br />Да ли желите да се вратите назад и исправите питање?';
$string['fractionsnomax'] = 'Један од одговора би требао носити 100%% оцене, тако да је <br />могуће добити максималну оцену за ово питање.<br />Да ли желите да се вратите назад и исправите питање?';
$string['fromfile'] = 'из датотеке:';
$string['functiontakesatleasttwo'] = 'Функција $a мора имати најмање два аргумента';
$string['functiontakesnoargs'] = 'Функција $a не употребљава ниједан аргумент';
$string['functiontakesonearg'] = 'Функција $a мора имати тачно један аргумент';
$string['functiontakesoneortwoargs'] = 'Функција $a мора имати или један или два аргумента';
$string['functiontakestwoargs'] = 'Функција $a мора имати тачно два аргумента';
$string['generalfeedback'] = 'Опште повратне информације';
$string['generatevalue'] = 'Генериши нову вредност између';
$string['geometric'] = 'Геометријски';
$string['gift'] = 'GIFT формат';
$string['giftleftbraceerror'] = 'Није пронађен знак {';
$string['giftmatchingformat'] = 'Одговори у питању са спаривањем одговора нису правилно форматирани';
$string['giftnonumericalanswers'] = 'Није пронађен ниједан одговор за нумеричко питање';
$string['giftnovalidquestion'] = 'Није пронађен ниједан исправан одговор';
$string['giftqtypenotset'] = 'Није подешен тип питања';
$string['giftrightbraceerror'] = 'Није пронађен знак }';
$string['grade'] = 'Оцена';
$string['gradeall'] = 'Оцени све';
$string['gradeaverage'] = 'Просечна оцена';
$string['gradeboundary'] = 'Ограничење оцене';
$string['gradeessays'] = 'Оцени есеје';
$string['gradehighest'] = 'Највиша оцена';
$string['grademethod'] = 'Метод оцењивања';
$string['gradesdeleted'] = 'Избрисано оцена теста:';
$string['gradesofar'] = '$a->method: $a->mygrade / $a->quizgrade.';
$string['gradingdetails'] = 'Оцена за овај одговор је: $a->raw/$a->max.';
$string['gradingdetailsadjustment'] = 'Са претходним казненим бодовима оцена је <strong>$a->cur/$a->max</strong>.';
$string['gradingdetailspenalty'] = 'Овим одговором сте зарадили $a казнених бодова.';
$string['gradingdetailszeropenalty'] = 'Нисте зарадили казнене бодове за овај одговор';
$string['guestsno'] = 'Нажалост, гости не могу ни да виде ни да решавају тестове';
$string['history'] = 'Историјат одзива система';
$string['hotpot'] = 'Hot Potatoes формат';
$string['illegalformulasyntax'] = 'Неподржана синтакса формуле почевши од \'$a\'';
$string['imagedisplay'] = 'Слика за приказ';
$string['imagemissing'] = 'Слика није расположива у линији $a. Име датотеке биће игнорисано';
$string['import'] = 'Увоз';
$string['importcategory'] = 'категорија увоза';
$string['importerror'] = 'Дошло је до грешке приликом процесирања увоза';
$string['importerrorquestion'] = 'Грешка при увозу питања';
$string['importfilearea'] = 'Увоз из датотеке која је већ међу датотекама курса';
$string['importfileupload'] = 'Увоз из новоучитане датотеке...';
$string['importfromthisfile'] = 'Увоз из ове датотеке';
$string['importingquestions'] = 'Увоз $a питања из датотеке';
$string['importmax10error'] = 'Постоји грешка у питању. Не може бити више од десет одговора';
$string['importmaxerror'] = 'Постоји грешка у питању. Има превише одговора.';
$string['importminerror'] = 'Постоји грешка у питању. Нема довољно понуђених одговора за овај тип питања';
$string['importparseerror'] = 'Пронађена је грешка у току парсирања увезене датотеке. Ниједно питање није увезено. Да би сте увезли она питања која су добра подесите опцију \'Стани при појави грешке\' на \'Не\'';
$string['importquestions'] = 'Увоз питања из датотеке';
$string['incorrect'] = 'Нетачно';
$string['indivresp'] = 'Одговори појединаца на сваку ставку';
$string['info'] = 'Информације';
$string['introduction'] = 'Увод';
$string['invalidcategory'] = 'Идентификатор категорије није ваљан';
$string['invalidnumericanswer'] = 'Један од одговора који сте унели није исправан број.';
$string['invalidnumerictolerance'] = 'Једна од толеранција који сте унели није исправан број.';
$string['invalidsource'] = 'Извор није прихваћен као валидан.';
$string['invalidsourcetype'] = 'Није валидан тип извора';
$string['itemanal'] = 'Анализа одзива система за ставке';
$string['itemdefinition'] = 'Дефиниција';
$string['itemsource'] = 'Извор ставке';
$string['itemsourceformat'] = 'Формат извора ставке';
$string['itemtypes'] = 'Врсте удаљених питања';
$string['lastanswer'] = 'Ваш одговор је био';
$string['learnwise'] = 'Learnwise формат';
$string['link'] = 'Линк';
$string['listitems'] = 'Листа ставки у тесту';
$string['literal'] = 'Знак';
$string['loguniform'] = 'цифре, из loguniform дистрибуције';
$string['makecopy'] = 'Сачувај као ново питање';
$string['managetypes'] = 'Управљање типовима питања и серверима';
$string['manualgrading'] = 'Оцењивање';
$string['mark'] = 'Предајте';
$string['markall'] = 'Предајте страницу';
$string['marks'] = 'Оцене';
$string['match'] = 'Спаривање';
$string['matchanswer'] = 'Спаривање одговора';
$string['matchanswerno'] = 'Спаривање одговора $a';
$string['matcherror'] = 'Оцене се не слажу са опцијама за оцењивање - питање је прескочено';
$string['matchgrades'] = 'Спаривање оцена';
$string['matchgradeserror'] = 'Грешка ако оцена није наведена';
$string['matchgradesnearest'] = 'Најближа оцена ако није наведена';
$string['max'] = 'Максимално';
$string['min'] = 'Минимално';
$string['minutes'] = 'Минут(а)';
$string['missinganswer'] = 'Премало :ОДГОВОР, :Lx, :Rx стања за линију $a овог питања. Морате дефинисати најмање 2 могућа одговора';
$string['missingcorrectanswer'] = 'Морате задати тачан одговор';
$string['missingformula'] = 'Недостаје формула';
$string['missingitemtypename'] = 'Недостаје назив';
$string['missingname'] = 'Недостаје назив питања';
$string['missingquestion'] = 'Недостаје назив питања након линије $a';
$string['missingquestiontext'] = 'Недостаје текст питања';
$string['missingword'] = 'Недостаје формат речи';
$string['modulename'] = 'Тест';
$string['modulenameplural'] = 'Тестови';
$string['moveto'] = 'Премести у >>';
$string['multianswer'] = 'Уметнути одговори (Затворено питање)';
$string['multichoice'] = 'Вишеструки избор';
$string['multipleanswers'] = 'Одаберите бар један одговор.';
$string['multiplier'] = 'Множитељ';
$string['name'] = 'Назив';
$string['newattemptfail'] = 'Грешка: Није било могуће започети нови покушај решавања теста';
$string['noanswers'] = 'Ниједан одговор није одабран!';
$string['noattempts'] = 'Није било покушаја да се реши овај тест';
$string['noattemptstoshow'] = 'Нема покушаја за приказ';
$string['nocategory'] = 'Погрешна или неспецифицирана категорија';
$string['nocommentsyet'] = 'Још нема коментара';
$string['noconnection'] = 'Тренутно није успостављена веза са веб сервисом који може да обради ово питање. Молимо контактирајте свог администратора';
$string['nodataset'] = 'ништа - није џокер знак';
$string['noessayquestionsfound'] = 'Нису пронађена питања која се ручно оцењују';
$string['nogradewarning'] = 'Овај тест се не оцењује, тако да не можете да подесите свеобухватну повратну информацију.';
$string['nomatchinganswer'] = 'Морате навести тачан одговор за питање \'$a\'.';
$string['nominal'] = 'Номиналан';
$string['nomoreattempts'] = 'Немате више право да покушавате да решите тест';
$string['none'] = 'Нема';
$string['nopossibledatasets'] = 'Нема могућих скупова података';
$string['noquestionintext'] = 'Текст питања не садржи уметнута питања';
$string['noquestions'] = 'Ниједно питање још није додато';
$string['noquestionsfound'] = 'Нема питања';
$string['noquestionsinfile'] = 'Нема питања у датотеци одабраној за увоз';
$string['noresponse'] = 'Без одзива система';
$string['noreview'] = 'Није Вам дозвољен преглед овог теста';
$string['noreviewuntil'] = 'Није Вам дозвољен преглед овог теста до $a';
$string['noscript'] = 'JavaScript мора бити омогућен да бисте наставили даље!';
$string['notavailable'] = 'Нажалост, овај тест није још расположив';
$string['notavailabletostudents'] = 'Напомена: Овај тест није још доступан Вашим студентима.';
$string['notenoughanswers'] = 'Овај тип питања захтева бар $a одговора';
$string['notenoughsubquestions'] = 'Није дефинисано довољно потпитања!<br />Да ли желите да се вратите назад и исправите питање?';
$string['notimedependentitems'] = 'Модул за тестове тренутно не подржава временски ограничена питања. Подесите временко ограничење за читав тест. Да ли желите да изаберете друго питање (или да ипак употребите тренутно питање)?';
$string['numattempts'] = '$a->studentnum $a->studentstring су начинили $a->attemptnum покушаја';
$string['numattemptsmade'] = '$a учињених покушаја решавања овог теста';
$string['numberabbr'] = '#';
$string['numerical'] = 'Нумеричко';
$string['onlyteachersexport'] = 'Само предавачи могу да извозе питања';
$string['onlyteachersimport'] = 'Само предавачи са правима уређивања могу да увозе питања';
$string['openclosedatesupdated'] = 'Ажурирани су датуми отварања и затварања теста';
$string['optional'] = 'опционо';
$string['outof'] = '$a->grade од максималних $a->maxgrade';
$string['outofpercent'] = '$a->grade од максимума $a->maxgrade ($a->percent%%)';
$string['outofshort'] = '$a->grade/$a->maxgrade';
$string['overallfeedback'] = 'Свеобухватне повратне информације';
$string['overdue'] = 'Закаснели';
$string['pagesize'] = 'Број покушаја приказаних по страници:';
$string['paragraphquestion'] = 'Параграф питање није подржано у линији $a. Питање ће бити игнорисано.';
$string['parent'] = 'Надређени';
$string['parsingquestions'] = 'Парсирање питања из увозне датотеке.';
$string['partiallycorrect'] = 'Делимично тачно';
$string['passworderror'] = 'Унета лозинка је погрешна';
$string['penalty'] = 'Казнени бодови';
$string['penaltyfactor'] = 'Казнени фактор';
$string['penaltyscheme'] = 'Примени казнене поене';
$string['percentcorrect'] = 'Проценат тачности';
$string['pleaseclose'] = 'Ваш захтев је прослеђен. Можете да затворите прозор';
$string['popup'] = 'Прикажи тест у \'сигурном\' прозору';
$string['popupblockerwarning'] = 'Овај део теста се ради у безбедном моду, што значи да морате решавати тест у безбедном прозору. Молимо искључите све алате за спречавање појаве искачућих прозора. Хвала.';
$string['popupnotice'] = 'Студенти ће видети тест у \'сигурном\' прозору';
$string['popupwithjavascriptsupport'] = 'Искачући прозор на целом екрану са нешто безбедности JavaScript-а';
$string['preview'] = 'Преглед';
$string['previewquestion'] = 'Преглед питања';
$string['previewquiz'] = 'Прегледај $a';
$string['previewquiznow'] = 'Прегледај тест сада';
$string['previous'] = 'Претходно стање';
$string['publish'] = 'Објави';
$string['publishedit'] = 'Да би сте додали или уредили питања у овој категорији морате имати одговарајуће право приступа';
$string['qti'] = 'IMS QTI формат';
$string['qti2'] = 'IMS QTI 2.0 формат';
$string['question'] = 'Питање';
$string['questioncats'] = 'Категорије питања';
$string['questiondeleted'] = 'Ово питање је обрисано. Молимо контактирајте свог предавача.';
$string['questioninuse'] = 'Питање \'$a->questionname\' се тренутно користи у <br />$a->quiznames<br />Питање неће бити обрисано из ових тестова, већ само са списка категорије.';
$string['questionname'] = 'Назив питања';
$string['questionnametoolong'] = 'Назив питања је предугачак у линији $a (максимум je 255 карактера). Назив је зато скраћен.';
$string['questionno'] = 'Питање $a';
$string['questions'] = 'Питања';
$string['questionsinclhidden'] = 'Питања (укључујући и скривена)';
$string['questionsinthisquiz'] = 'Питања у овом тесту';
$string['questionsinuse'] = '(* Питања означена звездицом се већ користе у неким тестовима. Та питања неће бити обрисана из тих тестова већ само са списка категорије.)';
$string['questionsperpage'] = 'Број питања по страници';
$string['questiontext'] = 'Текст питања';
$string['questiontype'] = 'Тип питања $a';
$string['questiontypesetupoptions'] = 'Опције подешавања за типове питања:';
$string['quiz:attempt'] = 'Покушај решавања тестова';
$string['quiz:deleteattempts'] = 'Брисање покушаја решавања тестова';
$string['quiz:emailconfirmsubmission'] = 'Пошаљи потврду о предаји теста електронском поштом';
$string['quiz:emailnotifysubmission'] = 'Пошаљи обавештење о предатим тестовима електронском поштом';
$string['quiz:grade'] = 'Преглед тестова';
$string['quiz:ignoretimelimits'] = 'Игнорише временска ограничења тестова';
$string['quiz:manage'] = 'Управљање тестовима';
$string['quiz:preview'] = 'Преглед тестова';
$string['quiz:reviewmyattempts'] = 'Прегледај сопствене покушаје';
$string['quiz:view'] = 'Преглед информација о тесту';
$string['quiz:viewreports'] = 'Преглед извештаја о тесту';
$string['quizavailable'] = 'Тест је доступан до: $a';
$string['quizclose'] = 'Затворите тест';
$string['quizclosed'] = 'Тест је затворен дана $a';
$string['quizcloses'] = 'Тест се затвара';
$string['quizcloseson'] = 'Овај тест се затвара $a';
$string['quiznotavailable'] = 'Тест неће бити доступан до: $a';
$string['quizopen'] = 'Отворите тест';
$string['quizopens'] = 'Тест се отвара дана';
$string['quizsettings'] = 'Подешавања теста';
$string['quiztimelimit'] = 'Временско ограничење: $a';
$string['quiztimer'] = 'Штоперица';
$string['random'] = 'Случајно питање';
$string['randomcreate'] = 'Креирај случајна питања';
$string['randomsamatch'] = 'Случајна питања са спаривањем кратких одговора';
$string['randomsamatchcreate'] = 'Направите случајна питања са спаривањем кратких одговора';
$string['randomsamatchintro'] = 'За свако од наведених питања, изаберите одговарајући одговор из менија.';
$string['randomsamatchnumber'] = 'Број питања за избор';
$string['readytosend'] = 'Управо ћете послати своје решење теста на оцењивање. Да ли сте сигурни да желите да наставите?';
$string['reattemptquiz'] = 'Поновни покушај решавања теста';
$string['recentlyaddedquestion'] = 'Недавно додато питање!';
$string['recurse'] = 'Прикажи и питања из подкатегорија';
$string['regrade'] = 'Поново оцени све покушаје';
$string['regradecomplete'] = 'Сви покушаји су поново оцењени';
$string['regradecount'] = '$a->changed од укупно $a->attempt оцена је промењено';
$string['regradedisplayexplanation'] = 'Покушаји који се мењају током поновног оцењивања се приказују као линкови на прозор за преглед питања';
$string['regradenotallowed'] = 'Немате дозволу за поновно оцењивање овог теста';
$string['regradingquestion'] = 'Поновно оцењивање \"$a\".';
$string['regradingquiz'] = 'Поновно оцењивање теста \"$a\"';
$string['relative'] = 'Релативно';
$string['remove'] = 'Уклони';
$string['removeallquizattempts'] = 'Уклони све покушаје теста';
$string['rename'] = 'Преименуј';
$string['renderingserverconnectfailed'] = 'Сервер $a није успео да обради RQP захтев. Проверите да ли је URL адреса тачна.';
$string['reordertool'] = 'Прикажи алат за реорганизовање';
$string['repaginate'] = 'Реорганизуј странице са $a питања по једној страници';
$string['replace'] = 'Замени';
$string['replacementoptions'] = 'Опције за замењивање';
$string['report'] = 'Извештаји';
$string['reportanalysis'] = 'Анализа ставки';
$string['reportfullstat'] = 'Детаљна статистика';
$string['reportmulti_percent'] = 'Више-процентно';
$string['reportmulti_q_x_student'] = 'Више могућности за студента';
$string['reportmulti_resp'] = 'Индивидуални одзиви система';
$string['reportoverview'] = 'Преглед';
$string['reportregrade'] = 'Поновна оцена покушаја решавања теста';
$string['reportresponses'] = 'Детаљни одзиви система';
$string['reports'] = 'Извештаји';
$string['reportsimplestat'] = 'Проста статистика';
$string['requirepassword'] = 'Неопходна је лозинка';
$string['requirepasswordmessage'] = 'Да бисте приступили решавању овог теста морате знати лозинку теста';
$string['requiresafeexambrowser'] = 'Захтева коришћење Сигурног веб читача за испите';
$string['requiresubnet'] = 'Захтевана мрежна адреса';
$string['response'] = 'Одзив система';
$string['responses'] = 'Одзиви система';
$string['results'] = 'Резултати';
$string['reuseifpossible'] = 'поново искористи претходно уклоњено';
$string['review'] = 'Преглед';
$string['reviewafter'] = 'Дозволити преглед након што се тест затвори';
$string['reviewalways'] = 'Дозволити преглед у било које време';
$string['reviewbefore'] = 'Дозволити преглед док је тест отворен';
$string['reviewclosed'] = 'Након што се тест затвори';
$string['reviewimmediately'] = 'Одмах након покушаја';
$string['reviewnever'] = 'Никад немој дозволити преглед';
$string['reviewofattempt'] = 'Преглед покушаја $a';
$string['reviewofpreview'] = 'Преглед приказа';
$string['reviewopen'] = 'Касније, док је тест још увек отворен';
$string['reviewoptions'] = 'Студенти могу да прегледају';
$string['reviewoptionsheading'] = 'Опције за преглед';
$string['reviewresponse'] = 'Преглед одзива система';
$string['reviewresponsetoq'] = 'Прегледај одговоре (питање $a)';
$string['rqp'] = 'Удаљено питање';
$string['rqps'] = 'Удаљена питања';
$string['safebrowsererror'] = 'Овај тест је подешен тако да се његово решавање може покушати само коришћењем Сигурног веб читача за испите. Не можете му приступити из овог веб читача.';
$string['safebrowsernotice'] = 'Овај тест је тако подешен да му студенти могу приступити само ако користе Сигурни веб читач за испите.';
$string['save'] = 'Сачувај';
$string['saveandedit'] = 'Сачувај промене и уреди питања';
$string['savedfromdeletedcourse'] = 'Сачувано са курса \"$a\" који је обрисан';
$string['savegrades'] = 'Сачувај оцене';
$string['savemyanswers'] = 'Сачувај моје одговоре';
$string['savenosubmit'] = 'Сачувај без предавања';
$string['savequiz'] = 'Сачувај цео тест';
$string['score'] = 'Необрађени резултат';
$string['scores'] = 'Резултати';
$string['select'] = 'Селектуј';
$string['selectall'] = 'Селектуј све';
$string['selectcategoryabove'] = 'Изаберите категорију од горе наведених';
$string['selectedattempts'] = 'Изабрани покушаји...';
$string['selectnone'] = 'Деселектуј све';
$string['serveradded'] = 'Сервер је додат';
$string['serveridentifier'] = 'Идентификатор';
$string['serverinfo'] = 'Информације о серверу';
$string['serverinuse'] = 'Сервер који се спремате да обришете је последњи $a сервер и уколико га обришете остаће питања које неће моћи више да се користе';
$string['servers'] = 'Сервери';
$string['serverurl'] = 'URL сервера';
$string['shortanswer'] = 'Питање са кратким одговором';
$string['show'] = 'Прикажи';
$string['showall'] = 'Прикажи сва питања на једној страници';
$string['showbreaks'] = 'Прикажи прекиде између страница';
$string['showcorrectanswer'] = 'Да ли да се уз повратне информације прикажу и тачни одговори?';
$string['showdetailedmarks'] = 'Прикажи детаље оцене';
$string['showfeedback'] = 'Да ли да се прикажу и повратне информације након давања одговора на питања?';
$string['showhidden'] = 'Прикажи и стара питања';
$string['shownoattempts'] = 'Прикажи студенте без покушаја';
$string['shownoattemptsonly'] = 'Прикажи само студенте без покушаја';
$string['showquestiontext'] = 'Прикажи текст питања у листи питања';
$string['showteacherattempts'] = 'Прикажи покушаје предавача да реши тест';
$string['shuffle'] = 'Измешај';
$string['shuffleanswers'] = 'Измешај одговоре';
$string['shufflequestions'] = 'Измешај питања';
$string['shufflewithin'] = 'Измешај у оквиру питања';
$string['significantfigures'] = 'са $a';
$string['significantfiguresformat'] = 'значајне цифре';
$string['singleanswer'] = 'Одаберите један одговор';
$string['sortage'] = 'Сортирај по времену креирања';
$string['sortalpha'] = 'Сортирај по имену';
$string['sortsubmit'] = 'Сортирај питања';
$string['sorttypealpha'] = 'Сортирај по типу, имену';
$string['startagain'] = 'Почни поново';
$string['startedon'] = 'Започето';
$string['stoponerror'] = 'Стани при појави грешке';
$string['subneterror'] = 'Нажалост, овај тест је закључан, односно доступан је само са појединих локација. Тренутно Ваш рачунар није један од оних којима је дозвољено да користе овај тест.';
$string['subnetnotice'] = 'Овом тесту се може приступити само са одређених места. Ваш рачунар се не налази у мрежи са које је приступ дозвољен. Ипак, као предавач свакако можете да прегледате тест.';
$string['substitutedby'] = 'биће замењено са';
$string['summaryofattempts'] = 'Кратак преглед ваших претходних покушаја';
$string['temporaryblocked'] = 'Привремено Вам није дозвољено да поново покушате да решите тест.<br /> Моћи ћете поново да му приступите дана:';
$string['time'] = 'Време';
$string['timecompleted'] = 'Завршено';
$string['timedelay'] = 'Није Вам дозвољено да радите тест јер још није прошао задати размак од Вашег последњег до следећег могућег покушаја решавања другог теста.';
$string['timeleft'] = 'Преостало време';
$string['timelimit'] = 'Временско ограничење';
$string['timelimitexeeded'] = 'Нажалост, време за решавање теста је истекло!';
$string['timelimitmin'] = 'Временско ограничење (у минутима)';
$string['timestr'] = '%%H:%%M:%%S дана %%d.%%m.%%y.';
$string['timesup'] = 'Време је истекло!';
$string['timetaken'] = 'Утрошено време';
$string['tofile'] = 'у датотеку';
$string['tolerance'] = 'Толеранција';
$string['tolerancetype'] = 'Врста толеранције';
$string['toomanyrandom'] = 'Број случајних питања потребних за тест је већи од укупног броја питања расположивих у задатој категорији!';
$string['top'] = 'Највиши ниво';
$string['true'] = 'Тачно';
$string['truefalse'] = 'Тачно/Нетачно';
$string['truefalseimporterror'] = '<b>Упозорење</b>: Питање типа Тачно/Нетачно \'$a->questiontext\' није могло правилно да се увезе. Није било јасно да ли је тачан одговор Тачно или Нетачно. Питање је увезено уз претпоставку да је одговор \'$a->answer\'. Уколико уочите да то није коректно, мораћете додатно уредити питање.';
$string['type'] = 'Тип';
$string['unfinished'] = 'отворено';
$string['ungraded'] = 'Неоцењено';
$string['uniform'] = 'децимале, из униформне дистрибуције';
$string['unit'] = 'Јединица';
$string['unknowntype'] = 'Тип питања који није подржан у линији $a. Ово питање ће бити игнорисано.';
$string['unsupportedformulafunction'] = 'Функција $a није подржана';
$string['unusedcategorydeleted'] = 'Након брисања курса, ова категорија је обрисана, због тога што се питања из ове категорија не користе у тестовима других курсева.';
$string['updatesettings'] = 'Ажурирај подешавања теста';
$string['upgradesure'] = '<div style=\"color: red;\">Тест модул ће извести крупне промене табела са тестовима у бази података. Ова надоградња још увек није довољно тестирана. Пре него што наставите строго Вам препоручујемо да направите резервну копију.</div>';
$string['url'] = 'URL';
$string['usedcategorymoved'] = 'Након брисања курса, ова категорија је сачувана и премештена на ниво сајта, због тога што се питања из ове категорије користе у тестовима других курсева.';
$string['validate'] = 'Провери';
$string['viewallanswers'] = 'Приказ $a покушаја решавања теста';
$string['viewallreports'] = 'Погледај извештаје за $a покушаја';
$string['warningmissingtype'] = '<p><b>Ово питање спада у питања типа који још није инсталиран на Вашем Moodle сајту.<br />Молимо упозорите свог адимистратора.</b></p>';
$string['warningsdetected'] = 'Детектовано је $a упозорење(а)';
$string['webct'] = 'WebCT формат';
$string['wheregrade'] = 'Где је моја оцена?';
$string['wildcard'] = 'Џокер знак';
$string['withselected'] = 'Са изабраним';
$string['withsummary'] = 'са статистичким резимеом';
$string['wronggrade'] = 'Погрешна оцена (након линије $a):';
$string['wronguse'] = 'Не можете тако да користите ову страницу';
$string['xhtml'] = 'XHTML формат';
$string['xml'] = 'Moodle XML формат';
$string['xmlimportnoname'] = 'Недостаје назив питања у xml датотеци';
$string['xmlimportnoquestion'] = 'Недостаје текст питања у xml датотеци';
$string['xmltypeunsupported'] = 'Тип питања $a није подржан XML увозом';
$string['youneedtoenrol'] = 'Потребно је да се упишете на овај курс пре него што покушате решавање овог теста';
$string['yourfinalgradeis'] = 'Ваша коначна оцена на овом тесту је $a';
$string['zerosignificantfiguresnotallowed'] = 'Тачан одговор не може имати нула значајних цифара!';
$string['accessnoticesheader'] = 'Можете прегледати овај тест, али ако је ово стварни покушај решавања, бићете блокирани јер:'; // ORPHANED
$string['addaquestion'] = 'Додај питање...'; // ORPHANED
$string['addarandomquestion'] = 'Додај насумично одабрано питање'; // ORPHANED
$string['adddescriptionlabel'] = 'Додај опис/натпис'; // ORPHANED
$string['addnewpagesafterselected'] = 'Додај нове странице после одабраних питања'; // ORPHANED
$string['addnewquestionsqbank'] = 'Додај питања у категорију $a->catname: $a->link'; // ORPHANED
$string['addpagehere'] = 'Додај страницу овде'; // ORPHANED
$string['addquestion'] = 'Додај питање'; // ORPHANED
$string['addrandomfromcategory'] = 'Додај насумично одабрана питања из категорије'; // ORPHANED
$string['addrandomquestion'] = 'Додај насумично одабрана питања'; // ORPHANED
$string['addrandomquestiontoquiz'] = 'Додај насумично одабрана питања у тест $a'; // ORPHANED
$string['aftereachquestion'] = 'Након додавања сваког питања'; // ORPHANED
$string['afternquestions'] = 'Након додавања $a питања'; // ORPHANED
$string['answered'] = 'Одговорено'; // ORPHANED
$string['areyousureremoveselected'] = 'Да ли сте сигурни да желите да обришете сва питања'; // ORPHANED
$string['asshownoneditscreen'] = 'Као што је приказано на страници за уређивање'; // ORPHANED
$string['attemptalreadyclosed'] = 'Овај покушај је већ завршен'; // ORPHANED
$string['attemptclosed'] = 'Покушај још увек није затворен'; // ORPHANED
$string['attempterror'] = 'Тренутно вам није дозвољено да покушате овај тест због  $a'; // ORPHANED
$string['attemptsallowedn'] = 'Дозвољен број покушаја: \$а'; // ORPHANED
$string['basicideasofquiz'] = 'Основне идеје прављења теста'; // ORPHANED
$string['blackboard_six'] = 'Blackboard V6+'; // ORPHANED
$string['cannotfindprevattempt'] = 'Није могуће пронаћи претходни покушај'; // ORPHANED
$string['cannotinsertrandomquestion'] = 'Није било могуће убацити ново насумично одабрано питање'; // ORPHANED
$string['cannotloadquestion'] = 'Није било могуће учитати опције питања'; // ORPHANED
$string['cannotloadtypeinfo'] = 'Није могуће учитати информације везане за тип питања'; // ORPHANED
$string['cannotrestore'] = 'Није било могуће вратити податке за сесије питања'; // ORPHANED
$string['cannotreviewopen'] = 'Не можете да прегледате овај покушај, још увек је отворен'; // ORPHANED
$string['cannotsavelayout'] = 'Није било могуће сачувати'; // ORPHANED
$string['cannotsavenumberofquestion'] = 'Није било могуће сачувати број питања по једно страници'; // ORPHANED
$string['cannotsavequestion'] = 'Не може се сачувати списак питања'; // ORPHANED
$string['cannotsetgrade'] = 'Није било могуће поставити нову максималну оцену за тест'; // ORPHANED
$string['cannotsetsumgrades'] = 'Покушај да се подеси сума оцена није успео'; // ORPHANED
$string['configadaptive'] = 'Уколико изаберете Да ѕа ову опцију онда ће студенту бити дозвољено да више пута одговори на питања чак у оквиру истог покушаја решавања теста.'; // ORPHANED
$string['configattemptsallowed'] = 'Ограничење у броју покушаја који су студентима дозвољени на тесту'; // ORPHANED
$string['configdecimaldigits'] = 'Број цифара након децималне тачке које треба приказати када се показују оцене.'; // ORPHANED
$string['configdecimalplaces'] = 'Број цифара након децималне тачке које треба приказати када се показују оцене за тест.'; // ORPHANED
$string['configdecimalplacesquestion'] = 'Број цифара након децималне тачке које треба приказати када се показују оцене за појединачна потања.'; // ORPHANED
$string['configdelay1'] = 'Уколико подесите временски размак, онда ће студент након првог покушаја морати толико времена да сачека пре него што буде могао поново да покуша да уради тест.'; // ORPHANED
$string['configdelay1st2nd'] = 'Уколико овде подесите временски размак, студенти не могу да други пут ураде тест пре него што не протекне толико времене од њиховог првог покушаја.'; // ORPHANED
$string['configdelay2'] = 'Уколико овде подесите временски размак, онда студент мора да сачека толико времене да прође пре него што започне свој трећи (и сваки наредни) покушај решавања теста.'; // ORPHANED
$string['configdelaylater'] = 'Уколико овде подесите временски размак, онда студент не може да започне трећи, четврти,... покушај пре него толико времена не прође од краја претходног покушаја решавања теста.'; // ORPHANED
$string['configeachattemptbuildsonthelast'] = 'Уколико су дозвољени вишеструки покушаји онда сваки нови покушај садржи резултате претходног покушаја.'; // ORPHANED
$string['configgrademethod'] = 'Када су вишеструки покушаји дозвољени који метод треба користити за израчунавање студентове завршне оцене за тест.'; // ORPHANED
$string['configintro'] = 'Вредности које сте овде подесили дефинише подразумеване вредности које се користе у обрасцу за подешавање када креирате нови тест. Можете, такође, да конфигуришете која подешавања теста се сматрају напредним.'; // ORPHANED
$string['confignewpageevery'] = 'Код додавања питања у тест, прекид странице ће аутоматски бити убачен према подешавању које одве одаберете,'; // ORPHANED
$string['configpenaltyscheme'] = 'Казнени поени који се одузимају за сваки погрешан одговор у адаптивном моду.'; // ORPHANED
$string['configrequirepassword'] = 'Студенти морају да унесе ову лозинку пре него што покушају да реши тест.'; // ORPHANED
$string['configrequiresubnet'] = 'Студенти могу да покушају да реше тест само са ових рачунара.'; // ORPHANED
$string['configreviewoptions'] = 'Ове опције контролишу које информације ће корисници моћи да виде када буду прегледали покушај или када буду гледали извештаје о тесту.'; // ORPHANED
$string['configshowuserpicture'] = 'Прикажи слику корисника на екрану током покушаја решавања теста.'; // ORPHANED
$string['configshufflequestions'] = 'Уколико омогућите ову опцију, онда ће редослед питања у тесту ће насумично измешан сваки пут када студент покуша да реши тест.'; // ORPHANED
$string['configshufflewithin'] = 'Ако омогућоте ову опцију, онда ће делови који сачињавају појединачно питање бити насумочно измешани сваки пут када студент започне да решава овај тест. Понуђена опција је такође укљученљ у подешаваљима питања.'; // ORPHANED
$string['configtimelimit'] = 'Подраумевано временско ограничење за тестове у минутима. 0 значи да нема временског ограничења.'; // ORPHANED
$string['configtimelimitsec'] = 'Подраумевано временско огрничење за тестове у секундама. 0 значи да нема временског ограничења.'; // ORPHANED
$string['configurerandomquestion'] = 'Конфигуриши питање'; // ORPHANED
$string['createcategoryfornewrandomquestion'] = 'Креирај нову категорију питања за ново насумично одабрано питање'; // ORPHANED
$string['createquestionandadd'] = 'Креирај ново питање и додај га тесту.'; // ORPHANED
$string['decimalplaces'] = 'Децимална места у оценама'; // ORPHANED
$string['decimalplacesquestion'] = 'Децимална места у оценама питања'; // ORPHANED
$string['delay1st2nd'] = 'Принудни временски размак између првог и другог покушаја'; // ORPHANED
$string['delaylater'] = 'Принудни временски размак између накнадни покушаја'; // ORPHANED
$string['empty'] = 'Празно'; // ORPHANED
$string['endtest'] = 'Заврши тест...'; // ORPHANED
$string['erroraccessingreport'] = 'Не можете да приступите овом извештају'; // ORPHANED
$string['errorunexpectedevent'] = 'Неочекивани код догађаја $a->event пронађен за шитање $a->questionid у покушају $a->attemptid.'; // ORPHANED
$string['everynquestions'] = 'Свака/их $a питања'; // ORPHANED
$string['everyquestion'] = 'Свако питање'; // ORPHANED
$string['extraattemptrestrictions'] = 'Додатна ограничења приликом покушаја'; // ORPHANED
$string['formulaerror'] = 'Грешка у формули!'; // ORPHANED
$string['gradingmethod'] = 'Метод оцењивања: \$а'; // ORPHANED
$string['hidebreaks'] = 'Сакриј прекиде страница'; // ORPHANED
$string['hidereordertool'] = 'Сакриј алатку за реорганизацију'; // ORPHANED
$string['infoshort'] = 'и'; // ORPHANED
$string['invalidattemptid'] = 'Такав id покушаја не постоји'; // ORPHANED
$string['invalidquestionid'] = 'Неисправан id питања'; // ORPHANED
$string['invalidquizid'] = 'Неисправан id теста'; // ORPHANED
$string['invalidstateid'] = 'Неисправан id стања'; // ORPHANED
$string['layout'] = 'Изглед (распоред питања)'; // ORPHANED
$string['layoutasshown'] = 'Изглед странице као што је приказано.'; // ORPHANED
$string['layoutasshownwithpages'] = 'Изглед странице као што је приказано. <small>(Нова страница аутоматски на сваких  $a питања.)</small>'; // ORPHANED
$string['layoutshuffledandpaged'] = 'Питања су насумично измешана са $a питања по страници.'; // ORPHANED
$string['layoutshuffledsinglepage'] = 'Питања насумично измешана, сва приказана на једној страници.'; // ORPHANED
$string['loadingquestionsfailed'] = 'Број неуспелих учитавања питања: \$а'; // ORPHANED
$string['moveselectedonpage'] = 'Премести изабрана питања на страницу: $a'; // ORPHANED
$string['neverallononepage'] = 'Никад, сва питања на једну страницу'; // ORPHANED
$string['newpage'] = 'Нова страница'; // ORPHANED
$string['newpageevery'] = 'Аутоматски старуј нову страницу'; // ORPHANED
$string['nodatasubmitted'] = 'Ниједан податак није послат.'; // ORPHANED
$string['noquestionsinquiz'] = 'Не постоје питања у овом тесту'; // ORPHANED
$string['noquestionsnotinuse'] = 'Ово насумично одрабрано питање није у употреби јер је његова категорија празна'; // ORPHANED
$string['noquestionsonpage'] = 'Празна страница'; // ORPHANED
$string['noreviewshort'] = 'Није дозвољено'; // ORPHANED
$string['noreviewuntilshort'] = 'Доступно $a'; // ORPHANED
$string['notyourattempt'] = 'Ово није Ваш покушај!'; // ORPHANED
$string['noview'] = 'Пријављеном кориснику није дозвољено да прегледа овај тест'; // ORPHANED
$string['numquestionsx'] = 'Питања: $a'; // ORPHANED
$string['open'] = 'Започет'; // ORPHANED
$string['orderandpaging'] = 'Редослед питања и организација страница'; // ORPHANED
$string['orderingquiz'] = 'Редослед питања и организација страница'; // ORPHANED
$string['parentcategory'] = 'Надређена категорија'; // ORPHANED
$string['preprocesserror'] = 'Дошло је до грешке у току препроцесирања!'; // ORPHANED
$string['qname'] = 'име'; // ORPHANED
$string['qti_two'] = 'MS QTI 2.0 формат'; // ORPHANED
$string['qtypename'] = 'тип, име'; // ORPHANED
$string['questionbankcontents'] = 'Садржај Банке питања'; // ORPHANED
$string['questionbankmanagement'] = 'Управљање банком питања'; // ORPHANED
$string['questionbehaviour'] = 'Карактеристике питања'; // ORPHANED
$string['questionmissing'] = 'Недостаје питање за ову сесију'; // ORPHANED
$string['questionnotloaded'] = 'Питање $a није учитано из базе података'; // ORPHANED
$string['questionorder'] = 'Редослед питања'; // ORPHANED
$string['questionsperpageselected'] = 'Број питања по страници је подешен, тако да је тренутно број страница фиксиран. Услед тога контроле за реорганиѕацију страница су искључене. Ово можете да промените на $a.'; // ORPHANED
$string['questionsperpagex'] = 'Питања по једној страници: $a'; // ORPHANED
$string['questiontextisempty'] = '[Нема текста питања]'; // ORPHANED
$string['quiz:regrade'] = 'Поново оцени покушаје'; // ORPHANED
$string['quizisclosed'] = 'Овај тест је ѕатворен'; // ORPHANED
$string['quizisopen'] = 'Овај тест је отворен'; // ORPHANED
$string['quizisopenwillclose'] = 'Тест је отворен (затвара се $a)'; // ORPHANED
$string['quiznavigation'] = 'Навигација теста'; // ORPHANED
$string['quizopened'] = 'Овај тест је отворен'; // ORPHANED
$string['quizopenedon'] = 'Овај тест отворен у \$а'; // ORPHANED
$string['quizopenwillclose'] = 'Овај тест је отворен, биће затоворен $a'; // ORPHANED
$string['quizordernotrandom'] = 'Редослед теста није измешан'; // ORPHANED
$string['quizorderrandom'] = '* Редослед теста је измешан'; // ORPHANED
$string['quizwillopen'] = 'Овај тест се отвара $a'; // ORPHANED
$string['randomfromcategory'] = 'Насумично одабрано питање из категорије'; // ORPHANED
$string['randomnosubcat'] = 'Питања само иѕ ове категорије, не и њених подкатегорија'; // ORPHANED
$string['randomwithsubcat'] = 'Питања из ове категорије и њених подкатегорија'; // ORPHANED
$string['removeemptypage'] = 'Уклони празну страницу'; // ORPHANED
$string['removeselected'] = 'Уклони изабране'; // ORPHANED
$string['reorderquestions'] = 'Промени редослед питања'; // ORPHANED
$string['repaginatecommand'] = 'Реорганизуј странице'; // ORPHANED
$string['repaginatenow'] = 'Реорганизуј странице сад'; // ORPHANED
$string['reportnotfound'] = 'Извештај није познат ($a)'; // ORPHANED
$string['reviewthisattempt'] = 'Прегледај свој одговор на овај покушај'; // ORPHANED
$string['sameasoverall'] = 'Исто као и за свеукупне оцене'; // ORPHANED
$string['saveattemptfailed'] = 'Неуспело чување актуелног покушаја решења теста.'; // ORPHANED
$string['selectcategory'] = 'Изабери категорију'; // ORPHANED
$string['selectquestiontype'] = '-- Избаери тип питања --'; // ORPHANED
$string['showcategorycontents'] = 'Прикажи садржај категорија $a->arrow'; // ORPHANED
$string['showinsecurepopup'] = 'Употребити \'безбедни\' искачући прозор за покушаје'; // ORPHANED
$string['showuserpicture'] = 'Прикажи слику корисника'; // ORPHANED
$string['shuffledrandomly'] = 'Насумично измешано'; // ORPHANED
$string['shufflequestionsselected'] = 'С обзиром да је опција за мешање питања укључена, неке акције које се тичу страница нису доступне. За промену опције мешања, $a.'; // ORPHANED
$string['sortquestionsbyx'] = 'Поређај питања по $a'; // ORPHANED
$string['specificapathnotonquestion'] = 'Задата путања датотеке није на датом питању'; // ORPHANED
$string['specificquestionnotonquiz'] = 'Задато питање није у датом тесту'; // ORPHANED
$string['statenotloaded'] = 'Стање за питање  $a није учитано из базе података'; // ORPHANED
$string['status'] = 'Статус'; // ORPHANED
$string['subnetwrong'] = 'Овом тесту могуће је приступити само са одређених локација, а овај рачунар није на списку дозвољених локација.'; // ORPHANED
$string['summaryofattempt'] = 'Резиме покушаја'; // ORPHANED
$string['timelimitsec'] = 'Временско ограничење (секунде)'; // ORPHANED
$string['totalpointsx'] = 'Укупно оцена: $a'; // ORPHANED
$string['totalquestionsinrandomqcategory'] = 'Укупно $a питања у категорији.'; // ORPHANED
$string['windowclosing'] = 'Овај прозор ће се убрзо затворити.'; // ORPHANED
$string['youcannotwait'] = 'Овај тест се затвара пре него што ће Вам бити дозвољено да почнете нови покушај.'; // ORPHANED
$string['youmustwait'] = 'Морате сачекати пре него што будете могли да поново покушате решавање теста. Биће Вам дозвољено да започнете нови покушај после \$а.'; // ORPHANED
$string['reviewnotallowed'] = 'Није Вам допуштенои да прегледате покушаје других корисника на овом тесту.'; // ORPHANED
$string['existingcategory1'] = 'израз из већ постојећег скупа израза који се користи и у другим питањима у овој категорији'; // ORPHANED
$string['existingcategory2'] = 'датотека из већ постојећег скупа датотека која се користи и у другим питањима у овој категорији'; // ORPHANED
$string['existingcategory3'] = 'линк из већ постојећег скупа линкове који се користи и у другим питањима у овој категорији'; // ORPHANED
$string['keptcategory1'] = 'израз из исте категорије скупа израза који се могу вишеструко искористити као пре'; // ORPHANED
$string['keptcategory2'] = 'датотека из исте категорије скупа датотека који се могу вишеструко искористити као пре'; // ORPHANED
$string['keptcategory3'] = 'линк из исте категорије скупа линкова који се могу вишеструко искористити као пре'; // ORPHANED
$string['keptlocal1'] = 'израз из истог приватног скупа израза за питање као пре'; // ORPHANED
$string['keptlocal2'] = 'датотека из истог приватног скупа датотека за питање као пре'; // ORPHANED
$string['keptlocal3'] = 'линк из истог приватног скупа линкова за питање као пре'; // ORPHANED
$string['newcategory1'] = 'израз из новог скупа израза који се може такође користити у другим питањима ове категорије'; // ORPHANED
$string['newcategory2'] = 'датотека из новог скупа датотека која се може такође користити у другим питањима ове категорије'; // ORPHANED
$string['newcategory3'] = 'линк из новог скупа линкова који се може такође користити у другим питањима ове категорије'; // ORPHANED
$string['newlocal1'] = 'израз из новог скупа израза који ће се користити само у овом питању'; // ORPHANED
$string['newlocal2'] = 'датотека из новог скупа датотека која ће се користити само у овом питању'; // ORPHANED
$string['newlocal3'] = 'линк из новог скупа линкова који ће се користити само у овом питању'; // ORPHANED

?>
