<?PHP // $Id$ 
      // scorm.php - created with Moodle 1.9.9 (Build: 20100609) (2007101590)


$string['activation'] = 'Активација';
$string['activityloading'] = 'Бићете аутоматски преусмерени на ову активност за';
$string['activitypleasewait'] = 'Активност се учитава, молимо сачекајте';
$string['advanced'] = 'Параметри';
$string['asset'] = 'Елемент';
$string['assetlaunched'] = 'Елемент - Прегледано';
$string['attempt'] = 'покушај';
$string['attempt1'] = '1 покушај';
$string['attempts'] = 'покушаји';
$string['attemptsx'] = '$a покушај(а)';
$string['attr_error'] = 'Неадекватне вредности за атрибут ($a->attr) у ознаци $a->tag.';
$string['autocontinue'] = 'Аутоматски наставак';
$string['autocontinuedesc'] = 'Ово подешавање поставља подразумевано аутоматски наставак за активност';
$string['averageattempt'] = 'Просечни број покушаја';
$string['badmanifest'] = 'Има грешака у манифесту: погледајте извештај о грешкама';
$string['badpackage'] = 'Има неких проблема са датим пакетом. Проверите га и покушајте поново.';
$string['browse'] = 'Преглед';
$string['browsed'] = 'Претражено';
$string['browsemode'] = 'Начин прегледања података';
$string['browserepository'] = 'Претрага репозиторијума';
$string['chooseapacket'] = 'Изабери или ажурирај SCORM пакет';
$string['completed'] = 'Завршено';
$string['confirmloosetracks'] = 'УПОЗОРЕЊЕ: Чини се да је дошло до промене пакета. Ако је промењена структура пакета, подаци о активностима неких корисника се могу изгубити током процеса ажурирања.';
$string['contents'] = 'Садржај';
$string['coursepacket'] = 'Пакет курса';
$string['coursestruct'] = 'Структура курса';
$string['datadir'] = 'Грешка датотечног система: Није могуће креирати директоријум за податке курса';
$string['deleteallattempts'] = 'Обриши све покушаје прегледа SCORM  пакета';
$string['details'] = 'Прати детаље';
$string['directories'] = 'Приказ линкова директоријума';
$string['display'] = 'Прикажи пакет';
$string['displaydesc'] = 'Ово подешавање поставља подразумевану вредност да ли приказати пакет или не за активност';
$string['domxml'] = 'DOMXML екстерна библиотека';
$string['element'] = 'Елемент';
$string['enter'] = 'Уђи';
$string['entercourse'] = 'Уђи у SCORM курс';
$string['errorlogs'] = 'Извештај о грешкама';
$string['everyday'] = 'Свакодневно';
$string['everytime'] = 'При сваком коришћењу';
$string['exit'] = 'Изађи из SCORM курса';
$string['exitactivity'] = 'Изађи из активности';
$string['expcoll'] = 'Прошири/Скупи';
$string['external'] = 'Ажурирај временско усклађивање екстерних пакета';
$string['failed'] = 'Није успело';
$string['finishscorm'] = 'Уколико сте завршили са прегледањем овог ресурса,';
$string['finishscormlinkname'] = 'кликните овде да бисте се вратили на страницу курса.';
$string['firstaccess'] = 'Први приступ';
$string['firstattempt'] = 'Први покушај';
$string['found'] = 'Манифест је нађен';
$string['frameheight'] = 'Ово својство одређује подразумевану висину оквира или прозора нивоа';
$string['framewidth'] = 'Ово својство одређује подразумевану ширину оквира или прозора нивоа';
$string['fullscreen'] = 'Попуни цео екран';
$string['general'] = 'Општи подаци';
$string['gradeaverage'] = 'Просечна оцена';
$string['gradehighest'] = 'Највиша оцена';
$string['grademethod'] = 'Начин оцењивања';
$string['grademethoddesc'] = 'Ово подешавање поставља подразумевани метод оцењивања за активност';
$string['gradescoes'] = 'Објекти за учење';
$string['gradesum'] = 'Коначна оцена';
$string['height'] = 'Висина';
$string['hidden'] = 'Сакривено';
$string['hidebrowse'] = 'Онемогући мод приказа';
$string['hidebrowsedesc'] = 'Ово подешавање поставља подразумевано да ли онемогућити или омогућити режим прегледа';
$string['hideexit'] = 'Сакриј линк за излаз';
$string['hidenav'] = 'Сакриј навигациону дугмад';
$string['hidenavdesc'] = 'Ово подешавање поставља подразумевано да ли приказати или сакрити навигациону дугмад';
$string['hidereview'] = 'Сакриј дугме за преглед';
$string['hidetoc'] = 'Приказ структуре курса (садржаја)';
$string['hidetocdesc'] = 'Ово подешавање поставља подразумевано да ли приказати или сакрити приказ структуре курса (стабло садржаја - TOC)';
$string['highestattempt'] = 'Најбољи покушај';
$string['identifier'] = 'Идентификатор питања';
$string['iframe'] = 'Текући прозор';
$string['iframedisplay'] = 'Отварање пакета у текућем прозору';
$string['incomplete'] = 'Непотпуно';
$string['interactions'] = 'Интеракције';
$string['last'] = 'Последњи пут приступљено дана';
$string['lastaccess'] = 'Последњи приступ';
$string['lastattempt'] = 'Последњи покушај';
$string['location'] = 'Прикажи локациону линију';
$string['max'] = 'Најбољи резултат';
$string['maximumattempts'] = 'Број покушаја';
$string['maximumattemptsdesc'] = 'Ово подешавање поставља подразумевани максимални број покушаја за активност';
$string['maximumgradedesc'] = 'Ово подешавање поставља подразумевану максималну оцену за активност';
$string['menubar'] = 'Прикажи линију менија';
$string['min'] = 'Најгори резултат';
$string['missing_attribute'] = 'Недостаје атрибут $a->attr у ознаци $a->tag';
$string['missing_tag'] = 'Недостаје ознака $a->tag';
$string['missingparam'] = 'Обавезна информација недостаје или је некоректна';
$string['mode'] = 'Начин рада';
$string['modulename'] = 'SCORM/AICC';
$string['modulenameplural'] = 'SCORM/AICC пакети';
$string['newattempt'] = 'Почни нови покушај';
$string['next'] = 'Наставак';
$string['no_attributes'] = 'Ознака $a->tag мора имати атрибуте';
$string['no_children'] = 'Ознака $a->tag мора имати потомке';
$string['noactivity'] = 'Нема података за извештај';
$string['nolimit'] = 'Неограничени број покушаја';
$string['nomanifest'] = 'Манифест није пронађен';
$string['noprerequisites'] = 'Нажалост, не испуњавате довољно предуслова за приступ овом објекту за учење';
$string['noreports'] = 'Нема извештаја за приказ';
$string['normal'] = 'Нормално';
$string['noscriptnoscorm'] = 'Ваш Web читач не подржава Javascript или је у његовим подешавањима искључена подршка за Javascript. Није могуће забележити никакве податке о праћењу.';
$string['not_corr_type'] = 'Неслагање типова за ознаку $a->tag';
$string['notattempted'] = 'Није покушавано';
$string['objectives'] = 'Циљеви';
$string['onchanges'] = 'Кад год се промени';
$string['options'] = 'Опције';
$string['organization'] = 'Организација';
$string['organizations'] = 'Организације';
$string['othersettings'] = 'Додатна подешавања';
$string['othertracks'] = 'Други записи';
$string['package'] = 'Пакет';
$string['packagedir'] = 'Грешка датотечног система: Није могуће креирати директоријум пакета';
$string['packagefile'] = 'Није наведена датотека с пакетом';
$string['passed'] = 'Положено';
$string['php5'] = 'PHP 5 (DOMXML изворна библиотека)';
$string['popup'] = 'Нови прозор';
$string['popupblocked'] = 'уколико се нови прозор не појави';
$string['popupblockedlinkname'] = 'кликни овде како би покренули активност';
$string['popupmenu'] = 'У падајућем менију';
$string['popupopen'] = 'Отвори пакет у новом прозору';
$string['position_error'] = 'Ознака $a->tag не може бити подређена ознаци $a->parent';
$string['prev'] = 'Претходни';
$string['raw'] = 'Основни резултат';
$string['regular'] = 'Регуларни манифест';
$string['report'] = 'Извештај';
$string['resizable'] = 'Дозволи промену величине прозора';
$string['result'] = 'Резултат';
$string['review'] = 'Преглед';
$string['reviewmode'] = 'Мод за прегледање';
$string['scoes'] = 'Објекти за учење';
$string['score'] = 'Резултат';
$string['scorm:deleteresponses'] = 'Обриши SCORM покушаје';
$string['scorm:savetrack'] = 'Чување резултата праћења';
$string['scorm:skipview'] = 'Прескакање прегледа';
$string['scorm:viewreport'] = 'Преглед извештаја';
$string['scorm:viewscores'] = 'Преглед резултата';
$string['scormcourse'] = 'SCORM курс';
$string['scormloggingoff'] = 'API извештавање је искључено';
$string['scormloggingon'] = 'API извештавање је укључено';
$string['scormresponsedeleted'] = 'Обрисани покушаји корисника';
$string['scrollbars'] = 'Дозволи излиставање прозора';
$string['sided'] = 'Са леве стране';
$string['skipview'] = 'Студент прескаче страницу са структуром садржаја';
$string['skipviewdesc'] = 'Ово подешавање поставља подразумевано када не приказати структуру садржаја за страницу';
$string['slashargs'] = 'УПОЗОРЕЊЕ: слеш аргументи нису дозвољени на овом сајту и објекти можда неће функционисати како се очекује!';
$string['stagesize'] = 'Величина нивоа';
$string['started'] = 'Започето дана';
$string['status'] = 'Статус';
$string['statusbar'] = 'Прикажи статусну линију';
$string['student_response'] = 'Одговор';
$string['suspended'] = 'Суспендовано';
$string['syntax'] = 'Синтаксна грешка';
$string['tag_error'] = 'Непозната ознака ($a->tag) са овим садржајем: $a->value';
$string['time'] = 'Време';
$string['title'] = 'Наслов';
$string['too_many_attributes'] = 'Ознака $a->tag има јако пуно карактеристика';
$string['too_many_children'] = 'Ознака $a->tag има јако пуно потомака';
$string['toolbar'] = 'Прикажи линију са алаткама';
$string['totaltime'] = 'Време';
$string['trackingloose'] = 'УПОЗОРЕЊЕ: Подаци о праћењу овог SCORM пакета биће изгубљени!';
$string['type'] = 'Тип';
$string['unziperror'] = 'Дошло је до грешке приликом распакивања пакета';
$string['updatefreq'] = 'Учесталост аутоматског ажурирања';
$string['updatefreqdesc'] = 'Ово подешавање поставља подразумевану фреквенцију аутоматског ажурирања активности';
$string['validateascorm'] = 'Провери исправност SCORM пакета';
$string['validation'] = 'Резултат провере исправности';
$string['validationtype'] = 'Ово својство одређује DOMXML библиотеку која се користи за валидацију SCORM манифеста. Ако нисте сигурни коју вредност треба да поставите, оставите тренутно активни избор.';
$string['value'] = 'Вредност';
$string['versionwarning'] = 'Верзија манифеста је старија од 1.3, упозорење на ознаци $a->tag';
$string['viewallreports'] = 'Прикажи извештај за $a покушаја';
$string['viewalluserreports'] = 'Прикажи извештај за $a корисника';
$string['whatgrade'] = 'Оцењивање покушаја';
$string['whatgradedesc'] = 'Ово подешавање поставља подразумевано оцењивање покушаја';
$string['width'] = 'Ширина';
$string['window'] = 'Прозор';
$string['allowtypeexternal'] = 'Омогући спољашњи тип пакета'; // ORPHANED
$string['allowtypeimsrepository'] = 'Омогући IMS тип пакета'; // ORPHANED
$string['allowtypelocalsync'] = 'Омогући преузети тип пакета'; // ORPHANED
$string['areacontent'] = 'Датотеке садржаја'; // ORPHANED
$string['areapackage'] = 'Датотека пакета'; // ORPHANED
$string['cannotfindsco'] = 'Није било могуће наћи SCO'; // ORPHANED
$string['displayattemptstatus'] = 'Прикажи статус покушаја'; // ORPHANED
$string['displaycoursestructure'] = 'Прикажи структуру курса'; // ORPHANED
$string['exceededmaxattempts'] = 'Достигли сте максималан број покушаја'; // ORPHANED
$string['expired'] = 'Опростите, ова активност је затоврена $a и није више доступна'; // ORPHANED
$string['gradeforattempt'] = 'Оцена за покушај'; // ORPHANED
$string['invalidactivity'] = 'Scorm активност је неисправна'; // ORPHANED
$string['lastattemptlock'] = 'Закључај након завршног покушаја'; // ORPHANED
$string['noattemptsallowed'] = 'Број дозвољених покушаја'; // ORPHANED
$string['noattemptsmade'] = 'Број покушаја који сте имали'; // ORPHANED
$string['notopenyet'] = 'Опростите, али ова активност није доступна до $a'; // ORPHANED
$string['scormclose'] = 'До'; // ORPHANED
$string['scormopen'] = 'Од'; // ORPHANED
$string['scormtype'] = 'Тип'; // ORPHANED
$string['timerestrict'] = 'Ограничи давање одговора на овај временски период'; // ORPHANED
$string['typeexternal'] = 'Екстерни SCORM манифест'; // ORPHANED
$string['typeimsrepository'] = 'Локални репозиторијум IMS садржаја'; // ORPHANED
$string['typelocal'] = 'Поставњени пакет'; // ORPHANED
$string['typelocalsync'] = 'Преутети пакет'; // ORPHANED
$string['updatetime'] = 'Време синхронизације'; // ORPHANED
$string['url'] = 'URL'; // ORPHANED
$string['zlibwarning'] = 'Упозорење: PHP Zlib компресија је омогућена на овом сајту, неки корисници могу могу имати проблема са учитавањем SCORM објеката у одређеним веб читачима.'; // ORPHANED

?>
