<?PHP // $Id$ 
      // message.php - created with Moodle 1.9.7+ (Build: 20091209) (2007101570)


$string['addcontact'] = 'Tilføj kontakt';
$string['addsomecontacts'] = 'For at sende en besked til nogen, eller for at tilføje en genvej til dem på denne side, kan du bruge <a href=\"$a\">søgesiden</a> på næste faneblad.';
$string['addsomecontactsincoming'] = 'Disse er fra personer der ikke er i din kontaktliste. Hvis du vil tilføje dem til dine kontakter kan du trykke på \"Tilføj kontaktperson\" ikonen ud for deres navn.';
$string['ago'] = '$a siden';
$string['allmine'] = 'Alle beskeder til mig eller fra mig';
$string['allstudents'] = 'Alle beskeder mellem elever i kurset';
$string['allusers'] = 'Alle beskeder fra alle brugere';
$string['backupmessageshelp'] = 'Hvis aktiveret vil beskeder blive inkluderet i automatiske SITE backups';
$string['beepnewmessage'] = 'Bip når der kommer en ny besked';
$string['blockcontact'] = 'Bloker kontakt';
$string['blockedmessages'] = '$a besked(er) til/fra blokerede brugere';
$string['blocknoncontacts'] = 'Blokér alle beskeder fra personer der ikke er i min kontaktliste.';
$string['contactlistempty'] = 'Din kontaktliste er tom';
$string['contacts'] = 'Kontakter';
$string['context'] = 'sammenhæng';
$string['deletemessagesdays'] = 'Antal dage før gamle beskeder automatisk bliver slettet';
$string['discussion'] = 'Diskussion';
$string['emailmessages'] = 'Send beskeder som e-mails hvis jeg er offline';
$string['emailtagline'] = 'Denne e-mail er en kopi af en besked sendt til \"$a\"';
$string['emptysearchstring'] = 'Du må søge efter noget';
$string['formorethan'] = 'i mere end';
$string['includeblockedusers'] = 'Inkluder blokerede brugere';
$string['incomingcontacts'] = 'Indkomne kontakter ($a)';
$string['keywords'] = 'Nøgleord';
$string['keywordssearchresults'] = 'Søgeresultat: $a beskeder fundet';
$string['mailsent'] = 'Din besked blev sendt via e-mail.';
$string['maxmessages'] = 'Maksimalt antal beskeder der vises i beskedhistorikken';
$string['message'] = 'Besked';
$string['messagehistory'] = 'Beskedhistorik';
$string['messages'] = 'Beskeder';
$string['messaging'] = 'Beskedsystem';
$string['messagingdisabled'] = 'Beskedsystemet er deaktiveret, der sendes e-mails i stedet';
$string['mycontacts'] = 'Mine kontakter';
$string['newonlymsg'] = 'Vis kun nye';
$string['newsearch'] = 'Ny søgning';
$string['noframesjs'] = 'Version uden rammer og JavaScript';
$string['nomessages'] = 'Ingen ventende beskeder';
$string['nomessagesfound'] = 'Ingen beskeder fundet';
$string['nosearchresults'] = 'Der var ingen beskeder der opfyldte søgekriteriet';
$string['offline'] = 'Offline';
$string['offlinecontacts'] = 'Offline kontakter ($a)';
$string['online'] = 'Online';
$string['onlinecontacts'] = 'Online kontakter ($a)';
$string['onlyfromme'] = 'Kun beskeder fra mig';
$string['onlymycourses'] = 'Kun i mit kursus';
$string['onlytome'] = 'Kun beskeder til mig';
$string['pagerefreshes'] = 'Denne side opdateres hvert $a sekund';
$string['readmessages'] = '$a læste beskeder';
$string['removecontact'] = 'Fjern kontakt';
$string['savemysettings'] = 'Gem mine indstillinger';
$string['search'] = 'Søg';
$string['searchforperson'] = 'Søg efter en person';
$string['searchmessages'] = 'Søg efter beskeder';
$string['sendmessage'] = 'Send besked';
$string['sendmessageto'] = 'Send besked til $a';
$string['sendmessagetopopup'] = 'Send besked til $a - nyt vindue';
$string['settings'] = 'Indstillinger';
$string['settingssaved'] = 'Dine indstillinger er gemt';
$string['showmessagewindow'] = 'Vis automatisk nye beskeder i et popupvindue (det kræver at din browser ikke blokerer for popupvinduer for dette site).';
$string['strftimedaydatetime'] = '%%A, %%d %%B %%Y, %%I:%%M %%p';
$string['timenosee'] = 'Antal minutter siden du sidst var online på sitet';
$string['timesent'] = 'Tid sendt';
$string['unblockcontact'] = 'Fjern blokering for kontakt';
$string['unreadmessages'] = '$a ulæste beskeder';
$string['userisblockingyou'] = 'Denne bruger har blokeret for beskeder fra dig.';
$string['userisblockingyounoncontact'] = 'Denne bruger accepterer kun beskeder fra personer der er på hans/hendes kontaktliste og det er du ikke på nuværende tidspunkt.';
$string['userssearchresults'] = 'Søgeresultat: $a brugere fundet';

?>
