<?PHP // $Id$ 
      // moodle.org.php - created with Moodle 1.9.7+ (Build: 20091209) (2007101570)


$string['aboutdemosite'] = 'På vores demonstrationsside finder du en fuld installation af Moodle med eksempler på kurser du kan afprøve som lærer, elev eller endda administrator. Vær ikke bange for at ødelægge noget, siden nulstilles hver hele time.';
$string['aboutdemositetitle'] = 'Demonstrationsside';
$string['aboutintro'] = 'Moodle er et Open Source Course Management System (CMS), også kaldet Learning Management System (LMS) eller et Virtual Learning Environment (VLE). Det er blevet meget populært blandt lærere over hele verden, som værktøj til oprettelse af dynamiske websider for deres studerende. For at fungere skal det installeres på en webserver et sted, enten på en af dine egne computere eller på en computer på et webhotel.';
$string['aboutoverview'] = '<p>Moodleprojektet har altid fokus på at give undervisere det bedste værktøj til at administre og understøtte læring, men der er mange måder at bruge Moodle på:</p> <ul>
<li>Moodle har funktioner der gør, at det kan skaleres til meget store organisationer med hundredtusinder studerende og samtidig kan det bruges af grundskoler eller til undervisning på hoppyniveau.</li>
<li>Mange institutioner bruger det som deres platform til rene onlinekurser mens andre bruger det som et supplement til ansigt til ansigts-undervisningen i klassen (også kaldet blended learning).</li>
<li>Mange af vores brugere elsker at bruge de mange aktivitetsmoduler (som f.eks. forummer, wikier, databaser mv.) til at bygge helt igennem kollaborative læringsfællesskaber omkring et emne (i den social konstruktivistiske tradition), mens andre foretrækker Moodle som en måde at give de studerende undervisningsmaterialer på (som f.eks. standard SCORM-pakker) og bedømme læringen ved brug af opgaver eller quizzer.</li> </ul>';
$string['aboutoverviewtitle'] = 'Hvad er Moodle?';
$string['aboutstatistics'] = 'Moodle kan frit downloades og det er frivilligt om man vil registrere systemet, så vi har ikke fyldestgørende information om alle der bruger det. Vi har imidlertid - på basis af de informationer vi får - nogle automatisk genererede interessante grafer og tal på vores statistikside.';
$string['aboutstatisticstitle'] = 'Statistik';
$string['browsecvstitle'] = 'Gennemse vores kildekode';
$string['communityintro'] = 'Moodle har et stort og bredt brugerfællesskab med over <a href=\"http://moodle.org/userpics\">$a->usercount registrerede brugere</a> alene på denne moodleside, der taler over <a href=\"http://download.moodle.org/lang16/\">$a->langcount sprog</a> i <a href=\"http://moodle.org/sites\">$a->countrycount lande</a> (vi har <a href=\"http://moodle.org/stats\">mere statistik her</a>).';
$string['conferencecenter'] = 'Moodles konferencecenter';
$string['connectedsites'] = 'Nogle moodlesites er forbundet til moodle.org ved brug af Moodle Netværk. Således kan du kan ind der direkte så snart du er godkendt her.';
$string['connectedsitestitle'] = 'Forbundne websteder';
$string['contactbugs'] = 'Du kan rapportere problemer med Moodlesoftwaren og på alle sider på moodle.org ved at udfylde en formular i Moodles \"Tracker\".';
$string['contactbugstitle'] = 'Rapportering af fejl';
$string['contactcommunity'] = 'Alle andre forespørgsler skal stiles til \"Moodle Community Manager\".';
$string['contactintro'] = 'Vælg venligst en af disse kontaktmuligheder:';
$string['contactlogin'] = 'Angående andre forespørgsler bedes du logge ind på denne side og bruge kontaktformularen som vil fremkomme på denne side.';
$string['contactmoodlecom'] = 'Forespørgsler relateret til licens, varemærke eller kommercielle anliggender så vel som større udviklingsprojekter stiles til Moodles helpdesk på <a href=\"http://moodle.com/\">Moodle.com</a>';
$string['contactmoodlecomhelpdesk'] = 'Moodle.com Helpdesk';
$string['contactmoodlecomtitle'] = 'Moodle.com';
$string['contactmoodleorgemail'] = 'Ved problemer med bekræftelse af en konto på moodle.org kan du sende en e-mail til denne adresse:';
$string['contactmoodleorglogin'] = 'Log ind på dette websted nu';
$string['contactmoodleorgother'] = 'Brug venligst nedenstående kontaktformular ved alle andre forespørgsler.';
$string['contactmoodleorgtitle'] = 'Moodle.org';
$string['contactsecurity'] = 'Sikkerhedsspørgsmål kan rapporteres sikkert i Moodles tracker, såfremt du sætter sikkerhedsniveauet derefter.';
$string['contactsent'] = 'Din besked er sendt via e-mail til Moodle Community Manager.';
$string['contactsupport'] = 'Vores suppoortside har en liste med mange nyttige ressourcer du kan gøre brug af.';
$string['contactsupporttitle'] = 'Support';
$string['developercontributors'] = 'Krediteringer';
$string['developerlist'] = 'Liste over udviklere med skriveadgang';
$string['developermeetings'] = 'Møder for udviklere';
$string['developers'] = 'Hovedudviklingen af Moodle ledes af et kerneteam på Moodle.com, hjulpet af hundreder af andre udviklere rundt omkring i verden. Mange af disse udviklere er også direkte ansvarlige for forskellige moduler og plugins.';
$string['developerstitle'] = 'Udviklere';
$string['developmentdocs'] = 'Hovedparten af vores dokumentation ligger i Moodle Docs - inklusiv specifikationer, brainstorms, procedurer, standarder og færdige brugerguides.';
$string['developmentdocstitle'] = 'Dokumentation for udviklere';
$string['developmentintro'] = 'Vi sigter mod en transparent og åben udviklingsproces der opfordrer hele brugerfællesskabet til at bidrage. PHP-programmører er selvfølgelig velkomne, men du kan også bidrage gennem diskussioner, ved testning, feedback og dokumentation.';
$string['developmenttracker'] = 'Alle udviklingsspørgsmål (bugs, nye funktioner og forbedringer) registreres og administreres i Moodle Tracker\'en. Du kan se hvem der arbejder på hvad og bidrage til konversationen. Du bør starte med at søge i tracker\'en hvis du prøver at finde ud af noget om specielle problemer og du må endelig <strong>stemme</strong> på de sager du især gerne vil have bliver taget hånd om, da din stemme hjælper os med at prioritere arbejdet.';
$string['donations'] = 'Moodle er helt fri for økonomiske forpligtelser for dig, men mange i fællesskabet har doneret et beløb til vores projekt til hjælp til at betale udviklere så det kan fortsætte.';
$string['donationstitle'] = 'Donationer';
$string['downloadcore'] = 'Vores hoveddistributionsmetode er via disse standard kernepakker. De indeholder et antal moduler der vedligeholdes af kerneudviklere, og som fint kan installeres på så godt som alle platforme med PHP og en database installeret.';
$string['downloadcoretitle'] = 'Standard Moodlepakker';
$string['downloadcvs'] = 'En anden måde at få fat i kildekoden på, er ved hjælp af CVS til at forbinde direkte til et af vores spejlinger af kodedepotet, som Moodles udviklere bruger. Dette gør opgradering meget let, selv hivs du har lavet lokale ændringer i kildekoden.';
$string['downloadcvstitle'] = 'Moodle via CVS';
$string['downloadintro'] = 'Moodle er open source under <a href=\"http://docs.moodle.org/en/License\">GPL licens</a>. Alt hvad vi fremstiller, er frit tilgængeligt til download og brug.';
$string['downloadlang'] = 'I de nuværende versioner af Moodle er installation af sprogpakker blevet automatiseret via administrationsmenuen på dit site. I ældre versioner af Moodle skal nye sprogpakker downloades manuelt.';
$string['downloadlangtitle'] = 'Sprogpakker';
$string['downloadlogotitle'] = 'Moodlelogoer';
$string['downloadmac'] = 'Hvis ikke du allerede har en webserver sat op, gør disse alt i et-pakker det meget let at installere Moodle på enhver applecomputer med Mac OS X.';
$string['downloadmactitle'] = 'Moodle til Mac OS X';
$string['downloadmodules'] = 'Se vores omfattende database med ekstra moduler og plugins der kan tilføjes til din Moodle og give den ekstra funktionalitet ud over kernepakkerne.';
$string['downloadmodulestitle'] = 'Moduler og plugins';
$string['downloadthemes'] = 'Moodles udseende kan ændres markant ved brug af forskellige layouts. Vi har en database med layouts som moodlere har oprettet og bidraget med.';
$string['downloadthemestitle'] = 'Layouts';
$string['downloadwin'] = 'Hvis ikke du allerede har en webserver sat op, gør disse alt i et-pakker det meget let at installere Moodle på enhver computer med Microsoft Windows.';
$string['downloadwintitle'] = 'Moodle til Windows';
$string['events'] = 'Selv om vi er specialiseret i onlinelæring, er det stadig rart fysisk at mødes i et lokale! Disse links har mere information om vores konferencer (vi kalder dem MoodleMoots) og andre arrangementer.';
$string['eventstitle'] = 'Arrangementer';
$string['frontpagewelcome1'] = 'Moodle er et Course Management System (CMS), også kendt som et Learning Management System (LMS) eller et Virtual Learning Environment (VLE). Det er en gratis webapplikation lærere kan bruge til at opbygge effektive online læringsmiljøer i.';
$string['frontpagewelcome2'] = 'Moodle.org er vores websted, hvor Moodle udvikles og diskuteres. Brug venligst menuerne til at se dig om og vær med!';
$string['frontpagewelcometitle'] = 'Velkommen til fællesskabet om Moodle!';
$string['generaldeveloperforum'] = 'Generelt udviklerforum';
$string['jobs'] = 'Besøg vores jobdatabase og få information om Moodle-relaterede stillinger i hele verden.';
$string['jobstitle'] = 'Moodlejobs';
$string['moodlecertification'] = 'Moodlecertificering';
$string['moodleconsulting'] = 'Moodlerådgivning';
$string['moodlecourseware'] = 'Moodle Courseware';
$string['moodlecustomisation'] = 'Specialtilpasning af Moodle';
$string['moodledocs'] = 'Moodle Docs';
$string['moodlehosting'] = 'Moodle Hosting';
$string['moodleinstallation'] = 'Moodleinstallation';
$string['moodleintegrations'] = 'Moodle Integrations';
$string['moodlesupport'] = 'Moodlesupport';
$string['moodlethemes'] = 'Moodle Layouts';
$string['moodletrackertitle'] = 'Moodle Tracker';
$string['moodletraining'] = 'Moodleoplæring';
$string['mycoursesintro'] = 'Du er pt. tilmeldt disse \"kurser\" på dette websted, hver med et eller flere forummer.';
$string['nameabout'] = 'Om';
$string['nameaboutmoodle'] = 'Om Moodle';
$string['namecommercial'] = 'Kommerciel service';
$string['namecommunity'] = 'Fællesskab';
$string['namecontact'] = 'Kontakt';
$string['namedevelopment'] = 'Udvikling';
$string['namedocumentation'] = 'Dokumentation';
$string['namedownloads'] = 'Downloads';
$string['nameevents'] = 'Begivenheder';
$string['nameforums'] = 'Forummer';
$string['namehome'] = 'Hjemmeside';
$string['namemycourses'] = 'Mine kurser';
$string['namenetwork'] = 'Forbundne websteder';
$string['namenews'] = 'Nyheder';
$string['namesecurity'] = 'Sikkerhedsnyt';
$string['namesupport'] = 'Support';
$string['networkintro'] = 'De følgende moodlewebsteder er forbundet til moodle.org gennem Moodle netværk, så du kan logge ind på dem direkte herfra.';
$string['newsbuzz'] = 'Moodle Buzz';
$string['newsbuzzdetail'] = 'Moodle-relaterede publikationer fra hele verden';
$string['newscalendar'] = 'Kalender';
$string['newscalendardetail'] = 'Moodle-relaterede arrangementer fremover';
$string['newsofficial'] = 'Officielt nyt om Moodle';
$string['newsplanet'] = 'Planet Moodle';
$string['newsplanetdetail'] = 'Samling af blogs af moodleudviklere.';
$string['newsrecent'] = 'Sidste nyt';
$string['newssecurity'] = 'Sikkerhedsnyt';
$string['newssecuritydetail'] = 'Vigtig information om sikkerhedsspørgsmål';
$string['noenrolledcoursesyet'] = 'Du er ikke tilmeldt kurser her på siden.';
$string['overview'] = 'Oversigt';
$string['overviewabout'] = 'En oversigt over Moodle';
$string['overviewcommunity'] = 'En oversigt over Moodlefællesskabet';
$string['overviewdevelopment'] = 'En oversigt over Moodles udvikling';
$string['overviewdownloads'] = 'En oversigt over Moodles downloads';
$string['overviewmy'] = 'Se alle de kurser du er tilmeldt på moodle.org';
$string['overviewnews'] = 'En oversigt over de aktuelle moodlenyheder';
$string['overviewsupport'] = 'En oversigt over Moodles supportmuligheder';
$string['popularissues'] = 'De mest populære spørgsmål';
$string['recentpart'] = 'Denne side viser nogle af de mennesker der bruger moodle.org i dag';
$string['recentparttitle'] = 'Sidst sete deltagere';
$string['registeredsites'] = 'Institutioner er ikke forpligtet til at informere om at de bruger Moodle da Moodle er open source. Nogle har dog valgt at registrere sig hos os og vi har en liste over dem.';
$string['registeredsitestitle'] = 'Registerede sider';
$string['roadmap'] = 'Moodlekøreplan';
$string['shop'] = 'Er du på udkig efter en måde hvorpå du kan vise at du er en del af vores fællesskab? Se vores butik med bluser, krus og mange andre ting.';
$string['shoptitle'] = 'Moodlebutik';
$string['sourcecodetitle'] = 'Open source kode';
$string['supportbooks'] = 'Vi vedligeholder en liste over mange tilgængelige bøger om Moodle, du kan købe.';
$string['supportbookstitle'] = 'Bøger og manualer';
$string['supportcommercial'] = '<a href=\"http://moodle.com/\">Moodle Partners</a> er en verdensomspændende gruppe autoriserede servicevirksomheder, der er forpligtede til at støtte open source-projektet, Moodle, økonomisk. De driver en række kommercielle tjenester til Moodlebrugere over hele verden:';
$string['supportcommercialtitle'] = 'Kommerciel service';
$string['supportdocs1'] = 'Moodle Docs er et godt sted at starte, specielt på vores sider med <acronym title=\"Frequently Asked Questions\">Ofte Stillede Spørgsmål</acronym> (<acronym title=\"FAQ\">OSS</acronym>).';
$string['supportdocs2'] = 'En god måde at få relevant dokumentation på, er at bruge linket \"Moodle Docs for denne side\" i bunden af hver side på din Moodle.';
$string['supportdocsfaq'] = 'Ofte Stillede Spørgsmål';
$string['supportdocslang'] = 'Moodle Docs på andre sprog';
$string['supportdocstitle'] = 'Dokumentation';
$string['supportforums'] = 'Vores brugerfællesskab kommunikerer hovedsagelig via forummer i \"kurser\" på denne Moodlebaserede side. Du må tilmelde dig et kursus for at kunne skrive i forummer (tilmelding er helt gratis).';
$string['supportforumsenglish'] = 'Hovedsupporten og udviklingsdiskussioner mellem brugere og udviklere på engelsk:';
$string['supportforumsenglishname'] = 'Using Moodle';
$string['supportforumslang'] = 'Hovedforummet til socialt \"samvær\" for moodlere på engelsk:';
$string['supportforumslangname'] = 'Moodle Lounge';
$string['supportforumslangurl'] = 'http://moodle.org/course/view.php?id=55';
$string['supportforumslist'] = 'Vi har også mange andre forummer på bl.a. dansk og adskillige andre sprog:';
$string['supportforumslistname'] = 'Liste over alle forummer';
$string['supportforumstitle'] = 'Forummer';
$string['supportintro'] = 'Du er ikke alene! Der er flere forskellige måde at få hjælp til Moodle på, hvis du har brug for det.';

?>
