<?PHP // $Id$ 
      // role.php - created with Moodle 1.9.3+ (Build: 20081025) (2007101530)


$string['addrole'] = 'Tilføj rolle';
$string['allow'] = 'Tillad'; // ORPHANED
$string['allowassign'] = 'Tillad rolletildeling'; // ORPHANED
$string['allowoverride'] = 'Tillad tilsidesættelse af roller'; // ORPHANED
$string['allsiteusers'] = 'Alle brugere på sitet'; // ORPHANED
$string['assignglobalroles'] = 'Tildel globale roller'; // ORPHANED
$string['assignroles'] = 'Tildel roller'; // ORPHANED
$string['assignrolesin'] = 'Tildel roller i $a'; // ORPHANED
$string['block:view'] = 'Se blok'; // ORPHANED
$string['blog:create'] = 'Opret nye weblogindlæg'; // ORPHANED
$string['blog:manageentries'] = 'Ret og administrer indlæg'; // ORPHANED
$string['blog:manageofficialtags'] = 'Administrere officielle tags'; // ORPHANED
$string['blog:managepersonaltags'] = 'Administrer personlige tags'; // ORPHANED
$string['blog:view'] = 'Vis weblogindlæg'; // ORPHANED
$string['calendar:manageentries'] = 'Administrer alle kalendere'; // ORPHANED
$string['calendar:managegroupentries'] = 'Administrer kalender for gruppe'; // ORPHANED
$string['calendar:manageownentries'] = 'Administrer egen kalender'; // ORPHANED
$string['capabilities'] = 'Kompetencer'; // ORPHANED
$string['capability'] = 'Kompetence'; // ORPHANED
$string['category:create'] = 'Opret kategorier'; // ORPHANED
$string['category:delete'] = 'Slette kategorier'; // ORPHANED
$string['category:update'] = 'Opdatere kategorier'; // ORPHANED
$string['category:visibility'] = 'Se skjulte kategorier'; // ORPHANED
$string['course:activityvisibility'] = 'Skjul / vis aktiviteter'; // ORPHANED
$string['course:bulkmessaging'] = 'Send en besked til mange personer'; // ORPHANED
$string['course:changefullname'] = 'Rediger kursets fulde navn'; // ORPHANED
$string['course:changeidnumber'] = 'Rediger kursets id-nummer'; // ORPHANED
$string['course:changeshortname'] = 'Rediger kursets korte navn'; // ORPHANED
$string['course:create'] = 'Opret kurser'; // ORPHANED
$string['course:delete'] = 'Slette kurser'; // ORPHANED
$string['course:manageactivities'] = 'Administrer aktiviteter'; // ORPHANED
$string['course:managefiles'] = 'Administrer filer'; // ORPHANED
$string['course:managegrades'] = 'Administrer karakterer'; // ORPHANED
$string['course:managegroups'] = 'Administrer grupper'; // ORPHANED
$string['course:managemetacourse'] = 'Administrer metakurser'; // ORPHANED
$string['course:managescales'] = 'Administrer skalaer'; // ORPHANED
$string['course:reset'] = 'Nulstil kursus'; // ORPHANED
$string['course:sectionvisibility'] = 'Kontroller synligheden af sektioner'; // ORPHANED
$string['course:setcurrentsection'] = 'Se aktuelle sektion'; // ORPHANED
$string['course:update'] = 'Opdater kursusindstillinger'; // ORPHANED
$string['course:useremail'] = 'Aktivere / Deaktivere e-mail-adresser'; // ORPHANED
$string['course:view'] = 'Se kurser'; // ORPHANED
$string['course:viewcoursegrades'] = 'Se kursuskarakterer'; // ORPHANED
$string['course:viewhiddenactivities'] = 'Se skjulte aktiviteter'; // ORPHANED
$string['course:viewhiddencourses'] = 'Se skjulte kurser'; // ORPHANED
$string['course:viewhiddensections'] = 'Se skjulte sektioner'; // ORPHANED
$string['course:viewhiddenuserfields'] = 'Se skjulte brugeroplysninger'; // ORPHANED
$string['course:viewparticipants'] = 'Se deltagerlisten'; // ORPHANED
$string['course:viewscales'] = 'Se skalaer'; // ORPHANED
$string['course:visibility'] = 'Vise / skjule kurser'; // ORPHANED
$string['currentcontext'] = 'Nuværende indhold'; // ORPHANED
$string['currentrole'] = 'Nuværende rolle'; // ORPHANED
$string['defaultrole'] = 'Standardrolle'; // ORPHANED
$string['defineroles'] = 'Definer roller'; // ORPHANED
$string['deletecourseoverrides'] = 'Slet alle tilsidesættelser af roller i kurset'; // ORPHANED
$string['deletelocalroles'] = 'Slet alle rolletildelinger'; // ORPHANED
$string['deleterolesure'] = 'Er du sikker på at du vil slette rollen \"$a->name ($a->shortname)\"?</p><p>Denne rolle er på nuværende tidspunkt tildelt til $a->count brugere.'; // ORPHANED
$string['duplicaterole'] = 'Kopier rolle'; // ORPHANED
$string['duplicaterolesure'] = 'Bekræft at du vil duplikere rollen \"$a->name ($a->shortname)\".'; // ORPHANED
$string['editrole'] = 'Ret rolle'; // ORPHANED
$string['errorbadrolename'] = 'Ugyldigt rollenavn'; // ORPHANED
$string['errorbadroleshortname'] = 'Ugyldigt rollenavn'; // ORPHANED
$string['errorexistsrolename'] = 'Rollen eksisterer allerede'; // ORPHANED
$string['errorexistsroleshortname'] = 'Rollen eksisterer allerede'; // ORPHANED
$string['existingusers'] = '$a eksisterende brugere'; // ORPHANED
$string['globalroleswarning'] = 'ADVARSEL! De roller du tildeler her vil gælde på hele sitet, inklusiv forsiden og samtlige kurser.'; // ORPHANED
$string['grade:export'] = 'Eksporter karakterer'; // ORPHANED
$string['grade:import'] = 'Importer karakterer'; // ORPHANED
$string['grade:override'] = 'Overskriv karakterer'; // ORPHANED
$string['grade:viewall'] = 'Vis andre brugeres karakterer'; // ORPHANED
$string['inactiveformorethan'] = 'inaktiv i mere end $a->timeperiod'; // ORPHANED
$string['ingroup'] = 'i gruppen \"$a->group\"'; // ORPHANED
$string['inherit'] = 'Nedarver'; // ORPHANED
$string['legacy:admin'] = 'STANDARDROLLE: Administrator'; // ORPHANED
$string['legacy:coursecreator'] = 'STANDARDROLLE: Kursusudvikler'; // ORPHANED
$string['legacy:editingteacher'] = 'STANDARDROLLE: Underviser'; // ORPHANED
$string['legacy:guest'] = 'STANDARDROLLE: Gæst'; // ORPHANED
$string['legacy:student'] = 'STANDARDROLLE: Elev'; // ORPHANED
$string['legacy:teacher'] = 'STANDARDROLLE: Medunderviser'; // ORPHANED
$string['legacy:user'] = 'STANDARDROLLE: Oprettet bruger'; // ORPHANED
$string['legacytype'] = 'Standardrolle type'; // ORPHANED
$string['listallroles'] = 'Vis alle roller'; // ORPHANED
$string['localroles'] = 'Lokal tildeling af roller'; // ORPHANED
$string['manageroles'] = 'Administrer roller'; // ORPHANED
$string['metaassignerror'] = 'Kan ikke tildele rollen til brugeren \"$a\" da rettigheden \"Administrer metakurser\" mangler.'; // ORPHANED
$string['metaunassignerror'] = 'Rollen fra brugeren \"$a\" er automatisk nedarvet. Fjern i stedet rollen i delkurset.'; // ORPHANED
$string['morethan'] = 'Mere end $a'; // ORPHANED
$string['my:manageblocks'] = 'Administrer myMoodle-blokke'; // ORPHANED
$string['nocapabilitiesincontext'] = 'Ingen rettigheder tilgængelige i denne sammenhæng'; // ORPHANED
$string['notes:manage'] = 'Administrer noter'; // ORPHANED
$string['notes:view'] = 'Vis noter'; // ORPHANED
$string['notset'] = 'Ikke angivet'; // ORPHANED
$string['overridepermissions'] = 'Tilsidesæt tilladelser'; // ORPHANED
$string['overridepermissionsin'] = 'Tilsidesæt tilladelser i $a'; // ORPHANED
$string['overrideroles'] = 'Tilsidesæt roller'; // ORPHANED
$string['overriderolesin'] = 'Tilsidesæt roller i $a'; // ORPHANED
$string['overrides'] = 'Tilsidesættelser'; // ORPHANED
$string['permissions'] = 'Rettigheder'; // ORPHANED
$string['potentialusers'] = '$a potentielle brugere'; // ORPHANED
$string['prevent'] = 'Tillad ikke'; // ORPHANED
$string['prohibit'] = 'Forbyd'; // ORPHANED
$string['question:add'] = 'Tilføj nye spørgsmål'; // ORPHANED
$string['question:config'] = 'Konfigurer typer af spørgsmål'; // ORPHANED
$string['question:editall'] = 'Rediger alle spørgsmål'; // ORPHANED
$string['question:editmine'] = 'Rediger dine egne spørgsmål'; // ORPHANED
$string['question:managecategory'] = 'Administrer spørgsmålskategorier'; // ORPHANED
$string['question:moveall'] = 'Flyt alle spørgsmål'; // ORPHANED
$string['question:movemine'] = 'Flyt dine egne spørgsmål'; // ORPHANED
$string['question:useall'] = 'Benyt alle spørgsmål'; // ORPHANED
$string['question:usemine'] = 'Benyt dine egne spørgsmål'; // ORPHANED
$string['question:viewall'] = 'Vis alle spørgsmål'; // ORPHANED
$string['question:viewmine'] = 'Vis dine egne spørgsmål'; // ORPHANED
$string['resetrole'] = 'Genskab standarder'; // ORPHANED
$string['resetrolenolegacy'] = 'Ryd tilladelser'; // ORPHANED
$string['resetrolesure'] = 'Bekræft at du vil gendanne rollen \"$a->name ($a->shortname)\" til standard?<p></p>Standardtilladelserne er taget fra den valgte standardrolle ($a->legacytype).'; // ORPHANED
$string['resetrolesurenolegacy'] = 'Er du sikker på at du vil rydde alle tilladelser defineret i rollen \"$a->name ($a->shortname)\"?'; // ORPHANED
$string['risks'] = 'Risici'; // ORPHANED
$string['role:assign'] = 'Tildel roller til brugere'; // ORPHANED
$string['role:manage'] = 'Opret og administrer roller'; // ORPHANED
$string['role:override'] = 'Tilsidesæt rettigheder for andre'; // ORPHANED
$string['role:switchroles'] = 'Skift til andre roller'; // ORPHANED
$string['role:unassignself'] = 'Fjern egne roller'; // ORPHANED
$string['role:viewhiddenassigns'] = 'Vis skjult rolletildeling'; // ORPHANED
$string['roleassignments'] = 'Rolletildeling'; // ORPHANED
$string['roles'] = 'Roller'; // ORPHANED
$string['roletoassign'] = 'Roller der kan tildeles'; // ORPHANED
$string['roletooverride'] = 'Roller der kan tilsidesættes'; // ORPHANED
$string['safeoverridenotice'] = 'Bemærk: Kompetencer med højere risici er låst fordi du kun har tilladelse til at overskrive sikre kompetencer.'; // ORPHANED
$string['selectrole'] = 'Vælg en rolle'; // ORPHANED
$string['showallroles'] = 'Vis alle roller'; // ORPHANED
$string['site:accessallgroups'] = 'Tilgå alle grupper'; // ORPHANED
$string['site:approvecourse'] = 'Godkend kursusoprettelse'; // ORPHANED
$string['site:backup'] = 'Tag backup af kurser'; // ORPHANED
$string['site:config'] = 'Ændre sitekonfiguration'; // ORPHANED
$string['site:doanything'] = 'Kan alt'; // ORPHANED
$string['site:doclinks'] = 'Vis links til offsite sider'; // ORPHANED
$string['site:import'] = 'Importer andre kurser til et kursus'; // ORPHANED
$string['site:langeditlocal'] = 'Skræddersy en lokal oversættelse'; // ORPHANED
$string['site:langeditmaster'] = 'Rediger master sprogpakker'; // ORPHANED
$string['site:manageblocks'] = 'Administrer siteblokke'; // ORPHANED
$string['site:mnetloginfromremote'] = 'Login fra en anden Moodleinstallation'; // ORPHANED
$string['site:mnetlogintoremote'] = 'Roam til en anden Moodleinstallation'; // ORPHANED
$string['site:readallmessages'] = 'Læs alle beskeder på sitet'; // ORPHANED
$string['site:restore'] = 'Genopret kurser fra backup'; // ORPHANED
$string['site:sendmessage'] = 'Send en besked til en vilkårlig bruger'; // ORPHANED
$string['site:trustcontent'] = 'Stol på afleveret indhold'; // ORPHANED
$string['site:uploadusers'] = 'Upload nye brugere fra en fil'; // ORPHANED
$string['site:viewfullnames'] = 'Se altid brugeres fulde navn'; // ORPHANED
$string['site:viewparticipants'] = 'Se deltagere'; // ORPHANED
$string['site:viewreports'] = 'Vis rapporter'; // ORPHANED
$string['tag:create'] = 'Opret nye nøgleord'; // ORPHANED
$string['tag:edit'] = 'Rediger eksisterende nøgleord'; // ORPHANED
$string['tag:manage'] = 'Administrer alle nøgleord'; // ORPHANED
$string['user:changeownpassword'] = 'Administrer eget kodeord'; // ORPHANED
$string['user:create'] = 'Opret brugere'; // ORPHANED
$string['user:delete'] = 'Slet brugere'; // ORPHANED
$string['user:editownprofile'] = 'Rediger egen brugerprofil'; // ORPHANED
$string['user:editprofile'] = 'Ret brugerprofiler'; // ORPHANED
$string['user:loginas'] = 'Login som andre brugere'; // ORPHANED
$string['user:readuserblogs'] = 'Se alle weblogs'; // ORPHANED
$string['user:readuserposts'] = 'Se alle forumindlæg'; // ORPHANED
$string['user:update'] = 'Opdater brugerprofiler'; // ORPHANED
$string['user:viewdetails'] = 'Se brugerprofiler'; // ORPHANED
$string['user:viewhiddendetails'] = 'Se skjulte brugeroplysninger'; // ORPHANED
$string['user:viewuseractivitiesreport'] = 'Se brugeraktivitetsrapport'; // ORPHANED
$string['user:viewusergrades'] = 'Se karakterer'; // ORPHANED
$string['userswithrole'] = 'Alle brugere med en rolle'; // ORPHANED
$string['viewrole'] = 'Se rolledetaljer'; // ORPHANED
$string['xuserswiththerole'] = 'Brugere med rollen \"$a->role\": $a->number'; // ORPHANED

?>
