<?PHP // $Id$ 
      // dialogue.php - created with Moodle 1.7 beta + (2006101003)

$string['addmynewentries'] = 'Új bejegyzéseim hozzáadása';
$string['addmynewentry'] = 'Új bejegyzésem hozzáadása';
$string['addsubject'] = 'Téma hozzáadása';
$string['allowmultiple'] = 'Ugyanazon személlyel egynél több párbeszéd engedélyezése';
$string['allowstudentdialogues'] = 'Tanulók közötti párbeszéd engedélyezése';
$string['close'] = 'Lezárás';
$string['closed'] = 'Lezárva';
$string['closeddialogues'] = 'Lezárt párbeszédek';
$string['confirmclosure'] = 'Párbeszédet készül lezárni $a-val/-vel. A lezárt párbeszédet nem lehet újból megnyitni. Ha lezárja a párbeszédet, megtekintheti, de nem tehet hozzá semmit, és egy új párbeszédet kell elindítani, ha az adott személyhez kíván szólni..<br /><br />Biztosan le akarja zárni ezt a párbeszédet?';
$string['deleteafter'] = 'Lezárt párbeszédek törlése ... (nap) elteltével';
$string['dialogueclosed'] = 'Párbeszéd lezárva';
$string['dialogueintro'] = 'Párbeszéd bevezetése';
$string['dialoguemail'] = '$a->userfrom új szöveget küldött az Ön \'$a->dialogue\' témájú párbeszédéhez. Ezt megtekintheti az alábbi párbeszédjéhez kapcsolva: $a->url';
$string['dialoguemailhtml'] = '$a->userfrom új szöveget küldött az Ön <i>$a->dialogue</i> párbeszédéhez. <br /><br /> Megtekintheti <a href=\"$a->url\">párbeszédjéhez</a> csatolva.';
$string['dialoguename'] = 'Párbeszéd neve';
$string['dialogueopened'] = 'Párbeszéd megnyitva a következő személlyel: $a';
$string['dialoguewith'] = 'Párbeszéd a következő személlyel: $a';
$string['everybody'] = 'Mindenki';
$string['furtherinformation'] = 'További információk';
$string['lastentry'] = 'Utolsó szöveg';
$string['maildefault'] = 'Levelezési alapbeállítás';
$string['mailnotification'] = 'Értesítés levél érkezéséről';
$string['modulename'] = 'Párbeszéd';
$string['modulenameplural'] = 'Párbeszédek';
$string['namehascloseddialogue'] = '$a lezárta a párbeszédet';
$string['newdialogueentries'] = 'Új párbeszédszövegek';
$string['newentry'] = 'Új szöveg';
$string['noavailablepeople'] = 'Nincs kivel párbeszédet folytatni.';
$string['nopersonchosen'] = 'Nem választott ki személyt';
$string['nosubject'] = 'Nincs megadva téma';
$string['notavailable'] = 'Vendégek nem folytathatnak párbeszédet';
$string['notextentered'] = 'Nincs megadva szöveg';
$string['notstarted'] = 'Még nem kezdte el ezt a párbeszédet';
$string['notyetseen'] = 'Még nem látták';
$string['numberofentries'] = 'Szövegek száma';
$string['numberofentriesadded'] = 'Új szövegek száma: $a';
$string['of'] = 'ból';
$string['onwrote'] = '$a-án/-én ezt írta';
$string['onyouwrote'] = '$a-án/-én Ön ezt írta';
$string['open'] = 'Megnyitás';
$string['openadialoguewith'] = 'Párbeszéd megnyitása a következővel';
$string['opendialogue'] = 'Párbeszéd megnyitása';
$string['opendialogueentries'] = 'Párbeszéd szövegeinek megnyitása';
$string['opendialogues'] = 'Párbeszédek megnyitása';
$string['pane0'] = 'Párbeszéd megnyitása';
$string['pane1'] = '$a párbeszéd vár választ Öntől';
$string['pane1one'] = '1 párbeszéd vár választ Öntől';
$string['pane2'] = '$a párbeszéd vár választ a másik személytől';
$string['pane2one'] = '1 párbeszéd vár választ a másik személytől';
$string['pane3'] = '$a lezárt párbeszéd';
$string['pane3one'] = '1 lezárt párbeszéd';
$string['seen'] = 'Megtekintve $a ezelőtt';
$string['sendmailmessages'] = 'Üzenetek küldése új szövegeimről';
$string['status'] = 'Állapot';
$string['studenttostudent'] = 'Tanuló és tanuló között';
$string['subject'] = 'Téma';
$string['subjectadded'] = 'Téma hozzáadva';
$string['teachertostudent'] = 'Tanár és tanuló között';
$string['typefirstentry'] = 'Az első szöveget ide írja be';
$string['typefollowup'] = 'A többit ide írja';
$string['typeofdialogue'] = 'A párbeszéd típusa';
$string['typereply'] = 'A választ ide írja be';
$string['viewallentries'] = '$a párbeszédszöveg megtekintése';

?>