<?PHP // $Id$ 
      // enrol_authorize.php - created with Moodle 1.7+ (2006101009)


$string['adminacceptccs'] = 'Milyen hitelkártyafajtákat fogadnak el?';
$string['adminaccepts'] = 'Válassza ki a megengedett fizetési módokat és azok típusait';
$string['adminauthcode'] = 'Ha egy felhasználó hitelkártyáját az interneten keresztül nem lehet közvetlenül elolvasni, telefonon kérjen hitelesítési kódot az ügyfél bankjától.'; 
$string['adminauthorizeccapture'] = 'Megrendelés ellenőrzése és beállítások automatikus rögzítése';
$string['adminauthorizeemail'] = 'E-mail küldésének beállításai';
$string['adminauthorizesettings'] = 'Authorize.net beállításai';
$string['adminauthorizewide'] = 'Portálra érvényes beállítások';
$string['adminavs'] = 'Jelölje be ezt, ha bekapcsolta a címellenőrzési rendszert (AVS) authorize.net fiókjában. Itt olyan címrészleteket kell megadni, mint utca, állam, ország és irányítószám, amikor a felhasználó fizetési űrlapot tölt ki.';
$string['adminconfighttps'] = 'Gondoskodjon arról, hogy a \"<a href=\"$a->url\">loginhttps BEKAPCSOLVA</a>\" legyen ezen segédprogramhoz <br />az Adminisztráció >> Beállítások >> Változók >> Biztonság >> loginhttps pontján.';
$string['adminconfighttpsgo'] = 'A segédprogram beállításához térjen át a <a href=\"$a->url\">biztonságos oldal</a>-ra.';
$string['admincronsetup'] = 'A cron.php karbantartó kód legalább 24 órája nem futott le. <br />Az ütemezett megterhelés használatához be kell kapcsolnia a Cront.<br />Állítsa be a cront megfelelően, vagy ismét szüntesse meg az an_review bejelölését.<br />Az ütemezett megterhelés kikapcsolásakor az ügyleteket törli a rendszer, ha 30 napon belül nem ellenőrzi őket.<br />Ellenőrizze az an_review-t és az an_capture_day mezőbe írjon \'0\' -t,<br />ha 30 napon belül kézzel kíván fizetéseket elfogadni/elutasítani.';
$string['adminemailexpired'] = '<b>$a</b> nappal korábban figyelmeztető e-mail küldése a rendszergazdáknak az \'engedélyezett/folyamatban lévő megterhelési\' ügyletről, mielőtt az lejár. (0=e-mail küldésének kikapcsolása, alapbeállítás=2, max=5)<br />Ez akkor hasznos, ha bekapcsolta a kézi megterhelést (an_review=bejelölve, an_capture_day=0).';
$string['adminemailexpiredsort'] = 'Ha a tanárok e-mailben értesülnek a lejáró elbírátlatlan megrendelések számáról, melyik legyen fontos?';
$string['adminemailexpiredsortcount'] = 'Megrendelések száma';
$string['adminemailexpiredsortsum'] = 'Teljes összeg';
$string['adminemailexpiredteacher'] = 'Ha bekapcsolta a kézi leemelést (lásd fent) és a tanárok kezelhetik a fizetéseket, értesülhetnek az elbírálatlan megrendelések lejártáról is. Ezzel a kurzusoktatók e-mailt kapnak a lejáró elbírálatlan megrendelésekről.';
$string['adminemailexpsetting'] = '(0=e-mail küldésének kikapcsolása, alap=2, max.=5)<br />(Kézi leemelés beállításai e-mail küldéséhez: cron=bekapcsolva, an_review=bejelölve, an_capture_day=0, an_emailexpired=1-5)';
$string['adminhelpcapturetitle'] = 'Ütemezett rögzítés napja';
$string['adminhelpreviewtitle'] = 'Rendelés ellenőrzése';
$string['adminneworder'] = 'Tisztelt Rendszergazda! Új folyamatban lévő megrendelést kapott: Rendelésazonosító: $a->orderid Ügyletazonosító: $a->transid Felhasználó: $a->user Kurzus: $a->course Összeg: $a->amount  AUTOMATIKUS MEGTERHELÉS BEKAPCSOLVA?: $a->acstatus Ha az automatikus megterhelés be van kapcsolva, $a->captureon esetén megtörténik a hitelkártya megterhelése, és a tanulót beiratkoztatja a kurzusra. Ellenkező esetben  $a->expireon dátummal lejár, és ezt követően már nem lehet megterhelni. Lehetősége van a tanulót beiratkoztató fizetés elfogadására/elutasítására az alábbi ugrópontot követve: $a->url';
$string['adminnewordersubject'] = '$a->course: Új folyamatban lévő megrendelés ($a->orderid)';
$string['adminpendingorders'] = 'Az ütemezett megterhelést kikapcsolta.<br />Az összes $a->count AN_STATUS_AUTH státusú ügyletet törli a rendszer, ha be nem jelöli.<br />Fizetések elfogadásához/elutasításához térjen át a <a href=\'$a->url\'>Fizetések kezelése</a> oldalra.';
$string['adminreview'] = 'Rendelés ellenőrzése a hitelkártya használata előtt.';
$string['adminteachermanagepay'] = 'Tanárok kezelhetik a kurzussal kapcsolatos befizetéseket.';
$string['allpendingorders'] = 'Összes elbírálatlan megrendelés';
$string['amount'] = 'Összeg';
$string['anlogin'] = 'Authorize.net: felhasználónév';
$string['anpassword'] = 'Authorize.net: jelszó (nem szükséges)';
$string['anreferer'] = 'Adja meg itt az URL-hivatkozást, ha ezt beállítja az authorize.net fiókjában. Ezzel a weboldalkérésben egy \"Referer: URL\" fejléc továbbítódik.';
$string['antestmode'] = 'Authorize.net: ügyletek próbája (nem történik pénz levétele)';
$string['antrankey'] = 'Authorize.net: ügyletkulcs';
$string['approvedreview'] = 'Jóváhagyott ellenőrzés';
$string['authcaptured'] = 'Engedélyezve / Megterhelve';
$string['authcode'] = "Hitelesítési kód";
$string['authorize:managepayments'] = 'Fizetések kezelése';
$string['authorize:uploadcsv'] = 'CSV-állomány feltöltése';
$string['authorizedpendingcapture'] = 'Engedélyezett / Folyamatban lévő megterhelés';
$string['avsa'] = 'Cím (utca) egyezik, irányítószám nem';
$string['avsb'] = 'Címadatok nincsenek megadva';
$string['avse'] = 'Címellenőrzési rendszerhiba';
$string['avsg'] = 'Nem USA-beli kártyát kiállító bank';
$string['avsn'] = 'Cím (utca) és irányítószám nem egyezik';
$string['avsp'] = 'Címellenőrzési rendszer nem alkalmazható';
$string['avsr'] = 'Próbálja újra - A rendszer nem elérhető vagy időtúllépés történt';
$string['avsresult'] = 'A címellenőrzési rendszer eredménye:';
$string['avss'] = 'A szolgáltatást a kibocsátó nem támogatja';
$string['avsu'] = 'Címadatok nem elérhetők';
$string['avsw'] = 'A 9 számjegyes irányítószám egyezik, a cím (utca) nem';
$string['avsx'] = 'A cím (utca)  és a 9 számjegyes irányítószám egyezik';
$string['avsy'] = 'A cím (utca)  és az 5 számjegyes irányítószám egyezik';
$string['avsz'] = 'Az 5 számjegyes irányítószám egyezik, a cím (utca) nem';
$string['canbecredit'] = 'Nem téríthető vissza ide:  $a->upto';
$string['cancelled'] = 'Törölve';
$string['capture'] = 'Megterhelés';
$string['capturedpendingsettle'] = 'Megterhelve / Rendezés folyamatban';
$string['capturedsettled'] = 'Megterhelve / Rendezve';
$string['captureyes'] = 'A hitelkártyát megterheljük és a tanulót beiratkoztatjuk. Biztosan ezt akarja?';
$string['ccexpire'] = 'Lejárat dátuma';
$string['ccexpired'] = 'A hitelkártya lejárt';
$string['ccinvalid'] = 'Érvénytelen kártyaszám';
$string['ccno'] = 'Hitelkártyaszám';
$string['cctype'] = 'Hitelkártyatípus';
$string['ccvv'] = 'Kártyaellenőrzés';
$string['ccvvhelp'] = 'Lásd a kártya túloldalán (3 számjegy)';
$string['choosemethod'] = 'Adja meg a kurzus beiratkozási kódját, ha ismeri; ellenkező esetben fizetnie kell a kurzus elvégzéséért.';
$string['chooseone'] = 'Az alábbi két mezőt vagy az egyiket töltse ki';
$string['costdefaultdesc'] = '<strong>A kurzusbeállításoknál adjon meg -1-et</strong> ezen alapköltség használatához a kurzusköltség mezőben.';
$string['cutofftime'] = 'Ügylet megszüntetésének ideje. Mikor kerül sor az utolsó ügylet rendezésére?';
$string['delete'] = 'Törlés';
$string['description'] = 'Az Authorize.net modullal forgalmazók térítéses kurzusai hozhatók létre. Ha valamely kurzus ára nulla, a tanulóknak nem kell fizetni a belépéshez. Itt adható meg a portálra globálisan érvényes költség, valamint az egyes kurzusokhoz egyenként beállítható költség. A kurzusköltség felülírja a portálköltséget.';
$string['echeckabacode'] = 'Bank ABA-száma';
$string['echeckaccnum'] = 'Bankszámla száma';
$string['echeckacctype'] = 'Bankszámla típusa';
$string['echeckbankname'] = 'Bank neve';
$string['echeckbusinesschecking'] = 'Ügyleti ellenőrzés';
$string['echeckchecking'] = 'Ellenőrzés';
$string['echeckfirslasttname'] = 'Bankszámla tulajdonosa';
$string['echecksavings'] = 'Takarék';
$string['enrolname'] = 'Authorize.net: hitelkártyakapu';
$string['expired'] = 'Lejárt';
$string['haveauthcode'] = "Már van hitelesítési kódom";
$string['howmuch'] = 'Mennyi?';
$string['httpsrequired'] = 'Sajnos kérését jelenleg nem tudjuk feldolgozni. A portált nem lehetett megfelelő módon beállítani.<br /><br /> Ne adja meg a hitelkártyaszámát, ha a böngésző alján nem jelenik meg egy sárga lakat. Ez azt jelzi, hogy az ügyfél és a kiszolgáló között minden adat továbbítása kódoltan történik. Így a 2 számítógép közötti kapcsolat adatforgalma védve van és hitelkártyája számát nem lehet interneten keresztül levenni.';
$string['invalidaba'] = 'Érvénytelen ABA-szám';
$string['invalidaccnum'] = 'Érvénytelen számlaszám';
$string['invalidacctype'] = 'Érvénytelen számlatípus';
$string['logindesc'] = 'Ezt az opciót be kell kapcsolni. <br /><br /> A Rendszergazda / Változók / Biztonság részben ellenőrizze, be van-e kapcsolva a <a href=\"$a->url\">loginhttps</a> opció. <br /><br />Ennek bekapcsolásakor a Moodle csak a bejelentkezési és fizetési oldalakon használ biztonságos https-csatlakozást.';
$string['logininfo'] = 'Biztonsági okokból a felhasználói név, a jelszó és az ügyletkód nem jelenik meg. Ha korábban már beállította ezeket a mezőket, akkor nem kell újból kitöltenie. Ha már beállított néhány mezőt, tőlük balra zöld szöveg látható. Ha először tölti ki ezeket a mezőket, először a felhasználói nevet (*) kell megadnia, majd a megfelelő mezőben <strong>vagy</strong> az ügyletkódot (1-es), <strong>vagy</strong> a jelszót (2-es) kell megadnia. Biztonsági okokból ajánlott az ügyletkód megadása. Ha a jelenlegi jelszót törölni kívánja, jelölje be a négyzetet.';
$string['methodcc'] = 'Hitelkártya';
$string['methodecheck'] = 'eCheck (ACH)';
$string['missingaba'] = 'Nincs megadva ABA-szám';
$string['missingaddress'] = 'Nincs cím';
$string['missingbankname'] = 'Nincs megadva banknév';
$string['missingcc'] = 'Nincs kártyaszám';
$string['missingccauthcode'] = "Nincs hitelesítési kód";
$string['missingccexpire'] = 'Nincs lejárati idő';
$string['missingcctype'] = 'Nincs kártyatípus';
$string['missingcvv'] = 'Nincs ellenőrző szám';
$string['missingzip'] = 'Nincs irányítószám';
$string['mypaymentsonly'] = 'Csak a befizetéseim';
$string['nameoncard'] = 'Kártyán szereplő név';
$string['new'] = 'Új';
$string['noreturns'] = 'Nincs visszatérítés!';
$string['notsettled'] = 'Nincs rendezve';
$string['orderid'] = 'Rendelés azonosítója';
$string['paymentmanagement'] = 'Fizetés kezelése';
$string['paymentmethod'] = 'Fizetési mód';
$string['paymentpending'] = 'Ezen kurzushoz tartozó fizetésének rendezése folyamatban ezzel a rendelésazonosítóval: $a->orderid.';
$string['pendingecheckemail'] = 'Tisztelt Igazgató Úr!

Jelenleg $a->count e-csekk van folyamatban, a tanulók beiratkozásához csv formátumú állományt kell feltöltenie.

Kattintson az ugrópontra és olvassa el az oldalon megjelenő súgót:
$a->url';
$string['pendingechecksubject'] = '$a->course: folyamatban lévő e-csekkek($a->count)';
$string['pendingordersemail'] = 'Tisztelt Rendszergazda! $a->pending ügylet lejár, ha nem fogadja el a befizetést $a->days napon belül. Ez egy figyelmeztető üzenet, mert nem kapcsolta be az ütemezett megterhelést. Vagyis a befizetést kézzel kell elfogadnia vagy elutasítania. Folyamatban lévő befizetés elfogadásához/elutasításához térjen át ide: $a->url Ütemezett megterhelés bekapcsolásához nem kap további figyelmeztető e-mailt, térjen át ide: $a->enrolurl';
$string['pendingordersemailteacher'] = 'Tisztelt Tanár! $a->pending ügylet költsége $a->currency $a->sumcost kurzushoz \"$a->course\" lejár, ha nem fogadja el a fizetést $a->days napon belül. A fizetést kézi úton kell elfogadnia vagy elutasítania, mert a rendszergazda nem kapcsolta be az ütemezett leemelést. $a->url';
$string['pendingorderssubject'] = 'FIGYELEM: $a->course, $a->pending megrendelés lejár $a->days napon belül.';
$string['reason11'] = 'Dupla ügyletet továbbítottak.';
$string['reason13'] = 'Az ügyintéző bejelentkezési azonosítója érvénytelen vagy a fiókja nem aktív.';
$string['reason16'] = 'Az ügylet nem található.';
$string['reason17'] = 'Az ügyintéző nem fogadja el ezt a fajta kártyát.';
$string['reason245'] = 'Ezt az eCheck-típust nem használhatja, ha a fizetést teljesítő átjáró fizetési űrlapját használja.';
$string['reason246'] = 'Ezt az eCheck-típust nem használhatja.';
$string['reason27'] = 'Az ügylet eredménye a címellenőrzési rendszerben egyezés hiányát mutatja. A megadott cím és a kártya tulajdonosának számlázási címe nem egyezik.';
$string['reason28'] = 'Az ügyintéző nem fogadja el ezt a fajta kártyát.';
$string['reason30'] = 'A feldolgozó konfigurálása érvénytelen. Forduljon az ügyintéző szolgáltatójához.';
$string['reason39'] = 'A megadott pénznemkód érvénytelen vagy nem támogatott, az ügyintéző számára nem engedélyezett, vagy nincs hozzá megadva árfolyam.';
$string['reason43'] = 'Az ügyintéző nem megfelelően lett beállítva a feldolgozónál. Forduljon az ügyintéző szolgáltatójához.';
$string['reason44'] = 'Az ügylet elutasítva. A kártyakód szűrőjének a hibája!';
$string['reason45'] = 'Az ügylet elutasítva. A kártyakód/címellenőrzési rendszer szűrőjének a hibája!';
$string['reason47'] = 'A befizetéshez kért összeg nem lehet nagyobb az eredetileg engedélyezett összegnél.';
$string['reason5'] = 'Érvényes összeget adjon meg.';
$string['reason50'] = 'Az ügylet szerinti befizetés folyamatban van, az összeg nem téríthető vissza.';
$string['reason51'] = 'Az ügylettel kapcsolatos jóváírások összege nagyobb az eredetileg ügyleti összegnél.';
$string['reason54'] = 'Az adott ügylet nem felel meg a jóváíráshoz szükséges feltételeknek.';
$string['reason55'] = 'Az adott ügyleti jóváírások összege meghaladná az eredeti terhelési összeget.';
$string['reason56'] = 'Ez a bonyolító csak eCheck (ACH) ügyleteket fogad el; semmilyen hitelkártyaügyletet nem fogad el.';
$string['refund'] = 'Visszatérít';
$string['refunded'] = 'Visszatérítve';
$string['returns'] = 'Visszatérítések';
$string['reviewday'] = 'Automatikusan terhelje meg a hitelkártyát, ha egy tanár vagy egy rendszergazda  <b>$a</b> napon belül nem vizsgálja felül a rendelést. A CRON LEGYEN BEKAPCSOLVA.<br />(0 nap = automatikus terhelés kikapcsolása = tanár, rendszergazda kézi úton felülvizsgálja. Az ügylet törlődik, ha kikapcsolja az automatikus terhelést, vagy ha 30 napon belül felülvizsgálja.)';
$string['reviewfailed'] = 'Ellenőrzés sikertelen';
$string['reviewnotify'] = 'Fizetését ellenőrizzük. Néhány napon belül e-mail üzenetet kap a tanárától.';
$string['sendpaymentbutton'] = 'Pénz küldése';
$string['settled'] = 'Rendezve';
$string['settlementdate'] = 'Rendezés dátuma';
$string['subvoidyes'] = 'A visszatérített $a->transid ügylet törölve lesz és $a->amount összeget jóváírunk a számláján. Biztosan ezt akarja?';
$string['tested'] = 'Ellenőrizve';
$string['testmode'] = '[ELLENŐRZÉSI MÓD]';
$string['testwarning'] = 'A megterhelés/törlés/jóváírás tesztmódban üzemel, de az adatbázisba nem került rekord vagy nem lett frissítve.';
$string['transid'] = 'Ügyletazonosító';
$string['underreview'] = 'Ellenőrzés alatt';
$string['unenrolstudent'] = 'A tanulót kiiratkoztatja?';
$string['uploadcsv'] = 'CSV-állomány feltöltése';
$string['usingccmethod'] = 'Beiratkozás <a href=\"$a->url\"><strong>hitelkártyával</strong></a>';
$string['usingecheckmethod'] = 'Beiratkozás <a href=\"$a->url\"><strong>eCheck-kel</strong></a>';
$string['void'] = 'Érvénytelen';
$string['voidyes'] = 'Az ügyletet töröljük. Biztosan ezt akarja?';
$string['welcometocoursesemail'] = 'Tisztelt Tanuló! Köszönjük befizetését. Ezen kurzusokra iratkozott be: $a->courses. Szerkesztheti profilját:  $a->profileurl. Megtekintheti fizetési adatait: $a->paymenturl';
$string['youcantdo'] = 'Ezt a lépést nem teheti meg: $a->action';
$string['zipcode'] = 'Irányítószám';

?>
