<?php

$string['addfilter']='Lisa filter';
$string['anycategory']='iga rubriik';
$string['anycourse']='iga kursus';
$string['anyfield']='iga väli';
$string['anyrole']='iga roll';
$string['anyvalue']='iga väärtus';
$string['contains']='sisaldab';
$string['content']='Sisu';
$string['courserolelabelerror']='$a->label viga: kursus $a->coursename ei eksisteeri';
$string['datelabelisafter']='$a->label on enne $a->after';
$string['datelabelisbefore']='$a->label on enne $a->before';
$string['datelabelisbetween']='$a->label on $a->after ja $a->before vahel';
$string['defaultx']='Vaikimisi ($a)';
$string['disabled']='Mitte võimaldatud';
$string['doesnotcontain']='ei sisalda';
$string['endswith']='lõpeb millega';
$string['firstaccess']='Esimene pöördumine';
$string['globalrolelabel']='$a->label on $a->value';
$string['isactive']='Aktiivne?';
$string['isafter']='on peale';
$string['isanyvalue']='on mistahes väärtusega';
$string['isbefore']='on enne';
$string['isdefined']='on defineeritud';
$string['isempty']='on tühi';
$string['isequalto']='on võrdne';
$string['isnotdefined']='ei ole defineeritud';
$string['isnotequalto']='ei ole võrdne';
$string['newfilter']='Uus filter';
$string['nofiltersenabled']='Filtri plugin ei ole võimaldatud sellel saidil.';
$string['off']='Väljas';
$string['offbutavailable']='Väljas, kuid saadaval';
$string['on']='Sees';
$string['profilelabel']='$a->label: $a->profile $a->operator $a->value';
$string['profilelabelnovalue']='$a->label: $a->profile $a->operator';
$string['removeall']='Eemalda kõik filtrid';
$string['removeselected']='Eemalda valitud';
$string['selectlabel']='$a->label $a->operator $a->value';
$string['startswith']='algab millega';
$string['tablenosave']='Muudatused üleval olevas tabelis salvestatakse automaatselt.';
$string['textlabel']='$a->label $a->operator $a->value';
$string['textlabelnovalue']='$a->label $a->operator';
$string['content']='Sisu'; // ORPHANED
$string['defaultx']='Vaikimisi ($a)'; // ORPHANED
$string['disabled']='Mitte võimaldatud'; // ORPHANED
$string['isactive']='Aktiivne?'; // ORPHANED
$string['nofiltersenabled']='Filtri plugin ei ole võimaldatud sellel saidil.'; // ORPHANED
$string['off']='Väljas'; // ORPHANED
$string['offbutavailable']='Väljas, kuid saadaval'; // ORPHANED
$string['on']='Sees'; // ORPHANED

?>